### ISSUE TITLE
[13.0] Inventory adjustment without 'Multi location' configrution on give me warning.

### ISSUE THREAD

**Issue by vikichavada** [odoo/odoo#51277]
Impacted versions:

Reproduced on 13.0 on runbot.

Steps to reproduce:
1. Configuration without "Storage Locations" on.
2. Product without stock. (new product)
3. Try to create inventory adjustment of that product.
4. Select that product on the inventory adjustment record and start inventory.
5. then try to create inventory line on the redirect screen and try to save.

Current behavior:
Giving warining for location_id field required and not given by user. 

Expected behavior:
But it should set default location to the current wareshouse's stock location.

Video/Screenshot link (optional):
![screenshot-2648571-13-0-d7e7eb runbot25 odoo com-2020 05 14-20_34_20](https://user-images.githubusercontent.com/16360459/81951778-34ad0f00-9623-11ea-8399-b6bfde4ffa3d.png)

**Comment by sswapnesh** [comment]
Could not Reproduce on Runbot (Maybe due to some demo data)

**Comment by vikichavada** [comment]
Yes now it seems working with any case. But yes demo data don't set the location_ids on inventory that the only way it can occur. btw i am closing this issue. thank you.
