### ISSUE TITLE
[13] payment: link to "Back to My Account" is not working

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#51287]
Impacted versions: 13.0

Steps to reproduce:
![screenshot-2651086-13-0-dd40fb runbot42 odoo com-2020 05 14-22_27_11](https://user-images.githubusercontent.com/16624719/81963231-72fdfa80-9632-11ea-841a-24c8dbe2c191.png)
![screenshot-2651086-13-0-dd40fb runbot42 odoo com-2020 05 14-22_30_12](https://user-images.githubusercontent.com/16624719/81963293-84df9d80-9632-11ea-9beb-51ebbd5ffb9c.png)

Process Payment

Current behavior: 
![screenshot-2651086-13-0-dd40fb runbot42 odoo com-2020 05 14-22_30_47](https://user-images.githubusercontent.com/16624719/81963356-9a54c780-9632-11ea-9ced-20c7c1a33abb.png)

Expected behavior: It should Redirect to `My account`

Video/Screenshot link (optional):

**Comment by bso-odoo** [comment]
Cause identified: the "Processed by Wire Transfer" div is on top of the "Back to My Account" and prevents it from being clicked.

**Comment by sswapnesh** [comment]
Seems to be fixed with https://github.com/odoo/odoo/pull/61589
Thanks  @bso-odoo
