### ISSUE TITLE
403 errors on Odoo Help Forum

### ISSUE THREAD

**Issue by ctringham** [odoo/odoo#51296]
There's a new user on the Odoo Help Forum complaining about getting 403 errors when editing his question:  https://www.odoo.com/forum/help-1/question/editing-a-question-and-saving-on-this-forum-fails-170467

As per comment from @ray-odoo he was able to reproduce this.  As the Help Forum is very public, maybe you can try to fix it?

I also get 403 errors sometimes when trying to convert answers to comments.  As I have 10,000+ xp / karma I suppose I should be able to do that, but maybe there's some restriction.

**Comment by Yenthe666** [comment]
@JKE-be

**Comment by JKE-be** [comment]
Most of the time it happens when you post link or image when you don’t have enough karma .

For your case of convert comment to answer ping me when you have a real exemple reproductible :) I will check the exception ...

**Comment by ray-odoo** [comment]
Today I was able to get a 403:

when including a URL (pasted, as hyperlink - not text -it works if I use text url's) with a user who has 3 Karma.

when including an image (pasted) with a user who has 3 Karma.

**Comment by ctringham** [comment]
Here's an example:

https://www.odoo.com/forum/help-1/post/re-filter-on-current-week-170224/convert_to_comment
![403](https://user-images.githubusercontent.com/38899643/82108626-4e08a500-9762-11ea-9a1d-af3ad9ed0a94.png)

I know nothing about web development, but is it possible to "trap" these errors and give some explanation?

**Comment by ctringham** [comment]
Same error with a different question:

https://www.odoo.com/forum/help-1/post/re-website-customer-account-free-sign-up-default-access-right-170685/convert_to_comment
![403 error](https://user-images.githubusercontent.com/38899643/82309454-be7b2480-99f5-11ea-8469-e1b7b9a3686c.JPG)

**Comment by jhk-odoo** [comment]
Hello,
there is an open ticket for a related issue (opw-2262832) and we are currently working on it.
I'll post here as soon as we have a fix.
