### ISSUE TITLE
Odoo 13 new install Connection to the database failed

### ISSUE THREAD

**Issue by raphaelpessanha** [odoo/odoo#51295]
Impacted versions:13

Steps to reproduce: Install Odoo 13 on Ubuntu 18.04 using this guide: https://linuxize.com/post/how-to-install-odoo-13-on-ubuntu-18-04/

I tried this https://www.odoo.com/documentation/13.0/setup/deploy.html, but still the same.

Current behavior: 

Expected behavior:

Video/Screenshot link (optional):

-- Logs begin at Wed 2020-05-13 19:24:38 UTC, end at Thu 2020-05-14 22:01:48 UTC. --
May 14 09:06:09 ip-172-31-8-60 systemd[1]: Started Odoo13.
May 14 09:06:10 ip-172-31-8-60 odoo13[11880]: /opt/odoo13/odoo-venv/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg
May 14 09:06:10 ip-172-31-8-60 odoo13[11880]:   """)
May 14 09:06:10 ip-172-31-8-60 odoo13[11880]: 2020-05-14 09:06:10,501 11880 INFO ? odoo: Odoo version 13.0
May 14 09:06:10 ip-172-31-8-60 odoo13[11880]: 2020-05-14 09:06:10,533 11880 INFO ? odoo: Using configuration file at /etc/odoo13.conf
May 14 09:06:10 ip-172-31-8-60 odoo13[11880]: 2020-05-14 09:06:10,535 11880 INFO ? odoo: addons paths: ['/opt/odoo13/odoo/odoo/addons', '/opt/odoo
May 14 09:06:10 ip-172-31-8-60 odoo13[11880]: 2020-05-14 09:06:10,535 11880 INFO ? odoo: database: odoo13@default:default
May 14 09:06:10 ip-172-31-8-60 odoo13[11880]: 2020-05-14 09:06:10,966 11880 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmlt
May 14 09:06:11 ip-172-31-8-60 odoo13[11880]: 2020-05-14 09:06:11,322 11880 INFO ? odoo.service.server: HTTP service (werkzeug) running on ip-172-
May 14 09:11:07 ip-172-31-8-60 odoo13[11880]: 2020-05-14 09:11:07,631 11880 INFO ? odoo.http: HTTP Configuring static files
May 14 09:11:07 ip-172-31-8-60 odoo13[11880]: 2020-05-14 09:11:07,660 11880 INFO ? odoo.sql_db: Connection to the database failed
May 14 09:11:07 ip-172-31-8-60 odoo13[11880]: 2020-05-14 09:11:07,662 11880 INFO ? werkzeug: 70.31.166.169 - - [14/May/2020 09:11:07] "GET / HTTP/
May 14 09:11:07 ip-172-31-8-60 odoo13[11880]: 2020-05-14 09:11:07,673 11880 ERROR ? werkzeug: Error on request:
May 14 09:11:07 ip-172-31-8-60 odoo13[11880]: Traceback (most recent call last):
May 14 09:11:07 ip-172-31-8-60 odoo13[11880]:   File "/opt/odoo13/odoo-venv/lib/python3.6/site-packages/werkzeug/serving.py", line 270, in run_wsg
May 14 09:11:07 ip-172-31-8-60 odoo13[11880]:     execute(self.server.app)
May 14 09:11:07 ip-172-31-8-60 odoo13[11880]:   File "/opt/odoo13/odoo-venv/lib/python3.6/site-packages/werkzeug/serving.py", line 258, in execute
May 14 09:11:07 ip-172-31-8-60 odoo13[11880]:     application_iter = app(environ, start_response)
May 14 09:11:07 ip-172-31-8-60 odoo13[11880]:   File "/opt/odoo13/odoo/odoo/service/server.py", line 439, in app
May 14 09:11:07 ip-172-31-8-60 odoo13[11880]:     return self.app(e, s)
May 14 09:11:07 ip-172-31-8-60 odoo13[11880]:   File "/opt/odoo13/odoo/odoo/service/wsgi_server.py", line 142, in application
May 14 09:11:07 ip-172-31-8-60 odoo13[11880]:     return application_unproxied(environ, start_response)
May 14 09:11:07 ip-172-31-8-60 odoo13[11880]:   File "/opt/odoo13/odoo/odoo/service/wsgi_server.py", line 117, in application_unproxied
May 14 09:11:07 ip-172-31-8-60 odoo13[11880]:     result = odoo.http.root(environ, start_response)
May 14 09:11:07 ip-172-31-8-60 odoo13[11880]:   File "/opt/odoo13/odoo/odoo/http.py", line 1287, in __call__
May 14 09:11:07 ip-172-31-8-60 odoo13[11880]:     return self.dispatch(environ, start_response)
May 14 09:11:07 ip-172-31-8-60 odoo13[11880]:   File "/opt/odoo13/odoo/odoo/http.py", line 1257, in __call__
May 14 09:11:07 ip-172-31-8-60 odoo13[11880]:     return self.app(environ, start_wrapped)
May 14 09:11:07 ip-172-31-8-60 odoo13[11880]:   File "/opt/odoo13/odoo-venv/lib/python3.6/site-packages/werkzeug/wsgi.py", line 766, in __call__
May 14 09:11:07 ip-172-31-8-60 odoo13[11880]:     return self.app(environ, start_response)
May 14 09:11:07 ip-172-31-8-60 odoo13[11880]:   File "/opt/odoo13/odoo/odoo/http.py", line 1421, in dispatch
May 14 09:11:07 ip-172-31-8-60 odoo13[11880]:     self.setup_db(httprequest)
May 14 09:11:07 ip-172-31-8-60 odoo13[11880]:   File "/opt/odoo13/odoo/odoo/http.py", line 1344, in setup_db
May 14 09:11:07 ip-172-31-8-60 odoo13[11880]:     httprequest.session.db = db_monodb(httprequest)
May 14 09:11:07 ip-172-31-8-60 odoo13[11880]:   File "/opt/odoo13/odoo/odoo/http.py", line 1506, in db_monodb
May 14 09:11:07 ip-172-31-8-60 odoo13[11880]:     dbs = db_list(True, httprequest)

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/13.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).
