### ISSUE TITLE
[8.0] Invoice taxes not printed in partner language

### ISSUE THREAD

**Issue by sbidoul** [odoo/odoo#5132]
Hi,

When printing an invoice, the taxes summary below the invoice lines is not translated in the partner language.

### How to reproduce 

* on runbot 8.0
* install French language
* make sure user language is English
* open tax VAT-OUT-21-L and translate the tax name VAT 21% > TVA 21%
* set the language for Agrolait to French
* create an invoice for Agrolait and add a line with tax VAT-OUT-21-L
* click update taxes
* print the invoice
* on the invoice lines, TVA 21% is printed: translated, OK
* in the taxes summary, VAT-OUT-21-L - VAT 21% is printed: *not translated, NOK*

Expected behaviour: the Tax Description in the Other Info tab should be translated in the partner language.

### Code analysis

In ```account_invoice.py```, at ```button_reset_taxes()```, the updated context with partner language is not propagated to ```account_invoice_tax.compute()```.

If I change the code to write ```account_invoice_tax.with_context(ctx).compute(invoice).values()``` it does not work either. A debugging session showed that at some point a record is fetched from the cache with the user language in the context instead of the partner language.

**Comment by guewen** [comment]
I confirm this issue.

**Comment by sbidoul** [comment]
@dmichiels I just tested with the latest 8.0 and the issue is still present.

**Comment by dmichiels** [comment]
@sbidoul 
Have you done the same steps as you explained in the first post? 
Because I just test on the runbot 8.0, and on the printed customer invoice, the two fields are well translated.

Regards,

**Comment by sbidoul** [comment]
@dmichiels I just tried on runbot 8.0.

Have a look at this invoice:

http://53157-8-0-a20545.runbot6.odoo.com/web#id=125&view_type=form&model=account.invoice&menu_id=462&action=521

![image](https://cloud.githubusercontent.com/assets/692075/6599697/83989d32-c80b-11e4-840e-d0da6ad33cc3.png)

is not translated.

Same in the PDF: on the invoice line, you see TVA 21%, and on the tax summary, you see VAT 21%.

Customer has french language.
User has English language.

**Comment by dmichiels** [comment]
@sbidoul 
The problem is that the "tax resume" is computed only when you click on the 'update' button for the total. If you duplicate the invoice and validate it, it works.
So it will be ok for all the future invoices, but not for the already validated one.

**Comment by sbidoul** [comment]
@dmichiels Ah, that is really weird. When you click update it works correctly as you say. But if you delete the line in the tax summary and click validate instead of (update), it does not translate.
