### ISSUE TITLE
[11.0] Rollback Issue While Creating Records via Python Code

### ISSUE THREAD

**Issue by Gokulakannanaj** [odoo/odoo#51331]
Impacted versions:
11.0

Steps to reproduce:
Create records via Python Code like below

try:
    self.env['model_name'].create({'name': "Name"})
except Exception:
     pass

Current behavior:
          Record Creation has done if even getting the exception

Expected behavior:
          Need to rollback the records if it throws an error

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

Little tip (without trying):
```python
try:
    with self.env.cr.savepoint():
        self.env['model_name'].create({'name': "Name"})
except Exception:
    pass
```

**Comment by Gokulakannanaj** [comment]
@pedrobaeza Thanks for your update
