### ISSUE TITLE
[WISHLIST] Merge procurement_jit and sale_stock

### ISSUE THREAD

**Issue by kos94ok-3D** [odoo/odoo#51353]
procurement_jit does not need now as a separate module.
We can move code to sale_stock and use system_parameter or company property in a res.config.setting instead of a simple boolean field.
What do you think about it? @sle-odoo

**Comment by sle-odoo** [comment]
Hello,

Indeed the module doesn't technically need to exist.
I wouldn't encourage you to work on a pull request though, we plan to add more reservation strategies than just direct/scheduler.

Is this an issue for you?

Regards

**Comment by kos94ok-3D** [comment]
I created this issue because of thought that you missing it and If you agree with me it can be done in Odoo14.
If you disagree, it is no problem and I can close an issue.
But I think if we keep it through one or two release Odoo, it`s OK. But if more it`s not good.

**Comment by kos94ok-3D** [comment]
Will be done in https://github.com/odoo/odoo/pull/60300

**Comment by Yenthe666** [comment]
Let's close this one off in favor of the PR?
