### ISSUE TITLE
We cannot use float for quantity in website_sale lines

### ISSUE THREAD

**Issue by jzahid** [odoo/odoo#51357]
Impacted versions:
13 community
Steps to reproduce:
1- add some product to cart ( in our case our costumer sells vegetebales online)
2- try to change the quantity to float. Ex 2.5 Kilo.
Current behavior:
-  Odoo is rounding the quantity.
Expected behavior:
- keep what the customer entered on cart line .
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
That's something expected, as e-commerce is only planned for integer quantities for now, so it can be interested as a new feature, but not something to fix, but to add.

@JKE-be is there any plan about this feature?

**Comment by JKE-be** [comment]
Thanks for feedback

Not in the current wishlist.
//cc @sbuhl 

It was a choice to avoid 1.0 in most view that was considered as ugly in ecommerce

Until now, we suggest to sold 15 x 100g instead of 1.5 kg or 3x500g as an hack

**Comment by jzahid** [comment]
@JKE-be . Situations in which we need small or decimal quantities are very common and are no exception.
Our customer, sells fruits and vegetables online. For him not having the opportunity to sell 1.5 kg or 2.3 is incomprehensible, he seriously considers using other cms for the front end (prestashop).
I believe this restriction will  put off many other users. For our part we will try some workarounds,  while waiting for that to be corrected in the sources.

**Comment by dalonsod** [comment]
Hello @jzahid ,
I'm facing the same problem, also working with fruits and vegetables online, did you finally solve? I'm considering buying an addon (such as https://apps.odoo.com/apps/modules/13.0/website_sale_decimal/), maybe you solved on the same way. Thanks in advance!

**Comment by jzahid** [comment]
Hello @dalonsod. Actually that addon is mine. i work it out with some minor modifications in javascript side. You can buy it if you're interested. Or you can do it your self by changing line 167 in website_sale. js 

from var check_value = parseInt($input.val() || 0, 10); 
to var check_value = parseFloat($input.val());

and line 433

from  var value = parseInt($input.val() || 0, 10);
to  var value = parseFloat($input.val());

**Comment by dalonsod** [comment]
Thanks for the responde @jzahid I've made the purchase :-)

**Comment by jamematen** [comment]
Here's the translation:

"Hi @jzahid, are you planning to update this plugin for version 15 of Odoo? I'm interested in purchasing it."

**Comment by jzahid** [comment]
@jamematen it's done.

**Comment by jamematen** [comment]
Hello @jzahid. Thank you very much for such a quick response.
 I have already purchased it. I wanted to mention that it works well except in the cart, where if you try to modify the quantity, it rounds off the decimals. 
Best regards.
