### ISSUE TITLE
arch_updated flag of ir.ui.view is set erroneously when updating theme

### ISSUE THREAD

**Issue by SplashS** [odoo/odoo#51358]
Impacted versions: Odoo Community 13.0 (from latest docker odoo:13.0)

Steps to reproduce:
1. Install some theme.
2. Change content of any `<template>` in theme.
3. Update theme.
4. Change content of the same `<template>` again.
5. Update theme again (it really happens only from second update).

Current behavior:
`<template>` won't be updated in database.

Expected behavior:
`<template>` will be updated in database.

Explanation (after some research):
When theme is being updated odoo is calling `website_theme_install` -> `ir.module.module` -> `_update_records`:
```python
if model_name == 'ir.ui.view' and (find.arch_updated or find.arch == rec_data['arch']):
    rec_data.pop('arch')
find.update(rec_data)
```
So in fifth reproduction step `website_theme_install` thinks that user was modified `<template>` manually, but flag `arch_updated` was set by the same method (`_update_records`) because of this code in `base` -> `ir.ui.view` -> `write`:
```python
# Keep track if view was modified. That will be useful for the --dev mode
# to prefer modified arch over file arch.
if ('arch' in vals or 'arch_base' in vals) and 'install_filename' not in self._context:
    vals['arch_updated'] = True
```
It happens because `write` is called from `_update_records` without `install_filename` in context.

**Comment by pedrobaeza** [comment]
Thanks for the analysis. @JKE-be are you involved in this code or it was @xmo-odoo ?

**Comment by JKE-be** [comment]
Seems linked to https://github.com/odoo/odoo/pull/49442/files

@fja-odoo is working in it

Thank

**Comment by JKE-be** [comment]
Thanks

We are merging https://github.com/odoo/odoo/pull/51431/commits that should fix it
