### ISSUE TITLE
[12]  Email marketing blocks - it doesn't send to all recipients

### ISSUE THREAD

**Issue by zozolpl** [odoo/odoo#51361]
Impacted versions: 12 

Steps to reproduce: Send a campaing to at least 1k recipients

Current behavior: Stuck It blocks at around 30% sent - the status changes to "sent" and activates the try again button

Expected behavior: Should send to all recipients

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/23475876/82125498-9ba70100-97a6-11ea-92d6-ab8e50f918e5.png)

The first suspicion was an outdated database that contains a lot of inactive recipients.
51k recipients, and the campaign blocked with about 15k sent.
That's why I created a new database (1100 addresses - all mine in gmail - 100% working)
I did the test, out of 1100 recipients, sent 300 and the campaign blocked in the same way.
To rule out a configuration problem, I installed a completely new system on a separate machine, imported the same database of 1,100 recipients onto gmail, and performed the test - exactly the same behavior with 300 sent blocked.

----------
I forgot about it, I once noticed such an error when the campaign blocked
https://imgur.com/cFeixBO

**Comment by zozolpl** [comment]
I forgot about it, I once noticed such an error when the campaign blocked
https://imgur.com/cFeixBO

**Comment by pedrobaeza** [comment]
This seems a problem of your specific deployment. Specifically, I would say that is your mail provider that doesn't allow too many mails sent in the same period. Gmail for example have a limit per hour.

Any way, as said it seems to not be something of Odoo itself, so closing this issue. If you check this and give more evidences about a real problem in Odoo, please write back.

**Comment by zozolpl** [comment]
I received information from the hosting administration that emails were blocked due to too many connections (> 10) of one program (odoo). In view of the above, is it normal for odoo to make so many connections at the same time? Is it possible to change the number of connections in the odoo backend?

LOG:
2020-05-15 10:23:23 1jZVco-001gAe-Cg no immediate delivery: more than 10 messages received in one connection

2020-05-15 10:24:30 1jZVco-001gAe-Cg frozen by root

**Comment by pedrobaeza** [comment]
No, that's not possible to be controlled I'm afraid.
