### ISSUE TITLE
cache load_views output

### ISSUE THREAD

**Issue by alfadil** [odoo/odoo#51362]
Impacted versions:
11.0, 12.0,13.0
Steps to reproduce:
open any menu
Current behavior:
take too long to load views

this specific call from the frontend take too long (up to minutes sometimes) so I'm thinking why we can't cache it, I mean it's not depend on data and only changing on technical specs would change it,But there are some issues to do this like security on some fields and localization but I think we can overcome those issues and add some caching layers.
so community I want your opinion on this.

**Comment by pedrobaeza** [comment]
Views are already cached (but I don't know exactly the involved methods), and it's weird that in your deployment the specific call to that method takes minutes, so for sure it seems there's something wrong on your side, but this is not an Odoo issue per se.

You can share on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups) more details about your specific questions.

Closing this by the reason above.
