### ISSUE TITLE
[WISH] Add a horizontal scroll bar in the search panel.

### ISSUE THREAD

**Issue by tanghulu0608** [odoo/odoo#51374]
Impacted versions:
13.0 

Steps to reproduce:
Add a new department with a long name.
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/5561864/82181689-961bf900-9915-11ea-80b2-bdf2ce7610fe.png">
the department name can not be fully shown  the employee kanban view.
<img width="753" alt="image" src="https://user-images.githubusercontent.com/5561864/82181626-797fc100-9915-11ea-8cdf-4385b1aee6ab.png">

Expected behavior:
Add a horizontal scroll bar in the search panel.

**Comment by pedrobaeza** [comment]
Duplicated of #49183
