### ISSUE TITLE
ParseError: "insert or update on table "website" violates foreign key constraint "website_user_id_fkey" DETAIL:  Key (user_id)=(3) is not present in table "res_users". while installing website builder module

### ISSUE THREAD

**Issue by IcemanFromMM** [odoo/odoo#51371]
Impacted versions: 8.0

Steps to reproduce:

Current behavior:   ParseError: "insert or update on table "website" violates foreign key constraint "website_user_id_fkey"
DETAIL:  Key (user_id)=(3) is not present in table "res_users".

Expected behavior:  website builder app installed 

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Hi, version 8.0 is out of official support, so I'm closing this issue due to this. If you find the problem in upper versions, please write back to reopen.

**Comment by IcemanFromMM** [comment]
hi @pedrobaeza  thank you for your comment, is there any way to solve this problem? and where can i find odoo 8 related problems?? because my stupid boss is still using odoo  8. I'm sorry.

**Comment by pedrobaeza** [comment]
Try on Odoo forums or hire specialized support.

**Comment by IcemanFromMM** [comment]
@pedrobaeza  thank you
