### ISSUE TITLE
[NEW API] Multiple inverse functions only fill first field

### ISSUE THREAD

**Issue by mileo** [odoo/odoo#5137]
Hi, 

I'm migrating l10n_br to v8 new API, in the class above we have 4 fields that use one inverse function: _set_l10n_br_data" but only suframa (the first field in values dict) field is writed. If i have one inverse function for each field works normaly.

The correct now is to use fields with related?

Regards
```
class ResCompany(models.Model):

    _inherit = 'res.company'

    @api.one
    def _get_l10n_br_data(self):
        """ Read the l10n_br specific functional fields. """
        self.legal_name = self.partner_id.legal_name
        self.cnpj_cpf = self.partner_id.cnpj_cpf
        self.inscr_est = self.partner_id.inscr_est
        self.inscr_mun = self.partner_id.inscr_mun
        self.suframa = self.partner_id.suframa

    @api.one
    def _set_l10n_br_data(self):
        """ Write the l10n_br specific functional fields. """
        values = {
            'suframa': self.suframa,
            'legal_name': self.legal_name,
            'cnpj_cpf': self.cnpj_cpf,
            'inscr_est': self.inscr_est,
            'inscr_mun': self.inscr_mun,
            }
        self.partner_id.write(values)

    cnpj_cpf = fields.Char(
        compute=_get_l10n_br_data, inverse=_set_l10n_br_data, size=18,
        string='CNPJ/CPF')

    inscr_est = fields.Char(
        compute=_get_l10n_br_data, inverse=_set_l10n_br_data, size=16,
        string='Inscr. Estadual')

    inscr_mun = fields.Char(
        compute=_get_l10n_br_data, inverse=_set_l10n_br_data, size=18,
        string='Inscr. Municipal')

    suframa = fields.Char(
        compute=_get_l10n_br_data, inverse=_set_l10n_br_data, size=18,
        string='Suframa')

    legal_name = fields.Char(
        compute=_get_l10n_br_data, inverse=_set_l10n_br_data, size=128,
        string=u'Razão Social')
```

**Comment by rm-jamotion** [comment]
Same problem here. 

I have implemented many computed fields which are representing values of a configuration file. When one or multiple field values are changed, it should write the data back into the config file with a multiple used inverse='_write_config_data' function. But when I request the first value (e.g. value = record.max_conn) all other computed values are reset to the before readed values.

Have you found any solution for this?

**Comment by cysnake4713** [comment]
anyone fix this yet?

**Comment by rruebner** [comment]
Maybe you already figured it out but I think it is not a bug. For example if you check https://github.com/odoo/odoo/blob/master/openerp/addons/base/res/res_company.py you see that odoo uses one compute function for all address fields and separate inverse functions for each address field.

**Comment by mileo** [comment]
We follow the same approach in location l10n_br: https://github.com/OCA/l10n-brazil/blob/8.0/l10n_br_base/models/res_company.py#L36

For me the issue can be closed.

**Comment by shepilov-vladislav** [comment]
Any news about this issue? Solutions from https://github.com/odoo/odoo/blob/master/openerp/addons/base/res/res_company.py and https://github.com/OCA/l10n-brazil/blob/8.0/l10n_br_base/models/res_company.py#L36 didn't helps.
