### ISSUE TITLE
Odoo 13 master doesn't have option to import/upload Chart of Accounts

### ISSUE THREAD

**Issue by E4O** [odoo/odoo#51388]
Impacted versions:
Odoo 13 enterprise
Branch: master

Steps to reproduce:
1. Go to Accounting - Configurations - Chart Of Accounts

Current behavior:
No import or upload button available:
![image](https://user-images.githubusercontent.com/40301417/82190543-d2416080-98f9-11ea-9c18-81eaa6e5ce19.png)
![image](https://user-images.githubusercontent.com/40301417/82190570-e2594000-98f9-11ea-9dcf-87904f4baf23.png)

Expected behavior:
I should be able to upload the chart of accounts through my Excel file.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
@qdp-odoo I think this is on purpose, isn't it?

**Comment by E4O** [comment]
I found a solution. Odoo has moved import feature under "Favourites".
![image](https://user-images.githubusercontent.com/40301417/82223803-d0909080-992b-11ea-8fbd-66b6e2b30e78.png)
