### ISSUE TITLE
[8.0] account: wrong amount in invoice taxes compute with price_unit=0

### ISSUE THREAD

**Issue by moylop260** [odoo/odoo#5140]
We need use a special tax with a final result
- invoice.subtotal = 0
- invoice.amount_tax = `price_unit * 0.16`
- (optional) tax_base_amount = `price_unit`

Then I try with a python_code tax with next configuration:
tax.type: python_code
py_code: `result = price_unit * 0.16`
![supplier invoices - odoo - broker tax - pycode price_unit](https://cloud.githubusercontent.com/assets/6644187/6094193/2e0e9e8c-aee5-11e4-9f6f-8136596c7ba5.png)
But invoice_tax.amount is equal = 0

Then I try with a python_code tax with next configuration:
tax.type: python_code
py_code: `result = quantity * 0.16`
![supplier invoices - odoo - broker tax - pycode qty](https://cloud.githubusercontent.com/assets/6644187/6094192/2b401fbe-aee5-11e4-9f21-4ef2db36c035.png)
And this one work fine, but I have to use quantity field.

A similar case is with fixed amount configuration:
fixed amount=100
invoice_line.quantity = 0
invoice_line.price unit = 1
![supplier invoices - odoo - broker tax - fixed amount price_unit1](https://cloud.githubusercontent.com/assets/6644187/6094191/2a18f2a0-aee5-11e4-915e-095cf2a8b7ed.png)
invoice_tax.amount=0

fixed amount=100
invoice_line.quantity = 1
invoice_line.price unit = 0
![supplier invoices - odoo - broker tax - fixed amount quantity1](https://cloud.githubusercontent.com/assets/6644187/6094189/13cc8b4c-aee5-11e4-9c0e-32aea477b468.png)
invoice_tax.amount=100

Why I can't use `price unit` field for this cases?
IMHO `fixed amount` or `python code` should work regardless of `quantity` or `unit price`

**Comment by odony** [comment]
The `price_unit` used to compute a tax is actually `(discounted) unit price * quantity`, because that is the amount on which the tax has to be computed. So whenever you set the quantity of the line to 0, you'll get 0 as the tax amount, regardless of the price you put on the line.

Collecting a tax on a product line with qty = 0 is very weird, so the behavior of the system seems logical to me. I don't know your real business case but in all your different examples the most logical one seems to be "fixed amount tax"  on a line with "qty = 1 and price = 0".

**Comment by moylop260** [comment]
@odony 
Thanks for reply.

I understand you.
I would explain you, my business case

My real business case is: importation.
I have a foreign supplier (e.g. China export) that create a invoice without taxes.
```python
invoice.number = 01
invoice.partner = China Export
invoice.subtotal = 100
invoice.tax = 0
invoice.total = 100
invoice_tax_line.tax_base = 0
```
Later, I have a local supplier as [broker] (http://en.wikipedia.org/wiki/Broker) this one create a new invoice with just taxes.
```python
invoice.number = 02
invoice.partner=Local supplier broker
invoice.subtotal = 0
invoice.tax = 100 * 0.16
invoice.total = 100 * 0.16 
invoice_tax_line.tax_base = 100
```

I understand that need develop a custom module for
```python
invoice_tax_line.tax_base = 100
```

But I expected that second invoice was possible to create, without develop.
With a percent in python_code based on invoice.price_unit (not fixed amount tax)

How do you recommend me to solve this business case?

**Comment by moylop260** [comment]
...continue:
We need that the account.move.line was created with taxes fields filled
For example this `tax account` field.
![odoo](https://cloud.githubusercontent.com/assets/6644187/6173721/84c561b6-b2af-11e4-960a-7472bc5380a1.png)

**Comment by Yenthe666** [comment]
Hi @moylop260 ,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
