### ISSUE TITLE
The field invoice control should not be fixed after pressing "bid received" in the RQ

### ISSUE THREAD

**Issue by ybofr** [odoo/odoo#5143]
When I create a RFQ and set the status to bid received, the field invoice control gets freezed. This is wrong, as the way to do invoice control has nothing to do with the bid, but all to do with the purchase order.

It should be possible to change this field, before I confirm the PO and after I have received the bid.

Thanks for the correction.

**Comment by Yenthe666** [comment]
Hi @ybofr,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
