### ISSUE TITLE
runbot V8: the field unit of measure has disappeared from the purchase order

### ISSUE THREAD

**Issue by ybofr** [odoo/odoo#5144]
The field unit of measure has disappeared from the PO making it impossible to make purchase without a product, as the system will be requesting the unit of measure.

Thanks for the correction

**Comment by Yenthe666** [comment]
Hi @ybofr,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
