### ISSUE TITLE
[12.0] is it normal to have quants reserved and no stock in hand ?

### ISSUE THREAD

**Issue by m3asmi** [odoo/odoo#51451]
Impacted versions: 12.0
I find there is some lines in stock.quant with no stock in hand and have a reserved quantity. 
I already deleted one month ago some lines like this because I thought they may came fron the older version before the migration. and now I found new lines!

![image](https://user-images.githubusercontent.com/7910752/82216107-f7d56680-9907-11ea-9afb-49a3ad1bc8fc.png)

**Comment by pedrobaeza** [comment]
This shouldn't happen, but unless you provide steps to reproduce the problem, we can't say that this is a bug in Odoo. Maybe you have some modules that are provoking this.

**Comment by sle-odoo** [comment]
If the product is consumable, it's normal.
If the source location bypasses the reservation (scrap, inventory loss, production, supplier, etc), it's normal.

**Comment by pedrobaeza** [comment]
Unless I'm mistaken, there are no quants for consumable, isn't it? For the other case, I don't know right now, but usually there's no quant also AFAIK...

**Comment by sle-odoo** [comment]
Oops, my bad, I read the issue as "is it normal to have reserved quantities on move lines with no associated quants".
