### ISSUE TITLE
'My Cart' and 'Wishlist' not translated and not translatable

### ISSUE THREAD

**Issue by HarlekinSimplex** [odoo/odoo#51475]
**Impacted versions:**
odoo 13 CE

**Steps to reproduce:**
- odoo 13 base install with eCommerce enabled
- install german as 2nd language
- enter something into the cart or wishlist

**Current behavior:**
The Label 'My Cart' of the shopping cart in the top menu bar is not translated and could not be translated using the odoo ui .
Checking with the translated terms dialog, it looks like all the translations are there, but the terms are not resolved during html rendering of the menu bar.
Even with full database access I found no way to get this label translated properly to german.
Probably the translation record itself is deleted somehow so the translation framework could not find the translation inside the PO file.
Even using the 'Create missing terms' feature did not (re)create the proper entry in the list of translated terms.

Same behavior with the 'Wishlist' lable in case you activate that feature too.
No way to translate that label though all required translations seem to be properly present and  loaded in the database as well as with 'My Cart'.

**Expected behavior:**
All top bar labels are translated into the actually select website language and those translations could be customized using the translated terms dialog.

**Additional Information:**
During the hunt for that bug at different levels I somehow messed up the translation of the 'Sign In' label as well. At least it stopped beeing translated properly.
To recover the proper translation of that 'Sign in' term required me to look into one of my backups of that now corrupted database where the term was still intact.
Only after manually recreating the entry with its proper database ID the translation did worked again.
So again there was NO other way to get a missing translation record back into service but creating it manually in full. In case you do not know the proper ID of such a accicdently deleted term you might not be able to fix this at all without reverting to a database backup.

I would expect that 'Create missing terms' creates or recreate ANY missing translation terms, to make them available for translation (again).
Obviously that fails somwhere with the labels placed on the main menu bar in case they are not standard menu items.

**Comment by Yenthe666** [comment]
@JKE-be @mart-e one for you two :)

**Comment by HarlekinSimplex** [comment]
Finally found the missing translation.

Open `Settings-Technical-User Interface-Views`
and search view for:
`Header Shop My Cart Link`

On my installation there were two hits;
One with the external id `website_sale.header` set and one without that id.

Opening the entry without the external id and then clicking on edit translations revealed a DE and an EN record both with **no** translation (aka both are using the EN source key for rendering) in there.

After editing the german translation it was used properly in the main menu bar and could be changed in the transalated terms dialog as well.

Opening the one with the external_id set showed that there are exactly the same entries assigned with the proper transalation already set.

So I wonder...
- How come that there are 2 sets of the same internal source
- How come that the one with the internal_id is ignored in translation resolution though it holds the proper translations
- How come that the translation appeared in the translated terms dialog only after I edited it in the view translations

Hope that helps finding and fixing this translation issue in the original lanaguage package.

**Comment by pedrobaeza** [comment]
Double view is due to new multi-website system, that creates a copy of all of the views. It's called internally COW. The question if why the translations are not propagated.

@JKE-be I remember there was some WIP for this, isn't it?

**Comment by HarlekinSimplex** [comment]
Just for others maybe searching github for similar issues:

The same apporach as described for `My Cart` above can be used if the `Wishlist` or `Sign in` menu items are not translated or not translated any longer after installing / deinstalling language packages.

Just search the not translated labels in the views dialog and edit/create the missing translations threre. Afterwards they should show up translated properly (again) and can be found and edited in the translated terms dialog (again) as well.
Having found that workaround safed me from fixing these issues directly in the ir.translation table with all the dangers and headaches attached in doing so at production systems.  

Cheers
Stephan

**Comment by HarlekinSimplex** [comment]
Today morning I ran the following server command on my dev server (bitnami/odoo) just to test what happens when I update all modules:
`./odoo-server -c odoo-server.conf --dev=all --log-level=debug -u all`

After that the 'Sign in' and 'My Cart' labels are back to english again.... !
The above mentioned method to fix that did not work, because all the translation records I edited are still there - nothing to fix here. Running the generate all missing terms did not help also. No additional records surfaced at the views or translated terms dialog.

Further more, the web_login dialog is not translated at all now.
The Button shows 'Log in' and there are links named 'Reset Password', 'Log in as superuser' and 'Don*t have an account?'.
Prior running the full upgrade all those links were presented in german.
All other pages seem to be fine.

I checked the language settings of the default user templates and the settings for the standard language for the website and in the user defined standards at the technical menu - they all still show de_DE.
For me it looks like odoo is reverting now to english rather then to german for the public login.

For the menu bar its even more weired now.
I tried to edit the english translations just to test if odoo pulls them instead the german translations. Well it does not. It looks like the translation mechanism doesn't find any of those records now and thus reverts to the source keys.

So I'm back to Start with no idea how to fix that issue if it happens in production eventually.
Right now I restored everything into working order again by replaceing my dev odoo and dev db container with the backups I took prior running that upgrade.

I have two languages installed.
en and de. All users (UID=0,2,3,..) except admin (UID=1) are set to de_DE.
Website language is de_DE only.

However, from my point of view running `-u all` at the server console should not break the translation mechanism like this - right?
Any idea's what I messed up here that needs to be fixed?
If you want to have a look into the live system I can provide a link by email or pm.

**Comment by bvr-odoo** [comment]
Hello @HarlekinSimplex , sorry for the late response.
But your issue is probably due to the fact that you are using "--dev=all" in your [command line.](https://www.odoo.com/documentation/master/reference/cmdline.html) This command also enalbe "--dev=xml" and therefore the templates are read from xml file directly instead of database. I hope this information will solve all your issues
