### ISSUE TITLE
Purchase send goods from supplier to customer not worked 

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#515]
when create PO, fill the `Customer Address` field, the picking is not correctly. the right behave should create a new delivery order and set the destination as the customer address. 

but the current logic just replace the `partner_id` with customer_address and change stock move 's destination location. have not changed the picking itself.

**Comment by Yenthe666** [comment]
Dear @jeffery9 ,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
