### ISSUE TITLE
ParseError: "External ID not found in the system:

### ISSUE THREAD

**Issue by IcemanFromMM** [odoo/odoo#51501]
Impacted versions: 8.0

Steps to reproduce: -

Current behavior:    raise ValueError('External ID not found in the system: %s' % (xmlid))
  ParseError: "External ID not found in the system: 

Expected behavior:  module successfully installed

Video/Screenshot link (optional):  
![Screenshot from 2020-05-19 11-54-17](https://user-images.githubusercontent.com/17077533/82288066-ab516000-99c7-11ea-88db-411b63f8c0f5.png)
![Screenshot from 2020-05-19 11-54-08](https://user-images.githubusercontent.com/17077533/82288077-b0aeaa80-99c7-11ea-97e6-402583aaf1b2.png)

**Comment by pedrobaeza** [comment]
The same about #51501 applies here, and there's no doubt that you have your DB in an inconsistent state, probably due to bad manipulation.

Closing as stated in the other issue.

**Comment by Yenthe666** [comment]
And besides of that Odoo 8 has been end of life for nearly three years now.
