### ISSUE TITLE
[8.0] Impossible to reverse a transfer with stock move which have UOS

### ISSUE THREAD

**Issue by adrienpeiffer** [odoo/odoo#5151]
Hi,

Here, a scenario on runbot 8.0

Steps to reproduce
------------------------
- Go on runbot 8.0
- Click on sale menu
- Click on product submenu
- Select and click on 'Yellow Peppers'
- Go on Sale page
- Change Unit of Sale to units
- Change Unit of Measure -> UOS Coeff to 3.0
- Click on save
- Go on warehouse menu
- Click on all Operations in your company delivery order
- Click on create
- Fill in partner
- Add a line (stock move) with Yellow Peppers product
- Set UOM quantity to 10
- UOS Quantity should be automatically set to 30
- Click on Save and Close
- Click on Save on picking view
- Click on Mark as todo
- Click on Check Availability
- Click on Transfer
- Transfer the all picking
- Click on reverse transfer on picking view
- Change quantity to 5
- Click on Return

Expected Behavior
------------------------
- A return picking is generated

Current Behavior
----------------------
- An exception is raised
`Error!
Conversion from Product UoM kg to Default UoM Unit(s) is not possible as they both belong to different Category!.`

Thanks !

**Comment by adrienpeiffer** [comment]
OPW 627478

**Comment by adrienpeiffer** [comment]
Fix on #5152

**Comment by jco-odoo** [comment]
Merged in v8.
