### ISSUE TITLE
In multi-company environment, one company's BOM interfering with other company's operation

### ISSUE THREAD

**Issue by misnedtech** [odoo/odoo#51533]
Impacted versions:
13 (I tested in v13 enterprise)

Steps to reproduce:
Create a database with multi-company and install sales, purchase and manufacturing apps.
Let first company is C1 and second C2.
In C1 create a product P1 with type "Storable Product". Select Routes "Replenish on Order (MTO)" and "Buy" from Inventory tab.
In this condition, when a sales order is created, system should automatically generate purchase order to replenish stock. It will work as expected now.
Now switch to second company C2. Create a Kit bill of material for product P1. No need to select any routes of components. Make sure to select BoM Type "Kit".
Now go back to C1 and create a sales order for product P1 and confirm. System will not generate purchase order and there is no way to automatically reserve product in delivery order.

Current behavior:
Kit BOM in other company affecting the sales order operation.

Expected behavior:
Kit BOM in other company should not affect the sales order operation. Only same company BOM should affect the sales. 

From my investigation, I think the problem in mrp module.
odoo\addons\mrp\models\stock_rule.py
Inside function run in class ProcurementGroup.
bom_kit = self.env['mrp.bom']._bom_find(product=procurement.product_id, bom_type='phantom')
It should pass company_id in _bom_find function.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
But the BoM has the `company_id` set?

**Comment by misnedtech** [comment]
> But the BoM has the `company_id` set?

Yes, in BOM company C2 is selected.

**Comment by pedrobaeza** [comment]
@amoyaux @sle-odoo can you take a look?

**Comment by amoyaux** [comment]
https://github.com/odoo/odoo/pull/51702

**Comment by pedrobaeza** [comment]
Closing as linked PR is being merged (not sure if it's going to be auto-closed).
