### ISSUE TITLE
[12.0] Website Homepage is not translated

### ISSUE THREAD

**Issue by CarmenMiranda** [odoo/odoo#51579]
**Impacted versions:**
12.0

**Steps to reproduce:**

1. Install a new language
2. Inherit the view homepage and do any change that allows you to add a translation.
3. Add the translations for the changes

**Current behavior:**
I did a [PR Dummy #50883 ](https://github.com/odoo/odoo/pull/50883) where I add a new module to add some changes to the Homepage. And the changes that I added were not translated.
![Task 39008 - Homepage not being translated](https://user-images.githubusercontent.com/26889951/82368287-cd081280-99da-11ea-962b-c6f9cc0860c7.png)
[Runbot](https://2606355-50883-50de2d.runbot31.odoo.com/es_ES/?db=2606355-50883-50de2d-all)

Even when the translations are there.
![Task 39008 - Website translation are there](https://user-images.githubusercontent.com/26889951/82369123-26bd0c80-99dc-11ea-86fc-f8ee685bde41.png)

**Expected behavior:**
The changes should be translated.

**Comment by pedrobaeza** [comment]
You have to regenerate terms from the option in settings.

**Comment by hugho-ad** [comment]
do you mean 

Re-load translations?

![image](https://user-images.githubusercontent.com/10233975/82370320-fb3b2180-99dd-11ea-9a52-e34a39b91439.png)

**Comment by CarmenMiranda** [comment]
> do you mean
> 
> Re-load translations?
> 
> ![image](https://user-images.githubusercontent.com/10233975/82370320-fb3b2180-99dd-11ea-9a52-e34a39b91439.png)

If it is the re-load, I tried it but that didn't work.

**Comment by hugho-ad** [comment]
@pedrobaeza 

I don't see why we have to made that extra-step if we are loading explicitly the terms.

**Comment by pedrobaeza** [comment]
I mean generate missing terms

**Comment by CarmenMiranda** [comment]
> I mean generate missing terms

I did it but it also didn't work, the translations are there, but the website is not being translated.
![Task 39008 - Translations after updating terms](https://user-images.githubusercontent.com/26889951/82371546-fc6d4e00-99df-11ea-86cf-7c45660ccd48.png)

**Comment by CarmenMiranda** [comment]
**OPW #2261278**

**Comment by farinoire** [comment]
> > I mean generate missing terms
> 
> I did it but it also didn't work, the translations are there, but the website is not being translated.
> ![Task 39008 - Translations after updating terms](https://user-images.githubusercontent.com/26889951/82371546-fc6d4e00-99df-11ea-86cf-7c45660ccd48.png)

Why not trying to import again the translation file?

**Comment by CarmenMiranda** [comment]
> > > I mean generate missing terms
> > 
> > 
> > I did it but it also didn't work, the translations are there, but the website is not being translated.
> > ![Task 39008 - Translations after updating terms](https://user-images.githubusercontent.com/26889951/82371546-fc6d4e00-99df-11ea-86cf-7c45660ccd48.png)
> 
> Why not trying to import again the translation file?

I tried it, but now I have duplicated translations, and the website remains with the same "translated" terms.
![Task 39008 - Importing translations](https://user-images.githubusercontent.com/26889951/82839810-333adc80-9e96-11ea-8a19-f5c6ac6a136e.png)

**Comment by hugho-ad** [comment]
@farinoire 

That's sound like a workaround, we need to fix the bug
