### ISSUE TITLE
[11]Draft PO Set date to all order lines not working

### ISSUE THREAD

**Issue by brasta** [odoo/odoo#51580]
Impacted versions: Odoo 11 enterprise https://runbot.odoo.com/runbot/build/2732378

Steps to reproduce: open new "request for quotation" (do not save yet), select vendor and add product. Go to "deliveries & invoice" tab and choose different "scheduled date" (PO should not be saved yet) and press "set date to all order lines".

Current behavior: Manual date we entered is reverted and not saved.

Expected behavior: Date we chose should be set on every purchase order line

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
As there's no yet lines, this is something expected. This behavior has been improved in later versions, but it's not going to be fixed in 11.0, and you need to adjust to its way of working.

Closing as won't fix in 11.0, but fixed in later versions.

**Comment by brasta** [comment]
But we added 1 Purchase order line with a product?

**Comment by pedrobaeza** [comment]
This is not what you have described in the original issue. Any way, do it a second time once saved, as not being saved doesn't allow to propagate data. Save, set the date, and click on propagate.

On later versions as said this has been improved.
