### ISSUE TITLE
Model Copy

### ISSUE THREAD

**Issue by neks-pl** [odoo/odoo#51586]
Impacted versions:13

Steps to reproduce: try to duplicate model action_>duplicate

Current behavior: error (same names model cant be created)

Expected behavior: create model with name=name+sequence

**Comment by pedrobaeza** [comment]
Which model? A custom one? If so, you have to handle that on your code.

**Comment by neks-pl** [comment]
Model made in studio. Sorry for not specifying. If its not button press than action duplicate should be removed if it's impossible :]  I'm not a programmer so when I see an option I expect it to do something ;]

**Comment by pedrobaeza** [comment]
For that kind of things I think Studio is not enough. Any way, you can ask to the paid support at odoo.com/help, as this is something enterprise and this issue tracker is mostly for Community Issue Tracking.
