### ISSUE TITLE
sale_mrp _get_bom_component_qty returns incorrect quantities for nested kits

### ISSUE THREAD

**Issue by theangryangel** [odoo/odoo#51592]
Impacted versions:

At least v12, v13

Steps to reproduce:

Create a phantom BoM with a valuation set to real_time and invoice policy of delivery.

Within that BoM have another phantom where the the quantities > 1.

i.e.  Seat (mrp kit) is comprised of;
* 1x seat back (stocked product)
* 2x arm kit (mrp kit)
  - 1x arm (stocked product)
  - 2x arm bolts (stocked product)

Current behavior:

With the example above, sale.order.line _get_bom_component_qty (sale_mrp) returns an incorrect quantity of arm bolts of 2 rather than 4 because it uses the line.product_qty rather than the line_data from explode.

Expected behavior:

_get_bom_component_qty should be returning a qty of 4 for the bolts.

I think? Or am I being stupid and not understanding what this function is supposed to be doing?

Video/Screenshot link (optional):

----

Potential fix, but I'd like to know if I'm misunderstanding/being stupid before I submit a PR..

```diff
diff --git a/addons/sale_mrp/models/sale_mrp.py b/addons/sale_mrp/models/sale_mrp.py
index 926c6259e03..c25b907f43f 100644
--- a/addons/sale_mrp/models/sale_mrp.py
+++ b/addons/sale_mrp/models/sale_mrp.py
@@ -33,7 +33,7 @@ class SaleOrderLine(models.Model):
         for line, line_data in lines:
             product = line.product_id.id
             uom = line.product_uom_id
-            qty = line.product_qty
+            qty = line_data.get('qty', line.product_qty)
             if components.get(product, False):
                 if uom.id != components[product]['uom']:
                     from_uom = uom
```

**Comment by Yenthe666** [comment]
@sle-odoo for you

**Comment by sle-odoo** [comment]
I'm not sure there's an issue, the result will be multiplied by the qty_invoiced.
Can you explain a little better the issue? The method pointed at is related in the stock valuation, did you find the issue in the accounting entries?

**Comment by theangryangel** [comment]
The customer I'm working with is adamant the cost of goods journal entries are not correct in the instance of nested items. However I'll be honest it's a little

**Comment by theangryangel** [comment]
The customer is adamant that the cost of goods isn't correct with nested items. That said the stock journals isn't an area I know well currently. What I'll do is go back to them, build up a little practical case with numbers and come back to you.
