### ISSUE TITLE
No prices are show in quotation when customer is not set before adding a product

### ISSUE THREAD

**Issue by HarlekinSimplex** [odoo/odoo#51597]
**Impacted versions:**
odoo 13 CE

**Steps to reproduce:**
- Create empty quotation
- Do not select any customer
- Add a product

**Current behavior:**
No price (just 0) is used for that product.
Same behavior if a pricelist ist selected prior adding the product

**Expected behavior:**
Standard prices should be used on adding a product without setting a customer
Pricelist prices should be used on adding a product without setting a customer but with a pricelist set.

**Comment by pedrobaeza** [comment]
This is something expected and you should use to this behavior, as it has been chosen this way: better to put 0 than a possible non real price, so set first the customer.

Closing as no issue, but expected behavior.

**Comment by HarlekinSimplex** [comment]
Thank you for that quick clarification.
