### ISSUE TITLE
[7.0] [8.0] It must not be possible to change the journal of an invoice that has already received a number

### ISSUE THREAD

**Issue by sbidoul** [odoo/odoo#5162]
In some circumstances it is possible to enter invoices in a journal with the numbering of another journal.

### How to reproduce

* runbot 8.0 (7.0 is the same)
* create an invoice, select journal A an validate it: it receives a number in journal A
* cancel the invoice and reset to draft
* change the journal (select journal B)
* validate it: it keeps the number of journal A

### Proposed solution

Prevent changing the journal when internal_number is not null.

**Comment by sbidoul** [comment]
@qdp-odoo @Whisno we want to propose a fix for this.
Would you accept it in the 7.0 branch?

cc/ @laetitia-gangloff

**Comment by sbidoul** [comment]
cc/ @adrienpeiffer

**Comment by antonylesuisse** [comment]
Fixed in eda2736e4c251e05ab50eb1db9c2cd9889088f30
