### ISSUE TITLE
--log-db and --log-level=debug_rpc are incompatible

### ISSUE THREAD

**Issue by dreispt** [odoo/odoo#5163]
Start a server with `./odoo.py -d myodoo --log-db=myodoo --log-level=debug_rpc`.
Now if you visit the "Logging" menu option on the Settings menu, you will see this error:

    Traceback (most recent call last):
      File "/home/dr/work/odoo/openerp/http.py", line 530, in _handle_exception
        return super(JsonRequest, self)._handle_exception(exception)
      File "/home/dr/work/odoo/openerp/http.py", line 562, in dispatch
        _, start_vms = psutil.Process().get_memory_info()
    TypeError: __init__() takes exactly 2 arguments (1 given)

If you use just `--log-level=debug` no error is found.

(I also noticed that most log messages are missing, so I get the impression that only some selected log messages are being written to the database...)

**Comment by rgo-odoo** [comment]
For v8, it should be fixed by PR #5108

**Comment by antonylesuisse** [comment]
Fixed in 04de29288559cdb4fe841e80b1f8bf41fb76dbfc
