### ISSUE TITLE
[8.0]Error when search product variants by location

### ISSUE THREAD

**Issue by jesusVMayor** [odoo/odoo#5164]
When search product variant by location or by warehouse raise an error.
![seleccion_001](https://cloud.githubusercontent.com/assets/5393537/6104418/a54f647c-b04d-11e4-86f1-e588444f9108.png)

**Comment by celm1990** [comment]
Please review  [this comment](https://github.com/odoo/odoo/commit/5e475f75de2a2dff24d6ae0b03d7ec4622a8c8a5#commitcomment-22939507)
