### ISSUE TITLE
Problem with scanning packs of products

### ISSUE THREAD

**Issue by cierek** [odoo/odoo#51648]
Impacted versions:
Odoo 12 Enterprise
Steps to reproduce:
1) Configure the product **with a serial number** 
2) set product units of measure as a pack of 100
3) Create a purchase order and use a scanner to receive the product
4) Once scanned the barcode only one product per scan, so if there is a pack of 100 pieces the barcode will have to be scanned 100 times...

Current behaviour:
When I scan a product that has configured packaging, one click is one pack and not as it is now a unit

Expected behaviour:
Odoo does not allow to scan products packed in multi-packs when the serial number is turned off.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
As this is something of enterprise, please report it to odoo.com/help instead.

**Comment by Yenthe666** [comment]
Plus this is kinda a new request because Odoo doesn't have anything built-in to scan boxes/packs/...
This would probably be a wishlist I guess. @sle-odoo what do you think?

**Comment by sle-odoo** [comment]
Hi,
It doesn't make sense to me. If your product is tracked by serial number, then you'll need to scan the 100 serial numbers.

If your product wasn't tracked by serial number, then you could use a product packaging and create a "pack of 100", add a barcode and you'd be able to scan it on both picking form and barcode client action.

> Odoo doesn't have anything built-in to scan boxes/packs/...

We do handle this use case with the product packaging.

Regards
