### ISSUE TITLE
transferring an unopened pack does not respect the owner

### ISSUE THREAD

**Issue by lepistone** [odoo/odoo#5165]
This was introduced in odoo/odoo#4548 (actually it was broken in a different way before that).

How to reproduce:

- enable stock ownership and packaging
- setup your warehouse for 2-step reception
- receive some stock with owner "Agrolait". In the first picking, from **suppliers** to **incoming**, set the owner to Agrolait and when transferring, hit the button to put the stock in a new pack and transfer the picking
- this will correctly create a quant in **incoming** with owner Agrolait and the pack we created
- Now open the chained picking from **incoming** to **stock** and transfer it. The pack we just created will be proposed as a whole in the second group, which is correct. Transfer the picking as it is.

Result: a quant with no owner is created in **stock**, and a negative quant with no owner is created in **incoming**.
Expected: a quant with owner Agrolait is created in **stock**, and the one in **incoming** is deleted.

Related issue: odoo/odoo#4136

Thanks!

**Comment by zbik2607** [comment]
Related issue: https://github.com/odoo/odoo/issues/3484
