### ISSUE TITLE
[12.0] sum of fields even if there is no sum tag in the list view

### ISSUE THREAD

**Issue by m3asmi** [odoo/odoo#51682]
for the view : https://2760122-12-0-2617f8.runbot43.odoo.com/web?debug=assets#action=321&active_id=1&model=hr.leave.report&view_type=list&menu_id=163

I removed the `sum tag` for  **Number of days** and there is still a sum!

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
