### ISSUE TITLE
[12.0] Inherited mail template are not exporting translate term

### ISSUE THREAD

**Issue by jat-odoo** [odoo/odoo#51684]
Impacted versions:
V12

Steps to reproduce:
Try to Export Translation for module which contains inherited mail template.

Current behavior:
It's not exporting translate terms of inherited mail body.

Expected behavior:
It should export translate terms of inherited mail body.

Video/Screenshot link (optional):
We did not find inherited mail body's terms in `i18n` folder of `l10n_be_invoice_bba` module.
https://github.com/odoo/odoo/blob/12.0/addons/l10n_be_invoice_bba/data/mail_template_data.xml

**Comment by jat-odoo** [comment]
@mart-e Can you check this?
Thanks.

**Comment by mart-e** [comment]
Hi Jigar,

This is the same for all translated records, it's translated inside the module defining the record. Your record `A.foo` will be translated inside the module `A`, even if `B` modifies it.
This is why a module should _not_ modify a translated record, it's a bad practice.

Everything works as exepected, l10n_be_invoice_bba should not modify the source template but works differently (content in python code,...).
Moreover mail templates are `noupdate` records so are even less good candidates to modifications.
