### ISSUE TITLE
[8.0] Date of Transfer isn't initialized on a picking genereted by a POS Order

### ISSUE THREAD

**Issue by adrienpeiffer** [odoo/odoo#5169]
Hi,

Here, a scenario on runbot 8.0

Steps to reproduce
------------------------

- Go on runbot 8.0
- Click on point of sale menu
- Open a session or create one
- Add a stockable product on the receipt
- Click on Bank journal
- Click on Validate
- Close the session
- On point of sale menu, click on order submenu
- Select the created order
- Go to Extra info page
- Open the related picking 

Expected behavior
------------------------

- On Additional info page, date of transfer is automatically initialized.

Current behavior
---------------------

- Date of transfer isn't initialized

Thanks

**Comment by adrienpeiffer** [comment]
OPW 627561

**Comment by dmo-odoo** [comment]
Thank you for the great steps indications !
Fixed in https://github.com/odoo/odoo/commit/88349d0fab46cfa4ebc36b28032f2871b039f2e4

**Comment by adrienpeiffer** [comment]
@dmo-odoo  Thanks for the fix :)
