### ISSUE TITLE
Is it the wrong po format?

### ISSUE THREAD

**Issue by jiad** [odoo/odoo#51690]
https://github.com/odoo/odoo/blob/7d339b354ddc6a68e6977e6c3367a58ca59facc5/addons/payment/i18n/zh_CN.po#L1737
https://github.com/odoo/odoo/blob/7d339b354ddc6a68e6977e6c3367a58ca59facc5/addons/payment/i18n/zh_CN.po#L1738

This two lines are seperated, and both in double quotes. 
But In my opinion, should be only one line like below:
**msgid "The transaction %s with %s for %s has been confirmed. The related payment is posted: %s"**
https://github.com/odoo/odoo/blob/2617f8c27262d8c923bea376b64d04e1804da15b/addons/payment/i18n/payment.pot#L1655

**Comment by pedrobaeza** [comment]
It's line wrap and it's allowed in the format.

Closing as no issue.
