### ISSUE TITLE
Incoming Notification Emails

### ISSUE THREAD

**Issue by EmirT** [odoo/odoo#51698]
**Impacted versions:** 
All versions

**Steps to reproduce:**
1. Send an Invoice to the client and add multiple followers/subscribers to the INV,
2. Client reply to INV,
3. Check the notification email which Odoo sends to the followers/subscribers about this INV reply.

Note: You can also see the notification emails follow by; Configuration > Messages > GroupBy (from)

**Current behavior:**
In order to notify followers (subscribers), Odoo using the client's domain under the Outgoing mail server.

**Expected behavior:**
Odoo should send notification from the company domain. This can be catchall or any other email setup.

Video/Screenshot link (optional):
Upon request I can screenshot or I can have shot meeting on google-meeting.

**Comment by pedrobaeza** [comment]
This has been something discussed previously and it's done this way on purpose. If you want to avoid it, put an intermediate relay that do SRS (https://en.wikipedia.org/wiki/Sender_Rewriting_Scheme).

Closing as expected behavior.
