### ISSUE TITLE
[7.0] for tax-inclusive case, base amount does not calculate properly when journal entry is posted through expenses

### ISSUE THREAD

**Issue by yostashiro** [odoo/odoo#517]
Base Amount does not deduct the tax amount from the input amount in expense entry even though price_include=true in tax setting.

I created an expense entry with a product with 8% inclusive tax setting with the amount 132,890.  I was expecting the base amount of the corresponding expense journal item to be 123,046 after 8% tax amount deduction, but it does not appear to be the case.
![_061314_044555_pm](https://cloud.githubusercontent.com/assets/7766939/3268054/25c7c282-f2d7-11e3-87d4-5220d81ccd73.jpg)

The result seems to be correct in case the same entry is done through supplier invoice.
![_061314_045559_pm](https://cloud.githubusercontent.com/assets/7766939/3268152/8d3615b2-f2d8-11e3-99ad-8ec2730cdca9.jpg)

I am actually not perfectly sure which (expenses or supplier invoices) is behaving correctly, but at least the behavior is inconsistent, which as a result makes the output the tax chart inconsistent (between base amount and tax amount) as well.

**Comment by Yenthe666** [comment]
Dear @yostashiro,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
