### ISSUE TITLE
Sale Order - catching state value on creation?

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#5171]
I need to override create method and add some functionality when state is set on creation. But I can't seem to catch state before creation, only after.

for example:

``` python
@api.model
def create(self, vals):
    print vals
    ctx = self.env.context
    print ctx
   print self.state
    return super(sale, self).create()
```

Doing this does not show that state is being set for sale order (I mean printing any of those, there is no state value in any). As I remember in the passed if default value for field was used, it would go to context, like `'default_state: 'draft'`, but now it is not passed in context. I'm wondering where it is being passed?
Because if I try to do this:

``` python
@api.model
def create(self, vals):
    rec = super(sale, self).create()
    print rec.state
    return rec
```

After record is created, then state is being printed. But I'm wondering, from where that value was passed?  Because before creation I could not see state being passed at all. Does something changed and default values and being passed somehow differently?

P.S. so the work around I see is I could let sale order creation happen and then check if state was set and then do changes. But this way performance would be slower, because on top of creation I would need to call write (if it would happened before creation I could simply pass new values for fields on creation method dictionary).

**Comment by lithint** [comment]
Hi,

You can try like the following to get state before getting created.


    @api.model
    def create(self, vals):
        if vals.get('state'):
            print "STATE...:",vals.get('state')
        return super(sale, self).create(vals)



On Mon, Feb 9, 2015 at 5:40 PM, Andrius Laukavičius <
notifications@github.com> wrote:

> I need to override create method and add some functionality when state is
> set on creation. But I can't seem to catch state before creation, only
> after.
>
> for example:
>
> @api.modeldef create(self, vals):
>     print vals
>     ctx = self.env.context
>     print ctx
>    print self.state
>     return super(sale, self).create()
>
> Doing this does not show that state is being set for sale order (I mean
> printing any of those, there is no state value in any). As I remember in
> the passed if default value for field was used, it would go to context,
> like 'default_state: 'draft', but now it is not passed in context. I'm
> wondering where it is being passed?
> Because if I try to do this:
>
> @api.modeldef create(self, vals):
>     rec = super(sale, self).create()
>     print rec.state
>     return rec
>
> After record is created, then state is being printed. But I'm wondering,
> from where that value was passed? Because before creation I could not see
> state being passed at all. Does something changed and default values and
> being passed somehow differently?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/odoo/odoo/issues/5171>.
>



-- 
Thanks & Regards,

Lithin T
Software Engineer
Mob  : +91 7736561076(India), +971556712557(UAE)
Mail  : lithint.mail@gmail.com | Skype : lithint.skype

**Comment by oerp-odoo** [comment]
Hi, maybe you didn't understand what I've written. I said it does not pass state this way. I mean if I print whole ```vals``` dictionary and can't see it there, then using vals.get('state'), does the same, because that key is simply not there. Thats where the problem is.

**Comment by Yenthe666** [comment]
Hi @oerp-odoo,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
