### ISSUE TITLE
[IMP] Tasks classification

### ISSUE THREAD

**Issue by aitalinassim** [odoo/odoo#51712]
**Impacted versions:**
13

**Feature this functionality:**
Integration of a new feature to improve module functionality and user experience.

**Current behavior:**
Only given kanban or list view of tasks, without classification possibility.
Only star given tasks are shown on the top.

**Desired behavior**:
Allow the user to class the tasks on 4 principle classes:

To do immediately
to do later
to delegate
not to do
This classification will be made as per each task, when the user enter the task, he gives "IMPORTANCE" note and "EMERGENCY" note.

Tasks will be classified as per the following.

![urgency-importance-matrix](https://user-images.githubusercontent.com/28365138/82680408-1effa100-9c44-11ea-92b3-f7a21878c621.png)

**Comment by Yenthe666** [comment]
I honestly do not think this will ever be implemented. In fact, I'd say you can do this all in Odoo by default. Create stages for your four pillars, assign it to the right people (or use activities) and you have pretty much the same.
@pedrobaeza what is your call?

**Comment by pedrobaeza** [comment]
Me neither, as it's not the way Odoo works. Several points about this:

- New features are always for master branch (which will be the next version). Never on current version.
- Odoo performs the design internally through their product owners.
- Sometimes, they expose to community that design early for community comments, but not the contrary.

You can any way implement that feature in the current version through new modules that makes use of inheritance mechanisms in ORM framework, which allows you to do a lot of things. This RFC/blueprint makes sense in a community discussion in OCA. For example, you can put an issue in https://github.com/OCA/project and maybe others might give their opinion on the feature, but later it has to be developed by someone.

Just this feature seems very similar to the one we migrated some time ago:

https://github.com/OCA/project/tree/12.0/project_risk

Any way, this is not going to evolve, so better to close it now.
