### ISSUE TITLE
Replacing jinja2 templates does not work

### ISSUE THREAD

**Issue by HarlekinSimplex** [odoo/odoo#51727]
**Impacted versions:**
odoo 13 CE

**Steps to reproduce:**
Create a module to change or replace a jinja2 email template and its translations using xml statements like this:

```
<delete model="mail.template" search="[('id','=',ref('sale.mail_template_data_notification_email_sale_order'))]"/>
<record id="sale.mail_template_data_notification_email_sale_order" model="mail.template">
    <field name="name">My new eMail template</field>
    <field name="subject">Regarding ... ${object.subject}</field>
    <field name="model_id" ref="mail.model_mail_message"/>
    <field name="auto_delete" eval="True"/>
    <field name="body_html"><![CDATA[<html> .... </html>]]></field>
</record>
```

**Current behavior:**
Using odoo 11 it was possible to just delete a template from mail.templates and create it anew as described above.

Using this with odoo 13 just produces a missing external identifier error.

**Expected behavior:**
Just like it was with odoo 11

If thats not the way to go what is?

How to change or modify jinja2 template bodies, subjects and of course their translations of stock  modules (like auth_signup, sales, etc.) using a custom modul?

Using the UI it is simple. But how to do that by installing a cutom module?

The no_update flag blocks any modifications to existing template records.
By design existing translations are not updateable by custom modules.
To do that you have to upgrade or reinstall the respective module.
And with that you are back to the original templates again.

I solved that problem by bust replacing the translation records of the existing templates directly at  ir.translations by using delete xml statements that remove the respective records together with a customized .po file in my module to create the deleted translations with the intended modifcations again.
I got feedback at the forum that this may not be the way to achive this.
But then which way is the right way?

If the currrent behavior is intended and my solution is a no fit, then this may lead to a feature request that enables us to change email templates properly.
Maybe this will pave to way to replace all remaining jinja2 email templates with QWeb templates that are easy to change by just using template inheritance.
Or the other way around there may be a way to implement a similar inheritance option for jinja2 templates too.

Cheers
Stephan

**Comment by pedrobaeza** [comment]
Are you depending on the module you are replacing the XML-ID?

**Comment by HarlekinSimplex** [comment]
Yes.
All of them.
The structure and content of more or less all stock templates need to be changed.
The most important elven templates I need to change are from:

- auth_signup
- account
- sale
- purchase
- invoice
- website
- website_sale
 
They all have xml ids now.

**Comment by HarlekinSimplex** [comment]
If there were a dialog or mapping mechanism where we could actually define which template to use if a certain template id is called - that would solve the whole problem very nicely.

This was I would just create and maintain my templates and then simpley tell the stock modules which template to use....

**Comment by pedrobaeza** [comment]
I have done this in the past without problems, so I'm not sure about the problem. And please don't deviate with side topics in the same issue.

**Comment by HarlekinSimplex** [comment]
Just run another test to make sure the problem still exists and to post the full error log:

**First Step - Create a new template (just to test that my modul is installing properly)**
```
    <record id="reset_password_email" model="mail.template">
        <field name="name">XXX Auth Signup: Reset Password</field>
        <field name="model_id" ref="base.model_res_users"/>
        <field name="subject">XXX Password reset</field>
        <field name="email_from">"${object.company_id.name | safe}" &lt;${(object.company_id.email or user.email) | safe}&gt;</field>
        <field name="email_to">${object.email_formatted | safe}</field>
        <field name="body_html" type="html">...XXX...</field>
        <field name="lang">${object.lang}</field>
        <field name="auto_delete" eval="True"/>
        <field name="user_signature" eval="False"/>
    </record>
```
This creates a new email template and an XML id with my module name in front.
OK - expected behavior

**Second Step - Test if we can modify the template record that was created by auth_signup**
```
    <record id="auth_signup.reset_password_email" model="mail.template">
        <field name="name">XXX Auth Signup: Reset Password</field>
        <field name="model_id" ref="base.model_res_users"/>
        <field name="subject">XXX Password reset</field>
        <field name="email_from">"${object.company_id.name | safe}" &lt;${(object.company_id.email or user.email) | safe}&gt;</field>
        <field name="email_to">${object.email_formatted | safe}</field>
        <field name="body_html" type="html">...XXX...</field>
        <field name="lang">${object.lang}</field>
        <field name="auto_delete" eval="True"/>
        <field name="user_signature" eval="False"/>
    </record>
```
This seems to be ignored completely.
There is no DEBUG log entry visible that tells me that this record update was ignored.
OK - expected behavior because of NO_UPDATE flag.

**Third Step - Test if I can create the template anew after deleting it as I did with odoo11**
```
    <delete model="mail.template" search="[('id','=',ref('auth_signup.reset_password_email'))]"/>
    <record id="auth_signup.reset_password_email" model="mail.template">
        <field name="name">XXX Auth Signup: Reset Password</field>
        <field name="model_id" ref="base.model_res_users"/>
        <field name="subject">XXX Password reset</field>
        <field name="email_from">"${object.company_id.name | safe}" &lt;${(object.company_id.email or user.email) | safe}&gt;</field>
        <field name="email_to">${object.email_formatted | safe}</field>
        <field name="body_html" type="html">...XXX...</field>
        <field name="lang">${object.lang}</field>
        <field name="auto_delete" eval="True"/>
        <field name="user_signature" eval="False"/>
    </record>
```
That now raised the following error:
```
2020-05-24 15:14:36,350 104 ERROR bitnami_odoo odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/opt/bitnami/odoo/odoo/tools/convert.py", line 712, in parse
    self._tag_root(de)
  File "/opt/bitnami/odoo/odoo/tools/convert.py", line 674, in _tag_root
    f(rec)
  File "/opt/bitnami/odoo/odoo/tools/convert.py", line 674, in _tag_root
    f(rec)
  File "/opt/bitnami/odoo/odoo/tools/convert.py", line 527, in _tag_record
    raise Exception("Cannot update missing record %r" % xid)
Exception: Cannot update missing record 'auth_signup.reset_password_email'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/bitnami/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/bitnami/odoo/odoo/modules/loading.py", line 419, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/opt/bitnami/odoo/odoo/modules/loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/bitnami/odoo/odoo/modules/loading.py", line 225, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/opt/bitnami/odoo/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/opt/bitnami/odoo/odoo/tools/convert.py", line 736, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/bitnami/odoo/odoo/tools/convert.py", line 803, in convert_xml_import
    obj.parse(doc.getroot())
  File "/opt/bitnami/odoo/odoo/tools/convert.py", line 721, in parse
    exc_info[2]
  File "/opt/bitnami/odoo/odoo/tools/pycompat.py", line 13, in reraise
    raise value.with_traceback(tb)
  File "/opt/bitnami/odoo/odoo/tools/convert.py", line 712, in parse
    self._tag_root(de)
  File "/opt/bitnami/odoo/odoo/tools/convert.py", line 674, in _tag_root
    f(rec)
  File "/opt/bitnami/odoo/odoo/tools/convert.py", line 674, in _tag_root
    f(rec)
  File "/opt/bitnami/odoo/odoo/tools/convert.py", line 527, in _tag_record
    raise Exception("Cannot update missing record %r" % xid)
```
Is that a bug or expected behavior?
And if that is expected then how I'm expected to do this with odoo 13 ?

Cheers
Stephan

**Comment by pedrobaeza** [comment]
It's totally expected behavior, as you are removing the record, and the XML-ID is removed with it.

With noupdate=1 records, you can't replace them on update, but installing your module that "replaces them" (with `--init`/`-i` mode), the change should be done. That's how this works.

Closing as no bug.
