### ISSUE TITLE
[13] website_rating/slides: wrong title on average rating

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#51743]
Impacted versions: 13.0

Steps to reproduce: 
![screenshot--2020 05 25-00_15_16](https://user-images.githubusercontent.com/16624719/82762121-d818d380-9e1c-11ea-9c4a-cef639d6f93e.png)
![screenshot--2020 05 25-00_16_47](https://user-images.githubusercontent.com/16624719/82762151-0dbdbc80-9e1d-11ea-987e-fb0347fb5398.png)

Current behavior: It is always `One star`

Expected behavior: Should be dynamic based on Rating average

Video/Screenshot link (optional):

**Comment by rdeodoo** [comment]
fixed with https://github.com/odoo/odoo/commit/6ef7d6fd8474cbf9685bf8e8c3520233c1403cfd
