### ISSUE TITLE
Odoo 13 cannot marshal None unless allow_none is enabled on action_post

### ISSUE THREAD

**Issue by dsonnet** [odoo/odoo#51741]
Impacted versions: Odoo 13 Enterprise

Steps to reproduce: From C# RPC call action_post on account.move model

Seems similar to https://github.com/odoo/odoo/issues/19889

I have no knowledge of python but could it be that the self.post() seems to have no return value

**Comment by pedrobaeza** [comment]
Yes, similar, but the solution is to make a pull request that returns something in that method, so what about doing that?

**Comment by Yenthe666** [comment]
Closing as a PR was made at https://github.com/odoo/odoo/pull/52022
