### ISSUE TITLE
[odoo9]two Install Problem in CentOS7 (HTTP Error 404 - Not Found)

### ISSUE THREAD

**Issue by akira32chen** [odoo/odoo#51746]
I see the document of odoo 9 to install odoo 9 community (https://www.odoo.com/documentation/9.0/setup/install.html) ,  but I meet two problems as below:

first problem :
When I run the command of 
$sudo postgresql-setup initdb

appears  the error message as below:
Data directory is not empty!

second problem is "HTTP Error 404 - Not Found"
When I run the command of
$ sudo yum install -y odoo
appears  the error message([Errno 14] HTTP Error 404 - Not Found) as below:

`
$ sudo yum-config-manager --add-repo=https://nightly.odoo.com/9.0/nightly/rpm/odoo.repo
Loaded plugins: fastestmirror, langpacks
adding repo from: https://nightly.odoo.com/9.0/nightly/rpm/odoo.repo
grabbing file https://nightly.odoo.com/9.0/nightly/rpm/odoo.repo to /etc/yum.repos.d/odoo.repo
repo saved to /etc/yum.repos.d/odoo.repo

$ sudo yum install -y odoo
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirror01.idc.hinet.net
 * epel: fedora.cs.nctu.edu.tw
 * extras: mirror01.idc.hinet.net
 * updates: mirror01.idc.hinet.net
Resolving Dependencies
--> Running transaction check
---> Package odoo.noarch 0:9.0rc20190424-1 will be installed
--> Processing Dependency: python-vobject for package: odoo-9.0rc20190424-1.noarch
--> Processing Dependency: python-openid for package: odoo-9.0rc20190424-1.noarch
--> Processing Dependency: python-werkzeug for package: odoo-9.0rc20190424-1.noarch
--> Processing Dependency: python-mock for package: odoo-9.0rc20190424-1.noarch
--> Processing Dependency: python-feedparser for package: odoo-9.0rc20190424-1.noarch
--> Processing Dependency: python-jinja2 for package: odoo-9.0rc20190424-1.noarch
--> Processing Dependency: python-xlwt for package: odoo-9.0rc20190424-1.noarch
--> Processing Dependency: python-docutils for package: odoo-9.0rc20190424-1.noarch
--> Processing Dependency: nodejs-less for package: odoo-9.0rc20190424-1.noarch
--> Processing Dependency: python-psutil for package: odoo-9.0rc20190424-1.noarch
--> Processing Dependency: python-imaging for package: odoo-9.0rc20190424-1.noarch
--> Processing Dependency: babel for package: odoo-9.0rc20190424-1.noarch
--> Processing Dependency: python-reportlab for package: odoo-9.0rc20190424-1.noarch
--> Processing Dependency: python-passlib for package: odoo-9.0rc20190424-1.noarch
--> Processing Dependency: libxslt-python for package: odoo-9.0rc20190424-1.noarch
--> Processing Dependency: pychart for package: odoo-9.0rc20190424-1.noarch
--> Running transaction check
---> Package babel.noarch 0:0.9.6-8.el7 will be installed
--> Processing Dependency: python-babel for package: babel-0.9.6-8.el7.noarch
---> Package libxslt-python.x86_64 0:1.1.28-5.el7 will be installed
---> Package nodejs-less.noarch 0:1.7.0-2.el7 will be installed
--> Processing Dependency: npm(ycssmin) < 1.1 for package: nodejs-less-1.7.0-2.el7.noarch
--> Processing Dependency: nodejs(engine) >= 0.8.0 for package: nodejs-less-1.7.0-2.el7.noarch
--> Processing Dependency: npm(ycssmin) >= 1.0.1 for package: nodejs-less-1.7.0-2.el7.noarch
--> Processing Dependency: nodejs for package: nodejs-less-1.7.0-2.el7.noarch
---> Package pychart.noarch 0:1.39-17.el7 will be installed
---> Package python-docutils.noarch 0:0.11-0.3.20130715svn7687.el7 will be installed
---> Package python-feedparser.noarch 0:5.1.3-3.el7 will be installed
---> Package python-jinja2.noarch 0:2.7.2-4.el7 will be installed
---> Package python-openid.noarch 0:2.2.5-7.el7 will be installed
---> Package python-pillow.x86_64 0:2.0.0-20.gitd1c6db8.el7_7 will be installed
---> Package python-reportlab.x86_64 0:2.5-10.el7 will be installed
---> Package python-vobject.noarch 0:0.8.1c-8.el7 will be installed
---> Package python-werkzeug.noarch 0:0.9.1-2.el7 will be installed
---> Package python-xlwt.noarch 0:0.7.4-5.el7 will be installed
--> Processing Dependency: antlr-python for package: python-xlwt-0.7.4-5.el7.noarch
---> Package python2-mock.noarch 0:1.0.1-10.el7 will be installed
---> Package python2-passlib.noarch 0:1.7.1-1.el7 will be installed
---> Package python2-psutil.x86_64 0:5.6.7-1.el7 will be installed
--> Running transaction check
---> Package antlr-python.noarch 0:2.7.7-30.el7 will be installed
---> Package nodejs.x86_64 1:6.17.1-1.el7 will be installed
--> Processing Dependency: npm = 1:3.10.10-1.6.17.1.1.el7 for package: 1:nodejs-6.17.1-1.el7.x86_64
--> Processing Dependency: libuv >= 1:1.9.1 for package: 1:nodejs-6.17.1-1.el7.x86_64
--> Processing Dependency: libuv.so.1()(64bit) for package: 1:nodejs-6.17.1-1.el7.x86_64
---> Package python-babel.noarch 0:0.9.6-8.el7 will be installed
---> Package ycssmin.noarch 0:1.0.1-6.el7 will be installed
--> Running transaction check
---> Package libuv.x86_64 1:1.37.0-1.el7 will be installed
---> Package npm.x86_64 1:3.10.10-1.6.17.1.1.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package            Arch    Version                         Repository     Size
================================================================================
Installing:
 odoo               noarch  9.0rc20190424-1                 odoo-nightly  107 M
Installing for dependencies:
 antlr-python       noarch  2.7.7-30.el7                    base           50 k
 babel              noarch  0.9.6-8.el7                     base           15 k
 libuv              x86_64  1:1.37.0-1.el7                  epel          147 k
 libxslt-python     x86_64  1.1.28-5.el7                    base           59 k
 nodejs             x86_64  1:6.17.1-1.el7                  epel          4.7 M
 nodejs-less        noarch  1.7.0-2.el7                     epel          102 k
 npm                x86_64  1:3.10.10-1.6.17.1.1.el7        epel          2.5 M
 pychart            noarch  1.39-17.el7                     epel          190 k
 python-babel       noarch  0.9.6-8.el7                     base          1.4 M
 python-docutils    noarch  0.11-0.3.20130715svn7687.el7    base          1.5 M
 python-feedparser  noarch  5.1.3-3.el7                     epel          107 k
 python-jinja2      noarch  2.7.2-4.el7                     base          519 k
 python-openid      noarch  2.2.5-7.el7                     epel          211 k
 python-pillow      x86_64  2.0.0-20.gitd1c6db8.el7_7       base          439 k
 python-reportlab   x86_64  2.5-10.el7                      base          1.2 M
 python-vobject     noarch  0.8.1c-8.el7                    epel           88 k
 python-werkzeug    noarch  0.9.1-2.el7                     extras        562 k
 python-xlwt        noarch  0.7.4-5.el7                     epel          164 k
 python2-mock       noarch  1.0.1-10.el7                    epel           92 k
 python2-passlib    noarch  1.7.1-1.el7                     epel          741 k
 python2-psutil     x86_64  5.6.7-1.el7                     epel          399 k
 ycssmin            noarch  1.0.1-6.el7                     epel           12 k

Transaction Summary
================================================================================
Install  1 Package (+22 Dependent packages)

Total size: 122 M
Total download size: 107 M
Installed size: 550 M
Downloading packages:
odoo_9.0c.20190424.noarch.rpm  FAILED                                          
http://nightly.odoo.com/9.0/nightly/rpm/odoo_9.0c.20190424.noarch.rpm: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below wiki article 

https://wiki.centos.org/yum-errors

If above article doesn't help to resolve this issue please use https://bugs.centos.org/.

Error downloading packages:
  odoo-9.0rc20190424-1.noarch: [Errno 256] No more mirrors to try.
`

**Comment by Elkasitu** [comment]
Hello,

> Data directory is not empty!
This means you most likely already have postgresql set up

As for the 404 error, Odoo 9.0 is no longer actively maintained (only versions 11.0 through 13.0 are) thus we no longer supply binaries for it, you're still able to install it through source if you so desire but we don't recommend it.
