### ISSUE TITLE
Failing Unit Test - TestBillsPrediction

### ISSUE THREAD

**Issue by reciprocal-space** [odoo/odoo#51745]
Hi,

I'm new to Odoo so apologies if I'm missing something obvious. Builds across all of my branches  - including branches that were previously stable - now contain an error with the unit test 'TestBillsPrediction'. The stable branches haven't had any new code pushed to them (modifications) so I think there may an issue with one of the core addons? I'm not sure, but would appreciate your expert insight :)

Impacted versions: 12.0

Steps to reproduce: Try building with a module that makes use of the 'TestBillsPrediction' unit test

Current behavior: Test fails

Expected behavior: Test should pass

Video/Screenshot link (optional): Stack trace below:

![image](https://user-images.githubusercontent.com/19412227/82768758-01c30200-9dff-11ea-9358-a779fbcb2f14.png)

**Comment by pedrobaeza** [comment]
Sorry, but there are 2 conditions that makes this issue to not be very suitable:

- It's an enterprise module. You can report things about enterprise in odoo.com/help.
- It's about tests and custom code, so there's no problem at all in Odoo itself, and tests are executed in a specified way all together, and that can be also the reason.

Then, I'm closing this issue.
