### ISSUE TITLE
Odoo 13 ModuleNotFoundError: No module named 'odoo.addons.web_kanban'

### ISSUE THREAD

**Issue by mehdi-24** [odoo/odoo#51742]
Impacted versions: Odoo 13

Steps to reproduce: When i run pycharm 

Current behavior: module web_kanban: module not found 

Expected behavior:

Video/Screenshot link (optional):

![2020-05-24_18-51-03](https://user-images.githubusercontent.com/59867267/82761763-28803900-9dfd-11ea-8708-c08988574a8a.png)

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/13.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).

**Comment by mehdi-24** [comment]
hello again, 
I followed the steps but I still have this problem, here is the configuration on pycharm. I tried several things but nothing works.
![image](https://user-images.githubusercontent.com/59867267/82800471-10033380-9e7c-11ea-89df-555576f5900e.png)

**Comment by pedrobaeza** [comment]
This kind of questions should be done on the forum, not here, as this is for issues with Odoo code.
