### ISSUE TITLE
issues in work orders planning

### ISSUE THREAD

**Issue by ccandito** [odoo/odoo#5176]
Dear Odoo,
we'd level production capacity through the "work order by resource" tool and we had the following issues:
1) it is not possible to check on line the capacity available per work center and compare it with the current workload; both figures should be available;
2) the bar length is sometimes wrong because the end date is not displayed correctly; the end date in WO is different to the end of the corresponding bar;
3) the corresponding start date in MO calendar is not updated, so there is a mismatch between MO's dates and WO's dates;
4) it is not possible to group by work center and MO both
thanks in advance
claudio candito

**Comment by Yenthe666** [comment]
Hi @ccandito,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
