### ISSUE TITLE
On odoo online on  page lead I create a new lead, confirm but odoo not create it (some error I think?)

### ISSUE THREAD

**Issue by ghost** [odoo/odoo#5179]
![image](https://cloud.githubusercontent.com/assets/665463/6122103/dd9b8e90-b0ee-11e4-8738-0ac2c9a587bc.png)

**Comment by hyperfocus1337** [comment]
Hosted Odoo from Bitnami cloud. Experiencing the same issue, any updates on this?

**Comment by Yenthe666** [comment]
Hi @hyperfocus1337,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
