### ISSUE TITLE
On Odoo Online app the product variant is not working

### ISSUE THREAD

**Issue by ghost** [odoo/odoo#5180]
![image](https://cloud.githubusercontent.com/assets/665463/6122142/69adcc9a-b0ef-11e4-8b6f-7e4200ea931d.png)

when I create a new product variants odoo create it (if I create another one with the same value it says that it exist), display it in the main product page (3 variant) but cannot display in the list nor appear in the list view of the variant to modify it

**Comment by Yenthe666** [comment]
Hi @ghost,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
