### ISSUE TITLE
[8.0] stock: bad config when changing wh from "Ship Only" to "Pick + Pack + Ship"

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#5181]
The `stock.picking.type` for Pack operation in configured differently when creating a warehouse in Pick + Pack + Ship mode (correct config) and when changing from a previous mode to  Pick + Pack + Ship (incorrect config). 
# Steps to reproduce
1. Connect to base instance of 8.0 on runbot 
2. Give Technical Features to Admin
3. Install the module "stock"
4. In settings / Warehouse, enable  `Manage multiple locations and warehouses` and `Manage advanced routes for your warehouse`
5. Create a new Warehouse called test1, short name t1 with outgoing shippings = `Ship directly from stock (Ship Only)`, click Save
6. Edit the warehouse test1, change outgoing shippings to `Make packages into a dedicated location, then bring them to the output location for shipping (Pick + Pack + Ship)`
7. Create a new warehouse called test2, short name t2 with outgoing shippings = `Make packages into a dedicated location, then bring them to the output location for shipping (Pick + Pack + Ship)`
# Expected Results

When checking  Warehouse / Types of Operations, the Pack operation for test1 and test2 should have the same locations (respective to the warehouse): src == Packing Zone, dest = Output. 
# Actual Results
- `t2/Pack` is correct
- the dest location of `t1/Pack` is `t1/Stock` (instead of `t1/Output`).

**Comment by gurneyalex** [comment]
#4985 could be related to this issue.

**Comment by gurneyalex** [comment]
When generating a SO from both warehouses, the pickings are correctly generated (because in this case the dest location of the picking type is not used, and the one from the pull rule is used).

**Comment by gurneyalex** [comment]
@jco-odoo could you check this? @guewen confirms fixing this should fix #4985

**Comment by Yenthe666** [comment]
Hi @gurneyalex,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
