### ISSUE TITLE
Slow loading fo product's form view in shop when many products exist with the same attribute value

### ISSUE THREAD

**Issue by a0c** [odoo/odoo#5182]
Obsolete check for attribute value's products (all of them!) slows down rendering of a product form considerably.
### Impacted versions:
- 8.0
##### Modules:
- product
- website_sale
##### Configuration:
- attribute with several values, like Size: S, M, L. Better several attributes => creates more different products.
- ~ 70 product templates, with the same attribute value shared across many templates (e.g. Size: M).
- ~ 2600 products
### Current behavior

Server response is terribly slow, 3-4 seconds to load the product page.
### To blame...

... is the obsolete check for `value_id.product_ids` when drawing the radio buttons for the possible attribute values. And the check happens for every radio button in the list ;)
### Solution

There is no point in checking if a variant value has any products attached to it, because:
1. it is guaranteed to be so: when variant values are added to a template, product creation is triggered automatically. So when Odoo shows a product view, the product is guaranteed to exist in the first place, and this product is guaranteed to be added to attribute value's list of products (`value_id.product_ids`).
2. moreover, `value_id.product_ids` returns ALL the products, not just those of the given product template -- so this check is faulty anyway.

Solution would be thus very simple: remove this obsolete check for `value_id.product_ids`.
### Possible drawbacks

The only case when this check would be relevant is if a user would have manually deleted ALL the products of ALL the templates with the given attribute value. This is unlikely to happen. And in this case user will not see the product in Shop anyway.

**Comment by Yenthe666** [comment]
It was handled in https://github.com/odoo/odoo/commit/a70ea6d03b3ddea0bf6b616f59085f8947219944
