### ISSUE TITLE
Remove width in .o_progressbar_value in css

### ISSUE THREAD

**Issue by tanghulu0608** [odoo/odoo#51828]
Impacted versions:
13.0

Steps to reproduce:
When progress bar widget used in a tree view,and there are a lot of fields show together,the progress number in the progress bar widget is not shown.
![image](https://user-images.githubusercontent.com/5561864/82847078-b0aa2f80-9f1e-11ea-9bf1-7ab90744273b.png)

Expected behavior:
remove width in .o_progressbar_value css, the number is show.
![image](https://user-images.githubusercontent.com/5561864/82847111-d59ea280-9f1e-11ea-9bd2-0f057209d6ed.png)

I have already used this in my system for some time. It is good.
I have make a pr here. [[FIX] remove width of o_progressbar_value](https://github.com/odoo/odoo/pull/51449)

**Comment by pedrobaeza** [comment]
As there's already a PR, there's no added value in having the same as issue, and there are the same chances (in fact, there are less as only an issue) to be checked, so closing. I have pong a possible reviewer on the PR.

**Comment by tanghulu0608** [comment]
Thanks.
