### ISSUE TITLE
[odoo9] I installed Odoo9 Windows, but I cannot find the location of source code 

### ISSUE THREAD

**Issue by akira32chen** [odoo/odoo#51829]
I had installed Odoo9 Windows version in Odoo Nightly builds(https://nightly.odoo.com/).
But I cannot find the location of source code. Does somebody know that location？

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
