### ISSUE TITLE
PO stat button on SO not working (disabled) in sale_purchase module

### ISSUE THREAD

**Issue by Rad0van** [odoo/odoo#51869]
Impacted versions: 13.0 sale_purchase

Steps to reproduce: create SO that contains Service products that have Purchase Automatically checked. Confirm the SO.

Current behavior: There is no PO stat button on SO

Expected behavior: There should be PO stat button on SO

The button is actually disabled because of PR #28410 from 12.0 where it didn't work correctly. Seems to be working correctly now so I guess the stat button could be enabled again.

**Comment by pedrobaeza** [comment]
You can make a PR activating it again.

**Comment by Rad0van** [comment]
> You can make a PR activating it again.

#51874

**Comment by pedrobaeza** [comment]
Closing then as there's a PR.
