### ISSUE TITLE
Attributes with a single value (e.g. Color: blue) make 'Product not available' in shop

### ISSUE THREAD

**Issue by a0c** [odoo/odoo#5189]
## Impacted versions:
- 8.0

###### Modules:
- product
- website_sale

###### Configuration:
- create a product template
- add an attribute to template and only specify 1 value for this attribute

## Current behavior:
In Shop, go to product's form view and see that product is not available (all of its variants).

## Expected behavior:
Product should be available.

**Comment by odony** [comment]
Are you sure this issue happens with the latest 8.0 version? It should have been fixed by c18a7eb82ae1a4a7cfd05c6e70bbf8c81e409ca9. Would you mind double-checking on the [latest 8.0 runbot build](http://runbot.odoo.com/runbot/b/8.0)? Thanks!

**Comment by a0c** [comment]
Sorry, my bad. Your commit works just fine. Took me a while to figure it out, 'cos in one of my modules I had to override `_get_attribute_value_ids()` completely, which prevented your commit from fixing my working copy :)
And your solution is definitely better.

**Comment by odony** [comment]
Thanks for the feedback, we can close this issue then :)
