### ISSUE TITLE
[13.0] account: could't change due date on lines

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#51928]
Impacted versions: 13.0

Steps to reproduce:  Try to change Due date
![screenshot- (4)](https://user-images.githubusercontent.com/16624719/82933204-383b8100-9fa7-11ea-84da-9efcf46e7140.png)

Current behavior: Due date is computed again and gets back to original one.

Expected behavior: Should be able to Change due date on lines

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
In an invoice, you must change it from the header.

Closing as no bug at all.

**Comment by sswapnesh** [comment]
What if we have multiple lines based on Payment terms and want to change date on on line ?

> help="This field is used for payable and receivable journal entries. You can put the limit date for the payment of this line."

Looking at the help of the field we should be able to change of from the view itself. 

If not, Why not making the field `readonly` here. (and also in `account.move.line` form)
Not sure but I think there's something wrong happening on onchange.

**Comment by pedrobaeza** [comment]
Have you tried with the invoice posted?

**Comment by sswapnesh** [comment]
https://2812252-13-0-23511d.runbot45.odoo.com/web?debug=1#id=5&action=550&model=account.move&view_type=form&cids=1&menu_id=384

On the Draft one, Lines are readonly on posted moves.

Ps: the same thing is working well on v12 (obv from the `account.move`)

**Comment by pedrobaeza** [comment]
Which data in header? A payment term with several terms or an invoice date?

**Comment by sswapnesh** [comment]
Tried Both (and also tried with payment term which created multiple Receivable lines)

**Comment by sswapnesh** [comment]
@qdp-odo What is your opinion on this one?

**Comment by pedrobaeza** [comment]
I have tried on runbot and I still see it correct: on draft moves, you can only edit due data in header. If you do it on lines, it's reset to previous values. On posted moves, lines are readonly. There's no too much sense on editing this information on draft moves. Once posted, you can edit due dates from other view, not this one. I agree though that it can be readonly in draft mode for avoiding false expectations, but that's an enhancement.

**Comment by sswapnesh** [comment]
> If you do it on lines, it's reset to previous values.

That's a bug IMO

> There's no too much sense on editing this information on draft moves.

I think It is because why do we need to switch the view to change date ?

> I agree though that it can be readonly in draft mode for avoiding false expectations, but that's an enhancement.

or Fix the onchange

Cc @qdp-odoo
