### ISSUE TITLE
OnChange will not apply, if the fieldname "length" is in the to evaluation object

### ISSUE THREAD

**Issue by agenterp** [odoo/odoo#51937]
https://github.com/odoo/odoo/blob/23511dffb9e3f597a7df9bb834d008f74abb07b8/addons/web/static/src/js/views/basic/basic_model.js#L1580

._each(object) will fail, if the key {'length': 10} will be in the onchange vals.

Something like Object.entries(values).forEach(([key, val]) => >...) should be used.

**Comment by pedrobaeza** [comment]
Duplicated of #50253

**Comment by Yenthe666** [comment]
Actually, I reported it through an OPW (`2151196`) and it should be changed in master, so upcoming V14.

**Comment by Yenthe666** [comment]
There's also this fix for default Odoo by the way: https://github.com/odoo/odoo/pull/43222
