### ISSUE TITLE
account.move invoice business fields modification through XMLRPC calls regression

### ISSUE THREAD

**Issue by a-willem** [odoo/odoo#51957]
Impacted versions:
13.0

Steps to reproduce:
Initially up until 12.0 the account.invoice model acted as a "gateway" to all other move-related features and allowed for a easy management of business fields (price_unit, quantity, ...)

After reviewing the UI code, it seems that, to update the 'quantity' on an account.move.line entry, you must :

1/ retrieve and edit the aml
2/ manually call on an onchange for the aml, building an onchangespec which is not coherent with the onchangespec returned to the UI (somehow fields_get on the model doesn't return the "on_change" tag, for instance)
3/ manually call an onchange on the related account.move (idem for the onchangespec)
4/ process the onchange return
5/ only then, write the account.move

Expected behavior:

This looks like a regression in "usability", or a mistake in the way I'm trying to interact with the model.

Expected behaviour would be to restore the default 'onchange' activation when writing a field on an aml, triggering account.move tax_line recalculation.

**Comment by pedrobaeza** [comment]
Onchange are not callable via XML-RPC while the onchange methods are prefixed with `_` in the method name, so that's not something new. Can you specify more?

**Comment by a-willem** [comment]
Hi @pedrobaeza, 

I proceeded with the XMLRPC API "just as" the GUI is behaving, here is a a trace of the XHR calls made by UI (see screenshot).

However, this does look quite complicated and I'd be *really* happy if you told me this isn't the proper way to proceed :) 

![image](https://user-images.githubusercontent.com/31848075/83004774-5b4e4b00-a010-11ea-890a-00a4a47829e2.png)

**Comment by a-willem** [comment]
Just for the record, up until v12, a simple call to `account.invoice.line, "write"` with `{'quantity': 42}` was enough to trigger all onchanges and updates to the receivables line and tax lines.

**Comment by pedrobaeza** [comment]
> Just for the record, up until v12, a simple call to account.invoice.line, "write" with {'quantity': 42} was enough to trigger all onchanges and updates to the receivables line and tax lines.

That's not really true. There's specific code in the `write` method that performs what you say.

I'm afraid you have to dig here how to do it, as this is an undocumented way of doing things. In v14, where computed writeable fields will replace all the onchanges, this won't be needed anymore, but until then, you have to investigate how to do it.

I let @Yenthe666 to decide if closing this, but this is custom development questions IMO.

**Comment by a-willem** [comment]
Indeed, you are right, the account.invoice.line write did all the heavy work, but leaving API users with a "nice and clean" way to updated invoices.

Is there a clean and documented way to proceed ? I'm more than happy to go the right path.

**Comment by pedrobaeza** [comment]
As said, there's no explicit documentation for "how to create invoices via XML-RPC and replicating UI experience with onchanges", but the general one, and you have to investigate how to do it. In v14 everything will be easier and one of the biggest flaws of the framework with the duality of behavior with onchanges will be removed (in core addons). Now in v13 the feature exists but the core code still uses onchanges.

Closing as no issue, but custom XML-RPC development stuff.

**Comment by Yenthe666** [comment]
Yeah it's custom stuff to figure out, I agree. 
What do you mean with this by the way? Maybe I've missed something lately:

>  In v14 everything will be easier and one of the biggest flaws of the framework with the duality of behavior with onchanges will be removed (in core addons)

**Comment by pedrobaeza** [comment]
Computed writeable fields will replace all the onchanges and you will get consistent behavior between code and UI, as no manual onchange triggering will be needed.

**Comment by a-willem** [comment]
Just a quick note to thank both of you for the time spent. I finally managed to get something working properly.
Hopefully v14 computed writable fields will make it easier on the RPC side :)

**Comment by Yenthe666** [comment]
Ahh right! Yeah they will simplify things quite a bit for RPC-operations :)

**Comment by pedrobaeza** [comment]
Not only for RPC operations, but your code also. Imagine creating an invoice programmatically in your custom module: it avoids to manually call onchanges (or use `onchange_helper`). FYI, on 12.0+ you have `odoo.tests.Form` to simulate the onchanges. Example of conversion of partial code against one taking into account all the onchanges automatically:

https://github.com/OCA/sale-workflow/commit/596aed2927d84c5c9ed7ce2f0e70808174bcd86c
