### ISSUE TITLE
[V8] Frozen dict error when called unlink method on account_move_line

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#5197]
Hi,

When I called unlink method in account_move_line I got the error that '**setitem**' not supported on frozen dict.

I sew the code in module account, file: account_move_line, in line 1154, there's a code that modify the context, and it modify directly not with copy the context first.

I think it must copy the context first then you modify the copy context.

Thank You.

**Comment by esperandus** [comment]
Confirmed - ran into the same issue. 
Fixing is simple, something like:

            unfrozen_context = context.copy()
            unfrozen_context['journal_id'] = line.journal_id.id
            unfrozen_context['period_id'] = line.period_id.id
            result = super(account_move_line, self).unlink(cr, uid, [line.id], context=unfrozen_context)

Works fine after doing that.
Blasted frozen dictionaries.
Not sure if this is current-version thing or not, I have one development server without the issue and a production server with the issue. They looked to be using the same version of the account module, but there might be some different dependencies.

**Comment by Yenthe666** [comment]
Hi @falinwa,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
