### ISSUE TITLE
missing system messages in capacity levelling

### ISSUE THREAD

**Issue by ccandito** [odoo/odoo#5201]
Dear Odoo,
I'm using the "work orders by resource" report for capacity leveling purposes.
Sometimes operation cannot be moved at all, that's after dispatching an operation manually, the system places back it at the initial date. In some cases this is right and the reason can be grasped easily (e.g. a second operation is placed before the first one), in other cases the reason is not so clear.
I'd suggest to implement some system messages to communicate errors in dispatching work orders.
Regards
claudio candito

**Comment by Yenthe666** [comment]
Hi @ccandito,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
