### ISSUE TITLE
Cannot uninstall 'psutil' for Install Odoo 13 on Ubuntu 18.04

### ISSUE THREAD

**Issue by rakibulinux** [odoo/odoo#52027]
Requirement already satisfied: attrs>=17.2.0 in /usr/lib/python3/dist-packages (from zeep==3.2.0->-r requirements.txt (line 41)) (17.4.0)
Collecting appdirs>=1.4.0
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting defusedxml>=0.4.1
  Using cached defusedxml-0.6.0-py2.py3-none-any.whl (23 kB)
Collecting isodate>=0.5.4
  Using cached isodate-0.6.0-py2.py3-none-any.whl (45 kB)
Collecting requests-toolbelt>=0.7.1
  Using cached requests_toolbelt-0.9.1-py2.py3-none-any.whl (54 kB)
Collecting python-stdnum
  Using cached python_stdnum-1.13-py2.py3-none-any.whl (839 kB)
Installing collected packages: psutil, psycopg2, pyparsing, pydot, python-ldap, python-dateutil, pyusb, qrcode, reportlab, cached-property, appdirs, defusedxml, isodate, requests-toolbelt, zeep, python-stdnum, vatnumber, vobject, Werkzeug, XlsxWriter, xlwt, xlrd
  Attempting uninstall: psutil
    Found existing installation: psutil 5.4.2
ERROR: Cannot uninstall 'psutil'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by UbuntuEvangelist** [comment]
Same here for Ubuntu

**Comment by pedrobaeza** [comment]
@KangOl is this then fixed by the linked PR?

**Comment by KangOl** [comment]
> @KangOl is this then fixed by the linked PR?

Not at all. I don't know why github think this PR is linked.

**Comment by KangOl** [comment]
Or I made a missclick.

**Comment by pedrobaeza** [comment]
OK, it was very weird indeed. The problem I see is a deployment thing and it's not on Odoo side. You have to check why pip returns that error. Ask on forums for possible support, but this is not something of Odoo itself, so closing.

**Comment by UbuntuEvangelist** [comment]
@pedrobaeza its a system bug for Python 3.7.7. Who try odoo using Python 3.7.7 with pip3 has same problem for Ubuntu 18.04 LTS and also for Ubuntu 20.04 LTS

**Comment by pedrobaeza** [comment]
You should stick to the minimum Python version indicated for avoiding problems, but any way, it's not an Odoo bug, but sysadmin stuff. Thanks for pointing to others the possible source of the problem.
