### ISSUE TITLE
SQL where clause problem

### ISSUE THREAD

**Issue by MeeleCode** [odoo/odoo#52024]
Version 13.0, stock module:
Is it possible to add the table name as prefix in the where clauses of _get_inventory_lines_values function in stock_inventory.py in stock module? It would be clearer to know which clause is referencing which table even though they don't exist in both tables. I'm testing products in multi companies and I have a problem when I add company_id as related field to product_product table because then it exists in both tables.

Original code is (lines 225-230):
###
    if self.company_id:
        domain += ' AND company_id = %s'
        args += (self.company_id.id,)
    if self.product_ids:
        domain += ' AND product_id in %s'
        args += (tuple(self.product_ids.ids),)

Could you change (add stock_quant prefix) it to:
###
    if self.company_id:
        domain += ' AND stock_quant.company_id = %s'
        args += (self.company_id.id,)
    if self.product_ids:
        domain += ' AND stock_quant.product_id in %s'
        args += (tuple(self.product_ids.ids),)

**Comment by pedrobaeza** [comment]
Has SQL come back??!! See #34387 and it's supposed that the SQL was removed in #34427.

**Comment by MeeleCode** [comment]
In current v13 it is SQL:
https://github.com/odoo/odoo/blob/19a9859985a4576943dad1312b1808c6c3690645/addons/stock/models/stock_inventory.py#L225

**Comment by pedrobaeza** [comment]
@sle-odoo did #34427 never reach master branch?

As you see, this problem is still happening. Would you please accept at least a fully qualified SQL?

**Comment by sle-odoo** [comment]
@pedrobaeza it did reach master but in another PR, see 68518afe33040ff6e000a15acd3a7080b2485e38

**Comment by pedrobaeza** [comment]
OK, I see, but for v14... Is there any chance we can fix this in stable versions through fully qualified SQLs?

**Comment by sle-odoo** [comment]
see this [comment](https://github.com/odoo/odoo/pull/34387#issuecomment-506222260)

**Comment by pedrobaeza** [comment]
Yeah but my reply is not something insane and it's affecting since 4 versions any extension adding a field with the same name: https://github.com/odoo/odoo/pull/34387#issuecomment-506292488

I beg you to reconsider.

**Comment by sle-odoo** [comment]
it's @nim-odoo you need to beg :-)

**Comment by MeeleCode** [comment]
Maybe it would help if I beg also? :)

**Comment by Yenthe666** [comment]
I'll add some begging in here too for @nim-odoo 😉

**Comment by MeeleCode** [comment]
Ok, @nim-odoo could you at least reconsider a fully qualified SQL as that is a minor change that could be added easily?

**Comment by nim-odoo** [comment]
![test](https://user-images.githubusercontent.com/11041725/83152502-2b7d7100-a0fe-11ea-901d-1b8d60e5da2f.png)

**Comment by pedrobaeza** [comment]
@nim-odoo do you have a bitcoin miner virus? :roll_eyes:

**Comment by nim-odoo** [comment]
> @nim-odoo do you have a bitcoin miner virus? roll_eyes

None that I am aware of, but that gives me an idea about a new Odoo module :thinking:

**Comment by pedrobaeza** [comment]
Hehe, OK, I asked as the qr code seems a `bitcoin` link. Anyway, I'm afraid others in the Apps Store had this idea some time ago and are mining bitcoins from unaware Odoo users :smiling_imp:

**Comment by Yenthe666** [comment]
😆 haha you guys.

**Comment by pedrobaeza** [comment]
Thank you very much for the fix!

**Comment by MeeleCode** [comment]
Great, thank you!
