### ISSUE TITLE
planning result report

### ISSUE THREAD

**Issue by ccandito** [odoo/odoo#5202]
Dear Odoo,
Results of planning run are immediately readable.
for example after deleting a quotation, the related procurement document is still alive, so it is not immediately clear why the system does not suggest another quotation.
A report listing for product code starting from the current stock all MRP elements (positive and negative, requirements) by date can be useful to support the planner in daily activity.
Regards
Claudio candito

**Comment by Yenthe666** [comment]
Hi @ccandito,

By default this wasn't really available in V8. You could export all data and do it yourself though.

Regards,
Yenthe
