### ISSUE TITLE
product costing feature

### ISSUE THREAD

**Issue by ccandito** [odoo/odoo#5207]
Dear Odoo,
I've found the module product_cost_incl_bom in V8.0.
Generally speaking, I've installed the module "Product extension to track sales and purchases" for calculating standard price in product master data.
unfortunately I'm not able to justify product costing calculation.
do a report exist detailing product costing structure?
Regards
claudio candito

**Comment by Yenthe666** [comment]
Hi @ccandito,

By default this wasn't really available in V8. You could export all data and do it yourself though.

Regards,
Yenthe
