### ISSUE TITLE
[12.0] Typo in view

### ISSUE THREAD

**Issue by BT-aestebanez** [odoo/odoo#52078]
Impacted versions: 12.0, 11.0, 10.0, 9.0

Steps to reproduce: https://github.com/odoo/odoo/blob/cdb072372bfaa3cdc85e7b6d79ad848e8d071e00/addons/hr_recruitment/views/hr_recruitment_views.xml#L396

Current behavior: it should be position, it's written positon

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
It has been fixed in V13 though :D

**Comment by BT-aestebanez** [comment]
Yes, XD
I think the whole view was deleted in V13... but it's funny nobody has realized since V9

**Comment by Yenthe666** [comment]
Haha you usually don't notice a missed field honestly.
Since it modifies a view it would require a module update before it is loaded anyways. It's no longer an issue in V13 either so maybe we shouldn't even touch it anymore.
@pedrobaeza what do you think?

**Comment by pedrobaeza** [comment]
I think it's good as it is, as it's not provoking any bug. If you want that filter in the view, you can add it through custom module/Odoo studio/direct modification in DB.

**Comment by Yenthe666** [comment]
Agreed. Let's close this one but thanks a lot for the report @BT-aestebanez :)

**Comment by BT-aestebanez** [comment]
You're welcome :)
