### ISSUE TITLE
One of the records you are trying to modify has already been deleted (Document type: Quants)

### ISSUE THREAD

**Issue by vulehd** [odoo/odoo#5208]
I have this error "One of the records you are trying to modify has already been deleted (Document type: Quants)" occurred when trying to Transfer a picking.

Here is the case:
- Product A in Location Z with quantity -1
- I try to move 1 Product A from Location X to Location Z
  => error occurred.

The error occurred on quants_unreserve() function. I think the quant has been reconciled (which delete the quant record) before it was unreserved which set reservation_id to False.

I suggest we should refresh move in quants_unreserve().

def quants_unreserve(self, cr, uid, move, context=None):
        move.refresh() #  should refresh here?
        related_quants = [x.id for x in move.reserved_quant_ids]

**Comment by Yenthe666** [comment]
Hi @vulehd,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
