### ISSUE TITLE
POS restaurant - can't print Bill

### ISSUE THREAD

**Issue by javierisc** [odoo/odoo#5211]
Hi,

I just installed odoo 8 with restaurant module. I can print an order on a pos printer (POSline) once it's been paid.

However, if I want to print the order before it's paid using "Bill" button, nothing happens.

Hope somebody has an idea how to solve it.

Best regards
This is the pic, when i click on Bill, nothing happens 
![screen shot 2015-02-10 at 5 53 30 pm](https://cloud.githubusercontent.com/assets/10949868/6139134/cf458e7c-b14d-11e4-9449-8bdf45a3b853.png)

This is what I get when I pay the order (I can print it)
![screen shot 2015-02-10 at 5 56 49 pm](https://cloud.githubusercontent.com/assets/10949868/6139185/5f0d0530-b14e-11e4-83c1-45b5057dac85.png)
![screen shot 2015-02-10 at 5 57 32 pm](https://cloud.githubusercontent.com/assets/10949868/6139188/65203d48-b14e-11e4-976e-552ea7800873.png)

**Comment by wtaferner** [comment]
@fvdsn :+1: experienced this lately too...did not dive into but might need it soon...

**Comment by mdo-odoo** [comment]
Hi,
Do you have a posbox connected in your local network ? 
Because the red icon notify you that the posbox is not connected.
Do you enabled the Receipt Printer option on the Point Of Sale configuration ? 
The Bill printing  option work with a posbox but not allow you to print bill with a classical printer.

Best regards

**Comment by javierisc** [comment]
Hi,  

Print bill is enabled at the point of sale configuration. 

I don't have a posbox, is it possible to print the bill using a POS printer directly connected to the openerp server?  The POS printer is currently working. 

Best regards

**Comment by mdo-odoo** [comment]
Yes, it's possible if the POS printer is compatible with Odoo (Epson TM-T20, Epson TM-T70, Epson TM-T20II). You need to follow the manual http://nightly.odoo.com/trunk/posbox/manual.pdf.

**Comment by javierisc** [comment]
Hi,
I'll try to configure the posbox as u suggest (no posbox hardware).

This is what I have in the POS Configuratiion. Don't see the "receipt printer" you mention,

![screen shot 2015-02-12 at 7 00 48 am](https://cloud.githubusercontent.com/assets/10949868/6167849/43a928b8-b285-11e4-8f1a-6a31f4433fa2.png)

![screen shot 2015-02-12 at 7 01 03 am](https://cloud.githubusercontent.com/assets/10949868/6167852/4f212f42-b285-11e4-8290-1a1c5b4c8f00.png)

![screen shot 2015-02-12 at 7 01 18 am](https://cloud.githubusercontent.com/assets/10949868/6167856/537716a6-b285-11e4-8cd0-84842aa12015.png)

**Comment by mdo-odoo** [comment]
You need to enable the option "Print via Proxy" and set the ip address to "localhost"

**Comment by javierisc** [comment]
Ok,

I enabled what u suggested. When I open the pos session, now the posbox is connected (doesn't appear the red icon on the top right), however, when I click the "Bill" botton still nothing happens, and now when I click "Cash" and make the payment I don't see the receipt that I was previously able to print.

I guess I have to configure the posboxless option you mentioned before. By the way, how do I know if I have a esc-pos printer driver in linux? Sorry I'm new to it, but doing my best.

![screen shot 2015-02-12 at 7 15 08 am](https://cloud.githubusercontent.com/assets/10949868/6168040/055598c4-b287-11e4-944b-dfabd3f4427b.png)

**Comment by mdo-odoo** [comment]
Several issues can appear. You need to look at your logs.

Maybe the server odoo dont have correct rights to access to drivers (as explained on the manual). 
Maybe a recent update can solve your problem too, try a git pull to be sure to have the lastest version.

You can try to install the correct version of pyusb via pip : 
sudo pip install pyusb==1.0.0b1

**Comment by javierisc** [comment]
Hi,

So far this is what I've done....

$ sudo pip install pyserial
$ sudo pip install --pre pyusb

Database Setup
Created a database called posbox with the modules hw_proxy, hw_escpos, and hw_scanner installed.
I succesfully installed hw_proxy and  hw_scanner, BUT CAN'T install hw_escpos

This is what I've got

![screen shot 2015-02-12 at 7 51 48 am](https://cloud.githubusercontent.com/assets/10949868/6168630/7d2b2a6c-b28c-11e4-8e89-ebe725c062e3.png)

I ran sudo pip install pyusb==1.0.0b1 as u suggested, but when I tried to install hw_escpos got the same error (as in the picture)

The only thing I didn't to (don't know how to do it) is "uninstall any esc-pos printer driver" cause I don't know how to do it.

Feels like I'm close..

**Comment by mdo-odoo** [comment]
So you have to install qrcode. 
You can try sudo pip install qrcode or sudo apt-get install python-qrcode

**Comment by javierisc** [comment]
Hi, I was able to install the missing module... now I'm having problems trying to start the server with the parameters for posbox.

I think the problem is I installed odoo 8 using the  instructions of ww.theopensourcerer.com ...

http://www.theopensourcerer.com/2014/09/how-to-install-openerp-odoo-8-on-ubuntu-server-14-04-lts/comment-page-2/#comment-567356

In order to start odoo, they created the following file:  sudo /etc/init.d/odoo-server start
And doesn't accept the parameters for posbox, just accepts "start" or "stop"

This is the content of the file.
#!/bin/sh

### BEGIN INIT INFO
# Provides:             odoo-server
# Required-Start:       $remote_fs $syslog
# Required-Stop:        $remote_fs $syslog
# Should-Start:         $network
# Should-Stop:          $network
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Complete Business Application software
# Description:          Odoo is a complete suite of business tools.
### END INIT INFO

PATH=/bin:/sbin:/usr/bin
DAEMON=/opt/odoo/openerp-server
NAME=odoo-server
DESC=odoo-server

# Specify the user name (Default: odoo).
USER=odoo

# Specify an alternate config file (Default: /etc/odoo-server.conf).
CONFIGFILE="/etc/odoo-server.conf"

# pidfile
PIDFILE=/var/run/$NAME.pid

# Additional options that are passed to the Daemon.
DAEMON_OPTS="-c $CONFIGFILE"

[ -x $DAEMON ] || exit 0
[ -f $CONFIGFILE ] || exit 0

checkpid() {
    [ -f $PIDFILE ] || return 1
    pid=`cat $PIDFILE`
    [ -d /proc/$pid ] && return 0
    return 1
}

case "${1}" in
        start)
                echo -n "Starting ${DESC}: "

                start-stop-daemon --start --quiet --pidfile ${PIDFILE} \
                        --chuid ${USER} --background --make-pidfile \
                        --exec ${DAEMON} -- ${DAEMON_OPTS}

                echo "${NAME}."
                ;;

        stop)
                echo -n "Stopping ${DESC}: "

                start-stop-daemon --stop --quiet --pidfile ${PIDFILE} \
                        --oknodo

                echo "${NAME}."
                ;;

        restart|force-reload)
                echo -n "Restarting ${DESC}: "

                start-stop-daemon --stop --quiet --pidfile ${PIDFILE} \
                        --oknodo
      
                sleep 1

                start-stop-daemon --start --quiet --pidfile ${PIDFILE} \
                        --chuid ${USER} --background --make-pidfile \
                        --exec ${DAEMON} -- ${DAEMON_OPTS}

                echo "${NAME}."
                ;;

        *)
                N=/etc/init.d/${NAME}
                echo "Usage: ${NAME} {start|stop|restart|force-reload}" >&2
                exit 1
                ;;
esac

exit 0

**Comment by mdo-odoo** [comment]
I cant help you with this procedure. 
Please follow instructions on the 'github.com/odoo/odoo' readme and after follow instructions from the posbox manual.

**Comment by javierisc** [comment]
Ok, thanks.

**Comment by libukoshy** [comment]
need to require POS box for printing receipt ? print the order before it's paid using "Bill" button,

**Comment by robpaz** [comment]
AFAIK, Odoo8 has not printing billing through posbox.

Billing just generates a QWEB report.

You need a custom solution for this.

**Comment by igallart** [comment]
Hello, I'm confused with print ticket without paid. ¿Is possible print bill in pdf (same with paid) with bill button from pos_restaurant?
Now nothing happens in odoo v8.

**Comment by Yenthe666** [comment]
Hi @javierisc,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
