### ISSUE TITLE
python3.8 with odoo12

### ISSUE THREAD

**Issue by dunxiangyu** [odoo/odoo#52119]
Impacted versions:odoo12

Steps to reproduce:
When using Python 3.8 to run odoo12, the database is created and an error is reported when entering the login page
Current behavior:

Expected behavior:

Video/Screenshot link (optional):

Error when compiling AST
TypeError: required field "posonlyargs" missing from arguments
Template: 173
Path: /templates/t/t/form/input[2]
Node: <input type="hidden" name="redirect" t-att-value="redirect"/>

**Comment by pedrobaeza** [comment]
Odoo is not compatible with that Python version. Please stick to the one indicated in the installation instructions, so closing this issue as invalid.

Anyway, FYI there are efforts inside Odoo team for compatibilizing Odoo with latest Python version, but that's usually for master version.
