### ISSUE TITLE
Wrong Identation in misc.py

### ISSUE THREAD

**Issue by pablocm83** [odoo/odoo#52127]
Impacted versions: 12.0

Steps to reproduce: create new database

Current behavior: problems to run

Expected behavior: database created
![Screenshot from 2020-05-28 12-28-32](https://user-images.githubusercontent.com/28315068/83168080-f7df1e80-a0de-11ea-80e6-b550f6cb9602.png)

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/13.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).
