### ISSUE TITLE
@api.constrains taking old value from db, not from view

### ISSUE THREAD

**Issue by Mitschmaster** [odoo/odoo#52137]
Impacted versions:
Odoo 13
Steps to reproduce:
constrains on a computed value which has a inverse function/has an onchange
Current behavior:
constrains is firing. when logging values i can see that it takes the old value which was in the database. but in the ui all values are ok.
Expected behavior:
constrains should take values as they are in the view.
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
That's something expected, as inverse are not executed until the end for several reasons. You must change your constraint to use another field than that. Or you can try with the new computed stored with readonly=False feature.

Closing as no bug, but current limitation of the framework.
