### ISSUE TITLE
New API and store=False, field is saved anyway on the DB

### ISSUE THREAD

**Issue by LeartS** [odoo/odoo#5216]
I wrote a module to store the smtp_pass in the DB encrypted.
I inherited `ir.mail_server` and 
- changed the field smtp_pass adding the parameters `compute='_get_pass', inverse='_set_pass', store=False`
- added 2 new fields: `smtp_pass_encrypted` and `smtp_pass_iv`
#### Results:

Go to outgoing mail servers, add/edit one with a new password. `smtp_pass_encrypted` and `smtp_pass_iv` are both saved correctly, but `smtp_pass` is also saved in plaintext in the DB, which defeats the purpose of the module. I need to be 100% sure the smtp_pass field is never stored in the DB.

Also, when saving the password, when the `_set_pass` method is executed, as soon as I assign `self.smtp_pass_encrypted = ...` the `_get_pass` method is called immediately, even before the assignment of `self.smtp_pass_iv` on the next line, which is why I had to add the 2 checks to `_get_pass`. Is that intended?

Here is the code:

``` python
KEY = 'f\x7f|cjbe}apkdivr\x82nf{qk_}gu\x80b~i'

import base64
from Crypto import Random
from Crypto.Cipher import AES

from openerp import models, fields, api


class ir_mail_server(models.Model):
    _inherit = 'ir.mail_server'

    def init(self, cr):
        update_query = """
        UPDATE ir_mail_server
        SET smtp_pass='', smtp_pass_encrypted=%s, smtp_pass_iv=%s
        WHERE id=%s
        """
        cr.execute("SELECT id, smtp_pass FROM ir_mail_server"
                   " WHERE smtp_pass IS NOT NULL"
                   " AND smtp_pass != ''")
        for mail_server_id, pwd in cr.fetchall():
            encrypted, iv = map(base64.b64encode, self._encrypt_password(pwd))
            cr.execute(update_query, (encrypted, iv, mail_server_id))

    smtp_pass = fields.Char(compute='_get_pass', inverse='_set_pass',
                            store=False)
    smtp_pass_encrypted = fields.Char(string='Encrypted password',
                                      invisible=True)
    smtp_pass_iv = fields.Char(string='IV', invisible=True)


    @api.one
    @api.depends('smtp_pass_encrypted', 'smtp_pass_iv')
    def _get_pass(self):
        if not self.smtp_pass_encrypted or not self.smtp_pass_iv:
            self.smtp_pass = False
            return
        iv = base64.b64decode(self.smtp_pass_iv)
        cryptor = AES.new(KEY, AES.MODE_CFB, IV=iv)
        self.smtp_pass = cryptor.decrypt(
            base64.b64decode(self.smtp_pass_encrypted)
        )

    @api.one
    def _set_pass(self):
        crypted, iv = self._encrypt_password(self.smtp_pass)
        self.smtp_pass_encrypted = base64.b64encode(crypted)
        self.smtp_pass_iv = base64.b64encode(iv)

    def _encrypt_password(self, password):
        """Returns (encrypted_password, iv)"""
        iv = Random.new().read(16)
        cryptor = AES.new(KEY, AES.MODE_CFB, IV=iv)
        return (cryptor.encrypt(password), iv)
```

**Comment by Yenthe666** [comment]
Hi @LeartS,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
