### ISSUE TITLE
[odoo9]install problem,odoo-9.0rc20190424-1.noarch: [Errno 256] No more mirrors to try

### ISSUE THREAD

**Issue by akira32chen** [odoo/odoo#52184]
I want to install odoo 9 in centos 7, but I meet a problem during installation.(a rpm not found)
http://nightly.odoo.com/9.0/nightly/rpm/odoo_9.0c.20190424.noarch.rpm: [Errno 14] HTTP Error 404 - Not Found

Does somebody know how to solve this problem?

$ sudo yum-config-manager --add-repo=https://nightly.odoo.com/9.0/nightly/rpm/odoo.repo
Loaded plugins: fastestmirror, langpacks
adding repo from: https://nightly.odoo.com/9.0/nightly/rpm/odoo.repo
grabbing file https://nightly.odoo.com/9.0/nightly/rpm/odoo.repo to /etc/yum.repos.d/odoo.repo
repo saved to /etc/yum.repos.d/odoo.repo
$ sudo yum install odoo

Downloading packages:
odoo_9.0c.20190424.noarch.rpm  FAILED                                          
http://nightly.odoo.com/9.0/nightly/rpm/odoo_9.0c.20190424.noarch.rpm: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below wiki article 

https://wiki.centos.org/yum-errors

If above article doesn't help to resolve this issue please use https://bugs.centos.org/.

Error downloading packages:
  odoo-9.0rc20190424-1.noarch: [Errno 256] No more mirrors to try.

**Comment by pedrobaeza** [comment]
Sorry, this issue tracker is for notifying problems in Odoo source code, not on the deployment methods. And even more, that version is out from official support since a lot.

Try to ask your question in Odoo forums.

Closing as no Odoo issue.
