### ISSUE TITLE
[survey] "Previous" button blocked due to required fields

### ISSUE THREAD

**Issue by nimeshcontractor** [odoo/odoo#5220]
Open a survey "User Feedback Form",
Click on test survey,
Fill the first page fileds and click on "Next" button.
Now, from the second page click on "Prevoius" button.

Here it will not allow to go on previous page, unitll you fill the required fileds of Second page.

![survey](https://cloud.githubusercontent.com/assets/7592468/6145139/929727c6-b204-11e4-9a99-27bbc0d488ea.png)

It should allow user to go back without filling the required fields.

Thanks,
Nimesh Contractor.

**Comment by rim-odoo** [comment]
"Previous page" button is designed to work in that way, so it is not a bug.
It is an implementation choice that can be discussed, of course :) (that should not be hard to change in a custom installation anyway)
