### ISSUE TITLE
lp:1317529 Manual reconcile is not multi-company aware

### ISSUE THREAD

**Issue by laetitia-gangloff** [odoo/odoo#5221]
Environement: V7

Stéphane Bidoul (Acsone) (sbi) wrote on 2014-05-08:

How to reproduce
- create two companies A and B
- create a partner P with no company_id
- create a non admin user U and sets its preferences to company A
- from now on, use user U, not admin
- create invoices and unreconciled payments for partner P on company A
- go to Manual Reconcile and view entries to reconcile for partner P
- now change the user preference to company B
- go to Manual Reconcile and view entries to reconcile: the partner P is proposed in the list of partners to reconcile but no entries are visible

Other problem is with last_reconciliation_date that is not multi-company.

This is due to the query in list_partners_to_reconcile() in account/account_move_line.py which is not multi-company aware.

And one more problem, is that last_reconciliation_date is set even if not all move are reconciled.

**Comment by laetitia-gangloff** [comment]
OPW : 632095

**Comment by mart-e** [comment]
Hello,

This was fixed at 884864c40fd6faa242a4bde3f055d0be59a9da12.
Thanks
