### ISSUE TITLE
10n_in: Indian GST: Fiscal Position in Multi GSTIN using Journal

### ISSUE THREAD

**Issue by kunalgoel1** [odoo/odoo#52210]
Please note that the current way of Fiscal Position doesn't apply with multiple GSTIN option. As Fiscal Position is defined based on the company and not based on the warehouse address / Journal GSTIN state. So when you use the Inter-State Fiscal Position, you cant add a filter for which warehouses or journals it should be used. It is important that the system should identify which tax to apply GST (CGST+SGST) or IGST based on the "Place of Supply".

So now, what needs to be corrected is that for Indian Companies, Inter-State fiscal position should be applied when Warehouse state / Journal GSTIN state is different from the Place of Supply. Please fix this.

**Comment by pedrobaeza** [comment]
@jco-odoo who is the suitable for this issue?

**Comment by jco-odoo** [comment]
@jva-odoo

**Comment by jva-odoo** [comment]
@kunalgoel1 Right now Fiscal Position is working on the company state and country so we need to do something hack on it. And it's not a good option so we don't do it right now.
but in the future we do it.

Thank you

**Comment by kunalgoel1** [comment]
@jva-odoo 

I would suggest that this should be fixed asap as it is a very basic requirement for all businesses in India and related to Tax compliance so it would be a problem it any mistakes are there in the GST Tax Returns filings.

You just need to add an extra Address field in the Fiscal Position Form visible to Indian companies, so that all addresses with the same GSTIN/State can be tagged in the field. So all operations from these addresses can apply the particular Fiscal Position.
![Screenshot 2020-06-01 at 10 27 59 AM](https://user-images.githubusercontent.com/16508765/83378445-59143400-a3f6-11ea-914c-ff63c148a540.png)

**Comment by jva-odoo** [comment]
@kunalgoel1 It is not a good option because we have a country state in Fiscal Position.
So Just wait I will discuss this with @jco-odoo

**Comment by kunalgoel1** [comment]
@jva-odoo Hope you have discussed the issue with @jco-odoo 
Please update on any new developments on this issue. Thanks.

**Comment by jva-odoo** [comment]
Ok, I will update you.

**Comment by kunalgoel1** [comment]
@jva-odoo Any progress??

**Comment by jva-odoo** [comment]
@kunalgoel1 Yes, you can check this https://youtu.be/4uPzin77oio

**Comment by kunalgoel1** [comment]
@jva-odoo Great to know that. I will test it today. Thanks.

**Comment by jva-odoo** [comment]
@kunalgoel1 this is under development so you can't test it in master or v13.

**Comment by jva-odoo** [comment]
You can test here https://3041537-51990-d3092b.runbot44.odoo.com/web
with database `3041537-51990-d3092b-jva`
Previously given video is link is updated so check it again.

Thank you

**Comment by kunalgoel1** [comment]
@jva-odoo 
Updated video looks pretty good. However, the link doesn't seem to work. Can you share the correct link for me to test?
Thanks

**Comment by jva-odoo** [comment]
@kunalgoel1 check this https://youtu.be/gFhBW-oGYIw

**Comment by kunalgoel1** [comment]
The functionality works perfectly well.

Also, I think that in the GSTIN units the Indian company unit should be created by default. And then further additional GSTIN units can be created. In the Fiscal Positions and Journals settings, filter (domain) for GSTIN units should be applied instead of showing all contacts. Also if you can share the database link then I can test and provide more feedback. Thanks.

**Comment by jva-odoo** [comment]
@kunalgoel1 No it's not merged yet. @jco-odoo review is pending.
Thank you

**Comment by kunalgoel1** [comment]
@jva-odoo Thanks for your contribution. 

@jco-odoo Request you to please expedite the review on priority and arrange to merge the changes. Thanks.

**Comment by jco-odoo** [comment]
@kunalgoel1 We will discuss this as soon as possible, but we need some time to correctly evaluate this functionality.

**Comment by kunalgoel1** [comment]
@jco-odoo Thanks for your kind consideration.

**Comment by kunalgoel1** [comment]
Hello @jco-odoo 
Sorry for bothering you again. But can we get a timeframe when this can be done ?? Thanks

**Comment by kunalgoel1** [comment]
@jva-odoo 
Just noticed another issue with the GSTIN. So for the reports like sales order, proforma invoice, purchase order, etc. The system is printing res.company GSTIN instead of the GSTIN based on journal. Have you corrected this too?

**Comment by kunalgoel1** [comment]
@jco-odoo @pedrobaeza @jva-odoo @xrg 
**When are you planning to update the changes on Odoo master**

**Comment by kunalgoel1** [comment]
@jva-odoo 
Any update ?

**Comment by jva-odoo** [comment]
@kunalgoel1 We decided to use multi-company instead of this.

**Comment by jva-odoo** [comment]
@pedrobaeza plz close this issue. because right now we decided to must use multi-company in case of multi GSTIN(vat).

**Comment by kunalgoel1** [comment]
@pedrobaeza @jva-odoo @jco-odoo @xrg 

Time to reopen this Issue since V15 suggest multi VAT.

**Comment by jva-odoo** [comment]
@kuldeep-joshi this is use full if you have Tax in another country. and tax report have different formate.
So this is not applicable in this case.

**Comment by kunalgoel1** [comment]
> @kunalgoel1 we think about it but it's too complex to configure because it's designed for different formate reports not for the same formate report. so we do not use this.

@jva-odoo Thanks.

We could use the model to configure according to indian GST standards since it does have the option of choosing the VAT/Unit in Fiscal Positions, Journal configurations, etc. And the GST reporting is same, it just need to be filtered based on the GSTIN (VAT).

Would be waiting for your revert on the same.

**Comment by kunalgoel1** [comment]
@jva-odoo 
Any Progress ?

**Comment by jva-odoo** [comment]
@kunalgoel1 we are not doing anything in this becosue we must create company if there is different GSTIN

**Comment by jco-odoo** [comment]
@MihranThalhath The goal is to do everything in multi-company.  Could you indicate why you see it as impractical that way?

**Comment by kkumawat25** [comment]
@jco-odoo @jva-odoo @kunalgoel1 
is this feature implemented in odoo 15 or do you still recommend using multi-company ? what are some known issues if do not use multi-company ?

**Comment by jva-odoo** [comment]
@kkumawat25 
Yes, we still recommend using multi-company.
if you don't use multi-company, standard E-invoice, E-waybill and GST E-filing is not work as expected.
and we recommended this because as per GST if you have a different GST number then you are a different entity not the same.

And this is one of the thumb rules to implication odoo in India.

And we have solutions for one bank account for multiple GST numbers.
connect us using the Odoo [support](https://www.odoo.com/help) with ticking type **A question in the use or the configuration of Odoo**

**Comment by planetodooofficial** [comment]
@jva-odoo , We really appreciate the efforts of Odoo India team has put in to implement GST / E-Invoicing / Eway Bill services module. However, I agree with @kkumawat25 and reading the thread from it started. 

The module work for small companies who operating with 2-3 GSTIN units and multi-company can work with Account consolidation module.

We have projects where companies have more than 20 GSTIN units and it really difficult to switch the companies and interbranch payments of the Invoices / Bills created within the GSTIN units.

We need to extend the module (VAT Unit) module which is already developed for outside India Localization and I see VAT unit option in the GSTR report as filter and GST Return Period.

Currently, we are not able to add Multiple VAT units in single company. 

Ultimately, we just need Filter of VAT Unit (Branches) at the Company Level B&S and P&L . SAP B1 and Tally Branch concept works as per the India GST LAWs perfectly. Request Odoo team to look into the functionality in SAP B1 ( Multi Branch ) to extend the Implementation.

Looking forward !



![Screenshot 2023-06-09 at 10 39 38 PM](https://github.com/odoo/odoo/assets/33413047/b257e6da-c2b5-4e34-b7fc-7c663af9d43d)
![Screenshot 2023-06-09 at 10 39 32 PM](https://github.com/odoo/odoo/assets/33413047/dbc7abbc-5a84-4da6-8268-3b1022521e3f)

**Comment by kkumawat25** [comment]
@planetodooofficial completely agree with you. It becomes more complete when you start with one GST and get a new GST after some time. If you do not want to give access to users of the new company, then they cannot see account receivables and payables, partner ledger of existing customers shifted to new GST.

**Comment by kkumawat25** [comment]
> @MihranThalhath The goal is to do everything in multi-company. Could you indicate why you see it as impractical that way?
@planetodooofficial @jva-odoo 
If there are 3/4 independent business verticals within a company, then we need to create 3/4 companies due to completely different business verticals. Now for each new  GST, we need to create 1*3/4 companies so the number of companies grows exponentially with the addition of new GSTs. A Data entry person with limited knowledge of Odoo and company business will have a higher probability of mistaking mistakes in selecting companies when creating bill/invoice/PO/SO if we give them access to multiple companies. If we only give access to one company, then she/he can not see vendors/customers payable/receivable and partner ledger across companies.

**Comment by kkumawat25** [comment]
> @jva-odoo Just noticed another issue with the GSTIN. So for the reports like sales order, proforma invoice, purchase order, etc. The system is printing res.company GSTIN instead of the GSTIN based on journal. Have you corrected this too?

Found any solution in Odoo 15 ?

**Comment by kunalgoel1** [comment]
@jva-odoo @pedrobaeza @fpodoo 

I really don’t know why is team Odoo so reluctant to make this change which will make life so much easier for so many of us.

I am already running multi-gstin in single company while also using Odoo e-invoicing and Odoo E-way bill service after getting some custom development done. If we are able to run it without any issues, I am sure Odoo can also make it.

Don’t know why there is reluctance from Odoo to solve this issue.

I would appreciate if it could be a default feature in Odoo Standard.

**Comment by planetodooofficial** [comment]
@kunalgoel1 , We have already implemented Multi-GSTIN with some customization in Journals , Fiscal Position . However, Stock and Payments in Balance sheet cannot be extracted for each GSTIN unit as Stock Journal Entry is done at company level. Also, there is concept of HO Payment as wee cannot make the Bills / Invoices as Paid from single Bank account.

Odoo India team needs to seriously take this feedback in positive way as there's lot of potential if this gets fixed in any upcoming version.

@jva-odoo , Please add your comments on If multi company is implemented for each GSTIN unit, Will you duplicate the Bank account in all the companies to receive and transfer the payment ? Bank Reconciliation will be duplicated and incomplete as transaction would be split in each company.

**Comment by kunalgoel1** [comment]
@planetodooofficial 

We have got the whole solution from our Odoo Partner, Emipro Technologies. 

Also, I agree with you that Odoo can partner with it Partners in India like @planetodooofficial and Emipro to fix this in Single Company.
