### ISSUE TITLE
Why i can't restore my Large Odoo Database

### ISSUE THREAD

**Issue by rakibulinux** [odoo/odoo#52215]
I tried much time to restore my 1.3 GB size Database from web panel and command line but every time I get fails. Please help me to restore the database. Please watch my problem video you will understand more: https://youtu.be/4WbrtoWZQus

http://myip:8069/web/database/manager

I also try this: curl -F 'master_pwd=masterpassword' -F backup_file=@/root/mydb.dump -F 'copy=true' -F 'name=test' http://myap:8069/web/database/restore

It's shown me this: curl: (7) Failed to connect to myip port 8069: Connection timed out

**Comment by pedrobaeza** [comment]
This is a deployment issue (probably memory or time limit in your configuration), but not an Odoo problem.

Please ask in forums about this kind of problem.

Closing as no Odoo issue, but configuration one.
