### ISSUE TITLE
Unique attribute values on product_template is not present in product_product.attribute_value_ids

### ISSUE THREAD

**Issue by n1b0r** [odoo/odoo#5225]
**Setting a unique attribute value on a product template model do not update product variant attribute_value_ids**

Impacted versions:
- 8.0

Steps to reproduce:
1. create a new database with demo data
2. check the template "Ipad Retina Display" (3 attribute lines; Color: White, Black; Memory:16, 32; Wifi:2.4)
3. on product variants list, the Wifi 2.4 value is not present in the attributes column.

Current behavior:
- Wifi 2.4 attribute value is not present in any product variants

Expected behavior:
- Wifi 2.4 attribute value should be **present** in **all** product variants

**Comment by Yenthe666** [comment]
Hi @n1b0r,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
