### ISSUE TITLE
When using Arabic language dropdown inputs are not displayed correctly 

### ISSUE THREAD

**Issue by obayit** [odoo/odoo#52289]
Impacted versions:
13.0
Steps to reproduce:
1. Activate Arabic language (either `ar`, or `ar_SY`)
2. Change user's language to Arabic
3. Open any form with a dropdown, like preferences form.
4. The text of dropdown inputs (when containing Arabic text) is cut.

Current behavior:
Dropdown inputs are not displayed correctly when its value contains Arabic:
![screenshot-localhost_8013-2020 06 02-19_48_23](https://user-images.githubusercontent.com/20386024/83553588-b2ba5280-a50b-11ea-867f-ec1b35633281.png)
The input box shows half of the words

Expected behavior:
The selection field should show all the Arabic text correctly.

Demo on runbot:
I tried it on the last runbot build [here](https://2908087-13-0-43aeb9.runbot39.odoo.com/web?debug=1#action=129&active_id=mailbox_inbox&cids=1&menu_id=99).
username: `arabic`
password: `arabicarabic`

**Comment by pedrobaeza** [comment]
@mart-e can you take a look?

**Comment by mart-e** [comment]
@obayit I tested on both community and enterprise and it worked fine.
![Screenshot_2020-06-04 Mitchell Admin - Odoo](https://user-images.githubusercontent.com/564822/83737812-cec90b80-a653-11ea-8965-74f1b89b5622.png)

What browser are you using?

**Comment by obayit** [comment]
I am using Chromium Version 81.0.4044.122 (Official Build) on Ubuntu 18.04
(64-bit)

**Comment by mart-e** [comment]
Indeed, it looks like there is a difference in chromium, community edition, in edit mode.
This is a CSS issue, I am not sure what makes the rendering different between browsers or in the enterprise version by the way. Sorry I can't help you more.
