### ISSUE TITLE
[13.0] account: cound not set Zero tax on manually

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#52286]
Impacted versions: 13.0

Steps to reproduce: Change tax on Vendor bill and set it to Zero
![screenshot-2902423-13-0-30be09 runbot48 odoo com-2020 06 02-23_05_17](https://user-images.githubusercontent.com/16624719/83551170-9deab880-a525-11ea-9ed3-1cba4500ecd4.png)

Current behavior: Its unchanged (Becomes 4 again) , Looks like its not sending data to server from widget

Expected behavior: Able to make it Zero

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Does it only happen with 0 or with any other amount?

**Comment by sswapnesh** [comment]
Only 0
(Maybe this can be handled along with https://github.com/odoo/odoo/issues/51737)

**Comment by pedrobaeza** [comment]
I don't think this is an error, as the tax amount is supposed to be non 0, and you edit it for correcting it, not for nullifying it. If you want 0 tax, remove taxes.

@Yenthe666 I call you for deciding to close this or not depending on your judge.

**Comment by sswapnesh** [comment]
Zero tax is also _Tax_.

> If you want 0 tax, remove taxes.

That's not solution IMO, As at many places (Eg, India) Zero tax is mandatory to record. 

I thinks its the issue with widget which is not considering null value.

**Comment by pedrobaeza** [comment]
One thing is to add a zero tax, which is legit and we have it here in Spain. Other thing is to pretend to nullify an existing tax that is not zero percentage, which is what you are doing here.

**Comment by Yenthe666** [comment]
Mhmm, it feels a bit like misuse to me. You should indeed set a tax of 0% which then results in 0.0 at the bottom. I agree with @pedrobaeza
