### ISSUE TITLE
Customer Returns causing ever increasing Asset/Liability account growth - real-time Stock valuation

### ISSUE THREAD

**Issue by sam-ecomdev** [odoo/odoo#523]
When selling physical products and using real-time Stock valuation the following is what happens when you process a customer return: 

* You receive goods back to your warehouse by returning them from a 'Delivery Order'. 
* You receive the goods and the system debits 'Stock Valuation' and credits '**Stock Output**' in the Stock Journal.
* You create/confirm the Customer Refund it the system creates a journal entry that debits '**Stock Input**' and credits the 'Debtors Control Account' in the Sales Refund Journal.

This makes no sense. The value of the customer refund movement should cancel out the value of the stock movement so they should both do movements in the 'Stock Input' account.

At the moment the more customer returns you process the more your Stock Output and Stock Input accounts will increase.  The Stock Input is an asset and the Stock Output is a liability so the values do cancel each other out, but if I trade for a number of years my Current Assets and Current Liabilities are going to be huge (for no reason).

Why does the 'Stock Journal' put a movement in one account and the 'Customer Refund' put a movement in the other?.  

I've been through the code and I can easily see why this happens:

in stock/stock.py (at line 2362 in the latest verison of v7) you will see this:

    journal_id, acc_src, acc_dest, acc_valuation =     self._get_accounting_data_for_valuation(cr, uid, move, dest_company_ctx)
    reference_amount, reference_currency_id = self._get_reference_accounting_values_for_valuation(cr, uid, move, src_company_ctx)
    #goods return from customer
          if move.location_id.usage == 'customer':
               account_moves += [(journal_id, self._create_account_move_line(cr, uid, move, acc_dest, acc_valuation, reference_amount, reference_currency_id, context))]
         else:
               account_moves += [(journal_id, self._create_account_move_line(cr, uid, move, acc_src, acc_valuation, reference_amount, reference_currency_id, context))]

 
What is the above conditional all about?  Any incoming stock (either from supplier or a customer) should be logged in the 'Stock Input' account.  Why does the above conditional switch the acc_dest with the acc_src and mess everything up?

Here is a balance sheet from my system after processing 1 single "sale/deliver/invoice/payment" process and 1 single "return/incoming shipment/customer refund/payment" process.

![screen shot 2014-06-13 at 13 42 40](https://cloud.githubusercontent.com/assets/3686837/3269968/7748bf28-f2f8-11e3-9d69-6826477fe0d0.png)

It is the return process that has created these two values of 84.00 GBP

If I remove the above conditional from the code and repeat the above sale/return process my balance sheet is completely zero which is what I would expect from selling something and taking it back for a full refund.

I think this is a bug.  These balance sheet accounts shouldn't grow and grow and grow in this manner.

**Comment by komsas** [comment]
@sam-ecomdev I suggest to close this issue because it's fixed (issue was with anglo saxon) https://github.com/odoo/odoo/commit/3a50d4b35b67743122899a3a525c93bcdab23f80

**Comment by sam-ecomdev** [comment]
Closing this issue because it's fixed (issue was with anglo saxon) 3a50d4b

**Comment by sam-ecomdev** [comment]
Closing this issue because it's fixed (issue was with anglo saxon) 3a50d4b
