### ISSUE TITLE
[8.0] origin field (Source Document) is no fill when creating a Refund invoice 

### ISSUE THREAD

**Issue by hugho-ad** [odoo/odoo#5233]
Steps to reproduce
--------------------------

Connect to base instance of 8.0 on runbot
Go to Accounting
Duplicate invoice
Validate the duplicate invoice
Go to refund Invoice
Specify a reason
Create refund
go to tab other information
and the field, origin (Source document) is not full

https://docs.google.com/a/vauxoo.com/file/d/0B_jQX2tloXM7UWRjV3ZudFpQMG8/edit

Expected Results
-----------------------
the correct filling of origin field with the invoice number

**Comment by hbto** [comment]
This is the expected result

https://docs.google.com/a/vauxoo.com/file/d/0B1w9gokcJL9hdXhnUWFkeDJTNGc/edit?usp=drivesdk

**Comment by hugho-ad** [comment]
hi @dmichiels ,
The solution given is not enough, the solution proposed in 5415 pr by @hbto , is because it makes difference between the number of client and provider number.
In the given solution is placing the invoice number and in case of supplier invoices is an internal number, the number is more appropriate to use supplier_invoice_number, proposed in 5415 pr.

Please reopen the issue.

Regards!
