### ISSUE TITLE
error in product costing calculation

### ISSUE THREAD

**Issue by ccandito** [odoo/odoo#5234]
dear Odoo,
in calculating standard unit cost in product master data the "number of hours" in routing are not taken into account.
in calculating analytic entry the cost per hour in WC is multiplied per number of hours in MO.
the number of hours in MO is calculated based "number of hours" in routing.
Therefore there is a difference in how the system calculate the unit cost and how actual cost are posted in analytic account.
My suggestion is to consider "number of hours" in unit cost calculation also.
Regards
claudio candito

**Comment by Yenthe666** [comment]
Hi @ccandito,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
