### ISSUE TITLE
[11, 12, 13] Method View.unlink must return result from super

### ISSUE THREAD

**Issue by suvit** [odoo/odoo#52364]
Impacted versions: [11, 12, 13] (may be lower)

Method View.unlink (model ir.ui.view) must return result from super like every other def unlink
Current behavior: View.unlink always return None.

**Comment by pedrobaeza** [comment]
@Elkasitu you did the override in bca2926b013733162355879ec4190e327c1a966a. Can you please check?

**Comment by suvit** [comment]
Yes. last line `super(View, self).unlink()` must be `return super(View, self).unlink()`
We have a module that changed behavior for unlink for all models, but View model dont return result of super call

**Comment by Elkasitu** [comment]
Should be fixed with #52390, thanks for the report.

Funny that it only affected someone now since it's been broken for 2 years :laughing:
