### ISSUE TITLE
[12.0] payment: Form implementation does not allow for tokens to be used

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#52389]
#### Impacted versions:
12.0, 13.0
#### Steps to reproduce:
- Configure form implementation for a payment acquirer
- Create a Token on the provider page (as this is using redirection)
- Save the Token
- Make another purchase
- Use the Token
#### Current behavior:
When the token is selected the process is changed to s2s, and the token is not available on the custom method `*_form_generate_values` 
#### Expected behavior:
If a token is used on a provider using the form implementation, form methods should be used, instead of s2s methods which are not even implemented in code.

cc: @Feyensv @dbo-odoo @tbe-odoo

**Comment by dbo-odoo** [comment]
Which provider are we talking about here?

**Comment by gustavovalverde** [comment]
Hi @dbo-odoo I'm not sure if any of the actual providers has this type of implementation. We're working on Cybersource's Hosted Checkout implementation.

But the same principle applies to other providers, as we also have 2 others with the same requirement, which basically is sending the token in the HTTP Post.

But the payment token is not an information available in this method https://github.com/odoo/odoo/blob/9aca7c464cef492c495a0c72d870b7075187dc63/addons/payment/models/payment_acquirer.py#L345

**Comment by gustavovalverde** [comment]
@dbo-odoo let me know if the issue is clear enough.

**Comment by gustavovalverde** [comment]
Ping @dbo-odoo

**Comment by dbo-odoo** [comment]
Hi,

I've re-read your use case; I'm afraid there's little I can do here.

If the provider you're implementing does not follow the same flows as those we did (namely: once you work with a token, the transaction is done in s2s mode), then you're out of luck. I'm not gonna change the implementation in a stable release for that; you're gonna have to patch this yourself somehow :/
