### ISSUE TITLE
[Improvement] purchase_stock - link SO/PO SOL/POL as in sale_purchase

### ISSUE THREAD

**Issue by Rad0van** [odoo/odoo#52402]
Impacted versions: 13.0

Steps to reproduce: add Product that has MTO & Buy options checked and available quantity 0 into Sale Order and confirm the Sale Order.

Current behavior: PO and POL is created/updated in StockRule _run_buy method and origin of PO is updated. 

Expected behavior: Linking SO/SOL with PO/POL as is done for example in sale_purchase for Services that have "Purchase Automatically" checked. There is currently no way (at least I don't know of any) to easily see associated POs from SO. In sale_purchase there is Smart Buttoin provided for that (but currently disabled in 13.0 - see #51874). It would probably be best if both modules used the same mechanism. Currently the linking comes from sale_purchase extensions to SaleOrder and SaleOrderLine.

I would be willing to work on this but currently I cannot conceive how that could/should be done. Any help/hints are welcome.

**Comment by pedrobaeza** [comment]
Yeah, it's a good idea. I think it's not the first time it has been proposed, but no idea why it hasn't been yet added (maybe the absence of the glue module?), but now that we have `sale_purchase`, there's not excuse, hehe.

@sle-odoo @amoyaux @dbo-odoo please consider this.

**Comment by Rad0van** [comment]
> Yeah, it's a good idea. I think it's not the first time it has been proposed, but no idea why it hasn't been yet added (maybe the absence of the glue module?), but now that we have `sale_purchase`, there's not excuse, hehe.
> 
> @sle-odoo @amoyaux @dbo-odoo please consider this.

@pedrobaeza I'm so glad you replied - I was considering asking you privately about how to appraoch this. I would start working on this with my limited skills but I am bit lost here because in StockRule _run_buy the argument holds procurements and so far I haven't found a way to get the SO/SOL from them. Any idea?

**Comment by sle-odoo** [comment]
It is done in master.

Regards

**Comment by pedrobaeza** [comment]
Oh, great, Simon! @Rad0van you can check how it's done there for backporting the option.

**Comment by Rad0van** [comment]
> It is done in master.
> 
> Regards

@sle-odoo so great to hear that! Going to check out instantly. This is going to be for 14.0 so I have to backport it as @pedrobaeza suggests?

**Comment by Yenthe666** [comment]
@Rad0van yeah if you'd want it in V13 you'll need to backport.

**Comment by pedrobaeza** [comment]
Yes, master becomes next version, which in this case will be v14.

**Comment by sle-odoo** [comment]
If you want to backport, most of the job was done https://github.com/odoo/odoo/pull/43366 but i remember a few bug fixes landed later on.

**Comment by Rad0van** [comment]
@sle-odoo, @Yenthe666  looking over the code I cannot see any reference to Sale Order or Sale Order Line. Where does the linking happen?

**Comment by Rad0van** [comment]
@sle-odoo and @Yenthe666 I didn't find where the magic happens but it works! Thanx for your input. I will have more thorough look and will try to backport this to 13.0
