### ISSUE TITLE
Context not being updated (v8)

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#5240]
It seems context does not update if I do this:
```python
@api.one
def some_method(self):
    self.with_context(new_key='hello')
    print self.env.context
    #or
    print self._context
```

For example it outputs this:

```python
{'lang': 'en_US', 'search_disable_custom_filters': True, 'tz': 'Europe/Vilnius', 'uid': 1, 'active_model': 'sale.order', 'active_ids': [55], 'active_id': 55}
```

As you can see it outputs only standard keys in context like tz, uid active_model etc. But new key/value pair is just not there.

**P.S**
Taken from ```with_context``` method description:
```python
            # current context is {'key1': True}
            r2 = records.with_context({}, key2=True)
            # -> r2._context is {'key2': True}
            r2 = records.with_context(key2=True)
            # -> r2._context is {'key1': True, 'key2': True}
```
As you can see it does not behave like it should.

**Comment by rco-odoo** [comment]
@oerp-odoo `with_context` **does not change** the context of a given recordset, instead it returns an *equivalent* recordset with the modified context:

    other = self.with_context(key="hello")
    print self._context         % same context as before
    print other._context        % modified context

The context of a recordset is captured in its *environment*, and by design the context associated to an environment **cannot be modified**, otherwise it would introduce inconsistencies in the cache.

**Comment by oerp-odoo** [comment]
@rco-odoo Then how do you pass that context to another method? In ol api, you could directly pass context anywhere and deal with it. But now only fixed keys are passed all the time.

**Comment by rco-odoo** [comment]
@oerp-odoo the context is attached to the recordset. So, if you want to invoke a method with a specific context, make a recordset with that context and invoke the method on that one:

    # make your own context dictionary
    my_context = {...}
    # make a recordset like self, but such that recs._context == my_context
    recs = self.with_context(my_context)
    # invoke method on recs; this is just like passing my_context in the old API
    recs.method()
