### ISSUE TITLE
Odoo v11 financial reports 

### ISSUE THREAD

**Issue by E4O** [odoo/odoo#52420]
Impacted versions:
v11, v12

Steps to reproduce:
1. Open Accounting - Reporting - Profit and loss financial report.
2. Now we need to get the last financial (01.01.2019 - 31.12.2019) year overview where you can see the comparison in months and get a print out from ERP system. We need to present it to the auditor. There isn't a way to get a report, where in the columns would be:
* January 2019
* February 2019
* March 2019
* April 2019
* May 2019
* June 2019
* July 2019
* August 2019
* September 2019
* October 2019
* November 2019
* December 2019

Current behavior:
If I select 12 periods and "this month" or "last month" I will get a result like below but I need to get this exact view starting from January 2019 until December 2019.
![image](https://user-images.githubusercontent.com/40301417/83747884-fc20b400-a669-11ea-86dd-8c9a5dbd5fce.png)

Expected behavior:
We need to get a view in Odoo that will show information like here in my Excel:
![image](https://user-images.githubusercontent.com/40301417/83747962-1e1a3680-a66a-11ea-8f0a-62f851aa90ef.png)

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Sorry, this is not an issue, but an specific layout request that is not going to get satisfied, and less in existing stable versions, as it goes against stability policy. Ask to your Odoo agent possible solutions (like custom dev).

Closing due to this.
