### ISSUE TITLE
[7.0/saas-3] Event: Registration List: delete icon appears after refreshing the screen

### ISSUE THREAD

**Issue by anthony-muschang** [odoo/odoo#5243]
In the registration list in event, the delete icon appears after refreshing the screen. If you click on it, the item disappears from the list but is not deleted.

This problem occurs only on 7.0 and saas-3, there is no problem on 8.0.
This issue has been first fixed on 8.0 by the following commit:
https://github.com/odoo/odoo/commit/6349048ba0e5e74c74e783ffce8c3c0083d2f060
But have been reverted by this commit:
https://github.com/odoo/odoo/commit/7aa5d397c8cc2a1e6fae4c6a289cd635b952ea42
I cannot find the final fix for this issue.

Scenario:
With the event module:
1/Go to Marketing/Event
2/Create/Edit an event
3/Add some registrations and save
4/The delete icon is not available
5/Refresh (F5)
6/The delete icon is now available
7/Try deleting some registrations
8/Refresh the screen again
9/The deleted registrations are still visible in the list.

Tested with Chrome and IE9.

**Comment by anthony-muschang** [comment]
Linked to opw-627885

**Comment by dmo-odoo** [comment]
Hello, 

The final fix was https://github.com/odoo/odoo/commit/7ec7f1ba4088525f3ad612557757deae294fc688. I have backported it to 7.0 in https://github.com/odoo/odoo/commit/e2fa66b05df027c3d0977bccf6bb508f2cfc3669 and it will be forwardported to the saas branches soon.

Best regards,
David
