### ISSUE TITLE
Issue v7, order confirmation, How to resolve !!!

### ISSUE THREAD

**Issue by vitasoa** [odoo/odoo#5246]
Hi all,

1 - In this link "https://www.odoo.com/fr_FR/forum/help-1/question/issue-v7-order-confirmation-how-to-resolve-73289" a bug is reported but not answered until now!

2- This is another link "https://www.odoo.com/fr_FR/forum/help-1/question/openerp-odoo-hell-big-issue-untraceable-workflow-stucked-73306"

i've managed this bug by sql query and sale_set_to_draft order of julius module.

Is this an Odoo bug???
How to manage it!!!!

Sincerly

**Comment by Yenthe666** [comment]
Hi @vitasoa,

Thank you for your bug report and my apologies for the late response.
This bug seems to be fixed in the newer versions (V8, V9 and V10). As we no longer support Odoo 7 (Odoo goes back three versions) I'm closing this bug report.

Regards,
Yenthe
