### ISSUE TITLE
8.0: the purchase order has two buttons named "view_picking"

### ISSUE THREAD

**Issue by lepistone** [odoo/odoo#5247]

**Comment by jco-odoo** [comment]
The stat button and the normal one?

**Comment by lepistone** [comment]
Hi @jco-odoo. Yes, one is on the header (`addons/purchase/purchase_view.xml`), the other one is the new-style stat one (`addons/puchase/stock_view.xml`).

**Comment by Yenthe666** [comment]
Hi @lepistone,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
