### ISSUE TITLE
[BUG] Context is not propagated on tree_but_open actions

### ISSUE THREAD

**Issue by tvibliani** [odoo/odoo#5248]
**Context is not propagated on tree_but_open actions**

Impacted versions:
- 7.0 and above

Steps to reproduce:
1. Open tree or list with specific context values
2. Click on the row, in order to proceed to next action (through tree_but_open)
3. Proceed to next step.

The problem was initially [posted on help page](https://www.odoo.com/forum/help-1/question/how-to-preserve-context-across-multiple-actions-wizards-64377) and it contains simplified code for problem reproduce. I've wrapped this example code from that post in the test module (the module you can [see here](https://github.com/tvibliani/odoo/tree/8.0_test_context_propagation/addons/context_propagation_test)) and problem is still reproduced on latest v8 server.

Current behavior:
- Context is not propagated on tree_but_open actions, in some cases it makes impossible to access exact state of the row clicked, as values of functional (computed) fields that are not stored in the database may depend on the context of tree/list, so only active_id is not sufficient for complete access to the state of the record clicked.

Expected behavior:
- To have access to state of all supported field types of the record clicked.
- To have the same context in the event handler function as in the tree/list event fired on.

**Comment by tvibliani** [comment]
@odony #5191

**Comment by odony** [comment]
@tvibliani As discussed on your PR #5191, it seems the problem might be solved by this patch: 8c3d71ccb88950ecc5741c76e7217e478e2f2988 that comes from the 8.0 series.
As are testing on 7.0, you'll have to **manually apply** it on your server, doing an update is not enough. I've extracted the relevant part for you [here](https://gist.githubusercontent.com/odony/a3cd254afde9a81a61fd/raw/af1e91cd50171bd7514ac8f97dc357dd302edac7/8c3d71ccb88950ecc5741c76e7217e478e2f2988_partial.patch), and I've tested that it applies cleanly on the latest 7.0 series. If that solves the problem, we'll know how to fix it in 7.0 too.

**Comment by tvibliani** [comment]
I guess it's time to use your advice about ignoring comments... just, I'd like to notice that in the part of "Steps to reproduce" above, I've mentioned that problem was reproduced on the latest v8 server (i.e. 8.0 series, not 7.0. as you have doubts you can see the branch [8.0_test_context_propagation](https://github.com/tvibliani/odoo/tree/8.0_test_context_propagation) -based on 8.0 series) it includes also mentioned fix 8c3d71ccb88950ecc5741c76e7217e478e2f2988 (as it was synchronized today with [Odoo 8.0](https://github.com/tvibliani/odoo/tree/8.0) ). It contains the test case module [context_propagation_test](https://github.com/tvibliani/odoo/tree/8.0_test_context_propagation/addons/context_propagation_test) (that is not something else than example code copied from the [question on help page](https://www.odoo.com/forum/help-1/question/how-to-preserve-context-across-multiple-actions-wizards-64377) and this module is only addition to original code in this branch) and it is **NOT** fixed... context propagation on tree_but_open actions is still problem.

**Comment by rahu1994** [comment]
Hello, 
I tried the following and it worked for me (in v8):

In 
**/web/static/src/js/view_tree.js** 
change the following line in the function _activate_ 

Line: 237:
```
 //var c = new instance.web.CompoundContext(local_context).set_eval_context(ctx);
 var c = new instance.web.CompoundContext(ctx);
```

Now the context is propagated to the next view.

**Comment by andreinl** [comment]
@rahu1994 Thank you very much for you solution. The bug is still there after all these years

**Comment by Yenthe666** [comment]
Hi @tvibliani,

Thank you for your bug report.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
