### ISSUE TITLE
[Master] hr_expense: cannot post journal entry. giving error

### ISSUE THREAD

**Issue by omalbastin** [odoo/odoo#52549]
Impacted versions:Master

Steps to reproduce:Create a expense,with payment by company and approve it and then click on post journal entry button

Current behavior:
AttributeError: 'account.journal' object has no attribute 'post_at'

Expected behavior:
should post the journal entry
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Please don't create issues over master branch, as it's a development branch that will contain for sure some problems. When the release date will be near (Mid September or so), then it can be useful as they new version is around to come, but not now.

**Comment by Yenthe666** [comment]
Sorry but bugs against the master version are not accepted/looked at. It's the development branch and is actively seeing changes/fixes.

**Comment by omalbastin** [comment]
okey. I understand. I would like to contribute to master. Is it possible?

**Comment by Yenthe666** [comment]
Sure thing! If you find the bug you can create a PR to resolve it.
See https://github.com/odoo/odoo/wiki/Contributing#making-pull-requests for extra info

**Comment by omalbastin** [comment]
okey. But in this case, I would need to know what are the changes made. Here a field(post_at) from journal entry which was there in v13 was removed in master. In v13 hr_expense module i cant find using the field post_at but it is there in master. 
Thank you for your valuable time

**Comment by Yenthe666** [comment]
@omalbastin yeah it takes some digging through the commits to figure out what was changed & why :) If you wait for a few weeks it will most likely be fixed in master again anyways.
