### ISSUE TITLE
Payment Server Error

### ISSUE THREAD

**Issue by guinhares** [odoo/odoo#52544]
Impacted versions: Odoo12

Steps to reproduce:
Odoo 12 is showing this error on the portal, when the payment will be made, can someone help me?

Video/Screenshot link (optional):
![Error](https://user-images.githubusercontent.com/66495194/83921889-bccf9180-a755-11ea-9e02-03b26fffa92c.png)

**Comment by pedrobaeza** [comment]
Which is the payment carrier? Do you have latest source code?

**Comment by guinhares** [comment]
Hi, sorry about delay response! i'm still testing

**Comment by Yenthe666** [comment]
Hi there,

Since there has been no feedback since our last question I'm closing this issue.
Don't hesitate to comment back with extra information / reproducable steps and we'll be happy to reopen this issue.

Regards,
Yenthe
