### ISSUE TITLE
Cannot click on Join Course tooltip <a href /> link

### ISSUE THREAD

**Issue by sansirit** [odoo/odoo#52547]
Impacted versions: 13.0

Steps to reproduce: 
- using website_slides module
- Create a training with channel_type = training
- Open the corresponding frontend page as a public user (without login), click on the "Join Course" button. 
- A tooltip popover will appear with an \<a href\> tag redirect to "/web/login" or "/web/signup" page.
- Clicking on the \<a href\> tag on the tooltip

Current behavior: Nothing happen after clicking on the \<a href\> tag on the popover tooltip.

Expected behavior: Redirect to login or signup page with a redirect parameter back to the course page.

Video/Screenshot link (optional): https://youtu.be/vROWk6f3akU

**Comment by Yenthe666** [comment]
Hi there,

It has been fixed in the meanwhile and works fine now! 👍 

Regards,
Yenthe
