### ISSUE TITLE
SSL POSBOX Issue 

### ISSUE THREAD

**Issue by KBrossmann** [odoo/odoo#52559]
Impacted versions:ODOO12 CE Secure Server, POSBOX image 20.02 (NGINX &SSL)

Steps to reproduce: When starting POS the system won't connect POSBOX (Printer display etc.)

Current behavior: This behavior changes, when reaching the POSbox first by entering its IP _(https://POSBOX_IP_here)_ via Browser and accept the (self-signed Certificate) warning. I.e. on the Warning Page (depending on Browser used) 1. click [advanced] and 2. click [Accept the Risk and Continue]. When done and restarting POS everything works mint.

![Capture](https://user-images.githubusercontent.com/46049111/83970459-f5d64600-a8bc-11ea-9dd4-1436d222b764.JPG)

Expected behavior: That POS should start correctly (with POSBOX) without prior need to reach the POSBOX and accept the risk! 

Maybe there is a way within Nginx default.conf to bypass the browser security warning? Help would be appreciated.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Duplicated of #3156
