### ISSUE TITLE
How to pack installation files for windows

### ISSUE THREAD

**Issue by dinhnghia** [odoo/odoo#52550]
Impacted versions: 13.0

Steps to reproduce: 

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
