### ISSUE TITLE
Backup user login failure

### ISSUE THREAD

**Issue by LSR29** [odoo/odoo#52553]
Impacted versions:
13
Steps to reproduce:

A disk is copied to the database and restored to another disk with the same version and error when trying to login "Internal Server Error"

Current behavior:

Error when trying to login

Expected behavior:

Enter OK

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Euhmm that's an issue related to your deployment/way of restoring but not to Odoo. Besides of that you didn't specify what the error is saying (log output etc) so there's nobody who can help you this way.
Perhaps you can ask this on the official help forums (help.odoo.com) and add more details about what went wrong.

Regards,
Yenthe

**Comment by LSR29** [comment]
Thanks for the reply but I think it could have something to do with Odoo.

I explain the more detailed problem:

I did a backup of Odoo 13.
When restoring the file in a new installation of Odoo 13 the following message appears:

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

I leave you the file Odoo.log

Thanks for the help

[odoo.log](https://github.com/odoo/odoo/files/4748758/odoo.log)

**Comment by Yenthe666** [comment]
It is giving errors such as
```
load could not load template
Template: web.login_layout
```

Which generally happens if the files do not have the right access rights or the modules are not loaded.
Another one is about a table not being found:
```
ValueError: <class 'psycopg2.errors.UndefinedTable'>: "no existe la relación «crm_lead_scoring_frequency_id_seq»
LINE 1: ..."value", "variable", "won_count") VALUES (nextval('crm_lead_...
```

There's absolutely something wrong with your Odoo instance or you did not restore your db well.
Your log is full of these kind of errors which makes me 100% certain there's an issue at your end

**Comment by LSR29** [comment]
Thanks for the reply,
Do you think it is due to the postgresql version? I made the backup from Odoo. Could you tell me where I could find a way to backup from postgresql?

Thanks once more for your time.

**Comment by Yenthe666** [comment]
@LSR29 do you mean a back-up from odoo.com or odoo.sh to your local server? Because if that is the case these errors are normal. The database model from odoo.com (and sh) is not the same as the major Odoo versions such as V13.
