### ISSUE TITLE
Photo Thumbnails in Many2One field - Odoo v11

### ISSUE THREAD

**Issue by fasilwdr** [odoo/odoo#52565]
Hi Guys,
below is my classes

```
class collormodel(models.Model):
    _name = 'collor.model'

    name = fields.Char(string='Collor Model Name')
    image = fields.Binary(string='Image')

class Customermodel(models.Model):
    _name = 'customer.modellines'

    collarmodel3 = fields.Many2one('collor.model', string="Model")
```

I need to show as given below with Image in form view of Customer model.
Please help on this.. what should I do write for the view.

![image](https://user-images.githubusercontent.com/63807062/84002359-fa5c3680-a970-11ea-9751-5af8ba7d24c8.png)

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
