### ISSUE TITLE
Sidebar empty after reload - convert to opportunity

### ISSUE THREAD

**Issue by coleste** [odoo/odoo#5256]
Branch 8.0, commit c62be6167a79e1d581aea2d2ad9fd53fbb70b43d
Using crm addon
- create a call in Sales / Phone Calls / Logged Calls
- save it
- click "convert to opportunity" icon
- reload browser
  (sidebar is empty)

This may be because there are no action parameter in the query string.

**Comment by Yenthe666** [comment]
Hi @coleste,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
