### ISSUE TITLE
showing secret key is a security issue

### ISSUE THREAD

**Issue by EsrefDurna** [odoo/odoo#52570]
Impacted versions: 13

Steps to reproduce:
1- setup stripe at website/ payment acquirer. place your publishable and secret key
2-  invoicing : at the first dashboard(blue wizard) click to step payment method
![unnamed (1)](https://user-images.githubusercontent.com/1230575/84012945-23f36e80-a92d-11ea-998d-41d40e7d06d7.png)
3- see the secret key and publishable key is being displayed to the user without masking....
![unnamed](https://user-images.githubusercontent.com/1230575/84012584-9fa0eb80-a92c-11ea-8e5d-124998bedcbb.png)

Current behavior: shows the secret key to the user

Expected behavior:should mask the secret key and publishable key

**Comment by Yenthe666** [comment]
@odony for your reference.

**Comment by odony** [comment]
PR welcome ;-)

**Comment by Yenthe666** [comment]
I'll put that onto my todo list, I have some others in line too. Just add a `type="password"` I assume you mean?

**Comment by Yenthe666** [comment]
Fixed in https://github.com/odoo/odoo/commit/65e201ecee3bc145c2ae76d59b6d2fd31c737872 🥳
