### ISSUE TITLE
How to Configure OpenERP 8.0 (odoo) to connect to LDAP ?

### ISSUE THREAD

**Issue by dg-clearcorp** [odoo/odoo#5257]
Hi guys, I have a problem with the module 'auth_ldap' need to configure it to achieve log in with a user created in the LDAP server that is not an administrator, which believe it is my mistake and what the correct configuration, I got no user admin, muy user are uid in people, I need configure with admin user and then i can to login with muy user uid in people or I can configure with than user (uid with her password at the same way). Thanks.
This is my configuration: https://drive.google.com/file/d/0B8NblWSNGrfKcnhuc0hwWGtRSk0/view?usp=sharing

**Comment by Yenthe666** [comment]
@dg-clearcorp this Github is used for reporting errors in Odoo and yours isn't an error, you simply don't know how to do it correctly.
The chances that one of the developers will look at this is small and when they do they'll most likely close it.

I'd suggest you to post this question on the help forums as there are a lot of people that love to help you out. Have a look at https://www.odoo.com/forum/help-1 and post a new topic there.
Best of luck :)
