### ISSUE TITLE
Installing failed

### ISSUE THREAD

**Issue by lupa18** [odoo/odoo#5258]
Hello, I tried do this: 

    wget -O- https://raw.githubusercontent.com/odoo/odoo/8.0/odoo.py | python

and results this: 

```
2015-02-12 19:21:12 (35,2 MB/s) - escritos a stdout [5618/5618]

Traceback (most recent call last):
  File "<stdin>", line 160, in <module>
  File "<stdin>", line 152, in main
  File "<stdin>", line 142, in cmd_setup
  File "<stdin>", line 60, in cmd_setup_git
  File "<stdin>", line 47, in git_locate
OSError: [Errno 2] No such file or directory
```
Env: Linux Linux Mint 17 (Ubuntu 14.04) - Linux 3.13.0-24-generic

**Comment by lukebranch** [comment]
@lupa18 ,

Are you trying to install Odoo by just downloading the odoo.py file? You need to download the complete source code from github.

I'd recommend referring to this install script as a guide for one of the methods for install Odoo from source:

https://github.com/lukebranch/odoo-install-scripts/blob/master/odoo-saas4/ubuntu-14-04/odoo_install.sh

Steps to install using this script are as follows:

1) sudo wget https://raw.githubusercontent.com/lukebranch/odoo-install-scripts/master/odoo-saas4/ubuntu-14-04/odoo_install.sh
2) sudo sh odoo_install.sh
3) after script has completed restart your server.

As this is not an issue/bug with the Odoo software i'd recommend closing this issue and creating a question in the help forum here:

<a href="http://help.odoo.com">http://help.odoo.com</a>

or referring to one of the many installation guides on the help forums already.

**Comment by sle-odoo** [comment]
@lupa18 
Hi,
It looks like git is not installed on your machine. Can you install it and try again?

@lukebranch 
The odoo.py script is meant to be an example of Odoo development environment (configuration of the repo). So *it is* downloading the complete sourcecode from github (`remote update` then `checkout`).

While i have nothing against your script, i'll add to note that for a deployment or classic installation, official builds are available at [nightly.odoo.com](https://nightly.odoo.com) and we have an [installation](https://www.odoo.com/documentation/8.0/setup/install.html) and [deployment](https://www.odoo.com/documentation/8.0/setup/deploy.html) guide.

**Comment by lukebranch** [comment]
@sle-odoo ,

Thanks for clarifying that, I was not aware that it was downloading the complete sourcecode from github. I may look into modifying my script as a result.
