### ISSUE TITLE
Materials booked on project doesnt show anywhere

### ISSUE THREAD

**Issue by fcorselis** [odoo/odoo#5261]
We are a project based company and we book our sales on contracts. From there we can make the invoice for services and materials. The best approach would be we could book our timesheet and materials on the project contract. from there we can select all the labor/material lines and make an invoice (the labor and material are invoiced in one line (ie install a heating installation).

Then we would need 
- a report : material / labor invoiced (cost/sale/gain).
- see material / labor not yet invoiced (with the possibility to invoice).

Does a module or combination like this exist or is there a way to make this possible?

Thank you.

**Comment by Yenthe666** [comment]
Hi @fcorselis,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
