### ISSUE TITLE
[BUG] Random error: Access Denied by ACLs for operation: read, uid: 4, model: sale.order 

### ISSUE THREAD

**Issue by sum1201** [odoo/odoo#52660]
Impacted versions:
13.0
Steps to reproduce:

   ```
 @http.route('/meituan/order_create', type='json', auth="public", csrf=False)
    def meituan_order_create(self, **kwargs):
        .......
       request.env['sale.order'].with_user(uid).create(vals)
       ........

```

I wrote the above code, but randomly reported an error during operation:
`Access Denied by ACLs for operation: read, uid: 4, model: sale.order `

I followed it for a long time and couldn't find the cause of the problem.
I have used **with_user** to authorize, there should be no permission problems, and the above error appears randomly, not every time it is requested.
I noticed that the uid in the error is public user, so I added the following code:
```
request.env.uid = uid
request.env.user = ota_id.user_id
```

The problem is solved, and no random error is reported.

Is this a bug? Or did I write it wrong?

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question about custom development. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
