### ISSUE TITLE
How can any tasks and activities that are assigned to someone in the project section be added to that person's calendar?

### ISSUE THREAD

**Issue by movahhed** [odoo/odoo#52678]
ODOO12 community
OS : ubunto server 18.04
How can any tasks and activities that are assigned to someone in the project section be added to that person's calendar?

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Comment by movahhed** [comment]
> Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.
> 
> Closing this by the reason above.


Dear friend
However, can you tell me what to do?

**Comment by pedrobaeza** [comment]
No, sorry.

**Comment by pedrobaeza** [comment]
Please write there in the forums and functional people will tell you. It's good to answer others' questions before and ask in exchange that others answer yours.
