### ISSUE TITLE
Question about behaviour of @api.onchange (maybe bug)

### ISSUE THREAD

**Issue by lrstry** [odoo/odoo#52671]
**Impacted versions:**

Im working with ODOO Community Edition 13.0-20191106.

**Steps to reproduce:**

- Coding: Define a One2many relation with required and non-required fields on the many-side
- Coding: Define a function annotated with @api.onchange("$ONE2MANY_RELATION_NAME$") with breakpoint in function
- UI: Add a new line-item for the One2many relation
- UI: When entering data in the new line-item considering only non-required fields, nothing happens until you satisfy every required field

- Doing the same with only non-required fields on the many-side, the onchange will be triggered on every field change

**Current behavior:**

The @api.onchange event for a fields.One2many relation is being triggered on every field-change **after** all required fields in many-side of One2many relation are satisfied.

**Expected behavior:**

The @api.onchange event for a fields.One2many relation should be triggered either consistently on every field-change (regardless of required or not) or "onExit"/"onSave". 

I would prefer an @api-Event for both cases:
- On every field change of the annotated relation
- On save, returning the new line item (Maybe there is already something? I actually need this.)

**Comment by pedrobaeza** [comment]
Can you please include a demo module that exercises the problem?
