### ISSUE TITLE
cannot print general ledger report

### ISSUE THREAD

**Issue by davshafik** [odoo/odoo#5268]
i got this error when trying to print general ledger report or invoice
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
Note : wkhtmltopdf is installed and working properly

**Comment by davshafik** [comment]
i got this error when trying to print general ledger report or invoice 
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
Note : wkhtmltopdf is installed and working properly

**Comment by Sameer1990** [comment]
what the version of odoo installed ?

**Comment by davshafik** [comment]
Odoo v8

**Comment by Sameer1990** [comment]
Checkout the latest master branch of odoo version 8. No error in printing reports .

**Comment by davshafik** [comment]
i will do it now, thnak you

**Comment by davshafik** [comment]
thnx its fixed

**Comment by wredwan** [comment]
What can i do to fix this issue without install new odoo version ???
