### ISSUE TITLE
8.0: JS crash in reconcile interface of bank statements

### ISSUE THREAD

**Issue by alexis-via** [odoo/odoo#5272]
Here is the scenario to reproduce the bug:
1) Connect on runbot 8.0 as admin user
2) Menu Accounting > Journal Entries > Journal Entries
Create an account move:
Journal: Sales Journal
Create 2 move lines:
a) name : POUET
   partner : Best Designers
   account : 701000
   credit : 100
b) name : POUET
   partner : Best Designers
   account : 400000
   debit : 100
Then clic on the "Post" button to post this account move.
This will create an account move with 2 lines ; on these 2 lines, the "ref" field will be empty (it is required to trigger the bug).

3) Menu Accounting > Bank and Cash > Bank Statements
Create a new bank statement. In this new bank statement, add 1 line:
Communication : test1
Partner : Best Designers
Amount: 2000

Clic on the "Reconcile" button

4) In the special reconcile interface, the focus will be on the line of Best Designers of 2000 €. The account move of 100 € that we created manually at step 2 will be pre-selected for reconcile.
In the Filter box, type "027" (this string doesn't match the move line POUET that is pre-selected for reconcile)
Unselect the line POUET by clicking on the "minus" sign next to the account code 400000.
You get a JS crash : 
```
TypeError: o.ref.indexOf is not a function
```

Code analysis: in odoo/addons/account/static/src/js/account_widgets.js line 1240 https://github.com/odoo/odoo/blob/8.0/addons/account/static/src/js/account_widgets.js#L1240
When o.ref is false (ref is not a required field on account.move.line), it crashes on o.ref.indexOf(self.filter)
So this code needs to be adapted to handle the case when o.ref is false.

**Comment by Whisno** [comment]
Thanks, I wasn't expecting it to be false instead of empty string
