### ISSUE TITLE
Event email body empty when odoo translation loaded

### ISSUE THREAD

**Issue by walther-barnett** [odoo/odoo#52744]
Impacted versions:
Odoo 13.0-20200121 (Community version) container
Events app version 13.0.1.0

Steps to reproduce:
Use on-prem mailserver
Install/Configure a standard company and standard user,
Install an official translation eg. Danish
Set language for admin and standard user to the loaded language
Create a homepage in translated language
Install the Event App
Create an Event
Publish on homepage
Reload the official translation to get the translated templates for the event app
Let a non-authenticated user, signup for an event

Current behavior:
The Event-registration email has no body only subject

Expected behavior:
The event registration email template being used

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
That's because the corresponding translation is not correct and don't keep correctly the placeholders or expressions.

Please see https://github.com/odoo/odoo/wiki/Translations for knowing how to change that translations.

Closing as translation issue.
