### ISSUE TITLE
Odoo 12 install on Ubuntu

### ISSUE THREAD

**Issue by payal-dot** [odoo/odoo#52747]
I am facing Daemon File not exist issue

**Comment by Digpal** [comment]
I am also facing this problem

**Comment by pedrobaeza** [comment]
How do you install it? Through the official .deb? Which Ubuntu version?

**Comment by Digpal** [comment]
Thanks for quick response pedrobaeza

**Comment by payal-dot** [comment]
![image](https://user-images.githubusercontent.com/64143063/84248089-91b6ba80-ab26-11ea-8b69-3c44d5fc03d0.png)

**Comment by payal-dot** [comment]
ubuntu 18.4

**Comment by payal-dot** [comment]
i am installing odoo12 i ubutu 18.4 via putty from my window system.Ad i getting this issue.
I have follow below link:
https://www.technaureus.com/how-to-install-odoo-12-on-ubuntu-18-4-odoo-installation/

**Comment by Digpal** [comment]
I am also getting this bug

**Comment by pedrobaeza** [comment]
Sorry, but you have to follow standard installation instructions https://www.odoo.com/documentation/12.0/setup/install.html.

If they fail, then you can go back here. For other methods, you should contact the method's author.
