### ISSUE TITLE
Hello. Can I Override standard Odoo Method. In http.py - Response Class?

### ISSUE THREAD

**Issue by Penetrator80** [odoo/odoo#52742]
Impacted versions:
13.0
Current behavior:
Standard behavior with allowed methods: POST, if CORS
Expected behavior:
I want override the method set_default(self, template=None, qcontext=None, uid=None)
To allow use such methods as DELETE, PUT, PATCH etc.,  but nothing happens.

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
