### ISSUE TITLE
Unintstalling a module takes long time, but not finishing yet?

### ISSUE THREAD

**Issue by jothehero** [odoo/odoo#5275]
Hi all,
I used a field in my custom module, like this

'module_list': fields.many2many('ir.module.module', id1='module_id', id2='ins_module_id', string='Modules'),

**Comment by Yenthe666** [comment]
Hi @jothehero,

This looks more like a question then a bug report to me. As this is also about custom development you should use the official help forums (https://odoo.com/help).
P.S: Do add more information next time too 😉 

Regards,
Yenthe
