### ISSUE TITLE
[13.0] Pasting an image (via CTRL+V) causes an image to be inserted twice into any HTML field

### ISSUE THREAD

**Issue by BlommaertsEdwin** [odoo/odoo#52752]
Impacted versions: V13

Steps to reproduce:
- Copy image data (e.g. from within Paint or GIMP), and paste it into an HTML field using CTRL+V (or right-click, paste)

Current behavior:
Image is inserted twice

Expected behavior:
Only one image should be inserted

Video/Screenshot link (optional):

**Comment by katyukha** [comment]
Seems to be fixed by https://github.com/odoo/odoo/pull/52512
But not sure.

**Comment by pedrobaeza** [comment]
@BlommaertsEdwin can you please check with latest code?

**Comment by tanghulu0608** [comment]
We have the same issue.

**Comment by BlommaertsEdwin** [comment]
@pedrobaeza I pulled the latest odoo and I'm no longer experiencing this bug.
