### ISSUE TITLE
[8.0] Wrong link to etherpad website

### ISSUE THREAD

**Issue by parthivgls** [odoo/odoo#5276]
Wrong link to etherpad website in "pad" module.

https://github.com/odoo/odoo/blob/8.0/addons/pad/__openerp__.py#L11

**Comment by Yenthe666** [comment]
Proposed a pull with a fix here: https://github.com/odoo/odoo/pull/5287

**Comment by Yenthe666** [comment]
Fixed at https://github.com/odoo/odoo/commit/67bdc241bd7c2a358871f43dd4adcc091d125711
