### ISSUE TITLE
Missing traslation

### ISSUE THREAD

**Issue by SBollatti** [odoo/odoo#5278]
At
odoo/addons/purchase/i18n/es_AR.po
line
211 msgstr "" 

Should say
msgstr "Compras"

**Comment by Sameer1990** [comment]
There is more than a word missing translation , Odoo not consider missing translation an issue .

**Comment by SBollatti** [comment]
Ok
Closing

**Comment by smack815** [comment]
@SBollatti Translations are added through Launchpad and migrated to GitHub monthly.  You can add the translation by joining the team for your language and add missing phrases there.  I have a [Odoo Forum Post](https://www.odoo.com/forum/help-1/question/64234) about this subject you might want to check out.
