### ISSUE TITLE
Odoo on FreeNAS?

### ISSUE THREAD

**Issue by thejrose1984** [odoo/odoo#5279]
Fairly certain I know the answer, but do you support an instance of Odoo running on FreeNAS? If so, is there an installation guide posted somewhere?

**Comment by thejrose1984** [comment]
Status?

**Comment by lukebranch** [comment]
@thejrose1984 ,

This is a question rather than an issue, so I think it would be better if you posted it to the community forums, as you are more likely to get help there.

**Comment by thejrose1984** [comment]
Community forums suggest installing from source (using git), which I did. Also installed all the required packages, but it still won't run. Looks to me like the code is not FreeNAS/FreeBSD friendly...

**Comment by mbaragiola** [comment]
Hello @thejrose1984 , I currently use FreeBSD to run Odoo. It wasn't a trivial install, so I wrote a small plain-text guide for others to set it up. I'm waiting for my CLA to be merged so I can add my guide to the install documentation.

I don't know about FreeNAS, though. But maybe I can send this guide to you and you can try it for yourself.

**Comment by thejrose1984** [comment]
@mbaragiola FreeNAS is essentially FreeBSD with some minor tweaks. Most, if not all, FreeBSD commands work in FreeNAS. I compiled a guide myself based on the "trial and error" approach, but found it was looking for directories that clearly didn't exist (e.g. /var/lib).

I'd appreciate swapping notes with you to see if I can figure out where I need to change my install strategy.

**Comment by mbaragiola** [comment]
@thejrose1984 sure. I'll try to reach you via email. Unrelated to your problem: it was a general consensus that SQL and ZFS are not best pals due to perfomance issues in the long run. I only mention this because FreeNAS heavily uses ZFS as far as I know. I may be wrong about the two things, though.

**Comment by thejrose1984** [comment]
@mbaragiola wouldn't surprise me. I have an instance of ownCloud running in one jail and MariaDB from another jail (as a general practice, I prefer not to have the database and application on the same system). Mind you, it's a relatively new install and working good with the occasional slowness (I've pegged that to PHP settings though).

**Comment by Yenthe666** [comment]
Hi there,

I'm closing this bug report as it is not a bug but a question.
Feel free to ask this on the help forums at https://odoo.com/help. To answer: there is no installation guide for that specific version 😉 

Regards,
Yenthe
