### ISSUE TITLE
Can POS orders be printed without POSBox? Odoo-12

### ISSUE THREAD

**Issue by fasilwdr** [odoo/odoo#52805]
Can POS orders be printed without POSBox?
Hope your suggestions and advises

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here. Short answer: yes.

Closing this by the reason above.
