### ISSUE TITLE
Change POS order name

### ISSUE THREAD

**Issue by javierisc** [odoo/odoo#5281]
Is there a way to change the default names of POS orders?

Instead of "1", "2", "3", etc I would like that the user be able to modify it and write any name.

Best regards

![screen shot 2015-02-14 at 8 06 35 pm](https://cloud.githubusercontent.com/assets/10949868/6201840/d62a46de-b485-11e4-8b6e-5e837c72ff33.png)

**Comment by Yenthe666** [comment]
@javierisc this isn't a bug or error so Odoo will probably not reply on this and will most likely just close the topic.
You should try at http://help.odoo.com/ there are a lot of tech-savvy people there that love to help others with things like this!

**Comment by Sameer1990** [comment]
This is not issue , share your problem in https://www.odoo.com/forum/help-1
