### ISSUE TITLE
[8.0]Sorting by name is done on the source instead of the translated fields

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#5283]
# Impacted versions:
8.0
#  Steps to reproduce:
Go to runbot and open a v8.0 instance.
Add a foreign language and log in with this new language
Create a product template first : http://46774-8-0-9ffa3a.runbot.odoo.com/web?#page=0&limit=80&view_type=list&model=product.template&menu_id=298&action=316
Clone it, and change the translation so that it should come before the product that has been cloned regarding to its name.
Do it another time so that you'l have 3 products

# Expected behavior :
Sorting products on name should dispaly values on the translated fields

# Current behavior:
It's not sorted on the translated field but on the source

![products](https://cloud.githubusercontent.com/assets/1043935/6204522/727684a8-b54e-11e4-82ac-2a459afe2257.png)

**Comment by thomich** [comment]
i confirm this issue, tested with latest commit https://github.com/odoo/odoo/commit/9333c622e967207dd6fc9ee23513af9769fc9ee1

**Comment by flotho** [comment]
Hy @mart-e any chance to be reviewed by the team on this?
Regards

**Comment by mart-e** [comment]
@flotho I was going to say no but then I saw #5310, so maybe :) (but we still have to check performances impact)

**Comment by flotho** [comment]
@mart-e a great thanks for your support. This kind of point (translation part) is frequently used as an example for illustrating that the product is not "finished"

**Comment by rco-odoo** [comment]
Sorting on translated fields was simply never implemented.
Implementing it has some non-trivial impact on existing code (API changes), it is not just a "fix".
The pull request #5310 has been cancelled and reworked for version 9.0, see #7091.

**Comment by thomich** [comment]
that measn really, that it won't be fixed in odoo 8???

**Comment by mart-e** [comment]
Sorry, this is not a change we can make in stable version.
The patch from #7091 changes too much the way the queries are generated and other low level operations, this would potentially break other modules relying on the old behaviour.

**Comment by thomich** [comment]
as from @mart-e reported, a lot of things has to be changed.. but the main thing is, that odoo is multi language based.. and it has to work for each language...

is there any plan to solve that or do it with a extra module?
is this implemented in odoo 9?

**Comment by mart-e** [comment]
Yes, it has been fixed for v9. Take a look at below example where the order is different in english and in french.
![screenshot from 2015-09-07 12-44-33](https://cloud.githubusercontent.com/assets/564822/9715182/422de59c-555e-11e5-9792-e05585373921.png)

![screenshot from 2015-09-07 12-42-57](https://cloud.githubusercontent.com/assets/564822/9715178/3ea38b16-555e-11e5-9298-a7766f191cc3.png)

**Comment by michaelkarrer81** [comment]
Is there any way in odoo 8.0 to sort a record set by the "translated" field? e.g.: by Name?
