### ISSUE TITLE
Stripe Checkout language

### ISSUE THREAD

**Issue by dirceu3h** [odoo/odoo#52879]
Impacted versions: Community 13

Steps to reproduce:
At the online store when the user clicks on "pay now" button using the stripe acquired method it takes them to the stripe checkout **English** version.

Current behavior:
The problem is that it always takes them to the English version of the stripe checkout. Even if the browser is in Spanish.

Expected behavior:
According to this documentation from stripe https://support.stripe.com/questions/supported-languages-for-stripe-checkout the checkout should use the browser's language, but it does not.
I suppose it is kind of hardcoded, somewhere in the module.
Do you know what might be the problem?

Video/Screenshot link (optional):
![checkout odoo](https://user-images.githubusercontent.com/42354147/84419086-558e6300-abd5-11ea-8737-6c8458176a69.png)
![stripe checkout](https://user-images.githubusercontent.com/42354147/84419088-5626f980-abd5-11ea-9de7-3e7cd518b100.png)

**Comment by pedrobaeza** [comment]
@dbo-odoo any hint?

**Comment by dirceu3h** [comment]
Hello friends from odoo. Could you provide some feedback about this issue?
are we doing something wrong?
regards

**Comment by nla-odoo** [comment]
Hello @dirceu3h 
It should work with browser locale as we left blank it
https://stripe.com/docs/api/checkout/sessions/create#create_checkout_session-locale
you can check here.

cc: @dbo-odoo 

Thanks

**Comment by dirceu3h** [comment]
I aksed some friends to test it in their broweaers and you are right l, it's showing in their browser language.
Prpbably in my browsers there is an issue or miss configuration. 
Thanks a lot, i will close the issue
