### ISSUE TITLE
I have follows your all the installation instructions but still I am facing DB error.

### ISSUE THREAD

**Issue by ajaybit** [odoo/odoo#52882]
Impacted versions:12

Steps to reproduce: Install and configure with Db

Current behavior: Unable to connect with DB
DB version using Postgres12

Expected behavior:
Should connect with DB

Video/Screenshot link (optional):
<img width="1341" alt="DB_error" src="https://user-images.githubusercontent.com/21233349/84432601-adb37c80-ac4a-11ea-982e-3d24f0bd8a42.png">

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/12.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).
