### ISSUE TITLE
Odoo reserve more than request to consume and I can't Close Production Order

### ISSUE THREAD

**Issue by gnfranco** [odoo/odoo#52884]
Impacted versions:

Steps to reproduce:
  I created a BOM that uses 3.5cm of a raw material. The standard measuring unit of the raw material is stored in meters. So when I try to execute and close a production order using the BOM with this raw material being requested in centimeters. Odoo reserves a little more than it needs to consume and now I have received the following message: "It is not possible to cancel the reservation of more raw material items than you have in stock."

 

Current behavior: Reservation was done in more than will be consumed. I can't cancel reservation and close the order.

Expected behavior: 

Video/Screenshot link (optional):
https://1drv.ms/u/s!ArflGpEQKCK2h7xqFhpyTmusiIctEQ?e=OaIdTN
https://1drv.ms/u/s!ArflGpEQKCK2h7xs9ehNfYHVQEpcCA?e=V4naaI
https://1drv.ms/u/s!ArflGpEQKCK2h7xrKKRWeM9uCuLyHw?e=qhHmad
https://1drv.ms/u/s!ArflGpEQKCK2h7l9n_8O_GAxC1QzSw?e=iBOab4

**Comment by pedrobaeza** [comment]
Odoo version? Please include images in issue itself instead of links.

**Comment by gnfranco** [comment]
![2020-06-11](https://user-images.githubusercontent.com/776952/84522707-817d1780-acad-11ea-8379-31b5250b3d5e.png)
![2020-06-11 (2)](https://user-images.githubusercontent.com/776952/84522721-88a42580-acad-11ea-80b0-851e27886204.png)
![2020-06-11 (1)](https://user-images.githubusercontent.com/776952/84522757-978ad800-acad-11ea-965e-acafb5f9ac2a.png)

**Comment by gnfranco** [comment]
> Odoo version? Please include images in issue itself instead of links.

Odoo 13 runing on Ubuntu 19.10 VPS

**Comment by gnfranco** [comment]
When I change BOM to uses 4cm instead 3,5cm, it works fine.

**Comment by gnfranco** [comment]
Dear Pedro
Please could you help, I just have to close an order that got reserved more than will be used. Even it condition happens odoo won't allow us to close or cancel a Manufacturer Order.

Can I close an production order with this issue any way?

**Comment by pedrobaeza** [comment]
Sorry, I'm not more responsible of tagging issues here. Anyways, I tagged it, but none from Odoo took care of this. You can try to set in the DB the proper values you need for unlocking this.

**Comment by gnfranco** [comment]
Thanks.
But I don't know how to edit my database and don't have ideia yet in how I will close this MO. I understand that here is a place to talk about code, bugfix and other related to coding. Any way I'm unable to get much more help with this issue on other places.

![2022-03-02](https://user-images.githubusercontent.com/776952/156476130-ba8dbedd-514f-4210-8e4b-693dc9cf7c75.png)

**Comment by gnfranco** [comment]
Need 600 ml of A185 but have reserved 601ml and now this message...

Something went wrong !
×
It is not possible to unreserve more products of [A185] Álcool Isopropílico than you have in stock. Contact an administrator.

**Comment by gnfranco** [comment]
It's solved.
Now I understand what issue was making system crazy. I ajusted rounding precision on UOM and now I'm able to close the Manufacturer Order.

Thanks a lot Baeza for your patience and support here even it's a monolog i yhonk so other people maybe uses this information.

**Comment by pedrobaeza** [comment]
Glad to hear that you get to a solution.
