### ISSUE TITLE
leave seconde validation activity with wrong responsible

### ISSUE THREAD

**Issue by m3asmi** [odoo/odoo#52901]
Impacted versions:12.0

Steps to reproduce:
create a leave for an employee in a departement that his parent is the manager for the departement

Current behavior:
1st and the seconde validation in the activity will  be by affected to the manager of the department

Expected behavior:
1st must be affected to the responsible of the departement
2nd must be affected to the parent of the responsible of the departement

Fix:
https://github.com/odoo/odoo/blob/12.0/addons/hr_holidays/models/hr_leave.py#L819

```

    def _get_responsible_for_approval(self):
        if self.state == 'confirm' and self.manager_id.user_id:
            return self.manager_id.user_id
        elif self.state == 'confirm' and self.employee_id.parent_id.user_id:
            return self.employee_id.parent_id.user_id
        elif self.state == 'validate1':
            return self.department_id.manager_id.parent_id.user_id
        elif self.department_id.manager_id.user_id:
            return self.department_id.manager_id.user_id
        return self.env['res.users']
```

**Comment by pedrobaeza** [comment]
That's not how it works: first approval is from the employee responsible. Second is from the department responsible.

Closing as invalid.
