### ISSUE TITLE
Using multiple currencies. Wrong calculation of cost for a product.

### ISSUE THREAD

**Issue by gnfranco** [odoo/odoo#52935]
I'm trying to buy a product in US$ but when run a purchase odoo stores the US$ value directely as other currency without had calculeted the cambial convertion.
Currencys are enabled and I update then manualy every time.

**Comment by gnfranco** [comment]
Odoo 13

**Comment by pedrobaeza** [comment]
You need to put currency rates. Please do these questions in the forum, not here.

**Comment by gnfranco** [comment]
I have currency rates.

![2020-06-12](https://user-images.githubusercontent.com/776952/84527532-7a0d3c80-acb4-11ea-9c48-5464fefba6dc.png)
![2020-06-12 (2)](https://user-images.githubusercontent.com/776952/84527551-81344a80-acb4-11ea-8b10-b280c310ddff.png)
![2020-06-12 (1)](https://user-images.githubusercontent.com/776952/84527567-85606800-acb4-11ea-85ae-33fc152019f4.png)

**Comment by pedrobaeza** [comment]
Then which is the problem?

**Comment by gnfranco** [comment]
I've runed an purchase and when check on my stock cost Odoo have stored the US$ value as BRL.
Could you understand me now?

**Comment by gnfranco** [comment]
All the system default currency is BRL but we buy things in US$ too.

 The system run but don't make cambial convertion to store the right value in BRL.

**Comment by pedrobaeza** [comment]
This is working in other systems, so you should have something misconfigured.

**Comment by gnfranco** [comment]
I will setup a clean VPS to test.
Thanks
