### ISSUE TITLE
Feature Request: please add voice message to the odoo chatting

### ISSUE THREAD

**Issue by mrzingo** [odoo/odoo#52941]
Please add the feature like whatsapp to send voice notes inside odoo discuss and chatting.

**Comment by pedrobaeza** [comment]
I don't think this is going to be the most wanted feature for Odoo PO, but I tag it.

**Comment by Yenthe666** [comment]
@tde-banana-odoo probably something for you guys to decide?

**Comment by tde-banana-odoo** [comment]
Hello,

I am not working in Discuss team; only maintaining backend / mail gateway. I know Discuss has plans to support voice and video (aka, replacing our internal Discord in the next confinement). I let @seb-odoo gives more details if he has any.

Cheers,

**Comment by seb-odoo** [comment]
This feeback is now considered in task-2278512, so I'm closing this issue.

No promise on the result or deadline though.

**Comment by pedrobaeza** [comment]
Thanks. Note that it's not the same to add audio/video chat than voice notes. For the first one, definitively +1. For the second, I don't like them (for not saying I hate them) the same as WhatsApp ones, but that's my personal opinion.
