### ISSUE TITLE
Account groups hidden in master

### ISSUE THREAD

**Issue by nhomar** [odoo/odoo#52948]
This is an issue for v14.0 *I know it is a WiP* but last time I wait I had bad surprises.

dear R&D team.

Account group is fully hidden from new account chart view (pretty nice BTW).

But we need such element for several reasons and reporting (Not all countries can relly 100% on the codding for the tree view) Remember we need the parent account name (which with auto coding tree feature is not possible to set).

![image](https://user-images.githubusercontent.com/338634/84605047-e2e4e800-ae5f-11ea-83ab-7319d30ef1da.png)

Can we add the group on that extra fields view? that's all what I ask for and happy happy.

**Comment by qdp-odoo** [comment]
what do you mean? you want to add the field `group_id` in the tree view of account.account (optional=hide) ?

**Comment by Yenthe666** [comment]
@nhomar can you give feedback?

**Comment by nhomar** [comment]
Hello @qdp-odoo 

>>.what do you mean? you want to add the field group_id in the tree view of account.account (optional=hide) ?

Yes exactly, (I am using it to fast reporting options) and visibility there helps a lot.

**Comment by antonylesuisse** [comment]
ok

**Comment by Yenthe666** [comment]
It's there in master now. See https://github.com/odoo/odoo/commit/476028c14a0bbe05db12e184b4efb6cd33297363
