### ISSUE TITLE
service in odoo crash automatically

### ISSUE THREAD

**Issue by saibhargav08** [odoo/odoo#52959]
Hi everybody,

I met a problem with service in odoo 13. Sometimes service crashes automatically. I don't know what's the problem. I checked on odoo log file but don't have any message here and I checked in syslog file in Ubuntu 18.04 LTS. It has a message as:
Jun 15 13:00:51 kernel: [1700987.563652] python3[32030]: segfault at 1 ip 000000000054451a sp 00007f7aaeff42a0 error 4 in python3.6[400000+3b4000]
I also checked memory but no issues here as well. 

Server config:

CPUs - 2
RAM - 8GB

Odoo config

; Workers related configurations
; workers = 3
max_cron_threads = 2
limit_time_real = 82800
limit_time_real_cron = 82800

;# Maximum allowed CPU time per request (default 60)
limit_time_cpu = 82800

; Worker memory limit configurations
limit_memory_soft = 1342177280
limit_memory_hard = 2610612736

This issue is been faced in production servers
Thanks in advance.

**Comment by Yenthe666** [comment]
Please add more info to this ticket or it will be closed off. Besides, this looks like a deployment issue ;)

**Comment by saibhargav08** [comment]
> Please add more info to this ticket or it will be closed off. Besides, this looks like a deployment issue ;)

I have updated the information please let me know in case of any further info

**Comment by saibhargav08** [comment]
Hi,

We are having this issue very frequently on our production servers. @Yenthe666 Can you provide any insights on this issue?

**Comment by Yenthe666** [comment]
Why have you commented out the workers? 2 CPU's for 8GB of RAM isn't really great either.
Have you checked https://www.odoo.com/documentation/13.0/setup/deploy.html#builtin-server?
CC @pedrobaeza

**Comment by saibhargav08** [comment]
@Yenthe666 Reg workers we don't have much load as of now
Hence we want to go with the default configuration
And also from the link provided 4 CPUs with 8 workers need 9GB so we think our configuration enough for the default configuration.

Let us know in case it is not

**Comment by pedrobaeza** [comment]
Sorry, seeing the `segfault`you have a faulty hardware or out of resources one, but that has nothing to do with Odoo itself. Anyway, workers are always advisable.

Closing this as no Odoo issue, but deployment one.
