### ISSUE TITLE
ODOO FORUM ISSUE

### ISSUE THREAD

**Issue by hilarak** [odoo/odoo#52968]
**Impacted versions:**
Latest

Steps to reproduce:
Open ODOO Help-Forum/ODOO Website

**Current behavior:**

Unknown CORS error

An unknown CORS error occurred. The error probably originates from a JavaScript file served from a different origin. (Opening your browser console might give you a hint on the error.)

**Expected behavior:**

**Video/Screenshot link (optional):**

![image](https://user-images.githubusercontent.com/24998694/84655710-7da5fb00-af22-11ea-9250-7fd903afdf52.png)

![image](https://user-images.githubusercontent.com/24998694/84656129-3f5d0b80-af23-11ea-997c-1891b7a67540.png)

**Comment by ray-odoo** [comment]
I can't reproduce.

1. Open Firefox 77.0.1 (64 bit)
2. Visit https://www.odoo.com
3. Login
4. Scroll to the bottom and click the link "Forum" under the "Community" section.

Can you add similar details to expand on "Open ODOO Help-Forum/ODOO Website" to make sure it is possible to test your exact steps and know which Browser?

**Comment by hilarak** [comment]
I am also using the same version of firefox. Yesterday I was trying to comment on a question.  Currently, I can't reproduce the client error wizard, but the error logs remaining the same.

![image](https://user-images.githubusercontent.com/24998694/84760449-172fe400-afd9-11ea-8264-d6668aa62910.png)

**Comment by caretit** [comment]
I have received this CORS error while opening elearning videos on website in odoo v14
