### ISSUE TITLE
Email notification doesn't seem to work when answered via email client

### ISSUE THREAD

**Issue by dlemireanybox** [odoo/odoo#52987]
Impacted versions: V12
**Steps to reproduce:**
2 users: user1( notif by email )  & user2 ( notif by email ) 
- From invoice in odoo , user1 create note with body like "@user 2 , Hello? " 
- From email client, user2 answer to the note with body "Hi!!!"
Current behavior:
- user1 is not notified user2 answer ( neither by odoo, or email ) 
Expected behavior:
- user1 receive an email with body = Hi!!!
Video/Screenshot link (optional):

Note that when user 1 chooses to be notified by odoo, he is notified of the response "Hi !!!" User 2

**Comment by pedrobaeza** [comment]
This is working correctly on all my deployments, so you should have something incorrect in your end, like incorrect incoming mail, catchall configuration, or other.

Closing thus as no Odoo issue unless you bring more evidences on contrary.

**Comment by dlemireanybox** [comment]
the user2 receive all message by email, even his own

**Comment by pedrobaeza** [comment]
user1 email shouldn't be correct or can be processed by your outgoing mail server.
