### ISSUE TITLE
[8.0] im_chat should not be auto_install=True

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#5299]
Why was im_chat made auto_installable? It is not useful to everyone, requires some specific setup to work correctly, and as far as I can tell is not a dependency of anything which gets installed by default. 

The current situation means that people who don't want that module need to uninstall it by hand after creating a new instance, which I feel is a hassle.

**Comment by StefanRijnhart** [comment]
+1. Also, after manual uninstallation, doing an --update all brings it back again if I am not mistaken.

**Comment by ludwiktrammer** [comment]
+1 That's also an annoying issue for us.

**Comment by jssuzanne** [comment]
+1, it is cause of the odoo support by chat, this functionality is a great
functionality in saas, but not in the custom integration

2015-02-17 15:11 GMT+01:00 Ludwik Trammer <notifications@github.com>:

> +1 That's also an annoying issue for us.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/odoo/odoo/issues/5299#issuecomment-74672771>.
>



-- 

Jean-Sébastien SUZANNE

jssuzanne@anybox.fr

**Comment by jssuzanne** [comment]
Alexandre, in the upgrade script of the recipe, you can uninstall the module

2015-02-17 15:39 GMT+01:00 Jean-Sébastien Suzanne <jssuzanne@anybox.fr>:

> +1, it is cause of the odoo support by chat, this functionality is a great
> functionality in saas, but not in the custom integration
>
> 2015-02-17 15:11 GMT+01:00 Ludwik Trammer <notifications@github.com>:
>
>> +1 That's also an annoying issue for us.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/odoo/odoo/issues/5299#issuecomment-74672771>.
>>
>
>
>
> --
>
> Jean-Sébastien SUZANNE
>
> jssuzanne@anybox.fr
>
>


-- 

Jean-Sébastien SUZANNE

jssuzanne@anybox.fr

**Comment by antonylesuisse** [comment]
Just uninstall the module it's not a bug and v8 is now an old stable serie in bugfix mode only.
