### ISSUE TITLE
Advance invoice put tax or not on invoice line according to type of advance

### ISSUE THREAD

**Issue by qtheuret** [odoo/odoo#530]
I saw an issue on Odoo when I invoice a confirmed sale order.

I made a SO with one line with one product with unit price = 1800.00 and add a 20.0% tax on this line. So the total amount of the SO is 2160.00.

I click on create invoice, choose 'Percentage' and put 50 % as percentage. Then, the invoice is created with one line of 1080.00 without tax, so the total amount of this invoice is 1080.00.
I go back to the sale order and click on 'Create invoice' button, at this time, I choose 'Fixed price', keep default 'Advance' product and put 1080 (50%) of total as advance amount. Then click on 'create invoice' button. An invoice is created with one line with 1800.00 as price and a tax of 20.0 so the total amount of this invoice is 1296.00.
The sale order is then invoiced as more than 100 % and I can still create a new invoice that invoiced the 'whole sale order'. But this invoice has a negative total amount !!!

Please see why the two kind of advance invoice method doesn't have the same behavior with the taxes and why I can create a negative invoice (but it is linked to the problem of taxes).

Please see the screencast at : https://cloud.quentin-theuret.net/public.php?service=files&t=f0ef96f444f2e2c70574956602810b21

Regards,

**Comment by markusr** [comment]
We have the same problem. As a workaround we calculate manually the according net amount and select the correct tax by hand.

A automatic solution would be preferred.

**Comment by elacunza** [comment]
Hi all,

We're seeing this problem too. I think this is quite a basic feature, how is it that Odoo developers haven't even replied to the issue?

**Comment by mylbco** [comment]
Having the same problem !

**Comment by elacunza** [comment]
I have fixed this issue in our fork, so that invoice has one line for each sale order line, each one with the correct tax.
https://github.com/binovo/OCB/commit/4d24e5855baba6545e0dfa5f21353a5ece30b46a

**Comment by elacunza** [comment]
Changed PR to #6073

**Comment by Yenthe666** [comment]
Dear @qtheuret,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe

**Comment by elacunza** [comment]
Yenthe666, if you're trying not to receive feedback from community, I must say you're doing it very well! There was no Odoo 6.0, 6.1 nor 7.0!!

**Comment by Yenthe666** [comment]
Hi @elacunza,

I'm not sure what you mean? Do you mean that I'm closing issues while there is no tag telling which Odoo version it is? Odoo 8 was launched on july 7, 2014 which makes this issue an unsupported one.
This is just an attempt to clean up the Odoo issues and to filter out old ones. If the issue still persist the creator (or anybody else in fact) is free to create a new issue against V8, V9 or V10.

Regards,
Yenthe

**Comment by elacunza** [comment]
You can look at my PR that is in fact for 8.0 #6073 . I don't see any way to tag this issue for v8...
