### ISSUE TITLE
portal module should not be autoinstalled

### ISSUE THREAD

**Issue by StefanRijnhart** [odoo/odoo#5303]
Odoo works fine without the Portal (most of our instances run without it). Having the invitation to inspect records online under every outgoing chatter message is embarrassing for instances that run behind a firewall.

Please set autoinstall to False for this module.

**Comment by Yenthe666** [comment]
+1, this shouldn't be installed as default. This is very annoying and most people that use Odoo do not even know it is automaticly included.

**Comment by antonylesuisse** [comment]
Just uninstall the module it's not a bug and v8 is now an old stable serie in bugfix mode only.
