### ISSUE TITLE
[8.0] no tax code pulled from product when creating PO out of call fo bid

### ISSUE THREAD

**Issue by jdegoy** [odoo/odoo#5307]
When creating a draft PO upon selection of a product with supplier tax it will complete the PO line accordingly.
When creating a draft PO starting from a call for bid for a product with supplier tax it will NOT complete the PO line accordingly.

![image](https://cloud.githubusercontent.com/assets/11032154/6215462/411c4236-b601-11e4-8507-3b510233dd81.png)
![image](https://cloud.githubusercontent.com/assets/11032154/6215465/4eaad462-b601-11e4-9de6-2592495287f3.png)
![image](https://cloud.githubusercontent.com/assets/11032154/6215467/52ba195a-b601-11e4-9d98-ef4f63af94e6.png)
![image](https://cloud.githubusercontent.com/assets/11032154/6215469/564279e6-b601-11e4-9fd3-131860feabba.png)
![image](https://cloud.githubusercontent.com/assets/11032154/6215472/59b8f62c-b601-11e4-9bf7-23a4ecd11e8c.png)

**Comment by jdegoy** [comment]
http://50611-8-0-85ede1.runbot7.odoo.com/
TE00004 => PO00036 & TE00005 => PO00037. No taxes pulled in on the Draft PO. Not fixed?

**Comment by nle-odoo** [comment]
Sorry, it should be wih [this new commit](https://github.com/odoo/odoo/commit/c40d5065faaf7afcb0552b23af66f5cb3f7dc1bc) on 8.0.
