### ISSUE TITLE
Problem with Manufacturing and Warehouse pull-rules in Odoo 8?

### ISSUE THREAD

**Issue by ramihelal** [odoo/odoo#5308]
My problem is when I tried to create a procurement rules (pull-rules) to get raw materials from the "Raw Materials" warehouse with every manufacturing order, and after then put the finished product in the "End Products" warehouse. 
My warehouses' design is to define three locations;

"RAW" for the "Raw Materials" warehouse
"MNF" for the "Manufacturing" warehouse, and
"END" for the "End Products" warehouse.
I tried many many times with no use.

**Comment by jco-odoo** [comment]
This is a question for the forum, not here.
