### ISSUE TITLE
Sorting of many2many fields use only one field from _order

### ISSUE THREAD

**Issue by funkring** [odoo/odoo#531]
Bugfix, Patch
==========

<pre>
### Eclipse Workspace Patch 1.0
#P odoo
diff --git openerp/osv/fields.py openerp/osv/fields.py
index 76afec4..12d20da 100644
--- openerp/osv/fields.py
+++ openerp/osv/fields.py
@@ -829,7 +829,10 @@
         if where_c:
             where_c = ' AND ' + where_c
 
-        order_by = ' ORDER BY "%s".%s' %(obj._table, obj._order.split(',')[0])
+        order_by = []
+        for t in obj._order.split(','):
+            order_by.append('"%s".%s' % (obj._table, t.strip()))
+        order_by = " ORDER BY %s" % ",".join(order_by)
 
         limit_str = ''
         if self._limit is not None:
</pre>

**Comment by Yenthe666** [comment]
Dear @funkring,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe

**Comment by ethanfurman** [comment]
Thank you, funkring!  I added your patch to my copy of v7.
