### ISSUE TITLE
Develop v12 -> v13 upgrade procedure for Odoo Community version

### ISSUE THREAD

**Issue by dthapostle** [odoo/odoo#53102]
Impacted versions:
v12, v13
Steps to reproduce:
- install and configure Odoo CE v12
- install Odoo CE v13 and configure it to point on v12 database
Current behavior:
- Odoo v13 fails with following error:
```ERROR dynamo odoo.sql_db: bad query: SELECT "website_rewrite".id FROM "website_rewrite" WHERE ((("website_rewrite"."active" = true)  AND  ("website_rewrite"."redirect_type" in ('308','404')))  AND  ("website_rewrite"."website_id" IS NULL   OR  ("website_rewrite"."website_id" = 1))) ORDER BY "website_rewrite"."id"
ERROR: relation "website_rewrite" does not exist
LINE 1: SELECT "website_rewrite".id FROM "website_rewrite" WHERE (((... 
```

Expected behavior:
There'd be either the script or at least manual with details about new DB version changes.
It'd be preferable to have manual for DB upgrade.

Video/Screenshot link (optional):

**Comment by tsabi** [comment]
Odoo have a commercial service to upgrade databases. CE is not supported, you need to buy the Enterprise Edition.

**Comment by pedrobaeza** [comment]
Exactly, so closing as expected behavior.

**Comment by dthapostle** [comment]
> Odoo have a commercial service to upgrade databases. CE is not supported, you need to buy the Enterprise Edition.

I know. I see that many developers work on open-source version of Odoo. I think that w/o any upgrade option Community version has significant disadvantage. So it looks like one-way road: open-source contributors put their efforts to Odoo for free but Community version is not fully usable: you can't upgrade to latest  Community version.

**Comment by Yenthe666** [comment]
It has always been the case and will probably always stay the case too.
If you want an open source alternative look at OpenUpgrade (https://github.com/OCA/OpenUpgrade)
