### ISSUE TITLE
Typo in product/i18n/de.po - "Mininale"

### ISSUE THREAD

**Issue by slu-010101** [odoo/odoo#5311]
Typo in de.po

wrong: Mininale
right: Minimale

odoo-8.0-20150216

--- de.po	2015-01-27 02:25:52.000000000 +0100
+++ de.po_new	2015-02-16 18:13:25.169250636 +0100
@@ -2296,7 +2296,7 @@ msgstr "Min. Bestellmenge"
 #. module: product
 #: field:product.supplierinfo,min_qty:0
 msgid "Minimal Quantity"
-msgstr "Mininale Menge"
+msgstr "Minimale Menge"
 
 #. module: product
 #: model:product.public.category,name:product.Modem_Router

**Comment by mart-e** [comment]
Hello,

The translations are handled on Transifex, not on Github. Please see the [wiki page](https://github.com/odoo/odoo/wiki/Translations) about translation for details.
