### ISSUE TITLE
Many2many problem in onchange method from any field

### ISSUE THREAD

**Issue by sandeepksrana** [odoo/odoo#5314]
HI 
there is a problem, a many2many field value get False in onchange of any field in that current form and if many2many is linked to current object

i have many2many field in hr.employee  which is also related to hr.employee but it get false in any onchange method in employee form while i have other many2many but they does'nt get False because they linked to different object 

Problem in only version 8 

have any one you faced the same problem...
plz odoo R&D team please check this issue.   

Thanks
Sandeep

**Comment by Sameer1990** [comment]
Please provide more details and any code to this issue to anyone help you in your problem

**Comment by sandeepksrana** [comment]
What kind of details everything i mentioned

**Comment by Sameer1990** [comment]
Your code at least , to make anyone help you .

**Comment by sandeepksrana** [comment]
Code is same as do, thing is that...  i return in onchange value only one field like  {'value':{'one_field':'value'}
but there is one many2many field which get effect or get false if some value already  in may2many

hope you understand

**Comment by Sameer1990** [comment]
I have face this issue now on hr.employee : 
scenario : 
1 - from employee create
2 - change manager field (manager field is many2one field on hr.employee) 
3 - change department will set manager to false .
I figure that onchange_department_id will effect on manager field  .

Hope that help you

**Comment by sandeepksrana** [comment]
no sameer,  i am talking about man2many field, just take you scenario suppose 
1.  on change trigger on department 
2.  and manger are more then one for a employee ( many2many related to hr.employee )
3.  and you fill up manager with two 
4.  now you can save and edit again and change department then mangers will get automatically False 
you can try to add m2m related hr.employee and check... it is happening to m2m related employee

i don't no why

**Comment by Sameer1990** [comment]
On my scenario : (many2many or many2one)
The onchange_department_id function effect on magaer_id field in source code .
It work like this : if you set manager field to one or two managers then change the department_id then onchange function will get the manager of this department  and set it to manager field , so if the department has not any manager then will return False for manager field .

**Comment by sandeepksrana** [comment]
Hi Sameer
i can understand all above things..
you can check by manual creation of some field 
1. create multi_manger field (many2many of hr.employee) in any model (my.model)
2. create other simple char field and add a onchange on that  (return just the same field or as you wish )
3. first create a record
4. suppose you add two name in (many2many of hr.employee) just save it
5. go ahead and edit that record and enter value in char field which having onchange method
6. now you will see many2many field which already having two name get False
7. hope you understand now

let me know

Thank you

**Comment by Sameer1990** [comment]
Hello , 
I create module as you mentioned : 
in .py file : 
_name = "test.module"
    _columns = {
        'name': fields.char('Name'),
        'emp_ids': fields.many2many('hr.employee', 'test_moves_rel', 'name', 'emp_id', 'Employees'),
    }

def onchange_name(self, cr, uid, ids, name, context=None):
        val = {}
        if name:
            val['name'] = name
        else:
            val['name'] = ''
            
        return {'value':val}


and .xml file : 
<record id="test_view_form" model="ir.ui.view">
            <field name="name">test.module.view_form</field>
            <field name="model">test.module</field>
            <field name="arch" type="xml">
                <form string="Test">
                	<sheet>
                		<group>
		                    <field name="name" on_change="onchange_name(name)"/>
                        	<field name="emp_ids" widget="many2many_tags"/>
                		</group>
                	</sheet>
                </form>
            </field>
        </record>

And then create record : name => myname , employee: add two emplyees , save it .
Then Edit and change the name , No False value in m2m field

**Comment by sandeepksrana** [comment]
Hi   i even made a new module as you did, and .. it is the same..

**Comment by kurkop** [comment]
Can you check in the light of #6927 and maybe confirm there? thanks.

**Comment by sandeepksrana** [comment]
This is issue related to database and i solved it with upgrade Postgresql version 9.4 and now it solved

**Comment by meswapnilwagh** [comment]
I have Postgresql version 9.4 but sill have same issue, is any one got a fix for that?

**Comment by Runwise** [comment]
The old style of writing，news nonsupport。

xml :
<field name="fields_a" on_change="employee_change(fields_a,field_b,...)"/>

py:
@api.multi
def product_id_change(self, fields_a, fields_b, ...):
    values = {'employee_ids': [1,2,3,4,5...]}
    return {'value': values}

**Comment by Runwise** [comment]
`xml:<field name="fields_a" on_change="employee_change(fields_a, fields_b)">`

or search for 'product_id_change' in your odoo project.
