### ISSUE TITLE
[master] When cancelling PO that was created from SO for MTO/Buy product, SO doesn't receive notification/exception

### ISSUE THREAD

**Issue by Rad0van** [odoo/odoo#53196]
Impacted versions: master

Steps to reproduce: Create and confirm Sale Order with a product that is marked as MTO and Buy and none is in stock. Purchase Order is created automatically. 

Current behavior: If you cancel SO, notification of exception is brought to PO. But if you cancel PO no notification of exception is brought to SO even the code to do so is there in sale_purchase module in PurchaseOrder's _activity_cancel_on_sale but purchase_line.sale_line_id is not present so it doesn't get to the point of notifying the SO.

Expected behavior: It should work both ways - i.e. if PO is cancelled SO should be notified as well.

I guess this concerns PR #43366 so maybe @ryv-odoo or @sle-odoo could have something to say. Thank you.

**Comment by pedrobaeza** [comment]
Please don't open issues on master, as it's a version in development that for sure will contain a lot of bugs. Only when the release is close is reasonable to put them for hunting latest bugs.

**Comment by Rad0van** [comment]
> Please don't open issues on master, as it's a version in development that for sure will contain a lot of bugs. Only when the release is close is reasonable to put them for hunting latest bugs.

@pedrobaeza I normally wouldn't but I am also working on backporting that PR to 13.0 so I guessed I'd give it a try. Thanx for the info.

**Comment by pedrobaeza** [comment]
For that cases, I think it's more interesting to comment on the PR (although already merged), as it reaches to the involved people, instead of an issue that doesn't notify by default (and pinging them on the issue is a workaround).

**Comment by Rad0van** [comment]
> For that cases, I think it's more interesting to comment on the PR (although already merged), as it reaches to the involved people, instead of an issue that doesn't notify by default (and pinging them on the issue is a workaround).

Thanx for the idea! Will do.
