### ISSUE TITLE
[regression] Compute function no longer run in draft mode on a related model

### ISSUE THREAD

**Issue by ludwiktrammer** [odoo/odoo#5319]
I've got a model A form with a one2many field related to model B, that can be edited inline (`<tree editable="true">`) directly in the model A form. Model B has a non-stored computed field that is present as a column in the one2many field's inline tree view. 

Before @rco-odoo's commit 2067a206ecba9a8dbf7f76a55926be964e580e7e when one clicked "Add an item" in the inline o2m tree view (to create a new model B object), the computed method was always run (in draft mode, because the new object is not saved to the db yet at this point) and the computed value was presented in the inline tree view. After 2067a206ecba9a8dbf7f76a55926be964e580e7e this broke. The computed method is never run in draft mode at all. It is only run after the whole model A form is saved. 

This is the module I'm experiencing this problem with: [bestja_requests](https://github.com/EE/bestja/tree/master/addons/bestja_requests). "Model A" from the example is called `bestja_requests.request` and "model B" is called `bestja_requests.item`. The compute function that is no longer run in draft mode after 2067a206ecba9a8dbf7f76a55926be964e580e7e is called `compute_template` - the one with a very long comment on top.

**Comment by Yenthe666** [comment]
Hi @ludwiktrammer,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
