### ISSUE TITLE
Stock rule issue with itertools._grouper object (Python)

### ISSUE THREAD

**Issue by Manuel-Dellisse** [odoo/odoo#53247]
Hi,

Discovered an issue with the groupby-function in the stock rules "_run_buy"-method. (Might possibly the case in other locations)
The usage of the `from itertools import groupby` (Python) instead of `from odoo.tools import groupby` (Odoo custom) gives different behaviour with possibly great impact.
The problem is that the Python groupby-function returns a generator-function which consumes on each iteration and only keeps values of the last iteration.
This means that there's is "data" loss and further manipulation is inconsistent, in this case "_find_candidate"-method gets only part of the PO lines.
The Odoo groupby-function returns a list with all the records and feeds the "_find_candidate"-method with all the PO lines.
Most likely fix would be using the Odoo tools groupby instead of the Python itertools groupby.

![image](https://user-images.githubusercontent.com/6159662/85027720-842eaf80-b17a-11ea-81bd-64793aa4a03e.png)
![image](https://user-images.githubusercontent.com/6159662/85027868-b3452100-b17a-11ea-9864-cfeb817eda6c.png)

After using the Odoo import

![image](https://user-images.githubusercontent.com/6159662/85028247-1d5dc600-b17b-11ea-8717-2a3fec5b1f2b.png)
![image](https://user-images.githubusercontent.com/6159662/85028365-45e5c000-b17b-11ea-8f7c-7f1e4677aab8.png)

https://github.com/odoo/odoo/blob/dfb65113293aa21b29bd6dfdfaaef05e70bce3eb/addons/purchase_stock/models/stock_rule.py#L6
https://github.com/odoo/odoo/blob/dfb65113293aa21b29bd6dfdfaaef05e70bce3eb/addons/purchase_stock/models/stock_rule.py#L96

Hopefully this is sufficiently clear, if not don't hesitate to contact me.

I'm looking forward from hearing you.

Sincerely,
Accomodata, Manuel Dellisse
manuel.dellisse@accomodata.be

**Comment by pedrobaeza** [comment]
Odoo version?

@sle-odoo @amoyaux for you

**Comment by Manuel-Dellisse** [comment]
In my case it's in Odoo v13.0

**Comment by amoyaux** [comment]
Hello. I don't really get it. We browse the generator and set every value in the dict. Even if the generator discard it afterward, it should still be present in the dict. Do you have a work flow that is not working?

**Comment by Manuel-Dellisse** [comment]
As shown in the above screenshots while debugging, we can see that the PO consists of two different products.
The PO has 9 lines total but `po_lines_by_product` only contains 3 lines total, which isn't clear to me as why product_id 233 has two lines.
Afterwards those po_lines_by_product are used as explained in `_find_candidate` for further filtering.

Some changes have been made in the way dropshipment works by allowing multiple origins on the same PO. Could explain why this is required but it's quiet long and complex.
Standard each procurement group has it's own separate PO, but in our case we have to allow "merging" multiple SOs on the same dropshipment.

What I want to point out is that the generator is creating inconsistencies in that part of the code and has shown great impact in our perhaps specific case.

Hopefully this helps a little? In anyways we can go on, but just wanted to point that out for maybe in the future.

Thanks you for your time.

**Comment by amoyaux** [comment]
Strange. It's maybe the sorted method which is not correct. Since the groupby only group adjacent key, it could remove existing one that would explain why the list miss some data.
You can easily check also by replacing
```python
po_lines_by_product = {}
```
by
```
po_lines_by_product = defaultdict(lambda: self.env['purchase.order.line'])
```

also
```
po_lines_by_product[product] = self.env['purchase.order.line'].concat(*list(po_lines))
```
```
po_lines_by_product[product] |= self.env['purchase.order.line'].concat(*list(po_lines))
```

Or if you an easy way to reproduce it on an test database we could analyze it our self.

**Comment by amoyaux** [comment]
Ok I found the issue. The sorted in odoo do not work like we did. We should replace it by
sorted(key=lambda r: r.product_id). This way it will work with classic python itertools. I will fix it.
Thanks for reporting
