### ISSUE TITLE
State of purchase.order.line issue

### ISSUE THREAD

**Issue by Botakely** [odoo/odoo#53253]
Impacted versions: 13

Steps to reproduce: Create a purchase.order

Current behavior: The state of purchase.order.line is not set

Expected behavior: The state of purchase.order.line should get the value of the state of purchase.order
This is the declaration of the field state in purchase.order.line:
state = fields.Selection(related='order_id.state', store=True, readonly=False)

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Is that happening with latest v13 code?

**Comment by Botakely** [comment]
I think so
Anyway, it's happening on runbot

**Comment by pedrobaeza** [comment]
@rco-odoo can you comment about this?

**Comment by sswapnesh** [comment]
Seems working well https://3203453-13-0-e220c5.runbot38.odoo.com/web?debug=1#id=10&action=755&model=purchase.order&view_type=form&cids=1&menu_id=534

![screenshot-3203453-13-0-e220c5 runbot38 odoo com-2020 06 18-22_38_29](https://user-images.githubusercontent.com/16624719/85050937-7d249300-b1b4-11ea-8f5b-f47ff404b76f.png)
![screenshot-3203453-13-0-e220c5 runbot38 odoo com-2020 06 18-22_39_15](https://user-images.githubusercontent.com/16624719/85051036-9dece880-b1b4-11ea-88e6-a1f25060fe20.png)

**Comment by pedrobaeza** [comment]
Well, I think he means while working in ORM. I remember this to happen when working with `new()` records, and that's why I have tagged directly.

**Comment by Botakely** [comment]
![image](https://user-images.githubusercontent.com/51913832/85053859-cfa98380-b1a3-11ea-9a43-c98ed3c145d9.png)
You can try to create a new purchase order here and see the bug.
https://3203236-master-c27228.runbot29.odoo.com/web?debug=1&fbclid=IwAR1u-SAeZii1A91TD7NFI7s13ttrk2L7hJt_cSvPN3IHxSgJIS0YPEX1urU#action=744&cids=1&id=11&menu_id=543&model=purchase.order&view_type=form

**Comment by pedrobaeza** [comment]
Hey, wait a minute! That's not version 13, but current master, so that's something not totally unexpected, as it's a development version, and there can be problems with it, but no reports can't be done over that version unless the release date is very close (which is not the case).

Closing then.

**Comment by Yenthe666** [comment]
Good catch Pedro, you really are some kind of robot 😉

**Comment by Botakely** [comment]
Well I can reproduce it in our odoo.sh platform and in this version.

> Seems working well https://3203453-13-0-e220c5.runbot38.odoo.com/web?debug=1#id=10&action=755&model=purchase.order&view_type=form&cids=1&menu_id=534
> 
> ![screenshot-3203453-13-0-e220c5 runbot38 odoo com-2020 06 18-22_38_29](https://user-images.githubusercontent.com/16624719/85050937-7d249300-b1b4-11ea-8f5b-f47ff404b76f.png)
> ![screenshot-3203453-13-0-e220c5 runbot38 odoo com-2020 06 18-22_39_15](https://user-images.githubusercontent.com/16624719/85051036-9dece880-b1b4-11ea-88e6-a1f25060fe20.png)

**Comment by pedrobaeza** [comment]
Please specify which version is mentioned there.

**Comment by Yenthe666** [comment]
And if you're on SH you can also use the enterprise support at odoo.com/help anyways.

**Comment by Botakely** [comment]
I tried in runbot again.

This is the version shown in setting
![image](https://user-images.githubusercontent.com/51913832/85109786-9102e000-b21a-11ea-98ba-cb5c72b34a65.png)

And this is screenshoot showing that I reproduce it again:
![image](https://user-images.githubusercontent.com/51913832/85110012-eccd6900-b21a-11ea-8f95-6e4329b27a7c.png)

This is the link of my purchase order on runbot:
https://3203996-13-0-03fb98.runbot29.odoo.com/web?debug=1#id=10&action=755&model=purchase.order&view_type=form&cids=1&menu_id=534

**Comment by pedrobaeza** [comment]
That's because you have added the field with readonly=0, giving priority to the value in screen. Changing the declaration works perfectly:

https://3203996-13-0-03fb98.runbot29.odoo.com/web?debug=1#id=12&action=755&model=purchase.order&view_type=form&cids=3&menu_id=534

**Comment by pedrobaeza** [comment]
FYI the problem in saas-13.4 is being fixed in #53898
