### ISSUE TITLE
[8.0] buttons "modify event" and "delete" are duplicated in calendar view when click on the workflow button

### ISSUE THREAD

**Issue by sergueikp** [odoo/odoo#5327]
Version Odoo 8.0
How to reproduce the bug : 
1. Install Openacademy module (or reproduce it like in the tutorial https://www.odoo.com/documentation/8.0/howtos/backend.html#advanced-views)
2. Add workflow
3. Create a Course and at least one session
4. Configure session.calendar view to open a popup when clicking on the session event in the calendar, by adding between "calendar" tags : event_open_popup="True"
5. In Open Academy > Sessions > select Calendar view > Click on a Session
6. In the opened popup click on any of work-flow button : "Confirm" or "Reset to draft" or "Mark as done"

Every time you click on the workflow button,  buttons "Modify event" and "Delete" are duplicated (see the screen shot)

![odoo_bug_workflow_modif_in_calendar_view](https://cloud.githubusercontent.com/assets/9844780/6236217/c98043ec-b6e8-11e4-9cfa-a2be00bbc41e.JPG)

**Comment by mart-e** [comment]
Hello,

Thank you for your contribution but the version 8.0 is no longer supported. We only support the last 3 stable versions so no longer accepts patches into this branch.
We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.
Regards
