### ISSUE TITLE
Confirm attribute on button does not support HTML tags parsing

### ISSUE THREAD

**Issue by mohdshoaib04** [odoo/odoo#53287]
Impacted versions: V11 (enterprise)

Steps to reproduce: Add confirm attribute to a button with HTML tags in CDATA, It wont be parsed and will be shown as it is.

Current behavior:
Does not parse HTML tags

Expected behavior:
Should parse HTML tags

Video/Screenshot link (optional):
```
<xpath expr="//button[@name='confirm_requisition']" position="attributes">
            	<attribute name="confirm">
            	<![CDATA[
            		XXXXXXXXXXXXXXXXXXXXXXXXXXXX<br />
	            	A)XXXXXXXXXXXXXXXXXXXXXXXXX<br />
			B)XXXXXXXXXXXXXXXXXXXXXXXXX<br />
			C)XXXXXXXXXXXXXXXXXXXXXXXX<br />
					Can you confirm ?
					]]>
				</attribute>
            </xpath>
```
Ref:
![image](https://user-images.githubusercontent.com/33711872/85117915-38910a00-b23d-11ea-9b33-4ab3a05e7d6c.png)

**Comment by pedrobaeza** [comment]
Yes, this is a know limitation. You can only put plain text. There are no plans AFAIK to change this.

Closing as expected behavior.
