### ISSUE TITLE
8.0 multi-company: pricelist from wrong company on PO generated by procurement scheduler

### ISSUE THREAD

**Issue by alexis-via** [odoo/odoo#5329]
Here is the scenario of the bug on odoo 8.0:
1) setup a multi-company environnement with at least 2 companies : A and B
2) generate a new procurement in company A that will generate a purchase order when the scheduler will run
3) login as admin user and switch to company B
4) wait for the procurement scheduler to run (by default, the procurement scheduler is executed by the admin user)
Once the procurement scheduler has run, you will see a new PO in company A, but this PO has 2 problems:
- the "pricelist_id" of the PO is from company B
- as a consequence, the "currency_id" is from company B (if your currencies are associated to companies)

Code analysis : in addons/purchase/purchase.py line 1324, the make_po() method of the object procurement_order is executed by the scheduler ; for the pricelist_id field, it will get partner.property_product_pricelist_purchase.id and property_product_pricelist_purchase is a property field that has a different value for each company, but as the scheduler is executed by the admin user in company B, the pricelist_id will be from company B.

**Comment by beledouxdenis** [comment]
Closed with #5330.
