### ISSUE TITLE
7.0/8.0 PLZ Currency code doesn't exists - remove it from selection

### ISSUE THREAD

**Issue by grzegorz-openglobe** [odoo/odoo#533]
Short description of the issue
- I noticed from version 7.0 that someone added currency with code PLZ. Such currency code doesn't exist in the world. It is old Polish Zlotys code (till 31.12.1994) which is no longer used. It is not used for many years and there is no reason to keep it even for historical rates.

For Poland currency code is PLN and it is only code to use. By now standard installation of OpenERP contains two codes for polish zloty PLN and PLZ. PLZ appears as default polish currency in OpenERP what misleads polish customers.

Can you remove PLZ currency from OpenERP standard installation? And leave just PLN as default polish currency?
***Impacted versions:***
7.0/8.0
***Steps to reproduce:***
Install any db with polish accounting package
***Current behavior:***
Default currency is PLZ
***Expected behavior:***
Default currency should be PLN.
PLZ code should be removed from list at all.

**Comment by Yenthe666** [comment]
Dear @grzegorz-openglobe ,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.
P.S: This also looks fixed.

Regards,
Yenthe
