### ISSUE TITLE
Wrong documentation

### ISSUE THREAD

**Issue by SplashS** [odoo/odoo#53303]
Impacted versions: odoo-13.0

Steps to reproduce:
Go to https://www.odoo.com/documentation/13.0/reference/data.html#template

Current behavior:
There is optional attribute "page". But there is no handling code in core.

Expected behavior:
There is no optional attribute "page" in documentation or there is handling code.

And additional question:
How to create theme.website.page in Theme? Only via &lt;record&gt;? Is there any shortcut options?

**Comment by JKE-be** [comment]
Not a bug.

Doc is not uptodate.
We plan to refresh it before the end of the year. 

For now, the code is the best documentation.

ps: no shortcut for theme.website.page

thx
