### ISSUE TITLE
DHL Fails on getting quote

### ISSUE THREAD

**Issue by eknoch** [odoo/odoo#53357]
Impacted versions: odoo enterprise 13

Steps to reproduce: request shipping rate on quote using DHL Option

Current behavior: fails with error

Expected behavior: provide rate

Video/Screenshot link (optional): https://drive.google.com/file/d/1Q0PoCrnobxeIWoU-WEMB-nJ--Azi39n5/view

**Comment by pedrobaeza** [comment]
As this is an enterprise module, and needs reproducible steps (it's not enough with the information provided), please report it through odoo.com/help instead of here, so closing.
