### ISSUE TITLE
[MRP] Manufacturing order is blocked due to same Lot

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#53368]
Impacted versions: 12/13

Steps to reproduce: 
* Create Product Tracked by Unique Serial
![screenshot-3241280-13-0-aba0b2 runbot38 odoo com-2020 06 21-21_18_43](https://user-images.githubusercontent.com/16624719/85229057-2feb3000-b405-11ea-9ebd-7ce142c0798d.png)

* Create Bom and MO for the same Product
* Product MO and Mark as Done
![screenshot-3241280-13-0-aba0b2 runbot38 odoo com-2020 06 21-21_21_53](https://user-images.githubusercontent.com/16624719/85229068-42fe0000-b405-11ea-9fa5-5f760e052fac.png)

* Create MO for same product --> Produce --> Select same Lot number
![screenshot-3241280-13-0-aba0b2 runbot38 odoo com-2020 06 21-21_22_38](https://user-images.githubusercontent.com/16624719/85229084-5d37de00-b405-11ea-97cf-5db6884fdb4b.png)
 * Mark as Done

Current behavior: 
Order is blocked and there is no way to change Lot number,

> A serial number should only be linked to a single product.

This is because the Product is Tracked by Unique Serial so we cant use the same serial number.

Expected behavior: This check should be Performed when we click on `Produce` or to be able to change lot number.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
I'm not getting the exact problem. Why can't you unlock the MO and change the serial number?

**Comment by sswapnesh** [comment]
My bad. you are Right. (We can unlock and change)

Unlock/Lock behavior is still not aligned ref https://github.com/odoo/odoo/issues/21904

**Comment by sswapnesh** [comment]
Added https://github.com/odoo/odoo/pull/53463 to make this work.
