### ISSUE TITLE
how to install my new odoo 13 enterprise on mac catalina 

### ISSUE THREAD

**Issue by satriaone** [odoo/odoo#53374]
Impacted versions: 13

Steps to reproduce: 

Current behavior:

Expected behavior:
![2019 odoo cant find server](https://user-images.githubusercontent.com/3284345/85254189-e5f85d80-b489-11ea-8206-f30806b14323.jpg)

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Please follow https://www.odoo.com/documentation/13.0/setup/install.html#mac-os
