### ISSUE TITLE
[Time Zone] Africa/Khartoum timezone is wrong

### ISSUE THREAD

**Issue by obayit** [odoo/odoo#53373]
**Impacted versions:**
13.0, 12.0, 11.0 (maybe all of them)
**Steps to reproduce:**
Change timezone to 'Africa/Khartoum'
**Current behavior:**
The offset is +3
**Expected behavior:**
The offset should be +2
**Screenshot:**
![screenshot-gsk-erp com-2020 06 22-06_02_36](https://user-images.githubusercontent.com/20386024/85247429-030f3b00-b44e-11ea-9e6a-2e6aa63ba748.png)

I live in Khartoum, thus the warning shouldn't show.

**Short Description:**
See this answer https://stackoverflow.com/a/11474330/3557761
And this bug report https://bugs.launchpad.net/ubuntu/+source/python-tz/+bug/1884458

**Long Description:**

I tried to print a purchase report to confirm this, and the time was +3 (instead of +2).

Screenshot of 'Scheduled Date' in the browser (+2)
![screenshot-localhost_8069-2020 06 22-06_10_52](https://user-images.githubusercontent.com/20386024/85247792-37372b80-b44f-11ea-9174-e072df2d5881.png)

[Request for Quotation - PO00011.pdf](https://github.com/odoo/odoo/files/4811083/Request.for.Quotation.-.PO00011.pdf)

This is probably because of how pytz works:

Odoo gets the timezone offset with this line of code:
https://github.com/odoo/odoo/blob/aba0b299243c3d9b4615e1066d641aa8360aabac/odoo/addons/base/models/res_partner.py#L254

Another one for res.users:
https://github.com/odoo/odoo/blob/aba0b299243c3d9b4615e1066d641aa8360aabac/odoo/addons/base/models/res_users.py#L358

**Brute Force Solution:**
[Compare link](https://github.com/odoo/odoo/compare/13.0...obayit:patch-5#diff-c087b09b8455bbf3fa546a56c6e271bcL358)

**Comment by pedrobaeza** [comment]
@mart-e can you check?

**Comment by mart-e** [comment]
Hello,

Does
```py
datetime.datetime.now(pytz.timezone('Africa/Khartoum')).strftime('%z') 
```

Are you saying returns `+0300` ?
I just tried on my side and it was `+0200`. Might it be because of outdated pytz database (the stackoverflow question talks about 2017)? What is your versions used?

**Comment by obayit** [comment]
pytz==2016.7 :D
I updated it and now it shows `+0200'
