### ISSUE TITLE
[Odoo 12.0] Domain for partner_bank_id field not set in invoice modify 

### ISSUE THREAD

**Issue by taifu** [odoo/odoo#53395]
https://github.com/odoo/odoo/blob/39c9ac02d42a9280caf41770efd2f91d096b52cf/addons/account/models/account_invoice.py#L881

This domain is set only after a change on Partner field. If I don't change the partner, I can see all partner_bank record, even those related to Contacts (res_partner) and this is a HUGE privacy problem!

**Comment by pedrobaeza** [comment]
This is a known limitation of domains through onchanges. This will change on v14, but for now not sure if it should be fixed. I don't consider it as a security problem not data leak, as you can see the same that data through other menu entry, but let's see what @qdp-odoo says about this.

**Comment by qdp-odoo** [comment]
indeed, if you want to restrict the visibility of res.partner.bank records you should add a record rule to filter them. Otherwise, those records will still show up elsewhere. 

And by default, I don't see why we'd set up such a record rule, so I'm closing the bug report.

Thanks anyway for your contribution

**Comment by taifu** [comment]
> indeed, if you want to restrict the visibility of res.partner.bank records you should add a record rule to filter them. Otherwise, those records will still show up elsewhere.
> And by default, I don't see why we'd set up such a record rule, so I'm closing the bug report.
> Thanks anyway for your contribution

You are wrong. In invoice creation Odoo correctly filters the account bank to prevent to mistakenly choose a employee bank account. In invoice editing Odoo doesn't do that because is not possibile, not because is not right.
