### ISSUE TITLE
8.0 Procurements stay in Running when partial reception of a picking generated by PO

### ISSUE THREAD

**Issue by alexis-via** [odoo/odoo#5344]
Here is the scenario of the bug on an up-to-date Odoo v8:
USB Headset and MultiMedia Speakers have the same supplier (China Export)
1) Connect on runbot v8
2) Sales > Product Variants
Edit USB Headset and activate the "Buy" Route
Edit MultiMedia Speakers and activate the "Buy" Route
3) In the same menu Product Variants :
USB Headset: Request Procurement > Qty = 1 > Ask New Products > Run Procurement
Multimedia speakers : Request Procurement > Qty 1 > Ask New Products > Run Procurement
4) Go to Purchase > Requests for quotation
Locate the draft Purchase Order for China Export: clic on "Confirm Order"
5) Clic on "Receive Products" then "Transfer" and do a partial reception:
Set the qty for "USB Headset" to 0 and clic "Apply"
Look at the procurement of the multimedia Speakers : it is still on "Running", even if the
 related stock move is done.

Let's imagine that the supplier informs us that he will never send the USB Headset, because this product is end of life:
Go to the backorder picking of China Export and clic on "Cancel"
The procurements for the 2 products are still on "running". It means that the procurement for the Multimedia Speakers will stay as running forever, even if we received the goods.

**Comment by Yenthe666** [comment]
Hi @alexis-via,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
