### ISSUE TITLE
[7] hr_payroll_account: wrong period_id in multi company senario

### ISSUE THREAD

**Issue by mohmarouf** [odoo/odoo#5347]
i found an issue while confirming the payslip
test case:
employee name "Jims"
partner name "Jims"
employee company "Emp company"

i logged in as admin whos company is "your company"
allowed company is "Emp company" and "your company"
as admin i try to confirm Jims salary slip and notice that period was wrong to fix that i found issue at line 98 on hr_payroll_account.py file  

ctx = dict(context or {}, account_period_prefer_normal=True) at line number 98
# posible solution

if context == None:
            context = {}
context['company_id'] = slip.company_id.id
ctx = dict(context or {}, account_period_prefer_normal=True)

**Comment by Yenthe666** [comment]
Hi @mohmarouf,

Thank you for your report and apologies for the late reply. 
At this point we no longer support Odoo 7, as we only support three Odoo versions at a time.
If you still face this report in a newer version (8.0, 9.0 and 10.0) please feel free to create a new bug report!

Regards,
Yenthe
