### ISSUE TITLE
[8.0] Can't modify employee

### ISSUE THREAD

**Issue by bidossessi** [odoo/odoo#5353]
## can't modify employee in Odoo

Impacted versions:
- 8.0-20150216

Steps to reproduce:
1. install odoo nightly Version 8.0-20150216 from source on Archlinux
2. run odoo.py and create new database with demo data
3. install hr module
4. modify any field in any demo employee form
5. Save

Current behavior:
- TypeError: undefined is not a constructor (evaluating 'Date.normalizeFormat(instance.web.strip_raw_chars(format))')
  ![screenshot from 2015-02-18 13 47 37](https://cloud.githubusercontent.com/assets/6638305/6247466/2248a82a-b775-11e4-9e6d-0285c5c1c468.png)
  Expected behavior:
- field takes new value

**Comment by a-da** [comment]
still the same thing in 2017 
this is happening with Phantomjs only
@bidossessi which browser have you used ?

**Comment by bidossessi** [comment]
@a-da That was [Qutebrowser](https://www.qutebrowser.org/). I've not pursued Odoo development after that.

**Comment by a-da** [comment]
Based on https://www.odoo.com/documentation/10.0/setup/deploy.html#supported-browsers

Odoo 8: IE9, Mozilla Firefox, Google Chrome, Safari, Microsoft Edge

It seems that there is no support for Phantomjs and  Qutebrowser.

@bidossessi can you close this issue ?
