### ISSUE TITLE
[12.0 e] stock: Negative quant, in current stock with availability

### ISSUE THREAD

**Issue by deivislaya** [odoo/odoo#53535]
**Impacted versions:** 12.0 e

**Steps to reproduce:**

1.  Create a new location of type internal in WH/test
2.  Create a new product test  with disponibility to hand of 100.0  in WH/stock
3.  Create a new transfer from WH/stock to WH/test with 50.0 product test and a package destination, for example, TESTPACK and validated it.
4.  Create a new transfer from WH/test to WH/Stock/Shelf 1 using TESTPACK and unpack it
5.  Repeat steps from 3 to 4
6.  Create a new transfer from WH/Stock/Shelf 1 to Customer.  with 100.0 product test
7.  Review stock quant from the location   WH/Stock/Shelf 1

**Current behavior:**

2 Quants of the same product in the location  WH/Stock/Shelf 1. One negative with -50.0 and another quant positive with 50.0    

**Expected behavior:**

Quant consumed in zero  in the location  WH/Stock/Shelf 1

**Video/Screenshot link (optional):**

1/2  https://youtu.be/U_ejEKin6Xs
2/2  https://youtu.be/mhDU0X7xfi4

**OPW #2283707**

**Comment by moylop260** [comment]
@JayVora-SerpentCS helpful comment
  - https://github.com/OCA/stock-logistics-workflow/pull/675#issuecomment-653022411
    - `Good catch! Should not the code be added upon unpack() process itself? ( override it and check) ?`
