### ISSUE TITLE
[8.0] Accounting configurations is broken

### ISSUE THREAD

**Issue by bidossessi** [odoo/odoo#5357]
**Accounting configurations page is broken**

Steps to reproduce:
1. install 8.0-20150216 from nightly
2. start odoo and create new database
3. install l10n_syscohada (possibly any?) accounting package
4. Go to Settings - Configuration - Invoicing
5. Change any setting and press apply or cancel

Current behavior:
![screenshot from 2015-02-18 14 47 32](https://cloud.githubusercontent.com/assets/6638305/6248218/76c75a38-b77d-11e4-96d3-55aaa846075d.png)

Expected behavior:
- requested changes applied

**Comment by Yenthe666** [comment]
Hi @bidossessi,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
