### ISSUE TITLE
Procurement: run scheduler failed to finish

### ISSUE THREAD

**Issue by akloptim** [odoo/odoo#53622]
Impacted versions: V12 Odoo.sh 

Steps to reproduce: Run the scheduler manually or Wait until the execution time

Current behavior: Now the procurement scheduler works and reserving available products to stock move. But it not finishing and Next Execution Date not updating. While inspecting database queries, the scheduled query still active and keep in an ideal state.  Also, the scheduler now trying to update **remaining_qty** and **remaining_value** of old return moves. I think the issue comes with a recent Commits on Jun 19, 2020 (commit: [FIX] stock: reserved quantity on return of return, ID: 35ceaf0336dec281a27d704f2fd39360094d1464). 

Expected behavior: Smooth running of Procurement scheduler and update of next execution date

Video/Screenshot link (optional):
Log from pg_activity 
![stock picking issue](https://user-images.githubusercontent.com/38882169/85663942-5be70980-b6c2-11ea-98ba-abb38e85a00c.png)

**Comment by pedrobaeza** [comment]
Are you sure you don't have any custom server action in your DB linked to `stock.move` update?

**Comment by akloptim** [comment]
Nothing

**Comment by pedrobaeza** [comment]
Can you revert before that commit again to check if it finishes?

@sle-odoo @amoyaux FYI

**Comment by akloptim** [comment]
> Can you revert before that commit again to check if it finishes?
> 
> @sle-odoo @amoyaux FYI


> Can you revert before that commit again to check if it finishes?
> 
> @sle-odoo @amoyaux FYI
I can't revert the commit because the server hosted in Odoo.sh. But I am sure my Procurement scheduler's Next Execution Date not changed after the last commit.

**Comment by sle-odoo** [comment]
This commit should not break the scheduler, it only touches to the return moves generation. Your issue is probably elsewhere and i'd suggest to open a ticket on the regular channel so that the support can inspect your database.

Regards
