### ISSUE TITLE
[8.0] action.name instead of action.display_name

### ISSUE THREAD

**Issue by funkring** [odoo/odoo#5363]
addons/web/static/src/js/views.js 
action.name is used for title instead of action.display_name
action.name is not translated

**Comment by flotho** [comment]
+1, Actually it's the same issue on the 7.x !

**Comment by flotho** [comment]
Hy @funkring , I think that #5277 solved this issue.

**Comment by funkring** [comment]
Thanks for the Info

---
Funkring.net

Ing. Martin Reisenhofer
Unterrohr 10
A-8294 Rohr bei Hartberg

Tel   +43 (0) 3332 86 927 11
Fax   +43 (0) 3332 86 927 99
Mail  martin.reisenhofer@funkring.net

**Comment by Yenthe666** [comment]
Hi @funkring ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
