### ISSUE TITLE
Stock Valuation & Sales Analysis Report Modification

### ISSUE THREAD

**Issue by orchidinfosys** [odoo/odoo#537]
Adding product template grouping in Stock Valuation and other sales reports will provide another dimension of products. Other wise product variant features will not be utilised fully.

**Comment by Yenthe666** [comment]
Dear @orchidinfosys,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
