### ISSUE TITLE
DHL Delivery should not require administration/settings right

### ISSUE THREAD

**Issue by jguerriat** [odoo/odoo#53709]
Impacted versions:
13.0

Steps to reproduce:
- install dhl_delivery
- configure your DHL shipping methods (demo data are sufficient)
- create a stock.picking using a DHL shipping method
- try to validate it with an inventory manager (who is not member of administration/settings group)

Current behavior:
- the validation will fail because you needs to be in the administration/settings group

Expected behavior:
- Use a lower security group. A stock picking should not need required "god mode" to be validated.

The problem is provoked by this:
    dhl_SiteID = fields.Char(string="DHL SiteID", groups="base.group_system")
    dhl_password = fields.Char(string="DHL Password", groups="base.group_system")
    dhl_account_number = fields.Char(string="DHL Account Number", groups="base.group_system")

which make those three fields unreadable for anyone outside of base.group_sytem.

IMHO, it should be at least readable by inventory users. Maybe writable by inventory manager?

**Comment by pedrobaeza** [comment]
`dhl_delivery` is not an Odoo module, so you have to put the issue where that module was got, not here.

**Comment by jguerriat** [comment]
Hm indeed its odoo enterprise. My bad

**Comment by pedrobaeza** [comment]
If it's an enterprise one, put a ticket in odoo.com/help about that.

**Comment by jguerriat** [comment]
Ok thanks, i'll do that
