### ISSUE TITLE
Partner Allotment not implemented in Sale Orders

### ISSUE THREAD

**Issue by clonedagain** [odoo/odoo#5371]
I'm interested in the allotment feature as documented in the official FAQ here : https://www.odoo.com/forum/how-to/sales-crm-2/whats-the-use-of-allotment-partner-in-sale-order-line-19346

However I tried to follow the indicated steps on runbot v8, but entering the allotment partner had absolutely no visible effect.
I made a quick look at the code and I couldn't find an evidence that this feature is implemented at all.

So either the documentation is wrong, or the feature was (maybe accidentally?) disabled.

**Comment by jco-odoo** [comment]
I think it would be best to remove it as such (maybe I will put invisible in the views for now).  It is only creating confusion and it is doing nothing.  We could let it set the partner_id on the move (as in the test), but then you would need to adapt the reports also for the allotment.  The idea was to remove it anyways.

**Comment by jco-odoo** [comment]
It is actually more logical on the reports to check the sale_line_id that's connected with the move (move.procurement_id.sale_line_id) instead of passing it on the move where we need it for other purposes.

**Comment by Solanki-Shamji** [comment]
Hello,

In odoo8 allotment partner fields functionality is not work. 

Please refer this 

https://www.odoo.com/apps/modules/8.0/line_ship/

 for module which enable the allotment partner functionality.

**Comment by clonedagain** [comment]
@Solanki-Shamji thanks for sharing your implementation.
I see you reused the field procurement.partner_dest_id, which the help string indicates is for drop shipping.
Is there a specific reason to store that data here and not to use procurement.sale_line_id.address_allotment_id directly as @jco-odoo suggests?

**Comment by Yenthe666** [comment]
Hi @clonedagain,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
