### ISSUE TITLE
WARNING Test odoo.addons.base.models.assetsbundle: Error: Invalid CSS after "

### ISSUE THREAD

**Issue by jackson-rpdcool** [odoo/odoo#53765]
Hi All,

I am just a beginner and trying to understand and solve this issue.. 

If anyone came across such issue please help me out. 

2020-06-27 05:52:41,358 13700 WARNING Test odoo.addons.base.models.assetsbundle: Error: Invalid CSS after "...2ac843ccbdf5 */": expected 1 selector or at-rule, was "/ *! =============="
        on line 15913 of stdin
>> *! 47d9e6d2-b3ea-44eb-ab18-2ac843ccbdf5 */

   ------------------------------------------^
This error occured while compiling the bundle 'web.assets_backend' containing:
    - /web/static/lib/bootstrap/scss/_functions.scss
    - /web/static/lib/bootstrap/scss/_mixins.scss
    - /web/static/src/scss/bs_mixins_overrides.scss
    - /web/static/src/scss/utils.scss
    - /web/static/src/scss/primary_variables.scss
    - /web_editor/static/src/scss/web_editor.variables.scss
    - /mail/static/src/scss/variables.scss
    - /portal/static/src/scss/primary_variables.scss
    - /account/static/src/scss/variables.scss
    - /hr_org_chart/static/src/scss/variables.scss
    - /web_editor/static/src/scss/secondary_variables.scss
    - /web/static/src/scss/secondary_variables.scss
    - /web_editor/static/src/scss/bootstrap_overridden_backend.scss
    - /web_editor/static/src/scss/bootstrap_overridden.scss
    - /web/static/src/scss/bootstrap_overridden.scss
    - /web/static/lib/bootstrap/scss/_variables.scss
    - /web/static/src/scss/import_bootstrap.scss
    - /web/static/src/scss/bootstrap_review.scss
    - /web/static/src/scss/webclient_extra.scss
    - /web/static/src/scss/webclient_layout.scss
    - /web/static/src/scss/webclient.scss
    - /web/static/src/scss/domain_selector.scss
    - /web/static/src/scss/model_field_selector.scss
    - /web/static/src/scss/progress_bar.scss
    - /web/static/src/scss/dropdown.scss
    - /web/static/src/scss/dropdown_extra.scss
    - /web/static/src/scss/tooltip.scss
    - /web/static/src/scss/switch_company_menu.scss
    - /web/static/src/scss/debug_manager.scss
    - /web/static/src/scss/control_panel.scss
    - /web/static/src/scss/fields.scss
    - /web/static/src/scss/fields_extra.scss
    - /web/static/src/scss/views.scss
    - /web/static/src/scss/pivot_view.scss
    - /web/static/src/scss/graph_view.scss
    - /web/static/src/scss/form_view.scss
    - /web/static/src/scss/form_view_extra.scss
    - /web/static/src/scss/list_view.scss
    - /web/static/src/scss/list_view_extra.scss
    - /web/static/src/scss/kanban_dashboard.scss
    - /web/static/src/scss/kanban_examples_dialog.scss
    - /web/static/src/scss/kanban_column_progressbar.scss
    - /web/static/src/scss/kanban_view.scss
    - /web/static/src/scss/kanban_view_mobile.scss
    - /web/static/src/scss/web_calendar.scss
    - /web/static/src/scss/web_calendar_mobile.scss
    - /web/static/src/scss/search_view.scss
    - /web/static/src/scss/search_panel.scss
    - /web/static/src/scss/search_view_mobile.scss
    - /web/static/src/scss/dropdown_menu.scss
    - /web/static/src/scss/search_view_extra.scss
    - /web/static/src/scss/data_export.scss
    - /base/static/src/scss/onboarding.scss
    - /web/static/src/scss/attachment_preview.scss
    - /web/static/src/scss/notification.scss
    - /web/static/src/scss/base_document_layout.scss
    - /web/static/src/scss/ribbon.scss
    - /web/static/src/scss/base_settings.scss
    - /web/static/src/scss/report_backend.scss
    - /base_import/static/src/scss/base_import.scss
    - /web_diagram/static/src/scss/diagram_view.scss
    - /web_editor/static/src/scss/web_editor.common.scss
    - /web_editor/static/src/scss/web_editor.backend.scss
    - /base_setup/static/src/scss/settings.scss
    - /mail/static/src/scss/announcement.scss
    - /mail/static/src/scss/discuss.scss
    - /mail/static/src/scss/abstract_thread_window.scss
    - /mail/static/src/scss/thread_window.scss
    - /mail/static/src/scss/composer.scss
    - /mail/static/src/scss/chatter.scss
    - /mail/static/src/scss/followers.scss
    - /mail/static/src/scss/thread.scss
    - /mail/static/src/scss/systray.scss
    - /mail/static/src/scss/mail_activity.scss
    - /mail/static/src/scss/activity_view.scss
    - /mail/static/src/scss/kanban_view.scss
    - /mail/static/src/scss/attachment_box.scss
    - /partner_autocomplete/static/src/scss/partner_autocomplete.scss
    - /snailmail/static/src/scss/thread.scss
    - /sms/static/src/scss/thread.scss
    - /resource/static/src/scss/section_backend.scss
    - /utm/static/src/scss/utm_views.scss
    - /sales_team/static/src/scss/sales_team_dashboard.scss
    - /account/static/src/scss/account_reconciliation.scss
    - /account/static/src/scss/account_journal_dashboard.scss
    - /account/static/src/scss/account_dashboard.scss
    - /account/static/src/scss/account_searchpanel.scss
    - /account/static/src/scss/section_and_note_backend.scss
    - /account/static/src/scss/account_activity.scss
    - /payment/static/src/scss/payment_acquirer.scss
    - /sale/static/src/scss/sale_onboarding.scss
    - /sale/static/src/scss/product_configurator.scss
    - /calendar/static/src/scss/calendar.scss
    - /gamification/static/src/scss/gamification.scss
    - /hr/static/src/scss/hr.scss
    - /hr_attendance/static/src/scss/hr_attendance.scss
    - /hr_contract/static/src/scss/state_selection.scss
    - /hr_contract/static/src/scss/calendar_mismatch.scss
    - /hr_holidays/static/scss/hr_leave_mobile.scss
    - /hr_holidays/static/src/scss/time_off.scss
    - /hr_org_chart/static/src/scss/hr_org_chart.scss
    - /hr_recruitment/static/src/scss/hr_job.scss
    - /project/static/src/scss/project_dashboard.scss
    - /stock/static/src/scss/stock_traceability_report.scss
    - /mrp/static/src/scss/mrp_workorder_kanban.scss
    - /product_matrix/static/src/scss/product_matrix.scss
    - /event/static/src/scss/event.scss
    - /sale_timesheet/static/src/scss/sale_timesheet.scss
    - /base_accounting_kit/static/src/scss/style.scss
    - /base_accounting_kit/static/lib/bootstrap-toggle-master/css/bootstrap-toggle.min.css
    - /base_accounting_kit/static/src/scss/account_asset.scss 
2020-06-27 05:52:43,240 13700 INFO Test odoo.models.unlink: User #2 deleted ir.attachment records with IDs: [4004] 
2020-06-27 05:52:43,433 13700 INFO Test odoo.modules.registry: At least one model cache has been invalidated, signaling through the database. 
2020-06-27 05:52:43,435 13700 INFO Test werkzeug: 127.0.0.1 - - [27/Jun/2020 05:52:43] "GET /web HTTP/1.1" 200 - 672 0.569 3.817
2020-06-27 05:52:43,533 13700 INFO Test werkzeug: 127.0.0.1 - - [27/Jun/2020 05:52:43] "GET /web/content/4005-af92f0d/web.assets_backend.js HTTP/1.1" 200 - 7 0.005 0.045
2020-06-27 05:52:44,884 13700 INFO Test werkzeug: 127.0.0.1 - - [27/Jun/2020 05:52:44] "POST /web/dataset/call_kw/res.users/systray_get_activities HTTP/1.1" 200 - 17 0.031 0.023
2020-06-27 05:52:44,957 13700 INFO Test odoo.addons.base.models.ir_attachment: _read_file reading C:\Users\JACKSON\AppData\Local\OpenERP S.A\Odoo\filestore\Test\c5/c54d3d5e2b1320083bf5378b7c195b0985fa04c1 
Traceback (most recent call last):
  File "D:\Odoo 13.0\server\odoo\api.py", line 745, in get
    value = self._data[field][record._ids[0]]
KeyError: 2

**Comment by pedrobaeza** [comment]
Derived from #53764, so closing as there are third party modules breaking your DB

**Comment by jackson-rpdcool** [comment]
> Derived from #53764, so closing as there are third party modules breaking your DB

Can you please help me sir to understand which module is that.. I have uninstalled all third party modules and tried still it was not working. If you can guide me how to solve this issue that will be a great help for me

**Comment by pedrobaeza** [comment]
Sorry, I can't help too much. Try to find the views (ir.ui.view) that loads that assets. You can ask on the forums. As a lesson, don't install third party modules in a production database for avoiding these problems.
