### ISSUE TITLE
Could not get content for /base_accounting_kit/static/src/scss/style.scss defined in bundle 'web.assets_backend'.

### ISSUE THREAD

**Issue by jackson-rpdcool** [odoo/odoo#53764]
Impacted versions: ODOO Community v13 in windows 10

Current behavior: After Installing Base Accounting Kit Module from Cybrosys in my DB, CSS files crashed and not able to load thereafter.. I have tried all the possible ways to correct this issue but in vain. Even uninstalled all the custom modules but it is not working. I have contacted Cybrosys about this issue sent my DB and custom modules and their standard answer, we cannot replicate the issue. Even appointed a developer but he could not understand how to solve this permission issue. 

Only with Developer mode (with Assets) the style works perfectly without that it crashes and gives odd report as shown in attached picture. 

1. I have uninstalled this modules 
2. Removed Static folder from this module and made new
3. Install node js

The style compilation failed, see the error below. Your recent actions may be the cause, please try reverting the changes you made.

Could not get content for /base_accounting_kit/static/src/scss/style.scss defined in bundle 'web.assets_backend'.
Could not get content for /base_accounting_kit/static/lib/bootstrap-toggle-master/css/bootstrap-toggle.min.css defined in bundle 'web.assets_backend'.
Could not get content for /base_accounting_kit/static/src/scss/account_asset.scss defined in bundle 'web.assets_backend'.

If anyone had same issue or has a solution for this then please help. 

Video/Screenshot link (optional):

![Capture](https://user-images.githubusercontent.com/67504863/85920879-a619e780-b888-11ea-9a37-6b4daf407c95.PNG)

**Comment by Yenthe666** [comment]
@jackson-rpdcool sorry but those issues are related to that app/your deployment. Please open a ticket with the author of that module, this is not a default Odoo addon.

**Comment by jackson-rpdcool** [comment]
Can you help me with the path for this style issue permissions plz so that i can find some solution. Author of the program as i mentioned earlier not supporting at all.

**Comment by jackson-rpdcool** [comment]
> @jackson-rpdcool sorry but those issues are related to that app/your deployment. Please open a ticket with the author of that module, this is not a default Odoo addon.

Can you help me with the path for this style issue permissions plz so that i can find some solution. Author of the program as i mentioned earlier not supporting at all.

**Comment by Yenthe666** [comment]
Check all the asset paths in the module and if they're correctly build. Make sure your Odoo user has access to the files.
