### ISSUE TITLE
[mass_mailing] mail_server_id ignored when sending test mail

### ISSUE THREAD

**Issue by mkanderson** [odoo/odoo#53768]
Impacted versions: 12+

Steps to reproduce: Create an additional 'Outgoing Mail Server', create a new mailing using this server, send using the "Send Sample Mail" button.

Current behavior: Mail is sent using the default SMTP server. This causes the user unnecessary confusion.

Expected behavior: Mail is sent using the server specified in the mailing configuration.

Workaround/Fix:

```
diff --git a/addons/mass_mailing/wizard/test_mailing.py b/addons/mass_mailing/wizard/test_mailing.py
index 2fddb3f631d..5953fca49fa 100644
--- a/addons/mass_mailing/wizard/test_mailing.py
+++ b/addons/mass_mailing/wizard/test_mailing.py
@@ -33,6 +33,7 @@ class TestMassMailing(models.TransientModel):
                 'mailing_id': mailing.id,
                 'attachment_ids': [(4, attachment.id) for attachment in mailing.attachment_ids],
                 'auto_delete': True,
+                'mail_server_id': mailing.mail_server_id.id,
             }
             mail = self.env['mail.mail'].create(mail_values)
             mails |= mail

```

**Comment by Yenthe666** [comment]
@tde-banana-odoo for your reference

**Comment by pedrobaeza** [comment]
This has been solved, so closing (no commit reference right now, but it's solved).
