### ISSUE TITLE
Multi Dimensional Product View - Brand , Group , Type  & HS Code

### ISSUE THREAD

**Issue by orchidinfosys** [odoo/odoo#538]
Need more grouping of products like category. And will be added to reports as well.
In category Parent Child relation will not give you 360 analysis.
Example.  Category - A B C
                   = Brand - X Y Z
                   = Group - Local & Import Purchase
                   = Sub Group - Warranty - Non-Warranty 
                   = Type - Long & Short Life
HS Code can be different based country of origin -It should be captured Purchase- And  updated in product master with supplier, country of origin also can added with supplier.

**Comment by Yenthe666** [comment]
Dear @orchidinfosys,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
