### ISSUE TITLE
[8.0] API bug: objects not rollbacked on stock.transfer.details wizard

### ISSUE THREAD

**Issue by pablocm-aserti** [odoo/odoo#5381]
This bug probably affects other wizards, but I'll exemplify the issue with this use case.
Lines in the stock.transfer.details wizard are not rollbacked when an exception rises on `do_detailed_transfer`. This leads to a "dirty" state in which you can't transfer goods even if they have lot.

How to reproduce:
1- Create a product with "Full Lots Traceability" and an outgoing picking to deliver this product.
2- Confirm, force availability and open the "Transfer" wizard.
3- Assign a lot to the displayed wizard line.
4- Add another line of the same product (or any with lot traceability) but do not assign lot and click "Apply". An exception will be raised.
5- Remove the line missing the lot and click "Apply" again. The same exception will be raised again even tough the only wizard line has a lot.

The problem is the second time you click "Apply", there are two wizard lines when
a) they sould have been rollbacked as a result of the exception thrown in step 4
b) if (a) is not a bug but a limitation in the framework concerning transient models, the same way the lines have been saved when clicking the first time the "Apply" button before calling `do_detailed_transfer`, they should have been removed before calling it the second time
![wiz](https://cloud.githubusercontent.com/assets/8291685/6267159/ff89ab68-b841-11e4-876f-3d0dafc15900.png)

![wiz_lines](https://cloud.githubusercontent.com/assets/8291685/6267141/d33b6d58-b841-11e4-8a64-f7d30db8ca87.png)

I have tested this bug in 25b1df2eb331275ab6bb5e572665492bbff15bdc with an empty database and no additional modules

**Comment by martinvarela** [comment]
I'm having the same problem in do_detailed_transfer wizard. Any solution?

**Comment by ulrichkrenn** [comment]
Hi, the problem still exists on actual odoo 8 runbot.

Example:
> Sale Order with one Track All produkt ([A1090] iMac, set to track all).
> Enter transfer details (stock_transfer_details wizard)
> Add lines manual (e.g. [1] Ice Cream 1x, [A1232] iPad Mini  1x)
> Click Apply 4 times With Empty Lot number for [A1090] iMac
   ("Warning! You must assign a serial number for the product iMac" each time)
> Remove lot Produkt iPad Mini
> Click Apply 

The dialog showed 2 lines each 1 piece.
4x 2 lines each 1 piece where shipped!!!

Shipped
[1] Ice Cream	1.000		Partner Locations/Customers		Done
[A1232] iPad Mini	1.000		Partner Locations/Customers		Done
[1] Ice Cream	1.000		Partner Locations/Customers		Done
[A1232] iPad Mini	1.000		Partner Locations/Customers		Done
[1] Ice Cream	1.000		Partner Locations/Customers		Done
[A1232] iPad Mini	1.000		Partner Locations/Customers		Done
[1] Ice Cream	1.000		Partner Locations/Customers		Done
[A1232] iPad Mini	1.000		Partner Locations/Customers		Done

**Comment by Yenthe666** [comment]
Hi @pablocm-aserti,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
