### ISSUE TITLE
[13.0] Media Images with higher ID than 1000 wont be shown in Product > eCommerce tab

### ISSUE THREAD

**Issue by yung-wang** [odoo/odoo#53818]
Impacted versions:
[13.0]

Steps to reproduce:
1. Make sure you have more than 1000 media images or maybe you can update the ID to higher than 1000. 
2. Make sure, you will use a language with a thousand separator configured.
3. Go to your Product > Tab eCommerce. You will see that the pictures are not shown (like screenshot)

![ksnip_20200629-162630](https://user-images.githubusercontent.com/30628967/86018234-56245780-ba25-11ea-90a7-c98956003b17.png)

If you inspect the URL. You will see that the thousand seperator is used in the ID:
/web/image?model=product.image&field=image_1920&**id=1.068**  

4. Remove the thousand separator in your language and go back to your product.

![ksnip_20200629-162536](https://user-images.githubusercontent.com/30628967/86018278-689e9100-ba25-11ea-8585-8b09fd1da5a3.png)

If you inspect the URL. You will see that the ID is correct:
/web/image?model=product.image&field=image_1920&**id=1068**  

The issue is in module website_sale, file /views/product_views.xml, in record id: product_image_view_kanban
The following piece of code:

```
                            <div class="o_squared_image">
                                <img class="card-img-top" t-att-src="kanban_image('product.image', 'image_1920', record.id.raw_value)" t-att-alt="record.name.value"/>
                            </div>
```

For some reason, record.id.raw_value doesn't really take the raw value of record.id (which is an integer) but gets parsed according to the language. If the language has some kind of thousand separator and the id is greater than 999, the system will generate a wrong URL (e.g.: [..]id=1,944 instead of [...]id=1944)

I suggest changing the code above with the following:

```
                            <div class="o_squared_image">
                                <t t-set="record_id" t-value="record.id.raw_value"/>
                                <img class="card-img-top" t-att-src="kanban_image('product.image', 'image_1920', record_id)" t-att-alt="record.name.value"/>
                            </div>
```

**Comment by Yenthe666** [comment]
@dbo-odoo 😉

**Comment by pedrobaeza** [comment]
@JKE-be please check this

**Comment by Yenthe666** [comment]
Interesting enough I'm pretty sure there has been a ticket about this like a year ago which had a fix added.. but can't find it anymore :)

**Comment by JKE-be** [comment]
@bvr-odoo will take a look asap. thx for reporting

**Comment by gdgellatly** [comment]
@Yenthe666 So much for the fix, it is now the break https://github.com/odoo/odoo/pull/51105

**Comment by Yenthe666** [comment]
Ahh yes I was looking for this onen thanks! @nle-odoo looks like you've introduced this accidentally 😉

**Comment by JKE-be** [comment]
Nle cannot reproduce this issue:

![image](https://user-images.githubusercontent.com/4848797/92114411-1301ae80-edf1-11ea-89bf-fc79f084fc0b.png)


Can you check that you had the last version before your change that should not change anything....

**Comment by gdgellatly** [comment]
@JKE-be My duplicate report was from a custom module, which had reused the old view code. Tested with raw value and OK. Of course I am not original reporter

**Comment by pedrobaeza** [comment]
Then is this solved and can be closed?

**Comment by JKE-be** [comment]
Hi @yung-wang 

Ensure to have the last version and no custom module and don't hesitate to reopen if needed, but seems like it has been already fixed a long time ago. 
If you can reproduce it on runbot.odoo.com, it is still better ;)
