### ISSUE TITLE
Failed running odoo.py because of hw_escpos addon

### ISSUE THREAD

**Issue by rizaldim** [odoo/odoo#5385]
I just installed odoo v8 locally and I try doing tutorial here: https://www.odoo.com/documentation/8.0/howtos/website.html

at the section "Creating a basic module". I try to run the scaffolding command and I got this error:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 808, in __bootstrap_inner
    self.run()
  File "/Users/jal/repo/odoo/addons/hw_escpos/controllers/main.py", line 198, in run
    if printer:
UnboundLocalError: local variable 'printer' referenced before assignment

Then I moved hw_escpos from addons directory and tried it again. It worked.

**Comment by aftabnaveed** [comment]
I got the same issue when I was trying to scaffold a module using odoo.py scaffold modul_name path, I am using version 8.0

**Comment by ajl7519** [comment]
Thanks for the fix. I had the same error as well.

**Comment by mario21ic** [comment]
Hi, I fix it adding "printer = None" on line 150

**Comment by macadames** [comment]
Thx to mario21ic, the temporary fix "printer = None" is working

**Comment by punketo28** [comment]
Thank you mario2lic, You helped me solve the problem temporalment.

**Comment by ludwiktrammer** [comment]
Having the same issue on Mac OS X 10.10.3 (Yosemite).

**Comment by Yenthe666** [comment]
Hi @rizaldim,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
