### ISSUE TITLE
13.0 Odoo stopped stock reservation for some products

### ISSUE THREAD

**Issue by maksatmoda** [odoo/odoo#53892]
I remove stock reservation for some "Pick Step" records.  but now  products doesnt reserve stock included already removed picks.

How can fix or reset all products reservation states ?

If product not reserverd with sale order. then doesnt ready pick pack ship steps. i am editing all time manually

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question about how to fix a touched DB. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here. Little tip: try updating base module for updating all DB.

Closing this by the reason above.
