### ISSUE TITLE
[8.0] Error shipping_id on website_sale/controllers/main checkout_values method when click confirm checkout 

### ISSUE THREAD

**Issue by Elghard** [odoo/odoo#5396]
I tried to confirm checkout the product in shop, but show up "Internal Server Error". In console it said Error on 'shipping_id' at line:391. Maybe it should int(data['post']['shipping_id']) ? or ? please check this bug out. 
Thank you.

**Comment by Yenthe666** [comment]
Hi @Elghard,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
