### ISSUE TITLE
[8.0] onchange() and depends() decorators only work for UI changes and 1 record only?

### ISSUE THREAD

**Issue by a0c** [odoo/odoo#5397]
Instead of calling `update_some_regular_fields()` method at the end of overwritten `create()` and `write()` methods, why can't I just decorate `update_some_regular_fields()` method with `@api.onchange()` or `@api.depends()`? This would shorten the code considerably and make it readable, but the decorators seem to only react on changes from UI and ignore all other programmatic changes to DB records.

Also, with `self` being a virtual record in the onchange method, changes to records other than `self` are obviously ignored.

Maybe it's more of a feature request?

**Comment by Yenthe666** [comment]
Hi @a0c,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
