### ISSUE TITLE
Event tracks speaker_ids show deformed in kanban view

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#5400]
Install `website_event_track` with demo data and go to _Marketing > Events > "Open Days in Los Angeles" > Tracks_. You will see this:

![captura de pantalla de 2015-02-20 11 25 28](https://cloud.githubusercontent.com/assets/973709/6284697/34515b00-b8f3-11e4-93cf-865120a361e4.png)

The problem is in [the class .oe_left](https://github.com/odoo/odoo/blob/5a207fa08ee3e52014764fe4983946d8504f6449/addons/web/static/src/css/base.sass#L343) of those images, or in [assigning it when others modules don't do it](https://github.com/odoo/odoo/blob/5a207fa08ee3e52014764fe4983946d8504f6449/addons/website_event_track/views/event_backend.xml#L254).

**Comment by Yenthe666** [comment]
Hi @Yajo,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
