### ISSUE TITLE
8.0 sale order: update fiscal position with order lines before save

### ISSUE THREAD

**Issue by alexis-via** [odoo/odoo#5402]
Here is the scenario to reproduce the bug on runbot:
1) connect to runbot v8 as admin user
2) Edit the admin user and remove him from the groups that trigger the opening of the sale
 order line form view (I don't know the exact list)
3) Edit the product "USB Adapter" and set a Sales Tax "VAT-OUT-21-S"
4) create a new quotation:
customer : Agrolait
create a sale order line (make sure that it doesn't open the form view of the sale order line ; the bug only happens when the sale order line is in editable tree view) :
1 x USB adapter -> Save & Close
Go to the "Other Information" tab and change the fiscal position from "Régime Nationale" to "Régime Extra-Communautaire"
SAVE the quotation (the save of the quotation must be done only now)
=> you get an error message : The following fields are invalid: Order Lines

**Comment by alexis-via** [comment]
This issue "look like" the bug on the OCA module sale_fiscal_position_update for v7.0 https://github.com/OCA/sale-workflow/issues/96 I developped a hack to fix this issue in sale_fiscal_position_update, see the bug report on OCA.

**Comment by alexis-via** [comment]
It is in fact very similar to the OCA bug in sale_fiscal_position_update and the hack to fix this issue is the same !

**Comment by Yenthe666** [comment]
Hi @alexis-via,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
