### ISSUE TITLE
Scrap move in manufacturing order

### ISSUE THREAD

**Issue by ccandito** [odoo/odoo#5406]
after performing a scrap move from manufacturing order the generic screen move appears instead of coming back to manufacturing order
thanks in advance
Claudio

**Comment by jco-odoo** [comment]
Indeed, afterwards we arrive in a new picking form.  We should inherit it in mrp. Was not there already some request for this?

**Comment by Yenthe666** [comment]
@jco-odoo any update here? I believe this can be closed?

**Comment by Yenthe666** [comment]
Hi @ccandito,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
