### ISSUE TITLE
[8.0] Anglo-saxon module : Supplier invoice gets wrong balance due in multicurrency

### ISSUE THREAD

**Issue by fclementic2c** [odoo/odoo#5407]
Install the anglosaxon module
Create an invoice in foreign currency 
Validate it
Check the consitency of balance

![image](https://cloud.githubusercontent.com/assets/5735158/6289744/983ed14a-b922-11e4-9af2-e2b1ef480612.png)

**Comment by Yenthe666** [comment]
Hi @fclementic2c,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
