### ISSUE TITLE
Access to write on sales orders should not be required to register payments

### ISSUE THREAD

**Issue by ebirbe** [odoo/odoo#54081]
Impacted versions:
12.0

Steps to reproduce:
- Create an invoice from a sales order and validate it.
- Create a restricted user profile capable to validate invoices, but with no access to `write` on `sales.orders`.
- Now using this restricted profile try to pay the invoice.

Current behavior:
- You get an Access Error because you need to have privileges to wirte on `sale.order` just to record a note saying "Invoice was paid":

https://github.com/odoo/odoo/blob/babada244b17a0dda479508390bd221b7c17474a/addons/sale/models/account_invoice.py#L80

Expected behavior:
For implementations of Odoo where customers want to have a grained access policies for their sales and invoicing workflows, it should not be required to have access to edit sales orders just to allow their users to register payments on invoices.

Video/Screenshot link (optional):

/cc @hugho-ad @moylop260

**Comment by pedrobaeza** [comment]
That message is only posted when the invoice is paid, so your case is not correct.

**Comment by sswapnesh** [comment]
> Create a restricted user profile capable to validate invoices, but with no access to write on sales.orders.

By default Billing user will have `write` access to `sale.order (I just tried same on v12/v13 and its working well with Billing user)`

**Comment by pedrobaeza** [comment]
Yes, I don't see an issue here with standard code, so closing, If further evidence is brought, then we can reopen.
