### ISSUE TITLE
[i18n] can not contribute translation on transifex.

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#54085]
Impacted versions:

- all odoo version

Steps to reproduce:

1. login into transifex
2. switch to project odoo-13, and choose chinese to translate.
3. choose resource said account, try to mark translation as reviewed.

Current behavior:

1. can not mark translation as reviewed.
2. all chinese team member has loss the reviewer permission

Expected behavior:

Video/Screenshot link (optional):

- i have the review and coordinator permission from 2016

**Comment by pedrobaeza** [comment]
@mart-e, for you.

**Comment by mart-e** [comment]
Thanks for the notice, should be good now.
Closing and replying to the message sent on Transifex (not a github bug)
