### ISSUE TITLE
Insecurity for / Web / content (odoo13)

### ISSUE THREAD

**Issue by 2861934674** [odoo/odoo#54093]
Problem Description: record rules can restrict users' access through / Web / content ir.attachment Attachment information, but if used fields.Many2many () ir.attachment ', When the string is set to "attachment", the access of the restricted to many to many fields cannot be restricted to unauthorized users ir.attachment Therefore, there is a security risk here that the user can obtain the information directly by traversing the data ir.attachment All records to which rules are limited ir.attachment enclosure

**Comment by pedrobaeza** [comment]
I don't get the problem, but please check: https://www.odoo.com/es_ES/security-report
