### ISSUE TITLE
对于/web/content的不安全性（odoo13）

### ISSUE THREAD

**Issue by 2861934674** [odoo/odoo#54092]
问题描述：记录规则可限制用户通过/web/content访问ir.attachment附件信息，但若使用fields.Many2many('ir.attachment',string="附件")时，限制改多对多字段无法限制到无权限用户访问ir.attachment，因此此处有个安全隐患是，用户可直接通过遍历数据来获取没被ir.attachment记录规则限制到的所有ir.attachment附件

**Comment by pedrobaeza** [comment]
Only in English, please.
