### ISSUE TITLE
[8.0] JS Error on /web/static/src/js/views.js:1292

### ISSUE THREAD

**Issue by antespi** [odoo/odoo#5416]
Impacted versions:

 - 8.0

Steps to reproduce:

1. Start a runbot v8
2. Go to Warehose > All operations > Delivery orders > All operations
3. Select one or more pickings
4. Click on More > Add to Wave
5. Error pop-up:
Uncaught TypeError: Cannot read property 'get_context' of undefined
http://48600-8-0-d350f5.runbot7.odoo.com/web/js/web.assets_backend/0551a93:3164 
6. Same error with other actions in More menu

Current behavior:

- JS Error

Expected behavior:

- Perform actions over selected item

**Comment by wtaferner** [comment]
Acknowledged
Seems to be introduced with https://github.com/odoo/odoo/commit/27a48f8026f824f62955d5bf2a83b2799ad98db1
@beledouxdenis

**Comment by antespi** [comment]
If you revert changes from addons/web/static/src/js/views.js, problem seems to be fixed. But I supose this change has been introduced for a reason, isn't it, @beledouxdenis?

**Comment by beledouxdenis** [comment]
Indeed, there is a reason, as mentioned in the detailed commit message.

I am on it right now :).

**Comment by beledouxdenis** [comment]
After upgrading your sources, and performing a browser cache refresh, this issue will be solved.

**Comment by wtaferner** [comment]
Thx @beledouxdenis

**Comment by antespi** [comment]
Thanks a lot @beledouxdenis
