### ISSUE TITLE
[11.0] Can't able change string name in One2many by using fields_view_get

### ISSUE THREAD

**Issue by Gokulakannanaj** [odoo/odoo#54182]
Impacted versions:
11.0

Steps to reproduce:

1. Create an One2many field with the editable bottom.
2. Add fields_view_get method for Main Module or One2many Module.

Current behavior:
1. Can't able to access one2many tree view fields in Main Module
2. Also can't able to find the fields in the relation table fields_view_get method too.

Expected behavior:
1. It should allow us to find the one2many fields in the main module fields_view_get method.

**Code Sample:**
XML
<field name="one2many_field">
     <tree editable="bottom">
               <field name="name" string="Test"/>
    </tree>
</field>
Python - In fields_view_get method

Way 1:
for node in doc.xpath("//field[@name='name']"):
    node.set('string', "Hello")

Way 2:
for node in doc.xpath("//field[@name='one2many_field']/tree/field[@name='name']"):
    node.set('string', "Hello")

**Comment by pedrobaeza** [comment]
This is not something planned. Possible workarounds:

- Override `fields_view_get` in the one2many model.
- Change it in XML.

Closing as no intended to change this being very specific.

**Comment by Gokulakannanaj** [comment]
@pedrobaeza - It's not called(one2many module) while loading the main view, So only I raised.
