### ISSUE TITLE
TypeError: Model 'hr.employee' does not exist in registry.

### ISSUE THREAD

**Issue by madrara256** [odoo/odoo#54204]
Impacted versions:12

Steps to reproduce: failed to reproduce this error

Current behavior: System fails to load with the error: TypeError: Model 'hr.employee' does not exist in registry.

Expected behavior:To load properly , all models that use the hr module have hr included in their dependencies

Video/Screenshot link (optional):

2020-07-07 15:36:13,511 6538 ERROR 12instance_one odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/modules/registry.py", line 60, in __new__
    return cls.registries[db_name]
  File "/opt/odoo12/odoo/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: '12instance_one'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo12/odoo/odoo/modules/loading.py", line 417, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/opt/odoo12/odoo/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo12/odoo/odoo/modules/loading.py", line 188, in load_module_graph
    model_names = registry.load(cr, package)
  File "/opt/odoo12/odoo/odoo/modules/registry.py", line 240, in load
    model = cls._build_model(self, cr)
  File "/opt/odoo12/odoo/odoo/models.py", line 439, in _build_model
    raise TypeError("Model %r does not exist in registry." % name)
TypeError: Model 'hr.employee' does not exist in registry.

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/12.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).

**Comment by mt-software-de** [comment]
@madrara256 did you find a solution for your problem?
Many thanks

**Comment by madrara256** [comment]
Yeap!!, I got this fixed, though I may have lost track of what the actual cause is now. Been on a number of projects

________________________________

Herbert Ichama
Software Engineer
Company

________________________________

**Comment by zeintiz** [comment]
@madrara256 could you please explain what you do? i have same problem?

**Comment by Amm-ar** [comment]
Hello :+1:  
i have a similar problem , I created a new model to extend hr_applicant and this is exactly what i get :
TypeError: Model 'hr_applicant' does not exist in registry.
 
:1234:  i have included hr_recruitment in my dependencies and tried referencing the model as hr_recruitment.hr_applicant and i get this error : 
TypeError: Model 'hr_recruitment.hr_applicant' does not exist in registry.

**Comment by JulissaCorralesIrias** [comment]
Lo que funcionó para mí fue agregar el modulo hr como dependencia en el manifest
