### ISSUE TITLE
In odoo master master replication is possible?

### ISSUE THREAD

**Issue by abhishekms123** [odoo/odoo#54203]
After doing master master replication for postgreql it is also properly working for odoo? If yes ! Type of replication !

Anyone please help me to solve this!

#odoo13 #odoo12 #odoo11 #CE #ENTERPRISE

**Comment by Yenthe666** [comment]
Yes it is possible and yes it can work. This is however not a bug in Odoo but a question about deployment. Please ask these kind of questions on the official help forum at https://www.odoo.com/forum/help-1
