### ISSUE TITLE
[8.0] Paypal acquirer encoding problem

### ISSUE THREAD

**Issue by rachkulik** [odoo/odoo#5421]
**When you use non latin-charset ex. cyrillic in product or company name, than you have encoding problem on paypal payment page**

Impacted versions:
- 8.0

Steps to reproduce:
1. Install ecommerce module with demo data
2. Change company name to cyrillic ex. (ООО "Тагес Джамп")
3. Install website_payment and payment_paypal
4. Activate paypal acquirer
5. Try to buy something using paypal acquirer
6. Do all steps in checkout while you will redirected to paypal payment page

Current behavior:
- п·п·п· "п╒п╟пЁп╣я│ п■п╤п╟п╪п©": 

Expected behavior:
- ООО "Тагес Джамп"

To fix this you need add this lines
addons/payment_paypal/models/paypal.py
LINE #118
            'charset' : 'utf-8',

addons/payment_paypal/views/paypal.xml
LINE #11
input type="hidden" name="charset" t-att-value="tx_values['charset'] or 'utf-8'"

Thank you!

**Comment by Yenthe666** [comment]
Hi @rachkulik,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
