### ISSUE TITLE
Missing header and footer on sales documents

### ISSUE THREAD

**Issue by vedh-cac** [odoo/odoo#54225]
Impacted versions: 13.0

Steps to reproduce: create a sales quotation / order / invoice and print or send the document

Current behavior: document layout is not complete, header (logo and adress), footer and total amount are missing

Expected behavior: all information of the document layout as seen in the studio version

Video/Screenshot link (optional): 

[S00001.pdf](https://github.com/odoo/odoo/files/4890626/S00001.pdf)

![Screenshot Studio](https://user-images.githubusercontent.com/64430234/86919224-2f9ea480-c128-11ea-8a28-af1a85243980.png)

Who can give us specifications to solve this issue?

Thanks in advance 
Veerle

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/13.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).

Tip: put a system parameter `report.url` with value `http://localhost:8069`.
