### ISSUE TITLE
[13.0] Allow to filter parterns by events

### ISSUE THREAD

**Issue by yaazkal** [odoo/odoo#54231]
Impacted versions: 13.0

Steps to reproduce:
Go to CRM - Filters - Add custom Filter

Current behavior:
There is no way to filter contacts by events

Expected behavior:
Events option should be available as other things like "elearning courses" are available.

Note that an smart button for events on the contact view already exists so the user expects to be able to filter contacts by events.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/5897701/86921641-10d0eb80-c0f1-11ea-8dbc-9fc98596fd13.png)

**Comment by pedrobaeza** [comment]
This can't be possible, as there's no partner in event registrations. You can check OCA's module `partner_event` for a module adding this link (through email field), but it's not going to be added in core (at least in this version), so closing.

**Comment by yaazkal** [comment]
@pedrobaeza thanks so much for the clarification. I hope is added in future versions then as users expect to see them in the list like other modules work; just because they can see in the partner information a smart button linking to events.

Have a nice day !
