### ISSUE TITLE
Unauthorized access to any view by url manipulation

### ISSUE THREAD

**Issue by mehdisam** [odoo/odoo#5424]
Hi,
The actual problem is URL manipulation where actions are not check for access control. My idea is: run act_window actions only if they have visible menu for current user. And please add access check for groups_id in action.

BR

**Comment by mehdisam** [comment]
The actual problem is URL manipulation where actions are not check for access control. My idea is: run act_window actions only if they have visible menu for current user. And please add access check for groups_id in action.
Thanx

**Comment by mehdisam** [comment]
Hi,
I create this module based on the above idea and it works. Naive but works.
https://github.com/mehdisam/ActionGroup.git

**Comment by Yenthe666** [comment]
Hi @mehdisam,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
