### ISSUE TITLE
[12.0] stock:  standard_price on fifo cleans cache when computing standard price from fifo

### ISSUE THREAD

**Issue by hugho-ad** [odoo/odoo#54288]
Impacted versions:
[12.0]

Steps to reproduce:
configure cost_method == 'fifo'
make a purchase and validate pickings

Current behavior:
Standard price is computed from  _run_fifo
https://github.com/odoo/odoo/blob/91f4adba90688d5f8a04d38d057df200db863478/addons/stock_account/models/stock.py#L303-L305
And since standard price, it's a company dependant field (ir.property)
It cleans the cache at
https://github.com/odoo/odoo/blob/91f4adba90688d5f8a04d38d057df200db863478/odoo/addons/base/models/ir_property.py#L115

This is a problem because cache it's cleaned each time, I never used properly.

Expected behavior:
Avoid cleaning the whole cache

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/10233975/87105091-98b51380-c21f-11ea-8043-240ca69a8df2.png)

![image](https://user-images.githubusercontent.com/10233975/87105153-c437fe00-c21f-11ea-8942-4235dd8ba0e8.png)

![image](https://user-images.githubusercontent.com/10233975/87105216-f8132380-c21f-11ea-9d2e-0cee988ad3fa.png)

## OPW 2294668

**Comment by moylop260** [comment]
@nim-odoo 
Is there a planned fix for v14.0?

FYI It is a big performance issue for our customers confirming pickings
The whole cache is cleaned so frequently

cc @odony

**Comment by nim-odoo** [comment]
I don't think it is planned for v14. @amoyaux Can you confirm?

Maybe it would be worth reconsidering the fact that the standard price is an `ir.property`... Or improve what @beledouxdenis mentioned in https://github.com/odoo/odoo/blob/715a24333bf000d5d98b9ede5155d3af32de067c/odoo/addons/base/models/ir_property.py#L121-L124 (cc @rco-odoo )

**Comment by amoyaux** [comment]
@nim-odoo you are right, nothing planned.

**Comment by moylop260** [comment]
Ok
I got it

Thanks for reply
