### ISSUE TITLE
[8.0] Quotation receives partner_id instead of project_id

### ISSUE THREAD

**Issue by RaffaeleT** [odoo/odoo#5430]
**project_id field of a quotation receives the value of partner_id**

Impacted versions:
- 8.0

Steps to reproduce:
1. activate analytic accounting
2. enter a contract
3. open quotations from the link "Quotations"
4. create and save a quotation

Current behavior:
- Partner_id: 680
- Project_id: 680

Expected behavior:
- Partner_id: 680
- Project_id: 1091

**Comment by Yenthe666** [comment]
Hi @RaffaeleT,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
