### ISSUE TITLE
Inverse Name with state in python

### ISSUE THREAD

**Issue by cedvict** [odoo/odoo#54310]
Impacted versions: 
**Odoo 11**

Steps to reproduce: 
**With two models that have an association. In class A, we have a field Many2one with this definition fields.Many2one('class.b', states={'draft': [('readonly', False)], 'confirm':  [('readonly', False)]}). In class B, we have a field One2many with this definition fields.One2many( comodel_name='class.a', inverse_name='b_id')**

Current behavior:
Some error occurs depending the way to display or use. I have two behaviors. For the first one I had a error on One2many with error on state undefined when trying to get form view. For the second one I used the One2many in compute function to have the number of occurence and display it in button widget statinfo but I always have zero as value

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Please include a minimal module showcasing the problem.

**Comment by cedvict** [comment]
We have an example with module hr_holidays. Actually there's not a field that give leave taken in hr.employee model. So I try to add one based on field employee_id in hr.holidays model.

**Comment by pedrobaeza** [comment]
I don't get you, but detailed steps to reproduce the problem are needed.

**Comment by Yenthe666** [comment]
@cedvict can you please add more detailed steps on how to reproduce this?

**Comment by pedrobaeza** [comment]
Closing as no answer
