### ISSUE TITLE
[8.0] & [7.0] Human resources-contracts-MISSING the company field.

### ISSUE THREAD

**Issue by hugho-ad** [odoo/odoo#5435]
## Problem

This field is necesary to :
- List all contracts by company
- A contract is meaningless if an employee is not associated with a company.
## Expected results

http://awesomescreenshot.com/0d04gxvq4a

 bug_followup@vauxoo.com

**Comment by hugho-ad** [comment]
Hello,
employees and contracts created by a user A of the company A, can be viewed by the user B of the company B.
This presents problems of access restriction, as this should not happen, is vulnerable.

https://docs.google.com/a/vauxoo.com/file/d/0B3Djhos9BJLIZENrTVdtWDVFRlk/edit

The expected outcome is that employees from the company A or B, can not be together by the user of such companies, including contracts generated.

No more for now, I hope your answer
Thank you.

**Comment by hugho-ad** [comment]
What we want is that native rules are created in Odoo as multicompany functionality implies that you can have integrity and security to Work Related with several companies.
rules are proposed.

![record rules odoo](https://cloud.githubusercontent.com/assets/10233975/6578847/2dd8e140-c70c-11e4-934a-0930b3e15a18.png)

**Comment by Yenthe666** [comment]
Hi @hugho-ad,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
