### ISSUE TITLE
[12.0] Rounding issue with quants reserved_quantity

### ISSUE THREAD

**Issue by kirca** [odoo/odoo#54357]
Impacted versions:
12

Steps to reproduce:
Exact steps are not known but occurs occasionally when using UoM with Rounding Precision 0.00001

Current behavior:
When validating a Picking or posting an inventory on a Manufacturing Order UserError is raised:
https://github.com/odoo/odoo/blob/2761393b06bb396cf08799948e6fda3091ff1f35/addons/stock/models/stock_quant.py#L266

Expected behavior:
No UserError

Video/Screenshot link (optional):
We are monitoring the server using Sentry and there are a couple cases that were caught

![case1](https://user-images.githubusercontent.com/4568032/87191686-33cbed00-c2f5-11ea-809e-2e479a8bd0d1.png)

![case2](https://user-images.githubusercontent.com/4568032/87191703-3c242800-c2f5-11ea-888f-d613f81e453b.png)

As we can see for the compared values `available_quantity` (the reserved quantity on the matching quants) and `quantity` (the reserved quantity on the move line), in both cases the difference would be negligible on a lower precision. That is:

```
>>> float_compare(0.66664, 0.6666700000000001, precision_rounding=0.001)
0
```

but we use 0.00001 so we get

```
>>> float_compare(0.66664, 0.6666700000000001, precision_rounding=0.00001)
-1
```

So the question is how is this error accumulated and how can we use a higher level rounding precision without triggering it.

Odoo Ticket #2275367

**Comment by llacroix** [comment]
For information 0.6666700000000001, is probably the result of 0.6666666666 rounded up to 0.66667 The issue is caused because odoo uses ROUND_HALFUP everywhere (almost).

If odoo gave on on float_utils and instead used something like the decimal module it would be possible to use something like 
ROUND_05UP which would round correctly 0.66666666666666 to 0.66666 

Here:

```
>>> Decimal("0.6666599999").quantize(Decimal("0.00001"), rounding=decimal.ROUND_05UP)
Decimal('0.66666')

>>> Decimal("0.6666666666").quantize(Decimal("0.00001"), rounding=decimal.ROUND_05UP)
Decimal("0.66666666").quantize(Decimal("0.00001"), rounding=decimal.ROUND_05UP)
```
