### ISSUE TITLE
[8.0] Cannot batch install modules

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#5440]
1. Go to _Settings > Modules > Local modules_.
2. Switch to list view.
3. Select some modules.
4. Click _More > Module Immediate Install_.

It fails with:

```
TypeError: self.dataset is undefined

http://localhost/web/js/web.assets_backend/b7961cc:3164
```

Installing modules one by one works.

**Comment by lukebranch** [comment]
@Yajo,

I've noticed this as well since version 7.0. I think there are a few discussions about it on the help.odoo.com and in these github issues as well. I don't think there has been any resolution to the issue yet though.

**Comment by ArturBertram** [comment]
The exactly same error appears when you're trying to print multiple reports. It happens with sale.order, purchase.order, manufacture.order and every other object.
It looks like the dataset isn't set in the list view.
It worked two weeks ago, before the changes with the active_ids was made.

**Comment by Yenthe666** [comment]
Hi @Yajo,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
