### ISSUE TITLE
Hard to inherit and extend pricelist price computation

### ISSUE THREAD

**Issue by LeartS** [odoo/odoo#5441]
The main culprit is the [_price_rule_get_multi function](https://github.com/odoo/odoo/blob/8.0/addons/product/pricelist.py#L196) which is 266 lines and the core of the price calculation.

This function should be split in smaller functions (and, possibly, rewritten) to ease inheritance and make it easier to edit the price calculation routine. Some common uses cases are: add a rule restriction field (e.g. product brand), add a calculation factor (e.g. an exponent), add a pricelist version restriction field.

**Comment by Yenthe666** [comment]
Hi @LeartS,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
