### ISSUE TITLE
Debug Mode view can't update/change, display only kanban view

### ISSUE THREAD

**Issue by imjaypatel** [odoo/odoo#5442]
In Debug Mode view can't update/change, display only Kanban view even if I select forum view still open Kanban view only.

View this video explanation: https://www.youtube.com/watch?v=Ci-k4BZKXhA

Effected version: 7.0
Worked on: 8.0, master

**Comment by Yenthe666** [comment]
Hi @imjaypatel,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
