### ISSUE TITLE
[8.0] wrong currency printed on purchase order

### ISSUE THREAD

**Issue by sbidoul** [odoo/odoo#5443]
When creating a PO in a non-default currency, the printed currency is wrong.

How to reproduce:
* runbot 8.0
* create a new quotation
* select supplier Asustek
* change currency to USD
* add an item (UDB Headset)
* the total on the purchase order screen is $ 60 -> OK
* print the purchase order: amounts in the PDF are in Euro -> NOK

**Comment by sbidoul** [comment]
OPW 628767

**Comment by ly-william** [comment]
Is it really solved in 8.0 ? I checked out the 8.0 branch and tried to create a PO with a different money. I can see the correct currency in the PO page but when I print it, it always comes out as euro. Tried on 9.0 branch and the issue is fixed there.
