### ISSUE TITLE
Multi warehouses access rights?

### ISSUE THREAD

**Issue by ramitalat** [odoo/odoo#5445]
My client has a company with the following structure:

```
The HO                                           (HO)
The Manufacturing Plant                (MF)
Other warehouses                          (OW)
```

Each of these branches has its own local warehouse as described, respectively.

The warehouse access rights should be distributed over these warehouses, as each stock keeper should only deal with his warehouse.

In Odoo Sales, each sales team member can be restricted to see only his leads.
However, in Odoo Warehouse, I cannot see such access rights.

Please help with your experience.

**Comment by Yenthe666** [comment]
Hi @ramitalat,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
