### ISSUE TITLE
Infinite recursion in XMLRPC with lazy results

### ISSUE THREAD

**Issue by beledouxdenis** [odoo/odoo#54466]
Impacted versions:
saas-13.3, at least. As e2b5a359c1d5eccbe725c1c3169b4130d7bca49b was applied in earlier version, earlier version could be affected to.
But with the current observed case using the method `find_or_create`on `res.partner`, it doesn't happen in versions < saas-13.3, but this might be because the signature of `find_or_create` just changed: It used to return an ID, it now returns a browse record.

Steps to reproduce:
1. Start odoo, install contacts
```sh
./odoo-bin -d mydb -i contacts
```

2. Call using XMLRPC:
```python
#!/usr/bin/env python3
import xmlrpc.client

url, db, username, password = 'http://localhost:8069', 'mydb', 'admin', 'admin'

common = xmlrpc.client.ServerProxy('{}/xmlrpc/2/common'.format(url))
common.version()
uid = common.authenticate(db, username, password, {})

models = xmlrpc.client.ServerProxy('{}/xmlrpc/2/object'.format(url))

models.execute_kw(db, uid, password, 'res.partner', 'find_or_create', ['gerard@agrolait.com'])
```

Current behavior:
```
2020-07-14 17:10:41,962 67874 INFO saas-13.3 werkzeug: 127.0.0.1 - - [14/Jul/2020 17:10:41] "POST /xmlrpc/2/common HTTP/1.1" 200 - 18 0.007 0.035
2020-07-14 17:10:42,030 67874 ERROR saas-13.3 odoo.http: maximum recursion depth exceeded in comparison 
Traceback (most recent call last):
  File "/home/dle/src/odoo/saas-13.3/odoo/http.py", line 140, in dispatch_rpc
    result = dispatch(method, params)
  File "/home/dle/src/odoo/saas-13.3/odoo/service/model.py", line 41, in dispatch
    res = fn(db, uid, *params)
  File "/home/dle/src/odoo/saas-13.3/odoo/service/model.py", line 174, in execute_kw
    return execute(db, uid, obj, method, *args, **kw or {})
  File "/home/dle/src/odoo/saas-13.3/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/dle/src/odoo/saas-13.3/odoo/service/model.py", line 181, in execute
    res = execute_cr(cr, uid, obj, method, *args, **kw)
  File "/home/dle/src/odoo/saas-13.3/odoo/service/model.py", line 168, in execute_cr
    for l in traverse_containers(result, lazy):
  File "/home/dle/src/odoo/saas-13.3/odoo/tools/misc.py", line 1529, in traverse_containers
    yield from traverse_containers(v, type_)
  File "/home/dle/src/odoo/saas-13.3/odoo/tools/misc.py", line 1529, in traverse_containers
    yield from traverse_containers(v, type_)
  File "/home/dle/src/odoo/saas-13.3/odoo/tools/misc.py", line 1529, in traverse_containers
    yield from traverse_containers(v, type_)
  [Previous line repeated 951 more times]
  File "/home/dle/src/odoo/saas-13.3/odoo/tools/misc.py", line 1523, in traverse_containers
    elif isinstance(val, Mapping):
  File "/usr/lib/python3.8/abc.py", line 98, in __instancecheck__
    return _abc_instancecheck(cls, instance)
RecursionError: maximum recursion depth exceeded in comparison
```

Expected behavior:
Return the ID of the browse record
(as the call to `create` or `search` does)

**Comment by beledouxdenis** [comment]
@xmo-odoo This needs to be fixed first thing tomorrow because it affects the synchronization of the upgrade platform with our production :).

**Comment by xmo-odoo** [comment]
>  this might be because the signature of find_or_create just changed: It used to return an ID, it now returns a browse record.

That's exactly why: the method is not annotated with `@returns`, so `api.call_kw` doesn't know how to convert it from a recordset to an RPC-compatible thing, and the unlazifier breaks because it can't handle recordsets.

**Comment by beledouxdenis** [comment]
K will do the fix then

**Comment by beledouxdenis** [comment]
K you did it

**Comment by xmo-odoo** [comment]
> K you did it

Yeah I posted the comment after I found out what the problem was, and it's not a super difficult fix, though it looks like `returns` annotations are not inherited so the override also has to be annotated which is a bit odd (/cc @rco-odoo shouldn't api attributes be inherited by all extenders?)

**Comment by odony** [comment]
As I understand it, `traverse_containers` still suffers from an infinite recursion problem when you call it on a recordset. That seems a likely enough case that we should handle it gracefully, don't you think?

Isn't the following sufficient to guard it, so the error in case someone else forgets the secret decorator will much more straightforward than an obscure infinite recursion?

```py
     if isinstance(val, type_):
         yield val
-    elif isinstance(val, (str, bytes)):
+    elif isinstance(val, (str, bytes, BaseModel)):
         return
     elif isinstance(val, Mapping):
         for k, v in val.items():
```

**Comment by xmo-odoo** [comment]
> As I understand it, `traverse_containers` still suffers from an infinite recursion problem when you call it on a recordset.

Yes, I created a PR in 12 for that (#54477).

> That seems a likely enough case that we should handle it gracefully, don't you think?

Sure, though the result isn't that useful either: it will either blow up with an error which is no clearer or (possibly worse) fail to blow up and send the client garbage (the stringification of the recordset) instead.
