### ISSUE TITLE
Warehouse operations Sequence number swaps SHORT NAME to use the PREVIOUS overwritten short name

### ISSUE THREAD

**Issue by eabquina** [odoo/odoo#54469]
Impacted versions: 13.0

Steps to reproduce: Create a Warehouse and activate multi-step routes

Current behavior: When editing a Warehouse shortname, save it with a new code,it saves the overritten/replaced code to the sequence identifier patterns

Expected behavior: Short Name should apply to the sequence numbers when saved.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Can you specify a bit more the problem (maybe with a video)?
