### ISSUE TITLE
Opening the customer invoice from the activity view is opening the vendor bill form view

### ISSUE THREAD

**Issue by Elbagoury** [odoo/odoo#54471]
Impacted versions:
Odoo 12 EE & CE

Steps to reproduce:

1. Schedule new activity under the customer invoice.
2. Open your activities and click on that activity.

Current behavior:
It will open the vendor bill form view
![customer_invoice](https://user-images.githubusercontent.com/9639673/87509553-7b969f80-c67a-11ea-842a-6b220869b00d.JPG)

Expected behavior:
It should open  the customer invoice form view

**Comment by pedrobaeza** [comment]
Unfortunately this is a known issue that happens on <=v12. The good new is that this doesn't happen anymore in v13, but it's not possible to be fixed in previous versions, so closing as won't fix in v12, but fixed in v13.
