### ISSUE TITLE
Method defined but it is not used anywhere

### ISSUE THREAD

**Issue by vaidehiv-scs** [odoo/odoo#54530]
Impacted versions:
13.0

Video/Screenshot link (optional):
[https://nimb.ws/gjDPbm](url)

![screenshot-github com-2020 07 15-21_13_06](https://user-images.githubusercontent.com/65062447/87566099-268d7480-c6e0-11ea-9966-d4944568e32e.png)

**Comment by pedrobaeza** [comment]
Although there's the possibility of having dead code, its existence is harmless, but removing it can lead to other consequences. You can propose a PR to master branch if you think it's better to remove it, but for current version it should be there.

**Comment by sswapnesh** [comment]
This has been removed in master  https://github.com/odoo/odoo/commit/03efbc63ae449b2ea1e8335d1d15fd8cfbf1bc5f
