### ISSUE TITLE
[v8] email not readable - content cut off

### ISSUE THREAD

**Issue by sterbhai** [odoo/odoo#5453]
In many incoming emails, the content is not fully readable due to lines cut of in the email reading view. Also posted in the help forum with a picture.

https://www.odoo.com/forum/help-1/question/email-v8-view-not-readable-what-is-your-solution-workaround-76870

**Comment by Yenthe666** [comment]
:+1: this should be addressed.

**Comment by Yenthe666** [comment]
Hi @sterbhai,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
