### ISSUE TITLE
[8.0]Client error in purchase order

### ISSUE THREAD

**Issue by JonathanNEMRY** [odoo/odoo#5454]
**Client error in purchase order**

Impacted versions:

 - 8.0

Steps to reproduce:

 1. Go to `Request for Quotation` menu or `Purchase Orders`

Current behavior:
![selection_015](https://cloud.githubusercontent.com/assets/7601731/6367541/9bbe76e4-bcd4-11e4-88e6-b0ea0c1ceeb6.png)

Expected behavior:

No Client Error

**Comment by xmo-odoo** [comment]
Somebody had misconfigured the last 8.0 Runbot branch with a decimal precision of 100 for product prices. Don't do that.
