### ISSUE TITLE
[12.0][BUG] stock quant wrong in_date value

### ISSUE THREAD

**Issue by AdriaGForgeFlow** [odoo/odoo#54557]
**Impacted versions**: v12 (but probably others as well)

**Steps to reproduce**: 
1. Create two PO and assign its products to a package in the stock move lines
2. Move one of the packages to another location under stock
3. Go to one of the products inside the package and enter inside the quant view (this will trigger the function __unlink_zero_quants_)
![image](https://user-images.githubusercontent.com/44768500/87659337-b58ca200-c75d-11ea-8a26-755d2f152069.png)
4. (optional) move the package back to the original location
5. Create a Sale Order that can be fulfilled with products inside one of the packages and check which one is the reserved package in the Delivery Order.

**Current behavior**:
Whenever a product is received into the warehouse, when the quant for that specific product is created, the in_date is passed through from the quant in the suppliers location instead of using the current datetime. This can lead to wrongly application of fifo since multiple quants (same product but different package) will have the same in_date. Since the in_date is the same, whenever the __gather_ function is triggered, the quants are order by ID which in theory is alright because the ID at first represents the creation order.
The problem appears when, as you can see in the video, you move a quant to a location inside the warehouse. In this case a new quant is created with an ID greater than other quants of the same product in different packages. This causes that this quant, even if it was the first created, won't be the first proposed in a Sale Order when delivering products to a customer.

**Expected behavior**:
Newly created quants from reception pickings should have the creation datetime as in_date to ensure a good removal strategy.

**Video/Screenshot link** (optional):
(Long gif)

![stockQuantWrongInDate](https://user-images.githubusercontent.com/44768500/87659638-2a5fdc00-c75e-11ea-91fd-2a6fcc24dd7f.gif)

Hope it's clear. Let me know if you have further questions.

------------------------------------------------------------------------------------------------------------------------------------------
In the code, the specific lines are in addons/stock/models/stock_move_line.py

line 440: updates available quantity in suppliers location and returns the in_date of the quant in suppliers location
https://github.com/odoo/odoo/blob/12.0/addons/stock/models/stock_move_line.py#L440
line 448: updates available quantity in destination location with the in_date comming from line 440
https://github.com/odoo/odoo/blob/12.0/addons/stock/models/stock_move_line.py#L448

Maybe with a check on the source location of the move line would be enough. I'm going to try to propose a Pull Request fixing this.

cc ~ @ForgeFlow

**Comment by MiquelRForgeFlow** [comment]
Solved in https://github.com/odoo/odoo/pull/82566 (v13).

It should be closed.
