### ISSUE TITLE
[8.0] Upload Files via Attachment

### ISSUE THREAD

**Issue by Sameer1990** [odoo/odoo#5457]
**Upload Files via attachment**
Impacted versions:
- 8.0

Steps to reproduce:
1. runbot.odoo.com ( http://49488-8-0-d41649.runbot.odoo.com/ )
2. Human Resource => Employee => any employee .
3. add files(size=14 MB) via attachment.

Current behavior:
- Loading for ever .....

Expected behavior:
- Upload the file .

**Comment by michaelkarrer81** [comment]
Same problem for me for any file and any model (project.task uploaded a pdf, file size 9MB)

Just happens in quick composer mode not in full composer mode!

**Comment by winston6071** [comment]
same here....

**Comment by Yenthe666** [comment]
Hi @Sameer1990 ,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
I've just tested this on V9 and it seems to work fine. If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report though!

Regards,
Yenthe
