### ISSUE TITLE
[6.1, 7.0, 8.0]Tabulations break translation

### ISSUE THREAD

**Issue by clb-openfire** [odoo/odoo#5458]
Tabulations in .po files are written as "\t".
When these files are loaded, "\t" becomes "\t", and then becomes "t" in tools/translate.py : unquote()
Thats makes translations unable do find an src matching the text we want to translate.

I've still not migrated to git, so I propose a diff patch (should work for 6.1, 7.0 and 8.0)

```
=== modified file 'openerp/tools/translate.py'
--- openerp/tools/translate.py  2013-04-04 12:20:31 +0000
+++ openerp/tools/translate.py  2015-02-25 09:27:20 +0000
@@ -251,7 +251,7 @@
                      .replace('\n', '\\n"\n"')

 re_escaped_char = re.compile(r"(\\.)")
-re_escaped_replacements = {'n': '\n', }
+re_escaped_replacements = {'n': '\n', 't': '\t'}

 def _sub_replacement(match_obj):
     return re_escaped_replacements.get(match_obj.group(1)[1], match_obj.group(1)[1])
```

**Comment by Yenthe666** [comment]
Hi @clb-openfire ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: This should be handled in newer versions.

Regards,
Yenthe
