### ISSUE TITLE
Wrong view opened if field becomes readonly

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#5462]
I have defined different view for stock.production.lot. I need it to open that view from other specific views, for example from sale order line view.

So I did this (in inherited sale.order view):

``` xml
 <field name="licence_id"
context="{'default_licence': True, 'form_view_ref': 'sale_prod_lot_licence.view_production_lot_form_licence'}"/>
```

The thing is, it opens that specified view only when sale order is not confirmed. When it is confirmed and all fields in sale order line become readonly, then when I go to that line and press on that field to open `stock.production.lot` model custom view, for some reason it opens default view instead (**the view that comes with 'stock' module**). 
Of course if I put sequence in my custom view to be lower than original view, then it opens my custom view from sale order line, but then it also opens it from warehouse menu, and then original view won't be opened anywhere.

So my question is, why `form_view_ref` is ignored when relation field becomes readonly?..

**Comment by Yenthe666** [comment]
Hi @oerp-odoo,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
