### ISSUE TITLE
Failed to load resource: net :: ERR_CONTENT_LENGTH_MISMATCH | Odoo screen blank after login

### ISSUE THREAD

**Issue by shazzwazz20** [odoo/odoo#54651]
Impacted versions:
Odoo 12.0

Steps to reproduce:

Add workers to .conf file

Current behavior:
Page is blank or css not loading properly.

Failed to load resource: net :: ERR_CONTENT_LENGTH_MISMATCH | Odoo screen blank after login

Expected behavior:
Css or page should properly

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/12.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).

**Comment by shazzwazz20** [comment]
Hi, the issue comes randomly.So i am not able to reproduce it or debug.

Sometime it works and sometime doesn't.

I have not installed ngninx/apache after enable worker in .conf file.
Configuring ngninx/apache will solve the issue?

**Comment by pedrobaeza** [comment]
No, your problem probably comes from workers memory limits, but this is out of scope of the issue tracker. For more questions, ask on the forums.

**Comment by shazzwazz20** [comment]
@pedrobaeza : Thanks for your feedback.  I have posted the question on forum but did not got any response yet.

**This is forum post**: https://www.odoo.com/es_ES/forum/ayuda-1/question/failed-to-load-resource-net-err-content-length-mismatch-odoo-screen-blank-after-login-173508

Since the issue has come up on production , i wanted to fix as earliest.
Below is my  odoo.conf file worker configuration . 
OS: Ubuntu 16.04
Python: 3.5
RAM: 16gb
CPU: 8core


proxy_mode = True
;Worker Settings
limit_memory_hard = 13690208256
limit_memory_soft = 11408506880
limit_request = 16384
limit_time_cpu = 3600
limit_time_real = 7200
max_cron_threads = 2
workers = 17

Any help would be appreciated to sort this issue.
