### ISSUE TITLE
Product Variant's functionality not proper 

### ISSUE THREAD

**Issue by bhaveshselarka** [odoo/odoo#5465]
Hello,

I have found some problem in product variant functionality of odoo. It behaves wrong as per below mentioned flow,

First create one product and add attribute color only now make sales order of any one of product from this and now go that product again and add size attribute now saves that product.

My all previous product active false and create new products with new combinations.Now go to previous sales order and then its allow to deliver that product also which inactive.

Can anyone explain why this happened ?

Here i am pasting a some code also which makes product active false its in product/product.py line no. 700

```
        for variant_id in map(int,variants_inactive):
            try:
                with cr.savepoint():
                    product_obj.unlink(cr, uid, [variant_id], context=ctx)
            except (psycopg2.Error, osv.except_osv):
                product_obj.write(cr, uid, [variant_id], {'active': False}, context=ctx)
                pass
    return True
```

Thanks in advance.

**Comment by Yenthe666** [comment]
Hi @bhaveshselarka,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
