### ISSUE TITLE
[Whishlist] Do not show edit/delete button if a user can't edit/delete a record

### ISSUE THREAD

**Issue by anthony-muschang** [odoo/odoo#5467]
If a record rule does not give write access on a specific record, the user should not be tempted to edit it.

**Comment by Yenthe666** [comment]
Hi @anthony-muschang,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
