### ISSUE TITLE
Remove autofill of manager field for manager of department

### ISSUE THREAD

**Issue by frlanxpertiz** [odoo/odoo#54686]
Impacted versions:13.0

Steps to reproduce:
Set an employe to be the manager of a department
set this department as the department of the employee
save
Current behavior:
The manager field is autofilled with the user itself which make the org chart loop
Expected behavior:
Either the manager should be autofilled as the manager of the parent department 
or the manager field should be left blank in such cases
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
I don't consider this critical, but tagging for seeing if Odoo thinks on contrary.

**Comment by sswapnesh** [comment]
Duplicate of https://github.com/odoo/odoo/issues/47043 

> it is an intentional behavior

As said in https://github.com/odoo/odoo/issues/47043#issuecomment-596453145
