### ISSUE TITLE
8.0: a stock picking can be returned more than once. 

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#5469]
## steps to reproduce:
- install sale_stock
- configure the warehouse with Pick Pack Ship
- create a Sale Order with 1 ipod
- run the scheduler
- click the View Delivery Order on the sale order form
- transfer the Pick/0001 picking 
- create a reverse picking for the transfered Pick picking -> Pick/0002
- display the Pick/0001 picking 
## expected:

the button to create a return for the picking is not available because a return for the whole quantity has 
been created
## actual:

the button is there. When I click it, the wizard offers to return the original quantity (1) (offering to return the remaining transfered (0) would be OK
## More

If I process Pick/0002 and create a second reverse picking for Pick/0001 (-> Pick/0003), the new picking is available for transfer, which will probably cause weird stuff with the quants.

**Comment by gurneyalex** [comment]
I tested the above on runbot with the fix for #5253 applied. I don't know if it is related to this fix. 

@jco-odoo you opinion on this is very welcome

cc @jgrandguillaume

**Comment by gurneyalex** [comment]
I tested without the fix applied and I was able to reproduce, so it is not related.

**Comment by jco-odoo** [comment]
The logic is that it should propose all the quants that went through the move you make the return for and are still in the destination location of that move.  (and if this quant is not reserved on a returned move already)

**Comment by Yenthe666** [comment]
Hi @gurneyalex,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
