### ISSUE TITLE
[13.0] [Website] get access error in website menu when set lowest permissions

### ISSUE THREAD

**Issue by MojtabaAp** [odoo/odoo#54695]
Hi
in runbot branch 13.0 when i set lowest permission for user. when user open website menu get this access error.

Sorry, you are not allowed to access documents of type 'Sales Order' (sale.order). This operation is allowed for the groups:
	- Inventory/User
	- Invoicing/Billing
	- Manufacturing/User
	- Project/Administrator
	- Sales/Administrator
	- Sales/User: Own Documents Only
	- Technical Settings/Show Full Accounting Features
	- User types/Portal - (Operation: read, User: 8)

when set invoice/billing access this error fix.

![Screenshot from 2020-07-19 10-29-30](https://user-images.githubusercontent.com/36371067/87868475-296fba00-c9ab-11ea-8ab4-19f799b3c0d6.png)
![Screenshot from 2020-07-19 10-30-08](https://user-images.githubusercontent.com/36371067/87868477-2b397d80-c9ab-11ea-9b02-7c20615eb210.png)
![Screenshot from 2020-07-19 10-30-13](https://user-images.githubusercontent.com/36371067/87868478-2c6aaa80-c9ab-11ea-8617-2b3bf2d017bc.png)

**Comment by pedrobaeza** [comment]
I'm not sure what do you mean by "website menu". Can you put a video reproducing the problem?

**Comment by MojtabaAp** [comment]
@pedrobaeza i attach a video

https://drive.google.com/file/d/1C2nK0rsRDr_O2wSjM4Rif3S9FTtNlND6/view?usp=sharing

**Comment by pedrobaeza** [comment]
I think that's something expected, as you don't have the permissions. The only thing I see to improve is to not show the section "Website" in the menu.

@JKE-be why that menu is shown?
