### ISSUE TITLE
on Fresh ubuntu 18.04 pip requirements.txt install fails on python3.8 

### ISSUE THREAD

**Issue by MjAbuz** [odoo/odoo#54694]
Impacted versions: 13

Steps to reproduce:
```
Current behavior:ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-a2vqp9di/ebaysdk/setup.py'"'"'; __file__='"'"'/tmp/pip-install-a2vqp9di/ebaysdk/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-0gv_cmwj
         cwd: /tmp/pip-install-a2vqp9di/ebaysdk/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 20, in <module>
        from setuptools.dist import Distribution, Feature
      File "/usr/local/lib/python3.8/site-packages/setuptools/dist.py", line 35, in <module>
        from setuptools import windows_support
      File "/usr/local/lib/python3.8/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
      File "/usr/local/lib/python3.8/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ModuleNotFoundError: No module named '_ctypes'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
Seems like its a common issue and this is what i got after browsing around ..see attached

[

](url)
Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Well, Python 3.8 compatibility is not assured, but let's see if @d-fence thinks it's worth to fix it for this version. General question for you and also for @mart-e @odony: isn't better to reduce the scope of the compatibility from `>= Python 3.6` to a reduced scope `Python 3.6 or Python 3.7` for avoiding this false expectations, also when Python 3.9 will go out?

**Comment by mart-e** [comment]
Hi,

Same answer as my previous comment at https://github.com/odoo/odoo/issues/41313#issuecomment-580162984.
The python 3.8 compatiblity is assured, even in 11.0 but the requirements.txt is not. You may have to tweak a bit the versions of the dependencies you install but you should be able to run Odoo on any python version >= 3.6.
If you notice errors running Odoo 13.0 in 3.8 (or even in 3.9), please let us know, we will fix these. If you have errors in the dependencies, these may need to be upgraded in case by case.

As I understand your report, you have manually upgraded the python version of your ubuntu installation (ubuntu 18.04 is supposed to run 3.6.5).
Reading the traceback, the error is not in the dependency installation but in setuptools itself. It is very likely that you are missing some `-dev` dependencies or that something is missing in your python install. This is out of the scope of the odoo installation.
