### ISSUE TITLE
pack created in transfer wizard does not compute the owner

### ISSUE THREAD

**Issue by lepistone** [odoo/odoo#5470]
To reproduce in runbot v8:
- enable "Manage owner on stock" and "Manage advanced routes for your warehouse" in warehouse configuration
- configure the warehouse for 3-step delivery (pick-pack-ship)
- take the product "ipad with retina display" (it has no stock with demo data)
- create a new picking IN for that product with owner "China export" and receive it
- check that you have in stock a quant of that product with owner "China export", and no other quants of that product
- create a sale for that product, validate id
- run the scheduler
- open the first picking. It should be available.
- In the transfer wizard, put the stock in a new package.
- Complete the transfer
- Open the created package: the owner of the package is empty
- The package contains quants that belong to China Export: it should have the same owner as its contents.
- Instead, the package has no owner, which is wrong.

Hint: it is probably a problem in the trigger of the method `_get_package_info`. The method is never called.

Thanks!

**Comment by jco-odoo** [comment]
Deletion of quants should never be done.  Doing a simple inventory should be able to care about that.  

For the _get_package_info: it is the same path as for the company_id as for the location_id, so if you could check that all the quants in the package have this owner, then we could really know if this _get_package_info is the cause.

**Comment by lepistone** [comment]
Hi @jco-odoo, thanks for your reply.

I deleted quants only to help me reproduce quickly, but I think you get the same result with an inventory.

FYI: this is support ticket 628913: I am sure the support team will try to find the cause as you suggest.

**Comment by jco-odoo** [comment]
In my case it is simply because the owner is not put on the move.  So there is negative stock created without owner associated.

**Comment by gurneyalex** [comment]
Hello @jco-odoo 
I just spent a few minutes to run @lepistone's scenario of runbot.odoo.com starting with a base database on which I installed sale, stock + configured "manage owner", "manage advanced routes" and "manage packages". 

creation of the incoming picking with owner:

![screenshot from 2015-03-16 11 10 14](https://cloud.githubusercontent.com/assets/2032807/6664355/4a8cebd4-cbcf-11e4-933d-5de46522b8cb.png)

I get a quant with owner in the Stock location:

![screenshot from 2015-03-16 11 10 47](https://cloud.githubusercontent.com/assets/2032807/6664373/6b07d112-cbcf-11e4-913f-45ebe1ca7c15.png)

Create a SO 

![screenshot from 2015-03-16 11 11 49](https://cloud.githubusercontent.com/assets/2032807/6664378/739afdf4-cbcf-11e4-87a3-5b6f7a457681.png)

Run the scheduler, the Pick move of the SO is ready to transfer:

![screenshot from 2015-03-16 11 12 25](https://cloud.githubusercontent.com/assets/2032807/6664398/8aba5692-cbcf-11e4-97f2-431576b486b9.png)

When processing the picking, put the product in a package:

![screenshot from 2015-03-16 11 13 54](https://cloud.githubusercontent.com/assets/2032807/6664413/b6169742-cbcf-11e4-892c-e5ab49bebfa3.png)

Result, I have a package without an owner:

![screenshot from 2015-03-16 11 15 45](https://cloud.githubusercontent.com/assets/2032807/6664426/d7381ae0-cbcf-11e4-9df2-5584611ffdcc.png)

containing a quant with an owner in location Packing zone:

![screenshot from 2015-03-16 11 17 16](https://cloud.githubusercontent.com/assets/2032807/6664446/ec34371c-cbcf-11e4-99f4-c5f1a9fe3b96.png)

There is no negative stock created as far as I can tell, and this is with as plain an Odoo setup that I can create.

**Comment by Yenthe666** [comment]
Hi @lepistone,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
