### ISSUE TITLE
Cannot open Menu Items / Purchases/Purchase/Quotations

### ISSUE THREAD

**Issue by librevilzz** [odoo/odoo#5472]
Impacted versions:

-7.0

Steps to reproduce:

-Login as admin 
-setting.
-Technical -> User Interface -> Menu items

Current behaviour:

-all record that have value in "action" field, prompt error when we open it

-here is error look like:
Uncaught TypeError: Cannot read property 'render_value_defs' of undefined
http://192.168.1.188:8069/web/webclient/js?db=test3:3628

**Comment by lukebranch** [comment]
@librevilzz ,

If you'd like this taken a look at by Odoo's developer team I recommend that you provide the steps to reproduce the error, and information about your setup (OS, installation method, community modules installed, etc.).

Here's a template you could use (first post):

https://github.com/odoo/odoo/issues/3339

You may also want to include some excerpts from your log files.

**Comment by librevilzz** [comment]
@lukebranch ,

thanks for advise sir, already update it :+1:

**Comment by satyakishores** [comment]
I have modified menu items in odoo10. After that users with the settings rights are getting 500 Internal Server error. Users without the settings access are able to access the web. 
Error:
'menu_data': request.env['ir.ui.menu'].load_menus(request.debug),
  File "<decorator-gen-218>", line 2, in load_menus

  File "/usr/lib/python2.7/dist-packages/odoo/tools/cache.py", line 87, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web_tour/models/ir_ui_menu.py", line 35, in load_menus
    _find_subtree(menu_root, menu_id)['xmlid'] = menu_xmlid
TypeError: 'NoneType' object does not support item assignment
@Yenthe666  please help.

**Comment by Yenthe666** [comment]
Hi @satyakishores,

Please don't start asking other questions on a topic that is not related and about another Odoo version.
Please ask this question on the official Odoo help forum (http://odoo.com/help).
@librevilzz I'm closing this issue as Odoo V7 is no longer supported by Odoo. if you still face this issue in Odoo 8, 9 or 10 don't hesitate to create a new bug report.

Regards,
Yenthe
