### ISSUE TITLE
Odoo (data_dir)

### ISSUE THREAD

**Issue by LcL54264** [odoo/odoo#54738]
Impacted versions: odoo12

hello,

Hope you have a good day.

I have a problem using Odoo, so I need your help

I accidentally deleted the file storage in the data_dir directory during my use of odoo. Is there any way to make my system work normally?

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
