### ISSUE TITLE
Can't find user by email

### ISSUE THREAD

**Issue by Heki67** [odoo/odoo#54806]
Impacted versions: 13

Steps to reproduce:
user = request.env["res.users"].search([('login', 'ilike', email)])

Current behavior:
Doesn't return any user, although there is a record have login = email

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question about development. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Anyway, this is working fine in my side other times that I have done it.

Closing this by the reason above.
