### ISSUE TITLE
[8.0] Error on field_name

### ISSUE THREAD

**Issue by malatestay** [odoo/odoo#5482]
I encounter this error in several areas of software and makes it unusable, for example impossoble enter the lines of an order of sale or purchase.
But also in other places.
This subject had was in late 2014 and seems to come back !!

  File "/usr/local/lib/python2.7/dist-packages/openerp-8.0-py2.7.egg/openerp/models.py", line 5711, in onchange
    if field_name and field_name not in self._fields:
TypeError: unhashable type: 'list'

**Comment by xmo-odoo** [comment]
I can not reproduce the issue locally, could you provide a repro case, ideally on a runbot instance?

**Comment by malatestay** [comment]
@xmo-odoo I can do a video on case i have this error, can you precise me what is a runbot instance ?

**Comment by xmo-odoo** [comment]
http://runbot.odoo.com/runbot builds all the Odoo branches at (more or less) each commit, and makes them available for testing. Green rectangles passed all their tests, red rectangles failed some tests, blue are currently building/testing, white is a pending test.

For each valid build (green-background rectangle) the blue button opens the "all" branch with all modules installed, you can also open the "base" branch with only "base" installed by clicking on the small gear and  selecting "connect base" (or "connect" to create a new branch)

**Comment by malatestay** [comment]
@xmo-odoo I have do a test with same installation (ubuntu 14.04 Posgresql 9.4) with last revision at this time, and new DB with demo datas.
It is impossible to install sales module i have following error.
For me this is the same raison it is impossible to do something in my previous database.

  File "/opt/odoo/addons/account/account_move_line.py", line 1399, in create
    recompute = journal.env.recompute and context.get('recompute', True)
ParseError: ""'Environment' object has no attribute 'recompute'" while evaluating
u'action_move_create()'" while parsing /opt/odoo/addons/account/demo/account_invoice_demo.xml:72, near
<workflow action="invoice_open" model="account.invoice" ref="invoice_1"/>

**Comment by malatestay** [comment]
After a fresh install (Ubuntu & Odoo 8) it seems that mistakes like this one disappeared without knowing the origin of this error because my previous installation appeared feature! For this reason I close this issue.
