### ISSUE TITLE
Sales > Opportunities - Mark Won button not working

### ISSUE THREAD

**Issue by cardaba** [odoo/odoo#5485]
Odoo v8 we are having problems with the 'Mark won' button under 'Sales > Opportunities'. When clicked it displays the following Odoo Warning!

Warning!

To relieve your sales pipe and group all Won opportunities, configure one of your sales stage as follow:
probability = 100 % and select "Change Probability Automatically".
Create a specific stage or edit an existing one by editing columns of your opportunity pipe.

The solution that I found is changing the code in crm_lead.py:
- case_mark_lost -->  stage_id = self.stage_find(cr, uid, [lead], lead.section_id.id or False, [('probability', '=', 0.0), ('on_change', '=', True), ('sequence', '>', 1)], context=context)
- case_mark_won --> stage_id = self.stage_find(cr, uid, [lead], lead.section_id.id or False, [('probability', '=', 100.0), ('on_change', '=', True)], context=context)

Regards

**Comment by mv-taktik** [comment]
:+1:

**Comment by Yenthe666** [comment]
Hi @cardaba,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
