### ISSUE TITLE
Chatbox and Sidemenu Overlaps

### ISSUE THREAD

**Issue by anandgodavarma** [odoo/odoo#54875]
Impacted versions: 10 community

Steps to reproduce: For arabic translation on implementing RTL the right side menu and chat box overlaps

Current behavior: Chatbox and menu overlaps

Expected behavior: The cahtbox sholud be floating and the user can place it anywhere 

Video/Screenshot link (optional):
![Screenshot from 2020-07-24 12-17-24](https://user-images.githubusercontent.com/24294204/88367601-d41c1a00-cda9-11ea-9487-aab4f863af1c.png)

**Comment by pedrobaeza** [comment]
Sorry, version 10 is no longer supported. Only latest 3 versions are (13, 12 and 11 in this moment). If the problems remains in upper versions, please open a new issue.
