### ISSUE TITLE
Models have no table: sale.report when updating few specific modules

### ISSUE THREAD

**Issue by bizzappdev** [odoo/odoo#54919]
Impacted versions: 13, 14 (working proper in v12 

Steps to reproduce:
1. Create a new database with "-i hr,sale_stock,sale_margin,point_of_sale".
2. we have warehouse_id and margin in the sale_report SQL View.
3. Update the database with -u hr 
4. margin and warehouse_id fields are no longer in SQL View.

Current behaviour:  
1.  odoo.modules.registry: Models have no table: sale.report and Recreate table of model sale.report in the log.
2. it is resetting sale.report view and while calling init it is not considering the sale_stock and sale_margin init/_query method and so it is missing the fields added from those modules.

Expected behaviour: either it not recreate the sale.report SQL view and it should be available already. or it should consider sale_stock and sale_margin modules also.

**Comment by Yenthe666** [comment]
Hmm that's an interesting one. @Elkasitu @mart-e who could check this out?

**Comment by bizzappdev** [comment]
FYI OPW-2306523

**Comment by pedrobaeza** [comment]
The OPW team has said something about this?

**Comment by ploegvde** [comment]
Nope, the are not that fast ;(

**Comment by bizzappdev** [comment]
Same Behaviour in V14 also.

**Comment by nle-odoo** [comment]
Hi,


This should be solved with this change: https://github.com/odoo/odoo/pull/57443

Regards.
