### ISSUE TITLE
My Current Timesheet doesn't verify exit without saving modifications

### ISSUE THREAD

**Issue by tuomoaura** [odoo/odoo#5492]
My Current Timesheet doesn't verify if user wants to exit without saving modifications.

**Impacted versions:**

8.0

**Steps to reproduce:**

Open My Current Timesheet
Add a project with some hours
Don't save
Exit view
Go back to My Current Timesheet

All your projects and hours after previous save has disappeared.

**Expected behavior:**

Odoo should verify user if there are unsaved hours and user is trying to leave the page without saving modifications.

**Comment by scosist** [comment]
I ran into the same issue yesterday. I was surprised to return to `hr.timesheet.sheet.form` (My Current Timesheet form view) and not find the changes I had entered earlier.

**Comment by Yenthe666** [comment]
Hi @tuomoaura,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
