### ISSUE TITLE
How change color text theme

### ISSUE THREAD

**Issue by movahhed** [odoo/odoo#54928]
![20200725_165453.jpg](https://user-images.githubusercontent.com/27208274/88456950-cc3aa380-ce97-11ea-8000-e853ec3ddc3b.jpg)

There are problem with odoo 12. In mobile display mode, the color of the text or the background color of the top menu bar is inappropriate.
How can I fix it?

**Comment by pedrobaeza** [comment]
Odoo Community is not mobile responsive. Try OCA's web_responsive module.

Anyway, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
