### ISSUE TITLE
Live chat  module send file problem

### ISSUE THREAD

**Issue by bahram-ashrafi** [odoo/odoo#54927]
Impacted versions: 13.0

Steps to reproduce: start chat and send a file but that file not shown

Current behavior: Dont show file

Expected behavior: Show file

Video/Screenshot link (optional):
https://youtu.be/38WVECKMPtU

**Comment by pedrobaeza** [comment]
Not sure if there's support for files in the chat. @JKE-be are you the one for chat things?

**Comment by JKE-be** [comment]
@odoo/rd-discuss ... it is probably for your

**Comment by alexkuhn** [comment]
Hello, sending files in live chat is indeed not supported yet. To make this clear, we're removing the "Add file" button in operator live chat composer in #54957.
