### ISSUE TITLE
[12.0][BUG] pos_sale, query could end in ambiguous qty field

### ISSUE THREAD

**Issue by GSLabIt** [odoo/odoo#54933]
Impacted versions: 12.0, 13.0

https://github.com/odoo/odoo/blob/bfd2b669c056cc9fa6e97992944e66aac7c1092a/addons/pos_sale/report/sale_report.py#L31-L32

this 2 lines could generate an ambiguous `qty` field if declared in any of the tables in JOIN; should be `l.qty` ins't it?

**Comment by GSLabIt** [comment]
@Yenthe666 what u think?

**Comment by Yenthe666** [comment]
@pimodoo it's final call but I don't think it would be bad to be less ambiguous yes :)

**Comment by pimodoo** [comment]
@GSLabIt @Yenthe666 Hello,

As for now there are no other tables having a qty field, I won't fix it in stable version. So I made the pull request in master: https://github.com/odoo/odoo/pull/54960 to avoid  introducing bugs.

Thanks

**Comment by Yenthe666** [comment]
Sounds fair to me as it is an improvement. Since it'll be merged in right away this can be closed.
