### ISSUE TITLE
Openerp 500 internal server error

### ISSUE THREAD

**Issue by yesh-hsey** [odoo/odoo#5499]
Once my server starts.. http://localhost:8069/ (UBUNTU 14.04)
I get this error.. How am i suppose to overcome?
Thanks in advance..
------------------------------------------------------------------------------------------------------------------------------
ERROR:

Internal Server Error

{"message": "OpenERP Server Error", "code": 200, "data": {"debug": "Server Traceback (most recent call last):\n File \"/opt/openerp/server/openerp/addons/web/session.py\", line 89, in send\n return openerp.netsvc.dispatch_rpc(service_name, method, args)\n File \"/opt/openerp/server/openerp/netsvc.py\", line 296, in dispatch_rpc\n result = ExportService.getService(service_name).dispatch(method, params)\n File \"/opt/openerp/server/openerp/service/web_services.py\", line 140, in dispatch\n return fn(*params)\n File \"/opt/openerp/server/openerp/service/web_services.py\", line 365, in exp_list\n cr = db.cursor()\n File \"/opt/openerp/server/openerp/sql_db.py\", line 486, in cursor\n return Cursor(self.__pool, self.dbname, serialized=serialized)\n File \"/opt/openerp/server/openerp/sql_db.py\", line 182, in __init__\n self._cnx = pool.borrow(dsn(dbname))\n File \"/opt/openerp/server/openerp/sql_db.py\", line 377, in _locked\n return fun(self, *args, **kwargs)\n File \"/opt/openerp/server/openerp/sql_db.py\", line 442, in borrow\n result = psycopg2.connect(dsn=dsn, connection_factory=PsycoConnection)\n File \"/usr/lib/python2.7/dist-packages/psycopg2/__init__.py\", line 179, in connect\n connection_factory=connection_factory, async=async)\nOperationalError: FATAL: role \"openerp\" does not exist\n\n\nClient Traceback (most recent call last):\n File \"/opt/openerp/server/openerp/addons/web/http.py\", line 285, in dispatch\n r = method(self, **self.params)\n File \"/opt/openerp/server/openerp/addons/web/controllers/main.py\", line 570, in index\n db, redir = db_monodb_redirect(req)\n File \"/opt/openerp/server/openerp/addons/web/controllers/main.py\", line 98, in db_monodb_redirect\n return db_redirect(req, not config['list_db'])\n File \"/opt/openerp/server/openerp/addons/web/controllers/main.py\", line 104, in db_redirect\n dbs = db_list(req, True)\n File \"/opt/openerp/server/openerp/addons/web/controllers/main.py\", line 90, in db_list\n dbs = proxy.list(force)\n File \"/opt/openerp/server/openerp/addons/web/session.py\", line 30, in proxy_method\n result = self.session.send(self.service_name, method, *args)\n File \"/opt/openerp/server/openerp/addons/web/session.py\", line 103, in send\n raise xmlrpclib.Fault(openerp.tools.ustr(e), formatted_info)\nFault: &lt;Fault FATAL: role \"openerp\" does not exist\n: 'Traceback (most recent call last):\\n File \"/opt/openerp/server/openerp/addons/web/session.py\", line 89, in send\\n return openerp.netsvc.dispatch_rpc(service_name, method, args)\\n File \"/opt/openerp/server/openerp/netsvc.py\", line 296, in dispatch_rpc\\n result = ExportService.getService(service_name).dispatch(method, params)\\n File \"/opt/openerp/server/openerp/service/web_services.py\", line 140, in dispatch\\n return fn(*params)\\n File \"/opt/openerp/server/openerp/service/web_services.py\", line 365, in exp_list\\n cr = db.cursor()\\n File \"/opt/openerp/server/openerp/sql_db.py\", line 486, in cursor\\n return Cursor(self.__pool, self.dbname, serialized=serialized)\\n File \"/opt/openerp/server/openerp/sql_db.py\", line 182, in __init__\\n self._cnx = pool.borrow(dsn(dbname))\\n File \"/opt/openerp/server/openerp/sql_db.py\", line 377, in _locked\\n return fun(self, *args, **kwargs)\\n File \"/opt/openerp/server/openerp/sql_db.py\", line 442, in borrow\\n result = psycopg2.connect(dsn=dsn, connection_factory=PsycoConnection)\\n File \"/usr/lib/python2.7/dist-packages/psycopg2/__init__.py\", line 179, in connect\\n connection_factory=connection_factory, async=async)\\nOperationalError: FATAL: role \"openerp\" does not exist\\n\\n'&gt;\n", "fault_code": "FATAL: role \"openerp\" does not exist\n", "type": "server_exception"}}

**Comment by lithint** [comment]
Dear yesh,
create  a postgresql user with name openerp or specify the postgres user
name in .config file

On Fri, Feb 27, 2015 at 11:17 AM, yesh-hsey <notifications@github.com>
wrote:

> Once my server starts.. http://localhost:8069/
> I get this error.. How am i suppose to overcome?
> Thanks in advance..
>
> ERROR:
>
> Internal Server Error
>
> {"message": "OpenERP Server Error", "code": 200, "data": {"debug": "Server
> Traceback (most recent call last):\n File
> \"/opt/openerp/server/openerp/addons/web/session.py\", line 89, in send\n
> return openerp.netsvc.dispatch_rpc(service_name, method, args)\n File
> \"/opt/openerp/server/openerp/netsvc.py\", line 296, in dispatch_rpc\n
> result = ExportService.getService(service_name).dispatch(method, params)\n
> File \"/opt/openerp/server/openerp/service/web_services.py\", line 140, in
> dispatch\n return fn(*params)\n File
> \"/opt/openerp/server/openerp/service/web_services.py\", line 365, in
> exp_list\n cr = db.cursor()\n File
> \"/opt/openerp/server/openerp/sql_db.py\", line 486, in cursor\n return
> Cursor(self.pool, self.dbname, serialized=serialized)\n File
> \"/opt/openerp/server/openerp/sql_db.py\", line 182, in __init\n self._cnx
> = pool.borrow(dsn(dbname))\n File
> \"/opt/openerp/server/openerp/sql_db.py\", line 377, in _locked\n return
> fun(self, *args, **kwargs)\n Fil e
> \"/opt/openerp/server/openerp/sql_db.py\", line 442, in borrow\n result =
> psycopg2.connect(dsn=dsn, connection_factory=PsycoConnection)\n File
> \"/usr/lib/python2.7/dist-packages/psycopg2/*init*.py\", line 179, in
> connect\n connection_factory=connection_factory,
> async=async)\nOperationalError: FATAL: role \"openerp\" does not
> exist\n\n\nClient Traceback (most recent call last):\n File
> \"/opt/openerp/server/openerp/addons/web/http.py\", line 285, in dispatch\n
> r = method(self, **self.params)\n File
> \"/opt/openerp/server/openerp/addons/web/controllers/main.py\", line 570,
> in index\n db, redir = db_monodb_redirect(req)\n File
> \"/opt/openerp/server/openerp/addons/web/controllers/main.py\", line 98, in
> db_monodb_redirect\n return db_redirect(req, not config['list_db'])\n File
> \"/opt/openerp/server/openerp/addons/web/controllers/main.py\", line 104,
> in db_redirect\n dbs = db_list(req, True)\n File
> \"/opt/openerp/server/openerp/addons/web/controllers/main.py\", line 90, in
> db_list\n dbs = proxy.list(force)\n File
> \"/opt/openerp/server/openerp/addons/web/session.py\", line 30, in
> proxy_method\n result = self.session.send(self.service_name, method,
> *args)\n File \"/opt/openerp/server/openerp/addons/web/session.py\", line
> 103, in send\n raise xmlrpclib.Fault(openerp.tools.ustr(e),
> formatted_info)\nFault: <Fault FATAL: role \"openerp\" does not exist\n:
> 'Traceback (most recent call last):\n File
> \"/opt/openerp/server/openerp/addons/web/session.py\", line 89, in send\n
> return openerp.netsvc.dispatch_rpc(service_name, method, args)\n File
> \"/opt/openerp/server/openerp/netsvc.py\", line 296, in dispatch_rpc\n
> result = ExportService.getService(service_name).dispatch(method, params)\n
> File \"/opt/openerp/server/openerp/service/web_services.py\", line 140, in
> dispatch\n return fn(*params)\n File
> \"/opt/openerp/server/openerp/service/web_services.py\", line 365, in
> exp_list\n cr = db.cursor()\n File
> \"/opt/openerp/server/openerp/sql_db.py\", line 486, in cursor\n return
> Cursor(self.*pool, self.dbname, serialized=serialized)\n File
> \"/opt/openerp/server/openerp/sql_db.py\", line 182, in __init*\n self.*cnx
> = pool.borrow(dsn(dbname))\n File
> \"/opt/openerp/server/openerp/sql_db.py\", line 377, in locked\n return
> fun(self, args, *kwargs)\n File \"/opt/openerp/server/openerp/sql_db.py\",
> line 442, in borrow\n result = psycopg2.connect(dsn=dsn,
> connection_factory=PsycoConnection)\n File
> \"/usr/lib/python2.7/dist-packages/psycopg2/__init*.py\", line 179, in
> connect\n connection_factory=connection_factory,
> async=async)\nOperationalError: FATAL: role \"openerp\" does not
> exist\n\n'>\n", "fault_code": "FATAL: role \"openerp\" does not exist\n",
> "type": "server_exception"}}
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/odoo/odoo/issues/5499>.
>



-- 
Thanks & Regards,

Lithin T
Software Engineer
Mob  : +91 7736561076(India), +971556712557(UAE)
Mail  : lithint.mail@gmail.com | Skype : lithint.skype

**Comment by yesh-hsey** [comment]
Dear Lithint, 
thank you so much.. it worked..
