### ISSUE TITLE
Binary Field shouldn't load all base64 data when the object data is loaded

### ISSUE THREAD

**Issue by a0c** [odoo/odoo#5501]
Once [reported on launchpad and fixed](https://bugs.launchpad.net/openerp-web/+bug/914272), this issue is back again.
#### Current behavior

The data of a **binary** field (the base64 text) is loaded when the object is loaded.

This means when you open a form view with a binary field:
    `<field name="image"/>`
the file is downloaded and stored in the browser memory.

For huge files (30MB) you can start feeling it. Especially, if you have several such files attached to your object.
#### Expected behavior

The data of the binary field should be downloaded only when the user clicks on the link to save the file.

**Comment by Yenthe666** [comment]
Hi @a0c,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
