### ISSUE TITLE
Pricelist Order of Operation not Configurable, Product Variants can't have discounts in eCommerce

### ISSUE THREAD

**Issue by walkerblackwell** [odoo/odoo#55017]
Impacted versions: all (specifically v13)

Steps to reproduce:

Create a percentage discount in pricelist for product category X of say 10% discount. All product.templates of category X will have discount of 10% unless otherwise specified in the product.template price-list line. Create a variant product with choosable attributes. Do extra price for each attribute so the different selections have different prices. The prices for the variants are not discounted (only the first lowest price variant from product.template). This is unexpected from a user standpoint and essentially halts using variant products with pricelist discounts on the web store effectively.

Current behavior:

Child products of product.template are not discounted because pricelist rules enforce product variants prices above product category prices. This results in only the cheapest product having a discount and all selected product variants in eCommerce not having discount. There is no base extra pice and discount field in the "extra prices" section or per-variant pricelist section either. No way to configure this.

Expected behavior:

Discounts applied to product categories should apply to product variants that are in those categories.

- Child (product.product) of product.template should use category discounts if applied lower in the pricelist priority and not applied in product variant pricelist line (currently unable to be applied in product variant pricelist line)
- There should be a base price and discount % field for product variants just like there is for product templates (api change sadly).
- Pricelist lines should be sequence-able.

**Comment by pedrobaeza** [comment]
AFAIK, this is possible, as product variant pricelist item have more priority than template ones. Can you please put screenshots of your configuration?

**Comment by walkerblackwell** [comment]
Making a product variant set as Discount instead of Fixed Price uses the price from the product.template (lowest price) and discounts from there. That will never work as variants are "extra prices" so that thinking is flawed and nobody has fixed it since god knows when.

Here's a video showing it:

[Screen Recording 2020-07-29 at 2.41.50 PM.mp4.zip](https://github.com/odoo/odoo/files/4996842/Screen.Recording.2020-07-29.at.2.41.50.PM.mp4.zip)

Creating a second variant product pircelist line set as discount instead of fixed with the first variant at a fixed (extra) price still pulls the price from the product template even though it's higher in priority and there's a Fixed variant price list line between product template and variant discount. It does not pick up from the variant.

This is pretty huge IMO. Nobody can do standard discount promo upsell e-commerce with variant products and Odoo since forever.

**Comment by pedrobaeza** [comment]
If you want to have first a fixed price for a variant and then a discount, you need to make 2 pricelists: one with the fixed prices, and the other based on the previous one adding the discounts, and use the second one in the website.

Closing as no issue, but expected behavior.

**Comment by walkerblackwell** [comment]
Seems to be an issue maybe with the js or qweb for pricing because calculating price in formula against another upstream pricelist does calculate the correct final total (with discount applied) but does _not_ show original price and final price if that option is selected in Odoo. So it's back to square one unfortunately.
