### ISSUE TITLE
When make an invoice from duplicate delivery order linked to a sale order, the partner of the sale order is used in the invoice.

### ISSUE THREAD

**Issue by Wided1** [odoo/odoo#5502]
Steps to reproduce:

Create a sale order
Create a delivery order from that sale order
Duplicate that delivery order
Change the partner for the new delivery order
Create an invoice from the new delivery order

The partner of the invoice is the partner of the sale order.

In my company we used to duplicate a lot of delivery orders to gain time in openerp 6, we can't do it any more in openerp 7 due to this issue.

When I looked in the code, the function _get_partner_to_invoice()  is inherited in sale_stock module, so when the delivery order is linked to a sale order, it's not the partner of the delivery order who is taken but the partner of the sale order!

The problem should be solved if we remove the _get_partner_to_invoice() function from the file stock.py in the sale_stock module.

**Comment by Yenthe666** [comment]
Hi @Wided1,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
