### ISSUE TITLE
spelling mistake in mail.message model

### ISSUE THREAD

**Issue by sandippatel27899** [odoo/odoo#55029]
Impacted versions:10

Steps to reproduce:None

Current behavior: testinh (spelling)

Expected behavior: testing (spelling)

Video/Screenshot link (optional):
![Screenshot from 2020-07-28 14-31-39](https://user-images.githubusercontent.com/38600866/88644999-40b45300-d0e1-11ea-99f1-c849196778f8.png)

**Comment by pedrobaeza** [comment]
Version 10 is already out of official support, but anyway, it's just a typo in the comments, so nothing critical nor malfunctioning, so closing. If you find in the future other typos, you can make a PR fixing them, but on master branch.
