### ISSUE TITLE
CUSTOM INVOICE TEMPLATE RENDER ERROR

### ISSUE THREAD

**Issue by chriswachira** [odoo/odoo#55075]
Impacted versions: **Odoo 12.0-20200728 (Community Edition)**

Steps to reproduce: Enable Developer Mode > Settings > Technical > Templates > Invoice: Send by email , then edit the template
![Screenshot_20200728_192432](https://user-images.githubusercontent.com/19710961/88694711-8f75e300-d109-11ea-9756-e5175b9f0d6b.png)

Current behavior: Fails to render email correctly. Placeholders still visible
![odoo-error](https://user-images.githubusercontent.com/19710961/88694649-7bca7c80-d109-11ea-8ce6-f57a19d5bfda.png)

Expected behavior: Render custom email correctly

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
The stored HTML is not correct, and that's why you get the error. Check code in HTML code editor, not rich text one.

Closing as no Odoo issue, but incorrect template.

**Comment by chriswachira** [comment]
Where do I get the HTML templates, kindly?

**Comment by pedrobaeza** [comment]
Enable developer mode, and click on the icon with the </> icon for seeing HTML code.

**Comment by chriswachira** [comment]
Thank you.
