### ISSUE TITLE
I cannot copy field information inside popup under Debug mode

### ISSUE THREAD

**Issue by tom10271** [odoo/odoo#55085]
Impacted versions: 12+ at least

Steps to reproduce:
![popup](https://user-images.githubusercontent.com/5089629/88749841-c0482d80-d186-11ea-94b6-7b2e57899a7a.gif)

Current behavior:
Popup disappeared once title mouse over out

Expected behavior:
Popup should have close button so that developer can copy useful information inside it

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
This has always been the case and was made that way on purpose. Imagine having to click on a close button for every hoover you make, you'd go insane.

**Comment by tom10271** [comment]
Is it possible for me to extend Odoo debug mode's JS?

This is what I want to add so that tooltip data will be dumped into console. Yeah close button sucks and the current version sucks so

```js
if ('jquery' in ($() || {})) {
    $('body.o_web_client[data-debug-mode=1]').on('DOMNodeInserted', '.tooltip', () => {
        const result = {};

        $('.tooltip-inner > .oe_tooltip_technical > li:not([data-item="selection"])').each(function () {
            const content = $(this).text().replace(/\s{2,}/g, '').split(/:(.+)/);

            result[content[0]] = content[1];
        });

        $('.tooltip-inner > .oe_tooltip_technical > li[data-item="selection"] > .oe_tooltip_technical > li').each(function () {
            if (!('Selections' in result)) {
                result.Selections = {};
            }

            const content = $(this).text().replace(/\s{2,}/g, ' ').split(/-(.+)/);

            result.Selections[content[0].replace(/\[|\]/g, '').trim()] = content[1].trim();
        });

        console.log($('.oe_tooltip_string').text().replace(/\s{2,}/g, ' ').trim()+"\n", result);
    });
}
```

**Comment by Yenthe666** [comment]
Sure you can inherit the JS widgets and extend them.
