### ISSUE TITLE
How can i remove More option containing dropdown of a menu from reporting manager login

### ISSUE THREAD

**Issue by saireddy57** [odoo/odoo#55087]
Impacted versions: odoo 8

Steps to reproduce:

Current behavior: More option displaying

Expected behavior:It should  not appear for the Reporting Manager login

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi,

Odoo 8 is no longer supported and the issue tracker is built for reporting bugs in Odoo, not for asking questions.
You can ask these kind of questions on the official help forums at help.odoo.com

Regards,
Yenthe
