### ISSUE TITLE
[13] sale coupon program: website_id have no effect

### ISSUE THREAD

**Issue by auyeung112002** [odoo/odoo#55121]
Impacted versions:
13

Steps to reproduce:
![image](https://user-images.githubusercontent.com/8391358/88797673-45a6fe80-d1d6-11ea-9bee-64f9446046f7.png)
![image](https://user-images.githubusercontent.com/8391358/88797754-6a02db00-d1d6-11ea-85e1-211185f0c596.png)

---
---
---

![image](https://user-images.githubusercontent.com/8391358/88798002-c5cd6400-d1d6-11ea-96ab-ca1600d78879.png)
![image](https://user-images.githubusercontent.com/8391358/88798239-2ceb1880-d1d7-11ea-8f62-b791071feda7.png)

Create a Promotion Program or Coupon Program, and select website
Go to the website which is not selected in the promotion/coupon program

Current behavior:
The discount can be applied no matter which website you are on.

Expected behavior:
The discount is only valid on the selected website in promotion/coupon program.

**Comment by sswapnesh** [comment]
Added fix https://github.com/odoo/odoo/pull/55175
