### ISSUE TITLE
Why product purchase price (or cost price) doesn't get distributed over variants rather than overriding them?

### ISSUE THREAD

**Issue by ramitalat** [odoo/odoo#5516]
In Odoo, if you created a product with many variants, the purchase price (or cost price) for those variants get updates together regardless how each variant differ between others in its price!
Odoo is dealing better with sales prices for variants (using extra prices,) while it didn't the same with purchase price (or cost price)!

So, is there any benefit from the current situation? or any fix for this shortage?

**Comment by Yenthe666** [comment]
Hi @ramitalat,

This has been improved in V9 and up and works better now.
As Odoo 8 is no longer supported I'm closing this question.

Regards,
Yenthe
