### ISSUE TITLE
See Own Leads gives permission on tasks

### ISSUE THREAD

**Issue by anajuaristi** [odoo/odoo#5518]
Hello:

I think See Own Leads group should only give permissions on sales objects but It's giving writing and creating permissions on tasks so I think it's a configuration error.

Thank you:
Ana

**Comment by Yenthe666** [comment]
Hi @anajuaristi,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by anajuaristi** [comment]
@Yenthe666 Thank you for solving SO FAST!!! Only 2 years and a half passed since I reported the error. 
I will try to text it on next version 20 or something. Mode ironic: on
:stuck_out_tongue_winking_eye:

**Comment by Yenthe666** [comment]
@anajuaristi thanks for the VERY positive feedback. I'm getting paid very well for closing all these bug reports and I love closing unsolved bug reports after 2 years an a half. Mode ironic: on
😜 


Note: Because I know some day somebody will flame me on this comment. No, I do not get paid and no I am not affiliated with Odoo. All my efforts are out of goodwill for the community and to improve Odoo.

**Comment by anajuaristi** [comment]
@Yenthe666 mode ironic: off
I know very well your impresive work on Odoo community, and I only want to thank your efforts to mantain the ecosystem.

My previous comment was only a joke you understood very well. 
Thank you!! :smile:

**Comment by Yenthe666** [comment]
I did, I couldn't resist to put my own ironic mode on too 😉
Again, sorry that I have to close so many of your bug reports though! If you ever make new ones just ping me, I'll make sure they get the attention they need.

**Comment by anajuaristi** [comment]
Thank you!!! :)
