### ISSUE TITLE
Displaying "TypeError: Cannot read property 'bind' of undefined" error.

### ISSUE THREAD

**Issue by rrakso** [odoo/odoo#55226]
Impacted versions:
- Odoo 13.0-20200730 (Community Edition)

Steps to reproduce:
- Click "_Settings -> General Settings -> Users -> Manage Users -> Create_"

Current behavior:
- **Cannot add new user**
I only have:
```javascript
Error: Traceback:
    at http://<HOST>/web/content/2028-46d7bfa/web.assets_common.js:4311:189
    at Function._.each._.forEach (http://<HOST>/web/content/2028-46d7bfa/web.assets_common.js:108:558)
    at http://<HOST>/web/content/2028-46d7bfa/web.assets_common.js:4311:106
```

Expected behavior:
- Displayed form to add new user

![image](https://user-images.githubusercontent.com/23143274/88948664-78163180-d292-11ea-8ecb-80233579c169.png)

**Comment by rrakso** [comment]
Ah @pedrobaeza at Odoo hosted by runbot everything seems to work :/ Can you give me some instructions how can I hunt down the bug? Should I "clean databse" or find if some (deleted or installed) modules breaked something?

**Comment by pedrobaeza** [comment]
I can't say exactly, as the error is very generic. Try updating source code and your modules in your DB, or with a fresh database. I have to close this because it's out of the scope of this issue tracker.

**Comment by rrakso** [comment]
WE (with @plejsq) DID IT!! :grin: 
---
The solution was to `Regenerate Assets Bundles` and then restart the Odoo!

--- 

To do it you need to have _developer mode_ on.
Go to **Settings** the scroll down to **Developer Tools** section and click `Activate the developer mode`. 

After that, you will see an small "bug" icon in top right corner - click it. You should see something like that:
![image](https://user-images.githubusercontent.com/23143274/90394437-f34d5500-e092-11ea-8ef4-bfa24fcc8eff.png)
select `Regenerate Assets Bundles` and after a while restart Odoo :smile_cat: 

Hope that this answer will help someone in future! (and nope - fresh install is not good idea :sweat_smile:)

###### Extra info
I discovered it by editing `/usr/lib/python3/dist-packages/odoo/addons/web_editor/static/src/js/wysiwyg/root.js` file. It came up that `instance[methodName]` was **`undefined`** when `methodName` variable was `saveCroppedImages` and then @plejsq found these issues:
- https://github.com/odoo/odoo/issues/46638
- https://github.com/odoo/odoo/issues/47623

**Comment by pedrobaeza** [comment]
Great that you solved it, and this can be used as reference for others with similar problems. Thanks for sharing.

**Comment by GoodERPJeff** [comment]
@rrakso You saved my life, it waste my 3 hours before get your solution.

**Comment by vixrodriguez** [comment]
@rrakso Thanks very much.
