### ISSUE TITLE
[13] Multi Website: website 1 link does not go website 2 with ?fw=2 if not logged in

### ISSUE THREAD

**Issue by martinsalcedoapps** [odoo/odoo#55232]
Impacted versions: 13.0

Steps to reproduce: Setup the multi website feature and create 2 websites (3 in total)

Current behavior: When create a link or menu entry and the url as '/?fw=2' or '/?fw=3'

Expected behavior: Open the website 2 home

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Why do you expect that `/fw=2` should open website 2? Put the absolute domain of website 2 in the menu URL.

**Comment by martinsalcedoapps** [comment]
What is the way to configure de WebSite Settings to setup the subdomain?
setting "subdomain" in the website domain field. or,
setting "subdomain.domain.com" 
It is necesary to configure in the DNS records for a on-premise instalation?

**Comment by pedrobaeza** [comment]
Each website has a domain to be filled (a field in that record), and yes, you have to configure DNS to point to your server.

Closing as this is not an issue, but deployment/general questions.
