### ISSUE TITLE
How to make a Multi-warehouse security model?

### ISSUE THREAD

**Issue by ramihelal** [odoo/odoo#5524]
When I deal with multi-warehouse company, I face a problem to separate each warehouse-moves privilege from the others.
I.e. having 5 warehouses (J, K, L, M, N), warehouse-man for warehouse (M) should only deliver/receive products to/from his warehouse only, and can't make any move in other warehouses.
And so for each other warehouses and warehouse-men.
Is this model of security applicable in Odoo?

**Comment by Yenthe666** [comment]
Hi @ramihelal,

Please do ask questions on the official help forum (odoo.com/help). The Github tracker is only used for bug reports, not for asking questions.
To answer your question: you can go as far as you like with security rights in Odoo.


Regards,
Yenthe
