### ISSUE TITLE
Passed value when editing one2many field is not correct

### ISSUE THREAD

**Issue by RandyRR** [odoo/odoo#5526]
How to recreate issue:
1. Create 2 class ( Parent - Children), parent has one2many field that connect to child.
2. Make on_change event on parent one2many field with it's own one2many field as parameter.
3. Create a new record of parent and some new line in one2many field.
4. Edit the one2many field.

Issue:
In onchange function the one2many parameter will return something like [(6,0,[xx,xy])], where xx / xy is child's ids. Changed value doesn't passed to onchange function in parent. I need to do something based on child value.

**Comment by kurkop** [comment]
Can you check your issue in the light of #6927 and maybe confirm there? thanks.

**Comment by Yenthe666** [comment]
Hi @RandyRR,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
