### ISSUE TITLE
Changing Product Type after a Sale has occurred breaks accounting journal entries

### ISSUE THREAD

**Issue by andrewdhastings** [odoo/odoo#55289]
Impacted versions:
Only tested v13

Steps to reproduce:
1) Create a stockable product
2) Add to SO, Deliver & Invoice
3) Zero out any qty on hand
4) Change to a consumable product
5) Add to SO, Deliver & Invoice

Current behavior:
The journal entry will follow the pattern of the original product type. It will use interim/cost of goods sold, even after changing to a consumable.

Expected behavior:
Journal entries should follow the module of the product type, regardless of what it was before. If it starts as a stockable then goes to consumable, then no interim/cogs entries should be made.

Video/Screenshot link (optional):

![product type](https://user-images.githubusercontent.com/32532163/89110146-fc88c180-d404-11ea-88ff-5fb6b15e1876.PNG)

I think this behavior either needs fixed as bug, or product types should be Locked after they are set (or after the first SO/PO) so you can't change them and create these errors.

**Comment by andrewdhastings** [comment]
Should add that the image above was a product that started as a consumable, had some sales, then I changed it to a stockable product. You can see the journals created.

**Comment by andrewdhastings** [comment]
I just tested this on v11, and this issue is not present. So this bug was introduced between 11 and 13.

**Comment by andrewdhastings** [comment]
@Yenthe666 This could be tied to, or corrected at the same time as the other inventory adjustment errors when changing from stackable to consumable. https://github.com/odoo/odoo/issues/43717

**Comment by andrewdhastings** [comment]
I actually think this might be a different issue. I have been doing more testing as a customer's Interim accounts are all out of wack. It looks like Consumables are not handled correctly in v13 CE ONLY. EE seems to work fine, but all consumables in CE v13 use interim accounts and they shouldn't. Not sure why it would be different between the two versions?

**Comment by ray-odoo** [comment]
@andrewdhastings can you share the Use Case for selling consumables?  Consumables are used most commonly as non-inventory items that are expensed at the time of purchase (Janitorial Supplies, Office Supplies, etc) or for smaller products used to make other larger products.

**Comment by andrewdhastings** [comment]
@ray-odoo sorry, I totally missed your question. We actually have customer do this all the time. For example, our customers often need to include an item with another product and they need it to show up on the delivery order so shipping doesn't forget. However, they don't care to track the inventory for that item. 

For example, an on demand printed instruction manual, or a USB thumb drive with hardware drivers, or a set of bolts. It happens all the time.

**Comment by andrewdhastings** [comment]
We found a different solution and this version is out of support. Closing the issue
