### ISSUE TITLE
Wrong foreach handling in kanban view

### ISSUE THREAD

**Issue by nurefexc** [odoo/odoo#55367]
Impacted versions:13

Steps to reproduce:
1. step: Created table and add many2many relation:
```python
    server_ids = fields.Many2many("oerp.odooris.server", "oerp_odooris_install_server_rel", "install_id", "server_id",
                                                        string="Server", readonly=False, ondelete='restrict', tracking=True, copy=False)
```
2. step: Created this kanban code:
```xml
                                    <span class="oe_kanban_list_many2many">
                                         <field name="server_ids"/>
                                    </span>
                                     <t t-foreach="record.server_ids" t-as="server">
                                         <span t-esc="server" class="badge badge-info"/>
                                     </t>
```
Current behavior:

1. case: Automatic created list, but it's not good for us because we want custom code. 
2. case: With the foreach we've got variables in the namespace and not the values of the many2many relation.

![Screenshot_20200804_091939](https://user-images.githubusercontent.com/65736397/89265422-bdd94e00-d634-11ea-9763-242a4d9e0da3.png)

Expected behavior: The foreach should go through the values of the many2many relation.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a development question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

As a short tip. JS Qweb views are not the same as other QWeb, and you should use proper variables, like `server.value`.

Closing this by the reason above.
