### ISSUE TITLE
[13.0] Cost of Revenue not properly deducted in P&L's Net Profit Figure in US GAAP reports

### ISSUE THREAD

**Issue by abdullah-netlinks** [odoo/odoo#55361]
Impacted versions: 13.0

Steps to reproduce:
1. In a blank database (with generic accounting installed: app name: l10n_generic_coa), pass the following two journal entries:

1.1. A sales of $100,000, with a cost of revenue of $40,000.
<img width="1152" alt="Screen Shot 2020-08-04 at 11 35 22 AM" src="https://user-images.githubusercontent.com/19147568/89263485-97bca980-d646-11ea-8603-e6aa779e48c7.png">
1.2. An entry to record misc. operating expenses for the month: of $10,000.
<img width="1152" alt="Screen Shot 2020-08-04 at 11 35 43 AM" src="https://user-images.githubusercontent.com/19147568/89263518-a3a86b80-d646-11ea-9e6a-8475b77527e1.png">

2. Open the 'Profit and Loss' report, and see the calculations for the Net Profit Figure:
<img width="879" alt="Screen Shot 2020-08-04 at 11 36 39 AM" src="https://user-images.githubusercontent.com/19147568/89263585-c470c100-d646-11ea-9db6-4a631e41b648.png">

Current behavior:
A 'Net Profit' of $90,000 is shown (which is the total income of $100,000 minus the expenses of $10,000.

Expected behavior:
A Net Profit of $50,000 should be shown. That is: a $100,000 minus the $40,000 of cost of revenue minus a $10,000 of expenses.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Which chart of accounts are you using?

**Comment by abdullah-netlinks** [comment]
US chart of account (l10n_generic_coa)

**Comment by pedrobaeza** [comment]
l10n_generic_coa is not US chart of accounts, but a generic one. You must use `l10n_us`.

**Comment by abdullah-netlinks** [comment]
@pedrobaeza apologies for the confusion - I thought they were both pretty much the same. 

I have replicated the steps in a new databases with `l10n_us` and still got the same results shared in the issue. 

Would someone look into this? Thanks.

**Comment by pedrobaeza** [comment]
As this is something enterprise (reports are not in CE edition), you should report the problem through odoo.com/help with your enterprise contract for being attended by the support team.

**Comment by abdullah-netlinks** [comment]
Noted and thank you.
