### ISSUE TITLE
BANK RECONCILIATION FOR RECEIPT AND PAYMENT ENTRIES THROUGH JOURNAL ENTRY

### ISSUE THREAD

**Issue by jackson-rpdcool** [odoo/odoo#55389]
Hope you are doing well.

I need clarification concerning Odoo 13 Bank reconciliation entries. 

We are doing some of the payment/receipt entries through Journal Entries (under accounting – accounting – Journal Entries) (PIC > Journal Entry) Eg:

04.08.2020 | Telephone charges | 5000.00 dr |  
-- | -- | -- | --
04.08.2020 | Bank Account |   | 5000.00 cr

Now, this being a journal entry, it is not reflecting in the bank statement for reconciliation. We have searched on the internet and found an option that we have to do a manual reconciliation. So we did manual reconciliation (PIC > Manual Operation option for the payments and receipts not reflecting in cust ven & Misc Match accounts). However, when we do manual reconciliation it again creates the same entry (PIC > Journal Entry created by System due to Manual Reconciliation). Hence the General ledger shows this entry two times. 

As we don’t receive bills for all the payment/receipt, how we can make payments/receipt entries that don't have bills. Is there no option making receipts and payments through journal entries and get it reflected on the bank statement for reconciliation. If NO, then how we can pass those entrys. 

Your help in this regard is highly appreciated. 

![Journal Entry created by System due to Manual Reconciliation](https://user-images.githubusercontent.com/67504863/89290608-2d1d6500-d66a-11ea-9997-79970fb6dbfc.PNG)
![Journal Entry](https://user-images.githubusercontent.com/67504863/89290612-2e4e9200-d66a-11ea-8d82-e7578ad6819f.PNG)
![Manual Operation option for the payments and receipts not refelecting in cust ven   Misc Match accounts](https://user-images.githubusercontent.com/67504863/89290615-2ee72880-d66a-11ea-80e3-4059cc68a86a.PNG)

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
