### ISSUE TITLE
one2many on change update performance issue

### ISSUE THREAD

**Issue by anilbhatt** [odoo/odoo#5539]
Hi there,

I want to update only 1 record of one2many field on change of its parent field's sibling. It works correctly but if i have 100 items in my one2many field and i want to update just one row of one2many field on change then there is quite slowness. 

Is there any workaround it?

**Comment by Yenthe666** [comment]
Hi @anilbhatt,

Not by default, this is how the framework works by default. You could write custom code to only update that record though.

Regards,
Yenthe
