### ISSUE TITLE
Stripe SCA

### ISSUE THREAD

**Issue by YoannyD** [odoo/odoo#55427]
Impacted versions: 13.0

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

I need a clarification, the functionality of Stripe SCA, is implemented in Odoo 13, because in v12 and v11 a new module was created but not in v13. If so, if they told me how to see it, I always get the same thing from introducing the card.

**Comment by Yenthe666** [comment]
Well it originally comes back from https://github.com/odoo/odoo/pull/38885 which was made by @dbo-odoo.
I guess in V13 it got merged into `payment_stripe` instead of separation because that was the first stable branch where it could be introduced before the release.
Maybe @dbo-odoo can confirm.

**Comment by pedrobaeza** [comment]
Yes, I confirm that SCA was directly integrated in `payment_stripe`. In previous versions, a glue module was needed due to stability policy. Closing then as answered, and not being an issue per se.
