### ISSUE TITLE
[13.0] got permission error on sms template

### ISSUE THREAD

**Issue by MojtabaAp** [odoo/odoo#55432]
Hi
When i want add sms template for sale order i got this error:
![Screenshot from 2020-08-05 09-42-56](https://user-images.githubusercontent.com/36371067/89374308-4244d300-d700-11ea-98e9-027bfd278d8f.png)

**Comment by sswapnesh** [comment]
IMO, Its should be Restricted to Admin only (Like Mail templates)
@tde-banana-odoo  What do you say ?

**Comment by tde-banana-odoo** [comment]
We added some limited rights to some manager groups, so that they can edit templates linked to their app. We could do the same for sales, makes sense.

We do not give extended rights to all users to avoid potential abuse, but limited rights should be ok. I create a feedback.

**Comment by tde-banana-odoo** [comment]
In case: task 2319841

**Comment by sswapnesh** [comment]
But how do we fix the Issue like this ? (Adding access Rights for all major Apps on stable version ?)

**Comment by tde-banana-odoo** [comment]
We will probably not do it in stable. Anyway this can be done using custom acls if required in stable.

**Comment by tde-banana-odoo** [comment]
Done for 14.1 at https://github.com/odoo/odoo/commit/61ed99d56e3d7ad37079b44966b8fc0ddc4be7c2 . We did not target 14 as time was short and this can easily be solved with custom ACLs.

Thanks for reporting !
