### ISSUE TITLE
attrs (readonly) not working on group tag

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#5547]
In documentation it says this:
"
attrs: Permits to define attributes of a field depends on other fields of the same window. (It can be use on page, group, button and notebook tag also)
"
https://doc.odoo.com/6.0/developer/2_6_views_events/views/design_element/

Did something change on Odoo 8? Or am I doing something wrong here? (look at example below):

This works (it becomes readonly if state is 'done'):

```xml
<field name="field1" attrs="{'readonly': [('state', '=', 'done')]}"/>
```
This does not work (field never becomes readonly):
```xml
<group attrs="{'readonly': [('state', '=', 'done')]}">
    <field name="field1"/>
</group>
```

**Update**
Also I found other people experienced same problem. So I guess it was never fixed. 
https://www.odoo.com/forum/help-1/question/readonly-in-view-not-working-50354

it seems such functionality was used in project view on `page` tag, but it actually never worked (but now it is removed from code)

**Comment by pji-odoo** [comment]
to make field readonly use attrs in <field> not in <group>

**Comment by oerp-odoo** [comment]
@pji-odoo why is there a difference? Also using `=` works on `field`, but not on `group` tag. And actually on my code I tried both `in` and `not in`. None of it work. Also there should be no difference in operator, because it does not make sense.

**Comment by pji-odoo** [comment]
oh!! it's not about operator,  i mean put attrs inside `<field>` tag.

**Comment by oerp-odoo** [comment]
@pji-odoo did you read my question?.. I know i can use in `field` tag I even showed example that in `field` tag it works, but it is not working if you use it inside `group` tag, even though documentation claims it should work not only on `field` tag, but also on `group`, `page`, `button` and `notebook` tags also.

**Comment by beledouxdenis** [comment]
Hello Andrius, 

The fact that attrs could be use on group was true for 6.0. This is no longer the case in 7.0 or 8.0.

You could simply try readonly="1" on the group tag and you will see it is not working either.

In 7.0 & 8.0, you are expected to set these attributes on the field itself, no longer on the group surrounding the groups.

Regards,

**Comment by Robx64** [comment]
Perfectly works, that's what I was looking for.
<field name="field1" attrs="{'readonly': [('state', '=', 'done')]}"/>
Thanks a lot

**Comment by vcloud9ray** [comment]
Looks like this is working at v10 now (attrs on GROUP tags)
