### ISSUE TITLE
Odoo 8 : Footer not display. Header only display in first (not in all) .pdf page.

### ISSUE THREAD

**Issue by trannhuvan** [odoo/odoo#5548]
Hi all,

I want to edit header and footer of sale order report (quotation, order, invoice...). That worked fine in html, but with report there are some problem.

1. Header is only displayed once, in first page. The others are empty

2. Footer is not displayed in any page.

Environment information

+ Odoo 8 in Ubuntu 12.01 32bit

+ Using wkhtmltox-0.12.1_linux-wheezy-i386.deb (with patched qt)

+ I set parameters, as report.url, base.url.freeze, ..so on

Here is my code to modify header and footer

    
    <template id="report_quotation_header" inherit_id="report.external_layout_header">
           <xpath expr="//div[@class='header']" position="replace">
        <div class="header">
            <t t-set="data_report_margin_top" t-value="12"/>
            <t t-set="data_report_header_spacing" t-value="9"/>
            <t t-set="data_report_dpi" t-value="110"/>
            <div class="row">
                        <div class="col-xs-3">
                            <img src="/sale_extension/static/image/logo/header.jpg" style="max-height: 90px;"/>
                        </div>
                </div>
        </div>
        </xpath>
    </template> 
    
    <template id="report_quotation_footer" inherit_id="report.external_layout_footer">
           <xpath expr="//div[@class='footer']" position="replace">
        <div class="footer">
            <div class="text-center">
                        <t t-if="'partner_id' in company"><span t-field="company.partner_id"/></t> - 
                    <t t-if="'company_registry' in company"><span t-field="company.company_registry"/></t> <br/>
                <t t-if="'street' in company"><span t-field="company.street"/>, </t>
                    <t t-if="'city' in company"><span t-field="company.city"/></t>
                    <t t-if="'zip' in company"><span t-field="company.zip"/></t>
                    <t t-if="'phone' in company">P: <span t-field="company.phone"/></t>
                    <t t-if="'fax' in company">F: <span t-field="company.fax"/></t>
                </div>
        </div>
        </xpath>
    </template> 

Thanks so much

**Comment by felixlim10** [comment]
I'm facing exactly the same problem as yours. Whether the header or reports are formatted or not, the problem still persist.

Problem still persist even I tried to start off a new database and left everything in default.

Running on Windows 8.1.

**Comment by trannhuvan** [comment]
Hi @felixlim10 

The reason is the bug of wkhtmltopdf.
In my case, I used wkhtmltopdf version 0.12.0 and the problem was solved. But with another OS, I dont know which version is suitable for it.

**Comment by felixlim10** [comment]
Hi there,

I have tried versions wkhtmltopdf versions 0.12.0 up to 0.12.2 on Windows 8.1. None of it fixes the footer problem. In addition, the header only appears on the first page.

**Comment by trannhuvan** [comment]
In the content of my report, I try using CSS attribute "break-page-before" to break page. It seem better, because It worked cool if the report have under three pages. 

But my report have four pages. So, my problem now is : one page only have header, another only have footer.

I'm using Ubuntu 12.04 with wkhtmltopdf 0.12.0. I don't know your problem can be fixed, or not. But if I found the solution, I'll update you soon.

**Comment by felixlim10** [comment]
Thanks for your suggestion. I'll give it a try later on.

You mentioned the HTML works fine. Do you mean the header is showing on all pages?
I'm on Chrome and tried on IE. The header appears only on first page, but the footer shows up on the last page. (In PDF, it doesn't even appear)

**Comment by trannhuvan** [comment]
In HTML, you can see only one header in top page and only one footer in bottom page, and it dont need wkhtmltopdf

But I mean the problem which is missing header and footer is in PDF. And my suggestion is for that, for printing with PDF.

**Comment by felixlim10** [comment]
Hi,

Do you mind to share how to set Odoo to look for wkhtmltopdf?

I've got Debian up and running. I get can't find wkhtmltopdf despite it is already installed (0.12.2.1).
As found in other guides, copying to /usr/bin - i've done that. but still doesn't work.

Linux: Debian Wheezy
Odoo: Installed via their Debian Nightly Build Repository

**Comment by felixlim10** [comment]
Hi.
I solved my problem by setting up a Debian Wheezy box and ditch the idea of running the Odoo from my laptop. It works well using 0.12.1. For 0.12.2.1, it doesn't work.

**Comment by trannhuvan** [comment]
Yes. wkhtmltopdf version 0.12.2 has a bug. You should use version 0.12.0 to 0.12.1

Thank you so much.

**Comment by SVQTQ** [comment]
Any luck on printing reports with more than 4 pages with multiple headers and footers?

**Comment by trannhuvan** [comment]
@SVQTQ 
Me too. That is the bug and I can't fix. If the report has 4 pages or more, it also has maximum 3 header/footer.

**Comment by beledouxdenis** [comment]
Closed with 3c61ee5c68e3796bb29d2521123f2a867c9cc157.

**Comment by tejastank** [comment]
Getting same issue with most latest odoo 8.0 revision. wkhtmltopdf version 0.12.1

**Comment by tejastank** [comment]
Also facing strange issue as I tested, if I remove header, footer is visible now, but when again adding header back, footer invisible. 

Odoo had wired reporting feature. West of time for odoo to fix minor header or footer and its hold hell of wkhtmltopdf version issue. Seems like platform depend only solution.

**Comment by tejastank** [comment]
Official odoo commit seems hard-code fix, even not proper solution.

https://github.com/odoo/odoo/commit/3c61ee5c68e3796bb29d2521123f2a867c9cc157

Its not working, single invoice report with header but no footer, if header disable footer show.

Looking for better fix.

**Comment by Gyuri77** [comment]
Hi all!
I have the same error on win-odoo8, no header bad footer.
wkhtml2pdf 0.12.1.2 with patched qt

I found a bad system variable, that caused it for me. The solution is:
set   Settings - Parameters- System paraters --- report.url      for correct value.

i changed it from "http://0.0.0.0:8069/" to "http://127.0.0.1:8069/" and i got header, correct footer and page numbers.
