### ISSUE TITLE
[13.0] stock: stock.quant corruption in concurrent transactions

### ISSUE THREAD

**Issue by moylop260** [odoo/odoo#55494]
# Impacted versions:
13.0 (maybe 12.0, 11.0,...)

# Steps to reproduce
1. Reproduce concurrency in quants (more than one transaction at the same time)
I have created the following code using quant and sequence concurrency to check both incremental cases.

<details>
  <summary>Quant and sequence concurrency code</summary>
  
  ```python
import logging
import threading
from contextlib import closing

import odoo
from odoo.addons.base.models.ir_sequence import _update_nogap
from psycopg2 import OperationalError

_logger = logging.getLogger(__name__)

THREADS = 5


def update_quant(thread_name, only_read=False):
    registry = odoo.modules.registry.Registry.new(self.env.cr.dbname)
    with odoo.api.Environment.manage(), closing(registry.cursor()) as new_cr, odoo.tools.mute_logger('odoo.sql_db'):
        # Create a new environment and database cursor
        new_env = odoo.api.Environment(new_cr, self.env.uid, self.env.context)
        quant = new_env['stock.quant'].search([], limit=1)
        old_value = quant.quantity
        if only_read:
            return old_value
        for i in range(10):  # concurrency attempts
            try:
                with new_cr.savepoint():
                    quant._update_available_quantity(product_id=quant.product_id, location_id=quant.location_id, quantity=1)
                    break
            except OperationalError as pgoe:
                if pgoe.pgcode == '40001':
                    # _logger.info("%s The field was changed after read (repeatable readable issue)", thread_name)
                    return False
        quant.flush()
        _logger.info("%s Quant %s  %d -> %d", thread_name, quant, old_value, quant.quantity)
        new_cr.commit()
        return True


def update_seq(thread_name, only_read=False):
    registry = odoo.modules.registry.Registry.new(self.env.cr.dbname)
    with odoo.api.Environment.manage(), closing(registry.cursor()) as new_cr, odoo.tools.mute_logger('odoo.sql_db'):
        # Create a new environment and database cursor
        new_env = odoo.api.Environment(new_cr, self.env.uid, self.env.context)
        seq = new_env['ir.sequence'].search([], limit=1)
        old_value = seq.number_next
        if only_read:
            return old_value
        for i in range(10):  # concurrency attempts
            try:
                with new_cr.savepoint():
                    _update_nogap(seq, 1)
                    break
            except OperationalError as pgoe:
                if pgoe.pgcode == '40001':
                    # _logger.info("%s The field was changed after read (repeatable readable issue)", thread_name)
                    return False
        _logger.info("%s Seq %s %d -> %d", thread_name, seq, old_value, seq.number_next)
        new_cr.commit()
        return True


def process():
    thread_name = threading.current_thread().name
    while True:
        if update_seq(thread_name):
            break
    while True:
        if update_quant(thread_name):
            break


old_seq = update_seq('first value', only_read=True)
old_quant = update_quant('first value', only_read=True)

threads = []
for i in range(THREADS):
    t = threading.Thread(target=process, name="Thread %d" % (i+1))
    threads.append(t)
    t.start()

[t.join() for t in threads]

new_seq = update_seq('final value', only_read=True)
new_quant = update_quant('final value', only_read=True)
_logger.info("Sequence. Number of threads %d. Initial value %d Final seq: %d == %d?", THREADS, old_seq, new_seq, old_seq + THREADS)
_logger.info("Quants. Number of threads %d. Initial value %d Final seq: %d == %d?", THREADS, old_quant, new_quant, old_quant + THREADS)

  ```
</details>

2. Store the code above and run it using `odoo-bin shell`

 - `~/odoo-13.0/odoo-bin shell -d db --log-level=warn < ~/concurrency_quant_seq.py`

3. Check the output:

<details>
  <summary>Quant and sequence concurrency code</summary>
  
  ```txt
Thread 2 Seq ir.sequence(1,) 188 -> 189
Thread 3 Seq ir.sequence(1,) 189 -> 190
Thread 1 Seq ir.sequence(1,) 190 -> 191
Thread 4 Seq ir.sequence(1,) 191 -> 192
Thread 5 Seq ir.sequence(1,) 192 -> 193

Thread 2 Quant stock.quant(1,)  119 -> 120
Thread 3 Quant stock.quant(1,)  119 -> 119
Thread 4 Quant stock.quant(1,)  120 -> 121
Thread 1 Quant stock.quant(1,)  121 -> 122
Thread 5 Quant stock.quant(1,)  121 -> 121
Sequence. Number of threads 5. Initial value 188 Final seq: 193 == 193?
Quants. Number of threads 5. Initial value 119 Final seq: 122 == 124?
  ```
</details>

# Current behavior:
Notice the last 2 messages:

 - `Sequence. Number of threads 5. Initial value 188 Final seq: 193 == 193?`
   - It means ir.sequence started in 188 and ended in 193 after 5 concurrent users. It is fine! 🟢 

 - `Quants. Number of threads 5. Initial value 119 Final seq: 122 == 124?`
   - It means stock.quant started in 119 and ended in 122 after 5 concurrent users. It is wrong it should be 124 🔴 

There is an logging output storing the same value without plus one:
 - `Thread 5 Quant stock.quant(1,)  121 -> 121`

Increasing the number of threads the gap is bigger.

# Expected behavior:
No corruption of the incremental number of quants similar to sequence no gap.

sequence no gap code:
 - https://github.com/odoo/odoo/blob/3fcadce3de4a1cfd067b155dd746854065f4b452/odoo/addons/base/models/ir_sequence.py#L51-L55

Quant code:
 - https://github.com/odoo/odoo/blob/3fcadce3de4a1cfd067b155dd746854065f4b452/addons/stock/models/stock_quant.py#L413-L417

Note: I have ideas about how to fix it, but the first step is to know that there is an issue.
In order to avoid closing it if the solution is not enough good like: 
 - https://github.com/odoo/odoo/pull/32160

UPDATE: Stock.quant is doing UPDATE in another record different. Checking...

**Comment by Belal-Abdullah** [comment]
@moylop260 Hi, I faced the same issue with Odoo 14 EE, Stock quant got corrupted under heavy transactions, in our environment we issue more than 100K SML every day and we discovered that the stock quants for some products got corrupted .. can we share our experiences to solve this issue?

**Comment by moylop260** [comment]
Could you describe a little more the "corrupt" case, please?

We had a lot of time waiting for merging too many records but it could be done in a vacuum process 

But we don't raised number increment wrong anymore

What is your issue here?
