### ISSUE TITLE
 UnicodeWarning: Unicode unequal comparison failed to convert both arguments to Unicode

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#5550]
I started getting this warning.
Full warning looks like this:

`
/home/user/odoo/odoo/openerp/models.py:458: UnicodeWarning: Unicode unequal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if cols[k][key] != vals[key]:
`
I checked what kind of label was throwing it and I got that it is throwing because of such field label name:
`Diameter (Ø)`

Whole field definition looks like this:

`diameter = fields.Float('Diameter (Ø)', digits=(12,1))`

I tried to make it read as unicode, so I changed label to:

`diameter = fields.Float(u'Diameter (Ø)', digits=(12,1))`

But it didn't help.

Is there a way to use unicode labels and avoid those unicode warnings?

**Comment by oerp-odoo** [comment]
Actually u'Diameter (Ø)' works. I didn't notice there was another field with same label that got such warning.

**Comment by anabeladamas** [comment]
hi, 
How did you do the debug ? How did you found the field that was causing the warning? 

Thanks

**Comment by oerp-odoo** [comment]
@anabeladamas I debugged this part ` /home/user/odoo/odoo/openerp/models.py:458`. Printed what kind of output it gives, when it fails to convert to unicode. Then I noticed which field was causing it.

**Comment by anabeladamas** [comment]
Thanks @oerp-odoo, I saw in the log file(info) what was the module that was loading before the error , and then I looked for the special caraters without the u"". 
My error was in the __openerp__.py file .... 
Thanks for your answer.
