### ISSUE TITLE
Wrong breadcrumb for the directories's structure

### ISSUE THREAD

**Issue by ghost** [odoo/odoo#5554]
Hello, 

I've some problems with the breadcrumb in the view "Directories's Structure".
### What is my problem

When I go to "Directories's Structure" (Knowledge => Configuration => Document Management => Directories's Structure), I see all directories with the breadcrumb "Directories's Structure".

![screen shot 2015-03-03 at 13 06 30](https://cloud.githubusercontent.com/assets/8790593/6462166/090056ec-c1a7-11e4-94f8-d9c5d20aa1ee.png)

Now, I click on one of them. 
If you see the breadcrumb, you'll see "Directories'... / Directory".

![screen shot 2015-03-03 at 13 06 59](https://cloud.githubusercontent.com/assets/8790593/6462182/42f30cd2-c1a7-11e4-8f82-679174874750.png)

According to me and the logic of Odoo, we should see "Directory / DIRECTORY_NAME".

Thanks for all,
Sylvain Van Hoof for Eezee-it

**Comment by Yenthe666** [comment]
Hi @ghost,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
