### ISSUE TITLE
Odoo can't able to handle the HEAD request from controller

### ISSUE THREAD

**Issue by dbu-odoo** [odoo/odoo#55617]
Impacted versions: 13.0 (or below versions may be)

Steps to reproduce:
1) I created the json route controller, I am not defining any methods like POST, GET
2) When some external system is calling my json route controller with HEAD request then odoo can not able to handle the HEAD request and gives back the 404 response to the external system

Current behavior:
1) Odoo giving the 404 response because odoo cant able to handle HEAD request in controller

Expected behavior:
1) Odoo should be able the HEAD request in controller

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
You need to put exactly what you are trying to do, but I would bet that you are not following standard JSON-RPC, and thus, it's not compatible and neither want to be with other protocols.

@mart-e should we close this according other issue you closed recently with the same reasoning?

**Comment by dbu-odoo** [comment]
I created one controller with the type="json" in "controllers > main.py" file
I am integrating some other softeware with odoo, that other software need to call our controller for verification with "HEAD" request.
But can not able to handle the "HEAD" request and so thats why odoo can not able to find the controller and gives the "404" as a response to that other software.

**Comment by pedrobaeza** [comment]
But as said, that `HEAD` request is JSON-RPC standard or other over HTTP protocol?

P.S.: You are hijacking the GitHub naming style of Odoo employees, which can confuse others and I don't see that a good practice.

**Comment by dbu-odoo** [comment]
I tried with HTTP and JSON both request, but not able to find the solution

**Comment by dbu-odoo** [comment]
There are many type of request methods there but odoo is only capable to handle the "GET" and "POST" method
https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html

**Comment by pedrobaeza** [comment]
But you are still insisting in going to HTTP, but this is not HTTP, it's JSON-RPC over HTTP. I have now clear that you are going out of standard, so closing the issue. If you prove that HEAD is supported in JSON-RPC, then we can reopen this.

**Comment by mart-e** [comment]
> should we close this according other issue you closed recently with the same reasoning?

Looks a lot like the other one indeed.

The point is that the standard `type="json"` controllers of Odoo work with JSON-RPC, it you are making calls from other software, it must "speak" rpc. If you want to implement a different api, you will need to customise the code of Odoo.
Note that when we interact with external services (e.g. payment providers), we use `type="http"`.

Anyway, please keep github only for bugs reporting on the standard Odoo. Not for questions or development help.
For help, you may try the [mailing lists](https://www.odoo.com/page/odoo-community), the [forum](https://www.odoo.com/forum/help-1) or the [support page](https://www.odoo.com/help) (for paying users).

Regards

> P.S.: You are hijacking the GitHub naming style of Odoo employees, which can confuse others and I don't see that a good practice.

@dbu-odoo as you are no longer an odoo employee, it would indeed be more clear if you could rename your github user too, it's a bit confusing.
