### ISSUE TITLE
Website double encoding parameters in language other than the default website language

### ISSUE THREAD

**Issue by MathAndrews** [odoo/odoo#55621]
**Impacted versions:** 
Odoo 11

**Steps to reproduce:**
- Create a new odoo server with website app enable
- install several language, add the language to the site web
- create a module with a simple controller
`# -*- coding: utf-8 -*-

from odoo import api, http

import logging
_logger = logging.getLogger(__name__)

class Partner(http.Controller):

    @http.route('/test/<string:value>', auth='public', website=True)
    def test_value(self, value):
        _logger.info('Test parameter: Value')
        _logger.info(value)

        return value`

- Acces to this url in a language that is not the default one with value containing a "special" character like 'ä'

**Current behavior:**

When you access to the page in the default language: /test/ä:
=> the log print: ä
=> the webpage display: ä

When you access to the page with a other language than the default: /fr_FR/test/ä
=> the log print: �
=> the webpage display: �

**Expected behavior:**
The log and webpage must display the same value if you are on the website in the every language available

**Issue**
In the file [http_routing - models - ir_http](https://github.com/odoo/odoo/blob/cfde4bc8b7f0f7edcae6f33ed2ce6569fcc46ca0/addons/http_routing/models/ir_http.py)

1. in the `_dispatch` method, it retreive the path using `request.httprequest.path` [line 358](https://github.com/odoo/odoo/blob/cfde4bc8b7f0f7edcae6f33ed2ce6569fcc46ca0/addons/http_routing/models/ir_http.py#L358) which is encode by the werkzeug BaseRequest object

2. The in the case of browsing in an other language than the default one, it go in the `reroute` method where it set back the path without the language: `request.httprequest.environ['PATH_INFO'] = path` [line 412](https://github.com/odoo/odoo/blob/cfde4bc8b7f0f7edcae6f33ed2ce6569fcc46ca0/addons/http_routing/models/ir_http.py#L412)

3. Then it go back to the `_dispatch` method where it retrieve again the path, like in step 1. and the path is encode a second time by the werkzeug BaseRequest object

So when setting back the "PATH_INFO" it should decode back the path to the orignal encoding: 
`request.httprequest.environ['PATH_INFO'] = path.encode(request.httprequest.charset).decode('latin1', 'replace')`

Best regards

M.

**Comment by pedrobaeza** [comment]
Outside of any involved code that can be refined, you mustn't use strings encoded on the URL path, as that's something that is not advised in any good practice, SEO or web guide. Anyway, you can propose your patch to Odoo as a PR to see if it's admitted.

As this is not something that is happening in standard Odoo controllers, I close.

**Comment by MathAndrews** [comment]
Hi,

The issue is that there is already a decoding/encoding happening in the werzeug's code, and it happened two time when browsing the website in a language other than the default language

I might not be clear enough.

When you get the path value:  [`path = request.httprequest.path.split('/')`](https://github.com/odoo/odoo/blob/cfde4bc8b7f0f7edcae6f33ed2ce6569fcc46ca0/addons/http_routing/models/ir_http.py#L358) you call this method in the [werkzeug BaseRequest class](https://github.com/pallets/werkzeug/blob/fef09eb909d1dd2afddb339ff1ceb2ca45df40f8/src/werkzeug/wrappers/base_request.py#L534) :


`def path(self):
        """Requested path. This works a bit like the regular path
        info in the WSGI environment but will always include a leading slash,
        even if the URL root is accessed.
        """
        raw_path = _wsgi_decoding_dance(
            self.environ.get("PATH_INFO") or "", self.charset, self.encoding_errors
        )
        return "/" + raw_path.lstrip("/")`

which is using the [method _wsgi_decoding_dance](https://github.com/pallets/werkzeug/blob/fef09eb909d1dd2afddb339ff1ceb2ca45df40f8/src/werkzeug/_internal.py#L107) : 
 `def _wsgi_decoding_dance(s, charset="utf-8", errors="replace"):
    return s.encode("latin1").decode(charset, errors)`

So as you can see there is encoding apply on URL path.

Now, let's look a the values during the process:
1. The first time you enter `_dispatch` the value of `request.httprequest.environ['PATH_INFO']` is `/fr_FR/test/Ã¤`,
2. Then when you get the path (via `request.httprequest.path`), where it apply `encode("latin1").decode("utf-8", "replace")` on `request.httprequest.environ['PATH_INFO']` and you get the value `/fr_FR/test/ä`,
3. Then, as we have a language set in the URL, you go in the method [`reroute`](https://github.com/odoo/odoo/blob/cfde4bc8b7f0f7edcae6f33ed2ce6569fcc46ca0/addons/http_routing/models/ir_http.py#L404) where you set `request.httprequest.environ['PATH_INFO']` with a the path; without the language; already encoded/decoded (`/test/ä`),
4. Then you go back in  the method `_dispatch` where the value of  `request.httprequest.environ['PATH_INFO']` is now `/test/ä`
5. You get the path (via `request.httprequest.path`) where it apply `encode("latin1").decode("utf-8", "replace")` on `request.httprequest.environ['PATH_INFO']` and you get the value `/test/�`,

So on the final path you have applied `encode("latin1").decode("utf-8", "replace")` twice.
That's will, I think you have to do the inverse of this `encode("latin1").decode("utf-8", "replace")` when setting the value of `request.httprequest.environ['PATH_INFO']` in the method `reroute` [line 412](https://github.com/odoo/odoo/blob/cfde4bc8b7f0f7edcae6f33ed2ce6569fcc46ca0/addons/http_routing/models/ir_http.py#L412)


Best Regards,
M.

**Comment by pedrobaeza** [comment]
Can you propose the patch as a PR and then discuss there with involved people?
