### ISSUE TITLE
[8.0] Imposible use 'parent.field from _parent' attr invisible in a view.

### ISSUE THREAD

**Issue by hugho-ad** [odoo/odoo#5564]
Issue
-----------------
When a field is added to account invoice line for later use in a view by adding the invisible attribute flag error be charged.

http://pastebin.com/70HaU8Z1

Code to reproduce issue
---------------------------------

http://pastebin.com/QvKMM4bH

in View:
http://pastebin.com/uXiT5wXH

Expected results
----------------------
Being able to iterate over another model at the hearing

bug_followup@vauxoo.com

**Comment by dmo-odoo** [comment]
Hello,

Could you please provide us with the error message so we can determine what you problem exactly is ?
And please, either past code or links to something like http://pastebin.com/, but not screenshots of code, thank you.

Regards,
David

**Comment by hugho-ad** [comment]
Hello @dmo-odoo ,
I have already corrected the comment, added a link with the code and the complete error.

**Comment by hugho-ad** [comment]
Hello,
An apology for the way you attach the code.
We are trying to use parent for a field 'one2many', this we try to use the
invisible attribute it, but we we throws the error.

http://pastebin.com/70HaU8Z1

No more for now, I hope to answer
regards

2015-03-04 2:47 GMT-06:00 David Monjoie <notifications@github.com>:

**Comment by dmo-odoo** [comment]
Hello,

Try quoting parent.partner_id so it reads:
<field name="invoice_broker_id" attrs="{'invisible':[('parent.partner_id','=',False)]}"/>
Instead of:
<field name="invoice_broker_id" attrs="{'invisible':[(parent.partner_id,'=',False)]}"/>

Best regards,
David

**Comment by hugho-ad** [comment]
Hello,
I made the switch without getting success, so I see this wrong, but the problem is not 
**partner.partner_id** , is **parent.partner_id**
![supplier invoices odoo](https://cloud.githubusercontent.com/assets/10233975/6532178/33056112-c404-11e4-88c2-a0db6251e232.png)

no more for now, I hope your answer.

regards,
Hugo

**Comment by hugho-ad** [comment]
Hello David,

I have posted one more comments in github page
Espero tu respuesta

Regards,


2015-03-06 3:17 GMT-06:00 David Monjoie <notifications@github.com>:

**Comment by dmo-odoo** [comment]
Hello,

Yes sorry, it was parent and not partner, but it was not the solution anyway as you pointed out.
Try to replace parent.partner_id by "invoice_id.partner_id" with the quotes, they are important.
If it still doesn't work, try "partner_id" instead of parent.partner_id, don't forget the quotes.

Best regards,
David

Best regards,
David

**Comment by hugho-ad** [comment]
Hello
I've already tried that with no results, there will be some way to iterate from the attr as well as in the domain

    field name = "invoice_broker_id" domain = "[('id', '! =', parent.id), ('type', '=', 'in_invoice')]"

**Comment by dmo-odoo** [comment]
Not sure you can write '! =' with a space like that instead of '!=' ...
What are you trying to do actually ? Because this domain is very different that the one in your original question?

**Comment by hugho-ad** [comment]
Sorry, you're right, it "! =" And not "! =" Error finger,
Anyway, I'm trying to iterate through a view, access the attributes of the parent model in the same way it is done in the domain.

**Comment by dmo-odoo** [comment]
You are mistaking account.invoice and account.invoice.line. Your invoice_broker_id field is on the account.invoice.line level, but the type field is on the account.invoice level.
