### ISSUE TITLE
--auto-reload, virtualenv and JetBrains PyCharm

### ISSUE THREAD

**Issue by dmzkrsk** [odoo/odoo#5570]
Launching `oody.py` 8.0.0 with `--auto-reload` via PyCharms's remote intepretier support results in replacing virtualenv's python executable with system-wide executable
And oody.py fails with:

```
Traceback (most recent call last):
  File "/opt/virtualenv/odoo/bin/odoo.py", line 164, in <module>
    main()
  File "/opt/virtualenv/odoo/bin/odoo.py", line 160, in main
    import openerp
ImportError: No module named openerp
```

`sys.executable` appears to change from `/opt/virtualenv/odoo/bin/python` to `/usr/bin/python`.

Looking through the source, in `services/server.py` in `_reexec` function, I found, that changing

```
exe = os.path.basename(sys.executable)
```

to

```
exe = sys.executable
```

i. e., using full path as first argument to `execv` works well

I had no this issue running `oddo.py` directly from linux shell, but it also runs well with the fix

**Comment by Yenthe666** [comment]
Hi @dmzkrsk ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: I believe it is handled better in V9 and up.

Regards,
Yenthe
