### ISSUE TITLE
Can't make order in Chinese Language, Data input like "03/04/2015 6:01:15 下午" not valid.

### ISSUE THREAD

**Issue by diddlboy** [odoo/odoo#5574]
I use Debian 8 (jessie) for test, with this repo: deb http://nightly.odoo.com/8.0/nightly/deb/ ./
I can make an order in English, but can't in Chinese Language, because the default date format is in Chinese, like this "03/04/2015 6:01:15 下午", and if I manually change the "下午" to "pm", then it is okay.
I think it is a bug.

**Comment by Yenthe666** [comment]
Hi @diddlboy,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
