### ISSUE TITLE
procurements silently fail if working time has no hours on it

### ISSUE THREAD

**Issue by AlanBell** [odoo/odoo#5575]
if you set up a working time and fail to define the working days, then put it on a routing and put the routing on a BOM then order point procurements for that product silently hang. No exception, no message in the log, no clue as to the reason. The procurement should go into exception.

**Comment by Yenthe666** [comment]
Hi @AlanBell,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
