### ISSUE TITLE
Odoo V7 / V8 : _default_get of account_move_line does not return move

### ISSUE THREAD

**Issue by svalaeys** [odoo/odoo#5578]
Hello,

When the user creates account move lines directly from the tree, he or she expects that if an move is not balanced, Odoo will automatically create a line that will balance it. 

To do so, Odoo, in the _default_get method of account_move_line, will attempt to find an unbalanced move by looking for the latest unbalanced draft move in the same journal for the same period created by the same user. This is done on line 254 of account_move_line.py in Odoo V8 (260 in Odoo v7) of the account module.

Practically, this is wrong. If accountant B modifies lines created by accountant A, Odoo does not create the correct entry. Instead, it will create a blank entry because it did not find any moves in the query mentionned above. Simply replacing create_uid by by write_uid solves the problem, since by making a modification and unbalancing the lines created by Accountant A, it is now Accountant B's UID which has done the last modification.

I can't think of any side effects to this modification, and anyway, as it stands, I am sure Odoo does not work as even you intended.

Kind regards,

Stephane Valaeys

**Comment by svalaeys** [comment]
As you will have no doubt corrected yourself, create_uid cannot simply be replaced by write_uid since the latter is sometimes null. It needs to be replaced by COALESCE(write_uid, create_uid).

**Comment by Yenthe666** [comment]
Hi @svalaeys,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
