### ISSUE TITLE
[12.0] hw_scale, hw_scanner and hw_display dropped from stable version ?

### ISSUE THREAD

**Issue by houssine78** [odoo/odoo#55808]
Impacted versions:
12.0

Steps to reproduce:
look at the addons folder and this [commit](https://github.com/OCA/OCB/commit/a6f44ee93e44b9784e6d0333d0284e3b28a35d9e)

Current behavior:
hw_scale, hw_scanner and hw_display not there anymore

Expected behavior:
having hw_scale, hw_scanner and hw_display present and working

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
That modules are only for PosBox/IoTBox, so they don't apply to regular versions and if such version is not applying to be used for the device, it's logical to be removed.

Closing as no issue, but question.

**Comment by houssine78** [comment]
sorry @pedrobaeza but I don't agree with you. How could you still have you scale working after updating the posbox code which may be usefull some time... Even then it's not even sure that the POS continue to work after updating the code while you keep the hw_* unchanged on the posbox.

my point is, it break the Point of Sale so more than a question it's an issue...

**Comment by pedrobaeza** [comment]
Steps to reproduce the problem?

**Comment by houssine78** [comment]
@pedrobaeza it's about to have the driver available. it seems that it has been forgotten to backport it from the 13.0

Maybe that @aprieels can enlight us ?

![image](https://user-images.githubusercontent.com/7766650/90541428-e7d95700-e182-11ea-82c9-e800d5306002.png)

![image](https://user-images.githubusercontent.com/7766650/90541522-12c3ab00-e183-11ea-9cc2-cfd294c73419.png)

**Comment by aprieels** [comment]
The version of the PosBox/IoTBox is different from the version of Odoo.
Images for the IoTBox are built from the latest release of Odoo and work with previous versions too.
The code of the IoTBox will soon be moved to a separate repository to avoid any confusion.

**Comment by houssine78** [comment]
@aprieels it means that until the move of the code, we should use the iot box code from 13.0 for a Point of Sale running on 12.0 right ?

thanks for your explanation

**Comment by aprieels** [comment]
The latest IoTBox image (20.06, available [here](http://nightly.odoo.com/master/posbox/iotbox/)) has been built from Odoo saas-13.4 and can indeed be used with 12.0

**Comment by houssine78** [comment]
thanks for your answer ! it's clear now !
