### ISSUE TITLE
[8.0] No Prevent message when deleting a one2many line

### ISSUE THREAD

**Issue by JonathanNEMRY** [odoo/odoo#5589]
**No Prevent message when deleting a one2many line**

**Impacted versions:**

 - 8.0

**Steps to reproduce:**

1. Go to runbot/configuration/Users/Groups
2. Select one and pass into `edit mode`
3. Click on the trash button of a line of the users list: a message is shown `do you really want to remove...`
4. Go to Sales/Quotations/ and select one with order lines
5. Pass into the edit mode and click on the trash button of a line

**Current behavior:**

 - No message, the record is deleted

**Expected behavior:**

- Same behavior as the users' lines into the goups form

**Notes**

1. This happens only for a `one2many`, not for a `many2many`
2. If you set a `widget=many2many` the message is shown and there is no bug
3. In debug mode we pass as well into the 
```
if (!(ids.length && confirm(_t("Do you really want to remove these records?")))) {
            return;
}
```
but strangely the right part return true without opening a window

**Comment by xmo-odoo** [comment]
> but strangely the right part return true without opening a window

The o2m list specifically replaces window.confirm by a no-op: https://github.com/odoo/odoo/blob/8.0/addons/web/static/src/js/view_form.js#L4573

Sadly, [the commit introducing that behavior does not indicate *why*](https://github.com/odoo/odoo/commit/3f955f05250614174be25d190c7d988d0a69b9aa) and I fear I do not remember. At any rate, it's been that way basically all along.

**Comment by Olivier-LAURENT** [comment]
> Maybe because it doesn't actually do anything until the parent form is saved...

Hmmm ... maybe the record was never saved ! In that case it is definitively lost without any "Pay Attention" message !

**Comment by beledouxdenis** [comment]
Hello Jonathan, 

The fact the Warning message is not shown for one2many list is actually the behavior chosen by Odoo: If you had a lot of lines to delete, you would have to confirm the Warning popup for each line, which would be cumbersome for the user / usability. Besides, you always have the possibility to discard your changes by hitting the discard button of the form.

For instance, this Warning message is not displayed for many2many tags either (e.g. taxes in a sales order line), while this is also a *2many fields, and, therefore, according to you, the Warning message should be displayed as well for these tags.

The fact that this message is displayed for many2many is, from our point of view, the actual issue. If we had to correct something, to standardize the behavior of all *2many fields, it would be to not display this Warning message for many2many fields, such as users of groups, which is the opposite of what you want.

Anyway, we cannot regard this as a bug, but rather as a wish, and the wish would be the opposite of what you want. Wishes are not done in stable releases, such as 7.0 and 8.0. We only fixes blocking issues. You can read our bug fixes policy here:
https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean

If we do something about this behavior being different for one2many and many2many, it would therefore be in the development branch, master.

We hope you will understand.

Regards,
