### ISSUE TITLE
Wrong inventory calculation

### ISSUE THREAD

**Issue by Muhammadinaam** [odoo/odoo#55909]
**Impacted versions**:11

**Odoo is not updating inventory calculations**
I tested Odoo 11 for this issue: https://github.com/odoo/odoo/issues/6618. This issue has been closed but it still exists in odoo 11. Please fix this.

**Comment by Yenthe666** [comment]
Closing as there are no reproducable steps or anything showing it is still an issue on V11.
Update your issue with teproducable steps & I'll reopen it.
