### ISSUE TITLE
[12.0] stock_account: _run_valuation ignores cost of selected serial number and uses FIFO cost

### ISSUE THREAD

**Issue by matt454357** [odoo/odoo#55905]
**Impacted versions:** 12.0 Enterprise and 12.0 Community

**Steps to reproduce:**

1. Create serial tracked product
   a. Tracking = serial
   a. Costing Method = fifo
   a. Inventory Valuation = automated
1. Purchase and receive first unit
   a. Price = $10
   a. Serial = L01
1. Purchase and receive second unit
   a. Price = $20
   a. Serial = L02
1. Sell and deliver the second unit (serial L02)

**Current behavior:**

- Credit to inventory account = $10
- Current Inventory valuation = $20

**Expected behavior:**

- Credit to inventory account = $20
- Current Inventory valuation = $10

**Comment by ray-odoo** [comment]
FIFO = first in, first out.

As far as I recall, this is how fifo costing works in Odoo. You can think of this as financial fifo. 

I believe you are asking for "costing based on actual deplenishment order chosen by the user".

**Comment by matt454357** [comment]
Hi @ray-odoo,
So, the "Real Price" costing method, as implemented in 10.0, has been abandoned.  You literally wrote the book on this stuff.  Are you aware of a way to get the old functionality back?

**Comment by ray-odoo** [comment]
@matt454357 - correct "real price" costing is no longer available.   Customization would be required to get this back.  I was never asked to implement real cost once FIFO was available, sorry!

**Comment by Yenthe666** [comment]
I guess this answers the questions & closes the issue. Thanks @ray-odoo
