### ISSUE TITLE
How to export the text inputted on " Log an Internal Note " ? Next to " Send a message "

### ISSUE THREAD

**Issue by ManosAC** [odoo/odoo#5592]
One problem, how can you export the text inputted after the " Log an Internal Note "  ?

I have went into the level selecting all the fields in the export section, even selecting " export all data " under " export type " however i did not saw the information regarding the " internal notes ",

Anyone has an idea if its possible to export the internal notes ? please advise

PS : what i mean is for instance in the Leads section, under the lead there is a " Send a message " or " log an internal note " , what im trying to export is the info in the " Log an internal note " section, anyone has an idea on that ?

**Comment by xmo-odoo** [comment]
Both "messages" and "internal notes" are the same regular chatter messages, they just differ in their subtypes. IIRC, "internal notes" have an empty subtype.

So you just need to export the content of the "Messages" field ("Contents" for the HTML contents, and "Subtype" so you can  check whether it's an internal note or a regular message).

/cc @tde-banana-odoo for confirmation
