### ISSUE TITLE
When using @api.constrains('one2many_field_ids'), it doesn't get called in the create().

### ISSUE THREAD

**Issue by NicolasWebDev** [odoo/odoo#5594]
**When using @api.constrains('one2many_field_ids'), it doesn't get called in the create()**

Impacted versions:
- 8.0

Models:
- Let's say I have a model of the form:

``` python
model_a(models.Model):
    _name = 'model.a'

    one2many_field_ids = fields.One2many('model.b', 'model_a_id')

    @api.constrains('one2many_field_ids')
    def _check_one2many_field_ids(self):
        print 'entered'
```

My goal
- In the model_a form, I present the one2many_field_ids field as a tree, and I would like the constraint to be called whenever I add, remove or modify one of its elements.

Current behavior
- The constraint gets called on the model_a.write(), not on the model_a.create().

Expected behavior
- I would expect the constraint to be called in the create() method as well.

**Comment by Yenthe666** [comment]
Hi @NicolasWebDev,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
