### ISSUE TITLE
[8.0] Navigation toggle bar missing in mobile interface

### ISSUE THREAD

**Issue by dsabrinarg** [odoo/odoo#5597]
Hello, I wonder if the following behavior is the desired or is it an issue, when Odoo opens in a mobile web browser the toggle bar navigation is missing making the menu nav bar hardly recognizable.

<b>Impacted versions:</b>
8.0

<b>Steps to reproduce:</b>
Here you can see a demo image from the missing navigation toggle bar in Odoo from a web browser on a mobile device

![odoo desde iphone](https://cloud.githubusercontent.com/assets/7597456/6489985/7269e65e-c268-11e4-9849-1e3167d47949.png)

<b>Current behavior:</b>
Here you can see a demo image from the navigation toggle bar in Odoo when a web browser window is smaller resized

![odoo_desde_browser](https://cloud.githubusercontent.com/assets/7597456/6490849/d14436b0-c26e-11e4-8e72-c7aca13b44ad.png)

<b>Expected behavior:</b>
That the navigation toggle bar in web browsers on mobile devices are displayed

**Comment by Yenthe666** [comment]
Hi @dsabrinarg,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
