### ISSUE TITLE
[8.0] field Boolean with attr related- value no updated correctly

### ISSUE THREAD

**Issue by hugho-ad** [odoo/odoo#5598]
When using a  boolean field with  attr related, this field is not filled with the value of the relation.
When I add a line to invoice, this line is created with the 'partner_broker_ok' field to False, although the partner of this has 'is_broker_ok' = True, then to save the invoice, is written 'res.partner' field as false, being related, which should not happen.

    class res_partner(models.Model):
    _inherit = 'res.partner'
    is_broker_ok = fields.Boolean(
        'Is broker OK?', help='Mark this field if this partner is a broker')

    class AccountInvoiceLine(models.Model):
    _inherit = 'account.invoice.line'
    partner_broker_ok = fields.Boolean(
        string='Partner Broker', **related='invoice_id.partner_id.is_broker_ok'**,
        store=False, help='Indicate if the partner to invoice is broker')

<h5>**Impacted versions:**</h5>
8.0

<h5>**My goal:**</h5>

Having integrity with this attr in the 'field.boolean' update fields proper activation either the left or right of the realción.

**Comment by rco-odoo** [comment]
@hugho-ad make your related field readonly, this should prevent the orm from writing a false value on it, and the value you read afterwards should be correct.
