### ISSUE TITLE
[12.0] Reserved Qty from production order is not been propagated to its workorders

### ISSUE THREAD

**Issue by Lopsanz** [odoo/odoo#55991]
Manufacturing based in Workorders:
* Finished: lot tracking, Bom with a route with 2 operations
** raw 1: lot tracking, Consumed in op1 inventory: 10 units of lot 0001, and 20units of lot 0002
** raw 2. lot tracking. Consumed in op2. there're 30 units of lot 003
-------------
Made a production order for 25 units of finished:
![image](https://user-images.githubusercontent.com/22096355/90622572-94641900-e215-11ea-873e-60d0b248b804.png)
![image](https://user-images.githubusercontent.com/22096355/90622649-b198e780-e215-11ea-8753-5e42d401349e.png)

When I plan production workorders where materials are already reserved, these reservations should be assigned to proper workorder, but a new stock.move.line is created and shown in work operation:
![image](https://user-images.githubusercontent.com/22096355/90622890-09375300-e216-11ea-8e7c-a3d39146593d.png)

https://github.com/odoo/odoo/blob/b8aa4f5719c2d12d9f12c57cb410f52bfaa3d1a6/addons/mrp/models/mrp_workorder.py#L276

This code should be like:
```
            else:
                if move.product_id.tracking == 'lot' and move.active_move_line_ids:
                    move.active_move_line_ids.write({
                        'production_id': self.production_id.id,
                        'workorder_id': self.id,
                        'done_wo': False, })
else:
   Moveline...
```

**Comment by pedrobaeza** [comment]
Please explain proper steps to reproduce the error.

**Comment by Lopsanz** [comment]
I've not tested this on 13.0 yet, @Yenthe666

**Comment by Yenthe666** [comment]
Sorry clicked the wrong label. Let us know when you have reproducible steps :)

**Comment by Lopsanz** [comment]
Issue explanation edited. Sorry for my english LOL!

**Comment by Yenthe666** [comment]
Sorry but this still doesn't really explain it. We need reproducable steps that we can do on a runbot instance to simulate the behaviour. You only describe a part.

**Comment by pedrobaeza** [comment]
Yes, @Lopsanz, please put a full example: this product X with this BoM, create a MO, etc, etc.

**Comment by Lopsanz** [comment]
Is this enough?

**Comment by pedrobaeza** [comment]
Uf, it still take some time, but why don't you propose a PR directly with the solution and this text if you have clear the bugfix?

**Comment by Lopsanz** [comment]
https://github.com/odoo/odoo/pull/56134
