### ISSUE TITLE
[v8] Bug - Weight / Volume on product view Locked at 3 digits and ignoring configuration.

### ISSUE THREAD

**Issue by richard-willdooit** [odoo/odoo#5599]
Why are weight and volume (particularly since weight DP is configurable) set at Decimal precision 3?

Looking in product_view.xml in product module, the 3 columns in question have "digits="(14, 3)" hard coded...

**Comment by lefas** [comment]
Me too look for set volume with 6 digits decimal for m2.

**Comment by Yenthe666** [comment]
Hi @richard-willdooit,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
