### ISSUE TITLE
Properly adding watermark on reports?

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#5601]
I need to add watermark in new qweb reports. I figured I could add it on header, so it would repeat watermark every page (If I add watermark in reports body, it will only show up in one page, in a place where you put that watermark).

But if I add it in header, then it will not add watermark on whole page, but only where header frame is, what I mean it looks like this:

Let say watermark in this example is two lines height:

`water`
`mark`

So now if report would be two pages long, it looks like this, when printed:

```
|------------|
|header      |
|water       |     
|------------|
|body        |
|            |
|------------|
|footer      |
--------------
|------------|
|header      |
|water       |     
|------------|
|body        |
|            |
|------------|
|footer      |
--------------
```

But I need watermark to go through whole report, not just in header frame. So it should look like this:

```
|------------|
|header      |
|water       |     
|------------|
|mark        |
|body        |
|------------|
|footer      |
```

In Odoo there are two main layouts that might be used to add watermark in.
First is general layout template, that defined whole report (header, body, footer). And it looks like this:

My watermark css looks like this (it takes image that is uploaded in Odoo and uses as watermark):

```
    <t t-if="company.img_watermark">
        <div class="watermark" style="position:absolute;opacity:0.25;width:100%;text-align:center;z-index:1000;">
            <img t-att-src="'data:image/png;base64,%s' % company.img_watermark"/>
        </div>
     </t> 

<template id="external_layout">
    <!-- Multicompany -->
    <t t-if="o and 'company_id' in o">
        <t t-set="company" t-value="o.company_id"></t>
    </t>
    <t t-if="not o or not 'company_id' in o">
        <t t-set="company" t-value="res_company"></t>
    </t>
    <!-- Calls header -->
    <t t-call="report.external_layout_header" />
    <!-- This is supposed to be body -->
    <t t-raw="0" />
    <!-- Calls footer layout-->
    <t t-call="report.external_layout_footer" />
</template>
```

If I add watermark in this template, then watermark is not showed at all. But if I add it in header template, then it shows, but only part of watermark (in other words only that part that fits in header).

So to get that I can do this:

<template id="external_layout_header" inherit_id="report.external_layout_header">
    <xpath expr="">

```
</xpath>
<div class="header">
    <div class="row">
        <div class="col-xs-3">
            <img t-if="company.logo" t-att-src="'data:image/png;base64,%s' % company.logo" style="max-height: 45px;"/>
        </div>
        <div class="col-xs-9 text-right" style="margin-top:20px;" t-field="company.rml_header1"/>
    </div>
    <div class="row zero_min_height">
        <div class="col-xs-12">
            <div style="border-bottom: 1px solid black;"></div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-3">
            <div t-field="company.partner_id" 
                t-field-options='{"widget": "contact", "fields": ["address", "name"], "no_marker": true}'
                style="border-bottom: 1px solid black;"/>
        </div>
    </div>
</div>
```

</template>

 But as I showed in that "graphical" example, it won't show whole watermark. Also as I written before, if I add watermark in body, it will only show in a first page, and won't repeat if report has more than one page.

P.S. there is this answer about watermarking https://www.odoo.com/forum/help-1/question/watermarking-in-odoo-8-reports-72810, but it does not solve the problem I mentioned.

**Comment by Yenthe666** [comment]
Hi @oerp-odoo,

Please do ask these kind of questions on the help forums. The Github bug tracker is only for bugs in the official code, it is not for asking questions.
To answer your question: CSS could be an option.

Regards,
Yenthe
