### ISSUE TITLE
[13.0] purchase_stock: write method

### ISSUE THREAD

**Issue by sudhir-erpharbor** [odoo/odoo#56041]
Impacted versions: v13

Steps to reproduce: Make the state field clickable and try to change the state to "Purchase Order" by clicking on the field.

Current behavior:
local variable 'pre_order_line_qty'  referenced before assignment.

Expected behavior:
System should not give the error in any case.

Video/Screenshot link (optional):

Error comes from the following code. I think "pre_order_line_qty" variable must be defined when the method is started to fix the error.

    def write(self, vals):
        if vals.get('order_line') and self.state == 'purchase':
            for order in self:
                pre_order_line_qty = {order_line: order_line.product_qty for order_line in order.mapped('order_line')}
        res = super(PurchaseOrder, self).write(vals)
        if vals.get('order_line') and self.state == 'purchase':
            for order in self:
                to_log = {}
                for order_line in order.order_line:
                    if pre_order_line_qty.get(order_line, False) and float_compare(pre_order_line_qty[order_line], order_line.product_qty, precision_rounding=order_line.product_uom.rounding) > 0:
                        to_log[order_line] = (order_line.product_qty, pre_order_line_qty[order_line])
                if to_log:
                    order._log_decrease_ordered_quantity(to_log)
        return res

![image](https://user-images.githubusercontent.com/7952467/90503097-85755c00-e16c-11ea-9de6-d38999790013.png)

**Comment by pedrobaeza** [comment]
You can't do that, as state can't be clickable, having other logic associated.

Closing as no valid issue, as this is modifying standard business logic. If you replicate the problem without modifying code, then please answer back.

**Comment by sudhir-erpharbor** [comment]
But this could happen if you have any customization as well. You know clients can have any demand and with any level of customization, system should not raise the error. Don't you agree?

**Comment by pedrobaeza** [comment]
Several points:

- If you plan to put a PR, don't open an issue. Put the "issue" text in the PR itself.
- OK, there can be a code bug that is not shown in standard behavior. The PR is there and it can be checked by Odoo team for its consideration, being an obvious variable not assigned question.
- Regardless of this, you can't make that kind of changes, or you will break a lot of things. You must respect the core logic and flows.
