### ISSUE TITLE
[8.0] SQL Views disappear from database

### ISSUE THREAD

**Issue by Cedric-Pigeon** [odoo/odoo#5605]
When you override a field by changing its type.
If this field is used in a sql view and you forget to override its corresponding field, the view is simply dropped from the database without any error message.

# Way to reproduce:

1. Install module sale:
    A SQL view named sale_report is in the database.
2. Create a module depending on sale which override the field ``date_order`` from model ``sale_order`' and put it as date in place of datetime.
3. Load this new module in the database
  => The sale_report view is not in the database anymore.

# Causes:

The model sale_report contains a column ´´date´´ filled with ´´date_order´´ of table sale_order.
Without any doubt this a programming error which introduce an inconsistency.
But, when loading the module, the odoo server does not raise any error and **there is no way to be aware of this problem**. The view is simply dropped.

**Comment by Cedric-Pigeon** [comment]
@rco-odoo  What's your opinion about this issue ? Thanks.

**Comment by Cedric-Pigeon** [comment]
ping @rco-odoo

**Comment by xmo-odoo** [comment]
This is a "known" issue in that we've hit it in the past, however we found no reliable solution to it: during the migration of columns, columns are dropped with `CASCADE` (if they're dropped or if they're altered in ways not supported by an in-place `ALTER COLUMN`) as they might have constraints or indexes which we want to ignore. However that also unconditionally drops views, I don't remember us finding any way around that: in theory you might be able to add a trigger on pg_views (though I'm not sure that actually works in practice) but then what? It's not like you can prevent modules e.g. dropping views before recreating them.

**Comment by Cedric-Pigeon** [comment]
@xmo-odoo  I understand your point of view and your difficulties. But you can also understand that spending hours to find the reason of view dropped is very frustrating. Are you working on a solution to improve this in the future ?

**Comment by xmo-odoo** [comment]
> But you can also understand that spending hours to find the reason of view dropped is very frustrating.

We've hit the issue in the past so I certainly can be cause I did exactly that.

> Are you working on a solution to improve this in the future ?

At the moment? No. There are relatively few views internally and as I said we didn't find any good workaround.
