### ISSUE TITLE
DELETE FROM ir_attachment WHERE id = %s make server slow and cannot even login

### ISSUE THREAD

**Issue by bjccdsrlcr** [odoo/odoo#56091]
Odoo server sudden stop or loading issue due to ir attachment

Impacted versions:
Odoo 10
Steps to reproduce:
Created binary field in odoo 9 and data stored in filestore. (attachment=True)
Current behavior:
Sometime log file below query is running at that time server is very slow and user unable to login system or server time out.
openerp.sql_db:bad query delete from ir_attachment where id in (257445, 25744)
openerp.sql_db:bad query delete from ir_attachment where id in (257445, 25744)
openerp.sql_db:bad query delete from ir_attachment where id in (257445, 25744)
openerp.sql_db:bad query delete from ir_attachment where id in (257445, 25744)
Expected behavior:
I would like to skip above query so user can login to system. The above query automatic run default odoo core module. Please let me know how to avoid to run the above query or skip? the above query run on which condition?

**Comment by pedrobaeza** [comment]
Odoo 10 is out of official support. Only last 3 versions are.

Closing due to this.
