### ISSUE TITLE
How can call from the event click of widget Y, the event defined on widget X?

### ISSUE THREAD

**Issue by RodmanII** [odoo/odoo#56090]
Impacted versions: 13.0

Steps to reproduce:
Is not really possible to reproduce

Current behavior:
Unable to do it myself

Expected behavior:
Receiving an answer

Video/Screenshot link (optional):
Im sorry to post this in here, but both the documentation and official forums are utter garbage.

How can call from the event click of widget Y, the event defined on widget X?

I created a widget for a button with js and xml
xml
```
<t t-name="OrderListButton" name="Order List Button">
<div class="control-button" id="sale_order_btn" style="width: 70%;margin-top: 5px;margin-bottom: -5px;">
    <i class='fa fa-th-list' role="img"
       aria-label="Pedidos" title="Pedidos"/> <span id="sale_order_txt" t-esc="widget.get_current_sale_name()"/> </div>
</t>
```

Js
```
var OrderListButton = screens.ActionButtonWidget.extend({
    template: 'OrderListButton',
    button_click: function(){
        var orders = this.pos.orders;
        var order = this.pos.get_order()
        order.sale_order_id = false;
        this.gui.show_screen('orderlist',{orders:orders});
    },
    get_current_sale_name: function() {
        var res = "Pedido";
        var order = this.pos.get_order();
        var orders = this.pos.orders;

        if (order) {
            if (order.sale_order_id && orders) {
                for(var j=0;j < orders.length; j++){
                    if(orders[j].id == order.sale_order_id) {
                        res = orders[j].name;
                        break;
                    }
                }
            }
        }

        return res;
    },

```
Such button opens another screen, in that other screen there a list and button that launch a popup, another button in the popup send me back to original screen, the one that contains the OrderListButton button, the problem is once back to this screen, the one containing OrderListButton, the value of the span sale_order_txt is still the same, when its supposed to be the label of the new sale_order_id, but the value remains the same despite the changes in the variable, and the variable does change. I was thinking maybe i could call from the modal the function .get_current_sale_name(), but how? How can call from the event click of widget Y, the event defined on widget X?

Something like
```
click_confirm: function(){
      this.widget_order_list.get_current_sale_name();
        }
```

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
