### ISSUE TITLE
When manually creating credit note: accounts are not inherited from product.category of upper levels (alike sale order)

### ISSUE THREAD

**Issue by scaldewi** [odoo/odoo#56119]
When using product in sale order line, the income account is inherited from product category if not set in product itself. 
If income is not set in product category, but in parent category, it is inherited from upper/top level product category.

this behaviour is missing if one creates credit note manually. Problem is if creating a credit note with product that has no income/expense account set in product itself or in direct category.

https://github.com/odoo/odoo/blob/01d92223d5b82dce83bf8c43c10b57c4b9193141/addons/account/models/product.py#L38

Expected behaviour: Odoo should "climb up" in product category to find income/expense account if not set in product itself.

Observed behaviour: Odoo only looks in product and direct product category, but not in higher level product categories

**Comment by pedrobaeza** [comment]
Odoo version? Where is the code for upper categories? I didn't know such behavior in standard.

**Comment by scaldewi** [comment]
Sorry, it is Odoo 13.0
When creating invoice from sale order, account properties are optional in product and in product category.
On creation of invoice from sale order Odoo iterates from product through product categories upwards until it finds account properties set.
Not 100% sure, but think upwards browsing is done here: https://github.com/odoo/odoo/blob/f68c523a4d2feccaecb84a67f573b477b95c1677/addons/product/models/product_template.py#L20

**Comment by pedrobaeza** [comment]
I don't think so, that's the default value of the category. Can you please show where the parent categories account behavior is reproduced (maybe a video)?

**Comment by scaldewi** [comment]
My confusion. Odoo takes default income account from company property if not set in product or direct product category.
The behaviour is different in credit note. There, it does not take it from company property but throws an error that no account is defined.

One could argue that it is more accurate to give error message instead of falling back to a default.
From my understanding both behaviours should be the same.
But as this is only kind of glitch, we can close this issue
