### ISSUE TITLE
Please document usage of openerp.model.Model.new()

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#5611]
Today I found [`new()`](https://github.com/odoo/odoo/blob/ad4a269554cf77e37ddcbc114bb919f54fb894b1/openerp/models.py#L5390) casually when I was facing a problem when trying to create a record inside an `api.onchange()` event, [as many others have](https://www.odoo.com/forum/help-1/question/create-new-many2one-records-in-api-onchange-method-2nd-try-70212).

It's not documented at all, and IMHO it would help a lot to module developers.

**Comment by Yenthe666** [comment]
Hi @Yajo,

Thank you for your bug report/tip.
@mart-e perhaps we can still add some info about it? Couldn't find it right away in the docs.

Regards,
Yenthe

**Comment by Frakenz** [comment]
@Yenthe666 Why was this closed? What is the use of new()? I am using it inside an onchange function in V13 and the record is still being stored in the database before I save or discard (discarding doesn't delete it either)

Here is my function if relevant:
```
    @api.onchange('location_id')
    def _onchange_location(self):
        for r in self:
            if r.location_id not in r.product_id.product_location_ids.location_id:
                r.product_id.product_location_ids |= r.env[
                    'my_inventory.product_location.rel'].new({
                        'location_id': r.location_id.id,
                        'product_id': r.product_id.id,
                    })
```
For context, `my_inventory.product_location.rel` is supposed to represent a Many2many relation between `my_inventory.product` and `stock.location` which stores and computes some attributes like quantity per location.
