### ISSUE TITLE
[12.0] Untranslatable string in .js file

### ISSUE THREAD

**Issue by reinaldoramosarxi** [odoo/odoo#56168]
Hello,

In the website_sale and website_event_sale add ons there are a couple of .js files with a string that can't be translated. 

It's e-commerce, so it's important that all of the strings visible to the costumer can be adapted to their languages.

The string is present in two lines:

https://github.com/odoo/odoo/blob/12.0/addons/website_sale/static/src/js/website_sale_tour_buy.js#L83
https://github.com/odoo/odoo/blob/12.0/addons/website_event_sale/static/src/js/website.tour.event_sale.js#L90

Thank you.

**Comment by pedrobaeza** [comment]
They are 2 tours, so nothing in the direct customer UI and only valid for testing purposes.

Closing, as no valid issue.

**Comment by reinaldoramosarxi** [comment]
Hello,

We found the actual strings afterwards, just had a lot of html mixed in.

Thank you!
