### ISSUE TITLE
Odoo is not able to handle HTTP and JSON request from the same controller

### ISSUE THREAD

**Issue by deep-rajput** [odoo/odoo#56175]
**Impacted versions:**
- 13.0
- 12.0
- 11.0

**Steps to reproduce:**

- The scenario is third party api is calling the odoo controller with HTTP type to verify the URL(odoo controller route). After successful verification that URL(odoo controller route) that third party api is post some data to that same URL(odoo controller route) with JSON type.

**Current behavior:**
- Odoo can not able to handle the JSON and HTTP type handling with the same controller.

**Expected behavior:**
- Odoo should be able to handle the HTTP and JSON type with the same controller.

**Comment by pedrobaeza** [comment]
@xmo-odoo I remember similar requests of this. Can you please remind us why is not possible for now?

**Comment by Yenthe666** [comment]
It was simply not engineered this way. Odoo V14 will add support to do both though.

**Comment by Yenthe666** [comment]
See https://github.com/odoo/odoo/pull/55303 as a reference. Closing as this will implemented in V14 and will not be backported to older versions (as it adds a feature)

**Comment by pedrobaeza** [comment]
Thanks for the reference, Yenthe. I remember that such thing exists, but without details.
