### ISSUE TITLE
ImportError: DLL load failed: The specified procedure could not be found

### ISSUE THREAD

**Issue by khaldon** [odoo/odoo#56170]
Impacted versions:
Odoo 13 
Steps to reproduce:
I am trying to run `python odoo-bin`  

Current behavior:
`ImportError: DLL load failed: The specified procedure could not be found.`
Expected behavior:
Run odoo server
Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/10290194/90694055-403e5080-e278-11ea-8085-f1a093592084.png)

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/13.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).
