### ISSUE TITLE
mailbox is set ok, but discuss app does not receive any new email, odoo13 linux

### ISSUE THREAD

**Issue by alexhmyang** [odoo/odoo#56172]
Impacted versions: 13 community

Steps to reproduce:

![image](https://user-images.githubusercontent.com/10215059/90714152-9c858c80-e2d9-11ea-86ea-6b705ce7b094.png)
technical-email-message , I can see odoo receives new email, but in discuss app, there is no email nor notice.

 
![image](https://user-images.githubusercontent.com/10215059/90714257-d787c000-e2d9-11ea-918d-8c70ee368b59.png)

![image](https://user-images.githubusercontent.com/10215059/90714393-26355a00-e2da-11ea-9277-b9a315021801.png)
the receiving mailbox is set ok

Current behavior:

Expected behavior:

I saw the other tutorial receive ok, but I cannot ,why?

![image](https://user-images.githubusercontent.com/10215059/90714316-fd14c980-e2d9-11ea-9472-756a98c21ea5.png)

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question on how to make social network to work. Take into account that the incoming server is not for having an inbox, but a router to Odoo documents. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
