### ISSUE TITLE
[7.0] Context missed out in do_partial class stock.picking

### ISSUE THREAD

**Issue by santiago-orozco** [odoo/odoo#5619]
When you invoke do_partial in a partial delivery , there is a bug in the copy method invocation where the context variable is missed out when it is called

**Comment by yvaucher** [comment]
I is missing in multiple `copy()` call in stock in 8.0 too as in https://github.com/odoo/odoo/pull/4993

**Comment by Yenthe666** [comment]
Hi @santiago-orozco,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
