### ISSUE TITLE
Example odoo qrcode url product

### ISSUE THREAD

**Issue by tunghactech** [odoo/odoo#56256]
i'm have project build 1 module about manager product and i want create qrcode for product 
Odoo have qrcode-> may be ?
But i don't be use ?
Example ??? 
Sr because i talk english not good . Thank you

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
