### ISSUE TITLE
[8.0][master] Picking Lists(Deliver Orders) are created without stock assignment if Create Invoice == Before Delivery

### ISSUE THREAD

**Issue by nafex** [odoo/odoo#5627]
**Picking Lists are created without stock assignment**

Since some days, if you create a sale order with "Create Invoice"= "Before Delivery", odoo will create picking lists with products that are not assigned to any reserved_quants if the invoice is payed. The picking list is allways "Ready to Transfer". On each line the product availabilty is 0.0 but the status is "Available". Doesn't matter if the products are available in stock or not. it's the same behavior...

Impacted versions:

 - 8.0 (reproduced on latest runbot 8.0)
 - master (reproduced on latest runbot master)

Steps to reproduce:

 1. create a new sale order with "Create Invoice"= "Before Delivery" on tab other information
 2. add a line with product [A1090] iMac (a product that is NOT available in stock)
 3. validate the sale order
 4. go to the invoice and validate them too
 5. in the invoice click on "Register Payment" and confirm the payment with Payment Method: Bank (EUR)
 6. the picking list is created by odoo. go back to your sale order and click on "view delivery order"
 7. click on "Check Availability"

Current behavior:

 - The delivery order is set to Ready to Transfer

Expected behavior:

 -  The delivery order should be set to waiting availability

**Comment by nafex** [comment]
maybe @jco-odoo should take a look on this...

**Comment by jco-odoo** [comment]
Before delivery or not has normally nothing to do with assigning the stock, ...

**Comment by nafex** [comment]
do you have reproduced the steps?

**Comment by nafex** [comment]
Maybe I expressed myself wrong, but the error is there...

**Comment by nafex** [comment]
@jco-odoo I tried again on runbot and creating the invoice "before delivery" has something to do with it. If you choose "on demand" or "on deliver order" everything works but if you choose "before delivery" the picking is created wrongly as described above

**Comment by nafex** [comment]
after some investigation i discovered that if the delivery order is created from an sale order with "invoicing set to before delivery", it will create the stock_moves with product_qty = NULL. and because of that the delivery order is set to ready to transfer... but i don't understand why the stock_moves are created wrong...

**Comment by jco-odoo** [comment]
We noticed this on our side too now.  What you say is interesting.  It must
have something to do with the store= of product_qty then.  But it stays
something strange, because in both cases, it should pass through the
action_ship_create in the same way.

**Comment by nafex** [comment]
Thank you very much for checking this.

The strange thing is: if invoicing is set to before delivery, in

/openerp/models.py line 4253

the recs.env.recompute is False but it should be True like if invoicing is set on demand...
I don't know where and how recs.env.recompute is set. But this is the only difference that i found between the two cases. All other things are equal. Like you said both cases passes the same way, but on this point they differs. And because of that the field product_qty is not set...

**Comment by nafex** [comment]
I don't understand why in one case recs.env.recompute is False and in the other case it is True.
@rco-odoo maybe this is a bug in the new api?

**Comment by nafex** [comment]
@jco-odoo @rco-odoo Do you have any idea how I can fix it? This bug is very anoying as we have many orders with invoicing before delivery and I must correct the delivery orders manually every day...

**Comment by jco-odoo** [comment]
We will do a quick and dirty patch with store=True in v8 and look asap for a complete solution.

**Comment by jco-odoo** [comment]
We did the temporary fix in v8 with store=True

**Comment by nafex** [comment]
thank you very much! commit ac67ce4ecc7e04467f3f4e0bdbdb32eef151ab31 fixed this
