### ISSUE TITLE
web_editor in odoo13 should not add images as attachment

### ISSUE THREAD

**Issue by eversatis** [odoo/odoo#56334]
Impacted versions: odoo13
This is a conflict with enterprise module sale_ebay. When I up listing product from odoo to ebay, odoo upload the attachment image to ebay product gallary. But if you have many images in website description, they will be all attach to the product. Since it is not that enterprise app issue. web_editor in odoo13 should not add images as attachment to avoid conflict.

**Comment by eversatis** [comment]
Alright, thank your for your reply. Actually I do not think it is enterprise issue. I see odoo12 website description images are not attached in the attachment list and have no such issue. So odoo13 may not consider the ebay module function and should not add the description images to the attachments. It should be the web_editor issue rather than the sale_ebay issue.

**Comment by pedrobaeza** [comment]
It doesn't matter, as if you have an enteprise contract, both modules (community and enterprise) are covered, so please expose your problem there and see what Odoo support team says about it.

**Comment by eversatis** [comment]
OK, I am not odoo partner but I will report it to the local partner who sold me the modules. Thank you!
