### ISSUE TITLE
report rendering needs safe defaults for 'lang' and 'o' variables

### ISSUE THREAD

**Issue by simahawk** [odoo/odoo#5633]
The [docs state](https://www.odoo.com/documentation/8.0/reference/reports.html) that a minimal report looks like this:

```
<template id="report_invoice">
    <t t-call="report.html_container">
        <t t-foreach="docs" t-as="o">
            <t t-call="report.external_layout">
                <div class="page">
                    <h2>Report title</h2>
                    <p>This object's name is <span t-field="o.name"/></p>
                </div>
            </t>
        </t>
    </t>
</template>
```

but this does not work, because when you don't use `translate_doc` you don't have the object of the report in `docs` but the report itself, nor you have `o` variable as the object of the report, [because `translate_doc` is the only one that inject the variable `o`](https://github.com/odoo/odoo/blob/8.0/addons/report/models/report.py#L114).

Moreover, if you use `translate_doc` [you are forced to pass a field](https://github.com/odoo/odoo/blob/8.0/addons/report/models/report.py#L113) (or a field of a field) of the object of the report containing the lang. BUT if you don't have a field like `partner_id` or whatever... you are lost. 

AFAIK, the only safe way to make it work as it is, is to use this trick: use `env.lang` that can be evaluated on the object itself...

```
<t t-raw="translate_doc(doc_id, doc_model, 'env.lang',  'my_reports.report_foo')"/>
```

This is a bit insane... :)
- 1st, we need a safe default for lang - from the user, the company, the context (it's even there!!), whatever
- 2nd we need `o` variable ALWAYS available, because people expects it, also for legacy reasons.

**Comment by Yenthe666** [comment]
Hi @simahawk,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by simahawk** [comment]
ages ago... fine :)

**Comment by Yenthe666** [comment]
Yep - sorry for the close though! 😉
