### ISSUE TITLE
slide not shown after install ssl for https nginx

### ISSUE THREAD

**Issue by alexhmyang** [odoo/odoo#56361]
Impacted versions:

Steps to reproduce:

Current behavior:
Mixed Content: The page at 'https://www.xxx.com/slides/slide/xxx-notes1-3?fullscreen=1' was loaded over HTTPS, but requested an insecure frame 'http://www.xxx.com/slides/embed/3?page=1'. This request has been blocked; the content must be served over HTTPS.

Expected behavior:

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/10215059/91014554-2c01a700-e61c-11ea-89bd-8c750e71738a.png)

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/13.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).

**Comment by alexhmyang** [comment]
https://stackoverflow.com/a/60274213/14155910
I find the solution here


 had a similar problem: Loading PDF presentation in the eLearning module ("slides") would request the resource over http rather than https. What worked in my case:

adding proxy_mode = True into the [options] section of odoo.conf (if you deployed using docker, put odoo.conf into /etc/odoo/odoo.conf, which in their docker-compose.yml example is a shared folder (./config:/etc/odoo)
nginx config I'm using (I was missing the X-Forwarded-Host header):
location / {
proxy_pass http://localhost:8069;
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
proxy_set_header Host $host;
proxy_cache_bypass $http_upgrade;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-NginX-Proxy true;
proxy_set_header X-Forwarded-Proto https;
proxy_set_header X-Forwarded-Host $host;
proxy_redirect off;
proxy_request_buffering off;
proxy_connect_timeout  36000s;
proxy_read_timeout  36000s;
proxy_send_timeout  36000s;
send_timeout  36000s;
client_max_body_size 10240m;
}
when in developer mode, go to Settings -> Technical -> System Parameters, and make sure your web.base.url contains https:// (some people also add web.base.url.freeze set to True -- this doesn't seem to have an effect on my installation)
Restart nginx, restart odoo, and voila, PDFs in Slides are being requested over https://.
