### ISSUE TITLE
[8.0] Error when switching lang in Shop with several filtered attributes turned on

### ISSUE THREAD

**Issue by a0c** [odoo/odoo#5637]
Impacted versions:
- 8.0

Steps to reproduce:
1. go to Website => Shop => any product
2. make sure `Product Attribute's Filters` is turned on in `Customize` menu
3. in attributes filter, select at least 2 values in the same attribute (e.g. 2 colors or 2 memories)
4. switch language by clicking on `English` link at the bottom of the page

Current behavior:
- Server Error 500

Diagnosis:
- Link  `/shop?search=&attrib=1-1&attrib=1-2` is turned into `/en_US/shop?search=&attrib=1-1%2C1-2` for a different language. Merged attributes thus cannot be parsed by the server. Should either fix the <a> link in the language, or fix attribute parsing on the server side.

**Comment by Yenthe666** [comment]
Hi @a0c,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
