### ISSUE TITLE
[8.0] Wrong ident in sale_stock

### ISSUE THREAD

**Issue by dhongu** [odoo/odoo#5640]
https://github.com/odoo/odoo/blob/8.0/addons/sale_stock/sale_stock.py#L355

Wrong:
``` python
        #update of warning messages
        if warning_msgs:
            warning = {
                       'title': _('Configuration Error!'),
                       'message' : warning_msgs
                    }
        res.update({'warning': warning})
        return res
```

Correct is 
``` python
        #update of warning messages
        if warning_msgs:
            warning = {
                       'title': _('Configuration Error!'),
                       'message' : warning_msgs
                    }
            res.update({'warning': warning})
        return res
```

**Comment by droelneo** [comment]
+1

Very annoying as we can't add warning messages.

The solution is not really here above.

As there is other messages in res, we have to concatenate strings in message!

**Comment by Yenthe666** [comment]
Hi @dhongu,

I don't see any problems with this code and neither do I see changes in the 'wrong' and 'correct' version?
Either way, this is not a bug and works as expected.

Regards,
Yenthe
