### ISSUE TITLE
[BUG][13.0] Formatting of date fields does not work for email templates

### ISSUE THREAD

**Issue by sudo-san** [odoo/odoo#56429]
Impacted versions:
13 Enterprise (maybe also 13 CE but only tested on EE)

This can be reproduced on odoo 13 enterprise runbot
On odoo 12 enterprise runbot, this works without error message.

Steps to reproduce:
Step 1. Go to Settings -> Email -> Templates (developper mode must be active)
Step 2. Select a standard Email Template of odoo ("Invoice: Send by email" in my case)

Now if you want display the invoice date on the email for example, you have to set the following placeholder in the email template: ${object.date_invoice}
The problem with this is, that odoo shows the date with the following format: YYYY-MM-DD
In V12, it was possible to define the format within the placeholder like this for example: ${format_tz(object.date_invoice, tz='UTC', format='%d/%m/%Y')}

Step 3. Add this placeholder in the email template: ${format_tz(object.date_invoice, tz='UTC', format='%d/%m/%Y')}
Step 4. Press Smart Button "Preview"

Current behavior:
You get an error:
Failed to render template <Template memory:7fa451eb92b0> using values {'format_date': <function MailTemplate._render_template.<locals>.<lambda> at 0x7fa452db9c80>, 'format_datetime': <function MailTemplate._render_template.<locals>.<lambda> at 0x7fa45131b048>, 'format_amount': <function MailTemplate._render_template.<locals>.<lambda> at 0x7fa45131b2f0>, 'format_duration': <function MailTemplate._render_template.<locals>.<lambda> at 0x7fa45131b268>, 'user': res.users(2,), 'ctx': {'lang': 'en_US', 'tz': 'Europe/Brussels', 'uid': 2, 'allowed_company_ids': [1], 'template_id': 31, 'active_model': 'mail.template', 'active_id': 31, 'active_ids': [31], 'template_preview_lang': 'en_US', 'safe': False}, 'object': account.move(86,)}

UndefinedError: 'format_tz' is undefined

Expected behavior:

The date should be formatted according to the defined format in the placeholder string

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a development question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Having something that works in one version, but not available in the following one doesn't mind is a bug. 

Closing this by the reason above.
