### ISSUE TITLE
[BUG][13.0] stock_landed_costs: Adjust the last line's value for currencies with decimal_places as 0

### ISSUE THREAD

**Issue by thongthele** [odoo/odoo#56433]
**Impacted versions:** v13 (but probably others as well)

**Steps to reproduce:**
1. Create a purchase order with 3 products:
- [DESK0004] Customizable Desk (CONFIG) (Aluminium, Black)
- [E-COM06] Corner Desk Right Sit, 
- [E-COM07] Large Cabinet
2. Confirm Order -> Receive Products -> Validate
3. Create a Landed Costs for the PO above with 1 product:
- Product `Shipping cost`, `Cost` as 10 VND, `Split Method` as Equal 
4. Click on `Compute` button

**Current behavior:**
- After the allocation, the new value is added with 1 VND due to rounding.

**Expected behavior:**
- Adjust the value of the last line for currencies with decimal_places as 0

**Video/Screenshot link (optional):**
![Brush-#1](https://user-images.githubusercontent.com/43790414/88870186-f812ac00-d23e-11ea-8307-b0992426342f.png)

**Comment by pedrobaeza** [comment]
Please don't open an issue if you are going to open a PR. Put the issue description there. Closing this one and letting the PR opened.

**Comment by thongthele** [comment]
> Please don't open an issue if you are going to open a PR. Put the issue description there. Closing this one and letting the PR opened.

I see, if I just open PR, you don't look at it

**Comment by pedrobaeza** [comment]
I'm not the one solving issues nor reviewing PRs, so it doesn't matter. A PR can be review easier than an issue report by Odoo stuff.

**Comment by thongthele** [comment]
> I'm not the one solving issues nor reviewing PRs, so it doesn't matter. A PR can be review easier than an issue report by Odoo stuff.

@pedrobaeza So can I close that PR, and re-open this issue?

**Comment by pedrobaeza** [comment]
Why? It's going to have the same attention. I'll ping possible reviewers, but without guarantees.
