### ISSUE TITLE
[BUG][13.0] The CSRF token is causing survey submissions to crash after 1h

### ISSUE THREAD

**Issue by thongthele** [odoo/odoo#56431]
**Impacted versions:** v13 (but probably others as well)

**Similar issues:** #51499

**Steps to reproduce:**
1. Create a survey that has a survey time limit> 60 minutes
2. Join the survey
3. When the 1h expiration occurs in the middle of taking a survey exam, and the user is never able to post the answers. It can even lead to blocking bugs.

**Current behavior:**

The CSRF token has a default value of 1 hour and cannot be changed in the template view, which causes survey submissions to crash after 1h. I think currently the CSRF token is causing survey submissions to crash after 1h, because the token never seems to be refreshed.

**Expected behavior:**

If survey time limit > 60 minutes, the CSRF tokens are based on the current time limit of survey, and automatically expire as soon as the survey done.

**Video/Screenshot link (optional):**

**Comment by pedrobaeza** [comment]
@odony should the patch you made be backported to v13?

**Comment by odony** [comment]
@pedrobaeza I'd rather not backport the global CSRF token expiration change, as it's a significant change in a stable feature. We can fix the issue for that specific case in 13.0, by passing `time_limit=None`, as I commented on the PR (#55895)

**Comment by pedrobaeza** [comment]
OK, good less invasive solution. Let's close then this issue as there's a PR in progress.
