### ISSUE TITLE
8.0: Export Translation: Popup does not adapt in size to select module

### ISSUE THREAD

**Issue by treviser** [odoo/odoo#5648]
It is not reasonably possible to select modules for translation export because the size of the popup window does not adapt in order to show the module selection scroll bar.
![exporttranslationpopup](https://cloud.githubusercontent.com/assets/1814941/6551724/9d4904b2-c63d-11e4-9edd-135a964c590b.png)

**Comment by Yenthe666** [comment]
:+1: this has annoyed me in the past too. Thanks for reporting!

**Comment by carlos-incaser** [comment]
:+1:

**Comment by treviser** [comment]
thanks for the reminder!

On 11.03.2015 13:48, Yenthe wrote:
>
> :+1: this has annoyed me in the past too. Thanks for reporting!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/odoo/odoo/issues/5648#issuecomment-78256193>.
>

-- 
twanda AG
Ermin Trevisan
Artherstrasse 19
CH-6318 Walchwil
T    +41 41 758 1515
M    +41 79 208 7373
E    trevi@twanda.com
www.twanda.ch
www.ipadweinkarte.twanda.ch

**Comment by sle-odoo** [comment]
Closing as it's functionally working, although unintuitive: the modal doesn't grow to display the selection but is scrollable, so you can see all of it. Fixing this will probably add a few other css glitches elsewhere so we won't do it. Also please note that this is fixed in >= 9.0.
