### ISSUE TITLE
[12.0] sale_mrp: Delivered qty of kit products is not computed correctly when cancelling a backorder

### ISSUE THREAD

**Issue by hugho-ad** [odoo/odoo#56535]
Impacted versions:
12.0

Steps to reproduce:
1-Create a Product Kit
2-Create a new Sales Order for your Kit
3-Make a partial Deliver and create a backorder
4- Update the delivered qty on sale order line Manually
5- Cancel the backorder
Current behavior:
The Delivered qty on line was updated with the original demand (prduct_qty)
Expected behavior:
Keep the delivery method on manually 

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/10233975/91196818-3a090380-e6c0-11ea-89bd-169a39a0408e.png)

![image](https://user-images.githubusercontent.com/10233975/91196779-2c537e00-e6c0-11ea-8975-bbfe22493189.png)

https://www.youtube.com/watch?v=R-P9rPKhv5M&feature=youtu.be

## OPW 2326028

**Comment by pedrobaeza** [comment]
What I don't get is how are you able to manually edit the delivered quantity, which in principle is not editable.

**Comment by hugho-ad** [comment]
because this line
https://github.com/odoo/odoo/blob/782534a429f10e7b114c838687d38aa4080a920c/addons/sale_mrp/models/sale_mrp.py#L84

Since all moves are not done (backorder is not canceled yet), qty_delivered_method is set to manually

**Comment by pedrobaeza** [comment]
Uhm, I see the hack about that explicitly for BoM kits... It's a bit weird, but indeed it should be consistent.

**Comment by vava-odoo** [comment]
Linked ticket is solved
