### ISSUE TITLE
Uncaught Error: QWeb2 - template['ListView.rows']: Runtime Error: Error: QWeb2 - template['ListView.row']: Runtime Error: Error: '32020-01-1' is not a correct date, datetime nor time

### ISSUE THREAD

**Issue by intisankar** [odoo/odoo#56546]
Impacted versions: odoo9

Steps to reproduce: Click on menu item

Current behavior: remaining working fine

Expected behavior: normally open the trree view

Video/Screenshot link (optional): https://paste.pics/9X8EM

**Comment by Yenthe666** [comment]
Hi,

Can you reproduce this issue on an official Odoo instance at runbot.odoo.com? The latest builds seem to work fine there. Besides of this your ticket lacks enough information to reproduce this issue. Please add more details to this ticket.

Regards,
Yenthe

**Comment by intisankar** [comment]
it happens in custom meu creation what are the possible case to produce this error

**Comment by Yenthe666** [comment]
Doesn't matter as V9 is no longer supported and it is custom development, which is both not covered in support. You should be making a mistake in your code though ;)
