### ISSUE TITLE
Odoo8 procurement and sales return document processing, the design is too simple, cannot meet the needs;

### ISSUE THREAD

**Issue by talway** [odoo/odoo#5654]
We are a Chinese trading company, do food, with a / / department stores such as a comprehensive trading company, products, customers; we do China's 430 WAL-MART business, 230 Carrefour business, 100 big Runfa business, and traditional wholesale channels, more types of customers, our existing system can not meet the need, we know the odoo is quite good, at present in the test whether the application of our company.
Currently found in returns processing too simple single, as follows:
         Our monthly shipments of relatively large, at the same time, due to reasons such as unsalable products returned or more, we are unable to know the goods that month issued, so the need for the same return processing, odoo must find the documents issued to return;

**Comment by Yenthe666** [comment]
Hi @talway,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
