### ISSUE TITLE
Odoo8 currently purchase returns and sales return, return form occurs in the purchase order and sales, no state or individual field suggest a return to

### ISSUE THREAD

**Issue by talway** [odoo/odoo#5655]
Odoo8 currently purchase returns and sales return, return form occurs in the purchase order and sales, no state or individual field suggest a return to; can not know the purchase order and sales of single return, need to own a document a document their own inquiries, not directly in the purchase order or sales document query happened to return,

**Comment by Yenthe666** [comment]
Hi @talway,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
