### ISSUE TITLE
Odoo8 the whole and parts conversion display problems

### ISSUE THREAD

**Issue by talway** [odoo/odoo#5656]
For example: 1 products are the basic units of measurement: a unit of measurement, outside the box: box; 1:24 is the conversion ratio. Is the 1 box has 24 products; if I buy or sell 50 products, at present the odoo8 conversion 50 divided by the 24=2.08 box; but I want a field to represent the field whole and parts of the "2 Box 2", is now the inbound or outbound can see the specific number of simple box number and individual pick up the goods, convenient and fast recognition; hope to increase the identification field identifies the whole and the parts, in picking or storage interface reflected, thank you.

**Comment by Yenthe666** [comment]
Hi @talway,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
