### ISSUE TITLE
[13.0] account: Deprecated accounts are selectable when manually creating a journal entry

### ISSUE THREAD

**Issue by pedrobaeza** [odoo/odoo#56586]
**Impacted versions:** 13.0

**Steps to reproduce:**

- Activate full account features.
- Go to chart of accounts, and mark as deprecated one of the accounts.
- Go to journal entries, and create one.

**Current behavior:**

You are able to select the deprecated account in the lines.

**Expected behavior:**

Not able to do it.

The domain `[('deprecated', '=', False)]` is put on the field (https://github.com/odoo/odoo/blob/e981c17dd93c756a5cf0384ab2dcc25ef58cb1b1/addons/account/models/account_move.py#L2529), but it's not getting to the view somehow that I haven't investigated yet.

@Tecnativa TT25276

**Comment by pedrobaeza** [comment]
@qdp-odoo @oco-odoo can you please take a look?

**Comment by oco-odoo** [comment]
@pedrobaeza Thanks for reporting ;) Fixed here https://github.com/odoo/odoo/pull/56676 I'm closing the issue :)

**Comment by pedrobaeza** [comment]
Thanks!
