### ISSUE TITLE
[Wish] New type of field: path

### ISSUE THREAD

**Issue by MiquelRForgeFlow** [odoo/odoo#56589]
**Current behavior:**

If you define a field like:
```python
filedata = fields.Binary(string="Import file")
```
then in the view form will appear a button to upload the file, which let you navigate in your data system to choose the corresponding file:
![Selection_028](https://user-images.githubusercontent.com/25005517/91308286-5c2d7f00-e7af-11ea-8c98-f1f98271601b.png)

**Request:**

I would like to have something similar, but instead of choosing a file, let's you choose a directory (folder) instead:
```python
filepath = fields.Path(string="Import path")
```
where Path supposedly should be an extension of Char.

**Comment by Yenthe666** [comment]
@MiquelRForgeFlow what's your functional idea for this? Do you have a sample?

**Comment by pedrobaeza** [comment]
That doesn't serve, as Odoo server doesn't have the notion of that directory.

**Comment by mart-e** [comment]
Hi,
I agree with Pedro, working with filepath is not very common for a webapp. Not that it isn't possible, just not a scenario frequent enough to justify a new field in standard. This is typically the kind of thing for custom module (e.g. someone made [an audio field](https://apps.odoo.com/apps/modules/13.0/audio_field/) as a module for instance).
