### ISSUE TITLE
Product quantity wrongly calculated in stock_move when uom<>uos

### ISSUE THREAD

**Issue by jalzaga** [odoo/odoo#5667]
Product quantity wrongly calculated in stock_move when uom<>uos

SERIOUS

Impacted versions:
- 8.0

Steps to reproduce:
1. create a new sale order that generates a stock picking
2. Use unit of sale box of 12, round factor 1.0
3. add a line with product , quantity 5, box of 12  
4. Confirm the order
5. Look at the stock picking - stock move

Current behavior:
- Product quantity = 61

Expected behavior:

 Product quantity = 60

The error is in the rounding method when the quantity is calcultated. It is using "UP" instead of "HALF-UP" so that the quantity 60.0000024 is rounded to 61. 
In /addons/product/product.py we can see in line 178:
def _compute_qty_obj(self, cr, uid, from_unit, qty, to_unit, round=True, rounding_method='UP', context=None):

change it by:
def _compute_qty_obj(self, cr, uid, from_unit, qty, to_unit, round=True, rounding_method='HALF-UP', context=None):

**Comment by kkoci** [comment]
Do you say that this lil change on product.py code,  will solve this issue?

**Comment by jalzaga** [comment]
Yes, I did it. However I expect it will be fixed in the standard Odoo code

**Comment by Yenthe666** [comment]
Hi @jalzaga,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
