### ISSUE TITLE
Add Transifex Live to Developement Mode

### ISSUE THREAD

**Issue by maxstoyanov** [odoo/odoo#56724]
I suggest using [Transifex Live](https://docs.transifex.com/live/introduction) for translating directly inside Odoo. Finding which terms belong together is quite timeconsuming and the translation of Odoo highly depends on the context that is not easily visible from the Transifex interface.

**What is Transifex Live**
> Transifex Live makes it easy to translate your web app or website. It works through a snippet of JavaScript you add to your site, similar to Optimizely or Google Analytics. With Transifex Live, you’re able to:
> 
> - Save content for translation directly from your website to Transifex without using files.
> - Translate and review your website in context (think WYSIWYG).
> - Publish translations on the fly without engineering dependencies.
> 
> There are two ways to use Transifex Live – directly on your site, or within Transifex itself. Both let you do the things mentioned above and show you the same information, so you can switch between the two as needed. We’ll look at the two options and the benefits of each.

**What are the benefits?**
- There are a lot of untranslated strings in Odoo. Lowereing the barrier might entice more contributors to translate Odoo to their language.
- Finding the right context is extremely important in a complex app like Odoo. Especially when there is a one to one mapping between terms in is not possible. (see expense in english and german: aufwand, auslagen, spesen, ausgaben. Those have substantial different meanings in the german fincance field.)

**Comment by pedrobaeza** [comment]
There's a module for easing the translation, but not sure if Transifex live can help more and the efforts to integrate it. @mart-e can you comment about?

**Comment by mart-e** [comment]
I have never tested Transifex Live but it doesn't seem compatible with Odoo, it's for static website as far as I understand (and not dynamic content as for most Odoo content).
Have you tried it?

**Comment by hoangtrann** [comment]
> There's a module for easing the translation

hi @pedrobaeza , could you point out which module is it?

**Comment by pedrobaeza** [comment]
https://github.com/odoo/odoo/tree/13.0/addons/transifex
