### ISSUE TITLE
[8.0] Removing an account.move.line results in a posted unbalanced account.move

### ISSUE THREAD

**Issue by pablocm-aserti** [odoo/odoo#5675]
How to reproduce:
Create a balanced journal entry (account.move) and post it.
Go to journal items and delete one of the previous journal entry lines.

Result:
The journal entry is still posted but its remaining lines are unbalanced without any kind of warning or error.

Expected result:
Removal of a journal item belonging to a posted entry should not be allowed. An error should have been raised.
If you try to post unbalanced entries it is not allowed, so removing a "posted" line is an unwanted way to circumvent that restriction

**Comment by Yenthe666** [comment]
Hi @pablocm-aserti,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
