### ISSUE TITLE
7.0 Debian nightly repository broken

### ISSUE THREAD

**Issue by mgmax** [odoo/odoo#56763]
Impacted versions: http://nightly.odoo.com/ 7.0 old release

Steps to reproduce:
- Add Debian repository: http://nightly.odoo.com/7.0/nightly/deb/
- apt-get install openerp

Current behavior:
Fails:
```
Err:1 http://nightly.odoo.com/7.0/nightly/deb ./ openerp 7.0.0
  404  Not Found [IP: 178.33.123.40 80]
```

Expected behavior:
works

Problem:
The release file http://nightly.odoo.com/7.0/nightly/deb/Release points to a non-existent file http://nightly.odoo.com/7.0/nightly/deb/./openerp_7.0.20170329_all.deb . It looks like this file was accidentally deleted on the server. 

I do understand that 7.0 is no longer supported since ages, but for archive purposes it would be good to have a working link on the nightly website.

**Comment by pedrobaeza** [comment]
@d-fence not sure if this is still supported, but I suppose that at least the file should be there.
