### ISSUE TITLE
[11.0] Change attribute editable of tree in form view

### ISSUE THREAD

**Issue by estraka** [odoo/odoo#56766]
Impacted versions: 11

I want to modify the behavior of a form-->tree so that a popup opens, but the code that worked in version 10 does not work in version 11. To do so, I need an attribute of the tree to be uninformed (neither top nor botton ).

Steps to reproduce:

When I create inherit of: "sale.view_order_form" with

    <xpath expr="//field[@name='order_line']/tree" position="attributes">
                <attribute name="readonly">[('state', 'in', ('done','cancel'))]</attribute>
                <attribute name="editable"/>  **ERROR IN THIS CODE LINE**
        </xpath>

This code is similar of standard: sale/views/sale_views.xml: (I don't know how to test it)
 
        <record id="view_order_form_editable_list" model="ir.ui.view">
            <field name="name">sale.order.form.editable.list</field>
            <field name="model">sale.order</field>
            <field name="inherit_id" ref="sale.view_order_form"/>
            <field name="groups_id" eval="[(4, ref('product.group_stock_packaging'))]"/>
            <field name="arch" type="xml">
                <xpath expr="//field[@name='order_line']/tree" position="attributes">
                    <attribute name="editable"/>
                </xpath>
            </field>
        </record>

ERROR:
--------
Error:
TypeError: undefined is not an object (evaluating 'this.state.fields[fieldName].string')

http://localhost:11069/web/content/8326-aabcd5e/web.assets_backend.js:1411
Rastreo de error:
_renderTagLabel@http://localhost:11069/web/content/8326-aabcd5e/web.assets_backend.js:1411:867
_renderInnerGroupLabel@http://localhost:11069/web/content/8326-aabcd5e/web.assets_backend.js:1401:120
http://localhost:11069/web/content/8326-aabcd5e/web.assets_backend.js:1398:136
http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:12:566
_renderInnerGroup@http://localhost:11069/web/content/8326-aabcd5e/web.assets_backend.js:1395:67
http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:3819:376
http://localhost:11069/web/content/8326-aabcd5e/web.assets_backend.js:1411:28
http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:13:278
_renderTagGroup@http://localhost:11069/web/content/8326-aabcd5e/web.assets_backend.js:1410:21
http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:3819:376
[native code]
http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:13:278
_renderTagForm@http://localhost:11069/web/content/8326-aabcd5e/web.assets_backend.js:1408:21
http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:3819:376
_renderView@http://localhost:11069/web/content/8326-aabcd5e/web.assets_backend.js:1417:1241
_render@http://localhost:11069/web/content/8326-aabcd5e/web.assets_backend.js:1355:189
start@http://localhost:11069/web/content/8326-aabcd5e/web.assets_backend.js:1099:342
http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:3816:493
http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:802:686
fire@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:796:304
add@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:797:471
http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:802:649
each@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:625:771
http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:802:564
Deferred@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:803:198
then@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:802:533
start@http://localhost:11069/web/content/8326-aabcd5e/web.assets_backend.js:1106:664
http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:3816:493
start@http://localhost:11069/web/content/8326-aabcd5e/web.assets_backend.js:1326:1023
http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:3816:493
http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:802:686
fire@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:796:304
add@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:797:471
http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:802:649
each@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:625:771
http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:802:564
Deferred@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:803:198
then@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:802:533
http://localhost:11069/web/content/8326-aabcd5e/web.assets_backend.js:1378:24
http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:802:686
fire@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:796:304
fireWith@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:801:202
http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:803:56
fire@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:796:304
fireWith@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:801:202
http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:803:56
fire@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:796:304
fireWith@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:801:202
http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:802:874
fire@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:796:304
fireWith@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:801:202
http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:804:502
fire@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:796:304
fireWith@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:801:202
http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:803:56
fire@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:796:304
fireWith@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:801:202
http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:802:874
fire@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:796:304
fireWith@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:801:202
http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:803:56
fire@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:796:304
add@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:797:471
http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:802:776
fire@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:796:304
fireWith@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:801:202
http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:803:56
fire@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:796:304
add@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:797:471
http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:802:776
fire@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:796:304
fireWith@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:801:202
http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:803:56
fire@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:796:304
fireWith@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:801:202
http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:803:56
http://localhost:11069/web/content/8326-aabcd5e/web.assets_backend.js:1263:12
fire@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:796:304
fireWith@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:801:202
http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:803:56
fire@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:796:304
add@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:797:471
http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:802:776
fire@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:796:304
fireWith@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:801:202
http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:803:56
http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:3869:363
http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:802:686
fire@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:796:304
fireWith@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:801:202
http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:803:56
fire@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:796:304
fireWith@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:801:202
http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:802:874
fire@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:796:304
fireWith@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:801:202
http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:802:874
fire@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:796:304
fireWith@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:801:202
done@http://localhost:11069/web/content/8320-db5f930/web.assets_common.js:1192:106

**Comment by pedrobaeza** [comment]
The error is not there, but on the `readonly` attribute, that can't be an expression. For that, you have `attrs`.

Closing as no real issue, but bad custom code.
