### ISSUE TITLE
Odoo 13 nightly debian repository is not signed

### ISSUE THREAD

**Issue by onorua** [odoo/odoo#56768]
Here is what I've got:
```Ign:7 http://nightly.odoo.com/13.0/nightly/deb ./ Release.gpg
Reading package lists... Done
E: The repository 'http://nightly.odoo.com/13.0/nightly/deb ./ Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.```

Release.gpg is not present at `http://nightly.odoo.com/13.0/nightly/deb` so there is nothing with the client-side but rather repo is broken.

**Comment by pedrobaeza** [comment]
@d-fence can you check?

**Comment by gnfranco** [comment]
> Here is what I've got:
> 
> ```
> Reading package lists... Done
> E: The repository 'http://nightly.odoo.com/13.0/nightly/deb ./ Release' is not signed.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.```
> 
> Release.gpg is not present at `http://nightly.odoo.com/13.0/nightly/deb` so there is nothing with the client-side but rather repo is broken. 
> ```

I'm having the same problem.

**Comment by d-fence** [comment]
Fixed, thanks for the report.
