### ISSUE TITLE
Can not change master password 

### ISSUE THREAD

**Issue by physiii** [odoo/odoo#56765]
On odoo 13, trying to change master password.

Go to file: ./debian/odoo.conf

change password in line: 

admin_passwd = admin

Restart odoo.

Still says: Database backup error: Access denied

Also tried commenting out the admin_passwd to see if it asks me to set a new one...nope

**Comment by pedrobaeza** [comment]
This is not something of Odoo, but on your deployment. Probably the config file you have modified is no longer valid.

Anyway, closing here. You can ask for help in forums.
