### ISSUE TITLE
[7.0 & 8.0] image_resize_image_big function: Wrong size

### ISSUE THREAD

**Issue by chesucr** [odoo/odoo#5677]
Inside the file image.py the function

     def image_resize_image_big(base64_source, size=(1204, 1024), ...
it should be

     def image_resize_image_big(base64_source, size=(1024, 1024), ...

**Comment by alejandrosantana** [comment]
Why close. Not being commented by Odoo nor PR merged. And the typo is still there. Can you reopen?

**Comment by chesucr** [comment]
ooops, I checked the file and I though it was fixed. My mistake

**Comment by alejandrosantana** [comment]
Yes, that typo is so easy to misread.
