### ISSUE TITLE
purchase.order tree view override

### ISSUE THREAD

**Issue by magimaidas** [odoo/odoo#56774]
Impacted versions: odoo12

Steps to reproduce: Inherit purchase order tree view => view id : purchase_order_tree

Current behavior:Unable to override purchase order tree

Expected behavior:To be overriden according to changes

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Please show your code :)

**Comment by magimaidas** [comment]
<record id="view_purchase_order_tree_onboarding" model="ir.ui.view">
        <field name="name">purchase.order.tree</field>
        <field name="model">purchase.order</field>
        <field name="inherit_id" ref="purchase.purchase_order_tree"/>
        <field name="mode">primary</field>
        <field name="arch" type="xml">
            <xpath expr="//tree" position="attributes">
                <attribute name="banner_route">/purchase/onboarding_panel</attribute>
            </xpath>
        </field>
    </record>

**Comment by Yenthe666** [comment]
Euhm shouldn't you override the banner view itself instead of the PO view?

**Comment by magimaidas** [comment]
> Euhm shouldn't you override the banner view itself instead of the PO view?

My intention is to add the attribute (banner_route) to the tree view(purchase.order).

**Comment by Yenthe666** [comment]
Why don't you just re-enable the banner & modify the banner itself? This is misuse. 
@pedrobaeza do you agree?

**Comment by pedrobaeza** [comment]
Yes, anyway, this is a question about custom development, so it should be placed in forums, not here.

**Comment by magimaidas** [comment]
> Why don't you just re-enable the banner & modify the banner itself? This is misuse.
> @pedrobaeza do you agree?

I am a newbie to odoo. It would be more helpful if you could explain the way. Thanks

**Comment by magimaidas** [comment]
> Yes, anyway, this is a question about custom development, so it should be placed in forums, not here.

Ok @pedrobaeza

**Comment by Yenthe666** [comment]
Please do ask these kind of questions at https://www.odoo.com/forum/help-1 :)
