### ISSUE TITLE
[12.0][FIX] account: impossible to reconcile tax

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#56803]
**Impacted versions**: 12.0 and maybe other

There are an issue when you try to reconcile taxes lines when you mix taxes on invoice and taxes on payment.

**Steps to reproduce:**
Create account `ACC TAX A`, `ACC TAX B`, with `reconcile` = `True`, `internal_type` = `other`

Create `Taxe A`, with `tax_exigibilty` = `on_invoice` and `account_id` = `ACC TAX A`, 20%
Create `Taxe B`, with `tax_exigibilty` = `on_payment` and `account_id` = `ACC TAX B` and `cash_basic_account_id` = `ACC TAX A`, 20%

Create `invoice A`, `account_id` = `Taxe A`, `unit_price` = 1000, Valide invoice
Create `invoice B`, `account_id` = `Taxe A`, `unit_price` = 500, Valide invoice, Then register a payment. Odoo create a miscellaneous operation `MISC A`, with a line with a `ACC TAX A`

Create `MISC TVA`,
        line 1 : `account_id` = `ACC TAX A`, credit = 300
        line 2 : `account_id` = `401100`, debit = 300

Now select:
        line of MISC A with account `ACC TAX A` (credit 300)
        line of `invoice A` with account `ACC TAX A` (debit 200)
        line of `MISC TVA` with account `ACC TAX A` (debit 100)

Reconcile.

Issue : it is not full reconciled. Because here https://github.com/odoo/odoo/blob/12.0/addons/account/models/account_move.py#L851
if you have one line with `cash_basis` and other line with not `cash_basis` but not paid, it is impossible to full reconcile taxes

Note : if you register a payment of `invoice B`, then try to reconcile, it is full reconciled

@qdp-odoo

**Comment by fmdl** [comment]
@simongoffin

**Comment by fmdl** [comment]
ping @oco-odoo @qdp-odoo @simongoffin

**Comment by fmdl** [comment]
OPW #2328696

**Comment by oco-odoo** [comment]
@fmdl I'm already on it ;) My fix is nearly ready, I'll come back to you soon.

**Comment by fmdl** [comment]
Close by https://github.com/odoo/odoo/pull/57495
