### ISSUE TITLE
[13] Fail to post vendor bill if product is inactive and storable

### ISSUE THREAD

**Issue by auyeung112002** [odoo/odoo#56834]
Impacted versions:
13

Steps to reproduce:
1. Go to runbot and create a new product, set type to **storable product**, create a product category(**costing method set to FIFO, Inventory Valuation set to Automated**)
2. Create a PO with the test product, set price and quantity to positive number.
3. Confirm the PO.
4. Validate the Delivery Order.
5. Create vendor bill.
6. **Archive the test product**
7. Post the vendor bill

Current behavior:
Warning: Odoo is not able to generate the anglo saxon entries. The total valuation of Test Product 2 is zero.

Expected behavior:
Post the vendor bill and create the related stock valuation layer and journal entry.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/8391358/91811437-10248380-ec62-11ea-9af1-6733299599d5.png)

**Comment by sswapnesh** [comment]
Already added Fix at #54610

**Comment by vava-odoo** [comment]
Fixed
