### ISSUE TITLE
Bank statement reconcile proposes vat movements to reconcile

### ISSUE THREAD

**Issue by jalzaga** [odoo/odoo#5683]
Bank statement reconcile proposes vat movements to reconcile

Impacted versions:

 - 8.0

Steps to reproduce:

 1. Create or import a bank statement
 2. Go to the estatement and press reconcile button 
 3. select one of the items and assign it to a customer that has open invoices (With vat lines)  
 4. The vat lines are proposed to reconcile, They are account moves associated to tax accounts.
 
Current behavior:

 - VAT account moves are proposed to reconcile

Expected behavior:

 Only invoice amounts should be proposed to reconcile

**Comment by fclementic2c** [comment]
How did you set the vat account ?

**Comment by jalzaga** [comment]
Internal type= Regular, account_type= Tax, Allow Reconciliation=True
The setup comes from the Spanish chart of account template.
I see, the point is in the Allow reconciliation parameter. It has to be set to False in the accounts you don´t want to reconcile. In fact the Spanish localization Accounts template has to be changed to accomplish this condition.
Thanks a lot for the information
