### ISSUE TITLE
Missing pos orders in Odoo 13v

### ISSUE THREAD

**Issue by bayarbayasgalanj** [odoo/odoo#56840]
Receipt has printed, But that order not found pos session's orders in Backend. How to solve this problem?
This Printed receipt
![2020-09-01](https://user-images.githubusercontent.com/18479401/91824802-ebcea400-ec6d-11ea-999f-02411cb433d4.jpg)
This Backend Orders
<img width="1169" alt="Screen Shot 2020-09-01 at 3 16 12 PM" src="https://user-images.githubusercontent.com/18479401/91824859-04d75500-ec6e-11ea-98ba-ff517185349a.png">

**Comment by pedrobaeza** [comment]
That order hasn't been synchronized, so you have to check why not. Anyway, without reproducible steps, nothing can be done, so I close this. If you find a way to reproduce it, please tell back.

**Comment by bayarbayasgalanj** [comment]
What do you mean by reproducible steps? Do you need the reproducible steps of how I got this error?

**Comment by pedrobaeza** [comment]
Yes, a way to get the problem in an standard installation.

**Comment by tdelbianco** [comment]
@pedrobaeza i can reproduce it at http://demo.odoo.com (V16) in this video: https://drive.google.com/file/d/1v29aPL1vG1uFDNhvp1c-I-aLGbllwlFi/view?usp=sharing

**Comment by pedrobaeza** [comment]
Please open a new issue with such video and instructions to reproduce it.

**Comment by pedrobaeza** [comment]
Great, it's labelled already, so let's see if someone attends it.
