### ISSUE TITLE
Landed Cost Issue in Multiple Lot items

### ISSUE THREAD

**Issue by orchidinfosys** [odoo/odoo#5685]
In multiple lots in Transfer showing wrong former cost in landed cost calculations
Issue is with summing up cost in quant lots - Quantity can be summed but not cost

![purchase orders odoo](https://cloud.githubusercontent.com/assets/2189864/6577329/8396cbca-c756-11e4-93b0-0546489fdfda.png)
![transfers odoo](https://cloud.githubusercontent.com/assets/2189864/6577330/85b20b36-c756-11e4-8710-c608868a0727.png)
![landed costs odoo](https://cloud.githubusercontent.com/assets/2189864/6577332/8735ff4e-c756-11e4-9c13-d9e2a32386ab.png)

**Comment by Yenthe666** [comment]
Hi @orchidinfosys,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
