### ISSUE TITLE
[Website] CMS not support IE8

### ISSUE THREAD

**Issue by auyeung112002** [odoo/odoo#5688]
OS: Windows 7 64 bit
IE: 8.0.7600.16385

Steps to reproduce:
1. Use IE8 to open odoo.com
2. Or Use IE8 to open website built by odoo 8 CMS.

Current behavior:
1. Layout is broken. Look like mobile device layout.
2. Navbar is not working
3. Javascript is not working

Since IE8 is shipped with Windows 7, this issue may affect many end users and stop companies from using odoo 8 for production website.

The issue may be related to watch.js
![image](https://cloud.githubusercontent.com/assets/8391358/6578716/c57e6406-c780-11e4-98d6-92fad4b0a6ad.png)

Maybe related:
http://stackoverflow.com/questions/21175290/object-defineproperty-alternative-for-ie8#21175380

**Comment by sle-odoo** [comment]
As Internet Explorer 8 does not support media queries and Odoo does not ship any polyfill, it cannot work. The minimal Internet Explorer version supported by the CMS of Odoo 8 is 9.
