### ISSUE TITLE
in l10n_cl, when posting a sale invoice for non-chilean customers, does not allow boletas

### ISSUE THREAD

**Issue by Danisan** [odoo/odoo#56982]
Impacted versions:
13.0

Steps to reproduce:
create an invoice for a foreign customer

Current behavior:
if you don't select document type 110, 111 or 112 you cannot invoice the customer

Expected behavior:
that at least if the foreign customer is not a company, you could create a document type "boleta" or "boleta exenta". This behavior is backed-up by this link:

http://www.sii.cl/preguntas_frecuentes/catastro/001_012_2506.htm

**Comment by pedrobaeza** [comment]
If you are going to put a PR, please don't create an issue first, but put the issue text in the PR. Closing as there's a PR fixing this.
