### ISSUE TITLE
Traceback when display image when the underlying model id is > 999 and represented as string to binary content.

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#56985]
Impacted versions: 13.0

Steps to reproduce:
I am sure there are many ways, but basically get a string representation of an integer id sent to binary_content. This is how I found it.

Have an image on a model with an id greater than 1000 and language set to en_AU
Website must be installed.
Show a resized version of that image in kanban view (e.g. image_300 = fields.Image(related=image_1920, width=300))

Current behavior:
Traceback with invalid literal for base 10  1,050

The particular error is triggered here but obviously the cause is somewhere else.
https://github.com/odoo/odoo/blob/73bf2b1a9768527a4dfb0d58b3fc00cabd48f07d/addons/website/models/ir_http.py#L329

Expected behavior:
Behave as though id was < 1000

As a workaround this is working
```python
class IrHttp(models.AbstractModel):
    _inherit = "ir.http"

    def binary_content(self, id=None, **kwargs):
        if isinstance(id, str):
            id = id.replace(",", "")
        return super().binary_content(id=id, **kwargs)
```
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Duplicated of #53818
