### ISSUE TITLE
Could not execute command 'lessc' 

### ISSUE THREAD

**Issue by Codefans-fan** [odoo/odoo#5698]
Use master code.
Run in Window system

when login system. Show the message in the top of web page

**Comment by Codefans-fan** [comment]
![lessc](https://cloud.githubusercontent.com/assets/5079520/6594095/29115f30-c819-11e4-8954-45a2f8e78fe5.png)

**Comment by xmo-odoo** [comment]
Did you install Odoo using the all-in-one installer or are you running it from source?

**Comment by Codefans-fan** [comment]
I running it from source code

**Comment by xmo-odoo** [comment]
Then you need to manually install the [LessCSS](http://lesscss.org) compiler and the clean-css plugin for the same. In master, the external Less compiler is a hard requirement.

**Comment by nick2474** [comment]
I solved this installing dependencies:
sudo apt-get install python-pip python-dev libevent-dev gcc libxml2-dev libxslt-dev node-less libldap2-dev libssl-dev
