### ISSUE TITLE
[8.0] Workflows for non loaded modules aren't disabled

### ISSUE THREAD

**Issue by llacroix** [odoo/odoo#5699]
Odoo loads any workflow it finds in the database even though the modules that created any part of the workflows might not be loaded in memory.

During tests, it is possible that workflows will be executed while loading demo data. After loading a python module, odoo load its data/demo and so on. It does that for each python module following dependency order.

In some rare case, a workflow could call a method that doesn't exist on the inital model during an on_create activity. The activity will fail with an error because the attribute in the "python function" workflow won't exist yet on the base model. Then odoo raises an error and tests fails because they are trying to call a method that is added by a module that isn't yet loaded.

How to reproduce:

Create a model Foo in module A
Add demo data for model Foo in module A

Extend model Foo in module B
Add a new method named bar() to Foo in module B
Add a workflow on_create to Foo and make it call method bar()
Add A as dependency to B

Install A and B
Run tests that will load demo data from A

Results:
The workflow added in B are going to get executed when creating a Foo object even though module B isn't yet loaded and method bar() doesn't yet exist in Foo.

Here's a fix, it could be better than that probably.
https://github.com/odoo/odoo/pull/5703

**Comment by Yenthe666** [comment]
Hi @llacroix,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
