### ISSUE TITLE
[8.0] Exhausted Stock, no results when searching products with qty_available = 0

### ISSUE THREAD

**Issue by franckbret** [odoo/odoo#5701]
On the product variant list view the two last columns are "Quantity on hand" and "Quantity available".
As they are function fields we can't click on their header column to do a sort on quantity. 

So I try with advanced search on latest 8.0 runbot instance with demodata. 

1. I want to see all the product variants where "quantity on hand" is equal to 0 -> no result
2. I want to see all the product variants where "quantity on hand " is less than 1 -> no result
3. I want to see all the product variants where "quantity on hand" is greater than 1 -> results

Obviously 1 and 2 should returns result as there are some products with "quantity on hand" = 0

Also, using the pre-defined filter 'Exhausted Stock' which should returns qty_available<=0 doesn't return any results.

Here are some screen captures from runbot v8 showing the no results problem...

![capture du 2015-03-11 12 46 01](https://cloud.githubusercontent.com/assets/91384/6595687/c9be9218-c7ec-11e4-9240-a8d8a2492562.png)
![capture du 2015-03-11 12 44 39](https://cloud.githubusercontent.com/assets/91384/6595688/c9bee902-c7ec-11e4-8220-c06eb8c69f2e.png)

**Comment by jco-odoo** [comment]
Thx.
