### ISSUE TITLE
Website Theme Notes: missing building block "Team Profiles"

### ISSUE THREAD

**Issue by treviser** [odoo/odoo#5707]
Please make also a building block for team profiles available.

**Comment by exidoncom** [comment]
Yes please, also put the information ,that you have to look for module in about-us page anywhere (for example module description). Anyone knows howto add building block manually?

**Comment by Yenthe666** [comment]
Hi @treviser,

Thank you for your suggestion. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
I'll label it wishlist so it keeps popping up.

Regards,
Yenthe
