### ISSUE TITLE
error 400 on HEAD request to json controller

### ISSUE THREAD

**Issue by yelizariev** [odoo/odoo#57133]
Impacted versions: tested in 12, but other should have the same behavior

Steps to reproduce:

* make a controller with ``type='json'``
* send HEAD request without headers

Current behavior:

* error 400

Expected behavior:

* response with code 200
----------------
I faced this problem on trying make integration with trello: https://developer.atlassian.com/cloud/trello/guides/rest-api/webhooks/

> The second requirement for a webhook is a callbackURL parameter. When a model with a webhook changes, the update is fired via an HTTP POST request from Trello to the URL provided. The body of the post will be a JSON payload of the action (the action that changed the model), and the updated model. It may be helpful for you to add your own parameters to the callbackURL if you’ll be using multiple webhooks, such as
> 
> https://mycallback.com/trelloCallbacks/?memberID=14&mainModel=true
> 
> The provided callbackURL must be a valid URL during the creation of the webhook. **We run a quick HTTP HEAD request on the URL, and if a 200 status code is not returned in the response, then the webhook will not be created**. Additionally, if your callbackURL contains an invalid SSL certificate the webhook will not be created (no SSL certificate will not cause the creation to fail).

-----------------
This issue is similar to https://github.com/odoo/odoo/issues/55617, but I decided to open a new one:

* I'm getting error 400 rather than 404
* I have specific example of third-party service
* I'd lilke to suggest more general solution: what about using not a HttpRequest by default, but the one specifed in ``type`` attribute? This should solve this specific issue, but also some other similar ones

  https://github.com/odoo/odoo/blob/467208f6e4d20997836e07a350e57b0a5ae482df/odoo/http.py#L1363-L1368

**Comment by Yenthe666** [comment]
@JKE-be

**Comment by lem8r** [comment]
Bump.

Selecting `JsonRequest` by `"application/json"` mimetype basically blocks integration with external services having plain json requests. There is no way to handle it with `type='http'` controller and return plain json response without wrapping it in RPC body.

@JKE-be is there any workaround to handle JSON post requests and issue JSON responses? I mean not JSON-RPC type.

**Comment by yelizariev** [comment]
@lem8r, I'm not sure that your question relates to this issue, but for pure JSON requests, you can check openapi module, which adds new ApiJsonRequest class

https://github.com/itpp-labs/sync-addons/blob/c669dbbe9951b1c4f722a7ef5644dfbead2d4b06/openapi/controllers/apijsonrequest.py#L230-L242

**Comment by lem8r** [comment]
@yelizariev Right, my question is not related to HEAD requests but more about handling plain json requests/responses in general.

Thanks for the tip. Sure we can solve it with yet another monkey-patch. But it seems like common requirement that should be supported out of the box.

**Comment by yelizariev** [comment]
You may need to open new issue or even a PR

**Comment by lem8r** [comment]
Yep, sorry for off-topic.

**Comment by yelizariev** [comment]
There are two possible solutions for this:
* don't raise an error https://github.com/odoo/odoo/pull/71622
* add `type='*'` https://github.com/odoo/odoo/pull/45367

**Comment by yelizariev** [comment]
The issue seems obsolete in v16. See  https://github.com/odoo/odoo/commit/034d01b2f36609297fd5af3bceb28ee7066ccc77 and https://github.com/odoo/odoo/pull/78857
