### ISSUE TITLE
Payment form should allow especifying form method.

### ISSUE THREAD

**Issue by muniter** [odoo/odoo#57130]
Impacted versions:
13.0, 12.0

Steps to reproduce:
Try setting a 'get' method for the form.

Current behavior:
There's no way by passing arguments, since [it's hardcoded](https://github.com/odoo/odoo/blob/0415da51960819ec9c989e15a9229bd6d583ba1b/addons/payment/static/src/js/payment_form.js#L287)

Expected behavior:

Ideally one should be able to change the method with the passed form like the `action_url` like is done [here](https://github.com/odoo/odoo/blob/0415da51960819ec9c989e15a9229bd6d583ba1b/addons/payment/static/src/js/payment_form.js#L291). Something like:

```javascript
// Current behavior
newForm.setAttribute("method", "post"); // set it to post

// Proposed Behavior
var form_method = $(newForm).find('input[name="data_set"]').data('formMethod'); || "post"
newForm.setAttribute("method", form_method); // set it to post
```

Recently I created a module for a Colombian payment provider named [Wompi Colombia](https://docs.wompi.co/docs/en/widget-checkout-web) and they use the common method of sending some data in a form and they take of processing the payment, but as a change, they wanted the data as a 'get' method instead of the typical 'post'. This should be really easy to do in Odoo by just sepcifying the method in the form, but Is hardcoded as seen [here](https://github.com/odoo/odoo/blob/0415da51960819ec9c989e15a9229bd6d583ba1b/addons/payment/static/src/js/payment_form.js#L291).

So instead had to overwrite the `payEvent` method to check if using `wompicol` and call a custom `WompiColPayEvent` which is exactly the same but changing the line were the method is defined to 'get'.

**Comment by pedrobaeza** [comment]
Sorry, but you are trying to modify current features, so this is not an issue. You can propose an improvement, but only for master branch.

You can ask on forums about possible techniques for getting what you need. One quick tip: create your own controller.

Closing then as stated.
