### ISSUE TITLE
As admin with group Administration Settings, I cannot change the password of a user => Validation Error

### ISSUE THREAD

**Issue by jcdrubay** [odoo/odoo#57149]
**Impacted versions:**
saas-13.5

**Steps to reproduce:**
As admin with group Administration Settings, I cannot change the password of a user

**Current behavior:**
I get this error
The operation cannot be completed:
- Create/update: a mandatory field is not set.
- Delete: another model requires the record being deleted. If possible, archive it instead.

Model: User, Change Password Wizard (change.password.user), Field: User (user_id)

**Expected behavior:**

Be able to force the change of password

**Video/Screenshot link (optional):**

![image](https://user-images.githubusercontent.com/1765420/92363965-8ae71600-f11c-11ea-9967-2ec814ee8129.png)

**Comment by pedrobaeza** [comment]
`master` is no longer v14. It's `saas-13.5`. Please don't report issues on master. Due to the close of release date, issues found on `saas-13.5` can be accepted.

**Comment by jcdrubay** [comment]
@pedrobaeza Same issue happens on saas-13.5

![image](https://user-images.githubusercontent.com/1765420/92375427-44e57e80-f12b-11ea-963a-22060bf5f4d5.png)

**Comment by jcdrubay** [comment]
@pedrobaeza I updated the version in the description of the issue. Can you re-open the issue?

**Comment by pedrobaeza** [comment]
OK, then that can be considered as bug for upcoming v14. @mart-e, does it seem some missing ACL for this transient?

**Comment by mart-e** [comment]
> Due to the close of release date, issues found on saas-13.5 can be accepted.

Please note that it's still a development version that is not yet released, so expect bugs and quick changes.

> does it seem some missing ACL for this transient?

Looks like a missing `user_id` value, probably linked to recent changes at #55995 (cc @rco-odoo )

**Comment by jcdrubay** [comment]
@mart-e thanks for taking this into account. I don't expect anything except the hope of helping you make Odoo greater :)

**Comment by Feyensv** [comment]
This should probably be fixed by https://github.com/odoo/odoo/pull/57922 ;)

**Comment by pedrobaeza** [comment]
Closing as probably solved by #57922
