### ISSUE TITLE
[13.0] Marketing Automation

### ISSUE THREAD

**Issue by gediminasvenc** [odoo/odoo#57144]
Impacted versions: 
13.0 EE, 13CE - untested

Steps to reproduce:
Create new campaign in Marketing Automation
![image](https://user-images.githubusercontent.com/19407260/92360271-37ad9d00-f0f5-11ea-8841-243a6a9941e7.png)
Add new activity:
![image](https://user-images.githubusercontent.com/19407260/92360415-6deb1c80-f0f5-11ea-9314-f60672f3d4df.png)
Launch a test:
![image](https://user-images.githubusercontent.com/19407260/92360539-a3900580-f0f5-11ea-921b-d5c5fca3231b.png)
Run it:
![image](https://user-images.githubusercontent.com/19407260/92360563-af7bc780-f0f5-11ea-8963-3ebd1ac40d5e.png)
Go back into campaing and edit it:
![image](https://user-images.githubusercontent.com/19407260/92360627-cde1c300-f0f5-11ea-8ef6-b05c7ea49b53.png)
Pick new email template and save:
![image](https://user-images.githubusercontent.com/19407260/92360664-e225c000-f0f5-11ea-9906-e004095237a4.png)
Launch a test again:
![image](https://user-images.githubusercontent.com/19407260/92360711-f1a50900-f0f5-11ea-83d7-7ed088a3b089.png)
Press run button:
![image](https://user-images.githubusercontent.com/19407260/92360743-fff32500-f0f5-11ea-9d1b-6b5d34659571.png)
You will see this error message:
![image](https://user-images.githubusercontent.com/19407260/92360790-113c3180-f0f6-11ea-95d2-22b7fe89b542.png)

Current behavior:
Gives an error if email template is changed after tracking links are generated from the first email template.

Expected behavior:

Video/Screenshot link (optional):

Link to a runbot campaign - https://4093058-13-0.runbot50.odoo.com/web?debug=1#id=3&action=507&model=marketing.campaign&view_type=form&cids=1&menu_id=378

**Comment by pedrobaeza** [comment]
As this is an enterprise module issue, please report it to odoo.com/help instead.
