### ISSUE TITLE
[13.0] account_intrastat report includes inventory valuation journal entries

### ISSUE THREAD

**Issue by paulius-sladkevicius** [odoo/odoo#57182]
Impacted versions: 

- 13.0 EE

Steps to reproduce:

1. Create a new invoice with a product that has: Costing Method = First In First Out (FIFO), Inventory Valuation = Automated
2. Set up an Intrastat Country for an invoice
3. Post Invoice
4. Review Intrastat Report

Current behavior:

- Includes journal entries related to inventory valuation

Expected behavior:

- Shows only journal entries related to a sold/bought product.

Video/Screenshot link (optional):

![2020-09-07 14-47](https://user-images.githubusercontent.com/213811/92385301-52463d00-f11a-11ea-9ade-2b3c95626177.gif)

**Comment by Yenthe666** [comment]
@paulius-sladkevicius why don't you report it with an official ticket? :)

**Comment by paulius-sladkevicius** [comment]
@Yenthe666 I do that by providing them with a link to an issue. I suppose it's better to report here first then at least others can find the same issue while on github enterprise you can't report issues at all.

**Comment by Yenthe666** [comment]
Okay so you do the same as me :) Yes it is good (although most people from Odoo don't like it) but can you then link the OPW here too please?

**Comment by paulius-sladkevicius** [comment]
I have a ticket reference number 2334835, not sure if it's OPW number.

**Comment by Yenthe666** [comment]
Yeah it is, thanks!

**Comment by oco-odoo** [comment]
Fixed here https://github.com/odoo/enterprise/pull/13415 . I'm closing this issue.
Thanks for the bug report! :)
