### ISSUE TITLE
Error on saving a many2one default in res_config

### ISSUE THREAD

**Issue by kirca** [odoo/odoo#5721]
``` python
from openerp.models import TransientModel
from openerp import fields


class SaleConfigSettings(TransientModel):
    _inherit = 'sale.config.settings'

    default_user_id = fields.Many2one(
        'res.users', 'Default Claim Responsible User', default_model='crm.claim')
```

```
Traceback (most recent call last):
  File "/home/kirca/oede_new/projects/walberg/odoo/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/kirca/oede_new/projects/walberg/odoo/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/home/kirca/oede_new/projects/walberg/odoo/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/kirca/oede_new/projects/walberg/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/kirca/oede_new/projects/walberg/odoo/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/kirca/oede_new/projects/walberg/odoo/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/home/kirca/oede_new/projects/walberg/odoo/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/home/kirca/oede_new/projects/walberg/odoo/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/kirca/oede_new/projects/walberg/odoo/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/kirca/oede_new/projects/walberg/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/kirca/oede_new/projects/walberg/odoo/openerp/addons/base/res/res_config.py", line 553, in execute
    ir_values.set_default(cr, SUPERUSER_ID, model, field, config[name])
  File "/home/kirca/oede_new/projects/walberg/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/kirca/oede_new/projects/walberg/odoo/openerp/addons/base/ir/ir_values.py", line 261, in set_default
    'value': pickle.dumps(value),
  File "/usr/lib/python2.7/pickle.py", line 1374, in dumps
    Pickler(file, protocol).dump(obj)
  File "/usr/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/usr/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python2.7/pickle.py", line 401, in save_reduce
    save(args)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/pickle.py", line 562, in save_tuple
    save(element)
  File "/usr/lib/python2.7/pickle.py", line 300, in save
    self.save_global(obj)
  File "/usr/lib/python2.7/pickle.py", line 748, in save_global
    (obj, module, name))
PicklingError: Can't pickle <class 'openerp.api.res.users'>: it's not found as openerp.api.res.users
```

Related question on forums:
https://www.odoo.com/forum/help-1/question/error-on-saving-a-many2one-default-configuration-settings-53017

**Comment by cysnake4713** [comment]
yes, got the same problem!

**Comment by jabbourb** [comment]
+1

Got the same error with Many2one field on 'res.currency'.
Is there a better way of doing this?

**Comment by tboulogne** [comment]
Hello,

Any solution to solve this ?

**Comment by pambudisatria** [comment]
+1
Got the same error.

**Comment by Yenthe666** [comment]
@mart-e I'm not sure about this one. What do you think about it?

**Comment by ydaniels** [comment]
no solution yet

**Comment by mart-e** [comment]
Hello,

Have you checked other examples of setting a default value for a many2one field? For instance [website_payment](https://github.com/odoo/odoo/blob/97da3b99b7eaa7eae9207f23b3c7b181ff358754/addons/website_payment/models/res_config.py)

**Comment by mart-e** [comment]
Closing as no issue in standard

**Comment by Fenkiou** [comment]
@mart-e I think you didn't understand the problem.

On [this line](https://github.com/odoo/odoo/blob/10.0/odoo/addons/base/res/res_config.py#L358) we can read that a field starting with `default_my_field` and with attribute `default_model=my.model` will set the value of `my_field` when creating a new record of `my.model`

But it seems that we cannot use this behavior for related fields.

It's not about getting default value in a config view, it's about setting default value for a many2one on a particular model.

Let's imagine you want a default `country_id` on `res.partner` without having to pass it to the context of each view that will be used for this model.

Please re-open, or leave it close (if like I guess, it's not feasible) but update the documentation.

**Comment by Gyuri77** [comment]
The problem appears when we put the default_model='x.y' attrib on the field definition.
account does not use this e.g.:
    default_sale_tax_id = fields.Many2one('account.tax', string="Default Sale Tax", help="This sale tax will be assigned by default on new products.", oldname="default_sale_tax")

but this means, that its not the default field value, because in res_config.py:

        for name, field in self._columns.items():
            if name.startswith('default_') and hasattr(field, 'default_model'):
                defaults.append((name, field.default_model, name[8:]))
            elif name.startswith('group_') and (isinstance(field, fields.boolean) or isinstance(field, fields.selection)) \
                 and hasattr(field, 'implied_group'):
                field_groups = getattr(field, 'group', 'base.group_user').split(',')
                groups.append((name, map(ref, field_groups), ref(field.implied_group)))
            elif name.startswith('module_') and (isinstance(field, fields.boolean) or isinstance(field, fields.selection)):
                mod_ids = ir_module.search(cr, SUPERUSER_ID, [('name', '=', name[7:])])
                record = ir_module.browse(cr, SUPERUSER_ID, mod_ids[0], context) if mod_ids else None
                modules.append((name, record))
            else:
                others.append(name)

        return {'default': defaults, 'group': groups, 'module': modules, 'other': others}

**Comment by Gyuri77** [comment]
@mart-e 

You linked  an example of the problem, not the solution. The standard odoo way does not work for many2one fields, because if you use the default_model attrib on the field as the documentation said, and the ir.values set_default function needs as you can see it in res.config, it gives you an ugly pickle error.

On your linked example, you see a workaround, which is not the odoo way of using default values. The odoo way is a simple field definition, the workaround is the 2 helper function, which simulates the res.config automations for default fields. You linked a workaround.

**Comment by mart-e** [comment]
@Gyuri77 thank you for the report, now I see your point. Indeed it was broken for relation fields.
We have fixed that in master at f5df7c60029d9496f82a67be13e6df43f1ff7c9f and 81352d47c5fd4f5b5c59a4614082510f2c05ca42. 
I will backport it.
you are running a 9.0 right?

**Comment by Fenkiou** [comment]
@mart-e Could you backport the fix on 10.0 too ?

**Comment by mart-e** [comment]
Yes, I backported to 10.0 at d7c248e3c05 (backporting to 9.0 is not possible as still using both API version)

**Comment by Gyuri77** [comment]
@mart-e 

Thank you for the answer and patches.
I use 9.0, so i use the  workaround you linked before.  We have a lot of time and code in 9.0 so we stay. The next project will be in 10 or 11 I hope.
