### ISSUE TITLE
[12.0] Change Password button with strange behaviour

### ISSUE THREAD

**Issue by nunosilvaarxi** [odoo/odoo#57272]
Impacted versions:
12.0

Steps to reproduce:
Login. In the top right-hand corner, go to "Preferences" and then go to "Change Password".
Current behavior:
Change Password button is semi-hidden behind the inputs.
Expected behavior:
Change Password button should be visible in that form.
Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/35144292/92495897-5c863b00-f1ef-11ea-98c5-5c7b9139fa90.png)

![update_password](https://user-images.githubusercontent.com/35144292/92495649-14ffaf00-f1ef-11ea-89e4-4ca75f2233aa.png)

**Comment by pedrobaeza** [comment]
As this is something with enterprise responsive theme, please report it instead in odoo.com/help.

**Comment by Yenthe666** [comment]
Seems to work okayish on the latest V12 build:
![image](https://user-images.githubusercontent.com/6352350/92498123-8729c100-f1fa-11ea-98dc-02df2b28da62.png)

But yes it is not 100% it seems.

**Comment by nunosilvaarxi** [comment]
> As this is something with enterprise responsive theme, please report it instead in odoo.com/help.

Ok thank you nonetheless.

**Comment by nunosilvaarxi** [comment]
> Seems to work okayish on the latest V12 build:
> ![image](https://user-images.githubusercontent.com/6352350/92498123-8729c100-f1fa-11ea-98dc-02df2b28da62.png)
> 
> But yes it is not 100% it seems.

Afaik, it depends on your screen resolution.
