### ISSUE TITLE
Function Field Many2many "store=True" are not computed during the creation of the field

### ISSUE THREAD

**Issue by JonathanNEMRY** [odoo/odoo#5729]
**Function Field Many2many ``store=True`` are not computed**

Impacted versions:

 - 8.0

Steps to reproduce:

1 Add two new fields  into a model `X` module `Y`
```
    @api.one
    @api.depends('Z')
    def _compute_field_m2m_ids(self):
        print 'will never pass here during creation of my field'

    field_m2m_ids = fields.Many2many(
        comodel_name='res.partner', relation='some_rel', string='M2M',
        compute='_compute_field_m2m_ids', store=True)

    @api.one
    @api.depends('Z')
    def _compute_field_char(self):
        print 'For type `char` and for other: pass here into the creation of the field'

    field_char = fields.Char(string='Char',
        compute='_compute_field_char', store=True)
```
 2 Update Odoo with a -u Y

**Current behavior:**

* field_char: its method is well called
* **field_m2m_ids: method is not called**

==> changing `Z` will trigger their respective methods just as it is wanted

**Expected Behavior:**

* field_char: its method is well called
* **field_m2m_ids: method is well called too**

==> changing `Z` will trigger their respective methods just as it is wanted

**Comment by JonathanNEMRY** [comment]
@rco-odoo do you have an idea about this one?

**Comment by JonathanNEMRY** [comment]
OPW 630330

**Comment by adrienpeiffer** [comment]
@rco-odoo Any news about this issue ?
