### ISSUE TITLE
send_email always uses SUPERUSER_ID?

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#5730]
model's `ir.mail_server` method use of `uid` as SUPERUSER_ID intended?..
I did an implementation of `send_email` method and needed to check which user sent email, but `self.env.uid` and `self.env.user` always return super user id (1) or superuser user (admin) - no matter who sends email. 

If user sends email from messaging, then I can catch his `uid` from context. But if user sends email for example from opportunity, then `uid` is not passed in context at all. And trying to get current `uid` always return admin's ID.

Is there a way to see who sent an email? Because now it shows that admin sent it, even though it did not.

Example in method itself:

    @api.model
    def send_email(self, message, mail_server_id=None, smtp_server=None, smtp_port=None,
                   smtp_user=None, smtp_password=None, smtp_encryption=None, smtp_debug=False):
        print self.env.context.get('uid') #if sent from messaging, returns it. If for example from opportunity, does not return it.
        print self.env.uid #always get ID `1`, does not matter who sends mail.
        print self.env.user # always get admin user. Does not matter who send mail.
        return super(ir_mail_server, self).send_email(message=message, mail_server_id=mail_server_id, smtp_server=smtp_server, smtp_port=smtp_port,
                   smtp_user=smtp_user, smtp_password=smtp_password, smtp_encryption=smtp_encryption, smtp_debug=smtp_debug)

**Comment by pvanthony** [comment]
Not sure if it is related. In the event module, it is also not picking up the object.user_id.email. Can anybody confirm this too?

**Comment by beledouxdenis** [comment]
This is indeed expected that the `send_email` method of the model `ir.mail_server` is always called as SUPERUSER_ID.

Anyway, the email queue is processed with a cron, with is processed as `SUPERUSER_ID`, so, indeed, this is perfectly normal.

The fact you can find the `uid` within the `context` is just luck. You shouldn't rely on that for your custom development.

There is nevertheless a way to know who send an email, but not overriding the `send_email` method of the model `ir.mail_server`. You should simply override the method `send` of the model `mail.mail`, and use the browse record of the mails sent (using the `ids` param from the method, e.g. `mails = self.browse(cr, uid, ids, context)`) and get the author from the `author_id` field of the mail.

**Comment by oerp-odoo** [comment]
But I the point of implementation is to use email server using `uid`. If I browse mails that were already sent, then there is nothing left to do.

**Comment by beledouxdenis** [comment]
I believe you do not haven't need any custom code to do that.

There is a field `mail_server_id` on the `mail.mail` model.

Therefore, I see as possible solution, without any custom code:
 - You create an automated action on model `mail.mail`, on creation, that change the field `mail_server_id` according to your need.

With custom code, even simpler:
 - You set the key `mail_server_id` in the `_defaults` dict according to your needs for the model `mail.mail`
 - You override the `default_get` method of model `mail.mail` and define the `mail_server_id` according to your need.

Clean and simple.

Notice that any mail is created before being send. There is no mail sent through `email_send` of model `ir.mail_server` without having it created in the `mail.mail` model before.

**Comment by oerp-odoo** [comment]
Thanks, I'll try that.

**Comment by pvanthony** [comment]
Just tried the following module and it seems to work. Just did the install and simple testing.
https://www.odoo.com/apps/modules/8.0/tko_mail_smtp_per_user/
