### ISSUE TITLE
[8.0][Regression]Installing module document failed

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#5732]
Hy,

I've tried to install the document module on the latest git pull.
I have this error :

```
Ceci est un syst\xe8me complet de gestion de documents.
===========================================
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/opt/odoo/odoo-git/openerp/netsvc.py", line 118, in format
    return logging.Formatter.format(self, record)
  File "/usr/lib/python2.7/logging/__init__.py", line 474, in format
    s = self._fmt % record.__dict__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 203: ordinal not in range(128)
Logged from file module.py, line 131
<string>:3: (WARNING/2) Title underline too short.
```

The module still in "update" mode.

I tried with an old git pull an it succeed.

3923f40 HEAD@{0}: pull: Fast-forward => Failed
9351415 HEAD@{1}: pull: Fast-forward => Succeed

I also tried in french an english and both of them are failing.

I think it could be considered as a bug

**Comment by flotho** [comment]
Additionnaly, the menus for browsing document is no more accessible.

**Comment by nono6677** [comment]
+1

**Comment by Yenthe666** [comment]
Hi @flotho,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
