### ISSUE TITLE
[master] Inventory adjustments can be deleted after validation

### ISSUE THREAD

**Issue by qtheuret** [odoo/odoo#5733]
**Inventory adjustments can be deleted after validation**

Impacted versions:
- master

Steps to reproduce:
1. create a new inventory adjustment
2. Choose 'One product only' and choose a product
3. Click on start inventory
4. Fill the quantity for this product
5. Validate the adjustment inventory
6. Try to delete the adjustment inventory

Current behavior:
- The adjustment inventory is deleted but the stock move are always here

Expected behavior:
- A message must be displayed to warn user that is not possible to delete an adjustment inventory.

**Comment by hbto** [comment]
I Don't think this is a bug,

because allowing cancelling/deleting a Stock Move, will introduce consistency data errores.

Best Regards.

**Comment by hbto** [comment]
I Withdraw my last statement, this is a bug, I have read it has to be possible to delete stock.move.

My apologies.

Best Regards.

**Comment by gurneyalex** [comment]
I am able to delete validated inventory adjustments in v8 (on runbot)

**Comment by aliomattux** [comment]
I came across this thread. I think the system should not be so restrictive and that you should be able to reverse an inventory adjustment. This functionality seems to be missing. This is different than just delete. In other standard ERP software you can reverse an adjustment. It's puzzling to a business owner/user for you to explain sorry you submitted this and its impossible to reverse or cancel it. Thats really silly

**Comment by Yenthe666** [comment]
Hi @qtheuret,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
