### ISSUE TITLE
UnicodeEncodeError during the visit of Tracked Link

### ISSUE THREAD

**Issue by tsabi** [odoo/odoo#5735]
Steps to reproduce:
- create a UTM Campaign with a non-latin character name. For example you can copy this text: "ÉŐÁ"
- create a Tracked Link for this campaign
- visit the shortened link
- you got an 500 internal error

```
  File "C:\oesrv_s6\lib\site-packages\odoo-8.saas_6-py2.7.egg\openerp\addons\website_links\models\website_links.py", line 103, in _compute_redirected_url
    self.redirected_url = '%s://%s%s?%s%s#%s' % (parsed.scheme, parsed.netloc, parsed.path, urlencode(utms), parsed.query, parsed.fragment)
  File "C:\Python27\Lib\urllib.py", line 1338, in urlencode
    v = quote_plus(str(v))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
```

**Comment by Yenthe666** [comment]
Hi @tsabi,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
