### ISSUE TITLE
[v8] Inconsistent CSV export from "Saved Exports"

### ISSUE THREAD

**Issue by richard-willdooit** [odoo/odoo#5736]
Choosing columns to export directly, or choosing a saved export, results in a different export.

Example:

Choose a product variant from the list view, choose **More > Export**

Select
- _Unit of Measure_ and **Add**
- _Supplier/Supplier_ and **Add**
- then **Save Fields List** giving it a name, and **OK**.

Note that _Import Compatible Export_ and _CSV_ options have not been changed.

When I click on **Export to File** I get columns for _id_, _uom_id/id_, and _seller_ids/name/id_, all with xml ids.

| id | uom_id/id | seller_ids/name/id |
| --- | --- | --- |
| **export**.product_product_3226 | **export**.product_uom_20 | **export**.res_partner_44 |

Now try again.  Go back to list view, choose **More > Export**
Pick the saved export from the list.
Note that _Import Compatible Export_ and _CSV_ options have still not been changed and are the same as before.

When I click on **Export to File** I get columns for _id_, _uom_id/id_ as before but the third column is _seller_ids/name_ with the proper name of the seller.

| id | uom_id/id | seller_ids/name |
| --- | --- | --- |
| **export**.product_product_3226 | **export**.product_uom_20 | ABC Corp |

**Comment by Yenthe666** [comment]
Hi @richard-willdooit,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
