### ISSUE TITLE
Calling with_context in overriding method leads to loop 

### ISSUE THREAD

**Issue by vuamitom** [odoo/odoo#5738]
Below code leads to infinite no. of calls to 'create'. The problem disappears when 'with_context' call is removed. 

``` python
class pos_category(models.Model):
    _inherit = 'pos.category'

   @api.model
    def create(self, data):
        r = super(pos_category,self).with_context(is_pos=True).create(data)
```

**Comment by guewen** [comment]
Correct call is

```
class pos_category(models.Model):
    _inherit = 'pos.category'

   @api.model
    def create(self, data):
        r = super(pos_category,self.with_context(is_pos=True).create(data)
```

**Comment by flotho** [comment]
:+1:

**Comment by Yenthe666** [comment]
Hi @vuamitom,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
