### ISSUE TITLE
Purchase Traceback

### ISSUE THREAD

**Issue by jat-odoo** [odoo/odoo#5739]
![puchase_traceback](https://cloud.githubusercontent.com/assets/7599689/6633447/a4e708c0-c96e-11e4-8337-4de98fe3ad63.png)

Occur in: 8.0, master

Reproduce Step:
---------------------
* Goto purchase
* Under Products label Products menuitem
* On a purchaseable product, there is a stat button "purchases"
* If you click on it, you get po lines
* If you click on the po line, you see the form view of the po line
* Click on create button

**Comment by bistaray** [comment]
I get a traceback with today's build on runbot clicking the Purchases button on the Product form.

Using Enterprise, the Developer Mode needs to be activate.  

![screenshot][http://i.imgur.com/cqakvRS.png]

http://110962-9-0-fe964d.runbot.odoo.com/web?debug=#min=1&limit=80&view_type=list&model=purchase.order.line&action=845&active_id=10:41
Traceback:
TypeError: dict.column.width is not a function
