### ISSUE TITLE
[master] TypeError: self.list is undefined by changing POS-User in running POS-Session

### ISSUE THREAD

**Issue by explanar** [odoo/odoo#5740]
The Error occurs by changing the user in a running POS-Session.

Server: Ubuntu 14.04 minimal.

**Comment by Yenthe666** [comment]
Hi @explanar,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
