### ISSUE TITLE
Lots of zombie chromium/chrome processes left after a test session

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#57403]
Impacted versions: 12.0, 13.0

Steps to reproduce:

1. Run tests that include tours.

Current behavior:

- Chromium processes are left in zombie status until odoo's parent PID exits: 
![2020-09-10_10-51](https://user-images.githubusercontent.com/973709/92714125-b43db700-f353-11ea-8cfc-473e6282161a.png)
- Possibly related to https://github.com/odoo/odoo/pull/45347?

Expected behavior:

- Chromium processes should get reaped immediately after they end.

@Tecnativa TT24972 @d-fence

**Comment by d-fence** [comment]
I cannot reproduce with Chrome. What is your chromium version ?

**Comment by Yajo** [comment]
Chromium 73.0.3683.75 built on Debian 9.8, running on Debian 9.13

**Comment by pedrobaeza** [comment]
@Yajo maybe provide a minimal docker-compose file + steps for easy reproducibility?

**Comment by Yajo** [comment]
Maybe @d-fence finds it easier to use his own dev env with that chromium version, but whatever he says...

**Comment by d-fence** [comment]
Well, I really like Docker, so if you provide a compose file, I can use it.
Otherwise I will try to reproduce locally.

**Comment by Yajo** [comment]
I tried to simplify it as much as possible for you, but you'll need some dependencies that you might want to install in a virtualenv. It's done for you so it's simpler:

```bash
# Prepare your env to avoid errors that have no relation with this bug
folder=$(mktemp -d)
cd $folder
python3 -m venv venv
source venv/bin/activate
pip install docker-compose invoke pre-commit
git clone -b 12.0-case_for_bug_odoo_odoo_57403 https://github.com/Yajo/doodba-devel.git
cd doodba-devel
# Download latest odoo code
invoke git-aggregate
# Actually run the tests
container=$(docker-compose run --rm -d odoo --stop-after-init -i website --test-enable)
# Inspect the processes inside the container as the test continues
watch -e docker container exec -it $container ps afuwwx
```

Once you reach the last command, it will display a live process list, similar to what `top` does. At some point you will be able to see some chromium processes being launched, for the tours. When they finish, you'll see something similar to:

![zombies](https://user-images.githubusercontent.com/973709/93328802-82799400-f81c-11ea-9cf6-8f6fb2286b2a.png)

Which shows the zombie plague.

---

Note 1: if you want to see the test logs while it goes, just get the container name (you see it in the 1st line of the above picture, but yours will be different) and run in another terminal `docker container logs -f $container`

Note 2: when you finish, don't forget to clean up: `docker-compose down -v`

**Comment by d-fence** [comment]
Ok, I was able to reproduce and I agree that they could be reaped immediately.
On the other hand, the get reaped once the parent Odoo process is finished.

**Comment by d-fence** [comment]
As the zombies PID's are reaped at the end of the Odoo process, it seems that there is no risk of exhausting the PID's.
A fix seems overkill and could cause more trouble or would waste more time resources that the actual problem of seeing a few zombie processes during the tests. See #57964 for more information.
Thanks for the report.
