### ISSUE TITLE
impossible d’accéder a certain liens odoo 13 sur la 2 eme base

### ISSUE THREAD

**Issue by anasdex** [odoo/odoo#57416]
Impacted versions:
odoo13 community 

Steps to reproduce:

hello  , sometimes   when i run  odoo  all is ok 
and sometimes for the unknown reason  when i  put the same  link   for my server i got like this image
![image](https://user-images.githubusercontent.com/71074126/92722216-27005f80-f35f-11ea-9737-330cc665dd74.png)
Current behavior:

so every time i see  link like that  i go to  change  the database name

and immidialty the screen become normal
![image](https://user-images.githubusercontent.com/71074126/92722631-c7ef1a80-f35f-11ea-8b67-22de4fd86014.png)
and i login to Naitconcept2  and it work
when it's done i disconnect and samply i log into  Naitconcept4 and it work 

Expected behavior:
i would like to know how i can fix that  that  , i mean connect to my server  and got the right screen  
![image](https://user-images.githubusercontent.com/71074126/92723396-e570b400-f360-11ea-8a8f-7d448a0b5d65.png)
Video/Screenshot link (optional):

and also sometimes  when am into Naitconcept4  i click into some links  like invoice item or create a user or see the content of a quote or any link , nothink happend 
i try  1,2,3....10 times and nothink happend
so i immidiatly disconnecte , reconnecte into database Naitconcept2  and go exactly in the same link  in database and i click on it . it work  et i go againe to database Naitconcept4 and re run the same link ans it work 

any have a solution of my probleme 
excuse my english also , thank you

**Comment by pedrobaeza** [comment]
Hi, sorry for being the bad guy telling you that this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/13.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).
