### ISSUE TITLE
`--stop-after-init` not honored when `--without-demo` is used

### ISSUE THREAD

**Issue by noteed** [odoo/odoo#5744]
Tested on a fresh Odoo 8. With the `openerp-server` script, using both `--stop-after-init` and `--without-demo`, the server doesn't stop after initialization. (`-d` and `-i` are used as required by `--without-demo`.)

**Comment by noteed** [comment]
The problem seems to be in the config parsing code, as this seems a possible workaround:

    sed -i -e 's/stop = config\["stop_after_init"\]/stop = True/' openerp/openerp/cli/server.py

I.e. the value in the `config` dictionary isn't correct when `--without-demo` is given, but correct otherwise.

**Comment by mart-e** [comment]
`--without-demo` requires an argument (probably `all` for all modules). The command should be `--without-demo=all --stop-after-init` and not `--without-demo --stop-after-init` (it the later case, it means "do not load demo data for the module "--stop-after-init")
