### ISSUE TITLE
[8.0] Some messages disappear on the tracker when active field becomes False

### ISSUE THREAD

**Issue by adrienpeiffer** [odoo/odoo#5746]
Hi,

Here, a scenario on runbot 8.0

Steps to reproduce
--------------------------

- Go on runbot 8.0
- Logon as admin
- Click on Sales Menu
- Click on Customer
- Open a partner
- Fill in all required field
- On the tracker, Click on Log an internal note
- Add a text and click on Log an internal note button
- Go on Settings, click on user and duplicate admin user.
- Log out and logon as the created user
- Go on sales, customer and open the modified customer.
- You can view admin's internal note
- Change active to False

Expected behavior
-------------------------
- No impact on messages

Current behavior
----------------------
- admin's internal note disappeared

Thanks !

**Comment by adrienpeiffer** [comment]
OPW 630295

**Comment by adrienpeiffer** [comment]
Any news about this one ?

**Comment by simongoffin** [comment]
Hello Adrien,

What do you mean by changing active to false?

**Comment by adrienpeiffer** [comment]
Hi Simon,

Thanks for your answer. I mean change the value of this field to False

**Comment by beledouxdenis** [comment]
Closed with 3bd29a348385dfaded8ff70240435b8c9ee89773.
