### ISSUE TITLE
 Deleted Validated Inventory Adjustment

### ISSUE THREAD

**Issue by emadgamal** [odoo/odoo#5748]
Could you help me to solve my issue That I have created Inventory adjustment and I have validated it ,  regardless for inventory adjustment create stock move .

After user has been deleted the  Validated Inventory adjustment could u help me to create any validation to prevent  deletion of Validated Inventory adjustment

**Comment by Yenthe666** [comment]
Hi @emadgamal,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
