### ISSUE TITLE
In mobile the Carousel doesn't play

### ISSUE THREAD

**Issue by TrejoCode** [odoo/odoo#57573]
Impacted versions: **13.00**

Steps to reproduce:
1. In structure add a Carousel
2. Set speed in 5s
3. See in a physical device like Android or IOS
4. Don't touch or interact with the Carousel
5.- **The Carousel doesn't play automatically** 

Current behavior:
**The Carousel doesn't play automatically in mobile** 

Expected behavior:
**When opening the website the carousel should start automatically**

Video/Screenshot link (optional):
https://youtu.be/UoD24aXHDU0

It's a bug, configuration or default behaviour? 🤔

**Comment by pedrobaeza** [comment]
There's no access to the video file, but I would say this can be on purpose for not data consuming.

**Comment by TrejoCode** [comment]
> There's no access to the video file, but I would say this can be on purpose for not data consuming.

Sorry, i changed it, now is in youtube.

**Comment by pedrobaeza** [comment]
@JKE-be is this something done on purpose?

**Comment by bmachat** [comment]
Hi, Any way to make it start automatically ?

**Comment by TrejoCode** [comment]
> Hi, Any way to make it start automatically ?

It's seems that Odoo is bussy on Oddo 14, because 20 days have passed,

Thanks Odoo.

**Comment by pedrobaeza** [comment]
Yes, they are busy, and there's any obligation of answering in any time. If you have an enterprise contract, then you can put a ticket in odoo.com/help and make sure it will get an answer in the SLA time.

**Comment by xO-Tx** [comment]
Hello @TrejoCode 
Actuelly in v12.0 it was an autoplay, but we decided to keep the default bootstrap behaviour for this snippet : (cycling starts once the user finished interacting with the carousel [hover/touchend]).
You can get the "autoplay on load" behaviour by :
- Adding the data-ride="carousel" to the carousel template in website editor.
- Overriding the widget javaScript initialization to set {ride: 'carousel'} in your .carousel() method :)

**Comment by TrejoCode** [comment]
> Hello @TrejoCode
> Actuelly in v12.0 it was an autoplay, but we decided to keep the default bootstrap behaviour for this snippet : (cycling starts once the user finished interacting with the carousel [hover/touchend]).
> You can get the "autoplay on load" behaviour by :
> 
> * Adding the data-ride="carousel" to the carousel template in website editor.
> * Overriding the widget javaScript initialization to set {ride: 'carousel'} in your .carousel() method :)

Works as expected, thank you.
