### ISSUE TITLE
[13][FIX]['hr_skills']: Return widget to re-use

### ISSUE THREAD

**Issue by RishabhJadia** [odoo/odoo#57589]
@aab-odoo @mart-e @hmo-odoo 
Return widget so that it's easy to inherit rather than rewrite the whole code and creating the new one for inherit the widget
https://github.com/odoo/odoo/blob/4ecefad09c0f6bc3ffe3536a3ef7b20c7d2058dd/addons/hr_skills/static/src/js/resume_widget.js#L238

```
return {
    FieldResume: FieldResume,
    SkillsRenderer: SkillsRenderer,
    AbstractGroupedOne2ManyRenderer:AbstractGroupedOne2ManyRenderer
};
```

**Comment by aab-odoo** [comment]
Same as https://github.com/odoo/odoo/issues/57590
