### ISSUE TITLE
[8.0] Binary download file don't work correcty at list view

### ISSUE THREAD

**Issue by alca259** [odoo/odoo#5758]
Hello,
In form view a binary field appear as a link to download the file, if you click it, the download have the correct name.
But when you click in the download link in list view (in a relation of one2many with ir.attachment), the download have generic name without extension.

I tested it with the today version of Odoo.

![image](https://cloud.githubusercontent.com/assets/3340608/6653889/cba50f04-caa2-11e4-836e-ad45b076d932.png)

**Comment by Yenthe666** [comment]
Hi @alca259,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
