### ISSUE TITLE
How to set over one QTY has discount in ecommerce?

### ISSUE THREAD

**Issue by leiw324** [odoo/odoo#57593]
Impacted versions: Odoo 13.0

Steps to reproduce: Sorry, this is not bug, but I don't know where to set over one QTY has discount.

Current behavior: I am try demo data, the Customizable Desk (CONFIG) has this discount

Expected behavior: I just wants to know where to setup this discount.

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/33790160/93020427-8c7a7780-f60f-11ea-8b1f-2397a63bb544.png)

![image](https://user-images.githubusercontent.com/33790160/93020432-94d2b280-f60f-11ea-9236-03238dfd750b.png)

**Comment by nhomar** [comment]
Can you make this question in help.odoo.com? 

Thanks in advance for your understanding.

**Comment by leiw324** [comment]
Hello,

I tried many time,  I can't post in help.odoo.com

![image](https://user-images.githubusercontent.com/33790160/93080307-1124ce80-f6c0-11ea-86df-3bc849eff26f.png)

**Comment by leiw324** [comment]
Can someone help why 403? thanks
