### ISSUE TITLE
[13][FIX]['website_slides']: Return widget to re-use 

### ISSUE THREAD

**Issue by RishabhJadia** [odoo/odoo#57590]
@aab-odoo @hmo-odoo @mart-e 

Return widget so that it's easy to inherit rather than rewrite the whole code and creating the new one for inherit the widget

https://github.com/odoo/odoo/blob/4ecefad09c0f6bc3ffe3536a3ef7b20c7d2058dd/addons/website_slides/static/src/js/slide_category_one2many.js#L181

```
return {
    SectionListRenderer: SectionListRenderer,
    SectionFieldOne2Many: SectionFieldOne2Many
}
```

**Comment by aab-odoo** [comment]
Hello @RishabhJadia 

We can't change that in stable as it is a breaking change. However, I agree that we should always return Widgets defined in the closure to ease customizations. That being said, you can access it from the FieldRegistry: `FieldRegistry.get('slide_category_one2many')`

Regards.
