### ISSUE TITLE
[8.0] _inherits more than 1 level --> wrong table alias used in read

### ISSUE THREAD

**Issue by comaxime** [odoo/odoo#5761]
Following commit #5549 (04-Mar. 2015), an error happens when reading fields of objects with more than 1 levels of _inherits

For example: Z _inherits Y, Y _inherits X
when reading a field of X, from object Z:

ProgrammingError: invalid reference to FROM-clause entry for table "X"
HINT:  Perhaps you meant to reference the table alias "alias_X".

**Comment by norlinhenrik** [comment]
This is a problem for me too. Is there any progress to fix this bug?

**Comment by sakvith** [comment]
Yes, this error still exist, modules that _inherits 'product.product' stopped working. Had to remove all nested fields and use reference field until issue is fixed.

**Comment by GeluB** [comment]
Did it get fixed ? I am waiting for this commit to be fixed so i can update the Odoo server.

**Comment by emiprotechnologies** [comment]
Hi, I might find fix for this issue.
can any one looking into it ? How can I give you this fix for review ?
thanks for your support.

**Comment by GeluB** [comment]
You could send a pull request

**Comment by richard-willowit** [comment]
Please! Is this going to be merged!
