### ISSUE TITLE
[8.0]Procurement make_po function issue

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#5762]
Hi,

As for version 8, there's an improvement on procurement, when the procurement make a PO creation, if there's a PO that has same supplier it will merge automatically.
But this behavior can be not wanted by some case.
So this function (make_po), in purchase module, must be flexible enough to override.
Right now the function is very hard to modify the behavior, it must be override completely which is a bad practice.

Please change it, like when we want to search available_draft_po_ids,
we can split it on different function, like def find_available_draft_po_ids.
and called it when we want to define that attribute on make_po function.
So on that way, we can modify the behavior easily.

Thank You.

**Comment by lukebranch** [comment]
@falinwa ,

Thank you for your email on the community list.

@odony ,

I'm sorry to ping you on this, if you are too busy please ignore it.

I would like to know for Version 9.0 (and perhaps even for 8.0) if there is any way to switch off the auto-merging of PO's to the same vendor.

Basically when a customer orders and confirms a sale order:

SOXXX (eg. SO123)

i'd like this SO to generate an RFQ only for that SO:

POXXXXX (eg. PO12345)

the next customer that comes along (or indeed the same customer) and orders with a new SO should generate another RFQ so the relationship between SO and RFQ is always 1:1.

We have a number of businesses in Hong Kong that operate in this manner, and @falinwa has also mentioned he has a number of customers in China/APAC that also require this behaviour.

Is there any way to disable this feature in Odoo 8.0/9.0 without over-riding core code ('make_po' method) in the purchasing module?

**Comment by Yenthe666** [comment]
Hi @falinwa,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
