### ISSUE TITLE
ldap authentication fails if binding as anonymous

### ISSUE THREAD

**Issue by Julien-Blanc** [odoo/odoo#5763]
If using ldap authentication, binding with anonymous dn, ldap authentication fails with « intrenal server error ».

Problem comes from:
File "/usr/lib/python2.7/dist-packages/openerp/addons/auth_ldap/users_ldap.py", line 144, in query
    conf['ldap_password'].encode('utf-8') or '')
AttributeError: 'NoneType' object has no attribute 'encode'

Since conf['ldap_password'] is not defined, it has no 'encode' method.

It should be fixed in a way like:

    ldap_password = ''
    if conf['ldap_password'] != None:
        ldap_password = conf['ldap_password'].encode('utf-8')
    conn.simple_bind_s(conf['ldap_binddn'] or '', ldap_password)

**Comment by slu-010101** [comment]
Same here is there a workaround?
