### ISSUE TITLE
[8.0] Taxes and prices missing in invoice of an incoming picking without purchase order

### ISSUE THREAD

**Issue by pablocm-aserti** [odoo/odoo#5767]
Invoicing an incoming picking with no purchase order results in an invoice without taxes nor prices.

Impacted versions:
8.0

How to reproduce:
Install stock, account and purchase
Create an incoming picking, change "Invoice control" in "Additional Info" to "To Be Invoiced".
Transfer the picking and create invoice.

Current behaviour:
An invoice without taxes and prices set to 0 is generated.

Expected behaviour:
A proper invoice with taxes and prices is generated.

**Comment by cliffkujala** [comment]
The taxes are also missing from invoices created from manually created delivery order directly in warehousing (AKA: transfer out from stock which does not come from a quotation/sale order).

**Comment by Yenthe666** [comment]
Hi @pablocm-aserti,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
