### ISSUE TITLE
Segfult ERROR many time and server get crashed 

### ISSUE THREAD

**Issue by sandeepksrana** [odoo/odoo#5768]
Hi 
Have you faced a issue (Segfult error on io.tree in Linux), because of this, Odoo server get crash. I find this in SE (google etc) but everything is ok in my system according to search. more RAM and ROM even more then 6 GB remaining free. It is a Debian system. Why this happen since odoo 8 it was nothing happen to odoo 7.

Please reply me if you have anything know about it 

Thanks
Sandeep

**Comment by k4rtik** [comment]
Is this still an issue?

**Comment by odony** [comment]
Sorry, that's not enough information for us to help. Segfault problems are most likely hardware issues or problems with your Python environment or packages.
