### ISSUE TITLE
Website module with Bootstrap tooltip encoding issue with weird circumstances.

### ISSUE THREAD

**Issue by yannprada** [odoo/odoo#5776]
Hi ! I'm in Odoo (v8).

I've created a module, which display some pages in the front-end.

The issue is, in one specific case, the first page will not show and throw an error. The error is:

    QWebException: 'ascii' codec can't decode byte 0xc3 in position 89: ordinal not in range(128)

The weird thing is that the issue only appear on my remote server (not on localhost), only with registered users (not visitors).

And this seems to be the text displayed by the Bootstrap's tooltip widget that I use in my template, that is causing the issue.

My template code where the tooltip is defined looks like this:

    <t t-foreach="shape_category.shape" t-as="shape">
        <button class="btn btn-default btn-submit col-md-2"
                data-toggle="tooltip"
                t-att-data-original-title="shape.name"
                t-att-shape_id="shape.id"
                t-field="shape.image"
                t-field-options="{
    &quot;widget&quot;: &quot;image&quot;, &quot;class&quot;: &quot;img-rounded&quot;
                }"/>
    </t>

When I remove the line:

     t-att-data-original-title="shape.name"

or when I replace shape.name with something else, I don't have this error. Also, if I remove the shapes with names which have non ascii characters, that works.

But then, why does my module works fine in local, not in remote server ? And why with registered users, like admin, it throws this error, and not with unregistered ones ?

Some help/hints ?

**Comment by rruebner** [comment]
Hi,

it looks like "shape.name" uses special characters like ä, ö or ü which causes the trouble in your attribute "data-original-title". If thats the problem either you look that you use the right encoding for your page on the remote server or you don't use special characters.

Regards, Robert

**Comment by yannprada** [comment]
This issue is caused by the version of Odoo I have on my remote server. So, since the version I use on my local computer is less old, that explain why this issue happened on the server and not on localhost. Problem solved.
