### ISSUE TITLE
[8.0] [account_anglo_saxon] Wrong Creditor Price Differences when Using Different UoMs

### ISSUE THREAD

**Issue by michaeljohn32** [odoo/odoo#5777]
It appears that the _anglo_saxon_purchase_move_lines function does not work correctly for calculating the unit cost when different uoms are used between the move_line and the invoice line.

To reproduce:
Config: account_anglo_saxon, generate invoices on PO Lines
1. Configure a product with:
   -- 'inch(es)' for the default uom
   -- stock input and output accounts
   -- real-time inventory valuation
2. at the category level, encode a price difference account
3. Purchase the product from a supplier at 200ft with a unit price of $7.30 per foot. ($.6083333 in default uom)
4. Receive the products into warehouse (2400 inch(es))
5. Generate a Supplier Invoice (on PO Line)
6. Validate the invoice
7.  View the accounting journal entries:
   A/P: Credit - $1460.00
   Price Difference Acct: Debit - $1338.33
   Price Input Acct: Debit - $121.67

Expected accounting entries:

A/P: Credit - $1460
Price Input Acct: Debit - $1460

**Comment by dsabrinarg** [comment]
@michaeljohn32 FYI issue solved by Odoo on the following [commit](https://github.com/odoo/odoo/commit/a5f186c1580b7a67cbf7c2d929533a7b06e144b6)

**Comment by Yenthe666** [comment]
Indeed - this was fixed at https://github.com/odoo/odoo/commit/a5f186c1580b7a67cbf7c2d929533a7b06e144b6
