### ISSUE TITLE
Purchase & Inventory Administrator cannot use the button "Receive Products": Access Error on 'Action Window'

### ISSUE THREAD

**Issue by jcdrubay** [odoo/odoo#57780]
Impacted versions:

saas-13-5

Steps to reproduce:

- Create an internal user who is administrator for both Purchase and Inventory
- Login with that user
- Open a Purchase order
- Click on the button "Receive Products"

Current behavior:

```
Access Error
×
You are not allowed to access 'Action Window' (ir.actions.act_window) records.

This operation is allowed for the following groups:
	- Administration/Settings

Contact your administrator to request access if necessary.
```

Expected behavior:

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/1765420/93292860-c6ff3280-f810-11ea-90d7-4aa1d360241f.png)

**Comment by Yenthe666** [comment]
@amoyaux bug in upcoming V14

**Comment by sswapnesh** [comment]
Has been fixed in https://github.com/odoo/odoo/pull/57834
