### ISSUE TITLE
Allow selection_add to add a value in the middle.

### ISSUE THREAD

**Issue by obayit** [odoo/odoo#57787]
Impacted versions:
10.0, 11.0, 12.0, 13.0
Steps to reproduce:
`selection_add` appends the new value to the end. In case of needing to add a new state in the middle, this
 will not work. the developer will have to override the entire selection array (of states).
Current behavior:
It is not possible to add a state in the middle without ugly overriding.
Expected behavior:
It should be possible.

**Comment by pedrobaeza** [comment]
Yes, it is possible already, although not well documented:

https://github.com/odoo/odoo/pull/46325#issuecomment-600672217
