### ISSUE TITLE
Procurement does not consider the sequence and the line choice

### ISSUE THREAD

**Issue by ybofr** [odoo/odoo#5779]
I have tested this on runbot v8.

I have a product with 2 possible routes: make2order and buy. I have set the make2order route at sequence 20 and the buy at sequence 10.

When i create a sales order, it does not matter what I put in the route, the make2order is always selected. So, I choose the route Buy, but the system forces a make2order.

First, I was expecting to have the first in the sequence chosen automatically, second, I do not understand why the system is overruling me, making the choice effectively impossible.

Thanks for any correction

Eva P:

**Comment by jco-odoo** [comment]
Buy and mto are routes applied on different locations, so it does not need to choose based on the sequence.  If you want to buy from the customer location, look into dropship.

**Comment by ybofr** [comment]
This is absolutely incorrect.
I want to be able to choose if I purchase specifically for a customer or if I purchase to stock. This has NOTHING to do with dropship. In the dropship process, the delivery is done from the supplier to the customer.  In the make2order, I receive the goods in stock and deliver it myself. So, I NEED to be able to choose.

And by the way, it was working perfectly in V7.

Regards
Eva P.

**Comment by jco-odoo** [comment]
You put the product not as MTO and then you can define it on the sale order
line.  MTO should have higher priority than ship only.
