### ISSUE TITLE
"Wrong Tax Calculation in case Excise and VAT inclusive in Price"

### ISSUE THREAD

**Issue by girishsomaiya** [odoo/odoo#5784]
Impacted Ver 

Odoo 8.0

Steps to reproduce

Create a Product with Cost Price as 500.00 
Create Tax for Excise @ 12.36% (Excise 12%, Child Tax: (1) Education Cess 2%, (2) Higher Education Cess 1%) inclusive Tax and Included in Base Amount 
and VAT @ 12.5% Inclusive in Tax and not Included in Base Amount

Create the Purchase Order for this Product first add only Excise and see the calculation and then add VAT and see the claculation:

Case 1:  Excise Tax Inclusive

Education Cess 2% (Not included in Price and not included in Base Amount Sequence 2)

Higher Education Cess 1% (Not included in Price and not included in Base Amount Sequence 2)

Excise 12% (included in Price and included in Base Amount Sequence 1)

Cost Price 500.00 INR

Current Calculation: 

Net Total                500.00

Sub Total               444.87

Excise                     53.57

Edu Cess                  1.04

H.Edu. Cess              0.52

Total                      500.00

The Calculation is wrong, it should be as below:

Expected Calculation:

Net Total                500.00

Sub Total               445.00

Excise                     53.40

Edu Cess                  1.07

H.Edu. Cess              0.53

Total                      500.00

Case 2 when we have Excise and VAT Inclusive.

Education Cess 2% (Not included in Price and not included in Base Amount Sequence 2)

Higher Education Cess 1% (Not included in Price and not included in Base Amount Sequence 2)

Excise 12% (included in Price and included in Base Amount Sequence 1)

VAT @ 12.5% (included in Price and not included in Base Amount Sequence 10)

Current Calculation: 

Total Amount         500.00

Sub Total               389.31

Excise                      53.57

Edu Cess                   1.04

H.Edu Cess                0.52

VAT                           55.56

Net                          500.00

This is wrong, calculation, it should be as below:

Expected Calculation:

Total Amount           500.00

Sub Total                  395.55

Excise                         47.47

Edu Cess                      0.95

H.Edu Cess                  0.47

VAT                             55.56

Net                            500.00

Please check and revert.

**Comment by Yenthe666** [comment]
Hi @girishsomaiya,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
