### ISSUE TITLE
[8.0] Computed field with store=True not saved to database.

### ISSUE THREAD

**Issue by vak0160** [odoo/odoo#5786]
Affected version:
odoo v8 git b6a528fbf092ef62746772f6d8324917ad38b4f4

How to reproduce:

1. Create a model with a computed field with store=True.
2. Create a new data on that model.
3. Got <code>NULL</code> on database for the computed field.

Extra:

1. A computed field with <code>store=False</code> is working fine.
2. A computed field with <code>store=True</code> always getting its value from database, which is <code>NULL</code>.
3. Editing also won't save the computed field.
4. For now I only tested it with <code>Float</code> field and <code>Datetime</code> field.
5. I use <code>@api.one</code> for the method.

**Comment by JonathanNEMRY** [comment]
Hi @vak0160,
I noticed this behavior too.
Into the odoo v7, computed field `store=True` was computed by any modification on the record.
Now to reproduce this previous use case with new api; An `api.depends(some fields)` is required to trigger associated method. Although I think this is not anymore the same behavior, this is currently the only way to set a stored field. (it is like into v7, a trigger was required in any cases)

Unfortunately this do not work for every type of fields...https://github.com/odoo/odoo/issues/5729#issuecomment-78537534

**Comment by vak0160** [comment]
@JonathanNEMRY, 
thanks for the reply, using the <code>@api.depends</code> works. Is this the normal behaviour or just a bug?

**Comment by rco-odoo** [comment]
@JonathanNEMRY this is not a bug. A computed field should have dependencies. The fields to recompute are recognized as the ones having dependencies.

**Comment by JonathanNEMRY** [comment]
So it is indeed a change from the V8. It is clearer now.
thanks for your answer @rco-odoo

**Comment by Danisan** [comment]
suppose I had to compute the stock of a product, making a sum of ins and outs from stock_move... it does not have dependencies, or the dependency is from another object, or actually in this example, the dependency is from a sum from another object..(moves) how to establish a dependency in this case? May I make this function depend from (what)?
