### ISSUE TITLE
[8.0] journal item amount from goods receipt is incorrect for both standard and average costing

### ISSUE THREAD

**Issue by yostashiro** [odoo/odoo#579]
Conditions for below cases:
- Enable real-time stock valuation.
- Cost price: 1000
- Stock qty: 1
- PO price: 1100
- PO qty: 1

In case the costing method = Standard Price
Expected result:
DR) Stock 1000, Price Variance 100
CR) Purchasing 1100  <- This is to be cancelled out by the journal entry from supplier invoice

Actual result (incorrect):
DR) Stock 1000
CR) Purchasing 1000

In case the costing method = Average Price
Expected result:
DR) Stock 1100
CR) Purchasing 1100

Actual result (incorrect):
DR) Stock 1050
CR) Purchasing 1050

---

As I understand, using above examples, the amount for Purchasing should always match the originating PO amount.  And the Stock amount should match the Purchasing amount in case of average price (inventory valuation and the stock account balance will be inconsistent, otherwise), and the product Cost Price in case of standard price.

**Comment by Yenthe666** [comment]
Hi @yostashiro ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
