### ISSUE TITLE
does not show discount for price types other then public price

### ISSUE THREAD

**Issue by userodoo** [odoo/odoo#5790]
i have created additional Price fields for products (list_price_usd, List_price_gbp, List_price_eur)

and then created price types for each one then created a price list and choose the base price for each product with the related discount

when creating a sales order i get can see the original price and discount for products with the public pricelist type

but when choose a product with different base pricelist type then the discount is not visible and i see directly the the final price

**Comment by Yenthe666** [comment]
Hi @userodoo,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
