### ISSUE TITLE
Can't install odoo on Python3.8

### ISSUE THREAD

**Issue by ZOOUQinn** [odoo/odoo#57902]
I can't install odoo on Python3.8 as this version just support Pillow 6.2.1 or later.

So, should we modify Pillow's version in file 'requirements.txt' to adapt it?

**Comment by pedrobaeza** [comment]
I don't recommend Odoo with Python 3.8, as there can be shortcomings not yet found. There's an effort trying to compatibilize it, but no guarantee.

Anyway, AFAIK the requirements.txt is provided for the Python version launched with Debian in the moment of version release, so no modification is expected there. Is that right, @Yenthe666 and @d-fence ?

**Comment by d-fence** [comment]
I confirm that we will not update the Pillow version in the stable versions of Odoo but you can bump the version on your local install.

**Comment by Yenthe666** [comment]
Yep you're absolutely right @pedrobaeza 
On a sidenote: there have also been quite some PY 3.8 fixes at 
https://github.com/odoo/odoo/pull/57298 and
https://github.com/odoo/odoo/pull/51784 and 
https://github.com/odoo/odoo/pull/44332

**Comment by pedrobaeza** [comment]
Closing then.
