### ISSUE TITLE
[12.0] When creating an email, then it does not allow to delete it 

### ISSUE THREAD

**Issue by igallart** [odoo/odoo#57931]
Impacted versions: 12.0 community

Steps to reproduce:

Enter to runbot, (admin or demo) and install mail (Discuss). Set perm of Administration -> Settings.

Current behavior:

Settings > Technical > Emails

Create a email and save, with default values.

The requested operation cannot be completed due to security restrictions. Please contact your system administrator.

(Document type: Message, Operation: unlink) - (Records: [27], User: 2) 

Email create a mail.message, and this is not possible delete. After, the mail and the mail.message are remain without eliminating.

Expected behavior:

Allow delete email.

**Comment by pedrobaeza** [comment]
That records shouldn't be created manually, as it's a technical object. Anyway, you can delete them becoming superuser.

Closing as no issue at all, but expected behavior.

**Comment by igallart** [comment]
Ok, thanks!
