### ISSUE TITLE
[10.0] 500 Internal Server Error when loading /page/website_livechat.channel_page as public user

### ISSUE THREAD

**Issue by mjnayee** [odoo/odoo#57954]
Impacted versions:
V10

Steps to reproduce:
Try and access the 'Livechat Channel Satisfaction Page' at /page/website_livechat.channel_page as a public user.

Current behavior:
Returns 500 Internal Server Error 

The log (see screenshot below) shows that it tries to load the template, but fails to render at loading the channel.name field.

This is being picked up by Google Search Console as an error.

Expected behavior:
Either a 403 or 404 error if the user doesn't have access to the page/have a valid channel.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/58254672/93476728-05205300-f8f2-11ea-9102-e44a61b5e295.png)

**Comment by pedrobaeza** [comment]
Version 10 is out of support version. Only last 3 versions are supported. Anyway, this seems something in your DB.

Closing as stated above.

**Comment by mjnayee** [comment]
Ah, okay. Understood.

I don't think it is a DB problem though as I was able to replicate locally and in a blank DB.

It's just seems to try and render the template without the values.

Thanks anyways.
