### ISSUE TITLE
Save/Discard buttons are shown on sale order when already saved

### ISSUE THREAD

**Issue by christophlsa** [odoo/odoo#5796]
## Problem

When creating a sale order and confirming it (still in the edit mode) the sale order is saved but the "Save" and "Discard" buttons are still shown.
## Affected Versions
- 7.x
- 8.x
- master
## Steps to reproduce
- Open "Sales"
- Open "Sales Orders"
- Click "Create"
- Fill all mandatory fields (at least Customer)
- Click "Confirm Sale" (or try "Cancel")
## Current behavior
- Sale order is saved.
- Buttons "Save" and "Discard" are shown
## Expected behavior
- Sale order is saved.
- Buttons like "Save" and "Discard" are not shown
## Screenshots

![sale_order_confirm_editmode](https://cloud.githubusercontent.com/assets/115873/6690741/8eb8ea12-ccc2-11e4-8700-cb1dc5d5f933.png)

![sale_order_confirmed](https://cloud.githubusercontent.com/assets/115873/6690745/947c8800-ccc2-11e4-9dfd-54aaa4f51468.png)
## Some Notes

I think this is a general bug. The same behavior is shown in the purchase order form. I tried this in the version 7, 8 and master and all have this bug. Good to know: On an older OpenERP 7 version this bug didn't occur.

**Comment by panaetov** [comment]
Hello.
I have this bug as well. 
Does anybody know where this bug is going to be fixed?

Thanks.

**Comment by wtaferner** [comment]
Well, from a usability point of view it might be more clear to not keep a view in editable mode when a button is successfully clicked and performed correctly during editing (which actually writes the changed form data for the sake of the user first and does whatever it was designed for), but functionally everything works as expected, so I doubt it will be accepted as a bug and it is actually the same for all models. So, it really depends on the point of view how to proceed on certain user interactions. No idea if this nuance will be changed any time soon.

**Comment by Yenthe666** [comment]
Not really a bug but an usuability thing I guess. I'm sure this is not something Odoo would want to change anyways.
As V7/V8 support has ended too I'm closing this report.

Regards,
Yenthe
