### ISSUE TITLE
virtual_available incorrectly computed for an active location child of an inactive location

### ISSUE THREAD

**Issue by lepistone** [odoo/odoo#5797]
Take a move that should not be counted at all in outgoing stock, because both origin and destination are descendants of `WH`. Now imagine one of those locations is in fact child of `Input`, that starts as inactive and has the `active` flag flipped if the warehouse is configured for multi-step reception.

Now, after https://github.com/odoo/odoo/commit/d4152c2a40877fd62815d0a55bce5e64b053db72 the locations used to compute product availability do not take into account the `active` flag of parents, and suddenly those internal moves described above are taken into account show up as incoming or outgoing.

Thanks!

**Comment by Yenthe666** [comment]
Hi @lepistone,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
