### ISSUE TITLE
[8.0] product.category has different values in Odoo web and API (XML-RPC)

### ISSUE THREAD

**Issue by maximusjunior** [odoo/odoo#5799]
Not sure if it is issue or feature. If it's feature please help me, where could I find new values of categories?

Impacted versions:
- 8.0 (8.0.20150317 installed on Ubuntu from http://nightly.odoo.com/8.0/nightly/deb/)

Steps to reproduce:
1. Create new category with the name "First",
2. Change name of this category to "Second",
3. Confirm everywhere in web interface name of this category has changed to "Second".
4. Make XML-RPC call of method "search_read" against model "product.category" with condition for example "id > 1".

Current behavior:
Name of the category is "First"

Expected behavior:
Name of the category is "Second"

**Comment by Yenthe666** [comment]
Hi @maximusjunior,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
