### ISSUE TITLE
[saas-3/master] Mass mailing create an attachment for each mail sent

### ISSUE THREAD

**Issue by anthony-muschang** [odoo/odoo#580]
When sending a mass mailing with an attachment, the attachment will be copied for each mail sent. This is very problematic when sending a huge attachment (i.e: 10 mo) to 100.000 contacts in term of performance and on disk utilization.

If the attachment is exactly the same for 100.000 it should not be duplicated 100.000 times.

**Comment by Yenthe666** [comment]
Dear @anthony-muschang,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
