### ISSUE TITLE
[8.0] [Business Logic Bug] Timesheet should not require employee to link to a user.

### ISSUE THREAD

**Issue by davidtranhp** [odoo/odoo#5802]
e.g. a company has thousand of employees and several hundreds of them are welders, carpenters, gardeners, etc that do not use the company's Odoo software. While Odoo requires an employee to link to a user, we cannot record timesheets for those welders, carpenters, gardeners, etc.

This situation happens to most of companies. Please have it fixed.

**Comment by Yenthe666** [comment]
Hi @davidtranhp,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
