### ISSUE TITLE
Test sale_mrp module error occurred

### ISSUE THREAD

**Issue by jaronemo** [odoo/odoo#5803]
When used in the manufacture of Property Groups, the way for the manufacture and supply of products with the Recording Rule, is an invalid use.
Procurements error occurred for No BoM exists for this product!

If the supply of this product changes the way for Make To Order, then follow the normal process
![image](https://cloud.githubusercontent.com/assets/8476734/6702688/4d966520-cd6a-11e4-94f6-4d7931107f76.png)
![image](https://cloud.githubusercontent.com/assets/8476734/6702703/8497de82-cd6a-11e4-9d99-41719db90c28.png)
![image](https://cloud.githubusercontent.com/assets/8476734/6702879/8994dce8-cd6d-11e4-89f6-986102febda2.png)
![image](https://cloud.githubusercontent.com/assets/8476734/6702886/9e6218f2-cd6d-11e4-9a36-35e8a5b745b3.png)
![image](https://cloud.githubusercontent.com/assets/8476734/6702892/aee3d468-cd6d-11e4-82c6-422a90ba477f.png)
![image](https://cloud.githubusercontent.com/assets/8476734/6702897/be5dccaa-cd6d-11e4-9f8a-45fe979787fa.png)
![image](https://cloud.githubusercontent.com/assets/8476734/6702901/c77d5878-cd6d-11e4-8763-8bb282a711ec.png)

**Comment by leangjia** [comment]
香烟啤酒矿泉水！

**Comment by 39181819** [comment]
瓜子可乐爆米花！

**Comment by Yenthe666** [comment]
Hi @jaronemo,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
