### ISSUE TITLE
Why making ids unique by hand instead of using distinct?

### ISSUE THREAD

**Issue by hbrunn** [odoo/odoo#5806]
In https://github.com/odoo/odoo/blob/8.0/openerp/models.py#L4641, we select a list of ids and uniquify them unconditionally afterwards in https://github.com/odoo/odoo/blob/8.0/openerp/models.py#L4652

Could you please explain the rationale behind doing it this way instead of saying `select distinct` above? Postgres should be faster doing this and the current way, we always run into problems when `limit != None`

**Comment by Yenthe666** [comment]
Hi @hbrunn,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
