### ISSUE TITLE
I want to change/rename radio buttons name "individual" and "company"

### ISSUE THREAD

**Issue by Prakashcis** [odoo/odoo#58099]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/71624031/93745411-2c319a00-fbfc-11ea-8c01-387ce40e36eb.png)

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
