### ISSUE TITLE
[DOC] Manifest parameter "active" is documented wrong

### ISSUE THREAD

**Issue by mlaitinen** [odoo/odoo#58090]
**Impacted versions:** 13.0

**Steps to reproduce:** -

**Current behavior:**

When setting `active` to `True` in the module's `__manifest__.py` file, the module gets installed automatically if the dependencies are satisfied. It's just a synonym for `auto_install`.

**Expected behavior:**

As per the [documentation](https://www.odoo.com/documentation/13.0/reference/module.html), this parameter should be used for archiving obsolete modules, not controlling whether it will be automatically installed or not.

This parameter was [renamed](https://github.com/odoo/odoo/blob/11.0/odoo/modules/module.py#L344-L346) already in Odoo 11.0, but it's still there even in 13.0.

**Video/Screenshot link (optional):**

_Documentation_
> **active (bool)**
> This indicates whether this module is to be used or not. It is generally used to archive obsolete modules.

_Code_
```
auto_install = info.get('auto_install', info.get('active', False))
```
Source: [odoo/modules/module.py](https://github.com/odoo/odoo/blob/13.0/odoo/modules/module.py#L338-L354)

**Comment by AdrienHorgnies** [comment]
Ha... The documentation I wrote is wrong rather than the feature. I'll fix that.

**Comment by sswapnesh** [comment]
This has been fixed in https://github.com/odoo/odoo/pull/59850
