### ISSUE TITLE
[6.1, 7.0, 8.0]Wrong total computation in reconcile_partial

### ISSUE THREAD

**Issue by clb-openfire** [odoo/odoo#5810]
account_move_line.reconcile_partial() can call reconcile() when the total amount of reconciled lines equals 0.
The problem is this total is wrong when some of the given lines are already partially reconciled together. In that case, the total of the partially reconciled lines is summed for each of its lines given in 'ids' parameter.

I suggest this patch : 

```
=== modified file 'account/account_move_line.py'
--- account/account_move_line.py    2014-01-10 15:40:23 +0000
+++ account/account_move_line.py    2015-03-18 10:09:25 +0000
@@ -778,10 +778,10 @@
                     if not line2.reconcile_id:
                         if line2.id not in merges:
                             merges.append(line2.id)
-                        if line2.account_id.currency_id:
-                            total += line2.amount_currency
-                        else:
-                            total += (line2.debit or 0.0) - (line2.credit or 0.0)
+                            if line2.account_id.currency_id:
+                                total += line2.amount_currency
+                            else:
+                                total += (line2.debit or 0.0) - (line2.credit or 0.0)
                 merges_rec.append(line.reconcile_partial_id.id)
             else:
                 unmerge.append(line.id)
```

**Comment by Yenthe666** [comment]
Hi @clb-openfire,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 6, 7 and 8 are no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
