### ISSUE TITLE
8.0, master: when passing lot, owner or package in the context, moves in and out are discarded

### ISSUE THREAD

**Issue by lepistone** [odoo/odoo#5814]
While quantity on hand is based on quants, incoming, outgoing and virtual stock also use stock moves. If you pass lot, owner or package in the context, these are used to restrict the selection of quants (which is correct), but they select no moves at all. 

For owners in particular, moves have a field `restrict_partner_id`, so it would make sense to use that one when figuring out the virtual stock by owner. The system instead returns the stock on hand, ignoring the moves.

This happens at https://github.com/odoo/odoo/blob/8.0/addons/stock/product.py#L140-L148.

Thanks!

**Comment by jco-odoo** [comment]
For lot and package, it does not make sense.  For owner it does.

**Comment by lepistone** [comment]
@jco-odoo I proposed #5824 to fix that, could you give a look? Thanks!
