### ISSUE TITLE
[11.0] Cannot do write-off in register payment wizard from tree view

### ISSUE THREAD

**Issue by Garcicasti** [odoo/odoo#58157]
Impacted versions: 11.0

Steps to reproduce: Create a new invoice, add some products and click on register payment. We can see that, if we indicate that the customer paid us less than the total amount, we can "leave the invoice open" or do a write-off.
![image](https://user-images.githubusercontent.com/23293693/93788882-74b77a80-fc31-11ea-94f4-56a905eb2063.png)

However, if we go back to the list view, and try to do the same operation from the "actions" menu, we can see there is not such option. 
![image](https://user-images.githubusercontent.com/23293693/93788894-78e39800-fc31-11ea-99cd-ffa53d8de8c5.png)

Expected behavior:

![image](https://user-images.githubusercontent.com/23293693/93788922-7ed97900-fc31-11ea-9bce-351c1dae535a.png)

I already checked this issue and it would involve changing quite some things in account_payment.py and account_payment_view.xml files. Apparently, it is fixed in 11.3 and above branches. 

Does anyone know which PR needs to be applied to 11.0 for this to be fixed?

In the case that we need to develop a fix from scratch, Is it possible that it could be accepted as a fix for the 11.0 branch?

Thanks.

**Comment by Garcicasti** [comment]
Hi there,

I got a fix for this. If I push the changes to this Issue, will it get merged? Or has the Odoo support for this version expired? 

Thanks

**Comment by Yenthe666** [comment]
The support for this version has ended (sorry). If you can reproduce it in V12 and write a fix there it'll be accepted though.
