### ISSUE TITLE
[13.0] svg logo not fully supported but possible to upload

### ISSUE THREAD

**Issue by grzekru** [odoo/odoo#58164]
**Impacted versions:**

13.0, only this version tested

**Steps to reproduce:**

upload svg logo for your company

**Current behavior:**

Field to upload logo is invisible (very small - no image displayed), logo not visible on documents
Logo visible in partner kanban view, and portal sites

**Expected behavior:**

No above issues

**Comment by pedrobaeza** [comment]
If the logo is very small, probably the source SVG defines that size. I'm using it without problems. Closing meanwhile no further hints are provided.

**Comment by nilshamerlinck** [comment]
I faced a similar case. Turns out it was because the svg had been [exported from Adobe Illustrator as "responsive"](https://www.growfox.co.uk/blog/how-to-make-sure-your-svgs-have-height-and-width-attributes-using-illustrator-cc) and didn't have any width/height attributes defined.
