### ISSUE TITLE
[8.0] Fleet Management: Getting "AttributeError: Field `in_group_14` does not exist" after UPDATING

### ISSUE THREAD

**Issue by Selbert-IT** [odoo/odoo#5820]
**Getting "AttributeError: Field `in_group_14` does not exist" after UPDATING Fleet Management**

Impacted versions:

 - 8.0

Steps to reproduce:

 1. create new Database
 2. install fleet management
 3. update fleet management
 4. open "Settings" -> "Users" -> "admin" 

Current behavior:

 - Raise AttributeError(message) -> AttributeError: Field `in_group_14` does not exist
   Error context: View `res.users.form`
   [view_id: 153, xml_id: base.view_users_form, model: res.users, parent_id: n/a]

Expected behavior:

 - No Exception -> Open the Formview

**Comment by MedMehdiMMM** [comment]
I have the same problem with the last version and exactly witn mail module (because its a fleet dependence).

**Comment by 4nu81** [comment]
I have the same Problem with an self made module with new user-Groups. After Updating the module I cannot access the res_users view anymore.

**Comment by diagramsoftware** [comment]
This problem has happened to us several times too, but in our case it was due to the missing attribute `noupdate="1"` in the tag `data` when declaring the groups. Could it be related to this behaviour?

**Comment by csmu-cenr** [comment]
Try updating the base module. That resolved the issue for me.

**Comment by bikthao** [comment]
base/res/res_user.py.
@api.multi
    def _is_admin(self):
        return self.id == openerp.SUPERUSER_ID or self.sudo(self).has_group('base.group_erp_manager')
