### ISSUE TITLE
[7.0, 6.1] Chained locations: processing first move does not copy prod.lot in chained moves

### ISSUE THREAD

**Issue by paulius-sladkevicius** [odoo/odoo#5829]
In the 6.0 there was bug fixed https://bugs.launchpad.net/openobject-addons/+bug/763437 a3f4cb4df31e362f10181b26995056b2d670b9eb, but on 7.0 and 6.1 this code was removed. I couldn't find commit why it was removed.

**Comment by Yenthe666** [comment]
Hi @paulius-sladkevicius,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 6.1, 7 and 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
