### ISSUE TITLE
[11.0][12.0][13.0][master] Changing template in mail compose wizard does NOT delete previous attachments

### ISSUE THREAD

**Issue by jonerikceberio** [odoo/odoo#58309]
Impacted versions:
11.0, 12.0 ,13.0, master
Steps to reproduce:
Go to Settings - Technical - Email - Templates
Find the "Sales Order: Send by email" template
Duplicate it, delete the field "Optional report to print and attach"
Go to Sales, enter in a sale and press "Send by email" button
Choose the "Sales Order: Send by email" template (or chosen by default) - you have a pdf attached
Now change the template to "Sales Order: Send by email (copy)"

Current behavior:
The attachment stays, opposed to what is stated in the template.
This means that we can send a report that should NOT be sent with the template.

Expected behavior:
All the previous attachments should be deleted, and new ones applied. So the onchange in mail_compose_message should clean the attachment_ids field.

**Comment by pedrobaeza** [comment]
I think is correct to keep attachments. Maybe the text should change. What do you think, @Yenthe666 ?

**Comment by Yenthe666** [comment]
Hmm I think it shouldn't happen if you checked off the option "Optional report to print and attach" in your duplicated template. 

Note: I've also reported a bug related to email templates close this one just this morning. Case:
1. Duplicate a template and set one word in title / body
2. Choose the duplicated template in the send mail dialog
3. Check off "Send e-mail"
4. Check on "Send e-mail"
5. The right template is still selected but with the wrong body & title
= Wrong email being sent. That's reported under OPW 2345200

**Comment by jonerikceberio** [comment]
The way I see it: you may have two templates for the same object, one with a report and the other one without it. Imagine that the report includes prices, while the template without the report does not. You change template, the attachment is still there, and you have sent the prices without realising it. 
Long story short: if your template does not have a report, it shouldn't have any attachments when applied.

**Comment by sswapnesh** [comment]
I agree with @jonerikceberio 
We already did this using custom code in the past.
Users were not realising they are sending email including attachment.

**Comment by sswapnesh** [comment]
@Yenthe666  Any update on OPW 2345200 ?

**Comment by Yenthe666** [comment]
Was fixed in https://github.com/odoo/odoo/commit/cd6c54b15ce328b58888a4f33a64ae61c7744a90

**Comment by sswapnesh** [comment]
It is only Fixed for invoice template, Not globally for  mail compose wizard

**Comment by david-fleischmann** [comment]
Anyone interested in the fix for this issue?
We've made a custom module to solve this. Shoot us an email: it@zebroo.de
We'll try to contribute it to OCA

**Comment by Yenthe666** [comment]
Why not push it to a public repo already? :)
