### ISSUE TITLE
[13.0] Error when installing l10n_es

### ISSUE THREAD

**Issue by HaraldPanten** [odoo/odoo#58315]
Impacted versions: 13.0 and maybe master as well

Steps to reproduce: try to install l10n_es

Current behavior: error when installing l10n_es

It seems that there's something wrong with l10n_es. When you try to install this module, an error occurs. Maybe coming from the last porting from V11 an V12?

@pedrobaeza @oco-odoo

**Comment by pedrobaeza** [comment]
Already reported and fixed in #58283. Please check before opening an issue. It's due to a bad forward-porting of the 11.0 new tax.
