### ISSUE TITLE
Multi-company / Category routes on Product form are not limited to selected companies 

### ISSUE THREAD

**Issue by werdan** [odoo/odoo#58357]
Impacted versions: 13.0

Steps to reproduce:

- Multi-warehouse + Multi-company setup
- Create Company A with warehouse and 1-step delivery
- Create Company B with warehouse and 2-steps delivery
- Switch to Company A: Set Logistics route on product category All/Saleable : 1-step delivery
- Switch to Company B: Set Logistics route on product category All/Saleable : 2-steps delivery
- Switch to Company A, make sure Company B is turned-off
- Open product category  All/Saleable - Logistics route show only "1-step" which is OK
- Create new product and set category to All/Saleable
- Save product. Multi-company error is coming
 

![image](https://user-images.githubusercontent.com/359393/94023518-93934980-fdb6-11ea-9bb3-c64680f1a460.png)

Current behavior:
User can not open product when category logistic routes has routes from 2 different companies (even though routes are not visible on its own)

Expected behavior:
User can open product and category routes are only the routes visible in the scope of active company

**Comment by hugho-ad** [comment]
OPW 2390983
