### ISSUE TITLE
Adding new field in shop/cart and relate it's value with the same field in sale.order.line

### ISSUE THREAD

**Issue by Sad0k** [odoo/odoo#58365]
odoo 12

 i've added a new attribute "with_delivery" in sale.order.line and it works in the module perfectly,
Now i need to add it to my e-commerce module, and save it's value in database from the shop/cart view by pressing on "Process Checkout"button.
![Screenshot from 2020-09-23 17-11-18](https://user-images.githubusercontent.com/63306326/94041074-abbc9600-fdc1-11ea-9eb6-853e9b5965f1.png)

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
