### ISSUE TITLE
odoo can be connected with oracle database? is it possible ? how? explain?

### ISSUE THREAD

**Issue by abhishekms123** [odoo/odoo#58378]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Not possible.

**Comment by Yenthe666** [comment]
Hi,

Github is used for issues and not for asking questions.
Please ask these kind of questions on the help forums at http://help.odoo.com/ in the future.
@pedrobaeza is kind of right, there is no easy way to do so. Unless you write your own in between layer but that's going to be very challenging.
