### ISSUE TITLE
customising help tips

### ISSUE THREAD

**Issue by nuria-opusvl** [odoo/odoo#5843]
Hi,

At the moment you cannot modify the help tips from the User Interface. You need to change it in the file and upgrade the module to make it effective.

But we are getting interest from our customers, and they want to be able to do it themselves as and when they need it.

Could this functionality be developed at some point?

Many thanks,
Nuria

**Comment by Yenthe666** [comment]
Hi @nuria-opusvl,

Thank you for the suggestion and sorry for the very late reply.
I've labelled it wishlist so it keeps popping up, even after closing it.
@mart-e this would be nice honestly.

Regards,
Yenthe
