### ISSUE TITLE
Author field of ir_module limited to 128 chars

### ISSUE THREAD

**Issue by pedrobaeza** [odoo/odoo#5850]
When I add an author longer than 128 chars, Odoo raises this error:

```
DataError: value too long for type character varying(128)
```

Now that you can indicate multiple authors for a module separated by commas, this limit is very short.

@odony, can you please check it and remove the limit or at least extend it to a more reasonable amount?

**Comment by odony** [comment]
@pedrobaeza Should be ok now (bumped up to 512). I'd rather not make it unlimited, to prevent abuse.

**Comment by pedrobaeza** [comment]
Thank you very much, Olivier! Can you point me to the involved commit?

**Comment by odony** [comment]
@pedrobaeza Oops, for some reason I was under the impression that you were referring to Odoo Apps - so the platform has been updated to support longer names. Now we also need to fix it in Odoo itself ;-) 8.0 sounds good enough as a target branch for the change, right?

**Comment by pedrobaeza** [comment]
Yeah, but it would be welcome on 7.0 also ;)

**Comment by pedrobaeza** [comment]
@odony, any news on this?

**Comment by pedrobaeza** [comment]
@odony, do we have any news on this topic?

**Comment by pedrobaeza** [comment]
@odony We are very constrained by this limitation. Can you please tell me how to move it forward? May I inspect and propose a PR?

**Comment by elicoidal** [comment]
This is indeed a limitation that is annoying and will become more and more a problem because we have modules in the OCA that comes from v5 with successive added authors over version, migrations and enhancements.
I understand not making it unlimited but what about 512 as you suggested?

**Comment by pedrobaeza** [comment]
@Yenthe666, maybe you can push this issue...

**Comment by pedrobaeza** [comment]
@odony I beg you to recheck this

**Comment by odony** [comment]
Sorry for the incredibly long delay :sweat: Hopefully this should be fixed in 8.0 by ce12a7397f6d2e02626155bb9c3685de96044689 (to be forward-ported)

**Comment by pedrobaeza** [comment]
Thank you very much, Olivier!
