### ISSUE TITLE
[13.5/V14] stock: unable to modify done quantities for transfers

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#58558]
Impacted versions: Saas-13.5 / upcoming V14

Steps to reproduce:
1. Login to the latest runbot 13.5 with the admin user
2. Create a new quotation with a new product that is of the type stockable
3. Confirm the sale order
4. Open the delivery
5. Click on "Edit", open the "Operations" tab and try to modify the quantity done:
![image](https://user-images.githubusercontent.com/6352350/94417167-04a07b80-0180-11eb-9420-83b36439a79c.png)

Current behavior:
It's impossible to update the "Done" quantity of the operation

Expected behavior:
You can edit it and the view is not bugged.

**Comment by Yenthe666** [comment]
@amoyaux for your interest :) Might want to fix it before V14.

**Comment by pedrobaeza** [comment]
I see that you haven't unlock the picking...

**Comment by Yenthe666** [comment]
Apoligies, better screenshot:
![image](https://user-images.githubusercontent.com/6352350/94417973-10407200-0181-11eb-93fe-e2cb656cbad9.png)

**Comment by sswapnesh** [comment]
@Yenthe666  You have to change Delivered quantity from Detailed Operations tab.

**Comment by Yenthe666** [comment]
Not sure what I was doing here 😆
