### ISSUE TITLE
[Odoo-8.0] POS model.js invoice_id reference

### ISSUE THREAD

**Issue by alejandroperezcosio** [odoo/odoo#5858]
I would like to know if there is a way to get the invoice_id reference for a pos order or when it will be implemented?

point_of_sale > models.js > export_for_printing > invoice_id

The reference is marked with a null value and a //TODO flag

Kind regards

**Comment by Yenthe666** [comment]
Hi @alejandroperezcosio,

These kind of questions should be asked on the help forums (at odoo.com/help) as this is not a bug in Odoo itself.
Sorry for the (very) late reply.

Regards,
Yenthe
