### ISSUE TITLE
On_change edit one2many values gives error when one of the field is empty

### ISSUE THREAD

**Issue by tfossoul** [odoo/odoo#586]
Hi,

I got this error : 
Uncaught TypeError: Cannot read property 'set' of undefined
http://localhost:8069/web/static/src/js/view_list_editable.js:333

How the bug appear :
On the view, you add a line on your resource_calendar_event_ids field. specify a resource_id. Then you leave the focus on your field. then you empty the resource_id.

Now, if you edit the date_start, the onchange should be processed and the resource_calendar_event_ids field should be edited. But the beautiful error appear...

I don't have the error with other kind of field. Just many2one.

Good luck and thanks in advance

Thomas F.

The structure:

class project.task: 
_column:
'date_start': fields.datetime('Starting Date',select=True),
'resource_calendar_event_ids': fields.one2many('resource.calendar.event', 'task_id', 'Ressource allocation',),      
        
def onchange_date_start(self, cr, uid, ids, date_start, resource_calendar_event_ids, context=None): 
        resource_calendar_event_ids = self.resolve_2many_commands(cr, uid, 'resource_calendar_event_ids', resource_calendar_event_ids)
        return {'value': {
                        'resource_calendar_event_ids': resource_calendar_event_ids
                 }}

class resource.calendar.event: 
_column:
...
'resource_id' : fields.many2one("resource.resource", "Resource", help="If empty, this is a generic holiday for the company. If a resource is set, the holiday/leave is only for this resource"),
....

**Comment by Yenthe666** [comment]
Dear @tfossoul,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
