### ISSUE TITLE
Empty Checkout form creates records

### ISSUE THREAD

**Issue by Karmdo** [odoo/odoo#5867]
Impacted versions:

- 8.0
- Master

Steps to reproduce:

1. Install the ecommerce module
2. Go to the yoursite/shop/checkout page
3. Without any input, Click on confirm

Current behavior:

- Even if the checkout form is not complete, when you click on confirm it creates a quotation
- Creation of empty quotations (by Robots?)

Expected behavior:

- Without the correct inputs in the checkout form, no creation in Odoo to prevent automatically generated input.

**Comment by JKE-be** [comment]
It is generated by bot which one know the url via the sitemap.
A normal flow should not arrive on this page with an empty cart.

If you add this route in your robot.txt, that should solve your problem for bot.
You can also add a cron which clean empty sale order from public user with state draft.
We are looking for a solution in standard, by default, in the next version.

Thanks for the reporting
