### ISSUE TITLE
[8.0] big regression in hr_timesheet_sheet Timesheet Analysis report

### ISSUE THREAD

**Issue by sbidoul** [odoo/odoo#5868]
The report shows incorrect values when there are multiple timesheet lines for the same day.

Regression introduced in commit https://github.com/odoo/odoo/commit/89093a26165ad61c63138c06ec6fe0575a33970a#diff-c5e80ecc7053ea28bb4636e043ce7290

**Comment by sbidoul** [comment]
ping @beledouxdenis

**Comment by beledouxdenis** [comment]
I would welcome a specific, step by step, use case, with the menus, actual examples, etc.

**Comment by sbidoul** [comment]
Of course. I'll try to do it.

But don't you agree that the added "left join hr_timesheet_sheet_sheet_day AS day ON (htss.id = day.sheet_id)" repeats each analytic line for each day that is present in the sheet?

**Comment by sbidoul** [comment]
Here is the example on runbot 8.0:

Timesheet activities (total 114h):
![image](https://cloud.githubusercontent.com/assets/692075/6780445/a97514dc-d165-11e4-904c-5f0713afec78.png)

The timesheet (total 114h):
![image](https://cloud.githubusercontent.com/assets/692075/6780436/96947ba0-d165-11e4-8efb-e126b0dd097a.png)

Timesheet Analysis (total 228h NOK!)
![image](https://cloud.githubusercontent.com/assets/692075/6780432/8204ec9c-d165-11e4-81dd-6304de0b2a6f.png)

**Comment by sbidoul** [comment]
@beledouxdenis are the screenshots above illustrative?

**Comment by beledouxdenis** [comment]
Hello @sbidoul, 

I am very sorry about the response delay. This issue / SQL view gave me a huge headache.

My above rev. was indeed wrong, very wrong.

At first, I was indeed tempted to revert my above revision. Nevertheless, I noticed that, once reverted it, the totals of columns diff, timesheet and attendances were still wrong when having multiple analytic lines to a same date. An issue was therefore already there, even before my revision. I therefore tried to build a new patch, still solving the performance issues from the OPW ticket the above revision was about, while solving what I broke with my above revision, and solving the diff / timesheet / attendances totals.

You can have a look to my PR #6010. I tested it with a lot of case, and I believe it solves everything. You will see why it gave me a headache :).

As soon as I have a positive review from you, I will proceed to the merge in stable branch.

**Comment by samuellefever** [comment]
With your last fix, the report does not show the timesheet from tasks.

**Comment by sle-odoo** [comment]
Closing as PR #6010 has been merged.
Regards
