### ISSUE TITLE
[ Odoo Failed ]  [Bug] Pricelist issue on sale order

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#5869]
Sale Order form view.

Pricelist field, when change customer automatically price-list filled,
Same price-list when try search in m2o pricelist field, unable to get it.

If default price-list is only for purchase then it should not be come in sale order.

Kindly review it and try to fix, if it to be consider as bug.

Thanks,
TEJAS

**Comment by Yenthe666** [comment]
Hi @tejastank,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
