### ISSUE TITLE
"Create a New Database" page broken since commit 53a9f6c

### ISSUE THREAD

**Issue by WohthaN** [odoo/odoo#5872]
Since commit 53a9f6c the page to create a new database on a clean installation is broken (nothing is shown on the page but the odoo logo).

Impacted versions:
- master

Steps to reproduce:
- start odoo without a database (as of, first installation).
It redirects to http://localhost:8069/web/database/manager
instead of  
http://localhost:8069/web/database/manager#action=database_manager 
and nothing is displayed in the page .

Expected behaviour:
- The usual initial database management page is shown.

The immediately previous commit db592ef seems to be working fine. The bug is still present up to commit 5aba579.

**Comment by aab-odoo** [comment]
Hi,

This is closed by rev. de1d7f93d04cbb61443015b732342a1e863b7827.

Thanks for reporting it.

**Comment by WohthaN** [comment]
Awesome. Thanks!
