### ISSUE TITLE
v8 - For crm.lead, not able to pass new customized view using form_view_ref in context.

### ISSUE THREAD

**Issue by omalbastin** [odoo/odoo#5874]
To recreate it,in odoo v8,
In sale order, add a field opportunity_id, relation to crm.lead, then try to open the leads view by adding context with key form_view_ref and value as leads view xml id. but it will open opportunity view. if you try to check the context in fields_view_get you cant find the context we have added.

**Comment by Yenthe666** [comment]
Hi @omalbastin,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
