### ISSUE TITLE
[Test naming convention ] Why do we use this naming convention on test fonction "test_xx_..." ?

### ISSUE THREAD

**Issue by tfossoul** [odoo/odoo#58763]
Why do we use this naming convention on test fonction "test_xx_..." ?

I see it everywhere in standard, enterprise and oca modules. But not always and not always maintained.
For instance in **account\tests\test_reconciliation_widget.py** - `def test_01_portal_attachment(self):`

**Comment by Yenthe666** [comment]
If it doesn't start with `test_` it will not execute the test, basically.

**Comment by tfossoul** [comment]
Sorry my question wasn't not clear enough. I was talking about the numbering in the name of the def. def test_**01**_...()

**Comment by pedrobaeza** [comment]
There's no obligation on using numbers after `test_`. Some use this for ensuring the test order.
