### ISSUE TITLE
[7.0] Wrong prices in product cost structure

### ISSUE THREAD

**Issue by Threepwood9985** [odoo/odoo#5882]
When we create the PDF file for the product cost structure of a product variant/product, the prices of the suppliers are wrong.

we defined a price list based on "supplier price on the product form" and set some values for different quantities of the product.

Example: Quantity:Unit Price

1: 100
10: 90
100: 80
1000:70

Now, when we create the PDF file with the cost structure of a bom, e.g. for a quantity of 10, the price is 80. But it should be 90.

the price for the PDF is calculated in the file ".../addons/mrp/price.py". 
method: create_xml(), line 86.

tested with version 7.0 and 8.0, problem occurs in both versions.

**Comment by Yenthe666** [comment]
Hi @Threepwood9985 ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
