### ISSUE TITLE
[8.0] Catchall should have fall back system.

### ISSUE THREAD

**Issue by Elastino** [odoo/odoo#5885]
Hi, 

Catchall trackback system is based on email header.
(I don't know exactly which one among [`References`]. [`In-reply-to`] or [`message-id`].

Odoo MTA should include reference information IN the email `BODY` and at the of `SUBJECT`

Some of webmail system cleans up email header for security reason, so it is impossible to retrieve emails.

Suggesion
1. Include `reference-id` in the email body.
2. Use message `header` as top priority.
3. Use message `subject` as second priority.
4. Use email `body's reference id` as third priority since it may have several references by threads.

How does it sound?

CJ Lee.

**Comment by Elastino** [comment]
Or. at least notify admin that 'unprocessed' message is available, then re-allocate to proper thread.
Currently, it fetches email then do nothing.

**Comment by Yenthe666** [comment]
Hi @Elastino,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
