### ISSUE TITLE
Website not selectable at more than one databases

### ISSUE THREAD

**Issue by diezcode** [odoo/odoo#5886]
How I make that in NGINX on ubuntu 14.04 linux

https://github.com/odoo/odoo/issues/1401#issuecomment-84889934

**Comment by lukebranch** [comment]
@diezcode ,

This is more of a configuration question than an issue/bug report. I'd recommend closing this issue and asking the question in detail in the help forum here:

https://www.odoo.com/forum/help-1

**Comment by diezcode** [comment]
give me better here an answer, thank you

**Comment by Yenthe666** [comment]
Indeed, not a bug but a question about implementation. You can ask this on the help forums or see the deployment docs at https://www.odoo.com/page/docs

Regards,
Yenthe
