### ISSUE TITLE
Some terms are not translated into Spanish in ODOO 13

### ISSUE THREAD

**Issue by hanzelrl** [odoo/odoo#58870]
Impacted versions: 13

Steps to reproduce: Using the ODOO 13 source repository from the GitHub and Pycharm, you can create a new database and use Mexico as the country and Spanish language.

Current behavior: A lot of terms are not translated into Spanish, for example in Inventory the Kanban view of the products contains many terms in English, for example for each product the property "On Hand", instead of "En Mano". I have already reloaded the Spanish language several times and everything is the same.

Expected behavior: It is assumed that the large amount of terms is in Spanish, especially in the ODOO core modules. In fact, using odoo_13.0.latest_all.deb on a production server, all these terms are correctly in Spanish.

Video/Screenshot link (optional):
![Screenshot from 2020-09-29 16-24-31](https://user-images.githubusercontent.com/36964254/94612197-c20a9c00-0270-11eb-9609-8b63927a0d0f.png)
![Screenshot from 2020-09-29 16-24-10](https://user-images.githubusercontent.com/36964254/94612337-f8481b80-0270-11eb-8a3e-284a28166460.png)

**Comment by pedrobaeza** [comment]
You don't have it properly updated:
![Selección_033](https://user-images.githubusercontent.com/7165771/94653584-16a72900-02fc-11eb-9b22-2f5e65cc8af4.png)
extracted from latest 13.0 runbot.
