### ISSUE TITLE
Minor security issues

### ISSUE THREAD

**Issue by obayit** [odoo/odoo#58882]
Impacted versions:
12.0
Steps to reproduce:
visit specific urls,
http://localhost:8069/web/login?error=fake_massege
http://localhost:8069/web/session/logout?redirect=https%3a%2f%2fanysite.com%2f
Current behavior:
query parameters can be  used to display arbitrary messages, and redirect user on logout.
Expected behavior:
This should not happen. At least the message part.

**Edit**
Already suggested a PR [#46108](https://github.com/odoo/odoo/pull/46108)

**Comment by pedrobaeza** [comment]
I don't consider it as critical, but please follow responsible disclosure in https://www.odoo.com/security and Odoo will consider it. Point to the PR as well.
