### ISSUE TITLE
It is possible to select a portal user as sales person (user_id) in crm leads

### ISSUE THREAD

**Issue by rruebner** [odoo/odoo#5889]
Hi all,

it is possible to select a portal user as a sales person in crm leads. Is it an expected behavior? In my opinion a portal user shouldn't be selectable as sales person in crm leads.
#### Impacted Versions:
- 8.0, master
#### Steps to reproduce
1. Use the latest runbot (8.0 or master) and login as admin
2. Go to Sales -> Sales -> Leads -> Create a new or open an existing lead
3. Type in "portal" in the Salesperson field -> now you can select the "Demo Portal User"

Regards, Robert

**Comment by Yenthe666** [comment]
Hi @rruebner,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by xabispacebiker** [comment]
The same is happening in my Odoo 11 installation. Registered customer in portal shows as salesperson. What am I missing?
