### ISSUE TITLE
Translation issue in barcode module

### ISSUE THREAD

**Issue by etechsam** [odoo/odoo#58916]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/66409528/94772147-a9f66200-03c1-11eb-8562-61a428a5ac6f.gif)
Impacted versions: Odoo 13

Steps to reproduce: Go to Barcode > Operations > Select a picking type > Open a picking > Edit a move line

Current behavior: FR Translation is not loaded in the form view

Expected behavior: Field name should be in French

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Have you checked that is translated in Transifex?

https://github.com/odoo/odoo/wiki/Translations

**Comment by etechsam** [comment]
> Have you checked that is translated in Transifex?
> 
> https://github.com/odoo/odoo/wiki/Translations
Not yet, but actually it's not translated even when I just install Odoo native module

**Comment by pedrobaeza** [comment]
As said, if not translated there, you can't expect to be. Translation is a community effort, not something guaranteed for 100% of the strings. Closing meanwhile you check it.
