### ISSUE TITLE
Unable to archive data under Inventory Valuation

### ISSUE THREAD

**Issue by pfeliprada** [odoo/odoo#58917]
Impacted versions: Odoo 13

Steps to reproduce: Go to Inventory > Reporting > Inventory Valuation > Select a data > Click action > Click archive

Current behavior: No changes, data not archived

Expected behavior: Data must be archived and must be categorized under archived tree when archived filter is ticked

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@amoyaux

**Comment by amoyaux** [comment]
You are not suppose to archive valuation.layer. They describe the inventory valuation and the different steps to the final value. Also the model does not have an active field, so it's normal that nothing happens. We added a new solution in v14 to be able to create a new valuation layer when the valuation is fifo or average. If you want to fix your valuation in 13.0, I suggest to enable the layer creation in the tree view and set the quantity field as read-only in the form view.

**Comment by Yenthe666** [comment]
@amoyaux the "Archive" action shouldn't be there in the first place anyways then.

**Comment by pfeliprada** [comment]
> You are not suppose to archive valuation.layer. They describe the inventory valuation and the different steps to the final value. Also the model does not have an active field, so it's normal that nothing happens. We added a new solution in v14 to be able to create a new valuation layer when the valuation is fifo or average. If you want to fix your valuation in 13.0, I suggest to enable the layer creation in the tree view and set the quantity field as read-only in the form view.

Thank you for your fast response and suggestion will keep this in mind!

**Comment by sswapnesh** [comment]
> Also the model does not have an active field, so it's normal that nothing happens.

It has active field related to the Product. (Non stored)

> "Archive" action shouldn't be there in the first place anyways then.

That's from Framework, It will automatically add the action if model has Active field. (We should have a tag so we can remove the this action, even model has Active field)
