### ISSUE TITLE
UOM issue in sale.order.line

### ISSUE THREAD

**Issue by etechsam** [odoo/odoo#58928]
Impacted versions: Odoo 13

Steps to reproduce: 
- Create a sale order
- Add a line with a storable product
- Remove the unit of measure

Current behavior:
- A bug pops up

Expected behavior:
- No bug pops up

Video/Screenshot link (optional):
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/66409528/94816212-27db5d00-0404-11eb-815f-4eeba6a0f130.gif)

**Comment by pedrobaeza** [comment]
This seems to be due to the stock info popup

**Comment by etechsam** [comment]
Alright, I assume that it has to be fixed?

**Comment by sswapnesh** [comment]
> Alright, I assume that it has to be fixed?

Added Fix at https://github.com/odoo/odoo/pull/59042 , Now the Stock Button (Widget) will not be displayed if UOM is Blank.

**Comment by sswapnesh** [comment]
Hello @etechsam 
This has been fixed in https://github.com/odoo/odoo/pull/59447/commits/2da85bf93e09bd94bace37017b70ad8ddee37b73

**Comment by Botakely** [comment]
Thank you

> Hello @etechsam
> This has been fixed in [2da85bf](https://github.com/odoo/odoo/commit/2da85bf93e09bd94bace37017b70ad8ddee37b73)
