### ISSUE TITLE
[ORM] Compute method not gets calculated when depends field is updated via scheduler (cron)

### ISSUE THREAD

**Issue by ajaychauhan727** [odoo/odoo#58930]
Impacted versions: 13.0, not sure about older version

Steps to reproduce:

1. Define one function field with store=True, and in depends have one filed which gets updated via scheduler (cron)
2. When you update any other field which is in depends via UI, method gets calculated

Current behavior:
when you update that specific field from depend via cron, compute method does not get calculated

Expected behavior:
Compute method should get called even when depend field is updated via scheduler (cron)

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
What do you understand by "depending"? Are you talking about "onchanges"?

**Comment by ajaychauhan727** [comment]
@pedrobaeza by depending I mean fields which we add in for any function field method. Please have a look at below code.

```
@api.depends('order_line.a', 'b', 'lines.c')
def compute_d(self):
    method code 
    ...
    ...
d = fields.Float(compute='compute_d', store=True)
```
In my above code example, when field `a`  of `order_line` or `b` gets updated via UI method `compute_d` gets called and calculation is done, but when field `c` of `lines` gets updated via scheduler (cron), method `compute_d` function does not get called.

**Comment by pedrobaeza** [comment]
I'm afraid this doesn't depend on being executed via cron, but the code you include in the cron. Via UI might be working through extra triggers that you don't know.

Anyway, this is a development question, and you should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here. Expose your problem with full code for people to be able to help you.

Closing this by the reason above.
