### ISSUE TITLE
POS Interface v14 is not compatible with all devices

### ISSUE THREAD

**Issue by EslamDawoud** [odoo/odoo#58943]
The design of session in the point of sale in version 13 is better than version 14 and version 13 is compatible with all devices, unlike version 14, please review.

**Comment by pedrobaeza** [comment]
Unless you specify explicitly a visualization problem, this will be closed as invalid. The concept "better" is relative.

**Comment by EslamDawoud** [comment]
![D2C4A590-2DFC-4854-BE69-5120C1A9EF5B](https://user-images.githubusercontent.com/72242202/94906769-5a866380-049f-11eb-9575-8c76fe7fb063.png)
![C112EFF9-81A8-4539-9FA1-451D1741B1C9](https://user-images.githubusercontent.com/72242202/94906776-5bb79080-049f-11eb-8038-8ccb4bc67f03.png)

**Comment by pedrobaeza** [comment]
Can you please try in English to see if you have the same problem?

**Comment by pedrobaeza** [comment]
and also in runbot to see if it's on outdated version.

**Comment by EslamDawoud** [comment]
The problem still exists
