### ISSUE TITLE
EAM / CMMS module & stock management

### ISSUE THREAD

**Issue by absystn** [odoo/odoo#5900]
Hello,
I look for ODOO module (v7 or v8) maintenance management computer assisted (EAM / CMMS) with stock management,
I found a CMMS that not suit me too, I have no stock of piece parts.
best regards

**Comment by Yenthe666** [comment]
Hi @absystn,

Not sure what your question / idea was at this time honestly.
An overview from the apps can be found on odoo.com and at that point it was not in Odoo.

Regards,
Yenthe
