### ISSUE TITLE
invoice's send error  -  Chile localization

### ISSUE THREAD

**Issue by Aligtrrz** [odoo/odoo#59000]
Impacted versions: 13.0

Steps to reproduce:  Create and send a  invoice to a costumer

Current behavior: Doesn't send the invoice to the SII for a schema error

Expected behavior:

Video/Screenshot link (optional):
 <string>:6:0:ERROR:SCHEMASV:SCHEMAV_ELEMENT_CONTENT: Element '{http://www.sii.cl/SiiDte}RutReceptor': This element is not expected. Expected is ( {http://www.sii.cl/SiiDte}RutEnvia ).

**Comment by Yenthe666** [comment]
Hi,

Can you reproduce this on an official test instance at runbot.odoo.com?
Which steps do we need to follow to reproduce this?

Regards,
Yenthe

**Comment by eladio77** [comment]
> the serial number was missing from the digital certificate.

Hi.. where is the serial number?
Thanks

**Comment by Aligtrrz** [comment]
Hi! 
the serial number, is the R.U.T. number of the certificate owner.

**Comment by eladio77** [comment]
Thanks Ali. I have the same problem. I see the field "Numero de Serie" but is not active. 


Passkey del Certificado |  XXXXXXXX
Fecha de vencimiento | 02/01/2021 20:00:00
Nro de Serie del Sujeto |  
Propietario del Certificado |  XXXXXX
Compañía | XXXXX

**Comment by eladio77** [comment]
Una Consulta Aligtrrz... la version 14 por lo que veo ya viene lista para fncionar con SII? Soy nuevo en Odoo.  Si me das una mano,... totalmente agradecido.

**Comment by Aligtrrz** [comment]
Hola Eladio!
en la version13 la localización Chilena estaba funcionando al 100% incluso logramos emitir documentos pero actualizamos a la versión 14 y presenta ese error que no permite ingresar el numero de RUT. 
Segun el proveedor de la aplicación eso debió quedar listo esta semana pero al dia de hoy aun no se resuelve.
Yo tengo pensado hacer unas pruebas con la API a ver si me resulta ingresar ese dato, ahí te comento.
Que versión usas tu?

**Comment by eladio77** [comment]
Hola... estoy usando la 14. Consulta.. instale odoo On Premise. Entonces supuestamente la version 14 .. si configuro el diario para que sea con gestión "En Linea" coloco el email para DTE y el certificado ditigal... deberia poder emitir facturas directo a SII?
Es solo emision verdad? o tambien la recepción está habilidata? Es que estoy ahorita haciendo todo manual en Odoo jejeje por que apenas ando comenzando un somos mini mini mini pyme jajajajaja

**Comment by eladio77** [comment]
Yo actualmente tengo factrruración electronica.. pero en SII cambié los emails registrados por el de mi empresa jejeje.. no se si es asi el procedimiento.

**Comment by eladio77** [comment]
Osea actualmente estaba usando BSale para hacer la facturación electronica, entré y actualice los emails de Bsale a los mios.

**Comment by Aligtrrz** [comment]
> Hola... estoy usando la 14. Consulta.. instale odoo On Premise. Entonces supuestamente la version 14 .. si configuro el diario para que sea con gestión "En Linea" coloco el email para DTE y el certificado ditigal... deberia poder emitir facturas directo a SII?
> Es solo emision verdad? o tambien la recepción está habilidata? Es que estoy ahorita haciendo todo manual en Odoo jejeje por que apenas ando comenzando un somos mini mini mini pyme jajajajaja

En Odoo puedes enviar los documentos al SII y recibirlos tambien. pero debes tener configurado el servidor de recepcion y envío. Para la recepción, debes tener configurado el mismo correo que aparece en el SII.
