### ISSUE TITLE
[8.0 Website] SEO language issue

### ISSUE THREAD

**Issue by auyeung112002** [odoo/odoo#5903]
Problem:
Crawler will ignore website default language and use en_US to crawl the page. Currently it uses 302 redirect based on browser's language setting. 302 redirect on index page may also harm SEO rank.

From Google Webmaster page: Avoid automatic redirection based on the user’s perceived language. These redirections could prevent users (and search engines) from viewing all the versions of your site.
https://support.google.com/webmasters/answer/182192

Related commit: https://github.com/odoo/odoo/commit/20d366595c303df29f72cc2016de5341d8827720

**Comment by auyeung112002** [comment]
@JKE-be Would you please take a look at this issue?

**Comment by JKE-be** [comment]
Hello, Thank you for your reporting.
We are aware of the issue... But always in discussion...
Remove the redirect  or apply patch/hack 59e8a2ef20fec40295749a0d075759b0888a6046

The purpose of this patch, is to ignore the redirect for crawler, but keeping the feature for visitor. And also allow the developer to disable it easily if he prefer to make a index with a language selector or ...

The redirect is to avoid duplicate content as explained in your link !

**Comment by auyeung112002** [comment]
Thanks for your update. Currently I remove the redirect by module.

**Comment by JKE-be** [comment]
Hello
For your information, we have changed the behavior in V8.
From now, we detect bot/crawler to avoid a redirection in the header/browser language.

For 'humans', if no cookie website_lang, we redirect to the browser language...
Else, we always respect the lang of the cookies...

So it will fix the bug of SEO, ... And improve the human behavior, because user will always see the website in the last language selected ! 

Commit : a696913

**Comment by exidoncom** [comment]
Well in my case it throws a 500 internal server error ;-(, My browser default language is english, I set spanish as default language, english and german as optional, I guess I did not translate any page yet. Any suggestions? compare http://exidon.com

**Comment by JKE-be** [comment]
Hi,

Oups ... it's strange...
Could you give me more information about your traceback in log...

Thank you

**Comment by exidoncom** [comment]
Sorry, how can I get the traceback, I have not such a window in the 500 error page as seen before in other contexts.

**Comment by JKE-be** [comment]
Hello,

I have just checked your website, and I see that the error is a bug with unicode decoding..
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128)

I check it now and let you know when I have a patch !

Sorry for the disagreement

**Comment by JKE-be** [comment]
Hi,

You have a very strange link under your video !

'''
 <small class="text-muted"><a href="/page/guía para recopilar la información necesaria">Cotiza</a> su proprio video promocional o de imagen corporativo!</small>
'''

This cause the error...
This page should not exist in Odoo because we slugify url ... /page/guía para recopilar la información necesaria...

Could you check if fixing your url, it help you ? 

Waiting your feedback

JKE

**Comment by exidoncom** [comment]
Wow, thank you very much, so a broken link causes 500-error in homepage, then? I guess, that should not be default behaviour, should it?  Is there any chance or module, I can make odoo showing up in website default language instead of browser-language? this en_US anyhow looks pretty ugly in URL; where would be .htaccess file in order to write some nice rewrite rules, I am also fearing of ranking, because my old URL-Structure got broke and I am about to loose a lot of link-juice for seo.

**Comment by JKE-be** [comment]
Happy to see that it works for you...
I note in my todo list to check it for the next time :) It's not really a broken link the problem, that was the accent in url.

If your are in local I can sent you a patch to disable the redirect. 

For the url broken, they exists a methos with attachment to specify a redirect between old url and new url.

Thank you for the reporting

Have fun with Odoo

JKE

**Comment by exidoncom** [comment]
Sure, that also bugged me, on demo deployment of odoo.com it seems already working fine, using accent when defining new website. If there is any patch (and how to apply) I would try first on a local deploy. Urls are kind of important for me, because I need to get found in google the organic way ;-).

**Comment by michaelkarrer81** [comment]
The Problem still exists if facebook crawls the page - Think you missed their crawler?!?

My default language is german - if i try the german link with CURL everything is correct now with your patch and i will get immedialtely the page content but if i try the same URL with the facebook debugger https://developers.facebook.com/tools/debug/og/object/ it will redirect me (302) to the en_US Version of the page! This makes linking to pages in facebook to odoo useless :(

**Comment by michaelkarrer81** [comment]
Here is the nginx access log:

31.13.99.112 - - [23/Apr/2015:17:58:25 +0200] "GET /blog/dadi-news-1/post/some-things-will-never-change-71 HTTP/1.1" 302 329 "-" "facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)"

31.13.99.112 - - [23/Apr/2015:17:58:25 +0200] "GET /en_US/blog/dadi-news-1/post/some-things-will-never-change-71 HTTP/1.1" 301 321 "-" "facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)"

31.13.99.112 - - [23/Apr/2015:17:58:26 +0200] "GET /en_US/blog/dadi-news-1/post/blognachricht-uberschrift-71 HTTP/1.1" 200 5024 "-" "facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)"

**Comment by JKE-be** [comment]
Hi,

Added in 6ced978

Thanks for the reporting !

**Comment by michaelkarrer81** [comment]
@JKE-be thank you very much for adding! Will this be merged in 8.0 branch too?

**Comment by JKE-be** [comment]
@michaelkarrer81 
Hi, sorry, it's a distraction error.
I cherry pick it in v8 (9f93a9ae1c98d9eea36b84c441fb87731df4f33b)

**Comment by auyeung112002** [comment]
@JKE-be 
The commit does not work for me. The website still returns 302 redirect.

I have tested my website with http://botsimulator.com using googlebot and vertified that is_a_bot() works correctly. I have set zh_TW as the default language. However, the request.lang is still en_US.

Below is the screen dump showing some key variables after running line 151 of website/models/ir_http.py

Thanks for your attention!

![image](https://cloud.githubusercontent.com/assets/8391358/8229524/6df57626-15ea-11e5-97e5-2cbbf8f7006b.png)

**Comment by JKE-be** [comment]
Hi @auyeung112002,

By default we try to find a lang similar to the request lang (Accept-Language)

So if you use google.com, it will crawl your website with en_us.
If your website have a lang en_*, it will be crawled in this lang else, in the default lang.

If you crawl with google.be, it will crawl your website with fr_BE.
If your website don't have a lang fr_*, it will be crawled in your default lang.

if you use your browser in zh_* it should be in your own lang

**Comment by auyeung112002** [comment]
Hi @JKE-be 
Thanks for your explanation. That means the program will return different language version depending on bot Accept-Language using 302 redirect. This method has its advantage since it will return appropriate language to bot, but the real problem is 302 redirect.

As far as I know, Google updated their crawling by adding locale-aware feature this year. It will improve the ability to crawl different language in the SAME url. However, we don't certainly know the effect when using 302 redirect on index page. The behavior of other search engines is unknown. As my experience, site ranking dropped by pages when having 302 redirect on index page.

**Comment by Himmawari** [comment]
Hi,

The module was finally created or not? Or Do I need to change file by file and line per line?

Thank youu!!

**Comment by JKE-be** [comment]
Hi @Himmawari 
Yes, all is published !
You can just pull/update to the last version

**Comment by Himmawari** [comment]
The last version has implemented all of this?  Because I have the last version. And now what would have to do?

**Comment by JKE-be** [comment]
Nothing except clear your cookies...

**Comment by Himmawari** [comment]
Mmm I have the same problem redirect 302 and I don't know how can I resolve it because I have the last version of Odoo and nothing has changed

@JKE-be When you say "You can just pull/update to the last version" Are you referring to the Odoo version or are you referring to patch of github?

Thanks

**Comment by ddfs** [comment]
get rid of all cookie detection part and it works perfectly. refer to URL only.

**Comment by auyeung112002** [comment]
@JKE-be Actually this problem is unresolved if the default language is not English. Also google webmaster guideline suggests not to redirect googlebot and real user differently.

Version: 8, 9

Step to reproduce:
1. Setup a new website.
2. Add a language(eg, zh_TW) and set website default language to that new language.
3. Use curl to load the website. (Accept-Language is empty, just like googlebot)

Expected Behavior:
Get a website in zh_TW.

Current Behavior:
Get a website in en_US.

![image](https://cloud.githubusercontent.com/assets/8391358/19103632/9ebd83a2-8b0a-11e6-9785-5ca37bf3604a.png)

**Comment by ddfs** [comment]
I have solved the problem at my end but includes a lot of other modifications so not sure it will be accepted as solution.

path: /

HTTP/1.1 200 OK
Server: nginx
Date: Mon, 10 Oct 2016 19:35:50 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Keep-Alive: timeout=1
Vary: Accept-Encoding
**Set-Cookie: website_lang=fi_FI; Path=/**
Cache-Control: no-cache, no-store, must-revalidate
Expires: -1
Pragma: no-cache
Vary: Accept-Encoding, User-Agent

path: /en

HTTP/1.1 200 OK
Server: nginx
Date: Mon, 10 Oct 2016 19:35:50 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Keep-Alive: timeout=1
Vary: Accept-Encoding
**Set-Cookie: website_lang=fi_FI; Path=/**
Cache-Control: no-cache, no-store, must-revalidate
Expires: -1
Pragma: no-cache
Vary: Accept-Encoding, User-Agent

**Comment by ITISAG** [comment]
hi ddfs and JKE-be, 

we would be happy if you share your experience since we are facing the same issue on odoo 10. How is teh cookie set to a different language? ddfs, we have already looked into the hreflang adaptation of yours. 

Many thanks

**Comment by ddfs** [comment]
@ITISAG in odoo-10, you should also check other modules inherits and overrides same functions.

hope that helps.

website/models/ir_http.py:

`  @classmethod
    def _dispatch(cls):`

website/controllers/website.py

`    #------------------------------------------------------
    # Business
    #------------------------------------------------------

    @http.route('/website/lang/<lang>', type='http', auth="public", website=True, multilang=False)
    def change_lang(self, lang, r='/', **kwargs):
        if lang == 'default':
            lang = request.website.default_lang_code
            r = '/%s%s' % (lang, r or '/')
        redirect = werkzeug.utils.redirect(r or ('/%s' % lang), 303)
        redirect.set_cookie('website_lang', lang)
        return redirect
`

**Comment by ITISAG** [comment]
Cool beans! This was quick!! 
Many thanks and Greetings to Finnland !! 



----- Ursprüngliche Mail -----

Von: "DD FS" <notifications@github.com> 
An: "odoo/odoo" <odoo@noreply.github.com> 
CC: "IT IS AG" <odoo@itis.de>, "Mention" <mention@noreply.github.com> 
Gesendet: Dienstag, 28. Februar 2017 20:27:42 
Betreff: Re: [odoo/odoo] [8.0 Website] SEO language issue (#5903) 


@ITISAG in odoo-10, you should also check other modules inherits and overrides same functions. 
hope that helps. 
website/models/ir_http.py: 
@classmethod def _dispatch(cls): 
website/controllers/website.py 
` #------------------------------------------------------ 
# Business 
#------------------------------------------------------ @http.route('/website/lang/<lang>', type='http', auth="public", website=True, multilang=False)
def change_lang(self, lang, r='/', **kwargs):
    if lang == 'default':
        lang = request.website.default_lang_code
        r = '/%s%s' % (lang, r or '/')
    redirect = werkzeug.utils.redirect(r or ('/%s' % lang), 303)
    redirect.set_cookie('website_lang', lang)
    return redirect 
`

**Comment by caiuka** [comment]
@ddfs Not understood your fix on the _dispatch method...do you intend to delete it?

**Comment by ddfs** [comment]
@caiuka taking out the cook_lang from equation does work. then it only relies on the path ( nearest_lang or default_lang  ) 

this is the entire dispatch method I have... ( additional conditions added since I have configurable language aliases enabled in base )

` 
   def _dispatch(self):

        first_pass = not hasattr(request, 'website')
        request.website = None
        handler = None

        try:
            # reroute if // in request path
            if request.httprequest.method == 'GET' and '//' in request.httprequest.path:
                new_url = request.httprequest.path.replace('//', '/') + '?' + request.httprequest.query_string
                return werkzeug.utils.redirect(new_url, 301)

            handler, arguments = self._find_handler()
            request.website_enabled = handler.routing.get('website', False)

        except werkzeug.exceptions.NotFound:
            # either we have a language prefixed route, either a real 404
            # in all cases, website processes them
            request.website_enabled = True

        request.website_multilang = (
            request.website_enabled and
            handler and handler.routing.get('multilang', handler.routing['type'] == 'http')
        )

        if 'geoip' not in request.session:
            record = {}
            if self.geo_ip_resolver is None:
                try:
                    import GeoIP
                    # updated database can be downloaded on MaxMind website
                    # http://dev.maxmind.com/geoip/legacy/install/city/
                    geofile = config.get('geoip_database')
                    if os.path.exists(geofile):
                        self.geo_ip_resolver = GeoIP.open(geofile, GeoIP.GEOIP_STANDARD)
                    else:
                        self.geo_ip_resolver = False
                        _logger.warning('GeoIP database file %r does not exists', geofile)
                except ImportError:
                    self.geo_ip_resolver = False
            if self.geo_ip_resolver and request.httprequest.remote_addr:
                record = self.geo_ip_resolver.record_by_addr(request.httprequest.remote_addr) or {}
            request.session['geoip'] = record

        cook_lang = request.httprequest.cookies.get('website_lang')

        if request.website_enabled:
            try:
                if handler:
                    self._authenticate(handler.routing['auth'])
                else:
                    self._auth_method_public()
            except Exception as e:
                return self._handle_exception(e)

            # request
            request.redirect = lambda url, code=302: werkzeug.utils.redirect(url_for(url), code)
            request.website = request.registry['website'].get_current_website(request.cr, request.uid,
                                                                              context=request.context)
            request.context['website_id'] = request.website.id

            # request path
            path = request.httprequest.path.split('/')

            # language and aliases
            langs = [lg[0] for lg in request.website.get_languages()]
            lang_aliases = [lg[1] for lg in request.website.get_language_aliases()]

            # language in request.path
            lang_path = None
            lang_path_redirect = False

            if path[1] in langs:
                lang_path = path[1]
                # redirect if given language not in aliases force redirect
                if lang_path not in lang_aliases:
                    lang_path_redirect = True
            elif path[1] in lang_aliases:
                lang_path = request.website.get_lang_from_alias(path[1])
            else:
                lang_path = request.website.default_lang_code

            if first_pass:
                # real or bot
                is_a_bot = self.is_a_bot()

                # language en_XX to en_US/en_GB
                nearest_lang = self.get_nearest_lang(lang_path)

                url_lang = nearest_lang and lang_path

                #
                # activate if auto language selection is desired
                #
                # if is_a_bot:
                #     preferred_lang = request.website.default_lang_code
                # else:
                #     preferred_lang = ((cook_lang if cook_lang in langs else False) or
                #                       self.get_nearest_lang(request.lang) or request.website.default_lang_code)
                #
                # request.lang = request.context['lang'] = nearest_lang or preferred_lang

                # activate if url language is desired
                request.lang = request.context['lang'] = nearest_lang or request.website.default_lang_code

                # if lang in url but not the displayed or default language --> change or remove
                # or lang in url but not as url_code --> redirect with 301
                # or no lang in url, and lang to dispay not the default language --> add lang
                # and not a POST request
                # and not a bot or bot but default lang in url
                if ((url_lang and (url_lang != request.lang or url_lang == request.website.default_lang_code)) or
                        (url_lang and lang_path_redirect) or (
                                not url_lang and request.website_multilang and request.lang != request.website.default_lang_code) and
                        request.httprequest.method != 'POST') and (
                            not is_a_bot or (url_lang and url_lang == request.website.default_lang_code)):

                    if lang_path_redirect:
                        redirect_code = 301
                        path.pop(1)

                        if lang_path != request.website.default_lang_code:
                            path.insert(1, request.website.get_alias_from_code(lang_path))

                        path = '/'.join(path) or '/'

                        if request.httprequest.query_string:
                            path += '?' + request.httprequest.query_string

                        return werkzeug.utils.redirect(path, code=redirect_code)

                elif url_lang:
                    path.pop(1)
                    return self.reroute('/'.join(path) or '/')

            # bind modified context
            request.website = request.website.with_context(request.context)

        result = base_ir_http._dispatch(self)

        if request.website_enabled and cook_lang != request.lang and hasattr(result, 'set_cookie'):
            result.set_cookie('website_lang', request.lang)

        return result
`

**Comment by caiuka** [comment]
@ddfs Oh great, now I understand! Thank you! 
And in change_lang controller method you only get rid of the default language? (the if  lang == 'default' statement)

**Comment by ddfs** [comment]
@caiuka  if lang == default, there is no point to keep it in url so pop it out and redirect/continue, thats odoo behavior. for cookie lang, same thing you can do and only rely on lang defined in url.

**Comment by popama** [comment]
@Himmawari I use version 9 and I confirm myself that 302 redirection is still available in this version.

I have two languages installed en_US and de_DE.
The default one is de_DE but when I access with incognito mode the redirection works because my browser language is english, so it make the redirection to /en_US. Let's say that this is well for users but in the end I was wonder how is this interpreted by search bots.

Also with the help of the search console tool, I noticed that most and the first indexes were for the routes /en_US although the default language is de_DE related to the route /.
My site's domain is currently associated with the target: Germany and first of all I expect pages indexed to be the default language which is not 'en_US'.

Also I made sure that `<link rel="alternate" hreflang="de" href="https://domain.de/"/>` and `<link rel="alternate" hreflang="en" href="https://domain/en_US/"/> ` are well rendered. 

I checked the header on my address with HTTP header checker tool and I found that there was few 
redirections which were also interpreted by search engines.

The manifest after I access the /:
https://domain.de/ with status 302 FOUND
http://domain.de/en_US/ with status 301 Moved Permanently
https://domain.de/en_US/ with status 200 OK

Because of that with help of @ddfs I discovered in method _dispatch(self) from website/models/ir_http.py the following condition is True
```
if ((url_lang and (url_lang != request.lang or url_lang == request.website.default_lang_code))
                or (not url_lang and request.website_multilang and request.lang != request.website.default_lang_code)
                and request.httprequest.method != 'POST') \
                and (not is_a_bot or (url_lang and url_lang == request.website.default_lang_code)):
                if url_lang:
                path.pop(1)
                if request.lang != request.website.default_lang_code:
                     path.insert(1, request.lang)
                     path = '/'.join(path) or '/'
                     redirect = request.redirect(path + '?' + request.httprequest.query_string)
                     redirect.set_cookie('website_lang', request.lang)
                     return redirect
```
The `path = request.httprequest.path.split('/')` returns 'en_US' and this I do not understand. But in the end it returns redirect which is `request.redirect(path + '?' + request.httprequest.query_string)`.

So for the moment I fix this by comment the condition block code mentioned above and the header now is 200 OK.
