### ISSUE TITLE
[Question] Does odoo keep a database connection open in a multitenant system?

### ISSUE THREAD

**Issue by clmno** [odoo/odoo#59046]
We know odoo can use the `dbfilter` - in the config file - for it to choose the right database when a new request comes in.

But does it keep the database connection open after the request is fulfilled (in its registry object)?

Let's say I have a system with 50 databases and `dbfilter=^%d$`. Here odoo will use the subdomain as the database filter and process the request. But I would like to know if it will keep the database connection open as a `registry object` so that every other request the comes from the same subdomain later on, doesn't have to open the connection, again.

Asking this because what if in my multi tenant architecture, certain DB's are used much less frequently than the others. Will keeping the database connection open be an expense?

This question was asked on SO too - [Does odoo keep a database connection open in a multitenant system?](https://stackoverflow.com/questions/64169770/does-odoo-keep-a-database-connection-open-in-a-multitenant-system)

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Comment by clmno** [comment]
Thank you @pedrobaeza . 
But there exist a label for questions, aptly named `question`. Could this be assigned the label `question` and be kept open? I'm yet to get a response from any sources I've asked the question on.

[Stackoverflow](https://stackoverflow.com/questions/64169770/does-odoo-keep-a-database-connection-open-in-a-multitenant-system)
[Odoo Forum](https://stackoverflow.com/questions/64169770/does-odoo-keep-a-database-connection-open-in-a-multitenant-system)
and github.

But as per you suggestion I've also raise a question on the mailing list (technical@mail.odoo.com)

**Comment by AjayViknesh** [comment]
Hi @pedrobaeza , even I am facing the multiple idle connections in odoo 13 multi tenant architecture.
Especially while editing the content through the website editor the connection is increasing from 4 -> 60 which is really huge.
And those connections are taking time to get closed which is affecting the performance of the database too.

Please let us know a solution for this.
Thanks.

**Comment by Yenthe666** [comment]
The label is for filtering out questions, which shouldn't be posted here. It is not used to label them so that we know what needs help/answers. The help forums exist for this. Please ask it on the official forums ;)
