### ISSUE TITLE
Issue with POS Cache module giving error due to "'datetime' is not JSON serializable" during cach write in odoo 14

### ISSUE THREAD

**Issue by parthjoshi90** [odoo/odoo#59043]
Impacted versions: Odoo 14

Steps to reproduce: install pos_cache module and during the write operation to cache it gives the error when all the data is being dumped using json.dump

Current behavior: Not able to get the Load the POS due to the above error

Expected behavior: The process of writing in cache for all the data should be done properly for all type of fields.

Video/Screenshot link (optional):
![Screenshot from 2020-10-03 15-22-16](https://user-images.githubusercontent.com/18608298/94988635-49675080-058c-11eb-8823-07ae2fb5a052.png)

**Comment by parthjoshi90** [comment]
currently solved by below approached
https://stackoverflow.com/a/22238613

**Comment by yelizariev** [comment]
fixed in https://github.com/odoo/odoo/commit/fd477f3f6d331355b5667a12b43d1c4a110b7e21
