### ISSUE TITLE
Point of Sale error Connection to printer failed

### ISSUE THREAD

**Issue by dishdoctor** [odoo/odoo#59059]
Impacted versions: 14 CE

Steps to reproduce: when you verify a POS order and print receipt through IoTBox (20_06) you get an error "Connection to the printer failed. Do you want to print using the web printer?"

The error comes up but then the receipt printer still prints the receipt.

On Odoo 14 SAAS POS using the IoT devices app I do not get an error.
Odoo 12CE and 13CE both print fine without error.
I have tried ssl and non-ssl servers, as well as local install on windows all get the same error.

Expected behavior: to be able to print without getting error

Video/Screenshot link (optional): https://drive.google.com/file/d/1Qy8jybcvqv2CUK92kZKr3l2DYgPwxXYD/view?usp=sharing

**Comment by dishdoctor** [comment]
Same issue on runbot

**Comment by anos4444** [comment]
Also same issue on odoo Mobile Application -Android ( tested) v14 EE

**Comment by dishdoctor** [comment]
Can someone look into this?

**Comment by dishdoctor** [comment]
@Yenthe666 can you assign this to someone who can fix the issue?

**Comment by dishdoctor** [comment]
also tested with iotbox 20_10.
Tested with two different printers (Epson and Star) Both work with odoo 12 and 13 no problem. 
I get the same error after printing receipt.

**Comment by dishdoctor** [comment]
reference to error "Do you want to print using the web printer"
found in:
addons/point_of_sale/static/src/js/Misc/AbstractReceiptScreen.js

odoo.define('point_of_sale.AbstractReceiptScreen', function (require) {
    'use strict';

    const { useRef } = owl.hooks;
    const { nextFrame } = require('point_of_sale.utils');
    const PosComponent = require('point_of_sale.PosComponent');
    const Registries = require('point_of_sale.Registries');

    /**
     * This relies on the assumption that there is a reference to
     * `order-receipt` so it is important to declare a `t-ref` to
     * `order-receipt` in the template of the Component that extends
     * this abstract component.
     */
    class AbstractReceiptScreen extends PosComponent {
        constructor() {
            super(...arguments);
            this.orderReceipt = useRef('order-receipt');
        }
      

  async _printReceipt() {

            if (this.env.pos.proxy.printer) {
                const printResult = await this.env.pos.proxy.printer.print_receipt(this.orderReceipt.el.outerHTML);
                if (printResult.successful) {
                    return true;
                } else {
                    const { confirmed } = await this.showPopup('ConfirmPopup', {
                        title: printResult.message.title,
                        body: 'Do you want to print using the web printer?',
                    });
                    if (confirmed) {
                        // We want to call the _printWeb when the popup is fully gone
                        // from the screen which happens after the next animation frame.
                        await nextFrame();
                        return await this._printWeb();
                    }
                    return false;
                }
            } else {
                return await this._printWeb();
            }
        }
        /**
         * https://stackoverflow.com/questions/21285902/printing-a-part-of-webpage-with-javascript
         */
        async _printWeb() {
            try {
                const isPrinted = document.execCommand('print', false, null);
                if (!isPrinted) window.print();
                return true;
            } catch (err) {
                await this.showPopup('ErrorPopup', {
                    title: this.env._t('Printing is not supported on some browsers'),
                    body: this.env._t(
                        'Printing is not supported on some browsers due to no default printing protocol ' +
                            'is available. It is possible to print your tickets by making use of an IoT Box.'
                    ),
                });
                return false;
            }
        }
    }

    Registries.Component.add(AbstractReceiptScreen);

    return AbstractReceiptScreen;
});

**Comment by dishdoctor** [comment]
if (printResult.successful) should be 
if (!printResult.successful)

**Comment by pimodoo** [comment]
@aprieels

**Comment by dishdoctor** [comment]
confirmed the error is gone once I added ! to if (printResult.successful)

if (!printResult.successful)

**Comment by dishdoctor** [comment]
When clicking the printer icon at the top of pos to print order details another error "connection to the printer failed" "Please check if the printer is still connected" pops up, and the printer proceeds to print as expected.

there maybe another typo somewhere, in the code. see linked photo.
https://drive.google.com/file/d/1bJ8ZI8omGLGzd_Ewa1kw3xJnckvI4orj/view?usp=sharing
