### ISSUE TITLE
Wrong reference for delivey note

### ISSUE THREAD

**Issue by jabirmisnedtech** [odoo/odoo#59057]
Impacted versions:
Version 13 and 14
Steps to reproduce:
When we create a sales order from the sales order calendar, the delivery note created from that sales order takes the summery as the reference which we were given on sales order calendar.

1. Open the sales order menu and click calendar view

2. Select the time slot. A popup window will appear to enter the summary (Pic 01 and 02).

3. Add some values and click Create. A new sales order will be created with the name whatever we give in the summary field.

4. Update sales order with required values and click confirm.

5. Now the sales order will update the name with the correct sales order sequence and generate a new delivery note. This delivery note will take the summery as its name. This name will not change even when we validated the delivery note. If the summary given is "/", then the delivery note generates a new sequence number.

Current behavior:
Whatever value given in the sales order calendar summery is taken as delivery note number.

Expected behavior:
Each delivery note should take the sequence we configured.

Video/Screenshot link (optional):
![01](https://user-images.githubusercontent.com/45730318/95010923-a834d480-0635-11eb-879f-9605f954117e.png)
![02](https://user-images.githubusercontent.com/45730318/95010926-aa972e80-0635-11eb-9714-6438e22d28c1.png)
![03](https://user-images.githubusercontent.com/45730318/95010927-ac60f200-0635-11eb-88fa-fea10d36808b.png)
![04](https://user-images.githubusercontent.com/45730318/95010928-aec34c00-0635-11eb-8bca-dc37a1a2ff7a.png)
![05](https://user-images.githubusercontent.com/45730318/95010931-b125a600-0635-11eb-8013-c3fe9e9e41c2.png)
![06](https://user-images.githubusercontent.com/45730318/95010932-b3880000-0635-11eb-9755-6ebade17efd2.png)
![07](https://user-images.githubusercontent.com/45730318/95010935-b5ea5a00-0635-11eb-9075-f7fc998af050.png)

**Comment by sswapnesh** [comment]
This is the Issue everywhere when you create new record from Calendar (Which is not Ideal way for this types of Record)
IMO, we should disable create Option from calendar view (In master)

What do you say @pedrobaeza  ?

**Comment by pedrobaeza** [comment]
Yes, difficult question for this kind of general concepts, but I think it can be alleviated through local options in each calendar. I'm tagging the specific team for they to think about it.

**Comment by sswapnesh** [comment]
Has been fixed in https://github.com/odoo/odoo/pull/58772 in 13.0 (https://github.com/odoo/odoo/pull/59080 for 14)

**Comment by pedrobaeza** [comment]
OK, let's close this. Thanks for the followup, @sswapnesh.
