### ISSUE TITLE
[8.0] Duplicate fied source document

### ISSUE THREAD

**Issue by nimeshcontractor** [odoo/odoo#5906]
Go to Purchase -> Call for bids.

Click on Create having SOURCE DOCUEMENT field two times.

![bid source doc](https://cloud.githubusercontent.com/assets/7592468/6798706/e15ae7f2-d235-11e4-9c31-9356b5dbc3b4.png)

Thanks,
Nimesh.

**Comment by rsi-odoo** [comment]
@nimeshcontractor, Can you check into the current ```master``` branch because It is fixed at 6b34dd9622ab87d707823da279df2c6b2220d0ef commit.
Thanks
