### ISSUE TITLE
Problem in sequence of call for Bids.

### ISSUE THREAD

**Issue by nimeshcontractor** [odoo/odoo#5907]
Hello,

Go to Purchase -> Purchase ->  Calls for Bids.

Now click on Create you will have Call for Bids Reference : TE00011 .
Now descard it withou entiring anything.

Now again click on create you will have Call for Bids Reference : TE00011 .

Even if we do not save the record it give us new sequence number.

Thanks,
Nimesh.

**Comment by Yenthe666** [comment]
Hi @nimeshcontractor,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
