### ISSUE TITLE
Import menu missing in Inventory/Products 

### ISSUE THREAD

**Issue by corradopagliarini-bikm** [odoo/odoo#59071]
Impacted versions: 14

Steps to reproduce: Open Inventory/Products; the Import menu is missing.

Current behaviour: Despite allowing the Import function in Settings, when opening Inventory/Products, the Import menu is missing.

Expected behaviour: Open Inventory/Products; the Import menu is present, and it is possible to import items massively.

Video/Screenshot link (optional):

![import_issue_1](https://user-images.githubusercontent.com/52817182/95055481-9ca7e300-06f3-11eb-92fb-d1cfd8c0c461.jpeg)
![import_issue_2](https://user-images.githubusercontent.com/52817182/95055482-9d407980-06f3-11eb-9895-e188323ab444.jpeg)

**Comment by pedrobaeza** [comment]
It's on favorites menu.

**Comment by corradopagliarini-bikm** [comment]
Thank you @pedrobaeza! ;-)
