### ISSUE TITLE
Documentation for Import needs to be updated

### ISSUE THREAD

**Issue by corradopagliarini-bikm** [odoo/odoo#59083]
Impacted versions: 14

Steps to reproduce: open https://www.odoo.com/documentation/user/14.0/general/base_import/import_faq.html

Current behaviour: https://www.odoo.com/documentation/user/14.0/general/base_import/import_faq.html is still saying that the Import menu is present

Expected behaviour: https://www.odoo.com/documentation/user/14.0/general/base_import/import_faq.html should say that the function to use is in Favourites

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
@mart-e who is responsible of this?

**Comment by mart-e** [comment]
This documentation is handled on https://github.com/odoo/documentation-user/ not here.
And the documentation content would probably be for @AntoineVDV (even if we still all pray for the return of the import button :pray: )

**Comment by AntoineVDV** [comment]
Hello @corradopagliarini-bikm,

As mart-e suggested, could you please open this again on https://github.com/odoo/documentation-user/ rater than here? The content team will then handle it ;)

**Comment by corradopagliarini-bikm** [comment]
Thanks @mart-e . I'm addressing the issue there

> This documentation is handled on https://github.com/odoo/documentation-user/ not here.
> And the documentation content would probably be for @AntoineVDV (even if we still all pray for the return of the import button 🙏 )

Thanks @mart-e  .
I'm addressing the issue on https://github.com/odoo/documentation-user/ .

**Comment by corradopagliarini-bikm** [comment]
> Hello @corradopagliarini-bikm,
> 
> As mart-e suggested, could you please open this again on https://github.com/odoo/documentation-user/ rater than here? The content team will then handle it ;)

Yes, of course ;-)
