### ISSUE TITLE
[ Odoo Failed ] Website CMS Home page bug

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#5909]
Regarding CMS website, 

By mistake home page removed then I try to recreate & set new page as first,
But after save new page, home page operate second page as home page newly created home page never run.

If newly created page as home, I try to set other sequence then it work, it seems other many issues their.

Please if you test during this bug and minor hidden configuration then share to community & test this bug & identify it.

Thanks

**Comment by Yenthe666** [comment]
Hi @tejastank ,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: Odoo 11 has a handy page overview just for these kind of cases!

Regards,
Yenthe

**Comment by tejastank** [comment]
Yes. in odoo 11.0 bug their, if website footer disable, complete website down, raise big bug .
Old clients migrated in #ERPNEXT, but new users also face till bugs in odoo.

Hope this time don't take 2/3 years to fix bug :)
