### ISSUE TITLE
[14.0] Product: Can't manually add product_name and product_code field values to product supplier info.

### ISSUE THREAD

**Issue by dangirasv** [odoo/odoo#59099]
Impacted versions:
14.0

Steps to reproduce:
Go to any Product record, click Purchase tab, click Edit.

Current behavior:
Since `product.supplierinfo` tree view does not have `product_name` and `product_code` fields displayed and since in v14.0 the tree view has [`editable="bottom"`](https://github.com/odoo/odoo/blob/338f8d843832c339c52c00c7f4c41b5ab2d696ed/addons/purchase/views/product_views.xml#L12) option, you can't manually add these field values anymore. In v13.0 you edited values in form view, which has these fields.

Expected behavior: 
Either missing fields should be added to tree view, or `editable="bottom"` removed so the fields could be accessed in editable form view.

Video/Screenshot link (optional):
![no_vendor_name_code](https://user-images.githubusercontent.com/46868659/95073966-629c0880-0716-11eb-89cb-44984f09144f.png)

**Comment by pedrobaeza** [comment]
Can't you add them through the 3 dots in the right part?

**Comment by dangirasv** [comment]
@pedrobaeza No, these two fields are [not among the optional fields in three view](https://github.com/odoo/odoo/blob/2d860cdddf29b9fbd1a5401082c9f743028d2fb5/addons/product/views/product_views.xml#L658).
![optional_fields](https://user-images.githubusercontent.com/46868659/95075099-4dc07480-0718-11eb-9a75-f5d090d531e1.png)

**Comment by pedrobaeza** [comment]
OK, then I think that should be the way to go.

@amoyaux @sle-odoo is this for you?

**Comment by amoyaux** [comment]
@pedrobaeza Yep, gonna do a quick fix.
FYI sle left odoo 2month ago.

**Comment by pedrobaeza** [comment]
Oh, I didn't have the occasion to say bye to him. I hope the best luck for him. Do you have then support from other people to know for pinging?
