### ISSUE TITLE
[8.0][POS] Bad tax code in case of a return product on the point of sale

### ISSUE THREAD

**Issue by adrienpeiffer** [odoo/odoo#5910]
Hi,

Here, a scenario on runbot 8.0

Steps to repoduce
-------------------------
- Go on runbot 8.0
- Logon as admin
- Click on point of sale menu
- Open Product submenu
- Open and edit a product  (Lays Natural 45g seems to be a good choice)
- Go on accounting page and add VAT-OUT-21-S taxe on customer taxes
- Click on save
- Open Your session submenu and create one or open an existing one
- Add the modified product on the order and change quantity to -1 (Case of product's return)
- Click on cash journal, fill in the amount and click on validate.
- Click on Close
- on Your session menu, click on Close session and Validate Closing & Post Entries
- Go on orders submenu
- Find and open your order
- Go an extra info page and open the related journal entry

Expected behavior
-------------------------
For the return product, you have to see a line on product account with a tax code '49 - Notes de crédit aux opérations du point II' and an other line on the tax account with the tax code '64 - TVA à recuperer sur notes de crédit delivrées'

Current behavior
-----------------------
The line on case 49 is present. Unfortunately, there is no line on case 64 but a ligne with the tax account '54 - TVA sur opérations des grilles [01], [02], [03]' .

Thanks !

**Comment by adrienpeiffer** [comment]
OPW 631303

**Comment by adrienpeiffer** [comment]
@fvdsn What do you think about this one ?

**Comment by chrisdec** [comment]
Hello, 

I also noticed an other problem with this journal entry. The amount on case 49 must be positif.

To prove that, you can try to make a credit note for a customer : Positive amount on case 49 and positive amount on case 64. 

Here we have, negative amount on case 49 and negative amount on case 54 --> Must be replaced by positive amount on case 49 and positive amount on case 64. 

Thanks

**Comment by adrienpeiffer** [comment]
Yes, I confirm the second problem described by @chrisdec. 
Any news about this issue ? This one looks pretty serious to me to have a correct VAT declaration.

**Comment by beledouxdenis** [comment]
Hello Adrien, 

This issue is solved in Odoo 8.0 from revision cb86fefc3a924abb185ff4a14eb375c202248595.

Regards,
