### ISSUE TITLE
[12.0 e] stock:  Incosistence in returned product with tracking

### ISSUE THREAD

**Issue by deivislaya** [odoo/odoo#59165]
**Impacted versions:**  12.0 e

**Steps to reproduce:**

1. Create a product with tracking By Unique Serial Number
2. Adjust inventory for the product e indicate its serials
3. Configure a type of picking, for its return **without** the options: Create New Lots / Serial Numbers and Use Existing Lots / Serial Numbers

![YourCompany-Delivery-Orders-Odoo](https://user-images.githubusercontent.com/5775695/95142187-2205b480-0741-11eb-8cb8-7a556da43694.png)

![YourCompany-Return-Odoo](https://user-images.githubusercontent.com/5775695/95142067-d2bf8400-0740-11eb-82a7-fee8ae7bbb54.png)
 
4. Make a product sale
5. After return the product
6. Try to sell the product again

**Current behavior:**

Product without Serial Number in picking return,  and the serial number continues to be located on the customer, on the other hand, in inventory adjustments if the withdrawal occurs, by entry without serial

![Product-Tracking-10-06-20-Odoo](https://user-images.githubusercontent.com/5775695/95146020-b7f20d00-074a-11eb-89a6-396ef372cd49.png)

**Expected behavior:**

Product with Serial Number, which is unique to the product
**Video/Screenshot link (optional):**

https://youtu.be/zeevwR416es 

 **OPW: #2352083**

**Comment by vava-odoo** [comment]
Linked ticket is closed
