### ISSUE TITLE
All website submenu are installed to the website's default main menu.

### ISSUE THREAD

**Issue by YnievesDotNet** [odoo/odoo#59164]
Impacted versions:
13

Steps to reproduce:
Create a module which includes website submenu like the following code:
```
<record id="menu_test" model="website.menu">
    <field name="name">Test</field>
    <field name="parent_id" ref="website.main_menu"/>
    <field name="sequence" type="int">20</field>
</record>
<record id="menu_test_dropdown" model="website.menu">
    <field name="name">Dropdown</field>
    <field name="url">/dropdown</field>
    <field name="parent_id" ref="menu_test"/>
    <field name="sequence" type="int">20</field>
</record>
```
Install the module.

Current behavior:
The submenu is installed to all website's default main menu. But both entries are at same level, both are children of "main_menu". All website submenu are installed to the website's default main menu.

Expected behavior:
The submenu "menu_test_dropdown" should be installed to its parent menu "menu_test" which is specified by the ref="menu_test"

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Comment by YnievesDotNet** [comment]
then, why that is not a issue? I write the correct method to create a submenu, but odoo assign the parent_id of website.main_menu at all menu entries, ignoring the assigned parent_id, that is a issue.

**Comment by pedrobaeza** [comment]
Because multi-website instantiates other records for final representation.

**Comment by YnievesDotNet** [comment]
ok, thanks
