### ISSUE TITLE
Send email of duplicated quote BEFORE save button is clicked sends the original quote

### ISSUE THREAD

**Issue by FrancoisKr** [odoo/odoo#59161]
Impacted versions: 13

Steps to reproduce:

- Create quote
- Duplicate quote
- Eventually change customer or a few things on duplicate
- Click "send by email", before saving the duplicated quote

Current behavior:
- The send email UI displays the duplicated quote data, but the recipient receives the original quote
- Also, the recipient receives the email in staging (did not try in dev)

Expected behavior:
- The recipient receives the duplicated quote OR it should not be possible to send the email before the user saves the duplicate
- In staging and dev branches the recipient should not recieve the email

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Can you please elaborate a video reproducing that behavior, as clicking on any button automatically saves the content, so the behavior you are describing is very odd.

**Comment by FrancoisKr** [comment]
I was able to replicate the problem once but can't anymore.

My customer has had the problem multiple times today. See attached screenshot.

Any ideas? I will try again to replicate the problem.
![odoo-quote-problem](https://user-images.githubusercontent.com/36109031/95118252-45812d00-074a-11eb-909f-81d09a1b439d.PNG)

**Comment by pedrobaeza** [comment]
OK, it's important to have the steps to reproduce it, as if not, it can't be solved. Maybe he/she has an slow connection and press send mail before finishing loading the duplicated record?

**Comment by GrupoAlvamex** [comment]
This happen, when you have a slow connection and click 2 times on save
button.

**Comment by pedrobaeza** [comment]
@GrupoAlvamex and can you record a video showing it?

**Comment by FrancoisKr** [comment]
Hi, figured it out: the user had saved a customized email template with the attachment of a previous quote and was calling back that template. So there is no bug, sorry for the hassle.
