### ISSUE TITLE
[8.0] last revision 56388-8-0-a70ea6 - maximum recursion depth exceeded

### ISSUE THREAD

**Issue by malatestay** [odoo/odoo#5916]
We have this error from last revision 56388-8-0-a70ea6 on loading odoo-server ! an idea ?

Exception RuntimeError: 'maximum recursion depth exceeded' in <function _remove at 0x7f053f207e60> ignored

**Comment by matthieuchoplin** [comment]
This issues duplicate other issues:
- https://github.com/odoo/odoo/issues/6141
- https://github.com/odoo/odoo/issues/6037

I think you should  close this issue and follow/ add comments on these issues where rco-odoo is already working on it.
