### ISSUE TITLE
view context with default_ does not recognize values before save

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#5920]
I noticed this thing:

For example I have a field like this (only tested with selection type) let say in sale.order.line:

``` python
test = fields.selection([('a', 'A'), ('b', 'B')], 'Test')
```

And have same field in sale.order:

``` python
test = fields.selection([('a', 'A'), ('b', 'B')], 'Test')
```

Then in xml when I fill something in one record that have one2many relation with another. And before saving that record I open to form of that one2many related new record (for example sale order line from sale order). And I wan't to fill that record with some values that were entered in main record (for example sale order). So in some xml:

``` xml
...
<field name="order_line" context="{'default_test': test}"/>
```

What happens, I see in a form that field was filled with wanted value (in my case that field is readonly). But when I try to save a record and check filled fields, I get warning that field was not entered.

And debugging it shows me this (calling print from sale.order.line):

``` python
print self.test
```

prints `False`

But if I implement onchange method to do exactly same thing (just to fill it when one2many related record was initially "created" (I mean when I open it from one2many field and filled it, but actually not create it yet) and then change for example `test` field value in sale.order to change for sale.order.line. It changes and printing it on check if it was filled, gives me this:

``` python
print self.test
```

prints for example `a`, meaning that value was caught before save. But why `default_` does not do the same? Is this intended?

This happened to me when implementing constraints check with and field value filling was done using fields context in a view as mentioned above:

``` python
@api.one
@api.constrains('test')
def _check_test(self):
    #passes if 'test' is filled from onchange, but does not pass if 'test' is filled with default_
    if not self.test:
        Warning('Test was not filled in sale.order.line')
```

**Comment by oerp-odoo** [comment]
Still no any answer?..

**Comment by tejastank** [comment]
Getting same issue.

**Comment by Yenthe666** [comment]
Hi @oerp-odoo,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
