### ISSUE TITLE
[13.0] stock: A serial number should only be linked to a single product in Customer Location 

### ISSUE THREAD

**Issue by thongthele** [odoo/odoo#59228]
**Impacted versions:** v13 (but probably others as well)

**Steps to reproduce:**
1. Create a product with tracking By Unique Serial Number
2. Make a product purchase, also generating the corresponding serial number
3. Make a product sale with the same serial number
4. Make a product purchase with the same serial number
5. Make a product sale with the same serial number

**Current behavior:**
A serial number should only be linked to a single product in Customer Location 

**Expected behavior:**
A serial number should only be linked to multi product in Customer Location, like Vendor Location

**Video/Screenshot link (optional):**

**Comment by pedrobaeza** [comment]
Duplicated of #57210

**Comment by thongthele** [comment]
@pedrobaeza no duplication, please read steps

**Comment by pedrobaeza** [comment]
I'm afraid it's the same, and won't be fixed in this version, having the roots in the same concept.
