### ISSUE TITLE
Send Emails and Discussions not found in V8

### ISSUE THREAD

**Issue by jorgenaranjoVauxoo** [odoo/odoo#5925]
Steps to reproduce
When you create a new document in some model, the document state is send to partners, this emails not should be send by emails. Only you should send email when create a discussion in document.
Document (sale order, invoice, etc..)
![](https://www.evernote.com/shard/s511/sh/ff7ecb8d-927d-4402-b9ef-5260b0a49d9b/d58ee0384e2ad742bd48181ef88219a0/deep/0/Customer-Invoices---Odoo.png)

Expected behavior
Send only emails and discussions to partners.
In the partners view, show this option. "Incoming Emails and Discussions"
![](https://www.evernote.com/shard/s511/sh/da5c505e-1f9c-4c63-afba-c0a158634c6e/91c0c37225eb6f5bb3a595560f1bc999/deep/0/Customers---OpenERP.png)
Image version 7.0

![](https://www.evernote.com/shard/s511/sh/aa965cb5-bc6b-4e0d-8b0f-662a4f0b592a/5c8fdd11848c75fd9c6df263b5ddfba7/deep/0/Odoo.png)
Image version 8.0

Current behavior
Send email, discussions and state of documents (Invoice created, Invoice validate ... etc.. but other models too).

Thanks !

**Comment by Yenthe666** [comment]
Hi @jorgenaranjoVauxoo,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
