### ISSUE TITLE
Wrong Incoming account entries for multi UoM

### ISSUE THREAD

**Issue by librevilzz** [odoo/odoo#5926]
Impacted versions:

-7.0

Steps to reproduce:

-Login as admin 
-Create Product A with :
  *Default UoM                        :Unit 
  *Purchase Unit of Measure   :Dozen(s) (bigger than reference unit-unit, ratio : 12)
  *Costing Method                   : Average 
  *average cost price               :100
  *Inventory Valuation              :Real Time (automated)

-Create PO for product A
  *qty  :1
  *UoM Dozen 
  *Unit Price : 1200
-confirm PO
-receive incoming

Current behaviour:
-generated journal entries with credit, debit = 14400
-when i set Costing Method to standard price, it generated correct journal entries = 1200

the problem is wrong calculation in generated accounting entries with credit, debit is 14400
system recalculate the dozen UoM where 1 \* 12 \* 1200 , and the average cost price  = 100 the calculation is correct

**Comment by niecw** [comment]
Linking my question in Odoo forum that describe the issue (last part) and the code in question: https://www.odoo.com/forum/help-1/question/what-is-the-proper-way-of-using-uom-and-uos-in-stock-move-85772

**Comment by Yenthe666** [comment]
Hi @librevilzz,

Thank you for your bug report.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by niecw** [comment]
It does not occur since v9.0 because the UoS fields have been dropped.
