### ISSUE TITLE
impossible to set invisible a field on a kanban view

### ISSUE THREAD

**Issue by rdeheele** [odoo/odoo#5936]
I want to set invisible the "Expected Revenues" label on the top of each crm stages. 
![image](https://cloud.githubusercontent.com/assets/7079268/6822373/76a46280-d2df-11e4-8025-6a1492e42203.png)
But set attribute invisible seems to have no effect.

Impacted versions:
- 8.0

Steps to reproduce:

Inherit a kanban view (e.g. crm.lead view) to set invisible the planned_revenue field.

``` xml
        <record id="crm_lead_kanban_view_inherit" model="ir.ui.view">
            <field name="name">Opportunities - Kanban - inherit</field>
            <field name="model">crm.lead</field>
            <field name="inherit_id" ref="crm.crm_case_kanban_view_leads"/>
            <field name="arch" type="xml">
                <field name="planned_revenue" position="attributes">
                    <attribute name="invisible">True</attribute>
                </field>
            </field>
        </record>
```

Current behavior:
- the field is always visible.

Expected behavior:
- the field shoud be invisible.

**Comment by a0c** [comment]
You should remove the `sum` attribute instead.

It is extracted by `kanban.js#instance.web_kanban.KanbanView#extract_aggregates()` function and added to group header by `web_kanban.xml#KanbanView.group_header` template (look for `class="oe_kanban_aggregates"`).

Here's the right way to remove aggregated header from Kanban view:
```xml
        <record id="crm_lead_kanban_view_inherit" model="ir.ui.view">
            <field name="name">Opportunities - Kanban - inherit</field>
            <field name="model">crm.lead</field>
            <field name="inherit_id" ref="crm.crm_case_kanban_view_leads"/>
            <field name="arch" type="xml">
                <field name="planned_revenue" position="attributes">
                    <attribute name="sum"/>
                </field>
            </field>
        </record>
```

**Comment by a0c** [comment]
If it solves your problem, please close the issue.
But don't delete it, as other people may google for it and would then see the answer immediately.

**Comment by Develoman** [comment]
Hi,
how can i put rating field readonly
this code don't work:
```
<record model="ir.ui.view" id="crm_lead1_kanban_view">
			<field name="name">Opportunities1 kanban</field>
			<field name="model">crm.lead</field>
			<field name="type">kanban</field>
			<field name="inherit_id" ref="crm.crm_case_kanban_view_leads" />
			<field name="arch" type="xml">
				<xpath expr="//field[@name='priority']" position="attributes">
					 <attribute name="readonly">1</attribute>					
				</xpath>
			</field>
		</record>
```
```
<xpath expr="//t/div/div/div/field[@name='priority']" position="attributes">
	<attribute name="readonly">1</attribute>					
</xpath>
```
thx

**Comment by Yenthe666** [comment]
It should be fixed as answered by @a0c - for these kind of questions you should go to odoo.com/help and ask it there.

**Comment by bunja100** [comment]
How to make some fields visible to login users and others?
