### ISSUE TITLE
[8.0] web_calendar sends ids as list of char

### ISSUE THREAD

**Issue by aristobulo-eezee** [odoo/odoo#5942]
To find the bug, use any debugger of your preference to evaluate type(ids) inside unlink method. 

When using calendar view, you will receive ids as list of char. Form and list view don't have the same behaviour.

This can generate issues when inheriting calendar.event unlink method and you use ids to do any other additional logic (searches), then using ids on any kind of domain like obj_b.search(cr, uid, [('event_id', 'in', ids)] doesn't return the same results when called from form/list and calendar views.

Can be caused by not parsing to int id at https://github.com/odoo/odoo/blob/8.0/addons/web_calendar/static/src/js/web_calendar.js#L852

**Comment by xmo-odoo** [comment]
Due to virtual identifiers for recurring events, calendar ids can often be not-numbers and not-database-ids.

**Comment by aristobulo-eezee** [comment]
Ok, maybe the error is not there, can you check calendar.py in calendar modules, al line 1748?

https://github.com/odoo/odoo/blob/8.0/addons/calendar/calendar.py#L1748

If what you say is correct, then at this point all logic to get event ids has been done, and regular unlink method is being called with ids_to_unlink as a list of char. Still, this is NOT correct.

**Comment by xmo-odoo** [comment]
`ids_to_unlink` is a list of ints, not a list of chars. The only items added to it are added [at line 1743](https://github.com/odoo/odoo/blob/8.0/addons/calendar/calendar.py#L1743) and explicitly forced to ints.
