### ISSUE TITLE
[13] Error with oauth authentication provider

### ISSUE THREAD

**Issue by davidmonterocrespo24** [odoo/odoo#59422]
Impacted versions:13

Steps to reproduce:
Configure the Facebook and Google authentication providers. If a user has the same email in his google and Facebook account, when he tries to enter with a different provider than the one that created his account, he will give an error accessing the database

*****ERRROR******
You do not have access to this database or your invitation has expired. 
Please ask for an invitation and be sure to follow the link in your "
invitation email.

Current behavior:

Expected behavior:

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/47928504/95340556-afedb680-088b-11eb-9c80-a16e58e15240.png)

**Comment by pedrobaeza** [comment]
AFAIK, this is something expected, as multi-sources for OAuth accounts is not allowed. Is this true, @odony ?

**Comment by odony** [comment]
> AFAIK, this is something expected, as multi-sources for OAuth accounts is not allowed.

Correct, we only store a single OAuth provider ID per user. The same "user ID" cannot be authenticated via different providers, as we have no guarantee that those IDs actually correspond to the same person. You could create your own OAuth2 service and allow users to choose their own ID without verifying their identity.

To be done safely it would therefore require an extra mechanism to allow a user to link an extra OAuth2 account on their existing user. That seems a bit overkill for such a rare use case.
