### ISSUE TITLE
Missing odoo-9.0rc20190424-l.noarch.rpm from repo 

### ISSUE THREAD

**Issue by Jaser01** [odoo/odoo#59424]
Impacted versions: 9.0 

Steps to reproduce: I went to http://nightly.odoo.com/9.0/nightly/rpm/ and verified that the listed file is missing 

Current behavior: Unable to install Odoo 9 

Expected behavior:

Video/Screenshot link (optional):
![Odoo Error](https://user-images.githubusercontent.com/72508219/95340948-c3951f00-0883-11eb-8558-f60dca2a4a72.JPG)

**Comment by pedrobaeza** [comment]
@d-fence, something to fix?

**Comment by d-fence** [comment]
I'm sorry to say that the 9.0 version is not supported anymore.
Only a few versions from the 1st of each month were kept there.
