### ISSUE TITLE
Manufacturing Orders: Cost Analysis is not working in multi-company

### ISSUE THREAD

**Issue by jva-odoo** [odoo/odoo#59500]
Impacted versions: V13

Steps to reproduce:

1. Create two company
2. check out at last created company
3. Create Manufacturing Orders
4. Print Cost Analysis report.

Current behavior:

Traceback

Expected behavior:

the print report in html

Extra Info:

This problem with action if qweb-html where cids is not passed so it gives an error.

Video/Screenshot link (optional):
![Screenshot 2020-10-08 at 4 51 07 PM](https://user-images.githubusercontent.com/34996524/95452977-ba8d7600-0987-11eb-9bbc-38b6bd9aeb0d.jpg)
![Screenshot 2020-10-08 at 4 51 13 PM](https://user-images.githubusercontent.com/34996524/95452992-bd886680-0987-11eb-9c47-6782a8192894.jpg)
![Screenshot 2020-10-08 at 4 51 16 PM](https://user-images.githubusercontent.com/34996524/95452995-be20fd00-0987-11eb-88ce-730e0020c43f.jpg)
![Screenshot 2020-10-08 at 4 51 34 PM](https://user-images.githubusercontent.com/34996524/95452997-beb99380-0987-11eb-86b6-9567d5760d5f.jpg)

**Comment by pedrobaeza** [comment]
Being an enterprise thing, please report it to odoo.com/help instead.

**Comment by jva-odoo** [comment]
@pedrobaeza ok Thank you
