### ISSUE TITLE
[13.0] Error in tax calculation

### ISSUE THREAD

**Issue by umiphos** [odoo/odoo#59563]
Impacted versions:
13.0 

### Steps to reproduce:

Create a tax with percentage amount add a group
Create a tax with fixed amount add a group
Create an invoice without an invoice_date
Add a line with first the fixed tax and then the percentage tax
Post it.
In the amount_by_group you can see that the amount is wrong for the second tax you add.

To "fix" this behavior you must add a date_due.

After this line the amount calculated by amount_by_group is affected
https://github.com/odoo/odoo/blob/d9f8efcc330bc7454411aad3546de663424724f7/addons/account/models/account_move.py#L2209

Error found in this runbot
https://runbot.odoo.com/runbot/bundle/vauxoo-dev-13-0-pre-merge-ubl-61562

### Video/Screenshot link (optional):

Check this video

[![IMAGE DESCRIPTION](https://img.youtube.com/vi/ftknLtMFQoE/sddefault.jpg)](https://youtu.be/ftknLtMFQoE "Showing the error in 5 minutes")

**Comment by nhomar** [comment]
este issue es inválido aquí
