### ISSUE TITLE
German Translation of a domain returns an error in the account.view_move_form View

### ISSUE THREAD

**Issue by aaly-dp** [odoo/odoo#59588]
Impacted versions:
14
Steps to reproduce:
Install German Translation -> change User Language to German -> got to Menu "Finanzen/Kunden/Rechnung"
Current behavior:
Error Message
Expected behavior:
No Error Message
Video/Screenshot link (optional):

The Issue can be solved if the translation is fixed in addons/account/i18n/de.po
Please use the following translation to fix the issue

#. module: account
#: model_terms:ir.ui.view,arch_db:account.view_move_form
msgid ""
"<span attrs=\"{'invisible': ['|', ('state', '!=', 'draft'), ('name', '!=', "
"'/')]}\">Draft</span>"
msgstr ""
"<span attrs=\"{'invisible': ['|', ('state', '!=', 'draft'), ('name', '!=', "
"'/')]}\">Entwurf</span>"

**Comment by pedrobaeza** [comment]
Duplicated: #59568

Please fix it in Transifex: https://github.com/odoo/odoo/wiki/Translations
