### ISSUE TITLE
[BUG][13.0] account: two methods with the same name in account.account model

### ISSUE THREAD

**Issue by thongthele** [odoo/odoo#59683]
**Impacted versions:** v13 (but probably others as well)

**Steps to reproduce:**

**Current behavior:**
Two methods with the same name in `account.account` model:

https://github.com/odoo/odoo/blob/50085b8db62fc7d58590ef4163520c40908d52c6/addons/account/models/account.py#L228-L229

https://github.com/odoo/odoo/blob/50085b8db62fc7d58590ef4163520c40908d52c6/addons/account/models/account.py#L293-L294

**Expected behavior:**

**Video/Screenshot link (optional):**

**Comment by sswapnesh** [comment]
I think we should merge both (Maybe in v14 as well)
Cc @qdp-odoo

**Comment by Yenthe666** [comment]
Probably nothing that is going to be changed in stable honestly. But yes should be removed in master.

**Comment by sswapnesh** [comment]
> Probably nothing that is going to be changed in stable honestly. But yes should be removed in master.

👁️  ...and it has been changed on v13

**Comment by Yenthe666** [comment]
Urgh, last times I made a PR for this it was completely denied. Nice.
