### ISSUE TITLE
CRM: "Log note" sends email to client

### ISSUE THREAD

**Issue by jpldcarvalho** [odoo/odoo#59681]
**Impacted versions:** 14

**Steps to reproduce:**
1. Create an opportunity
2. Open the opportunity page
3. Click "Log note"
4. Write a note and click "Log"

**Current behavior:**
The first note created is sent to the client instead being kept internal. After the first note, it will not send anything.

**Expected behavior:**
Send a notification for the followers of the opportunity apart of the client, using only the "Send message" to communicate with the client.

**Screenshot:**
![test](https://user-images.githubusercontent.com/5263301/95634756-864ab000-0a82-11eb-9f47-23c141bd598e.jpg)

**Comment by Yenthe666** [comment]
@jpldcarvalho this doesn't seem to happen on the latest 14.0 though. Can you reprduce it on a runbot?

**Comment by jpldcarvalho** [comment]
@Yenthe666, unfortunately, I can't reproduce on a runbot.
The bug happens with all the users in the database. Also, I've tested with a new database and there is no bug.
Do you have any idea how we can solve this issue without migrating the old database to a new one? (if you need access to our database, feel free to ask)

**Comment by pedrobaeza** [comment]
Probably, the subtype "Note" has unchecked the mark "Internal". Closing as no Odoo issue at all.

**Comment by jpldcarvalho** [comment]
Thank you very much @pedrobaeza

**Comment by DustyQuince** [comment]
I am having the same issue, and it is not the "Internal only" mark. This was closed prematurely

**Comment by Yenthe666** [comment]
@DustyQuince can you add a video / reproducable steps please? Then we will recheck.
