### ISSUE TITLE
[BUG] [14] When click on stock.production.lot record in the tree view! 

### ISSUE THREAD

**Issue by redapureskill** [odoo/odoo#59774]
Impacted versions: Odoo 14

Steps to reproduce: Click on any stock.production.lot record in the tree view to attend the form view

Current behavior: Bug, An error occurred

Expected behavior: attend the form view of the clicked 'lot' record 

Video/Screenshot link (optional):

![bug1](https://user-images.githubusercontent.com/9614843/95762073-2122d480-0ca5-11eb-84b9-f9f8e33b8146.png)
![bug2](https://user-images.githubusercontent.com/9614843/95762080-22ec9800-0ca5-11eb-9b5a-574e1dc6bf6c.png)

**Comment by sswapnesh** [comment]
Seems working well on Runbot

![Screenshot from 2020-10-12 22-01-48](https://user-images.githubusercontent.com/16624719/95770114-8b07a200-0cd6-11eb-862c-0721ecde00a1.png)
