### ISSUE TITLE
[13.0] payment: internal users can read all information integrated with payment acquirer via rpc

### ISSUE THREAD

**Issue by thongthele** [odoo/odoo#59816]
**Impacted versions:** v13 (but probably others as well)

Steps to reproduce:
ex. `payment_paypal` module:

https://github.com/odoo/odoo/blob/e9c54f6b3d5c36b658308e1900ab68dcc9de0357/addons/payment_paypal/models/payment.py#L24-L30

**Current behavior:**
Internal users can read all information integrated with payment acquirer via rpc. Users can use this information to create a refund payment, as such will not be secure.

**Expected behavior:**
Is there any reason?

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@tde-banana-odoo

**Comment by mart-e** [comment]
Hi,

Thanks for the report and analysis !
We consider that the employees have objectives aligned with their employer and are then usually trusted, they have higer priviledges. The access rights are modular at Odoo and each company is free to adapt them to what suits best their organisation.

However, we also recognise it is not always necessary to be open by default for some technical models. We are currently working to restrict all the access to these "meta-models" progressively (the 14.0 has already some removed from the 13.0). The payment acquiers are typically technical records that do not need to be accessible by every employee, we also plan to restrict the access to this one.
We will most likely remove the access at least in master, and maybe in stable if @nim-odoo is ok with it.
