### ISSUE TITLE
[14] sale: Error on Refreshing Forecasted Report page

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#59924]
Impacted versions: 14.0

Steps to reproduce: 
Open Forecasted Report from Sale order line
Refresh Page
![Screenshot from 2020-10-14 00-53-22](https://user-images.githubusercontent.com/16624719/95906385-ae564e00-0db7-11eb-8e79-89b84cd544a6.png)

![Screenshot from 2020-10-14 00-53-55](https://user-images.githubusercontent.com/16624719/95906445-c0d08780-0db7-11eb-98a4-6591191735eb.png)

Current behavior:
![Screenshot from 2020-10-14 00-52-40](https://user-images.githubusercontent.com/16624719/95906297-967eca00-0db7-11eb-8d32-d9f216c32325.png)

(It seems due to Wrong use of active_id in widget)

Expected behavior: Load correct Page

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
OPW `2372610`, didn't notice that PR yet but we'll see.

**Comment by ryv-odoo** [comment]
Fixed by svs
