### ISSUE TITLE
[14.0] Production Lot quantities do not update mid transaction.

### ISSUE THREAD

**Issue by richard-willdooit** [odoo/odoo#59929]
Impacted versions:

14, 13, 12, 11

Steps to reproduce:

In a routine - check the "product_qty' of a lot, validate a transaction, and retrieve the value of product_qty again.

Current behavior:

product_qty does not change

Expected behavior:

product_qty should change to reflect the validated move

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
I don't get the problem, but as you have put, I'm closing the issue and continuing through it.

**Comment by richard-willdooit** [comment]
@pedrobaeza 

The problem is, if you write a piece of code that looks up "product_qty", then it is not correct after a validate:

if lot.product_qty> 5 :
    m=create_move({product_uom_qty=5, lot_id=lot.id})
    m.validate()
    if lot.product_qty == 0:
        do_something

product_qty will never be 0, because inspecting "product_qty" again for the lot uses the cached value.
