### ISSUE TITLE
[14.0 odoo.sh]partner_autocomplete: Due to error not able to save form general settings (res.config.settings)

### ISSUE THREAD

**Issue by hareshkansara** [odoo/odoo#59933]
Impacted versions: 14.0 (odoo.sh)

Steps to reproduce: Install following applications: sales, purchase, contacts, inventory, invoicing, link tracker, calendar.
After installed, go to Sales > Configuration > Settings, and click on check box "Deliver Content by Email", at the time of clicking you will get error 

Current behavior: Error when click on some checkbox in sales general settings

Expected behavior: Whenever we tick any checkbox no error should be come

Video/Screenshot link (optional):
![1](https://user-images.githubusercontent.com/25735763/95943651-087d0080-0e04-11eb-82e2-336e0b3487b9.PNG)
![3](https://user-images.githubusercontent.com/25735763/95943676-16328600-0e04-11eb-8c95-c1df141fedea.PNG)
![2](https://user-images.githubusercontent.com/25735763/95943678-1763b300-0e04-11eb-8e96-272cf77f5083.PNG)

Video Link: https://drive.google.com/file/d/1XSYOq7aEDtomuxUChM9kKUt1pchmpSbA/view

**Comment by Yenthe666** [comment]
@hareshkansara can you also reproduce it on a runbot?

**Comment by hareshkansara** [comment]
No. Only in odoo.sh 14, but also i checked that in odoo.sh it only give error sometime not always. I am not sure due to installation of some other module. But i am sure this is not from any custom addons. This is odoo base error

**Comment by Yenthe666** [comment]
Hmm perhaps this is already fixed in the newest patches but they're not yet on SH 🤔 What do you think @pedrobaeza?
You could compare your SH view with the code on the latest 14.0

**Comment by hareshkansara** [comment]
Ok thanks

**Comment by pedrobaeza** [comment]
Isn't odoo.sh synchronizing when you make a new build? I don't know about how it works.

**Comment by Yenthe666** [comment]
Hmm no they do it on scheduled times, like once a week or so I believe. @hareshkansara let me know after comparing please :)

**Comment by hareshkansara** [comment]
code are same in odoo.sh and odoo github
