### ISSUE TITLE
[13.0] Stock: "You have not recorded done quantities yet ..." can not be translated

### ISSUE THREAD

**Issue by tanghulu0608** [odoo/odoo#59932]
Impacted versions:
13.0

Steps to reproduce:
Validate a stock picking without input done qty. Odoo shows a message.

Current behavior:
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/5561864/95937799-28fc8900-0e0b-11eb-8f93-4192c69d3116.png">

the Term seems can not be translated 

<img width="1352" alt="image" src="https://user-images.githubusercontent.com/5561864/95938181-ee472080-0e0b-11eb-8b71-bea149b78521.png">

The source code is here:
https://github.com/odoo/odoo/blob/43d3a73be3f11d8c3a9bcb6331a1669700f2f6c3/addons/stock/wizard/stock_immediate_transfer_views.xml#L9

Expected behavior:
"You have not recorded done quantities yet" can be translated

**Comment by Yenthe666** [comment]
@mart-e

**Comment by mart-e** [comment]
Hi,
The fact that a term is not present in the list of translated terms does not mean it is not translatable.
You have correctly identified the view where the code is present, you have to go to the view definition and there, click on the translate button.

It is also already translated on Transifex so maybe your install is not up to date.
https://www.transifex.com/odoo/odoo-13/translate/#zh_CN/stock/180743401?q=occurrence%3Aview_immediate_transfer
