### ISSUE TITLE
hr_holidays/hr_bel_holidays_2008.xml not used anywhere

### ISSUE THREAD

**Issue by alexis-via** [odoo/odoo#5993]
in v8, I just discovered that the file addons/hr_holidays/hr_bel_holidays_2008.xml is not used anywhere : it is not mentionned in `__openerp__.py` and doesn't seem to be used anywhere else. It is just an old thing of the past ? Is it given as an example ?

**Comment by JayVora-SerpentCS** [comment]
I remember when I worked on this module initially back in 2008! It was for demo data!

**Comment by Yenthe666** [comment]
Hi @alexis-via,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
