### ISSUE TITLE
can't save blog posts

### ISSUE THREAD

**Issue by peseotni** [odoo/odoo#59945]
Impacted versions: 14

Steps to reproduce: create new blog post, no save button

Current behavior: I can create a new blog post and put everything in, but there is no save button to save the work

Expected behavior: after finishing the blog, saving it.

Video/Screenshot link (optional):
![odoo14_blog](https://user-images.githubusercontent.com/22613392/95963649-3c5a2500-0e08-11eb-90a9-c4b96fdf5834.png)

**Comment by rdeodoo** [comment]
Hello, this is now working.
The screenshot is from a previous version, the topbar is now in the rightpanel.
