### ISSUE TITLE
[BUG][13.0] lang: error when only activating a language that is not English (US)

### ISSUE THREAD

**Issue by thongthele** [odoo/odoo#59940]
**Impacted versions:** v13 (but probably others as well)

**Steps to reproduce:**

1. Create a brand new Vietnamese database (using `-l vi_VN` and `--load-language=vi_VN`).
2. Install Contacts (`contacts`).
3. Under `Tuỳ chỉnh cá nhân` (as `Preferences`), then remove user’s language and click SAVE.

 **BUG 1:** 
4. Go to `Contacts` menu, then click the `Create` button.
5. Under `Contacts & Addresses` and click `Add` button.
6. An error occurred

**Traceback:**

Odoo Server Error
Traceback (most recent call last):
  File "/home/user/odoo-13/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/user/odoo-13/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/user/odoo-13/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/home/user/odoo-13/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/home/user/odoo-13/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/user/odoo-13/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/user/odoo-13/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/user/odoo-13/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/home/user/odoo-13/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/user/odoo-13/addons/web/controllers/main.py", line 1322, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/user/odoo-13/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/user/odoo-13/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/user/odoo-13/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/user/odoo-13/odoo/models.py", line 6159, in onchange
    record[name] = value
  File "/home/user/odoo-13/odoo/models.py", line 5698, in __setitem__
    return self._fields[key].__set__(self, value)
  File "/home/user/odoo-13/odoo/fields.py", line 1077, in __set__
    self.write(new_records, value)
  File "/home/user/odoo-13/odoo/fields.py", line 949, in write
    cache_value = self.convert_to_cache(value, records)
  File "/home/user/odoo-13/odoo/fields.py", line 2246, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for res.partner.lang: 'en_US'

 **BUG 2:**
7. Go to `Contacts` menu -> `Configuration` -> `Countries`.
8. I want to search `united states`, i use a search term as `united` and press `Enter` key.
9. Not found, I must use a different search term as `hoa kỳ` to get results

**Current behavior:**

**Expected behavior:**

**Video/Screenshot link (optional):**

**Comment by MjAbuz** [comment]
python version & OS? @thongthele

**Comment by thongthele** [comment]
@MjAbuz  I'm using python 3.7+ on Ubuntu 20.04 LTS

**Comment by MjAbuz** [comment]
Ubuntu 20.04 LTS recently upgraded their python version and I had some issues after an upgrade, Check this https://github.com/odoo/odoo/commit/61417ecaf75b6e4dc9c84fd21313cc251f600340 and this  https://github.com/odoo/odoo/commit/6c634c789061d95a56355e5617d5431fb4cacb48 @thongthele

**Comment by thongthele** [comment]
I checked it, but this is another issue.
The problem here will happen when only activating a language that is not English US, not just the Vietnamese. @MjAbuz

**Comment by MjAbuz** [comment]
@thongthele did you install this addon https://odoo-community.org/shop/product/onchange-helper-1716 ?

**Comment by MjAbuz** [comment]
@thongthele did you include translate_modules = ['all'] in your odoo config ?

**Comment by thongthele** [comment]
> @thongthele did you install this addon https://odoo-community.org/shop/product/onchange-helper-1716 ?
> @thongthele did you include translate_modules = ['all'] in your odoo config ?

Yes, i did.
I must use a different search term as `hoa kỳ` to search `United States`: @MjAbuz 
![Screenshot from 2020-10-19 07-21-22](https://user-images.githubusercontent.com/43790414/96389876-050ac000-11dc-11eb-9d5c-9d2cad587f48.png)

**Comment by MjAbuz** [comment]
If you installed onchange-helper then what I would suggest is remove that module and try, I did face issues for that addon when I was translating in BN and then always tried to avoid it @thongthele ... i guess in your error log this is where is the issue "File "/home/user/odoo-13/odoo/models.py", line 6159, in onchange
record[name] = value" .. is creating the conflict

**Comment by thongthele** [comment]
So I would suggest customer to avoid it, and there is not thing to do? @MjAbuz

**Comment by MjAbuz** [comment]
Just uninstall it and try @thongthele

**Comment by thongthele** [comment]
> Just uninstall it and try @thongthele

I uninstalled `onchange-helper` module, and i did face issues without it. @MjAbuz

**Comment by MjAbuz** [comment]
@thongthele did you make a pull from git for latest updates and then try it? It not then do that and check.. if not happening then you can try,
pg_dump, drop the old one and create a  fresh database from psql command and restore the dump in that then start the server with odoo-bin -c /etc/whereever ur odoo config -d "newly created database" --without-demo --update=all --stop-after-init then start the server and see if you get it back or not... before trying all this first update ur source from git first and try after then do this ... not sure about whether its gonna work or not.

**Comment by thongthele** [comment]
ok, i can try and feedback to you then @MjAbuz

**Comment by thongthele** [comment]
@MjAbuz it isn't work.
did you reproduce?

**Comment by MjAbuz** [comment]
@thongthele no..

**Comment by thongthele** [comment]
Why? Will you solve this issue? @MjAbuz

**Comment by MjAbuz** [comment]
@thongthele  I will try but later ...stuck with something ...will keep u posted

**Comment by MjAbuz** [comment]
@thongthele sorry for late response, I will try it now... one thing just popped up in my mind. You started facing this issue before uninstalling onchange-helper module or after when you install and then uninstalled. Try reinstall that addon then revert the changes to see if the issue get resolved. I am not facing any issue with Translation here.. so i guess its to deal with installing onchage-helper and uninstalling it.. i guess.

**Comment by thongthele** [comment]
@MjAbuz  I did face issues without onchage-helper, not with installing onchage-helper and uninstalling it.

**Comment by MjAbuz** [comment]
Did u install onchage-helper on this specific database? @thongthele if not had this on this specific DB server and uninstalled it? I am asking is because i guess installing and uninstalling of that add on could be causing the issue...

**Comment by MjAbuz** [comment]
@thongthele  I just used to web interface and created a new database selecting Vietnam as country and Vi language .. every thing works fine here... no error.
![Screenshot from 2020-10-21 11-10-06](https://user-images.githubusercontent.com/13909949/96676118-6b374480-138e-11eb-9dee-6aefd7cadfe8.png)
![Screenshot from 2020-10-21 11-14-13](https://user-images.githubusercontent.com/13909949/96676186-96219880-138e-11eb-8c54-124e3cf7a484.png)

**Comment by MjAbuz** [comment]
@thongthele  here are the steps as u said .. i performed here ... no error 
![Screenshot from 2020-10-21 11-20-21](https://user-images.githubusercontent.com/13909949/96676616-8c4c6500-138f-11eb-8249-c2a9eb84167b.png)
![Screenshot from 2020-10-21 11-20-11](https://user-images.githubusercontent.com/13909949/96676625-92424600-138f-11eb-9448-c7c1adfa3512.png)

**Comment by MjAbuz** [comment]
@pedrobaeza I see no issues with odoo13 on on my ubuntu 20.4 python 3.8.3 vi_VN

**Comment by thongthele** [comment]
> ![Screenshot from 2020-10-21 11-20-11](https://user-images.githubusercontent.com/13909949/96676625-92424600-138f-11eb-9448-c7c1adfa3512.png)

Under `Contacts & Addresses` tab and click `Add` button, please @MjAbuz

**Comment by thongthele** [comment]
Go to Contacts menu -> Configuration -> Countries.
Search `united states`, i use a search term as `united` and press `Enter` key. @MjAbuz

**Comment by MjAbuz** [comment]
I followed as u said @thongthele , united dont give me any result and NO ERROR too, US gives me United States 
![Screenshot from 2020-10-21 13-32-52](https://user-images.githubusercontent.com/13909949/96688751-587b3a80-13a3-11eb-876c-f4ea848f0d0f.png)
![Screenshot from 2020-10-21 13-33-11](https://user-images.githubusercontent.com/13909949/96688795-629d3900-13a3-11eb-8cc6-522eb60be9e8.png)
![Screenshot from 2020-10-21 13-38-21](https://user-images.githubusercontent.com/13909949/96688813-66c95680-13a3-11eb-9560-70f588866d33.png)

**Comment by MjAbuz** [comment]
@mart-e I guess you should look into this? I see no issues

**Comment by thongthele** [comment]
click `Add` button in Contacts & Addresses tab, please @MjAbuz

![96688795-629d3900-13a3-11eb-8cc6-522eb60be9e8](https://user-images.githubusercontent.com/43790414/96689292-6b463d00-13ac-11eb-97ec-4df1fbf482de.jpg)

**Comment by MjAbuz** [comment]
Oh man @thongthele ... why wouldn't you get an error.. cause there is no value for your language preference... you need to activate en_US first to save the value .... 
![Screenshot from 2020-10-21 13-56-41](https://user-images.githubusercontent.com/13909949/96690261-45696a00-13a5-11eb-977e-3b21d71b071b.png)
![Screenshot from 2020-10-21 13-59-40](https://user-images.githubusercontent.com/13909949/96690623-bdd02b00-13a5-11eb-90d2-659d2a27aaa2.png)
![Screenshot from 2020-10-21 13-59-08](https://user-images.githubusercontent.com/13909949/96690627-be68c180-13a5-11eb-97d0-55c293795855.png)

**Comment by thongthele** [comment]
oh right, when english US is archived, an error occurred @MjAbuz

**Comment by MjAbuz** [comment]
> oh right, when english US is archived, an error occurred @MjAbuz

so u know what to do now :100:

**Comment by thongthele** [comment]
@MjAbuz there is not thing to do?

**Comment by MjAbuz** [comment]
> @MjAbuz If only activating a language that is not English? there is not thing to do?

@thongthele , Its because your language preference is empty, so obviously it will through error.

**Comment by pedrobaeza** [comment]
Any emtpy language preference defaults to "English", so having it disable leads to an error.

This is then a configuration error, so please fix it on your side, but not an Odoo error itself. The handling of the fallback language has to be improved though, but this is something on the roadmap.

**Comment by MjAbuz** [comment]
@pedrobaeza I guess my advice should get a :+1:
