### ISSUE TITLE
encoding bug

### ISSUE THREAD

**Issue by billlv** [odoo/odoo#5994]
hi,  my english pool
app module description  (index.html file) , have an encoding bug
on base/module/module.py 
func: _get_desc (line 174)  need add doc = doc.decode('utf8', 'ignore')

**Comment by Yenthe666** [comment]
Hi @billlv,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
