### ISSUE TITLE
[14.0] Can not edit Invoice Sequence

### ISSUE THREAD

**Issue by haconsult** [odoo/odoo#59969]
Impacted versions:

- v14

Steps to reproduce:

- Install accounting app
- Enable developer mode
- Go to: Settings → Technical → Sequences

Current behavior:

- No entry for Invoice Seqences

Expected behavior:

- Some way to customize Invoice Sequences

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
@haconsult Sequence of Invoice is being managed by _SequenceMixin_

https://github.com/odoo/odoo/blob/14.0/addons/account/models/sequence_mixin.py

For changing Sequence of Invoices You can do it by this way

![72](https://user-images.githubusercontent.com/16624719/95998549-9c75b900-0e52-11eb-8934-dee8abdd3839.gif)

**Comment by sswapnesh** [comment]
You can change them by `sequence_override_regex`

https://github.com/odoo/odoo/blob/14.0/addons/account/models/account_journal.py#L112

**Comment by haconsult** [comment]
Thanks!
