### ISSUE TITLE
Stock Picking not continuing even if lines have been set to done

### ISSUE THREAD

**Issue by jethroguce** [odoo/odoo#59975]
https://github.com/odoo/odoo/blob/5a621cea4c5a16998a3b83890144f81a3880244b/addons/stock/models/stock_picking.py#L851

i think this should have a validation that there's atleast one record, checking an empty `all([])` returns True

**Comment by pedrobaeza** [comment]
Please explain any step to reproduce a problem, base on real case, not on reading code guesses.
