### ISSUE TITLE
[master] Website builder background color selector

### ISSUE THREAD

**Issue by alejandrosantana** [odoo/odoo#600]
When adding a block using the website frontend, you can choose several backgrounds.
But in "**Customize > Background > Uniform color**" you have a limited amount of colours available. It would be nice to be able to specify a hexadecimal RGB colour (#f5f5f5), allowing to match customers specific corporative colors. (Similar as "Choose an image..." option).

***Impacted versions:***

 - master
 - Probably SaaS with webbuilder

***Steps to reproduce:***

 1. Log in
 2. Access the website frontend
 3. Hit "Edit" button
 4. Click in a block "Customize" option and go to "**Customize > Background > Uniform color**"

***Current behavior:***

 - Limited options for "**Customize > Background > Uniform color**"

***Expected behavior:***

 - There should be a "Customize > Background > Uniform color > **Choose your color...**" that let you specify a hexadecimal colour (i.e.: #f5f5f5)
 - This simple thing would allow customers to use their own specific corporate colour, which is a much desired feature sometimes.

**Comment by jl2035** [comment]
Also some instructions on how to add your colors would be nice... anyone?

**Comment by Yenthe666** [comment]
Dear @alejandrosantana,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe

**Comment by jl2035** [comment]
Solution for Odoo 8: https://www.odoo.com/forum/help-1/question/is-it-possible-to-add-more-colours-to-uniform-colour-of-block-background-75186

But I need to do this in Odoo 9. I'm asking here: http://stackoverflow.com/questions/40016934/odoo-website-editor-how-to-add-custom-colors
