### ISSUE TITLE
hr.leave multi company global rule

### ISSUE THREAD

**Issue by gbaumgartner-callino** [odoo/odoo#60011]
Impacted versions: 12.0

Steps to reproduce: Add leaves within a multi company setup with little regard for "holiday_status_id", access holiday calendar with a user in a different company than the employees in the leave record.

Current behavior: In a multicompany setup Odoo tries to load leaves from employees not in the current users company. For example in the leave calendar view. Raising an AccessError cause empoyee record is not readable.

Expected behavior: Leaves should be accessed with consideration of the employee access.

I'm proposing the domain of this security reord to use employee_id instead of holiday_status_id:
`<record id="hr_leave_rule_multicompany" model="ir.rule">
<field name="name">Leaves: multi company global rule</field>
        <field name="model_id" ref="model_hr_leave"/>
        <field name="global" eval="True"/>
        <field name="domain_force">['|', ('employee_id.company_id', '=', False), ('employee_id.company_id', 'in', [user.company_id.id])]</field>
    </record>`

I don't really see any advantages to use company of 'hr.leave.type' in the rule.

**Comment by pedrobaeza** [comment]
Duplicated of #45246, but I didn't do the PR. Can you?
