### ISSUE TITLE
Bank statement reconciliation: Base amount wrong in currency when tax is included

### ISSUE THREAD

**Issue by bringsvor** [odoo/odoo#6003]
Using the new Odoo 8 bank statement GUI I have discovered the following bug:

I have USD as company currency, and a journal in NOK.

So I enter a statement line of 1000 NOK. I click reconcile and use a statement operation that has a tax that is 25% VAT included.

Then I check the journal entry.
1. The bank account (journal account) is credited with amount currency NOK 1000. USD 128.44. Good.
2. The VAT account is debited with amount currency NOK 200.01 and USD 25.69. Quite good.
3. The expense account is debited with amount currency NOK 1000.00 and USD 102.75. Not so good. The USD amount is fine, but the NOK amount should have been subtracted the VAT amount, so it should be 800 or 799.99 or something.

This is a bit of a showstopper for the customer, they rely heavily upon multi currency posting.

**Comment by fclementic2c** [comment]
seems to behave correctely on the last runbot instance.

Check out my test here : http://57402-8-0-020caa.runbot.odoo.com/web?db=57402-8-0-020caa-base#page=0&limit=80&view_type=list&model=account.move.line&active_id=4

**Comment by bringsvor** [comment]
Pardon my ignorance, but how do I log on to this instance?

Anyway, this is what happens my end:

![image](https://cloud.githubusercontent.com/assets/7498104/6868024/4631546e-d488-11e4-91fe-421b56e8a7ba.png)

![image](https://cloud.githubusercontent.com/assets/7498104/6868034/6259b316-d488-11e4-84bb-12ed49710d5c.png)

**Comment by fclementic2c** [comment]
yep, it does not look good at you end.

to connect go to http://runbot.odoo.com/runbot
click on the blue button (instance 57402-8-0-020caa )
login : admin  password admin
choose the db ending by -base

[image: Images intégrées 1]



*camptocamp*

INNOVATIVE SOLUTIONS
BY OPEN SOURCE EXPERTS

*Frédéric Clementi*
Project Manager
Business Solutions

+41 21 619 10 41

www.camptocamp.com


2015-03-27 13:53 GMT+01:00 Torvald Baade Bringsvor <notifications@github.com

**Comment by bringsvor** [comment]
The problem is there in the runbot too. But the journal view when you click journal items from the bank statement doesn't have the amount currency column.

If you go to journal entries and look for TUBK/2015/0002/1 it is the same problem.
![image](https://cloud.githubusercontent.com/assets/7498104/6868526/99fc5afe-d48c-11e4-918f-16937017fa78.png)

**Comment by fclementic2c** [comment]
Good catch. I fully agree.
@qdp-odoo : You should have a look at this one -> the 100 USD are wrong.

Thanks

**Comment by bringsvor** [comment]
Thanks. I tried to see if I could fix it myself but it seems to be stuck somewhere in Javascript and there I must plead incompetence, regrettably.

**Comment by Whisno** [comment]
Hi,
I don't currently have time to solve this but I might have some elements of solution. The problem probably comes from the fact that the creation of move lines corresponding to taxes is not centralized.

In the case of invoices, it happens there : https://github.com/odoo/odoo/blob/master/addons/account/account_invoice.py#L780

In the case of bank statement reconciliation, it happens in account_move_line.create() following this path (passing account_tax_id) : https://github.com/odoo/odoo/blob/master/addons/account/static/src/js/widgets.js#L1700 -> https://github.com/odoo/odoo/blob/master/addons/account/account_bank_statement.py#L878 -> https://github.com/odoo/odoo/blob/master/addons/account/account_move_line.py#L1337

**Comment by Yenthe666** [comment]
Hi @bringsvor,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
