### ISSUE TITLE
[14.0] Database fetch misses ids (('2',)) and has extra ids ((2,)), may be caused by a type incoherence in a previous request

### ISSUE THREAD

**Issue by hajajroshan** [odoo/odoo#60040]
Impacted versions:
14.0

Current behavior:
When try to create a record it shows this warning

![image](https://user-images.githubusercontent.com/62367855/96031927-9f38d400-0e7b-11eb-81de-37bb835e051f.png)

getting self value-> hospital.application('2',) in the function def _read(self, fields): from models.py

**Comment by pedrobaeza** [comment]
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.

Tip: this seems a browse with an incorrect type in the passed id.
