### ISSUE TITLE
Mail Delivery Failed

### ISSUE THREAD

**Issue by mustafa-almulla** [odoo/odoo#6005]
I am getting this issue when trying to send an email from Odoo 8? what could be the problem and is there any solution?

Mail Delivery Failed

Mail delivery failed via SMTP server 'box1028.bluehost.com'.
SMTPRecipientsRefused: {'agallaf@sam-it.biz': (550, 'Verification failed for bounce-34-res.users-9@192.168.1.14\nThe mail server could not deliver mail to bounce-34-res.users-9@192.168.1.14. The account or domain may not exist, they may be blacklisted, or missing the proper dns entries.\nSender verify failed')}

**Comment by pvanthony** [comment]
Please check the setting at Setting > Configuration > General Settings > Email > Alias Domain.

On my odoo V8, sending an email seems to be working.

**Comment by mustafa-almulla** [comment]
@pvanthony thank you for your response, the strange thing is I have two instances of odoo running on different servers, on one of them is working with no issue, but in the second one I am facing this issue. I am trying to understand why I am getting two different behaviors

**Comment by Hongxingdu** [comment]
Me too. One is working perfectly, and the other one is just not working. They are same version even. I guess just some minor error of configuration, but where is it?

**Comment by CRDeveloper** [comment]
Hi,

One of my client's server was also refusing to send emails, look if the email server has the setting "Sender Verification" enabled. Ask for support with your host!

Check WHM:
Exim Configuration Manager -- ControlF for "Sender Verification"
disable => senders verifications

**Comment by Yenthe666** [comment]
Hi guys,

This was absolutely a configuration issue. As Odoo 8 is no longer supported I'm closing this.

Regards,
Yenthe

**Comment by buketseker** [comment]
Hello,
I encountered the same problem. Mail authentication is success but don't send mail on Odoo.
How to fix the same error? Thanks
