### ISSUE TITLE
Latest CE not installable

### ISSUE THREAD

**Issue by kwoot** [odoo/odoo#60053]
Impacted versions:
v12

Steps to reproduce:
on ubuntu 20.04: dpkg -i /root/odoo_12.0.latest_all.deb

Current behavior:
See error log below

Expected behavior:
That the package gets installed.

Video/Screenshot link (optional):

dpkg -i /root/odoo_12.0.latest_all.deb 
Selecting previously unselected package odoo.
(Reading database ... 110936 files and directories currently installed.)
Preparing to unpack /root/odoo_12.0.latest_all.deb ...
Unpacking odoo (12.0.20201015) ...
Setting up odoo (12.0.20201015) ...
/usr/lib/python3/dist-packages/odoo/addons/account/models/account.py:1018: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.amount_type is not 'group':
/usr/lib/python3/dist-packages/odoo/addons/base/models/res_config.py:609: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if method.startswith('set_') and method is not 'set_values':
/usr/lib/python3/dist-packages/odoo/fields.py:2896: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if size is 0:
/usr/lib/python3/dist-packages/odoo/fields.py:2898: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif size is 1:
/usr/lib/python3/dist-packages/odoo/tools/misc.py:1153: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if not digits and digits is not 0:
Created symlink /etc/systemd/system/multi-user.target.wants/odoo.service → /lib/systemd/system/odoo.service.
Processing triggers for systemd (245.4-4ubuntu3.2) 

Database name is "--init" and owned by user odoo. Weird.

**Comment by hajajroshan** [comment]
Odoo 12 is not support Python 3.8 above versions. Ubuntu 20.04 Python 3.8 or above versions. So either you configure odoo with Python 3.5 or Downgrade to Ubuntu 18.04

**Comment by kwoot** [comment]
I do not see the email reply I got here so I will paste it: 

Odoo 12 is not support Python 3.8 above versions. Ubuntu 20.04 Python 3.8 or above versions. So either you configure odoo with Python 3.5 or Downgrade to Ubuntu 18.04

**Comment by kwoot** [comment]
Thanks.
