### ISSUE TITLE
Don't understand property_stock_production 

### ISSUE THREAD

**Issue by kkoci** [odoo/odoo#6007]
Hi

I'm noticing a weird behavior IMHO, when I manufacture whatever product, no matter what I choose into production order, as a location_dest, it always "sends" the raw materials into the actual product 'property_stock_production' field, ie: virtual locations/production, or whatever location is specified on the actual product as a production location.

This was also possible into v7 Odoo, BUT if I specify another location_dest in the mrp production order, it always sends raw materials into THAT location, not forcing the workflow to use the product's 'property_stock_production' no matter what.

Also into production order, I don't see the internal move of the production, it should create an internal movement for that matter.

I'm sorry but this is confusing, anyone has some idea of what am I missing here?

Thanks in advance!

**Comment by Yenthe666** [comment]
Hi @kkoci,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
