### ISSUE TITLE
[master] Database manager: db selector in duplicate

### ISSUE THREAD

**Issue by alejandrosantana** [odoo/odoo#601]
In the database manager, the "duplicate" tool should have a database drop-down selector for field "**Original database name**", the same way it exists in "drop" and "backup" tools.

That would make it much easier to perform the duplication, and make the user happy to not copy the database name from the URL (is there anywhere else where I can select and Ctrl+C) and then go back to the database manager.

***Impacted versions:***

 - 7.0 and beyond, including master

***Steps to reproduce:***

 1. Access the "database manager"
 2. Go to "Duplicate" manu
 3. Take a look to the "**Original database name**" field: text field (while in "Drop" and "Backup" it is a drop-down where you can select one of the available databases)

***Current behavior:***

 - In "Duplicate" menu, the "**Original database name**" field is just a text field 

***Expected behavior:***

 - In "Duplicate" menu, the "**Original database name**" field shuold be a drop-down where you can select one of the available databases (same as in "Drop" and "Backup").

**Comment by Yenthe666** [comment]
Dear @alejandrosantana,

Thank you for reporting this issue!
It has been fixed in the meanwhile and we no longer support issues for V7 and below. Consider this done 😉 

Regards,
Yenthe
