### ISSUE TITLE
Product template search view wrong behavior

### ISSUE THREAD

**Issue by diegomor** [odoo/odoo#6011]
In product template search view is defined a field to do search by product attributes:

```
 <field string="Product Variant" name="product_variant_ids" filter_domain="['|', ('product_variant_ids.name','ilike',self), ('product_variant_ids.attribute_value_ids.name','ilike',self)]"/>
```

product_variants_ids is a one2many field in product.template. When I write some attribute value, it brings the correct record, but if I write the atrribute name, it brings nothing, for example, in attribute page for some product I have:

MEMORY      32GB
COLOR      red

If I type 32gb, it brings record, whereas if I type MEMORY, brings nothing

Can any one help me?

**Comment by Yenthe666** [comment]
Hi @diegomor,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
