### ISSUE TITLE
Event Module: When event is confirmed, no email sent out.

### ISSUE THREAD

**Issue by pvanthony** [odoo/odoo#6012]
Using odoo from odoo.com, the event module has a bug.
The same bug is also there when odoo is installed locally using git.

When the event is confirmed, there is no email sent to the confirmed registrants to inform them that the event is confirmed and will go on.

There is a default event confirmed email template, but it is not being sent out.

Has anyone experienced this as well.

**Comment by Yenthe666** [comment]
Hi @pvanthony,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
