### ISSUE TITLE
Event Module: Confirmed registration "from" email address is wrong.

### ISSUE THREAD

**Issue by pvanthony** [odoo/odoo#6013]
When a customer has confirm a registration for an event, the confirmation email's 'from' address is wrong. It shows the company address instead of the selected email address.

This can be solved by changing the template from,

```
${(object.user_id.email or object.company_id.email or 'noreply@' + object.company_id.name + '.com')|safe}
```

to

```
${(object.event_id.reply_to or object.company_id.email or 'noreply@' + object.company_id.name + '.com')|safe}
```

**Comment by pvanthony** [comment]
Not sure if I should close this issue because the bug is also at odoo.com

**Comment by armandov91** [comment]
Hi there, please also check other module templates like sale order,
FROM:${(object.user_id.email or '')|safe}
it shows company email  but if you leave blank it show the user email.

Also  in:
REFERENCES
  Order number: ${object.name}
  Order total: ${object.amount_total} ${object.pricelist_id.currency_id.name}
  Order date: ${format_tz(object.date_order, tz=user.tz, context={'lang':object.partner_id.lang})} 
% if object.origin:   Order reference: ${object.origin}
% endif % if object.client_order_ref:   Your reference: ${object.client_order_ref}
% endif % if object.user_id:   Your contact: ${object.user_id.name} % endif
(In the hyperlink on object.user_id.name it shows company email not salesperson email)

This is in the sale order-send by email template.

**Comment by Yenthe666** [comment]
Hi @pvanthony,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
