### ISSUE TITLE
Model Constraint fails because it uses an old value

### ISSUE THREAD

**Issue by Fritzlseppl** [odoo/odoo#60147]
Impacted versions:
13.0

Steps to reproduce:
My code is kind of large, basically it has a order class with product lines and with cost center (describes the billing) lines. the are summed up and must be equal. but the constraint on both the computed sum fields always takes the old value. so if you save an order the first time it works. but when changing the values the constraint fires uppon saving. the strange thing is, that in the view all values are ok. 

when i log the communication with my browser i can see that when changing something there is a onchange call with all the right values. when saving, only one value is transmitted, which also has the right value. but the constraint goes off.

i am really desperate cause i tried many things but had no success...

Current behavior:
constraint taking old value

Expected behavior:
constraint taking the values in the view

Video/Screenshot link (optional):
-

**Comment by mart-e** [comment]
Hello,

Thank you for your report but please keep github only for bugs reporting on the standard Odoo. Not for development help.

For help, you may try the [mailing lists](https://www.odoo.com/page/odoo-community), the [forum](https://www.odoo.com/forum/help-1) or the [support page](https://www.odoo.com/help) (for paying users).

Regards
