### ISSUE TITLE
Purchase Receipt - Incorrect Journal Entry (Unbalanced)

### ISSUE THREAD

**Issue by felixlim10** [odoo/odoo#6015]
Purchase Receipt creates Purchase Journal Entry that does not balance with Tax.

Condition: Tax Included in Price.
When Tax is not included in price, it works properly.

Odoo Version: 8.0-20150326
Tested on Ubuntu & Debian

![image](https://cloud.githubusercontent.com/assets/11506858/6860787/d53b455a-d467-11e4-90dd-736110de8d7a.png)

![image](https://cloud.githubusercontent.com/assets/11506858/6860767/9d089d9a-d467-11e4-9e3d-ad0cb9a6a3bb.png)

**Comment by thomich** [comment]
hey

this is a remaining, old bug.. ;)... check out this bug fix on our bitbucket repo:
https://bitbucket.org/thomi/odoo-tools-8.0/src
module: account_voucher_payment_fix

don't even know, why they not solve this bug...

regards
thomi

**Comment by felixlim10** [comment]
Yup. This problem is still around today.

**Comment by thomich** [comment]
strange.. after some odoo updates.. this bug is still open and not fixed...
another long time bug?

**Comment by Yenthe666** [comment]
Hi @felixlim10,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
