### ISSUE TITLE
[14.0] Product and E-commerce Ribbon Configuration

### ISSUE THREAD

**Issue by hajajroshan** [odoo/odoo#60204]
**Impacted versions:**
14.0

**Steps to reproduce:**

1. Open a product.
2. In Ecommerce tab Select one Ribbon 
![image](https://user-images.githubusercontent.com/62367855/96294479-10a68d00-100a-11eb-954d-f32d7b961853.png)
- There is 'rec_name' not provided

3. Click external link
![image](https://user-images.githubusercontent.com/62367855/96294592-3d5aa480-100a-11eb-9a78-be730446fe5d.png)

**Current behavior:**

- The background color and text color not working, I tried with 3 methods to applying colors.
- If there is a way to change the colors, please add help for those fields.

**Comment by sswapnesh** [comment]
Seems to be working well 
![Screenshot from 2020-11-24 00-21-36](https://user-images.githubusercontent.com/16624719/100002790-0d61a680-2deb-11eb-8923-dd03bb833b29.png)

![Screenshot from 2020-11-24 00-21-59](https://user-images.githubusercontent.com/16624719/100002819-16eb0e80-2deb-11eb-8271-23543aef2894.png)


PS: You need to remove Ribbon class `bg-primary` to make these colors work.

**Comment by sswapnesh** [comment]
>    There is 'rec_name' not provided

https://github.com/odoo/odoo/pull/62208

**Comment by sswapnesh** [comment]
Fixed in https://github.com/odoo/odoo/commit/f70f017a04c4d0e2aaf378cce9541b01b42ed0a7
