### ISSUE TITLE
Partner Aged Balance Showing Duplicate with Opening Period Entries

### ISSUE THREAD

**Issue by orchidinfosys** [odoo/odoo#6022]
I have invoices 3 Invoices
05-Nov-2014 = 2000
13-Dec-2014 = 3000
25-Jan-2015 = 2500
Total ----------   7500
If you take Aged balance after closing Year 2014, It will be 7500 + 5000 = 12500 (Considering Opening period entries in 2015) 
There is no option to Filter by Year, So its considering Actual Invoices and Carry Forward Entries from the last Years. @qdp-odoo 

![customer invoices odoo](https://cloud.githubusercontent.com/assets/2189864/6868542/df50996c-d4a5-11e4-8ad8-0bb05721f866.png)

**Comment by Yenthe666** [comment]
Hi @orchidinfosys,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
