### ISSUE TITLE
[14][website] icons in timeline snippet can't be changed more than once

### ISSUE THREAD

**Issue by zeroheure** [odoo/odoo#60224]
Impacted versions: 14, on Odoo hosting. User with latest Firefox (81.0.2) on Ubuntu 20./ KDE Néon 5.20.

Steps to reproduce: Choose a theme for your website, for example "Orchid" which contains a timeline snippet. Add a timeline on a page. Try to change the icons. First time, it works well and the new icon is display in a circle. Do it once again and the circle disapear. One can display it again with the circle option in the text toolbar, but honestly it's not easy.

Current behavior: Circle around icon disapear

Expected behavior: Circle doesn't disapear

**Comment by Yenthe666** [comment]
Confirmed & reproduced on the latest 14.0 (without custom themes or any major changes);
![image](https://user-images.githubusercontent.com/6352350/96412016-bc5a0380-11e9-11eb-846b-ba9fd4a9904b.png)

@JKE-be

**Comment by sdegueldre** [comment]
fixed in https://github.com/odoo/odoo/pull/60450
