### ISSUE TITLE
[8.0] Transfer of picking confused with same products moves

### ISSUE THREAD

**Issue by guewen** [odoo/odoo#6030]
**Transfer of picking confused with same products moves**

Impacted versions:

 - 8.0

Steps to reproduce (on runbot):

 1. Create a new sale order
 2. Add a line with product 'Ice Cream', quantity 100, unit price 100.0
 3. Add a second line with product 'Ice Cream', quantity 50, unit price 120.0
 4. Validate the sale order. It generates a picking with 2 stock moves.
 5. Search for the procurement of the 'Ice Cream' with 100 kg and cancel it (the picking has one line canceled and one line confirmed).
 6. Go to the picking, assign it and click on 'Transfer'. There is 1 line with 50 kg of 'Ice Cream', which is correct. Confirm the transfer

Current behavior:

 - The picking is 'Cancelled'; it contains only 1 stock move, the one with 100 canceled kg of Ice cream. A second picking has been created with 50 kg of Ice cream, which is in state 'confirmed'.

Expected behavior:

 - The picking should be 'Done' but should still contains the 2 stock moves, one with 100 kg being canceled and one with 50 kg being done.

**Comment by nim-odoo** [comment]
Hello,

I am not able to reproduce the bug. Actually, the behavior I observe is the expected one: the picking is done, and contains 2 stock moves (one canceled and one done):

http://pix.toile-libre.org/?img=1427962196.png
http://pix.toile-libre.org/?img=1427962243.png
http://pix.toile-libre.org/?img=1427962261.png

Could you try on the latest version of the runbot?

Thanks!

**Comment by nim-odoo** [comment]
Thanks. The behavior arises since you click on "Force Availability", while I was clicking on "Check Availability". Anyway, this is indeed a bug.
