### ISSUE TITLE
Database Manager not dowloading backup with Firefox

### ISSUE THREAD

**Issue by isometriq** [odoo/odoo#6033]
I have to switch to Chrome when using the Database Manager, because downloading backup doesn't work on Firefox for me. It asks me where to download, but then I doesn't get added to my downloads list.

I've had this problem on more than one computer. Seems to be related to Firefox somehow...

**Comment by alejandrosantana** [comment]
Also happens to me, but if I download it using a downloader (DownThemAll in
my case) I can do it.



--
*Alejandro Santana*
alejandrosantana@anubia.es
· · · · · · · · · · · · · · · · · · · · · · · · · · · · ·

ANUBÍA, soluciones en la nube, S.L.

Colón 26, planta 3, oficina 1
36201, Vigo (Pontevedra)

www.anubia.es

[image: anubía_logo_2014_i_o_140x140.png][image:
odoo_logo_odoo_ready_140x140.png] <http://www.anubia.es/>



2015-03-30 10:42 GMT+02:00 Daniel Lorenzo <notifications@github.com>:

**Comment by isometriq** [comment]
That's a weird bug, maybe an http headers problem?
Thanks for the workaround though.

**Comment by Yenthe666** [comment]
Hi @isometriq,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
