### ISSUE TITLE
Calling `models.fields_get` via JSON-RPC requires giving undocumented arguments

### ISSUE THREAD

**Issue by aisopuro** [odoo/odoo#6034]
When calling JSON-RPC through `/web/dataset/call` from JavaScript, giving only the documented arguments as positional arguments (the `args` list) does not work:
```
var params = {
    model: model,
    method: 'fields_get',
    args: [
        allfields,
        attributes
    ]
}
```
The given parameters will not filter only the given attributes. instead you have to say:
```
var params = {
    model: model,
    method: 'fields_get',
    args: [
        allfields,
        something, // dummy
        somethingElse, // dummy
        attributes
    ]
}
```
This seems to be according to the function definition in `models.py`:
```
def fields_get(self, cr, user, allfields=None, context=None, write_access=True, attributes=None):
```
However, neither `context` or `write_access` are mentioned in the comment, and hence are not in the Pydoc either:
```
""" 
fields_get([fields][, attributes])
Return the definition of each field.
The returned value is a dictionary (indiced by field name) of
dictionaries. The _inherits'd fields are included. The string, help,
and selection (if present) attributes are translated.
:param allfields: list of fields to document, all if empty or not provided
:param attributes: list of description attributes to return for each field, all if empty or not provided
"""
```
It seems to me that the parameters should at least be mentioned in the comment. However, looking at the code it seems that at least `write_access` isn't used. Might it make sense to move these two parameters to be the last parameters of the function? This way calls from JavaScript wouldn't need to put two dummy arguments into every call, since it isn't possible to make named parameter calls in JavaScript like it is in Python (at least not yet).

**Comment by xmo-odoo** [comment]
> This way calls from JavaScript wouldn't need to put two dummy arguments into every call, since it isn't possible to make named parameter calls in JavaScript like it is in Python (at least not yet).

The `call_kw` endpoint allows passing positional arguments and keyword arguments. That is what the web client uses internally for straight calls to Odoo models, I'm not sure there's any calls to the straight `/web/dataset/call` left.
