### ISSUE TITLE
[ Confirmed BUG ] New Odoo Instance & maximum recursion depth

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#6037]
Odoo new instance started & in terminal with new database "maximum recursion depth"

Just all official module and code, getting odoo bugs...

 Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f29afa0d398> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f29afa0d398> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f29afa0d398> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f29afa0d398> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f29afa0d398> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f29afa0d398> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f29afa0d398> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f29af340d70> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f29af340d70> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f29af340d70> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f29af340d70> ignored

**Comment by Olivier-LAURENT** [comment]
Hi @rco-odoo,

This bug was coming with the merge of the pull request #5676.
It occurs when setting up models and fields and (re-)building column objects for some kinds of fields (it seems function fields), e.g., ´´´complete_name´´´ of ´´´res.partner.category´´´. In fact the new method ´´´column.__getattr__()´´´ is sometimes called with the name ´´´_args´´´ and the recursion is infinite.

This regression has a very troublesome side-effect for developpers (ubuntu/windows, Eclipse Kepler/Luna) who write tests: once this untrapped exception is raised, it is no more possible to debug tests, i.e. breakpoints never break !

Note that the debugger recovers its normal behaviour after the installation phase of the server.

Olivier

**Comment by michaelkarrer81** [comment]
hit the same problem on clean mac install

**Comment by JonathanNEMRY** [comment]
Any news about this issue?

**Comment by Olivier-LAURENT** [comment]
Hi @rco-odoo,

By modifying your code in ```osv.fields._column.__getattr__()``` like this:
<pre>
    def __getattr__(self, name):
        """ Access a non-slot attribute. """
        if name == '_args':
            import traceback
            traceback.print_stack()
            pass
        try:
            return self._args[name]
        ...
</pre>

A stack trace is produced when when setting up some function or related fields:
<pre>
  ...
  File "D:\Projects\openerp\ficep\odoo\openerp-server", line 5, in <module>
    openerp.cli.main()
  File "D:\Projects\openerp\ficep\odoo\openerp\cli\__init__.py", line 71, in main
    o.run(args)
  File "D:\Projects\openerp\ficep\odoo\openerp\cli\server.py", line 180, in run
    main(args)
  File "D:\Projects\openerp\ficep\odoo\openerp\cli\server.py", line 174, in main
    rc = openerp.service.server.start(preload=preload, stop=stop)
  File "D:\Projects\openerp\ficep\odoo\openerp\service\server.py", line 948, in start
    rc = server.run(preload, stop)
  File "D:\Projects\openerp\ficep\odoo\openerp\service\server.py", line 350, in run
    rc = preload_registries(preload)
  File "D:\Projects\openerp\ficep\odoo\openerp\service\server.py", line 915, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "D:\Projects\openerp\ficep\odoo\openerp\modules\registry.py", line 368, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "D:\Projects\openerp\ficep\odoo\openerp\modules\loading.py", line 301, in load_modules
    registry.setup_models(cr, partial=True)
  File "D:\Projects\openerp\ficep\odoo\openerp\modules\registry.py", line 192, in setup_models
    model._setup_fields(cr, SUPERUSER_ID)
  File "D:\Projects\openerp\ficep\odoo\openerp\api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "D:\Projects\openerp\ficep\odoo\openerp\api.py", line 336, in old_api
    result = method(recs, *args, **kwargs)
  File "D:\Projects\openerp\ficep\odoo\openerp\models.py", line 2988, in _setup_fields
    column = field.to_column()
  File "D:\Projects\openerp\ficep\odoo\openerp\fields.py", line 714, in to_column
    self.column = self.column.new(_computed_field=bool(self.compute), **args)
  File "D:\Projects\openerp\ficep\odoo\openerp\osv\fields.py", line 1394, in new
    return copy.copy(self)
  File "C:\Program Files\Python27\lib\copy.py", line 96, in copy
    return _reconstruct(x, rv, 0)
  File "C:\Program Files\Python27\lib\copy.py", line 335, in _reconstruct
    if hasattr(y, '__setstate__'):
  File "D:\Projects\openerp\ficep\odoo\openerp\osv\fields.py", line 160, in __getattr__
    return self._args[name]
  File "D:\Projects\openerp\ficep\odoo\openerp\osv\fields.py", line 156, in __getattr__
    traceback.print_stack().
</pre>

Many thanks to have a look to this critical issue.

Olivier

**Comment by mv-taktik** [comment]
We have got the same issue... 
Are you working on this? What's the status? This is major...

**Comment by staminaloops** [comment]
Same here...

**Comment by flotho** [comment]
+1

**Comment by Olivier-LAURENT** [comment]
Linked to opw-633109

**Comment by tejastank** [comment]
Till getting issue, reopen it.

:2: (WARNING/2) Block quote ends without a blank line; unexpected unindent.
:2: (WARNING/2) Block quote ends without a blank line; unexpected unindent.
:2: (WARNING/2) Block quote ends without a blank line; unexpected unindent.
:2: (WARNING/2) Block quote ends without a blank line; unexpected unindent.
:2: (WARNING/2) Block quote ends without a blank line; unexpected unindent.

tejastank@usa-vps:~$ :2: (WARNING/2) Block quote ends without a blank line; unexpected unindent.
:2: (WARNING/2) Block quote ends without a blank line; unexpected unindent.
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in > ignored

**Comment by jl2035** [comment]
This is critical. Is anybody working on this?

```
user@UserHP:~/Prog/ODev/odoo$ ./odoo.py -c debian/openerp-server.conf -d boatcompany -u boatcompany --stop-after-init
2016-04-05 08:33:23,974 25309 INFO ? openerp: OpenERP version 9.0c
2016-04-05 08:33:23,974 25309 INFO ? openerp: addons paths: ['/home/user/.local/share/Odoo/addons/9.0', u'/home/user/Prog/ODev/odoo/addons', u'/home/user/Prog/ODev/odoo/my-modules', '/home/user/Prog/ODev/odoo/openerp/addons']
2016-04-05 08:33:23,974 25309 INFO ? openerp: database: user@default:default
2016-04-05 08:33:24,125 25309 INFO boatcompany openerp.modules.loading: loading 1 modules...
2016-04-05 08:33:24,141 25309 INFO boatcompany openerp.modules.loading: 1 modules loaded in 0.02s, 0 queries
2016-04-05 08:33:24,374 25309 INFO boatcompany openerp.modules.loading: loading 42 modules...
2016-04-05 08:33:24,379 25309 INFO boatcompany passlib.registry: registered crypt handler 'pbkdf2_sha512': <class 'passlib.handlers.pbkdf2.pbkdf2_sha512'>
2016-04-05 08:33:24,380 25309 INFO boatcompany passlib.registry: registered crypt handler 'md5_crypt': <class 'passlib.handlers.md5_crypt.md5_crypt'>
2016-04-05 08:33:24,410 25309 INFO ? openerp.addons.bus.models.bus: Bus.loop listen imbus on db postgres
2016-04-05 08:33:24,421 25309 INFO boatcompany openerp.addons.report.models.report: You need Wkhtmltopdf to print a pdf version of the reports.
2016-04-05 08:33:24,684 25309 CRITICAL boatcompany openerp.modules.module: Couldn't load module boatcompany
2016-04-05 08:33:24,685 25309 CRITICAL boatcompany openerp.modules.module: maximum recursion depth exceeded
2016-04-05 08:33:24,685 25309 ERROR boatcompany openerp.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/home/user/Prog/ODev/odoo/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/user/Prog/ODev/odoo/openerp/modules/loading.py", line 334, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/home/user/Prog/ODev/odoo/openerp/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/user/Prog/ODev/odoo/openerp/modules/loading.py", line 123, in load_module_graph
    load_openerp_module(package.name)
  File "/home/user/Prog/ODev/odoo/openerp/modules/module.py", line 324, in load_openerp_module
    __import__('openerp.addons.' + module_name)
  File "/home/user/Prog/ODev/odoo/openerp/modules/module.py", line 61, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/home/user/Prog/ODev/odoo/my-modules/boatcompany/__init__.py", line 4, in <module>
    from . import models
  File "/home/user/Prog/ODev/odoo/my-modules/boatcompany/models/__init__.py", line 3, in <module>
    from . import models
  File "/home/user/Prog/ODev/odoo/my-modules/boatcompany/models/models.py", line 17, in <module>
    class boatcompany_product_product(models.Model):
  File "/home/user/Prog/ODev/odoo/openerp/models.py", line 258, in __init__
    setattr(self, name, column.to_field())
  File "/home/user/Prog/ODev/odoo/openerp/fields.py", line 358, in __getattr__
    return self._attrs[name]
  File "/home/user/Prog/ODev/odoo/openerp/fields.py", line 358, in __getattr__
    return self._attrs[name]


Many many many many


  File "/home/user/Prog/ODev/odoo/openerp/fields.py", line 358, in __getattr__
    return self._attrs[name]
  File "/home/user/Prog/ODev/odoo/openerp/fields.py", line 358, in __getattr__
    return self._attrs[name]
  File "/home/user/Prog/ODev/odoo/openerp/fields.py", line 358, in __getattr__
    return self._attrs[name]
RuntimeError: maximum recursion depth exceeded
2016-04-05 08:33:24,691 25309 CRITICAL boatcompany openerp.service.server: Failed to initialize database `boatcompany`.
Traceback (most recent call last):
  File "/home/user/Prog/ODev/odoo/openerp/service/server.py", line 885, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/home/user/Prog/ODev/odoo/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/user/Prog/ODev/odoo/openerp/modules/loading.py", line 334, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/home/user/Prog/ODev/odoo/openerp/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/user/Prog/ODev/odoo/openerp/modules/loading.py", line 123, in load_module_graph
    load_openerp_module(package.name)
  File "/home/user/Prog/ODev/odoo/openerp/modules/module.py", line 324, in load_openerp_module
    __import__('openerp.addons.' + module_name)
  File "/home/user/Prog/ODev/odoo/openerp/modules/module.py", line 61, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/home/user/Prog/ODev/odoo/my-modules/boatcompany/__init__.py", line 4, in <module>
    from . import models
  File "/home/user/Prog/ODev/odoo/my-modules/boatcompany/models/__init__.py", line 3, in <module>
    from . import models
  File "/home/user/Prog/ODev/odoo/my-modules/boatcompany/models/models.py", line 17, in <module>
    class boatcompany_product_product(models.Model):
  File "/home/user/Prog/ODev/odoo/openerp/models.py", line 258, in __init__
    setattr(self, name, column.to_field())
  File "/home/user/Prog/ODev/odoo/openerp/fields.py", line 358, in __getattr__
    return self._attrs[name]
  File "/home/user/Prog/ODev/odoo/openerp/fields.py", line 358, in __getattr__
    return self._attrs[name]
  File "/home/user/Prog/ODev/odoo/openerp/fields.py", line 358, in __getattr__
    return self._attrs[name]


Many many many many


  File "/home/user/Prog/ODev/odoo/openerp/fields.py", line 358, in __getattr__
    return self._attrs[name]
  File "/home/user/Prog/ODev/odoo/openerp/fields.py", line 358, in __getattr__
    return self._attrs[name]
  File "/home/user/Prog/ODev/odoo/openerp/fields.py", line 358, in __getattr__
    return self._attrs[name]
RuntimeError: maximum recursion depth exceeded
```

**Comment by a0c** [comment]
Still getting the issue. Reopen it.

**Comment by a0c** [comment]
Solved a similar problem this way:
```diff
Subject: [FIX] error on changing quant's owner

all_parents computed field of res_partner contained cycles (included self)
during cache serialization with convert_to_write(). this lead to a maximum
recursion depth exceeded error. we exclude self from all_parents to avoid
cycles, and add a dedicated check for self everywhere all_parents is used.
---
 models/partner.py            | 2 +-
 models/stock.py              | 2 +-
 security/portal_security.xml | 2 +-
 3 files changed, 3 insertions(+), 3 deletions(-)

diff --git a/models/partner.py b/models/partner.py
index 1df54b3..85f02c8 100644
--- a/models/partner.py
+++ b/models/partner.py
@@ -11,7 +11,7 @@ def _type(self):
class res_partner(models.Model):
     _inherit = 'res.partner'
     def _all_parents(self):
         for x in self:
             all_parents = []
-            parent = x
+            parent = x.parent_id
             while parent:
                 all_parents.append(parent.id)
                 parent = parent.parent_id
             x.all_parents = all_parents

     all_parents = fields.Many2many('res.partner', compute=_all_parents)
diff --git a/models/stock.py b/models/stock.py
index 3cacf8c..b3502e6 100644
--- a/models/stock.py
+++ b/models/stock.py
@@ -1009,7 +1009,7 @@ def _search_id_range(self, operator, value):
     owner_parents = fields.Many2many('res.partner', related='owner_id.all_parents')
-    status = fields.Many2one('stock.quant.status', domain="[('partners', 'in', owner_parents[0][2])]")
+    status = fields.Many2one('stock.quant.status', domain="['|',('partners', 'in', owner_parents[0][2]),('partners', 'in', [owner_id])]")
diff --git a/security/portal_security.xml b/security/portal_security.xml
index 27c3b82..621f482 100644
--- a/security/portal_security.xml
+++ b/security/portal_security.xml
@@ -38,7 +38,7 @@
         <record id="portal_status_rule" model="ir.rule">
             <field name="name">Portal Statuses</field>
             <field name="model_id" ref="bla_bla_bla.model_stock_quant_status"/>
-            <field name="domain_force">[('partners','in',user.partner_id.all_parents.ids)]</field>
+            <field name="domain_force">[('partners','in',user.partner_id.all_parents.ids+[user.parent_id.id])]</field>
             <field name="groups" eval="[(4, ref('base.group_portal'))]"/>
         </record>
```

**Comment by a0c** [comment]
Here is another workaround to avoid cycles in cache.
Use `no_prefetch()` before calling the field that creates cycles in cache (`link_quant_ids` in my case):
```python
# use no_prefetch() to avoid cycles in cache leading to infinite recursion:
#   https://github.com/odoo/odoo/issues/6141
#   https://github.com/odoo/odoo/issues/6037
linked_quants = quant.no_prefetch().link_quant_ids
last_moved_quants = self.last_pick.mapped('move_lines.quant_ids')
self.quants = last_moved_quants | linked_quants
```
Chainable `no_prefetch()` is defined as follows:
```python
def no_prefetch(self, fields=None):
    """ only prefetch `fields` for the *current* records (self).
        avoids prefetching `fields` for *all* records _in_cache_without `fields` """
    prefetch_ids = self._context.get('prefetch_ids', {})
    if fields is None:
        prefetch_ids[self._name] = set(self.ids)
    else:
        for f in fields:
            prefetch_ids['%s.%s' % (self._name, f)] = set(self.ids)
    return self.with_context(prefetch_ids=prefetch_ids)

BaseModel.no_prefetch = no_prefetch


def no_prefetch_field(self, key):
    field_recs = self.mapped(key).no_prefetch()
    return self.with_context(field_recs._context)

BaseModel.no_prefetch_field = no_prefetch_field


@api.model
def _in_cache_without(self, field):
    """ Make sure ``self`` is present in cache (for prefetching), and return
        the records of model ``self`` in cache that have no value for ``field``
        (:class:`Field` instance).
    """
    env = self.env
    prefetch_ids = env.prefetch[self._name]
    prefetch_ids.update(self._ids)
    ids = filter(None, prefetch_ids - set(env.cache[field]))
    ids = self._apply_prefetch_ids_in_context(ids, field)
    return self.browse(ids)

def _apply_prefetch_ids_in_context(self, ids, field):
    if self.env.context.get('prefetch_ids'):
        prefetch_ids = self.env.context['prefetch_ids'].get(str(field), self.env.context['prefetch_ids'].get(self._name))
        if prefetch_ids:
            ids = [x for x in ids if x in prefetch_ids]
    return ids

BaseModel._in_cache_without = _in_cache_without
BaseModel._apply_prefetch_ids_in_context = _apply_prefetch_ids_in_context
```
