### ISSUE TITLE
[14.0] Duplicate Page named Calendar on user

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#60387]
Impacted versions: 14.0

Steps to reproduce: Open User

Current behavior: 
![Screenshot from 2020-10-20 22-14-10](https://user-images.githubusercontent.com/16624719/96617739-99326f80-1321-11eb-80db-a76a9d67624f.png)

Both are added from separate module
https://github.com/odoo/odoo/blob/4f7a314eff2725d7bf03188634eff7af9b82cd0d/addons/microsoft_calendar/views/res_users_views.xml#L10

https://github.com/odoo/odoo/blob/4f7a314eff2725d7bf03188634eff7af9b82cd0d/addons/google_calendar/views/res_users_views.xml#L10

Expected behavior: We should have One Page named Calendar Containing fields for Google/Microsoft.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
I think that's not possible right now. As much, you can have a page called "Google Calendar" and another called "Microsoft Calendar".

**Comment by sswapnesh** [comment]
> you can have a page called "Google Calendar" and another called "Microsoft Calendar".

Yes,Exactly. (with different name of Pages)

(or At least One Page "Calendar" with two groups)

**Comment by pedrobaeza** [comment]
But that means to have a common ancestor that have such page, which is too much change for stable.

**Comment by sswapnesh** [comment]
and It is already fixed in https://github.com/odoo/odoo/commit/9b3b2e8d711e3be75b1faffaf6f4f8f4ec90186e (in 14 😃 )


![Screenshot from 2021-03-29 00-30-58](https://user-images.githubusercontent.com/16624719/112764460-378bd500-9026-11eb-8dda-d53b8c452829.png)
