### ISSUE TITLE
Spanish Language is not working since commit fb7407cba6afe433bad1d7786997b13e34b0a9b7

### ISSUE THREAD

**Issue by santiant** [odoo/odoo#60394]
Impacted versions: 
Latest 14.0 version.

Steps to reproduce:
Enable Spanish as language.  Everything is still in English.

Current behavior:
Almost if not all strings are back to English. 

Expected behavior:
Spanish should be displayed when it is selected as default language.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
@mart-e It's true that I have tried in runbot and everything appears still in English.

**Comment by pedrobaeza** [comment]
Fixed in 99702e109f661dc5d705a3337c7213a2b5f404b6
