### ISSUE TITLE
[14.0]Lost default relate id while editing a record from one2many field

### ISSUE THREAD

**Issue by lin-ww** [odoo/odoo#60400]
Impacted versions:  
14.0  

Steps to reproduce:  
Create a new record from one2many field with context {'default_xxx_id': active_id}  
xxx_id related to the the model in current page

Current behavior:
xxx_id default value is lost in new page, as the screenshot below  
![image](https://user-images.githubusercontent.com/50607366/96683790-3686b580-13ad-11eb-8e2e-3fcc83ee6ce0.png)

**Comment by pedrobaeza** [comment]
That's not a correct way to develop what you want. One2many handle directly the `inverse_name` field, and it mustn't be in the view.

Closing as no issue, but development question.

**Comment by lin-ww** [comment]
> That's not a correct way to develop what you want. One2many handle directly the `inverse_name` field, and it mustn't be in the view.
> 
> Closing as no issue, but development question.

Thanks for your answer. I may not have made it clear for what i want.  
There's modelA, modelB. Code in modelA:
```python
modelB_ids = fields.One2many("modelB", "modelA_id")
```
Now in modelA form view, `modelB_ids` is displayed as one2many_list with context `{'default_modelA_id': active_id}`. I click the create buttom in one2many_list and open modelB's create form. `modelA_id` should be the active_id in new form, but actually not.   
  
If it is not a legical case, how can i deliver modelA's active_id to `modelA_id` of modelB?

**Comment by pedrobaeza** [comment]
Questions should go to the forums, not here, but as said, inverse_name (`modelA_id` for your example) is auto-populated by the one2many widget, and the field mustn't appear in the view.

**Comment by lin-ww** [comment]
> Questions should go to the forums, not here, but as said, inverse_name (`modelA_id` for your example) is auto-populated by the one2many widget, and the field mustn't appear in the view.

Thanks~ I got it
