### ISSUE TITLE
[8.0] Scheduler - Timezone changes

### ISSUE THREAD

**Issue by jdegoy** [odoo/odoo#6043]
Scheduler data is stored in database in UTC. A daily job will run 24 hours after the latest execution time. When the server changes timezone automatically this will result in a shift in execution time.
Would it be possible to add timezone to the model in order to be able to "fix" the execution time accordingly? This avoids to have to fix the timezone of the server.

Daily job execution time calculation will look like this: 
Next Execution Time = DB reference time (UTC) + 24h + server time - timezone time (UTC +/- X)
Example;
Server in UTC+2 job is fixed in UTC+1: 10:00 + 24:00 + 12:00 - 11:00 => job is executed @ 11:00 UTC+1
The next day the server switches to UTC+1: 10:00 + 24:00 + 11:00 - 11:00 => job is still executed @ 11:00 UTC+1

**Comment by Yenthe666** [comment]
Hi @jdegoy,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
