### ISSUE TITLE
Decimal mark (decimal_point) wrong for es_ES

### ISSUE THREAD

**Issue by anderswallenquist** [odoo/odoo#6046]
http://en.wikipedia.org/wiki/Decimal_mark

https://github.com/odoo/odoo/blob/8.0/openerp/addons/base/res/res_lang.py
line 112
 'decimal_point' : fix_xa0(str(locale.localeconv()['decimal_point'])),

seems to get "." instead of "," when you install es_ES on Ubuntu 14.04

**Comment by Yenthe666** [comment]
Hi @anderswallenquist,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
