### ISSUE TITLE
[V8/saas-6] Bug in editable tree view

### ISSUE THREAD

**Issue by joshuajan** [odoo/odoo#6047]
**Input area "disappear" in editable tree view**

Impacted versions:
- 8.0

Steps to reproduce:
1. Modify the sale order form view. Add the attrs="{'readonly':[('price_unit', '>', 500)]}" in the order line`s product_id fields.
2. open a exist quotation.
3. Edit the first line and Enter. 
   Current behavior:
- Can mot modify the second line in right input area. The input move to the left top and can`t see it.

Expected behavior:
- Can modiy the second line

![editable-tree-view-bug](https://cloud.githubusercontent.com/assets/1176173/6898322/1027dd6a-d72c-11e4-9196-b49367795ac1.png)

**Comment by joshuajan** [comment]
Hi @mart-e I found you add a "timeout" function to addons/web/static/src/js/view_list_editable.js line 463 (cfd24d98). I think the "timeout"  make  this problem happen (When I comment this , everything is go well). 

Thank you very much

**Comment by joshuajan** [comment]
I think this problem will make the input become very inconvenient

**Comment by carllhw** [comment]
I got the same problem

**Comment by Yenthe666** [comment]
Hi @joshuajan,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
