### ISSUE TITLE
Web controller auth="none" does not work per documentation

### ISSUE THREAD

**Issue by elgow** [odoo/odoo#60486]
Impacted versions: 11 and probably all others

Steps to reproduce:
Create a web controller module `my_controller_module` like: 

```
class MyController(http.Controller):
    log.info('loading MyController class')
    # route declaration example copied from Odoo codebase
    # @http.route('/web/database/create', type='http', auth="none", methods=['POST'], csrf=False)
    @http.route('/my_controller/event',  type='http', auth='none', methods=['POST'], csrf=False)
    def index(self, **post):
        return "Hello, world"
```
Install this module in the server. Try to hit the specified URL, e.g. using curl:

```
curl -v -d 'data="the data"' http://server_host/my_controller/event
```

You should expect a 404 Not Found error. 

Now restart the server with the option `--load web,my_controller_module` and try the curl again. It will return "Hello, world".

Current behavior:
The behavior is described above, but it is not as described in the documentation. The documents imply that simply specifying `auth="none"` will make it work. 

Expected behavior:
That it behave per the documentation. 

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
The problem seems to be that you have several databases in your host without a dbfilter for selecting the correct one. Any way, development questions should go to forums and 11.0 is a version out of official support, so closing.

**Comment by elgow** [comment]
"The problem seems to be that you have several databases in your host without a dbfilter for selecting the correct one. Any way, development questions should go to forums and 11.0 is a version out of official support, so closing."

Actually that is not the problem. The endpoint never gets added to the nodb endpoints registry, and the code is not trying to access the DB anyway. 

It is highly likely that this behavior is the same in all versions up through 14, and I note than v. 14 docs are identical to v. 11 for `auth="none"`.  I'm not really sure who you think you are helping by sweeping problems under the rug.

**Comment by elgow** [comment]
Well, Pedro, I stand corrected. The behavior differs depending on whether the server has one database or more than one. When there is only one DB the `server_wide_modules` config is not needed and the feature works as documented. 

Once again, this behavior is very likely the same in v.14, so a small note in the docs about this detail would be helpful.

**Comment by pedrobaeza** [comment]
Where do you suggest to put that?

**Comment by elgow** [comment]
I think that a small note added to the `auth="none"` section of the Routing section of https://www.odoo.com/documentation/14.0/reference/http.html  [source:  https://github.com/odoo/odoo/blob/14.0/odoo/http.py#L430]  to the effect of:

'Note: If more than one database is active in the server then a module using auth="none" must be preloaded using the server_wide_modules configuration parameter or the --load CLI argument."

**Comment by pedrobaeza** [comment]
Good idea. Can you please make the pull request adding such text?

**Comment by elgow** [comment]
Will I need to have filed a contributor agreement? The organization bureaucracy where I work makes this troublesome.

**Comment by pedrobaeza** [comment]
Any way, a good deployment should always provide one unique DB via dbfilter, or this is only one the problems you can face.

**Comment by pedrobaeza** [comment]
I'm afraid so. You can fill the CLA as individual and make the contributor as a personal one.

**Comment by elgow** [comment]
Thanks. That is good to know, and I've changed my dev config to have only one DB active at a time to avoid issues in future.

Since this is docs and not code I'll file as an individual. If it were code developed "on the clock" that could be a problem with the boss.
