### ISSUE TITLE
FATAL Error when connection to "postgres" DB forbidden

### ISSUE THREAD

**Issue by AlexFomin1349466** [odoo/odoo#60509]
Impacted versions: 13.0

Steps to reproduce:
1. forbid Odoo postgres user to create a connection to postgres database
    Example: "REVOKE connect ON postgres FROM PUBLIC; REVOKE connect ON postgres FROM [odoo_user];"

2. set "db_name" in Odoo configuration file
3. start odoo server

Current behavior:
Odoo throws a fatal error and will not start, although odoo postgres user has sufficient rights to work in [db_name] database.

Expected behavior:
The same behavior, if the odoo postgres user had insufficient privileges. Skipping database auto-creation and successful  start of Odoo server

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
That's a deployment issue and out of scope of the default Odoo issue tracker though. You specifically revoked rights yourself.
