### ISSUE TITLE
Compute field not working when using Store attribute.

### ISSUE THREAD

**Issue by shadow-1995** [odoo/odoo#60515]
Impacted versions:
Odoo 13

Steps to reproduce:
```python
	@api.depends("product_tmpl_id")
	def _computeBOMLine(self):
		for record in self:
			bom_lines = record.product_tmpl_id.bom_ids.mapped("bom_line_ids").filtered(lambda x: record.id in x.bom_product_template_attribute_value_ids.ids)
			if any(bom_lines):
				record.computed_bom_line_id = bom_lines[0].id
			else:
				record.computed_bom_line_id = False

	computed_bom_line_id = fields.Many2one("mrp.bom.line",compute="_computeBOMLine", store=True)
```
Current behavior:
Compute method is not called at all.

Expected behavior:
Based on attribute mapping in BOM, a BOM line should have been mapped to attribute value and it was supposed to be stored in database.

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a development question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here. Little tip: it's not working because the depends is not complete.

Closing this by the reason above.

**Comment by shadow-1995** [comment]
Hi,
Got it. Just one more thing, same code is working on 3 instances but on my prod its not working. Any reason?

**Comment by pedrobaeza** [comment]
I can't say. Ask of the forums.

**Comment by shadow-1995** [comment]
Thanks.
