### ISSUE TITLE
CSV import bypass model constraints

### ISSUE THREAD

**Issue by dannyadair** [odoo/odoo#6052]
If CSV import is enabled (General Settings), and a user is allowed "Invoicing & Payments", they cannot only create an invoice, but also import an invoice. With matching identifiers, an existing invoice can be changed this way.

You are not allowed to change the date of a validated invoice.
But if you export it to CSV, change the date, then import it again, the date on the existing invoice is changed.

This is an unacceptable security hole - import must go through the same constraints as Add/Edit of the web interface.

The invoice date is just an example of a seemingly general issue.
It seems to apply to all versions from OpenERP from at least 7 to Odoo up to master.

**Comment by gdgellatly** [comment]
tested and confirmed on v7 and v8, (exported an invoice and imported with different date)

**Comment by wtaferner** [comment]
Good catch :+1:

**Comment by beledouxdenis** [comment]
I won't call this an "unacceptable security hole", as it does not lead to any information leak nor any privilege escalation. But I confirm this as a bug and the fact that
>"import must go through the same constraints as Add/Edit of the web interface."

**Comment by morrillo** [comment]
This is anything but a security hole. Do you mind changing the title of the issue in order to avoid confussions?

**Comment by beledouxdenis** [comment]
Done, thanks for the advise :).

**Comment by ybofr** [comment]
Is this generally for all imports or only for the import of invoices? Can I also change any other document by importing?
Furthermore, does the system document the changes done via csv import, so that I have a traceability of the changes?

Thanks for the answers

**Comment by dannyadair** [comment]
Have a try with other documents :-) I strongly suspect so.
I saw this on invoices and quickly reported it as it is a complete showstopper.

Changes by import are not logged (which makes matters arguably worse).

**Comment by beledouxdenis** [comment]
> Changes by import are not logged (which makes matters arguably worse).
That isn't true. The regular messages posted on record changes during regular create/write operations will be posted as well during imports, and the write_uid on updated records will be updated as well.

**Comment by dannyadair** [comment]
Sorry I'm just using a plain vanilla 8.0 branch installation, created a fresh invoice.

If I change the invoice partner or the state through the form, then I see a message.
If I only change the date of a Draft invoice through the form, I never see a message.
If I only change the date of a validated invoice through import (not allowed through form), I still don't see a message.

Just checked - "Import/Export compatible", only field "Invoice Date". Change date in CSV, import, latest message still only "Invoice validated", date changed.

**Comment by beledouxdenis** [comment]
As I said, only change messages that are posted during regular create/write operations will be posted as well during imports.

As you said it, there is no message posted when changing the date of an invoice during regular create/write operations, so, indeed, there will not be any messages posted when changing the date of an invoice through import.

Only fields defined with a `track_visibility` argument or listed within the `_track` dict of a model will have messages posted on change. Please refer to the doc.

**Comment by dannyadair** [comment]
Sorry for the misunderstanding. I should have written "Those changes".

**Comment by ybofr** [comment]
Can we agree on the fact that the system does not do the exact same check for import and that this should be corrected?
For accounting, this is a major breach of traceability, as anybody can change relevant data in an accounting document, just by importing. So, I believe that we have a bug there.

**Comment by beledouxdenis** [comment]
I already confirmed this as a bug on comment
https://github.com/odoo/odoo/issues/6052#issuecomment-88412275

**Comment by dannyadair** [comment]
By the way, you can overwrite the date to be outside the invoice's period (or any defined period), that will also import happily.

**Comment by osvalr** [comment]
Tested on runbot and I confirm this is happening, maybe a video with this issue should help to visualize it

**Comment by dannyadair** [comment]
NB sorry but together with https://github.com/odoo/odoo/issues/12077 we're forced to disable CSV import/export which is unfortunate.

**Comment by Yenthe666** [comment]
Hi @dannyadair,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
