### ISSUE TITLE
Auth_singup emails are deleted from the queue even if the template configures otherwise

### ISSUE THREAD

**Issue by xpeco** [odoo/odoo#60533]
Impacted versions:
Tested in v13 and v14

Steps to reproduce:
Go to Settings->Technical->Templates
Select  Auth Signup: Odoo Connection and set Advanced Settings->Auto Delete = False
Create a new internal user.
The email sent won't appear on the queue (Technical->Emails)

Current behavior:
The message is sent but removed from the queue by forcing the "auto delete" and changing the template settings
It is not possible to recover any mail sent about it.

Expected behavior:
Use the configuration of auto_delete defined at the templates (auth_signup.set_password_email and auth_signup.reset_password_email).

Attached is a patch for the odoo/addons/auth_signup/models/res_users.py
[res_users.patch.log](https://github.com/odoo/odoo/files/5422880/res_users.patch.log)

I look forward to any suggestion as well as if a PR is needed

**Comment by sswapnesh** [comment]
This is on purpose to Prevent Other users to Read email.( Which leaks Access token)

Cc @odony

**Comment by odony** [comment]
Indeed, this is done for security reasons. The auto-delete is forced to make sure reset password links aren't kept around in the database (they can be used to take over the account).

If your goal is to test/debug those emails, you can use the "Preview" button on the mail template (in form view). Or simply trigger a real password reset email to test it.

If your goal is to keep those emails in the database, it's not possible due to the security implications.

**Comment by xpeco** [comment]
I understand.

I think it would be a good improvement to hide the auto_delete option (for these templates) or just let the user take the risk.
For instance, in some cases the template is modified (not to show the token link) so the risk goes down considerably.

**Comment by Yenthe666** [comment]
The current implementation works really good and it's secure so that won't be changed. If you want it do it in custom development but I really wouldn't recommend you to do so.

**Comment by xpeco** [comment]
The auto_delete option has no effect on those templates and you need to download to the sources to understand why.
At least, with this closed ticket other users will find it here the reason.
