### ISSUE TITLE
[BUG][12.0] account: error when changing Rounding Factor'value of currency

### ISSUE THREAD

**Issue by thongthele** [odoo/odoo#60575]
**Impacted versions:** v12

**Steps to reproduce:**
1. Create a company with base currency as `VND`
2. Go to menu `Accounting -> Configuration -> Currencies`, then click `VND`
3. Edit `Rounding Factor`'s value as `1000`
4. Create a new `Customer Invoice`
5. On form, select a `Customer`
6. An error occurred.

**Traceback:**

> File "/home/thongle/Viindoo/odoo-12/addons/account/models/account_invoice.py", line 911, in _onchange_payment_term_date_invoice
>    self.date_due = max(line[0] for line in pterm_list)
> ValueError: max() arg is an empty sequence

**Current behavior:**
An error occurred.

**Expected behavior:**

**Video/Screenshot link (optional):**

**Comment by Yenthe666** [comment]
Let's close this as you already made a PR and PR's get priority :)
