### ISSUE TITLE
[7.0] duplicate a delivery order, the associated manufacturing order of the old delivery will be appended with unnecessary finished product  lines  

### ISSUE THREAD

**Issue by oliverzgy** [odoo/odoo#606]
Duplicate a delivery order, the associated manufacturing order of the old delivery will be appended with unnecessary finished product  lines. The issue is reproduced at runbot.   

***Impacted versions:***

 - 7.0 latest 

***Steps to reproduce:***

 1. Create a clean instance and install sales, mrp, stock, jit
 2. Define a stockable product with Procurement Method as 'make to order' and then define a bom
 3. Confirm a sales order of this product -> a delivery order and a manufacturing order are generated accordingly
 4. Start the manufacturing order and produce partially
 5. Duplicate the delivery generated above

***Current behavior:***
 1. Go to the manufacturing order mentioned above, under finished product tab, two more lines are added to the 'Products to produce' 

![2014-06-18 14_06_11-sales orders - openerp](https://cloud.githubusercontent.com/assets/3712729/3310192/5cbd2166-f6af-11e3-8669-32433cc39d61.png)
![2014-06-18 14_07_31-delivery orders - openerp](https://cloud.githubusercontent.com/assets/3712729/3310193/5fad521a-f6af-11e3-80a9-0891afb35907.png)
![2014-06-18 14_07_47-delivery orders - openerp](https://cloud.githubusercontent.com/assets/3712729/3310205/b4681740-f6af-11e3-8a63-2ed58d8d0251.png)
![2014-06-18 14_08_14-manufacturing orders - openerp](https://cloud.githubusercontent.com/assets/3712729/3310206/ba658740-f6af-11e3-8fe5-29dfd4da7c6b.png)

***Expected behavior:***
 1. A new manufacturing order need to be generated

**Comment by Yenthe666** [comment]
Dear @oliverzgy,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
