### ISSUE TITLE
[13.0][14.0][BUG?] Removing taxes dont remove repartition lines

### ISSUE THREAD

**Issue by jjscarafia** [odoo/odoo#60603]
Impacted versions:
13.0, 14.0

Steps to reproduce:
Create some account.tax
Delete the account.tax
open view for "account.tax.repartition.line" using debugger. Search for "Invoice Tax is not set" & "Refund Tax is not set"

Current behavior:
Dangling repartition lines remains on database

Expected behavior:
Repartition lines deleted oncascade

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/3016656/96989856-a9527680-14fc-11eb-953a-f596eaa20580.png)

**Comment by william-andre** [comment]
@oco-odoo Is that intended? Shouldn't it be `ondelete='restrict'`?

**Comment by oco-odoo** [comment]
@william-andre No, it's not intended. We want indeed 'cascade' here; 'restrict' would forbid deleting account.tax objects if they have at least one repartition line (which they always do, so no tax removal at all).

@jjscarafia Nice catch! :)

**Comment by william-andre** [comment]
@oco-odoo Yes,what I meant is cascade on the tax, but restrict on the repartitions line: you don't want to delete used repartitions lines.

**Comment by oco-odoo** [comment]
@william-andre indeed, a 'restrict' is missing on account.move.line's tax_repartition_line_id . @sswapnesh Can you add it to your PR as well?

**Comment by sswapnesh** [comment]
> a 'restrict' is missing on account.move.line's tax_repartition_line_id .

https://github.com/odoo/odoo/blob/43184af875f3eb52586348b383627cb0140484f5/addons/account/models/account_move.py#L3006-L3009


@oco-odoo am I missing something ?

**Comment by oco-odoo** [comment]
@sswapnesh You're not. I probably hadn't seen well :eyes: 
Anyway, The fix is currently being merged, so I'm closing the issue :)
