### ISSUE TITLE
The system duplicates the accounting entries after user error

### ISSUE THREAD

**Issue by zbik2607** [odoo/odoo#6065]
See video: http://www.rybieoko.pl/html/OdooError.html

**Comment by Yenthe666** [comment]
Hi @zbik2607,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
