### ISSUE TITLE
[13.0] website, portal : sale order sidebar overlapping on mega menu

### ISSUE THREAD

**Issue by kig-odoo** [odoo/odoo#60666]
![7d218958-d574-40cf-b356-e8fec2df8c57](https://user-images.githubusercontent.com/22187704/97041114-a2734480-158c-11eb-9db2-202c8ee64b45.png)

Technical: 
`.sticky-top` class on sidebar card has higher z-index then mega-menu dropdown

**Comment by rdeodoo** [comment]
At first look, it is somehow fixed in 14.0 even if the `.sticky-top` sidebar z-index is still 1020 and `.dropdown-menu` mega menu is still 1000.

**Comment by qsm-odoo** [comment]
Fixed with https://github.com/odoo/odoo/commit/702f2b93cec19fab75eca25a53aa16cf419b289e
