### ISSUE TITLE
[14.0] Error delete internal notes in the product form

### ISSUE THREAD

**Issue by nuelgoz** [odoo/odoo#60672]
I cannot delete or modify the internal notes in the product form in the general information tab, once this field is edited and cannot be modified.

this is reproduced when you have several languages in Odoo, I have tried runbot version 14 and the same happens, so the enterprice version works ok.

**Comment by pedrobaeza** [comment]
Can you put any video exercising the problem?

**Comment by nuelgoz** [comment]
editing the field with two languages installed

![odoo error internal notes](https://user-images.githubusercontent.com/9434922/97093474-8df68100-164c-11eb-9ce2-c21fea869fab.gif)

**Comment by pedrobaeza** [comment]
That's not an error, but a behavior you don't understand who it works: removing a translation means that the original source term is then shown, which is the effect you are seeing. You need to edit translations (through the corresponding icon) for emptying the source term as well.

Closing as no bug, but the described behavior.

**Comment by nuelgoz** [comment]
Por que no lo pruebas antes de decir que no es un error, así no aportas nada, a mi me da igual si es un error o no, yo simplemente lo reporto para que Odoo tenga conocimiento del mismo y lo arregle si quiere.
