### ISSUE TITLE
widget="selection" for 'label'. It is necessary to remove.

### ISSUE THREAD

**Issue by KomarovAlea** [odoo/odoo#60678]
https://github.com/odoo/odoo/blob/1a5f71bec0073197e2eacc7929d79599ccff250d/addons/point_of_sale/views/pos_config_view.xml#L511

**Comment by Yenthe666** [comment]
Please add detailed steps of what you believe is wrong and why it is.

**Comment by sswapnesh** [comment]
@Yenthe666 `widget="selection"` is not needed as this is just a Label.

**Comment by Yenthe666** [comment]
ohhh. @KomarovAlea a PR is welcomed :)

**Comment by KomarovAlea** [comment]
> Please add detailed steps of what you believe is wrong and why it is.

widget 'selection' doesn't work to 'labels'. It's work only with 'fields'.
Code 'widget="selection"' need to remove from label tag.

> ohhh. @KomarovAlea a PR is welcomed :)

Sorry, but all my PR-s reject. And it lowers my rating on github. 
Therefore, I do not do PR, but create issues.

**Comment by Yenthe666** [comment]
Well I'm not going to keep an issue open for this because I know where it ends: nowhere. Nobody from Odoo is going to take the time to look at this and 'fix' it, it is basically a dead attribute. It'll be removed automatically at some point
