### ISSUE TITLE
Incorrect key 'stored'. 'storeD=' need to change into 'store='

### ISSUE THREAD

**Issue by KomarovAlea** [odoo/odoo#60677]
https://github.com/odoo/odoo/blob/1a5f71bec0073197e2eacc7929d79599ccff250d/addons/stock/models/stock_production_lot.py#L29

**Comment by pedrobaeza** [comment]
Which Odoo version? This means a change in DB layout, so not sure this can be feasible in stable.

@amoyaux what is your opinion?

**Comment by Yenthe666** [comment]
Already fixed in V14:
https://github.com/odoo/odoo/blob/4058b200102eec88956913af1ad98adf2f7f0ec7/addons/stock/models/stock_production_lot.py#L28
It is indeed wrong in V13:
https://github.com/odoo/odoo/blob/13.0/addons/stock/models/stock_production_lot.py#L29

@amoyaux should we still fix it in V13?

**Comment by sswapnesh** [comment]
> @amoyaux should we still fix it in V13?

It is already stored field.

**Comment by Yenthe666** [comment]
Good point. Let's close it off since it is fixed in V14
