### ISSUE TITLE
[11.0][Board] Filter result still appearing even if the filter is removed 

### ISSUE THREAD

**Issue by OthmaneGhandi** [odoo/odoo#60705]
Impacted versions: 11.0

Steps to reproduce: **Go to any tree view** -> **apply a filter** -> (in Favorites) Use **add to my Dashboard** ->  **remove the filter**

Current behavior: The results of the filter still applied even the filter is removed

Expected behavior: When removing the filter we need to see the results without filter

**Comment by pedrobaeza** [comment]
v11 is already out of official support. Please see if you can replicate in an upper version and in runbot, and if so, please give some hints on how to reproduce it (a video would be good), as it's difficult to imagine what do you mean.
