### ISSUE TITLE
Generated moves thru change quantity wizard in MO cannot be processed

### ISSUE THREAD

**Issue by yostashiro** [odoo/odoo#60751]
### Impacted versions:

12.0

### Steps to reproduce:

1. Create an MO with quantity 10.
1. Produce the full quantity (i.e. 10), and post stock moves. Note that at this point the MO is still not marked as done.
1. Change the quantity to 11 through 'Change Quantity To Produce' wizard. With this, new stock moves are generated for finished goods and raw materials.
1. Press 'Check Availability'.

### Current behavior:

No reservation takes place for the generated raw material moves.

### Expected behavior:

Reservation takes place for the generated raw material moves.

**Comment by pedrobaeza** [comment]
Are you sure about the step 2 not being marked as done?

**Comment by pedrobaeza** [comment]
I see your PR, so closing this. Next time, please put directly the issue text on the PR.
