### ISSUE TITLE
project issue replies are missing reference ID

### ISSUE THREAD

**Issue by collinssolutions** [odoo/odoo#6075]
I have setup an incoming mail server for support and created a project that catches all these emails as project issues. It works in that respect but when i reply the customer gets the email but when they reply back it creates a new issue. From what i can tell there is no reference anywhere in the email as to what issue it came from so do has no way to know where to put it back.

**Comment by collinssolutions** [comment]
i have determined this has something to do with using Amazon SES services. Problem is i need to use SES. I have zoho and it does not allow relays so anything going out has to be from the email address used to authenticate with zoho smtp.

**Comment by collinssolutions** [comment]
I have more info on this. When odoo makes an email it creates a message-id field in the email header. Amazon ses replaces this with its own message-id. Odoo really needs to track this in a different way.

**Comment by mmalorni** [comment]
@collinssolutions Old mail clients that do not support the message-id fields are also causing issues. They are stripping the message-id header and then the email gets stuck in the mailbox and there are no warning that they are sitting there. There should be a way to identify those emails that are missing the message-id and warn the recipient or the destinator that the email was not integrated in Odoo.
We mainly have this issue with clients answering their emails with old (2 years) Android phones.
Could be costly if the reply that is lost is for a big contract.
@tde-banana-odoo is this something that can be fixed?  
There is an OCA module that send back the email to the sender but I feel this is not a good solution.
https://github.com/OCA/server-tools/tree/9.0/fetchmail_notify_error_to_sender

**Comment by Yenthe666** [comment]
Hi @collinssolutions,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
