### ISSUE TITLE
CORS issue in odoo 12

### ISSUE THREAD

**Issue by sakibindia** [odoo/odoo#60776]
Impacted versions: odoo 12

Steps to reproduce:I've try to expose api from odoo controller to Angular10 which are in different servers. But getting cors
 error. As recommended I put cors="*" in parameters of http.route but no luck. I also tried reverse proxy but also not luck.

Current behavior:Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://*.*.*.*/api/list_property_all. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Expected behavior:response 200 with data

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
