### ISSUE TITLE
Date mixing american and european format

### ISSUE THREAD

**Issue by ybofr** [odoo/odoo#6078]
I have noted that, if you define the date format as being %d.%m.%Y but you have the locale en_US, if you enter the date in the said format for instance 10.02.2015, the system will consider that you have entered the second october 2015.
It seems that the date format given in the language selection is not respected and there is no way for the user to influence how the date can be entered or to see what is specified in the locale.

thank you for a correction
regards

**Comment by Yenthe666** [comment]
Hi @ybofr,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by gdgellatly** [comment]
for posterity, it was an issue with the datepicker widget that has been resolved in v9.  It was actually worse than that.  If you entered 10.02.2015 it would be 10th February, but if you entered 10.02.15 it would be 2nd October.
