### ISSUE TITLE
fstring doesn't seems to work inside à _() translation declaration

### ISSUE THREAD

**Issue by tfossoul** [odoo/odoo#60828]
Impacted versions:
All

Steps to reproduce:

```
fstring_var = "Hello world"
print(_(f" {fstring_var}"))
```

fstring is a >3.6 feature fyi.

**Comment by pedrobaeza** [comment]
Indeed `fstring` can't be supported in translatable strings due to its nature. You shouldn't use it also if your target Odoo version support previous Python versions.

Closing as no issue, but impossible to implement feature.
