### ISSUE TITLE
[survey][8.0] Not allowed to edit survey text format

### ISSUE THREAD

**Issue by alejandrosantana** [odoo/odoo#6088]
**Survey does not allow edit content format**

Impacted versions:

 - 8.0

Steps to reproduce:

 1. create a survey
 2. enter in its "Design" option, so you are prompted to the website survey page
 3. Press "Edit" button (on top left)
 4. Select some text within a textbox 

Current behavior:

 - Formatting tools (bold, italic,...) are disabled

Expected behavior:

 - Formatting tools (bold, italic,...) are available so I can apply some formatting to some words (as simple as bold, italic,...)

**Comment by rim-odoo** [comment]
Why do you want to design text *inside* a textbox. Design mode is used to build a survey, and textboxes are to be used by people who answer the survey.

For me, it is not a bug, but working as designed.
