### ISSUE TITLE
[14.0] Wrong stars on Rating widget

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#60933]
Impacted versions: 14.0

Steps to reproduce: Open Reviews on Courses

Current behavior: 
![download](https://user-images.githubusercontent.com/16624719/97482109-b7c8e400-197b-11eb-8e2d-e6a7a5799dfa.png)

Expected behavior: 1 to 5 Stars

Video/Screenshot link (optional): 

Seems to be coming from https://github.com/odoo/odoo/blob/7f1bcc8ceb78729725f65585e923b08f94bf75b5/addons/rating/models/rating_mixin.py#L269

https://github.com/odoo/odoo/blob/7f1bcc8ceb78729725f65585e923b08f94bf75b5/addons/portal_rating/static/src/js/portal_chatter.js#L120

**Comment by Yenthe666** [comment]
Adding a comment here so I get notified, I noticed the same in my db :)

**Comment by Yenthe666** [comment]
Fixed in https://github.com/odoo/odoo/commit/7b2daced6610b901ead4a98070c33c7ca7bbe308

**Comment by mamiu** [comment]
> Adding a comment here so I get notified, I noticed the same in my db :)

@Yenthe666 Just hit the *subscribe* button on the right sidebar. 😉

<img width="411" alt="Screen Shot 2020-11-07 at 00 14 26" src="https://user-images.githubusercontent.com/3653465/98375781-5648f980-208e-11eb-910f-bd21e372cf7b.png">

**Comment by Yenthe666** [comment]
@mamiu I'm by default described to the whole stack so I get hundreds of notifications a day 😄 By commenting I can filter them out with the "Participating" block.

**Comment by mamiu** [comment]
@Yenthe666 Ah ok, because I already wondered and was actually sure that you knew that. 😂

But thanks for the trick of how to handle a huge amount of notifications! 👍🏻
