### ISSUE TITLE
Compute product fields 'code' and 'partner_ref' incorrect for variants.

### ISSUE THREAD

**Issue by doug-willdooit** [odoo/odoo#60936]
Impacted versions:

10.0, 11.0, 12.0, 13.0, 14.0

Steps to reproduce:

(in 13.0)
Create a product with variants.
On the product ‘Purchase’ tab add supplier info records for vendor A for each variant, giving each variant a unique Vendor Product Name and Vendor Product Code.
Create a purchase order for vendor A and with a line for each of the variants.

Modify the purchase order report (template report_purchaseorder_document) to include the partner_id in the context and print the product ‘code’ and ‘partner_ref’ fields on each order line.

Current behavior:

The 'code' and 'partner_ref' fields on the printed report show the vendor product name and vendor product code for one of the variants, but not necessarily the variant on the purchase order line.

Expected behavior:

The 'code' and 'partner_ref' fields should return the vendor product name and vendor product code for the variant on the purchase order line.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Closing as there's a PR for this.
