### ISSUE TITLE
Odoo13 pos receipt printed but no records at backend

### ISSUE THREAD

**Issue by mubam** [odoo/odoo#60939]
Impacted versions: odoo v.13

Steps to reproduce: Our shopping POS was running normally. But yesterday one of shopping branch's / This branch has new casher/  internet connection disconnected while in payment process. Order receipt was printed and red triangle appeared top right side corner. Casher clicked this triangle repeatedly and it wasnt working. So she turned off computer. After that internet connection connected and red triangle disappeared and turned green. After work she closed cash and 1 receipt was extra and this order wasnt recorded at backend.
Current behavior:
Now its working normally but i dont want to make this bug again and i dont want to be fired :(. / what if, we dont save receipts? / This situation happened 3 times before. I thought this bug happening rarely and its OK, but my CEO doesnt want to happen this again. 
Expected behavior:
I checked all of my JSON files and there was no track about this order. So how i fix this bug and never happen again? 
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Sorry, but this problem seems to be that the local storage of the browser was emptied meanwhile, and thus, Odoo doesn't have the possibility to resend the not sent orders. There's nothing that can be done in this side.

Closing due to this.
