### ISSUE TITLE
[14.0][FIX] base: res.partner no gravatar image loading because of missing context

### ISSUE THREAD

**Issue by skeller1** [odoo/odoo#60941]
Impacted versions: 14.0

Steps to reproduce:

    Go to contacts and open form for new record
    Enter Email in form (with valid Gravatar email)

Current behavior:

    Gravatar image is not loaded because of missing context gravatar_image: True

Expected behavior:

    Gravatar image should be loaded

Solution:

mail addon is removing context, already fixed in 12.0 and 13.0 with #50980

**Comment by pedrobaeza** [comment]
Maybe you can do the same PR. @sswapnesh you were the original author of the PR.

**Comment by tde-banana-odoo** [comment]
See https://github.com/odoo/odoo/pull/54758/files seems forward port did not spam me to continue doing it.

**Comment by sswapnesh** [comment]
Has been fixed in 14.
