### ISSUE TITLE
[master] The new bank statement import wizard does not take into account multiple accounts per file

### ISSUE THREAD

**Issue by NL66278** [odoo/odoo#6097]
Many dutch banks give customers the possibility to download data for several accounts at once - in one file. The new import framework however assumes that in one bank statement file to import, all statements will belong to the same bank account and have the same currency. This is not necesarily true.

So currency and bank account number should be part of statement and not separate. The import parsers should return just an array of statements.

**Comment by Whisno** [comment]
That doesn't look very difficult to fix, I'll do it once #5863 is merged.
BTW, could you send us an anonymized file ? We badly lack 'real-life' testing material, especially to test country-specific behaviours

**Comment by NL66278** [comment]
@Whisno Solution is here: https://github.com/acsone/odoo/pull/2

Maybe you would be so kind as to review it?

**Comment by Whisno** [comment]
I am definitively going to do this. Unfortunately, it might take quite a long time seeing th

**Comment by Yenthe666** [comment]
Hi @NL66278,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
