### ISSUE TITLE
[8.0] missing max-height: 40mm; in .oe_logo img and oe_single_form_logo img

### ISSUE THREAD

**Issue by svenpetersen** [odoo/odoo#6099]
Hello,

it's no April Fools Day joke, although it might sound like one.

After a user uploaded a real big company logo (1600px height) the login View and the Menu was broken. 
I noticed that in an up2date version of 8.0 the "max-height: 40mm;" style attribute must have been removed from .oe_logo img and oe_single_form_logo img.

In earlier Builds it caused no problem because it was limited to 40mm.

with kind regards,
Sven

**Comment by Yenthe666** [comment]
Hi @svenpetersen,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
