### ISSUE TITLE
Minus sign only character doesn't show up when selecting many2one field

### ISSUE THREAD

**Issue by dyshrmn** [odoo/odoo#61021]
Impacted versions: 13

Steps to reproduce: Fill any many2one field with value '-' only, then select it from odoo ui

Current behavior: Cannot select many2one field with value '-' only

Expected behavior: Can select many2one feld with value '-' only

Video/Screenshot link (optional): There's similar problem from others who only using pure jquery autocomplete (https://stackoverflow.com/questions/37793238/why-doesnt-jquery-ui-autocomplete-style-minus-signs-correctly-in-options).

**Comment by pedrobaeza** [comment]
Unless you include screenshots or better a video, it's difficult to understand the problem
