### ISSUE TITLE
Can't enter a procurement in a customer location

### ISSUE THREAD

**Issue by clonedagain** [odoo/odoo#6106]
When a sale order is entered in Odoo, a procurement is generated for the "Customer" location for each Sale Order Line.
However, it is not possible to manually enter procurements for customer locations using the form at "Warehouse > Schedulers > Procurements". Only internal locations seem to be allowed.

**Comment by jco-odoo** [comment]
I guess we could change the domain in the view to allow for customer locations also.  (Transit locations does not seem logical because normally you transit to somewhere)

**Comment by clonedagain** [comment]
OK, will you get in charge or should I ask OPW ?

**Comment by jco-odoo** [comment]
opw

**Comment by Yenthe666** [comment]
Hi @clonedagain,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
