### ISSUE TITLE
print HTML type report, the content is spillout of the page.

### ISSUE THREAD

**Issue by fanha99** [odoo/odoo#61068]
Impacted versions: 12.0, 13.0, 14.0

Steps to reproduce: 
- change the "Quotation / Order" report to HTML
- any sale order, print / "Quotation / Order"
- press Ctrl+P (chrome) or menu print (firefox)

Current behavior:
- firefox: 
scale 100%, the content is spillout of the page
scale shrink to fit: all the content is too small, the footer info is in the center of the page
-chrome: default is zoom 100%, and the result is the same as scale shrink to fit in firefox

Expected behavior:
in the 11.0, the content is almost the same as the pdf version.

Video/Screenshot link (optional):
![100](https://user-images.githubusercontent.com/1172848/97726127-7e21e580-1b01-11eb-8141-cd0742529320.png)
![shrink](https://user-images.githubusercontent.com/1172848/97726132-7feba900-1b01-11eb-9a00-e72896bbfcc5.png)

**Comment by pedrobaeza** [comment]
I don't know how you get to that screenshot, but in Odoo core where HTML is populated (like invoice in portal) is shown properly, so this can't be considered as a bug unless that HTML is not well viewed in standard.

**Comment by fanha99** [comment]
Hi, 
I'm testing and capture more screen shot from 14.0. Using firefox 82. windows 10 64bit.

![invoice_setting](https://user-images.githubusercontent.com/1172848/97771687-18ba0d00-1b72-11eb-88dc-51f097d1c55a.png)

![draft_invoice](https://user-images.githubusercontent.com/1172848/97771690-21124800-1b72-11eb-876a-b445e28b6da5.png)

![firefox_print](https://user-images.githubusercontent.com/1172848/97771698-2a031980-1b72-11eb-963b-5b2eb98f3817.png)

![print_review](https://user-images.githubusercontent.com/1172848/97771700-2ec7cd80-1b72-11eb-93f4-13a735e106d9.png)

**Comment by fanha99** [comment]
in 11.0, I can print this way with best quality.

**Comment by fanha99** [comment]
more screen shot from chrome.
![chrome](https://user-images.githubusercontent.com/1172848/97771807-3b005a80-1b73-11eb-9f1b-6a1a2a636dc5.png)

**Comment by fanha99** [comment]
in firefox, when choice landscape, the content is fit, but loss the footer info. there are 2 pages too.
![landscape](https://user-images.githubusercontent.com/1172848/97771871-e6111400-1b73-11eb-8a04-e8bbc52f2b36.png)

**Comment by fanha99** [comment]
not sure is this the source of problem?
https://github.com/odoo/odoo/blob/6d2c030b9eb37f3f524125aeeeac4f6d70417ed0/addons/web/static/lib/bootstrap/css/bootstrap.css#L9998

  @page {
    size: a3;
  }

**Comment by pedrobaeza** [comment]
Yeah, but as said, the problem comes from the fact that you are deviating the standard use putting that to be printed as HTML, which is not used in standard, and when used (for example, on invoices on portal), everything is shown properly, so it's a problem on your custom use that you are wanting to make and thus, you have to fix it on your side.
