### ISSUE TITLE
Inválidas Cuenta a cobrar y Cuenta a pagar

### ISSUE THREAD

**Issue by eestebad** [odoo/odoo#61101]
Impacted versions: Odoo 13 y 14

Steps to reproduce: Install Purchase. I try to create a Partner, but gives an error: Invalid account receivable and account payable. This fields do not appear in this option.

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by ivanporras** [comment]
You need to install a localization module for example l10n_mx

**Comment by pedrobaeza** [comment]
You need to install the chart of accounts in your company.

Closing as no issue, but misuse.

**Comment by eestebad** [comment]
Gracias.
