### ISSUE TITLE
odoo14 daily version upgrade error problem (starting from the 29th, 30, 31)

### ISSUE THREAD

**Issue by nj-dream** [odoo/odoo#61107]
I download the latest deb installation package upgrade through nightly.odoo.com every day.
From the 29th, 29, 30, 31, the three-day installation package after the upgrade, enter odoo, the system will prompt

Error: QWeb2: Template'systray_odoo_referral.gift_icon' not found
exception@https://mydomain.com/web/content/483-76b2e93/web.assets_common.js:4389:16
_render@https://mydomain.com/web/content/483-76b2e93/web.assets_common.js:4434:112
render@https://mydomain.com/web/content/483-76b2e93/web.assets_common.js:4430:158
renderElement@https://mydomain.com/web/content/483-76b2e93/web.assets_common.js:4941:740
https://mydomain.com/web/content/483-76b2e93/web.assets_common.js:4951:19
promiseReactionJob@[native code]

If I downgrade to 14.0.20201027, everything is normal.

**Comment by Yenthe666** [comment]
@tfr-odoo maybe your PR (https://github.com/odoo/odoo/pull/60863) broke this?

**Comment by adekock11** [comment]
@nj-dream you can just uninstall `odoo_referral` module and try again

**Comment by nj-dream** [comment]
hello,
thank you very much!

I remove the odoo_referral module.and upgrade odoo by odoo_14.0.20201031_all.deb.but in odoo backend(discuss）,I get this error:

Error: undefined is not an object (evaluating 'scope['threadView'].nonEmptyMessages.length')
anonymous
render@[native code]
__render@https://mydomain.com/web/content/483-76b2e93/web.assets_common.js:1278:41
https://mydomain.com/web/content/483-76b2e93/web.assets_common.js:1276:37
asyncFunctionResume@[native code]
[native code]
promiseReactionJobWithoutPromise@[native code]

**Comment by nj-dream** [comment]
Now I upgraded to the 31st version, and it works well together, including normal mode and 3 different developer modes.
From abnormal to normal, the only operation I did was to add a user (there was only the admin user).

**Comment by adekock11** [comment]
@nj-dream do you also get the error if you are in debug mode? https://mydomain.com/web?debug=assets

**Comment by adekock11** [comment]
@nj-dream I only saw your second reply now. I think when you removed `odoo_referral` and it still did not work, there was a caching issue. The cache got cleared and that's why it "magically" started working again.

**Comment by nj-dream** [comment]
It should be the reason for the caching you mentioned. I can't think of any other possibilities. I almost did nothing, and it was fine.
> @nj-dream I only saw your second reply now. I think when you removed `odoo_referral` and it still did not work, there was a caching issue. The cache got cleared and that's why it "magically" started working again.
