### ISSUE TITLE
Calendar Card item list scroll not working

### ISSUE THREAD

**Issue by composercodes** [odoo/odoo#61112]
Impacted versions: 
14
Steps to reproduce: 
create calendar view add many fields
Current behavior:
 card open but edit delete button not shown and scroll not working
Expected behavior:
 card open but edit delete button shown and scroll working
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a development question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
