### ISSUE TITLE
why I changed the value in fields.Selection , and restart odoo , but take no effect

### ISSUE THREAD

**Issue by alexhmyang** [odoo/odoo#61151]
`    # company_type is only an interface field, do not use it in business logic

    company_type = fields.Selection(string='Company Type',
        selection=[('person1', 'Individual'), ('company1', 'Company')],
        compute='_compute_company_type', inverse='_write_company_type')`

why I changed the value in fields.Selection of   res.partner.py and restart odoo , but take no effect

why?

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a development question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
