### ISSUE TITLE
serial product odoo v8

### ISSUE THREAD

**Issue by koooler** [odoo/odoo#6117]
Hi guys
am facing problem of split serial products on odoo v8 no such module available .

any help i will be appreciated and if i want to migrate module from v7 to v8 is that possible

Thanks

**Comment by Yenthe666** [comment]
Hi @koooler,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
