### ISSUE TITLE
Clicking studio in accounting module

### ISSUE THREAD

**Issue by Maoie86** [odoo/odoo#61216]
Impacted versions: v14e

Steps to reproduce: go to accounting module, then click studio

Current behavior: error 

Expected behavior: no error
[odoo.txt](https://github.com/odoo/odoo/files/5479223/odoo.txt)

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@Maoie86 seems to work fine by now on the latest build. Can you add a video to show it please?
