### ISSUE TITLE
Error: QWeb2: Template 'systray_odoo_referral.gift_icon' not found

### ISSUE THREAD

**Issue by hazemomr** [odoo/odoo#61221]
Hi everyone,
after update of 1-nov-2020 i got error .. when i login i got this error below (attached)
when i pressed ok .. i cant see the right of top menu (notification - sing out)
please any advise to correct this error.
thanks in advance.

![odoo error1](https://user-images.githubusercontent.com/26384703/97959846-a5123d00-1dc9-11eb-8464-bbab34a70086.png)

**Comment by Yenthe666** [comment]
@tfr-odoo and yet another report that your PR broke db's. Comes back from https://github.com/odoo/odoo/pull/53507

**Comment by hazemomr** [comment]
thanks a lot 
i uninstalled  odoo referral program from Apps
working fine right now

**Comment by tfr-odoo** [comment]
Thanks for the feedback
unfortunately I'm not able to reproduce the issue with the following scenario:
- Create a database with a build prior https://github.com/odoo/odoo/commit/dda0bb499b0964b3a1750431255ecfef6cc9eb46 
    - I can see the gift icon
- Then I switch on last commit of 14.0
- Refresh the page
  - No error and the gift icon has disappeared

The Js that cause the error of the missing xml template is also gone in the same commit.
The only reason I can see to have this error it's when web.assets.common.js is not refreshed properly after the update of odoo.
