### ISSUE TITLE
Ticket is not creating in Odoo.sh 

### ISSUE THREAD

**Issue by Techloyce-Odoo** [odoo/odoo#61303]
Impacted versions:
Odoo version 14

Steps to reproduce:
Go to Helpdesk create a ticket and save it it will popup an error.

Current behavior:

Expected behavior:
Save my ticket

ScreenShots:
Instance # 1:

![Screenshot from 2020-11-04 11-49-33](https://user-images.githubusercontent.com/60097032/98079089-179c1f00-1e95-11eb-8d93-ac65237c72e4.png)

Instance # 2:

![Screenshot from 2020-11-04 11-54-49](https://user-images.githubusercontent.com/60097032/98079103-1c60d300-1e95-11eb-8033-93180454f0b8.png)

**Comment by pedrobaeza** [comment]
As this is something in an enterprise module, please report it to odoo.com/help instead.
