### ISSUE TITLE
Imported modules are not excluded when checking missing ones

### ISSUE THREAD

**Issue by luisg123v** [odoo/odoo#61302]
Impacted versions:
- 12.0
- 13.0
- Probably 14.0, altough not tested yet

Steps to reproduce:
- Import a  custom module using the module "Base import module", e.g. `awesome_module`
- Update all modules by running `-u all`

Current behavior:
The following error is shown:

`ERROR server Some modules are not loaded, some dependencies or manifest may be missing: ['awesome_module']`

Expected behavior:
Since the custom module was imported, it's expected not to be present in the addons-path, so no errors should be shown.

This is similar to what happened with `studio_customization`, which was addressed on https://github.com/odoo/odoo/pull/43892. The same could be implemented for imported modules, by checking [the Imported field](https://github.com/odoo/odoo/blob/ce3da3f50b99/addons/base_import_module/models/ir_module.py#L26).

Actually, `studio_customization` is also marked as an imported module, so if that approach is taken, it would include also that module.

**Comment by luisg123v** [comment]
OPW #2366384

CC @edy1192 @CarmenMiranda

**Comment by vava-odoo** [comment]
Linked ticket is closed
