### ISSUE TITLE
[DOC] Force ping documentation is not complete

### ISSUE THREAD

**Issue by frlanxpertiz** [odoo/odoo#61340]
The documentation doesn't explain how to force a ping when there was too many user or modules installed and that it has been fixed. There is an anchor link but it doesn't lead to an explanation
https://www.odoo.com/documentation/user/13.0/db_management/db_premise.html#error-message-due-to-too-many-users

**Comment by ojuschugh1** [comment]
Hi, I wanted to work on this issue .Is it still open ?

**Comment by vava-odoo** [comment]
Hi @ojuschugh1 
Thanks for your helop, but this has already been updated: https://www.odoo.com/documentation/16.0/administration/maintain/on_premise.html#error-message-due-to-too-many-users
Cheers,
