### ISSUE TITLE
New and old API field inheritance seems not to be interoperable

### ISSUE THREAD

**Issue by nch-odoo** [odoo/odoo#6138]
Hi,

Most probably related to the one fixed earlier: #2088 

There seems a problem for the fields with compute attributes.
for eg: I have a code in v7
```
class sale_advance_payment_inv(osv.osv_memory):
_columns = {
'advance_payment_method':fields.selection(
[('all', 'Invoice the whole sales order'), ('percentage','Percentage'), ('fixed','Fixed price (deposit)'),
('lines', 'Some order lines')],
```
and I want to convert this to new api v8 and also use it as a function field: I did like this:
```
class sale_advance_payment_inv(models.TransientModel):
advance_payment_method = fields.Selection(compute='_get_advance_payment_method',

@api.one
def _get_advance_payment_method(self):
```
but it always has one value the first one 'Invoice the whole sales order' and like a normal char field.

![image](https://cloud.githubusercontent.com/assets/7599820/6981380/0cbba55e-da1e-11e4-8656-e9be40b20760.png)

**Comment by nch-odoo** [comment]
@rco-odoo . Can you please comment on this ?

**Comment by yvaucher** [comment]
Could be the same as https://github.com/odoo/odoo/issues/2797

**Comment by dreispt** [comment]
The code you show looks correct. Could there be a bug in your `_get_advance_payment_method`?

**Comment by nch-odoo** [comment]
Thanks @dreispt 
Here is the code of _get_advance_payment_method
 @api.one
    def _get_advance_payment_method(self):
         res = []
         if self._context.get('active_model', False) == 'sale.order':
             sale_id = self._context.get('active_id', False)
             if sale_id:
                 sale = self.env['sale.order'].browse(sale_id)
                 # Advance option not available when, There are at least 1 non-cancelled invoice created
                 num_valid_invoice = 0
                 for i in sale.invoice_ids:
                     if i.state not in ['cancel']:
                         num_valid_invoice += 1
                 if sale.order_policy == 'manual' and (num_valid_invoice or not self._context.get('advance_type', False)):
                     res.append(('all', 'Invoice the whole sales order'))
                     res.append(('lines', 'Some order lines'))
                 if not num_valid_invoice and self._context.get('advance_type', False):
                     res.append(('percentage', 'Percentage'))
                     res.append(('fixed', 'Fixed price (deposit)'))

         self.advance_payment_method = res

**Comment by dreispt** [comment]
This doesn't work because the method is to calculate the field value, not the selection list available.
You're assigning a list to the `advance_payment_method` field  and it should be a string.

**Comment by nch-odoo** [comment]
Thanks for the reply @dreispt , is this not we used to do until 7.0 ?
how do we achieve this ..If I want a list of tuple [()] to be returned dynamically in a selection ?

**Comment by dreispt** [comment]
> how do we achieve this ..If I want a list of tuple [()] to be returned dynamically in a selection ?

I haven't seen that being done.
In many2one fields you can use domains to filter the available options, but I'm not sure if that is possible for selection fields. Maybe you can try that.

If not, the next best option is to show all options, but add a validation to prevent setting certionan values in specific cases.

**Comment by nch-odoo** [comment]
Thanks ,  but as this used to work in < 8.0 
so it seems like a bug in new api. 
Waiting for someone from RD to confirm it.

**Comment by dreispt** [comment]
AFAICS in the example code you present, v7 code has a fixed selection list, and you only introduce the computed function in the v8 code.

**Comment by nch-odoo** [comment]
@dreispt What I meant is in v7 if we would inherit a fixed selection field and change it to a function returned list of values. it was possible. the same code like this:
```
def _get_advance_payment_method(self, cr, uid, context=None):
        res = []
        if context.get('active_model', False) == 'sale.order':
            sale_id = context.get('active_id', False)
            if sale_id:
                sale = self.pool.get('sale.order').browse(cr, uid, sale_id)
                # Advance option not available when, There are at least 1 non-cancelled invoice created
                num_valid_invoice = 0
                for i in sale.invoice_ids:
                    if i.state not in ['cancel']:
                        num_valid_invoice += 1
                if sale.order_policy == 'manual' and (num_valid_invoice or not context.get('advance_type', False)):
                    res.append(('all', 'Invoice the whole sales order'))
                    res.append(('lines', 'Some order lines'))
                if not num_valid_invoice and context.get('advance_type', False):
                    res.append(('percentage', 'Percentage'))
                    res.append(('fixed', 'Fixed price (deposit)'))
        return res
Field Defination
'advance_payment_method': fields.selection(_get_advance_payment_method,
            'What do you want to invoice?', required=True,
```

**Comment by nch-odoo** [comment]
@mart-e @rco-odoo any workaround or am I missing something ?

**Comment by mart-e** [comment]
@nch-odoo I think you are mixing two different things.
```
foo = fields.Selection('_get_selection',
    compute='_get_foo',
    inverse='_set_foo',
    search='_search_foo')
```
https://www.odoo.com/documentation/8.0/reference/orm.html#openerp.fields.Selection

Getting the list of possibilities is not the same (expects list of tuples, uses `@api.model`) as getting a result (expects the key of the selection fields, users `@api.one` or multi).
If you have only a compute method, you will get a readonly field with no define possibilities.

Get in contact with me or somebody of R&D if not clear but please open issues only if you are reporting a clear bug (not to ask migration questions).

Thanks @dreispt for the analysis

**Comment by dreispt** [comment]
So, you can provide a method to dynamically generate the option list, instead of providing a fixed list. The way it was being done wasn't the correct one. Nice. Thanks!

**Comment by mart-e** [comment]
@dreispt we do the first [in event](https://github.com/odoo/odoo/blob/99c44334f10427ec351ff8d205a7662b31ea0ce0/addons/event/event.py#L119) and second [in base](https://github.com/odoo/odoo/blob/99c44334f10427ec351ff8d205a7662b31ea0ce0/openerp/addons/base/module/module.py#L808)

**Comment by nch-odoo** [comment]
Thanks @mart-e
