### ISSUE TITLE
how to create dynamic table in qweb report???? bellow is my code which give me output in text....

### ISSUE THREAD

**Issue by Bhaviraj** [odoo/odoo#6139]
_table = ['<table border="1px;" class="table table-condensed" style="border-color: #ff0000 #0000ff;">', '<tbody>']
        for row in range(1,11):
            _table.append('<tr>')
            for col in range(1,5):
                _table.append('<td>ABC</td>')
            _table.append('</tr>')
        _table.append('</tbody>',)
        _table.append('</table>')
        return _table

**Comment by sle-odoo** [comment]
Closing as i don't understand anything of this issue.
Regards
