### ISSUE TITLE
Inventory values not calculated

### ISSUE THREAD

**Issue by avanzella** [odoo/odoo#6143]
Hello,

I'm facing an issue where some products are not properly valuated in the inventory.
Their inventory value remains at zero no matter the quantity in stock and the cost price.
Does anybody see a reason for such a behavior?
Is the inventory value calculated?
Is there a way to force the calculation?

Thank you for any help.

Regards,
Alain

**Comment by jco-odoo** [comment]
they are consumable instead of stockable products?

**Comment by avanzella** [comment]
No, products are all stockable.

**Comment by avanzella** [comment]
I'm still facing this issue.
Thank you for any help.

**Comment by tuananhv** [comment]
I get the same behavior. I use ODOO 8.0

**Comment by avanzella** [comment]
What costing method are you using (on the product procurements tab)?

**Comment by tuananhv** [comment]
I am using the costing method "standard price".

Another question: how can I assign a price / cost to products during an inventory ?

**Comment by avanzella** [comment]
Using "Real price" should normally solve your problem.

**Comment by tuananhv** [comment]
Is the standard price not actually the "real price", because I am using a price list for the standard price ? So,  the price in each purchasing order / procurement is correct.
