### ISSUE TITLE
Stock: multi-steps and backorder for partial receipt

### ISSUE THREAD

**Issue by Thanh-Tu7785** [odoo/odoo#61453]
1. Activate receipt in 3 steps
2. Make a PO of 60
3. Receive 40, QC passed 20, backorder 40 and draft 20 returning Vendor
4. Receive backorder 40, QC passed 20 -> backorder 20 and draft 20
5. Receive backorder 20, QC passed 20 -> no backorder ---> Done PO

Do you have any solution for our flow?
Please help it out

Thanks

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
