### ISSUE TITLE
Average Cost price calculation bug

### ISSUE THREAD

**Issue by madrose** [odoo/odoo#6148]
Odoo V8
Anglo Saxxon Accounting
Product set to Average price + Real Time (Automated)
Product Category is set FIFO

First buy a one unit of a product for $1000. cost get update to $1000. Next you get another unit for free, cost remains $1000 (Which is totally wrong of course).
Next try to sell 1 unit, cost of the product remains $1000. accounting entry passed for COGS @ $1000 (which is correct).
Try to sell the other unit and the product cost remains $1000 and accounting entry is passed @ $1000 for COGS? How come?????

this is a serious bug in the system and when dealing with hundreds of products and many daily transaction it is easy to have totally wrong accounting entries in the system and wrong financials as well.

**Comment by anajuaristi** [comment]
I think the problem could be this small piece of code (I said could be, not sure)
https://github.com/odoo/odoo/blob/8.0/addons/stock_account/stock_account.py#L324

```
    def product_price_update_after_done(self, cr, uid, ids, context=None):
        '''
        This method adapts the price on the product when necessary
        '''
        for move in self.browse(cr, uid, ids, context=context):
            #adapt standard price on outgoing moves if the product cost_method is 'real', so that a return
            #or an inventory loss is made using the last value used for an outgoing valuation.
            if move.product_id.cost_method == 'real' and move.location_dest_id.usage != 'internal':
                #store the average price of the move on the move and product form
                self._store_average_cost_price(cr, uid, move, context=context)
```
 
This is updating product form field value just on moves having destiny NOT "internal". That is ... it's only updating on moving to virtual locations. 

Normally it's just the contrary. You will never change cost price on outgoings but only on incomings so... the correct code should be
```
    if move.product_id.cost_method == 'real' and move.location_dest_id.usage == 'internal' 
```
And it would also should control the origin of the movement to not be internal. That is... cost price on product form should change only on the case of incoming/produce moves, never on outgoing or internal moves. 

I would like to know other experts opinion on this critical subject.
@pedrobaeza
@nhomar
@odony

**Comment by spadae22** [comment]
I am not an 'expert'... but have some common sense. Now when using real costing, product cost is zero. Purchase 5 units @ $1000. Product cost is zero? So when the first one in sold, it sells for 100% margin (zero cost). Then it updates, but the issue I also see is I but 5 more at $1200. First sells at 0 cost, 6 sell at  $1000, 4 @ $1000. This is not correct. We are looking to use landed costs and it does update the correct quants, but not on the sales order line where commission is paid from and the users see a zero cost? The above fix works correctly. 

The other issue that when you apply Landed Costs it does not update the cost, only the quant, until the first one is sold.... both should be fixed

**Comment by hbto** [comment]
Hi community,

We, at vauxoo, have been working for a while in computing rightfully landed
costs

https://github.com/Vauxoo/addons-vauxoo/pull/64

In the meantime we are working on UnitTest in order to provide a meaningful
use case.

Your input is valuable.

Best Regards

Quien suscribe,

*Hbto*

**Comment by hbto** [comment]
This is for average realtime products.

Best Regards.

Quien suscribe,

*Hbto*

**Comment by spadae22** [comment]
Great, is this ready to test?

**Comment by hbto** [comment]
E.R. Spada II

I am finishing TestUnits,

I considere it be ready to test leaning to production.

Best Regards.

Quien suscribe,

*Hbto*

**Comment by Yenthe666** [comment]
Hi @madrose,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
