### ISSUE TITLE
duplicate translation field in ir_translation after term synchronization.

### ISSUE THREAD

**Issue by crackerizer** [odoo/odoo#6149]
Hello,

In Odoo 8, when I use the menu 'Synchronize Terms' in Settings->Translations->Application Terms, number of term in ir_translation will be (almost) doubled every time. To reproduce, go to the menu as mentioned and do synchronization. Check the number of term in 'Translated term' menu.

**Comment by maljac** [comment]
Same problem here, V8 20150628

**Comment by SaFi2266** [comment]
I faced this issue too

**Comment by lapagept** [comment]
Idem here!

**Comment by pancks** [comment]
anybody got the solution for this?
