### ISSUE TITLE
All versions - 21 CFR part 11

### ISSUE THREAD

**Issue by aitalinassim** [odoo/odoo#61508]
**Impacted versions:**
All versions

**Steps to reproduce:**
Try a simple validation protocol to meet the 21 CFR part 11 for special sectors like food, medical ...

**Current behavior:**
Not possible to validate, many options are missing.

**Comment by Yenthe666** [comment]
It's not a bug, it's just not added? cc @pedrobaeza

**Comment by pedrobaeza** [comment]
It's a nonsense to start enumerating all the specific localization and sector things that Odoo doesn't handle because nobody has worked yet on that, so this is not a wishlist, but a development work for someone who wants to enter in that sector and in that country.

**Comment by aitalinassim** [comment]
> It's a nonsense to start enumerating all the specific localization and sector things that Odoo doesn't handle because nobody has worked yet on that, so this is not a wishlist, but **a development work** for someone who wants to enter in that sector and in that country.

Exactly, why not to be standard as some others do: Coppa Data, SAP ...
This is a feature which will open big doors to odoo.
@pedrobaeza

**Comment by pedrobaeza** [comment]
The focus of Odoo is not that one, but if you want to mount a company on top of current base specialized on that, for sure you will find your market.
