### ISSUE TITLE
[14.0]User can cancel repair after the product is repaired

### ISSUE THREAD

**Issue by hajajroshan** [odoo/odoo#61509]
**Impacted versions:**
14.0

**Steps to reproduce:**
- create a repair for a product
- complete the process
- make the repair order to repaired state

**Current behavior:**
![image](https://user-images.githubusercontent.com/62367855/98434277-4d8b0e80-20f4-11eb-9323-c363b71f5e1c.png)
in odoo 13 cancel button is invisible

**Expected behavior:**
Normally it should not possible to cancel a finished repair order. In version 13.0, the cancel button is invisible in the repaired state

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
I consider this as an improvement, as cancelling a repaired one can be a use case.

**Comment by Yenthe666** [comment]
Yep, I agree.

**Comment by pedrobaeza** [comment]
Closing then as no bug, but expected behavior (and improvement, although not all consider that. In my county, they say "It never rains to everyone's liking").
