### ISSUE TITLE
Company Map (google map) is not shown on contact page

### ISSUE THREAD

**Issue by alex71m-zz** [odoo/odoo#61501]
Impacted versions: v13

Steps to reproduce:
Install google map module, setup your API key and then navigate to your contact-us page.

Current behavior:
No map is shown

Expected behavior:
A Map centered on your company location should be shown

Solution:

modify .../addons/website/models/res_partner.py
by changing the return urlplus call on line 31 from

return urlplus('//maps.googleapis.com/maps/api/staticmap', params)

to

return urlplus('https://maps.googleapis.com/maps/api/staticmap', params)

![image](https://user-images.githubusercontent.com/13301337/98397399-96dd4e80-205f-11eb-986d-502f19b13d4a.png)

**Comment by rdeodoo** [comment]
I just had a look and everything is working fine, on runbot 12 13 14.
Since your report is quite new, please can you have another look?

**Comment by alex71m-zz** [comment]
Hi Roman

 

I updated odoo yesterday with the lasts build, removed an extension inheriting res_partner and now can confirm that this issue is gone.

Should I close it myself?

Thanks for your support…

 

Best Regards / Mit freundlichen Grüssen / Distinti saluti / Atenciosamente

F.Alex Maone

**Comment by pedrobaeza** [comment]
Closing as solved.
