### ISSUE TITLE
oddo problems with leap year

### ISSUE THREAD

**Issue by JDavidVR** [odoo/odoo#6150]
Hi I was testing oddo 8 and I found that it has problems with leap year.
When I was creating a new Fiscal year on: Accounting > Configuration > Periods > Fiscal Years

Start date 04/01/2015
End date 03/31/2016

it saves without problems, the problem appears when I press on "Create Monthly Periods" it can't generate automatically and it's because 2016 is a leap year so feb has 29 days.

I tested with another years:
Start date 04/01/2016
End date 03/31/2017

and it generates without problems

**Comment by Yenthe666** [comment]
Hi @JDavidVR,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
