### ISSUE TITLE
Payment screen: Payment method should be before payment amount

### ISSUE THREAD

**Issue by ybofr** [odoo/odoo#6151]
The reason is that the payment amount changes when you change the payment method. By having the amount below, the process is more fluid and there is no necessity for the user to go back to the payment amount.

Regards
Eva P.

**Comment by Yenthe666** [comment]
Hi @ybofr,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
