### ISSUE TITLE
[14.0] Stock Landed Cost type does not default from product

### ISSUE THREAD

**Issue by richard-willdooit** [odoo/odoo#61514]
Impacted versions:

14.0

Steps to reproduce:

Create a landed cost product with a default split method which is not equal

Current behavior:

Puttng on to a vendor bill and creating landed cost entries splits by equal

Expected behavior:

Should split using method on product.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Closing as there's a PR. If you plan to put a PR, you can put the issue description directly in the PR.

**Comment by richard-willdooit** [comment]
Not a problem.  Thanks.

**Comment by richard-willdooit** [comment]
I thought putting an issue might help if someone else finds the problem and looks if it has been reported ;)
