### ISSUE TITLE
Pay invoice screen: Does not calculate the difference amount

### ISSUE THREAD

**Issue by ybofr** [odoo/odoo#6152]
When I pay a GBP invoice in EUR, there may be difference, but the system does not calculate the difference amount immediately. Only when the button pay is pressed that the difference amount is calculated and this forces to reconcile the invoice manually after paying it.

Thank you for a correction.

This is valid for SAAS 6.0

**Comment by Yenthe666** [comment]
Hi @ybofr,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
