### ISSUE TITLE
Customer/Supplier payments: The system does not show original amount in invoice currency

### ISSUE THREAD

**Issue by ybofr** [odoo/odoo#6153]
When creating a payment, the system automatically calculates the original amount in the journal currency. This is not a wanted behaviour, as mostly on the payment document, the original amount in the document currency is shown. The calculation, based on any exchange rate is more troubling than helping.

Please let the original amount in the original currency and add the original currency next to it. This is the easiest way to have a proper search on the open invoices: using the original amount in the original currency.

Thanks

**Comment by Yenthe666** [comment]
Hi @ybofr ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
