### ISSUE TITLE
Hide fields in advance filter by using fields_get with selectable

### ISSUE THREAD

**Issue by myat90thu** [odoo/odoo#61559]
Impacted versions: 14.0

Steps to reproduce:

   @api.model
    def fields_get(self, fields=None, attributes=None):
        hide = ['invoice_user_id']
        res = super(AccountMove, self).fields_get(fields, attributes)
        for field in hide:
            res[field]['selectable'] = False
        return res

Current behavior:

- Still show "Salesperson" in advance filter selection box.

Expected behavior:

- Shouldn't show "Salesperson" in advance filter selection box.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Where do you get that this is the expected behavior?

**Comment by myat90thu** [comment]
Normally, we can hide Fields at Advance Filter.
To hide the field in advance filter, we have to use the code below:
`@api.model
def fields_get(self, fields=None, attributes=None):
hide = ['invoice_user_id']
res = super(AccountMove, self).fields_get(fields, attributes)
for field in hide:
res[field]['selectable'] = False
return res`

It still show invoice_user_id in advance filter.
