### ISSUE TITLE
Overload in the forecast of stock move version 14 odoo

### ISSUE THREAD

**Issue by sergiogonzalez298** [odoo/odoo#61557]
Impacted versions:
V14
Steps to reproduce:
when the proyect have many location in my case 42000 the widget for forecast overload the memory of server and cant open de stock picking 

![image](https://user-images.githubusercontent.com/23149912/98599474-49214a00-22dc-11eb-865a-fe21cb8dcbff.png)
The solution is get warehouse and put in the context can you fix this in the odoo repository?
@api.depends('product_id', 'picking_type_id', 'picking_id', 'reserved_availability', 'priority', 'state', 'product_uom_qty')
    def _compute_forecast_information(self):
        """ Compute forecasted information of the related product by warehouse."""
        self.forecast_availability = False
        self.forecast_expected_date = False

        not_product_moves = self.filtered(lambda move: move.product_id.type != 'product')
        for move in not_product_moves:
            move.forecast_availability = move.product_qty
        outgoing_unreserved_moves_per_warehouse = defaultdict(lambda: self.env['stock.move'])
        for move in (self - not_product_moves):
            picking_type = move.picking_type_id or move.picking_id.picking_type_id
            is_unreserved = move.state in ('waiting', 'confirmed', 'partially_available')
            if picking_type.code in self._consuming_picking_types() and is_unreserved:
                outgoing_unreserved_moves_per_warehouse[picking_type.warehouse_id] |= move
            elif picking_type.code in self._consuming_picking_types():
                move.forecast_availability = move.reserved_availability

        for warehouse, moves in outgoing_unreserved_moves_per_warehouse.items():
            product_variant_ids = moves.product_id.ids
            wh_location_ids = [loc['id'] for loc in self.env['stock.location'].search_read(
                [('id', 'child_of', warehouse.view_location_id.id)],
                ['id'],
            )]
            context = self.env.context.copy()
            context.update({'warehouse':warehouse.id})
            forecast_lines = self.env['report.stock.report_product_product_replenishment'].with_context(context)\
                ._get_report_lines(None, product_variant_ids, wh_location_ids)
            for move in moves:
                lines = [l for l in forecast_lines if l["move_out"] == move._origin and l["replenishment_filled"] is True]
                if lines:
                    move.forecast_availability = sum(m['quantity'] for m in lines)
                    move_ins_lines = list(filter(lambda report_line: report_line['move_in'], lines))
                    if move_ins_lines:
                        expected_date = max(m['move_in'].date for m in move_ins_lines)
                        move.forecast_expected_date = expected_date
![image](https://user-images.githubusercontent.com/23149912/98599600-88e83180-22dc-11eb-9f24-380414e0636f.png)

**Comment by pedrobaeza** [comment]
If you think you have a performance fix, please propose directly the PR.

**Comment by sergiogonzalez298** [comment]
Hello whats is the way for send this fix to PR?

**Comment by Yenthe666** [comment]
See https://github.com/odoo/odoo/wiki/Contributing#making-pull-requests
