### ISSUE TITLE
Create Database: SyntaxError: Unexpected token < in JSON at position 18 Odoo14

### ISSUE THREAD

**Issue by NizarMuhamad** [odoo/odoo#61563]
Impacted versions: 14.0

Steps to reproduce: Installed odoo 14
![Screenshot from 2020-11-10 15 26 36](https://user-images.githubusercontent.com/41617256/98648839-63553980-2369-11eb-8ab7-48916a0f1803.png)

Current behavior:
![Screenshot from 2020-11-10 10 31 45](https://user-images.githubusercontent.com/41617256/98648886-736d1900-2369-11eb-87a8-df6734d81625.png)

Expected behavior:
Database created

Video/Screenshot link (optional):

Anyone have the same problem?

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/14.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).

**Comment by NizarMuhamad** [comment]
Ok Thanks,
I will check it again
