### ISSUE TITLE
Interest on late payment

### ISSUE THREAD

**Issue by 2SI3NX** [odoo/odoo#6157]
Hi

I am struggling to find a way to automatically calculate interest on late payment on invoices.
Under 'Payment Terms' it does calculate percentage but it calculates it from the original price which is fine if you need to make certain payment terms with the customer.  But it should also calculate the interest percentage from the total amount of all invoices of the customer for the month and add it as an extra amount called: 'Interest on late payment'

It has been really hard to even find a module for this on the internet. they all say that i should edit account_invoice and i dont want to edit the code directly. 

Is there no way for this to be an enhancement for Odoo 8?

or if there is already a way to calculate interest on late payment then please let me know.

thanks in advance

**Comment by Yenthe666** [comment]
Hi @2SI3NX,

Sorry for the very late reply.
By default this wasn't available on V8. You could add custom code for it though!

Regards,
Yenthe
