### ISSUE TITLE
Delivered quantity on saleorder is not correct while using intercompany with transit location.

### ISSUE THREAD

**Issue by wruiter** [odoo/odoo#61612]
Impacted versions:
13.0

Steps to reproduce:
Setup 2 company's company 1 wil sell to company 2.
On both company's set customer and vendor location 2 inter company transit location.
 
Current behavior:
After confirming the outgoing shipment on company 1 the delivered quantity on the sale order stays on "0"

Expected behavior:
The delivered quantity should be counted correctly.

Video/Screenshot link (optional):
odoo/addons/sale_stock/models/sale_order.py /
![image](https://user-images.githubusercontent.com/31248475/98790715-67826500-2404-11eb-863e-5da55131ebfb.png)
![image](https://user-images.githubusercontent.com/31248475/98790750-6ea97300-2404-11eb-9954-2c38b589fd22.png)

**Comment by pedrobaeza** [comment]
You are doing an incorrect setting, as transit-locations can't be selected as customer locations (as their usage is not customer), so it's logical that this fails.

Closing as no bug, but incorrect settings.

**Comment by wruiter** [comment]
Can you explain why it is wrong using "Inter Company Transit" location for moving stock from company "a" to "b"?

**Comment by pedrobaeza** [comment]
Because that's not a customer location. Use another location with usage "customer", and then it will count as delivered. Note that inter company operations are not supported in community.
