### ISSUE TITLE
[all] product's main image size is allways "optimized" (and higher than expected)

### ISSUE THREAD

**Issue by zeroheure** [odoo/odoo#61620]
Optimized images from graphical team can't be kept.

Impacted versions: 8,9,10,11,12,13

Steps to reproduce: Optimize image file size for the web, using Gimp "Save For The Web" plugin or [Mozilla mozjpeg tool](https://github.com/mozilla/mozjpeg) or an optimization service like [ImageOptim free web interface](https://imageoptim.com/online). Use it as your **product's main image**.

Current behavior: Even if you ask to not optimize, Odoo save the image in the wrong quality and it can't keep the optimized file size. For example, on Odoo 13 size increase from 45 Kb to 152 Kb like the optimized one attached. This doesn't happen to images uploaded through web_editor.

Expected behavior: Be allowed to really disable Odoo image optimization. 

See a test image attached.
![carte cadeau recto-R](https://user-images.githubusercontent.com/24126/98855784-dd1a1f80-245c-11eb-95f2-f30f6bdf598b.jpg)

**Comment by pedrobaeza** [comment]
There are no plans of changing how this works in this version. Let's talk in #61619 about 14.0

**Comment by zeroheure** [comment]
it is not the same problem than  #61619

**Comment by pedrobaeza** [comment]
This is not what I have said. It's that this won't be changed in these versions.

**Comment by zeroheure** [comment]
Still in #15

**Comment by zeroheure** [comment]
Please reopen as a wish
