### ISSUE TITLE
Web editor background color not applying when header position as over the content

### ISSUE THREAD

**Issue by saikiruba-mj** [odoo/odoo#61655]
Impacted versions:14.0

Steps to reproduce:

1. Press Edit in website Editor

2. Mouseover navbar header and change background color with header position as over the content

3.While preview background color applying fine but while saving not applying properly 

Current behavior: Background color not applying while saving

Expected behavior:  Background color need to apply while saving

**Comment by pedrobaeza** [comment]
Duplicated of #61654
