### ISSUE TITLE
Fiscal position should be based on Delivery Address not Customer

### ISSUE THREAD

**Issue by pjmcdermott** [odoo/odoo#6166]
If you set up "Automatic" Fiscal Positions and create a Quotation, the Fiscal Position field is completed after selecting a Customer, but not after selecting a Delivery Address.

There should at least be an option to create Fiscal Positions based on the delivery address.

An example use case:
If you are based in the UK and sell goods to UK or EC consumers, VAT needs to be charged at the standard rate. If you sell goods outside of the EC, VAT is charged at zero rate. But whether to charge VAT is determined by the shipping address, not the customer address. If a UK billing address customer wants an order shipped outside of the EC, then it should be zero rated. If a customer based in the USA orders goods, but has them shipped to a forwarding address in the UK, then they should not be zero rated. The correct VAT is based on the shipping address, not the billing address.

Fiscal Positions would be an ideal way to trigger the alternative VAT arrangements. But as currently setup, they are triggered by the Customer field on the quotation form, not the Delivery Address field. Delivery Address triggered Fiscal Positions should be a possibility.

**Comment by Yenthe666** [comment]
Hi @pjmcdermott,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
