### ISSUE TITLE
The testing credential for dhl module return Site Id is wrong error

### ISSUE THREAD

**Issue by frlanxpertiz** [odoo/odoo#61674]
Impacted versions: 13 and 14

Steps to reproduce:
install the dhl shipping module and publish it on the website with the testing credentials. then go on the payment page of your cart.

Current behavior:
return "100: Validation Failure:Site Id is wrong"

**Comment by pedrobaeza** [comment]
As this is an enterprise module, please report it to odoo.com/help.

Closing as this issue in public tracker doesn't add too much value right now, as this can be linked to the deployment.
