### ISSUE TITLE
Webbuilder Create page throws Internal Server Error (500) when using accents in Title

### ISSUE THREAD

**Issue by exidoncom** [odoo/odoo#6167]
**Create page throws Internal Server Error (500) when using accents in Title**

Impacted versions:
- 8.0

Steps to reproduce:
1. install Odoo 8.0 on Ubuntu 12.14 (I installed on digital ocean)
2. enable webbuilder module
3. create new page with title including accents like  "áúé something"

Current behavior:
- throws internal server error

Expected behavior:
- create the page as on demo.odoo.com instance

**Comment by Yenthe666** [comment]
Hi @exidoncom,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
