### ISSUE TITLE
method self, does not have env attribute

### ISSUE THREAD

**Issue by ronozoro** [odoo/odoo#6168]
i create this function to get some data and do sum operation when i excute it
it give me error does not have env attribute
Here is my code 
```python
def get_the_noobs_attendace(self,cr,uid,ids,context=None):
        noobs_data=[]
        subject_id=8
        self._cr.execute(
            "select DISTINCT ON (student_id)student_id, count(present) AS Number_of_Absenece,present, s.name AS Student_Name from fci_attendance_line ,fci_student s,fci_subject d where d.id=%d and present=False group by student_id ,s.sit_number,present, s.name  "% (
                subject_id))
        noobs = self._cr.dictfetchall()
        self._cr.execute(
            "select DISTINCT ON (student_id)student_id, count(present) AS Number_of_Absenece,present, s.name AS Student_Name  from fci_attendance_line ,fci_student s,fci_subject d where d.id=%d and present=False group by student_id ,s.sit_number,present, s.name  "% (
                subject_id))
        noobs_details = self._cr.dictfetchall()
        for details_ids in noobs_details:
            for data in noobs:
                details_ids[data['student_id']] = '(' + str(data['number_of_absenece']) + ')\n' + data['student_name']
            noobs_data.append(details_ids)
        print (noobs_data)
        return noobs_data
```

**Comment by jssuzanne** [comment]
the attribute "env" is only for the new api, you use the old api.
http://odoo-new-api-guide-line.readthedocs.org/en/latest/

2015-04-07 1:34 GMT+02:00 ronozoro <notifications@github.com>:

> i create this function to get some data and do sum operation when i excute
> it
> it give me error does not have env attribute
> Here is my code
> [CODE]
> def get_the_noobs_attendace(self,cr,uid,ids,context=None):
> noobs_data=[]
> subject_id=8
> self._cr.execute(
> "select DISTINCT ON (student_id)student_id, count(present) AS
> Number_of_Absenece,present, s.name AS Student_Name from
> fci_attendance_line ,fci_student s,fci_subject d where d.id=%d and
> present=False group by student_id ,s.sit_number,present, s.name "% (
> subject_id))
> noobs = self._cr.dictfetchall()
> self._cr.execute(
> "select DISTINCT ON (student_id)student_id, count(present) AS
> Number_of_Absenece,present, s.name AS Student_Name from
> fci_attendance_line ,fci_student s,fci_subject d where d.id=%d and
> present=False group by student_id ,s.sit_number,present, s.name "% (
> subject_id))
> noobs_details = self._cr.dictfetchall()
> for details_ids in noobs_details:
> for data in noobs:
> details_ids[data['student_id']] = '(' + str(data['number_of_absenece']) +
> ')\n' + data['student_name']
> noobs_data.append(details_ids)
> print (noobs_data)
> return noobs_data
> [/CODE]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/odoo/odoo/issues/6168>.
>



-- 

Jean-Sébastien SUZANNE

jssuzanne@anybox.fr
