### ISSUE TITLE
Location wise stock & Cost in Product Master with Currency

### ISSUE THREAD

**Issue by orchidinfosys** [odoo/odoo#617]
Showing location wise stock in product master will be useful.
In Multi company Multi Currency environment - cost of sales must be calculated based on locations. So keeping the cost and stock in location wise will be a good solution for MNC s.

**Comment by Yenthe666** [comment]
Dear @orchidinfosys,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
