### ISSUE TITLE
Odoo ignores record rules and shows invoices to a wrong person from wrong company inside Portal

### ISSUE THREAD

**Issue by Gumaa** [odoo/odoo#61702]
Impacted versions: 13.0

Steps to reproduce:

1. Create sale order (I have sale order generated by eCommerce module)
2. Generate invoice on this sale order
3. Modify the invoice partner_id as well as company of the invoice
4. Log in as original partner

Current behavior:
**Odoo still shows the invoice to the original customer even if partner and company of the invoice does not match**

Expected behavior:
Odoo does not show invoices to a customer if he isn't the receiver or invoice has different company that he has

Weird enough there are record rules for that and they seem to work on a `my/home` page with a summary of all the various documents. But when displaying linked invoices on a sale order it straight up just ignores them.

This is the line responsible for showing the invoices (`addons\sale\views\sale_portal_templates.xml`):
```xml
<t t-set="invoices" t-value="[i for i in sale_order.invoice_ids if i.state not in ['draft', 'cancel']]"/>
```

And maybe it ignores all the record rules on invoices because `sale_order` is fetched with superuser (`addons\sale\controllers\portal.py`):

```python
order_sudo = self._document_check_access('sale.order', order_id, access_token=access_token)
# ...
values = {
    'sale_order': order_sudo,
# ...
```

```python
def _document_check_access(self, model_name, document_id, access_token=None):
    document = request.env[model_name].browse([document_id])
    document_sudo = document.with_user(SUPERUSER_ID).exists() # <----------- SUPERUSER!
    if not document_sudo:
        raise MissingError(_("This document does not exist."))
    try:
        document.check_access_rights('read')
        document.check_access_rule('read')
    except AccessError:
        if not access_token or not document_sudo.access_token or not consteq(document_sudo.access_token, access_token):
            raise
    return document_sudo
```

This is really bad and I don't know if I can trust Odoo on handling document permission any more.

**Comment by rdeodoo** [comment]
> This is really bad and I don't know if I can trust Odoo on handling document permission any more.

The system is working as it should. The customer that created the sale order is set as customer **AND** follower of the invoice you created for that sale order.
So even if you changed the customer after creating the invoice, he is still follower and allowed to see the invoice which makes sense as he is the owner of the order and will always be as you won't be able to change that once the SO is validated.

If you really want the customer to not see the invoice of his own sale order, remove him from the followers but that's a weird flow IMHO.

**Comment by Gumaa** [comment]
Problem is that customers were able to view the invoices **even when they were not followers of that invoices**.
That is the whole point.

```xml
<t t-set="invoices" t-value="[i for i in sale_order.invoice_ids if i.state not in ['draft', 'cancel']]"/>
```

This line inside `addons\sale\views\sale_portal_templates.xml` shows every invoice assigned to that particular sale order. Without checking customer or followers of that invoice.

**Comment by rdeodoo** [comment]
That's not what I experienced when testing it, removing the customer from the invoice follower correctly removed the invoiced from the portal.

**Comment by pedrobaeza** [comment]
AFAIK record rules are always applied, even on one2many/many2many like the expression `sale_order.invoice_ids`, so I'm with @rdeodoo

**Comment by Gumaa** [comment]
I have replicated this bug inside runbot:
https://5608325-13-0.runbot39.odoo.com (5608325-13-0-all).

1. Login as portal user
2. Create an order
3. With an admin confirm the order and create invoice - but do not validate it yet
    (At this point invoice does not have followers other than admin)
4. Inside the invoice change the customer to a different user
5. Validate the invoice - invoice now has new customer and admin as the followers
6. Portal users still has access to the invoice

![image](https://user-images.githubusercontent.com/16503469/103638583-688bca80-4f4d-11eb-88bb-96d9ac6e1d8d.png)
![image](https://user-images.githubusercontent.com/16503469/103638600-6f1a4200-4f4d-11eb-81c7-aab690f53ab7.png)

**Comment by pedrobaeza** [comment]
OK, seems to be correct, although weird use case, but it's true that they are not filtered out if invoices have other followers. I'm reopening, but not sure if Odoo will consider this as a problem to be fixed.

**Comment by rdeodoo** [comment]
I don't think that's a flow we want to consider as a bug, I would even consider it as a good compromise after thinking about it.
The client don't see the invoice in his `/my/invoices` listed directly but he can still see the invoices related to **his** order under his `/my/order` as shown on previous @Gumaa answer.
At the end it's nice to see how/why **his** order is paid, since it is still his order, even tho it was paid by another person/entity.

We can still ask for @sbuhl POV

**Comment by sbuhl** [comment]
I do agree with @rdeodoo arguments. 
The use-case sounds strange in my opinion though.

**Comment by pedrobaeza** [comment]
Closing then. Thanks for the feedback.
