### ISSUE TITLE
Multiple Reseller Locations

### ISSUE THREAD

**Issue by Xpiva** [odoo/odoo#6171]
I have re-sellers with multiple locations, however the re-seller page only shows the main location. I added each location as a contact then gave each contact a grade same as the main company.
Is this a bug, or by design. if by design, how can I change that and also search by zip code within ?miles?

**Comment by Yenthe666** [comment]
Hi @Xpiva,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
