### ISSUE TITLE
[14.0] Undefined exception thrown in _tag_root while xml-view import 

### ISSUE THREAD

**Issue by lrstry** [odoo/odoo#61715]
Impacted versions: ODOO Community Edition 14.0-20201111 (and prior 14.0 releases)

Steps to reproduce:

- My custom module is perfectly working in 13.0
- I followed the migration steps described in [Migration to version 14.0](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0)
- Import the following stripped-down views/hr_employee.xml as data-import (defined in __manifest__.py):

```xml
<?xml version="1.0" encoding="utf-8"?>
<odoo>
    <record id="view_employee_form" model="ir.ui.view">
        <field name="name">hr.employee.form</field>
        <field name="model">hr.employee</field>
        <field name="inherit_id" ref="hr.view_employee_form"/>
        <field name="arch" type="xml">
            <xpath expr="//field[@name='category_ids']" position="attributes">
                <attribute name="invisible">1</attribute>
            </xpath>
        </field>
    </record>
</odoo>
```

Current behavior:

> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
>     result = request.dispatch()
>   File "/usr/lib/python3/dist-packages/odoo/http.py", line 682, in dispatch
>     result = self._call_function(**self.params)
>   File "/usr/lib/python3/dist-packages/odoo/http.py", line 358, in _call_function
>     return checked_call(self.db, *args, **kwargs)
>   File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
>     return f(dbname, *args, **kwargs)
>   File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in checked_call
>     result = self.endpoint(*a, **kw)
>   File "/usr/lib/python3/dist-packages/odoo/http.py", line 911, in __call__
>     return self.method(*args, **kw)
>   File "/usr/lib/python3/dist-packages/odoo/http.py", line 530, in response_wrap
>     response = f(*args, **kw)
>   File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1363, in call_button
>     action = self._call_kw(model, method, args, kwargs)
>   File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1351, in _call_kw
>     return call_kw(request.env[model], method, args, kwargs)
>   File "/usr/lib/python3/dist-packages/odoo/api.py", line 396, in call_kw
>     result = _call_kw_multi(method, model, args, kwargs)
>   File "/usr/lib/python3/dist-packages/odoo/api.py", line 383, in _call_kw_multi
>     result = method(recs, *args, **kwargs)
>   File "<decorator-gen-78>", line 2, in button_immediate_upgrade
>   File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 73, in check_and_log
>     return method(self, *args, **kwargs)
>   File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 653, in button_immediate_upgrade
>     return self._button_immediate_function(type(self).button_upgrade)
>   File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 592, in _button_immediate_function
>     modules.registry.Registry.new(self._cr.dbname, update_module=True)
>   File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 89, in new
>     odoo.modules.load_modules(registry._db, force_demo, status, update_module)
>   File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 451, in load_modules
>     force, status, report, loaded_modules, update_module, models_to_check)
>   File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 348, in load_marked_modules
>     perform_checks=perform_checks, models_to_check=models_to_check
>   File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 221, in load_module_graph
>     load_data(cr, idref, mode, kind='data', package=package)
>   File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 69, in load_data
>     tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
>   File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 733, in convert_file
>     convert_xml_import(cr, module, fp, idref, mode, noupdate)
>   File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 799, in convert_xml_import
>     obj.parse(doc.getroot())
>   File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 719, in parse
>     self._tag_root(de)
>   File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 684, in _tag_root
>     etree.tostring(rec, encoding='unicode').rstrip()
> Exception
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/odoo/http.py", line 638, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/usr/lib/python3/dist-packages/odoo/http.py", line 314, in _handle_exception
>     raise exception.with_traceback(None) from new_cause
> odoo.tools.convert.ParseError: while parsing /mnt/extra-addons/custom_swaf_hr/views/hr_employee.xml:3, near
> <record id="view_employee_form" model="ir.ui.view">

Expected behavior:

- I don't see any problem with overwriting hr.view_employee_form this way and also not within the XPath-definition, since it worked in v13
- I would wish to get a more precise Exception message

**Comment by pedrobaeza** [comment]
Sorry, this is not a problem of Odoo, but your custom module, so it's out of the scope of this issue tracker. The message error is cut, so please find the complete one and post it on forums or mailing lists for getting support.

Closing due to this.

**Comment by lrstry** [comment]
I get your point. It's being caused by Xpath expressions which are not valid anymore moving from v13 to v14.

BUT:

The error-log being returned by convert.py/_tag_root():681 #(https://github.com/odoo/odoo/commit/8bb0530017adba6a37f2b1ad36a5c9dfddae17d7) does not help at all.
The exception object e knows the exact Xpath-expression causing the problem but this is not being indicated in the error-log.

I suppose a lot of developers are being confronted by this kind of exception while migrating to v14 and it would be helpful for the community to receive meaningful information in the error-log to efficiently resolve these migration issues.

**Comment by pedrobaeza** [comment]
I remember receiving the exact problem when having a bad inheritance with xpaths migrating some modules in v14, so you are probably seeing at the bottom while you have to check upper in the log.

**Comment by lrstry** [comment]
> I remember receiving the exact problem when having a bad inheritance with xpaths migrating some modules in v14, so you are probably seeing at the bottom while you have to check upper in the log.

That's not true in this case. Have a look at my edit. Helpful information in Exception e is not being used at all to generate the error log message.
