### ISSUE TITLE
Amount currency (and currency_id) added when it is not supposed to

### ISSUE THREAD

**Issue by bringsvor** [odoo/odoo#6174]
Hi

I suddenly kept running into this constraint when creating an account move (in my own module):

(_check_currency_amount, 'The amount expressed in the secondary currency must be positive when account is debited and negative when account is credited.', ['amount_currency']),

This had been working fine before, so I had to do some digging. Turned out that when my move_line did not have a currency_id and an amount_currency, but the default account of the journal had, the currency_id and amount_currency of the default credit (or debit) account of the journal was used. And in this instance someone had configured a secondary currency on the account that was configured to be the default account for the journal (in good faith I believe).

Is this a feature? It seems more like a bug to me. Also to make matters worse the amount_currency (which should not have been there in the first place) is not calculated with a minus sign when the move line is a credit line so the posting failed (thankfully, in this instance).

**Comment by Yenthe666** [comment]
Hi @bringsvor,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
