### ISSUE TITLE
[migrations] migration script for v7 no longer works

### ISSUE THREAD

**Issue by duanyp1991** [odoo/odoo#6177]
Hi all,

I want to execute a method once one module is firstly installed.
**What I have tried:**
My current version of the module is: 7.0.1.2 and here is my folder structure:
<moduledir>
            `-- migrations
                |-- 7.0.1.2
                |   |-- post-migration.py
 
and in the file: **post-migration.py**, I put a method:
```python
def migrate(cr, version):
    if not version:
        # here goes the code.
```

**What is the result**: 
Failed! The method is not executed.

**Extra note**:
I tried before and it worked, so I wonder if the function of Odoo has changed somehow.
I spent some time debugging on it: it always pass this if:
```python
if not (hasattr(pkg, 'update') or pkg.state == 'to upgrade'):
    return
```

Looking forward to your reply and thanks in advance!

BR,
Alex

**Comment by KangOl** [comment]
Not a bug.
Migration script are for **migration**, not **installation**.

There are now hooks you can define, which will be called at module install et uninstall.

See 4105b5f0285821d8056c721b5fd50b9cae902988
