### ISSUE TITLE
[13.0] I can't reserve a full lot to a MO even the quantity planned is lower

### ISSUE THREAD

**Issue by SIC-pmrteixeira** [odoo/odoo#61819]
Impacted versions: 13.0

Steps to reproduce: Have producsts by lot to be consume by a manufacturing order

Current behavior: Wen I have a lot with bigger quantity then I have planned for an MO, Odoo will reserve the quantity planned for the MO and the remaining quantatie in other MO that have the same need

Expected behavior:  I can't do parcial consuption of the lot, once open the lot he dosen't availeble to stock, so it's not real to reserve the remain quantatie for other MO. It's possible reserve a full lot to a MO even the quantity planned is lower?

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
I don't get the problem, as the reserved quantity is different from the quant quantity. Can you put a video explaining the problem?

**Comment by SIC-pmrteixeira** [comment]
I can´t made a video because I can't put in Odoo, is what want I want :)
I'll try to explain with an simple exemple:
Imagine I have a sandwich factory and I have an MO to manufacturing Sandwichs with tomato, based on the quantaty planned I'll need 0,6 tomato and Odoo will reserve 0,6 of tomato leaving the 0,4 in wherehouse, but I want to reserve 1 tomato instead of 0,6 because I will rever return the other 0,4 tomato to the wherehouse.
This explain better the problem?

**Comment by pedrobaeza** [comment]
This is not a problem, but a feature request, but you can try to simulate through units of measure with rounding in bill of materials.

Closing as no Odoo bug, but question, and answered in a brief way. For further questions, please go to the forums.

**Comment by SIC-pmrteixeira** [comment]
Hi Pedro Baeza,

Hi Pedro Baeza, Yes it's a feature request and through units of measure do not answer it, because I want to book all the lot regardless the unit or quantity in stock.

Thanks for your feedback.
