### ISSUE TITLE
SMTP - hello command rejected: Get lost!

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#6181]
I configured outgoing mail server with Connection security: TLS (STARTTLS) and provided username/password. smtp port: 25. Checking connection gives this message:

```
Connection Test Succeeded!

Everything seems properly set up!
```

But if I send mail, in log I see this:

```
2015-04-07 12:38:48,674 5156 ERROR db_name openerp.addons.base.ir.ir_mail_server: Mail delivery failed via SMTP server 'smtp.test.com'.
SMTPRecipientsRefused: {'"test@test.com"': (554, '5.7.1 <localhost.localdomain>: Helo command rejected: Get lost!'), 'test@test.com': (554, '5.7.1 <localhost.localdomain>: Helo command rejected: Get lost!')}
```

Does Odoo not support some smtp servers or smtp server migh not let Odoo use it? Or maybe something else might be the problem?

That mail server works normally outside Odoo.

**Comment by Yenthe666** [comment]
Hi @oerp-odoo ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
