### ISSUE TITLE
[8.0] product_qty not initialized: this is a regression introduced by c9154e08

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#6189]
I'm very concerned by  a1da6c21325ae7121aaba643aa1eea6401649dec by @simongoffin, which only fixes the symptom and not the underlying cause.

I hit this issue when creating pickings from a SO with invoicing policy 'before delivery'. In which case, the stack leading to the creation of the stock move by the procurement goes through several workflow transitions. 

At one step of this stack, account_move_line.reconcile() is called, which triggers the creation of an account_move_line. This call to models.create() goes in the "recompute new-style fields" section of models._create, which calls models.recompute. The code of recompute was modified in c9154e08 by @beledouxdenis to use with `rec.env.norecompute()`. 

As a result of this, when the stock.move is finally created, `recs.env.recompute` is False. This causes stored function fields to not be recomputed and therefore not stored (see https://github.com/odoo/odoo/blob/8.0/openerp/models.py#L4252) which is exactly the point of c9154e08 from the changeset description. I don't understand why new API function fields are not affected by this behavior

In my opinion, c9154e08 is a problematic changeset, as it introduces this regression, an potentially many others, as any old api object created after the account move line in the chain of workflow propagation will suffer the same issues with its stored computed fields. 

a1da6c21325ae7121aaba643aa1eea6401649dec does fix the problem for stock.move, but there are potentially production databases affected by this and being slowly and silently corrupted right now.

**Comment by gurneyalex** [comment]
this is potentially related to  #4905 (cc @olilau et @odony who participated in the discussion on that issue).

**Comment by odony** [comment]
Please discuss it on #6053, it is the PR that should have been reviewed before committing a1da6c2
