### ISSUE TITLE
Qweb group-based control of contents is not possible

### ISSUE THREAD

**Issue by alejandrosantana** [odoo/odoo#6190]
**Based on https://github.com/odoo/odoo/issues/5058 , it looks impossible to have group-based control over qweb template contents.**

Impacted versions:

 - 8.0

Steps to reproduce:

 1. Try to create a module that extends some qweb view template and try to hide some element based on user's groups.

Current behavior:

 - Impossible to have group-based control over qweb template contents.

Expected behavior:

 - Easy xpath + 'groups="my_whatever_security_group' group-based control over qweb template contents, as with regular views.

**Comment by xmo-odoo** [comment]
No issue here. Created a module with just a server-side template:
```xml
<openerp>
  <data>
    <template id="remove_about" inherit_id="website.footer_default">
      <xpath expr="//div[3]/div" position="attributes">
        <attribute name="groups">base.group_no_one</attribute>
      </xpath>
    </template>
  </data>
</openerp>
```
and when the module is installed the rightmost section of the footer disappears unless the current user is logged in and a member of `base.group_no_one`.

**Comment by alejandrosantana** [comment]
@xmo-odoo There are two different scenarios, and yours is different from what I try to explain. Maybe I failed explaining myself, so I will try to explain this better.

### Scenario 1: (Let's call it *python-qweb*?) - Your example
- Module: website
- Template "footer_default" is defined in file: website/views/website_templates.xml
- This file has <openerp><data> tags
- This file is imported in \_\_openerp\_\_.py within 'data' key (same as any regular view)
- To extend this template you can use *inherit_id*, xpath and *groups* policy to hide elements based on user's groups:
```
<openerp>
  <data>
    <template id="remove_about" inherit_id="website.footer_default">
      <xpath expr="//div[3]/div" position="attributes">
        <attribute name="groups">base.group_no_one</attribute>
      </xpath>
    </template>
  </data>
</openerp>
```
- Nice and almost lovely. :)


### Scenario 2: (Let's call it *json-qweb*?) - My case
- Module: web
- Template "UserMenu.about" is defined in file: web/static/src/xml/base.xml
- This file does **not** have <openerp><data> tags.
- This file is imported in \_\_openerp\_\_.py within 'qweb' key
- If you try to extend this template like qweb views (the other example) with *inherit_id* (not even xpath involved), it fails silently (no one warning in log) giving a 'Internal Server Error' on browser.
- To extend this template you must use no <openerp><data> tags in this file and *t-extend* syntaxis. Something like:
```
<?xml version="1.0" encoding="UTF-8"?>
<templates id="template" xml:space="preserve">
    <t t-extend="UserMenu.about">
        <t t-jquery=".oe_activate_debug_mode" t-operation="replace">
            <a class="oe_activate_debug_mode oe_right label label-primary hidden" href="?debug" groups="base.group_no_one">Activate the developer mode</a>
        </t>
    </t>
</templates>
```
- There *groups* policy has no effect at all for hiding elements, and "groups" is set as a simple html attribute. Thefore, *groups* is useless to hide elements based on user's groups.


**Current behaviour:**
- Qweb templates behave in two completely different fashion depending on how they are imported (in 'data' vs 'qweb', with or without <openerp><data> tags in file).


**Desirable behaviour:**
- Consistent behaviour in all qweb templates, and being able to keep using *groups* attribute in xml.


**Doubts:**
- How to capture current user's groups or user *uid* to try using *t-if* (if possible)?
- Is it necessary to extend JS methods in order to achieve something that in views takes less than a line?
- Aren't all qweb templates "qweb view templates"? What else should they be called? Why two different behaviours?

**Comment by xmo-odoo** [comment]
> Consistent behaviour in all qweb templates, and being able to keep using groups attribute in xml.

Not going to happen, qweb rendering is synchronous and supporting groups on the JS side would require an asynchronous call to the server. If you want that filtering, extend the corresponding widget to fetch whatever group information you need asynchronously and change the template to use that information.

> Is it necessary to extend JS methods in order to achieve something that in views takes less than a line?

Yes.

> Aren't all qweb templates "qweb view templates"?

No. QWeb view templates are qweb templates stored as Odoo views, that uses the Python implementation. Client-side qweb templates are loaded directly by clients from the XML files.

> What else should they be called? 

Client and server? JS and Python?

> Why two different behaviours?

Because different implementations with different underlying capabilities, extension mechanisms, execution contexts and expression languages.

**Comment by alejandrosantana** [comment]
Thanks for clarification.
