### ISSUE TITLE
[14.0] raw field in ir.attachment via xml-rpc give not well-formed (invalid token):

### ISSUE THREAD

**Issue by OmniaGit** [odoo/odoo#61919]
Impacted versions: 14.0

Steps to reproduce:
run the following script:
```
import xmlrpc.client
db='' # write your database
user='' #write your user
password='' # write your password
url = 'http://localhost:8069'
ir_attachment_ids = [] # your valid ir_attachemnt_id
common = xmlrpc.client.ServerProxy('{}/xmlrpc/2/common'.format(url))
uid = common.authenticate('odooV14E_PLM_demo', 'admin', 'admin', {})
models = xmlrpc.client.ServerProxy('{}/xmlrpc/2/object'.format(url))
res11 = models.execute_kw(db, uid, password,'ir.attachment', 'read', ir_attachment_ids ,{'fields': ['raw'],'load': 'load'})
```

Current behavior:
the call give this error
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.7/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/usr/lib/python3.7/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.7/xmlrpc/client.py", line 1170, in single_request
    return self.parse_response(resp)
  File "/usr/lib/python3.7/xmlrpc/client.py", line 1336, in parse_response
    p.feed(data)
  File "/usr/lib/python3.7/xmlrpc/client.py", line 439, in feed
    self._parser.Parse(data, 0)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 53, column 15
```
The error is due to the field raw in the ir.attachment that when it's returned give the error:
The field definition is this:
`raw = fields.Binary(string="File Content (raw)", compute='_compute_raw', inverse='_inverse_raw')`

Expected behavior:
no error
Video/Screenshot link (optional):

**Comment by xmo-odoo** [comment]
Finally noticed this issue. The good news is we can probably fix the crash, the bad news is... that's unlikely to be by returning the data, the cause of the crash is a BC shim which assumes binary data is base64 and forces a string output for historical reasons.

xmlrpc.client's `Binary` is absolutely not compatible with bytes, so updating the code to serialize binary data as an actual XMLRPC-level binary would break existing clients. And conditionally outputting binary data or text depending on the details of the content seems... more than iffy. Also wouldn't really work the other way around as there's a similar issue: the server generally doesn't handle `xmlrpc.client.Binary` objects at all.
