### ISSUE TITLE
[11.0] hw_ecspos: throw an error "cannot set daemon status of active thread"

### ISSUE THREAD

**Issue by Hoaitran299** [odoo/odoo#61912]
Impacted versions: [11.0] POSBOX

Steps to reproduce: 
I'm using [11.0] POSBOX, Ubuntu 16.04, printer CodeSoft.  
Normally it works, but sometimes it goes wrong 5-6 times a day.

Current behavior:
- POS printer connection is Red.
- Tickets are not printed.
- Cashdrawer doesn't open automatically.
- Posbox odoo-log show the following error:
![image](https://user-images.githubusercontent.com/68218154/99504129-a8a0e900-29b1-11eb-86c7-4d1cbaf1731c.png)

Expected behavior:
My current temporary workaround is to restart POSBOX.
But I want it to work properly because it's quite inconvenient if the customer is using it and fails continuously for a day.

Video/Screenshot link (optional):
Currently, printer connection is in red but connected via ssh to the POSBOXand I do a ping to server all packets are transmitted
![image](https://user-images.githubusercontent.com/68218154/99504419-1c42f600-29b2-11eb-95e1-407eaeacc805.png)

**Comment by pedrobaeza** [comment]
Please update to IoTBox, as this is no longer supported.

Closing as out of official support.
