### ISSUE TITLE
[14.0] POS translation

### ISSUE THREAD

**Issue by qdelcourte** [odoo/odoo#61947]
Impacted versions:
14.0

Steps to reproduce:
- Runbot 14.0
- Set fr_Fr language
- Start POS

Current behavior:

See sales receipt screenshot.
"Served by" is not translated.

https://github.com/odoo/odoo/blob/d66063ea1d5f2c43867ce1cbf627e175c04b8fa2/addons/point_of_sale/static/src/xml/Screens/ReceiptScreen/OrderReceipt.xml#L41

Expected behavior:

Should be translated with this:

https://github.com/odoo/odoo/blob/d66063ea1d5f2c43867ce1cbf627e175c04b8fa2/addons/point_of_sale/i18n/fr.po#L4316-L4321

Another example but this time in JS
"Set Customer", "Deselect Customer", "Change Customer" aren't translated
https://github.com/odoo/odoo/blob/d66063ea1d5f2c43867ce1cbf627e175c04b8fa2/addons/point_of_sale/static/src/js/Screens/ClientListScreen/ClientListScreen.js#L85-L93

**There are plenty of them in fact. I can't list you all the case like this but there is a lot.**
Do you plan to add them later or is it an oversight?

Video/Screenshot link (optional):

<img src="https://user-images.githubusercontent.com/30729669/99536962-55c43300-29ab-11eb-8fc0-45352eca50dd.png" width="300">
<img src="https://user-images.githubusercontent.com/30729669/99537838-7345cc80-29ac-11eb-97c6-e480474ff6d5.png" width="300">

**Comment by pedrobaeza** [comment]
@yelizariev can it be the same problem as in "This Week"?

**Comment by yelizariev** [comment]
I dont't think so. Both duplicates have openerp-web comment. "This week" issue happens when a term without openerp-web override the one with openerp-web.

https://github.com/odoo/odoo/blob/f22c34e7f61f7f8ac5b9ab7f9579cc4e6dd0e334/addons/pos_restaurant/i18n/pos_restaurant.pot#L1006-L1011

https://github.com/odoo/odoo/blob/f22c34e7f61f7f8ac5b9ab7f9579cc4e6dd0e334/addons/point_of_sale/i18n/point_of_sale.pot#L4189-L4194

**Comment by pedrobaeza** [comment]
OK, thanks for the clarification.

**Comment by yelizariev** [comment]
It's because of space around the term. It's fixed in owl. We are waiting when it's updated in Odoo
https://github.com/odoo/owl/commit/f54b9a4a0cbdd5bb6088b15218e73d5b4a9731c8
cc @ged-odoo

**Comment by yelizariev** [comment]
opw-2399387

**Comment by yelizariev** [comment]
Fixed in https://github.com/odoo/odoo/pull/63327
