### ISSUE TITLE
[13.0] fiscal position can be deleted

### ISSUE THREAD

**Issue by zeroheure** [odoo/odoo#61942]
Impacted versions: 10 (untested on others)

Steps to reproduce: set a fiscal position on an invoice, validate the invoice. Go to Accounting > Fiscal position, delete that fiscal position (as admin). Works exactly the same for a tax.

Current behavior: no error message while we can't know if a tax or fiscal position is in use.

Expected behavior: at least something like "this is a dangerous action".

**Comment by pedrobaeza** [comment]
10.0 is not supported anymore (nor 11.0). If this is happening in 12.0+, please write back, but meanwhile, we should close this.

**Comment by zeroheure** [comment]
Please re-open. Tested on Odoo 13 enterprise. Both taxes and fiscal position can be deleted while in use.

**Comment by Vanneri** [comment]
@pedrobaeza  Fixes at #62167
