### ISSUE TITLE
Manufacturing Work Order bug

### ISSUE THREAD

**Issue by spinks-bill** [odoo/odoo#61955]
I have been working with a couple odoo reps on a demo site before purchase.  This last issue I was told was a bug and I need to post here so it can be addressed.

Impacted versions:14

Steps to reproduce:  Create sales order of made to order product which initiates purchase order, manufacturing orders and work orders.

Current behavior: Work Orders showing ready even when there is no material to start work.

Expected behavior:  Work Orders should not be ready when material is not available to complete the work.

Video/Screenshot link (optional):

Here you can see we have no material available and the raw material is -1 because we will use one sheet that we do not have.
![image](https://user-images.githubusercontent.com/74666820/99544346-31a02c00-2982-11eb-8958-d155182b684f.png)

Here you can see a PO was created for the raw material.
![image](https://user-images.githubusercontent.com/74666820/99544621-8479e380-2982-11eb-8f5d-d82d12b93e72.png)

Here you can see the Manufacturing Orders are all waiting on material:
![image](https://user-images.githubusercontent.com/74666820/99544738-a70bfc80-2982-11eb-9f6d-8aa169782a55.png)

From the work center overview you see that each work center has work orders ready, these should not be available yet due to no material for any of the MO.

![image](https://user-images.githubusercontent.com/74666820/99544926-d7539b00-2982-11eb-8438-e74c60695b21.png)

From the Work Order Screen you can see they are listed as ready, they are not ready as the material isnt available yet.

![image](https://user-images.githubusercontent.com/74666820/99545034-f81bf080-2982-11eb-847f-7987266abaec.png)

Another view:
![image](https://user-images.githubusercontent.com/74666820/99545145-14b82880-2983-11eb-8df6-75ef529f7c44.png)

When clicking the ready button it starts the work order even though there is no material to do so.

![image](https://user-images.githubusercontent.com/74666820/99545286-37e2d800-2983-11eb-8357-f8440d3b76f3.png)

All BOM have the option "When all components are available" under Manufacturing Readiness selected.

![image](https://user-images.githubusercontent.com/74666820/99545591-8abc8f80-2983-11eb-9d2c-4d3abed17b9e.png)

**Comment by pedrobaeza** [comment]
It seems you are using enterprise. Why don't you put this issue in odoo.com/help as an enterprise support ticket for getting the needed attention, as this issue tracker is only voluntary?

**Comment by spinks-bill** [comment]
I thought I did as I arrived here from the odoo site.  I will see if I can find the right forum. Thanks
