### ISSUE TITLE
ir.mail_server doesn't work with username containing non-ascii characters.

### ISSUE THREAD

**Issue by Linekio** [odoo/odoo#61972]
Impacted versions:
All

Steps to reproduce:
Create a new config in "outgoing mail servers", with a non-ascii character in the username. (The SMTP server field should be valid).
Then click on "Test connection"

Current behavior:
Odoo server error (see screenshot)

Expected behavior:
SMTP usernames are generally email addresses. The domain part should be translated to ascii with IDNA/punycode encoding.(The test connection works if I translate manually). The other part maybe should be converted to SMTPUTF8, I'm not sure.
@Julien00859 had fixed that but only for email headers: https://github.com/odoo/odoo/pull/47709 

Video/Screenshot link (optional):
![Capture d’écran du 2020-11-18 21-49-21](https://user-images.githubusercontent.com/25034353/99586402-fafcfc80-29e7-11eb-9d55-5769affc66e3.png)

**Comment by Julien00859** [comment]
See also #47709
