### ISSUE TITLE
Who has a solution for odoo cluster deployment? Can you introduce it

### ISSUE THREAD

**Issue by 516300502** [odoo/odoo#61974]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
The Github tracker is only for bugs in the official code, this is not the place to ask questions about deploment or custom code.
Please ask it on the official help forums a thttps://www.odoo.com/forum/help-1
