### ISSUE TITLE
[8.0] IE9 compatibility - Kanban view

### ISSUE THREAD

**Issue by jdegoy** [odoo/odoo#6198]
Thanks to the recent fixes we now have an almost complete compatibility on IE9.
Some issues remain. The screenshot herein shows that the drag&drop functionality on the kanban view is not fully operational in IE9. It is only possible to drag & drop in the case where there are already elements in the stage you are dragging to.
![screenshot at apr 08 11-14-23](https://cloud.githubusercontent.com/assets/11032154/7042311/3f4eed20-dde1-11e4-90c9-c0dae9da52bf.png)

**Comment by Yenthe666** [comment]
https://github.com/odoo/odoo/commit/8a285e6a6269c9f2834081caede64cdbb9934dd4 should have fixed this back then.
