### ISSUE TITLE
[8.0] IE9 compatibility - Lists within form view

### ISSUE THREAD

**Issue by jdegoy** [odoo/odoo#6200]
Some of the lists on form views are displaced in IE9. See screenshot herein for example.
![screenshot at apr 08 11-30-23](https://cloud.githubusercontent.com/assets/11032154/7042631/8cc4aa52-dde3-11e4-9454-9236e329bb1f.png)

**Comment by Yenthe666** [comment]
Should have been handled at https://github.com/odoo/odoo/commit/8a285e6a6269c9f2834081caede64cdbb9934dd4 back in the day
