### ISSUE TITLE
[14.0] column website.cookies_bar does not exist

### ISSUE THREAD

**Issue by crackerjam** [odoo/odoo#62043]
Impacted versions: 14.0 (pulled minutes ago)

Steps to reproduce: Update from current 13.0 branch to 14.0 branch, load base site

Current behavior: Browser shows "internal server error", logs show log messages below

Expected behavior: Site should load properly

Video/Screenshot link (optional): https://pastebin.com/Qs8Tq5f3

**Comment by pedrobaeza** [comment]
There's no possibility of updating an Odoo version through that method. You need to make a migration, which is a process that transforms data to adapt it to the new version. Odoo offers such migration in their enterprise paid contract, and there are other alternatives out there, both paid and free, but the most popular free community one is not yet ready for v14.
