### ISSUE TITLE
After cloning repo,Unable to create user or switch th db

### ISSUE THREAD

**Issue by sudarsan15** [odoo/odoo#62054]
After i cloned the repository and i have successfully run the project. It leads me to login . I don't see any option to create new user for account and secondly i tired creating new database but then i am unable to use them as well. Thanks in advance!

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
