### ISSUE TITLE
[14.0] TimeOff errors when Language is set to Arabic "ValueError: time data '٢٠٢٠-١٠-٣٠' does not match format '%Y-%m-%d'"

### ISSUE THREAD

**Issue by Mhnd3** [odoo/odoo#62053]
**Impacted versions:** 
> 14.0 Community Edition, commit: 938d621

**Steps to reproduce:** 
> Change to Arabic Language, then access "TimeOff" App.

**Current behavior:**
> 2020-11-19 20:53:11,439 31311 ERROR test14 odoo.http: Exception during JSON request handling. 
> Traceback (most recent call last):
>   File "/home/odoo14/odoo14-server/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
>     result = request.dispatch()
>   File "/home/odoo14/odoo14-server/odoo/odoo/http.py", line 682, in dispatch
>     result = self._call_function(**self.params)
>   File "/home/odoo14/odoo14-server/odoo/odoo/http.py", line 358, in _call_function
>     return checked_call(self.db, *args, **kwargs)
>   File "/home/odoo14/odoo14-server/odoo/odoo/service/model.py", line 94, in wrapper
>     return f(dbname, *args, **kwargs)
>   File "/home/odoo14/odoo14-server/odoo/odoo/http.py", line 346, in checked_call
>     result = self.endpoint(*a, **kw)
>   File "/home/odoo14/odoo14-server/odoo/odoo/http.py", line 911, in __call__
>     return self.method(*args, **kw)
>   File "/home/odoo14/odoo14-server/odoo/odoo/http.py", line 530, in response_wrap
>     response = f(*args, **kw)
>   File "/home/odoo14/odoo14-server/odoo/addons/web/controllers/main.py", line 1359, in call_kw
>     return self._call_kw(model, method, args, kwargs)
>   File "/home/odoo14/odoo14-server/odoo/addons/web/controllers/main.py", line 1351, in _call_kw
>     return call_kw(request.env[model], method, args, kwargs)
>   File "/home/odoo14/odoo14-server/odoo/odoo/api.py", line 392, in call_kw
>     result = _call_kw_model(method, model, args, kwargs)
>   File "/home/odoo14/odoo14-server/odoo/odoo/api.py", line 365, in _call_kw_model
>     result = method(recs, *args, **kwargs)
>   File "/home/odoo14/odoo14-server/odoo/addons/hr_holidays/models/hr_leave.py", line 1252, in get_unusual_days
>     dfrom = datetime.combine(fields.Date.from_string(date_from), time.min).replace(tzinfo=UTC)
>   File "/home/odoo14/odoo14-server/odoo/odoo/fields.py", line 1752, in to_date
>     return datetime.strptime(value, DATE_FORMAT).date()
>   File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
>     tt, fraction = _strptime(data_string, format)
>   File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
>     (data_string, format))
> Exception
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/home/odoo14/odoo14-server/odoo/odoo/http.py", line 638, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/home/odoo14/odoo14-server/odoo/odoo/http.py", line 314, in _handle_exception
>     raise exception.with_traceback(None) from new_cause
> ValueError: time data '٢٠٢٠-١٠-٣٠' does not match format '%Y-%m-%d'

**Expected behavior:** 
> The Date to be passed Formatted properly, therefore the app would run without any error.

**Screenshots**
<img width="1440" alt="Screenshot 2020-11-20 at 03 10 55" src="https://user-images.githubusercontent.com/29144704/99749415-cc158200-2ade-11eb-82f0-1d2d355966b9.png">

**Comment by mhabboush97** [comment]
This happens because strptime doesn't support Arabic numerals, the string can be parsed using dateutil.parser (which supports different locales)
If you need to get this fixed yourself, you have to override get_unusual_days in hr_leave.py
```
from dateutil.parser import parse

@api.model
def get_unusual_days(self, date_from, date_to=None):
  date_from = parse(date_from).strftime('%Y-%m-%d')
  if date_to:
     date_to = parse(date_from).strftime('%Y-%m-%d')
  return super(yourclassname, self).get_unusual_days(date_from, date_to)
```

I think fields.Date.from_string function should use dateutil.parser.parse instead of datetime.strptime to eliminate any other possible errors

**Comment by mos1em** [comment]
same error .. tried on run bot and same..

**Comment by yelizariev** [comment]
fixed in https://github.com/odoo/odoo/pull/63833
