### ISSUE TITLE
Unexpected convert_to_cache parameter

### ISSUE THREAD

**Issue by unique4** [odoo/odoo#62069]
There should be a loop over "records" when passing record to convert_to_cache function
https://github.com/odoo/odoo/blob/84bc58fc06fb460b63907102ac29d0c295636584/odoo/fields.py#L2663

**Comment by pedrobaeza** [comment]
Please indicate the steps to reproduce the possible problem. This one is a very low level method and reading code is not usually the best way to determine how it works.

**Comment by unique4** [comment]
Sorry for providing lack of information. 
Affected version: 13.0, 14.0
Steps to reproduce:
1. Mass editing and records with a delegate Many2one field in the values (from mass_editing or from code). Eg. Model 'hr.recruitment.source' with delegated field 'source_id'
2. Error raised:  ValueError("Expected singleton: %s" % record) because of get id on recordset with len>1 at this line
https://github.com/odoo/odoo/blob/84bc58fc06fb460b63907102ac29d0c295636584/odoo/fields.py#L2600

So there should be an loop over records at the 'write' method at here, since it's receiving multi records as params
https://github.com/odoo/odoo/blob/84bc58fc06fb460b63907102ac29d0c295636584/odoo/fields.py#L2663

**Comment by pedrobaeza** [comment]
I suspect the problem is in mass_editing, not in core.

**Comment by unique4** [comment]
mass_editing is just an example when I was trying to describe the issue. 
Actual code raising Error will be like: `self.env['hr.recruitment.source'].browse(ids).write({'source_id' : (int)})`
With len(ids) > 1. This source_id is a delegated Many2one field.

**Comment by pedrobaeza** [comment]
OK, thanks for specifying the minimal steps to reproduce the problem. With that, there's base for working on. Last question: are you working with latest source code?

**Comment by unique4** [comment]
I was tracing lines from Odoo Github source branch. As i noted, affected branch is 13.0 and 14.0. So yes, it is the latest source code from Odoo Github

**Comment by Yenthe666** [comment]
@Elkasitu probably for your interest.
