### ISSUE TITLE
Odoo report , missing header and footer in some page 

### ISSUE THREAD

**Issue by sandeepksrana** [odoo/odoo#6207]
Hi 
Odoo qweb  report , missing header and footer in some page, while in first page and later on 7 pages it is there.

Have anyone faced this problem ...
Please let me know..    as i search everything ..

Thanks
Sandeep

**Comment by Cedric-Pigeon** [comment]
@sandeepksrana  Which version of wkhtmltopdf do you use ?

**Comment by sandeepksrana** [comment]
it is latest one problem in some pages ... as i mentioned everything above

**Comment by hbto** [comment]
Hello @Cedric-Pigeon & @sandeepksrana 

This is actually happening in runbot for odoo

In the link below there is an example on which of some reports this is happening.

https://docs.google.com/a/vauxoo.com/file/d/0B1w9gokcJL9hY2hkbTNjemhrQ1U/edit?usp=drivesdk

**Comment by hbto** [comment]
This issue is a duplicated of #5548

**Comment by beledouxdenis** [comment]
Closed with 3c61ee5c68e3796bb29d2521123f2a867c9cc157.

**Comment by tejastank** [comment]
We same face issue, also footer is not stable at bottom, crap feature.

**Comment by tejastank** [comment]
Same issue yet found with latest odoo 10 version, was exist in 9.0.
