### ISSUE TITLE
fax in ir_qweb_widget_templates.xml but not in ir_qweb_fields.py?

### ISSUE THREAD

**Issue by baimont** [odoo/odoo#62105]
Hey Odoo guys!
Why are you keeping 'fax' here:
https://github.com/odoo/odoo/blob/042298f8c949fba470eda6ad90f94c95ca291030/odoo/addons/base/views/ir_qweb_widget_templates.xml#L37

like we could use it in contact widget

but not here:
https://github.com/odoo/odoo/blob/042298f8c949fba470eda6ad90f94c95ca291030/odoo/addons/base/models/ir_qweb_fields.py#L647

making it impossible to use it in contact widget.

Am I missing something?

**Comment by pedrobaeza** [comment]
Fax field was removed, but that's a leftover. Anyway, it can't be used.

@tde-banana-odoo maybe that should be removed for not confusing?

**Comment by pedrobaeza** [comment]
Note that there's an OCA module called `partner_fax` that re-adds such field, and maybe it can be benefited by this code.

**Comment by tde-banana-odoo** [comment]
Indeed there is no fax field anymore. We could remove it in template, especially that in OCA module adding partner_fax it is easy to make an xpath to add if again into contact widget.

**Comment by tde-banana-odoo** [comment]
Cleaned at https://github.com/odoo/odoo/commit/34ca7817ecf659fb69a0e8b7c1a649a320c6aaf8

Thanks !
