### ISSUE TITLE
solved-How to add field in 2 tables same time?

### ISSUE THREAD

**Issue by ronozoro** [odoo/odoo#6211]
I have model table called student,the student should be registered in 1 group and 1 standard.

I want that when choosing  standard and group on creating student 
the student should automatically added to standard table model and group table model 

here is my fields in student model table 

    'standard_id': fields.many2one('fci.standard', string='Standard', required=True),
    'group_id': fields.many2one('fci.standard.groups',string='Groups(s)'),

and here is my field that should be updated in standard model table 

    'student_ids': fields.many2many('fci.student', 'student_standard_rel', 'fci_student_standard_id', 'standard_id',
                                            string='Student(s)'),
    'groups_ids': fields.many2many('fci.standard.groups', 'standard_group_rel', 'fci_standard_group_id', 'standard_group_id',
                                            string='Groups(s)'),

and here is my fields in group table model:

    'student_ids': fields.many2many('fci.student', 'students_groups_rel', 'group_student_rel', 'student_group_id',string='Student(s)'),

I have idea maybe a solution to (to create related field but i can't do it with many2many fields )

**Comment by mart-e** [comment]
Hello,

Sorry but the github issues are for bug reports, not to ask questions. Please check on the support or forum.
https://www.odoo.com/page/community
