### ISSUE TITLE
Error when print Purchase Order

### ISSUE THREAD

**Issue by jcerquin** [odoo/odoo#62128]
Impacted versions:
14.0
Steps to reproduce:
- Change language to SPANISH (PE)
- When print Purchase Order from Purchase Module 

Current behavior:

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo14/addons/web/controllers/main.py", line 2103, in report_download
    report_name = safe_eval(report.print_report_name, {'object': obj, 'time': time})
  File "/opt/odoo/odoo14/odoo/tools/safe_eval.py", line 322, in safe_eval
    c = test_expr(expr, _SAFE_OPCODES, mode=mode)
  File "/opt/odoo/odoo14/odoo/tools/safe_eval.py", line 178, in test_expr
    code_obj = compile(expr, "", mode)
  File "<string>", line 1
    (object.state in ('draft', 'sent') and ‘Solicitud de Presupuesto - %s' % (object.name) or
                                                    ^
SyntaxError: invalid character in identifier

Expected behavior:
- download PDF (Purchase Order)

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/36120752/99866537-008d4a80-2b80-11eb-835a-9b9532aa0cb1.png)

![image](https://user-images.githubusercontent.com/36120752/99866530-f5d2b580-2b7f-11eb-851a-43bc7a559c4d.png)

**Comment by pedrobaeza** [comment]
It seems the translation is not correct. I have change it in:

https://www.transifex.com/odoo/odoo-14/translate/#es/purchase/298942836

and on next synchronization (tonight), it will be available. You need to overwrite your translations in your local DB.

**Comment by jcerquin** [comment]
I updated all today, but the error still appears

**Comment by pedrobaeza** [comment]
Terms are updated in Transifex, so maybe you haven't overwritten on your DB. Try with a fresh DB or please locate the wrong string.

**Comment by jmmmmr** [comment]
There is a failure in the translation, instead of including an apostrophe ', a quote  ` has been included, this is the reason why the error appears. By correcting the sign, the error is fixed.

![image](https://user-images.githubusercontent.com/48723466/147034877-d98b1c23-89bc-42a7-9700-3892beee08ca.png)
