### ISSUE TITLE
Attachment not showing in ir.attachment view (Settings > Database Structure > Attachments) when using many2many_binary widget

### ISSUE THREAD

**Issue by aaronsaquing** [odoo/odoo#62136]
Impacted versions: 14

Steps to reproduce:
1. Set to Developer Mode
2. Go to Settings > Emails > Templates
3. Edit a Template > Upload file in Content Tab (targeting attachment_ids field which use many2many_binary widget)
4. Go to Settings > Database Structure > Attachments
5. You will not see the file in the list. File also not callable in json-rpc, xlmrpc odoo apis

Current behavior:
Not showing the uploaded file in ir.attachment list view

Expected behavior:
Should show the uploaded file in ir.attachment list view

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/42097911/99927653-3148cc00-2d9a-11eb-819b-bfd863acff1b.png)
![image](https://user-images.githubusercontent.com/42097911/99927697-67864b80-2d9a-11eb-87e3-c8ebef595a99.png)

**Comment by pedrobaeza** [comment]
That's something expected, as such widget doesn't store the files as attachments, but binary fields inside DB.

Closing thus.
