### ISSUE TITLE
Odoo Marketing Automation - Original subject line always persists in mass email 

### ISSUE THREAD

**Issue by sandra22s** [odoo/odoo#62132]
Odoo Marketing Automation - sending campaigns

Steps to reproduce:
1. Create a mass email message with a given set of recipient criteria.
2. Copy this message to retain the same criteria. Change subject line and contents.
3. Send test message and see that everything looks right.
4. Send to all recipients.

5. Considering the case
[11.0] Original subject line always persisted in mass email #23280
this should be solved with the translation settings when editing the mass mail. However this doesn't work and the campaign is still sent with wrong subject.

Current behavior:
Email is sent with updated contents, but the subject line of the original message (which is no longer visible anywhere else in the Odoo interface).

Expected behavior:
Email is sent with updated contents and updated subject line.

**Comment by pedrobaeza** [comment]
Which Odoo version? The answer remains the same as explained in the other issue.

**Comment by sandra22s** [comment]
I resolved it. I thought this setting is directly in the email settings an not in the general settings
