### ISSUE TITLE
[13.0][OE] account_followup : impossible to define followup adresse

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#62141]
Impacted versions: 13.0 and other

Steps to reproduce:
- create a customer, create invoice contact and set this email `invoice@supplier_1.com`
- this customer using this alias `invoice@supplier_1.com` to catch her purchase invoice.
- create an invoice for this customer and send to `invoice@supplier_1.com`
- this customer make time to pay
- this Followup-report, 
--> Issue the report will be send to `invoice@supplier_1.com`, and you can not send to an other contact (the big boss for exemple)

Expected behavior:
make the a distinction between invoice-partner  (the real accounting guy) and catch-invoice (the email adresse to send invoice).

@alexis-via

**Comment by fmdl** [comment]
@oco-odoo

**Comment by Yenthe666** [comment]
That's kinda a wishlist & not supported right now by default, right?

**Comment by oco-odoo** [comment]
Sounds indeed like a new feature. @tsb-odoo , possible new task? :)
