### ISSUE TITLE
Point of Sale : bad opening balance if 2 pos.config and cash_control enabled

### ISSUE THREAD

**Issue by legalsylvain** [odoo/odoo#62147]
### Impacted versions:
- V12. certainly V13.

### Steps to reproduce:

**settings**
- Enable cash_control on your demo pos config
- Add a cash journal
- duplicate your pos config to have a "Shop (2)"
- as admin user : open your shop 1, make a sale
here is the state of the session 1
![image](https://user-images.githubusercontent.com/3407482/99943681-f59a0c00-2d71-11eb-87aa-00d296633359.png)

- as demo user : open your shop 2
![image](https://user-images.githubusercontent.com/3407482/99943714-05b1eb80-2d72-11eb-9397-3a64f83f120b.png)

### Current behavior:
The interface proposes a wrong opening balance for the session **2**, based on the last statement of the session **1**.

### Expected behavior:

The opening balance of the session **2** should be the ending balance of the last statement of the session **2**.

Here is the code that generates the bug. I guess the function should be overloaded in ``point_of_sale`` module.

https://github.com/odoo/odoo/blob/12.0/addons/account/models/account_bank_statement.py#L112

CC Community : @Yenthe666, @OCA/pos-maintainers, @alexis-via, @quentinDupont.

CC Odoo team : @lap-odoo

**Comment by pimodoo** [comment]
Hello, this error comes from a bad configuration of your Odoo instance. You are using the same cash journal for multiple POS config, in the accounting of most country, you must have a different cash journal for each physical cash box (like each bank account should have its own journal), so the cash journal represent the flow of cash in a cashbox.

**Comment by legalsylvain** [comment]
Hi @pimodoo.
First thanks for your quick answer.

I'm quite surprised by what you said. I never heard such accounting constraint in France. Is it mandatory in Belgium ?
I can not figure out that some big hypermarkets like Carrefour have 400 ``account.journal`` to handle the 100 ``pos.config`` for at least 4 types of payment. (Cash / Check / Credit Card / Meal Voucher).
I did'nt found any documentation on internet. could you mention some links ? 
Thanks !
  
CC : @fclementic2c do you follow the same logic in Switzerland ?

**Comment by Yenthe666** [comment]
Euhh, do you? I was not aware of this either honestly.

**Comment by pimodoo** [comment]
I don't follow you on the credit card and meal voucher, do you have a different bank account for each of your POS config?

**Comment by usmanfarzandali** [comment]
@pimodoo said 100% Right i also solve this issue as he said , its configuration issue ...

**Comment by legalsylvain** [comment]
> I don't follow you on the credit card and meal voucher, do you have a different bank account for each of your POS config?

No I currently have a journal for each payment method, used for all the ``pos.config`` of a same company. So 4 journals for X ``pos.config`` with the following french accounts : 

- Credit Card : 5115 - Carte bleue en attente d'encaissement
- Check : 5112 - Chèques à encaisser
- Meal Voucher : 5111 - Coupons échus à l'encaissement
- Cash : 5311 - Caisse en monnaie nationale

>  So what does the balance of your cash journal represent?

Not sure to understand that point. I would say that my cash journal balance represents the money currently in my cash drawers that has not yet been deposited in the bank.

> @pimodoo said 100% Right i also solve this issue as he said , its configuration issue ...

Not only. I understand the technical solution proposed. One journal per pos config, But I'm not sure that it is an accounting constrains.
I mean, current UI allow such configuration (same cash journal for different pos.config). 
- There is no constraints, no checks, and no help or text that mentions that we have to select a different cash journal for each pos.config. 
- Moreover, if you install point_of_sale, and pos_restaurant with demo data, you have 2 ``pos.config`` with the same cash journal. So the demo data itself is misleading.
