### ISSUE TITLE
[14.0] 'Create' and 'Create and Edit' option doesn't show unless user starts typing anything in many2one field.

### ISSUE THREAD

**Issue by sergemercado** [odoo/odoo#62140]
https://github.com/odoo/odoo/blob/658d0fa32f35f4c4f9a1828b11fa383d3dad3b46/addons/web/static/src/js/fields/relational_fields.js#L650

Impacted versions: 14.0

Steps to reproduce: 
1. Add a many2one field in a form view or wizard.
2. Click the field.

Current behavior: The dropdown list doesn't automatically show 'Create' and 'Create and Edit' options. I have to type anything to use those options.

Expected behavior: 'Create' and 'Create and Edit' options in drop-down list of many2one should always be there without the 'Start typing...' or at least give us an option to disable the 'Start Typing...' behavior since uploading a file in the 'ir.attachment' model overrides the name we type by the name of the file being uploaded thus adding more steps just to add a record and making the typing pretty useless in this case.

Video/Screenshot link (optional):
First Image (Before Typing)
![image](https://user-images.githubusercontent.com/71862217/99935095-d82d6800-2d9a-11eb-8ad2-4fe4b6b88da7.png)

Second Image (After Typing)
![image](https://user-images.githubusercontent.com/71862217/99935757-681fe180-2d9c-11eb-98f8-67ffdbc4408e.png)

Third Image (Name filled)
![image](https://user-images.githubusercontent.com/71862217/99935786-7968ee00-2d9c-11eb-8456-f0ddb7528739.png)

Fourth Image (Name replaced by file attached)
![image](https://user-images.githubusercontent.com/71862217/99935819-8be32780-2d9c-11eb-980c-73b57588daac.png)

**Comment by msh-odoo** [comment]
@sergemercado It is not a bug, many2one Create and Create & Edit has been changed in v14, instead of Create and Create & Edit option you will have "Start typing..." option which is not selectable but it tells you to type something, as soon as you type something it will try to search for matching records and it will also give you Create and Create & Edit options(if create on modal is enabled).

Thanks.

**Comment by Yenthe666** [comment]
Yep it has been reported before too (@sswapnesh or @pedrobaeza do you remember the ticket?).
I'd like to add to this that this feature is the most annoying one I've seen introduced in years. It is inefficient and a true pain. I don't get how this was ever added.

**Comment by sergemercado** [comment]
> Yep it has been reported before too (@sswapnesh or @pedrobaeza do you remember the ticket?).
> I'd like to add to this that this feature is the most annoying one I've seen introduced in years. It is inefficient and a true pain. I don't get how this was ever added.

May you please reference also the link of the existing ticket if ever found? I was searching with related issues but none popped up. It would be really great to be updated with this. Thank you!

**Comment by sswapnesh** [comment]
https://github.com/odoo/odoo/issues/59695
