### ISSUE TITLE
[8.0] [7.0] Voucher misscalculates writeoff amount when used via the Register Payment button.

### ISSUE THREAD

**Issue by mvaled** [odoo/odoo#6216]
Steps to reproduce (in both versions):
1. Create a new DB with demo data, set up Accounting.
2. Go to Accounting, Customer invoices.
3. Click over the first open invoice.  If there are no open invoice (version 7) create one and validate it.
4. Click the "Register payment" button.
5. On the wizard enter the Bank account as payment method and then change the amount paid to less than the amount proposed.

Current result:

The difference amount remains 0.

Expected result:

The difference amount should be anything but 0, and you should have the choice to write-off the outstanding amount.

The following images shows the problem in both versions using newly created DBs with demo data:

![v7](https://cloud.githubusercontent.com/assets/270825/7061382/3dc06df2-de5f-11e4-82e3-48256bceabbb.png)

![v8](https://cloud.githubusercontent.com/assets/270825/7061439/f95934f4-de5f-11e4-8863-946a8a1a93ca.png)

**Comment by cysnake4713** [comment]
Yes, Confirmed This one!

**Comment by NL66278** [comment]
And another confirmation. Very strange this is not picked up By Odoo. Is nobody using register payment button? Or are customers always paying the right amount? I can not imagine....

**Comment by spadae22** [comment]
@NL66278 This has been the same bug forever, @Yenthe666, maybe you could pull some strings?  A shitt work around is that if you make the payment again, then you see the balance. Our users just use the payment screen instead since this is something going on for years

**Comment by NL66278** [comment]
One of our customers absolutely needs this fixed, so I am going to write a fix and create a PR. No guarantees when it will be ready, but working on it right now.

**Comment by wtaferner** [comment]
@NL66278 @spadae22 @cysnake4713 
Not sure if your issue is about this, but I guess it was fixed today in https://github.com/odoo/odoo/commit/d40631463822a4d39662bd02de9a6a62f4af687a

**Comment by spadae22** [comment]
@wtaferner Nice, testing now

**Comment by NL66278** [comment]
Tested Odoo with d406314. Problem remains. So unfortunately it is not fixed.

**Comment by mart-e** [comment]
Hello,

Sorry but I will reject this. The "Difference Amount" field represent actually the exceeding amount, the label is a bit unclear, I admit. In this case, you have not fully paid the invoice yet, so there is no difference to report to an account.
The 8.0 is now in end of life cycle and will soon be unsupported. We are only patching critical or security issues. The risk of regressions or introducing side effects is too high.
Having a negative amount in the field will change its meaning, maybe some code was only considering if it is different than zero, not positive.
We have changed the way this works in 9.0 so you should no longer have this issue in upper version.

Regards
