### ISSUE TITLE
[14.0] Zoom/Automatic Zoom not working on website products

### ISSUE THREAD

**Issue by avmediadesign** [odoo/odoo#62171]
Impacted versions: 14.0 CE
Steps to reproduce: Active Zoom function for product on website
Current behavior: Zoom is not working (reproducible on Runbot)
Expected behavior: Zoom should work

**Comment by sswapnesh** [comment]
Seems working well.

**Comment by avmediadesign** [comment]
After double checking, it works indeed. I have been misled by the image size. In former versions, the zoom was working for 1000 px images when now the image size has to be over 1000 px for the zoom to activate.
