### ISSUE TITLE
odoo12 when dialing from contact, redirected to discuss, clicking back does not work.

### ISSUE THREAD

**Issue by f1-outsourcing** [odoo/odoo#62186]
odoo12 when dialing from contact, redirected to discuss, clicking back does not work.

That is of course very annoying when the call is not answered, and you have to manually go back to the contacts and search for the contact.

**Comment by pedrobaeza** [comment]
This is not something of Odoo community, so I close it. If you are using enterprise module, please report it through odoo.com/help.
