### ISSUE TITLE
Enabling search for computed boolean field?

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#6219]
It seems search on computed Boolean field does not work or I'm doing something wrong.
Here is my code"

```python
    is_manager = fields.Boolean('Is Manager', compute="_find_manager", search="_search_is_manager",)

    def _find_manager(self):
        for rec in self:
            manager_groups = self.env['hr.department.group'].search([('manager_id', '=', rec.id), ('date_management', '<=', date.today())])
            if manager_groups:
                rec.is_manager = True
```
This part works normally, I see is_manager field set to true if it meets conditions provided in `_find_manager` function. But search method seems to not be working, if I search in search bar using `'Is Manager' is true`, it never find any results even though I see that some employees have `is_manager` set to true.

My search method:

```python
    def _search_is_manager(self, operator, value):
        return [('name', operator, value)]
```

**Comment by xmo-odoo** [comment]
That search method doesn't really make sense. You're going to get something along the lines of `operator='=', value=True`, resulting in an effective search on `[('name', '=', True)]` which really doesn't look like your original search criteria.

**Comment by oerp-odoo** [comment]
@xmo-odoo  well all I wanted to do, was to implement same search as it would be used for boolean field that is stored in a database. So what kind of search method would make sense?

**Comment by xmo-odoo** [comment]
A search which matches your criteria for computing the `is_manager` field?

**Comment by oerp-odoo** [comment]
@xmo-odoo yeah. I mean it does not matter by what conditions employee got `is_manager` set to True (when searching). What matters when searching is to simply find those employees (records) that have `is_manager` set to true (or false if opposite search would be used), just like in any ordinary search.

In other words using advanced search menu.

**Comment by xmo-odoo** [comment]
>  What matters when searching is to simply find those employees (records) that have is_manager set to true (or false if opposite search would be used), just like in any ordinary search.

Right but that's not what you're doing here. Odoo's search is done entirely via an in-database select, so the domain ultimately provided to the mode's search method can only contain stored fields (computed or not). By default, computed fields are not stored so they can't be used in domains (which is why they can't be searched).

The purpose of the search parameter on computed fields is to tell Odoo how to *transform* a domain on a non-stored computed field into a domain on stored fields, that resulting domain being what's actually used for the search.

Here you're telling Odoo that when you're searching for `is_manager = True` it should really search for `name = True` which makes basically no sense, and is why you never get any result.

**Comment by oerp-odoo** [comment]
@xmo-odoo yeah thats what I thought at first, so I thought I should change `name` to `is_manager` and make a domain like this `[('is_manager', operator, value)]`, but then if I try to search, Odoo goes in some kind of infinite loop and I have to stop the server.

And I looked this as reference to how implement search method (https://www.odoo.com/documentation/8.0/reference/orm.html#computed-fields):

```python
upper_name = field.Char(compute='_compute_upper', search='_search_upper')

def _search_upper(self, operator, value):
    if operator == 'like':
        operator = 'ilike'
    return [('name', operator, value)]
```
And as you can see it also uses in field part `name`, when its name is actually `upper_name`. Thats why I got confused here.

So do you know how that domain should look like?..

**Comment by xmo-odoo** [comment]
> yeah thats what I thought at first, so I thought I should change name to is_manager and make a domain like this [('is_manager', operator, value)]

That generates the same domain you get as input to the method. As I said, this function should return a domain working on *stored* fields. `is_manager` is not a stored field, and you're transforming `('is_manager', operator, value)` into `('is_manager', operator, value)`, there's no reason for this to work.

> And as you can see it also uses in field part name, when its name is actually upper_name. Thats why I got confused here.

It uses `name` in the field part because `upper_name` is a transformation on `name`, so a search on the computed field `upper_name` is a slightly different search on the `name` field.

> So do you know how that domain should look like?..

I don't understand what your `is_manager` field is supposed to do, but I'd expect `[('date_management', '<=', date.today())]` or something along those lines, considering the way you're computing the field. Alternately, just make it a stored field.

**Comment by oerp-odoo** [comment]
@xmo-odoo as I understood, search simply does not work on computed field if you need to search for it directly. That documentation got me confused. So I guess storing is the only way, but conditions for that field are on entirely another model where I can't use dependencies, so it might reduce performance.

**Comment by xmo-odoo** [comment]
> So I guess storing is the only way

No, *correctly* implementing search on the field will also work.

**Comment by oerp-odoo** [comment]
@xmo-odoo so why can't you tell me how to do it then? 

But as you said yourself `is_manager` can't be put in search domain, because it does not exist (as it is not stored), so for what field should I search then if the one I need simply `does not exist`?

**Comment by xmo-odoo** [comment]
> so why can't you tell me how to do it then?

I did… 

> But as you said yourself is_manager can't be put in search domain, because it does not exist (as it is not stored), so for what field should I search then if the one I need simply does not exist?

The one based on which you're computing the field in the first place. From your compute method, it looks like the `is_manager` flag is just an alias to `('date_management', '<=', date.today())`, so that's your domain.

**Comment by oerp-odoo** [comment]
@xmo-odoo but `date_management` is in different model. I'm searching in `hr.employee` and `date_management` (as `manager_id`) is in model `hr.department.group`. As you can see I'm using search `env` on that "remote" model. And that model is not directly related with `hr.employee`.

So If I use `date_management` in that domain, it will do the same as it did with `is_manager`, it just won't find it.

**Comment by ymazal** [comment]
Wow ! That documentation is very confusing.... And if you put the attribute store to true, to get into another complicated problem: when should the field be computed ?

In that case, you have to provide the field that its based on, but some times, there is not simple field... Imagine a case where the first element of many to many is taken and checked...

**Comment by dirtyhandsphp** [comment]
@xmo-odoo : You closed this issue without any proper answer. Please provide solution for this if you can otherwise reopen it.

**Comment by tushardonga** [comment]
i have age field in my file which is computed field, now i want to show this field at the time of search what can i do i dont know anything about search computed field,what i have to write in python give me tips plzz

**Comment by Yenthe666** [comment]
@tushardonga please don't hijack random bug report topics. You can ask these kind of questions on the official help forum at help.odoo.com.

**Comment by tushardonga** [comment]
then what use of github website
