### ISSUE TITLE
odoo12: un checked "phone formatting" yet still my +XX is being removed

### ISSUE THREAD

**Issue by f1-outsourcing** [odoo/odoo#62209]
phone formatting still active after turning it off with crm ->contacts -> un checked "phone formatting"

**Comment by pedrobaeza** [comment]
Do you still have `phone_validation` module installed?

**Comment by f1-outsourcing** [comment]
I do not know. I will check it. But one assumes from being able to uncheck 'phone formatting' there is no need to do something else.

**Comment by pedrobaeza** [comment]
Yes, but what do you expect? That all formatted phones return to non-formatted? Or is it for new phone numbers?

**Comment by f1-outsourcing** [comment]
I expect nothing to be changed. Everything I enter stays as it is. Now it removes +XX if the contact is in the same country.

ps. it is not possible to uninstall the module, it is being used by eg. base_phone

**Comment by pedrobaeza** [comment]
Then this is the expected behavior: base_phone requires this module to be installed, and while installed, it formats the numbers. The check is for uninstalling the module.
