### ISSUE TITLE
Preview on Attachement field (ir.attachment)

### ISSUE THREAD

**Issue by fasilwdr** [odoo/odoo#62215]
How can I get preview on form view for below field

```
doc_attachment_id = fields.Many2many('ir.attachment', 'doc_attach_rel', 'doc_id', 'attach_id3', string="Attachment",
                                     help='You can attach the copy of your document', copy=False)
```

Impacted versions: Odoo Community-v13

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
