### ISSUE TITLE
Add chatter widget inside form

### ISSUE THREAD

**Issue by fasilwdr** [odoo/odoo#62216]
How can add below chatter **inside form**

```
<div class="oe_chatter">
    <field name="message_follower_ids" widget="mail_attachment"/>
</div>
```

Impacted versions: Odoo Community-v13

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Comment by Yenthe666** [comment]
Please ask this on the official help forums. The Github tracker is only for bugs in the official code :)
