### ISSUE TITLE
pip install have confliction on windows with python 3.7 installed

### ISSUE THREAD

**Issue by tinybench** [odoo/odoo#62214]
Impacted versions:
14.0
Steps to reproduce:
run pip install -r .\requirements.txt
Current behavior:
report error
Double requirement given: gevent==1.4.0 (from -r .\requirements.txt (line 10)) (already in gevent==1.5.0 (from -r .\requirements.txt (line 9)), name='gevent')
Expected behavior:
install dependencies
Video/Screenshot link (optional):
N/A

Root Cause:
the line 9 and line 10 in requirements.txt are conflict if the os is windows and installed python version >= 3.7

**Comment by minhhq09** [comment]
In case to install `requirements.txt` it has given error so to avoid them follow this solution:

- Open your `requirements.txt` file and remove or `# gevent 1.4. ; sys_platform=='win32'` as the below image and save.

![image](https://user-images.githubusercontent.com/28040072/100040491-fbf3bb00-2e39-11eb-8673-bc65bde50ab2.png)

**Comment by tinybench** [comment]
Thanks, I bypasse the error using the same way you provides, anyway thanks.
But do we have a fix on the requirements.txt later, otherwise, other people is still going to meet the error
