### ISSUE TITLE
odoo12: icon for sms is showing on contacts while it is not enabled/working 

### ISSUE THREAD

**Issue by f1-outsourcing** [odoo/odoo#62220]
What use is it to show something that does not work? If you have no subscription do not show it!!!!! 

![untitled](https://user-images.githubusercontent.com/13450219/100066614-97cef800-2e35-11eb-9ab6-25c1f8379852.png)

https://github.com/odoo/odoo/issues/62212
You do know how your own product looks like not?

**Comment by pedrobaeza** [comment]
That's the expected behavior IMO.

**Comment by f1-outsourcing** [comment]
I assumed. My suggestion is to change the expected behaviour. This is behaviour is comparable to sleazy in apps/game purchases where you do not want to be associated with. You will not see this in things like libre office etc.

**Comment by Yenthe666** [comment]
It is indeed expected and I'm starting to get really tired of people being so cocky here. I do this on a voluntary basis to help Odoo/the community and I get called out all the time. If it annoys you so much fix it instead of freaking complaining.

**Comment by f1-outsourcing** [comment]
@Yenthe666  I think you should get a % of the sms sales!! ;) 

Whether you do something for free or not, is not really relevant here. If your kid receives a free cookie in some store, you also expect to meet it certain standards, like that it was not dropped on the floor. 
And if you really would accept a fix for this, why is this issue closed? It should remain open until someone decides to do a pull request for it.

**Comment by Yenthe666** [comment]
Because it is not a fix. It is at best an improvement and it is your opinion that this needs a fix. If I keep this 'issue' open it will stay open for years and nobody will look at it. If you make a PR to 'fix' it you might have a fighting chance to get it in but even then the odds are very unlikely.
Source: best contributor nominee for 5+ years, most active collaborator on official Odoo stuff for 5+ years. Let's talk again when you're there.

**Comment by f1-outsourcing** [comment]
Ok that is clearing up the issue. But I do not get why you then suggested "If it annoys you so much fix it instead of freaking complaining." first.

PS
I think you can auto close issues after a 'period' here on github.

PPS.
I have looked at th openerp7 db and odoo12 db, and the work is quite rookie level I would say. If you are a frontend guy. Why do you not switch projects. I wanted to switch to opencrx, but they do not have nice opensource gui. These guys really know how to design databases. That project really deserves more exposure.

**Comment by pedrobaeza** [comment]
@f1-outsourcing I'm now seeing this issue and your attitude is really very bad and don't deserve even an answer. If you don't like what you see, go to another ERP system, but don't demand changes that in your opinion are not correct and even reject any possible answer or reasoning.

Veterans in this software like Yenthe and I knows that not everything is perfect in this world, but focus on:

- Important things.
- Don't start fightings with Odoo S.A. itself in things that are not so important and are there for commercial purposes.
- Don't have that attitude at all, as you get nothing with it.

**Comment by Yenthe666** [comment]
I've decided to lock this conversation. This will only end up in a huge discussion that keeps going on while not getting anyone where we'd like to go.
We're not here to be mean or automatically close issues. We're here to pick out the important things and to try and come up with a solution for big(ger) issues. If you think the database design is so poor and you don't like the product I'd advice you to look at other software perhaps.
