### ISSUE TITLE
Unable to upgrade to nightly - Ubuntu

### ISSUE THREAD

**Issue by Magnum26** [odoo/odoo#6223]
The following NEW packages will be installed
  odoo
0 to upgrade, 1 to newly install, 0 to remove and 0 not to upgrade.
Need to get 0 B/47.8 MB of archives.
After this operation, 300 MB of additional disk space will be used.
(Reading database ... 323783 files and directories currently installed.)
Preparing to unpack .../odoo_8.0.20150409_all.deb ...
Unpacking odoo (8.0.20150409) ...
dpkg: error processing archive /var/cache/apt/archives/odoo_8.0.20150409_all.deb (--unpack):
 trying to overwrite '/usr/bin/openerp-server', which is also in package openerp6.1-core 6.1-1+dfsg-0ubuntu3
Processing triggers for ureadahead (0.100.0-16) ...
Errors were encountered while processing:
 /var/cache/apt/archives/odoo_8.0.20150409_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by sle-odoo** [comment]
Seems that you have conflicting package installed: openerp6.1-core. Remove this one and you'll be able to install Odoo 8.

Regards
