### ISSUE TITLE
[8.0] Tax calculation Rounding Method is not taken into account in the POS 

### ISSUE THREAD

**Issue by chrisdec** [odoo/odoo#6224]
Hello, 

I noticed a bug regarding the tax calculation rounding method.

In the Point of Sale (POS), this option is not taken into account. Never mind that you choose "Round globaly" or "round per line" in accounting settings, the rounding is always per line in the POS.

Because of that, sometimes you sell products to a customer in the POS and the amount at the screen (amount to pay) is not the same as the amount on the invoice generated by the POS. 

Step to reproduce : 
------------------------
Go to settings > Configuration > Accounting 
Choose Tax calculation rounding method : "Round Globally"

You need to configure 4 different products: 

- Product 1 : price = 1.48 and sale taxe = VAT-OUT-21-L
- Product 2 : Price = 1.52 and sale taxe = VAT-OUT-21-L
- Product 3 : Price = 1.54 and sale taxe = VAT-OUT-21-L
- Product 4 : Price = 0.39 and sale taxe = VAT-OUT-21-L

Then, open a session in the point of sale. 

Choose a customer and sell him : 

- product 1 : X4
- Product 2 : X1
- Product 3 : X1
- Product 4 : X1

The customer has to pay 11,33 (base = 9.37 and vat = 1.96)

Choose a payment method and ask an invoice for the customer 

Current behaviour 
-------------------------

The total of the invoice is 11.34 (base = 9.37 and vat =1.97). The amount of the pos order is not correct. 

It's incorrect to give the customer an invoice with an amount different of the amount he just paid!

Expected behavior 
---------------------------

If I choose to use "round globally" method for vat calculation, it must be rounding globally in the POS also and not only in accounting. 

The amount in the POS must be 11.34

Thanks in advance,

**Comment by chrisdec** [comment]
OPW 632537

**Comment by beledouxdenis** [comment]
Hello Christelle, 

This issue is solved in Odoo 8.0 from the revision fc132665d77ec630b45b0aec808b32b6797a57dc

Regards,
