### ISSUE TITLE
[8.0][7.0] crm_profiling: Wrong crm_profiling_view.xml

### ISSUE THREAD

**Issue by erc-anubia** [odoo/odoo#6226]
**crm_profiling: Wrong crm_profiling_view.xml**

Impacted versions:

 - 7.0
 - 8.0

Steps to reproduce:

 1. go to Sales -> Configuration -> Contacts Segmentation
 2. create Contact Segmentation
 3. go to the tab "Profiling"

Current behavior:

![image](https://cloud.githubusercontent.com/assets/8233008/7066612/a5cb53fc-dec4-11e4-983b-d242e245972c.png)

Expected behavior:

 - Included Answers:
 - Table
 - Excluded Answers:
 - Table

**Comment by alejandrosantana** [comment]
Pull requests fails test due to my CLA sign is pending merge. See: https://github.com/odoo/odoo/pull/6231
