### ISSUE TITLE
print invoice POS > orders

### ISSUE THREAD

**Issue by AlSayedGamal** [odoo/odoo#6227]
Steps:
1- install pos
2- do some orders
3- exit session
4- click orders
5- select few orders
6- print invoice
![screenshot 2015-04-09 14 41 23](https://cloud.githubusercontent.com/assets/1265603/7066872/585f3baa-decf-11e4-9495-34b5247478a8.png)

**Comment by nim-odoo** [comment]
Fixed, now a normal warning pops up.
Thanks!
