### ISSUE TITLE
[RFC] Add `@api.rpc_disable` to make methods not available via XMLRPC

### ISSUE THREAD

**Issue by simahawk** [odoo/odoo#62299]
Impacted versions: master

Current behavior: all public methods are XMLRPC available. Sometimes this is not wanted/convenient/secure.

Expected behavior: prevent RPC calls to decorated methods.

The decorator can just set a flag on the method and the [service](https://github.com/odoo/odoo/blob/master/odoo/service/model.py#L39) can simply check for this flag.

**Comment by pedrobaeza** [comment]
Why not simply add _ at the beginning of the method name?

**Comment by simahawk** [comment]
@pedrobaeza because that's not what you do when defining an API.
Normally, you use public methods to define something that developers can rely on and you can change whatever happens underneath without affecting others' code. 

> there is a convention that is followed by most Python code: a name prefixed with an underscore (e.g. _spam) should be treated as a non-public part of the API (whether it is a function, a method or a data member). It should be considered an implementation detail and subject to change without notice.

https://docs.python.org/3/tutorial/classes.html#private-variables

**Comment by pedrobaeza** [comment]
Well, I see that this is a non-public part of the API, but maybe what you want is to overwrite a method that was public for not being anymore. Is that your intention?

**Comment by Elkasitu** [comment]
I'm on the same camp as @pedrobaeza I don't understand why you can't/won't use `_` to prevent methods from being used over xmlrpc? what you quoted describes exactly that, do you mean `_` is not explicit enough and you'd like it to be more explicit?

That being said there have been (informal) internal discussions about changing the way this works, more importantly the goal would be to have security by default so all methods would be private by default and would need to be flagged with something akin to `@api.rpc_enable`, but it's just some random discussions we had, nothing final

**Comment by simahawk** [comment]
> I'm on the same camp as @pedrobaeza I don't understand why you can't/won't use `_` to prevent methods from being used over xmlrpc? what you quoted describes exactly that, do you mean `_` is not explicit enough and you'd like it to be more explicit?

`_` is very explicit. It says "You should not use me directly to interact with this tool/class".

Probably we should start from defining what do you mean with "public". For you public seems to be "I can call it from the world outside" (aka xmlrpc). For me and for many others that look at this from a "pythonic perspective" is "these methods are the ones to deal with, the rest could be rewritten".

How many times have you used a python lib and you have imported or used a private method? Not so often I bet. And why? Because that's the convention I mentioned above.

Anyway, I understand that the convention here is "your api should use always private methods" but this makes weird to define the api and to keep separated the public layer from the private layer (in the pythonic sense).

> That being said there have been (informal) internal discussions about changing the way this works, more importantly the goal would be to have security by default so all methods would be private by default and would need to be flagged with something akin to @api.rpc_enable, but it's just some random discussions we had, nothing final

Good to know, thanks for the spoiler :) 
From my PoV having a decorator to disable will not have any impact on current code base.

**Comment by Yenthe666** [comment]
Another possible/cool option would be to fully disable XML-RPC on a model level. e.g:
```
class SomeModel(models.Model):
    _name = 'some.model'
    _allow_xml_rpc = 'False'
```
Some models I just don't want to expose at all through XML-RPC :)

**Comment by simahawk** [comment]
> Another possible/cool option would be to fully disable XML-RPC on a model level. e.g:
> 
> ```
> class SomeModel(models.Model):
>     _name = 'some.model'
>     _allow_xml_rpc = 'False'
> ```
> 
> Some models I just don't want to expose at all through XML-RPC :)

Totally agree. The decorator could work at class level as well:

```py
@api.rpc_disable
class SomeModel(models.Model):
```

**Comment by simahawk** [comment]
FTR this has been implemented here https://github.com/OCA/server-tools/pull/2293 and improved on https://github.com/OCA/server-tools/pull/2294 to allow configuration from backend UI.

**Comment by Yenthe666** [comment]
I still think this should become a core feature too :)

**Comment by simahawk** [comment]
> What if i want to disable xml-rpc completely ?

You could apply this to `base` model https://github.com/OCA/server-tools/tree/16.0/rpc_helper#via-code
