### ISSUE TITLE
Stock assign: why stock assignement not using child locations of the source location?

### ISSUE THREAD

**Issue by m3asmi** [odoo/odoo#62318]
Impacted versions:
12.0

Current behavior:
for chained moves using routes when we have an article that has been located in the child location, why it's not assigned ?
https://github.com/odoo/odoo/blob/12.0/addons/stock/models/stock_move.py#L1020

Expected behavior:
to assign an article even if it's in child locations

**Comment by pedrobaeza** [comment]
Please include full detailed steps for reproducing the issue.
