### ISSUE TITLE
Border-image in qweb-pdf Odoo 13

### ISSUE THREAD

**Issue by loubnaBENMOUSSA** [odoo/odoo#62315]
Impacted versions:
Hi everyone, i'm using Odoo 13 and  i'm trying to use border-image in order to export pdf with border, i try this code 

1-This is my xml report
```
<data>
    <template id="report_double" inherit_id="web.report_assets_common">
      <xpath expr="." position="inside">
        <link rel="stylesheet" href="/report_sale/static/src/css/report.css"/>
      </xpath>
    </template>
    <template id="test_border">
      <t t-call="web.html_container">
        <t t-foreach="docs" t-as="doc">
          <t t-call="web.basic_layout">
            <div class="my-border">
              <div class="page">
                <h1>teeeeeeeest</h1>
              </div>
            </div>
          </t>
        </t>
      </t>
    </template>
    <report string="report dashed"
            id="report__dashed"
            model="sale.order"
            report_type="qweb-html"
            name="argos_sale.test_border"
            file="argos_sale.test_border"
    />
  </data>
```
2-My css

```
.my-border {
padding: 16px;
border: 17px solid transparent;
border-image: 17 repeating-linear-gradient(-45deg, #EF4135 0, #EF4135 16px, transparent 0, transparent 32px,#0055a4 0, #0055a4 48px, transparent 0, transparent 64px);
width: auto;
height: auto;
}

```
Note : with that code i got this in html interface
![image](https://user-images.githubusercontent.com/71273599/100222940-1b164980-2f1b-11eb-82a4-eb51ca137511.png)

but when i print it:
there is no border displayed 

![image](https://user-images.githubusercontent.com/71273599/100222990-31240a00-2f1b-11eb-9525-b99a3b7dde47.png)

Please any suggestion
Thank you

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
