### ISSUE TITLE
[BUG][12.0] Base: Users with access rights: Administration / Access Rights can set everyone to Administration / Settings Group

### ISSUE THREAD

**Issue by khaihoan123** [odoo/odoo#62362]
Impacted versions: 12.0, 13.0

Current behavior:
-Users with access rights: Administration / Access Rights Group can not set themselves to Administration / Settings Group but can add themselves to Administration / Settings Group in res.groups form view or can set other users  to Administration / Settings Group, and then use that accounts to set their access rights to Administration / Settings Group.

Expected behavior:
Users with access rights: Administration / Access Rights do not set anyone to Administration / Settings Group

Video/Screenshot link (optional):
https://drive.google.com/file/d/1IitL95vkPeuUae0K2hmwAmKYCVwtQsl8/view?usp=sharing

**Comment by pedrobaeza** [comment]
This has been expressed other times, and it's the chicken/egg problem. I'm not able to locate right now the issue where this was commented in extension. @Yenthe666 do you remember such issue? Anyway, this can be considered as won't fix.

**Comment by khaihoan123** [comment]
> This has been expressed other times, and it's the chicken/egg problem. I'm not able to locate right now the issue where this was commented in extension. @Yenthe666 do you remember such issue? Anyway, this can be considered as won't fix.

thanks your answers, i'm trying to fix this. if i can, i will make a PR for Odoo

**Comment by Yenthe666** [comment]
Hmm sorry I can't find it either but it has been discussed a few times in the past indeed. @khaihoan123 we always welcome PR's and since this won't be changed by Odoo itself now I'm closing it as won't fix.
