### ISSUE TITLE
No way to pass context from kanban view link or buttons to called action

### ISSUE THREAD

**Issue by michaelkarrer81** [odoo/odoo#6236]
It seems there is no way to pass context to the called action from kanban-view links or buttons?

Because of this you can not reproduce the behaviour of e.g. a smart button in a kanban link :( 

In the documentation is a note that mentions that hyperlinks in kanban views would take more or less the same attribs than buttons - but is seems context is not one of them?!?

**Comment by msh-odoo** [comment]
This may help you, https://github.com/odoo/odoo/pull/6079/files

**Comment by Yenthe666** [comment]
Yup - should have been handled at https://github.com/odoo/odoo/pull/6079/files
