### ISSUE TITLE
typo in ResConfigSetting

### ISSUE THREAD

**Issue by tinybench** [odoo/odoo#62361]
Impacted versions:
14.0

file: addons\purchase\models\res_config_settings.py
line: 34
code: help="Allow automatically send email to **reminde** your vendor the receipt date")

reminde should be remind?

**Comment by pedrobaeza** [comment]
Yes, it's a typo, but it implies to change all translations. @mart-e should it be fixed in current branch?

**Comment by mart-e** [comment]
It's kind of my fault, it was bad before, and it's still bad now :confused: 
See https://github.com/odoo/odoo/pull/61785#pullrequestreview-531510160
I plan to fix it soon, in 14.0 it's still tolerated to change a bit the translatable content in the following weeks/months after the release.

**Comment by tinybench** [comment]
@mart-e when shall I close the issue? now or you will close when you fix it?

**Comment by Faroukkooli** [comment]
https://github.com/odoo/odoo/pull/61785#pullrequestreview-531510160 is wheere you can find the solution for this type of error for anyone who needs it

**Comment by mart-e** [comment]
Forgot to close the issue but indeed should be good now
