### ISSUE TITLE
AssertionError "{} is a required field ({})" not raised for Many2Many field

### ISSUE THREAD

**Issue by rven** [odoo/odoo#62375]
Impacted versions:
12.0, 13.0, 14.0
Steps to reproduce:
```python
class ProductTemplate(models.Model):
    _inherit = "product.template"

    platform_required = fields.Boolean(string="Platform Required")
    platform_ids = fields.Many2many(
        comodel_name="platform",
        string="Platforms",
        ondelete="restrict",
    )
```
```xml
<odoo>
    <record id="product_template_form_view" model="ir.ui.view">
        <field name="model">product.template</field>
        <field name="inherit_id" ref="product.product_template_form_view" />
        <field name="arch" type="xml">
            <xpath expr="//field[@name='categ_id']" position="after">
                <field name="platform_required"/>
                <field name="platform_ids" widget="many2many_tags" attrs="{'required': [('platform_required', '=', True)]}"/>
            </xpath>
        </field>
    </record>
</odoo>
```

Current behavior:
Following test is not raising the expected AssertionError "is a required field"
```python
    def test_platform(self):
        """
        Test creation of product with required platforms, but not specified
        """
        with Form(self.product_obj) as p:
            p.name = "TST Product"
            p.platform_required = True
        p.save()
```
The check **v is False** is incorrect for a Many2many field
https://github.com/odoo/odoo/blob/700dba53843e71f5f34c86305cc658d9273914aa/odoo/tests/common.py#L1776
![image](https://user-images.githubusercontent.com/8638295/100329991-abfa2d00-2fce-11eb-8cf8-93917ac7c35e.png)
![image](https://user-images.githubusercontent.com/8638295/100331162-1b245100-2fd0-11eb-82d6-c41030ff9747.png)
Expected behavior:
The test should raise the expected AssertionError "is a required field"

**Comment by xmo-odoo** [comment]
Hello @rven 

Thanks for the report, however as far as I can tell the behaviour observed here is the correct one: the server-side form view aims to more or less replicate the behaviour of the Odoo client, and the Odoo client does not take in account "required" on many2many fields. I just tested this on the runbot, whether in 12.0 or master making the `users` field of `res.groups` required (whether through `@required` or `@attrs`) does not prevent creating a group with no users.
