### ISSUE TITLE
Wrong translation

### ISSUE THREAD

**Issue by antoniov** [odoo/odoo#6238]
Two countries are wrong translated in italian.
Niger -> Niger  (Not Nigeria that is another different country)
Dominica -> Dominica  (Not Repubblica Dominicana that is another different country)

File name: ./server/openerp/addons/base/i18n/it.po

**Comment by mart-e** [comment]
Hello,

For correction of translations, please check [translation guidelines](https://github.com/odoo/odoo/wiki/Translations) but globally, go to [transifex](https://www.transifex.com/projects/p/odoo-8/) to join translation team.
Thanks

**Comment by antoniov** [comment]
Thank
I signed in transifex
