### ISSUE TITLE
odoo12: preferences odoobot status: disabled, yet still requests 

### ISSUE THREAD

**Issue by f1-outsourcing** [odoo/odoo#62392]
I disabled the odoobot status 2-3 days ago, yet still getting "Odoobot has a request" messages.

**Comment by pedrobaeza** [comment]
Are they from before that disabling?

**Comment by f1-outsourcing** [comment]
I do not think so. I am testing with multiple accounts currently with the Administrator, and I have been refusing this request several times on several accounts. I cannot imagine this last one is from before disabling it.

**Comment by f1-outsourcing** [comment]
I just logged out and then logged in with the admin, and it is back again as not being read. So maybe the message is from before disabling it, but somehow the 'read' status is not maintained? Or it is a new message.

**Comment by pedrobaeza** [comment]
I would say that you need to mark as read such message, and see if with new users or current ones you see more messages coming. If not, this is not a bug, but a reminder of previous messages.

**Comment by f1-outsourcing** [comment]
It is even worse. If I mark it as read on company A, switch to company B, I am getting the request at company B, mark it there as read again, then switch back to company A the same request is back again.
So it constantly keeps asking to enable desktop notifications.

**Comment by pedrobaeza** [comment]
OK, not sure if that's the wanted behavior, but I have tagged it.

**Comment by seb-odoo** [comment]
Odoobot status, which is controlling the Oboobot onboarding chat, is not related to the "Odoobot has a request" message for requesting browser notifications. This last one should normally disappear on your browser immediately after you accepted or declined it, as it's based on the browser notification permission.

**Comment by seb-odoo** [comment]
Assuming this is resolved as no response since my last message.
