### ISSUE TITLE
CRM Kanban Drag & Drop does not recompute the probability

### ISSUE THREAD

**Issue by enclustra-odoo** [odoo/odoo#62408]
Impacted versions:
13.0

Steps to reproduce:
1. Go to the kanban view of the CRM opportunities
2. Drag an opportunity from a "won" stage (where the won flag is set and probability is 100%) and drop to another stage where probability is not 100%

Current behavior:
- The probability does not change when using drag & drop in the kanban view
- When changing the stage in the form view of the opportunity itself,  the probability is recomputed
- Drap & drop somehow does not trigger a recomputation of the probability

Expected behavior:
- Same behaviour as selecting the stage in the opportunity form view
- Drag & drop does trigger a recomputation of the probability

**Comment by pedrobaeza** [comment]
On v13, there's no more automatic probability change according stages. There's a won flag for stages, but nothing more. Instead, an auto-calculated probability based on IA is provided, and you can click for using such probability. If you want such functionality, you need a third-party module that re-adds such behavior.

Closing as no bug, but expected behavior.

**Comment by enclustra-odoo** [comment]
Clearly you did not understand nor test it yourself. This has nothing to do with _how_ the probability is calculated but more with _when_ the probability calculation is triggered.
I will try to explain it again:

1. When changing the stage from "won" to e.g. "new" using the stage buttons (see Capture 1 below) the green "won" flag is removed (see capture2 below
![Capture1](https://user-images.githubusercontent.com/56344061/100729252-cebe8400-33c8-11eb-8794-015f027c7ec2.PNG)
![Capture2](https://user-images.githubusercontent.com/56344061/100729549-307eee00-33c9-11eb-89e3-35060295ec24.PNG)
2. When doing the same procedure but using drag&drop (see capture 3 and 4 below)
 in the kanban view instead, the "won" flag is still shown (see capture 5 below), altough the stage has changed to "new"
![Capture3](https://user-images.githubusercontent.com/56344061/100729857-98353900-33c9-11eb-8824-f65500fe3479.PNG)
![Capture4](https://user-images.githubusercontent.com/56344061/100730949-0a5a4d80-33cb-11eb-9506-a991807bb2d0.PNG)
![Capture5](https://user-images.githubusercontent.com/56344061/100729929-ae42f980-33c9-11eb-8b2d-75573381c77d.PNG)

Facts:
- When using the clicking feature in the stage (option 1 above), the probability is recomputed and the "won" flag is removed
- When using drag&drop the probability is not recomputed, hence the "won" flag is **not** removed

Please test it youself. If you still see this as an expected behaviour, I would like a detailed explanation on why this behaviour would be expected and why it is fixed in Odoo14 but cannot be backported to Odoo13

**Comment by pedrobaeza** [comment]
First of all, with such attitude, you won't get too much here, as this is a voluntary effort, and as such, the goal is to report things that can be fixed to you with no cost, so you should be more polite.

Next, the initial explanation was not good enough for understanding the problem. On the second try, you are still mentioning "changing probability", which has nothing to do with the "Won" flag, but I have understood you. Anyway, this is not happening on a quick try that I have made on runbot:

![Peek 01-12-2020 17-42](https://user-images.githubusercontent.com/7165771/100769903-f16a9000-33fc-11eb-90b6-00de4046cc63.gif)

So you have outdated code or third-party modules that are breaking this behavior.
