### ISSUE TITLE
[8.0] Cancel Manufacture Order, cancel the related delivery order line

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#6246]
Hello Odoo,

I want to ask a question, when I cancel the manufacture order that generated from procurement, the related delivery order line in sale order will cancel too.
How can I disable this behavior?

So here is what I done:
1.  Create a sale order with product that has make to order and manufacture and BoM.
2.  Confirm the sale order and the system will generate procurement.
3.  Run the procurement, and the system will generate the manufacture order.
4.  I cancel the manufacture order.
5.  I look on the delivery order on the sale order that I created, the delivery order line is cancel too. (the expected behavior is this line is not cancel)

So how can I disable this behavior? On the version 7 , the behavior is not like this.

Thank You.

**Comment by Yenthe666** [comment]
Hi @falinwa,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
