### ISSUE TITLE
[13.0] Implementing socket.io with odoo

### ISSUE THREAD

**Issue by crtmneric** [odoo/odoo#62462]
Hi there,

I have some business requirements for sharing real time data like broadcasting. Is it possible to use socket.io server with odoo ? I have searched a lot to find a simple or not guideline but there is nothing about this topic ?

Can you guys give me hints please ?
btw: client's are not web users,they are IoT devices.

**Comment by pedrobaeza** [comment]
I don't know any effort on such direction, but anyway this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
