### ISSUE TITLE
[8.0] Bug in Invoice supplier

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#6247]
Hi Odoo,

I find a bug when I want to generate the invoice from incoming shipment.
The supplier display the wrong one.
You can test in your fresh database.

So this is what I done:
1.  Create sale order with agroilat, and order the product that has buy and make to order procurement method and has a supplier list on it.
2.  Confirm the sale order
3.  Run the procurement.
4.  It will create a new purchase order
5.  Change the invoice method to the based incoming shipment on purchase order
6.  Confirm the purchase order
7.  It will generate the incoming shipment
8.  Transfer the incoming shipment
9.  Create the invoice
10. The invoice supplier will be agroilat which is wrong, it must be the supplier of the purchase order.

Here is the video to explain things:
https://falinwa-my.sharepoint.cn/personal/falinwa1_falinwa_partner_onmschina_cn/_layouts/15/guestaccess.aspx?guestaccesstoken=KJkBazmwnlkAdrVBe1RZ94zVdvlRcQg9RstPln%2fi6%2f4%3d&docid=06a1c902696e54686899a8ee0afdb67e9

**Comment by aliomattux** [comment]
Confirmed issue caused by commit
https://github.com/odoo/odoo/commit/d416492259f08cff03004e8679bf63afde260ab2

**Comment by Yenthe666** [comment]
Hi @falinwa ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
