### ISSUE TITLE
[8.0] Bug when invoicing based on group partner on picking

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#6248]
Hi Odoo,

I find a bug when I want to generate invoice on picking.
When I generate the invoice from 2 picking, and group by partner.
It will create 2 invoices, even it the same partner and I already check the group by partner checkbox.

So here is what I do:
1.  Create sale order with invoice method on delivery order and confirm it.
2.  Create another sale order with same customer but different sale person and with invoice method based on delivery order and confirm it.
3.  Both of it will generate the picking.
4.  I go to the warehouse and select both picking that I generated.
5.  I generate the invoice by click more and create draft invoice.
6.  I check the checkbox group by partner.
7.  The system still create 2 invoice, it must be just 1 invoice.

I think this problem occur because we have different sale person, but the behavior is it should be merged because we already check the checkbox group by partner.
So it must be 1 invoice, and the behavior from version 7 is like that.

Video to explain things:
https://falinwa-my.sharepoint.cn/personal/falinwa1_falinwa_partner_onmschina_cn/_layouts/15/guestaccess.aspx?guestaccesstoken=IuYIDQi4%2bWP9ak%2f79TCj9C0nsRcVRh5DnIN0K3vldgo%3d&docid=0d466b3f763bb46ec931648a1a86a15cf

**Comment by Yenthe666** [comment]
Hi @falinwa,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
