### ISSUE TITLE
Newsletter-subscription blocked by recaptcha

### ISSUE THREAD

**Issue by NICO-SOLUTIONS** [odoo/odoo#62504]
Impacted versions: Odoo V14 CE

Steps to reproduce: 
- activate recaptcha on google website!
- define reCaptcha V3 keys in settings. 
- Add a newsletter block to your website. 
- try to subscribe to newsletter

Current behavior:
- After clicking the subscribe button, a pop-up appers with the Error " Suspicious activity detected by Google reCaptcha.". The subscription is rejected.
- Other input forms works great (login, contact form, recruitment form)

Expected behavior:
- After clicking the subscribe button the subscription should not be rejected.

Any ideas of whats going on here? i tried to compare the scripts behind the buttons but i cant find to culprit.

All the best
Nils

**Comment by NICO-SOLUTIONS** [comment]
Is it possible, that the problem is related to a missing "Content-Security-Policy"?

in the console i can see...
Content Security Policy: Ignorieren von "http:" innerhalb script-src: 'strict-dynamic' angegeben
Content Security Policy: Ignorieren von "'unsafe-inline'" innerhalb script-src: 'strict-dynamic' angegeben
... a few times. 

I dont think, that this is the problem, as i do have the same warnings on the contact form, which is working...

So... This is just a hint for what i noticed.

All the best
Nils

**Comment by JKE-be** [comment]
@bso-odoo if you can check this one in v14.
thx

**Comment by bso-odoo** [comment]
Problem reproduced and identified: the action identifier used to obtain the reCaptcha token was different from the one used to verify the validation.

**Comment by NICO-SOLUTIONS** [comment]
Many thanks @JKE-be for the marker & @bso-odoo for finding the problem. 
i suppose the hint for a corrected code will be displayed here when this is done? 

THX

**Comment by JKE-be** [comment]
Hi @NICO-SOLUTIONS 
Yes, you can see in the thread the commit that reference this issue.
Bso is working on a PR (#62713) to fix it

Thanks for the reporting...
