### ISSUE TITLE
[8.0] Sale/Purchase Receipt wrong period on journal change

### ISSUE THREAD

**Issue by thomich** [odoo/odoo#6251]
Impacted versions:
- 8.0

Requirements for tests:
- edit the form view of eg. purchase receipt and remove attribute from tab Journal Items
  attrs="{'invisible': [('state','!=','posted')]}"
  ![account_voucher view_sale_receipt_form](https://cloud.githubusercontent.com/assets/4398840/7085337/1e9b0c80-df76-11e4-824e-cc04cf9e222a.png)

Steps to reproduce:
1. create sale or purchase receipt > period will be selected from todays date
2. change date of receipt to a date of previous period > period will be changed to date of receipt
3. change journal > period will be selected from todays date

Current behavior:
- wrong period after journal change

Expected behavior:
- journal change should change period based on receipt date and NOT todays date

Workaround:
- change receipt date again > period will be changed to date of receipt

BUG FIX ;) http://paste.ubuntu.com/10790167/

regards
thomi

**Comment by Yenthe666** [comment]
Hi @thomich,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by thomich** [comment]
I love that kind of Feedback.... and this kind of Feedback started month ago...
Odoo LTS mean, that it's ends when they decide it ends...
https://www.odoo.com/de_DE/page/odoo-long-term-support
Here we see Odoo 8 LTS ends by End of 2017...

![image](https://user-images.githubusercontent.com/4398840/33894174-99ed488c-df5d-11e7-8989-ad25556c6ef2.png)

No need any feedback in this, this is just a statement...

**Comment by spadae22** [comment]
YES, very nice since some of the 'BUGS' go back to 2015.....

**Comment by Yenthe666** [comment]
Hi @thomich,

It actually closed 6 october 2017. As you can see in the screenshot it isn't for the whole year (it stops a bit before 2018).
Again, I'm sorry it wasn't ever handled (along with some others). In general the feedback and solving issue has gone up quite good though, as you can see at https://github.com/odoo/odoo/issues?q=is%3Aopen+is%3Aissue+label%3A11.0

Regards,
Yenthe
