### ISSUE TITLE
[8.0]Manufacture Order Sequence Bug

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#6252]
Hi Odoo,

I found a bug when I want to generate the manufacture order from procurement.
Environment multicompany:
Parent: A
Sister: B
Brother: C

Procurement rule manufacture and make to order for company B
There’s a sequence for manufacture order both for company B and C

So here is what I done:
1.  The administrator in company C
2.  I login as another user in company B
3.  I make a sale with the product that has manufacture and make to order for company B
4.  I confirm the sale order, the system will generate the procurement.
5.  I run the procurement, the system will generate the manufacture order with sequence for company C.
6.  The expected behavior should be the sequence for company B.

I think there’s a lot of problem in multicompany for Odoo.
We have a lot of complain since we move to version 8,
I think it because you use administrator now to generate the manufacture order.
Its okay to use administrator, but you must respected the company that already configured in rule and what kind of record that belong to that company.
If the source record is company B, the generated record should be in company B too, wherever the administrator belong to.

Video to explain things:
https://falinwa-my.sharepoint.cn/personal/falinwa1_falinwa_partner_onmschina_cn/_layouts/15/guestaccess.aspx?guestaccesstoken=AuEQEuiDiH4Px663NXC8sZHm23LT8opkMvRxF0X7QVU%3d&docid=0ff5b4922f21c4d73ad7547179c0bea42

**Comment by Yenthe666** [comment]
Hi @falinwa,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
