### ISSUE TITLE
Traceback in the blank database when trying to create analytic account

### ISSUE THREAD

**Issue by jni-odoo** [odoo/odoo#6254]
Steps to produce the issue: (version 8.0)

(1) Create a blank database (without any demo data)
(2) Install the module "analytic_user_function" (which installs the dependencies of time sheet and accounting)
(3)Now allow the analytic accounting feature in the database
(4) Go to the menu Accounting -> Configuration -> Analytic Accounting -> Analytic Accounts..click in the Create button to create a new analytic account...you will get the traceback..

See image : https://docs.google.com/file/d/0B5j41T1Hqv1sMG1RSGhYRlBQM1k/edit?usp=drivesdk

**Comment by Yenthe666** [comment]
Hi @jni-odoo,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
