### ISSUE TITLE
Error after deleting the Weight and Litre from UOM Categories

### ISSUE THREAD

**Issue by niyasraphy** [odoo/odoo#62567]
Impacted versions:  Saw the issue in odoo14

Steps to reproduce: Activate the multi uom in the database, and delete the uom category weight or litre and try to open the product form.

Current behavior: allow to delete the uom categories and error is thrown on opening the product form.

Expected behavior: Either block deletion of this uom categories or handling of the error in product form.

Video/Screenshot link (optional):

![Screenshot from 2020-11-28 08-40-40](https://user-images.githubusercontent.com/27989791/100494762-e17d5280-3155-11eb-8d98-b33289e41c69.png)

**Comment by pedrobaeza** [comment]
Yes, they can't be deleted. Update `uom` module for restoring them.

There's an ongoing conversation in #61762 about how to prevent deletion of essential data, so I close this one.
