### ISSUE TITLE
"gevent" version fo Python3.8

### ISSUE THREAD

**Issue by ska-ibees** [odoo/odoo#62569]
Impacted versions: 14.0

Steps to reproduce: Install odoo with python3.8

Current behavior:
When running Odoo getting below error:

<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject

Details:

It seems that gevent version in requirements.txt:

`gevent==1.5.0 ; python_version >= '3.7'` is not compatible with python3.8.

As per [discussion here ](https://github.com/python-greenlet/greenlet/issues/178#issuecomment-698874295)

>On Python 3.8 or 3.9, the minimum gevent version is 20.6.0, and the minimum greenlet version is 0.4.16.

>I'd just use gevent>= 20.9; greenlet >= 0.4.17 everywhere.

After updating gevent to 20.9.0 that error is gone. 

So, is it ok to use gevent=20.9.0 or there any potiential risks involved?

**Comment by Yenthe666** [comment]
@d-fence you're probably the best person to check this :)

**Comment by bobslee** [comment]
FYI...
I also encountered that `RuntimeWarning`, if I remember correctly... after I updated the PyPi libraries (`pip install -U requirements.txt`).
Which occurred during my quick analysis of issue https://github.com/odoo/odoo/issues/62786
In the issue you'll notice the PyPi versions recently (week ago) changed in the `requirements.txt`.

**Server / environment:**
- Odoo 14
- Python 3.8
- Ubuntu 20.04

**Comment by d-fence** [comment]
I cannot reproduce.
Tested a fresh install in pyenv with:

- 0doo 14
- Python 3.8.5
- `pip install -r requirements.txt`

**Comment by bobslee** [comment]
I just tested again on an install / server (Ubuntu 20.04, Python 3.8.5):

with already:
- Odoo 14 478ebc74554f6609a1414726ee1f35fe5dcd6a81 (November 10th).

updated to:
- Odoo 14 2a12393b68bbec9b76f1534b3e881c39348d8a0e (November 19th),
which introduced the change in the `requirements.txt` (PyPI) 
=> https://github.com/odoo/odoo/commit/648635deca67df09417ae55c6eb181c98524b74d#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552
- `pip install -U -r requirements.txt`

**After the update and restart I get the log below**
No issue before the update.
Seems like some "dev header package" is incompatible.

```
2020-12-04 15:47:55,879 783 INFO ? odoo: Odoo version 14.0 
2020-12-04 15:47:55,879 783 INFO ? odoo: Using configuration file at /home/odoo/odoo/odoo.conf 
2020-12-04 15:47:55,879 783 INFO ? odoo: addons paths: ['/opt/odoo/odoo/odoo/odoo/addons', '/root/.local/share/Odoo/addons/14.0', '/opt/odoo/odoo/enterprise', '/opt/odoo/odoo/odoo/addons'] 
2020-12-04 15:47:55,879 783 INFO ? odoo: database: odoo@localhost:default 
2020-12-04 15:47:56,003 783 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf 
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
```

**Comment by ap-wtioit** [comment]
had the same errors and fixed it like mentioned here: https://github.com/odoo/odoo/pull/57328

**Comment by rk-aix** [comment]
Had also same errors here after upgrading Ubuntu Server from **18.04 to 20.04** with Python **3.8.5**, Gevent **20.9.0**, Greenlet **0.4.17** on November 27th. Odoo 14 (from December 5th)
Just approx. one week before Greenlet rised up from 0.4.1**6** to 0.4.1**7**.
Returning back to 0.4.16 solved the problem for me e.g.: pip install greenlet==0.4.16
No further effects noticed since then...

**Comment by jorgeegomez** [comment]
> I cannot reproduce.
> Tested a fresh install in pyenv with:
> 
>     * 0doo 14
> 
>     * Python 3.8.5
> 
>     * `pip install -r requirements.txt`

@d-fence The error is not shown when installing; did you try running `python -m gevent` in the venv?

**Comment by bobslee** [comment]
Should be solved by PR: https://github.com/odoo/odoo/pull/65012

Related issues:
- https://github.com/odoo/odoo/issues/64106
- https://github.com/odoo/odoo/issues/62786

**Comment by Yenthe666** [comment]
Yep, correct! Thanks for mentioning this Bob :)
