### ISSUE TITLE
[14.0] Due to security restrictions, you are not allowed to delete 'Time Off' (hr.leave) records.

### ISSUE THREAD

**Issue by hongquangminh** [odoo/odoo#62572]
Impacted versions: 14.0

Steps to reproduce:

- Create a new user (m_test). Also linked employee to the user.
- Logged as user m_test and create new Time Off.
- Make as draft for this Time Off. Then delete but cannot.

Current behavior:

- Cannot delete the Time Off record when the state is To Submit.

Expected behavior:

- User can delete the Time Off when the state is To Submit.

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/28040072/100575566-f8b37000-330e-11eb-8e29-0e7842446034.png)

**Comment by sswapnesh** [comment]
Tried same on Runbot and it Seems Working well .

**Comment by pedrobaeza** [comment]
Closing until further evidence of the problem still remains.
