### ISSUE TITLE
Module description not in .po file of this module

### ISSUE THREAD

**Issue by GoodERPJeff** [odoo/odoo#626]
From 6.1, I found when we try to translate a module, each time I export the po file for this module, the module mainfest information not included in the generated po file.

they goes to base module for official addons, that's why BASE module have so many long terms to translate without context.

this behave also ham to non-official  addons, because we have no chance to provide complete locale translation due to this issue.

**Comment by zaoral** [comment]
This problem persist in odoo 8.0. the module description is not taked into account when exporting a module translations wizard from the odoo instance, either the module description is in the __openerp__py or in the README.md file.

I think this is a flaw for localization modules. In those modules should be complete translated.

**Comment by Yenthe666** [comment]
Dear @GoodERPJeff ,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.
P.S: This will still pop-u as wishlist, even after closing this.

Regards,
Yenthe

**Comment by mrshelly** [comment]
+1

**Comment by jeffery9** [comment]
this should be re-open, this issue affected all version.

**Comment by Yenthe666** [comment]
@jeffery9 the wishlist items are looked at, even if they're closed, so it'll keep popping up. 😄
