### ISSUE TITLE
Cannot change website style while on ?debug=assets

### ISSUE THREAD

**Issue by yajo** [odoo/odoo#62602]
Impacted versions: 12.0. Not tested on others.

Steps to reproduce:

1. Log in runbot.
1. Enable `theme_bootswatch` on your website.
1. Apply the Cerulean style.
1. Go to `/?debug=assets`.
1. Apply the Default style.

Current behavior: Odoo will reload, but still will keep the Cerulean style, although Default is selected. 

Expected behavior: Default style is correctly applied.

This is possibly related to https://github.com/odoo/odoo/pull/57241, because I managed to reproduce it while debugging why https://github.com/odoo/odoo/pull/57241#issuecomment-735736706 didn't work now.

@Tecnativa TT25283 @qsm-odoo

**Comment by rdeodoo** [comment]
Hello and sorry for not taking care of this one (sooner).

As the 16.0 was finally released and the OXP rush is over, I am trying to sort and clear the website issues pipe.
In the future, don't hesitate to ping `@odoo/rd-website` and we will reply in a decent timeframe, as we try to do with PR (where we are automatically pinged thanks to the codeowner feature).

For this one, as `theme_bootswatch` was removed in 14.0, I'll close it.
