### ISSUE TITLE
Odoo confuses website and mass_mailing assets when website is forced

### ISSUE THREAD

**Issue by yajo** [odoo/odoo#62604]
Impacted versions: 12.0. Not tested on others.

Steps to reproduce: Quoting from https://github.com/odoo/odoo/pull/57241:

> using the mass mailing editor in `debug=assets` mode after performing some action on the website that added the `force_website_id` key to user's session (such as installing a theme), the downladed assets would be polluted with the currently-forced website's theme.

See video.

Current behavior: Website themed styles get merged with mass_mailing styles.

Expected behavior: Mass mailing styles should be independent of website. https://github.com/odoo/odoo/pull/57241 fixed the problem on an older codebase, but it seems something new has happened in Odoo (see https://github.com/odoo/odoo/issues/62602) that made https://github.com/odoo/odoo/pull/57241#issuecomment-735736706 not fix this anymore.

Video/Screenshot link (optional): https://youtu.be/wtYmU_eiXRM

@Tecnativa TT25283 @qsm-odoo

**Comment by rdeodoo** [comment]
Hello and sorry for not taking care of this one (sooner).

As the 16.0 was finally released and the OXP rush is over, I am trying to sort and clear the website issues pipe.
In the future, don't hesitate to ping `@odoo/rd-website` and we will reply in a decent timeframe, as we try to do with PR (where we are automatically pinged thanks to the codeowner feature).

For this one, we obviously don't support the 12.0 version and we made fix for this in later version (and now have tests for this), I'll close it.
Should you find some more issues related to assets mismatch, don't hesitate to open a new issue and ping `rd-website` directly and we will handle it in short delay.
Thanks.
