### ISSUE TITLE
[8.0] Group by + remove grouping results in no arrows to move between pages

### ISSUE THREAD

**Issue by mariuszmizgier** [odoo/odoo#6262]
1. Go to any tree view with more than 80 records in database and apply any group by.
2. Remove that group by from search field.

Result - arrows to move between pages of records are gone.
Expected result - arrows to move between pages of records are present and working.

Movie - http://youtu.be/zRGnFB4za54

**Comment by Yenthe666** [comment]
Hi @mariuszmizgier ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
