### ISSUE TITLE
Qweb template inheritance doesn't work.

### ISSUE THREAD

**Issue by xor3** [odoo/odoo#6264]
The following qweb template does't work.

```
    <t t-extend="ViewManager">
        <t t-jquery=".oe_view_title" t-operation="before">

            <div>
                <span>hello world</span>
            </div>
        </t>
    </t>
```

But this one does.

```
    <t t-extend="ViewManagerAction">
        <t t-jquery=".oe_view_title" t-operation="before">

            <div>
                <span>hello world</span>
            </div>
        </t>
    </t>
```

While "ViewManagerAction" extends from "ViewManager",  what happens with QWeb?
Any explanation? Thanks.

**Comment by Yenthe666** [comment]
Hi @xor3,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
