### ISSUE TITLE
[14] website_blog: Newly added tag should be displayed in existing

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#62647]
Impacted versions: 14.0

Steps to reproduce: Edit Blog post --> Create New Tag
![Screenshot (2)](https://user-images.githubusercontent.com/16624719/100651000-cd5e6e80-336a-11eb-84b9-14a091634819.png)

Select the new Tag from Existing List

![Screenshot (3)](https://user-images.githubusercontent.com/16624719/100651005-ce8f9b80-336a-11eb-9bca-fc5178444d29.png)

Current behavior: 
![Screenshot (4)](https://user-images.githubusercontent.com/16624719/100651019-d0f1f580-336a-11eb-9e56-f74015cf56dd.png)

 
Expected behavior: Newly added tag should not be displayed in the existing list since It is added automatically when we create a new tag.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@JKE-be for your team
