### ISSUE TITLE
[14.0] account: unbalanced journal entry with custom field in invoice lines

### ISSUE THREAD

**Issue by abdallamohamedcore** [odoo/odoo#62667]
Impacted versions:
14.0

Steps to reproduce:
- Activate studio.
- Create a new field in the invoice lines tab related to "Analytic Account" called  "Cost Center".
- Add the same field in the journal items tab.
- Create a new invoice and choose any product then choose any cost center then save the invoice.
- Edit the same invoice and add a new line with the same or another cost center.
- Click on "Save"

Current behavior:
appear unbalanced journal entry due to "Account receivable" does not update with tax for the new invoice line

Video/Screenshot link (optional):
Video: https://drive.google.com/file/d/1L8QMUcFbkZ5OWudiwMNFk1LQKj9V6jqC/view
Exported Studio: [stuido_customizations.zip](https://github.com/odoo/odoo/files/5621652/stuido_customizations.zip)

**Comment by pedrobaeza** [comment]
Sorry, but the error you are mentioning corresponds to a custom module or code (or Odoo Studio), so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you. You can also write to odoo.com/help for enterprise support.
