### ISSUE TITLE
Bank and Cash statement

### ISSUE THREAD

**Issue by zbik2607** [odoo/odoo#6266]
Operations "Put Money In" and "Take Money Out" cause an error: a mandatory field is not correctly set\n\n[object with reference: date - date

Similar Error when Cash Register is closed with Loss or Profit

The Reason:  field date in account.bank.statement.line is required but date value not propagate from views and when button_confirm_cash() is called

PS. When "Put Money In" partner_id should be set as selected partner or as default user.

**Comment by Yenthe666** [comment]
Hi @zbik2607,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
