### ISSUE TITLE
fixed rate problem on sales invoice always less

### ISSUE THREAD

**Issue by brahimtsi** [odoo/odoo#62670]
Impacted versions: V14

Steps to reproduce: add fixed taxe in tax

Current behavior: 
deductible in invoice 

Expected behavior:

Video/Screenshot link (optional):

**Comment by brahimtsi** [comment]
![Capture](https://user-images.githubusercontent.com/11885420/100730326-345f4000-33ca-11eb-922d-936a6a3d5185.PNG)

**Comment by pedrobaeza** [comment]
And what is the problem?
