### ISSUE TITLE
email digest not available on odoo 14

### ISSUE THREAD

**Issue by dirceu3h** [odoo/odoo#62695]
Impacted versions: Odoo 14 community

Steps to reproduce: When i try to enable email digest on the settings section there is no option for that. On odoo 13 there was that option. We already updated the source code to lastest version.
Was it moved to another section?
It's not available on community anymore?
Do i need to install certain module ?

Current behavior:
no statistics or email digest on settings section

Expected behavior:
Should be an email digest option on settings section

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/42354147/100762677-82b41500-33b1-11eb-8d32-a435c563f45a.png)

**Comment by pedrobaeza** [comment]
The `digest` module still exists. Anyway, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
