### ISSUE TITLE
Computed fields without dependencies are not computed during record creation (as a default value)

### ISSUE THREAD

**Issue by NicolasWebDev** [odoo/odoo#6270]
**Computed fields without dependencies are not computed during record creation**

Impacted versions:
- 8.0

Steps to reproduce:
1. create a computed field without dependencies
2. open its creation form

Current behavior:
- The compute does not get called.

Expected behavior:
- That it got called as a default value also.

Details:
- So far I need to define the compute as self.computed_field = self.computation(), and in the default I have to put default=lambda self: self.computation(), which is code duplication I do not like.
- Why not call the compute automatically as default value?
- Is this a defect or a feature?

Thanks

**Comment by akhmadMizkat** [comment]
Anyone please ?

I'm facing this problem too....

**Comment by Sathors** [comment]
So far it has not been assigned, so we will still wait quite some time I guess...

**Comment by deepa-venkatesh** [comment]
Even am facing this problem.. Please help...

**Comment by sagastume** [comment]
is there solution for this?

**Comment by raj15feb** [comment]
Hi, I have created a compute field in sale order form and updating the values in order line. But when I changed the product or qty or price value is not calculated correctly after refresh more than two times value corrected. Please help.
Thanks

**Comment by Yenthe666** [comment]
Hi @NicolasWebDev,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
