### ISSUE TITLE
mail an error occurred

### ISSUE THREAD

**Issue by ricky-ming** [odoo/odoo#62710]
Impacted versions:  12.0+e

Steps to reproduce:this error occurs when RMA is created from helpdesk

Current behavior:

Expected behavior:

Video/Screenshot link (optional):
![Snipaste_2020-12-02_13-56-16](https://user-images.githubusercontent.com/64247188/100834123-47dfd900-34a6-11eb-8b4f-8bb48538a7ed.png)

**Comment by ricky-ming** [comment]
From the error point of view, it is because there is an extra space in this parameter. I hope you can check and update it as soon as possible, because the company system can no longer operate normally

**Comment by Yenthe666** [comment]
Can you reproduce this on runbot.odoo.com on the latest 12.0? You have a module from muk installed (`muk_security`) which seems to cause this issue. Odoo is just mentioning it:
https://github.com/odoo/odoo/blob/152237fa28ac22a869402310939a2459c50f22b5/odoo/addons/base/models/ir_rule.py#L77-L79

**Comment by ricky-ming** [comment]
I mean, this place itself is an error. Why is there a parameter with a space?

**Comment by Yenthe666** [comment]
There is no space in the core, the space is coming back from a super call from the MUK module. Please check in the custom code from `muk_security`

**Comment by ricky-ming** [comment]
This parameter is directly written and fixed in this code. How can it be transmitted?

**Comment by Yenthe666** [comment]
`def _compute_domain(self, model_name, mode="read"):`
Do you see any space in there? :)
I bet that `super()` call from MUK has an invalid space it in.

**Comment by ricky-ming** [comment]
![image](https://user-images.githubusercontent.com/64247188/100990216-9bc4ed80-358c-11eb-9fbb-929fc1ed7279.png)
It is because the official updated source code is an extra space,
Cause the parameters to be obtained with a space

**Comment by ricky-ming** [comment]
That's why I submitted it

**Comment by Yenthe666** [comment]
Sorry, I initially misunderstood your screenshot & issue :) You are right. One of the developers introduced a bug. I made a fix at https://github.com/odoo/odoo/pull/62792

**Comment by Yenthe666** [comment]
Fixed in https://github.com/odoo/odoo/commit/11476453484ab8922a25ea41e882aa0c1b080a30
