### ISSUE TITLE
[8] Once a chained move is unreserved, it can never be re-reserved again if its quant slips away

### ISSUE THREAD

**Issue by a0c** [odoo/odoo#6272]
When the last move in a chain gets unreserved, its quants are freed and can be legally reserved for other moves. If this happens, the last move in a chain can never be reserved again due to restriction to its history (its ancestor moves whose quants are now overtaken by that other move).

There should be a way to revive moves that got stuck this way.
Last move in a chain can be either an MTO move or a chained MTS move.
Generally, a user should have 3 options to bring last moves in a chain to life:
1. re-Manufacture,
2. re-Purchase,
3. re-reserve from Stock.

In my next Pull Request I will offer a non-invasive solution to option 3, requiring minimal interaction from user.

**Comment by Yenthe666** [comment]
Hi @a0c,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
