### ISSUE TITLE
pos_cache not correctly upgraded to version 14

### ISSUE THREAD

**Issue by bwilmus** [odoo/odoo#62754]
Impacted versions: 14

Steps to reproduce: install pos + pos_cache and open a new session

Current behavior:
Traceback (most recent call last):
File "/opt/odoo/odoo-server/odoo/http.py", line 638, in _handle_exception
return super(JsonRequest, self)._handle_exception(exception)
File "/opt/odoo/odoo-server/odoo/http.py", line 314, in _handle_exception
raise exception.with_traceback(None) from new_cause
TypeError: Object of type datetime is not JSON serializable

Expected behavior: No error :-)

**Comment by Yenthe666** [comment]
Can you reproduce this on runbot.odoo.com?

**Comment by yelizariev** [comment]
opw-2410334

@Yenthe666 yes, it's reproducible on runbot

@bwilmus the best way to report CE bugs is make an issue first, then make a ticket, send post a ticket number here

**Comment by bwilmus** [comment]
Ticket number is 2410334

There is a video of that bug in the ticket.

**Comment by yelizariev** [comment]
fixed in https://github.com/odoo/odoo/commit/fd477f3f6d331355b5667a12b43d1c4a110b7e21
