### ISSUE TITLE
[8.0] Consistent tax and price application (POS + Webshop + other ERP Workflows) - Tax (Included/Excluded)

### ISSUE THREAD

**Issue by wtaferner** [odoo/odoo#6275]
## Impacted versions:

8.0 and above
## Steps to reproduce:
- Create a product with a sale price 10 and assign a tax T1 with 20% where the tax is included
- Assign a standard or no fiscal position to the public user
- Create a fiscal position P1 where you map tax T1 to tax T2 where the only difference is that the tax is not included anymore (B2C > B2B)
- Go to the shop as public/anonymous user and add the product to your shopping cart (Use Case 1)
- Go to the shop as authenticated user/customer with a fiscal position P1 and add the same product to your shopping cart (Use Case 2)
## Current behavior:
- Use Case 1 does have a total of 10 including tax (8,33 + 1,67 [T1] - which is correct)
- Use Case 2 does have a total of 12 (10 + 2 [T2] - which should not happen as the standard tax on the product is T1 and the sale price is related to T1, so T1 != T2 !!!)
## Expected behavior:
- Price computation does respect the sale price in correlation to its standard/original taxes. 
- Use Case 2: 10 / 1,2 = 8,33 as mapped unit price derived from product sale price and therefore T1 = T2 for the two use cases.
- Extra Use Case 3: Mapping from tax included to tax included tax: 10 / 1,2 \* 1,2 = 10

At least this should be fixed for the online shop where it is all about correct communication of prices in the first place. Showstopper for all mixed online shop approaches (B2B + B2C)

@qdp-odoo 
What do you think?

**Comment by wtaferner** [comment]
Ok guys,
There is exactly one setting which is working properly for the webshop, but it does not work for the point of sale in the same instance. So, still it is a bug which needs to be fixed in an ERP scope which hopefully will happen in v9(!!!) at the latest and not only in v10 or v11.

Configuration which works now for the webshop (as far as I tested it)!
**Sale price:** 8,33 (=net price)
**Product Tax:** Tax excluded
**Pricelist for B2C customers:** Sale price + Tax
**Product Tax Mapping (B2C):** Tax included

**Fiscal Position for Public User:** B2C customers)
**For all B2B customers choose the standard pricelist.**

Based on this the sale order and the invoice should be fine as far as I know.

The only problem (webshop order) is in case you start off as an anonymous user and add some items to the sale order and later identify as B2B customer…which could be probably done manually in the backend…there you would have to switch the fiscal position which does update the taxes BUT does not touch the unit prices as they could have been changed manually (at least a warning like we have it onchange of the pricelist would be good as a helper and even better we could find out by computation if the price was changed manually and only do not touch them in case it was)

For the **Point of Sale** it does not work at all as the quick bill and therefore the document for the customer does not work as the fiscal position is not taken into account the same way as it is on the webshop. The invoice workflow might work in some sort but probably is also a weird solution which would need fixes before working smoothly with one configuration.

This is really tricky and only works based on an experienced workaround for some parts but not the whole ERP, so I hope that this will be fixed at least in the future (master v9) and in a very **SIMPLE** way (please put your heads together and define a strategic and awesome way…don’t know if it was on the roadmap for the v9 accounting stuff, but PUT it there as a TOP PRIORITY). I would assume that it is the best to ALWAYS define the price on the product NET (or define if it is net or brut) and based on this there should be a way to apply all use cases which might happen (POS + Webshop + Normal workflows).

Of course, I would appreciate an earlier resolving or improvement of this issue as it is annoying that nobody was thinking or forcing solutions about the whole picture at the time of a first implementation (Odoo was right from the start an ERP not a shop nor just a point of sale or an invoice tool).

Best regards,
Wolfgang

OPW-632653

@qdp-odoo @odony @beledouxdenis @antonylesuisse @fvdsn

**Comment by wtaferner** [comment]
Just to give others an overview about the discussion and make it possible to join, I post here the officially suggested solutions (Thibaud Dubuisson) and some comments about it.
> - The B to C with an external tax. For example in your case put 8,33 as sale price and the tax not included. Then in B to B, just don't put a tax. This configuration is simplest but has a negative side : the prices will be without tax on the ecommerce. 

Almost, but as it is only a half-way solution it is not a solution...at least this approach + modifications made it somehow possible for the webshop (see above)

> If you want them included, you can
> - Configure the B to C with a tax included, then you have to link a pricelist with a different sale price (8,33 instead of 10 in your case) for the specific products linked to the customers in B to B. That way, the ecommerce will be tax included for public users (B to C) and once a customer B to B is logged, he will see the price without taxes

This does not work as you can see on the screenshot (B2B view) - it is not a discount...it should be a net price...
![b2b_with_pricelist](https://cloud.githubusercontent.com/assets/362478/7175056/88b1a9be-e410-11e4-9684-ac36d51c15e6.jpg)

Does anyone have a configuration which works for all use cases (based on official modules)?

**Comment by jholze** [comment]
:+1:

**Comment by wtaferner** [comment]
This issue was classified by Odoo SA as a missing feature and is marked to be solved in v9 on the internal roadmap (as told by Thibaud), so I will keep it open as an issue and reference and hope that the solution for v9 will be outstanding and smart. 

Hopefully I can close it soon after the release of v9...

**Comment by wtaferner** [comment]
Jens (@jholze), as Markus (@OSguard) asked me yesterday about the B2C/B2B module/approach I was talking with him and some others on OCA venue before Odoo Experience, as they would like to see if they might use it, I finally put up the modules (https://github.com/wt-io-it/odoo-addons) - not yet ready for the OCA, but if you are interested, just take a look and feel free to give feedback...it works quite well for my customer...of course it is not perfect, but should help to make it possible to have both B2B + B2C in one instance.
