### ISSUE TITLE
Qweb reports, two reports with same template but different paper size

### ISSUE THREAD

**Issue by agb80** [odoo/odoo#6277]
I'm trying to create two versions for invoice reports, the view is exactly the same for both versions, but the paper size is different, one report is intended to be printed on A4 paper size and the other on A5.

The problem is that Odoo always print both reports with the same paper size.

**Comment by sle-odoo** [comment]
The `paperformat_id` field on `ir.actions.report.xml` is meant to solve your usecase. Please define multiple paper format, create a new ir.actions.report.xml for the second report (using the same template) and define on the second your new paperformat.

I'm closing this as it seems to be working on 8.0.
