### ISSUE TITLE
V12 Website - blog cover images 403 status

### ISSUE THREAD

**Issue by zozolpl** [odoo/odoo#62773]
Impacted versions: 12

Steps to reproduce: Open website editor in front end, add Feature Latest posts - big images and set some images.

Current behavior: Showing images correctly, but slows done website loading with 403 status

Expected behavior: Load images with 2xx or 3xx status

Video/Screenshot link (optional):
![network](https://user-images.githubusercontent.com/23475876/100924141-84c8c180-34e0-11eb-901b-844cad997bea.png)

Hello, this 4 images are slowing website loading a lot. When I try to access those images by path with ?access_token=xxx Im getting 403 as it is also on screen. 
When I delete the ?access_token=xx from URL it is showing corectly. 
On website those images are visible, but need to wait for load them. Also CDN can not cache it because of 403. 
Im guessing it is permission issue, but can not figure it out.

**Comment by JKE-be** [comment]
hello @zozolpl 

Can you reproduce it on runbot ? 

thanks
