### ISSUE TITLE
[12.0] Error with cash basis get wrong paid amount and affects DIOT report

### ISSUE THREAD

**Issue by alan196** [odoo/odoo#62779]
Impacted versions:
- 12.0

Configuration required

- Install Mexican reports.
- Configure cash basis accounting.
- Configure decimal accuracy for product price to 6 decimals
- Configure decimal accuracy for a unit of measure of 4 decimals.
- Configure the costing method to FIFO
- Configure Inventory Valuation to Automated and define accounts for stock valuation.

Steps to reproduce:

- Create a Purchase Order for a stock product with quantity 1,262.84 and price unit of 10.37.
- Confirm the Purchase Order.
- Receive product for 1,262.835
- Create the vendor bill from the purchase order for 1,262.84 and price unit of 10.37.
- Validate the vendor bill and pay it.

What is the current behavior that you observe?

- The cash basis journal entry is created with an incorrect amount of 0.05 of Base Tax Received Account.

What would be your expected behavior in this case?

- The cash basis journal entry must be created with the amount paid of 13095.65 of Base Tax Received Account

I replicated this issue in a runbot instance of Odoo 12.0 https://5249917-12-0.runbot51.odoo.com/web#home

I recorded a video where I replicate the issue in Runbot.

https://youtu.be/BSjYHOGIfwU

This is a very important and urgent issue as the DIOT report is a legal report used to report taxes to the government and is generating an issue reporting less paid taxes and this could generate a fine or a legal problem for the company.

OPW 2411516

**Comment by alan196** [comment]
@luistorresm @hbto @moylop260 @nhomar are you aware of this issue??

**Comment by hbto** [comment]
@alan196 Thanks for Highlighting this issue I wasn't aware of this case.

I have check on your same DB and I have created a Video and I have make some suggestions.

https://youtu.be/C0RmWOqjOCQ

Regretful suggestion
-

This regretful suggestion is a workaround while this bug is fixed.

- Make the transitory (stock_in / stock_out) accounts in the Product Categories non-reconciliable.

Regards.

**Comment by hbto** [comment]
Hello Odoo Guys there have been any progress on fixing this issue.

Regards.

**Comment by vava-odoo** [comment]
Fixed with https://github.com/odoo/odoo/pull/63738
