### ISSUE TITLE
how to connect local zktecho biometric (F19) device with odoo 10 installed in cloud server 

### ISSUE THREAD

**Issue by abhishekms123** [odoo/odoo#62783]
Anyone please give me proper steps for connecting a local biometric device with the cloud server of odoo.

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
