### ISSUE TITLE
[master] KanbanView Can not be loaded in js asset mode

### ISSUE THREAD

**Issue by synee** [odoo/odoo#6278]
In Asset mode, when i use the code blow, i cannot load KanbanView.So I cannot load the kanban page in browser.

``` javascript
KanbanView = core.view_register.get("KanbanView");
```

**Comment by synee** [comment]
In Asset mode, when i use the code blow, i cannot load KanbanView.So I cannot load the kanban page in browser.
```javascript
KanbanView = core.view_register.get("KanbanView");
```

**Comment by Yenthe666** [comment]
Hi @synee,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
