### ISSUE TITLE
Values returned by old API on_change are not available for new API onchange

### ISSUE THREAD

**Issue by pedrobaeza** [odoo/odoo#6279]
I have this case (due to inheritance of an old API style on_change of the core):

```
    @api.multi
    def product_id_change(...)
        ...
        res['value']['x'] = ...

    @api.onchange('x')
    def onchange(self):
        print self.x
```

When using the value in the new onchange, `self.x` doesn't contain the value written in the old style on_change, but both methods are triggered.

@rco-odoo, another task for you :wink:

**Comment by digitalsatori** [comment]
I confirm this issue.

I'm trying to set up an `onchange` method on the `team_id` of `crm_lead` obj using the new API.
old API onchange method `crm_lead.on_change_user` in the crm module did triggered , we can see the team_id on the screen, but in my onchange method `self.team_id` has no value

**Comment by pedrobaeza** [comment]
Any news on this?

**Comment by pedrobaeza** [comment]
Fortunately on v10 there's no old API, and we have moved almost everything, so I close it although is not solved.
