### ISSUE TITLE
Wrong currency symbol used for LSL

### ISSUE THREAD

**Issue by thizzie** [odoo/odoo#62807]
Impacted versions: All

Steps to reproduce: Go to "Invoicing Settings" and view the LSL (Lesotho Loti) symbol under currencies

Current behavior: The symbol is listed as 'L'

Expected behavior: The symbol should be listed as 'M'

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
@mart-e are you the suitable for this?

@thizzie do you have any link where we can check that the currency symbol is that one?

**Comment by thizzie** [comment]
@pedrobaeza No problem. Here's a article from one of Lesotho's most popular newspapers 'The Lesotho Times' showing how currency is quoted: http://lestimes.com/businessman-xie-in-m27-million-scandal/

Here is the 2019/20 annual report from the country's tax authority the Lesotho Revenue Authority (LRA): http://lra.org.ls/sites/default/files/2020-10/LRA%20Integrated%20Annual%20Report%202019.pdf
For quick reference, you can check page 15 for how the figures are written.

**Comment by Yenthe666** [comment]
@mart-e

**Comment by mart-e** [comment]
Thank you for the report, fix in progress at #65633

**Comment by Yenthe666** [comment]
Fixed in https://github.com/odoo/odoo/pull/65633/commits/f4b99e972aa3224332d44eb0fd8ec36d78a4c7b2 - forward ports are in progress so will soon be fixed in all versions.

**Comment by mart-e** [comment]
@Yenthe666 thanks for the followup but don't worry, it was going to be closed automatically once the code is merged in 14.0 ;-)

**Comment by Yenthe666** [comment]
I was excited 🙊
