### ISSUE TITLE
Invoice form cannot be submitted; no access to journal list

### ISSUE THREAD

**Issue by tfelice** [odoo/odoo#6280]
I upgraded a working Odoo install with several databases to 8.0.20150411.  I ran a script that executed "/usr/bin/odoo.py --config /etc/odoo/openerp-server.conf -d $DATABASE -u all" for each DATABASE.

Then I found an identical problem in all of the existing databases and also replicated it in a database that I created after the upgrade.  On the invoice form, there are no choices in the journal drop-down list.  The default account shown below the journal field is Accounts Payable when it should be Accounts Receivable.  If I manually enter "Sales Journal" into the journal field and try to submit, I get an error complaining that two fields are invalid: Journal and Currency.

I restored the server VM from a snapshot made just before the update, and all works again.

**Comment by Yenthe666** [comment]
Hi @tfelice,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
