### ISSUE TITLE
Webbuilder Internal server error on create blogpost

### ISSUE THREAD

**Issue by exidoncom** [odoo/odoo#6282]
**Webbuilder Internal server error on create blogpost**

Impacted versions:
- 8.0

Steps to reproduce:
1. make sure, webbuilder and blog is installed, maybe set main language of website to spanish
2. login as first real name user with manager right to webbuilder module (users standard language english, but switching also to spanish within website)
3. realize that there is still login menu button after logged-in username. 
   1. Try to create first blog entry

Current behavior:
-  All function menu entries point to actual page url, or if they appear after refresh, after selecting predefined blog to create a new entry for, server throws 500 internal server error, finishing with a note, that there is an issue with permissions

Expected behavior:
- Create new post
  ![internal server error](https://cloud.githubusercontent.com/assets/7328993/7109411/d139d95a-e162-11e4-8657-10926f6867fe.png)

**Comment by AlSayedGamal** [comment]
Can you change the language to English and reproduce the issue again please.
Thanks.

**Comment by exidoncom** [comment]
If I put /en_US to see the menu in English and select create blog post, I get the same error. If I go to Website settings in order to set default language of website to english, i still can reproduce the error.

**Comment by noamix** [comment]
same here,any workaround? using Espanish /Espàñol (AR)

**Comment by Yenthe666** [comment]
Hi @exidoncom,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
