### ISSUE TITLE
"Unicity based on" is meaningless on Marketing Automation module

### ISSUE THREAD

**Issue by ThanhICSC** [odoo/odoo#62850]
Impacted versions:
13, 14
Steps to reproduce:
Click on the menu Marketing Automation / Campaigns 
Click on the Create button
Current behavior:
Show form view with Unicity based on field
And "Unicity based on" is meaningless
Expected behavior:
It's should be like version 12 is "Unique Field" or "Unity based on" or "Unique based on"

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
If I check the translation of "Unicity", it seems to be correct. Why do you say is meaningless?

**Comment by ThanhICSC** [comment]
Hi Pedro M. Baeza,

Please let me know the meaning of "Unicity" in English. Thank you so much

**Comment by pedrobaeza** [comment]
https://www.merriam-webster.com/dictionary/unicity

**Comment by ThanhICSC** [comment]
Thank you so much. So please close this report. Sorry for my mistake

Vào Th 7, 5 thg 12, 2020 lúc 16:39 Pedro M. Baeza <notifications@github.com>
đã viết:

**Comment by murayajoe** [comment]
Thanks . Implementation will be easier
