### ISSUE TITLE
[12][13][14] fetchmail: Infinite loop with POP

### ISSUE THREAD

**Issue by ypapouin** [odoo/odoo#62856]
If your catchall account contains unroutable e-mails, they will be kept on the server and the `failed` counter is increased.
But after some times, you will be in a state where you will have more than `MAX_POP_MESSAGES` unroutable e-mails.
So `pop_server.dele(num)` will never be called and the `num_messages` counter will stay the same that means that the `break` will never be called: The cron task will stay locked in an infinite loop.

https://github.com/odoo/odoo/blob/338f8d843832c339c52c00c7f4c41b5ab2d696ed/addons/fetchmail/models/fetchmail.py#L195-L213

Note that you don't have this issue when using IMAP since the `Seen` flag is set after the exception catch

**Comment by Yenthe666** [comment]
@tde-banana-odoo

**Comment by nle-odoo** [comment]
Hi

The loop should be fixed by the change in https://github.com/odoo/odoo/commit/72cd8d0769097b21bbf94a34496888617058cb1b as far as I can tell.

Thanks for your report.
