### ISSUE TITLE
Call external source as QR-Code Provider because odoo doesnt support error_correction of H

### ISSUE THREAD

**Issue by TheCoderLife** [odoo/odoo#62867]
Impacted versions: Odoo 13.0-20201112 (Community Edition) 

Steps to reproduce: Call external source as qr code provider - example: <img t-att-src="'https://api.qrserver.com/v1/create-qr-code/?data=%s&amp;size=%sx%s&amp;ecc=%s' % (move_line.lot_id.barcode_lot_add, 600, 600, 'H')" style="width:100%;" alt="Barcode"/>

I tried to deploy a flask server which is also sends back a generated QR Code - there is the same problem, so its not because of an external source. 

i saw in the serverlogs the requests came to fast inside, i have feeling like odoo is not waiting for the response of the first request. 

Is there something i can do like a time.sleep(2) where the requests are sent? If yes on which place in the code. 

Current behavior: qr-codes are just coming for every second/third requested items back.

Expected behavior: it should come for every item a qr-code back. 

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
