### ISSUE TITLE
[14.0] Invoice with lot number and expiry date

### ISSUE THREAD

**Issue by aitalinassim** [odoo/odoo#62877]
**Impacted versions:**
14.0

**Steps to reproduce:**
Login in runbot
Goto settings
In the search box type lot
check the box Display Lots & Serial Numbers on Invoices
Click on save
Goto sales
Create a new product:
-- product type: Storable
-- Inventory / tracking: by lots
Save
Purchase any quantity and introduce date and exp. date
Now Sell a quantity and chose the purchased lot
Create invoice
Print the invoice

**Current behavior:**
No lot number or expiry date

**Expected behavior:**
lot number and exp. date should be visible on the printed invoice

**Comment by pedrobaeza** [comment]
The lot can be printed if you choose the proper option, but expiry date is a feature that is not implemented, and it's not required as well in most sectors.

**Comment by aitalinassim** [comment]
OK, so it is not an issue !?
Can you show the proper option please  ?

**Comment by pedrobaeza** [comment]
![Selección_002](https://user-images.githubusercontent.com/7165771/101161064-49d5a380-3630-11eb-9c77-b922431b7a02.png)

**Comment by aitalinassim** [comment]
It was done, but even ike that the lot is not shown in the invoice.
Please check again.

**Comment by pedrobaeza** [comment]
This is working by default, so unless you show a video and reproducible steps in runbot, it shouldn't fail and it's assumed this is not a bug.
