### ISSUE TITLE
[13] Deactivating "Manufacturing" -> "Work Orders" (group_mrp_routings) can have unexpected behaviour

### ISSUE THREAD

**Issue by axxelia-dev-fr** [odoo/odoo#62884]
Impacted versions: Odoo 13

Steps to reproduce: 

Activate "Work Orders" for "Manufacturing" (group_mrp_routings). Now create a routing with at least two steps. Assign this routing to the BoM of a product. Creating new manufacturing orders now works as expected and uses the associated and displayed routing.

Now deactivate "Work Orders" for "Manufacturing" (group_mrp_routings). And create a new manufacturing order.

Current behavior:

Even after group_mrp_routings has been deactivated the new manufacturing order still uses the routing which was previously assigned to the BoM. But now it is not displayed on the form anymore.

Expected behavior:

After deactivating group_mrp_routings a new manufacturing order should not take into account the routing, even if it was previously assigned.

Video/Screenshot link (optional):

**Comment by amoyaux** [comment]
Dear,

Thanks for reporting. Currently, I recommend you to enable the settings again and archive all the routing linked to the company then disable the settings again.

Since there is a workaround, we won't do a bugfix for it. However we take it as a feedback and we will do it on master version.

**Comment by Yenthe666** [comment]
As it won't be fixed in stable & there is a feedback for the master there is nothing left to do I guess.
