### ISSUE TITLE
Odoo Master : POS doesnot load when install "pos_restaurant" module

### ISSUE THREAD

**Issue by parikshitbapat** [odoo/odoo#6292]
POS does not load when install "pos_restaurant" module. It did not work even if creates fresh database.

**Comment by iceship** [comment]
I found windows work great, but apple product(mac, ios) didn't work.

**Comment by parikshitbapat** [comment]
DO you mena in windows it works ?? I am installing on ubuntu 14.04 ?

**Comment by jaymaniar** [comment]
Issue: Odoo POS module does not operate correctly on iPad web browser.


Test device:
iPad Air
iOS 8.3 (12F69)

Error Description:-
1. odoo version: 66800-master-4bef17 on runbot6.odoo.com
Blank black screen when launching "Point of Sale" module in both Safari and Chrome browser.
(Chrome browser app version 42.0.2311.47, updated 17 Apr 2015)

2. odoo version: 69313-8-0-3e14a4 on runbot.odoo.com
"Point of Sale" module loaded and open up successfully in Safari and Chrome browser.
However, in Safari, after "Add to Home Screen", when click on icon to launch full screen mode,
will show error
"Not Found. The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."

**Comment by willylim** [comment]
Test device:
iPad Air
iOS 8.3 (12F69)

Error Description:-
odoo version: 66800-master-4bef17 on runbot6.odoo.com
Blank black screen when launching "Point of Sale" module in both Safari and Chrome browser.
(Chrome browser app version 42.0.2311.47, updated 17 Apr 2015)

![image](https://cloud.githubusercontent.com/assets/12483798/7670674/a414a010-fce0-11e4-9508-c0fc8a3dad93.png)

**Comment by willylim** [comment]
Still no one can fix this bug?

**Comment by Yenthe666** [comment]
Hi @parikshitbapat,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
