### ISSUE TITLE
[12] (feature request) move contact to different company

### ISSUE THREAD

**Issue by f1-outsourcing** [odoo/odoo#62922]
It would be nice in a multi company environment to have an option to move a contact from one company to another.

**Comment by Yenthe666** [comment]
Uhh just change the company/companies on the contact form? This is already available by default.

**Comment by f1-outsourcing** [comment]
I mean this company

![20201207-155011-192 168 x x_8069](https://user-images.githubusercontent.com/13450219/101366073-cd97c600-38a4-11eb-98f0-9d0f148427f9.png)

**Comment by pedrobaeza** [comment]
- Be in company A.
- Empty the field "Company".
- Move to company B.
- Fill the field "Company" with company B.

**Comment by f1-outsourcing** [comment]
Yes a bit confusing but I found it at "Sales & Purchases" there you can change also a company.
