### ISSUE TITLE
V14 CE, website: Google Maps Snippet disappearing

### ISSUE THREAD

**Issue by NICO-SOLUTIONS** [odoo/odoo#62932]
Impacted versions:
- V14 CE

Steps to reproduce:
- Add the google Maps snippet to your webseite

Current behavior:
- When dragging the map snippet to the page, everythig seem to be ok. But as soon as you select the map snippet and try to configure the settings, the snippet disappears completly.

Expected behavior:
- The maps snippet should not disappear and should be configurable.

**Comment by rk-aix** [comment]
Same here, new api code generated and inserted in settings. In web editor, click on saved snippet to configure, it disappears directly...
Odoo V14 (git / December 5th)

**Comment by rk-aix** [comment]
Ok. folks - tricky fault - inspected dom and network, found that Google Java Api is not enough to be activated, it seems mandatory to enable also Google Api Places.
After enabling this in Google Business Account everything works fine...

**Comment by Yenthe666** [comment]
@NICO-SOLUTIONS could you verify if you have the same issue as @rk-aix please?
CC @JKE-be

**Comment by NICO-SOLUTIONS** [comment]
@Yenthe666 i confirm the observations of @rk-aix herewith. 
Activating the Places API solved the problem! 

Thumbs up!

**Comment by Yenthe666** [comment]
Thanks for the feedback guys! :)

**Comment by RubenLauwaert** [comment]
Hey, could someone specify which Google API's one should enable to prevent this error from happening ? Right now I have the following api's enabled but the bug described above is still active:
- Places API
- Maps JavaScript API

Thanks in advance :)

**Comment by NICO-SOLUTIONS** [comment]
Did you enable the billing?
In addition i have enabled the static API, but from my point of view this is more related to the contact form map.

**Comment by RubenLauwaert** [comment]
> Did you enable the billing?
> In addition i have enabled the static API, but from my point of view this is more related to the contact form map.

Yes, billing is enabled and the static API is also enabled, but the issue is still there.

**Comment by JKE-be** [comment]
Hello @RubenLauwaert 

Just tested now on runbot 14.0 and it works as expected.
Reminder to make it work:

need to enable billing on your account
need to enable "Maps JavaScript API" to have the small cart into the right column
need to enable "Maps JavaScript API" and "Place API" to use the "google maps" snippets

You can enable 3 together.

Don't forget to restrict your keys, if you do it by "HTTP referrers (web-sites)" method, be aware that you need to use wildcard in websites restrictions. E.g.: `https://7253460-14-0-all.runbot33.odoo.com/*`, if you forget the `/*` it will not works.

Open your browser console, to see the error if it doesn't work and provide your 'log' and 'config screenshot'

**Comment by RubenLauwaert** [comment]
I made a mistake with the API Key authorization. This response made me
solve my issue.
Big thanks !

Op ma 19 apr. 2021 om 14:43 schreef JKE-be ***@***.***>:
