### ISSUE TITLE
How can i do barcode integration to openerp7 for the modules Sales nad Purchase not for Point of Sale

### ISSUE THREAD

**Issue by bvarjun** [odoo/odoo#6294]
Can anyone help me on this?

**Comment by Yenthe666** [comment]
Hi @bvarjun,

Thank you for your question. Please do ask them on the official help forums (odoo.com/help) as the Github tracker is only for bugs in the official code.
As for your question: If you place your cursor in the text field you can scan. If you want an advanced barcode interface you'll need to add your own custom development.

Regards,
Yenthe
