### ISSUE TITLE
Datetime field going back by 1 when using date widget

### ISSUE THREAD

**Issue by PackSmartInc** [odoo/odoo#62962]
**Impacted versions:**
Reproduced on v12 and v15. Possibly all versions

**Steps to reproduce:**
1. Create a datatime field in a form with 'date' as widget.
2. Go to the form, enter a date in above field
3. Click Save

**Current behavior:** 
Odoo will save the datetime file as the day before
e.g. if you enter 1/1/2021 and save, the field will save as 12/31/2020

**Comment by Yenthe666** [comment]
1. There is no V15, the latest is v14.
2. Did you configure your timezone on the user?
3. Can you reproduce it on runbot.odoo.com?

**Comment by pedrobaeza** [comment]
That something normal as the date doesn't contain hours, and thus 0:00 is considered for the time, that translated through the timezone of the user, leads to that datetime in previous day. For example, for UTC+2, you'll get N-1 22:00.

Closing as expected behavior with that combination.

**Comment by PackSmartInc** [comment]
@Yenthe666 
1. Sorry, I reproduce it on demo.odoo.com which I thought is v15
2. Yes users are in Canada/Eastern

@pedrobaeza 
Thanks for the explanation but what could be the solution for users in this case?

**Comment by pedrobaeza** [comment]
You can have a computed date field with inverse that processes for storing the desired datetime final value, and also displaying the desired one.
