### ISSUE TITLE
[7.0][8.0][BUG] Not able to print Quarter VAT declaration with monthly fiscal period

### ISSUE THREAD

**Issue by jlaloux** [odoo/odoo#6297]
Here is my case,

My fiscal period are configured with monthly fiscal periods:
![image](https://cloud.githubusercontent.com/assets/7678583/7115834/5476d564-e1ec-11e4-9630-2a40b34bae11.png)

But if i want to generate a Belgian VAT Declaration, I can't do it for quarters. I can select only one period. So if don't configure my fiscal period as a quarter period, i'm not able to get a quarter period declaration.
![image](https://cloud.githubusercontent.com/assets/7678583/7115806/1aad4f48-e1ec-11e4-8477-fb9b9793aa59.png)

But if i look for the Partner VAT Intra. Here i will be able to select more than one period so i'm able to print a quarter report even if i configure my fiscal positions monthly.
![image](https://cloud.githubusercontent.com/assets/7678583/7115820/3b95c1d6-e1ec-11e4-825d-3a56dbb33f51.png)

For me, the comportment should be identical and we should be able to select more than one period in the Belgian VAT Declaration because for now it's impossible to generate a Quarter VAT Declaration with a monthly fiscal position configuration.

**Comment by Yenthe666** [comment]
Hi @jlaloux ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
