### ISSUE TITLE
Module Mercado Pago Does Not Work

### ISSUE THREAD

**Issue by hcortez-bit** [odoo/odoo#62985]
Impacted versions: Odoo Help Forums

Steps to reproduce: i have unistalled the module and reinstalled from here [Mercado Pago](https://github.com/ctmil/payment_mercadopago/)

Current behavior: the error persists

Expected behavior: it should redirect to continue with the payment

Video/Screenshot link (optional): 
**Server Error:**
**We are not able to redirect you to the payment form. 'payment.acquirer' object has no attribute 'state'**

**Comment by Elkasitu** [comment]
@hcortez-bit we don't offer support for issues caused by third-party modules, bring it up with the module's maintainer but from looking at their repo a) they don't really offer much support either and b) you're not the only one having trouble getting it to work
