### ISSUE TITLE
In a multi-company environment are seen the teams of all companies

### ISSUE THREAD

**Issue by isalvat** [odoo/odoo#6303]
Hi,

Thanks for such a great piece of software.

The bug I have detected is that in a multi-company configuration the sales team does not have the company are related to, so users from any company can see the general data  of every team present in th databse.

This means than a team manager from one company can change many values (not all of them) of teams creates by users of other company.

**Comment by Yenthe666** [comment]
Hi @isalvat,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
