### ISSUE TITLE
[BUG][13.0] sale_coupon: cannot set coupons to 'expired' state when archiving coupon programs

### ISSUE THREAD

**Issue by khaihoan123** [odoo/odoo#63061]
Impacted versions: 13.0

Steps to reproduce:
- Create a coupon programs
- generate coupons
- archive coupon program
- check state of coupons
Current behavior:
when archiving coupon programs, the state of generated coupons still is 'valid' 
Expected behavior:
when archiving coupon programs, the state of generated coupons will be set to 'valid' 
Video/Screenshot link (optional):
https://drive.google.com/file/d/1HFRd0cQ7R_SlHCOcMe2z6cgzOIPoCOFL/view?usp=sharing
Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
Closing as there a PR solving it.
