### ISSUE TITLE
[8.0,7.0] Layout of Calendar settings

### ISSUE THREAD

**Issue by ghost** [odoo/odoo#6307]
**Layout of Calendar settings**

Impacted versions:

 - 8.0, 7.0

Current behavior:

 - The menu is in Settings -> Technical -> Calendar

Expected behavior:

 - I think it would be in Messaging -> Configuration (not exist yet)

**Comment by sle-odoo** [comment]
We changed it in 9.0 but please note that you can customize the menu the way you want in every Odoo version.

Regards
