### ISSUE TITLE
[FR] Add TVA Autoliquidation

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#63082]
Can you add the TVA Autoliquidation in standard in Odoo ?

Vente :
![image](https://user-images.githubusercontent.com/16716992/101618871-d27a8800-3a12-11eb-856a-7cdc5d6eebaf.png)
![image](https://user-images.githubusercontent.com/16716992/101618901-da3a2c80-3a12-11eb-8f7b-57ed277a03a3.png)

Achat
![image](https://user-images.githubusercontent.com/16716992/101618946-e7efb200-3a12-11eb-8a67-4b238a5cbcec.png)
![image](https://user-images.githubusercontent.com/16716992/101618980-ef16c000-3a12-11eb-88e3-b8d76621b48e.png)

Position fiscale
![image](https://user-images.githubusercontent.com/16716992/101619156-29805d00-3a13-11eb-9c40-219cb6557807.png)

@alexis-via 
@oco-odoo 

Thank !

**Comment by oco-odoo** [comment]
@tsb-odoo Any opinion on this?
