### ISSUE TITLE
[master] issue with decorator cr_uid_id*

### ISSUE THREAD

**Issue by rgo-odoo** [odoo/odoo#6309]
@rco-odoo 

Please find the modules to reproduce the situation at https://drive.google.com/file/d/0B8BReoCdAXSca2syaUJmR1dqaFk/view?usp=sharing (where one module is written in old api and the other is in new api, installing both module will make you face the issue).

Issue description:
==============
If I have some method defined in OLD API with parameters "cr, uid, id" or "cr, uid, id, context" which returns a list(say [1,2,3,4]) and if I call that method using new api then it returns the result as list of list([[1,2,3,4]]).

So, in new api, the actual result of such method is stored in the first element of that method's return value(list). Hence, it needs to be accessed as return_result[0] to access the actual result.

For example, for below code,

result = self.foo(cr, uid, id, context)
#OUTPUT: result = [1,2,3,4]

will now has to be written like,

newapi = self.foo()
#OUTPUT: newapi = [[1,2,3,4]]
result = newapi[0]

I think [1] and [2] should be coded like(return actual result of the 'method' and not inside the list),

result = method(self._model, cr, uid, self.id, *args, **kwargs) #no need to iterate in self.ids as it's going to have 1 record(id) only.

Similar thing has been done at [3] where the actual result of compute(...) was accessed from 0th index in new api call and direct result in call to old api of compute(...) at [4]

So, is it a bug or intentional behavior ?

[1] https://github.com/odoo/odoo/blob/master/openerp/api.py#L477
[2] https://github.com/odoo/odoo/blob/master/openerp/api.py#L503
[3] https://github.com/odoo/odoo/blob/master/addons/account/account_invoice.py#L503
[4] https://github.com/odoo/odoo/blob/master/addons/account/account.py#L2329

**Comment by rco-odoo** [comment]
The behavior is intensional, and the motivation behind it comes from method `copy`. In the old API, copy returns a record id. In the new API, its returns a list of record ids... that is automatically converted to a recordset using `browse`. Therefore `records.copy()` duplicates a recordset.
