### ISSUE TITLE
[8.0] Picking transfer wizard operation destinations differ from initial move

### ISSUE THREAD

**Issue by komsas** [odoo/odoo#6310]
Impacted versions:

- Tested on the latest Odoo 8.0.

Steps to reproduce::

- Make few stock moves in the picking with different destination locations.
- Push "Transfer" button.
- Destination locations are different from stock move destination locations.

Excepted behavior:

- Destination location should match.

Please check screenshot.

![ready transfers - odoo](https://cloud.githubusercontent.com/assets/213811/7135464/b1917498-e2af-11e4-8198-1b63f3a58cde.png)

**Comment by jco-odoo** [comment]
This has been done on purpose.  One picking should be from one parent location (you could see it as a zone) to another parent location.  Pickings are not meant anymore (except scrapped moves) to do whatever.  It is a little bit unclear now as you can change locations in the stock moves like this right now and that will be improved in a next version.

**Comment by komsas** [comment]
@jco-odoo thanks for explanations. In such case why nobody added constrain or raised exception when locations are different?

**Comment by intero-technologies** [comment]
I understand this way, when there is Recipt in 3 steps. So coming into warehouse, and then transfer to shelf or another final place. But what is with receipt in 1 step? Here it shouldn't ask for zones, because this isn't needed.

@jco-odoo could you clarify me, how i should book incoming products? Incoming goes to /WH/Stock but my destination is WH/Stock/F01-02. How i have to do it right?

**Comment by intero-chz** [comment]
@jco-odoo i don't get the logic behind this.

A simple example:

warehouse structure: 
WH/Stock
WH/Stock/px
WH/Stock/py
WH/Stock/pz

products have fixed locations

now we get a receipt with
2x productx
1x producty
1x productz

How do i transfer these products into their fixed locations? Will i end up with 3 different pickings?

**Comment by ztsiklauri** [comment]
Watching

**Comment by jco-odoo** [comment]
You use the putaway strategies.
