### ISSUE TITLE
[BUG 7.0, 8.0] Recursive structure in Bill of Materials (mrp module)

### ISSUE THREAD

**Issue by chesucr** [odoo/odoo#6313]
MRP Module

When I build a bill of materials (mrp.bom), a product template (product_tmpl_id) is made of some materials (mrp.bom.line). The product template of these materials can't coincide with the main product template of the bill materials. If not, I get this error when I try to print the report of the structure. It's due to the recursiveness:

```
Uncaught SyntaxError: Unexpected token o
http://localhost:30080/web?debug=#id=45&view_type=form&model=mrp.bom&menu_id=317&action=396:1
```

Example of a wrong Bill of Materials tree. The second Product1 is wrong:

```
Product1
    Product2
    Product3
        Product1
    Producr4
```

Version 7. It validates only one level
Version 8. It doesn't validate anything

**Comment by Yenthe666** [comment]
Hi @chesucr,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
