### ISSUE TITLE
please update `jquery.scrollTo.js`; please remove `jquery.scrollTo-min.js`

### ISSUE THREAD

**Issue by onlyjob** [odoo/odoo#6314]
`addons/web/static/lib/jquery.scrollTo/jquery.scrollTo.js` is quite old: newer version is available:

https://github.com/flesler/jquery.scrollTo/blob/2.1.0/jquery.scrollTo.js

Also please remove minified `jquery.scrollTo-min.js` -- there should be no pre-built binaries in source. 

Thanks.

**Comment by sle-odoo** [comment]
It's not quite old. rev f4c3ecb493abaa6814977fd2e80ff472cb16d2d5 updated to the latest version at the time and the latest version is only one month old. Please note that the minified version is not present anymore in master and cannot be removed from stable.

If you want this library to be updated quickly, feel free to open a pull request against master and double check that the new changes don't break our existing use cases.

I'm closing this as it's not an issue.
Regards

**Comment by onlyjob** [comment]
I see... I did not check master as I was looking into 8.0.0 tarball... Cheers and thanks for quick reply.
