### ISSUE TITLE
[7.0] Upgrade Cost Price of the Product

### ISSUE THREAD

**Issue by carlositurri** [odoo/odoo#6319]
why, when I updated the cost price from the product master data, this operation generates accounting entries for each internal location configured in my company with the same values for each accounting entries, why generates this number of accounting entries? thanks

**Comment by Yenthe666** [comment]
Hi @carlositurri,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 (& Odoo 8) is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
