### ISSUE TITLE
In stock.py (addons/stock), assigning min_date and max_date has a bogus logic

### ISSUE THREAD

**Issue by luismasuelli-trescloud** [odoo/odoo#6321]
Inverse functions, intended for assigning values to max_date and min_date in OpenERP7, have a bogus logic. Let's look at the following code chunks:

addons/stock/stock.py:567

```
def _set_maximum_date(self, cr, uid, ids, name, value, arg, context=None):
    """ Calculates planned date if it is greater than 'value'.
    @param name: Name of field
    @param value: Value of field
    @param arg: User defined argument
    @return: True or False
    """
    if not value:
        return False
    if isinstance(ids, (int, long)):
        ids = [ids]
    for pick in self.browse(cr, uid, ids, context=context):
        sql_str = """update stock_move set
                date_expected='%s'
            where
                picking_id=%d """ % (value, pick.id)
        if pick.max_date:
            sql_str += " and (date_expected='" + pick.max_date + "')"
        cr.execute(sql_str)
    return True
```

Take an example: Assume I have a picking with 4 (four) stock_move entries. Such entries have dates (date_expected) A, B, C, D such that A > B > C > D.

The max_date field would get A as date, when I ask for such value. However, assume I want to assign max_date=E. Such function would be called, and the stock_move (potentially many entries) with date_expected=A would be changed to date_expected=E). There's a problem here:

If E follows the rule: B > E > D, and I assigned max_date=E, when I retrieve the max_date field in a future access, I will get that max_date==B instead of max_date==E.

The exact same problem occurs with min_date if I alter the signs < (lower-than) with > (greater-than).

My suggestion is: alter the chunk

```
            sql_str += " and (date_expected='" + pick.max_date + "')"
```

With:

```
            sql_str += " and (date_expected>='" + min(pick.max_date, value) + "')"
```

And the analogous for the min_date (using "<=" instead of "=", using "max" instead of "min").

**Comment by Yenthe666** [comment]
Hi @luismasuelli-trescloud,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
