### ISSUE TITLE
Bank accounts are not shown (anymore) in bank statements

### ISSUE THREAD

**Issue by avanzella** [odoo/odoo#6322]
After a recent code update, bank accounts are not shown anymore in bank statements.

**Comment by avanzella** [comment]
Any idea about this issue ?

**Comment by Yenthe666** [comment]
Hi @avanzella,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
