### ISSUE TITLE
Error when group by partner invoice created by picking

### ISSUE THREAD

**Issue by luistorresm** [odoo/odoo#6323]
1) Steps to reproduce the issue you have observed

- Create a sale requisition to a partner, this with order_policy = 'picking', and not validate it.
- Create a PO with a line for 1 unit, for other partner to the sale.order, validate it and receive this product.
- Create a new PO to the same supplier of last PO, too with a line for 1 unit, validate it and receive the product, but in this picking you receive 3 units.
Note: This PO must have the invoice control as 'Based on incoming shipment'

Then go to picking operations and create the invoice of this operations with the wizard 'Create Draft Invoices', with the field 'group by partner' active.

Can find a demonstrative video here: 
https://youtu.be/SQYtcVjJw1I

2) The result you observed
I get two invoice for the same partner

I observed that in the second PO, when I receive more product, the picking create a new line, but this line don´t have reference to group of procurement, by this the picking not have value in field 'group_id', then when the method of wizard check partner to pickings to group, this comes to the next function:

https://github.com/odoo/odoo/blob/8.0/addons/sale_stock/sale_stock.py#L420,

in this function, the system search sale.order that have the same procurement group that the picking, and as this picking haven´t the group, If in the DB I have sale without group and with order_policy as picking, the search return this sale order and take the partner of this.

 3) The result you expected 
I expected that only was created a invoice for the 2 pickings.

**Comment by beledouxdenis** [comment]
Hello Luis, 

I am almost sure that this issue is solved in Odoo 8.0 from the below revision:
https://github.com/odoo/odoo/commit/4a7159ca7803ccd679cf613bd862d61bac3038ae

At least, I just tried to reproduce your use case, but couldn't face the issue.

Can you confirm ?

Regards,

**Comment by luistorresm** [comment]
Hello Denis,

Sorry, the commit that you comment me not solve my problem, I was try in
runbot with the commit
https://github.com/odoo/odoo/commit/64fd1dc636eb93a01631facfa7530f6be94b8852,
and the error continue. The video that I add in the Issue I test with the
commit that you said that resolve the bug

Can you check the Issue and see the error?

I generated the next PR to solve this.

https://github.com/odoo/odoo/pull/6325

You can reopen the Issue?

Regards

2015-04-21 8:54 GMT-05:00 Denis Ledoux <notifications@github.com>:

**Comment by nim-odoo** [comment]
Fixed with 01e4b76f656df1ef88b57af511ea28f3e9b6dc1d
