### ISSUE TITLE
[8.0]  duplicate key value violation

### ISSUE THREAD

**Issue by ddfs** [odoo/odoo#6326]
I deleted and re-added 'mail.catchall.alias' from System Parameters panel for testing custom module.
custom module is uninstalled. got the new code base from nightly applied the updates.
and started with odoo server with -u all.

got the following error:

ParseError: "duplicate key value violates unique constraint "ir_config_parameter_key_uniq"
DETAIL:  Key (key)=(mail.catchall.alias) already exists.
" while parsing /opt/odoo-8/openerp/addons/mail/data/mail_data.xml:61, near
<record id="icp_mail_catchall_alias" model="ir.config_parameter">
            <field name="key">mail.catchall.alias</field>
            <field name="value">catchall</field>
        </record>

to continue I had to remove 'mail.catchall.alias' manually from db 

expected: should just ignore if key exists.

**Comment by l-arnold** [comment]
I got the same error by trying to "upgrade" the Base Module.

Seems this would be an inappropriate fix, but I have gone into
/openerp/odoo/addons/mail/data/mail_data.xml and removed

        
        <record id="icp_mail_catchall_alias" model="ir.config_parameter">
            <field name="key">mail.catchall.alias</field>
            <field name="value">catchall</field>
        </record>

No Error yet, but very long process.  Finished the process also.  May have worked.  Gave me a seemingly new "home action" on my one user.

I have a snapshot and can go back to where I was.  Several Access errors were appearing and ref on help.odoo.com

**Comment by Yenthe666** [comment]
Hi @ddfs,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by l-arnold** [comment]
Does this mean that Odoo has pulked the whole 8.0 repository or does it just mean they don't support it anymore for paying customers.

I am assuming the latter.

________________________________

**Comment by litnimax** [comment]
The same issue is wuth Odoo 10.0.
Here is my view:
```
<odoo><data noupdate="1">

    <!-- ZMQ Bus Settings -->
    <record  id="pub_addr" model="ir.config_parameter">
        <field name="key">barrier.pub_addr</field>
        <field name="value">tcp://zmanager:8882</field>
    </record>
</data></odoo>
```
When doing odoo -u barrier I get:
```
ParseError: "duplicate key value violates unique constraint "ir_config_parameter_key_uniq"
DETAIL:  Key (key)=(barrier.pub_addr) already exists.
" while parsing /opt/odoo/local-src/barrier/data/settings_data.xml:4, near
<record forcecreate="1" id="pub_addr" model="ir.config_parameter">
        <field name="key">barrier.pub_addr</field>
        <field name="value">tcp://zmanager:8882</field>
    </record>
```

Actually I am surprised as I expected noupdate="1" to ignore changes.  Current database has another value and the same key but this is how it was supposed to be - initial setup and after that customer changes value and it's not reset on every update.

**Comment by Yenthe666** [comment]
@l-arnold this means there is no longer support for this version but it is still available.
@litnimax `barrier` is not a default Odoo app so this is an issue with your custom development.

**Comment by litnimax** [comment]
Yenthe666, the problem is in algorithm Odoo uses to update records.
It has nothing to do with a particular module.

**Comment by yelizariev** [comment]
Workaround: remove you parameter via ``[[ Settings ]] >> Technical >> Parameters`` before upgrading.
Recommendation for custom modules: use function instead of record, e.g. ``<function model="ir.config_parameter" name="set_param" eval="('auth_signup.allow_uninvited', True)"/> ``
Mor information http://odoo-development.readthedocs.io/en/latest/odoo/models/ir.config_parameter.html

**Comment by litnimax** [comment]
Thanks! YML solution is the only acceptable.
P.S. But  anyway, how it is possible? How noupdate="1" tries to overwrite a record with same same xmlid??

**Comment by yelizariev** [comment]
YML support is removed in master, so it's recommended to avoid that

**Comment by yelizariev** [comment]
Instead of yaml you can create method in python and call it via ``<function ...`` in xml

**Comment by yelizariev** [comment]
noupdate="1" means that record is not updated **if it already exist**. In you case record with *external id* ``pub_addr`` doesn't exist), but manually created record does exist (without *external id*)

**Comment by litnimax** [comment]
Thanks Ivan!

**Comment by litnimax** [comment]
I also found a solution for me:
```
    <record  forcecreate="0" id="pub_addr" model="ir.config_parameter">
        <field name="key">barrier.pub_addr</field>
        <field name="value">tcp://zmanager:8882</field>
    </record>
```
It is ```forcecreate="0"```.

**Comment by yelizariev** [comment]
[According to code](https://github.com/odoo/odoo/blob/cd48a806ac636806130efcf5c055f73758cb0902/odoo/tools/convert.py#L604) forcecreate means ``# if it doesn't exist and we shouldn't create it, skip it``. So, in your case it seems to be the same as just removing whole node, isn't it?

**Comment by shadab95** [comment]
Can anyone please help me with this issue

ParseError: "duplicate key value violates unique constraint "ir_filters_name_model_uid_unique_action_index"   DETAIL:  Key (lower(name::text), model_id, (COALESCE(user_id, (-1))), (COALESCE(action_id, (-1))))=(sales funnel, sale.report, -1, -1) already exists. " while parsing /opt/odoo10.0/addons/sale/report/sale_report_views.xml:28, near <record id="filter_sale_report_sales_funnel" model="ir.filters">

I don't know why this issue is coming as I haven't done anything in that particular part..Any help wil be greatful
