### ISSUE TITLE
proxy mode not active because of unneeded limitations

### ISSUE THREAD

**Issue by jerzyk** [odoo/odoo#63276]
Impacted versions:
all

Steps to reproduce:
start odoo and use any proxy that is *not* setting HTTP_X_FORWARDED_HOST e.g.:
`
ngrok httop 8069
`
Current behavior:
accessing odoo (root url) via https address is redirects to http because in `odoo/service/wsgi_server.py` proxy wrapper middleware is being applied when `HTTP_X_FORWARDED_HOST` is set by upstream proxy:

this is part of the code that is responsible:
`
if config['proxy_mode'] and 'HTTP_X_FORWARDED_HOST' in environ:
`

this should be limited only to checking `proxy_mode` in the config - as this must be explicitly set (default value is False) and additionally this middleware is not harmful to the requests

Expected behavior:

proxy middleware should be applied and redirect urls should work correctly with https address

**Comment by pedrobaeza** [comment]
Odoo doesn't understand about the rest of your infrastructure and shouldn't be, as that detail will complex the underlying code where it's not its duty, so proxy_mode config option should be manually specified on each case.

Closing as no Odoo bug.

**Comment by jerzyk** [comment]
INCORRECT!

this is odoo bug because  code I've mentioned is part of the odoo and this code is directly responsible in messing up infrastructure - not allowing to proxy middleware to work!

**Comment by pedrobaeza** [comment]
I don't think so. My reverse proxy is working perfectly with `proxy_mode=True`.

**Comment by jerzyk** [comment]
so, please tell me why, what is doing:
`'HTTP_X_FORWARDED_HOST' in environ:`

in the line 140 of the odoo/service/wsgi_server.py file?

In the mentioned code - as it is clearly disabling ProxyMiddleware  if an *optional* )(as per [rfc723](https://tools.ietf.org/html/rfc7239)) header is not set by upstream proxy?


`HTTP_X_FORWARDED_HOST` is *optional* header and there may be few more (x_forwarded_for, x_forwarded_port or x_forwarded_proto).

This is an expected behaviour of the proxy, because `HOST` header is not being changed so proxy do not need to set such a header if e.g. only upstream is changing protocol (X-Forwarded-Proto: https)

and last: "works form me" is a wrong answer on so many levels...

**Comment by pedrobaeza** [comment]
Please see https://www.odoo.com/documentation/14.0/setup/install.html about how to deploy Odoo.

**Comment by jerzyk** [comment]
yes, I've read this document, but this is stil not changing a fact that there is an error in odoo - please read the following till the end..

I've clearly demonstrated you what the issue is, how to replicate it and state reasons why this should be changed (RFC).

Despite my efforts, time spent on analysing the issue, checking how it should work, checking all the facts and preparing  bug report with all the information, bug is being closed by you without even thinking what it is.

_"Odoo doesn't understand about the rest of your infrastructure and shouldn't be"_
but clearly odoo (in the mentioned code) is trying to be smarter and is checking my infrastructure where is shouldn't

if I want a proxy mode that should be it, there is a werkzeug that is doing things right and let it do its things

look at the RFC, look at the werkzeug code for the proxy -  checking for `HTTP_X_FORWARDED_HOST` in odoo is not only a problem but is redundant

_"Closing as no Odoo bug"_
this is an odoo bug, in odoo code... 
I've politely asked you to explain why this check is there - I do not see an answer.

_"Please see ... about how to deploy Odoo"_
so, is there anything about reverse proxy? about setting `HTTP_X_FORWARDED_HOST` header?
had you seen how many times this issue is coming back and biting people? not to look too far: #18052

so, again please, take some time to understand this issue, if not for a professional curiosity but as an appreciation to another fellow odoo contributor who want this software to be better and is not wasting anybody time with poorly research issues...

**Comment by pedrobaeza** [comment]
I still don't see the bug, but I'm not a deep expert on this, and indeed this has reported other times, but the problem has been always on the deployment configuration (reverse proxy configuration, libraries versions, etc). I'm reopening for not "blocking any contribution", but not sure if this will reach to any happy end for you, as I don't have clear what do you expect.

**Comment by jerzyk** [comment]
thanks, added pull request #63277

**Comment by pedrobaeza** [comment]
Closing and following in the PR.
