### ISSUE TITLE
[14] Bug on shipment weight calculation

### ISSUE THREAD

**Issue by aitalinassim** [odoo/odoo#63273]
**Impacted versions:**
14 CE

**Steps to reproduce:**
Create new product and specify weight
Create SO
Make the delivery

**Current behavior:**
Weight on picking operation is wrong.

**Expected behavior:**
Weight on picking operation should be equal to Delivery slip.

**Comment by pedrobaeza** [comment]
Please specify more details with specific data and screenshots or video and what do you consider wrong.
