### ISSUE TITLE
PORT environment variable conflicts with Google Cloud Run

### ISSUE THREAD

**Issue by sffc** [odoo/odoo#63285]
As documented in the [Odoo Docker Readme](https://github.com/docker-library/docs/blob/master/odoo/README.md), the Odoo container expects the following environment variables:

- HOST: The address of the postgres server. If you used a postgres container, set to the name of the container. Defaults to db.
- PORT: The port the postgres server is listening to. Defaults to 5432.
- USER: The postgres role with which Odoo will connect. If you used a postgres container, set to the same value as POSTGRES_USER. Defaults to odoo.
- PASSWORD: The password of the postgres role with which Odoo will connect. If you used a postgres container, set to the same value as POSTGRES_PASSWORD. Defaults to odoo.

Unfortunately, the name for PORT conflicts with [the PORT variable used in Google Cloud Run](https://cloud.google.com/run/docs/reference/container-contract#port), which is the port of the application server, not the port of the database.  This means that Odoo cannot be deployed on Google Cloud Run without additional workarounds.

Suggested backwards-compatible fix: allow `DB_HOST` and `DB_PORT` as environment variables, and if they are present, they are used instead of `HOST` and `PORT` when connecting to Postgres.

Impacted versions: 14.0

**Comment by pedrobaeza** [comment]
Please open this on odoo/docker instead.

**Comment by sffc** [comment]
https://github.com/odoo/docker/issues/344
