### ISSUE TITLE
Small server error when openening developer mode, continues to work

### ISSUE THREAD

**Issue by Numiah** [odoo/odoo#63308]
Impacted versions: 14 (in Docker on Synology)

Steps to reproduce: select settings and activate developer mode.

Current behavior: shows error, opens a blank page with only top menu bar, continues to work after selecting menu.

Expected behavior: 

Video/Screenshot link (optional):
```
Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 2090, in report_download
    data = dict(url_decode(url.split('?')[1]).items())  # decoding the args represented in JSON
IndexError: list index out of range
```

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/14.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).
