### ISSUE TITLE
[8.0] Datetime field doesn't support null value?

### ISSUE THREAD

**Issue by aristobulo-eezee** [odoo/odoo#6332]
Hello, I have declared a field like this:

period_start = Datetime('Period start') , with no default value, then if I create a new record and try to see the view form I get error:
```
File "/Users/aristobulo/eezee-it/projects/RBO/parts/odoo/openerp/fields.py", line 1260, in from_string
    value = value[:DATETIME_LENGTH]
TypeError: 'bool' object has no attribute '__getitem__'
```
If I set a value directly in the database, I don't get this error anymore.

Why datetime fields doesn't support null values?

**Comment by aristobulo-eezee** [comment]
Field is declared in view like this:

<field name="period_start" readonly="1"/>

**Comment by rco-odoo** [comment]
@aristobulo-eezee Can you give a try to the fix in the linked pull request? Thanks!
