### ISSUE TITLE
incorrect copyright years / invalid copyright statements

### ISSUE THREAD

**Issue by onlyjob** [odoo/odoo#6333]
There are many files where copyright statement contains invalid years, like the following:

```
Copyright (c) 2013-TODAY OpenERP S.A.
```

"TODAY" is not a valid year.

See files

```
addons/account_followup/tests/__init__.py
addons/auth_oauth/res_config.py
addons/base_action_rule/tests/__init__.py
```

There are much more, over 50 files exhibiting such problem.
The following command could be useful to find them: `ack -i "\(c\).*today"`.

Also in file

```
addons/website_mail/tests/__init__.py
```

copyright statement is malformed:

```
Copyright (c) 20123TODAY OpenERP S.A.
```

Also the following files have no copyright years in the copyright statement:

```
addons/l10n_at/__init__.py
addons/l10n_at/account_wizard.py
addons/l10n_ch/__init__.py
```

Valid copyright statement must contain years.

**Comment by Yenthe666** [comment]
Hi @onlyjob,

Thank you for your bug report and bringing this to our attention.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
