### ISSUE TITLE
Libxml problem..  Odoo server get crashed 

### ISSUE THREAD

**Issue by sandeepksrana** [odoo/odoo#6334]
Hi there is a problem in libxml it is a latest one in my Linux system but there are two error related to this.

Segfault ERROR and General protection fault.

I have check my Kernel logs and these error related to libxml or lxml. (io.etree) 

have any one faced this problem... please let me know..  it repeat in every 10 to 15 days and odoo server process get crash. then we will have to restart the server again if we want to work on odoo.

Thanks
Sandeep

**Comment by hackman61** [comment]
Hi, I have exactly the same problem : 

Here is the syslog trace : 

Jun  9 09:09:11 odoo-01a kernel: [516654.619787] odoo.py[65039]: segfault at 3c ip 00007fef7ccbfd00 sp 00007fef6da3e510 error 4 in etree.so[7fef7cc30000+fa000]

And my config : 

 lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 7.8 (wheezy)
Release:        7.8
Codename:       wheezy

@sandeepksrana , have you some news about this problem ?

Thanks

Nicolas

**Comment by Anhlq87** [comment]
I met same case and I'm finding the way to solve it. Please let me know if you can solve it. Thanks :)

**Comment by sandeepksrana** [comment]
Its is issue in Debian.  I have change my server with Ubuntu and i never seen this problem till now.
I have found only this solution...

**Comment by sle-odoo** [comment]
Closing as i reproduce the issue at my end. I suggest you to turn on the workers mode, which will most probably prevent these kind of issues. If you have a way to reproduce this issue i'll be happy to try it and try to fix the real issue.

Regards
