### ISSUE TITLE
[12.0-14.0] calendar_sms: Clear global cache for all workers for all models each 30 minutes

### ISSUE THREAD

**Issue by moylop260** [odoo/odoo#63354]
# Impacted versions:
 - [12.0](https://github.com/odoo/odoo/blob/5aa540091f3f301960aa5a07fba2a6d009f09624/addons/calendar_sms/models/calendar.py#L74)
 - [13.0](https://github.com/odoo/odoo/blob/d947ea609b458ddbccabd661c22652d6c86a8167/addons/calendar_sms/models/calendar.py#L77)
 - [14.0](https://github.com/odoo/odoo/blob/008def3f878b63cb49e0b5ef09a2cc22c784c0a9/addons/calendar_sms/models/calendar.py#L79)

# Steps to reproduce:

 - Install the module [website_calendar](https://github.com/odoo/enterprise/blob/da63a9fb9cd932d12d70947e0f8dda9f6a9b8ab3/website_calendar/__manifest__.py#L17)
  - Notice it depends of calendar_sms
 - Check the new `ir.cron` created `calendar.ir_cron_scheduler_alarm`
   - https://github.com/odoo/odoo/blob/5aa540091f3f301960aa5a07fba2a6d009f09624/addons/calendar/data/calendar_cron.xml#L5
 - It is executed each 30m
   - https://github.com/odoo/odoo/blob/5aa540091f3f301960aa5a07fba2a6d009f09624/addons/calendar/data/calendar_cron.xml#L12-L13
 - It is calling the method `env['calendar.alarm_manager'].get_next_mail()`
   - https://github.com/odoo/odoo/blob/5aa540091f3f301960aa5a07fba2a6d009f09624/addons/calendar/data/calendar_cron.xml#L9
 - This method is calling `env['ir.config_parameter'].set_param` method
  
   - https://github.com/odoo/odoo/blob/5aa540091f3f301960aa5a07fba2a6d009f09624/addons/calendar_sms/models/calendar.py#L74

This method call `clear_caches` method

# Current behavior

The global cache for all models for all workers is cleared each 30 minutes.

# Expected behavior:

Reduce the number of times a global cache is cleared
Since that it improve the performance for too many method in odoo
IMHO clearing cache so frequently is not a good idea.
The full system is overloaded because all cache is re-built again and again.

# Reproduced in runbot.odoo.com

It is reproduced in runbot.odoo.com:
 - Open `Full run logs` of latest 12.0 build (or 13.0, 14.0)
 - Search the following string Starting job \`Calendar: Event Reminder\`
 - Check the following output:
```txt
2020-12-14 18:57:33,178 29 INFO 5397098-14-0-base odoo.addons.base.models.ir_cron: Starting job `Calendar: Event Reminder`. 
2020-12-14 18:57:33,226 29 INFO 5397098-14-0-base odoo.modules.registry: At least one model cache has been invalidated, signaling through the database. 
2020-12-14 18:57:33,228 29 INFO 5397098-14-0-base odoo.addons.base.models.ir_cron: Job `Calendar: Event Reminder` done
```
 - Notice between "starting job" and "job done" process there is a "At least one model cache has been invalidated, signaling through the database."

# OPW
 - `OPW#2417002`

UPDATED:

calendar module has the same issue:
  - https://github.com/odoo/odoo/blob/5aa540091f3f301960aa5a07fba2a6d009f09624/addons/calendar/models/calendar.py#L408

**Comment by Yenthe666** [comment]
Hmm that's an interesting find actually :) Curious to hear back from Odoo!
