### ISSUE TITLE
[8.0] Reporting module - Export all Data from list

### ISSUE THREAD

**Issue by jdegoy** [odoo/odoo#6336]
Reporting -> Warehouse -> Intrastat (or Latest Inventories & Moves for other example)
Select items and Export -> Export all Data
=>
Traceback: Exception: You can not export the column ID of model report.stock.lines.date, because the table report_stock_lines_date is not an ordinary table.

For every object/report (sql query) behind the Reporting module the Export should not add the ID which causes the error. There is no Import anyway.

**Comment by nle-odoo** [comment]
Hi,

Should be fixed in 8.0 since commit : odoo@f2fccdfaf02702f2
Regards.
