### ISSUE TITLE
[8.0] exclude urls from sitemap

### ISSUE THREAD

**Issue by ddfs** [odoo/odoo#6340]
is it possible to exclude selected routes from sitemap generation?

url like:

/web/reset_password
/web/signup
/web/login
/website/info
....
/page/temporary-page
...

so on

and other pages

**Comment by ddfs** [comment]
added version

**Comment by jholze** [comment]
Would be nice to have this as an option in the menu edit view and when creating a page. Or maybe in the backend under website settings. :+1:

**Comment by lukebranch** [comment]
yes, would be very useful in the backend website settings.

Being required to use the module names is a bit of an issue as well. It would be far better for SEO in 9.0 if instead of having:

/shop/category/[...]
/shop/product/[...]

it would be far more useful to have the option to have:

/[category name]/[product name]
/[product name]

or whatever combination you like. Similar to slug rewrites in Magento, Wordpress, etc. The current restrictions on requiring the use of the module names is ugly and cumbersome, and the way URL's are so tightly integrated with functionality is also an issue.

**Comment by jholze** [comment]
Hey @lukebranch,

i was sure that you will comment in this ticket ;) -as i know our new dev guy Zak is working on a SEO Suite to support all the long missed SEO Features to get more useful URL's. We will publish the code within the next two weeks in think.

**Comment by ddfs** [comment]
magento isn't very friendly either when it comes to modify urls for category, product, search etc.

let's see what will come with new version :)

**Comment by lukebranch** [comment]
@jholze ,

Awesome, thanks! I remember you mentioning something about that in another thread. Really looking forward to seeing what you guys have built, it sounds like it's going to be very useful.

**Comment by ddfs** [comment]
made something simple and code is here. (not a python expert, any suggestions welcome)

![screenshot from 2015-08-08 14-04-51](https://cloud.githubusercontent.com/assets/6930079/9150239/764e9adc-3dd6-11e5-98f6-08c575f755cc.png)


https://github.com/ddfs/odoo/tree/master/addons/sitemap

**Comment by jholze** [comment]
:+1:

**Comment by jholze** [comment]
Maybe a good option to add it to the options panel in the cms builder and also in the edit menu modal.

**Comment by ddfs** [comment]
that would be very handy but i don't have to do it yet

**Comment by jholze** [comment]
Lets me ask some of our devs, maybe someone is interested :) - i remember that we did something similar in the belsonno.de project. I'll let you know next days.

**Comment by jholze** [comment]
I got another idea, why not adding the functionality directly to the sitemap page which is rendered in the frontend ? because it's then list with all pages in the systems and maybe the easiest way to mange it. What do you think ?

**Comment by ddfs** [comment]
not sure if such interface exists. at least yet to manage the urls. 

but what you are asking is possible yet it might require couple of extra tables in db to keep the relation and track of urls. keeping them as text block is a lot easier than picking them from a list. 

adding regular expressions would do better job i think.

**Comment by JKE-be** [comment]
Hello @ddfs,
Could you make a pr for master with your code ? 

Until now, the only way is to use noindex in header.

**Comment by ddfs** [comment]
@JKE-be if you copy paste all the code i have in repo, and include in your module, it should work without any problem.

**Comment by JKE-be** [comment]
hello,  after some discussions internally...

- you can do it in robots.txt without add anything in Odoo code. Robots.txt priority is bigger than sitemap.xml
- Route like /web/databases... should be by default removed from sitemap.
- And if you really want one /page/xxx not indexed, you can always add header noindex.

I hope, that we will improve it for v11...

**Comment by ddfs** [comment]
-- true robots.txt priority is higher than sitemap.xml. proper way will be excluding them from there.

i was considering adding a parameter in the controller method parameters like:

``
    @http.route('/sitemap.xml', type='http', auth="public", website=True, sitemap=False)
    def sitemap_xml_index(self):
``

-- another problem during the sitemap generation when running in proxy mode with https,
urls not generated with https:// prefix. i have tried many combinations with no help.


-- customizing the language prefixes from language options added another field: url_code

-- to customize the existing odoo url  structure, give users more flexibility. implemented the following structure that works well with cms, e-commerce and backend

``
    @http.route([ROUTE_SITE_SHOP_PRODUCT['route']], type='http', auth="public", website=True, sitemap=True)
    def product(self, site_shop_product, category='', search='', **kwargs):
``

``
#
# Product
#
ROUTE_SITE_SHOP_PRODUCT = {
    'name': 'site_shop_product',
    'weight': 100,
    'route': '/<site_shop_product("product.template"):site_shop_product>',
    'build': ':name-p:id',
    'regex': re.compile(r'(?:(\w{1,2}|\w[A-Za-z0-9-_]+?\w))-p?(-?\d+)(?=$|/)'),
    'match': 2,
    'prefix': None,
    'suffix': None
}
``

**Comment by Yenthe666** [comment]
@JKE-be I think you've handled this pretty much. Can we close it? Final call is for you.

**Comment by JKE-be** [comment]
Thanks for your suggestions

- robots is always editable
- sitemap=False is now supported in v11 -  [('1','=','0')] should work for v8 in model converter
- change structure of URL is available for /page n v11 and will be partially improved for controller in v12 (WIP)
- url_Code is alway in the top of the wishlist
