### ISSUE TITLE
Files missing from v14 nightly repo

### ISSUE THREAD

**Issue by Royalpopat** [odoo/odoo#63419]
Impacted versions:14

Steps to reproduce:https://nightly.odoo.com/14.0/nightly/rpm/

Current behavior:repo not working from CentOS, unable to install Odoo v14 from repo.

Expected behavior:repo should not error and installation should work as normal for Odoo v14

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by Royalpopat** [comment]
Hi all,

I am very new to Linux, Odoo and this forum.

Looking for help on installing and configuring Odoo on a CentOS VM.

I came across an error where the installation would not happen when trying to install from 

https://nightly.odoo.com/14.0/nightly/rpm/

When I looked around it seems like the repo does not work possibly because there are some files on v13 repo that are missing from the v1 repo. Namely; "odoo.repo" and a folder "repodata".

Where can a request be submitted to look into this and get the repo working as normal?

Regards,

Govind

**Comment by Yenthe666** [comment]
@d-fence

**Comment by Royalpopat** [comment]
[root@Odoo ~]# sudo dnf install https://nightly.odoo.com/14.0/nightly/rpm/odoo_14.0.latest.noarch.rpm
Last metadata expiration check: 1:49:29 ago on Mon 30 Nov 2020 08:39:00 NZDT.
[MIRROR] odoo_14.0.latest.noarch.rpm: Curl error (60): Peer certificate cannot be authenticated with given CA certificates for https://nightly.odoo.com/14.0/nightly/rpm/odoo_14.0.latest.noarch.rpm [SSL certificate problem: certificate is not yet valid]
[MIRROR] odoo_14.0.latest.noarch.rpm: Curl error (60): Peer certificate cannot be authenticated with given CA certificates for https://nightly.odoo.com/14.0/nightly/rpm/odoo_14.0.latest.noarch.rpm [SSL certificate problem: certificate is not yet valid]
[MIRROR] odoo_14.0.latest.noarch.rpm: Curl error (60): Peer certificate cannot be authenticated with given CA certificates for https://nightly.odoo.com/14.0/nightly/rpm/odoo_14.0.latest.noarch.rpm [SSL certificate problem: certificate is not yet valid]
[MIRROR] odoo_14.0.latest.noarch.rpm: Curl error (60): Peer certificate cannot be authenticated with given CA certificates for https://nightly.odoo.com/14.0/nightly/rpm/odoo_14.0.latest.noarch.rpm [SSL certificate problem: certificate is not yet valid]
[FAILED] odoo_14.0.latest.noarch.rpm: Curl error (60): Peer certificate cannot be authenticated with given CA certificates for https://nightly.odoo.com/14.0/nightly/rpm/odoo_14.0.latest.noarch.rpm [SSL certificate problem: certificate is not yet valid]
Curl error (60): Peer certificate cannot be authenticated with given CA certificates for https://nightly.odoo.com/14.0/nightly/rpm/odoo_14.0.latest.noarch.rpm [SSL certificate problem: certificate is not yet valid]

**Comment by d-fence** [comment]
Thanks for the information, working on it.

**Comment by Royalpopat** [comment]
Thanks a lot guys for all the time and help. I am still a bit lost on what I have to do to get it working. Cause I am still getting the same error.

[root@Odoo ~]# sudo dnf install https://nightly.odoo.com/14.0/nightly/rpm/odoo_14.0.latest.noarch.rpm                                                                       Last metadata expiration check: 1:30:16 ago on Tue 01 Dec 2020 05:54:10 NZDT.
[MIRROR] odoo_14.0.latest.noarch.rpm: Curl error (60): Peer certificate cannot be authenticated with given CA certificates for https://nightly.odoo.com/14.0/nightly/rpm/odoo_14.0.latest.noarch.rpm [SSL certificate problem: certificate is not yet valid]
[MIRROR] odoo_14.0.latest.noarch.rpm: Curl error (60): Peer certificate cannot be authenticated with given CA certificates for https://nightly.odoo.com/14.0/nightly/rpm/odoo_14.0.latest.noarch.rpm [SSL certificate problem: certificate is not yet valid]
[MIRROR] odoo_14.0.latest.noarch.rpm: Curl error (60): Peer certificate cannot be authenticated with given CA certificates for https://nightly.odoo.com/14.0/nightly/rpm/odoo_14.0.latest.noarch.rpm [SSL certificate problem: certificate is not yet valid]
[MIRROR] odoo_14.0.latest.noarch.rpm: Curl error (60): Peer certificate cannot be authenticated with given CA certificates for https://nightly.odoo.com/14.0/nightly/rpm/odoo_14.0.latest.noarch.rpm [SSL certificate problem: certificate is not yet valid]
[FAILED] odoo_14.0.latest.noarch.rpm: Curl error (60): Peer certificate cannot be authenticated with given CA certificates for https://nightly.odoo.com/14.0/nightly/rpm/odoo_14.0.latest.noarch.rpm [SSL certificate problem: certificate is not yet valid]
Curl error (60): Peer certificate cannot be authenticated with given CA certificates for https://nightly.odoo.com/14.0/nightly/rpm/odoo_14.0.latest.noarch.rpm [SSL certificate problem: certificate is not yet valid]
[root@Odoo ~]# sudo dnf install https://nightly.odoo.com/14.0/nightly/rpm/odoo_14.0.latest.rpm
Last metadata expiration check: 1:31:36 ago on Tue 01 Dec 2020 05:54:10 NZDT.
[MIRROR] odoo_14.0.latest.rpm: Curl error (60): Peer certificate cannot be authenticated with given CA certificates for https://nightly.odoo.com/14.0/nightly/rpm/odoo_14.0.latest.rpm [SSL certificate problem: certificate is not yet valid]
[MIRROR] odoo_14.0.latest.rpm: Curl error (60): Peer certificate cannot be authenticated with given CA certificates for https://nightly.odoo.com/14.0/nightly/rpm/odoo_14.0.latest.rpm [SSL certificate problem: certificate is not yet valid]
[MIRROR] odoo_14.0.latest.rpm: Curl error (60): Peer certificate cannot be authenticated with given CA certificates for https://nightly.odoo.com/14.0/nightly/rpm/odoo_14.0.latest.rpm [SSL certificate problem: certificate is not yet valid]
[MIRROR] odoo_14.0.latest.rpm: Curl error (60): Peer certificate cannot be authenticated with given CA certificates for https://nightly.odoo.com/14.0/nightly/rpm/odoo_14.0.latest.rpm [SSL certificate problem: certificate is not yet valid]
[FAILED] odoo_14.0.latest.rpm: Curl error (60): Peer certificate cannot be authenticated with given CA certificates for https://nightly.odoo.com/14.0/nightly/rpm/odoo_14.0.latest.rpm [SSL certificate problem: certificate is not yet valid]
Curl error (60): Peer certificate cannot be authenticated with given CA certificates for https://nightly.odoo.com/14.0/nightly/rpm/odoo_14.0.latest.rpm [SSL certificate problem: certificate is not yet valid]

**Comment by Royalpopat** [comment]
Thanks again guys, looks like the SSL certificate has been sorted as well. Much appreciated.
