### ISSUE TITLE
[14] core : cache issue

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#63428]
Impacted versions: 14

Steps to reproduce:
- go to runbot : https://5415540-14-0.runbot38.odoo.com/web?debug=1#id=70&action=1112&model=sale.order&view_type=form&cids=1&menu_id=789 (you can fins this exemple)
- create a new model (for exemple : x_test_cache)
- create a field on sale.order.line : x_field_test, with store=False, readonly=False and compute, type = many2many, relation = x_test_cache
```python
@api.depends('product_id')
def _compute(self):
    for line in self:
         line.x_test_cache = self.env['x_test_cache'].search([])

```
- open tab A and create a new record of `x_test_cache` : `Test A`
- open tab B and create a new sale.order, add line with a product, you see `Test A`, then Save
- now on tab A, unlink `Test A` (or unlink can be perform by a cron)
- now on tab B, click on EDIT
--> Issue you see `Test A` (the field `x_test_cache` is not recomputed, it should be because unlink should clear all caches, no ?).

@rco-odoo 

Support ticket number submitted via odoo.com/help (optional): #2418071

**Comment by rco-odoo** [comment]
It is a client-side question: should the client re-read the shown record when you click "edit"?
I think it currently does not.

**Comment by fmdl** [comment]
Yes it currently not.
