### ISSUE TITLE
[8.0] ecommerce: can't remove optional products from cart

### ISSUE THREAD

**Issue by eLBati** [odoo/odoo#6344]
Steps
 - Go to runbot 8.0
 - Open 'iPad Mini' product and set 'Apple In-Ear Headphones' as 'Optional Product'
 - Open anonymous window and open /shop
 - Select 'iPad Mini' and 'add to cart'. Click 'Add to Cart' for 'Apple In-Ear Headphones'
 - Click 'proceed to checkout'
 - Click '-' on 'ipad min' quantity

Quantity of 'Apple In-Ear Headphones' remains 1

**Comment by beledouxdenis** [comment]
Closed with 67530c7b1d6712737d109596048f15739a45f4e1
