### ISSUE TITLE
[Point Of Sale] :  While Adding image in POS customer create screen, getting Odoo Client Error

### ISSUE THREAD

**Issue by Ctwinkle410** [odoo/odoo#6345]
Follow Below steps 

Go to POS  >  Click on Unknown Customer button  >   Now Customer list will open  >  

Now click on any of the customer or create new one. And try to add image.

You will get Client Error

Odoo Client Error

ReferenceError: event is not defined

http://qa-bma8.officebeacon.com/web/js/web.assets_backend/54ecc9d:4628

Regards,
Twinkle Christian

**Comment by Yenthe666** [comment]
Hi @Ctwinkle410,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
