### ISSUE TITLE
[8.0] page banner block behaviour

### ISSUE THREAD

**Issue by ddfs** [odoo/odoo#6347]
create a page -> insert banner -> add more slides. 

current behavior : carousel slider is continuously running during the edit mode.

expected: carousel should stop auto-play. slides should should turn on by clicking next/prev icons.

**Comment by flotho** [comment]
Same issue for me

**Comment by Yenthe666** [comment]
Hi @ddfs,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
