### ISSUE TITLE
POS product search not available when we do not set any POS Product Category

### ISSUE THREAD

**Issue by HendryLeo** [odoo/odoo#63483]
Impacted versions: 14.0

Steps to reproduce:
1. Run a new Odoo 14, from runbot
2. Choose -all database
3. Delete all POS Product Categories
4. Open new POS Session

Current behavior: 
Product Search Bar is not available

Expected behavior:
Product Search Bar is available

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/10069724/102449640-4f3ae100-4067-11eb-96af-ea77eb18e81c.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
The requirement is to have any category. You should have at least `All` category. If not, a lot of errors will appear, not only here. Closing as expected behavior.
