### ISSUE TITLE
[8.0,7.0] mrp_operations.py calculate the End date of Work Orders wrongly

### ISSUE THREAD

**Issue by ghost** [odoo/odoo#6348]
**"End date" (date_planned_end) of Work Orders is calculated wrong**

Impacted versions:
- 8.0, 7.0

Steps to reproduce:
1. go to Manufacturing in https://demo1.odoo.com/
2. create a new Manufacturing Order of "[HDD-DEM] HDD on Demand"
3. go to their Work Orders
4. watch the field "End date"

Current behavior:

![image](https://cloud.githubusercontent.com/assets/8233008/7187199/41afa7c8-e46f-11e4-818b-6d3aa5ccdb6d.png)

This is the code of this field in "mrp_operations" module:

```
       'date_planned_end': fields.function(_get_date_end, string='End Date', type='datetime'),
```

It seems that the function _get_date_end forget minutes and seconds of "Scheduled date".

Expected behavior:

The "End date" must be an addition of: "Scheduled date" + "Number of hours"

**Comment by alejandrosantana** [comment]
Verified. It is a big problem, indeed.

Another example:
Imagine starting time is 08:59:59, it will discard 59 minutes and 59 seconds and count as starting at 08:00:00. (Chops off almost 1 whole hour)
If "Number of hours" = 00:30, Odoo tells you you will end at 08:30, which is almost half an hour **before** you start. Critical.

There is also a +/- 12 seconds offset. Float rounding problem?

**Comment by karl-cenliming** [comment]
Hi All,
I've been fixed this issue in 8.0 as following:
go to file addons\resource\resource.py line 161

interval = (interval[0], interval[1] + relativedelta(seconds=seconds(limit-res)))

change this line as following:

interval = (interval[0], interval[0] + relativedelta(seconds=seconds(limit-res)))

can fix this bug.

**Comment by karl-cenliming** [comment]
and I just checked 9.0 code, this bug still there.

**Comment by Yenthe666** [comment]
Hi @ghost,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment). 
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report. @karl-cenliming feel free to create a new, detailed, bug report for V9 if it is still the case.

Regards,
Yenthe
