### ISSUE TITLE
Odoo 14 community - _handle_visibility - file ir_ui_view.py - website module - No password field show for page with password visibility

### ISSUE THREAD

**Issue by landlogicit** [odoo/odoo#63498]
From line file ir_ui_view.py#L366 to #L369 this code:
 try:
      self._check_view_access()
 except AccessError:
      error = werkzeug.exceptions.Forbidden()

Not show password visibility field.
If i comment this line then password field visibility is show. Please check.

**Comment by Yenthe666** [comment]
Then don't comment it 🤷 cc @pedrobaeza

**Comment by landlogicit** [comment]
Maybe you meant then apply the comment

**Comment by pedrobaeza** [comment]
Unless the steps to reproduce a problem is specified, this issue can't be "decoded" to be correct or not.
