### ISSUE TITLE
chatter not refresh 

### ISSUE THREAD

**Issue by movahhed** [odoo/odoo#63502]
Impacted versions: 12

Steps to reproduce:
please help me how to fix cant refresh when send chat
Current behavior:

Expected behavior:

Video/Screenshot link (optional):
![MyVideo_4](https://user-images.githubusercontent.com/27208274/102472869-fde12080-406b-11eb-9e4f-7e185155d4a9.gif)

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

A little tipo: it seems a problem on the deployment, with the longpolling port not working properly.

Closing this by the reason above.
