### ISSUE TITLE
potentially non-free CSS: `keyboard.css`

### ISSUE THREAD

**Issue by onlyjob** [odoo/odoo#6351]
File [addons/point_of_sale/static/src/css/keyboard.css](../blob/master/addons/point_of_sale/static/src/css/keyboard.css)

is based upon

  http://code.tutsplus.com/tutorials/creating-a-keyboard-with-css-and-jquery--net-5774

which is licensed with non-free terms (no re-distribution; restricted use):

> use the effects and techniques demonstrated in the content, and the
>  knowledge you learn, for personal or commercial purposes, without needing
>  to say where you learned it (attribution);
> 
> use, modify and manipulate assets made available like source files but
>  only for your own personal, educational purposes and without
>  redistributing them.

See http://tutsplus.com/terms-of-use

Also `keyboard.css` is missing copyright statement and license.

According to `git blame` this file was committed by _Frédéric van der Essen_ who might be able to spread some light on licensing. Otherwise we might have to remove that file.
Thanks.

**Comment by Yenthe666** [comment]
Hi @onlyjob,

Thank you for letting us know about the copyright issue.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can find this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
