### ISSUE TITLE
[8.0] Selecting group by exporting Bug

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#6352]
Hi Odoo,

I find a bug when I want to do an exporting.

So here is what I did:
1.  I go to invoice
2.  I group by status
3.  I check all by checking the checkbox beside group
4.  I click more>and export
5.  The popup message said, that “Please pay attention that all records matching your search filter will be exported. Not only the selected ids.” (the expected behaviour should be the selected ID, because I already select it)
6.  I export and I receive all the records, not just the one that I selected. (the expected behaviour should be the selected ID is exported)

In version 7, we don’t have this issue because we have an option what method should we export(export all or just selected id), now because you add that not added value feature we have this issue.

Video to explain things:
https://falinwa-my.sharepoint.cn/personal/falinwa1_falinwa_partner_onmschina_cn/_layouts/15/guestaccess.aspx?guestaccesstoken=m1ChUFMnnhoU4xYnGvHKEipcJl3NLAeMCOFun72Jpm0%3d&docid=0320b6b96d0a7437f8e433399e8030af3

**Comment by Yenthe666** [comment]
Hi @falinwa,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
