### ISSUE TITLE
[8.0] Qweb question for float/integer widget

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#6353]
Hi Odoo,

So I am in the middle to migrate the report from RML to Qweb,

I found this code in RML [[ formatLang(o.product_qty, digits=0) ]]
So in this code, we display the qty without digit precision.

How I migrate this code to qweb?

As my code in qweb I did this:

span t-field=”o.product_qty” t-field-options=’{“digits”:0}’

And its not worked, it just display the qty with digit precision.

If I did this:
span t-raw=”o.product_qty” 
Or
span t-raw=”o.product_qty”  t-field-options=’{“widget”:’integer’}’ 

The display will be: 1.0
What I want is just :1
Without digit precision.

How can I do that? Is there any people that know it?

**Comment by jar-odoo** [comment]
Use this code <span t-esc="'%.0f'%o.product_qty"/>
It's display will be: 1 not 1.0

**Comment by falinwa** [comment]
Hello Jar,

Thx for your answer, buy I can't see your code in here.

**Comment by falinwa** [comment]
ok, I have seen it,
its worked!

Thankyou so much jar.

**Comment by ayazmansuri** [comment]
Finally i got an answer. t-esc="'%.0f'%product.sale_delay"
Thank You So Much Jar..!!!

**Comment by rha-odoo** [comment]
Besides, FormatLang is still supported for QWeb,
https://github.com/odoo/odoo/blob/9.0/addons/account_budget/views/report_crossoveredbudget.xml#L70
https://github.com/odoo/odoo/blob/9.0/addons/account_budget/views/report_crossoveredbudget.xml#L67
