### ISSUE TITLE
Module from the master branch insert in stable version possible?

### ISSUE THREAD

**Issue by webghostx** [odoo/odoo#6354]
I would need a few features that are included only in the master brach. Would it be possible to install, for example, the website builder from the master branch to the stable version?

**Comment by jsh-odoo** [comment]
Request you to use [Odoo Forum] (https://www.odoo.com/forum/help-1) for asking this kind of questions. Thank you.

**Comment by webghostx** [comment]
I was hoping here to find a solution, because the question  likely is aimed at developers

**Comment by Yenthe666** [comment]
Hi @webghostx,

As mentioned, do ask this on the official help forums at odoo.com/help.
To answer this: technically it is possible but it won't be easy. You'll get troubles with changes and dependencies etc so not adviced.

Regards,
Yenthe
