### ISSUE TITLE
Odoo printing purchase order on a different language 

### ISSUE THREAD

**Issue by JustRibokas** [odoo/odoo#63564]
Impacted versions: 14.0 

Steps to reproduce: Change user language to Dutch (BE) / Nederlands (BE), print purchase order report.

Current behavior: System raises an error when printing purchase order report.
        ```
Error message :
        Fout:
        Odoo Server Error
        
        Traceback (most recent call last):
          File "/data/build/odoo/addons/web/controllers/main.py", line 2122, in report_download
            report_name = safe_eval(report.print_report_name, {'object': obj, 'time': time})
          File "/data/build/odoo/odoo/tools/safe_eval.py", line 328, in safe_eval
            c = test_expr(expr, _SAFE_OPCODES, mode=mode)
          File "/data/build/odoo/odoo/tools/safe_eval.py", line 184, in test_expr
            code_obj = compile(expr, "", mode)
          File "<string>", line 1
            (object.state in ('concept', 'verzonden') en 'Offerte aanvraag - %s'% (object.name) of
                                                       ^
        SyntaxError: invalid syntax
```

Expected behavior: System prints a purchase order report 

Video/Screenshot link (optional): https://ibb.co/s9g4FbZ

Support ticket number submitted via odoo.com/help (optional):

**Comment by KarstenK77** [comment]
I dont not really know if it relies, but I recognized for a long time, perhaps since Version 9 that when calling subtemplates, the languague settings get lost. For the same time I work around and set language in subtemplate again insteat debugging this issue:
```
<t t-set="partner" t-value="doc.partner_id"/>
<t t-call="mymodule.report_invoice_document" t-lang="doc.partner_id.lang"/>

...

<template id="mymodule.report_invoice_document">
        <t t-name="Document">
            <t t-call="mymodule.report_wrapper" t-lang="doc.partner_id.lang">
                <div class="page">
                    <t t-call="mymodule.invoice_info"/>


<!-- and in subtemplates first  -->

            <t t-set="doc" t-value="doc.with_context({'lang': partner.lang})"/>

```

@JustRibokas 
Perhaps you can check if this workaround helps you.

**Comment by JustRibokas** [comment]
P.S i think there's an issue with the translation for the record, it translated the 'and' and 'or' operators.

**Comment by Yenthe666** [comment]
Yeah, one of the Dutch translaters (@ploegvde) blew up the translation by translating too much of the string. I've fixed this 5 days ago though: 
![image](https://user-images.githubusercontent.com/6352350/102687279-37419980-41ee-11eb-8a1a-5805f891f817.png)

Update your translation terms again and it should be fixed :)
