### ISSUE TITLE
source-less (minified) `jSignature.min.js`

### ISSUE THREAD

**Issue by onlyjob** [odoo/odoo#6357]
Please replace source-less (minified) [jSignature.min.js](../blob/8.0/addons/website_quote/static/lib/jSignature/jSignature.min.js) in `addons/website_quote/static/lib/jSignature` with original uncompressed javascript:

  https://raw.githubusercontent.com/brinley/jSignature/v2.0.2/src/jSignature.js

Minified javascripts are effectively the same as pre-compiled binaries -- un-readable, non-modifiable and non-distributable in [Debian](http://debian.org). It is the best to have no minified files in source tree at all.

Thanks.

**Comment by odony** [comment]
We fixed that as of version 9.0, see eddcb46c82f17d75c99b8dacdee15d6489467b59.
Thanks!
