### ISSUE TITLE
[Whishlist] - Account Wizard from Template :: Cherrypicking Accounts

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#636]
It should be possible to easily select accounts (or in general items) of the accunt (or other) wizards to specifiy which templates should be copied and which left out (or aternatively inactivated on import).

> **_Rationale**_
> Convenience, convenience, convenience.
> 
> **_Usefulness**_
> This could make sort of an "ootb-coustomizing" easier, as exeeding items clutter the data and reduce simplicity.
> 
> **_References**_
> Moste accounting software has this or similar funcionality

**Comment by antonylesuisse** [comment]
Account template instanciation is non interactive (done based on the country of the company).
