### ISSUE TITLE
[13.0 / 14.0] Mismatch product on Import using External ID 

### ISSUE THREAD

**Issue by subaru22b** [odoo/odoo#63612]
Impacted versions: 13, 14

Steps to reproduce:

1. Import products with external id

id | Name
-- | --
1 | Apple
2 | Banana
3 | Mango
4 | Pineapple
5 | Grapes
6 | Watermelon
7 | Avocado

2. Import an excel file in Purchase RFQ with Order Lines/ Product/External ID, (I tested this on Purchase module, it could be the same with Sales module)

Order Date | Order Reference | Supplier | Order Lines / Product/ External Id | Order Lines / Quantity
-- | -- | -- | -- | --
2012-12-15 | PO00008 | ASUSTeK | 1 | 20
  |   |   | 2 | 30
  |   |   | 3 | 40
2012-12-15 | PO00009 | Axelor | 4 | 5
  |   |   | 5 | 15
2012-12-15 | PO000010 | China Export | 4 | 10
  |   |   | 5 | 20
  |   |   | 3 | 35
  |   |   | 2 | 40

Current behavior:

Importing in Purchase RFQ using the products' External ID shows a different product. In the example ASUSTek request is for product 1,2,3, or Apple, Banana, Mango, but it will show a different product

Expected behavior:

The result of import should show the correct product based on the External ID of the product.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
You are mismatching product templates and product variants, importing the first one as master data, but the second one on PO import. Activate variants and import them instead.

Closing as no bug.

**Comment by subaru22b** [comment]
I don't use any product variants and the variant option in not checked. I don't understand why I need to activate variants for importing into the PO.
