### ISSUE TITLE
[13.0][14.0] Language for newly registered portal user is not taken from the current website language

### ISSUE THREAD

**Issue by lhalda-pcv** [odoo/odoo#63616]
https://github.com/odoo/odoo/blob/12bf6a56e52f8e7b44babe87f71fbeaa0593df5f/addons/auth_signup/controllers/main.py#L130

the `.split('_')[0]` part shouldn't be there. It seems copied from the `web` module where it is used for selecting `.po` files, but in this context, the `lang` string gets compared to the `supported_lang_codes` list which is a list of lang **codes** (`code` field of `res.lang`), so after cropping everything from the first underscore onward, we won't get any match (as long as the lang code has an underscore, which is mostly the case).

Thus, the language from context never gets added to `values` for the new user and it is copied from the template portal user instead.

It seems to be the same in code of the `14.0` branch, I only tested it on `13.0` though.

Originally added: https://github.com/odoo/odoo/commit/d0a4b20d3660c09b1ebe203125d57c9a533c7957
Per its commit message, *The fix here is the same as what was done on `web` on the mentioned commit.* I'm guessing it means this change: https://github.com/odoo/odoo/commit/269aa594111a152ad4b7714856ea745bfef57155#diff-8f0bbb50491623995fba965c3d64585c6cbfdbbe519ec95473e472826d253826

**Comment by pedrobaeza** [comment]
@seb-odoo can you please check it?

**Comment by seb-odoo** [comment]
I don't understand the problem, please provide an example to reproduce.

**Comment by lhalda-pcv** [comment]
Scenario:

Odoo has 2 allowed languages (both used in website):
- English with code `'en_US'`
- French with code `'fr_FR'`

Language of *Portal User Template* is `'fr_FR'`.

New person comes to website in English and signs up. Expected behavior: newly created user's language is English (per website language when he created his user). Actual behavior: newly created user's language is French.

Reason:
- `supported_lang_codes` is `['en_US', 'fr_FR']`
- `request.context.get('lang', '')` is `en_US`
- `lang` is `'en_US'.split('_')[0]` which is `'en'`
- `if lang in supported_lang_codes:` evaluates as `False` because `'en'` is not in `['en_US', 'fr_FR']`
- thus, `values['lang']` is not set and `lang` of newly created user is instead taken from the portal user template.

**Comment by seb-odoo** [comment]
Ok thank you, I see now. So just remove the split? Do you want to do the PR yourself?

**Comment by lhalda-pcv** [comment]
Exactly. I'd prefer you to do it, I'm not familiar enough with GitHub :)
