### ISSUE TITLE
The base currency is not the base

### ISSUE THREAD

**Issue by zbik2607** [odoo/odoo#6361]
When two currencies (or more) have a rate = 1.0 (in some date) system gets bad as the base currency:

Examples from v8 code:

1) account_invoice_report

```
    currency_rate_id = currency_rate_obj.search(
        cr, uid, [
            ('rate', '=', 1),     
            '|',
                ('currency_id.company_id', '=', user.company_id.id),
                ('currency_id.company_id', '=', False)
            ], limit=1, context=context)[0]
    base_currency_id = currency_rate_obj.browse(cr, uid, currency_rate_id, context=context).currency_id.id
```

2) account_payment (here is also another error - why currency_obj and not currency_rate_obj?)

return currency_obj.search(cr, uid, [('rate', '=', 1.0)])[0]

3) res_company

```
rate_id = rate_obj.search(cr, uid, [('rate', '=', 1)], context=context)  
```

**Comment by eLBati** [comment]
Hello @zbik2607 please see https://github.com/odoo/odoo/pull/7550

**Comment by Yenthe666** [comment]
Hi @zbik2607,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
