### ISSUE TITLE
[14.0] website editor doesn't respect chosen header template

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#63630]
Impacted versions: 14.0

Steps to reproduce:
1. Login to the latest Odoo runbot 14.0 with the admin user
2. Go to the website and click on the header
3. In the right editor click on "Template" and choose the second template option where the logo is left and the dropdown right
4. Press OK and wait for a minute for Odoo to apply it
Video that shows this: https://drive.google.com/file/d/1UejHKMtQ4R03iBVUAL8io9HSuROrX5Q1/view 

Current behavior: The template you chose is not applied and is wrong.

Expected behavior: The template is applied.

**Comment by Yenthe666** [comment]
OPW `2421263`

**Comment by rdeodoo** [comment]
HI @Yenthe666 thanks for reporting, you can totally flag this one as `Website` as it is website editor not web editor, we don't check web editor PR (unless ping like this one ofc).
I think @bvr-odoo worked on that, can we have your input?

**Comment by bvr-odoo** [comment]
@rdeodoo @Yenthe666 Actually it's the right template.. Its just that the navbar option "alignment" is to "left" by default .... But the image of the template is like the navbar option is set to "right". So (if we want to improve that...) do we need to change the image or do we need to set the navbar option to "right" by default ? Question for @sbuhl IMO ;)

**Comment by Yenthe666** [comment]
Thanks for the feedback guys!
The image in the editor shows
"Logonavbar option(dropdown)"
but the view shows
"Navbar option (dropdown)          Logo            Icons & contact us"

IMO it should follow the design of the image which means the logo is all the way to the left and the navbar dropdown is all the way to the right. See img of where the red & green block should move:
![image](https://user-images.githubusercontent.com/6352350/102786531-f5585500-439f-11eb-9400-b838dfb54530.png)

**Comment by sbuhl** [comment]
Hello @Yenthe666 
Thank you for reporting this, you're correct. 
We have a bigger task to improve the global behavior of the headers, we'll add this point in it. 
As there is no blocking point, we'll not change the stable for this.
Thank you for your understanding.

Regards

**Comment by Yenthe666** [comment]
@sbuhl happy to hear you confirm and agree that this is wrong. Since this is wrong this can be considered a bug and since it is a bug it means it has to be fixed in stable as I raised an official helpdesk ticket. Can you please reconsider this for V14? We need it for our project(s).

**Comment by sbuhl** [comment]
@Yenthe666 
Worst case it's a visual bug but without any blocking point. Thumbnail are not supposed to match 100%. They are a clue of what can be the expected result. 
Though, I've no doubt that an experienced user as you are can achieve what is displayed on the thumbnail.
Tip, only in 3 easy steps:
1. Change the alignement of the navbar to the right
2. Hide the Sign in option
3. Remove the call to action button
See https://tinyurl.com/ycbd6zp3
I eager to see what you can achieve with the new website builder.

**Comment by JKE-be** [comment]
See the official response on the official helpdesk ticket of your official bug.

Their are nothing wrong, and no bug. Only an improvement of usability to do in master to make thumbnails nearest from the reality. But the template is correctly switched. If you want the same style, you jsut need to set position to right once the hamburger template is enable.

KR

**Comment by Yenthe666** [comment]
@JKE-be but there is not a single option to get the logo in the middle of your header :)

**Comment by JKE-be** [comment]
![image](https://user-images.githubusercontent.com/4848797/103927249-58751600-511a-11eb-845d-09dfeaee5619.png)

**Comment by JKE-be** [comment]
https://5654097-14-0.runbot49.odoo.com/?#
