### ISSUE TITLE
Performance issue: creation of BoM due to Forecasted Inventory modification

### ISSUE THREAD

**Issue by jvandri** [odoo/odoo#63631]
**Impacted versions:**
13.0

**Steps to reproduce:**

Go to menu Sales > Products.
Create a Bills of Material with several components (E.g 10).
 
**Current behavior:**
On a large database, creation of Bills of Material can take up to 10 to 15 minutes. Which leads to worker timeout. 

After local investigation, a modification of the report.stock.quantity sql view is the cause of the slowness. A single select (made by the ORM at the creation of a BoM) in the view takes from 20 to 50seconds. This call is done for each BoM line.

The modification leading to this behavior was done in this commit https://github.com/odoo/odoo/commit/4e4584c4b00d70215713029fc1c2a96641d99aa9

**Expected behavior:**

Creation of the Bills of Material in less than 10minutes.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):
2420830

**Comment by ryv-odoo** [comment]
Hello @jvandri , 
Thank you for the issue.
You are maybe right for the the slowness of the report but I do see the link with the creation of BoM ? Or I miss something ?

**Comment by jvandri** [comment]
Hi @ryv-odoo,

Well at the creation of the BoM, in the many operations made by the ORM, it does a write on the product, which triggers the modification of cache and then the select occurs due to the relation of the report with the product.template model.

Here is the stacktrace that lead to the select: 

execute, sql_db.py:240
wrapper, sql_db.py:173
_search, models.py:4475
search, models.py:1643
**_modified_triggers, models.py:5857
modified, models.py:5795
write, models.py:3565
write, mail_activity.py:726
write, mail_thread.py:323
write, product.py:330
write, product.py:540**
__set__, fields.py:1089
__setitem__, models.py:5718
_inverse_related, fields.py:594
determine_inverse, fields.py:1124
create, models.py:3821
_model_create_multi, api.py:336
<frame not available>
create, mrp_bom.py:365
_model_create_multi, api.py:335
<frame not available>
create, mrp_bom.py:138
<genexpr>, api.py:317
_model_create_single, api.py:317
<frame not available>
flush, fields.py:3024
write_real, fields.py:3060
write_batch, fields.py:2887
create, fields.py:2861
_create, models.py:3948
create, models.py:3788
_model_create_multi, api.py:336
<frame not available>
create, mail_thread.py:269
_model_create_multi, api.py:336
<frame not available>
create, mrp_bom.py:129
_model_create_multi, api.py:335
<frame not available>
_call_kw_model_create, api.py:365
call_kw, api.py:385
_call_kw, main.py:1319
call_kw, main.py:1327
response_wrap, http.py:515
__call__, http.py:915
checked_call, http.py:339
wrapper, model.py:94
_call_function, http.py:350
dispatch, http.py:669
_dispatch, ir_http.py:234
_dispatch, ir_http.py:519
_dispatch, ir_http.py:29
_dispatch, ir_http.py:21
_dispatch, ir_http.py:19
_dispatch, ir_http.py:172
_dispatch, ir_http.py:15
dispatch, http.py:1457
__call__, wsgi.py:766
__call__, http.py:1257
__call__, http.py:1287
application_unproxied, wsgi_server.py:117
application, wsgi_server.py:142
app, server.py:439
execute, serving.py:258
run_wsgi, serving.py:270
handle_one_request, serving.py:328
handle, server.py:418
handle, serving.py:293
__init__, socketserver.py:724
finish_request, socketserver.py:364
process_request_thread, socketserver.py:654
run, threading.py:864
_bootstrap_inner, threading.py:916
_bootstrap, threading.py:884

Hope this will help you :)

**Comment by ryv-odoo** [comment]
Yeah, it is due to the `readonly=False` of the related `product_tmpl_id` in `mrp.bom.line`. I am going to make a PR to remove it, in all situation the `product_tmpl_id` shouldn't be modify from a BoM line models. 
Thank you for the information.
