### ISSUE TITLE
Horizontal Menu Drop-Down of Website module not working from any website. 

### ISSUE THREAD

**Issue by exidoncom** [odoo/odoo#6367]
Impacted versions:
- 8.0

Steps to reproduce:
1. Open 104.236.113.197:8069
2. Hover over horizontal menu and click to any subpage
3. Try todo same several times

Current behavior:
- Horizontal Dropdown menus stop opening, so you could choose its subpages.

Expected behavior:
-  Showing subpage on hover independent from where you are.

**Comment by Yenthe666** [comment]
Hi @exidoncom,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
