### ISSUE TITLE
[13.0] How to override kanban global click action ?

### ISSUE THREAD

**Issue by thopv133802** [odoo/odoo#63672]
Impacted versions: 13.0

Steps to reproduce: Kanban view -> Click kanban card

Current behavior: Go to Department's form view

Expected behavior: Go to another view(e.g: Click Department go to Department's employees)

Video/Screenshot link (optional): 

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
