### ISSUE TITLE
The qweb FieldMonetary widget should use a non-breaking space between currency symbol

### ISSUE THREAD

**Issue by sbidoul** [odoo/odoo#6369]
Otherwise you obtain such not-so-nice reports where the currency wraps on the next line:

![selection_030](https://cloud.githubusercontent.com/assets/692075/7206634/a41c6cec-e533-11e4-871c-77ba3f6035a8.png)

**Comment by alejandrosantana** [comment]
Agreed.

**Comment by falinwa** [comment]
+1
agree

**Comment by bealdav** [comment]
+1

**Comment by adrienpeiffer** [comment]
OPW 633975

**Comment by adrienpeiffer** [comment]
:+1:
