### ISSUE TITLE
Submit Survey Answer raise TypeError if the answer contain the word 'comment'

### ISSUE THREAD

**Issue by sekawe** [odoo/odoo#63718]
**Impacted versions**: 14

**Steps to reproduce**: Create Survey -> Start answering -> type the word 'comment' in any text field

**Current behavior**: raise an error (TypeError: string indices must be integers)

**Expected behavior**: save the answer

**Screenshot**:

![Screen Shot 2020-12-22 at 8 33 38 PM](https://user-images.githubusercontent.com/10577765/102921394-fc14c400-4494-11eb-8c1d-0d9f8f5b79e1.png)

Knowing that this scenario has been tested on the run bot and the same result has occurred.

Thanks

**Comment by niyasraphy** [comment]
hi @sekawe ,
it seems to be working now, may be it get fixed in between.
feel free to close the ticket.

thanks
