### ISSUE TITLE
Fedora 33 and Odoo 14 Nightly repository problem 

### ISSUE THREAD

**Issue by kajo23** [odoo/odoo#63719]
Impacted versions: 14

https://nightly.odoo.com/14.0/nightly/rpm/
Repository return Error 404

**Comment by pedrobaeza** [comment]
I see the rpms inside...

**Comment by kajo23** [comment]
I also see it.

When I use: dnf update
Error: Failed to download metadata for repo 'odoo-nightly': Cannot 
download repomd.xml: Cannot download repodata/repomd.xml: All mirrirs 
were tried


Dimitar Pertov
Sofia, Bulgaria
+359 (88) 845 0743

**Comment by kajo23** [comment]
Now I face with another problem:

Last metadata expiration check: 0:08:22 ago on Thu 14 Jan 2021 11:50:30 AM EST.
Error: 
 Problem: conflicting requests
  - nothing provides pychart needed by odoo-14.0.post20210114-1.noarch
  - nothing provides pyparsing needed by odoo-14.0.post20210114-1.noarch
  - nothing provides libxslt-python needed by odoo-14.0.post20210114-1.noarch

**Comment by kajo23** [comment]
Last metadata expiration check: 0:13:28 ago on Fri 15 Jan 2021 02:09:34 PM EST.
Error: 
 Problem: conflicting requests
  - nothing provides pychart needed by odoo-14.0.post20210115-1.noarch
  - nothing provides pyparsing needed by odoo-14.0.post20210115-1.noarch
  - nothing provides libxslt-python needed by odoo-14.0.post20210115-1.noarch

**Comment by Yenthe666** [comment]
@d-fence

**Comment by hallcrash** [comment]
same problem on Fedora 32


    nothing provides pychart needed by odoo-14.0.post20210115-1.noarch
    nothing provides pyparsing needed by odoo-14.0.post20210115-1.noarch
    nothing provides libxslt-python needed by odoo-14.0.post20210115-1.noarch

**Comment by d-fence** [comment]
I'm on it

**Comment by kahtooei** [comment]
i have same problem. how can i solve it and install odoo 14 on fedora 33?

Problem: conflicting requests

    nothing provides pychart needed by odoo-14.0.post20210114-1.noarch
    nothing provides pyparsing needed by odoo-14.0.post20210114-1.noarch
    nothing provides libxslt-python needed by odoo-14.0.post20210114-1.noarch
