### ISSUE TITLE
Odoo v14.0 repodata folder empty

### ISSUE THREAD

**Issue by Royalpopat** [odoo/odoo#63720]
Impacted versions:v14.0

Steps to reproduce: sudo dnf install -y odoo

Current behavior: error code 404

Expected behavior: to install Odoo and dependencies

Video/Screenshot link (optional): [root@Odoo ~]# sudo dnf groupinstall 'development tools'
Odoo Nightly repository                                                                                                                                                    106  B/s | 146  B     00:01
Errors during downloading metadata for repository 'odoo-nightly':
  - Status code: 404 for http://nightly.odoo.com/14.0/nightly/rpm/repodata/repomd.xml (IP: 178.33.123.40)
Error: Failed to download metadata for repo 'odoo-nightly': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
[root@Odoo ~]# sudo dnf install bzip2-devel expat-devel gdbm-devel \
>     ncurses-devel openssl-devel readline-devel wget \
>     sqlite-devel tk-devel xz-devel zlib-devel libffi-devel
Odoo Nightly repository                                                                                                                                                     76  B/s | 146  B     00:01
Errors during downloading metadata for repository 'odoo-nightly':
  - Status code: 404 for http://nightly.odoo.com/14.0/nightly/rpm/repodata/repomd.xml (IP: 178.33.123.40)
Error: Failed to download metadata for repo 'odoo-nightly': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
[root@Odoo ~]#  sudo dnf install -y odoo
Odoo Nightly repository                                                                                                                                                     93  B/s | 146  B     00:01
Errors during downloading metadata for repository 'odoo-nightly':
  - Status code: 404 for http://nightly.odoo.com/14.0/nightly/rpm/repodata/repomd.xml (IP: 178.33.123.40)
Error: Failed to download metadata for repo 'odoo-nightly': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

Support ticket number submitted via odoo.com/help (optional):

**Comment by Royalpopat** [comment]
[root@Odoo ~]# sudo dnf groupinstall 'development tools'
Odoo Nightly repository                                                                                                                                                    106  B/s | 146  B     00:01
Errors during downloading metadata for repository 'odoo-nightly':
  - Status code: 404 for http://nightly.odoo.com/14.0/nightly/rpm/repodata/repomd.xml (IP: 178.33.123.40)
Error: Failed to download metadata for repo 'odoo-nightly': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried


[root@Odoo ~]# sudo dnf install bzip2-devel expat-devel gdbm-devel \ ncurses-devel openssl-devel readline-devel wget \ sqlite-devel tk-devel xz-devel zlib-devel libffi-devel
Odoo Nightly repository                                                                                                                                                     76  B/s | 146  B     00:01
Errors during downloading metadata for repository 'odoo-nightly':
  - Status code: 404 for http://nightly.odoo.com/14.0/nightly/rpm/repodata/repomd.xml (IP: 178.33.123.40)
Error: Failed to download metadata for repo 'odoo-nightly': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried


[root@Odoo ~]#  sudo dnf install -y odoo
Odoo Nightly repository                                                                                                                                                     93  B/s | 146  B     00:01
Errors during downloading metadata for repository 'odoo-nightly':
  - Status code: 404 for http://nightly.odoo.com/14.0/nightly/rpm/repodata/repomd.xml (IP: 178.33.123.40)
Error: Failed to download metadata for repo 'odoo-nightly': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried


[root@Odoo ~]#

**Comment by Royalpopat** [comment]
@d-fence @Yenthe666

**Comment by Royalpopat** [comment]
Guys please help, hopefully it installs fine after this. Merry Xmas to all :)

**Comment by Royalpopat** [comment]
hi all, any luck with this?

**Comment by Yenthe666** [comment]
As long as you don't hear back anything there is no update from the Odoo team & you can consider this as nobody has looked at it yet.

**Comment by d-fence** [comment]
I'm on it

**Comment by d-fence** [comment]
Repo is now fixed, thanks for the reporting.

**Comment by Royalpopat** [comment]
Thanks guys, have a great year ahead.
