### ISSUE TITLE
Google OAuth 2 authorization - Error: redirect_uri_mismatch

### ISSUE THREAD

**Issue by exidoncom** [odoo/odoo#6373]
*_Following Oauth setup instruction runs into Error *_

Impacted versions:
- 8.0

Steps to reproduce:
1. Goto settings - General Settings
2. Allow external authentication provider
3. Follow Instructions for setup Google Oauth
   1. Paste clientid you get from google devleoper console
   2. Logout
   3. Choose option of Google Account for relogin
   4. Login into your Google Account
   5. See error message from google, telling there is URI_Mismatch

Current behavior:
- No login or sync via oauth2 possible follwing instruction

Expected behavior:
- Automatic login, after granting permissions in Google Account for first time.

**Comment by exidoncom** [comment]
Could it be that for any reason, google redirect stripes out port???

**Comment by jsh-odoo** [comment]
I think you have not properly set the 'Redirect URIs' in the configuration part of Google API. For Google Oauth 2.0 provider you have to set 'Domain-name/auth_oauth/signin' in the settings of Oauth 2.0 API. [Domain-name](http://en.wikipedia.org/wiki/Domain_name) , [Setting Google Oauth provider] (https://developers.google.com/console/help/new/?hl=en_US#generatingoauth2)

**Comment by Danisan** [comment]
So, the instructions in the wizard (spanish) are not good

**Comment by Yenthe666** [comment]
Hi @exidoncom,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
