### ISSUE TITLE
8.0: permanent password reset note

### ISSUE THREAD

**Issue by onlyjob** [odoo/odoo#6374]
I've used _"Send Reset Password Instructions"_ link once and now user profile have permanent yellow bar (which I can't dismiss even by editing user properties):

_"A password reset has been requested for this user. An email containing the following link has been sent:"_.

Any ideas?

**Comment by Yenthe666** [comment]
Hi @onlyjob,

Sorry for the very late reply.
This means an e-mail was send out to the new user but that he/she has never clicked on the link and changed the password.

Regards,
Yenthe
