### ISSUE TITLE
remove `es5-shim.min.js`; update `es5-shim.js`

### ISSUE THREAD

**Issue by onlyjob** [odoo/odoo#6375]
Please remove redundant minified [es5-shim.min.js](../blob/8.0/addons/web/static/lib/es5-shim/es5-shim.min.js): 

Minified javascripts are effectively the same as pre-compiled binaries --
un-readable, non-modifiable and often non-distributable.
It is the best to have no minified files in source tree at all.

Uncompressed `es5-shim.js` could benefit from upgrading to recent version.
To document origin of the 3rd party script I recommend adding `es5-shim.js.url` file with the following URL:

```
https://raw.githubusercontent.com/es-shims/es5-shim/v4.1.1/es5-shim.js
```

Thanks.

**Comment by Yenthe666** [comment]
Hi @onlyjob,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
