### ISSUE TITLE
[14.0] Incorrect if statements in point_of_sale/static/src/js/models.js

### ISSUE THREAD

**Issue by em230418** [odoo/odoo#63769]
Impacted versions:
14.0

https://github.com/odoo/odoo/blob/3c285d5cd931e6f503060c6daa1823507aba7957/addons/point_of_sale/static/src/js/models.js#L1019-L1031

`If` expression on line 1019 is the same as on `else if` on line 1029. So block in that `else if` wont be executed.

**Comment by pedrobaeza** [comment]
And how this affects any functional process?

**Comment by em230418** [comment]
> And how this affects any functional process?

I have no idea. But in general, that `else if` block exists, so something is intended to be executed within this block.

**Comment by Yenthe666** [comment]
If there's no way to reproduce it or has any issues its not really a bug. You're free to make a PR to improve this in future versions though.
@pedrobaeza I guess we can close this anyways?

**Comment by pedrobaeza** [comment]
I think so, as the code can be improved indeed, but if it doesn't reflect any functional misfunction, we can't say it's a bug.
