### ISSUE TITLE
Accounting sequence missing on reconciling from Accounting Dashboard

### ISSUE THREAD

**Issue by jabirmisnedtech** [odoo/odoo#63794]
Impacted versions:
13 and 14
Steps to reproduce:
Please check the attached video
1. Create a statement from the accounting overview dashboard.
2. Add lines in the statement and reconcile. For each line, there will be separate journal entries generated.
3. Open the same statement and click the RESET TO PROCESSING button and RESET TO NEW. Then delete a line and reconcile the statement.
The journal entry created for the deleted line will be deleted and the sequence number is lost. This will cause a gap in the accounting sequence.

Current behavior:
Editing already reconciled statement causes a gap in the sequence number

Expected behavior:
Use the number for the next journal entry or keep it in the system in cancelled state.

Video/Screenshot link (optional):
https://user-images.githubusercontent.com/45730318/103132173-ab7bb180-46b4-11eb-9375-3bee9fc3b0a7.mp4

Support ticket number submitted via odoo.com/help (optional):
#2423349

**Comment by william-andre** [comment]
@smetl Should we revert/cancel the move if it has been posted? Or prevent deleting it (and put it at 0)?

**Comment by william-andre** [comment]
Otherwise, you could use the Resequence wizard to remove the gaps.

**Comment by smetl** [comment]
When we made the payment refactoring in 14.0, we agreed this behavior wasn't an issue thanks to the resequence wizard.
