### ISSUE TITLE
Odoo installation error: psycopg2.errors.UndefinedTable: relation "ir_module_module" does not exist

### ISSUE THREAD

**Issue by MisaghMi** [odoo/odoo#63802]
I want to install Odoo version 12 on my "Windows Server 2019" with "Python 3.9" and "postgresql 13" but when I want to create DB this error shown:

Database creation error: relation "ir_model" does not exist LINE 1: SELECT * FROM ir_model WHERE state='manual' ^

I used this command to run Odoo:

python odoo-bin -r user -w pass -d odoo -i base --db-filter=^%d$

Odoo makes the DB but there is no table stored in there.

_Originally posted by @MisaghMi in https://github.com/odoo/odoo/issues/51400#issuecomment-749501926_

**Comment by pedrobaeza** [comment]
Please use a lower version of Postgresql, and Windows is not the most suitable platform for Odoo, although supported through the Windows installer, but not with custom deployments.

Closing as deployment question.

**Comment by MisaghMi** [comment]
I've already installed lower version of Postgresql (version 10.15) but I get same error every time I run Odoo.
`ERROR: relation "ir_module_module" does not exist`

**Comment by pedrobaeza** [comment]
You have to use windows installer or switch to Linux.

**Comment by pedrobaeza** [comment]
The problem seems to be PostgreSQL configuration.

**Comment by MisaghMi** [comment]
this is my pg_hba.conf:
`# TYPE  DATABASE        USER            ADDRESS                 METHOD

# IPv4 local connections:
host    all             all             127.0.0.1/32            md5
# IPv6 local connections:
host    all             all             ::1/128                 md5
# Allow replication connections from localhost, by a user with the
# replication privilege.
host    replication     all             127.0.0.1/32            md5
host    replication     all             ::1/128                 md5
# foreign connections
host    all             all             0.0.0.0/0               md5
host    all             all             ::/0                    md5`

i'm working on a remote server.

**Comment by pedrobaeza** [comment]
For further questions, please go to forums, as this is not an Odoo issue, but configuration one.

**Comment by mvint** [comment]
https://github.com/odoo/odoo/issues/63802#issuecomment-752011218 is the same problem

**Comment by kamyaD** [comment]
I am facing the same problem but it has not been answered even on official odoo page.  Is it that you guys don't have the answer to the question? Look at this answer for example: 
![image](https://user-images.githubusercontent.com/33648833/133962028-16c29051-43ab-4e96-8954-d103531c8ab2.png)

**Comment by kamyaD** [comment]
Installing  `docutils` and  `html2text` though pip solved the issue.

**Comment by zorojurio** [comment]
instead of using the
 `odoo/odoo-bin  -c conf/myconff.cfg -i base`

after deleting the database
use
`python3 odoo/odoo-bin -d databasename -i base --addons-path=odoo/addons `


this worked for me

**Comment by hugolvc** [comment]
This worked for me https://www.odoo.com/es_ES/forum/ayuda-1/attributeerror-module-lib-has-no-attribute-x509-v-flag-cb-issuer-check-when-creating-new-staging-branch-202955

**Comment by victoryohanna** [comment]
Thank you @kamyaD I installed html2text and changed docutils==0.16 to docutils==0.19 the latest version at the moment then run pip install -r requirements.txt

**Comment by kamyaD** [comment]
Try running update all

**Comment by MuhammedMiiRanna** [comment]
> Try running update all

I am not sure i'am following, i asked gemini about that command and here's what he said: https://g.co/gemini/share/991a5594b253

![image](https://github.com/user-attachments/assets/924dcbda-a6fe-44f1-9eb5-987392752d42)

**Comment by ariitano** [comment]
I have the same error, but I'm using the official docker image, I cannot (or I should not) manually install pip modules in there... they should be already present...

**Comment by MohamedAliMerali** [comment]
I quite that job, thanks everyone for helping i appreciate that,
Btw I solved the issue by having a new computer (literally) i was trying to run it in Linux too
