### ISSUE TITLE
[14.0] Duplication of Order lines when creating RFQ from Purchase Agreement.

### ISSUE THREAD

**Issue by dipsshah42** [odoo/odoo#63804]
Impacted versions: 14.0 C

Steps to reproduce:
- Go to Purchase > Orders > Click on Purchase agreement
- Create record in purchase agreement, Confirm it and Click on 'New Quotation' button.

Current behavior:
- When new quotations is getting created, its duplicating order lines from agreement.

Expected behavior:
- It should create one line in RFQ. Currently creating 2 lines for same product.

Video/Screenshot link (optional):
[Video link](https://www.awesomescreenshot.com/video/2196381?key=2b1df64b4c9aa8bbfa2f53e6262ae17b)
![image](https://user-images.githubusercontent.com/35560490/103170066-62b82a00-4867-11eb-95f2-8ab8933ca6a5.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by svs-odoo** [comment]
Hello,
This issue will be fixed soon, thank you for your report !

**Comment by svs-odoo** [comment]
Fixed by #63983
