### ISSUE TITLE
HTML-Edit bar not available, when creating quote template in non-default Language

### ISSUE THREAD

**Issue by exidoncom** [odoo/odoo#6380]
Impacted versions:
- 8.0

Steps to reproduce:
1. create demo instance with webbuilder, quotation builder, 3 languages (default webpage language spanish, default user backend langauge: english) and  use a browser with english as default browser language
2. goto sales, create quotation template, click edit template
3. try to inseret a header 1

Current behavior:
- edit template switches to en_US of a non existing default document

Expected behavior:
- Should allow to create template in default language and independently of language show edit bar on top.

**Comment by Yenthe666** [comment]
Hi @exidoncom,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
