### ISSUE TITLE
Can I create a public open source github repo based on odoo community version source code?

### ISSUE THREAD

**Issue by odoochina-dev** [odoo/odoo#63801]
This is actually not a bug, but just a **question**.

I have create a repo on github, based on odoo nightly release build at https://nightly.odoo.com/

It does nothing but checkin each odoo nightly release souce code a commit of this repo. Main purpose is to quickly find what's changed between each odoo nightly releases.  below screenshots are from the repo, which currently it's a **private** repo.

My question is, can I make the repo public? The chosen license is LGPLv3,  the same as odoo.
Maybe I'm too cautious, but I just want to dobule confirm there is no any legal risk，and perfectly there will be offical confirm from odoo team.  Thanks!

---------------------------------------------

**1) repo introduction** (screenshot)
![odoo14-releases](https://user-images.githubusercontent.com/76577822/103154492-8c734180-47d2-11eb-9d92-e3243de2094b.png)

**2) get to know what's the diff between two odoo daily releases ** (screenshot)
![odoo14-releases-diff](https://user-images.githubusercontent.com/76577822/103154488-8a10e780-47d2-11eb-9f46-daf419a6233a.png)

**Comment by Yenthe666** [comment]
I _think_ it is okay. @pedrobaeza I know you know much more about licensing so maybe you could give feedback?

**Comment by pedrobaeza** [comment]
You are not indicating the URL of your repository, so we don't exactly know what it contains.

**Comment by odoochina-dev** [comment]
Thanks @Yenthe666 and @pedrobaeza .

It's still a private repo, thus not providing the url.
Basically it contains nothing but odoo source code. (each odoo nightly release souce code is as an commit of this repo)

$ tree -L 2 .
.
├── README.md                       # a simple readme as screenshot above
├── latest.txt                             # recording which odoo releases are included.
└── odoo14_latest                    # the odoo 14 community version source code.
    ├── LICENSE
    ├── MANIFEST.in
    ├── PKG-INFO
    ├── README.md
    ├── odoo
    ├── odoo.egg-info
    ├── requirements.txt
    ├── setup
    ├── setup.cfg
    └── setup.py

4 directories, 9 files

**Comment by pedrobaeza** [comment]
Well, I don't see the usefulness for that, as IMO you should use directly git for that instead of mounting all this stuff, but it's not illegal to do it while you keep the same license for the code.
