### ISSUE TITLE
What does this green Indicator on odoo icon means ?

### ISSUE THREAD

**Issue by HaydarZaraki** [odoo/odoo#63812]
Impacted versions:
13 Enterprise
Steps to reproduce:
 

Current behavior:
![Screenshot from 2020-12-28 11-14-54](https://user-images.githubusercontent.com/32509226/103204003-03a5f400-48ff-11eb-8206-78dfb8c01094.png)
Expected behavior:

Video/Screenshot link (optional):

Support ticket number su

bmitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
