### ISSUE TITLE
Fonts without license? (mnmliconsv21-webfont.*)

### ISSUE THREAD

**Issue by onlyjob** [odoo/odoo#6382]
Please document origin, copyright and the license for fonts `addons/web/static/src/font/mnmliconsv21-webfont.*`. 
I was not able to find an authoritative source of those fonts on web. It seems those font files were developed by Carlos Elías (http://www.carloselias.cl/) but his web site is not in English.
Someone need to contact Carlos to confirm copyright and license of those fonts or they will have to be removed.

**Comment by Yenthe666** [comment]
Hi @onlyjob,

Thanks for the feedback.
These fonts are still in Odoo 9-11 so we might want to double check this. @qsm-odoo you where the guy that commited this - can you double check please?

Regards,
Yenthe

**Comment by qsm-odoo** [comment]
@Yenthe666 Where did you see I committed that ?

**Comment by Yenthe666** [comment]
@qsm-odoo apoligies, I was looking at the last commit (https://github.com/odoo/odoo/commit/e503fc80df86f461e8952877a9aa22c1ae0ac318) which was done by you. 
@aab-odoo and @qsm-odoo you two are the only ones with a history on this (https://github.com/odoo/odoo/commits/11.0/addons/web/static/src/fonts) could any of you two check this though?

**Comment by qsm-odoo** [comment]
Yes, I think @aab-odoo is the one for that kind of issue :)

**Comment by bgermann** [comment]
I do not see this addressed. Please reopen.
