### ISSUE TITLE
Website Sale: Any quantity can be added to the cart for a product regardless of the stock available.

### ISSUE THREAD

**Issue by nggopakumar** [odoo/odoo#6383]
Let there be 10 quantity available for a product in the warehouse for a product (say Product A). In the website part this product can be purchased(or can be added to the cart and checkout) with quantity 20(greater than the stock available for the product). If Odoo is considering this as the extra quantity should be purchased from outside and make it available to the customer by the company, there should be any configuration for it like following:
1. If product A is need not to be purchased for a quantity above 10, the customer should be warned that the quantity available for this product is only 10 and could not make a purchase above it and should be prevented to do so.
2. If it is like this: the extra quantity will be purchased by the company and make it available for the customer, then there should be a configuration to do these two ways mentioned. The second one is not common in the case of e-commerce websites.

**Comment by Yenthe666** [comment]
Hi @nggopakumar ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
