### ISSUE TITLE
Change Default value on Currency in KRW

### ISSUE THREAD

**Issue by Linkup2017** [odoo/odoo#63863]
Impacted versions: All

Steps to reproduce:

Current behavior: 

-  Decimal = 2
-  Position = after

Expected behavior: 

- Decimal = 0
- Potion = Before

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/34224366/103251080-850e8c80-49ba-11eb-85b5-15579be15a32.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
Can you add any link supporting this change?

**Comment by Yenthe666** [comment]
I honestly see no good reason to round to a decimal precision of 0 by default? What's your usecase? cc @mart-e

**Comment by Linkup2017** [comment]
Hello.Thanks for your concern. we are Odoo ready partner in S.Korea and first time to create issue. 
I wish that many of Korean user can use easily with Korean localization. 

Regarding Korean currency Won does not use decimal point. Even if formal document such as in tax Bill. 
Rounding value can be from under 0.1 so there are no decimals on monetary(field). 
If you need more information please let me know. 

Here are route, I checked to find res.currency

1. Login to the latest runbot 14.0 with the admin user
2. Open Accounting - Configuration - Setting 
3. active multi currency and click 'activate other currencies(ignore alarm message)
4. search "KRW"
![image](https://user-images.githubusercontent.com/34224366/103267570-1d296780-49f5-11eb-9dbc-a835d2d3f850.png)

**Comment by pedrobaeza** [comment]
We need some official documentation supporting what you say.

**Comment by ggumzangi83** [comment]
Hello. I'm member of Link-up
For currency rule, can you refer as link below?

http://www.londonfx.co.uk/ccylist.html
![image](https://user-images.githubusercontent.com/52647650/103273847-9fb92380-4a03-11eb-84f8-f292711c0fb2.png)

**Comment by Yenthe666** [comment]
Adyen does seem to refer to a rounding of 0 (https://docs.adyen.com/development-resources/currency-codes) but for the rest there seems very little official content about it 🤔 
Same in https://www.localeplanet.com/icu/currency.html and http://www.londonfx.co.uk/ccylist.html
From what I get from it South-Korea rounds to 2 decimals while North-Korea rounds to 2 decimals though.

**Comment by ggumzangi83** [comment]
Please refer ISO Standard document as link below. 

https://developer.cybersource.com/library/documentation/sbc/quickref/currencies.pdf
![image](https://user-images.githubusercontent.com/52647650/103323432-26164980-4a86-11eb-94b4-2800cea47266.png)

Can you kindly feedback to me what kind of document if need more document?

**Comment by pedrobaeza** [comment]
OK, it seems ISO 4217 refers to this the same as 0 decimal places:

https://en.wikipedia.org/wiki/ISO_4217

Let's tag it for Odoo team to check.

**Comment by mart-e** [comment]
@Feyensv weren't you working on a currency refresh PR? One more to take into account

**Comment by Feyensv** [comment]
I've made some changes to the currencies to protect/restrict their modifications, but I don't have anything related to decimal precisions updates :thinking:.
Such a "functional" change is more for @jco-odoo and the accounting team I believe.
