### ISSUE TITLE
markerclusterer.js concerns (no copyright statement)

### ISSUE THREAD

**Issue by onlyjob** [odoo/odoo#6389]
First of all please remove redundant minified [markerclusterer_compiled.js](..//blob/master/addons/website_google_map/static/src/js/markerclusterer_compiled.js): committed minified files is a bad practice just like committing other compiled binaries.

As for uncompressed [markerclusterer.js](../blob/master/addons/website_google_map/static/src/js/markerclusterer.js) there are some licensing concerns -- this file have license but no copyright statement. One can not go without another. File appears to be based on https://gmaps-utility-library-dev.googlecode.com/svn/tags/markerclusterer/1.0/src/markerclusterer.js but not identical to it.
It is important to document the origin of `markerclusterer.js` and determine its copyright owner(s) and their copyright years as well as to confirm license.

`git blame` revealed only one committer -- Christophe Matthieu who might know something about the origins of this file.

**Comment by Yenthe666** [comment]
Hi @onlyjob,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
