### ISSUE TITLE
[Bug Accounting] Getting issue when register payment

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#6395]
Raise a bug when register payment, where invoice had 86 invoice lines.

Accounting - > customer invoice -> create new invoice and 86 invoice lines.

Guide what might be issue,

  File "/home/o/source/v8/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/o/source/v8/odoo/addons/account/account_invoice.py", line 1207, in pay_and_reconcile
    writeoff_acc_id, writeoff_period_id, writeoff_journal_id, name=name)
  File "/home/o/source/v8/odoo/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/o/source/v8/odoo/addons/account/account_invoice.py", line 1143, in pay_and_reconcile
    name = name or self.invoice_line.name or self.number
  File "/home/o/source/v8/odoo/openerp/fields.py", line 757, in __get__
    record.ensure_one()
  File "/home/o/source/v8/odoo/openerp/models.py", line 5152, in ensure_one
    raise except_orm("ValueError", "Expected singleton: %s" % self)

Thanks,

**Comment by tejastank** [comment]
I found code to detect.


    @api.v8
    def pay_and_reconcile(self, pay_amount, pay_account_id, period_id, pay_journal_id,
                          writeoff_acc_id, writeoff_period_id, writeoff_journal_id, name=''):
        # TODO check if we can use different period for payment and the writeoff line
        assert len(self)==1, "Can only pay one invoice at a time."
        # Take the seq as name for move
        SIGN = {'out_invoice': -1, 'in_invoice': 1, 'out_refund': 1, 'in_refund': -1}
        direction = SIGN[self.type]
        # take the chosen date
        date = self._context.get('date_p') or fields.Date.context_today(self)

        # Take the amount in currency and the currency of the payment
        if self._context.get('amount_currency') and self._context.get('currency_id'):
            amount_currency = self._context['amount_currency']
            currency_id = self._context['currency_id']
        else:
            amount_currency = False
            currency_id = False

        pay_journal = self.env['account.journal'].browse(pay_journal_id)
        if self.type in ('in_invoice', 'in_refund'):
            ref = self.reference
        else:
            ref = self.number
        partner = self.partner_id._find_accounting_partner(self.partner_id)
        name = name or self.invoice_line.name or self.number

Here line,         name = name or self.invoice_line.name or self.number

self.invoice_line.name, It seems wrong code here, Does #odoo verify its right code here ?

**Comment by tejastank** [comment]
As I had updated code to...

From:
name = name or self.invoice_line.name or self.number

To:
 name = name or self.number or self.invoice_line.name 

This fixed my issue.


Thanks,

**Comment by max3903** [comment]
Did you make a pull request with your fix ?

**Comment by tejastank** [comment]
No, I had fix code as I had explain and done.
