### ISSUE TITLE
OAuth2 Authentication (auth_oauth): Tokens end up in the server logs

### ISSUE THREAD

**Issue by ghost** [odoo/odoo#63963]
**Tokens end up in the server logs due to inappropriate use of URI query-string parameters**

Impacted versions:
 
 - 14.0 (probably all the others as well)
 
Steps to reproduce:
 
 1. Use the "OAuth2 Authentication" (auth_oauth) module
 
Current behavior:
 
 - Tokens for sure end up in the local Odoo server logs
 - Tokens potentially end up in the remote Oauth2 provider logs as well
 
Expected behavior:
 
 - Tokens NOT being logged

#### Detailed Description of the Issue:

Tokens end up in the logs of odoo server (and potentially in the
remote logs of the Oauth2 provider as well) because the original
`auth_oauth` module sends tokens as URI query-string parameters,
which is discouraged for security reasons. Moreover, it will be
deprecated soon by Google (and other Oauth2 providers will probably
do the same at some point in the future). Relevant Quote
from Google oauth2 documentation[_(1)_][1]:
> After an application obtains an access token, it sends the
> token to a Google API in an HTTP Authorization request header.
> It is possible to send tokens as URI query-string parameters,
> but we don't recommend it, because URI parameters can end up
> in log files that are not completely secure. Also, it is good
> REST practice to avoid creating unnecessary URI parameter names.
> Note that the query-string support will be deprecated on
> **June 1st, 2021.**

[1]:https://developers.google.com/identity/protocols/oauth2#4.-send-the-access-token-to-an-api.

**Comment by Yenthe666** [comment]
@odony this will probably interest you :)
