### ISSUE TITLE
binary field allow to upload pdf and other file types also

### ISSUE THREAD

**Issue by sandippatel27899** [odoo/odoo#63960]
Impacted versions:12

Steps to reproduce:
Go to Sales > Products > Any older product 
edit product
upload any file other than image in main image of product
save the product record

Current behaviour:
gives warning ..that not supported file by widget="image"
but not restrict to save record
it is not showing that file image of product in backend as well as on website so it is affecting website also

Expected behaviour:
we may  restrict when we save the record
or should give other way to only upload images in that particular field.
don't know the answer !

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
How do you it's being saved? If I don't remember bad, the widget doesn't preserve contents.

**Comment by sandippatel27899** [comment]
![Screenshot from 2021-01-13 12-03-31](https://user-images.githubusercontent.com/38600866/104415103-6520c080-5597-11eb-8e2c-31f8c36784d5.png)

yes you are right.  widget doesn't preserve contents. but  new empty record getting create which doesnot have any datas.
just reported because new record gets created which is of no purpose. if this behaviour is intentional then we may close this bug. 
 :+1:

**Comment by pedrobaeza** [comment]
Yes, I think so. The usage is a bit convoluted.
