### ISSUE TITLE
[v8.0][etherpad]Problem with authentication and editOnly mode

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#6399]
Hy,

I'm trying to configure properly the authentication between my odoo and etherpad.
It works perfectly with default options.
Yet I would like to allow only the api to create new pads so I set the editOnly to true : https://github.com/ether/etherpad-lite/pull/222 
I was expecting Odoo to use api to create pads. Yet when I create a new note, impossible to get access to the pad because it hasn't probably been created through the API. Am I wrong?

regards

**Comment by Yenthe666** [comment]
Hi @flotho,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
