### ISSUE TITLE
redundant minified file (jquery.nearest.min.js)

### ISSUE THREAD

**Issue by onlyjob** [odoo/odoo#6401]
Please remove redundant minified file `addons/website/static/lib/nearest/jquery.nearest.min.js` (its uncompressed original is right next to it).

Having minified files in source tree is a bad practice. Just like other pre-compiled binaries, minified javascripts are unreadable, unmodifiable and often non-distributable.

Ironically `website_templates.xml` uses uncompressed file so it is safe to delete minified file (no patching needed).

Thanks.

**Comment by Yenthe666** [comment]
Hi @onlyjob,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
