### ISSUE TITLE
8.0(latest): unable to import companies

### ISSUE THREAD

**Issue by onlyjob** [odoo/odoo#6403]
I'm getting the following error when I'm trying to import companies from .CSV file:

```
Unknown error during import: <class 'openerp.exceptions.except_orm'>: (u'Access Denied', u'The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\n\n(Document type: Partner, Operation: create)') at row 2
```

**Comment by wonderfan** [comment]
This is permission issue

**Comment by onlyjob** [comment]
It looks like permission issue but I can't figure out how/where to overcome it. Unless you prove me wrong I consider this to be a bug. Suggestions are welcome, of course...

**Comment by Yenthe666** [comment]
Hi @onlyjob,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
