### ISSUE TITLE
Fresh install has no settings page

### ISSUE THREAD

**Issue by bamilab** [odoo/odoo#64039]
Impacted versions: 14.0

I'm doing this from Debian 10 (buster), with pretty much

Steps to reproduce:
Assuming you have wkhtmltox already installed manually:
```
git clone -b 14.0 https://github.com/odoo/odoo
cd odoo
virtualenv -p python3 ~/venvodoo
. ~/venvodoo/bin/activate
pip3 install -r requirements.txt
createdb odoo-test
./odoo-bin -d odoo-test --addons-path=addons --db-filter=odoo-test --dev all -i base
```

Current behavior:
When you click on the settings menu in the top left corner, I get the users overview page.

Expected behavior:
Getting into the settings menu should open the settings page.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/66418554/103565329-77786b80-4ec0-11eb-82ac-14fa48baa74f.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question, as this is a change on how v14 works. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
