### ISSUE TITLE
Security Issues on Odoo 10 (Link Manipulation DOM-based and Session token in URL)

### ISSUE THREAD

**Issue by gretheleinstein** [odoo/odoo#64045]
Impacted versions: 10

Steps to reproduce: run Odoo 10 on a VAPT Online Tool

Current behavior: Failed because of Link Manipulation DOM-based and Session token in URL

Expected behavior: Passed or no issues found. 

Any help or suggestion would be highly appreciated. Thank you!

**Comment by pedrobaeza** [comment]
Odoo 10 is out of official support, and see https://www.odoo.com/es_ES/security-report for security related things if applicable to upper versions.

Closing due to this.

**Comment by Yenthe666** [comment]
Plus anything related to security shouldn't be opened up to the public like this anyways. It is a bad practice.

**Comment by gretheleinstein** [comment]
@pedrobaeza Thank you very much for letting me know, will read this.

@Yenthe666 Ohh, I'm sorry. I'm still a beginner on coding and these kind of issues. Thank you for correcting me! I really appreciate it.
