### ISSUE TITLE
Check that module dependencies have been loaded

### ISSUE THREAD

**Issue by dreispt** [odoo/odoo#6406]
When module has dependencies missing in the manifest file, it can result in an error traceback that is very hard to debug.

I t would be very helpful if, during the module loading sequence, a check were made to confirm that the dependencies for the module being loaded are already loaded.

**Comment by alejandrosantana** [comment]
:+1:

**Comment by Yenthe666** [comment]
Hi @dreispt ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
On a sidenote: this has been improved quite a bit in the newest versions though.

Regards,
Yenthe
