### ISSUE TITLE
[All] gevent 1.5.0 not compatible with Python 3.8.x

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#64106]
Impacted versions: At least 14.0 but I assume all

Steps to reproduce: Install Odoo V14 on an Ubuntu 20.04 and run the requirements file. This will install gevent `1.5.0` according to:
https://github.com/odoo/odoo/blob/c37afdf3e9f680cd186872e509c6ab8e47b70782/requirements.txt#L10
However, multiple sources seem to indicate that Python `3.8.x` does not work with gevent `1.5.0`. E.g: https://github.com/gevent/gevent/issues/1260#issuecomment-697346787 

Current behavior: Errors in the log:
```
2021-01-05 17:28:36,382 73666 WARNING ? py.warnings: <frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
```

Expected behavior: Install a higher `gevent` version that is compatible with Python `3.8.x`?
I can't seem to find an exact table that mentions which gevent version to use though..

**Comment by Yenthe666** [comment]
@d-fence can I ask your input/knowledge here please?

**Comment by Yenthe666** [comment]
I did a test by installing the latest `gevent` (20.12.1) and interesting enough this also solves the Longpolling 502 (Bad Gateway) Error messages that I got. It seems that an older `gevent` version directly breaks the longpolling itself too causing the annoying "Connection restored" pop-ups along with networking issues.

**Comment by bobslee** [comment]
I also experience these issues with same setup (versions).
Any news/progress on this?

**Comment by Yenthe666** [comment]
I decided to make an OPW for it (`2428934`)

**Comment by bobslee** [comment]
Thanks @Yenthe666 !
Please could you report progress/updates in this issue?

**Comment by Yenthe666** [comment]
Yes, I will update this issue & will keep them in sync :)

**Comment by avg-odoo** [comment]
> I decided to make an OPW for it (`2428934`)

@Yenthe666 hello, I'm part of the support team.
I wish to update you that your  issue has been forwarded to our bug fix team
Followup will be done through the opw 2428934
Have a nice day

**Comment by bobslee** [comment]
Any news on this issue (OPW 2428934) ?

**Comment by Yenthe666** [comment]
Nope, as usually the support is incredible slow sadly.

**Comment by bobslee** [comment]
Thanks for your answer.

What would be a temporary workaround?
- `pip` install/update specific `gevent` ? Or is fragile and not recommended?
- Use Ubuntu 18.04 or Debian ?

**Comment by Yenthe666** [comment]
I personally just did a `pip` install of the latest `gevent` version through the command line (`pip install gevent==20.12.1`) which works fine :)

**Comment by bobslee** [comment]
I confirm, the `pip install gevent==20.12.1` (upgrade gevent) seems to work fine and no other issues experienced.
So notifications, chatter (longpolling) now works fine.

This also solves the logging issue - Fast subsequent "config" log entries: https://github.com/odoo/odoo/issues/62786

Experienced and tested with: Ubuntu 20.04, Odoo 14
