### ISSUE TITLE
Odoo cannot handle www alias on multi website setup

### ISSUE THREAD

**Issue by NaNraptor** [odoo/odoo#64103]
**Impacted versions:**
13 and 14 (havent tested others)

**Steps to reproduce:**
Create an nginx reverse proxy with two virt hosts files for each domain (with ssl)
The server block should have a server name that looks like this:
`server_name domainname.com www.domainname.net;`
and the other virt host should have one like so:
`server_name domainname2.com www.domainname2.net;`

Create a second website within odoo:
    On website 1 enter the "domain" field to be: `domain.com`
    On website 2 enter the "domain" field to be: `domain2.com`

**Current behavior:**
Go to browser and:
1. navigate to `www.domain.com` - the website that has domain.com field name works as expected (`domain.com` website displayed)
2. navigate to `domain.com` - the website that has domain.com field name works as expected (`domain.com` website displayed)
3. navigate to `www.domain2.com` - the website that has domain2.com INCORRECTLY GOES TO THE WEBSITE UNDER `domain.com` instead of the website under `domain2.com`
4. navigate to `domain2.com` - the website that has domain.com field name works as expected (`domain2.com` website displayed)

**Expected behavior:**
entering www in front of domain2 correctly takes the user to the `domain2.com` website

EDIT: spelling

**Comment by pedrobaeza** [comment]
This is something that you should handle at proxy level, always redirecting at that level from domain.com to www.domain.com, and putting the domain in Odoo as www.domain.com.

Closing this as no Odoo bug, but deployment question.

**Comment by NaNraptor** [comment]
As I mentioned nginx proxy is configured correctly www.domain2.com DOES redirect to domain2.com

however odoo does NOT display the correct website, and that is happening ONLY for the second website and the second domain

**Comment by pedrobaeza** [comment]
Proper proxy configuration will recommend the contrary: redirect from domain.com to www.domain.com. Anyway, the redirection won't be a hard one and will keep in any header the old one that makes odoo to not match the proper website. As said, this is something you need to handle outside Odoo.

**Comment by NaNraptor** [comment]
Could you point me to the code that handles which website gets displayed depending on the headers/url?

I am convinced the issue is within Odoo but cant describe my problem very well

**Comment by pedrobaeza** [comment]
It's inside https://github.com/odoo/odoo/blob/14.0/addons/website/controllers/main.py
