### ISSUE TITLE
Odoo Help Forum - Trending

### ISSUE THREAD

**Issue by zbik2607** [odoo/odoo#6410]
The same posts on many pages when "by relevance" sorting (Trending menu)!?

Today, for example post: https://www.odoo.com/forum/help-1/question/legal-reports-in-excel-83466, but not only.

**Comment by Yenthe666** [comment]
Hi @zbik2607,

Thanks for the report.
This should have been handled ages ago but nobody ever responded here. Working fine now.

Regards,
Yenthe
