### ISSUE TITLE
Typo in SQL query in account_check_printing module

### ISSUE THREAD

**Issue by dloewen** [odoo/odoo#64113]
On this line `movE.id` should be `move.id`.

https://github.com/odoo/odoo/blob/a23a47457d98aba4ec643f4422f3735d98fab2b4/addons/account_check_printing/models/account_payment.py#L123

**Comment by pedrobaeza** [comment]
Is that breaking anything?

**Comment by dloewen** [comment]
@pedrobaeza technically not, since column names are case-insensitive in PostgreSQL if not quoted.

**Comment by pedrobaeza** [comment]
Then nothing to repair. If you want to fix the type, you can put a PR over master branch, but if nothing is broken, this kind of improvements is not allowed on stable branches.

Closing thus.
