### ISSUE TITLE
[14.0] account: cash statements open the bank statements action

### ISSUE THREAD

**Issue by eefahd** [odoo/odoo#64118]
Impacted versions: 14.0

Steps to reproduce:
- Open the accounting dashboard.
- Open the 'Cash' journal menu then press Statements under the View tab.
- The 'Bank Statements' action will be open.

Current behavior:
- The 'Bank Statements' action will be open.

Expected behavior:
- The 'Cash Statements' to be open.

This bug is related to the pull request [#61121](https://github.com/odoo/odoo/pull/61121) which passes the bank statement action 'action_bank_statement_tree' by the context while we need the cash statement 'action_view_bank_statement_tree' instead.

**Comment by Yenthe666** [comment]
@william-andre @oco-odoo for you guys :)

**Comment by william-andre** [comment]
@eefahd The only difference is the title of the tree view, right?

**Comment by eefahd** [comment]
@william-andre Actually the important thing is the domain and the context of the action which are [('journal_id.type', '=', 'bank')] and {'journal_type':'bank'}. This causes the cash statements to disappear.
