### ISSUE TITLE
[8.0] Partner=False on Picking for purchase order

### ISSUE THREAD

**Issue by ernesto-gm** [odoo/odoo#6412]
**Partner=False on "Receipt in 2 steps" for purchase order**

Impacted versions:
- 8.0

Steps to reproduce:
1. Create a new Purchase order
2. Go to "Deliver To" --> go to Warehouse --> click on Routes
3. Edit "Receipt in 1 step"
4. Create a push rule with to send from an internal location to other internal location
5. Create new Purchase Order and assign the "Deliver To" edit
6. Confirm and receive the products
7. Search all transaction where Source Document contains "#PO"
   https://www.youtube.com/watch?v=IVT3yvWKjUU&feature=youtu.be

Current behavior:
- The partner of only one picking is set with the supplier of Purchase Order.

Expected behavior:
- The partner of all pickings is set with the supplier of Purchase Order.

**Comment by nim-odoo** [comment]
Hello,

By convention, the partner is not set on internal moves, so this can be considered as a normal behavior. (@jco-odoo)

Regards,
Nicolas

**Comment by Yenthe666** [comment]
This was already answered - just not closed. 😉
