### ISSUE TITLE
As Purchase User, I cannot create a Purchase Order

### ISSUE THREAD

**Issue by jcdrubay** [odoo/odoo#64135]
# Impacted versions:

14 enterprise

# Steps to reproduce:

- Create a user with ONLY the group Purchase User
- With developer mode, ensure that the user does NOT have the group Contact Creation
- Login with the newly created Purchase User
- Try to create a new purchase order (Request for Quotation) for an EXISTING supplier
- You will get an Access Error: You are not allowed to modify 'Contact' (res.partner) records.

While the runbot build is active:

- https://5634380-14-0.runbot50.odoo.com/
- select database `5634380-14-0-all`
- login / password: `purchase@komit-consulting.com` / `purchase@komit-consulting.com`

# Current behavior:

Access Error related to partner modification while I am only creating a Purchase Order (not trying to change a partner)

# Expected behavior:

No access error and be able to create the Purchase Order

# Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/1765420/103757401-4d9b8200-5043-11eb-8f24-ff914ba5516c.png)

**Comment by sswapnesh** [comment]
I can confirm this issue. 

This is happening due to writing related fields on Partner

https://github.com/odoo/odoo/blob/755bdbeb04a769bf1fcf9157f74d6a5deb4ad48d/addons/purchase/models/purchase.py#L135-L136

**Comment by pedrobaeza** [comment]
Yeah, they should be `readonly=True` or `related_sudo=True`

**Comment by sswapnesh** [comment]
I think related_sudo=True is just to Read field's value.

This should be handled like this https://github.com/odoo/odoo/commit/2a8b56174609d15bf1c38e7b47515b397f40b707
