### ISSUE TITLE
[8.0] Wrong 'Group by' partner on invoice list view

### ISSUE THREAD

**Issue by fclementic2c** [odoo/odoo#6415]
This Group by must aggregate by legal entity instead of partner and contact.
Thanks

![1](https://cloud.githubusercontent.com/assets/5735158/7268732/cebfa698-e8cc-11e4-8ad1-7bad598899c0.png)

**Comment by flotho** [comment]
Hy @fclementic2c ,

I almost agree with you. Most of my customers are asking for this. Additionnaly they also want to group by partner.
So both are useful FMO.

Regards

**Comment by Yenthe666** [comment]
Hi @fclementic2c,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
