### ISSUE TITLE
[8.0] Invoice's creation problem starting from the customer's form

### ISSUE THREAD

**Issue by francoislawarree** [odoo/odoo#6420]
Hello,

We have detected a problem when you want to create an invoice by starting from the partner form (in the Sales module) and click on the invoice button.

![brx_screen](https://cloud.githubusercontent.com/assets/11072956/7271928/45643a60-e8e7-11e4-8631-874b54f80204.png)

![brx_screen2](https://cloud.githubusercontent.com/assets/11072956/7271959/71f101c6-e8e7-11e4-8eb2-2145a04ab5cf.png)

The button used to create new invoice can't determine which type of invoice should be created (Customer invoice/Refund or Supplier invoice/Refund). 

![brx_screen3](https://cloud.githubusercontent.com/assets/11072956/7272082/58bee1fe-e8e8-11e4-9f95-62cf99532ee0.png)

And the problem occurs due to a bad default invoice's template used to create the new invoice (purchase template invoice used). 

This behaviour isn't user friendly, because it oblige the user to not start from the partner form to create directly the good invoice's type.

Regards,

François

**Comment by beledouxdenis** [comment]
Hello François,

This issue is solved with the below revision:
296130fbd30e2603211ea7ce18137d32505290f0

Regards,
