### ISSUE TITLE
Odoo v8  not working fine :Register payement?

### ISSUE THREAD

**Issue by m3asmi** [odoo/odoo#6421]
follow the instruction in a new databes as the steps

```
install new database with account_vocher module

select Maroc accounting package

create new invoice

register payement for the invoice

check if the payement are listed on the payements tab
```

I make the payement but the balance stel the same and there is no payement lines in the payements tab!!

**Comment by Yenthe666** [comment]
Hi @m3asmi,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
