### ISSUE TITLE
[14.0] number the lines in RFQ, Orders, Invoices, etc.

### ISSUE THREAD

**Issue by zeroheure** [odoo/odoo#64233]
Impacted versions: 14

Trying to find a line inside a long invoice is a pain. Supplier talk about line 53 and one must manually count to check that line. Please add numbers in front of items or lines in RFQ, orders, invoices, etc.

**Comment by pedrobaeza** [comment]
IMO it's a mistake to talk in that terms. You should talk instead about the line of the product X or with reference Y. Any way, this has been talked other times and there's no plans to support this on Odoo itself, but I remember an OCA module about that.

Closing then.

**Comment by Yenthe666** [comment]
Yup. Alternatively you could remove the widget from the sequence to see an actual number to reference or you could add a custom field that auto-numbers if you really want/need this.
