### ISSUE TITLE
Tests fail/pass randomly (inconsistent caching)

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#64265]
Impacted versions:
14.0
Steps to reproduce:
for example, install standard module `test_access_rights` and run all its tests multiple times.

Current behavior:
Tests sometimes pass, sometimes fail when no data/code is changed.

It throws traceback like this:

```python
2021-01-08 13:05:15,307 110338 ERROR address_lau odoo.addons.test_access_rights.tests.test_check_access: ERROR: TestAccess.test_check_access
Traceback (most recent call last):
  File "/home/oerp/odoo14/odoo/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/home/oerp/odoo14/odoo/odoo/tools/func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
  File "/home/oerp/odoo14/odoo/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: ('ir.default', <function IrDefault.get_model_defaults at 0x7f4fb019cf70>, 1, 1, 'res.partner', False)

During handling of the above exception, another exception occurred:
```

Expected behavior:
Tests should always pass or fail all the time if no data/code is changed.

Support ticket number submitted via odoo.com/help (optional): #2429860

P.S. note this problem is happening across whole Odoo, not just `test_access_rights` module. Noticed same behavior on own modules while writing unittests.

**Comment by pedrobaeza** [comment]
I don't think this is an error, but the way tests work. They are not re-entrant, and depends on the previous state. Example: a required field in a model that is added by module A, but that module is not loaded yet in registry and the default is not applied. Result: the DB constraint is preventing the record creation.

**Comment by oerp-odoo** [comment]
@pedrobaeza how can proper tests work this way? It should not depend on previous state, because after tests are run, it should clear all changes and if need to - clean up cache etc. So next time you run it, it will pass or fail same way.

But if what you are saying is true, it then should fail/pass in consistent manner either way. For example, first time it passes, then fails, then passes or some other variation (if some previous condition needs to be met or something). But it looks like it fails/passes in inconsistent manner too. 

P.S. to me it looks like it could have something to do with new caching/in memory use. In older versions, it was not working this way. Because I migrated module from version 12 and same behavior started on 14 as I described here.

**Comment by pedrobaeza** [comment]
With current design, tests must be executed only at install time.

**Comment by oerp-odoo** [comment]
So thats a regression of tests usability now. Tests run faster, but are less useful. Is there maybe a `developer` option to force use tests old way without putting everything in memory (so they run slower, but are actually consistent)?
Because when you are developing a module, you rerun same tests over and over again. What would then be workflow with such design choice?..

**Comment by pedrobaeza** [comment]
No, that's happen the same on previous versions. Maybe you haven't faced such problem, but it was the same.

**Comment by oerp-odoo** [comment]
Strange. Maybe I had few similar cases. But now I see lots of it and my colleagues also noticed it. Does it matter if you rerun tests more frequently on short amount of time? Maybe thats the case, cause I was debugging this behavior in such way.

**Comment by pedrobaeza** [comment]
That shouldn't count. Several things you have to take into account:

- Don't run tests with workers>0
- If there are installed modules that adds required fields, the trick is to temporarily add them as dependencies of your module and then it won't be a problem.

**Comment by oerp-odoo** [comment]
I know these problems. For first one, I never run with workers>0. For second also know this issue, but I'm getting such errors even taking in consideration mentioned limitations.

For example if I run same test let say 10 times, it can fail one or two times. Throws that error, then see:

```
  File "/home/oerp/odoo14/odoo/odoo/addons/base/models/ir_default.py", line 147, in get_model_defaults
    for row in cr.fetchall():
psycopg2.ProgrammingError: no results to fetch
```
And then it explodes with maximum recursion exceeded. 

I guess will have to live with this:)

**Comment by pedrobaeza** [comment]
I have never experimented that problem till now, but on 14.0 my development cycle is still very limited. Some module migrated and run tests in non an intensive way.

**Comment by Elkasitu** [comment]
Unfortunately at this time tests within Odoo are not idempotent, as @pedrobaeza said, this means that you **shouldn't** run tests on databases that are not brand new, this happens across all Odoo versions.

Ideally they would be idempotent, but currently we have no plans to do so, so I'm closing this issue for now.
