### ISSUE TITLE
PO status is wrong when draft invoice is deleted

### ISSUE THREAD

**Issue by ybofr** [odoo/odoo#6426]
Hello,

I have tested this in runbot:
a. Create a PO with invoice control on PO lines
b. Goods receipt
c. Create the invoice
d. Delete the invoice. There is nothing to block this action, but the status of the PO is not changed and there is no way to recreate the invoice.

This causes a lot of trouble by customers, as they delete a document because it is wrong and then they cannot recreate it and they cannot change the status manually to reset it or to put it in exception.

Thanks for the correction

**Comment by Yenthe666** [comment]
Hi @ybofr,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
