### ISSUE TITLE
[14.0] sale : update price doesn't appear in new order

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#64269]
**Impacted versions**: 14.0 (and maybe other)

**Steps to reproduce:**
- Go to runbot: https://5668596-14-0.runbot47.odoo.com/web?#id=&action=1116&model=sale.order&view_type=form&cids=1&menu_id=791
- activate pricelist
- go to sale module
- click create a new sale order (don't save)
- add partner and one product (don't save)
- change pricelist
--> issue the button update_price doesn't appear

It works if you save before.

Because self._origin.pricelist_id is empty (new record). https://github.com/odoo/odoo/blob/14.0/addons/sale/models/sale.py#L449

@rco-odoo 

Support ticket number submitted via odoo.com/help (optional):
#2429987

**Comment by sswapnesh** [comment]
@fmdl https://github.com/odoo/odoo/issues/74924 is introduced due to this fix
