### ISSUE TITLE
[8.0] couldn't see the correct sale order lines of product if the product_id and product_tmpl_id are not the same.

### ISSUE THREAD

**Issue by fanha99** [odoo/odoo#6429]
Hi All,
after upgrade from v7 to v8. In my database, there is some product with the product_id and product_tmpl_id are not the same. 

for ex: 
A: product_id = 101, product_tmpl_id = 88
B: product_id = 120, product_tmpl_id = 101

when I check the sale order lines of B, it will show the sale order lines of A, because product_id A is 101 and the same as product_tmpl_id of B

when I check the sale order lines of A, it will show the error message because of there is no product with product_id = 88

![database](https://cloud.githubusercontent.com/assets/1172848/7278830/1ceb7d68-e942-11e4-9b07-7c65f44415ba.png)

**Comment by flotho** [comment]
Hy,

I have also the problem.
