### ISSUE TITLE
In odoo, the operator  disconnected and the chatBox of the website will not be started. How can the chatBox be opened all the time?

### ISSUE THREAD

**Issue by fanrong1993** [odoo/odoo#64298]
In odoo, the operator  disconnected and the chatBox of the website will not be started. How can the chatBox be opened all the time?

**Comment by Yenthe666** [comment]
Please fill in a detailed report with reproducable steps on runbot.odoo.com. If we don't get clear steps to reproduce it this issue will be closed off in a few days. We don't have enough info to help you
