### ISSUE TITLE
Procurement is not properly recreated after changing the product

### ISSUE THREAD

**Issue by ybofr** [odoo/odoo#6430]
This was tested in runbot
1. create a product
2. create a sales order
3. The delivery is automatically created.
4. cancel the linked procurement
5. change the product to "call for bid"
6. recreate the delivery
7. The procurement is not recreated, but only reactivated. This way, the data on the product form are not read again and no call for bid is created.

**Comment by Yenthe666** [comment]
Hi @ybofr,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
