### ISSUE TITLE
Purchasing: Schedule date is not copied from the call for bid

### ISSUE THREAD

**Issue by ybofr** [odoo/odoo#6431]
Tested on runbot.odoo.com
Impacted versions:
- 8.0
  Steps to reproduce:
- create a procurement for a call for bid material
- create call for bid with a given schedule date
  1. Create the RFQ

Current behavior:
- The schedule date is not present in the RFQ.

Expected behavior:
- The schedule date should be used in the RFQ

**Comment by Yenthe666** [comment]
Hi @ybofr,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
