### ISSUE TITLE
[WISHLIST] Show name_get value of referenced record of Many2oneReference fields on FROM VIEW.

### ISSUE THREAD

**Issue by tanghulu0608** [odoo/odoo#64325]
Impacted versions:
[13.0] maybe all

Steps to reproduce:
Put a Many2oneReference fields on a form view, then show an integer on the form.

Expected behavior:
Put a Many2oneReference fields on a form view, then show name_get value of referenced record, like normal many2one field.

Video/Screenshot link (optional):
<img width="454" alt="image" src="https://user-images.githubusercontent.com/5561864/104176436-3218e880-5442-11eb-8ee8-25596bff54a2.png">

**Comment by pedrobaeza** [comment]
AFAIK, with the proper widget, this happens.

**Comment by tanghulu0608** [comment]
@pedrobaeza I agree with you. 
Wish odoo will add this feature. Only show the integer on the form is useless.

**Comment by pedrobaeza** [comment]
It's already implemented AFAIK. As said, use the proper widget (not sure if `reference`).

**Comment by tanghulu0608** [comment]
Thanks. Let me try .

**Comment by tanghulu0608** [comment]
I use this code` widget="reference"` , it not works.
Maybe we should make a new widget.

**Comment by pedrobaeza** [comment]
Menus contain a reference field, and it acts as many2one on view mode:
![Selección_010](https://user-images.githubusercontent.com/7165771/104283358-b3a75f80-54b0-11eb-8bb2-f2c59fc6f887.png)
and on double selection on edit mode:
![Selección_011](https://user-images.githubusercontent.com/7165771/104283398-c326a880-54b0-11eb-9fb6-de90d389d76b.png)
so it's working as expected.

https://5697553-13-0.runbot45.odoo.com/web?debug=1#id=63&action=27&model=ir.ui.menu&view_type=form&cids=1&menu_id=

**Comment by tanghulu0608** [comment]
hello @pedrobaeza ,
What I am talking about is the field type: `Many2oneReference`. It is different with `Many2one` or `Reference`.

https://github.com/odoo/odoo/blob/f29c6b1ffcbcfdf12d848df8ee427cc11d2df123/odoo/fields.py#L2504
https://github.com/odoo/odoo/blob/f29c6b1ffcbcfdf12d848df8ee427cc11d2df123/odoo/fields.py#L2747
https://github.com/odoo/odoo/blob/f29c6b1ffcbcfdf12d848df8ee427cc11d2df123/odoo/fields.py#L2393

**Comment by pedrobaeza** [comment]
No, that one is not intended to have such widget.

**Comment by tanghulu0608** [comment]
OK, Thanks.😳

**Comment by StarV5s** [comment]
There is a module in odoo app store that fit your needs, named "generic_m2o".
