### ISSUE TITLE
[8.0][9.0][Wishlist]Implement pandas or bdateutil in Odoo framework for domain attribute in xml views

### ISSUE THREAD

**Issue by 10537** [odoo/odoo#6434]
Hello everybody,

Only as wishlist, it's important that Odoo can accept bussines days in the relativedelta in xml views, because the actual support don't provide this behavior for example:

Actual behavior:

```<filter string="-2 Working Days" name="date_delivery" domain="[('date_delivery','=', (context_today - relativedelta(days=2).strftime('%%Y-%%m-%%d')))]"/>```

This filter get the all register from today - 2 days no matter if they are non-working days.

New behavior:

`<filter string="-2 Working Days" name="date_delivery" domain="[('date_delivery','=', (context_today - relativedelta(bdays=2)).strftime('%%Y-%%m-%%d'))]"/>`

or if you adds pandas library in Odoo framework:

`<filter string="-2 Working Days" name="date_delivery" domain="[('date_delivery','=', (context_today - BDay(2)).strftime('%%Y-%%m-%%d'))]"/>`

with this options we can get the minus 2 working days and other options available in pandas library, you can use also bdateutil for this improvement, I hope my suggestion can be help for you, Thanks for read.

**Comment by Yenthe666** [comment]
@mart-e would this ever be considered for implementation? 
@10537 sorry for the very late reply!

**Comment by mart-e** [comment]
Sorry but that kind of advanced filtering based on wordays should not be applied at the filter level but should relies on code.
We have the `resource` module to be able to manage week schedules and when employees are working. It is a bit complex but everything should be there to be coded in a module.

So far, no plan to add this in the filters, sorry.
