### ISSUE TITLE
CURRENCY ODOO 14.0 Sale Margin

### ISSUE THREAD

**Issue by jeffryjdelarosa** [odoo/odoo#64350]
Impacted versions:
14.0
Current behavior:
@Feyensv @pedrobaeza I don't know if I have a wrong configuration on the currency, This is a I made.

I activate multi currency:

My Country is DOP Rates = 1.00 this is the default currency.
Foreigner Currency is USD = 0.017094017094

When I create an Order, by the default currency is DOP on selecting the pricelist. : Sometime the users forget to change the currency to USD, so once the users change the pricelist. the purchase_price store the the currency DOP instead of changing to USD.
The users have to remove and reselect the product for changing the purchase_price to USD currency.

Once the order is confirm the line purchase_price, margin and the margin on the order, it get it wrong.

1

Expected behavior:
the line purchase_price, margin and the margin on the order, should be on Foreigner currency.

Video/Screenshot link (optional):
Check on Runbot
https://5696659-14-0.runbot57.odoo.com/web?debug=1#id=51&action=1112&model=sale.order&view_type=form&cids=1&menu_id=79

@pedrobaeza

**Comment by pedrobaeza** [comment]
Well, this is the same question as when changing pricelist and prices not being recomputed. Does Odoo need to recompute all or do you only want to apply the new pricelist to new items? Odoo chooses second approach, but I want to have a second opinion on this.

**Comment by jeffryjdelarosa** [comment]
@pedrobaeza well om Version 12.0 before there's was currency_id available to change, but now it depends of the pricelist_id. okey find on this way. 

While Im adding or changing the product on the order line, the line.purchase_price, margin compute well, but once the action_confirm instead of take the currence_id it changes to the company_currency.

So as you can see on the link it brings negative and are not in the order currency it takes the company.

Now I can see once I create the invoice the amount and total is wrong, it should be in the foreigner currency.

**Comment by pedrobaeza** [comment]
I don't get what you are trying to explain. Please expose the problem in clear English with an example reproducing the problem and whole detailed written steps.

**Comment by jeffryjdelarosa** [comment]
Ok step by step.

I have multi currency activated.

The currency of my country is Pesos.

I have updated the foreign currency rates.

We sell in dollars.

I installed the Sale Margin module.

When I create an order form when confirming the margins are not correct. Then when creating the invoice the invoice the articles are in the foreign currency but the total is in the currency of my country, that is, it should have the foreign currency.

You can see the link in Runbot so you can determine why the margin is wrong.

![error_margin](https://user-images.githubusercontent.com/16416149/104209855-96b75180-5408-11eb-8793-2356cb07b44a.png)

**Comment by pedrobaeza** [comment]
So you are telling that the invoice is in one currency and the sales order in another currency?

**Comment by jeffryjdelarosa** [comment]
yes that's write.

**Comment by pedrobaeza** [comment]
Then this is definitively something not covered and won't be "fixed", as there are basic rules you have to respect, and one of them is to not change the currency from sales order to invoice.

**Comment by jeffryjdelarosa** [comment]
@pedrobaeza could you please explain how can I fix the the margin?, could please a least check the sale order of the link I write didn't change the currency manually, I just select the pricelist in the foreigner currency, and the margin show negative and it shows the company.

**Comment by pedrobaeza** [comment]
Sorry, I hardly understand your English, but you should make questions on Odoo forums.

**Comment by jeffryjdelarosa** [comment]
okey fine. But please install the Sale Margin Module, update the rates and create an order with foreigner currency and you will see the margin will be wrong computed

**Comment by jeffryjdelarosa** [comment]
@Feyensv check please

**Comment by jeffryjdelarosa** [comment]
@fpodoo Hi, I need help on this case.

**Comment by Yenthe666** [comment]
Please don't start randomly pinging people across the ecosystem to find yourself a solution. Pedro answered you & suggested to ask it on the help forums :)

**Comment by jeffryjdelarosa** [comment]
thanks @Yenthe666 for your answer I didn't pinged anyone randomly, there's a issued with sale margin using multi currency, @pedrobaeza didn't check or see the image I uploaded before. I will solve this problem I will making a PR, but before close any issue so quick without testing or what is wrong, I think other people can handle the situation but the issue is still there. even I tried on the runbot version. if you can check let me know.

**Comment by Yenthe666** [comment]
So you decide to ping the CEO of a company who manages 1.000+ people? 😅 Show us a way to reproduce it on a runbot instance with reproducable steps & if I can reproduce it i'll reopen it but it looks like misuse right now.

**Comment by jeffryjdelarosa** [comment]
Simple Step

- Install Sale Margin (the module that has the issue).
- Install Inventory.
- Active Multi Currency. 
- Update rates of any foreign currency.
- Create an order with the foreign currency.
After do this step you will get a wrong margin computed. 

- Create an invoice to the order created.

Here all the products on subtotal line will be fine but on amount_untaxed and amount_total order will be on your company default currency instead on the foreign currency you've already selected.

I reproduced in my instance, runbot, and others odoo database version 14.

**Comment by Yenthe666** [comment]
Seems to work a bit different/weird in V14 compared to previous versions yeah. Example done on runbot:
![image](https://user-images.githubusercontent.com/6352350/104468093-5a762380-55b7-11eb-8f3d-61df2d8c09c6.png)


It sets the full unit price as margin while the cost price of the product is 70 (EUR).. @pedrobaeza maybe debatable?

**Comment by pedrobaeza** [comment]
I miss the cost price at sales order line for tracing the problem.
