### ISSUE TITLE
Divide by Zero Introduced

### ISSUE THREAD

**Issue by jspizziri** [odoo/odoo#6435]
@jco-odoo 

In this commit https://github.com/odoo/odoo/commit/1ac4d31db739769ba403c23fc795426051238dcd, a divide by zero issue was introduced in that line.

A potential use case is users entering a product with a zero value on a SO so that they can receive inventory (that has been drop shipped from the manufacturer) on the same sales order.

**Comment by jspizziri** [comment]
Either the divide by 0 needs to be fixed or entering 0 qty on a sales order needs to be disallowed.

**Comment by Yenthe666** [comment]
Hi @jspizziri,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
