### ISSUE TITLE
odoo.py scaffold - No handlers could be found for logger

### ISSUE THREAD

**Issue by eduardobape** [odoo/odoo#6436]
When I'm trying to execute the 'odoo.py scaffold mymodule' command, I'm getting this message:
`No handlers could be found for logger "openerp.addons.hw_escpos.controllers.main"`

The list of files and directories for the module are created correctly, but I don't know why I get this message in the command shell after executing odoo.py scaffold.

**Comment by xmo-odoo** [comment]
Because the scaffold command does not configure the logging subsystem, and escpos happens to log a message on import (probably to warn that the usb support isn't installed).

It's a minor warning which you can safely ignore.

**Comment by eduardobape** [comment]
Thanks for your answer @xmo-odoo
