### ISSUE TITLE
[14.0] website: images stretched depending on title size

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#64375]
Impacted versions: 14.0

Steps to reproduce:
1. Login to the latest runbot 14.0 with the admin user
2. Go to the website and drag the "Showcase" block on the page
3. Set the title of the first, left, block to "First feature that's a bit long, ya'll"
4. Set an image on the first, left block, I used this one: 
![image](https://user-images.githubusercontent.com/6352350/104289076-f79e6280-54b8-11eb-87a6-e9f38decdfb8.png)

5. Switch from desktop to the mobile view

Current behavior: The image is stretched out because the title is quite long & takes up two lines. It is now pulled out of proportion. You can also get this issue when you make a really long title on desktop as it also takes up too much size and makes a second line then.
Mobile:
![image](https://user-images.githubusercontent.com/6352350/104288990-dc335780-54b8-11eb-85c2-6710ffd1fa0a.png)
Desktop:
![image](https://user-images.githubusercontent.com/6352350/104289023-e9504680-54b8-11eb-8fc1-a9d133d656e6.png)

Showcased on https://5700577-14-0.runbot41.odoo.com/#

Expected behavior: The image is not stretched out, neither on mobile nor or desktop.

**Comment by Yenthe666** [comment]
OPW `2447087`

**Comment by JKE-be** [comment]
Fixed by https://github.com/odoo/odoo/pull/67234
