### ISSUE TITLE
Bug when input new quantity on Produce wizard

### ISSUE THREAD

**Issue by cuongbui-novobi** [odoo/odoo#64468]
Impacted versions: 13.0

Steps to reproduce:
- Create a new MO, click Produce.

- Add a new component line (can be the same or different product).

- Change the produce quantity (see Capture0.PNG)

Current behavior:
- An error occurred (see Capture.PNG)

Expected behavior:
- Users can proceed the MO as usual, or a different warning is shown.

Video/Screenshot link (optional):
![Capture0](https://user-images.githubusercontent.com/54257731/104448800-3541df00-55d0-11eb-878e-bd2975865156.PNG)
![Capture](https://user-images.githubusercontent.com/54257731/104448809-3a9f2980-55d0-11eb-83fa-79b3ee4d4be0.PNG)

Support ticket number submitted via odoo.com/help (optional):
2439172

**Comment by pedrobaeza** [comment]
Do you have latest Odoo code?

**Comment by cuongbui-novobi** [comment]
> Do you have latest Odoo code?

Hi @pedrobaeza, i did a test on the lastest Odoo 13.0 enterprise runbot.

**Comment by ryv-odoo** [comment]
Thank you for the report

It seems that it was introduced by https://github.com/odoo/odoo/pull/60403 (@kitan191 )
The `_workorder_line_ids()`  can return either `mrp.workorder.line` or `mrp.product.produce.line` but `finished_workorder_id` only exist for `mrp.workorder.line`. 

cc @Whenrow

**Comment by kitan191** [comment]
This PR https://github.com/odoo/odoo/pull/64906 is fixing the issue.
