### ISSUE TITLE
[V8]Project team members are not added to the followers of the project/tasks

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#6450]
Hy,

freshly tested here : http://64383-8-0-ca5562.runbot.odoo.com/web?db=64383-8-0-ca5562-all#id=15&view_type=form&model=project.project&menu_id=357&action=378
In V7, adding users to the team member of the projetct automatically added them in followers. It's no more the case.
Additionnally, they should also be added to followers of tasks.

regards

**Comment by Yenthe666** [comment]
Hi @flotho,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
