### ISSUE TITLE
bug in `fields.Selection` with both space and underscore as values

### ISSUE THREAD

**Issue by mrm-david** [odoo/odoo#64567]
bug in `fields.Selection` with both space and underscore as values

## Impacted versions:

14.0

## Steps to reproduce:

Install linked module  [bug_odoo.zip](https://github.com/odoo/odoo/files/5815579/bug_odoo.zip)

## Current behavior:

Module install crashes with the following message from postgresql : 

```text
ERROR: ON CONFLICT DO UPDATE command cannot affect row a second time
HINT: Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
```

Query that triggers this error :

```sql
INSERT INTO ir_model_data (module, name, model, res_id, noupdate)
VALUES ('bug_odoo', 'selection__bug_odoo__some_field___', 'ir.model.fields.selection', 228, false), ('bug_odoo', 'selection__bug_odoo__some_field___', 'ir.model.fields.selection', 229, false)
ON CONFLICT (module, name)
DO UPDATE SET write_date=(now() at time zone 'UTC') 
```

Probable cause: 

This is the model : 

```python
from odoo import models, fields


class BugOdoo(models.Model):
    _name = 'bug.odoo'

    some_field = fields.Selection([(' ', 'value 1'), ('_', 'value 2')])
```

When giving a name to the selection value, odoo doesn't like the space and replaces it by an underscore. Unfortunately, there is also an underscore in the selection leading to a duplicate name.

## Expected behavior:

Module installs

## Video/Screenshot link (optional):

N/A

## Support ticket number submitted via odoo.com/help (optional):

N/A

**Comment by pedrobaeza** [comment]
Please don't open again the same issue.

**Comment by mrm-david** [comment]
@pedrobaeza sorry, for the first issue github returned me a 404, I didn't know it was saved.

**Comment by pedrobaeza** [comment]
Please see my answer, as I'm afraid you have to look for other selection values.
