### ISSUE TITLE
Bug in fields.Selection with both space and underscore as values

### ISSUE THREAD

**Issue by mrm-david** [odoo/odoo#64565]
## Impacted versions:

14.0

## Steps to reproduce:

Install linked module  [bug_odoo.zip](https://github.com/odoo/odoo/files/5815579/bug_odoo.zip)

## Current behavior:

Module install crashes with the following message from postgresql : 

```text
ERROR: ON CONFLICT DO UPDATE command cannot affect row a second time
HINT: Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
```

Query that triggers this error :

```sql
INSERT INTO ir_model_data (module, name, model, res_id, noupdate)
VALUES ('bug_odoo', 'selection__bug_odoo__some_field___', 'ir.model.fields.selection', 228, false), ('bug_odoo', 'selection__bug_odoo__some_field___', 'ir.model.fields.selection', 229, false)
ON CONFLICT (module, name)
DO UPDATE SET write_date=(now() at time zone 'UTC') 
```

Probable cause: 

This is the model : 

```python
from odoo import models, fields


class BugOdoo(models.Model):
    _name = 'bug.odoo'

    some_field = fields.Selection([(' ', 'value 1'), ('_', 'value 2')])
```

When giving a name to the selection value, odoo doesn't like the space and replaces it by an underscore. Unfortunately, there is also an underscore in the selection leading to a duplicate name.

## Expected behavior:

Module installs

## Video/Screenshot link (optional):

N/A

## Support ticket number submitted via odoo.com/help (optional):

N/A

**Comment by pedrobaeza** [comment]
Yes, they are forbidden values. Use another.

Closing as framework limitation.

**Comment by mrm-david** [comment]
I understand, though it is not obvious from reading https://www.odoo.com/documentation/14.0/reference/orm.html

**Comment by pedrobaeza** [comment]
You can add a PR for explicitly state that, but sincerely I would never though on using space or underscore as selection value.

**Comment by mrm-david** [comment]
In my case I have a setting per customer for a character as separator beween a product code and a product size. That's used when exchanging files with them in a way they can understand. Some customers use a space, others an underscore, some a dash, some another char, but since I don't wan't to allow anything, I wanted to have a selection rather than a field.Char

I will find a way around it.
