### ISSUE TITLE
[14.0] l10n_mx_edi: XML generated should not be Foreign Commerce

### ISSUE THREAD

**Issue by suniagajose** [odoo/odoo#64585]
Impacted versions:
14.0
Steps to reproduce:
1. Install Mexican Localization EDI
2. Create an customer invoice for a MX partner.
3. Validate invoice
4. Send EDI document

Current behavior:
A XML for foreign commerce is generated

Expected behavior:
Should no be a foreign commerce XML, because is not a Foreign Customer.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):
Odoo Ticket #2440247

**Comment by suniagajose** [comment]
@luistorresm please help me following this isse.

Regards,

**Comment by william-andre** [comment]
https://github.com/odoo/enterprise/pull/15854
