### ISSUE TITLE
[14.0] l10n_mx_edi: Odoo try to stamp an invoice already stamped (infinity loop)

### ISSUE THREAD

**Issue by suniagajose** [odoo/odoo#64586]
Impacted versions:
14.0

Steps to reproduce:
1. Install Mexican Localization EDI
2. Create an customer invoice for a MX partner.
3. Validate invoice
4. Send EDI document (but webservice not send response back)
5. Try to send again.

Current behavior:

The XML is generated without fiscal stamp, and EDI Documento tab show this error:

> PAC failed to sign the CFDI:
> Code : 307
> Message : El CFDI contiene un timbre previo

The step 5 still happen over and over again automatically by Odoo, and webservice never return the properly stamped XML

Expected behavior:
If in step 4 the webservice received EDI document, in the step 5 Odoo should generate the XML stamped.

Video/Screenshot link (optional):
1. Step 5 over and over again by Odoo.
https://drive.google.com/file/d/1p5TLvJKtcQp2We4mP-5IB3VCbrbbe7Is/view

2. EDI document status:
https://drive.google.com/file/d/1zqI0dmfZsWHZCcdhelj8TEGIzzNZLPa2/view

3. XML without stamp:
https://drive.google.com/file/d/109m-T0ehqPVJ3dq_XdfDUdoHURg_fx4M/view

Support ticket number submitted via odoo.com/help (optional):
Odoo Ticket #2440256

**Comment by suniagajose** [comment]
@luistorresm please help me following this isse.

Regards,

**Comment by william-andre** [comment]
https://github.com/odoo/enterprise/pull/15858
