### ISSUE TITLE
[13.0] Wrong product price rounding

### ISSUE THREAD

**Issue by zonclayv** [odoo/odoo#64588]
Impacted versions:
13.0

Steps to reproduce:
1. Create product with price 5.10 (in db in table product_template column list_price = 5.10)
2. Look at field 'price' of created product. There is 5.1000000000000005 in field 'price'.
 After debuging I found that odoo.tools.float_utils.float_round function doesn't work as expected and return broken price. Pls look at screenshot.

Current behavior:
Field 'price' has value 5.1000000000000005

Expected behavior:
Field 'price' has value 5.10

Video/Screenshot link (optional):
<a href="https://ibb.co/NKjDfJq"><img src="https://i.ibb.co/x6j9wBb/Screenshot-from-2021-01-15-11-02-47.png" alt="Screenshot-from-2021-01-15-11-02-47" border="0"></a>

**Comment by pedrobaeza** [comment]
This is how float works (https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html). On UI, you won't be see such rounding artifact.

Closing as no real bug.
