### ISSUE TITLE
An M2M type field is used as a filter for the calendar

### ISSUE THREAD

**Issue by he-junjie** [odoo/odoo#64590]
My requirement requires an M2M type field as the calendar filter, but I have learned that Odoo Calendar does not support it, so I want to know whether there are other methods to achieve the above requirement.

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Comment by he-junjie** [comment]
Thank you for your help
