### ISSUE TITLE
sql alias bug

### ISSUE THREAD

**Issue by leopard7777777** [odoo/odoo#6460]
we know product.product inherits product.template by 'product_tmpl_id',now product.child.listing inherits product.product by 'parent_product_id'
when i read product.child.listing , throws a exception
 SELECT \* FROM "product_child_listing","product_product" as "product_child_listing__parent_product_id","product_template" as "product_product__product_tmpl_id"
                        WHERE "product_child_listing".id IN %s AND ("product_child_listing"."parent_product_id" = "product_child_listing__parent_product_id"."id") AND ("product_product"."product_tmpl_id" = "product_product__product_tmpl_id"."id")  ORDER BY "product_child_listing"."id"  

product_product alias product_child_listing__parent_product_id,because product.child.listing inherits product.product.
("product_product"."product_tmpl_id" = "product_product__product_tmpl_id"."id")  throws a exception

ProgrammingError: invalid reference to FROM-clause entry for table "product_product"
LINE 2: ...duct_child_listing__parent_product_id"."id") AND ("product_p...
                                                             ^
HINT:  Perhaps you meant to reference the table alias "product_child_listing__parent_product_id".

**Comment by Yenthe666** [comment]
Hi @leopard7777777,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
