### ISSUE TITLE
[Fixed ][ Confirmed Critical Bug ] [Odoo 8 Failed] (Document type: stock.picking.type, Operation: read)

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#6462]
We had created multi company one parent two child.
From child company when create new purchase raise error.

Install modules: sales, purchase, warehouse, invoice.
Given all rights with manager and higher, even getting bug.

AccessError
The requested operation cannot be completed due to security restrictions. Please contact your system administrator.
(Document type: stock.picking.type, Operation: read)

**Comment by tejastank** [comment]
I had investigated and found in purchase code.

pick_type = obj_data.get_object_reference(cr, uid, 'stock', 'picking_type_in') and obj_data.get_object_reference(cr, uid, 'stock', 'picking_type_in')[1] or False

It return id 1 even for any other company, seems obj_data.get_object_reference failed to work for muliti-company. It might you need to correct odoo framework code, might be its small change.

But it seems too urgent to fix, I hope you investigate much better way and fix it.

Thanks,

**Comment by tejastank** [comment]
[FIXED]

I had replaced code, new code as below.

    def _get_picking_in(self, cr, uid, context=None):
        obj_data = self.pool.get('ir.model.data')
        type_obj = self.pool.get('stock.picking.type')
        user_obj = self.pool.get('res.users')
        company_id = user_obj.browse(cr, uid, uid, context=context).company_id.id
        
        #Fixed, @moreinfo, Tejas Tank
        pick_type = type_obj.search(cr, uid, [('code', '=', 'incoming'), ('warehouse_id.company_id', '=', company_id)], context=context)
        pick_type = pick_type[0] if pick_type != [] else False
        
        if not pick_type:
            pick_type = type_obj.search(cr, uid, [('code', '=', 'incoming')], context=context)
            pick_type = pick_type[0] if pick_type != [] else False

        if not pick_type:
            raise osv.except_osv(_('Error!'), _("Make sure you have at least an incoming picking type defined"))
        
        return pick_type


purchase.py line, 151 function updated, As per my review their bad logic, so I had replace my code and its works for me, excellent.

If some one had similar issue, might be it better solution with isolated Multi-Company environment.

Someone had better solution or fix, kindly share here, else if my code work, merge it.

Thanks,

**Comment by Yenthe666** [comment]
I can no longer reproduce this issue and you've written an own fix, as stated in your above comment.
Closing this for both those reasons.
