### ISSUE TITLE
[13.0] website_sale -> Product Multi Company Rule issue

### ISSUE THREAD

**Issue by rohitramnani1994** [odoo/odoo#64621]
Impacted versions: 13.0

Steps to reproduce:
-Enable Multi-company from the configuration\
- Creat 3 Companies
  Company A (Main Company)
  Company B
  Company C

- Install website_sale module
- Go to the products menu and create a new Product A and select Company A in the product itself
- Click Go to website smart button

Current behavior:
- It will raise traceback
![403-My-Website](https://user-images.githubusercontent.com/25322407/104739911-4f64f400-576d-11eb-91b5-c4c3f4a9d2df.png)

Expected behavior:
- It will open be open product details page
Video/Screenshot link (optional):

https://user-images.githubusercontent.com/25322407/104740599-25600180-576e-11eb-8e16-86589b99f34c.mp4

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
The video is not correct. Can you re-upload it? Are you sure you select company A in the product?

**Comment by rohitramnani1994** [comment]
> The video is not correct. Can you re-upload it? Are you sure you select company A in the product?

Yes I'm sure

**Comment by rohitramnani1994** [comment]
> The video is not correct. Can you re-upload it? Are you sure you select company A in the product?

Yes sure let me upload another video

**Comment by rohitramnani1994** [comment]
> The video is not correct. Can you re-upload it? Are you sure you select company A in the product?

Please find another video link with Company B

https://drive.google.com/file/d/14N8D6UfxPDwpSaFReGm72Uu52iyzNAMR/view?usp=sharing

Thank you

**Comment by sswapnesh** [comment]
> Go to the products menu and create a new Product A and select Company A in the product itself

@rohitramnani1994 It seems due to Wrong company in Website. Please Check the Company field in the Website.
You are Trying to Access Product A (Belongs to Company A) while website has some other company.

**Comment by rohitramnani1994** [comment]
Thank you @sswapnesh 
It's Worked 👍
