### ISSUE TITLE
Website rewrite issue due to slug and RequestUID in Environment

### ISSUE THREAD

**Issue by lem8r** [odoo/odoo#64635]
Impacted versions: 14.0

Steps to reproduce:

1. Create 308 rewrite:
  from url: `/blog/<model("blog.blog"):blog>/feed`
  to url: `/news/<model("blog.blog"):blog>/feed`
2. Visit `/blog/1/feed`

Current behavior: Server Error: `psycopg2.ProgrammingError: can't adapt type 'RequestUID'`

Expected behavior: rewrite to `/news/1/feed`

Video/Screenshot link (optional):
[Fake uid is passed directly to environment](https://github.com/odoo/odoo/blob/6b4941160f336ed7a45287c5568dabd1c56289aa/addons/http_routing/models/ir_http.py#L257)

However before slug refactor [there was check](https://github.com/odoo/odoo/commit/014b5c9f7c2f0a5c9741569525364ff9cd6cb4cc#diff-f444d9b99919dbdbf8a57e1492478cb518cd2f78ec07dfedebff81140210671bL247-L248) if `uid` is instance of `RequestUID` we pass `request.uid` to `Environment`.

Slug tries to get `record.display_name`. Since record (blog.blog(1,) in my case) is not in cache ORM tries to fetch it and fails on first SQL query that uses user id in `check_access_rights()`

**Comment by lem8r** [comment]
@JKE-be please, have a look.

**Comment by JKE-be** [comment]
Hello
Are you sure to use thé last code?
I havé fixed This 1 week ago if i ´m not wrong ... 
ty

**Comment by JKE-be** [comment]
https://github.com/odoo/odoo/pull/64328/commits/5a20f03d977794490759a2e06b09617173bf037e

**Comment by lem8r** [comment]
Hi,

This commit is not merged yet.
But since it is know bug and fix is coming no need for issue.

Thanks!

**Comment by lem8r** [comment]
UPD: it is merged already and fixes the issue.
