### ISSUE TITLE
[14.0] website raise error when use language Chinese (Simplified) 

### ISSUE THREAD

**Issue by dx19910707** [odoo/odoo#64648]
Impacted versions:
odoo14

Steps to reproduce:
1.init a new database
2.active and switch to  language Chinese (Simplified)  
3.install website module, then visit your website

Current behavior: 
can't visit website

Expected behavior:
correct the translation at addons/web/i18n/zh_CN.po L259

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
You need to fix the translation, and that's done by community:

https://github.com/odoo/odoo/wiki/Translations

@mart-e is this applicable to be fixed other way?

**Comment by Yenthe666** [comment]
@pedrobaeza nope, needs to be fixed through Transifex & then synced :)

**Comment by pedrobaeza** [comment]
OK, then closing this.
