### ISSUE TITLE
[14.0] account: Not able to access accounting module with wrongly configured journal

### ISSUE THREAD

**Issue by gustavovalverde** [odoo/odoo#64681]
##### **Impacted versions:**
14.0

##### **Steps to reproduce:**
- Migrate from 12.0 to 14.0
- Access the account module

##### **Current behavior:**
In v13 there were cash/bank journals without a default account, and `_get_journal_bank_account_balance()` **returns 0** if this is the case, but it's actually expecting a **tuple**:

https://github.com/odoo/odoo/blob/95ffa9fd122eae82d12d40db3cb7364cf3d3c919/addons/account/models/account_journal.py#L636-L649

**Traceback:**
```python
  File "/usr/local/lib/python3.8/site-packages/odoo/addons/account/models/account_journal_dashboard.py", line 233, in get_journal_dashboard_datas
    bank_account_balance, nb_lines_bank_account_balance = self._get_journal_bank_account_balance(
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/local/lib/python3.8/site-packages/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: cannot unpack non-iterable float object
```

#### Expected behavior:
A warning which allow to fix the journal; as this error completely locks-out the end user without technical knowledge to continue using the service.

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
If it's something on the enterprise upgrade, you should report it then, and if it's something reproducible without the migration, please indicate bare detailed steps for being able to reproduce it on runbot.

**Comment by gustavovalverde** [comment]
This is reproducible as long as there's a bank or cash journal without the **default_account_id** set.

**Comment by pedrobaeza** [comment]
Then why do you add the non needed information about migrating a DB. Please put the steps in UI in a runbot.

**Comment by gustavovalverde** [comment]
I added the migration information because this is how most people will hit this issue.

Anyways, the **core issue** here is that the method **_get_journal_bank_account_balance()** shouldn't return 0, as this is expecting a **tuple**, not an **float** value. 

**Wrong return:**
https://github.com/odoo/odoo/blob/1601bc85bf57c32151306f4f66c0537dceba4534/addons/account/models/account_journal.py#L649

**Correct return:**
https://github.com/odoo/odoo/blob/1601bc85bf57c32151306f4f66c0537dceba4534/addons/account/models/account_journal.py#L673

cc: @smetl

**Comment by smetl** [comment]
Fix in progress at https://github.com/odoo/odoo/pull/64664

**Comment by gustavovalverde** [comment]
Thank you @smetl
