### ISSUE TITLE
relative time in domain is doing wrong

### ISSUE THREAD

**Issue by digitalsatori** [odoo/odoo#6469]
When trying to set a filter like 'Today', 'Tomorrow', 'This week', 'This year' etc on records, the suggested way will be set up a domain like the following:
**(a domain for 'Today', the others are similar)**

    <filter string="Today" domain="[('start_datetime','&lt;=', time.strftime('%%Y-%%m-%%d 23:59:59')),('start_datetime','&gt;=', time.strftime('%%Y-%%m-%%d 00:00:00'))]"/>

or 

    <filter string="Today" domain="[('start_datetime','&lt;=', context_today().strftime('%%Y-%%m-%%d 23:59:59')),('start_datetime','&gt;=', context_today().strftime('%%Y-%%m-%%d 00:00:00'))]"/>

Those are all wrong and they appear in many of official and non-official addons. The first one compare utc time ('start_datetime') with server time, the second compare utc time with client time. ( Not sure, The first one may also be client time? py.js did the parse)

~~Actually those filters for relative time should always be client side comparison, server time or utc time shouldn't be involved. In my example above, the 'start_datetime' should be converted to client time first, then do the comparison with client time at right side.~~

Here is an example: 
I'm on UTC+8 time zone.
when I input a record and make the 'start_datetime'  as 2015/04/26 07:55:00 my local time, the record in the database will be '2015/04/25 23:55:00' utc time.
When I use the 'Today' filter to filter records on the same day local time , this record disappeared even though the start_datetime on screen read '2015/04/26 xxxxxx'

**Comment by digitalsatori** [comment]
@odony can you please advise on this issue, Thank you

**Comment by vrms** [comment]
I can confirm this issue. 

Same timezone here (UTC +8). A calender event Mon, 2015-04-27 7:30 (which is 2015-04-26 in UTC) is still shown on Monday in the Calender, but once you apply a Filter to show only events for 27th it is being filtered out.

**Comment by hbrunn** [comment]
That's why I wrote https://github.com/OCA/web/pull/45, you might want to read https://github.com/odoo/odoo/pull/2914 too

**Comment by digitalsatori** [comment]
@hbrunn cool, thank you very much for the module and the reference link. Learned a lot.

**Comment by jcchua** [comment]
@digitalsatori Tony, I have the same UTC+8 issue, where did you download the module mentioned, I w found  https://github.com/OCA/web  but not sure if I am right, could I  implement the module at my addons or to replace the web directly or to do some patching? sorry for the stupid questions still learning.

**Comment by digitalsatori** [comment]
@jcchua The module is in the V7 branch , named 'web_pytz'. You can just install the module if you are working on Odoo V7. You will need to change the js  registeration to make it work with V8

**Comment by jcchua** [comment]
@hbrunn by any chance you can make it works in version 8 too?

**Comment by odony** [comment]
Not sure if you're referring to 7.0 or 8.0, but in both branches one solution is to update to the latest revision (for 7.0, this means at least after the merge of #6229 at 76881fb2262c9fcfc306c8b1f6d2394b402d0ce1), and then you can have a look at 81a3f5665154bc3c864d5910d50a44496b4fc295 to see examples of domains that will get you the expected result, regardless of the user's timezone:
```
<filter string="Today" domain="[('start_at', '&gt;=', 
      datetime.datetime.combine(context_today(), datetime.time(0,0,0)))]" />
```

The idea is to avoid the use of `strftime()` completely, and directly use a DateTime value in the domain, so it is serialized properly and sent to the server using the right timezone info.
See the commit message of 76881fb2262c9fcfc306c8b1f6d2394b402d0ce1 and discussion on #6229 for more details.

I think we can therefore close this issue, unless this solution does not work for you?

**Comment by digitalsatori** [comment]
@odony Great, Thank you very much for the info.
I'm working on Saas-6 and test the new syntax, I got following result. Can you please further explain what could be the reason?

1. this works fine
 ``` <filter string="Tomorrow" domain="[('start_at', '&lt;=', 
                 datetime.datetime.combine(context_today() +datetime.timedelta(days=1),
                 , datetime.time(23,59,59)))]"/>```

2. this one prompt  "unsupported operand type(s) for +: 'datetime' and 'timedelta'" error
```[('start', '<=',(datetime.datime.now()              +datetime.timedelta(days=1)).replace(hour=23,minute=59,second=59))] ```

3. this one prompt "function got an unexpected keyword argument 'hour'" error
``` [('start', '<=',(context_today() +datetime.timedelta(days=1)).replace(hour=23,minute=59,second=59))]```

Another issue for filters on datetime field: #6486

**Comment by odony** [comment]
@digitalsatori You're mixing types in your operations in a way that is not supported. Our Javascript implementation of Python's datetime module is purposely limited:

In particular:
- Note that `context_today()` returns a `datetime.date`, not a `datetime.datetime`
- Use `datetime.datetime.combine` to combine a `datetime.date` with a `datetime.time` into a new `datetime.datetime` value.
- You can add a `datetime.timedelta` to a `datetime.date` (e.g. `context_today()`), not to a `datetime.datetime` (unsupported operand)
- The `replace()` method of `datetime.datetime` accepts both `year`, `month`, `day` and also `hour`, `minute`, `second`
- The `replace()` method of `datetime.date` logically only accepts `year`, `month` and `day`  -> unexpected keyword if you try to pass hour, minute, second.
- So if you want to add a `timedelta` to a `datetime.datetime`, add the delta to a `datetime.date` first (e.g. `context_today`)

You can infer the rest based on the above...

**Comment by digitalsatori** [comment]
@odony Thank you very much for the clear explanation.
You may close this issue now.
