### ISSUE TITLE
[V8] Pos and Pos Restaurant code needs to be updated to let users use system printers. 

### ISSUE THREAD

**Issue by effelle** [odoo/odoo#6471]
Looking on various forums (including the official one) is evident the need to extend the printers list to enhance compatibility. Epson printer are not cheap, even understanding you choose them for the highest ESC/POS compatibility in your tests you are involuntary blocking all the other solutions. I have myself a generic usb thermal printer and I can't use it with esc/pos module with stock settings.
To have it partially working I had to "cheat" the system using the report to printer module and a modified invoice button 
![img_20150426_211313601](https://cloud.githubusercontent.com/assets/7702766/7340020/6e385c56-ec51-11e4-9d26-3173bf27da55.jpg)
Loosing the invoice was not a big deal for me since I use Odoo just for the POS and for statistic reports. We have a custom software for the business management.
Edit the pos_restaurant "order" function appears to be really hard due to the hard-coded hw_proxy call and my poor knowledge of Python/XML... 
Anyway, here's what I did to archive my result:

https://www.odoo.com/forum/help-1/question/print-order-instead-of-coupon-on-pos-what-qweb-view-82635

Have the "order" function working is fundamental for a restaurant: if is possible to create the pdf invoice and consequently print it automatically with a system printer trough the report to printer module, should be possible do the same on order,split and bill options offered by pos_restaurant module.
Please, if is not possible explain once for all why, just to avoid hammering about this topic. Thanks!

**Comment by Yenthe666** [comment]
Hi @effelle,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
