### ISSUE TITLE
odoo sales, purchase, invoicing analysis are not multiple currency

### ISSUE THREAD

**Issue by uynil** [odoo/odoo#6472]
Given multiple currency is activated in odoo v8 or v7.
The amount in sales, purchase, invoicing analysis are in their original currency, the total of one group of the report (by customer, by month) are mixes of different currencies.

**Comment by rcarnes** [comment]
I noticed today that although Journal Entries are correctly recorded in the currency, the reports are converting the currency to itself!  (My journal entry is for $100, the exchange rate of the currency is 16 and the amount in the report is 6.25 - which is 100 / 16).  I have a base currency and I can't work out if this is a configuration problem or a bug.

**Comment by h4818** [comment]
Experiencing the same problem with v8. 
By I do have an instance where Sales Analysis is in the company currency (ZAR), while invoice analysis seems to be in EUR.
All new instances use EUR for both reports (I am using custom chart of accounts - not sure if that matters)

**Comment by Yenthe666** [comment]
Hi @uynil,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
