### ISSUE TITLE
[8.0] can not create distribution model form analytic plan context menu, and does not show distribution field in sale invoice form if not install analytic plan for sale 

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#6473]
Impacted versions:
- 8.0

Steps to reproduce:
1. install modules, account_analytic_plans and account_analytic_default.  _does not_ to install sale_analytic_plans and purchase_analytic_plans
2. create new analytic plan and assign this plan to sale journal.
3. click analytic context menu item Distribution Models, it should go to  Distribution Models list `account.analytic.plan.instance` , if click the create button, as we Expected, it should populate the dynamic view to create new distribution model that should flow the analytic plan rules. but it just to show the `account.analytic.plan.instance` creation form that not follow any plan rule.
4. go to sale invoice and create one invoice, the invoice form does not show distribution field. as we Expected is to show this field.   if we installed  sale_analytic_plans, it should show this field.
   . 
   so i think that there have any broken.  i should try to fix this soon.

**Comment by Yenthe666** [comment]
Hi @jeffery9,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
