### ISSUE TITLE
Multi Company User Access Right

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#6474]
Hi Odoo,

I want to ask a question for you,
So we have a multi-company configuration.

Let say we have:
Parent company: A
And have children company:
Brother: B
Sister: C

I created the user name Hans, it have all the access company for A, B, C
I want the user Hans, in B company become sale manager
But in the C company, only can see his own leads.

How can I achieve this?

**Comment by Yenthe666** [comment]
Simple answer: not at this point. Not on the wishlist either.
You could do this with custom development 😉
