### ISSUE TITLE
[14 ]Survey not emailing correctly

### ISSUE THREAD

**Issue by designbybeck** [odoo/odoo#64763]
Impacted versions: 14

Steps to reproduce: Create Survey > Save > Share > Fill in email address > Click Send. Once you receive email, variables are not populated and you can see that code in the email body itself.

Current behavior: Survey Variables are not populated and shown in email. Also when you receive the email, it includes extra company graphic and text in the header, which you can't edit out in the Survey template. Not sure if that is related. 

Expected behavior: Survey variables should be populated with correct information when end users read their email asking them to take the survey.

Video/Screenshot link (optional): Attached
![Odoo_Survey_Problem](https://user-images.githubusercontent.com/4542852/105068504-a0fbd000-5a46-11eb-83be-415c503577dc.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
You have manipulated the template through UI editor and thus the Jinja expression are mangled. Restore the initial template.

Closing due to this.
