### ISSUE TITLE
Please update translations from Launchpad

### ISSUE THREAD

**Issue by dskarataev** [odoo/odoo#6476]
Hi @odony,

Our Russian translation team made a massive update of translation for Odoo 8.0 on Launchpad. Please transfer it to GitHub.

Thank you.

**Comment by sysadminmatmoz** [comment]
I would like to join to my Russian colleagues initiative - a same massive effort was done in the Slovenian translation team (completely translated). If launchpad project is dead, we can make a merge request in Github too.

**Comment by odony** [comment]
@dskarataev @sysadminmatmoz @clonedagain
Finally resync'd the 8.0 translations at revision 622e00baa5e920863dc1daee49d420ede4056b0f, sorry for the delay. The new ones will be included in tomorrow's nightlies.
Note that you can also post on the [translators mailing-list](https://www.odoo.com/groups/community-translators-63) to request a resync if you see the translations are lagging behind.

**Comment by dskarataev** [comment]
Thanks @odony!

**Comment by sysadminmatmoz** [comment]
Appreciate it, thanks!
