### ISSUE TITLE
Issue printing while evaluating POSBox with Epson TM20i printer: Printing Error Undefined

### ISSUE THREAD

**Issue by uojeh** [odoo/odoo#6477]
I'm currently playing around with the POSBox, evaluating it for use in a solution which will extend the OpenERP project.
So far, i've been unable to get it to print, scan and/or open up the cashdrawer successfully.

Convinced that my issue was hardware based, I switched the Star Micronics printer i was previously using to an Epson printer.
I was under the impression I was getting the Epson TM-T20 printer, however it turns out I got the Epson TM-T20i printer.

however, after editing the supported_devices.py script, i was able to get a successful status print out, and connect successfully via an instance of the SaaS POS.

now comes my problem, when i attempt to validate a transaction from the POS, I get an error, saying Printing Error: Undefined.

I'm able to open the cashdrawer, and the printer shows as online when i'm running a POS Session.
Also, if i connect the printer directly to my pc, and run the session for a pc web browser, i'm able to print successfully.

Please help!!!  Thanks in advance.
![printing error screenshot](https://cloud.githubusercontent.com/assets/12132065/7342712/1e1593e4-ec86-11e4-863b-d57767a061a1.jpg)

**Comment by uojeh** [comment]
leaving a comment to pull in @fvdsn per communique.  Frederic please let me know if you're able to make any headway with this issue please.  thanks

**Comment by Yenthe666** [comment]
Hi @uojeh,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
