### ISSUE TITLE
zero is not recognized as default value

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#6484]
I have this field:

``` python
min_range = fields.Float('Min. Range', required=True, default=0.0)
```

But when I try to save a record with that field, I get warning, that field is not entered. If I manually enter `0.0`, only then it recognizes zero as value. Why this is happening?

P.S. this is only happened when record is being created through One2many relation (using editable tree view).

**Comment by Yenthe666** [comment]
Hi @oerp-odoo,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
