### ISSUE TITLE
union of filters for datetime field not working right

### ISSUE THREAD

**Issue by digitalsatori** [odoo/odoo#6486]
I'm on Saas-6 branch

Let say I have two filters 'Today' and 'Tomorrow' on a datetime field of a model.
When I use the filter separately ,they are working fine. However, when I choose both filters, that is union of the filters, the expected result should be:
showing records both Today and Tomorrow,
but the actual result is:
showing records whichever the latter filter apply(the first filter will be ignored)

**Comment by odony** [comment]
@digitalsatori It would be great if you could include the details of the filters you are trying to combine (i.e. the definition of the fields/filters) in the search view, or better yet, a simple list of steps to reproduce your problem on runbot. (See the [bug report template](https://github.com/odoo/odoo/wiki/Contributing#reporting-issues))

PS: the saas-6 branch is unsupported/unrecommended outside the Odoo Online environment, so in general you should test and report bugs on an official branch, such as 7.0, 8.0 or master

Thanks!

**Comment by Yenthe666** [comment]
Hi @digitalsatori,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
