### ISSUE TITLE
Odoo 14 Backend on iPhone is not responsive

### ISSUE THREAD

**Issue by alex71m-zz** [odoo/odoo#64865]
Impacted versions: 14

Steps to reproduce: log into the Backend from a smartphone

Current behavior: the screen doesn't scale down with the resolution of the smartphone

Expected behavior: as in odoo 13

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/13301337/105366546-c2ec8280-5bff-11eb-99d9-6309942786bc.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
Yes, community interface is not responsive. Use enterprise responsive addon or look for a community alternative addon.
