### ISSUE TITLE
Python library version conflict: firebase_admin

### ISSUE THREAD

**Issue by hmrickhoff** [odoo/odoo#64882]
Impacted versions: 14

Steps to reproduce: installing socialmarketing addon

Current behavior: error message while installing Python library version conflict: firebase_admin

Expected behavior:

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/29108847/105382857-d18f6580-5c10-11eb-911a-1bae2efbeeaa.png)

Support ticket number submitted via odoo.com/help (optional):

its a "library version conflict" not a not installed problem. i ran "pip3 install firebase_admin" and it installed that via python3.6

**Comment by pedrobaeza** [comment]
As this is an enterprise problem (and deployment one), please report it through odoo.com/help.
