### ISSUE TITLE
hr_holidays : set a color for a type, doesn't apply in calendar view

### ISSUE THREAD

**Issue by bjoliveau** [odoo/odoo#6489]
Tested this day in http://65175-8-0-cf4d14.runbot6.odoo.com
You can set any color you want for a type of leave in hr_holidays (Odoo v8.0) and the calendar view doesn't apply the color setted in calendar view.
Some screenshots below

![001_201504_e75](https://cloud.githubusercontent.com/assets/1226478/7354162/30d70d1c-ece7-11e4-8c73-2ecfbdd338fc.png)

![001_201504_2e1](https://cloud.githubusercontent.com/assets/1226478/7354174/4e3ae89c-ece7-11e4-9a87-364dff5b3cb7.png)

![001_201504_1d4](https://cloud.githubusercontent.com/assets/1226478/7354175/5376176e-ece7-11e4-83e5-023f46585e6c.png)

**Comment by yasii1991** [comment]
Any updates regarding this?

**Comment by Yenthe666** [comment]
Hi @bjoliveau,

Thank you for your report.
You're mixing up two concepts though. Setting the colour in report for a legal type is for the PDF report "Leaves summary". It has nothing to do with the colour of the agenda items, it is only for in the PDF. The leave category:
![image](https://user-images.githubusercontent.com/6352350/31068990-ba8ba326-a75a-11e7-8f8b-6fb6c6b87efe.png)
The agenda:
![image](https://user-images.githubusercontent.com/6352350/31068998-c882ecb4-a75a-11e7-94a3-34300ab4000e.png)
The report:
![image](https://user-images.githubusercontent.com/6352350/31069007-d5fc3f62-a75a-11e7-997e-6266fc9ebd47.png)

So this is not a bug, you're just mixing two different functionalities. 😉 

Regards,
Yenthe
