### ISSUE TITLE
[14.0] VIES VAT check doesn't work

### ISSUE THREAD

**Issue by alexis-via** [odoo/odoo#64897]
Here are the steps to reproduce the bug:
- connect to runbot v14
- go to the accounting config page and enable the option " Verify VAT numbers using the European VIES service"
-  create a new partner with country = France and VAT number FR38392834230
- the partner is saved without errors.
- if you check this VAT number in VIES, you will see that this number is invalid (because the company has been closed)
![vies_refused](https://user-images.githubusercontent.com/1157917/105411580-daddf980-5c33-11eb-88ef-69f667174906.png)

Code analysis:
In the method vies_vat_check on https://github.com/odoo/odoo/blob/14.0/addons/base_vat/models/res_partner.py#L105
all the exceptions are catched. If you remove the try/except in this method, you will get this error:
```
AttributeError: module 'stdnum' has no attribute 'eu'
```
Analysis and solution
```
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import stdnum
>>> stdnum.eu.vat.check_vies('FR38392834230')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'stdnum' has no attribute 'eu'
>>> from stdnum.eu.vat import check_vies
>>> check_vies('FR38392834230')
(reply){
   countryCode = "FR"
   vatNumber = "38392834230"
   requestDate = 2021-01-21
   valid = False
   name = None
   address = None
 }
```

The bug is NOT present on v13 nor v12 (because the code of _check_vies uses the old/deprecated vatnumber lib)

**Comment by Yenthe666** [comment]
We're also bitten by it so I made an OPW for it :) Ref `2451951`
