### ISSUE TITLE
Brexit and Northern Ireland: new VAT numbers starting with XI

### ISSUE THREAD

**Issue by alexis-via** [odoo/odoo#64891]
Following Brexit on January 1st 2021, companies in Northern Ireland have a new VAT number starting with XI instead of GB. More info: https://www.gov.uk/government/publications/accounting-for-vat-on-goods-moving-between-great-britain-and-northern-ireland-from-1-january-2021/check-when-you-are-trading-under-the-northern-ireland-protocol-if-you-are-vat-registered-business

Tested on runbot v14: when I create a new company with country = United Kingdom and VAT number starting with XI, i get an error "The VAT number [XI.......] for partner [.......] does not seem to be valid. Note: the expected format is GB123456782".

For my test, I used the following VAT number which is considered valid by VIES:
![vat_xi_vies](https://user-images.githubusercontent.com/1157917/105389010-9f353680-5c17-11eb-865a-919f2a0707e9.png)

I also opened a bug on python-stdnum about this, cf https://github.com/arthurdejong/python-stdnum/issues/250

**Comment by Yenthe666** [comment]
@oco-odoo @qdp-odoo this is for your interest & might need a quite soon fix actually.

**Comment by alexis-via** [comment]
Support for VAT numbers starting with XI has been added in stdnum lib tonight. If you update stdnum to the master branch and you create a partner with the VAT number of my screenshot and country = United Kingdom, it will be accepted.

It seems to me that the code in base_vat needs a serious cleanup. I already opened another bug report about VIES check which doesn't work in v14 cf https://github.com/odoo/odoo/issues/64897
But I discovered other strange things:
- the method fix_eu_vat_number() is never called
- the dict _eu_country_vat_inverse which is built from _eu_country_vat has country codes as upper letters and it is read by the method simple_vat_check() which uses country_code with lower letters.

Maybe this cleanup would be an opportunity to simplify the code and use stdnum.vatin which is designed to check VAT numbers for all countries:
```
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from stdnum.vatin import is_valid
>>> is_valid('FR86792377731')
True
>>> is_valid('CHE-109.298.651 TVA')
True
```

**Comment by Yenthe666** [comment]
OPW `2451954`

**Comment by alexis-via** [comment]
FYI, as you can see in the latest comments on this PR https://github.com/arthurdejong/python-stdnum/pull/251, a new "Bexit-compliant" release of stdnum will be made on pypi in the coming days. This release will have support for the XI VAT numbers.

**Comment by alexis-via** [comment]
FYI, stdnum 1.16 has been released today with support for the new XI VAT numbers of Northern Ireland https://pypi.org/project/python-stdnum/1.16/  I tested this new release of stdnum and it works fine.

**Comment by Yenthe666** [comment]
I've asked Odoo to update their packaging etc :) Looks like a lot of Odoo installs will need a `python-stdnum` update to 1.16 I guess.

**Comment by william-andre** [comment]
`python3-stdnum` will be on Debian bullseye https://packages.debian.org/bullseye/python3-stdnum
That freeze is expected 2021-03-12 https://wiki.debian.org/DebianBullseye
We would also like to support it for Ubuntu, where 1.16 will be available for Hirsute https://packages.ubuntu.com/hirsute/python3-stdnum
That freeze is expected 2021-04-22 https://discourse.ubuntu.com/t/hirsute-hippo-release-schedule/18539

Until then, we should patch it in `base_vat`.
