### ISSUE TITLE
On inherited models, field redefinition does not replace attibutes with False

### ISSUE THREAD

**Issue by gamarino** [odoo/odoo#6490]
If you redefine a required field (like company_id in account.tax) and sets required = False, it is not taken into account by the orm. The field will be still required=True (using old style fileds)

The fault is en the way fields are created in models.
The following repairs the fault:

```
diff --git a/openerp/models.py b/openerp/models.py
index 9d44280..3ead2ad 100644
--- a/openerp/models.py
+++ b/openerp/models.py
@@ -2962,7 +2962,7 @@ class BaseModel(object):
         cls._fields = {}
         cls._defaults = {}
         for attr, field in getmembers(cls, Field.__instancecheck__):
-            cls._add_field(attr, field.new())
+            cls._add_field(attr, field.copy_field())
 
         # add magic and custom fields
         cls._add_magic_fields()

```

**Comment by rco-odoo** [comment]
@gamarino simply use new-style fields to override parameters.

(Sorry for the long delay, BTW.)
