### ISSUE TITLE
Payment lines can be deleted, but not the header

### ISSUE THREAD

**Issue by ybofr** [odoo/odoo#6491]
I tested this in runbot:

How to get the error:
Create a sales order
Invoice the sales order
Register a payment to the newly created invoice
Go to the reconciliation number and unreconcile the lines
Then delete both lines of the payment
Save it
The payment does not have any line item, but cannot be delete and has still the status POSTED, even if there was nothing poste with the payment. 

Expected behaviour
1.If a document has no line, I should be able to change it's status from "Posted" to "unposted" or able to delete it, as there is no reference anymore to the original invoice.
2. The status "posted" in this case seems to implicate that a posting in accounting was done, but this is not the case. Posted should only be used in one way.

**Comment by Yenthe666** [comment]
Hi @ybofr,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
