### ISSUE TITLE
Can Odoo be developed on M1 Macbook

### ISSUE THREAD

**Issue by hoangtrann** [odoo/odoo#64969]
Hi Odoo team,

I'm wondering if Odoo could be developed on a M1 Macbook? As far as I see, M1 could run python 3.9 native, but Odoo is now using python version 3.7 or 3.8 (with some dependencies issues). Beside that, Odoo docker image only support x86 arch but not ARM.

Would love to have you guys shed some light on this.

Thanks

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
