### ISSUE TITLE
Product attribute import broken when attribute values are not unique

### ISSUE THREAD

**Issue by WoLpH** [odoo/odoo#64977]
Impacted versions:

I've tested these:

 - 12.0
 - 13.0
 - 14.0

Steps to reproduce:

1. Install Odoo
2. Enable the Inventory app
3. Enable Attributes for the inventory app
4. Create an attribute with some value
5. Create another attribute with the same value as above
6. Try and import a product with 1 of those attributes set. The import will result in an error if the attribute value exists in more than 1 attribute.

Current behavior:

You get this error: `Found multiple matches for field 'Product Attributes' (2 matches) at row 2`

Expected behavior:

A working import

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/270571/105649155-467fcb00-5eaf-11eb-9d5d-2da7907508f0.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by WoLpH** [comment]
Depending on the other data in your database, you can also end up with an error like this:

![image](https://user-images.githubusercontent.com/270571/105649939-5816a200-5eb2-11eb-8579-a845a20134f9.png)

**Comment by pedrobaeza** [comment]
You have to use external ID if the match is not unique.

Closing as invalid.

**Comment by WoLpH** [comment]
If that's the case, that would be good to include in the error and the documentation.

Nothing is currently mentioning that and there are no examples showing how to do that.

**Comment by pedrobaeza** [comment]
Well, if you have 2 attributes with the exact same name, it's normal that Odoo are not able to determine which one is. If you want to improve documentation, please propose such change doing a pull request.

**Comment by WoLpH** [comment]
If I knew how to do it, I wouldn't need the docs :) So I'm not sure if I'm the person to write useful documentation about this subject. 

If we look at the documentation, nowhere does it clearly state what to select in the dropdown. Or at least, not correctly: https://www.odoo.com/documentation/user/14.0/sales/products_prices/products/import.html

The documentation does mention `Product Attributes / Attribute / ID` which doesn't exist:
![image](https://user-images.githubusercontent.com/270571/105733362-c51d4c80-5f31-11eb-9b20-a9cbefd30df5.png)

Simply searching for `Product Attributes` generates a very long and unreadable list with no clear indication which to use:
![image](https://user-images.githubusercontent.com/270571/105733507-e9792900-5f31-11eb-9750-7838f8f0ad1e.png)

The documentation about attributes doesn't mention anything either: https://www.odoo.com/documentation/user/14.0/ecommerce/managing_products/variants.html?highlight=attributes
Nor the documentation about the import template or the import template itself: https://www.odoo.com/documentation/user/14.0/general/base_import/adapt_template.html?highlight=attributes
And the documentation about using product variants doesn't help either: https://www.odoo.com/documentation/user/14.0/sales/products_prices/products/variants.html?highlight=attributes

It could help a lot if there was an example file which would at least have the correct column names prefilled because even when exporting and re-importing the data from the system this is currently very hard to use or perhaps even broken (I haven't found a combination of exported fields that work).

**Comment by pedrobaeza** [comment]
It's "External ID"...
