### ISSUE TITLE
Can not override the   parse_config() in config.py of odoo server code

### ISSUE THREAD

**Issue by forhadsidhu** [odoo/odoo#64988]
Impacted versions: v11.0

Steps to reproduce:  11.0/odoo/server/tools/config.py

Current behavior: currently there is no customization option in parse_config() method like for encrypting db_password.

Expected behavior: Need some customization option in config.py file

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
This is not a bug, but something that you want to perform and it's not possible, and more over an outdated version that is out of official support. If you want to have that configurable, then propose a pull request over master branch, as this can't be considered for stable versions.
