### ISSUE TITLE
[12.0] Automated action is executed more than once

### ISSUE THREAD

**Issue by em230418** [odoo/odoo#65003]
Impacted versions:
12.0

Steps to reproduce:
1. Install base_automation and account modules with demo data
2. Create Automated action (Settings -> Technical -> Automated Actions):
- Model: Invoice (account.invoice)
- Trigger condition: on creation or update
- Before update domain: [("state", "!=", "paid")]
- Apply on: [("state", "=", "paid")]
- Action To Do: Execute Python Code
- Python code:
```
log("hello")
```
3. Make sure Settings -> Technical -> Logging returns empty list. If it has items - delete them
4. Open any non-paid invoice (Menu Invoicing)
5. Click Register payment, then click Validate

Current behavior:
That automated action is executed 2 times. See number of records in Settings -> Technical -> Logging.

Expected behavior:
That automated action should run once

Video/Screenshot link (commentary in Russian).

https://user-images.githubusercontent.com/52414052/105709461-8f7b6200-5f37-11eb-8ee8-ce57ca53e911.mp4

**Comment by pedrobaeza** [comment]
Although it's not the odeal, this depends on the business logic that it's involved behind these operations, and you can find that there are 1, 2 or N writes on some objects depending on the optimization of the core modules, third-party installed modules, etc.

Thus, you should articulate your automated action other way (fine-tuning domains)) for being unique, or using another tool for what you want (custom code?).

Closing as no bug.
