### ISSUE TITLE
How to change the display name of Live  Chat Operator

### ISSUE THREAD

**Issue by agilekinah** [odoo/odoo#65035]
Hello, is there any way to change the operator name in live chat box?
If yes, do you know some articles on how to do it? I am using Odoo 10
Your help is greatly appreciated. Thanks :)

![Screenshot from 2021-01-26 11-35-55](https://user-images.githubusercontent.com/78007414/105798817-f77c8780-5fcd-11eb-8b86-69a4b6fee13c.png)

**Comment by Yenthe666** [comment]
Hi,

Sorry but this is not a bug, it is a question. This is not the right place to ask this as Github is only for bugs in the code. Please post it on the official help forums at https://www.odoo.com/forum/help-1

Regards,
Yenthe
