### ISSUE TITLE
Import supplier invoice number onto supplier payment invoice

### ISSUE THREAD

**Issue by Morney** [odoo/odoo#6503]
Hello, 

I am looking at taking the supplier given invoice number and placing this number onto the supplier payment invoice, however I am struggling on how to link these fields together. 

At present I have created a new model field on the account.voucher model

I have then created a new field in the group where the supplier invoice number can go on the account.voucher.payment.form

However I now am not sure how I can get to the supplier invoice number.

Is there anyway that I can do this please?

**Comment by Yenthe666** [comment]
Hi @Morney,

Please do ask these kind of questions on the help forums (at odoo.com/help).
The bug tracker is only used for bugs in the official code.

Regards,
Yenthe
