### ISSUE TITLE
cash rounding not working 

### ISSUE THREAD

**Issue by HendryLeo** [odoo/odoo#65043]
Impacted versions: 14.0

Steps to reproduce:
1. activate cash rounding feature
2. create a rounding strategy, round half up to nearest 1
3. assign cash rounding to POS Config, apply only to cash method
4. make 1 order with amount 22.9
5. make payment, click on Cash method

Current behavior:
remaining 0.1, and cannot validate
have to press cash method again or override the amount to be able to validate

Expected behavior:
cash payment automatically rounded 23, and can validate

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/10069724/105827427-8f8d6780-5ff4-11eb-9cb0-45f949b11e83.png)
![image](https://user-images.githubusercontent.com/10069724/105827505-aa5fdc00-5ff4-11eb-9e8b-5a22fadf0a12.png)
![image](https://user-images.githubusercontent.com/10069724/105827630-ce232200-5ff4-11eb-832c-6d3a10ac1f41.png)
![image](https://user-images.githubusercontent.com/10069724/105827699-e430e280-5ff4-11eb-8697-1dceaf53936d.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
The profit and loss accounts can't be the same as the cash journal account (nor the same internal type). They should be income/expense accounts.

**Comment by HendryLeo** [comment]
Hi @pedrobaeza 
The account is not the point here.

The issue is DUE amount is not rounded correctly the first time CASH method is clicked

**Comment by Yenthe666** [comment]
@pimodoo could you have a look?

**Comment by DonFeraRRi** [comment]
Any updates on this?

**Comment by pimodoo** [comment]
Hello @HendryLeo , I've just tried on the runbot, and when I arrive on the on the payment page, the amount is correctly pre-filled with 23, which mean you've encoded 22.9 manually. So I don't really see where there is a bug.

**Comment by pimodoo** [comment]
@HendryLeo Hello again, I've just found that it happens onoly when we are in "Only Cash", I'll fix it.

**Comment by HendryLeo** [comment]
@pimodoo , yes this will only happen to "Only Cash"

**Comment by HendryLeo** [comment]
@pimodoo, I saw #69544 .
Is it somehow related to this problem?
This morning, I tried the latest runbot for Odoo 14.0 and the problem is getting worse

I set ROUNDUP
![image](https://user-images.githubusercontent.com/10069724/117237733-beb63f00-ae55-11eb-8f8d-16418f789421.png)

and use it in POS Setting
![image](https://user-images.githubusercontent.com/10069724/117237817-e6a5a280-ae55-11eb-80d5-747b60cbc424.png)

I create POS transaction for 1 item, total USD 22.9
![image](https://user-images.githubusercontent.com/10069724/117237892-12288d00-ae56-11eb-896f-c67dab28db0e.png)

Bank payment is OK
![image](https://user-images.githubusercontent.com/10069724/117237953-308e8880-ae56-11eb-92fa-6e88fb42bde0.png)

But Cash Payment is not OK
![image](https://user-images.githubusercontent.com/10069724/117238128-8b27e480-ae56-11eb-959b-535efce47572.png)

![image](https://user-images.githubusercontent.com/10069724/117238295-ccb88f80-ae56-11eb-9a35-f4beb5af64f0.png)

![image](https://user-images.githubusercontent.com/10069724/117238376-f4a7f300-ae56-11eb-9da7-92699793347e.png)

**Comment by HendryLeo** [comment]
HALF UP Rounding Strategy is OK
![image](https://user-images.githubusercontent.com/10069724/117238886-ead2bf80-ae57-11eb-9d1d-1e64dad25838.png)

ROUND DOWN is not OK
![image](https://user-images.githubusercontent.com/10069724/117239022-31281e80-ae58-11eb-8072-48fbf2826480.png)
![Uploading image.png…]()

**Comment by pimodoo** [comment]
@rhe-odoo could you have a look

**Comment by HendryLeo** [comment]
#71219 seems to fix this issue
