### ISSUE TITLE
[8.0]Expense Tax Issue

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#6507]
Hi Odoo,

I find a bug when I want to create an expense, and generate the journal entries.
The journal entries will generate the tax entries based on the not include price wherever the tax account  computation method already set to include the price or not.
1.  I set the product ledger account for expense product to be 20% tax include price on the default tax.
2.  I create the expense with that product.
3.  I confirm the expense and generate the entries.
4.  The system will generate the entries with tax that not include the price.

The expected behavior:
The tax computation in the journal entries must be based on the tax account configuration is it include or not include the price.

You can test it on the latest runbot.

Thank You.

**Comment by Yenthe666** [comment]
Hi @falinwa ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
