### ISSUE TITLE
[14] 'active': True does not install module automatically.

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#65076]
Impacted versions: 14

Steps to reproduce:  Add 'active': True on Manifest and Create new Database.

Current behavior: Module is not installed automatically

Expected behavior: As Documented at https://github.com/odoo/odoo/blob/14.0/doc/reference/module.rst
Module should be installed automatically.

```
_active (bool)
    This indicates whether this module must install automatically or not._

```
Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

Ref Commit: https://github.com/odoo/odoo/pull/44107/commits/c248f3d9cad1cd02bdec52f6c6c0e3f39f9fbd40 and https://github.com/odoo/odoo/commit/12030dde4fcc63b6bcb037084c21c24b23a91ff4

**Comment by rrahir** [comment]
This isssue looks solved in https://github.com/odoo/documentation/pull/1109. Thank you for reporting this issue !
