### ISSUE TITLE
[8.0]get traceback on_click 'confirm sale' button in sale order 

### ISSUE THREAD

**Issue by jpr-odoo** [odoo/odoo#6510]
create a new sale order with event type product then on_click 'confirm sale' button.
revision number: 65722-8-0-c09abf
 it's gives traceback:
![image](https://cloud.githubusercontent.com/assets/7599806/7385714/5378d15c-ee68-11e4-9109-9ff0ccac8bcf.png)

**Comment by Yenthe666** [comment]
Hey @jpr-odoo,

Thank you for your bug report.
This should have been fixed a while ago and shouldn't be a problem anymore. As this should be fixed and the support for Odoo 8 has stopped I'm closing this bug report.

Regards,
Yenthe
