### ISSUE TITLE
[8.0] Dissapearing Rows in One2Many field

### ISSUE THREAD

**Issue by NaGeL182** [odoo/odoo#6514]
I have the following view set up:
i have a custommodule that has a One2Many field called `ertekeles_adat_ids` and i display it so:

``` xml
<field name="ertekeles_adat_ids"
   context="{'tree_view_ref' : 'rch_tmr.view_ertekeles_adat_tree'}"/>
```

the tree view is this:

``` xml
<record id="view_ertekeles_adat_tree" model="ir.ui.view">
            <field name="name">view.ertekeles.adat.tree</field>
            <field name="model">ertekeles.adat</field>
            <field name="arch" type="xml">
                <tree string="Értékelések" editable="bottom">
                    <field name="maxdb" invisible="1"/>
                    <field name="lezarva" invisible="1"/>
                    <field name="state" invisible="1"/>
                    <field name="fix_cel" invisible="1"/>
                    <field name="min_szazalek" invisible="1"/>
                    <field name="max_szazalek" invisible="1"/>
                    <field name="kategoria_id" attrs="{'readonly':[('fix_cel','=', True)]}"/>
                    <field name="name" attrs="{'readonly':[('fix_cel','=', True)]}"/>
                    <field name="fix_cel_ertek" attrs="{'readonly':[('fix_cel','=', True)]}"/>
                    <field name="suly" attrs="{'readonly':[('fix_cel','=', True)]}"/>
                    <field name="teny_ertek" attrs="{'readonly':[('state','in', ['new'])]}"/>
                    <field name="teljesites" attrs="{'readonly':[('state','in', ['new'])]}"/>
                    <field name="comment"/>
                </tree>
            </field>
        </record>
```

and this all works. The Problem comes in when i edit multiple records from this view, and if i press enter and it jumps to the next one, if its an already existing  line with filled out fields, certain fields disappears, like the image bellow: 
![image](https://cloud.githubusercontent.com/assets/598533/7388203/ba610970-ee63-11e4-937d-3a6ecd733e6b.png)

Clicking the row again the fields reappear.  It happens in IE10&IE11 , Chrome and in Firefox as well.

**Comment by Yenthe666** [comment]
Hi @NaGeL182,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
