### ISSUE TITLE
[8.0] many2many fileds ignore relation=' ' for old api fields and use default rel table name instead

### ISSUE THREAD

**Issue by michaelkarrer81** [odoo/odoo#6515]
@rco-odoo @tgr-odoo  If i create a new many2many field for a inherited model written in the old api and use relation= the relation table will not be created but the standard (by odoo automatically named) rel. table is used or created! 

Fails - will use generated rel table name:
```python
class mail_message(osv.Model):
    _inherit = "mail.message"
    _columns = {
        'notified_by_email_ids': fields.many2many('res.partner',
                                                  relation='mail_message_res_partner_notified_by_email_rel',
                                                  string='Partners notified by e-mail'),
    }
```

**Even worse the default relation table name is used which may already be in use by another many2many field leading to the same relations for both fields!**

I suggest that 
- relation='' should work also for old api field definition
- auto created relation table names should include the many2many field name to make sure they are unique

**Comment by michaelkarrer81** [comment]
Maybe related to #5924

**Comment by rco-odoo** [comment]
@michaelkarrer81 your example code is buggy in several ways, in fact:
 * `relation` is not the right attribute name for the table in the old API;
 * you have to provide the table name **and** the column names: names are automatically generated if you don't provide the three elements.

This example should work as expected:

    class mail_message(osv.Model):
        _inherit = "mail.message"
        _columns = {
            'notified_by_email_ids': fields.many2many(
                'res.partner',
                'mail_message_res_partner_notified_by_email_rel',    # table name (rel)
                'message_id',                                        # column to self (id1)
                'partner_id',                                        # column to other (id2)
                string='Partners notified by e-mail'),
        }
