### ISSUE TITLE
[8.0] contract generate recurring invoices does not follow analytic defaults.

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#6516]
as we excepted that, if have set the analytic default, it should follow the anlytic defualt when we create invoice.  but when generate recurring invoice form contracts it does not work as  we excepted.

have reviewed the code, found that  function `_prepare_invoice_data`  of model `account.analytic.account`  does not invoke the `account_get` method of  analytic default.

i think that we should fix this .

i would to fix this in module `account_analytic_defaults`.

any feedback should be thanksful

**Comment by Yenthe666** [comment]
Hi @jeffery9,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
