### ISSUE TITLE
[14.0] the (confirm=")confirmation message(") stay displayed after validation

### ISSUE THREAD

**Issue by luffah** [odoo/odoo#65168]
Impacted versions: 14.0 (using https://github.com/OCA/OCB//archive/08978c6d2d14a94e6ee2fea0dedc805a56378de0 )

# Steps to reproduce: 
There is 2 way to reproduce (using a custom view, or digging in existing wizards).
## Custom view
Make a new view with confirm="", for example attachment_ids (added to any model).
```python
    attachment_ids = fields.One2many('ir.attachment', 'res_id',
                                    domain=lambda self: return [('res_model', '=', self._name)],
                                    string='Documents')
```
```xml
                    <field name="attachment_ids" readonly="1">
                        <tree editable="bottom">
                            <field name="name"/>
                            <field filename="name" name="datas" widget="file"/>
                            <field name="create_date" string="Deposited on"/>
                            <button icon="fa-trash-o" name="unlink"  type="object" confirm="Remove this attachment?"/>
                        </tree>
                    </field>
```
When you try to remove the attachment , the confirmation message appears. You can click YES, and then the attachment is removed, but the confirmation popup still here.

## Existing case
In Contact list, switch to list view, select some contacts, and itn 'Actions', click 'Merge' contacts to open base_partner_merge wizard. Click 'Merge Contacts", next select a filter and "Merge Automatically". You will have a confirmation popup. Click Yes to open another wizard : just close it. The confirmation popup still here but do no action.

# Expected behavior
The confirmation popup shall disappear once it triggered the operation or opened another wizard.

**Comment by Yenthe666** [comment]
@Feyensv maybe something for you? :)

**Comment by Feyensv** [comment]
This looks like a JS framework issue and that's not really my scope :sweat_smile:

**Comment by Yenthe666** [comment]
I summon you, the almighty @ged-odoo

**Comment by HarshitKsolves** [comment]
is it reolved?

**Comment by Yenthe666** [comment]
If you have an enterprise database please report it under odoo.com/help, then it gets a priority

**Comment by HarshitKsolves** [comment]
> If you have an enterprise database please report it under odoo.com/help, then it gets a priority

Resolved taken pull of latest odoo code
