### ISSUE TITLE
Missing functionality: set the purchase order as received

### ISSUE THREAD

**Issue by ybofr** [odoo/odoo#6517]
Step to reproduce:
1. Create and confirm a PO
2. cancel the delivery
3. recreate a delivery
4. Receive the goods.
5. Sometimes the system does not update the field goods received in the PO (it depends on many factors linked to the cancelling and/or the dates...difficult to reproduce

Expected behavior
The possibility to set the PO as received when all quantities are received and when due to some technical issue, the status was not set automatically.

**Comment by Yenthe666** [comment]
Hi @ybofr,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
