### ISSUE TITLE
[Google_Calendar] Google calendar not updating

### ISSUE THREAD

**Issue by mba-odoo** [odoo/odoo#6518]
varsion 8.0, saas-6
Issue:

Create an event and set the start date and end date of event, Now syn it with google calendar.
Go to calendar on instance and click on event >> click on edit event.
In edit mode change the date of event and save it, Now click on Sync with Google it will not update in google calendar.

See here: http://goo.gl/5GfzLC

Expected Result:
 On change of Event Start date and end date the google calendar is updated after synchronization.

**Comment by Yenthe666** [comment]
Hi @mba-odoo,

Thanks for your bug report.
As Odoo 8 is no longer supported I'm closing this report. If you can still reproduce this on 9.0, 10.0 or 11.0 I encourage you to create a new report.

Regards,
Yenthe
