### ISSUE TITLE
[V8]Some files are missing in rpm

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#6521]
Hy,

I've just reported  #6356 that could come from the fact that the audio file is missing.
Additionnally, when using rpm to be up to date, it seems that some other files are missing.
For example openerp-wsgi.py is no more shipped in the rpm, is it normal?

Thanks for your feedback

**Comment by flotho** [comment]
Hi @sle-odoo, as this part couldn't be managed by pull requests, is it possible to be reviewed and check if all the files are "pushed" in the rpm?
regards

**Comment by sle-odoo** [comment]
Hi,
I just extracted odoo_8.0.20150519.noarch.rpm and you're right, openerp-wsgi.py and the audio files are missing. I'm not sure about the first but to make the audio files appear it should be straightforward: include them in the MANIFEST.in file. I'll have a look into that but i'm pretty busy at the moment.

Regards

**Comment by flotho** [comment]
@sle-odoo , no problem I understand you're busy.
I'll wait your action.
regards

**Comment by flotho** [comment]
also closed by #7569 and  #7352
