### ISSUE TITLE
SUPERUSER invalid writing cost_price in multi-company situation

### ISSUE THREAD

**Issue by KevinMcMenamin** [odoo/odoo#6523]
In a multi-company environment there is no guarantee that the superuser will be in the same company as the user updating average cost (by way of receiving goods). I have tested this in a simple 2 company environment and the average price for the wrong company gets updated.

We had a module in V6 to resolve the access user issue (which largely doesn't exist in V8) but the same logic should be used - any write to a property field should look up the users company record and get the special user (who would be set up with the correct rights) which is then used for the update.

see stock_account _store_average_cost_price for example of incorrect logic.

This is affecting an in production company with a support agreement.

**Comment by KevinMcMenamin** [comment]
**Average cost not updated to correct company **

Impacted versions:

 - 8.0

Steps to reproduce:

 1. create 2 companies. Create a product that is not company specific with average cost method
 2. have admin user in company 1
 3. have non-admin user log in to company 2 & receive goods.

Current behavior:

 - Average cost is updated to company 1 (ie the superuser company) 

Expected behavior:

 - Average cost should update the product in the user company (ie company 2)


Check ir_values to see invalid results. 

Note - this error was introduced by a pull request to solve another problem, so ideally fixing this should not re-introduce the original problem.

The original code used the user's credentials to update average cost, but this required the user to have write access to products which they may not have (typically you do not want an inwards goods person being able to update product data).

Our solution has been to have a special user by company which is configured in the company record. This special user has superuser type access so no security issues, but are limited to a single company.

**Comment by Yenthe666** [comment]
Hi @KevinMcMenamin,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
