### ISSUE TITLE
LiveChat on multiple databases not working with WSGI

### ISSUE THREAD

**Issue by marcosbc** [odoo/odoo#6524]
**LiveChat on multiple databases not working with WSGI**

Impacted versions:

 - 8.0

Steps to reproduce:

 1. Set up Odoo with WSGI, make also sure that you do a reverse-proxy on `/longpolling`.
 2. Make sure you have, at least, 2 databases. If not, create them.
 3. Open two independant browsers (e.g. Firefox normal window with a private window):
 4. Browser 1:
    1. Login at Odoo in database 1.
    2. Enable LiveChat.
    3. Go to the LiveChat page (will be referred as LiveChat page 1).
 5. Browser 2:
   1. Login at Odoo in database 2.
   2. Enable LiveChat.
   3. Go to the LiveChat page (will be referred as LiveChat page 2).

Current behavior:

 - Both chats (in LiveChat page 1 and LiveChat page 2) show up.
 - When sending messages, they don't work.
 - When looking at error logs, you see the following:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/odoo-8.0_20150427-py2.7.egg/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/local/lib/python2.7/dist-packages/odoo-8.0_20150427-py2.7.egg/openerp/http.py", line 1399, in _dispatch_nodb
    func, arguments = self.nodb_routing_map.bind_to_environ(request.httprequest.environ).match()
  File "/usr/lib/python2.7/dist-packages/werkzeug/routing.py", line 1433, in match
    raise NotFound()
NotFound: 404: Not Found
```
 - When looking at Firebug, you see the following error for each request to `/longpolling` (the same one as before):
```
Server application error Object { message="Odoo Server Error",  code=200,  data={...}}
```

Expected behavior:

 - Both chats should be working correctly, independently and without interference.
 - No errors should appear in the error logs.

**Comment by mart-e** [comment]
@jem-odoo will probably answer better than me this but two questions:

- are you using a [db-filter](https://www.odoo.com/documentation/8.0/setup/deploy.html#dbfilter) ? (mandatory for multi-instances)
- have you checked #3437 ? There is some information on the configuration of the server

**Comment by marcosbc** [comment]
I was currently using the same WSGI script. So is it mandatory to use a dbfilter for each longpolling process? I mean, even if you are using the databases in the same domain name.

**Comment by marcosbc** [comment]
Hi, I was able to get it working but I had to specifying the `db-filter` option and the `longpolling_port` for both the `openerp-gevent`, create a copy of the `openerp_wsgi.py` configuration file and set up the same options there (`db-filter` and `longpolling_port`), too.
Then, I had to create a separate virtual host, configure each one to use a WSGI file and making each one do a reverse-proxy to the longpolling port.

It is a bit messy, but it works at least.

I hope it helps others who face the same issue! Thanks!

**Comment by wangsamas** [comment]
Hi, I'm installing odoo 12 using bitnami and facing the same problem.
please explain more about the solution

**Comment by marcosbc** [comment]
Hi @wangsamas,

This is the solution we identified back in 2015.

Please note it is not updated for an Odoo 12 install. Some things that have likely changed are the WSGI script filename (openerp.wsgi is probably odoo.wsgi now) and the service names (now they start with "odoo_", not "openerp_"). Keep in mind there will probably be other changes as well.


> We have been able to find a fix to this issue, but it is not simple because many changes are involved. We will modify the stack on our side to make these changes easier to apply.
>
> The issue is happening because of the following causes:
> - Using mod_wsgi for accessing Odoo. This is a Bitnami configuration.
> - Make use of openerp_gevent (which is currently only being used for the Odoo Live Chat).
> - Having multiple databases and not configuring the pages correctly.
>
>I will try to do my best in explaining why this happens: Odoo works correctly because it is able to get the current session and the cookies from the current user and domain. However, openerp_gevent does not, so it needs to know which database we currently want to access.
>
> To fix this, I will try to summarize first all things that will need to be changed, and then proceed to giving specific instructions:
> - Since openerp_gevent runs on HTTP ports, for each new database, openerp_gevent will need to run on a different port with a different dbfilter. This implies that, for N databases, you will need to run N openerp_gevent processes, using each one a different port.
> - We configure openerp_gevent to run with Apache (and Odoo runs on Virtual Hosts), so this means that we will need one virtual host per openerp_gevent process (which has a dbfilter to a database's name).
> - Since each virtual host is configured to use a specific WSGI configuration file, you will need to create one WSGI script (each with a longpolling_port and dbfilter attribute specified). You can check more information here: 
>   - https://www.odoo.com/documentation/8.0/setup/deploy.html#dbfilter
>   - https://github.com/odoo/odoo/issues/6524#issuecomment-97754297
>
>
> I have created the following guide so you can check this before doing the changes to the installer. In this example, we are supposing you are using two databases ("first" and "second"):
>
>
>1. Make sure you have created N (in this example, and from now on, N is 2) virtual hosts in `ODOO_INSTALLDIR/apps/odoo/conf`, based on httpd-vhosts.conf, and the same number of Apache app configuration files ("first-httpd-app.conf" and "second-httpd-app.conf"), which you can base on "httpd-app.conf". Therefore, you would have, in this example, the following files:
>    - first-httpd-vhosts.conf
>    - second-httpd-vhosts.conf
>    - first-httpd-app.conf
>    - second-httpd-app.conf
>2. Create N (in this example, 2) "openerp.wsgi" copies: "first-openerp.wsgi" and "second-openerp.wsgi".
>3. Update "first-httpd-app.conf" and "second-httpd-app.conf". On each of these:
>   1. Rename the process name and group from wsgi-odoo to first-wsgi-odoo and second-wsgi-odoo, respectively, in both files.
>   2. Replace openerp.wsgi in both files, by first-openerp.wsgi and second-openerp.wsgi respectively.
>   3. In the end of these, make sure the following lines are added (do not duplicate them, replace PORT by 8000 and 9000 respectively, and DBNAME by first and second respectively):
>
>          ProxyPass /longpolling/poll http://localhost:PORT/longpolling/poll/
>          ProxyPass /DBNAME-openerp.wsgi/longpolling/poll http://localhost:9000/longpolling/poll/
>          ProxyPass /longpolling/poll/ http://localhost:PORT/longpolling/poll/
>          ProxyPass /DBNAME-openerp.wsgi/longpolling/poll/ http://localhost:9000/longpolling/poll/
>          ProxyPassReverse /longpolling/poll/ http://localhost:PORT/longpolling/poll/
>          ProxyPassReverse /DBNAME-openerp.wsgi/longpolling/poll/ http://localhost:PORT/longpolling/poll/
>
>4. Update "first-httpd-vhosts.conf" and "second-httpd-vhosts.conf". On each of these, update the following things:
>   1. Server name and alias. The server domain name and alias must be different since, from now one, you will have to access them from different domains.
>   2. Make sure they include "first-httpd-app.conf" and "second-httpd-app.conf", respectively, instead of simply "httpd-app.conf".
>
>5. Modify each WSGI configuration files: Add the following lines to first-openerp.wsgi and second-openerp.wsgi files, where your_database is "first" or "second" respectively, and where "your_longpolling_port" is "8000" and "9000" respectively:
>
>        conf['dbfilter'] = '^your_database$'
>        conf['longpolling_port'] = 'your_longpolling_port'
>
>    So it would be, for "first-openerp.wsgi":
>
>        conf['dbfilter'] = '^first$'
>        conf['longpolling_port'] = '8000'
>
>    And for "second-openerp.wsgi":
>
>        conf['dbfilter'] = '^second$'
>        conf['longpolling_port'] = '9000'
>
>6. Remove the mention of "odoo/conf/httpd-app" in "/opt/bitnami/apache2/conf/bitnami/bitnami-apps-vhosts.conf", and add the following lines:
>
>        Include "/opt/bitnami/apps/odoo/conf/first-httpd-vhosts.conf"
>        Include "/opt/bitnami/apps/odoo/conf/second-httpd-vhosts.conf"

**Comment by wangsamas** [comment]
Hi, thanks for the answer.

for documentation, I post here the files that I found
/opt/bitnami/apps/odoo/conf/odoo-server.conf
/opt/bitnami/apps/odoo/conf/httpd-vhosts.conf
/opt/bitnami/apps/odoo/conf/httpd-app.conf
/opt/bitnami/apps/odoo/scripts/odoo.wsgi

I'm using only 1 database, so I just edit odoo.wsgi to add these code
conf['dbfilter'] = '^bitnami_odoo$'
conf['longpolling_port'] = '8072'
it doesn't work, I keep on getting OSError: [Errno 98] Address already in use: ('0.0.0.0', 8072)

btw, I don't understand no 6.
which file should ProxyPass in?

**Comment by wangsamas** [comment]
I found it already in /opt/bitnami/apps/odoo/conf/httpd-app.conf like this

ProxyPass /odoo.wsgi/longpolling/poll http://localhost:8072/longpolling/poll/
ProxyPass /odoo.wsgi/longpolling/poll/ http://localhost:8072/longpolling/poll/
ProxyPass /longpolling/poll http://localhost:8072/longpolling/poll/
ProxyPass /longpolling/poll/ http://localhost:8072/longpolling/poll/
ProxyPassReverse /longpolling/poll/ http://localhost:8072/longpolling/poll/

**Comment by wangsamas** [comment]
the error that I keep on getting is like this

2019-03-29 07:47:14,295 7756 INFO ? odoo.service.server: Evented Service (longpolling) running on 0.0.0.0:8072
2019-03-29 07:47:14,296 7756 ERROR ? odoo.service.server: Evented Service (longpolling): uncaught error during main loop
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/service/server.py", line 507, in start
    self.httpd.serve_forever()
  File "/opt/bitnami/python/lib/python3.7/site-packages/gevent-1.3.7-py3.7-linux-x86_64.egg/gevent/baseserver.py", line 362, in serve_forever
    self.start()
  File "/opt/bitnami/python/lib/python3.7/site-packages/gevent-1.3.7-py3.7-linux-x86_64.egg/gevent/baseserver.py", line 306, in start
    self.init_socket()
  File "/opt/bitnami/python/lib/python3.7/site-packages/gevent-1.3.7-py3.7-linux-x86_64.egg/gevent/pywsgi.py", line 1487, in init_socket
    StreamServer.init_socket(self)
  File "/opt/bitnami/python/lib/python3.7/site-packages/gevent-1.3.7-py3.7-linux-x86_64.egg/gevent/server.py", line 146, in init_socket
    self.socket = self.get_listener(self.address, self.backlog, self.family)
  File "/opt/bitnami/python/lib/python3.7/site-packages/gevent-1.3.7-py3.7-linux-x86_64.egg/gevent/server.py", line 157, in get_listener
    return _tcp_listener(address, backlog=backlog, reuse_addr=cls.reuse_addr, family=family)
  File "/opt/bitnami/python/lib/python3.7/site-packages/gevent-1.3.7-py3.7-linux-x86_64.egg/gevent/server.py", line 256, in _tcp_listener
    sock.bind(address)
OSError: [Errno 98] Address already in use: ('0.0.0.0', 8072)
