### ISSUE TITLE
Changing Reference on Supplier Payment Report

### ISSUE THREAD

**Issue by Morney** [odoo/odoo#6527]
Hello, 

I am trying to change the reference field of the table on the Supplier Payment Report print so that it only shows the reference in the brackets (as they repeat each other).

I have been able to change the first row of the table but it wont change any other row, the code I have used is as followed:

```
            <td class="lines-cell-ref" name="test_cell">
                <span id="test" t-field="l.move_line_id" />
                                   <script>
                window.onload = function() { 
                $test = document.getElementById('test').innerHTML;
                $testing = $test.replace(/[()]/g, ''); 
                document.getElementById('test').innerHTML = $testing.substr(5);
                }
                </script>
            </td>
```

The script changes the value of the first row reference by deleting the first 4 numbers and deleting the brackets. 

How would I repeat this for each row please?

**Comment by Yenthe666** [comment]
Hi @Morney,

Please do ask these kind of questions on the official help forums (at odoo.com/help).
The Github bug tracker is only used for bug reports in the official code, it is not the place to ask about custom development.

Regards,
Yenthe
