### ISSUE TITLE
[7.0] Wrong Inventory Value if Force Assignment of Deliveries

### ISSUE THREAD

**Issue by msteinfeld** [odoo/odoo#6528]
**Outcoming Quantity is wrong, when forced assignment of Deliveries**

Impacted versions:
- 7.0

Steps to reproduce:
1. Create a Product
2. Buy 266
3. Deliver 266 into stock
4. Deliver 797 with force assignment of difference
5. Make an Inventory to 3 of that product
6. => New Stock: 534

Current behavior:
- new Qty = 534

Expected behavior:
- new Qty = 3

Debugged that time and found out, that here is something strange in def product_get_multilocation.
And the calculating of variable "change".

**Comment by msteinfeld** [comment]
In the meantime i get, that it is not only forcing assignment of stock, it is some kind of mix with lt numbers.

So i have to update my steps t reproduce:

1. Create a product
2. Buy 797
3. Deliver in with lot number
4. Deliver out 794 without lot number
5. Make an inventory to 3 without lot number
6. => New Stock 534

**Comment by Yenthe666** [comment]
Hi @msteinfeld,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
