### ISSUE TITLE
V14 CE - User access error

### ISSUE THREAD

**Issue by cybtech** [odoo/odoo#65306]
Impacted versions:
V14 CE

Steps to reproduce:

1. Install Odoo on Centos / Ubuntu Server (Postgres 10)
2. Create a new database
3. Login to Odoo
4. Install CRM only
5. Click at the left top corner, and choose "Settings".
6. Click again on "Settings"

Current behavior:
It shows a User access error: "Record cannot be modified right now: This cron task is currently being executed and may not be modified Please try again in a few minutes"

Expected behavior:
Should not show the error message

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/42453256/106340905-50b41780-6269-11eb-92cb-237f3c1f2727.png)

This is caused by the "Lead Enrichment" option. If we uncheck it, the error disappears.

**Comment by pedrobaeza** [comment]
This is not an issue, but a thing to avoid race conditions. That cron is currently running, so until it finishes, you can't deactivate it. Try later.

Closing thus.
