### ISSUE TITLE
[Issue] portal : impossible to update your login

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#65305]
Impacted versions: 14.0 and later

Steps to reproduce:
- go to runbot
- install website
- allow free signin
- create a new account
- go to in your home
- update the email adress (it should be your login)
--> Issue the login it is not updated

@odony

**Comment by pedrobaeza** [comment]
This is something expected, as you can't change your login unique identifier. You can change the "notification email" for that login, but not the login itself. If allowed, that can have other security consequences. For that kind of changes, a backend admin user should intervene.

I let the issue opened if Olivier or anybody else want to expand the information, but if not, I will close it in some days.
