### ISSUE TITLE
[14.0] Project Manager cannot duplicate projects

### ISSUE THREAD

**Issue by cvinh** [odoo/odoo#65310]
Impacted versions:
14.0-ce
Steps to reproduce:
on last runbot, log in with demo user
Select a project and duplicate it
Current behavior:
the security does not allow to write mail.alias.
The project is not duplicated
Expected behavior:
the project should be duplicated without error
Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by cvinh** [comment]
cc @LuceEasyPme

**Comment by estudioalfa** [comment]
Hello @cvinh,

I solved the issue by setting allowing the user to read, write and create mail.alias.user in his permissions access configuration.

Go to settings, users, choose the user, click on permissions tab (link above the user avatar). 

In the next screen search for mail.alias.user permission, click on the record, click edit button and add write and create permissions and it will be solved.

Hope it helps!

**Comment by estudioalfa** [comment]
![image](https://user-images.githubusercontent.com/1329054/110917297-0c14a500-831a-11eb-8cfc-655df9f01efd.png)

![image](https://user-images.githubusercontent.com/1329054/110917133-dbcd0680-8319-11eb-935e-88a3739ad76c.png)

![image](https://user-images.githubusercontent.com/1329054/110917409-2a7aa080-831a-11eb-88ce-1bd1d00260c1.png)

**Comment by rafaelbn** [comment]
This issue is solved here: https://github.com/odoo/odoo/pull/70315
