### ISSUE TITLE
Can't access odoo after reinstall Odoo 8 Windows 

### ISSUE THREAD

**Issue by balmes92** [odoo/odoo#6532]
Hi,
I'm trying to reinstall Odoo 8 all-in-one in Windows server 2012. First installation worked without any problem. I removed odoo and postgree, and installed again same versión, the installator finished without errors, but when the initial url opens, It allways redirects to http://localhost:8069/web/database/manager , and this page only shows the odoo logo. Seems that this page is for manage the current databases.
I can't start the steps to create the database.
I tried to install last versión with same result.

Thanks in advance.

**Comment by MehdiF2T** [comment]
hello,
I do have exactly the same problem, I dont know if you found a solution. I installed it today and I think that there is a problem in the postgresql configuration.
Thnx to shae if you have any clue,

**Comment by Yenthe666** [comment]
Hi @balmes92,

Thanks for your report. It looks like you've had implementation issues and that your deployment is the problem of the cause. In the meanwhile we've gotten documentation for this at https://www.odoo.com/documentation/11.0/setup/deploy.html

Regards,
Yenthe
