### ISSUE TITLE
Fetchmail with multi company

### ISSUE THREAD

**Issue by bkautap** [odoo/odoo#65340]
Impacted versions: 14

Steps to reproduce: 

Setup Odoo with multicompany (at least 2)
Setup fetchmail and let the new mail create a task

Current behavior:

Fetchmail fetch the mail and creats a task the first company

Expected behavior:

When creating a task via fetchmail, we like to add the company where the mail has to land

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
You have to change your alias to provide such default value `company_id`.

Closing as no real issue.

**Comment by bkautap** [comment]
Dear Pedrobaeza,

Could you explain?

If i have multi companies,
all have several mail accounts per company.

How can i create a alias where i can fill company_id?

Thanks

**Comment by pedrobaeza** [comment]
mail.alias model in Odoo has this. For more questions, please go to forum.
