### ISSUE TITLE
AUD currency symbol defaults to incorrect position.

### ISSUE THREAD

**Issue by gigaplus** [odoo/odoo#6535]
In Odoo 8.0 there is an issue with the default symbol position for currency AUD (Australia).
It displays default as 99.99$ when it should be $99.99
(See attached screenshot) Should default to "Before Amount"
![aud error](https://cloud.githubusercontent.com/assets/7801740/7424482/ea4bd2e6-efe4-11e4-9a41-6c54aa2d4bae.png)

**Comment by mart-e** [comment]
Fixed (some time ago) at 91aa012ed030c9927f49fd1d799321744729ef83
