### ISSUE TITLE
Supplier minimum quantity applied individually to multiple SO with same product resulting to large draft PO quantity when scheduler is run

### ISSUE THREAD

**Issue by aldennis** [odoo/odoo#6536]
This can be determine by doing the following:
- Create a new MTO product (Routes = Buy, Make to Order)
- Indicate a Supplier with minimum quantity set to 5 in the procurement section of the MTO product
- Create 2 separate SO with different customer but with same MTO product in their order line and set quantity of SO1 to 3 and SO2 to 2
- Confirm SO1 and SO2
- Run Scheduler under Warehouse/ Schedulers
- Generated Draft PO will indicate MTO product with 10 quantity

**Comment by jco-odoo** [comment]
There is a pull request for this for v8.

**Comment by aldennis** [comment]
I've seen the pull request #6206 already merged. I'll be updating our installation with the latest version. Closing this issue for now.
