### ISSUE TITLE
[8.0] Fiscal Year, constraint error

### ISSUE THREAD

**Issue by ddfs** [odoo/odoo#6537]
installed a fresh odoo. using 20150430 codebase

installed accounting module skipped creating fiscal year using wizard. 

accounting / configuration / periods / fiscal year.. created a new here  manually. monthly or 3 months periods pick one.

moved to configuration / accounting  to set default sale / purchase taxes.. and getting the following error. 

---

Constraint Error
## The name of the period must be unique per company! 

the exception:

``` log
2015-05-01 08:05:45,949 11797 ERROR odoodb openerp.sql_db: bad query: UPDATE "account_period" SET "company_id"=1 WHERE id = 28
Traceback (most recent call last):
  File "/opt/workspace/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: duplicate key value violates unique constraint "account_period_name_company_uniq"
DETAIL:  Key (name, company_id)=(Opening Period 2015, 1) already exists.

2015-05-01 08:05:45,950 11797 ERROR odoodb openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/workspace/odoo/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/workspace/odoo/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/opt/workspace/odoo/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/workspace/odoo/openerp/service/model.py", line 129, in wrapper
    raise openerp.osv.orm.except_orm(_('Constraint Error'), tr(registry._sql_error[key], 'sql_constraint') or inst[0])
```

tried out:

deleting the period and creating it using wizard.. 

creating periods manually

no help.

**Comment by ddfs** [comment]
another fresh installation, fresh db. still same problem

**Comment by ddfs** [comment]
delete all lines in db account_fiscalyear and account_period

goto settings/configuration accounting, create new fiscal year using wizard, 

fiscal start-ends:  25/03/2015 - 31/12/2015

creates all monthly periods. but throws the same constraint error when trying to update something in same window.

on the other hand... if you generate 1 full fiscal year 25/03/2015 - 25/03/2016 then there is no problem. yet that doesn't work for me.

**Comment by ddfs** [comment]
diff --git a/openerp/addons/account/res_config.py b/openerp/addons/account/res_config.py
index bc44920..a06ef7c 100644
--- a/openerp/addons/account/res_config.py
+++ b/openerp/addons/account/res_config.py
@@ -299,11 +299,22 @@ class account_config_settings(osv.osv_memory):
             res['value'] = {'income_currency_exchange_account_id': False, 'expense_currency_exchange_account_id': False}
         return res
     
-    def onchange_start_date(self, cr, uid, id, start_date):
-        if start_date:
+    # def onchange_start_date(self, cr, uid, id, start_date):
+    #     if start_date:
+    #         start_date = datetime.datetime.strptime(start_date, "%Y-%m-%d")
+    #         end_date = (start_date + relativedelta(months=12)) - relativedelta(days=1)
+    #         return {'value': {'date_stop': end_date.strftime('%Y-%m-%d')}}
+    #     return {}
+
+    def onchange_start_date(self, cr, uid, id, start_date, stop_date):
+        if start_date and stop_date:
             start_date = datetime.datetime.strptime(start_date, "%Y-%m-%d")
-            end_date = (start_date + relativedelta(months=12)) - relativedelta(days=1)
-            return {'value': {'date_stop': end_date.strftime('%Y-%m-%d')}}
+            stop_date = datetime.datetime.strptime(stop_date, "%Y-%m-%d")
+
+            if not stop_date >= datetime.datetime.today():
+                end_date = (start_date + relativedelta(months=12)) - relativedelta(days=1)
+                return {'value': {'date_stop': end_date.strftime('%Y-%m-%d')}}
+
         return {}
 
     def open_company_form(self, cr, uid, ids, context=None):

**Comment by ddfs** [comment]
diff --git a/openerp/addons/account/res_config_view.xml b/openerp/addons/account/res_config_view.xml
index f5d071f..6e73aac 100644
--- a/openerp/addons/account/res_config_view.xml
+++ b/openerp/addons/account/res_config_view.xml
@@ -92,7 +92,7 @@
                             <div>
                                 <label for="date_start" string="Date Range"/>
                                 <field name="date_start"
-                                    on_change="onchange_start_date(date_start)"
+                                    on_change="onchange_start_date(date_start, date_stop)"
                                     class="oe_inline"
                                     help="The fiscal year is created when installing a Chart of Account."/> -
                                 <field name="date_stop" class="oe_inline"/>

**Comment by ddfs** [comment]
changes does the job 

yet one thing remains unclear:

account.config.settings -> on update generates new record in db every time you click Save from Settings / Configuration / Accounting. 

why to stuff db with multiple records?

**Comment by WnP** [comment]
Please learn how to use markdown syntax, especially block code to make your comments readable
 
```diff
this is a bock code! with diff syntax highlighting 
+ foo
- bar
```
[Here is the reference](https://guides.github.com/features/mastering-markdown/)

**Comment by ddfs** [comment]
@WnP  you already know it so, i don't need to.

**Comment by WnP** [comment]
@ddfs if you know it, just use it!

**Comment by ddfs** [comment]
@WnP for me long time no coding, i don't remember everything anymore so not gonna argue. i will try to use.

**Comment by ddfs** [comment]
@WnP  happy now?

**Comment by Yenthe666** [comment]
Hi @ddfs ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
