### ISSUE TITLE
Odoo is very slow in Production database with large data and multi-workers

### ISSUE THREAD

**Issue by HaydarZaraki** [odoo/odoo#65376]
Impacted versions:
13 Enterprise
Steps to reproduce:

Current behavior:

The System is taking so much time loading views and forms daily in peak hours

### I'm using Odoo 13 EE on vps server with the following specs:

**RAM: 256 GB**
Architecture: x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):    20
Thread(s) per core:  2
Core(s) per socket:  10
CPU family:          6
Model:               79
**Model name:          Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz**
Stepping:            1
CPU MHz:             1200.846
CPU max MHz:         3100.0000
CPU min MHz:         1200.0000
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            25600K

### odoo-server.conf
**workers = 13
limit_memory_hard = 12719476736
limit_memory_soft = 10719476736**

### Daily Usage of the odoo system:
- We Have More than **80 POS Sessions Daily** with more than **300000+ products** (We already tried to install **POS Cache** Module but the system still slow) the sessions takes more than **20-30 minutes** Loading Time to open and **10-20 minutes** to close
- We Close Sessions Daily but like i said it takes tremendous time to load and close sessions
- Inventory Application is also slow when loading Transfers and moves (any view with large records) + it takes **10-20 minutes** to validate transfers.
- We Have more than **1,000,000 Records** of POS Orders until this day and more than **900,000 Transfers** in Inventory
- **we're very concerned that Odoo Can't Handle this amount of data**

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
Unless you have specific traces of a slow query or operation, this can't be qualified to be an issue, as there's no possible steps to reproduce the problem and it can even be a bad deployment or third-party modules breaking the performance.

Closing thus.
