### ISSUE TITLE
l10n_multilang No account.group name filed is not translated

### ISSUE THREAD

**Issue by rosenvladimirov** [odoo/odoo#65375]
Impacted versions: 13.0

Steps to reproduce: Install l10n_multilang

Current behavior: No account.group translate

Expected behavior: No field name from account.group model

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
The field has been made translatable in 14.0:

https://github.com/odoo/odoo/blob/14.0/addons/l10n_multilang/models/account.py#L33

Closing then as fixed in later version.
