### ISSUE TITLE
/web/static/src/scss/asset_styles_company_report.scss referenced in xml but NOT EXIST !

### ISSUE THREAD

**Issue by vanderperre** [odoo/odoo#65377]
Impacted versions:13.0

Steps to reproduce:see addons/web/views/report_templates.xml, Line 28

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
It's injected in real time:

https://github.com/odoo/odoo/blob/8b5d9f08058dee48a2579b120eeabd7281753715/addons/web/data/report_layout.xml#L28-L34
