### ISSUE TITLE
[8.0] Finnish Accounting

### ISSUE THREAD

**Issue by ddfs** [odoo/odoo#6538]
Finnish accounting charts and taxes.. it has been missing for years. anytime it will be official in i10n ?

**Comment by mlaitinen** [comment]
There are two non-official chart of accounts under development. First is based on Raportointikoodisto (https://github.com/avoinsystems/l10n_fi_rapko) and the second one is based on Liikekirjuri (https://github.com/OCA/l10n-finland/pull/1, not merged yet).

Not sure if Odoo S.A. would do these by themselves. I believe other COA's are also contributions.

**Comment by ddfs** [comment]
yes, i have already found them before but avaoinsystems are lack of translations (i m not finnish speaker). i found another for version 5 has translations too but not compatible.

and having some modification in account/sale module to generate reference/viite numero for invoices compatible with finvoice would be great too.

**Comment by mlaitinen** [comment]
We have created two payment reference generators; one for Finnish banks (last digit checksum) and one with the international RF reference. We are going to release them for free, but unfortunately I can't say when. They currently aren't their own modules, but I think they should be, so Finnish companies could choose which reference type to use.

**Comment by ddfs** [comment]
i was planing to use your generators to integrate but no time yet. 
I am not a full-time developer, just fixing things when really needed.

**Comment by Yenthe666** [comment]
Hi @ddfs,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
