### ISSUE TITLE
[8.0] fresh DB - error when installing account_accountant

### ISSUE THREAD

**Issue by Karsten-77** [odoo/odoo#6539]
Hello,

After setup new db and installing my first modul which depends on account, I got following error.
Can be reproduced with any modul which depends on account.
Iam on current branch 8.0.

`2015-05-01 14:57:00,259 15812 INFO develop openerp.modules.loading: loading account/account_view.xml`
`2015-05-01 14:57:02,004 15812 DEBUG develop openerp.tools.convert: Context value ({'search_default_account_id': [active_id], 'fiscalyear': context.get('fiscalyear')}) for element with id "action_account_items" or its data node does not parse at server-side, keeping original string, in case it's meant for client side only`
`Traceback (most recent call last):
  File "/opt/workspace/odoo/openerp/tools/convert.py", line 259, in get_context
    ctx_res = unsafe_eval(ctx, eval_dict)
  File "<string>", line 1, in <module>
NameError: name 'context' is not defined`
`2015-05-01 14:57:12,394 15812 INFO develop openerp.modules.loading: loading account/account_report.xml`

Perhaps next error is caused by top, after configure chart_wizard website never stops loading, without any error. After refreshing the page, this error appears:

`2015-05-01 15:34:31,076 16484 ERROR develop openerp.sql_db: bad query: INSERT INTO "account_account" ("id", "currency_id", "code", "reconcile", "name", "level", "company_id", "user_type", "shortcut", "note", "parent_id", "currency_mode", "active", "type", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval('account_account_id_seq'), NULL, '101300', false, 'Roh- Hilfs- und Betriebsstoffe (Bestand)', 6, 1, 19, NULL, NULL, 178, 'current', true, 'other', 1, 1, (now() at time zone 'UTC'), (now() at time zone 'UTC')) RETURNING id
Traceback (most recent call last):
  File "/opt/workspace/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update
CONTEXT:  SQL statement "SELECT 1 FROM ONLY "public"."res_users" x WHERE "id" OPERATOR(pg_catalog.=) $1 FOR KEY SHARE OF x"

2015-05-01 15:34:31,077 16484 INFO develop openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.7370 sec...`

For the moment it isnt possible to set up charts for the default company.
When trying to use action for configure chart manuell this error appears:

`2015-05-01 15:56:41,065 16484 ERROR develop openerp.sql_db: bad query: UPDATE "res_company" SET "paypal_account"=NULL,"write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (1)
Traceback (most recent call last):
  File "/opt/workspace/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-05-01 15:56:41,066 16484 INFO develop openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.5627 sec...`

**Comment by ddfs** [comment]
concurrent update? are you running your odoo instance with  " -u all  " parameter ?

**Comment by Karsten-77** [comment]
No, iam not using "-u all" my executed instance:

/opt/workspace/Odoo8env/bin/python /opt/workspace/ide/pycharm-community-4.0.6/helpers/pydev/pydevd.py --multiproc --client 127.0.0.1 --port 51042 --file /opt/workspace/odoo/odoo.py -c openerp-server.conf

**Comment by matheo** [comment]
I just got a similar error message on a clean install of 9.0c (9.0 branch of the repository):
```
2016-03-17 16:53:26,446 5507 INFO ecom openerp.modules.loading: loading mail/wizard/mail_compose_message_view.xml
2016-03-17 16:53:26,518 5507 DEBUG ecom openerp.tools.convert: Context value ({                             'default_composition_mode': 'mass_mail',                             'default_partn$
Traceback (most recent call last):
  File "/opt/odoo/odoo/openerp/tools/convert.py", line 226, in get_context
    ctx_res = unsafe_eval(ctx, eval_dict)
  File "<string>", line 1, in <module>
NameError: name 'context' is not defined
```
