### ISSUE TITLE
[V8]Website Insert Blocks are no more visible

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#6540]
Hy,

Today, while I was editing many many pages, my Insert Block button disappears.
Impossible to find what happens.
What I can observe is that the part of the html code that is responsible of this is as follow  :

```
<button type="button" data-action="snippet" class="hidden btn btn-primary btn-xs">Insert Blocks</button>
```

I dont know why the class "hidden" appears in this and I'm not able to make it appears.

Any help would be appreciated

regards

**Comment by flotho** [comment]
I uninstall all the website module, the reinstall everything and import datas.
Everything was looking fine until I set a website setting on facebook (I have no FB account).
When a setting is not well configured, UI seems to behave weird => No more Snippets

regards

**Comment by Yajo** [comment]
This started to happen to me in 8.0 in some views. Use the HTML editor and cut everything under div#wrap. Paste it into your favorite text editor. Now save in Odoo and try to edit, your Insert Blocks should appear again.

Now keep pasting code from the text file until you find the guilty part. Recreate that part and save.

**Comment by qsm-odoo** [comment]
Hello,
Sorry we could not handle this bug when it was reported. Unfortunately, we are so late that the 8.0 version is now unsupported. If you still have a similar issue in 9.0 or higher, please do not hesitate to report it and ping me.
