### ISSUE TITLE
[V8]Website no more save the changes, navbar issue?

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#6541]
Hy,

Running on the latest Odoo, Using edit an save button don't work anymore. I tried this https://www.odoo.com/fr_FR/forum/help-1/question/insert-block-on-new-odoo-online-63507 and it works but I've lost all my datas.
I suspect that this issue  #6540 is related

Any advice too check would be appreciated

Regards

**Comment by flotho** [comment]
Additionnaly, using  the HTML editor works perfectly

**Comment by qsm-odoo** [comment]
Hello, same as #6540,
Sorry we could not handle this bug when it was reported. Unfortunately, we are so late that the 8.0 version is now unsupported. If you still have a similar issue in 9.0 or higher, please do not hesitate to report it and ping me.
