### ISSUE TITLE
[V8] Firefox says "TypeError: openerp.Tour is undefined"

### ISSUE THREAD

**Issue by l8m8** [odoo/odoo#6542]
Firefox generates this error on odoo sites. This seems to be something unique to Firefox (Chrome and Safari either don't agree or don't care) and unfortunately appears to have the effect of terminating any further javascript on the site.

Opening www.odoo.com on Firefox while viewing the console produces this error twice (in addition to a "SecurityError: The operation is insecure." error.)

![screen shot 2015-05-01 at 10 28 55 pm](https://cloud.githubusercontent.com/assets/12206513/7440046/86f7561c-f051-11e4-9264-8a6faafb3123.png)

Any ideas?

**Comment by JayVora-SerpentCS** [comment]
Possibly, this was longback while the version was not stable.
Did you check with recent source @l8m8 ?

**Comment by Yenthe666** [comment]
Hi @l8m8,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
