### ISSUE TITLE
[8.0] invoice not load defaults value from analytic defaults settings after install sale analytic plans and purchase analytic plans.

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#6543]
- this should effect all version. *

when installed sale analytic plans and purchase analytic plans, create invoice form  sale order or purchase order should never follow analytic defaults.

as we excepted was that, when create invoice, by default it should populate the default analytic distribution from analytic defaults settings.

how to to, i proposed that should rewrite `invoice_line_create`, to load the default value which calculate with analytic defaults., and add onchange logic to change the default value when changed the product that invoked with the invoice.

**Comment by invitu** [comment]
I confirm the issue
@jeffery9 your fix works

**Comment by jeffery9** [comment]
i already have signed CLA

**Comment by Yenthe666** [comment]
Hi @jeffery9,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
