### ISSUE TITLE
>13.0 Invoice line doesn't restrict linked product deletion

### ISSUE THREAD

**Issue by chienandalu** [odoo/odoo#65445]
Impacted versions: >13.0

Steps to reproduce:

- Create a new product
- Make an invoice with such product in the line
- Validate the invoice
- Delete the product

Current behavior:

- The product record gets deleted and all the `account.move.line` records lose that info.

Expected behavior:

- Up to 12.0, `product_id` field in `account.invoice.line` had an `ondelete="restrict"` to avoid such inconsitencies. With the merge with `account.move.line`, such restriction has been removed.

**Comment by pedrobaeza** [comment]
@qdp-odoo can you please take a look to this?

**Comment by Yenthe666** [comment]
Eek, good catch!

**Comment by pedrobaeza** [comment]
@william-andre any news about this?
