### ISSUE TITLE
ir.property access Error if a company dependent fields is used in domain (or searched in computed field)

### ISSUE THREAD

**Issue by levkar** [odoo/odoo#65450]
Impacted versions: 14.0

Steps to reproduce:

1) declare a company dependent field

```
class ProductTemplate(models.Model):
    _inherit = "product.template"

    expense_group_id = fields.Many2one(
        comodel_name='account.expense.group',
        string='Expense Group',
        company_dependent=True,
    )

class HrExpense(models.Model):
    _inherit = 'hr.expense'

    expense_group_id = fields.Many2one(
        comodel_name='account.expense.group',
        string='Expense Group',
    )
```

2) use it in a domain
`
<field name="product_id"> domain="[('expense_group_id', '=', expense_group_id)]"/>`

Current behavior:

You are not allowed to access 'Company Property' (ir.property) records.

This operation is allowed for the following groups:
	- Administration/Settings

Contact your administrator to request access if necessary.

Expected behavior:

This is caused by this PR: https://github.com/odoo/odoo/pull/51658

It should work.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (

**Comment by pedrobaeza** [comment]
@mart-e can you please check it?
