### ISSUE TITLE
OpenERP/Odoo Incoming Mails all marked as read

### ISSUE THREAD

**Issue by Sameer1990** [odoo/odoo#6545]
I have configure my incoming and outgoing email in OpenERp/Odoo , but all email that comes in marked as read and open on the mail server by OpenERP/Odoo and send same email to my email account with my signature .

Is there any way to prevent OpenERP/Odoo from do these things ??

Incoming amil server configuration : IMAP Server with 993 port and SSL/TLS

**Comment by ge2kaslt** [comment]
Same issue here. Is it possible to prevent it?

**Comment by Yenthe666** [comment]
Hi @Sameer1990 ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment). On a sidenote: this is the exact difference between IMAP and SMTP. 

Regards,
Yenthe
