### ISSUE TITLE
filename attribute does not work in treeviews

### ISSUE THREAD

**Issue by ecoservice-mh** [odoo/odoo#6546]
Hello,

in origin/8.0 the filename attribute does not work well in the treeview. The Problem is that the right filename is shown in the treeview but when i want to download the file, the file gets a random filename.

E.g.:

< tree>
< field name="data_fname" invisible="1"/>
< field name="data" filename="data_fname"/>
< /tree>

Regards

**Comment by flotho** [comment]
+1

**Comment by ecoservice-mh** [comment]
My Workarround:


diff --git a/addons/web/static/src/js/view_list.js b/addons/web/static/src/js/view_list.js
index ee934d6..9664a6e 100644
--- a/addons/web/static/src/js/view_list.js
+++ b/addons/web/static/src/js/view_list.js
@@ -2312,7 +2312,7 @@ instance.web.list.Binary = instance.web.list.Column.extend({
         }

         var download_url;
-        if (value.substr(0, 10).indexOf(' ') == -1) {
+        if (value.substr(0, 10).indexOf(' ') == -1 && !this.filename) {
             download_url = "data:application/octet-stream;base64," + value;
         } else {
             download_url = instance.session.url('/web/binary/saveas', {model: options.model, field: this.id, id: options.id});

**Comment by Yenthe666** [comment]
Hi @ecoservice-mh,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
