### ISSUE TITLE
Impossible to Add new field to `res_partner`

### ISSUE THREAD

**Issue by mromdhane** [odoo/odoo#65475]
Impacted versions:
13.0
Steps to reproduce:

Add new field `test` to `res_partner`
I worked on CI env
My pipeline works fine with any update and I have this issue only with res_partner model

Current behavior:

`        "2021-02-03 21:33:38,702 17849 INFO sefqinterne_prod_mromdhane_add_field_client_file_202102031630 odoo.modules.loading: 28 modules loaded in 0.87s, 0 queries ", 
        "2021-02-03 21:33:39,014 17849 INFO sefqinterne_prod_mromdhane_add_field_client_file_202102031630 odoo.modules.loading: Modules loaded. ", 
        "2021-02-03 21:33:39,023 17849 ERROR sefqinterne_prod_mromdhane_add_field_client_file_202102031630 odoo.sql_db: bad query: SELECT \"res_partner\".\"id\" as \"id\",\"res_partner\".\"name\" as \"name\",\"res_partner\".\"display_name\" as \"display_name\",\"res_partner\".\"date\" as \"date\",\"res_partner\".\"title\" as \"title\",\"res_partner\".\"parent_id\" as \"parent_id\",\"res_partner\".\"ref\" as \"ref\",\"res_partner\".\"lang\" as \"lang\",\"res_partner\".\"tz\" as \"tz\",\"res_partner\".\"vat\" as \"vat\",\"res_partner\".\"website\" as \"website\",\"res_partner\".\"comment\" as \"comment\",\"res_partner\".\"credit_limit\" as \"credit_limit\",\"res_partner\".\"active\" as \"active\",\"res_partner\".\"employee\" as \"employee\",\"res_partner\".\"function\" as \"function\",\"res_partner\".\"type\" as \"type\",\"res_partner\".\"street\" as \"street\",\"res_partner\".\"street2\" as \"street2\",\"res_partner\".\"zip\" as \"zip\",\"res_partner\".\"city\" as \"city\",\"res_partner\".\"state_id\" as \"state_id\",\"res_partner\".\"country_id\" as \"country_id\",\"res_partner\".\"partner_latitude\" as \"partner_latitude\",\"res_partner\".\"partner_longitude\" as \"partner_longitude\",\"res_partner\".\"email\" as \"email\",\"res_partner\".\"phone\" as \"phone\",\"res_partner\".\"mobile\" as \"mobile\",\"res_partner\".\"is_company\" as \"is_company\",\"res_partner\".\"industry_id\" as \"industry_id\",\"res_partner\".\"company_id\" as \"company_id\",\"res_partner\".\"color\" as \"color\",\"res_partner\".\"partner_share\" as \"partner_share\",\"res_partner\".\"commercial_partner_id\" as \"commercial_partner_id\",\"res_partner\".\"commercial_company_name\" as \"commercial_company_name\",\"res_partner\".\"company_name\" as \"company_name\",\"res_partner\".\"partner_type\" as \"partner_type\",\"res_partner\".\"message_main_attachment_id\" as \"message_main_attachment_id\",\"res_partner\".\"email_normalized\" as \"email_normalized\",\"res_partner\".\"message_bounce\" as \"message_bounce\",\"res_partner\".\"user_id\" as \"user_id\",\"res_partner\".\"signup_token\" as \"signup_token\",\"res_partner\".\"signup_type\" as \"signup_type\",\"res_partner\".\"signup_expiration\" as \"signup_expiration\",\"res_partner\".\"partner_gid\" as \"partner_gid\",\"res_partner\".\"additional_info\" as \"additional_info\",\"res_partner\".\"phone_sanitized\" as \"phone_sanitized\",\"res_partner\".\"partner_category\" as \"partner_category\",\"res_partner\".\"job_category\" as \"job_category\",\"res_partner\".\"birth_date\" as \"birth_date\",\"res_partner\".\"phone_post\" as \"phone_post\",\"res_partner\".\"firstname\" as \"firstname\",\"res_partner\".\"test\" as \"test\",\"res_partner\".\"lastname\" as \"lastname\",\"res_partner\".\"note\" as \"note\",\"res_partner\".\"organisation_id\" as \"organisation_id\",\"res_partner\".\"create_uid\" as \"create_uid\",\"res_partner\".\"create_date\" as \"create_date\",\"res_partner\".\"write_uid\" as \"write_uid\",\"res_partner\".\"write_date\" as \"write_date\" FROM \"res_partner\" WHERE \"res_partner\".id IN (2)", 
        "ERROR: column res_partner.test does not exist", 
        "LINE 1: ...ne_post\",\"res_partner\".\"firstname\" as \"firstname\",\"res_partn...", 
        "                                                             ^", 
        " ", 
        "Traceback (most recent call last):", 
        "  File \"/opt/odoodev/git/odoo/odoo/tools/cache.py\", line 85, in lookup", 
        "    r = d[key]", 
        "  File \"/opt/odoodev/git/odoo/odoo/tools/func.py\", line 69, in wrapper", 
        "    return func(self, *args, **kwargs)", 
        "  File \"/opt/odoodev/git/odoo/odoo/tools/lru.py\", line 44, in __getitem__", 
        "    a = self.d[obj].me", 
        "KeyError: ('res.users', <function Users.context_get at 0x7f7d3b8dc048>, 1)", 
        "", 
        "During handling of the above exception, another exception occurred:", 
        "", 
        "Traceback (most recent call last):", 
        "  File \"/opt/odoodev/git/odoo/odoo/api.py\", line 745, in get", 
        "    value = self._data[field][record._ids[0]]", 
        "KeyError: 1", 
        "", 
        "During handling of the above exception, another exception occurred:", 
        "", 
        "Traceback (most recent call last):", 
        "  File \"/opt/odoodev/git/odoo/odoo/fields.py\", line 1035, in __get__", 
        "    value = env.cache.get(record, self)", 
        "  File \"/opt/odoodev/git/odoo/odoo/api.py\", line 751, in get", 
        "    raise CacheMiss(record, field)", 
        "odoo.exceptions.CacheMiss: ('res.users(1,).lang', None)", 
        "", 
        "During handling of the above exception, another exception occurred:", 
        "", 
        "Traceback (most recent call last):", 
        "  File \"/opt/odoodev/git/odoo/odoo/api.py\", line 745, in get", 
        "    value = self._data[field][record._ids[0]]", 
        "KeyError: 2", 
        "", 
        "During handling of the above exception, another exception occurred:", 
        "", 
        "Traceback (most recent call last):", 
        "  File \"/opt/odoodev/git/odoo/odoo/fields.py\", line 1035, in __get__", 
        "    value = env.cache.get(record, self)", 
        "  File \"/opt/odoodev/git/odoo/odoo/api.py\", line 751, in get", 
        "    raise CacheMiss(record, field)", 
        "odoo.exceptions.CacheMiss: ('res.partner(2,).lang', None)", 
        "", 
        "During handling of the above exception, another exception occurred:", 
        "", 
        "Traceback (most recent call last):", 
        "  File \"./upgrade_odoo\", line 100, in <module>", 
        "    sys.exit(anybox.recipe.odoo.runtime.upgrade.upgrade('/opt/odoodev/git/sfl/tools/upgrade.py', 'run', '/opt/odoodev/git/sfl/tools/etc/dev.cfg', '/opt/odoodev/git/sfl/tools'))", 
        "  File \"/opt/odoodev/git/sfl/tools/src/anybox.recipe.odoo/anybox/recipe/odoo/runtime/upgrade.py\", line 118, in upgrade", 
        "    session.open(db=db_name, with_demo=bool(arguments.init_load_demo_data))", 
        "  File \"/opt/odoodev/git/sfl/tools/src/anybox.recipe.odoo/anybox/recipe/odoo/runtime/session.py\", line 198, in open", 
        "    self.context = self.env['res.users'].context_get()", 
        "  File \"<decorator-gen-84>\", line 2, in context_get", 
        "  File \"/opt/odoodev/git/odoo/odoo/tools/cache.py\", line 90, in lookup", 
        "    value = d[key] = self.method(*args, **kwargs)", 
        "  File \"/opt/odoodev/git/odoo/odoo/addons/base/models/res_users.py\", line 581, in context_get", 
        "    values = user.read(list(name_to_key), load=False)[0]", 
        "  File \"/opt/odoodev/git/odoo/odoo/addons/base/models/res_users.py\", line 1298, in read", 
        "    res = super(UsersView, self).read(other_fields, load=load)", 
        "  File \"/opt/odoodev/git/odoo/odoo/addons/base/models/res_users.py\", line 454, in read", 
        "    return super(Users, self).read(fields=fields, load=load)", 
        "  File \"/opt/odoodev/git/odoo/odoo/models.py\", line 2965, in read", 
        "    vals[name] = convert(record[name], record, use_name_get)", 
        "  File \"/opt/odoodev/git/odoo/odoo/models.py\", line 5731, in __getitem__", 
        "    return self._fields[key].__get__(self, type(self))", 
        "  File \"/opt/odoodev/git/odoo/odoo/fields.py\", line 1059, in __get__", 
        "    self.compute_value(recs)", 
        "  File \"/opt/odoodev/git/odoo/odoo/fields.py\", line 1144, in compute_value", 
        "    records._compute_field_value(self)", 
        "  File \"/opt/odoodev/git/odoo/odoo/models.py\", line 4005, in _compute_field_value", 
        "    field.compute(self)", 
        "  File \"/opt/odoodev/git/odoo/odoo/fields.py\", line 579, in _compute_related", 
        "    record[self.name] = self._process_related(value[self.related_field.name])", 
        "  File \"/opt/odoodev/git/odoo/odoo/models.py\", line 5731, in __getitem__", 
        "    return self._fields[key].__get__(self, type(self))", 
        "  File \"/opt/odoodev/git/odoo/odoo/fields.py\", line 1042, in __get__", 
        "    recs._fetch_field(self)", 
        "  File \"/opt/odoodev/git/odoo/odoo/models.py\", line 2994, in _fetch_field", 
        "    self._read(fnames)", 
        "  File \"/opt/odoodev/git/odoo/odoo/models.py\", line 3066, in _read", 
        "    cr.execute(query_str, params)", 
        "  File \"/opt/odoodev/git/odoo/odoo/sql_db.py\", line 173, in wrapper", 
        "    return f(self, *args, **kwargs)", 
        "  File \"/opt/odoodev/git/odoo/odoo/sql_db.py\", line 250, in execute", 
        "    res = self._obj.execute(query, params)", 
        "psycopg2.ProgrammingError: column res_partner.test does not exist", 
        "LINE 1: ...ne_post\",\"res_partner\".\"firstname\" as \"firstname\",\"res_partn...", 
        "                                                             ^", 
        "", 
        "2021-02-03 21:33:39,117 17849 WARNING sefqinterne_prod_mromdhane_add_field_client_file_202102031630 odoo.sql_db: Cursor not closed explicitly", 
        "Please enable sql debugging to trace the caller. "`

**Comment by rb3606** [comment]
@mromdhane how you added field? whenever we add field in company, users and partner odoo module require to upgrade immediately. because it will not allow you to navigate any screen. So if you added field restarted server but not upgrade module then it will give same error. so try to upgrade module from console.

**Comment by mromdhane** [comment]
@rb3606 I added a field on my custom module. I can't upgrade like this, because I am working on CI env; I start a build by Jenkins (get the production DB and loads and upgrade the modules). I have this error only with res_partner.
 I get this error only with Odoo 13!, the same pipline works fine with Odoo 11

**Comment by Yenthe666** [comment]
That's normal behaviour. You have to trigger an update from the module.
@pedrobaeza has more knowledge/experience with CI's so maybe he knows more.

**Comment by pedrobaeza** [comment]
Yes, it's something of your CI pipeline, that is not working according what is expected. Check how is done on Odoo and OCA.

Closing as no Odoo issue.

**Comment by rb3606** [comment]
Yes its your configuration issue not Odoo issue.

**Comment by mromdhane** [comment]
@pedrobaeza I have this issue only with `res_partner`, my pipeline works fine with other models.

**Comment by pedrobaeza** [comment]
Yeah, that model has several special things (like its inheritance with `res.users`). You should test on install mode and splitting the base addons installation from the tested ones.

**Comment by nilshamerlinck** [comment]
Hi @mromdhane your case is similar to https://github.com/odoo/odoo/issues/26757

According to the logs, your pipeline relies on [`anybox.recipe.odoo`](https://github.com/anybox/anybox.recipe.odoo) which has been [fixed to address this issue](https://github.com/anybox/anybox.recipe.odoo/commit/b32bd15905ba18f5a2cfd79ba896bb46daf501eb).

Upgrading it should help :)

**Comment by matteoopenf** [comment]
I have the same problem on odoo 14 in odoo.sh and I can't do the -u all because the status of the container has been reset and I have the old code

is not possibile take this https://github.com/anybox/anybox.recipe.odoo/commit/b32bd15905ba18f5a2cfd79ba896bb46daf501eb on odoo master?

**Comment by hilarak** [comment]
still, there is no workaround to handle this scenario. The only way is to handle it with the command line? The same issues appear if we add any new fields in partner/employee.

**Comment by matteoopenf** [comment]
in my cases the problem is I add other selection in a fields in a wrong way

**Comment by burkeallen** [comment]
old question/issue but this is the best way i have found to deal with this issue, which still exists in Odoo 16.

this is an old question but still a relevant issue with Odoo.



these 2 blog articles explains in detail how to accomplish this. so kudos to the blog owners for providing it, 

https://www.excelroot.com/post/error-upgrading-after-adding-new-field-to-res-users-and-res-company
https://mellowhost.com/blog/how-to-add-fields-to-res-users-or-res-partners-model-in-odoo.html

**Comment by fcoca-datec** [comment]
Any solution to this? I'm very dissapointed, this issue exists since v10 and there is no a real solution from Odoo. 

Odoo 17 ignores the update all and breaks the system, so no, there is no solution yet.

![Image](https://github.com/user-attachments/assets/5f8d270e-a093-4e48-9955-64261359c235)

**Comment by fractalf** [comment]
If someone needs to do this in a docker container this is what I do

```sh
$ python3 /usr/bin/odoo -u <module name> -d ff --http-port=9090 --gevent-port=9091 --stop-after-init
```

...you don't need to close the other service down, just update the db
