### ISSUE TITLE
Odoo v8  not working fine :Register payement?

### ISSUE THREAD

**Issue by m3asmi** [odoo/odoo#6550]
follow the instruction in a new databes as the steps

```
install new database with account_vocher module

select Maroc/Morocco accounting package l10n_ma

create new invoice

register payement for the invoice

check if the payement are listed on the payements tab
```

I make the payement but the balance stel the same and there is no payement lines in the payements tab!!

http://i.stack.imgur.com/Ei6W7.png
http://i.stack.imgur.com/3gNwi.png
http://i.stack.imgur.com/gTUlF.png
http://i.stack.imgur.com/u1Sdk.png

**Comment by Imoujib** [comment]
Make sure that you've checked the Allow reconciliation box in the customer account and the default journal credit and debit accounts.

**Comment by Yenthe666** [comment]
Indeed - this was answered!
