### ISSUE TITLE
[V8] Reverse proxy 'sign out' is not using web.base.url

### ISSUE THREAD

**Issue by SamVerschueren** [odoo/odoo#6551]
Hi everyone

Today I installed Odoo on our servers and I am configuring everything right now. Odoo is running on the default port 8069 and I am using Nginx to forward all the requests from port 80 to 8069. This implies that all the mail URLs start of with http://localhost:8069, rather then the domain you want. This was solved by editing the `web.base.url` and setting `web.base.url.freeze` to `true`.

So far so good. The problem is, when I press the Sign out button, it redirects me to http://localhost:8069 instead of `web.base.url`.

I also added Google as OAuth provider and when I try to authenticate, it uses http://localhost:8069 as redirect_uri instead of `web.base.url`. Should I set something else as well or is this really a bug?

Thanks in advance

**Comment by SamVerschueren** [comment]
The reason for why the Google OAuth provider is not working correctly can be found in this issue https://github.com/odoo/odoo/issues/6556

I dived deeper into why the redirect after the logout is not correct. At line [859](https://github.com/odoo/odoo/blob/8.0/addons/web/controllers/main.py#L859) of the file [addons/web/controllers/main.py](https://github.com/odoo/odoo/blob/8.0/addons/web/controllers/main.py), the user gets redirected by `werkzeug.utils` after a logout. Because werkzeug is running on the localhost, and on port 8069, it will redirect me to http://localhost:8069/web, which is not what I want offcourse.

So as a quick and dirty fix, I changed that line to the following 
```
werkzeug.utils.redirect('https://my-domain.com' + redirect, 303)
```

And this works as expected. So ideally, that line should be changed so it uses the `web.base.url` property instead.

**Comment by ravishekharco** [comment]
I am using %h parameter when running the server such that database is selected based on the domain used to access the server. So, I can not implement the solution which SamVerschueren has suggested. Is there any other workaround to the issue? Can we not modify the controller to use web.base.url while logging out?

**Comment by ravishekharco** [comment]
Found a fix by overriding the "logout" method : 

###############
    def logout(self, redirect='/web'):
        from openerp import http, SUPERUSER_ID
        ir_config_id=request.registry['ir.config_parameter'].search(request.cr,SUPERUSER_ID,[('key','=','web.base.url')])
        base_url=request.registry['ir.config_parameter'].browse(request.cr,SUPERUSER_ID,ir_config_id[0],request.context).value
        request.session.logout(keep_db=True)
        return werkzeug.utils.redirect(base_url, 303)
#########

**Comment by charyorde** [comment]
@ravishekharco Cool hack.

**Comment by mrshelly** [comment]
@ravishekharco :+1:

**Comment by Yenthe666** [comment]
Hi @SamVerschueren,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by acpmasquerade** [comment]
still there in 11 when used with nginx as reverse proxy
