### ISSUE TITLE
V8 - Repair Order - Stock moves source

### ISSUE THREAD

**Issue by juli1r** [odoo/odoo#6552]
Hello all,

we have found a strange behavior with the repair order and the related stock moves.

If the stock moves come from a repair order, there is no data in the source field.

See picture attached for more details.

This behavior have been spotted on runbot so it's an original source code issue.

Take to care to this until Odoo have done the correction.
![repairorderstockmoves](https://cloud.githubusercontent.com/assets/8482862/7460982/01604484-f275-11e4-9315-9a6997fef729.jpg)
![repairorderstockmoves2](https://cloud.githubusercontent.com/assets/8482862/7460983/01609b96-f275-11e4-82b6-33615810919e.jpg)

Regards.

**Comment by Yenthe666** [comment]
Hi @juli1r,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
