### ISSUE TITLE
Date validation does not account for localization

### ISSUE THREAD

**Issue by kenneaal** [odoo/odoo#6562]
Greetings.

The validators being applied to date fields, such as the fiscal periods, do not account for localized abbreviated month names.

Switching the user language to English works as a workaround for the problem.

This problem is most visible in sales orders and financial periods, where the validation prevents creating periods on the months of May, October and December (Abbreviated Mai, Okt, Des in Norwegian, while English abbreviations are May, Oct, Dec), or making sales orders for those months.

**Comment by Yenthe666** [comment]
Hi @kenneaal,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
