### ISSUE TITLE
[V8] domain does not apply on subview

### ISSUE THREAD

**Issue by houssine78** [odoo/odoo#6569]
Hi,

I think that domain does not apply as expected on subview. You can take the example the module stock_picking_wave where a domain on the field picking_ids of the stock.picking.wave model

https://github.com/odoo/odoo/blob/8.0/addons/stock_picking_wave/stock_picking_wave_view.xml#L27
according the domain defined the subtree should not display the picking with state done or cancel
<field name="picking_ids" widget="many2many" domain="[('state', 'not in', ('done', 'cancel'))]">

state is defined in the subtree view so can't get why it does not work... to reproduce install a new fresh database with demo data and install stock and stock_picking_wave modules. then go in picking wave choose one of the two listed and cancel the picking... it should normally not appear anymore as far as I understood... but it still displayed...

Thanks

**Comment by Yenthe666** [comment]
Hi @houssine78,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
