### ISSUE TITLE
[8.0] Admin user destroyed when using the on-line-proposal module

### ISSUE THREAD

**Issue by anderswallenquist** [odoo/odoo#6570]
I got admin user destroyed when I use the on-line proposal module.

This is the steps I do:

1) create an empty database
2) install on-line proposal (and sale etc)
3) create a new qutation template with some new products
4) create a new qutoation with a customer and my new qutoation-template, send the quotation to the customer
5) The customer does a auth-signup using the link in the mail
6) The admin user are now destroyed. (overwritten by the user for the customer)

I suspect the auth_signup-module but I havent found the faulty code yet.

Any ideas?

**Comment by Yenthe666** [comment]
Hi @anderswallenquist ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
