### ISSUE TITLE
[14.0] ValidationError when creating bank.statement.line with two numbers + letter in name 

### ISSUE THREAD

**Issue by NMisko** [odoo/odoo#65703]
**Impacted versions:**
14

**Steps to reproduce:**
```
statement = self.env['account.bank.statement'].search([], limit=1)
journal = self.env['account.journal'].search([], limit=1)
self.env["account.bank.statement.line"].create({'name': '38g', 'partner_id': None, 'amount': 33.99, 'journal_id': journal.id, 'statement_id': statement.id, 'move_type': 'entry', 'payment_ref': 'x', 'currency_id': 1})
```
**Current behavior:**
```
ValidationError: The Date (02/08/2021) doesn't match the Number (38g).
You might want to clear the field Number before proceeding with the change of the date.
```

It works if `name` is:
* `38`
* `abcdefgh`
* `3g`
* `g38`

**Expected behavior:**
Any name should be usable in a bank statement line, without raising an error.

**Additional Notes**
The ValidationError comes from the related `account.move.line` which gets created along side the bank statement line and it being a `sequence.mixin`. Two numbers + letter in the name get somehow parsed as a date, though I don't really understand what's going on there. I was not able to replicate this via frontend.

**Comment by ppapadeas** [comment]
I have a similar error here from importing bank statements via CSV
![Screenshot from 2021-02-25 18-43-26](https://user-images.githubusercontent.com/498592/109186294-73b6e600-7799-11eb-95d8-2b9082c06880.png)

**Comment by Yenthe666** [comment]
@ppapadeas hmm I've seen it happen a few times on V14 builds too but was never able to really find a good reproducable flow. Interesting enough at some days it will not work and at some it will.

**Comment by krijn1981** [comment]
We facing the same issue with Bank statements and Miscellaneous entries.
It seems when the posting is done in the same month of the server (so you posting having a date of April and the server also having April time, then it will be no issue).

But 2 things:
1) as financial I want and need to determine myself the sequence of my journal entries (by journal of course) setting them up in certain way can be criterial in multiple company envoriments for controlling purpose. Most companies do not want to have a month period in there sequences.
2) as financial manager you ALWAYS make corrections in a different period.

**Comment by william-andre** [comment]
As a brief explanation, this is because [`sequence.mixin`](https://github.com/odoo/odoo/blob/14.0/addons/account/models/sequence_mixin.py) will try to match your sequence to a pattern.

`38` would be evaluated as a sequence.
`38g` would be evaluated as a year (`38` or `2038`), followed by a separator (`g`), with a missing sequence, which would start at `1` for the next number.

However, this constraint has been removed since for `account.bank.statement` https://github.com/odoo/odoo/commit/6f260124a01879ce39933b2671c002cf1b7d13e7
