### ISSUE TITLE
Followers should not be added automatically

### ISSUE THREAD

**Issue by pvanthony** [odoo/odoo#6573]
Partners are automatically added as followers in opportunity. 
We can remove the partner manually but if the partner replies to an email, the partner is automatically added as a follower. This is a problem.

This problem is the same as the following in openerp v7.
https://bugs.launchpad.net/openobject-addons/+bug/1237470

**Comment by aftabnaveed** [comment]
+1 it is very annoying customers get automated random emails when they are added as followers. Some actions like Order Confirmation will add it regardless and send an unwanted email to customer.

**Comment by innovo3d** [comment]
+1 Using V9 community.  This also happens in quotes.  Even if I remove the partner, if I make any updates to the quote it will automatically add them again.  This has caused us already several situations where the client received email notifications that were not meant for them to see.  Very annoying.

**Comment by nhomar** [comment]
You can configure the removal with a server action, it is a 30 minutes work. Isn't this work for you?

I have more request of "add the partner as follower" than remove them.

IOH: If you use the new approach of send a message pointing explicitally to an internal user the message will not go to the partner by default (using @username in the message).

I hope it helps.

**Comment by bistaray** [comment]
I'd like to know more about "the 30 minute server action".  It should be possible to remove followers if they are not matched to res.users right?  So only add 'users' and not 'customers' and 'vendors'?

**Comment by bistaray** [comment]
![image](https://cloud.githubusercontent.com/assets/13910162/25885051/1b25a294-350b-11e7-9676-8170ee9860cc.png)


![image](https://cloud.githubusercontent.com/assets/13910162/25885061/27db3116-350b-11e7-8932-f63cc270873c.png)


![image](https://cloud.githubusercontent.com/assets/13910162/25885070/34706fd6-350b-11e7-8199-9f9fbca32741.png)


(10 minutes!!)  -  will test this method.

**Comment by Yenthe666** [comment]
Hi @pvanthony ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by rafaelbn** [comment]
About this issue I'm not agree. This is you personal PoV, for me is absolutely necessary that customer get automatically added as followers.

An Opportunity is for getting in contact with the customer! a not to not contact. In fact for you use case you have Internal notes.

**Comment by pedrobaeza** [comment]
I think the same, so this is not a valid issue although closed by triaging.
