### ISSUE TITLE
[14.0] web, *: word "null" replaced in every search domain from JS

### ISSUE THREAD

**Issue by vedler** [odoo/odoo#65743]
**Impacted versions:** 14.0, 13.0

**Steps to reproduce:** Use the word "null" in any search bar.

**Current behavior:** 'null' replaced in all domains from JS

**Expected behavior:** 'null' literals should perhaps be replaced in some other way, because some languages actually use that word.

**Video/Screenshot link (optional):**
Screens from Odoo master demo.

![image](https://user-images.githubusercontent.com/22161082/107245433-d25d2f80-6a37-11eb-81c3-198d7c604d1c.png)
![image](https://user-images.githubusercontent.com/22161082/107245490-e143e200-6a37-11eb-9575-c9ae2154ba0e.png)

Code: [addons/web/static/src/js/core/domain.js](https://github.com/odoo/odoo/commit/5804ed100ec790a36c5ff30a217914950cd78098#diff-62caa7ad6605a60e0eff056f8c45ac3cf1796f961a0c3ee12cdeaccbe6cdb25aR208)

I just spent half an hour figuring out where I made a typo of naming a field "Noneifying_test_id" only to realize every single occurrence of "null" in a domain is replaced with "None". And it's not only in the left element of a domain leaf, but the right as well. So many languages, including my own, use the word "null" in everyday use (for example it means 'zero' in Estonia, not to mention the various forms of "nullify" in a lot of languages (annulleerima, annullata, e annullo etc). This effectively means that any legitimate occurrence of "null" in a word makes it such that the normal search bar, any domain based searches with user-defined filters or even advanced filters will erroneously translate this partial string to None.

I think I physically smacked myself in the head during testing this, when I made a favourite filter under whatever table, named it "Test nulls", then went under User-defined filters and tried to search for it...

**Comment by pedrobaeza** [comment]
This has reminded me Bobby Tables: https://bobby-tables.com/img/xkcd.png

@ged-odoo @aab-odoo can you take a look?

**Comment by ged-odoo** [comment]
ouch...

**Comment by Yenthe666** [comment]
Well, this is going to be fun @ged-odoo 😉

**Comment by Yenthe666** [comment]
Now that was faster as expected. Kudos to the JS team!
