### ISSUE TITLE
[8.0] Bug when validate invoice

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#6575]
Hello Odoo Support,

At 2015-05-04, I have update the Odoo to the newest.
But after that I found a bug, there’s an user that just have account access right and she cannot validate the invoice.

So here is the sequence to produce the bug:
1.  Have an user to just have access on accounting only. (the access right is accountant)
2.  Create a purchase order, with invoice mehod based on generated draft invoice.
3.  After you confirmed the purchase order, the system will automatically generate the invoice.
4.  Login with the user with just accounting access right, and validate the invoice.
5.  It will have an error message: No value found for purchase.order(38,).invoice_method
6.  I think the bug happen too when we don’t have access in picking too.
7.  The expected behavior must be the accountant can able to validate the invoice whether she doesn’t have access on purchase or picking.

You can test it on runbot, I tested it on runbot and I got the same behavior.

Video to explain things:
https://falinwa-my.sharepoint.cn/personal/falinwa1_falinwa_partner_onmschina_cn/_layouts/15/guestaccess.aspx?guestaccesstoken=9AFwSaxgYM0OC%2bu8Qnk9dIYIWapZ72OKSo3Osf9G0Qs%3d&docid=075dc6dfac8ee45f4b33f73efb54b1f9d

**Comment by Yenthe666** [comment]
Hi @falinwa ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
