### ISSUE TITLE
[8.0] Rounding problems with hr_expense module

### ISSUE THREAD

**Issue by Julien-Blanc** [odoo/odoo#6576]
Configuration is the following :
- product prices are rounded to 3 digits
- account price (total) is rounded to 2 digits

This is typically needed because of kilometric prices, which in France are specified as 3 digits values, but total is rounded to 2 digits.

Problem: when entering a new expense, product prices are systematically rounded to 2 digit, which is wrong. This is done server side.

After some investigation, rounding seems to be done here :
hr_expense.py, line 473 :

```
product = self.pool.get('product.product').browse(cr, uid, product_id, context=context)
```

switching to :

```
product = self.pool.get('product.product').browse(cr, uid, product_id, context=None)
```

gives correct result (price not rounded), but is probably a very wrong fix. I don’t have the knowledge of odoo internals to provide a correct fix (or is it just a configuration issue ?).

**Comment by Yenthe666** [comment]
Hi @Julien-Blanc ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
