### ISSUE TITLE
Unable to change avatar picture in forum profile

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#6577]
**Profile picture can not be changed on forums/online**

Impacted versions:

 - 8.0

Steps to reproduce:

 1. Go to help.odoo.com
 2. Login as a user
 3. Click on your profile and then click on 'Edit Your Bio'.
 4. You will see a screen where you can edit your whole profile. You can not change the image in any way though. <img src="http://i.imgur.com/rptiD6B.png" alt="Unable to edit"/>
In the past you could also edit your profile picture from odoo.com by logging in and clicking on 'My Account', but this option is also gone. <a href="https://www.odoo.com/nl_NL/forum/help-1/question/how-can-i-upload-a-photo-to-my-profile-in-this-forum-71630#answer-71632">You can see the old way here</a>

Current behavior:

 - No option to change your profile picture

Expected behavior:

 - Ability to update / delete your profile picture

**Comment by Yenthe666** [comment]
@odony could this be changed with your implementations to combat spam etc? or is it from something else?

**Comment by odony** [comment]
This is a temporary quirk while we adapt our website menu to the front-end portal pages of saas-6 (Portal access to orders and invoices used to be in the back-end)
We've added a temporary menu "Old Portal" that will give you access to the backend and the "Preferences" menu where you can change the avatar. You can also simply navigate manually to `https://www.odoo.com/web` after logging in.  /cc @julienlegros

**Comment by Yenthe666** [comment]
Thanks for the response & link to the old portal @odony!

**Comment by houssine78** [comment]
Hi,

As far as I can see this is not yet fixed. Not able to change the avatar through the edit profile of the forum. Does the temporary quirk became permanent?

**Comment by Gokulakannanaj** [comment]
Hi @odony and @Yenthe666 ,

Getting following error while navigating.

Sorry, you are not allowed to access this document. Only users with the following access level are currently allowed to do that:
- CN Projects Custom
- LATAM CRM/Tickets Custom
- Administration/Settings
- User types/Internal User

(Document model: ir.ui.menu)

**Comment by odony** [comment]
@Gokulakannanaj somehow you've been redirected to odoo.com/web in error.  You can simply go back to the homepage or https://www.odoo.com/my to find your way back.

**Comment by Gokulakannanaj** [comment]
@odony There is no option to change profile picture in that page. It shows only Address info not profile picture and Karma info.

**Comment by thayifkabir** [comment]
Hi,
Unable to change profile picture in odoo forum. Is there any way to change it.
