### ISSUE TITLE
Unable to see 'Highscores' on forums anymore

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#6578]
**Highscore list only shows first 30 records**

Impacted versions:

 - 8.0 and above

Steps to reproduce:

 1. Go to https://www.odoo.com/nl_NL/forum/help-1/users
 2. Scroll down > there is no option to scroll through other pages

Current behavior:

 - Only top 30 people are showed on the highscores. 

Expected behavior:

 - In the past you could browse through pages which showed the next 30 people, so you could browse anybody. Ability to have a next button.

**Comment by Yenthe666** [comment]
@odony I think this is introduced/implemented when you've added extra anti-spam features and changed things around? Not sure though.

**Comment by mart-e** [comment]
It works fine on the runbot 8.0 so it's most likely some view customisations or current anti-spam features we are testing.

I will check if it's expected to hide for public user (probably) but do not reports on github bugs present only on odoo.com as it's our instance with some changes in views or other customisations (moreover currently running saas-6 and not 8.0).
Regards

**Comment by odony** [comment]
Actually it's a good point, thank you @Yenthe666. There was a bug in saas-6 that prevents seeing the page in the list of users, and it was visible on Odoo Help. It's fixed by bd8617ffd92ad91f478e2066a04b2a934cd9a056.

**Comment by mart-e** [comment]
Oh my bad, I saw it was not possible to reproduce on standard but didn't thought about saas-6 only bugs.

**Comment by Yenthe666** [comment]
Thanks for fixing it @odony! :+1: 
@mart-e that can happen, its fixed now! :) I believe this can be closed now, since its fixed.
