### ISSUE TITLE
[14.0] delivery/test_00_delivery_cost.py failure if l18n_fr installed before.

### ISSUE THREAD

**Issue by pascalmimiague** [odoo/odoo#65810]
Impacted versions: 14.0

Steps to reproduce: 
1- install i18n_fr
2- run delivery/test_00_delivery_cost.py

Current behavior:
 Assert Error :  self.assertEqual(float_compare(line.price_subtotal, 10.0, precision_digits=2), 0,
            "Delivery cost is not correspond."), line.price_subtotal = 12.38 € != 10.0 USD
Expected behavior:
          compare value with the same currency
Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
Sorry, but this doesn't applied as an issue, as the tests are required to be executed in a determined way (on install mode) and, they are not re-entrant.

Closing thus.
