### ISSUE TITLE
XMLRPC calls target method twice for no apparent reason

### ISSUE THREAD

**Issue by fhossfel** [odoo/odoo#65876]
Impacted versions: 12.0

Steps to reproduce: Can't be reproduced systematically

Current behavior: We do have an XMLRPC call to create a stock.picking though a custom method. The signature is like this:

    @api.model
    def custom_create_stock_picking(self, vals):

During processing we are placing some key (e.g. "location")  with there technical key ("location_id") before creating a new stock.picking. So basically the flow is like this:

    location = vals.pop("location")
    res_model, location_id = res_model, res_id = self.env['ir.model.data'].get_object_reference("my_ooo", location)
    vals["location_id"] = location_id.id

    self.create(vals)
  
We were seeing KeyErrors in the line with the vals.pop("location") -despite the fact that we have included this value in the XMLRPC. The error can't be reproduced systematically. It happens in 20-30% of the cases.

In order to trace the error down we have added two lines at the very beginning of the method:

    vals_orig = ("%s" % vals)
    vals['time_first_seen'] = time.time()

In case of an error we would include vals in vals_orig in the log message. We expected that vals_orig would always have a "location" and never have a "time_first_seen". However, to our surprise we saw that vals_orig was already at the beginning of the method without "location" and with a "time_frist_seen". In these cases the "time_first_seen" in vals and val_orig where 1.5s apart.

So the only reasonable explanation we came up with is: The method is called twice. But this second call is definitely not coming from our code. We have not overriden the create method but included a prefix to identify our custom method, e.g. "custom_create_stock_picking". We can definitely say this code is only defined in one single place and is never called from the python code anywhere. We have also excluded old/stale deployments. This must be a bug in the way the XMLRPC call is processed in Odoo. For some reason the method is called twice per stack call. However, this second call is not visible in the stack trace:

    File "/opt/bitnami/odoo/odoo/addons/base/controllers/rpc.py", line 63, in xmlrpc_2
       response = self._xmlrpc(service)
     File "/opt/bitnami/odoo/odoo/addons/base/controllers/rpc.py", line 43, in _xmlrpc
       result = dispatch_rpc(service, method, params)
     File "/opt/bitnami/odoo/odoo/http.py", line 120, in dispatch_rpc
       result = dispatch(method, params)
     File "/opt/bitnami/odoo/odoo/service/model.py", line 39, in dispatch
       res = fn(db, uid, *params)
     File "/opt/bitnami/odoo/odoo/service/model.py", line 171, in execute_kw
       return execute(db, uid, obj, method, *args, **kw or {})
     File "/opt/bitnami/odoo/odoo/service/model.py", line 97, in wrapper
       return f(dbname, *args, **kwargs)
     File "/opt/bitnami/odoo/odoo/service/model.py", line 178, in execute
       res = execute_cr(cr, uid, obj, method, *args, **kw)
     File "/opt/bitnami/odoo/odoo/service/model.py", line 167, in execute_cr
       return odoo.api.call_kw(recs, method, args, kw)
     File "/opt/bitnami/odoo/odoo/api.py", line 745, in call_kw
       return _call_kw_model(method, model, args, kwargs)
     File "/opt/bitnami/odoo/odoo/api.py", line 718, in _call_kw_model
       result = method(recs, *args, **kwargs)
     File "/bitnami/odoo/addons/my_module/models/stock_picking.py", line 52, in custom_create_stock_picking
     
The error can not be in the calling system because the value of "time_first_seen" is never handed out to any other system. This must occur in Odoo itself.

Expected behavior: An XMLRPC should only call the method once.

**Comment by xmo-odoo** [comment]
You may want to take a look at the server logs: one of the standard low-level behaviours of Odoo is that it will automatically retry *the entire request / RPC call* in case of Postgres triggering some specific errors (serialization and deadlocks, basically concurrency issues). In this case the error is logged, and a retry is attempted after a short sleep. This can occur up to 5 times in a row.

This applies to basically all remote calls, whether XMLRPC, JSON-RPC or regular HTTP accesses.

You can see the code in question at https://github.com/odoo/odoo/blob/c9e29e5917d1bd1b9ef584b0e013deaca03ee8d8/odoo/service/model.py#L95-L105
