### ISSUE TITLE
[12] are you going to implement an option that does not change how I store my phone number

### ISSUE THREAD

**Issue by f1-outsourcing** [odoo/odoo#65913]
I wondered if you are going to implement some setting, that prevents odoo from changing how I store my phone numbers? So if I store +1 123 123 123 or 1 123 123 123  it stores  1 123 123 123 (at most the plus is cut of, but never the international dialing code)

**Comment by pedrobaeza** [comment]
Don't install phone_validation of you don't want such formatting.

Closing as no issue.

**Comment by f1-outsourcing** [comment]
Oh yes sorry forgot that the external module had a dependency on it, sorry. Do you know of an alternative to this OCA/connector-telephony these people akretion.com are not really into maintaining it, and it is really buggy when used in a multi company environment.

Maybe such vital part of crm functionality should be a default module in odoo instead of 'maintained' by a third party.

**Comment by Yenthe666** [comment]
Lol. No offense but I've seen you hating on Odoo and OCA by now. Either if you think you can do better you do it yourself or you contribute to the eco-systems to improve it ;-)

**Comment by f1-outsourcing** [comment]
Hating, hating, is a bit overstated, and there are indeed things I would differently. I was already having something in the back of my mind that if I get my funding, I will put the development team in their spare time on such application. 
I am not sure if and how, but I would try to separate more the coding from the frontend, have good people make a good backend. And because there so many people that have so many different interests. They all can build a different frontends on this rock solid backend. And instead of what you advice build it yourself, I would ask existing projects to join forces. So you have one really good project with a large market share.
For me odoo is just a tool and unfortunately it annoys me sometimes when I use it. I am not going to contribute, my passions are in a different area.
