### ISSUE TITLE
Sales can't install in odoo14

### ISSUE THREAD

**Issue by yinmazatin** [odoo/odoo#65914]
Impacted versions: 14.0

Steps to reproduce:
1. Create the database
2. click on install App "Sale"
Current behavior:
Can't install App "Sales"
Expected behavior:
Can install App "Sales" 
Video/Screenshot link (optional):
![12](https://user-images.githubusercontent.com/30262465/107596515-8c2bea00-6c4a-11eb-8353-f7e329a705d5.PNG)

Impacted File :  sale_management_security.xml
Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/14.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).
