### ISSUE TITLE
V8 - Repair Order - Stock moves status

### ISSUE THREAD

**Issue by juli1r** [odoo/odoo#6591]
Hello everyone,

we have found a strange behavior with the repair order and the related stock moves.

When a repair order is completed ("repaired"), the system generate two stock moves: one for the product to repair and another one for the product we add or delete during the repair.

The stock move for the product to repair is complete automatically by the system but the one for the product we add or delete during the repair, the stock move stay at "available".

The stock move for the product we add or delete during the repair process must have his related stock move set automatically by the system to done since the repair order is completed.

See the pictures below.

Thanks for the quick fix.

Regards.

![repairorder1](https://cloud.githubusercontent.com/assets/8482862/7500577/78dc9926-f3fc-11e4-8696-87e9f6eb9fe6.png)
![repairorder2](https://cloud.githubusercontent.com/assets/8482862/7500579/78e0049e-f3fc-11e4-8eab-1d5b6753c4a1.png)
![repairorder3](https://cloud.githubusercontent.com/assets/8482862/7500578/78dfa54e-f3fc-11e4-820b-bc9f3f6494a2.png)

**Comment by Yenthe666** [comment]
Hi @juli1r,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
