### ISSUE TITLE
[12] right click copy email address not available in this view

### ISSUE THREAD

**Issue by f1-outsourcing** [odoo/odoo#65912]
right click copy email address not available in this view. 
![test](https://user-images.githubusercontent.com/13450219/107577936-5c9dc300-6bf3-11eb-8eec-519e4bf39448.png)

**Comment by pedrobaeza** [comment]
Not sure what do you mean.

**Comment by f1-outsourcing** [comment]
You always end up clicking the contact in this case 'Administrator' and going to the contact page, and then you can right click and copy the email address. That can be annoying if you have to get a few email addresses. Say if I need 3 addresses. Implementing this change, I would have these addresses with 3 clicks. Now I have to try and select the email address and if it goes wrong it opens the contact page, there I can right click the email address, then I have to click back, and start trying to get the 2nd address.
And since the whole contact box is already a link, why not make the email address a different link.

![test2](https://user-images.githubusercontent.com/13450219/107585908-4bf34a00-6bff-11eb-8685-99bf7bb598e3.png)

**Comment by pedrobaeza** [comment]
Use the list view and copy the emails from there. See also latest versions, and you can propose a pull request with improvements for master version.

Closing as no Odoo issue.
