### ISSUE TITLE
[8.0] Search returns different curious results (product.category)

### ISSUE THREAD

**Issue by Karsten-77** [odoo/odoo#6598]
No idea why, but my search in product.category returns every time only 3 results. Something hardcoded missed?

Iam on 8.0 currently.

As example I search for "baby" in category Odoo only returns:
   `Deutschland / Baby`
   `Deutschland / Baby / Kinderwagen & -tragen / Babytragen`
   `Deutschland / Baby / Sicherheit / Babyphones`

why not all categories which have Baby in route? When I search for Topcategory "Baby" it returns:

   `Deutschland / Baby / Kleidung, Schuhe & Accessoires`
   `Deutschland / Baby / Pakete & -Sets`
   `Deutschland / Baby / Auto-Kindersitze & Zubehör`
   `Deutschland / Baby / Badezubehör`
   `Deutschland / Baby / Bettausstattung`
   `Deutschland / Baby / Bücher & Zeitschriften`
   `Deutschland / Baby / Ernährung`
   `Deutschland / Baby / Möbel`
   `Deutschland / Baby / Kinderwagen & -tragen`
   `Deutschland / Baby / Pflege`
   `Deutschland / Baby / Sicherheit`
   `Deutschland / Baby / Spielzeug`
   `Deutschland / Baby / Taufe`
   `Deutschland / Baby / Zwillinge`
   `Deutschland / Baby / Sonstige`

I not found any expression to get ALL categories with Baby in tree. 

And as feature request: Why you cannot store the default field in which I want to search?

OK, sorry that I opened a ticket, it seems caused by the creation of that categories 
    `.with_context(defer_parent_store_computation=True)`

BUT 

```
`@api.multi
 def get_site_categories(self, account=None, category=None):
    account = account if account else self
    cat_model = account.env['product.category']
    error_msg = 'Cant get the Site Categories for site %s' % account.site
    if category:
        call_data = dict(LevelLimit=6, DetailLevel='ReturnAll', CategorySiteID=int(account.site.ebay_id), CategoryParent=category)
    else:
        call_data = dict(LevelLimit=2, DetailLevel='ReturnAll', CategorySiteID=int(account.site.ebay_id))
    reply = account.call(account, 'GetCategories', call_data, error_msg).response.reply
    ebay_categories = reply.CategoryArray.Category
    cats = []
    if isinstance(ebay_categories, list):
        for item in ebay_categories:
            cat = dict(CategoryID=item.CategoryID, CategoryLevel=item.CategoryLevel, CategoryName=item.CategoryName,
                       CategoryParentID=item.CategoryParentID)
            cats.append(cat.copy())
    else:
        raise orm.except_orm('Info!', 'This category has no more children')
    cats.sort(key=lambda x: x['CategoryLevel'])
    id_map = {}
    for cat in cats:
        parent_id = ''
        # Checks if this eBay Category exists in database
        record = cat_model.search([('ebay_cat_id', 'in', [cat['CategoryID']])]).id
        if cat['CategoryParentID'] in id_map:
            parent_id = id_map[cat['CategoryParentID']]
        # Checks if it is eBay Root Category
        elif cat['CategoryParentID'] == cat['CategoryID']:
            ebay_cat_id = 'site'+str(account.site.ebay_id)
            root_id = cat_model.search([('ebay_cat_id', 'in', [ebay_cat_id])]).id
            if not root_id:
                root_id = cat_model.create({'name': account.site.name, 'type': 'ebay',
                                            'ebay_cat_id': ebay_cat_id, 'ebay_site': account.site.ebay_id}).id
            parent_id = root_id
        elif record:
            pass
        else:
            assert False, "This should not happen if the raw data is consistent"
        if record:
            id_map[cat['CategoryID']] = record
            continue
        record = cat_model.with_context(defer_parent_store_computation=True).\
            create({'name': cat['CategoryName'], 'type': 'ebay', 'parent_id': parent_id,
                    'ebay_cat_id': cat['CategoryID'], 'ebay_site': account.site.ebay_id}).id
        print cat['CategoryName'] + '(' + str(record) + ')'
        id_map[cat['CategoryID']] = record
    cat_model._parent_store_compute(cat_model.cr)
    return`
```

   `cat_model._parent_store_compute(cat_model.cr)`  my ide returns
{TypeError}_parent_store_compute()takes at least exactly 2 arguments(3 given)

Mh, ok I changed to `cat_model._parent_store_compute()` and it seems to work.
Bad documentation of that.

But at least, it changes nothing on behavior for search I discribed at top. Fixed my code, deleted all categories, have reimported and Search returns curious results.

**Comment by Yenthe666** [comment]
Hi @Karsten-77 ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
