### ISSUE TITLE
Unit test "Dropship should not impact the price" is never executed

### ISSUE THREAD

**Issue by chrisrobi** [odoo/odoo#65987]
Hello, if I'm not mistaken, in Odoo v11, v12, v13, the method **test_average_perpetual_8(self)** in file **/addons/stock_account/tests/test_stockvaluation.py** is intended to check that products standard_price is not impacted is case of dropship.
However this method name is used twice is the same class, hence this test has no chance to be performed.

for v11 see : 
https://github.com/odoo/odoo/blob/53fa869179673d7a45ab9e5708e963ae6294fd6f/addons/stock_account/tests/test_stockvaluation.py#L2632
and
https://github.com/odoo/odoo/blob/53fa869179673d7a45ab9e5708e963ae6294fd6f/addons/stock_account/tests/test_stockvaluation.py#L2683

for v12 see :
https://github.com/odoo/odoo/blob/9993d651747fb37e0a0eff6dd724fd57b5af943d/addons/stock_account/tests/test_stockvaluation.py#L2566
and
https://github.com/odoo/odoo/blob/9993d651747fb37e0a0eff6dd724fd57b5af943d/addons/stock_account/tests/test_stockvaluation.py#L2617

PS : I saw this while investigating for a customer, who runs a v11 Odoo instance, and who reports that with average costing, validating a dropship stock move do impact standard_price.

Edit : just seen it is fixed in v14.0

**Comment by pedrobaeza** [comment]
Although that can be true, that's not a problem per se. If there's an issue that can be revealed by that test, please report it instead with the steps to reproduce.

Closing thus.

**Comment by chrisrobi** [comment]
Ok thanks @pedrobaeza, got it.
