### ISSUE TITLE
Mark as invoiceable analytic lines not invoiceable

### ISSUE THREAD

**Issue by anajuaristi** [odoo/odoo#660]
Hello:

Just an small wishlist that improves invoicing from analytic lines.

Suposing a user forgets configuring analytic contract as "invoiceable" setting the different type of invoiceble concepts. 
Suposing same user start some tasks on project and includes timesheets on tasks. After that someone realize that the timesheet lines would be invoiceable. 
The only way to go is setting line by line invoiceable "100%"

It would be good improving having an small wizard on tasks that directly marks as invoiceable selected lines depending on project settings.

Related: tasks could show somewhere (Link?) to related analytic lines in order to see if there is any Work summary/timesheet that is not set "to invoice"

**Comment by Yenthe666** [comment]
Dear @anajuaristi,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
