### ISSUE TITLE
what's the point of Current Inventory Valuation ?

### ISSUE THREAD

**Issue by kevin8909** [odoo/odoo#6603]
I couldn't understand the  result of Current Inventory Valuation menu gives to me. I purchased two products and then move them to stock location from input location. But when I use the Current Inventory Valuation to view the current valuation. The result confused me:
![Uploading QQ截图20150507183736.png…]()

shouldn't it shows me the stock valuation of the stock location instead of input location ?

I check it from stock_valution_history.py file and I couldn't figure it out the point of filter condition:
""AND ((source_location.company_id is null and dest_location.company_id is not null) or
                (source_location.company_id is not null and dest_location.company_id is null) or source_location.company_id != dest_location.company_id)

AND ((dest_location.company_id is null and source_location.company_id is not null) or
                (dest_location.company_id is not null and source_location.company_id is null) or dest_location.company_id != source_location.company_id)""

Is anybody could give me a tip to understand this ? Thx.

**Comment by Yenthe666** [comment]
Hi @kevin8909,

You're probably better off asking these questions on the official help forums (odoo.com/help)
You might want to look at https://www.odoo.com/documentation/user/11.0/inventory.html

Regards,
Yenthe
