### ISSUE TITLE
Order in dashboard.

### ISSUE THREAD

**Issue by justinasjaronis** [odoo/odoo#6606]
When You filter records in tree view, order them by some property (i.e. Sales Lead name) and add current view to dashboard, the order there is lost.

**Comment by justinasjaronis** [comment]
When You filter records in tree view, order them by some property (i.e. Sales Lead name) and add current view to dashboard, the order there is lost.

**Comment by Yenthe666** [comment]
Hi @justinasjaronis,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
