### ISSUE TITLE
[14.0] framework: using 'length' as field name in view breaks views

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#66126]
Impacted versions: 14.0 At least.

Steps to reproduce:
1. Create a new custom module
2. Inherit an existing model, for example `product.template` and add a field `length` on the model:
```
class ProductTemplate(models.Model):
    _inherit = 'product.template'

    product_length = fields.Float(
        string='Length'
    )
```
3. Install the module. Everything is A-okay.
4. Now inherit a view and add the field `length` in it, for example on the product form:
```
<?xml version="1.0" encoding="UTF-8"?>
<odoo>
    <record id="custom_product_template_form_view" model="ir.ui.view">
        <field name="name">custom.product.template.product.form</field>
        <field name="model">product.template</field>
        <field name="priority">99</field>
        <field name="inherit_id" ref="product.product_template_form_view"/>
        <field name="arch" type="xml">
            <xpath expr="//page[@name='general_information']/group/group" position="inside">
                <field name="length"/>
            </xpath>
        </field>
    </record>
</odoo>
```
5. Open the product form and notice how none of the values seem to be set.
6. Remove the field `length` from the form again and update your module. Everything works fine again. The product its default values are now set correctly.

Current behavior: All of a sudden a lot of the values on the form are randomly not set/provided:
![image](https://user-images.githubusercontent.com/6352350/107854265-20e54200-6e1b-11eb-9ef3-d9194c496689.png)
It looks as if the JavaScript side is no longer passing along the values gotten from the Python ORM. Neither the Odoo logs nor the browser console shows you any issues though. Which makes it a very hard one to figure out.

Expected behavior: `length` should be a usuable field and should not result in this very odd behaviour which is totally impossible to figure out. I only figured it out by thinking of "length" as a possible reserved/misinterpret key in the JS framework from Odoo.. :)

**Comment by Yenthe666** [comment]
It might be related to https://github.com/odoo/odoo/issues/41353
However there the values where just not updated, here it completely breaks views and UI logic.

**Comment by ged-odoo** [comment]
Hmm, interesting.  This definitely look like a bug. Now that I think of this, we should have a test with a few test fields named `length`, `isPrototypeof`, `constructor`, and other such names.

**Comment by Yenthe666** [comment]
Yeah would be good to have some tests for this indeed 😄 Do you want me to make an OPW for this issue Géry?

**Comment by Yenthe666** [comment]
OPW `2465808`

**Comment by gdgellatly** [comment]
haha I first reported this 7 years ago and @ged-odoo and @aab-odoo tracked it down for me maybe 4 years ago. It is because of the way underscore.js operates. In OCA we raise a linting error if length is ever used as a variable or field name for this reason.

**Comment by Yenthe666** [comment]
Yeah I've seen reports about it before too. I kinda hope that with this OPW they'd finally decide to fix/failsafe it honestly :) Even just some error saying "Don't use the field `length`" I'd be a happy man 😆

**Comment by gdgellatly** [comment]
@Yenthe666 https://github.com/OCA/pylint-odoo will tell you exactly that and many more bad things.

**Comment by Yenthe666** [comment]
Okay I just did a detailed testing with a custom module throughout models & with different logics. All works like a charm now, thanks :)

**Comment by ged-odoo** [comment]
excellent. I was worried that some other unrelated part of the code would hide some additional issue.
