### ISSUE TITLE
[8.0] Not show all moves of Purchase Order

### ISSUE THREAD

**Issue by ernesto-gm** [odoo/odoo#6614]
**Show all moves of Purchase Order**

Impacted versions:
- 8.0

Steps to reproduce:
 with 
1. Create a new Purchase order
2. Go to "Deliver To" --> go to Warehouse --> click on Routes
3. Edit "Receipt in 1 step"
4. Create a push rule with to send from an internal location to other internal location
5. Create new Purchase Order and assign the "Deliver To" edit
6. Confirm and receive the products
7. Search all transaction where Source Document contains "PO#"

https://www.youtube.com/watch?v=ZN_Fot1MCgc&feature=youtu.be

Current behavior:
- Only show one picking of purchase order on form view.

Expected behavior:
- Show all Pickings of purchase order.

**Comment by Yenthe666** [comment]
Hi @ernesto-gm,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
