### ISSUE TITLE
[account_bank_statement] missing exchange rate difference account with multicurrency

### ISSUE THREAD

**Issue by JulioSerna** [odoo/odoo#6615]
Impacted versions:
- 8.0

Steps to reproduce:

Allow multi currencies and to set gain/loss accounts
Create one invoice with currency **USD** by amount = **100.00**
Validate invoice
Create banks statement and create statement line by amount = **99.90**
to try pay invoice and difference to make writeoff adding one tax

current behavior 
shows the warning,
![reconciliation on bank statements - odoo](https://cloud.githubusercontent.com/assets/7595505/7528411/ef973062-f4ec-11e4-95c0-a9e754d429f8.png)

expected behavior
create journal entry

i made a video,
https://www.youtube.com/watch?v=yjcmxRDckRc&feature=youtu.be

this happen just when the invoice and payment has difference currency at the currency company

**Comment by Yenthe666** [comment]
Hi @JulioSerna,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
