### ISSUE TITLE
Incorrect Product Cost Calculation in Odoo (Example of Average Method)

### ISSUE THREAD

**Issue by ztsiklauri** [odoo/odoo#6618]
**Impacted versions:**
- 8.0 and above

**Steps to reproduce:**

**Step 1.**

Create a Supplier: Pepsi Co and Create a Product: “Can”.  In Costing Method of product select: Average Price.

**Step 2.**

Operation: Create a Purchase Order with above Supplier and Product. Quantity = **5**, Purchase Price = **10**. Confirm Purchase, Receive Products and Validate Invoice. 
Results:
Total Cost of Products = **50**. Total Quantity = **5**. Adjusted Cost per Can = **10**. 

**Step 3.** 

Operation: Create a Purchase Order with above Supplier and Product. Quantity = **8**, Purchase Price = **15.**  Confirm Purchase, Receive Products and Validate Invoice. 
Results:
Total Cost of Products = **170**. Total Quantity = **13**. Adjusted Cost per Can = **13.08**. 

 **Step 4.**

Operation: Create a Sales Order with above Supplier and Product. Quantity = **4**, Sales Cost Generated By Odoo will be = **13.08**.  Confirm Sale, Transfer Products and Validate Invoice. 
Results:
Total Cost of Products = **117.69**. Total Quantity = **9**. Adjusted Cost per Can = **13.08**

**Step5.**

Operation: Create a Purchase Order with above Supplier and Product. Quantity = **50**, Purchase Price = **1**. Confirm Purchase, Receive Products and Validate Invoice. 
Results:
Total Cost of Products = **167.69**. Total Quantity = **59**. Adjusted Cost per Can = **2.84**. 

**Step 6.**

Now, Suppose I forgot to register a purchase order after Step 3. Register it with the back Date so it will be after third PO: Quantity = **25**, Purchase Price = **50.**  Confirm Purchase, Receive Products and Validate Invoice. 
Results:
Total Cost of Products = **1417.69**. Total Quantity = **84**. Adjusted Cost per Can = **16.88.** 

**This Last Cost Of Product calculated by ODOO is TOTALLY INCORRECT!**

Cost should be **15.72.**

Reasons: 
1. Last Picking was made was with back date after third step, and If you make it after step 3 without “”forgetting”, then the Cost will be: **15.72**.  This means that program didn’t recalculate the cost as should have done. It means that Inventory valuation becomes incorrect if someone makes a purchase with back date.
2. If user uses Anglo Saxon Accounting (Which writes off cost with journal entry), then the journal entry posted by sale will be INCORRECT as well.

**Expected Behavior**

Program should recalculate the cost of the product if user registers the purchase with the back date. Same is for Sales for Back Dates. 

**Note:** 

Forgetting to register sale or purchase is normal and is faced in everyday operations. Incorrect Inventory value will result in charges from TAX Department or Noticed in Audit Reports.

**Comment by orchidinfosys** [comment]
HI Zura,

Up to Step 5 have understand well, Step 6, i am not able to forgot as you said.

Coming to the point, recalculation of backdated entries not a best practice. the reason is as and when the stock move happens system calculating the cost.
If you have installed Anglo saxon even cost of sales also calculated so recalculating the cost for the done transactions will effect the system reliability.
   

Thanks & Regards
Fakrudeen Abbaz, ACMA - ERP Consultant 
Mobile: +97155 66 77 001, skype : fakrudeenabbaz
Sales : 04 295 6615,  Support : 04 295 8986

**Comment by ztsiklauri** [comment]
Hi, thanks for the reply. 

In step 6 I registered Purchase with back date and system didn't calculate correct cost. I understand the concerns about affecting system reliability, but concerns about wrong inventory valuation should have higher priority.

If recalculation is not an option, then Odoo should disable an option to do picking with back dates.

**Comment by orchidinfosys** [comment]
In Average cost  you have option to update the cost in product master manually

Thanks & Regards
Fakrudeen Abbaz, ACMA - ERP Consultant 
Mobile: +97155 66 77 001, skype : fakrudeenabbaz
Sales : 04 295 6615,  Support : 04 295 8986

**Comment by ztsiklauri** [comment]
Imagine 30.000 Purchase and 23.454 Sale orders and Excel sheets to update Cost Manually.

**Comment by kevin8909** [comment]
watching

**Comment by mtutberidze** [comment]
completely agree with this issue.

**Comment by tammrii** [comment]
subscribed

**Comment by kingsleyuk2003** [comment]
any solution yet?

**Comment by Yenthe666** [comment]
Hi @ztsiklauri ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by Muhammadinaam** [comment]
Does this issue exist in Odoo 13?
