### ISSUE TITLE
[8.0] All listviews are empty with IE10. PO creation form also empty

### ISSUE THREAD

**Issue by kristjanm** [odoo/odoo#6621]
Issue Occurs both in odoo.com testversion and in our local installation.
All listviews are empty with the IE10 web browser.. When pressing "Create PO", empty form is displayed

![odoo broken po form](https://cloud.githubusercontent.com/assets/12332993/7535301/37b294d2-f58c-11e4-93f1-898f7a40606b.png)

**Comment by Yenthe666** [comment]
Hi @kristjanm ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
