### ISSUE TITLE
[8.0] mass mailing opt-out selection of contact does not work

### ISSUE THREAD

**Issue by yostashiro** [odoo/odoo#6623]
**mass mailing opt-out selection of contact does not work**

## Impacted versions:

 - 8.0

## Steps to reproduce:

 1. create a mailing list
 2. add a contact in mailing list
 3. select Opt-Out for this contact
 4. select Mailing List for Recipients in mass mailing form, select the mailing list created in above step, and click 'Send to All' button

## Current behavior:

 - Emails are generated for all the contacts including the ones that have opted out.

## Expected behavior:

 - Email should not be generated for contacts that have opted out.

**Comment by judecoster** [comment]
Hello,

Thanks for the feedback ! It's fixed. (https://github.com/odoo/odoo/commit/2d260b78d8c9f910719e7537e98e940ee1abefca)

**Comment by yostashiro** [comment]
Great, thanks!
