### ISSUE TITLE
[8.0] Reconciliation : split of the customer payment 

### ISSUE THREAD

**Issue by chrisdec** [odoo/odoo#6624]
Hello, 

I noticed a strange behavior in Odoo regarding reconciliation on bank statements. 
## Step to reproduce 

Let's imagine you make two invoices for the same customer : 
- The first one has a total of 80€
- The second one has a total of 20€

You customer makes a payment of 100 for those two invoices. In your bank statement, you have one line of 100€. 

In the reconciliation screen, Odoo easily understands that those 100€ are related to invoice 1 and invoice 2. You can thus click on "OK" to reconcile. 
## Current behavior 

If you go in journal items, you have two reconciliation references and 4 lines on the customer account : 
- Invoice 1 reconcile with a payment of 80
- Invoice 2 reconcile with a payment of 20

Let's imagine your customer calls you and asks about his 100€ payment --> You don't have this information in your comptability. You simply don't see the payment of 100€ for this customer. This behavior is not good for historic. 
## Expected behavior 

It must be only one reconciliation reference and 3 lines : 
- Payment of 100€ reconciled with invoice 1 and invoice 2

Thanks in advance for your answer, 

Christelle

**Comment by adrienpeiffer** [comment]
OPW 634884

**Comment by Yenthe666** [comment]
Hi @chrisdec,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
@adrienpeiffer could you mention wat the response was on 634884 too?

Regards,
Yenthe
