### ISSUE TITLE
Point_of_sale: open session error- file script chrome.js

### ISSUE THREAD

**Issue by ToubkalTech** [odoo/odoo#66270]
Impacted versions: 13

Steps to reproduce: open new session.

Current behavior: When create new database with demo data and open session from pos app, the session has broken in 'loading pictures'.
![pos_1](https://user-images.githubusercontent.com/74025293/108074108-1e782780-7069-11eb-8f8a-fb8b636a8b24.png)
![pos_2](https://user-images.githubusercontent.com/74025293/108074111-1f10be00-7069-11eb-88cd-4e9e1a06b0d4.png)

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by Yenthe666** [comment]
Hi,

I see you're running a local stack. Can you reproduce this on the latest runbot instances at runbot.odoo.com?
