### ISSUE TITLE
Product Type depcrecated?

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#6630]
[Here](https://github.com/odoo/odoo/blob/622e00baa5e920863dc1daee49d420ede4056b0f/addons/stock/product.py#L376), it says: 
"Consumable: Will not imply stock management for this product.
Stockable product: Will imply stock management for this product."
However, tested in runbot 8.0 as of today, a stock movement will be created.

The only instance of 'consu' beeing used without 'product' seems to be:
https://github.com/odoo/odoo/blob/622e00baa5e920863dc1daee49d420ede4056b0f/addons/stock/stock.py#L2210

The tooltip however in it's present form does not predict it's behaviour correctly, as a normal english speeking person would understand it in the given context.

It's a big deal for onboarding, because it's a value destroying tooltip.

Thanks considerung sorting this out correctly.

**Comment by jco-odoo** [comment]
Your consumable products are those that don't need an accurate follow-up of stock levels.  You kind of assume you will have enough of it, maybe because you need it all the time anyways and the cost is not too high e.g. pencils, toilet paper, scotch tape, ...  

In fact, the notion of consumable and stockable products makes sense, but following your explanation, stockable products seem to be more like the correct default value.

**Comment by blaggacao** [comment]
Thanks, I understand the concept. :-) Actually, I claim, that the tooltip is misleeding. I think this misleeding tooltip should be improoved, or it should be inforced programatically, what it promises.

In fact, programatical prohibition of stock moves, it would easily produce wrong entries through parametrization errors: If I have set on the gategory income, expence, incoming, outgoing and valuation accounts, then not respecting the latter three would result in inconsistent accounting entries.. So if it is decided to enforce the field's behaviour programatically, it must at least be added on the category a similar field and must be made a constraint check, so that the fields coincide. It would be better however to move the concept towards the product category (as interreted as "accounting category"). It can still be displayed on the product as relational or similar, and can be made available to grouping. It would require some sensible defaults on the product category, however.

If you have any questions or doubts about this, don't hestiate to ask me for clarification.

best, David

**Comment by Yenthe666** [comment]
Hi @blaggacao,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
