### ISSUE TITLE
[V8][Website] Wrong url reused in alternate tags in header for SSL website

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#6631]
Hy,

I've a website running in httpS.
In the meta, Odoo generate the following tag :

```
<link rel="alternate" hreflang="fr" href="http://domain.tld/page/homepage"/>          
```

How can I change this?

**Comment by nafex** [comment]
i have the same problem. Also all urls in the sitemap.xml are http...

**Comment by jaredkipe** [comment]
I can confirm this, even with https in the SystemParameters and X-Forwarded-Proto set appropriately.  This affects V9 as well.

**Comment by jaredkipe** [comment]
This can be corrected by setting the appropriate proxy headers. See #9057 (the sitemap needs to be re-generated, if you leave it alone it will eventually re-generate on its own)

**Comment by jaredkipe** [comment]
This can be closed.

**Comment by mgielissen** [comment]
For Apache:

RequestHeader set X-Forwarded-Proto https
ProxyPreserveHost  On
