### ISSUE TITLE
Database subdomain: db-filter does not work behind Apache Proxy

### ISSUE THREAD

**Issue by treviser** [odoo/odoo#6633]
My set-up:
Odoo 8.0, package install according to the official odoo documentation, last updated about 2 weeks ago, Ubuntu 14.04, Amazon EC2 instance in VPC, Apache 2.2 on a separate server in the same VPC.

When I request a database using a subdomain in the http-request, I always get to the database selector (see attached network request data).

My VirtualHost definition: 
#NameVirtualHost *:80
<VirtualHost *:80>
    #ServerAdmin webmaster@dummy-host.example.com
    ServerName *.twanda.ch
    ServerAlias hpt-smoke.twanda.ch
    ProxyRequests off
    ProxyPreserveHost On
    ProxyVia On
    
    Proxypass / http://192.168.100.184:8069/
    #ProxypassReverse / http://192.168.100.184:8069/
</VirtualHost>

My Odoo config file:
[options]
; This is the password that allows database operations:
admin_passwd = XXXXXXXXXXXXXXXXXXXX
db_host = False
db_port = False
db_user = odoo
db_password = False
db_filter = ^%d$
addons_path = /usr/lib/python2.7/dist-packages/openerp/addons,/usr/lib/python2.7/dist-packages/openerp/custom/addons
proxy_mode = True

Also documented here: https://www.odoo.com/forum/help-1/question/how-to-set-database-filter-on-sub-domain-for-odoo-website-using-apache-web-server-64935

And it seems to be a very old bug back to Version 6.1:
https://bugs.launchpad.net/openobject-server/+bug/1065127

...and my result result:

![inspect network request_024](https://cloud.githubusercontent.com/assets/1814941/7551635/e988bc9a-f690-11e4-8d53-36c8105e29d3.png)

**Comment by CraigBarnesOpusVL** [comment]
I have found that the config option db_filter does not work at all, but the commandline option --db-filter does.

**Comment by vincentkedison** [comment]
--db-filter becomes dbfilter in configuration file
https://www.odoo.com/documentation/8.0/reference/cmdline.html
