### ISSUE TITLE
Chart of Accounts filter is not respected on jurnal items view

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#6636]
The Chart of Accounts Tree-View display is fine and respects the filters set in the wizard (eg. 2014, 04/2014-08/2014). However, when you click on any one account that has additional entries, the set date filter is not respected. This is not intuitive. It makes work more difficulte and can be a source of error, because intuitively a different behaviour would be expected.

**Comment by Yenthe666** [comment]
Hi @gustavovalverde,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
