### ISSUE TITLE
[8.0]picking shouldn't always trust the reserved information when move

### ISSUE THREAD

**Issue by GoodERPJeff** [odoo/odoo#6637]
version: openerp 8.0 runbot
## Step to produce:

for picking WH/OUT/00005, we plan to move 80 ipad, and reserved 80, ready for move.

now I edit and change the quantity to 40, then save.

now click "transfer" button
## Espected result:

popup window for confirm 40 ipad mini to delivery or raise an error
## current result

popup window with 80 ipad mini and happily been confirmed

**Comment by Yenthe666** [comment]
Hi @GoodERPJeff ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
