### ISSUE TITLE
Bug V8.0 Settings -> Configuration -> Sales 'Access Error'

### ISSUE THREAD

**Issue by linuxyeti** [odoo/odoo#6639]
Hi

OK, here's the setup ...

Installed odoo and setup company A
 --------- Created users, all functionality fine
Wanted to add a second company, but have it effectively managed by an umbrella company
---------- Setup Company B , and made this a parent on company A
---------- Setup company C , again setting Company A as the parent.
-------------- Created a new set of users assigned only to company C
Everything seems to work fine, all the configuration options tried etc, however, when a user is logged in only to Company C, and they access  Settings -> Configuration -> Sales the following error is returned

'The requested operation cannot be completed due to security restrictions. Please contact your system administrator.
'Document type: product.product, Operation: read'

However, if a user has their preferences set to log into company A, they are able to access the Sales configuration.

Even if a user has company A as an allowed company, but are logged into any company other than company A they get the above error.

These companies are all setup in the same database..

A work around, for the time being appears to be to assign the user from company C to company A to access the sale configuration, however, does this only change the sales configuration for company A or is it changed globally?

Is there a way to get this working as it should? I have tried all weekend to get this to work...

**Comment by linuxyeti** [comment]
Hi 

Any news?

**Comment by Yenthe666** [comment]
Hi @linuxyeti,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
