### ISSUE TITLE
VPC 

### ISSUE THREAD

**Issue by njohnjoel** [odoo/odoo#66410]
Impacted versions: 14.0

Steps to reproduce:

Current behavior: Working on one server , not able to set-up on VPC

Expected behavior: Trying to install odoo on 2 servers (for failover purpose) and the DB (postgreSQL will be on private server) .. So you setup instructions where do I change the string to point the DB to diff server

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a deployment question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
