### ISSUE TITLE
pdf generation fails

### ISSUE THREAD

**Issue by bash-stack** [odoo/odoo#66418]
Impacted versions:
14 (maybe below)
`wkhtmltopdf 0.12.6`

Steps to reproduce:
Generate PDF ( by pressing print or send by mail)

Current behavior:
```
The switch --header-spacing, is not support using unpatched qt, and will be ignored.
The switch --header-html, is not support using unpatched qt, and will be ignored.
The switch --footer-html, is not support using unpatched qt, and will be ignored.
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once
```

Expected behavior:

make pdf

Video/Screenshot link (optional):

![screenie](https://user-images.githubusercontent.com/62184749/108284336-4e1c5200-7185-11eb-9280-5d7008471a9c.png)

Support ticket number submitted via odoo.com/help (optional):
should i ?

**Comment by raspberryflakes** [comment]
Hi, try to reinstall wkhtmltopdf by following step on this [gist](https://gist.github.com/faniska/37f896d5e9de5fee925925d7caf3cb9e)

**Comment by pedrobaeza** [comment]
You must use 0.12.5 version. Please follow https://www.odoo.com/documentation/14.0/setup/install.html

Closing as no issue, but incorrect deployment.
