### ISSUE TITLE
Attachment File translation not work

### ISSUE THREAD

**Issue by rb3606** [odoo/odoo#66420]
Impacted versions: 14.0

Steps to reproduce: Create fresh purchase order and set lang of customer any other than english. And click on Send By Mail button , Mail wizard dialog will open , Body of mail is translated but attachment file name remain in english .

Current behavior: Attachment file name not translating as per customer language

Expected behavior: Attachment file should be translated. 

Video/Screenshot link (optional): Screenshot taken from runbot. 
![image](https://user-images.githubusercontent.com/6355966/108306286-d9233980-71d1-11eb-90b4-53591a771e86.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
Confirmed not working in runbot.
![Selección_003](https://user-images.githubusercontent.com/7165771/108321270-3912e380-71c4-11eb-940d-ee2bcc9a5d43.png)
![Selección_004](https://user-images.githubusercontent.com/7165771/108321286-3b753d80-71c4-11eb-9831-589a0513dcef.png)

@mart-e is this something for you?

**Comment by mart-e** [comment]
Hi,

Thanks for the report. I have fixed it at #66441
![Screenshot_2021-02-18 P00008 - Odoo](https://user-images.githubusercontent.com/564822/108347858-5609df80-71e1-11eb-81e0-4a4e89cf299c.png)
It will soon be integrated.

**Comment by rb3606** [comment]
Thanks @pedrobaeza @mart-e
