### ISSUE TITLE
[XMLRPC API] Get field default value

### ISSUE THREAD

**Issue by Prometee** [odoo/odoo#66450]
**Impacted versions:** >= 13

**Steps to reproduce:**
Introspect models to find the default value of any fields using `defaults_get` action

**Current behavior:**
The default value can't be retrieved by `defaults_get` because the default value could be computed and could depends on the context or other things. Also some models are operating process like update or sending emails into this method.

**Expected behavior:**
Retrieve a default value in any cases.

I'm doing this using the XMLRPC API so no python code is involved here. I'm building a tool to get a representation of each Odoo models. I'm using what it's available in `ir.model` and from what I can get with a call to the action `fields_get`, but at the end I need to found a way to retrieve (at least) the scalar `default` value of each `Selection` fields.

Is there a way to do that or not ?

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

Little tip: You have to provide the context for getting that.
