### ISSUE TITLE
Problem downloading PDF invoice in Firefox

### ISSUE THREAD

**Issue by ozeh** [odoo/odoo#6647]
I have Odoo ver 8 installed on a Gentoo Linux environment and as a client I'm using Firefox 37.0.2 with the option "Ask where to save file" selected. When I'm generating the PDF from an invoice record a window with the options "Open in Adobe Reader" and "Select where to save file". Opening up the PDF file works like a charm, but when I select the second option nothing happens and I end up without a saved PDF. The folder dialog where I should select the saving location never comes up.

There is no issue with IE (didn't check on Chrome). When I set the default saving location in Firefox it works so the issue is only when I want to select the saving location each time (my default setting).

**Comment by Yenthe666** [comment]
Hi @ozeh,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
