### ISSUE TITLE
[8.0][9.0] Graph: All `Float` fields shown even when not defined in graph view.

### ISSUE THREAD

**Issue by vak0160** [odoo/odoo#6648]
Impacted Versions:
- 8.0 -> 94aae97c041ce42da62dd8b062e91bec10f64e65
- master -> 4bef17cc555af487b989dd470b0988c21db37a9a

Steps to reproduce:
1. Create a query driven model (using _init_ method).
2. Add one `Date` field (e.g. `workdate`).
3. Add more than one `Float` fields (e.g. `late`, `late2`, `late3`).
4. Add `workdate` field to graph definition with `interval="month"`.
5. Add `late` field to graph definition with `type="measure"`.

Current behavior:
- All `Float` fields shown to graph view, and using the first field it choose (not the one I defined for my case).

Expected behavior:
- Graph view only shows the field I defined and use it.

Example code:

```
<field name="arch" type="xml">
    <graph string="testing_graph_multi_float" type="bar">
        <field interval="month" name="workdate"/>
        <field operation="+" type="measure" name="late"/>
    </graph>
</field>
```

Image:

![screenshot from 2015-05-11 16 16 24](https://cloud.githubusercontent.com/assets/8555196/7561811/27d717b2-f7f9-11e4-949c-5abd32894123.png)

The field I defined is the _Total Late_ one, I didn't define the _Total Early_ field, but it exists on model, and the one it choose as default is the _Total Early_ one.

**Comment by jcdrubay** [comment]
I am facing the same behavior in v10 :/

This "auto-discovery" of measure  seems nice, however it should be possible to:
 - exclude some fields; now I get my sequence field added as a measure
 - define the defaults measure

**Comment by pedrobaeza** [comment]
I'm afraid this is how the framework works on this. You should avoid to declare fields that you don't want to be visible in your pivot/graph.

For now there are no plans to change this AFAIK. I close this issue for triaging old ones.
