### ISSUE TITLE
Child Taxes in POS does not get computed properly

### ISSUE THREAD

**Issue by parikshitbapat** [odoo/odoo#6649]
Hello 

I have installed Indian COA in odoo DB. I have applied tax "Input Service Tax @ 12.36%" to one of the product as follows : 

![tax_1](https://cloud.githubusercontent.com/assets/10809905/7562598/4d490966-f7f3-11e4-9bc1-c062c5aa0c62.png)

![tax_2](https://cloud.githubusercontent.com/assets/10809905/7562602/55c56b2a-f7f3-11e4-9b99-c188f78000b6.png)

 but on POS takes care of only parent tax. i.e 12 %. Child taxes are not considered.

![tax_4](https://cloud.githubusercontent.com/assets/10809905/7562706/0f0545ce-f7f4-11e4-95c8-c1dc2a5763f4.png)

So logically the tax should get compute to 12.36 and not 12.

has any one experience this before ? Is there any solution available.

**Comment by parikshitbapat** [comment]
Has any one answer to this ?

**Comment by Yenthe666** [comment]
Hi @parikshitbapat,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
