### ISSUE TITLE
translation term of crm_partner_assign seems to miss in lp .po templates

### ISSUE THREAD

**Issue by tv-openbig** [odoo/odoo#6655]
Version: odoo 8.0
How to recapture the issue ?

1. I have installed the module crm_partner_assign ?
2. I am logged in as "admin" with active language "german" (de_DE)
3. I have created a test lead named "lead". 
4. I have opened the action menu "more".

Wrong Result: I see the menu term in english language  : "Assign Salesmen of assigned partner"

![bildschirmfoto 2015-05-11 um 14 30 42](https://cloud.githubusercontent.com/assets/8348598/7564885/59008df4-f7eb-11e4-8166-e133d160c7a3.png)

Expected result: I would expect this term as a translatable term under launchpad:
https://translations.launchpad.net/openobject-addons/8.0/+pots/crm-partner-assign/de/+translate?search=Assign&show=all&memo=10&start=10

Unfortunately i could not find it. Therefore it is also not possible to translate the 
non-existing term.

**Comment by mart-e** [comment]
Indeed, the crm_partner_assign seemed to be still with 7.0 terms, we missed it during export for 8.0
Fixed at 3280819

PS: we are now using Transifex, check [wiki page](https://github.com/odoo/odoo/wiki/Translations) for details
