### ISSUE TITLE
Cant uncheck "lead enrichment" in crm settings

### ISSUE THREAD

**Issue by werkwolk** [odoo/odoo#66578]
Impacted versions: odoo 14 community 6304260-14-0.runbot54.odoo.com

Steps to reproduce: go to settings -> CRM -> uncheck "lead enrichment" checkbox -> save -> return -> you'll find it checked again.

Maybe its done on purpose. First thing a colleague did when he saw it was click on it so i assume this can provide company data to odoo?

**Comment by Yenthe666** [comment]
Hmm, this works fine on V13 and should also work fine on V13. @mart-e @tde-banana-odoo who can check this one?

**Comment by werkwolk** [comment]
its nothing critical, just thought i'd mention it

**Comment by Yenthe666** [comment]
OPW `2465817` for now you can manually uninstall the app `crm_iap_lead_enrich` to accomplish the same

**Comment by mart-e** [comment]
Actually, it's the `iap_crm` module that you have to uninstall, `crm_iap_lead_enrich` is in autoinstall since 20fff84b9d0e4d96a3a657965ae5e82a1e59f7bb so it's reinstalled just after being uninstalled.

**Comment by werkwolk** [comment]
thx guys!

**Comment by Yenthe666** [comment]
After some digging & discussing it with Odoo this only happens on a runbot actually. The runbot has some extra logic which triggers this but on local instances you're able to disable it. So, not really an issue :)

**Comment by werkwolk** [comment]
I went to runbot because I encountered it. Perhaps in the packaged windows version it's similar?

⁣
Mvg

Mesud Branswijck (Smartphone)

Support: +32 53 610 102
Personal: +32 53 610 123​
