### ISSUE TITLE
duplication on sale order odoo 14

### ISSUE THREAD

**Issue by mah007** [odoo/odoo#66580]
Odoo 14 enterprise sale order reference (sale order name) duplicated some time 
why ?
![download](https://user-images.githubusercontent.com/7385542/108635225-064c4200-7487-11eb-9907-e2be200a0ff8.png)

**Comment by pedrobaeza** [comment]
Steps to reproduce the problem?

**Comment by mah007** [comment]
data team in my company discovered that many sale orders has the same sequence 
we don't know if that happened becoz of restart and update or this is an odoo bug

**Comment by pedrobaeza** [comment]
Yeah, but while you don't provide more information on how to reproduce it, I'm afraid this won't be solved. Try with a sequence with no gap. Closing meanwhile further information is provided.
