### ISSUE TITLE
[master] Error: send_commands to 'product_return_moves' receive a non command value.

### ISSUE THREAD

**Issue by oliverzgy** [odoo/odoo#6663]
An Error happened when to reverse a transfer

![2015-05-12 16 20 19](https://cloud.githubusercontent.com/assets/3712729/7582697/dced1876-f8c2-11e4-8ffa-dfe1653704fb.png)

**Comment by Yenthe666** [comment]
Hi @oliverzgy ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
