### ISSUE TITLE
Squash.io integration?

### ISSUE THREAD

**Issue by emiquelito** [odoo/odoo#66644]
Hello Odoo Community!

I'm with [Squash.io](https://www.squash.io/) and we wanted to support the Odoo project by providing on-demand test environments for each Pull Request (i.e: a complete staging environment for each PR, running your full stack). Our service is free for Open Source projects like Odoo and we would be able to increase our standard limits as needed to provide great user experience for Odoo developers and contributors.

Here is how it works, you push a branch of code, create a Pull Request and Squash automatically posts a comment with a unique URL where you can test the branch changes in isolation (it usually takes just a few minutes for an environment to spin up):

![squash-url](https://user-images.githubusercontent.com/98694/108773052-0c8bfe00-751b-11eb-8fad-7334b11b80bf.png)

You may also customize the comment to include links for different versions of Odoo if it makes sense, like this:

![custom-pr-comments-full](https://user-images.githubusercontent.com/98694/108785585-f25c1b00-752e-11eb-9095-486b688d115d.png)

Squash can also spin up a new environment for each commit within a PR, and give you a pass or fail if it can receive a success HTTP response. You can also run any existing front-end tests (Selenium, TestCafe, etc.) on top of this Squash environment.

![squash-check2](https://user-images.githubusercontent.com/98694/108773348-6ee4fe80-751b-11eb-92e3-d9262192264e.png)

### Squash setup

Let me know if you like the idea of using Squash on this project. If so, we would be happy to create a Pull Request with a Squash YAML file so you don't have to invest any time on this.

**Comment by Yenthe666** [comment]
Odoo S.A has its own automated deployments and platforms. Besides of this the issue tracker is only for official bugs, not for advertising :)
