### ISSUE TITLE
[8.0] Calendar View of SO: broken customer names in sidebar filter

### ISSUE THREAD

**Issue by a0c** [odoo/odoo#6668]
Open any v8 in Demo / Runbot.

Goto: Sales > Sales Orders

Switch to Calendar View.

Customer names in the sidebar filter on the right are 1-dummy-letter long.

**Comment by alejandrosantana** [comment]
I see it happening in "Sales Orders" and "Quotations", but not in "Opportunities" or "Leads", if it helps.

**Comment by Yenthe666** [comment]
Hi @a0c,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
