### ISSUE TITLE
Possible expected behavior? -> ValueError: Invalid field project.project.activity_ids in leaf ('activity_ids', '!=', False)

### ISSUE THREAD

**Issue by werkwolk** [odoo/odoo#66685]
Impacted versions: Project - odoo 14 community 6353769-14-0.runbot56.odoo.com

Steps to reproduce: enable developer mode -> Projects -> dev options -> edit action -> add activity view 
![image](https://user-images.githubusercontent.com/69362083/108844153-00b44080-75dc-11eb-9c12-05b54f9d0c21.png)

-> open activity view

Current behavior: 

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/69362083/108843952-b632c400-75db-11eb-99d9-6ebae6e4492b.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
This can be considered as an error, as you are "developing" something that can't be done, although done directly in the DB through developer mode.

That object doesn't accept activities.

**Comment by werkwolk** [comment]
I had a suspicion the exception route was used to message. hence the "expected behavior?" prefix 

Thank you for pointing this out. i'll keep that fact (that odoo allows exception->messaging) in consideration in the future.
