### ISSUE TITLE
attachement problem

### ISSUE THREAD

**Issue by jzahid** [odoo/odoo#66699]
Impacted versions:
14 
Steps to reproduce:
-  create a new quottation , save then try to edit again
Current behavior:
- pdf attachemnt is created , and whenever we try to add new line or modify existing one, error message shows up with the message :  Model (ir.attachment)  Database fetch misses ids ((<NewId origin=4661>,)) and has extra ids ((4661,)), may be caused by a type incoherence in a previous request.
- If we delete the attachement then saving record. we can edit
Expected behavior:
 - normal edition
Video/Screenshot link (optional):
![ksnip_20210223-145302](https://user-images.githubusercontent.com/11353154/108853921-90abb780-75e7-11eb-9549-8199def6e81d.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
When you say "pdf attachemnt is created", how is it created exactly? Is this reproducible on runbot?

**Comment by jzahid** [comment]
Attachements are created automatically for sale orders and purchase orders. When i delete attachement this i don't have the error message.

**Comment by pedrobaeza** [comment]
Not by default, as you can see in runbot. Maybe you have activated the option in the report, but this is working correctly for invoices that are stored, so this indicates something incorrect in your end. Please try to reproduce the problem in runbot.
