### ISSUE TITLE
odoo: mail server issue with code 554

### ISSUE THREAD

**Issue by nitishnm** [odoo/odoo#66705]
Hi,

Facing issue in odoo 14 while sending the email. Below is the error .. can anyone please help with solution

SMTPDataError: 554
5.2.0 STOREDRV.Submission.Exception:SendAsDeniedException.MapiExceptionSendAsDenied; Failed to process message due to a permanent exception with message Cannot submit message. 0.35250:51200000, 1.36674:0A000000, 1.61250:00000000, 1.45378:02000000, 1.44866:CC1F0000, 1.36674:0E000000, 1.61250:00000000, 1.45378:D11F0000, 1.44866:0E020000, 16.55847:2C0F0000, 17.43559:0000000024020000000000000000000000000000, 20.52176:140F1C8F2100103100000000, 20.50032:140F1C8F9117000000000000, 0.35180:140F1C8F, 255.23226:77210000, 255.27962:0A000000, 255.27962:0E000000, 255.31418:A8210000, 0.35250:0201F285, 1.36674:0A000000, 1.61250:00000000, 1.45378:02000000, 1.44866:18000000, 1.36674:32000000, 1.61250:00000000, 1.45378:1D000000, 1.44866:01000000, 16.55847:84000000, 17.43559:00000000A8030000000000000000000000000000, 20.52176:140F1C8F2100101053000000, 20.50032:140F1C8F911700002E000000, 0.35180:58000000, 255.23226:4800D13D, 255.27962:0A000000, 255.27962:32000000, 255.17082:DC040000, 0.27745:3E000000, 4.21921:DC040000, 255.27962:FA000000, 255.1494:46000000, 0.38698:05000780, 0.37692:01000000, 0.44092:0F010480, 0.41232:0F010480, 0.60208:0F010480, 0.37136:00000000, 0.34608:1A010480, 0.55056:1A010480, 0.42768:00000000, 0.56112:1A010480, 0.52807:1A010480, 7.36354:01000000000001091A010480, 4.33016:DC040000, 7.40748:010000000000010B1A010480, 7.57132:000000000000000000000000, 1.63016:32000000, 4.39640:DC040000, 8.45434:39779764EA1C2E4582A45C65D88A1BDA05000780, 1.46798:04000000, 5.10786:0000000031352E32302E333836382E3033333A4D4131505230314D42333033363A65616666316133352D323766382D343164392D626139632D6137313365616164653564613A383634353600, 7.51330:44AAB3F806D8D80800000000, 0.39570:05000780, 1.55954:0A000000, 0.49266:02000000, 1.33010:0A000000, 2.54258:00000000, 0.40002:7A000000, 1.56562:00000000, 1.64146:32000000, 1.33010:32000000, 2.54258:DC040000, 255.1750:0A005636, 255.31418:7D000000, 0.22753:BE000000, 255.21817:DC040000, 0.64418:82000000, 4.39842:DC040000, 0.41586:03003866, 4.60547:DC040000, 0.21966:C8000000, 4.30158:DC040000 [Hostname=MA1PR01MB3036.INDPRD01.PROD.OUTLOOK.COM] 

Tried with both SMTP outlook with ports 25 and 587

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
