### ISSUE TITLE
[8.0] The price of the product in the e-shop is zero

### ISSUE THREAD

**Issue by Kollda** [odoo/odoo#6673]
Hello,

my problem is that when I set the sales price list of the partner, so the transition to e-shop, prices are zero (the original price is crossed out next to the zero price). But when I switch to the shipping cart, the prices are displayed correctly, the same in the sales offer.

I saw it on the issue in view, but still I can not find anything ..

Thank you and best regards

![e-shop_problem](https://cloud.githubusercontent.com/assets/12412174/7588418/405b890c-f8bd-11e4-8076-45cbe9ce58d3.jpg)

![shopping cart](https://cloud.githubusercontent.com/assets/12412174/7588825/ba2cc1c2-f8bf-11e4-8d1d-6e86a6bd6744.jpg)

**Comment by Yenthe666** [comment]
Hi @Kollda,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
