### ISSUE TITLE
[13.0] Error when printing pdf report with lots of pages

### ISSUE THREAD

**Issue by tinhnguyen-novobi** [odoo/odoo#66744]
Impacted versions: 13.0 Enterprise (Maybe: 11.0, 12.0, 14.0)

Steps to reproduce:
- Use the Odoo 13 database which has a lot of data.
- Select lot of records (Ex: 3000 invoices (account.move)) -> Click on Print

Hello all,
I'm trying to print a pdf with a lot of records in Odoo 13.0 Enterprise (Server Ubuntu 18.04, 18Gb RAM) and it faced the error (I didn't face that error on Odoo 10).
- I tried to increase the limit_time_cpu, limit_memony on odoo.conf
- I tried to increase the timeout of proxy (Nginx)

After that, I check the system and I found something that can affect the system.
The library **wkhtmltopdf** eat RAM to out of memory. It generates pdf reports with a lot of .HTML files.

I checked the source code on Github and found the function [_run_wkhtmltopdf](https://github.com/odoo/odoo/blob/13.0/odoo/addons/base/models/ir_actions_report.py#L398).
@smetl did a great improvement on the module report. Commit [Remove pdf merge with single call to wkhtmltopdf](https://github.com/odoo/odoo/commit/b446930dc42479f524eab7e677c5b2007f9fa0a6)

But in case we print the pdf report with a lot of records, we can face 2 issues:
1. The library wkhtmltopdf eat RAM to out of memory.
2. The limit of the number of files a single process is allowed to have open https://stackoverflow.com/questions/16526783/python-subprocess-too-many-open-files

On Odoo 10, it calls wkhtmltopdf for each report and puts all of them together
using the merge_pdf method. It's slower than the new code but it doesn't eat more RAM.
Please advise.

Current behavior:
Select lot of records (Ex: 3000 invoices (account.move)) -> Click on Print
It takes a lot of time and raises the error.

Expected behavior:
Download a pdf report with lots of pages

Video/Screenshot link (optional):
![Error](https://user-images.githubusercontent.com/60870440/108979947-c0c58a00-76bd-11eb-9f86-6c3febbf0a0c.png)
![wkhtmltopdf](https://user-images.githubusercontent.com/60870440/108986554-d7bbaa80-76c4-11eb-8e22-9b74db5b139b.png)
![Out of memory](https://user-images.githubusercontent.com/60870440/108981858-be642f80-76bf-11eb-8574-29ad270f19da.png)

**Comment by tanghulu0608** [comment]
![image](https://user-images.githubusercontent.com/5561864/109108456-941d7b00-776e-11eb-8f6e-8d0fdf9453ac.png)

**Comment by jlzhou** [comment]
try to adjust layout and foreach sequence in your report xml like above.

**Comment by Yenthe666** [comment]
Well, this is a bit of a known limitation/issue with Odoo. Usually the best way is to batch it in smaller files or automate it in some way. I wouldn't really consider this a bug plus it is wkhtmltopdf, not Odoo.
@pedrobaeza do you agree?

**Comment by pedrobaeza** [comment]
Yes, it's outside of scope of Odoo IMO.

**Comment by ruria** [comment]
I disagree.
Odoo choose to use wkhtmltopdf, so here it is some kind of responsability. Even worst, if it is really that previous versions didn´t face this issue because were using wkhtmltopdf in another way, I think something better than nothing can be done.

Note: I´m using Odoo 12 with wkhtmltopdf 0.12.5

**Comment by pedrobaeza** [comment]
Well, if you have an enterprise contract, you can ask for a better explanation or workaround. Concerning this community issue tracker, having this opened is not going to bring anything of value nor it's going to be fixed.

**Comment by sustatio** [comment]
# i had the same issue in odoo 16. here is how i solved it. 
# we take chunks of 30 documents and print them to a one document. then merge all the documents 

class IrActionsReport(models.Model):
    _inherit = 'ir.actions.report'

    def _render_qweb_pdf(self, report_ref, res_ids=None, data=None):

        if res_ids and len(res_ids) > 300:
            raise UserError(_("The report is too large to be printed in one go. Please select less than 300 records."))
        if res_ids and len(res_ids) > 30:
            chunks = [res_ids[i:i+30] for i in range(0, len(res_ids), 30)]
            pdf_merger = PyPDF2.PdfFileMerger()  # Add this line to define pdf_merger
    
            for chunk in chunks:
                pdf_data = super()._render_qweb_pdf(report_ref, res_ids=chunk, data=data)
                pdf_file = io.BytesIO(pdf_data[0])
                pdf_merger.append(pdf_file)
    
            merged_pdf = io.BytesIO()
            pdf_merger.write(merged_pdf)
            pdf_merger.close()
            return merged_pdf.getvalue(),'pdf'
        else:
            return super()._render_qweb_pdf(report_ref, res_ids=res_ids, data=data)
