### ISSUE TITLE
[BUG] Calendar events are not timezone-aware

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#66754]
Impacted versions: 12-14 at least

Steps to reproduce:

1. Log in as Mitchell Admin.
2. Change TZ to Europe/Lisbon
3. Create an event today at 12:00
4. Invite Marc Demo.
5. Check your calendar. It's at 12:00.
6. Log out.
7. Log in as Marc Demo.
8. Change TZ to Europe/Madrid.
9. Go to your calendar.
10. Event is at 12:00 also, although there's 1 hour of difference among timezones.

Current behavior:

Tested on runbot v14

![screenshot-2021-02-24-12-30-31](https://user-images.githubusercontent.com/973709/109002033-949a1100-769d-11eb-8900-3566157b4bb8.png)

Expected behavior:
![imagen](https://user-images.githubusercontent.com/973709/109002203-cdd28100-769d-11eb-9b73-c9f21f9a7654.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by odony** [comment]
As you know, the timezone used for displaying content on the web UI is the browser's timezone (up until a short time ago, it was impossible to work properly with a different timezone). The timezone set in the user preferences is used on the server-side only, when there is no browser context (e.g. for printing PDFs).

The system tries to keep them in sync when the user logs in for the first time, but if you purposely create a mismatch, you can get such discrepancies (there's a warning sign in the prefs dialog when that happens).

**Comment by Yajo** [comment]
I see, then it makes sense, although it's strange that users can choose their timezones in UI but they're not used in UI. Thanks for the clarification! 😊
