### ISSUE TITLE
[8.0] Workflow activity's Server Action not triggered by wkf signal - only by button

### ISSUE THREAD

**Issue by a0c** [odoo/odoo#6676]
#### Reproduce
- Open Sales Order's workflow.
- In the _route_ activity, set Server Action to a new one that prints PDF of the Sale Order (need to set this action as a Client Action).
- Create a new Sales Order and confirm it.

**Expected:** order printed upon confirmation.
**Actual:** order is not printed, though the Python action (i.e. confirmation process) of the activity is executed just fine.
#### Remarks

Note that if we replace the **workflow signal** with a **button signal** in Sales Order's view, the Server Action will be triggered just fine. Namely, if we change the declaration of "Confirm Sale" button in Sales Order's view from this:

``` xml
<button name="action_button_confirm" states="draft" string="Confirm Sale" type="object" groups="base.group_user"/>
```

to this:

``` xml
<button name="order_confirm" states="draft" string="Confirm Sale" groups="base.group_user"/>
```

the Server Action will be invoked and the PDF will be printed just fine.

**Comment by effelle** [comment]
I can confirm e reproduce the issue. 
Applying the new button name solve the problem but have it working with a workflow will avoid unnecessary inherits. Could someone have a look on it? 
Thanks.

**Comment by Yenthe666** [comment]
Hi @a0c,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
