### ISSUE TITLE
[Odoo failed | Bug confirmed]  RuntimeError: 'maximum recursion depth exceeded while calling a Python object'

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#6677]
Getting bug in server

 Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f5982cbf9b0> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f5983006938> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f5983003de8> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f5982f9b668> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f5983032230> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f598529af50> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f59857305f0> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f598c2db578> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f598c661050> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f59875eaf50> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f598eebe578> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f598ef5c140> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f5970c70cf8> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f59709c6150>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f59709c63d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f5971dd1350>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f5971dd1650>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method Cursor.__del__ of <openerp.sql_db.Cursor object at 0x7f596b661050>> ignored
<string>:2: (WARNING/2) Block quote ends without a blank line; unexpected unindent.
<string>:2: (WARNING/2) Block quote ends without a blank line; unexpected unindent.

Continuous with latest code too.

**Comment by rim-odoo** [comment]
https://github.com/odoo/odoo/wiki/Contributing#reporting-issues
