### ISSUE TITLE
[12.0] web_editor, mass mailing: editor converting all links to underlined links on save

### ISSUE THREAD

**Issue by kig-odoo** [odoo/odoo#66785]
in all mass mailing, template editor converting all links to underlined links on save. I've tested it by sending a real email. Links are underlined in real email too.
see video:

https://user-images.githubusercontent.com/22187704/109048095-ab238500-76fc-11eb-8a37-0ccc0cbeca00.mp4

I've checked technically there is a default user agent style applied by the browser itself. maybe Odoo should normalize that CSS rule to remove those defaults.
![image](https://user-images.githubusercontent.com/22187704/109048539-33098f00-76fd-11eb-8424-9d9e69079af5.png)

**Comment by kig-odoo** [comment]
Hello @rdeodoo 

Can someone from your team take a look at this one?

**Comment by rdeodoo** [comment]
@kig-odoo thank you for the report
Not for now as we have more critical & urgent tasks
Maybe later, or ideally you can provide a fix?
