### ISSUE TITLE
HTML Editor sanitizes links (a-tags) unusable

### ISSUE THREAD

**Issue by rossi256** [odoo/odoo#6678]
& is transformed to &amp for example. complex links are not working anymore and there is no way to make them work.

--> it needs a way to exclude a-tag url from sanitizing, or a way to switch off html sanitizing.

**Comment by Yenthe666** [comment]
Hi @rossi256 ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
