### ISSUE TITLE
the act_window was repeated

### ISSUE THREAD

**Issue by jianjian001** [odoo/odoo#668]
the act_window was repeated，  id = "action_stock_invoice_onshipping", here is th e  address , https://github.com/odoo/odoo/blob/7.0/addons/stock/wizard/stock_invoice_onshipping_view.xml .and i think it's a error.

 &lt;act_window name="Create Draft Invoices"
        res_model="stock.invoice.onshipping"
        src_model="stock.picking.out"
        key2="client_action_multi"
        multi="True"
        view_mode="form"
        view_type="form"
        target="new"
        id="action_stock_invoice_onshipping"/>

 &lt;act_window name="Create Draft Invoices"
        res_model="stock.invoice.onshipping"
        src_model="stock.picking.in"
        key2="client_action_multi"
        multi="True"
        view_mode="form"
        view_type="form"
        target="new"
        id="action_stock_invoice_onshipping"/>

**Comment by Yenthe666** [comment]
Dear @jianjian001,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
