### ISSUE TITLE
Sales Journal entries are not being autoposted even after ticking "Autopost Created Moves" checkbox

### ISSUE THREAD

**Issue by chavu** [odoo/odoo#6680]
I have Odoo POS and Accounting modules setup. When I close the POS session after capturing one item sale of P2.24 incl 12% VAT, the following journal entries are automatically created:

Cash Journal:
Cash Account - Debit 2.24,
Debtors Account - Credit 2.24

Sales Journal:
Debtors Account - Debit 2.24
Sales Account - Credit 2.0
Tax Received. - Credit 0.24

The Cash journal entries are being automatically posted to GL but Sales Journal entries are not being automatically posted to GL. I tried checking the "Autopost Created Moves" checkbox" in the Sales journal form but it is still not working.

**Comment by mrzingo** [comment]
Same issue here

**Comment by Yenthe666** [comment]
Hi @chavu,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
