### ISSUE TITLE
[8.0] Payment Validate button in Point of Sale not available 

### ISSUE THREAD

**Issue by chrisdec** [odoo/odoo#6681]
Hello, 

I noticed a problem in the point of sale, I think it's a rounding problem 

Step to reproduce 
------------------------

1. Go on runbot 

2. Activate technical features for your user (admin)

3. Go to settings > Technical > Database structure > Decimal accuracy 

       Change product price. Digits = 4 

4. Go to settings > Configuration > Accounting 

       Tax calculation rounding method must be "Round Globally"

5. Create a product : 

    name = product 1
    Product price = 3.232
    Customer taxes = VAT-OUT-21-L
    Available in the point of sale 

6. Start a POS session :

    Sell 6 units of product 1

    The total is 23.46 €

    Choose Bank Journal to pay 23.46 €

Current behavior 
----------------------

You can't click on validate to register the payment

The customer paid the exact amount but you can't validate 

If you put 23.47 --> there is a change of 0.01 €

Expected behavior 
-------------------------

If the customer pay the exact amount, you must be able to validate the payment without register a fictive change. 

Thanks a lot for your answer,

**Comment by adrienpeiffer** [comment]
:+1: OPW 639686

**Comment by adrienpeiffer** [comment]
#6682 Seems to fix this issue

**Comment by beledouxdenis** [comment]
Seems related to fc132665d77ec630b45b0aec808b32b6797a57dc.
#6682 doesn't seem to be the appropriate fix, this should be corrected directly at the source: in the `compute_all` method of `model.js`.
https://github.com/odoo/odoo/blob/8.0/addons/point_of_sale/static/src/js/models.js#L860-L909

**Comment by adrienpeiffer** [comment]
Hi Denis,
Thanks for your answer. 
Indeed it's related to fc13266
I let you to propose a better appropriate solution

**Comment by adrienpeiffer** [comment]
Thanks !
