### ISSUE TITLE
Product volume and weight informations should be per product variant

### ISSUE THREAD

**Issue by LeartS** [odoo/odoo#6686]
Think for example for variants for different materials, or different sizes, or different packaging.

**Comment by explanar** [comment]
There's a €15,00 App from Webkul that resolves it: https://www.odoo.com/apps/modules/8.0/product_variant_weight/

I actually try to get comparable functionality based on the Weight-Calculator of OCA Product-Attribute Addon-Set: https://github.com/OCA/product-attribute, especially from "product_weight" - a calculator that uses the total amount of weight by summing all components of all bills of material of the product.

Any experiences out there?

**Comment by Yenthe666** [comment]
Hi @LeartS ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
