### ISSUE TITLE
Email template strings not getting translated

### ISSUE THREAD

**Issue by os-ia** [odoo/odoo#66861]
Impacted versions: 12.0

Steps to reproduce:

1. Enable `Spanish` language and load its translation
2. Set the language of a contact (company) to `Spanish`
2. Create a new quotation with _said company_ as a `Customer`
3. Click `Send by Email`
4. Click `Send`

Current behavior:
There are at least two strings that are not translated in English, "Your" and "Best regards,".

These strings come from the following views which are located in the file `addons/mail/data/mail_data.xml`: 
- `mail_notification_paynow`
- `mail_notification_light`

Expected behavior:
Strings getting translated

Video/Screenshot link (optional):
![Screenshot 2021-02-25 at 15 37 57](https://user-images.githubusercontent.com/75302079/109169140-cdaab200-777f-11eb-8294-151395b59380.png)

---

**Also tested on 14.0 and the strings get translated properly.**
![Screenshot 2021-02-25 at 15 39 00](https://user-images.githubusercontent.com/75302079/109169381-0a76a900-7780-11eb-84f0-25d31efd26a7.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
I'm Spanish and on all my v12s, these parts get translated, so it seems to have something weird on your end.

Please re check your custom module chain and your translations.

If you find a hint that involves a bug, please comment, but meanwhile, I'm closing this.

**Comment by KarstenK77** [comment]
I have exactly the same problem. @os-ia could you find the reason?
