### ISSUE TITLE
Timesheet_analysis report not showing tasks's timesheet

### ISSUE THREAD

**Issue by samuellefever** [odoo/odoo#6689]
Impacted versions:

8.0
Steps to reproduce:

Create several work log entries on tasks
In Reporting -> Human Resources -> Timesheet Analysis
No lines are displayed

Expected behavior:

Have results following the time encoded on tasks

**Comment by Yenthe666** [comment]
Hi @samuellefever,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by samuellefever** [comment]
Thank you for your response 2 years and a half later.
Fortunately, we do not have the problem in the next versions!
