### ISSUE TITLE
Advanced search on cost price does not work

### ISSUE THREAD

**Issue by samuellefever** [odoo/odoo#6690]
Impacted versions:

8.0

Steps to reproduce:

Create a product with a cost price = 0
Go in product and make an advanced search on the cost price (is equal to 0,0)
No product shows up

Expected behavior:

All the products with the cost price = 0 should be shown

**Comment by beledouxdenis** [comment]
This issue is solved in Odoo 8.0 from the below revision:
6e063188282e3594178c9ae367fa939ea890c9f9

Regards,
