### ISSUE TITLE
[WISHLIST] Pivot tables to show percentages

### ISSUE THREAD

**Issue by alejandrosantana** [odoo/odoo#6692]
Right now (SaaS-6 in runbot) pivot tables show values only as **amounts** (30, 55, 6000, etc.), but it is requested by some customers interested in Business Intelligence to show values as **percentages**, as it gives a much better perspective for many managers than a cold amount.

So maybe pivot tables could have 2 modes: "amount" and "percentage".
That way, "amount" mode would work as it does now.
In the other hand, in "percentage" mode, for a given "TOTAL" (that could be expressed as an amount, to give the right context for percentages), each line should be expressed of a percentage of such total.

@odony @antonylesuisse What do you think? I think that would be a big leap for pivot tables power and make them absolutely essential for managers.

The image shows a screen capture of current (SaaS-6) pivot table behaviour.
![pivot_not_percentage](https://cloud.githubusercontent.com/assets/3707483/7614780/578b5fc6-f999-11e4-8409-b84bde56b64d.png)

**Comment by adriencombourieu** [comment]
I agree completely !
Any news on that topic since 2015 ?

**Comment by pedrobaeza** [comment]
This has been discussed in other issues, and some moves have been done lately (like the aggregations in `read_group` method). I'm preparing an RFC for improving this, so I'm closing this issue for not having several ones about the same topic.

**Comment by darshan-odoo** [comment]
Was this feature achieved?

if yes could you please let me if there's a way to get a percentage on the Pivot, thanks.
