### ISSUE TITLE
ESCPOS printer workaround

### ISSUE THREAD

**Issue by danny-therp** [odoo/odoo#66941]
Impacted versions: 12.0

Currently, the point of sale module talks to the iotbox, and the iotbox uses the hw_escpos module to talk to the escpos printer.
After a command to open the cash drawer is sent to the usb port, a command to read its printer status is sent as well. This has no other use than to be a workaround for some printers. See the following comment:
```
        """ Send pulse to kick the cash drawer

        For some reason, with some printers (ex: Epson TM-m30), the cash drawer
        only opens 50% of the time if you just send the pulse. But if you read
        the status afterwards, it opens all the time.
        """
```
However, we stumbled upon a escpos printer that doesn't behave quite well either, in its own way. Our printer (a Sam4s ELLIX30iiis) actually breaks down and becomes unusable when you attempt to read its printer status.

We've made a patch that skips the workaround (status read) for Sam4s printers. Is this worth making a PR for?

**Comment by pedrobaeza** [comment]
Is there a way to keep both behaviors?

**Comment by danny-therp** [comment]
Yes, I should have clarified.

The patch I made for myself skips the workaround conditionally. It checks the vendor id and sees if it is a Sam4s printer.

**Comment by pedrobaeza** [comment]
You can propose a PR about that then to Odoo.

**Comment by danny-therp** [comment]
See PR.
