### ISSUE TITLE
Changing Manufacturing order date does not affect to work orders and viceversa

### ISSUE THREAD

**Issue by anajuaristi** [odoo/odoo#6694]
Hi:

To reproduce the case:
.- Go to manufacturing orders menu entry
.- Take one demo manufacturing order having related work orders
.- Go to calendar view
.- Change the manufacturing order date
.- go to workorders view --> you can see all workorders are staying on same planned date than before.

On the other side, changing operations planned dates does not affect to their MO planned date.   

This is causing extrange behaviors on gantt views 
.- moving MO on gantt view shows order on correct data, but MO is not correctly shown on workorders gantt view (it seems it's calculating MO dates on the fly depending on workorders but that's not true at all.

I think this issues with MO - Workorders dates makes almost impossible to correctly plan tools.

If you are interested, we could try to provide a fix for this issue asap.
Thank you:
Ana

**Comment by nim-odoo** [comment]
Hello,

I think that the trigger should be done in only one direction: when the date_planned of the manufacturing order is changed, the date_planned of the related work orders are computed accordingly.

I also think that the issue #6710 is not directly linked to this issue.

Regards,
Nicolas

**Comment by anajuaristi** [comment]
But... if you change the start date of first WO it should also affect to MO. It's not only one side but both sides. Otherwise you will create inconsistencies.

**Comment by anajuaristi** [comment]
About this issue being related to #6710... i think they are directly related since if dates from MO-WO are correctly set, gantt view will be also correct.

**Comment by nim-odoo** [comment]
@jco-odoo : What is your opinion about it?

**Comment by jco-odoo** [comment]
I am not too familiar with this.  Is not it possible that someone wants to plan the work orders differently than fixed through the manufacturing order?  If the manufacturing order does what the work orders do and vice versa, what is the difference with putting related fields?

**Comment by anajuaristi** [comment]
One MO includes N WO
That is, the first WO planned data should be the same to MO planned data. 
On the other side if one WO is moved to be the first one, the MO should also be moved.

At the end, the last WO end data would be the MO planned data.
 
It's like project and tasks. You can not start a project after starting the first task and you can not end the project after the end of the last task

That's all. 
Whising it helps:
Ana

**Comment by anajuaristi** [comment]
Thank you for the fix. We will test and come back to you.

**Comment by anajuaristi** [comment]
Solved. 
Thank you

**Comment by hippe-67** [comment]
Is this fixed to Odoo 11?

**Comment by Yenthe666** [comment]
@hippe-67 yes, at https://github.com/odoo/odoo/commit/9c6ae3cf6c3772fcfd2127022cacc8f3233fea0a

**Comment by hippe-67** [comment]
Is this really on Odoo11e ???
I't seems to be old OpenErp.
Anyway, I did not succeed in installing it (Odoo 11e)

**Comment by Yenthe666** [comment]
@hippe-67 well it has been originally fixed in 7.0 at https://github.com/odoo/odoo/pull/6768 but this should always be forward ported.
If you really believe the issue is back and if you can reproduce it on an official runbot instance (runbot.odoo.com) then you can create a new bug report.

Regards,
Yenthe
