### ISSUE TITLE
[8.0] View Editor (in debug mode) doesn't allow to add items to a view

### ISSUE THREAD

**Issue by a0c** [odoo/odoo#6695]
#### Reproduce
- enable debug mode
- goto e.g. Sale Order, Form view
- from Debug View, select Manage Views > Edit
- select some button element > hit '+' button > select e.g. button > hit 'Update'

**Expected:** buttton is added
**Actual:** `Can't Update View` error (regardless of the element being added)
#### Remarks

Looks like `properties` should be used directly instead of `_CHILDREN[properties[0]]` or something like that. Don't have time to investigate this right now.

**Comment by Yenthe666** [comment]
Hi @a0c,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
