### ISSUE TITLE
Odoo Docker/Kubernetes multi-replica support ? 

### ISSUE THREAD

**Issue by jCOTINEAU** [odoo/odoo#66969]
Hello everyone,

Do you know if it is safe to deploy multiple replicas of odoo, with the same database connection and a share filestore volume ?

I am going to test is and post the result right here if i have some times, but i'd like to have some advice.

Thanks everyone have a nice day

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
