### ISSUE TITLE
8.0: you should not be able to cancel an account move of a closed fiscal year

### ISSUE THREAD

**Issue by alexis-via** [odoo/odoo#6696]
Here is the scenario to reproduce the bug on an up-to-date Odoo v8 from github/odoo:
1. Create a new DB with demo data
2. Install the module "account_cancel"
3. In Accounting > Journal > Journal, edit the journal "Sales Journal - (test)" and check the option "Allow cancelling entries"
4. Go to Accounting > Periodical Processing > Draft Entries > Post Journal Entries : in the wizard, select all the journals and all the periods of 2015 and click on the "Approve" button.
5. Go to Accounting > Periodical Processing > End of Period > Close a fiscal year : select the fiscal year "Fiscal Year X 2015" and click on "Close Fiscal Year"
6. Go to Accounting > Customers > Customer Invoice : select a customer invoice in "Open" state that is linked to a period in 2015 and linked to the journal "Sales Journal - (test)". Go to the "Other Info" tab and click on the Journal Entry. On the form view of this journal entry, click on the "Cancel Entry" button : it works ! That's the bug ! The account.move is now in "Unposted" state ! If you click on the "Post" button, you get can error message "You can not add/modify entries in a closed period X 05/2015 of journal Sales Journal - (test)." (which is normal).

I think that this bug is very serious because it means that you can modify account.move that belong to a closed fiscal year.

**Comment by agb80** [comment]
I have checked the code of the same function on v7.0 and is exactly the same so I suspect that the same bug will be found on v7.0, @alexis-via would you mind backport your fix to v7.0 branch?

**Comment by sbidoul** [comment]
:+1:

**Comment by alexis-via** [comment]
I made a new test today on runbot v8, and I am still able to cancel an account move in a closed fiscal year. The scenario is still valid with a small modification:
on step 6: Go to Accounting > Journal Entries > Journal Entries, select an account move attached to the Sale Journal (test) (or any journal that allows cancelling entries) and click on the button "Cancel Entry".

@qdp-odoo I think this bug is really important. I've hit it again today with Akretion's Odoo v8, where I cancelled an account.move of a closed fiscal year (I didn't see that it was in a closed fiscal year) and then I cannot post it back because I get en error message saying that the period is closed (this error is "good" of course)... so it's really annoying.

**Comment by feketemihai** [comment]
@alexis-via @qdp-odoo It's the same in a opened fiscalyear and closed period, you can cancel the move and can't repost it...

**Comment by Yenthe666** [comment]
Hi @alexis-via ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
