### ISSUE TITLE
Product.CustomerLeadTime is not used to calculate date_planned

### ISSUE THREAD

**Issue by odoochina-dev** [odoo/odoo#66970]
Odoo user doc: https://www.odoo.com/documentation/user/14.0/inventory/management/planning/scheduled_dates.html
> The Customer Lead Time **is the time needed for your product to go from your warehouse to the customer place.** It can be configured on any product by going to Sales ‣ Products ‣ Products. 

but currently this configure value is not used to calcuate the planned delivery date:

https://github.com/odoo/odoo/blob/14.0/addons/sale_stock/models/sale_order.py
```
def _prepare_procurement_values(self, group_id=False):
    ...
    date_planned = date_deadline - timedelta(days=self.order_id.company_id.security_lead)
    # this line shall change to ?
    date_planned = date_deadline - timedelta(days=self.order_id.company_id.security_lead) - timedelta(days=self.customer_lead or 0.0)
```

**Impacted versions:**
14.0

**Steps to reproduce:**
1.set customer lead time of product A == 2days in Sales ‣ Products ‣ Products. 
2.create a sale order of product A, which delivery date is set as (e.g. 2021.March.30)

**Current behavior:**
The delivery ticket of this SO is set as planned at 2021.March.30

**Expected behavior:**
The delivery ticket of this SO is set as planned at 2021.March.28
> According to above mentioned user docu, since we set "the time needed for your product to go from your warehouse to the customer place." == 2 days, and we set the commitment_date == 2021.March.30., thus 'delivery ticket' should be planned 2 days eariler than commitment_date (thus should be 2021.March.28).
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
In the line above, `customer_lead` is used when you don't fix a commitment date, so everything is correct according expected behavior.

https://github.com/odoo/odoo/blob/a8cb6a6a43b892ad8d93ae50cf011922037697be/addons/sale_stock/models/sale_order.py#L500

Closing thus.
