### ISSUE TITLE
[12.0] Image not show in qweb report 

### ISSUE THREAD

**Issue by akhmadali22** [odoo/odoo#66976]
#Impacted versions:
odoo12 with docker

Steps to reproduce:
I would like insert image from static file
`<img src="/my_module/static/img/img.png" width="100%" height="100%"/>`

Current behavior:
Image not show

Video/Screenshot link (optional):
![1](https://user-images.githubusercontent.com/51687742/109448606-f3ce9b80-7a78-11eb-9e5a-2310039aecba.PNG)

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a development question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
