### ISSUE TITLE
Customer cannot access his course in eLearning, two users with same email

### ISSUE THREAD

**Issue by marcosmonauta** [odoo/odoo#66972]
Impacted versions: CE v14

Problem: 
When a customer of a eLearning course signs up before buying the course, you got a problem, the customer cannot access his course after paying.

Steps to reproduce:
1. Sign up as a customer , for example  John1  john@gmail.com
2. Sing out
3. Buy a course and in the proccess introduce any name and SAME email , for example John2  john@gmail.com . DO NOT log in when buying the course when odoo asks for customer's data. Odoo creates a second user with same email (here comes the problem)
4. After buying when you want to login from the purchase page, and create a password Odoo says that that email already exist.
5. Go to home, log in with john@gmail.com (password used when creating John1). You can log in but you dont have access to your course.

Current behavior:
Customer signs up, and logs in with his email,  but he cannot see his course

Solution:
MANUALLY change email of John1, remove his access to the portal and grant access to John2 (after getting emails of a frustrated customer). Mind that this is a online course and the purchasing process should run smooth with instant access to the course after paying.

¿ANYONE KNOWS ANY STANDARD SOLUTION FOR THIS PROBLEM? IT IS A BIG PROBLEM FOR A E-LEARNING SOLUTION

Thank you for your help

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/75961027/109402396-3712f800-791b-11eb-88fb-7a4090bba7d1.png)

SORRY ABOUT THE LANGUAGE , I HAVE INSTALLED ONLY SPANISH. THE MESSAGE SAYS:
You have serveral users with same email

To solve it you can:
- change emails of the users
- Grant access only to users with unique email
- change internatl users to portal manually

![image](https://user-images.githubusercontent.com/75961027/109402426-632e7900-791b-11eb-956e-322af524f324.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
You should merge contacts instead of trying to create a new portal access.

As there's a way to manage this, I close this report.

**Comment by marcosmonauta** [comment]
Hi Pedro,

how can I merge the contacts?

**Comment by pedrobaeza** [comment]
A quick search reveals it: https://www.youtube.com/watch?v=wZURmCBWz20
