### ISSUE TITLE
No warning when inputting too much data in a limited char field

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#6698]
Create a module with:

_./models.py_:

```
from openerp import models, fields
class Partner(models.Model):
    _inherit = "res.partner"
    short_field = fields.Char(size=5)
```

_./tests/test_module.py_:

```
from openerp.tests.common import TransactionCase
class LengthCase(TransactionCase):
    def test_1(self):
        partner = self.env["res.partner"].create({
            "name": "test"})
        self.assertRaises(Exception):
            partner.short_field = "123456"
```

The test will fail. `short_field` will become "12345" without any kind of warning.

The ORM should fail (or at least warn) instead of just truncating input.

**Comment by Yenthe666** [comment]
Hi @Yajo,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
