### ISSUE TITLE
[14.0] Widget forcast availability

### ISSUE THREAD

**Issue by quinten-accomodata** [odoo/odoo#67003]
Impacted versions: 14 (widget forecast_availability)

**Steps to reproduce:**
1) Set "Product Unit of Measure" to 3
2) Create a BoM with 1 product (new product without stock) e.g. you need 0,3 to create 1Kg
3) Add BoM to a product
4) Create a production order for the product with this BoM just created
5) You now see that the product is available which is not

**Current behavior:**
In "stock/static/src/js/forecast_widget.js" at line 34
`data.will_be_fulfilled = utils.round_decimals(data.forecast_availability, this.record.fields.forecast_availability.digits[1]) >= utils.round_decimals(data.product_qty, this.record.fields.product_qty.digits[1]);`

it is using product_qty which is by default 0, this should be set to "Product Unit of Measure"
See "stock/models/stock_move.py" line 55

**Fix :**
replace _digits=0_ with _digits="Product Unit of Measure"_

**Expected behavior:**
The widget should show not available instead of available because it is rounding to the down side.

**Video/Screenshot link (optional):**

Support ticket number submitted via odoo.com/help (optional):
#2472301

**Comment by ryv-odoo** [comment]
It should be fixed in odoo/odoo#67067 . Note that we can't put `digits="Product Unit of Measure"` on the product_qty fields because we need all possible decimal.
