### ISSUE TITLE
creating a email template for custom module

### ISSUE THREAD

**Issue by grantern** [odoo/odoo#6702]
Create a custom email template like this:

```
                    <record id="email_template_super_sale" model="email.template">
                        <field name="name">Super Sales Order - Send by Email</field>
                        <field name="email_from">${(object.user_id.email or '')|safe}</field>
                        <field name="subject">Quote from ${object.company_id.name}</field>
                        <field name="partner_to">${object.partner_invoice_id.id}</field>
                        <field name="model_id" ref="elmatica_super_sales_order.model_super_sales_order"/>
```

When creating the template Odoo connects the template to the wrong model:
![email_template_wrong_model](https://cloud.githubusercontent.com/assets/9212406/7629404/8048706e-fa2c-11e4-9f9b-b1d186513afa.png)

The <field name="model_id" ref="elmatica_super_sales_order.model_super_sales_order"/>
does a complete wrong lookup. I've seen this in two different databases now. One after updating the code with this new email template and one clean install.

**Comment by lukebranch** [comment]
@grantern ,

I've run into what I think is a similar/related issue described in this forum post:

https://www.odoo.com/forum/help-1/question/sending-by-email-invoice-generated-with-aeroo-83358#answer-84428

**Comment by Yenthe666** [comment]
Hi @grantern ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
