### ISSUE TITLE
Update from nightly results in multiple tracebacks

### ISSUE THREAD

**Issue by moongoggles** [odoo/odoo#67027]
Today I updated my system to 14.0.20210301 from 14.0.20210110.  Prior to this, everything was behaving normally.  But now, I get tracebacks on almost everything I try to do.  Here is one from clicking on the MRP module:

Error:

Traceback:
Error: this.constructor.subTemplates[7] is undefined
anonymous@https://erp.ad.bridgerphotonics.com/web/content/1197-b084f22/web.assets_common.js line 970 > Function:396:13
fn@https://erp.ad.bridgerphotonics.com/web/content/1197-b084f22/web.assets_common.js:952:173
render@https://erp.ad.bridgerphotonics.com/web/content/1197-b084f22/web.assets_common.js:959:20
useModel/__owl__.renderFn@https://erp.ad.bridgerphotonics.com/web/content/1198-b7f656e/web.assets_backend.js:1325:147
__render@https://erp.ad.bridgerphotonics.com/web/content/1197-b084f22/web.assets_common.js:1278:33
__prepareAndRender@https://erp.ad.bridgerphotonics.com/web/content/1197-b084f22/web.assets_common.js:1276:29

All of the other tracebacks I get have that bottom line in common:   ...../1197-b084f22/web.assets_common.js:1276:29

Starting a new database works fine so I'm sure it's something in my database.  Maybe this isn't enough info but can someone point me in the right direction?

Thanks!

**Comment by pedrobaeza** [comment]
I'm afraid this doesn't qualify as an Odoo issue. Try to upgrade your modules in the existing DB, and if not, you can ask for help in the Odoo forums.

Closing thus.
