### ISSUE TITLE
No journal found in company xxxxx for any of these types: general

### ISSUE THREAD

**Issue by PDMeira** [odoo/odoo#67037]
Impacted versions:
14

Steps to reproduce:
Try to install any odoo application from apps menu.

Current behavior:
we cannot install anything else from apps menu.We have a popup window with No journal found in company xxxxx for any of these types: general

Expected behavior:
Install invoice, sales, account (as an option) normaly

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
This seems a problem in your deployment, as this is not happening on normal. Please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/14.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).

**Comment by PDMeira** [comment]
Hi Pedro, everything was working smoothly for a few weeks. I am not sure, so I cannot confirm that, but this problem could be visible after account module om_account_accountant 14.0.3.8.0 installation. We remove that module, now we cannot install anything. We have CRM and employees data on the database. By any chance, is there a way of manually install invoicing, or sales? Can I manually import/setup that journal (general)?

thanks in advance

**Comment by pedrobaeza** [comment]
As you are talking about an enterprise module, please go to odoo.com/help and give the details there, so support team can check about that part.
