### ISSUE TITLE
[8.0] mass mailing UTF-8 encoding

### ISSUE THREAD

**Issue by djulien19** [odoo/odoo#6706]
Hi,
When I send an email with the group email address, some of followers receive a message with a specific encoding.
For example the title of the message from the original version
Offre : Prévention pour reconnaître votre addictologie avec Mélika
became
Fw: Re: Offre : =?utf-8?Q?Pr=C3=A9vention_?=pour =?utf-8?Q?reconna=C3=AEtre_?=votre addictologie avecMélika
I do not know if there is any setttings in Odoo for that or if it is a real bug.
Thanks for your understanding,
Julien

**Comment by burton1982** [comment]
Hello!

I have the same problem. The encoding is working fine in the text field, but subject and TO Field are messed up. You will find a piture in the attachment:
Thanks
![encoding](https://cloud.githubusercontent.com/assets/5064384/8881445/25cd22aa-3240-11e5-95fd-dd541b5ea4f7.png)

**Comment by burton1982** [comment]
okay. I found my issue. In the template I forgot to put "|safe" into the placeholder. The correct syntax for me was:  ${object.email_from|safe}  

I hope this help someone.

**Comment by djulien19** [comment]
Still not working though for me... Does anyone know how to change the format for any outcome email from the groups?

**Comment by Yenthe666** [comment]
Hi @djulien19,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
