### ISSUE TITLE
Mailing list: option to choose who to answer

### ISSUE THREAD

**Issue by djulien19** [odoo/odoo#6707]
Hi again,
There is another issue in the group message that could be resolved in the settings I'm pretty sure.
I would like when sby answer to a message that it will be receive only by the sender and not all the followers of the mailing-list.
Thanks for your help,
Julien

**Comment by Yenthe666** [comment]
Hi @djulien19,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
