### ISSUE TITLE
UOM field missing in order lines form

### ISSUE THREAD

**Issue by maxhome1** [odoo/odoo#6708]
When i create an order line in purchase of a product that miss in Werehouse i have the error:
The following fields are invalid: Product unit of measure.
The fields UOM missing in this view

**Comment by gautampai17** [comment]
I am facing the same issue..??

**Comment by Yenthe666** [comment]
Hi @maxhome1,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
