### ISSUE TITLE
[13.0] Payment Reference set to Customer Reference instead of Invoice Number

### ISSUE THREAD

**Issue by CRogos** [odoo/odoo#67098]
Impacted versions:
Odoo.sh 13.0 - starting on 25.02.2021
Reverting this commit fixes the behavior:
https://github.com/odoo/odoo/commit/7a7dc212af7279544cffba362bce7daa4fc00865
 
Steps to reproduce:
Create a invoice draft from sales order.

Current behavior:
The "Payment Reference" is set to the customer "Reference" instead of left empty. Therefor it will not be replaced with the invoice number.

Expected behavior:
Payment Reference in draft stage should be empty and will be updated on post with the invoice number.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/1799080/109679517-f1089f00-7b7b-11eb-8562-6e509e023c4d.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
@smetl can you please take a look to this? We have gone in and out with this problem. Maybe the problem is that your fix is intended for vendor bills, but it's affecting also customer invoices.

**Comment by smetl** [comment]
@pedrobaeza We are reverting the problematic commit

**Comment by pedrobaeza** [comment]
Thanks!

**Comment by smetl** [comment]
Revert done by https://github.com/odoo/odoo/pull/67169
Forwart-port in progress
