### ISSUE TITLE
[saas6] Product Description not saved for all products

### ISSUE THREAD

**Issue by rba-odoo** [odoo/odoo#6712]
Product Description not saved for all products on quote template

Affected Version:
Saas6 and master

Steps to reproduce:
- Go to Sale > Configuration > Sales > Quotation Templates 
- Create new template, add new products 
- click on edit template 
- now, add all products description(suppose add snippet to each product) and save 
- you can see product description not saved for all products
  Bug video: http://youtu.be/F3c-W5aEFyU

**Comment by Yenthe666** [comment]
Hi @rba-odoo,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
