### ISSUE TITLE
[11.0] Stripe payment, Deutsche Bank Card issue

### ISSUE THREAD

**Issue by filipocc** [odoo/odoo#67125]
Impacted versions: 11.0

Steps to reproduce: Add to cart some products. Perform checkout payment on last step, by using Deutsche Bank card with 3D Secure.

Current behavior: Confirm Payment pop-up -> displays amount to pay = 0.00 €

Expected behavior: Confirm pop-up displays the correct amount to pay

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/15066476/109765406-171e5580-7bf5-11eb-8bf5-99d1216d8ad4.png)

Support ticket number submitted via odoo.com/help (optional):

PD: I've just check the logs and after the stripe payment intent, I've seen this, but i'm not sure if it is related to the issue:
![image](https://user-images.githubusercontent.com/15066476/109766451-79c42100-7bf6-11eb-8963-89be3e5144c8.png)

**Comment by Yenthe666** [comment]
Sorry but Odoo V11 is no longer officially supported.
