### ISSUE TITLE
It's not just a man's world

### ISSUE THREAD

**Issue by geoff-bbc** [odoo/odoo#67124]
![image](https://user-images.githubusercontent.com/59264352/109741508-0f719900-7b82-11eb-83ce-a00915585adb.png)
The alert that pops up after a new user logs in for the first time assumes the user is a "he". I think we can do better in this day and age. 😉 

Suggested: This is their first connection. Wish them welcome.

**Comment by Yenthe666** [comment]
Well, we have no field that says which gender a person is so we can't 'sense' it. At best it could be "Wish him/her" welcome but that feels so robot-ish ahah.
@pedrobaeza your thoughts? I'd say feel free to make a PR but I think we have more important issues in the world :)

**Comment by gdgellatly** [comment]
@Yenthe666 Actually I think this is quite an important issue. 

It is not too hard to resolve. In Pseudocode.

Title: %s just connected for the first time.
Message: Wish %s.split[0] welcome.

Sure it's not perfect but a lot better than what there is. Odoo should really be resolving this one.
Then fix up all the translations.

**Comment by Yenthe666** [comment]
Well, probably not accepted in any stable version anyways. :) 
I'll leave the final call for @mart-e

**Comment by mart-e** [comment]
Hi there,

I agree, we can do better than that. Using a singular they is a good way for a more neutral form.
@geoff-bbc do you wish to make a PR (against master) to make the change you suggested?

**Comment by NL66278** [comment]
Their and them is not logical if a known person connects for the first time. Completely ungrammatical to use a plural to refer to a single person. What about: `Jane Smith connected for the first time. Wish the new user welcome!` ?

**Comment by mart-e** [comment]
@NL66278 you suggestion is valid but we are referring to "singular they" which is grammaticaly correct
https://en.wikipedia.org/wiki/Singular_they

**Comment by NL66278** [comment]
@mart-e Thanks for the link. I stand corrected for English. I must still say that avoiding a pronoun will still make for easier translation to languages (like Dutch) that do not have such a neutral form.

**Comment by geoff-bbc** [comment]
@mart-e I'm new at this. Hopefully https://github.com/odoo/odoo/pull/69275 lives up to guidelines.

**Comment by geoff-bbc** [comment]
@mart-e - regarding your comment in the PR:
> On the phrase itself, I agree with @NL66278 rephrase to add the name of the person directly in the message may make it a bit easier for the users.

Notice in the screenshot that I included at the top here that the user's name is featured in the subject of the alert. I think it would be redundant to use it again, agree? If agreed then I will submit a new PR according to your recommendations.

**Comment by mart-e** [comment]
Actually it was already fixed at #64023

**Comment by geoff-bbc** [comment]
Thanks for your help on this @mart-e. Merci.
