### ISSUE TITLE
crm_helpdesk write with not existing field

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#6717]
There seems a bug in a write method for `crm.helpdesk` (in crm_helpdesk) module.

When I write something in helpdesk record, in log I get such warning:

`
2015-05-15 06:33:32,452 3633 WARNING db_name openerp.models: crm.helpdesk.write() with unknown fields: date_open`

Looking at described fields in `/addons/crm_helpdesk/crm_helpdesk.py`: there is no such field `date_open`. And looking in write method:

``` python
    def write(self, cr, uid, ids, values, context=None):
        """ Override to add case management: open/close dates """
        if values.get('state'):
            if values.get('state') in ['draft', 'open'] and not values.get('date_open'):
                values['date_open'] = fields.datetime.now()
            elif values.get('state') == 'close' and not values.get('date_closed'):
                values['date_closed'] = fields.datetime.now()
        return super(crm_helpdesk, self).write(cr, uid, ids, values, context=context)
```

As you can see it tries to write to field that does not exist.

**Comment by Yenthe666** [comment]
Hi @oerp-odoo,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
