### ISSUE TITLE
[APM] Install AppDynamics Python Agent

### ISSUE THREAD

**Issue by khalidrehan** [odoo/odoo#67214]
**Impacted versions:** Odoo ver. 9

**Steps to reproduce:** https://docs.appdynamics.com/display/PRO21/Install+the+Python+Agent
We are trying to use AppDynamics to monitor the Application Performance.

**Current Status:** Can't proceed

# Steps from the Controller:

1. Install the appdynamics agent: `# pip install appdynamics `
2. Choose the "Deployment Method": Do we consider Odoo as a Python application?
![image](https://user-images.githubusercontent.com/37035465/109954108-f4be3200-7cf1-11eb-9101-d2e9c27caed3.png)

3. We can't proceed step 2, we need to know what is the suitable input.

Regards,
Khalid.

**Comment by Yenthe666** [comment]
Hi,

Sorry but the issue tracker is only for issues in V12-V14. V9 is no longer supported.
Besides of this this is a question and not a bug so please ask it on the official help forums at help.odoo.com.

Regards,
Yenthe

**Comment by khalidrehan** [comment]
> Hi,
> 
> Sorry but the issue tracker is only for issues in V12-V14. V9 is no longer supported.
> Besides of this this is a question and not a bug so please ask it on the official help forums at help.odoo.com.
> 
> Regards,
> Yenthe

I can't open a support ticket help.odoo.com

**Comment by Yenthe666** [comment]
Why not? But anyways it is V9 so there is no support for this version anymore anyways.

**Comment by khalidrehan** [comment]
> Why not? But anyways it is V9 so there is no support for this version anymore anyways.

![image](https://user-images.githubusercontent.com/37035465/109992796-ad00d000-7d1c-11eb-922a-25663eea7179.png)
