### ISSUE TITLE
[13.0] Member:  Indexing personal data in search engines

### ISSUE THREAD

**Issue by fcvalgar** [odoo/odoo#67224]
Impacted versions: V13

Steps to reproduce: AEOdoo (Asociación Española de Odoo) uses the members module to manage its associates. One of the functionalities of this module is the publication of the partner's data on the website. 

Current behavior: This functionality creates a url with the partner's file and indexes the page in search engines. If that partner page is unpublished, the module removes the url but continues to allow the data in search results. If 
If the partner is a person, and without the consent of the interested party constitutes a breach of the RGPD.

Expected behavior: No index in the html of website partner page

Video/Screenshot link (optional): https://i.gyazo.com/5a281ff35df6a4fad61471c8d2d38f60.png

Support ticket number submitted via odoo.com/help (optional):

**Comment by rafaelbn** [comment]
Hello @odony could you give an opinion here please?

As said the concern it that eventthough the contact is "unpublished" the URL of the contact get indexed in Google...

Thanks

cc @OCA/data-protection-maintainers

**Comment by rafaelbn** [comment]
Hello @odony  could you give an opinion here please?

As said the concern it that eventthough the contact is "unpublished" the URL of the contact get indexed in Google...

Thanks

Ping @data-protection-maintainers

**Comment by odony** [comment]
Could you be a bit more specific?

From what I can see once a member is unpublished their data is not visible anymore, and the old URL simply returns the member list, as does any URL that starts with `/members/` and does not match anything.

The member URLs are not included in the `sitemap.xml` at all, so at that point it's just an old link that will be removed eventually from the index, as it's not referenced anymore anywhere. It would probably make sense to return a 404 instead, but that does not guarantee that the search engine will be updating its caches. In general the solution if you want the fastest deindexing is to request it directly to the search engine using the appropriate method (e.g. for Google, [the webmaster tools](https://support.google.com/webmasters/answer/9689846)). Odoo can't do that for you.

If you'd like to have Odoo return a 404 instead of the generic member list, feel free to make a PR, but that's a matter a taste, and won't really fix your problem, as far as I can tell.

**Comment by Yenthe666** [comment]
Plus the screenshot shows a signed in user with enough rights to see unpublished pages too.

**Comment by fcvalgar** [comment]
I can't show the screenshot because it contains personal information.

The person did a google search for his name and city. The search returned the search list with its data in the meta description.

https://gyazo.com/dd392626188da1408299aee0e3066a47

Our sitemap contains <loc> https://www.aeodoo.org/members </loc>

For example, if I google "Landoo AEOdoo", the search engine returns the information from the screenshot.

https://gyazo.com/0c3fe3322c6b8323fd45796fca94bcaf

This url https://www.aeodoo.org/members/landoo-s-l-245 that It contains a block of text but if it is empty, google 
show us contact details.

We have requested in Search console the elimination of the indexing of the url.

What is expected is not that the search engine does not index members because it is necessary. What should be done to add a noindex and nofollow to the tag of an unpublished member.

Thak you so much

**Comment by odony** [comment]
> What should be done to add a noindex and nofollow to the tag of an unpublished member.

That makes no sense, as that would mean the link is still generated?

Don't be confused by what you see on `/members` when you are connected as an admin. You have to test it in private browsing/incognito mode to get the same result as googlebot. Then you will see that the link is not included on /members anymore after you unpublish it. At that point it only exists in the google index, and as soon as you request the elimination, it will be gone forever.

**Comment by fcvalgar** [comment]
Then If you are an Odoo user, and you dont know GSC, you will violate the RGPD.

**Comment by rafaelbn** [comment]
I have created a real case in produccion to check if google index it

- https://www.aeodoo.org/members/personal-data-example-for-issue-67224-1456
- https://www.aeodoo.org/partners/personal-data-example-for-issue-67224-1456

Regards

**Comment by odony** [comment]
> Then If you are an Odoo user, and you dont know GSC, you will violate the RGPD.

Well, there are only 2 possible ways for your to take down cached results from Google indexes:

1. Take it offline from your website, and wait for Google to remove it from its cache automatically.
2. Take it offline from your website, and use the GSC to speed up removal from the cache.

Both techniques have the same result, the second one is just a bit faster. So it's hard to say that opting for option 1 would be a violation of GDPR, even if you're aware of option 2.

Also, it should also be obvious that Google is not the only crawler with a cache, and you can't be expected to contact them all (there are hundreds of them). You probably can't even identify them all technically, even from your web server logs.

So it's up to you to decide how much resources you are going to dedicate for this. But Article 17.2 of GDPR clearly states that you only have to take reasonable steps, taking into account the technology and cost:

_17.2 Where the controller has made the personal data public and is obliged pursuant to paragraph 1 to erase the personal data, the controller, taking account of available technology and the cost of implementation, shall take reasonable steps, including technical measures, to inform controllers which are processing the personal data that the data subject has requested the erasure by such controllers of any links to, or copy or replication of, those personal data._

**Comment by fcvalgar** [comment]
That's right. But it is the control authority that will have to decide whether it was within your operational possibilities since it is a widely interpretable and nuanced article in territorial legislation.
We for our part comply 100% with the protocols and obligations. For this reason, we have opened a security breach by reporting the incident to the control authority (www.aepd.es) (art 33 and 34 of the GDPR), indicating all the relative information and notification of this issue.
