### ISSUE TITLE
Set Income and Expense Account in Product.Template with default value. 

### ISSUE THREAD

**Issue by ekitsikpui5** [odoo/odoo#6727]
I have  about 9000 products in my Odoo, I want to write a sql statement to set the property_income_account with id 1147. 

Can someone please help. Thank you.

**Comment by Yenthe666** [comment]
Hi @ekitsikpui5,

Please ask these kind of questions on the official help forum (odoo.com/help).
The Github tracker is only for bugs in the official code, not for questions.

Regards,
Yenthe
