### ISSUE TITLE
[8.0] Disable English language - No more prices shown on Website shop

### ISSUE THREAD

**Issue by vilder** [odoo/odoo#6728]
![decimal-separator](https://cloud.githubusercontent.com/assets/7828591/7650910/6d3b2ea6-fafb-11e4-8698-ac13483f4cab.gif)

**Comment by Yenthe666** [comment]
Hi @vilder ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
