### ISSUE TITLE
[14.0] website_sale: Redirect to Cart page after add a product to cart

### ISSUE THREAD

**Issue by tanghulu0608** [odoo/odoo#67301]
Impacted versions:
14.0, maybe all

Steps to reproduce:

1. Add a product to cart
<img width="1457" alt="image" src="https://user-images.githubusercontent.com/5561864/110057335-643c2c00-7d9b-11eb-801d-c57cbee31bb3.png">

2. Odoo redirect to cart page
<img width="1539" alt="image" src="https://user-images.githubusercontent.com/5561864/110057400-80d86400-7d9b-11eb-94a6-89018bae1f5f.png">

3. If the customer want to add other products, they need to click Continue Shopping to go back to the shop page.

4. Customer need to click the **Continue Shopping** again and again.
 
Expected behavior:

When customer add a product to cart , odoo do not redirect to cart page. If the customer want to go to the cart page ,they should click the cart button.
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/5561864/110057766-21c71f00-7d9c-11eb-885b-bd4ef1c72274.png">

taobao.com, the biggest e-commerce website in China, also behavior like this.

**Comment by Yenthe666** [comment]
Not a bug, this is the default way of Odoo. Customize it if you want it to work different.
