### ISSUE TITLE
[11.0] Typo in Rating Page Submit template

### ISSUE THREAD

**Issue by cuongnmtm** [odoo/odoo#67304]
Impacted versions:
11.0

Video/Screenshot link (optional):

https://github.com/odoo/odoo/blob/8011a8f2f5682e28f7296d1f2c96db7854ed3dab/addons/rating/views/rating_template.xml#L30

There are three other places that have this issue

![ảnh](https://user-images.githubusercontent.com/32898439/110071323-65c31f80-7dae-11eb-937b-3735fe565741.png)

**Comment by Yenthe666** [comment]
Hi,

Thanks for your report but v11 is no longer supported.
These issues have however been fixed in V12 and up. For example at https://github.com/odoo/odoo/commit/96b8f2cee17e707d27af0f31065d55c79df812e1
