### ISSUE TITLE
[14.0][hr] Installing hr module creates a new partner called Administrator and work address linked to address of administrator user

### ISSUE THREAD

**Issue by omalbastin** [odoo/odoo#67314]
Impacted versions: 14

Steps to reproduce: Install hr module

Current behavior: Installing the hr module creates partner with name "Administrator" and a employee "Administrator" with related user linked to the user "Administrator", work address linked to the related partner of user Administrator and private contact address(address_home_id) linked to the newly created partner with name "Administrator"

Expected behavior: Installing the hr module should only create a employee "Administrator" with related user linked to user "Administrator", work address linked to the related partner of the company(same like when we create a employee from user record) and private contact address should be linked to the related partner of the user Administrator

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by Yenthe666** [comment]
I've seen it happen on a db before actually. @tde-banana-odoo

**Comment by omalbastin** [comment]
Following is the code creating it.
https://github.com/odoo/odoo/blob/0784e14dd39817720e6fc70c2b41ea3bbad5843a/addons/hr/data/hr_data.xml#L21

**Comment by tde-banana-odoo** [comment]
@tivisse

**Comment by tivisse** [comment]
@omalbastin Thank for the feedback. 

However I have to partially reject it. 

We want to use a private addresses (i.e. res.partner with type="private") as private address. That way, the home addresses of the employees are protected from users having a read access to customers (which is a lot of people). It's also a bad idea to link the user's partner to the home address, as you could modify the user's name or email without knowing it. 

I agree concerning the ``work address linked to the related partner of the company``.

I'll create an internal task to manage this properly. 

Have a nice day,

Yannick.

**Comment by omalbastin** [comment]
Thank you @tivisse  for the information. I would be great if we use a new name or at least "Administrator ( Private)" so that we will be able to distinguish both these addresses when we see them in Contacts.
