### ISSUE TITLE
Price list mesh values mismatch on webshop

### ISSUE THREAD

**Issue by catroot** [odoo/odoo#6735]
Hi all!
A have setup 2 price lists - one for public with 50% margin from base product price and the second one  for regular buyers with 30% margin. 
When i add a product to cart as an regular buyer - i see that the price in my cart as if i`m a public buyer, after increasing/decreasing ammount of selected product - the price changes to correct value for regular buyers but total summ remains incorrect - as it must to be calculated for public buyers, not regular.
See mismatch: http://SSMaker.ru/4d005ba2/ http://SSMaker.ru/bf693928/

And there is product attributes additional price shown as it typed in product, but calculated by the client pricelist values.
http://SSMaker.ru/5cb7c847/
http://SSMaker.ru/402ecabc/

**Comment by Yenthe666** [comment]
Hi @catroot,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
