### ISSUE TITLE
attrs-domains don't work with many2many fields

### ISSUE THREAD

**Issue by hbrunn** [odoo/odoo#674]
Given that many2many fields store their values in the form of [(6, 0, [ids...])] on the client side, all comparisons in https://github.com/odoo/odoo/blob/master/addons/web/static/src/js/view_form.js#L1708 ff fail. I think we need to check for the fields type and handle this as special case. When doing that, we could also handle some inconsistencies for one2many-fields (the operators '=' and 'in' don't behave as they do in search domains)

**Comment by Yenthe666** [comment]
Dear @hbrunn,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
