### ISSUE TITLE
Automatically separate and sum eligible and ineligible products in POS (Food Stamp/EBT) when accepting payment. [Wishlist]

### ISSUE THREAD

**Issue by jaronbender** [odoo/odoo#67412]
Impacted versions:
All versions

Steps to reproduce:
In Point of Sale session we have to manually do two transactions when a customer is paying for part of their purchase via a government food assistance card.

Current behavior:
Customers are asked to alert the cashier if they intend to pay with Food Stamps. If they don't the cashier has to go back over the order and remove products that are ineligible e.g. non-food.

Expected behavior:
We are looking for a way in a POS order to automatically separate and sum products that are eligible for government food assistance payment cards (EBT, SNAP, Food Stamps, WIC). Products would be categorized as eligible (food) or non-eligible (non-food). At payment products should be automatically split into eligible/non-eligible amounts. Selecting the Food Stamp/EBT payment method should only allow payment for the sum of the eligible products.

**Comment by pedrobaeza** [comment]
This doesn't apply as issue, as it's a non existing feature, so closing it. @pimodoo can take it as feedback and inspiration for future new features, or you can extend Odoo for allowing that.
