### ISSUE TITLE
Suppliers error - relation "account_invoice_report" does not exist

### ISSUE THREAD

**Issue by linuxyeti** [odoo/odoo#6741]
Hi

Odoo 8, getting the above error wjen creting or attempting to edit suppliers.

I've check the backend postgres database, and it's true, that table does not exist

Cheers

Tony

**Comment by linuxyeti** [comment]
Ok, well, eventually worked out a fix myself. Basically, a module, which one I don't know, install delete the account_invoice_report view. I've found the sql to manually create the view.

-- View: account_invoice_report

-- DROP VIEW account_invoice_report;

CREATE OR REPLACE VIEW account_invoice_report AS
 SELECT sub.id,
    sub.date,
    sub.product_id,
    sub.partner_id,
    sub.country_id,
    sub.payment_term,
    sub.period_id,
    sub.uom_name,
    sub.currency_id,
    sub.journal_id,
    sub.fiscal_position,
    sub.user_id,
    sub.company_id,
    sub.nbr,
    sub.type,
    sub.state,
    sub.categ_id,
    sub.date_due,
    sub.account_id,
    sub.account_line_id,
    sub.partner_bank_id,
    sub.product_qty,
    sub.price_total / cr.rate AS price_total,
    sub.price_average / cr.rate AS price_average,
    cr.rate AS currency_rate,
    sub.residual / cr.rate AS residual,
    sub.commercial_partner_id
   FROM ( SELECT min(ail.id) AS id,
            ai.date_invoice AS date,
            ail.product_id,
            ai.partner_id,
            ai.payment_term,
            ai.period_id,
            u2.name AS uom_name,
            ai.currency_id,
            ai.journal_id,
            ai.fiscal_position,
            ai.user_id,
            ai.company_id,
            count(ail.*) AS nbr,
            ai.type,
            ai.state,
            pt.categ_id,
            ai.date_due,
            ai.account_id,
            ail.account_id AS account_line_id,
            ai.partner_bank_id,
            sum(
                CASE
                    WHEN ai.type::text = ANY (ARRAY['out_refund'::character varying::text, 'in_invoice'::character varying::text]) THEN (- ail.quantity) / u.factor * u2.factor
                    ELSE ail.quantity / u.factor * u2.factor
                END) AS product_qty,
            sum(
                CASE
                    WHEN ai.type::text = ANY (ARRAY['out_refund'::character varying::text, 'in_invoice'::character varying::text]) THEN - ail.price_subtotal
                    ELSE ail.price_subtotal
                END) AS price_total,
                CASE
                    WHEN ai.type::text = ANY (ARRAY['out_refund'::character varying::text, 'in_invoice'::character varying::text]) THEN sum(- ail.price_subtotal)
                    ELSE sum(ail.price_subtotal)
                END /
                CASE
                    WHEN sum(ail.quantity / u.factor * u2.factor) <> 0::numeric THEN
                    CASE
                        WHEN ai.type::text = ANY (ARRAY['out_refund'::character varying::text, 'in_invoice'::character varying::text]) THEN sum((- ail.quantity) / u.factor * u2.factor)
                        ELSE sum(ail.quantity / u.factor * u2.factor)
                    END
                    ELSE 1::numeric
                END AS price_average,
                CASE
                    WHEN ai.type::text = ANY (ARRAY['out_refund'::character varying::text, 'in_invoice'::character varying::text]) THEN - ai.residual
                    ELSE ai.residual
                END / (( SELECT count(*) AS count
                   FROM account_invoice_line l
                  WHERE l.invoice_id = ai.id))::numeric * count(*)::numeric AS residual,
            ai.commercial_partner_id,
            partner.country_id
           FROM account_invoice_line ail
             JOIN account_invoice ai ON ai.id = ail.invoice_id
             JOIN res_partner partner ON ai.commercial_partner_id = partner.id
             LEFT JOIN product_product pr ON pr.id = ail.product_id
             LEFT JOIN product_template pt ON pt.id = pr.product_tmpl_id
             LEFT JOIN product_uom u ON u.id = ail.uos_id
             LEFT JOIN product_uom u2 ON u2.id = pt.uom_id
          GROUP BY ail.product_id, ai.date_invoice, ai.id, ai.partner_id, ai.payment_term, ai.period_id, u2.name, u2.id, ai.currency_id, ai.journal_id, ai.fiscal_position, ai.user_id, ai.company_id, ai.type, ai.state, pt.categ_id, ai.date_due, ai.account_id, ail.account_id, ai.partner_bank_id, ai.residual, ai.amount_total, ai.commercial_partner_id, partner.country_id) sub
     JOIN res_currency_rate cr ON cr.currency_id = sub.currency_id
  WHERE (cr.id IN ( SELECT cr2.id
           FROM res_currency_rate cr2
          WHERE cr2.currency_id = sub.currency_id AND (sub.date IS NOT NULL AND cr2.name <= sub.date OR sub.date IS NULL AND cr2.name <= now())
          ORDER BY cr2.name DESC
         LIMIT 1));

ALTER TABLE account_invoice_report
  OWNER TO odoo;

I'm not closing the issue, as the issue still exists, this is just a work around

**Comment by kingofsevens** [comment]
Same issue here.. #3882

The above solution is correct but the sql is wrong probably from copy paste. Here is what I have run. But the problem still persists.

```sql
CREATE or REPLACE VIEW account_invoice_report as (
    WITH currency_rate (currency_id, rate, date_start, date_end) AS (
        SELECT r.currency_id, r.rate, r.name AS date_start,
            (SELECT name FROM res_currency_rate r2
             WHERE r2.name > r.name AND
                   r2.currency_id = r.currency_id
             ORDER BY r2.name ASC
             LIMIT 1) AS date_end
        FROM res_currency_rate r
    )
    SELECT sub.id, sub.date, sub.product_id, sub.partner_id, sub.country_id,
        sub.payment_term, sub.period_id, sub.uom_name, sub.currency_id, sub.journal_id,
        sub.fiscal_position, sub.user_id, sub.company_id, sub.nbr, sub.type, sub.state,
        sub.categ_id, sub.date_due, sub.account_id, sub.account_line_id, sub.partner_bank_id,
        sub.product_qty, sub.price_total / cr.rate as price_total, sub.price_average /cr.rate as price_average,
        cr.rate as currency_rate, sub.residual / cr.rate as residual, sub.commercial_partner_id as commercial_partner_id
    FROM (
        SELECT min(ail.id) AS id,
            ai.date_invoice AS date,
            ail.product_id, ai.partner_id, ai.payment_term, ai.period_id,
            u2.name AS uom_name,
            ai.currency_id, ai.journal_id, ai.fiscal_position, ai.user_id, ai.company_id,
            count(ail.*) AS nbr,
            ai.type, ai.state, pt.categ_id, ai.date_due, ai.account_id, ail.account_id AS account_line_id,
            ai.partner_bank_id,
            SUM(CASE
                WHEN ai.type::text = ANY (ARRAY['out_refund'::character varying::text, 'in_invoice'::character varying::text])
                    THEN (- ail.quantity) / u.factor * u2.factor
                    ELSE ail.quantity / u.factor * u2.factor
                END) AS product_qty,
            SUM(CASE
                WHEN ai.type::text = ANY (ARRAY['out_refund'::character varying::text, 'in_invoice'::character varying::text])
                    THEN - ail.price_subtotal
                    ELSE ail.price_subtotal
                END) AS price_total,
            CASE
                WHEN ai.type::text = ANY (ARRAY['out_refund'::character varying::text, 'in_invoice'::character varying::text])
                    THEN SUM(- ail.price_subtotal)
                    ELSE SUM(ail.price_subtotal)
            END / CASE
                WHEN SUM(ail.quantity / u.factor * u2.factor) <> 0::numeric
                    THEN CASE
                         WHEN ai.type::text = ANY (ARRAY['out_refund'::character varying::text, 'in_invoice'::character varying::text])
                             THEN SUM((- ail.quantity) / u.factor * u2.factor)
                             ELSE SUM(ail.quantity / u.factor * u2.factor)
                         END
                    ELSE 1::numeric 
                END AS price_average,
            CASE
            WHEN ai.type::text = ANY (ARRAY['out_refund'::character varying::text, 'in_invoice'::character varying::text])
                THEN - ai.residual
                ELSE ai.residual
            END / (SELECT count(*) FROM account_invoice_line l where invoice_id = ai.id) *
            count(*) AS residual,
            ai.commercial_partner_id as commercial_partner_id,
            partner.country_id
                FROM account_invoice_line ail
                JOIN account_invoice ai ON ai.id = ail.invoice_id
                JOIN res_partner partner ON ai.commercial_partner_id = partner.id
                LEFT JOIN product_product pr ON pr.id = ail.product_id
                left JOIN product_template pt ON pt.id = pr.product_tmpl_id
                LEFT JOIN product_uom u ON u.id = ail.uos_id
                LEFT JOIN product_uom u2 ON u2.id = pt.uom_id
                    GROUP BY ail.product_id, ai.date_invoice, ai.id,
                        ai.partner_id, ai.payment_term, ai.period_id, u2.name, u2.id, ai.currency_id, ai.journal_id,
                        ai.fiscal_position, ai.user_id, ai.company_id, ai.type, ai.state, pt.categ_id,
                        ai.date_due, ai.account_id, ail.account_id, ai.partner_bank_id, ai.residual,
                        ai.amount_total, ai.commercial_partner_id, partner.country_id
    ) AS sub
    JOIN currency_rate cr ON
        (cr.currency_id = sub.currency_id AND 
         cr.date_start <= COALESCE(sub.date, NOW()) AND 
         (cr.date_end IS NULL OR cr.date_end > COALESCE(sub.date, NOW()))));
```

**Comment by kingofsevens** [comment]
Out of the blue the view gets deleted. Above code works if you don't use sales. If you use sales below code with additional `section_id` is needed. Here is the code..

```sql
CREATE or REPLACE VIEW account_invoice_report as (
    WITH currency_rate (currency_id, rate, date_start, date_end) AS (
        SELECT r.currency_id, r.rate, r.name AS date_start,
            (SELECT name FROM res_currency_rate r2
             WHERE r2.name > r.name AND
                   r2.currency_id = r.currency_id
             ORDER BY r2.name ASC
             LIMIT 1) AS date_end
        FROM res_currency_rate r
    )
    SELECT sub.id, sub.date, sub.product_id, sub.partner_id, sub.country_id,
        sub.payment_term, sub.period_id, sub.uom_name, sub.currency_id, sub.journal_id,
        sub.fiscal_position, sub.user_id, sub.company_id, sub.nbr, sub.type, sub.state,
        sub.categ_id, sub.date_due, sub.account_id, sub.account_line_id, sub.partner_bank_id,
        sub.product_qty, sub.price_total / cr.rate as price_total, sub.price_average /cr.rate as price_average,
        cr.rate as currency_rate, sub.residual / cr.rate as residual, sub.commercial_partner_id as commercial_partner_id,
        sub.section_id as section_id
    FROM (
        SELECT min(ail.id) AS id,
            ai.date_invoice AS date,
            ail.product_id, ai.partner_id, ai.payment_term, ai.period_id,
            u2.name AS uom_name,
            ai.currency_id, ai.journal_id, ai.fiscal_position, ai.user_id, ai.company_id,
            count(ail.*) AS nbr,
            ai.type, ai.state, pt.categ_id, ai.date_due, ai.account_id, ail.account_id AS account_line_id,
            ai.partner_bank_id,
            SUM(CASE
                WHEN ai.type::text = ANY (ARRAY['out_refund'::character varying::text, 'in_invoice'::character varying::text])
                    THEN (- ail.quantity) / u.factor * u2.factor
                    ELSE ail.quantity / u.factor * u2.factor
                END) AS product_qty,
            SUM(CASE
                WHEN ai.type::text = ANY (ARRAY['out_refund'::character varying::text, 'in_invoice'::character varying::text])
                    THEN - ail.price_subtotal
                    ELSE ail.price_subtotal
                END) AS price_total,
            CASE
                WHEN ai.type::text = ANY (ARRAY['out_refund'::character varying::text, 'in_invoice'::character varying::text])
                    THEN SUM(- ail.price_subtotal)
                    ELSE SUM(ail.price_subtotal)
            END / CASE
                WHEN SUM(ail.quantity / u.factor * u2.factor) <> 0::numeric
                    THEN CASE
                         WHEN ai.type::text = ANY (ARRAY['out_refund'::character varying::text, 'in_invoice'::character varying::text])
                             THEN SUM((- ail.quantity) / u.factor * u2.factor)
                             ELSE SUM(ail.quantity / u.factor * u2.factor)
                         END
                    ELSE 1::numeric
                END AS price_average,
            CASE
            WHEN ai.type::text = ANY (ARRAY['out_refund'::character varying::text, 'in_invoice'::character varying::text])
                THEN - ai.residual
                ELSE ai.residual
            END / (SELECT count(*) FROM account_invoice_line l where invoice_id = ai.id) *
            count(*) AS residual,
            ai.commercial_partner_id as commercial_partner_id,
            partner.country_id, ai.section_id as section_id
                FROM account_invoice_line ail
                JOIN account_invoice ai ON ai.id = ail.invoice_id
                JOIN res_partner partner ON ai.commercial_partner_id = partner.id
                LEFT JOIN product_product pr ON pr.id = ail.product_id
                left JOIN product_template pt ON pt.id = pr.product_tmpl_id
                LEFT JOIN product_uom u ON u.id = ail.uos_id
                LEFT JOIN product_uom u2 ON u2.id = pt.uom_id
                    GROUP BY ail.product_id, ai.date_invoice, ai.id,
                        ai.partner_id, ai.payment_term, ai.period_id, u2.name, u2.id, ai.currency_id, ai.journal_id,
                        ai.fiscal_position, ai.user_id, ai.company_id, ai.type, ai.state, pt.categ_id,
                        ai.date_due, ai.account_id, ail.account_id, ai.partner_bank_id, ai.residual,
                        ai.amount_total, ai.commercial_partner_id, partner.country_id, ai.section_id
    ) AS sub
    JOIN currency_rate cr ON
        (cr.currency_id = sub.currency_id AND
         cr.date_start <= COALESCE(sub.date, NOW()) AND
         (cr.date_end IS NULL OR cr.date_end > COALESCE(sub.date, NOW()))));

```

**Comment by amjedns2** [comment]
I face the same problem the solution is simple the module of sales is not installed it appear in menu from database but actually it's not install just install sale module and the problem will be solved

**Comment by Yenthe666** [comment]
Hi @linuxyeti,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
