### ISSUE TITLE
[14.0] Module: Survey - Error on editing answers.

### ISSUE THREAD

**Issue by dharaaktiv** [odoo/odoo#67429]
Impacted versions:14.0 CE

Steps to reproduce: Go to Surveys > Open survey > Click on the smart button "Answers" > Open any answer try to edit it will show an Error.

This error is also genearted in Runbot.

Video/Screenshot link (optional): 
![Feedback-Form-Odoo](https://user-images.githubusercontent.com/69238920/110284934-825a9400-8008-11eb-9e6c-b0de81714d76.png)

**Comment by pedrobaeza** [comment]
I have just tried what you say in runbot and the error is not happening.

**Comment by dharaaktiv** [comment]
Hi @pedrobaeza 
Here is the video link:
https://www.awesomescreenshot.com/video/2982771?key=b38546e9fb38902db4a3de81aedb59fd

**Comment by pedrobaeza** [comment]
OK, then in your initial steps, 2 steps are missing:

- Fill "Row answer".
- Click on "Save.

**Comment by dharaaktiv** [comment]
Hi @pedrobaeza 
Is there any update ?

**Comment by pedrobaeza** [comment]
No, as long as there's no answer from Odoo stuff.

**Comment by sswapnesh** [comment]
Added fix on #68500

**Comment by dharaaktiv** [comment]
@pedrobaeza Is it possible to merge the PR #68500?

**Comment by pedrobaeza** [comment]
I only manage issues, but don't merge PRs.

**Comment by dharaaktiv** [comment]
Okay. Can you please guide me whom shall I contact to merge this PR?

**Comment by pedrobaeza** [comment]
For surveys, I can't say.

**Comment by tde-banana-odoo** [comment]
Should have been fixed with https://github.com/odoo/odoo/commit/0d32ed45aebe2721073580ddae68ec4a8c1499d6 by the way
