### ISSUE TITLE
[13.0]Groups not apply in followers in chatter

### ISSUE THREAD

**Issue by yousef-soliman** [odoo/odoo#67426]
Impacted versions:
13.0
Steps to reproduce:

- create a from and add Chatter 
- add groups like this 
- ` <field name="message_follower_ids" widget="mail_followers" groups="base.group_no_one"/>
`

Current behavior:
it shows the followers in form when doesn't has this group 
Expected behavior:
show the followers in form only when user has this group

**Comment by pedrobaeza** [comment]
Yes, the way this widget works doesn't allow to apply groups, so it's a known limitation, and thus, closing as won't fix.

**Comment by yousef-soliman** [comment]
Hello Pedrobeaza, 
the field has the modifier data, all we need to apply this modifier.
so i applied it with simple customization 

```
var Followers = require("mail.Followers");
  Followers.include({
    _render: function () {
      if (this.attrs.invisible) {
        this.$el.toggleClass("o_invisible_modifier");
        return;
      }
      this._super.apply(this, arguments);
    },
  });
  ```

**Comment by pedrobaeza** [comment]
Make the pull request adding that, and let's see if Odoo considers it
