### ISSUE TITLE
[language flag] Website flag issue for bangla language

### ISSUE THREAD

**Issue by kmrul** [odoo/odoo#67420]
Impacted versions: 
14.0

Steps to reproduce:
Change Indian flag to Bangladeshi flag for Bangla language.

Current behavior:
When added Bangla language in website, showing Indian flag 

Expected behavior:
Need to show Bangladeshi flag

Video/Screenshot link (optional):
https://prnt.sc/10f0lp3

Reference:
Please showing those reference for Bangla language: 
https://en.wikipedia.org/wiki/International_Mother_Language_Day

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
hi @kmrul ,
upon checking the same it seems to be working fine. Not sure whether the flags has been wrongly configured in your instance or whether it has been fixed in the mean while.

can you confirm the same and close the ticket.
thanks
