### ISSUE TITLE
problem to get self on selection field in odoo

### ISSUE THREAD

**Issue by Bharat2512** [odoo/odoo#6744]
Hello,

Whenever I tried to fill selection field dynamically by calling method then I can't get self on that method.
My code is below:

grade = fields.Selection(selection='_select_grade', string="Grade")    

```
@api.multi
def _select_grade(self):
    res = []       
    ctx = self._context
    if ctx.get('active_id', False):
        assignment_id = self.env['assignment.assignment'].browse(ctx['active_id'])
    else: 
        assignment_id = self.assignment_id
    if assignment_id:
        if assignment_id.scale_type == "bad_good":
            res = [('bad','Bad'), ('medium','Medium'), ('good','Good')]
        elif assignment_id.scale_type == "regular_excellent":
            res = [('defficient','Defficient'), ('regular','Regular'), ('exellent','Exellent')]
        elif assignment_id.scale_type == "attendance":
            res = [('attendance', 'Attendance')]
        elif assignment_id.scale_type == "frequency":
            res = [('frequency','Frequency')]
        elif assignment_id.scale_type == "useful":
            res = [('useful','Useful')]
        elif assignment_id.scale_type ==  "presentation_skill":
            res = [('presentation_skill','Presentation Skill')]                
    return res
```

grade is selection field, in which values are dynamically fill up by '_select_grade' method. But I can't get 'ids' in context. even self.assignment_id is also get Null value. So, how can I overcome this problem? Is there any alternate solution to get self here?

Thanks in advance.

**Comment by lynndotconfig** [comment]
have you solved it now ? i meet the same problem.

**Comment by Yenthe666** [comment]
Hi @Bharat2512,

Please ask questions about custom development on the official help forums (at odoo.com/help).
The Github bug tracker is only for bugs in the official code, not for asking development questions.

Regards,
Yenthe
