### ISSUE TITLE
[8.0] Reordering rules of a Consumable product

### ISSUE THREAD

**Issue by ghost** [odoo/odoo#6745]
**Impossible to create a reordering rule from Reordering rules menu**

Impacted versions:
- 8.0

Steps to reproduce:
1. create a new reordering rule
2. try to select a Consumable product

Current behavior:
- You cannot do this. You must go to Consumable product and click on Reordering rules button to create it.

Expected behavior:
- The same as Stockable products.

**Comment by Yenthe666** [comment]
Hi @ghost,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: My god you where active back in the days!

Regards,
Yenthe
