### ISSUE TITLE
[8.0] Bad Datetime value in search view filter_domain

### ISSUE THREAD

**Issue by sergueikp** [odoo/odoo#6755]
[8.0] Bad Datetime value in search view filter_domain

Impacted versions:

```
8.0 (Nightly build odoo-8.0_20150512) on Ubuntu 14.04 and on Windows 7
```

Steps to reproduce:
Crate an workaround to search date in date range in search view of sale.order.line 
"field name="search_date_from" filter_domain="[('date_depart','&gt;=', self)]"/ "
"field name="search_date_to" filter_domain="[('date_depart','&lt;=', self)]"/"

Put this python lines in Inherited model of sale.order.line
 date_depart = fields.Datetime(string='Date de depart', required=True)
 search_date_from = fields.Date(string='Date Debut : ', compute='_get_date_search')
 search_date_to = fields.Date(string='Date Fin : ', compute='_get_date_search')
      def _get_date_search(self):
        lambda _a,_*k:{}

Current behavior:
The search is performed on Datetime field date_depart, when you enter  in search field a date for eg 2015-05-18 it didn't take in account Datetime  like this 2015-05-18 00:00 to 01:59, it only filter correctly when time is > than 02 hours. I think it's a problem with tiemzone! 

Expected behavior:
If you enter in search field the date 2015-05-18  it should take in account datetime fields like 2015-05-18  01:59, 2015-05-18  01:00, etc. 
It should  take in account datetime fields with hours from 00:00 to 01:59

Can any body help us with this quite critical issue ?

**Comment by Yenthe666** [comment]
Hi @sergueikp,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
