### ISSUE TITLE
[14.0] mrp: Machine translation adds unexpected escape characters

### ISSUE THREAD

**Issue by janikvonrotz** [odoo/odoo#67553]
The translation at https://github.com/odoo/odoo/blob/14.0/addons/mrp/i18n/de.po#L5197 breaks the form logic.

Instead of `{'invisible'\\:` it should be `{'invisible'\:`.

Can I help resolving this issue through Transifex?

# Test case

Execute these steps to reproduce the issue:

* Change Odoo language to `de`
* Create product 

```yml
Product: Main
Type: Storable Product
Route: Manufacture
BoM:
  - Consumption: With Warning
    Operation: Assemble
    Components:
      - Product: Sub
        Qty: 2
        Operation: Assemble
```

* Set stock `WH/Stock` for *Sub* to 10
* Replenish *Main* with route `Manufacture`
* Start work order
	* Produce 1 qty
	* Use 1 Sub and continue consumption
	* Use 2 Sub and finish order
* Open MO and mark as done

This error occurs:

```
...
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/janikvonrotz/Odoo-Development/odoo/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/janikvonrotz/Odoo-Development/odoo/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
  File "<unknown>", line 1
    {'invisible'\: [('consumption', '=', 'strict')]}
                                                   ^
SyntaxError: unexpected character after line continuation character
```

**Comment by pedrobaeza** [comment]
Please fix the translation in Transifex:

https://github.com/odoo/odoo/wiki/Translations

**Comment by janikvonrotz** [comment]
@pedrobaeza I tried to fix it: https://www.transifex.com/odoo/odoo-14/translate/#de/mrp/298938428?q=text%3A'ou+consumed+a+different+quantity+than+expected+for+the+following+products'

But I guess this is Transifex related issue. Somehow the parameters are not escaped properly.

**Comment by pedrobaeza** [comment]
@mart-e do you know about this issue?

**Comment by mart-e** [comment]
Hi!

What do you mean the parameters are not escaped properly? I have used the Transifex editor and fixed the issue, it works well.
You can see in the history the tags were using a different number, indication they don't match
https://www.transifex.com/odoo/odoo-14/translate/#de/mrp/298938428?q=translation_text%3A'Sie+verbrauchen+f%C3%BCr'
![Screenshot from 2021-03-12 07-33-34](https://user-images.githubusercontent.com/564822/110901929-58091f00-8305-11eb-82c5-d0eded1e13b3.png)
How did you created your translation ?

In case you have some issues with Transifex editor, the [transifex support](https://www.transifex.com/contact/) will probably be able to help you more than us.

Closing as the error is corrected but let me know if I misunderstood.

**Comment by janikvonrotz** [comment]
@mart-e I think you have misunderstood. See the translation file: https://github.com/odoo/odoo/blob/14.0/addons/mrp/i18n/de.po#L5197
Instead of `attrs=\"{'invisible'\\: [('consumption',` it should be `attrs=\"{'invisible': [('consumption'` (not backslashes before `:`) and so on.
I assume this file is the output of Transifex.

**Comment by mart-e** [comment]
@janikvonrotz it was indeed incorrect and I have just fixed it this morning. The synchronisation Transifex -> Github is done every Sunday so it's not present there yet. If there is still the issue on Monday, we will need to investigate more.
