### ISSUE TITLE
Two different companies in one database will not flip approriate company logos...

### ISSUE THREAD

**Issue by tezozomoc** [odoo/odoo#6756]
Running odoo 8.0 on ubuntu 14 
1.  I installed two separate companies  and not in multi-company mode.
2.  Each company has its own logo.
3.  When I log out of one company and login into the other the old companies logo will remain.
4.  This is very confusing because there is no other way to distinguish the companies...

**Comment by falinwa** [comment]
yes, I also have this problem,
and in odoo v8, in web address, there's no database name again which is confuse a lot of user.

**Comment by flotho** [comment]
did you clear your cache browser?

**Comment by tezozomoc** [comment]
Yes... it does not make a difference... 

Tezo

Date: Tue, 19 May 2015 14:01:17 -0700

**Comment by falinwa** [comment]
actually when you clear your cache it will fixed the problem, but not fixed permanently, the problem will come again when we change the database that has different company logo.

**Comment by AlanBell** [comment]
this is going to be related to #3753 and probably has a related solution, however adding ensure_db to the company logo method doesn't appear to solve this problem.

**Comment by mart-e** [comment]
8.0 is no longer supported but the issue should be fixed in upper versions
