### ISSUE TITLE
sale analysis grouped by customer (= contact) instead of company.

### ISSUE THREAD

**Issue by mylbco** [odoo/odoo#6762]
grouping is done by contact id instead of commercial_id ...

I think in 90% of the use cases user is interested in grouping by commercial_id (company of the customer), not by contact.

![selection_572](https://cloud.githubusercontent.com/assets/3402495/7698830/8ea05696-fe13-11e4-968f-42462817ff73.png)

**Comment by Yenthe666** [comment]
Hi @mylbco ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
