### ISSUE TITLE
Bug if decimal accuracy more than 6

### ISSUE THREAD

**Issue by jackysupit** [odoo/odoo#67639]
Impacted versions:
12, 13, 14

Steps to reproduce:
You must have this addons installed: sale/purchase/any addons depend to decimal accuration
then
1 set the decimal accuracy Product Price to 8
2 go to sale / purchase, create
3 on the order line, pick any product
4 set the unit price to 100,000,000 enter to trigger onchange
5 the price will change to 100,000,000.00000004
6 see the point .00000004? this should be .00000000

Current behavior:
Any value without decimal will be automatically added with decimal.
example: 100,000,000 will become 100,000,000.00000004

Expected behavior:
the value should not change from 100,000,000 to 100,000,000.00000000

I know how to fix this, because I have fixed this on my local odoo. But I can not make a Pull Request. I don't know how to make a pull request if we can not even fork the branches. If anyone could help me to join as a contributor, I would love to contribute to the odoo development. I will be gladly and thankfully accepting any advices from you guys. thanks

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
This can't be considered as a bug, as float arithmetic works that way. In any case, I don't recommend you to use 6 decimals for prices, as that will be overkilling for most things.

Closing as won't fix, due to limitations of float arithmetic.
