### ISSUE TITLE
[14.0] BUG in form view pager when Reload page

### ISSUE THREAD

**Issue by redapureskill** [odoo/odoo#67665]
Impacted versions: 14

Steps to reproduce: 1) click on a any record from any tree view to go to the record's form view (no specific model) , 2) refresh the page.

Current behavior: the form view's pager turn (1/1)

Expected behavior: 1/(data limit in context)

Video/Screenshot link (optional):
![before_3](https://user-images.githubusercontent.com/9614843/110786979-17f65d80-826d-11eb-8774-447a19104da0.png)
![after_3](https://user-images.githubusercontent.com/9614843/110786977-162c9a00-826d-11eb-9325-7ecb74522453.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
Odoo is a single page app, and as such, if you reload the browser page, only the minimum information can be rescued from the URL, but such context is not there and it can't never be there due to a lot of technical, usability and security reasons.

Closing as won't fix.

**Comment by redapureskill** [comment]
Odoo 8 used to work fine

**Comment by pedrobaeza** [comment]
Odoo 8 assumed the default context filter, which is wrong in several cases, so this was changed for avoiding misunderstandings.
