### ISSUE TITLE
on chatter uploading file but the Form view is not refreshed

### ISSUE THREAD

**Issue by grey27** [odoo/odoo#67672]
Impacted versions:14.0

Steps to reproduce:
1.Display the `message_attachment_count` field in the Form view
2. chatter uploading file

Current behavior:
message_attachment_count no update

Expected behavior:
Auto-refresh data

In my tests on version 13, it was automatically refreshed
This functionality is missing with OWL

**Comment by redapureskill** [comment]
it works fine on runbot:
![11112](https://user-images.githubusercontent.com/9614843/110786529-8a1a7280-826c-11eb-8893-6de5b74d311a.png)
![111111111111](https://user-images.githubusercontent.com/9614843/110786535-8ab30900-826c-11eb-8e23-88cc54c3e885.png)

**Comment by grey27** [comment]
> 在runbot效果好:
> ![11112](https://user-images.githubusercontent.com/9614843/110786529-8a1a7280-826c-11eb-8893-6de5b74d311a.png)
> ![111111111111](https://user-images.githubusercontent.com/9614843/110786535-8ab30900-826c-11eb-8e23-88cc54c3e885.png)

Uploading files is normal,But the Form view data is not updated

**Comment by redapureskill** [comment]
If it's not updated how is it showing the number of attachement count right? !
should be gone if i reload the page , but still works fine after that

**Comment by grey27** [comment]
The Attachment Count fields (this is a mail module defined field) were not updated when I uploaded the picture

**Comment by grey27** [comment]
![image](https://user-images.githubusercontent.com/39294698/110788587-c7e9bc00-82a9-11eb-8565-294ee5c5070f.png)
![image](https://user-images.githubusercontent.com/39294698/110788611-ce783380-82a9-11eb-968b-9217aad67899.png)

**Comment by grey27** [comment]
@redapureskill Can you help me? Thank you

**Comment by redapureskill** [comment]
i'll check it on my localhost

**Comment by redapureskill** [comment]
can you provide me with how did you display message_attachment_count in this form view, code : python and view : xml ? !

**Comment by redapureskill** [comment]
> @redapureskill Can you help me? Thank you

it's just you need to reload the page to get the count, the compute is not triggered while adding a new file.

**Comment by redapureskill** [comment]
this is a bug , true

**Comment by grey27** [comment]
@pedrobaeza can it be included in the restoration plan

**Comment by seb-odoo** [comment]
The form view is not automatically sync with the chatter (for technical reasons). 

The best I can suggest for you is to use `post_refresh` which will trigger a full refresh of the view on change `<field name="message_ids" options="{'post_refresh': 'always'}"/>`

**Comment by grey27** [comment]
> 表单视图是不会自动同步聊天(因为技术原因)。
> 
> 最好的我可以为你建议是使用 `post_refresh `这将触发一个完整的刷新视图的变化 `<字段名= " message_ids "选项= " {“post_refresh”:“总是”}" / > `

Thank you. It worked

**Comment by grey27** [comment]
![image](https://user-images.githubusercontent.com/39294698/111571728-349d1300-87e2-11eb-92ed-373ac7fb4738.png)
![image](https://user-images.githubusercontent.com/39294698/111571752-3ff03e80-87e2-11eb-874b-a7eb413cd383.png)
![image](https://user-images.githubusercontent.com/39294698/111571776-4aaad380-87e2-11eb-86cd-14ab7b7e91e1.png)
This is a valid refresh when I upload the attachment, but its data lag when I delete the attachment
@seb-odoo

**Comment by pedrobaeza** [comment]
@seb-odoo I agree with the issuer that this is not optimal and can be considered a regression. Is this workaround going to be added on Odoo code? It seems also to be partial, as deleting doesn't refresh.

**Comment by seb-odoo** [comment]
It should refresh also on delete when the flag is set, if that's not working correctly this could be addressed as a fix.

But we are not going to add the flag on all the views, because we normally don't display the attachment count on our views. If you need it, just add it.

Maybe when everything is converted to OWL we can try to properly trigger on change if we detect the field on the view, if that is feasible I don't see why we wouldn't do it, but we are still far from a point where everything is converted.

**Comment by pedrobaeza** [comment]
OK, thanks for the insights. I now see that this is not the attachment count of the chatter, so for me it's OK to work this way.
