### ISSUE TITLE
multiple declaration of _prepare_all_journals in i10n_fr

### ISSUE THREAD

**Issue by HendryLeo** [odoo/odoo#67728]
I notice there are 2 places where _prepare_all_journals being defined in the same module named i10n_fr

https://github.com/odoo/odoo/blob/2542f731c5b06c3b451ecde7992d3bb45adb2c60/addons/l10n_fr/models/account_chart_template.py#L11
https://github.com/odoo/odoo/blob/2542f731c5b06c3b451ecde7992d3bb45adb2c60/addons/l10n_fr/models/l10n_fr.py#L14

Logic of the function is same. Is it intentional?

**Comment by Yenthe666** [comment]
@HendryLeo it is an override of the original. Notice the small difference in:
https://github.com/odoo/odoo/blob/2542f731c5b06c3b451ecde7992d3bb45adb2c60/addons/l10n_fr/models/account_chart_template.py#L15-L16

@Feyensv you've built it so I'm pinging you but to me it totally looks on purpose.

**Comment by Feyensv** [comment]
I modified the code for a global task, but didn't notice that the method was duplicated :D.

**Comment by Yenthe666** [comment]
Thanks @Feyensv :)

**Comment by HendryLeo** [comment]
any plan to commit this to 14.0 branch?

**Comment by Feyensv** [comment]
It's been there for 2 years and that's only some duplicated code, it doesn't break anything.
We avoid to make "cosmetic" changes in stable branches, cleaning it in master is enough.
