### ISSUE TITLE
No location to drop in

### ISSUE THREAD

**Issue by martinllanos** [odoo/odoo#67758]
Impacted versions:

odoo 14+e release 20210308
Website builder with default theme

Steps to reproduce:

On website builder with default theme
1. Add Text snippets
2. Below add Columns with images snippets
3. Clear text
4. Set two columns
5. Set two images with upload
6. Duplicate Add Text and drag down the column
7. Save
8. Edit again
9. Add any block of snippets
10. Save and see, the fragments are locked

Current behavior:

1. When hovering over the snippet, it displays the message: "No location to drop in"
2. When dragging a snippets to the web page, it shows the following error: Error: dragAndDropResolve is not a function

Expected behavior:

It has to allow to drag a snippets from the wysiwyg to the website.

Video/Screenshot link (optional):

![No-location-to-drop-in](https://user-images.githubusercontent.com/463008/110939438-2ea3bf80-8314-11eb-9c60-2d8295337324.png)

![error](https://user-images.githubusercontent.com/463008/110939465-3bc0ae80-8314-11eb-8f26-ed7bc6f7facd.png)

Support ticket number submitted via odoo.com/help (optional):

#2481476

**Comment by vava-odoo** [comment]
Linked ticket is closed
