### ISSUE TITLE
[13.0, 14.0] framework: clickable="True" on statusbar no longer works

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#67769]
Impacted versions: V13 & V14

Steps to reproduce:
1. Login to the latest runbot 13.0 or 14.0 with the admin user
2. Activate developer mode
3. Go to Sales > Sale Orders and open up a sale order
4. Open up the action "Edit View: Form" from the developer icon at the top and add `clickable="True"` on the `state` field.
5. Save it and refresh the view

Current behavior: 
The statusbar is still not clickable.

Expected behavior: 
The statusbar is clickable. This worked just fine in V7-V12 and doesn't work on V13/V14 anymore.
It's really clunky having to add multiple buttons to just influence a state on the field.

**Comment by Yenthe666** [comment]
OPW `2481567`

**Comment by pedrobaeza** [comment]
@Yenthe666 are you sure of this? In project task, I'm able to click on the statusbar for changing the stage.

**Comment by Yenthe666** [comment]
@pedrobaeza  actually, you gave me a good idea to check this. They changed the syntax & the old way is no longer working.
You used to be able to do :
```
<field name="status" widget="statusbar" clickable="True"/>
```

But now you have to do this to have it work:
```
<field name="status" widget="statusbar" options="{'clickable': '1'}"/>
```

I'll ask for a feedback if they can't support both or give some deprecated warning and otherwise we'll close it off. ty :)

**Comment by sswapnesh** [comment]
@Yenthe666  Have a look at https://github.com/odoo/odoo/commit/7afc5fd6ad47e73c0ad1c8607203c0a958a3fa8b

**Comment by Yenthe666** [comment]
I don't really see the benefit plus no retro-compatibility so I think it could've been handled smoother?

**Comment by pedrobaeza** [comment]
This line is supposed to offer retro-compatibility:

https://github.com/odoo/odoo/commit/7afc5fd6ad47e73c0ad1c8607203c0a958a3fa8b#diff-e3526e2f4f8145679370ff9ac0ca70cba153b83df1fdba2453b13a3dbd62a8adR1953

**Comment by pedrobaeza** [comment]
Note that in v13 the syntax is different:

https://github.com/odoo/odoo/blob/5dde4347545e94f9e6547310ebe65edd5ece5882/addons/web/static/src/js/fields/relational_fields.js#L2649

Maybe a bad re-implementation?

**Comment by Yenthe666** [comment]
Feedback from Odoo:
> You Could use one of the following expressions instead of ‘clickable =" True "’ to make the statusbar clickable:
-clickable = "true"
-clickable = "1"
-options = "{'clickable': 1}"
-options = "{'clickable': true}"
