### ISSUE TITLE
Value Error for only one user after sign in 

### ISSUE THREAD

**Issue by maltehelmhold** [odoo/odoo#6778]
for one User of an Odoo instance and only one of many users 
I get this error:

File "/opt/odoo/odoo-server/openerp/osv/expression.py", line 812, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'journal_id.type' in leaf "< osv.ExtendedLeaf: ('journal_id.type', 'in', ['bank', 'cash']) on mail_message (ctx: )>"

Malte

**Comment by Sqmir** [comment]
Hi, i got the same issue concerning another field:  File "/opt/odoo/openerp/osv/expression.py", line 812, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'state' in leaf "<osv.ExtendedLeaf: ('state', 'in', ['draft', 'sent', 'cancel']) on mail_message (ctx: )>"

this error was mentionned in another issue report but no solution has been posted. Do your user got special rights?

**Comment by aaronneon2** [comment]
Hi Malte,

I have the same issue too. What I did was used the More -> Share to share a Customer Payment record to an existing user. Then after the user login, he will see this error everytime he access Messaging and Customer Payments records.

Did you managed to solve this issue somehow?

Regards,
Aaron Neo

**Comment by Sqmir** [comment]
Hi, 

i found a solution which worked for me, you can see it her:
https://www.odoo.com/fr_FR/forum/help-1/question/error-in-messaging-app-valueerror-invalid-field-state-in-leaf-osv-extendedleaf-state-in-draft-sent-cancel-on-mail-message-ctx-65251

Hope it will solve your problem

**Comment by aaronneon2** [comment]
Thank you Sqmir for your reply!  Your reply pointed me in the right direction to find a solution.
So this is what I did to eliminate the error. In case anyone is also trying to find a solution.

I went to Settings -> Technical -> Security -> Record Rules and found a record rule created with name containing "Sharing filter created by user XYZ". Unchecked "Active" field and Save. However, error still there.
Then I realised there is a Group created for the share in the Groups section.
I removed the user from the group and that eliminated the error.
Thinking the record rule would be redundant, i also deleted the record rule.

Hope this helps anyone else.

Regards,
Aaron Neo

**Comment by Yenthe666** [comment]
Hi @maltehelmhold ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
