### ISSUE TITLE
CANNOT SIGN IN in my new odoo14 website.. it says oops something went wrong no matter what credentials i enter.. i dont understand what went wrong

### ISSUE THREAD

**Issue by jaybhatia1706** [odoo/odoo#67798]
Impacted versions:odoo14

Steps to reproduce:

Current behavior: i am new here i dont  what to do ..try borlaug-chemicals.com and try sign up or sign in

Expected behavior:

Video/Screenshot link (optional):
![2021-03-13](https://user-images.githubusercontent.com/80581949/111030011-5f215180-8419-11eb-9f23-f7bb2e114181.png)
![2021-03-08](https://user-images.githubusercontent.com/80581949/111030017-69435000-8419-11eb-9560-0b121cdf4ae9.png)
![2021-03-13 (2)](https://user-images.githubusercontent.com/80581949/111030021-706a5e00-8419-11eb-8948-0876f9b520dd.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/14.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).
