### ISSUE TITLE
[8.0] Bad conversion of Datetime field to Date format

### ISSUE THREAD

**Issue by sergueikp** [odoo/odoo#6779]
[8.0] Bad conversion of Datetime field to Date format
Impacted versions:

8.0 (Nightly build odoo-8.0_20150512) on Ubuntu 14.04 and on Windows 7

Steps to reproduce:
Create fields in _inherit = 'sale.order.line'
 date_depart = fields.Datetime (string='Date de depart', required=True)

 date_depart_filtre = fields.Date (string='Date de depart pour filtrage', compute='_get_filter_date', store=True)

Create function to copy value from Datetime to Date field:
@api.one
@api.depends('date_depart')
    def _get_filter_date(self):
        if not (self.date_depart):
            self.date_depart_filtre = self.date_depart
            return

Current behavior:
My local timezone is Europe/Paris. 
Enter the Date and time in Datetime field.
The Datetime format is converted in Date format not in local timezone but in UTC. 
eg. datetime value  2015-05-18 01:59 is converted in to 2015-05-17. 
But 2015-05-18 02:00 is converted in to 2015-05-18. 

Expected behavior:
The Datetime value should be converted in Date format using local timezone.

Thank you very much for help and correcting this bug.
Best regards.

**Comment by iceship** [comment]
I hope this will help your problem.

import pytz

timezone = pytz.timezone(self._context.get('tz') or 'UTC')
self.date_depart_filtre = timezone.localize(datetime.strptime(self.date_depart,'%Y-%m-%d %H:%M:%S')).astimezone(pytz.UTC)

**Comment by sergueikp** [comment]
Hi Iceship, thank you, I will try your solution. 
I've got the same issue with datetime timezone in Qweb report. Can you indicate me how can I import pytz in Qweb report, thus I will try your solution in Qweb reports also. 
Datetime values in tags like t-esc are not converted in user timezone, can you please, indicate me a simple way to convert fields like this : 
<span t-foreach="docs[-1]" t-as="o">
<t t-esc="o.date_depart"/>
</span>
into user timezone ?
I have to use t-esc for datetime because I need to use a loop on the tree view and need to retrieve the value of the first and last row of the list, and this does not work with t-field tags.

Thank you in advance!

**Comment by sergueikp** [comment]
Hi iceship, I did not managed to work your code of timezone conversion, but this one is working fine:
@api.one
    @api.depends('date_depart')
    def _get_filter_date(self):
        if not (self.date_depart):
            self.date_depart_filtre = self.date_depart
            return
        my_tz = pytz.timezone(self._context.get('tz') or 'UTC')
        #my_tz = pytz.timezone('Europe/Paris')
        utc_tz = tz.tzutc()
        my_dt = datetime.strptime(self.date_depart,'%Y-%m-%d %H:%M:%S')
        utc_dt = my_dt.replace(tzinfo=utc_tz)
        self.date_depart_filtre = utc_dt.astimezone(my_tz)
        return
What do you think about this solution ?

**Comment by sergueikp** [comment]
Here is final solution, 
@api.one
    @api.depends('date_depart')
    def _get_filter_date(self):
        if not (self.date_depart):
            self.date_depart_filtre = self.date_depart
            return
        my_tz = pytz.timezone(self._context.get('tz') or 'UTC')
        #my_tz = pytz.timezone('Europe/Paris')
        utc_tz = tz.tzutc()
        my_dt = datetime.strptime(self.date_depart,'%Y-%m-%d %H:%M:%S')
        utc_dt = my_dt.replace(tzinfo=utc_tz)
        self.date_depart_filtre = utc_dt.astimezone(my_tz)
        return
