### ISSUE TITLE
BUG in Multi-website login

### ISSUE THREAD

**Issue by imanie383** [odoo/odoo#67799]
Impacted versions: 12.0

Steps to reproduce:
1.- Activate Free sign up on the website
2.- Register a user with login = imanie383@me.com
3.- Activate Specific User Account in the same website
4.- Register a user with login = imanie383@me.com

Video on odoo/runbot-enterprise 12.0
https://user-images.githubusercontent.com/35231827/111033380-98849d80-83d6-11eb-9e68-a5feb17f7c9f.mp4

Current behavior:
There may be a user.website_id == False and user.website_id = 1
 with the same login,

That occasions that the login returns two records and fails in
user = user.sudo(user.id)

Expected behavior:

if you return two users in the login you must limit the _get_login_domain to the .get_current_website ()

Video/Screenshot link (optional):
https://user-images.githubusercontent.com/35231827/111033380-98849d80-83d6-11eb-9e68-a5feb17f7c9f.mp4

Support ticket number submitted via odoo.com/help (optional):

**Comment by JKE-be** [comment]
Backport wip: https://github.com/odoo/odoo/pull/67815

**Comment by imanie383** [comment]
But with the limit return the first user not the one of the current website

**Comment by JKE-be** [comment]
https://github.com/odoo/odoo/pull/67815/files#diff-a46ceea50883b6d9ada4232dd4ba4eff01d3ca52161208f83096d31b234a884fR37

Return the more specific user first

```sql
blogprod=# insert into res_users(login, website_id, company_id, partner_id, notification_type) VALUES ('user_generic', null, 1, 1, 'mail');
INSERT 0 1
blogprod=# insert into res_users(login, website_id, company_id, partner_id, notification_type) VALUES ('user_specific', 1, 1, 1, 'mail');
INSERT 0 1
blogprod=# select website_id, login from res_users where login ilike 'user_%' order by website_id, company_id;
 website_id |     login     
------------+---------------
          1 | user_specific
            | user_generic

```

**Comment by JKE-be** [comment]
Thanks for reporting. 
The commit has been backported in v12 and 12.3.

**Comment by imanie383** [comment]
Thank you
