### ISSUE TITLE
Update Google icon on login page

### ISSUE THREAD

**Issue by amcgeough** [odoo/odoo#67810]
Impacted versions: 12.0/13.0/14.0

Steps to reproduce: Enable Google Oauth Authentication and log out

Current behaviour: Google+ 'fa-google-plus-square' icon displays on odoo login page beside 'Log in with Google' button

Expected behaviour: Google+ is now deprecated by Google, icon needs to be updated i.e. 'fa-google' instead

**Comment by khalidelhaji** [comment]
I have tried to address this issue in #67813, but it should be noted that many i18n files still use the outdated logo.
