### ISSUE TITLE
We should append instead to replace the values in the `invoice_vals['invoice_line_ids']` with new data from the invoiceable_lines

### ISSUE THREAD

**Issue by davidtranhp** [odoo/odoo#67828]
We should append instead to replace the values in the `invoice_vals['invoice_line_ids']` with new data from the invoiceable_lines
```python
            invoice_vals['invoice_line_ids'] += [
```

_Originally posted by @davidtranhp in https://github.com/odoo/odoo/pull/63717#discussion_r594218826_

**Comment by pedrobaeza** [comment]
Closing as there's a PR and not enough information in this issue.
