### ISSUE TITLE
oe_structure extension views are deleted when updating theme

### ISSUE THREAD

**Issue by yajo** [odoo/odoo#67834]
Impacted versions: 12 (not tested others)

Steps to reproduce:

1. Create a theme.
2. The theme defines in some template view a `<div id="oe_structure_01" class="oe_structure oe_empty"/>` element.
3. Install theme.
4. Go to that page on website.
5. Edit.
6. Drag some block into that element.
7. Save.
8. At this point, a new extension view has been created automatically.
7. Update theme.

Current behavior: The extension view is removed, and the user edits in that page disappear.

Expected behavior: The extension view should remain.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

@Tecnativa TT28769

**Comment by Yenthe666** [comment]
@JKE-be

**Comment by adar2378** [comment]
@yajo What was the fix? Is this approach wrong? Could you please help me to understand it, TIA.

**Comment by yajo** [comment]
I can't remember, but have you been able to reproduce it in modern Odoo versions?
