### ISSUE TITLE
Documentation on /shop/checkout?express=1 vs /shop/checkout?

### ISSUE THREAD

**Issue by tractionrnd** [odoo/odoo#67892]
Impacted versions:  13

Steps to reproduce:  In Runbot (v13) - log in as admin/admin.  Add a product to the web cart.  Then hover-over the Proceed To Checkout button and see the system adds "?express=1" to the URL, which will bypass the Address Selection screen.

Current behavior:  It seems the Web Cart is always adding ?express=1 to the "Proceed To Checkout" function.  Where is this setting, and how can we turn off?  It is not documented anywhere, and if the customer wants clients to "verify the shipping" instead of skipping right to delivery method, there does not appear to be a way to do this?

Expected behavior:  A setting somewhere where we can turn off "Express Checkout" 

Video/Screenshot link (optional):  https://6701824-master-all.runbot54.odoo.com/shop/cart

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
