### ISSUE TITLE
Leave and Allocation hours not displayed correctly if calendar different than 8h per day

### ISSUE THREAD

**Issue by Shide** [odoo/odoo#67915]
https://github.com/odoo/odoo/blob/bb43c74dd10c76b8a80d5749106b86432b13909e/addons/hr_holidays/models/hr_leave.py#L417

If an employee has a different calendar rather than 8 hours per day, this can be displayed incorrectly.

This line should be 
```python
holiday.number_of_hours_display = number_of_hours or (holiday.number_of_days * (calendar.hours_per_day or HOURS_PER_DAY))
```
> Replaces constant `HOURS_PER_DAY` by `(calendar.hours_per_day or HOURS_PER_DAY)`

Same approach as allocation function `_compute_number_of_hours_display`:
https://github.com/odoo/odoo/blob/bb43c74dd10c76b8a80d5749106b86432b13909e/addons/hr_holidays/models/hr_leave_allocation.py#L212

**Comment by pedrobaeza** [comment]
Odoo version? Is the same on upper versions?

**Comment by Shide** [comment]
Version 12.0

On version 13, that line are as I've wrote:

https://github.com/odoo/odoo/blob/df434b63ddf9b54377d224b8ff29703dbcd95ada/addons/hr_holidays/models/hr_leave.py#L477

**Comment by Shide** [comment]
CLA PR 
https://github.com/odoo/odoo/pull/67917

FIX PR:
https://github.com/odoo/odoo/pull/67918

**Comment by pedrobaeza** [comment]
OK, closing this as there's a PR.

**Comment by Shide** [comment]
@pedrobaeza Both of these PRs are mine, but cannot be merged due to CLA branch lock.
You can make these PRs pass or remove these PRs and upload the fix by yourself.

**Comment by pedrobaeza** [comment]
I think you are not using the same committer email than the one put in the CLA.

**Comment by pedrobaeza** [comment]
Anyway, wait for feedback about backporting this and if it's going to be accepted before going further IMO.
