### ISSUE TITLE
Cookies problem prevents switching from one server to another

### ISSUE THREAD

**Issue by alejandrosantana** [odoo/odoo#6792]
## Impacted versions:

- 8.0 at least

## Steps to reproduce:

- Login to a database in one server or instance (if more than one Odoo in the same server). Log out.
- Try to access other server or instance (in another port, of course, in the same machine).

## Current behavior:

- If you just login to different databases in the same server/instance, everything is OK.
- When you try to change server/instance, browser shows "Internal server error", yet server log shows nothing. (Tested in Chromium and Firefox, under Kubuntu 14.04)
- F5 does nothing
- If you delete cookies and hit F5, Odoo loads correctly. (But this something many final users are not willing or even capable)

## Expected behavior:

- Be able to switch among several Odoo in different servers without problems.

Flawless switch between databases

**Comment by odony** [comment]
Could you provide more details regarding the setup of your "several Odoo in the same server". Are they running on different public ports? Are they behind a reverse proxy such as nginx?
Do you see any errors in the log when the problem happens? What is the cookie domain you get when the problem happens, and what is it in the new cookie after your delete the cookies and refresh? Thanks!

**Comment by alejandrosantana** [comment]
@odony  In further testing I have detected it happens even within the same instance, when trying to change from one DB to another. So I believe the problem is not several instances, but the session cooky of one DB, preventing to swith to any other (in the same Odoo or another).

Steps:

1. Enter `http://localhost:8069` (or 8072 or whatever port) in browser.
  - I am redirected to `http://localhost:8069/web/database/selector` , everything OK.

2. I select a DB: **db1**, loads login for **db1**. I can login and use it OK.
  - Browser says: `http://localhost:32080/web/login?redirect=http%3A%2F%2Flocalhost%3A8069%2Fweb%3Fdb%3Ddb1`

3. Now, if I try to change to another DB: **db2**, I get a "Internal Server Error" in browser, nothing in server log, nor in JS console except the "Internarl Server Error" message.
  - Browser dir now is: `http://localhost:8069/web/login?db=db2`

4. At this point, if I delete session cookies an refresh the page, the login page for **db2** appears and I can log in it. But, obviously, if now I try to swith to the fisrt DB **db1**, it gives me an "Internal Server Error".
 


For testing I used these configs:
- Server in Kubuntu14.04, but also tested in UbuntuSever14.04
- Browsers:
  - Chromium 41.0.2272.76 Ubuntu 14.04 (64-bit)
  - Firefox 37.0.2
- Nginx and no nginx, did not mean any difference.
- *localhost*, but happens the same accessing by IP:port to a remote server
- Different port for each Odoo instance, no interferring with anything else. for example, I may use `localhost:8069` and `localhost:30080`. Happens the same in both.
- I launch them, some with `openerp-server` and others with `openerp-gevent`, no difference.
- There is no error shown in server log, although "Internal server error" is shown in browser.

It passed quite some time since last `git pull` (maybe 4 months, so I am not helping much it timespan), but this behaviour didn't happen before. I could change as many times as I wanted, without needing to delete cookies.

**Comment by KangOl** [comment]
Commit 8a430c4a238912b45e3c4d805bb78a1131dd7612 indirectly fixes your problem.

When you change the database in the database selector, you are logged out then redirected through an exception. The handling of this exception should not try to serve you an attachment matching the url.

**Comment by odony** [comment]
@alejandrosantana Could you test commit 8a430c4a238912b45e3c4d805bb78a1131dd7612 and see if it fixes your problem? Thanks!

**Comment by alejandrosantana** [comment]
@odony @KangOl Yes, that solves the problem, so I am happy and will close this issue.
But anyway, shifting database is handled with an exception? Sounds weird.

**Comment by odony** [comment]
@alejandrosantana Thanks for the feedback. Regarding the exception, yes and no. If you care about the details: it so happens that when you switch database you have a mismatch between the database in your session and the database you are trying to load. This requires an URL redirect that will update your session accordingly. And the internal mechanism to abort a page load and trigger a redirect relies on a special kind of "Response" that is also an Exception, so it can be raised. This is part of the werkzeug framework internals, not quite specific to Odoo, actually.
The reason for the problem you had is a change in the way we handle 404 errors (page not found), which did not properly distinguish true 404 errors from the special "Redirect" exception pages, in some cases, and triggered the wrong behavior.
Not sure this explanation is very clear, but it's hard to explain without discussing all the implementation details ;-)

**Comment by alejandrosantana** [comment]
@odony Thanks for the explanation. Good enough to understand the main aspects, although I am no werkzeug or web expert.
