### ISSUE TITLE
translate() function throws an exception in case both name and source are False

### ISSUE THREAD

**Issue by andreinl** [odoo/odoo#67962]
Impacted versions: 12

Steps to reproduce: write _sql_constraints with the third parameter set to False and try to save the wrong record

Current behavior: psycopg2.ProgrammingError: no results to fetch

Expected behavior: Should appeare a form with inst.pgerror message inside

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
Why is this a valid use case? You should fill all the sql_constraints expected arguments.

**Comment by Yenthe666** [comment]
Indeed, to me it is misuse.

**Comment by andreinl** [comment]
> Why is this a valid use case? You should fill all the sql_constraints expected arguments.

Sometimes (when you process more than one record at a time) it is better to have a raw error message than anonymous generic description. Obviously it will be better if we can use variables in sql_constraint message but we can't.

**Comment by andreinl** [comment]
I can say it is expected that translate() can return False sometimes:

`raise ValidationError(tr(registry._sql_error[key], 'sql_constraint') or inst.pgerror)`

This code is in core model.py module

**Comment by pedrobaeza** [comment]
I still don't understand the use case, but you can try to put a PR improving it, but for sure this won't be accepted on stable versions, so it has to point to master branch

**Comment by mart-e** [comment]
Hi,

Indeed, as said Pedro, don't hesitate to submit a PR against master version to make the framework more tolerant but we won't consider this as a bugfix for stable and definitly not in 12.0.
