### ISSUE TITLE
[8.0] Unnecessary account move line form bank statement

### ISSUE THREAD

**Issue by adrienpeiffer** [odoo/odoo#6799]
Hi,

In some cases, unnecassary move line is genereted from the bank statement reconcilation with taxes.
In this example we will use a 21%.

Here, a scenario on runbot 8.0
## Steps to reproduce
- Create a bank statement with a line with an amount of -121.00
- Click on 'Reconcile'
- Click on 'Choose a counterpart'
- Change account to 656000 (Belgium PCMN)
- Change amount to -100.00
- Change tax to VAT-IN-V81-21
- Click on 'Ok' button
- Go on Journal Entry tree view
- Open the created entry

![2](https://cloud.githubusercontent.com/assets/8035793/7746719/ee45f27a-ffb4-11e4-9b64-be4b5a9e1634.png)

We can see a tax move line with debit, credit equal to 0.0, tax code isn't set but there is a tax amount and account use in this line not corresponding with account in the tax definition (No account in tax definition). The expected behavior is to not have this line.

Thanks,

**Comment by adrienpeiffer** [comment]
OPW 640447

**Comment by Yenthe666** [comment]
Hi @adrienpeiffer ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: I'm going to guess this has been fixed back then to be honest.

Regards,
Yenthe
