### ISSUE TITLE
[8.0] Project Issue Access Error for Portal Users when 'Invoice working time on Issues' enabled

### ISSUE THREAD

**Issue by georodop** [odoo/odoo#6800]
**Problem**: I get an Access Error when Portal Users try to view an issue.

**Hint**: It happens only if 'invoice working time on issues' is enabled.

**Steps to reproduce the problem**:

```
1. Provide Portal Access to one of the customers

2. Create a new Project and a Project Issue related to this customer and add this customer 
as a follower to the project and the issue

3. Go to Settings --> Configuration --> Project and enable the option 'invoice working time
on issues' under 'Helpdesk & Support '

4. Login to the portal using the account of the aforementioned customer and try to view 
the issue
5. Notice the error:

    AccessError
    Sorry, you are not allowed to access this document. Only users with the following 
    access level are currently allowed to do that:
    - Human Resources/Officer
    - Human Resources/Employee
    - Human Resources/Employee
   - Human Resources/Employee
    - Project/User
    - Project/User
    (Document model: hr.analytic.timesheet)

6. Go to Settings --> Configuration --> Project and disable the option 'invoice working 
time on issues' under 'Helpdesk & Support ' 

7. Login to the portal using the account of the aforementioned customer and try to 
view the issue. This time there is no error!
```

**I can reproduce the problem on runbot** by just adding the Demo Portal User as follower to a project and a related issue and then logging in using Demo Portal User.

**Comment by RodGer-GR** [comment]
Related question on Odoo help forum:
https://www.odoo.com/forum/help-1/question/issues-portal-access-and-invoice-working-time-on-issues-how-to-fix-access-error-85613

I'm looking for a way to fix (at least as a work-around):
I tried modifying the view in order to hide the timesheet related fields from the portal users using the groups attribute. 

Just for testing I tried modifying the file 
/addons/project_issue_sheet/project_issue_sheet_view.xml 
but with no luck. Is there any chance we can prevent the error by hiding the related fields using the groups attribute ?

**Comment by avanzella** [comment]
This issue is still present in v9c+E.
Is there any solution available ?
Regards.

**Comment by Yenthe666** [comment]
Hi @georodop ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
@avanzella I've tried this on V9E but it seems to work with the latest V9. If you can still reproduce it you're free to create a new report!

Regards,
Yenthe
