### ISSUE TITLE
[13.0]: Update a name of field in res users

### ISSUE THREAD

**Issue by yousef-soliman** [odoo/odoo#68047]
Impacted versions:
13.0

Steps to reproduce:
- Create a New Module 
- Add a new field (python, xml) named "test_boolean"
- Add a new group
- Add the manifest 
- Add data like this
```
    "data": [
        "security/res_groups.xml",
        "views/res_users.xml"
    ],

```
- Change the name of field in ("python and xml") named as "test"

Current behavior:
- Raise an Error that the old field not found

```
Field `test_boolean` does not exist

Error context:
View `res.users.groups`
[view_id: 160, xml_id: base.user_groups_view, model: res.users, parent_id: 156]
None" while parsing /mnt/extra-addons/xmlrpc_utils/security/res_groups.xml:2, near
<odoo>

    <record id="group_edit_extraction" model="res.groups">
        <field name="name">Edit Extraction &amp; Acceptance</field>
        <field name="users" eval="[(4, ref('base.user_root')), (4, ref('base.user_admin'))]"/>
    </record>

</odoo>

```
Expected behavior:
not raise an error

--------------------------
i searched in code i found that Odoo update the xml form to include the groups fields in("view") in
`    def _update_user_groups_view(self):` 
so i think we need to update user form from files,  before update_user_groups

**Comment by unjoss** [comment]
hello, I had the same issue before and this one worked for me:  https://www.odoo.com/es_ES/forum/ayuda-1/add-custom-field-to-customer-model-181355

**Comment by Yenthe666** [comment]
Needs a terminal update, not a bug. It has been like this for years.

**Comment by yousef-soliman** [comment]
@Yenthe666  i am using terminal update
`docker-compose run --rm -p 8069:8069 odoo --log-level debug -d test -u test_module`

**Comment by yousef-soliman** [comment]
i think all we need to try update user forms before add groups fields

**Comment by yousef-soliman** [comment]
@unjoss in my case there is a xml error not a python error
