### ISSUE TITLE
This line raise an error if the user does not have a sale group

### ISSUE THREAD

**Issue by sergiocorato** [odoo/odoo#68052]
Steps to reproduce: an user without permission to view sales will receive an error if he try to open stock production lot views here: https://github.com/odoo/odoo/blob/12.0/addons/sale_stock/views/stock_production_lot_views.xml

This line retrieves record without sudo():  https://github.com/odoo/odoo/blob/c0afa00d7cdbe98e4c67d2987a2b808bedd474ac/addons/sale_stock/models/stock.py#L126

Moreover, the views don't have sale groups.

**Comment by pedrobaeza** [comment]
As explained in the other issue, you need to explain steps to reproduce the problem.

**Comment by sergiocorato** [comment]
I was writing, done!

**Comment by Feyensv** [comment]
Well, by default, any stock user has access to SO's and SO lines but some other rules may conflict with this (e.g. if the user also has basic sales rights).

A simple sudo would fix the problem of opening the lot view, but the user still wouldn't have access to the related SO and this requires a deeper analysis to find the best fix.  I've created a bugfix ticket for this issue ;).

**Comment by sergiocorato** [comment]
Thanks!
> but the user still wouldn't have access to the related SO 
This behaviour seems logic - no errors and no buttons-fields shown to access the SO the user would not access anyway.
