### ISSUE TITLE
[14.0] QWEB Reports: style rendering

### ISSUE THREAD

**Issue by Abdulrahmannaser** [odoo/odoo#68084]
Impacted versions:
14.0 -Didn't try others-
Steps to reproduce:
Add this div in qweb report template
```html
<div style="column-count: 3;">
Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius.
</div>
```
Current behavior:
Displays the div as one block
Expected behavior:
Supposed to be 3 columns as [this example ](https://www.w3schools.com/cssref/tryit.asp?filename=trycss3_column-count) 
Note: It works fine in case the report type is qweb-html but doesn't work with qweb-pdf

**Comment by Yenthe666** [comment]
Maybe a limitation of QWeb in Odoo? @pedrobaeza do you know?

**Comment by pedrobaeza** [comment]
It's more a limitation of wkhtmltopdf, but nothing that can do. You can open an issue at that project to see if they support it.

Closing then as outside Odoo control (unless they change the HTML to PDF conversor, which is not going to happen in a stable version nor something planned for now).
