### ISSUE TITLE
Account invoice report read group error

### ISSUE THREAD

**Issue by ToubkalTech** [odoo/odoo#68087]
Impacted versions: 13

Steps to reproduce:
![account_invoice_report_read_group_error_v13](https://user-images.githubusercontent.com/74025293/111637766-09262280-87fa-11eb-90b8-8f5760e9f4c2.PNG)

Current behavior: Account invoice report read group error

Expected behavior:

Video/Screenshot link (optional): See Screenshot

Support ticket number submitted via odoo.com/help (optional):

**Comment by Yenthe666** [comment]
Please add steps on how to reproduce it on runbot.odoo.com :)
