### ISSUE TITLE
Config allows overriden

### ISSUE THREAD

**Issue by hoangtrann** [odoo/odoo#68124]
Impacted versions: 12.0, possible 13.0 and 14.0

Steps to reproduce:
In any python file that is loaded on init, import `config` from `odoo.tools` and set attribute. I spotted this on Odoo.sh

Current behavior:
Value parsed from config file can be override by python code

Expected behavior:
Not allowing override attribute of config using python code

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
I don't see this specially problematic or a source of any leak or source of problem, but I let others to decide. At the end, this is how Python works with the variables, but all the relevant config options have been already applied.

@xmo-odoo maybe you are the one for saying something about this?

**Comment by xmo-odoo** [comment]
@pedrobaeza your analysis seems completely correct. Python code can do essentially all it wants, and though there are some limitations in that module code is only called after a certain point you could still swap modules, restart servers, etc...

Unless this is accessible from "restricted" contexts (e.g. server actions) it's expected behaviour.

**Comment by hoangtrann** [comment]
Thanks for your insight. Side question, how would you manage that configs like `limit_time_real` or `memory_limit_soft` being overridden on infrastructure like Odoo.sh?

**Comment by xmo-odoo** [comment]
> Thanks for your insight. Side question, how would you manage that configs like `limit_time_real` or `memory_limit_soft` being overridden on infrastructure like Odoo.sh?

This is more of a question for @amigrave or @Icallhimtest as I don't really deal with odoosh, but I can see two possible issues there (broadly):

* infrastructurally I expect the odoo.sh containers have their own external limits to avoid abuse, so these updates would not do anything to odoosh itself though it might get your instance throttled or restricted by some abuse mitigation system
* internally, as ever if you install untrusted code it could wreck havoc on your instance, it could DOS you by triggering abuse mitigation but that seems low-potato when the untrusted app could just as well crash your system in a loop, steal your data, etc...

**Comment by amigrave** [comment]
@hoangtrann you can't do that. I will not discuss it here because github is not the place for Odoo.sh support, please use https://www.odoo.com/help instead. Also note that this particular question will be answered in the Odoo.sh FAQ soon.
