### ISSUE TITLE
[8.0] Bug on expected date when we merge purchase order

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#6815]
Hi Odoo ,

I found a bug on expected date purchase order,
It will be disappear and I cannot filled it manually.

So here is how to produce:
1.  Merge two purchase order.
2.  The system will merge it, and show the merge purchase order.
3.  In that purchase order the expected date will be disappear, and we can’t filled it.

The expected behavior: it must be based on the schedule date on purchase order line not just disappear.

You can test it on runbot, we found the same behavior.

**Comment by Yenthe666** [comment]
Hi @falinwa,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
