### ISSUE TITLE
[14.0] website_sale_stock: free_qty should be used instead of virtual_available

### ISSUE THREAD

**Issue by tanghulu0608** [odoo/odoo#68185]
Impacted versions:
[14.0]

**Steps to reproduce:**
1. Create a new product: p1.  Update onhand qty 100. Publish it, then 100 is show on the shop. This is OK.

<img width="1406" alt="image" src="https://user-images.githubusercontent.com/5561864/111935913-776f2b80-8aff-11eb-80ac-5bedba8bb55a.png">

2. Create a new purchase order with 100 p1. Then confirm the purchase order.
<img width="1677" alt="image" src="https://user-images.githubusercontent.com/5561864/111936061-c7e68900-8aff-11eb-8eba-b7263a06b4e4.png">

3. As we expect, p1 is 100 on hand ,150 forecasted. This is ok.

<img width="795" alt="image" src="https://user-images.githubusercontent.com/5561864/111936085-dcc31c80-8aff-11eb-8f85-8e0931b36586.png">

4. Open product p1 in website shop, It shows 150 Units available. This is not ok. Because the purchase order is not received now. Also it maybe wouldn't be received at all.

<img width="1407" alt="image" src="https://user-images.githubusercontent.com/5561864/111936242-417e7700-8b00-11eb-9a6b-7f6d4374fbff.png">

**Expected behavior:** 
In some use case this is not good. Customer buy the product on website shop, but it can not deliveried.
Maybe odoo can add a website option: to allow the system manager to decide use free_qty or virtual_available on website shop.

**Comment by pedrobaeza** [comment]
I agree the virtual quantity is not the more suitable one, as you can have confirmed purchase orders which receptions are several months in the future. It should be selectable.

Meanwhile, you can check https://github.com/OCA/e-commerce/tree/13.0/website_sale_stock_available and https://github.com/OCA/e-commerce/pull/492 (not available yet for 14.0).

@JKE-be is your team responsible of this?

**Comment by JKE-be** [comment]
We don't consider it as a bug, and don't plan to change it in stable.

But we have a wip branch that already change it for v15: https://github.com/odoo/odoo/pull/67132/files#diff-9db95dd51674ba759a767208a1239bcbaeaa48a1b229867c0e4946a0313a6793R34

@pedrobaeza, not an option 'selectable' as you suggested, but always the available qty.

Thanks for reporting

**Comment by pedrobaeza** [comment]
Thanks for the follow-up. If I understand correctly, it's going to use `qty_available`, but that doesn't exclude reserved quantity, so it isn't still the valid quantity IMO. Why not using `free_qty`?

**Comment by JKE-be** [comment]
I will double check that, thanks for your follow-up ;)

**Comment by tanghulu0608** [comment]
I write these code in my project.


class ProductTemplate(models.Model):
    _inherit = "product.template"


    def _get_combination_info(self, combination=False, product_id=False, add_qty=1, pricelist=False, parent_combination=False, only_template=False):
        combination_info = super(ProductTemplate, self)._get_combination_info(
            combination=combination, product_id=product_id, add_qty=add_qty, pricelist=pricelist,
            parent_combination=parent_combination, only_template=only_template)
        if combination_info['product_id']:
            product = self.env['product.product'].sudo().browse(combination_info['product_id'])
            website = self.env['website'].get_current_website()
            virtual_available = product.with_context(warehouse=website.warehouse_id.id).free_qty
            combination_info.update({
                'default_code': product.default_code,
                'virtual_available': virtual_available,
                'virtual_available_formatted': self.env['ir.qweb.field.float'].value_to_html(virtual_available, {'precision': 0}),
            })
        return combination_info

**Comment by tanghulu0608** [comment]
@JKE-be  I think free_qty is very suitable to use here.

**Comment by JKE-be** [comment]
Yes, I already ask to my colleague to adapt it in his PR.

ty

**Comment by tanghulu0608** [comment]
@JKE-be  Thanks. When the pr created, please let me know it .

**Comment by tanghulu0608** [comment]
Good job
