### ISSUE TITLE
8.0 General Ledger filter by period including initial balances give wrongs results

### ISSUE THREAD

**Issue by paulius-sladkevicius** [odoo/odoo#6818]
When user choose periods they are ignored and a first period is taken who have earliest start date.
I would suggest to take a start date from period.

When General Ledger is printed by date filter it use date from, so if you print for e.g. from period 2015-02 to 2015-03 and similar dates e.g. 2015-02-01 to 2015-03-31 you get different results for initial balance what should not be a case.

Additionally when period filter are using combining with initial balance it takes oldest period, even from a different fiscal year.
Issue is lying here: https://github.com/odoo/odoo/blob/8.0/addons/account/account_move_line.py#L82

**Comment by Yenthe666** [comment]
Hi @paulius-sladkevicius,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
