### ISSUE TITLE
How to execute sql in batches

### ISSUE THREAD

**Issue by ajaxjsonspring** [odoo/odoo#68189]
How to execute sql in batches
![image](https://user-images.githubusercontent.com/18209434/111972337-51b24880-8b38-11eb-927f-80431309f4e2.png)

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
