### ISSUE TITLE
TypeError: unhashable type: 'list' when creating partners in crm opportunities

### ISSUE THREAD

**Issue by rruebner** [odoo/odoo#6821]
Hi all,

This problem is something special but maybe someone can help.

We want to provide some additional information like phone, fax and partner categories for partners in the contact tab (it is a kanban view) of partner companies for one of our customers. One of their workflow is to create partner companies with related partners within crm opportunities. This leads to an "TypeError: unhashable type: 'list'" error when closing the partner modal view in the partner company detail view. I make a video for a better understanding of the problem (first I simulate the partner view inheritance and than I create the partner company with related partners within a crm opportunity). If you close the error modal and save all stuff you will see that the partner will be created but the error is still disturbing our customer.
Some additional information: If I take out the partner categories no error is shown. If I add partners in the partner company view in Messaging -> Organizer -> Contacts no error is shown. This error only happens when I use the steps described in the video.

[Video](https://www.youtube.com/watch?v=WB-jKPH9Lrs)

**_Impacted versions:**_
- 8.0

**_Steps to reproduce:**_
- in runbot version 8, see the video for detailed steps

**_Current behavior:**_
- see the video for the result
- the error log

```
Odoo Server Error
Traceback (most recent call last):
  File "../openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "../openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "../openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "../openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "../openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "../openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "../openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "../addons/web/controllers/main.py", line 936, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "../addons/web/controllers/main.py", line 928, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "../openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "../openerp/addons/base/res/res_partner.py", line 105, in name_get
    for category in self.browse(cr, uid, ids, context=context):
  File "../openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "../openerp/models.py", line 5207, in browse
    return self._browse(Environment(cr, uid, context or {}), ids)
  File "../openerp/models.py", line 5200, in _browse
    env.prefetch[cls._name].update(ids)
TypeError: unhashable type: 'list'
```

**_Expected behavior:**_

Adding partners in the partner company view while I am in a crm opportunity should work like I would do it in Messaging -> Organizer -> Contacts regardless of the partner view inheritance.

Regards, Robert

**Comment by Yenthe666** [comment]
Hi @rruebner,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
