### ISSUE TITLE
No recognize bootstrap 4 styles in report PDF

### ISSUE THREAD

**Issue by winaytel** [odoo/odoo#68216]
**### Impacted versions**:14.0

**Steps to reproduce**: To print report in PDF no recognize any bootstrap 4 styles . 

**Current behavior**:No recognize all bootstrap styles

**Expected behavior**: The PDF report should have the same styles that in web version

**Note** : My other reports made without bootstrap are printing well. My parameters web.url and report.url are well configured .

**Comment by pedrobaeza** [comment]
Duplicated of #28681
