### ISSUE TITLE
Once in a while a lot of longpolling requests on 8072 port are staying in "CLOSE_WAIT" state which is causing connecting/disconnecting issue and session expired issue. In that period no new requests are accepted on 8072 port. 

### ISSUE THREAD

**Issue by gekkaBee** [odoo/odoo#68220]
**Impacted versions:**
Odoo 13.0

**System Parameters:**
CPU Cores - 8 
RAM - 128 GB 

**Nginx Configuration**
server {
  listen 80;
  client_max_body_size 25M;

  location /longpolling {
   proxy_read_timeout 3600;
   proxy_connect_timeout 3600;
   proxy_send_timeout 3600;
   proxy_set_header X-Forwarded-Host $host;
   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
   proxy_set_header X-Forwarded-Proto $scheme;
   proxy_set_header X-Real-IP $remote_addr;
   proxy_http_version 1.1;
   proxy_set_header Connection "";
   proxy_pass http://127.0.0.1:8072;
  }

  location / {
   proxy_read_timeout 300000;
   proxy_pass http://127.0.0.1:8069;
   proxy_redirect off;
   proxy_set_header Host $host;
   proxy_set_header X-Real-IP $remote_addr;
   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
   proxy_set_header X-Forwarded-Proto $scheme;
  }
}

**Odoo Configuration**

[options]
db_maxconn=64
logrotate = True
proxy_mode = True
longpolling_port=8072
workers = 13
limit_memory_hard = 5684354560
limit_memory_soft = 5147483648
limit_request = 8192
limit_time_cpu = 5600
limit_time_real = 7400
max_cron_threads = 3

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/14.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).

**Comment by fnaquira** [comment]
@gekkaBee did you manage to solve it? I am having the same trouble with Odoo CE 14

**Comment by gekkaBee** [comment]
@fnaquira No, I haven't been able to solve the issue.
