### ISSUE TITLE
Signup up and reset password always redirect to odoo website !

### ISSUE THREAD

**Issue by malakeel** [odoo/odoo#6828]
Under Settings >> Configuration >> General Settings:

Portal access:
We have two check boxes:
Enable password reset from Login page
Allow external users to sign up 

If we enable them, logout, and try to use any of these links, we will be redirected to odoo website:  

https://accounts.odoo.com/web/login?redirect= .... 

I am on a fresh odoo 8 install. Python 2.7 and postresql 9.4.1 

I am not sure if theres anything I need to do in the configuration to fix this, but it looks to me like a bug.

**Comment by lukebranch** [comment]
@malakeel ,

I'd recommend asking this question on the forums:

http://help.odoo.com

This is not a bug, this is a matter of configuration. Go to Settings >> General Settings >> and un-tick "Use external authentication providers, sign in with google, facebook, ..."

**Comment by kesturbo** [comment]
@lukebranch ,
But if unselect that option about external authentication, sign up does not work. Email and Name is inactive in form. How can I solve this issue ?

**Comment by Yenthe666** [comment]
Indeed - this is a case of configuration (database filter for example).
