### ISSUE TITLE
Export Data changes depending on steps taken

### ISSUE THREAD

**Issue by serkia** [odoo/odoo#6831]
Problem: Saving export fields will restore incorrect columns

Steps to reproduce:
(1) Under Warehouse > Inventory Adjustments
(2) Checkmark one of the previously created Inventory Reference's, then click (more) > export

From the Export Data popup window
(3) Select under Inventories > "Inventories/Location", and "Inventories/Product" and export to file
...export header will read...
id
line_ids/location_id/id
line_ids/product_id/id

....values will read...
**export**.stock_inventory_541
stock.stock_location_stock
**export**.product_product_1902

Save field list to use for later, and click Close
Repeat steps 1 & 2 and instead of manually selecting the columns, from the drop down select your saved export and export it. The exported file will have different values in both the header and obviously the rest of the data

...header row...
id
line_ids/location_id
line_ids/product_id

...values...
**export**.stock_inventory_541
WH/Stock
[750342PSA] Dangle 14K Pink Ribbon

**Comment by Yenthe666** [comment]
Hi @serkia,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
