### ISSUE TITLE
Print a devis

### ISSUE THREAD

**Issue by leuz20028** [odoo/odoo#6833]
Hello dear friends, I have a little problem for a long time.
I installed Odoo on Windows Server 2008 R2.
When you print a quote, he tells me that the file is 0 bytes.
I looked everywhere. Help me please.

![odoo print](https://cloud.githubusercontent.com/assets/12589537/7790586/e03344ce-027c-11e5-94e5-81551c5eced5.png)

Thanks

**Comment by lukebranch** [comment]
@leuz20028 ,

I think you may not have installed wkhtmltopdf in your system. I'd recommend closing this issue and asking this question in the forum here:

https://www.odoo.com/forum/help-1/question/wkhtmltopdf-on-v8-not-found-48208

**Comment by leuz20028** [comment]
Thanks but I have installed Wkhtmltopdf and I have mentioned the webkit_path
in parameters and systems within the parameters of Odoo. But it's still not good for me.

**Comment by sle-odoo** [comment]
It's working fine on the last version on [nightly](http://nightly.odoo.com/)
