### ISSUE TITLE
[14.0] Invoice from repair order with no lines

### ISSUE THREAD

**Issue by LoisRForgeFlow** [odoo/odoo#68370]
Since this commit (https://github.com/odoo/odoo/commit/fdc96de0e411760f84a78c36543f9157332346de), using the action to create an invoice from a repair generates an invoice with no lines.

Impacted versions: 14.0

Steps to reproduce:
1. Go to any of the demo repair order or create a new one.
2. Set a invoice method.
3. Click on "Create Invoice".

Current behavior:
No lines in the invoice.

Expected behavior:
Parts and operations should generate invoice lines.

Video/Screenshot link (optional):
![no-invoice-lines-repair](https://user-images.githubusercontent.com/23449160/112546035-373ad200-8db9-11eb-9090-cdebb99844b0.gif)

@ForgeFlow

**Comment by LoisRForgeFlow** [comment]
cc @oco-odoo

**Comment by Yenthe666** [comment]
Plus, on a sidenote, it is terrible that this landed in a stable >.<

**Comment by oco-odoo** [comment]
Got fixed here https://github.com/odoo/odoo/commit/952ff15a3af90bb32660262b4fd32ca8a1172eac
Thank you for reporting :)
