### ISSUE TITLE
plz som help for this problem i am bignier in odoo 

### ISSUE THREAD

**Issue by seifeddin** [odoo/odoo#6837]
![capture du 2015-05-25 03 57 11](https://cloud.githubusercontent.com/assets/12595044/7796260/4cf4a688-0292-11e5-919d-28c8ffd4c348.png)
![capture du 2015-05-25 03 57 24](https://cloud.githubusercontent.com/assets/12595044/7796262/4eb98fba-0292-11e5-8ac4-a1c6a90e096a.png)
![capture du 2015-05-25 03 57 31](https://cloud.githubusercontent.com/assets/12595044/7796261/4cf794f6-0292-11e5-820e-d5ea64f030cc.png)

the problem is AttributeError: 'module' object has no attribute 'float' som help please

**Comment by rop-odoo** [comment]
set   
 name=fields.Float() 
 fields.Integer()
in Demo.py

**Comment by seifeddin** [comment]
thnx but look at this 
this errur shwo after the fixed the first problem 
![capture du 2015-05-25 04 25 17](https://cloud.githubusercontent.com/assets/12595044/7796652/4ae324e2-0296-11e5-8606-296fe0868db5.png)

**Comment by jar-odoo** [comment]
change the field in demo.py file
name = fields.Integer(string="Quantity") to 
quantity = fields.Integer(string="Quantity")

**Comment by seifeddin** [comment]
thinx for help but i have anthor erreur it is bad day for me :p
![fs2](https://cloud.githubusercontent.com/assets/12595044/7797942/0b3778ae-02a8-11e5-89e7-aa3c319f4489.png)
![Uploading fs3.png…]()

**Comment by lukebranch** [comment]
@seifeddin ,

I'd recommend referring to the documentation here:

https://www.odoo.com/documentation/8.0/

and asking these types of questions on the forums. You'll find more people to answer your questions there.

**Comment by xtjie** [comment]
please learn a example module,then write program.or change example module.you should first  understand odoo`s  module structure.

**Comment by seifeddin** [comment]
thenk you you konow a good one please

**Comment by lukebranch** [comment]
@seifeddin ,

You may also want to pick up a book to teach you how to build Odoo modules. I've bought this one recently, and it should give you a good idea of where to start:

https://www.packtpub.com/big-data-and-business-intelligence/odoo-essentials

**Comment by seifeddin** [comment]
great thanx for you

**Comment by belkacem77** [comment]
You can take a look on tutorials availible on line.

**Comment by seifeddin** [comment]
i try that thinx @belkacem77

**Comment by Yenthe666** [comment]
As suggested - follow tutorials or read the book. This should have been closed back in 2015. 😆
