### ISSUE TITLE
survey: thank_you_message not included in form view

### ISSUE THREAD

**Issue by geraldaistleitner** [odoo/odoo#68381]
Impacted versions:
13.0

Steps to reproduce:
Create a survey and try to add a thank you message which is shown upon completion of the survey.

Current behavior:
The field thank_you_message is not editable, as it is just not shown in backend.

Expected behavior:
The field thank_you_message is editable in backend.

**Comment by pedrobaeza** [comment]
AFAIK that content is edited through the website, not in the backend. Can you confirm, @gdgellatly , as you have worked with surveys?

**Comment by Yenthe666** [comment]
Yep, it is through the frontend.

**Comment by pedrobaeza** [comment]
OK, thanks for confirming, so closing.
