### ISSUE TITLE
false quantity shown in Tracebility view (stock.move) when lot number is split

### ISSUE THREAD

**Issue by bastopoles** [odoo/odoo#6839]
When a lot number has been split (same product, 2 or more lot numbers) in a delivery order, a wrong quantity delivered per lot number is shown in the tracibility view. (Traceablility / Serial No. / Traceability )

The total number  delivered is shown for all lot numbers and not by quantity per lot actually delivered

**Comment by glomium** [comment]
+1

**Comment by AntMoreno** [comment]
I also agree.

This makes useless the traceability view/report, I can't understand how after nearly one year that this issue was opened it has not been addressed and there's only two people participating, when traceability is a key functionality for many companies.

**Comment by Yenthe666** [comment]
Hi @bastopoles,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
