### ISSUE TITLE
ValueError  Expected singleton: facturation.facturation(1, 2, 3, 8, 9, 10)

### ISSUE THREAD

**Issue by mohammedabbou** [odoo/odoo#6840]
plz any body help me     

this is my code.py
# -_\- coding: utf-8 -_-

from lxml import etree
from openerp import models, fields, api, _
from openerp.exceptions import except_orm, Warning, RedirectWarning
from openerp.tools import float_compare
import openerp.addons.decimal_precision as dp

class facturation(models.Model):
    _name = 'facturation.facturation'
    _order = 'patient asc'

```
patient = fields.Char('Patient')
date = fields.Date('date de la facture',size=30)
description = fields.Char('description')
comment = fields.Text('notes')

informations = fields.Text('informations')
invoice_line_ids = fields.One2many('facture.invoice.line','product_id',string='Invoice Lines')
amount_untaxed = fields.Float(compute='_compute_tota', string='Total à payer')

@api.multi
@api.depends('invoice_line_ids.total')
def _compute_tota(self):
    self.amount_untaxed = sum(line.total for line in self.invoice_line_ids)
```

class facture_invoice_line(models.Model):
    _name = "facture.invoice.line"

```
product_id = fields.Many2one('services.services', string='service')
description = fields.Char('description')
total = fields.Float(compute='_total', string='total',store=True)
quantit = fields.Float('quantité', default=1)
price_unit = fields.Float( string='Prix unitaire', required=True)
amount_untaxed = fields.Float(string='Total à payer', readonly=True)


@api.depends('quantit','price_unit')
def _total(self):
    self.total = self.quantit * self.price_unit
```

**Comment by Yenthe666** [comment]
Hi @mohammedabbou,

Thank you for your report.
The Github tracker however is only for bugs in the official code, not for asking questions about how to develop something.
You can ask this on the official help forums (help.odoo.com).
Closing as this is not a real bug.

Regards,
Yenthe
