### ISSUE TITLE
ValueError  Expected singleton: facturation.facturation(1, 2, 3, 8, 9, 10)

### ISSUE THREAD

**Issue by mohammedabbou** [odoo/odoo#6841]
plz any body help me     

this is my code.py

# -*- coding: utf-8 -*-
from lxml import etree
from openerp import models, fields, api, _
from openerp.exceptions import except_orm, Warning, RedirectWarning
from openerp.tools import float_compare
import openerp.addons.decimal_precision as dp

class facturation(models.Model):
    _name = 'facturation.facturation'
    _order = 'patient asc'

    patient = fields.Char('Patient')
    date = fields.Date('date de la facture',size=30)
    description = fields.Char('description')
    comment = fields.Text('notes')
   
    informations = fields.Text('informations')
    invoice_line_ids = fields.One2many('facture.invoice.line','product_id',string='Invoice Lines')
    amount_untaxed = fields.Float(compute='_compute_tota', string='Total à payer')
	
    @api.multi
    @api.depends('invoice_line_ids.total')
    def _compute_tota(self):
	    self.amount_untaxed = sum(line.total for line in self.invoice_line_ids)
		
		
class facture_invoice_line(models.Model):
    _name = "facture.invoice.line"
	
    product_id = fields.Many2one('services.services', string='service')
    description = fields.Char('description')
    total = fields.Float(compute='_total', string='total',store=True)
    quantit = fields.Float('quantité', default=1)
    price_unit = fields.Float( string='Prix unitaire', required=True)
    amount_untaxed = fields.Float(string='Total à payer', readonly=True)
	
   
    @api.depends('quantit','price_unit')
    def _total(self):
        self.total = self.quantit * self.price_unit

**Comment by ashraf92hesham** [comment]
i don't think that it is normal to make the many2one relation field in 'facture.invoice.line' NOT realted to 'facturation.facturation'.
 because facturation.facturation' has a one2many field which needs a many2one field in the related model.
try to do it like that :
 product_id = fields.Many2one('facturation.facturation', string='service')

**Comment by mohammedabbou** [comment]
nn because i need to make relation betwin  facturation modul and an other modul service's name

**Comment by ashraf92hesham** [comment]
ok you can make another field related to the services.services , but the field named 'product_id' must be related to facturation.facturation

**Comment by mohammedabbou** [comment]
ok svp dites que doit je faire exactement

**Comment by ashraf92hesham** [comment]
sorry, what do you mean ?

**Comment by mohammedabbou** [comment]
ok can you tel me exactly what i shoud i do??

**Comment by ashraf92hesham** [comment]
if you want the relation to go right you should do that: 
product_id = fields.Many2one('facturation.facturation', string='service')

and if you want to make a relation between  'facture.invoice.line' and 'services.services' you should make: 
new_field = fields.Many2one('services.services', string='relation field')

**Comment by mohammedabbou** [comment]
the problem is product_id  shoud be related to the modul's name  service  so when  i use this syntax  product_id = fields.Many2one('facturation.facturation', string='service')  its not waht i want to have  because  for mee  product_id   is  "service"

**Comment by mohammedabbou** [comment]
he problem is product_id shoud be related to the modul's name service
so when i use this syntax product_id =
fields.Many2one('facturation.facturation', string='service') its not
waht i want to have because for mee product_id is "service"

**Comment by mohammedabbou** [comment]
this is service's modul

**Comment by ashraf92hesham** [comment]
invoice_line_ids = fields.One2many('facture.invoice.line','product_id',string='Invoice Lines')
this line is telling the 'facturation.facturation' that it will be related to the 'facture.invoice.line' and the relation foreign key is 'product_id' , so it is not right to make the product_id NOT related to the 'facturation.facturation'

**Comment by mohammedabbou** [comment]
yes i know just tel me  how can i have relation beteen  service'modul  and facturation look at pictures that i sent to you

**Comment by ashraf92hesham** [comment]
sorry they are not appearing send them to ashrafhesham1992@gmail.com

**Comment by mohammedabbou** [comment]
oookk

**Comment by mohammedabbou** [comment]
this is my new code.py but again the same error   




# -*- coding: utf-8 -*-
from lxml import etree
from openerp import models, fields, api, _
from openerp.exceptions import except_orm, Warning, RedirectWarning
from openerp.tools import float_compare
import openerp.addons.decimal_precision as dp

class facturation(models.Model):
    _name = 'facturation.facturation'
    _order = 'patient asc'

    patient = fields.Char('Patient')
    date = fields.Date('date de la facture',size=30)
    description = fields.Char('description')
    comment = fields.Text('notes')
   
    informations = fields.Text('informations')
    invoice_line_ids = fields.One2many('facture.invoice.line','invoice_id',string='Invoice Lines')
    amount_untaxed = fields.Float(compute='_compute_tota',store=True, string='Total à payer')
	
    @api.v8
    @api.depends('invoice_line_ids.total')
    def _compute_tota(self):
	    self.amount_untaxed = sum(line.total for line in self.invoice_line_ids)
		
		
class facture_invoice_line(models.Model):
    _name = "facture.invoice.line"
    product_id = fields.Many2one('services.services', string='service')
    invoice_id = fields.Many2one('facturation.facturation', string='service')
    description = fields.Char('description')
    total = fields.Float(compute='_total', string='total',store=True)
    quantit = fields.Float('quantité', default=1)
    price_unit = fields.Float( string='Prix unitaire', required=True)
    amount_untaxed = fields.Float(string='Total à payer',  store=True, readonly=True)
	
    @api.v8
    @api.depends('quantit','price_unit')
    def _total(self):
        self.total = self.quantit * self.price_unit

**Comment by mohammedabbou** [comment]
thnx it woks now  :+1:

**Comment by ashraf92hesham** [comment]
you are welcome man :+1: 
you can close the issue now

**Comment by Leningsv** [comment]
Hola amigos resolvi el problema resulta que ese error se genera porque estamos intentando desplegar un objeto tipo lista para desplegar o trabajar con este objeto se lo puede hacer por medio de una lista, les dejo un ejemplo:
    @api.multi
    def onchange_get_organizer_account(self,auxType):
    if auxType:
        ids=self.env['gol.organizer.account'].search([['organizerType', '=', auxType]])
        auxIds=[]    
        for item in ids:
            auxIds.append(item.id) 
        print ids
        print auxIds
        return {'domain':{'organizerAccount':[('id','in',auxIds)]}}  


si kieren saber mas en mi pagina describo la solucion con mayora claridad

https://github.com/Leningsv/Odoo/wiki/Dominios,-Busquedas-(env,-browse,-search),-Filtros,-Agrupamientos
