### ISSUE TITLE
[8.0] Choose product from manufacture order too slow

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#6842]
Hi Odoo,

I found a bug when I want to choose product from manufacture order, (type a character in many2one field)
Its very slow, I need to wait for 5-6 seconds,
But when I choose product from other form like invoice line and sale order line,
It will be very fast, even I don’t need to wait 1 second for that.

Expected behavior:
When I choose product in manufacture it must be fast as I choose product from invoice line or sale order line.

I think in the environment, you must be have 50K product in database to have that kind of behavior.

Thank You.

**Comment by tesserB** [comment]
Falinwa,
We would have to see a sample of the code/gist to even approach this. That said, if you're still having issues with this and are willing to provide a little more detail:

Mailing Lists:
https://www.odoo.com/groups

Help Forum:
https://www.odoo.com/forum/help-1
 
Respectfully,
Cody K.
ckitterm@gmail.com

@mart-e , sir...
