### ISSUE TITLE
How to force product available in case of Waiting for another operation

### ISSUE THREAD

**Issue by rb3606** [odoo/odoo#68441]
Impacted versions: Odoo13

Steps to reproduce: Set product route Buy and Replish On Order , Create Sale order, Confirm (it create delivery and purchase order), But if i update qty manually then it should allow me deliver

Current behavior: Delivery order in Waiting for another operation

Expected behavior: But if i update qty manually then it should allow me deliver , without waiting for another operation. 

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
