### ISSUE TITLE
[12:0] res.partner.rule.private.employee

### ISSUE THREAD

**Issue by andrei-borcea** [odoo/odoo#68479]
Impacted versions: 12.0 (?)

Steps to reproduce: Create a new user and try to limit access to own customers

Current behavior: Sale agent during login get a 403 (rule disabled) or see all the customers is rule enabled

Expected behavior: Each user see own contacts/partners

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a development question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Comment by andrei-borcea** [comment]
I don't agree....this is not a development issue...as the main problem is inside Odoo...
This record rule in someway exclude any other rule for the model.This maybe its not a bug for sure its not a feature
