### ISSUE TITLE
V7/V8 - Check date in period

### ISSUE THREAD

**Issue by juli1r** [odoo/odoo#6850]
Hello,

we have found a bug in the accounting module regarding the feature "check date in period".

How to reproduce:
Activate the option in the journal settings and create an entry correctly (with the date in the period) and post it.

Then duplicate this entry and change the date field with a date outside the period and post it.

So you can post en entry outside the period and create wrong entries in the system. The feature does not work as intended.

See the picture below for more details.

Thanks for a quick fix.

![dateinperiodnotactif](https://cloud.githubusercontent.com/assets/8482862/7816361/e4bcc05e-039b-11e5-8cf1-6a962b43aec4.png)
![journalconstraint](https://cloud.githubusercontent.com/assets/8482862/7816360/e4bbd4c8-039b-11e5-9f6e-b1f5e6c6df90.png)

**Comment by Yenthe666** [comment]
Hi @juli1r,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
