### ISSUE TITLE
Odoo 13 

### ISSUE THREAD

**Issue by iman-alhaddar** [odoo/odoo#68508]
Impacted versions:
Odoo 13
Steps to reproduce:
1- limit each point of sale with its customers.
2- don't show users within the customers in the point of sale.
Current behavior:
In POS we are finding all customers and our users in each point of sale.
Expected behavior:
We should limit each point of sale with its customers.

Please I need help in this issue so important, 

Thanks,

**Comment by pedrobaeza** [comment]
How do you do point 1?

**Comment by iman-alhaddar** [comment]
I want to have these points in my system if anyone have idea I wish he/she can help please .
Thanks so much,

**Comment by pedrobaeza** [comment]
Sorry, but this issue tracker if for problems in existing features, so closing. Look for a third-party module doing what you want.

**Comment by iman-alhaddar** [comment]
I didn't find what I found is set default customer only

**Comment by pedrobaeza** [comment]
Then it doesn't exist, and the only option is to develop it or pay someone to do it.
