### ISSUE TITLE
[Bug on sale order] "discount_applied" while evaluating

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#6851]
Menu sales>sales>sale order.

Form view,
When click on send by email,

below message comes

QWebException: "discount_applied" while evaluating
"translate_doc(doc_id, doc_model, 'partner_id.lang', 'sale.report_saleorder_document')"

Thanks,

**Comment by Yenthe666** [comment]
Hi @tejastank ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by tejastank** [comment]
Hey, @Yenthe666 

Thank you for late response.

We had migrated odoo 8 client in @erpnext #ERPNext, 

Its really great news issue on 26 May 2015 finally closed in Dec13-2017

**Comment by Yenthe666** [comment]
Enjoy Erpnext!
