### ISSUE TITLE
Unrealized gain/loss does not use the company's current rate.

### ISSUE THREAD

**Issue by mvaled** [odoo/odoo#6853]
A USD reporting company that:
- Updates the USD currency rate (but keeps the EUR 1:1).
- Keeps some accounts in EUR.

Fails to get useful information from the Unrealized Gain/Loss report cause the rate use for EUR accounts would be EUR/EUR.

**Comment by Yenthe666** [comment]
Hi @mvaled ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
