### ISSUE TITLE
Odoo 14.0 l10n_lt - Error loading Lithuanian translation

### ISSUE THREAD

**Issue by psugne** [odoo/odoo#68552]
Impacted versions: 14.0 community. I simulated the problem within an instance of Odoo in Runbot

Steps to reproduce: From Apps install `l10n_lt` module. Go to _Settings_ -> _Translations_ -> _Languages_, Select _Lithuanian / Lietuvių kalba_, click on _Activate and Translate_ button and _Load_. Make sure that _Overwrite Existing Terms_ is checked.

Current behavior:
```
  File "/data/build/odoo/odoo/addons/base/models/ir_translation.py", line 124, in finish
    """ % (self._model_table, self._table))
  File "<decorator-gen-3>", line 2, in execute
  File "/data/build/odoo/odoo/sql_db.py", line 101, in check
    return f(self, *args, **kwargs)
  File "/data/build/odoo/odoo/sql_db.py", line 298, in execute
    res = self._obj.execute(query, params)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/build/odoo/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/build/odoo/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
psycopg2.ProgrammingError: ON CONFLICT DO UPDATE command cannot affect row a second time
HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
```

Expected behavior: Load Lithuanian language correctly.

Video/Screenshot link (optional):
https://www.awesomescreenshot.com/video/3224036?key=cd63eb357ceba6b24d2e86a717e42a28

Support ticket number submitted via odoo.com/help (optional):

**Comment by psugne** [comment]
@Tecnativa

**Comment by sswapnesh** [comment]
Added Fix on https://github.com/odoo/odoo/pull/68565

**Comment by Tomaskarpovic** [comment]
@sswapnesh what is the status of merging your fix to source?
