### ISSUE TITLE
[8.0] Answer from PaymentProviders depends on the odoo session! Will fail for multiple answers from PP.

### ISSUE THREAD

**Issue by michaelkarrer81** [odoo/odoo#6856]
If odoo receives an answer from the payment provider e.g.: ogone it will in most cases call the /shop/payment/validate controller to update the SO state. But this controller and therefore the related update of the sales order is dependent on the current odoo session. Which will fail if the answer from the PP is send later or the user already started a new sales order. 

Also the current logic of odoo would make quite some trouble if no answer from the pp is received or there is an assertion during the processing of the PP answer. In this case it could be that the user is stuck and can no longer start a new Sales Order (Shop process) because the SO ID and / or the Payment Transaction ID is already taken. Payment process would therefore constantly fail until the odoo session of the user is deleted which in most cases would never happen.

I wrote an addon to lock the sales order and reset the shop session if the Pay Now button is pressed and also makes the answer (at least from ogone) of the PP totally undependend of the odoo session. 

After all testing and code review this seems like quite a big flaw of the current shop system too me! It may also be that i just misunderstood the current shop behavior but i don't know the right place to discuss this with odoo.

**Comment by Yenthe666** [comment]
Hi @michaelkarrer81,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
