### ISSUE TITLE
Space in function call

### ISSUE THREAD

**Issue by sergiocorato** [odoo/odoo#68575]
https://github.com/odoo/odoo/blob/be09fa8ebcefe1794577c90236fa210efaa2125e/addons/website_forum/controllers/main.py#L573

**Comment by pedrobaeza** [comment]
Is this causing any error?

**Comment by sergiocorato** [comment]
None AFAIK, but is it acceptable?

**Comment by pedrobaeza** [comment]
Well, yes. It's not ideal according usual guidelines, but it's not blocking. Odoo has added linters in recent versions, so they will avoid this kind of things.

**Comment by sergiocorato** [comment]
Thanks for the info.
