### ISSUE TITLE
[8.0] product_margin wrong data with variants

### ISSUE THREAD

**Issue by pablocm-aserti** [odoo/odoo#6860]
Impacted versions:
8.0 / master

How to reproduce:
Have several product templates with variants, do some invoices of products whose ids don't match with their templates' ones and try to figure out what means the data shown under "Reporting"->"Purchase"->"Product Margins" for those products.

Current behaviour:
Wrong data is shown due to [this](https://github.com/odoo/odoo/blob/75b993245116d0d662bf4205eb8df3cbc4b6def1/addons/product_margin/product_margin.py#L68) join, mixing product ids with template ones. In a scenario with 1-product:1-template the data should be right and maybe that's why it passed unnoticed.
It should be changed to 
```sql
left join product_template pt on (pt.id = product.product_tmpl_id)
```
Expected behaviour:
Product Margins showing the right amounts.

**Comment by jco-odoo** [comment]
You are right about this.  I will try to change it quickly.
