### ISSUE TITLE
multi line product description problem in qweb report odoo

### ISSUE THREAD

**Issue by Bhaviraj** [odoo/odoo#6861]
if the product description is too long then description in the new page is overwriting on the product line table. is there any way to remove the header tag from report

**Comment by Yenthe666** [comment]
Hi @Bhaviraj,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
