### ISSUE TITLE
[12.0] DST incorrect handling affects cron jobs

### ISSUE THREAD

**Issue by pelayog** [odoo/odoo#68612]
Impacted versions: 

At least, 12.0, probably also from 9 to 13

Steps to reproduce:

1. Create a scheduled task
2. Wait for the next time change

Current behavior:
The task is performed +-1 hour shifted

Expected behavior:
The task is executed at the time initially set.

---
Although I suspect it may be related to the issue https://github.com/odoo/odoo/issues/9268 I don't know if in the specific case of scheduled tasks it might have an easier or different solution.

It is especially critical when you rely on scheduled tasks to perform maintenance, backups, etc.

There is any way to fix this behavior?

**Comment by pedrobaeza** [comment]
Closing as this is not going to be fixed. The same you need to change your analog clock when the hour is adjusted due to DST, you have to adjust your crons according that if you want to perform things in the same "artificial" hour that you had before.

**Comment by boskowski** [comment]
Disappointed to see this issue closed without a resolution. Automated DST handling is a fundamental requirement for reliable task scheduling in ERP systems, ensuring consistency and accuracy in operations. Manual adjustments are prone to human error and defeat the purpose of automation. Reconsidering this could significantly enhance user trust and system robustness.

**Comment by Said113** [comment]
the same issue in v17, there have been no updates regarding this matter.
