### ISSUE TITLE
[13.0] Vulnerability detected CWE ID 601 addons/web/static/src/js/views/basic/basic_controller.js and addons/web/static/lib/qweb/qweb.js

### ISSUE THREAD

**Issue by TatianaGarcia94** [odoo/odoo#68624]
Impacted versions: 13.0

Path: 
    * addons/web/static/src/js/views/basic/basic_controller.js line 826
    * addons/web/static/lib/qweb/qweb.js line 390
Vulnerability Name: URL Redirection to Untrusted Site ('Open Redirect')
Detection mode: A static scan was carried out, which detected the line mentioned as a vulnerability according to security standards

**Comment by Yenthe666** [comment]
Please see https://www.odoo.com/nl_NL/security-report.
