### ISSUE TITLE
[13.0] Vulnerability detected CWE ID 73 addons/web/static/lib/pdfjs/web/viewer.js

### ISSUE THREAD

**Issue by TatianaGarcia94** [odoo/odoo#68623]
Impacted versions: 13.0, 12.0, 11.0

Path: addons/web/static/lib/pdfjs/web/viewer.js 412, 438
Vulnerability Name: External Control of File Name or Path
Detection mode: A static scan was carried out, which detected the line mentioned as a vulnerability according to security standards

**Comment by GoZippy** [comment]
Where is this at?

**Comment by Yenthe666** [comment]
Please see https://www.odoo.com/security-report.
