### ISSUE TITLE
[10, 11, 12, 13, 14] Accounting, Warehouse: Stock valuation wrong value

### ISSUE THREAD

**Issue by BusinessAgilityMasters** [odoo/odoo#68639]
Impacted versions:
10, 11, 12, 13, 14

Steps to reproduce:
- "Decimal Accuracy" -> 'Product Price' to 3 digits
- Change category -> Costing method: FIFO, Inventory Valuation: Automated

- Create a new product -> Set costprice to "0.004" per kg.
- Create a Purchase Order, add the created product and confirm the order. 
- Validate the delivery

Current behavior:
The "Valuation" of this delivery is 0, however the product does have a price. Field "Unit Value" is 2 digits but product price has been set to 3 digits.

Expected behavior:
That the field "Unit Value" uses the same 'Decimal Accuracy' as is used in the vendor pricelist / product.

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/39414107/113281928-8a93af80-92e6-11eb-8da1-92ad38d6e35f.png)

![image](https://user-images.githubusercontent.com/39414107/113281990-a13a0680-92e6-11eb-92ad-04230ca5b6e2.png)

![image](https://user-images.githubusercontent.com/39414107/113284246-a8aedf00-92e9-11eb-96f0-cce36a797afb.png)

![image](https://user-images.githubusercontent.com/39414107/113284358-ce3be880-92e9-11eb-8624-1546806e9b3c.png)

![image](https://user-images.githubusercontent.com/39414107/113284710-4f937b00-92ea-11eb-969a-d90fa3445652.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
I think unit value shouldn't have 3 decimals, but the total value should reflect the multiplication of such low value.

**Comment by ray-odoo** [comment]
Odoo is showing the value based on the decimals of the Currency (which are two).

0.004 is stored in the database.

If you want, you can increase the decimals of the Currency via the rounding:

![Screenshot 2021-04-04 121706](https://user-images.githubusercontent.com/41073831/113519246-d68d6100-953f-11eb-996f-c91f5a58de6f.png)

My PO had no tax, and I think you may have done your steps out of order because I did get both costs shown:

![SECOND](https://user-images.githubusercontent.com/41073831/113519251-dc834200-953f-11eb-9330-b95366256e2a.png)

**Comment by pedrobaeza** [comment]
@ray-odoo that's not the convenient thing, as the currency has the decimals that it has, not more or less. The total value should reflect correctly the amount independently from the currency precision.

**Comment by ray-odoo** [comment]
So change the widget to float with digits then:

`<field name="unit_cost" widget="float" digits="[6,3]"/>
<field name="value" widget="float" digits="[6,3]"/>`

![THIRD](https://user-images.githubusercontent.com/41073831/113519342-67643c80-9540-11eb-84f5-dbaa0d9804b4.png)

**Comment by pedrobaeza** [comment]
But there's an inner problem in this: if there's no digits set, no rounding should be done when taking the value for getting the total one. I sincerely don't see that very understandable.

**Comment by ray-odoo** [comment]
Rounding isn't happening in the database but via the UI because of the conflict between asking to store a cost at 3 decimals and at the same time asking for it to be displayed with 2 decimals via the valuation record.

**Comment by BusinessAgilityMasters** [comment]
> Rounding isn't happening in the database but via the UI because of the conflict between asking to store a cost at 3 decimals and at the same time asking for it to be displayed with 2 decimals via the valuation record.

1. The issue is the Total Value that is passed on incorrectly. If we check the value in Accounting that is also incorrect so this leads to incorrect Journal Entries! Please see the screenshot below, you can see that the value of the sand in the Purchase Order is 100,40 and in the Journal entry the value is set to 100,00. This means that the Inventory Valuation is incorrect. 
![image](https://user-images.githubusercontent.com/39414107/114188200-32455900-9949-11eb-9b35-3b6ddb7e9c0a.png)

2. There also is a difference in behaviour, if you set no tax on the Purchase Order Line, then the 'Total Value' is correct. So I doubt if this is done in the UI, seems that the TAX method affects the 'Total Value'. 
![image](https://user-images.githubusercontent.com/39414107/114188627-9e27c180-9949-11eb-8487-858f5b17b6b6.png)

**Comment by ray-odoo** [comment]
Please open a Support Ticket via https://www.odoo.com/help using the subscription code of either yourself or GRIP ICT

Choose one scenario - either 0.004 as the price per KG or 1.004 as the price per UNIT - if you want to report both make it clear when one scenario ends and the other starts.

I do get the same experience you have posted using 1.004 when comparing a PO with Tax and a PO without Tax **AND** I get no valuation when the product is valued at 0.004 - both look like they are problematic to me. 

I see 0.004 and 1.004 stored in the database in the stock_valuation_layer table (which you can test by exporting the records).

**Comment by andrius-preimantas** [comment]
@BusinessAgilityMasters @ray-odoo there's already a support ticket submitted for this issue opw-2472192 (Date: 03/01/2021)

**Comment by ray-odoo** [comment]
I have reviewed the OPW ticket. Seems our team has already been making progress on a fix.

**Comment by ray-odoo** [comment]
Please see https://github.com/odoo/odoo/pull/69297
