### ISSUE TITLE
[POS] Issue on payment using different currency

### ISSUE THREAD

**Issue by dipesh-suthar-flectra** [odoo/odoo#6864]
Version: 8.0
- Default curency of company is EUR,
- Create one payment method with currency USD,
- Customer wants to pay bill in USD,
- You have to select payment method USD Bank Journal.

Current Behavior:
- Bill amount will not convert in USD
- Also getting currency symbol of EUR

Expected Behavior:
- Bill amount should be converted in USD (EUR >> USD)
- with exchange rate amount should be converted and symbols as well.

See here: https://goo.gl/y5QsTo

**Comment by invitu** [comment]
Hello
this issue is still here in v10...
Did you find a solution ?
Best Regards

**Comment by Yenthe666** [comment]
Hi @dipesh-suthar-flectra ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you (or @invitu) can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
