### ISSUE TITLE
[14] project: can not duplicate project

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#68669]
Impacted versions: 14

Steps to reproduce: Login with Demo user (Project Administrator)
Projects --> Duplicate

Current behavior: 
![Screenshot from 2021-04-01 23-56-32](https://user-images.githubusercontent.com/16624719/113337816-ea6d7300-9345-11eb-9a72-b6c99550824e.png)

Expected behavior: Able to Duplicate Project

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional): 2506566

**Comment by rafaelbn** [comment]
This issue is solved here: https://github.com/odoo/odoo/pull/70315

**Comment by sswapnesh** [comment]
Indeed, I was the one to add that OPW (Missed to link it here)
