### ISSUE TITLE
Point of sale Cash Round Off

### ISSUE THREAD

**Issue by DonFeraRRi** [odoo/odoo#68684]
Impacted versions: 14.0 (I checked and found in this)
Confirmed through RunBot.
Steps to reproduce: 

Step 1: Go inside Point of sale >>>>Configurations>>>>Settings

Step 2: Select Cash Rounding and create a cash rounding.

Step 3: Now inside Point of sale >>>>Configurations>>>>Point of sale

Open shop pos settings and enable cash rounding and select the previously created cash rounding.

A Boolean is there "Only on cash methods". 

Current behavior: If this boolean is selected, the rounding isn't happening.

When I uncheck this boolean, rounding happens/

Expected behavior: Vice-versa

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by HendryLeo** [comment]
might be duplicate of #65043

**Comment by DonFeraRRi** [comment]
Yeah Correct... he is also talking about the same issue but that is also not closed.

**Comment by Yenthe666** [comment]
Let's close this one in favor of https://github.com/odoo/odoo/issues/65043 so there's no duplicated efforts.
