### ISSUE TITLE
Not possible to update product stock through stock.change.product.qty model for products that are tracked in lots

### ISSUE THREAD

**Issue by GruberViktor** [odoo/odoo#68693]
**Impacted versions:** 
14.0 - I have not tried older versions

**Steps to reproduce:** 

1. create product that is tracked with lot numbers. 
2. change on-hand quantity - create a lot number in the process
3. Through API:

```
change_id = models.execute_kw(
    db, uid, password,
    'stock.change.product.qty',
    'create',
    [{
          'new_quantity': 100,
          'product_id':  product_id,
          'product_tmpl_id':  product_tmpl_id,
          #'lot_id':  lot_id <- is not accepted
    }]
)

models.execute_kw(
    db, uid, password,
    'stock.change.product.qty',
    'change_product_qty',
    [[change_id]]
)
```
Response: `xmlrpc.client.Fault: <Fault 2: 'You need to supply a Lot/Serial Number for product: \n - Testproduct'>`

**Current behavior:**
Can't change the stock via this API Model

**Expected behavior:**
Be able to specify the lot id somehow.

I need this functionality to sync the stock with another application. Unfortunately it's a dealbreaker right now, and I lack the understanding of the code to fix it on my own. If anybody has a suggestion for a workaround for the time being, I'm all ears.

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a development question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
