### ISSUE TITLE
[8.0] US Chart of Accounts - Duplicate Account Types

### ISSUE THREAD

**Issue by ghost** [odoo/odoo#6871]
When creating a new database, and installing the US Chart of Accounts (first module) and Accounting (second module) I observed the following (Configurable Chart Template):

Direct Duplicate Account Types:
Cash (External ID: account.data_account_type_cash)
Cash (External ID: l10n_us.user_type_cash)
Equity (External ID: account.conf_account_type_equity)
Equity (External ID: l10n_us.user_type_equity)
Expense (External ID: account.conf_account_type_equity)
Expense (External ID: l10n_us.user_type_equity)
Income (External ID: account.data_account_type_income)
Income (External ID: l10n_us.user_type_liability)

Indirect Duplicate Account Types:
Payable (External ID: account.data_account_type_payable)
Account Payable (External ID: l10n_us.user_type_account_payable)
Receivable (External ID: account.data_account_type_receivable)
Account Receivable (External ID: l10n_us.user_type_account_receivable)

US Types are added without leveraging, deleting or updating existing Default Types.

Users now have more than one choice when being asked to select an account type.

Report definitions also show the duplicate account types.

**Comment by Yenthe666** [comment]
Hi @ghost,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
