### ISSUE TITLE
Regarding Backup data

### ISSUE THREAD

**Issue by NaduniPulsarani** [odoo/odoo#6875]
I researched so many links to find out how to backup data and migrate to Odoo. I didn't find any links regarding that. I need to know for Windows. 
Pls Help me..

And also I need to find out how to transfer the data over

Thank You,
Naduni Pulsarani

**Comment by lukebranch** [comment]
@NaduniPulsarani ,

This is a question rather than an issue report. For this reason you should close this issue report and move over to:

https://www.odoo.com/forum/help-1

where you'll find people who may be able to help you if you provide a clear explanation of exactly what you want to accomplish.

**Comment by NaduniPulsarani** [comment]
@lukebranch ,

I tried to post that in to above link(Odoo Forum) But still they didn't register my email.I sent an email  to them for the verification.  Without activating my account I couldn't post my questions.  :(

**Comment by lukebranch** [comment]
@NaduniPulsarani ,

You'll need to wait for them to activate it. This is due to a spam fighting mechanism they have developed to stop forum spam. The forums were overrun by spam for awhile and many features like this needed to be implemented in order to keep the forums free of spam.

**Comment by NaduniPulsarani** [comment]
@lukebranch 

k. I will wait for the activation.

Thank you,

**Comment by lukebranch** [comment]
@NaduniPulsarani ,

No problem. I would recommend closing this github issue using the button below. This will make sure that the issue reporting system is kept for only reporting issues/bugs with Odoo to help ease the developer's workload.

**Comment by Yenthe666** [comment]
@NaduniPulsarani I've added a detailed answer on your post (on Odoo help) which tells you all the ways to backup. :+1:
