### ISSUE TITLE
[7.0/8.0] Dashboard list view limitation

### ISSUE THREAD

**Issue by francoislawarree** [odoo/odoo#6876]
Hi,

We have discovered a bug concerning the representation of a list view into the Dashboard. The window defined for a list is limited by 80 elements and there is no way to show the others elements that belong to the list.

![image](https://cloud.githubusercontent.com/assets/11072956/7854534/a190469a-051a-11e5-8e73-cc2f3049cfae.png)

Could you provide a solution (button / pages) to be able to extend and to show all the elements when the list have more than 80 elements.

In the case of a kanban view, a button is defined to extend the list:

![image](https://cloud.githubusercontent.com/assets/11072956/7854545/bb0b0a10-051a-11e5-8e7a-f8c09005eeb0.png)

Thanks in advance for your return

François Lawarrée

**Comment by Yenthe666** [comment]
Hi @francoislawarree ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
