### ISSUE TITLE
[13,14,master] hr_presence [Employee > HR Presence State Display] not automatically updated, ir_cron missing

### ISSUE THREAD

**Issue by chrisandrewmann** [odoo/odoo#68761]
Impacted versions:

- 13, 14, and master

Steps to reproduce:

1. Install hr_presence
2. Enable [Advanced Presence Control]  and Presence control [Based on user status in system]
3. Note that field on Employee [HR Presence State Display] is not updated automatically unless manually clicking the [Employees > Reporting > Employee Presence] menu item, which is only available to HR Officers.
 
Current behavior:

- Field on Employee [HR Presence State Display] is not updated automatically unless manually clicking the [Employees > Reporting > Employee Presence] menu item, which is only available to HR Officers. 

Expected behavior:

- Field should be updated on a cron job (Scheduled Action) so that non HR employees can view status.
**- Note: There is already a cron job here https://github.com/odoo/odoo/blob/14.0/addons/hr_presence/data/ir_cron.xml but is missing from the manifest file so is never installed**

**Comment by pedrobaeza** [comment]
Closing, as there's a PR where this can be discussed.
