### ISSUE TITLE
[14.0] webshop: failing VIES vat check gives no warning to customer

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#68768]
https://www.odoo.com/web#active_id=2498695&cids=1&id=2498695&model=project.task&menu_id=

Impacted versions: 14.0 At least

Steps to reproduce:
1. Login to the latest runbot 14.0 with the admin user
2. Go to Accounting > Settings, enable the option Verify VAT Numbers and save.
3. Open the same Odoo instance in an incognito and go to the webshop
4. Add a product to your cart, go to the steps and in the "Address" step fill in an invalid VAT number. For example `BE0745455292000` for `Belgium`.

Current behavior: You get a red highlight but no feedback/warning of why it is red and you're blocked:
![image](https://user-images.githubusercontent.com/6352350/113514391-811c7880-956e-11eb-87ab-b15a8b6f25b1.png)

Expected behavior: You get a warning saying something like "This VAT number is invalid. Please correct the VAT number or remove the company name."

**Comment by rdeodoo** [comment]
This is weird, because I just tried the exact same steps and I got a clear message as you would like to have, see 
![image](https://user-images.githubusercontent.com/30048408/113867922-671da880-97af-11eb-85bd-4994ba782920.png)

**Comment by Yenthe666** [comment]
I just tested on a new runbot again and it indeed succeeded. I then test my local instance again which was still not doing this. After updating it to the latest commit it is now working so I guess one of the commits from the last weeks or so changed something to make it go off again 🤷
