### ISSUE TITLE
[v8.0.0] Document - Order does not work for Related documents

### ISSUE THREAD

**Issue by tasa87** [odoo/odoo#6878]
If you open a customer and then open More->Related documents, list with customer related documents is shown. If you want to sort documents by name or any other field, it has no effect.

<b>Affected version</b>
8.0.0 and above

<b>Steps to reproduce</b>
1. Install document module
2. open a customer
3. go to More->Related documents
4. Add view document to different directories
5. click on column header to sort by name or oder field

<b>Current behaviour:</b>
Order stay at the same order.

<b>Expected behaviour:</b>
Items should be ordered by selected column.

**Comment by lukebranch** [comment]
@tasa87 ,

I'm only an Odoo user like yourself, however i'd recommend using a screencap/gif creation program like licecap:

http://www.cockos.com/licecap/

to demonstrate the issue visually as well as detailing some steps to reproduce and a description of the error using a format like this example:

https://github.com/odoo/odoo/issues/3339

This will increase your chances of your issue being noticed and resolved more quickly by Odoo SA in my experience.

**Comment by tasa87** [comment]
I found that in file addons/document/document.py - documents are grouped by directory (parent_id) - it's iterate through parent_ids , line 105-108:

{code}
        # null parents means allowed
        ids = parents.get(None,[])
        for parent_id in visible_parent_ids:
            ids.extend(parents[parent_id])
{code}

Possible solution is to change this code to use temp list to not break the order (change lines 105-110 in original file):
{code}
 # null parents means allowed
         temp_ids = parents.get(None,[])
         for parent_id in visible_parent_ids:
             temp_ids.extend(parents[parent_id])
        
         res = [x for x in ids if x in temp_ids]
        
        return len(res) if count else res
{code}

**Comment by tasa87** [comment]
@lukebranch,

thanks for your advice, I changed description a little.

**Comment by lukebranch** [comment]
@tasa87 ,

No problem. Good luck!

**Comment by Yenthe666** [comment]
Hi @tasa87,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
