### ISSUE TITLE
AbstractModel not found

### ISSUE THREAD

**Issue by seifeddin** [odoo/odoo#6880]
![te](https://cloud.githubusercontent.com/assets/12595044/7858201/6e9507a8-052e-11e5-9059-4e50ebe8d2bb.png)
this the code 
![l](https://cloud.githubusercontent.com/assets/12595044/7858208/78f129ac-052e-11e5-84d2-0237357b3c73.png)
help !

**Comment by xmo-odoo** [comment]
The error message seems to indicate that you have added AbstractModel to your `depends` in `__openerp__.py`. Don't do that, `depends` is just for models dependencies.

And you should get `AbstractModel` from `openerp.models`, same as `Model`. `openerp.osv.osv` only imports it (and unknowingly exposes it) so it can expose `osv_abstract` for backwards-compatibility reasons.

**Comment by seifeddin** [comment]
the problem is not fixed i change the AbstractModel by osvabstract but every thing stay unchanged

**Comment by xmo-odoo** [comment]
> help me please @xmo-odoo

Have you looked at your module's dependencies?

> the problem is not fixed i change the AbstractModel by osvabstract but every thing stay unchanged

That makes literally no sense. You've replaced a deprecated behaviour by an other deprecated behaviour, none of which has any reason to be the original issue.

**Comment by seifeddin** [comment]
@xmo-odoo  thnx bro it is work

**Comment by seifeddin** [comment]
@xmo-odoo  you have idea for crate a new report of new model created by my self . i try many solution but is not work it  you have a good example or titou

**Comment by lukebranch** [comment]
@seifeddin ,

I think this is a question not an issue report, and is better asked in the community forums here:

https://www.odoo.com/forum/help-1

I'd recommend referring to the contributing guidelines, specifically the reporting issues section:

https://github.com/odoo/odoo/wiki/Contributing
