### ISSUE TITLE
report.abstract_report unexisting

### ISSUE THREAD

**Issue by seifeddin** [odoo/odoo#6884]
TypeError: The model "fs.report_fs" specifies an unexisting parent class "report.abstract_report"
You may need to add a dependency on the parent class' module.

**Comment by Bartii** [comment]
same error for QWeb raport with reference to custom python function 

TypeError: The model "report.bmbi_test.report_bmbi_sample_document" specifies an unexisting parent class "report.abstract_report"
You may need to add a dependency on the parent class' module.

odoo v9

**Comment by Bartii** [comment]
solved in my case by add dependency to report in __openerp__.py 
'depends': ['base', 'report'],

regards

**Comment by ibrahimomer** [comment]
thanks alot
