### ISSUE TITLE
Social push notifications dependency

### ISSUE THREAD

**Issue by pollarolas** [odoo/odoo#68853]
Impacted versions: 13.0

Steps to reproduce: Install social_push_notifications and its dependency firebase_admin and any other module that works with pandas library

Current behavior: Error with pandas function "read_html". Without the mentioned module (social_push_notifications) everithyng works well, but after installing the module and trigger the same pandas function returns an error.

Expected behavior: Work with the social_push_notifications module installed.

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/42778294/113765812-5d7a3f00-96e2-11eb-86a9-a38c4c3c6548.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
Being an enterprise module, and with certain specifications that are not regular (I don't see `firebase_admin` dependency nor the rest of the explanation), please report it to odoo.com/help instead of here.
