### ISSUE TITLE
Print layout problem when product description is too long in qweb report

### ISSUE THREAD

**Issue by fraxnet** [odoo/odoo#68876]
Impacted versions:
Odoo EE 13, 14

Steps to reproduce:  
print a sales order and invoice 

Current behavior: 
if the product sales description is too long it will appear on the next page, leaving blank space between sales line 

Expected behavior:
to let the discription flow from the first page to the next page without blank space.
Video/Screenshot link (optional):
https://github.com/wkhtmltopdf/wkhtmltopdf/files/3948682/CLUDO_DEC_062_19-20._R-1.6.pdf

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
Yes, this is a known problem that can't be avoided for now, due to the possibilities of wkhtmltopdf with table breakings + preserve headers. Closing as won't fix.
