### ISSUE TITLE
Point of sale cash transactions balance mismatch

### ISSUE THREAD

**Issue by DonFeraRRi** [odoo/odoo#68879]
Impacted versions: Checked on 14 Community/Enterprise

verified on runbot/demo.odoo.com

Steps to reproduce: Create multiple Point Of Sale counters. Configure them to have a cash opening balance as true from the settings.

Open 2 or more sessions on respective POS counters and Set the opening cash balance as 2000 while opening a new session and do some cash transactions on anyone  POS counters and then close the session. now close another POS session as well. 

Current behavior: While closing another POS counter, the cash transaction balance of the previous closed POS counter gets added to the closing balance of the now-closed POS counter.

Expected behavior: This transferring of cash transaction balances not happen and should be avoided as it causes discrepancy while reconciling the system cash balance and actual cash balance in a respective POS Counter

**Comment by pedrobaeza** [comment]
I don't get what do you mean by "Point Of Sale counters". Maybe a video would help.

**Comment by DonFeraRRi** [comment]
> I don't get what do you mean by "Point Of Sale counters". Maybe a video would help.

counters i mean point of sale terminals.

**Comment by DonFeraRRi** [comment]
> I don't get what do you mean by "Point Of Sale counters". Maybe a video would help.

https://drive.google.com/file/d/14_kJLiodRTFWn7E3dOsD29ZzIbBLDEB5/view?usp=sharing

Above mentioned is the link to the video for the same.

**Comment by pedrobaeza** [comment]
Are you sharing the same journal for both PoS?

**Comment by DonFeraRRi** [comment]
Yes.

**Comment by pedrobaeza** [comment]
That's the problem then. You should use a different journal per PoS. Closing then as clarified.

**Comment by DonFeraRRi** [comment]
Hey @pedrobaeza  i believe you again need to open the issue as after using seperate journals also there is the same behaviour.

**Comment by pedrobaeza** [comment]
And both journals point to the same income account?

**Comment by DonFeraRRi** [comment]
Yes

**Comment by pedrobaeza** [comment]
Then that's also the problem according to my investigations.

**Comment by DonFeraRRi** [comment]
But this should not be the case as I can have same income account linked to multiple journals. Its not making a logic to have seperate COA for seperate Point of sale.

**Comment by pedrobaeza** [comment]
The expected cash is got from the balance of such account, so yes, it's needed.

**Comment by DonFeraRRi** [comment]
But this should fetch from the journals and not from account, as I can have seperate journals linking to same account and it does not show this behaviour in previous versions as well.

**Comment by DonFeraRRi** [comment]
In Odoo13 it's not happening. Then why it's required here, please clarify it, its causing trouble.

**Comment by DonFeraRRi** [comment]
Can we have further discussion? That is an issue for sure.

**Comment by aqeelrgs** [comment]
We are using community 14.
Similar issue we are facing

Usual behaviour should be opening cash plus transactions should be actual/expected closing cash.

But when we start new session, we make opening cash nil but while closing this new session system use opening balance amount of previous closing session amount instead of zero which make at start thus disturbing closing cash session results

**Comment by MissionCriticalInc** [comment]
Same problem here, and now the books are off by over $130,000.00...

Can these journal entries be deleted somewhere so I can balance the books? Right now it looks like it's off by WAY over what is should be.

**Comment by sc-dfernandez** [comment]
Hi guys, I am having the same problem with a version 15. Did you find the solution?
