### ISSUE TITLE
help plz

### ISSUE THREAD

**Issue by seifeddin** [odoo/odoo#6888]
class report_saleorderqweb(osv.AbstractModel):
    _name = ‘module_name.report_sale_order_qweb’
    _inherit = ‘report.abstract_report’
    _template = ‘module_name.report_sale_order_qweb’
    _wrapped_report_class = sale_quotation_report
the erreur be report.abstract unexciting

**Comment by flotho** [comment]
@seifeddin , your issue is not relevant.
Could you precise, print the logs etc...
