### ISSUE TITLE
Overriding Required attribute property of a Field in Saas

### ISSUE THREAD

**Issue by deepa4lok** [odoo/odoo#6890]
Well this looks so silly, but it is not, because this is not happening in Saas version and i just want to confirm whether it is bug or not...

 Consider an example,

In Account.Invoice (Standard) - "partner_id" is set as <i> required=True </i>, which will in turn set Not Null Constraint in the Backend..

Lets say in my custom module, am going to override the column "partner_id" to set <i> required=False </i>, Now am in for surprise, my  property is not considered at all...

Did anyone faced this weird problem in Saas version, If so did you find any fix for this...

And am pretty sure this is bug left behind in Saas version..

**Comment by Yenthe666** [comment]
Hi @deepa4lok,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
