### ISSUE TITLE
[8.0][stock][stock.inventory.line] Unit of measure by default in the model stock.inventory

### ISSUE THREAD

**Issue by josemoralesp** [odoo/odoo#6891]
At the moment to create a new inventory adjustment when you create a new inventory line by default is set Unit like unit of measure[1] even when the product is not set yet. If you select a product with a unit of measure different to Unit and in different category of the unit of measure, you will have an error message[2].

The error is because technically you cannot set the unit measure by default [3] if you don´t know the product to use, for that you have the onchange methods. With this default, your onchange method is not working correctly because is taken Unit like unit of measure of the all products[4].

I propose you 2 solutions:

1) Remove the default of the product_uom_id field and leaves to the onchange work (This works one time. If you need to change the product in the same line, the uom will not recompute by the onchange because the field is not empty)
2) Remove the condition in the onchange and always set the uom of the product no matter if the product_uom_id field is empty or not. You need to change the method onchange_createline to apply the same condition[5]. ( I would remove the default value with this change ).

[1] https://www.evernote.com/l/AOCHi6qd1CxAXpCp7AKQ1L-xtUTaHPlIUhAB/image.png
[2] https://www.evernote.com/l/AOCad3sHHalFpL7ptxrHMPJpvJHRmXmfm6gB/image.png
[3] https://www.evernote.com/l/AOCtpkU1_rlJFbelh0-qCNbOFnXKMSetMYAB/image.png
[4] https://www.evernote.com/l/AOB1o9iGjRtDZ7gNm8Mf-Xu1dsp0XFu3Cd8B/image.png
[5] https://www.evernote.com/l/AOBjZ_cbjO9FzKD2OCNuJnzJa03OoS3TuWoB/image.png

**Comment by Yenthe666** [comment]
Hi @josemoralesp,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
