### ISSUE TITLE
[7.0] Default taxes are not get on sale/purchase order in multi-company environement

### ISSUE THREAD

**Issue by gbard** [odoo/odoo#6893]
There is no issues when creating a sale order in the main company but as as soon as I try to create a sale order in one of the child companies, the default taxes are not get. We have to manually input the appropriate tax on each sale order lines.

**Comment by Yenthe666** [comment]
Hi @gbard ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
