### ISSUE TITLE
[8.0] Drop Shipping - Incomplete origin in purchase.order

### ISSUE THREAD

**Issue by rafaelbn** [odoo/odoo#6894]
HI,

If you create (for example), 4 sales order for 1 client and the products are configured for Drop Shipping, Odoo create only 1 purchase order with all product of the 4 sales order. But "Source document" (origin) only have the information of the first sales order.

This is very confusing as you can make sales order during one full month and process only one purchase order at the end of the month, so it will be difficult to recognize where are that units of the products.

Regards,
Rafael
![2015-05-29_2-03-15](https://cloud.githubusercontent.com/assets/8736623/7873851/dcab915c-05a7-11e5-9bbe-3b79fbe6bb10.png)

**Comment by rafaelbn** [comment]
Same case for Make To Order.

**Comment by beledouxdenis** [comment]
Fixed with ad253a33863c0e2b7bf4add5f689461120278a1b

**Comment by rafaelbn** [comment]
:+1:
