### ISSUE TITLE
erreur in the installition plugin openoffice repport

### ISSUE THREAD

**Issue by seifeddin** [odoo/odoo#6895]
<class 'SyntaxError'>: invalid syntax (OpenERPReport.py, line 36), traceback follows
  /usr/lib/libreoffice/program/pythonloader.py:102 in function getModuleFromUrl() [codeobject = compile( src, encfile(filename), "exec" )]
  /usr/lib/libreoffice/program/pythonloader.py:149 in function writeRegistryInfo() [mod = self.getModuleFromUrl( locationUrl )

**Comment by lukebranch** [comment]
@seifeddin ,

What is this? I can't see any explanation of what you are trying to report, only an error message. Please follow these guidelines for reporting issues:

https://github.com/odoo/odoo/wiki/Contributing

consider using the forum (https://www.odoo.com/forum/help-1) for help, and the github issues (http://github.com/odoo/odoo/issues) for reporting bugs and issues only.

**Comment by seifeddin** [comment]
thanks is work it
