### ISSUE TITLE
Odoo package list

### ISSUE THREAD

**Issue by AsmaAl-Haddar** [odoo/odoo#68968]
Impacted versions: 13.0

Steps to reproduce: Go to Inventory> then master data> then packages.

Current behaviour: We will find that there is no data except for the (Company , Owner, Location, and the content which is Product, L/S number , quantity, unit of measure).

Expected behaviour: We want to define more info like to add the gross and net weight and we need to print all the report in QR code instead of barcode.

Thanks,

**Comment by Yenthe666** [comment]
Duplicate of https://github.com/odoo/odoo/issues/68957
