### ISSUE TITLE
[7.0] Weight in 'Delivery / Receipt slip' report is always empty

### ISSUE THREAD

**Issue by hugues-michel** [odoo/odoo#6900]
In report 'addons/stock/report/picking.rml' ( Object is stock.picking.out )
[[ 'weight' in picking._columns.keys() and picking.weight or '']]
always return an empty string !

Something had to change ... and it was not updated.

**Comment by gurneyalex** [comment]
which branch?

**Comment by hugues-michel** [comment]
Yes is 7.0

**Comment by hugues-michel** [comment]
@gurneyalex  This is related to
[6.1, 7.0] delivery/stock.py : does not redefine stock_move._prepare_chained_picking #367

**Comment by hugues-michel** [comment]
It's not a bug, I'm a little confused ...

Simply install 'delivery' module !

After this module install 'stock.picking.out' have weight, weight_net, volume, carrier.
Thanks to Ramzi

You can close this issue, thanks
