### ISSUE TITLE
Company headers still defined in RML and Webkit

### ISSUE THREAD

**Issue by alejandrosantana** [odoo/odoo#6904]
**Company headers still defined in RML and Webkit**

I see in runbot that even in *master* the company headers are still defined in RML and Webkit (both deprecated).
It should be Qweb already! Much desired to get rid of RML

Impacted versions:

 - master, but would be desirable for 8.0 and beyond

Steps to reproduce:

 1. Just go to Settings > Companies
 2. Select a company
 3. Go to the "Report configuration" tab
 4. There they are "Configuration (Webkit)" and "Configuration (RML)"
 
Current behavior:

 - Have to deal with RML (which even have some parts not translatable like "Phone:" and "Mail:") or Webkit.

Expected behavior:

 - Be able to take advantage of Qweb power.

**Comment by Yenthe666** [comment]
:+1: should have been introduced/fixed when they released 8.0 in my opinion.

**Comment by sle-odoo** [comment]
Fixed at 2e16296099d76b38cab30cf1a968147233d9d462
You only see the rml and webkit one in technical features.
Regards
