### ISSUE TITLE
Why @api.onchange is activated when a view is opened?

### ISSUE THREAD

**Issue by eduardobape** [odoo/odoo#6905]
Hello.

I'm not sure but I have checked that a method with a @api.onchange decorator is activated not only when the field changes, but also when the form view is opened for the first time and all input fields are empty.

Why does it happen this way?. When the form view is opened for the first time, all input fields are empty and no one have changed its value yet.

Thanks.

**Comment by sarac2013** [comment]
Hello,
You can have some fields that are set by default or defined in the context so you would like that the on change is called at the opening of the form to consider the default values.

**Comment by eduardobape** [comment]
Thank you @sarac2013. You are right. I had not realized this.
