### ISSUE TITLE
error using delegation inheritance from res.users model

### ISSUE THREAD

**Issue by eduardobape** [odoo/odoo#6907]
Hi Odoo developers.

I have created a new model Comercial which inherits from res.users model using delegation inheritance.

``` python
class Comercial(models.Model):
    _name = 'crm.comercial'
    _inherits = {'res.users': 'usuario_id'}

    num_ventas = fields.Integer()
    usuario_id = fields.Many2one('res.users', required=True, ondelete='restrict', 
        auto_join=True)
    name = fields.Char(related='usuario_id.name', inherited=True)
    email = fields.Char(related='usuario_id.email', inherited=True)
```

I haven't defined a form view for Comercial model, so when I create a new Comercial in a form, it shows all fields from res.users model and res.partner model. It shows the fields from res.partner model because res.users inherits from res.partner using delegation inheritance too.

``` python
class res_users(osv.osv):
...
_inherits = {
        'res.partner': 'partner_id',
    }
...
'partner_id': fields.many2one('res.partner', required=True,
            string='Related Partner', ondelete='restrict',
            help='Partner-related data of the user', auto_join=True),
```

When I create a new Comercial in the form and click on the Save button, I get this error:

```
...
File "/opt/odoo/odoo_server/openerp/sql_db.py", line 234, in execute
res = self._obj.execute(query, params)
ProgrammingError: invalid reference to FROM-clause entry for table "res_users"
LINE 2: ...ario_id" = "crm_comercial__usuario_id"."id") AND ("res_users...
                                                                                                  ^
HINT: Perhaps you meant to reference the table alias "crm_comercial__usuario_id".
```

Thank you.

**Comment by gaso** [comment]
I have the same problem when trying to order from a delegation inheritance model. Any solution?

**Comment by mboujdid** [comment]
I have the same problem when trying to order from a delegation inheritance res.partner model. Any solution?

**Comment by Yenthe666** [comment]
Hi @eduardobape,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
