### ISSUE TITLE
Physical Inventories - Posted Inventory - Serial Number Icon

### ISSUE THREAD

**Issue by ghost** [odoo/odoo#6908]
Click Inventory line: OK
Click Serial Number Icon: Error: NameError: name 'parent' is not defined

stock_view.xml 
line 170
<button name="%(track_line)d" string="Split in serial numbers" type="action"
                                    icon="gtk-justify-fill"
                                    attrs="{'invisible': [('prodlot_id','&lt;&gt;',False)]}"
                                    states="draft,done,cancel"
                                    context="{'inventory_id':parent.id}"
                                    groups="stock.group_production_lot"/

**Comment by Yenthe666** [comment]
Hi @ghost,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
