### ISSUE TITLE
Broken links in docs

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#6912]
**Links to sections in the documentation are broken.** This started happening after the new design.

Impacted versions:

 - 8.0

Steps to reproduce:

 1. Visit https://www.odoo.com/documentation/8.0/reference/reports.html
 2. Click on the link that reads *Custom Reports*.

Current behavior:

 - Redirected to https://www.odoo.com/documentation/8.0/reference/reports.html#reference-reports-custom-reports

Expected behavior:

 - Redirected to https://www.odoo.com/documentation/8.0/reference/reports.html#custom-reports

It happens with all links I tested.

**Comment by xmo-odoo** [comment]
Both work fine for me, could you try again? Might have been broken for a short time.

**Comment by Yajo** [comment]
The ones that fail are those on the text. The ones on the left menu seem to work.

![captura de pantalla de 2015-06-03 11-40-40](https://cloud.githubusercontent.com/assets/973709/7957231/0ae18102-09e6-11e5-85c1-e7cff924a5ca.png)

**Comment by xmo-odoo** [comment]
It seems to work in Safari and Chrome but behave oddly in Firefox. Is that the one you were testing with?

**Comment by Yajo** [comment]
Yes

**Comment by xmo-odoo** [comment]
Fixed the theme, works locally, should be visible after next doc build, around 7~8 UTC tomorrow. Thanks.
