### ISSUE TITLE
[14]: eCommerce: Internal Server Error after payment with Stripe

### ISSUE THREAD

**Issue by smonv** [odoo/odoo#69145]
Impacted versions: 14

Steps to reproduce:
- Checkout a card with payment method Stripe (test mode)
- Stripe payment with test card
- Stripe redirect back to website with error

Current behavior:

Display Internal Server Error because of `payment_transaction` `is_process` still having value `false`

<img width="406" alt="Screen Shot 2021-04-13 at 08 40 34" src="https://user-images.githubusercontent.com/8962973/114484366-47193980-9c34-11eb-96ba-748cdcedd2f7.png">

Expected behavior:

Display text like "Your transaction is being process" instead of error while wait for Strip transaction processing

Video/Screenshot link (optional):

<img width="406" alt="Screen Shot 2021-04-13 at 08 40 34" src="https://user-images.githubusercontent.com/8962973/114484460-77f96e80-9c34-11eb-8707-63abe04eaaab.png">

<img width="750" alt="Screen Shot 2021-04-13 at 08 44 49" src="https://user-images.githubusercontent.com/8962973/114484503-8a73a800-9c34-11eb-9eeb-0403dca6a3a5.png">

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
This seems a problem in the translations, with one of them not having all the placeholders (`%s`). Are you using another language apart from English?

**Comment by smonv** [comment]
> This seems a problem in the translations, with one of them not having all the placeholders (`%s`). Are you using another language apart from English?

Yes, currently I trying Vietnamese with my website. I will try English only and report back.

**Comment by smonv** [comment]
@pedrobaeza Thank you so much for suggestion. I tried with English only and it working. Do you know what translation is missing?

**Comment by Yenthe666** [comment]
You can correct the wrong ones at https://www.transifex.com/odoo/odoo-14/dashboard/

**Comment by pedrobaeza** [comment]
It's not a missing translation, but a bad one, missing placeholders. Check that you have latest one loaded in your DB, overwriting existing terms, and if still present, check on Transifex.
