### ISSUE TITLE
[14] stock_account SVL access error for inventory user

### ISSUE THREAD

**Issue by mhabboush97** [odoo/odoo#69144]
Impacted versions:
14, maybe others
Steps to reproduce:
validate delivery picking
create return from it
validate return picking
Current behavior:
read access error for model stock.valuation.layer for inventory user,
Expected behavior:
inventory user should be able to validate pickings

tested on runbot, same behavior
inventory user can validate all types of pickings, but this error shows for return only
@Whenrow

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by celm1990** [comment]
possible solution: https://github.com/odoo/odoo/pull/62772

Ping @sle-odoo

**Comment by Whenrow** [comment]
Hello, 
We forgot a `sudo()` in case of return move. It is fixed in this PR https://github.com/odoo/odoo/pull/69151 . I just need to add a little test.

@celm1990 fyi SLE doesn't work for Odoo anymore. In case you need to ping someone from the logistic team you can use @odoo/rd-logistics

**Comment by celm1990** [comment]
@Whenrow thanks for clarify, please can be review my PR for V13 please???
