### ISSUE TITLE
help for create web service 

### ISSUE THREAD

**Issue by seifeddin** [odoo/odoo#6915]
I need some help to create web service for a new module (create by my self ) I try with the titou in page office https://www.odoo.com/documentation/8.0/howtos/backend.html#webservices but this documentation not have many detail and is not working with me . I search a titou have more detail plzz help guys

**Comment by seifeddin** [comment]
any one here ­!

**Comment by lukebranch** [comment]
@seifeddin ,

This is not the place for questions, it's for reporting bugs. Use the forums!

http://help.odoo.com/

**Comment by seifeddin** [comment]
OK thanks @lukebranch
