### ISSUE TITLE
web service not launched 

### ISSUE THREAD

**Issue by seifeddin** [odoo/odoo#6917]
I crate new web service for new module and I test him with soapui but not result show 
![test](https://cloud.githubusercontent.com/assets/12595044/7910506/362a1292-084d-11e5-9654-5e8d94effeeb.png)
![ss](https://cloud.githubusercontent.com/assets/12595044/7910510/4700449c-084d-11e5-9bba-0cfd8df9aea3.png)

**Comment by seifeddin** [comment]
any one here !

**Comment by xmo-odoo** [comment]
* your declaration makes no sense, it's a script to connect to an existing XML-RPC endpoint not a "declaration of web service"
* what little I can see from the SOAPui screenshot makes no sense to connect to an XML-RPC endpoint. I do not know whether SOAPui can do XMLRPC, but doing a GET on an XMLRPC endpoint is definitely nonsensical:

  http://xmlrpc.scripting.com/spec
 > An XML-RPC message is an HTTP-POST request. The body of the request is in XML. A procedure executes on the server and the value it returns is also formatted in XML.
* questions about how to use odoo belong on the forum or training not the bug tracker
