### ISSUE TITLE
after to declarate the web service 

### ISSUE THREAD

**Issue by seifeddin** [odoo/odoo#6919]
![lol](https://cloud.githubusercontent.com/assets/12595044/7911331/857bffa2-0854-11e5-94aa-1092b3b8d0ae.png)

**Comment by seifeddin** [comment]
why not response !!

**Comment by xmo-odoo** [comment]
1. the bug tracker is for bugs, you probably want the forum
2. the question makes no sense, the xmlrpc API can't be accessed through a browser
