### ISSUE TITLE
Replace Image on https://www.odoo.com/documentation/14.0/setup/cdn.html#step-2-configure-the-odoo-instance-with-your-zone

### ISSUE THREAD

**Issue by rjo-odoo** [odoo/odoo#69212]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):
![28293266](https://user-images.githubusercontent.com/61477595/114610704-1269aa00-9c55-11eb-9496-863f9edcd2ef.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
I don't get the problem.

**Comment by Yenthe666** [comment]
and neither do I 😓

**Comment by rjo-odoo** [comment]
Created in error
