### ISSUE TITLE
[14.0] Accounting: Error on reconciliation model of type “Suggest counterpart values”

### ISSUE THREAD

**Issue by VladimirMaleyev** [odoo/odoo#69277]
Impacted versions:
14.0 Enterprise

Steps to reproduce:
1. Enter runbot infrastructure ( http://runbot.odoo.com/runbot - click on the blue door icon of the 14.0 Enterprise version row - admin/admin)
2. Open Accounting - Accounting Dashboard
3. In Bank journal, click "Reconcile XX items"
4. Find an automatically suggested line "Bank fees"
5. Remove suggested line by clicking on it, switch to Manual Operations tab
6. Locate reconciliation model button "Line with bank fees"
7. Press the gear icon on the "Line with bank fees" button.

Current behavior:
Error message is shown "ValueError: Expected singleton: account.reconcile.model()"

Expected behavior:
No error is shown.

Video/Screenshot link (optional):
![vivaldi_2021-04-15_08-03-15](https://user-images.githubusercontent.com/38422885/114818577-adcd5d00-9dc4-11eb-88ed-dfd1fc43cf7f.png)

![vivaldi_2021-04-15_08-03-45](https://user-images.githubusercontent.com/38422885/114818532-9aba8d00-9dc4-11eb-8e9b-a46b34cf6b55.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
As this is something enterprise, please report it through odoo.com/help instead.

**Comment by VladimirMaleyev** [comment]
Ok, ticket #2507717. Should I close this issue then?

**Comment by pedrobaeza** [comment]
I think we can avoid duplication that way.

**Comment by VladimirMaleyev** [comment]
Ok, thanks. Closing this one.
