### ISSUE TITLE
PoS user cannot open a session

### ISSUE THREAD

**Issue by mhabboush97** [odoo/odoo#69282]
Impacted versions:
14, maybe others
Steps to reproduce:
on runbot, create a user with only PoS user access rights, 
try to open a session
Current behavior:
access error is thrown "You are not allowed to access 'Sales Order Line' (sale.order.line) records."
Expected behavior:
PoS user should be able to open a PoS session
Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/71262174/114834690-7d43ee00-9dd9-11eb-9dfb-d4198bedfabe.png)
seems to be a sale_coupon module error?
Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
I have tried to reproduce the problem in https://7199230-14-0-all.runbot47.odoo.com with demo user restricted to PoS, and I'm not able to get the error.

**Comment by mhabboush97** [comment]
@pedrobaeza this is very weird, it maybe it has something to do with browser cache
closing it :+1:
