### ISSUE TITLE
base_geolocalize violate googleapi terms restrictions usage

### ISSUE THREAD

**Issue by nbessi** [odoo/odoo#6929]
We notice this in issue https://github.com/OCA/geospatial/issues/32

As specified in https://developers.google.com/maps/documentation/geocoding/#Limits

"The Geocoding API may only be used in conjunction with a Google map; geocoding results without displaying them on a map is prohibited. For complete details on allowed usage, consult the Maps API Terms of Service License Restrictions."

https://developers.google.com/maps/terms

"(b) No Pre-Fetching, Caching, or Storage of Content. You must not pre-fetch, cache, or store any Content, except that you may store: (i) limited amounts of Content for the purpose of improving the performance of your Maps API Implementation if you do so temporarily (and in no event for more than 30 calendar days), securely, and in a manner that does not permit use of the Content outside of the Service; and (ii) any content identifier or key that the Maps APIs Documentation specifically permits you to store. For example, you must not use the Content to create an independent database of "places" or other local listings information."

**Comment by mart-e** [comment]
Hello,

You are right, this could be an issue. OpenStreetMap is a nice alternative (go open data!) and if you can adapt @lmignon's PR OCA/geospatial#34 to Odoo, we would gladly accept it.
However, when adapting, please make sure to use standard `urllib` instead of adding `requests` as a new dependency and make sure it's still easy to overwrite in submodules if somebody else wants to use another provider (e.g. if wants to use to MapQuest, Bing,...).

**Comment by nbessi** [comment]
@mart-e ok I'll have a look. That said Bing conditions are the same :P.

**Comment by lmignon** [comment]
@mart-e PR done odoo/odoo#7958

**Comment by Yenthe666** [comment]
@mart-e I know I'm digging up an old one here but what ever happend to this? Is this handled/can it be closed or?

**Comment by mart-e** [comment]
Well we never got a PR if I recall so nothing has changed.

**Comment by Yenthe666** [comment]
@nbessi and @lmignon feel free to make a PR to fix this 😉

**Comment by lmignon** [comment]
@mart-e You've got a PR odoo/odoo#7958

**Comment by mart-e** [comment]
@lmignon but you closed it as it did not worked, right?

**Comment by lmignon** [comment]
@mart-e I no more know why it has been closed. I'm sure it worked for the button on the partner. May be an other part of the code was not working but I don't remember. Sorry.

**Comment by gdgellatly** [comment]
@lmignon @mart-e with the terms changes of July 16 2018 I'm not sure this is relevant anymore as it specifically permits use without a map and with a google map, only non google maps are excluded.

https://cloud.google.com/maps-platform/terms/maps-service-terms/ clause 3.1

The new terms and api service are much better

**Comment by lmignon** [comment]
@gdgellatly Thank you for the link. I'm sure that Odoo will find the better solution. I'm not a lawyer and this issue must be placed into the context of jun 2, 2015. It may be no longer relevant.
