### ISSUE TITLE
[14.0][hr_expense_predict_product] Error at creation of hr.expense with special char

### ISSUE THREAD

**Issue by leemannd** [odoo/odoo#69307]
Impacted versions:
14.0

Steps to reproduce:
- go into application hr_expense -> "my expenses to report" -> create a new hr_expense. When you write into the description something containing a special char, it will fail. Like with: `This fails <`

Current behavior:
The error is coming from the module hr_expense_predict_product. When searching potential products, this modules doest not handle correctly special char.

Expected behavior:
When I'm creating a new expense, I should not have this error. Special characters should be escaped correctly.
This is coming from the method: `enterprise/hr_expense_predict_product/models/hr_expense.py", line 113, in _onchange_predict_product`

Video/Screenshot link (optional):
![hr_expense](https://user-images.githubusercontent.com/3664638/114862270-9acf8280-9dee-11eb-8cc7-883afa2310f2.gif)
Stacktrace -> https://gist.github.com/leemannd/d3790bef00a5737ba168ec51eca1e822

Support ticket number submitted via odoo.com/help (optional):
OPW 2499702

**Comment by pedrobaeza** [comment]
The error is then in `hr_expense_predict_product`, not in `hr_expense`, isn't it?

**Comment by leemannd** [comment]
Hello @pedrobaeza ,
Absolutely. I'm updating the title

**Comment by pedrobaeza** [comment]
Fixed according done PRs.
