### ISSUE TITLE
[14.0] stock : use decimal precision in tree view

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#69313]
Impacted versions: 14.0 (and maybe other

Steps to reproduce:
Go to runbot:
https://7201395-14-0-all.runbot57.odoo.com/web?debug=1#id=185&model=product.product&view_type=form&cids=1&menu_id=528
- set decimal.precision Product Unit of Measure with digits = 5
- set rounding of Unit to 0.0001
- Create a Product
- Start an inventory adjustment
- add product, set 0.999 unit
- Validate Inventory

Go to in product page, you see 0.99900 in stock 
![image](https://user-images.githubusercontent.com/16716992/114864511-5e515600-9df1-11eb-8f8d-dee6194a1fdd.png)

But in quants view you see 
![image](https://user-images.githubusercontent.com/16716992/114865056-0bc46980-9df2-11eb-8268-1e3b7ecf5d49.png)

1.00 != 0.99900

Support ticket number submitted via odoo.com/help (optional):

**Comment by fmdl** [comment]
OPW #2507976

@amoyaux

**Comment by pedrobaeza** [comment]
That's because quant quantity is not restricted by "Product Unit of Measure", and thus is shows in UI always 2 digits. Maybe it can interesting to see if this should be also affected by that precision. What do you think, @amoyaux?
