### ISSUE TITLE
[8.0] Website Blog - Public User can't comment

### ISSUE THREAD

**Issue by JavierIniesta** [odoo/odoo#6932]
Hi,

If you check the Public User's box 'Website Comments', when you try to write a comment without logging in, Odoo raises an internal server error.

Regards,
Javier Iniesta.

![selection_027](https://cloud.githubusercontent.com/assets/11073758/7934605/73b23090-0929-11e5-8b73-12256bfac16c.png)

![selection_028](https://cloud.githubusercontent.com/assets/11073758/7934625/a75b274e-0929-11e5-9568-edd84ad76833.png)

![selection_029](https://cloud.githubusercontent.com/assets/11073758/7934640/c0e8106e-0929-11e5-8d9e-343a91f30e3e.png)

**Comment by flotho** [comment]
Hi,

I also observe the same issue on centos with official rpms

**Comment by rafaelbn** [comment]
We have created this temporary module to fix this issue:
https://github.com/Antiun/antiun-odoo-addons/tree/8.0/website_blog_login_for_comment

**Comment by rafaelbn** [comment]
Hi @beledouxdenis @simongoffin , you (odoo) solve this issue. I think you can close it.

Check

- https://www.odoo.com/web#id=643412&view_type=form&model=project.issue&menu_id=4906&action=1901

And

- https://github.com/odoo/odoo/commit/998ea74c64a0a09f7ea27516cfc61367aaa45b33

Thanks
Regards

**Comment by rafaelbn** [comment]
@beledouxdenis Could you close this issue? It is solved in https://github.com/odoo/odoo/commit/998ea74c64a0a09f7ea27516cfc61367aaa45b33. thanks

**Comment by beledouxdenis** [comment]
Closed with 998ea74c64a0a09f7ea27516cfc61367aaa45b33.
