### ISSUE TITLE
why does my custom module with old api use new api

### ISSUE THREAD

**Issue by webgourou** [odoo/odoo#6936]
HI,

I have a trouble with an on_change function, once called it returns something like
return{'value' : {'data' : value}}
and I get the following error
 File "/media/Media/Devel/odoo/openerp/api.py", line 546, in new_api
    result = method(self._model, cr, uid, self.ids, _args, *_kwargs)
TypeError: update() got multiple values for keyword argument 'context'

here is the method
def onchange_type(self, cr, uid, ids, type_id, context=None): 

it is called by a usual
<field name="type" widget="selection" on_change="onchange_type(type)"/>     

My questions are why does odoo use new api, this module is old api...?
What to change...?

Thanks for support

Aurel

**Comment by Yenthe666** [comment]
Hi @webgourou,

The Github tracker is only used for bugs in the official code and not for questions about custom development. As V8 and down are no longer supported either I'm closing this bug report.

Regards,
Yenthe
