### ISSUE TITLE
recompute old style stored related fields

### ISSUE THREAD

**Issue by clonedagain** [odoo/odoo#6942]
@hbrunn reported in https://github.com/odoo/odoo/pull/6774 :

> Old style related fields behave as function fields now, but we need to set up triggers for the field to be recomputed for changes on all records involved in the path (this only applies if the related field is stored).
> For a demonstration of this bug, go to runbot and change a pricelist's company, observe that the pricelist versions' company is unchanged. As a followup, the pricelist items' company is unchanged too.
> (...)
> This is a serious regression as you put your database in an inconsistent state by changing the company - stored related fields are very often used for company_id, accounting makes a lot of use of it too.

A fix is proposed for v8, but the bug also exists in v6 and v7.

**Comment by flotho** [comment]
Same things here.
trying to override _get_pickings  like this
```
    @api.v7
    def _get_pickings(self, cr, uid, ids, context=None):
        result = super(StockPicking, self)._get_pickings(cr, uid, ids, context=None)
     .../...
     state = fields.Selection(compute=_state_get, type="selection", copy=False,
               store={'stock.move': (_get_pickings, ['state', 'picking_id', 'partially_available'], 20)},
      .../....
```
In the client I have this issue :
```
TypeError: <function _get_pickings at 0x7f7452ef9c80> is not JSON serializable
```

**Comment by flotho** [comment]
This resource https://www.odoo.com/documentation/8.0/reference/orm.html#openerp.api.depends could be an answer

**Comment by Yenthe666** [comment]
Hi @clonedagain,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
As this issue was only present in versions <= 8 this is no longer a bug in newer versions.

Regards,
Yenthe
