### ISSUE TITLE
Date time filter not working properly on any records

### ISSUE THREAD

**Issue by jabirmisnedtech** [odoo/odoo#69438]
Impacted versions:
14.0

Steps to reproduce:
My time zone is GMT+3.
Create any record R1 with previous day's date and time after 21:00.
Create any record R2 with today's date and time after 21:00.
Create a filter to show all todays records (Date is between "<TODAY'S DATE> 00:00:00 and <TODAY'S DATE> 23:59:59" .
Even though R1 is in yesterday's date, it will show in the list.
R2 will not show in this list.
This bug happens only for current day filter.

Current behavior:
When creating date time filter for today's record, system shifts the domain 3 hours before.  The starting time and ending time in the domain. I think here 3 hours is the time zone.

Expected behavior:
Date time filter should work properly so that we can take accurate reports and analysis.                                         
       
Video/Screenshot link (optional):

https://user-images.githubusercontent.com/45730318/115192666-c8207700-a0f3-11eb-8406-b278d48d6fbd.mp4

Support ticket number submitted via odoo.com/help (optional):
#2510005

**Comment by vava-odoo** [comment]
Fixed with https://github.com/odoo/odoo/pull/75663
