### ISSUE TITLE
[8.0] Bad display in calendar of field 'state = fields.Selection(....)'

### ISSUE THREAD

**Issue by sergueikp** [odoo/odoo#6943]
[8.0] Bad display in calendar of field 'state = fields.Selection(....)'

Hello my Odoo friends, here is a new bug,
In fact calendar attribute  'color=', does do not render simple fields as char or select, but it works fine with relational fields!!!

Impacted versions:

8.0 (Nightly build odoo-8.0_20150528) on Ubuntu 14.04 and on Windows 7
Steps to reproduce:
Create inherited model : _inherit = 'fleet.vehicle.log.services'
Create in this inherited model field : state = fields.Selection([
                             ('draft', "Brouillon"),
                             ('planned', "Planifie"),
                             ('end', "Termine"),
                             ('canceled', "Annule")
                             ,], required=True)
Create calendar view
Put in calendar attriute color="state" like this :  "calendar string="Planning entretien" color="state" date_start="date" date_delay="duree""
Put in calendar fields : "field name="state"/"

Current behavior:
Bad display of state field values, on the calendar sidebar the text is troncated and in the calendar we see key instead of value:
![image](https://cloud.githubusercontent.com/assets/9844780/7956529/adb1895a-09e0-11e5-9f3e-76815acf6584.png)
![image](https://cloud.githubusercontent.com/assets/9844780/7956536/b8546648-09e0-11e5-9bfa-211c4b29df5c.png)
![image](https://cloud.githubusercontent.com/assets/9844780/7956551/c4d3c4d6-09e0-11e5-8a9e-5eb3fa091afe.png)

Expected behavior:
It have to display value of field 'state' instead of key and on the sidebar it have to display the not troncated text. 

Best regards.

**Comment by xavieralt** [comment]
Fixed in 91417516ae9399793697d569569dc49945971213
