### ISSUE TITLE
[14.0] website_sale : pay now disabled after click back

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#69453]
Impacted versions:
14.0
Safari 14.1

Steps to reproduce:
- Go to runbot
- Activate Ingenico in test mode (write aaa in required fields)
- go to shop, buy product, select ingenico
- pay now
- you arrive on the ingenico page, press back
- -> Issue the page is block and the button is disabled

Note this issue doesn't exist with chrome.

Video/Screenshot link (optional):
https://user-images.githubusercontent.com/16716992/115214344-b4304180-a102-11eb-87b8-1671f6342495.mov

Support ticket number submitted via odoo.com/help (optional):
OPW #2510281

**Comment by fmdl** [comment]
@JKE-be

**Comment by rdeodoo** [comment]
Fixed with https://github.com/odoo/odoo/commit/fd0c2a18ac469239fe5d9c837f2fee8aa33f846b
