### ISSUE TITLE
Bug: tax columns

### ISSUE THREAD

**Issue by SabrinaReiner** [odoo/odoo#69451]
Hi guys,

I want to add in the column tax a tax rate, but then the system calculate new and change the quantity to 0.083 instead of 0.083333 - and then the subtotal changes. That is wrong. 
So how is it possible the have a quantity of 0.08333333 and not of 0.083??

![Capture](https://user-images.githubusercontent.com/31648193/115213788-27858380-a102-11eb-8f84-beff9a4c2fda.PNG)

So the subtotal in this example should be 2,083.34 € (1/12 for a month).

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

Little tip: check decimal precision.
