### ISSUE TITLE
One2Many search_default 

### ISSUE THREAD

**Issue by ernesto-gm** [odoo/odoo#6946]
**Apply search_default on one2many fields**

Impacted versions:
- 7.0 and 8.0

Steps to reproduce:
 with 
1. Add new filter on model of one2many, in this instance 'mrp.bom.line'
   ![paso1](https://cloud.githubusercontent.com/assets/7605672/7962884/8c6a2f28-09d5-11e5-8765-f0b7f7ded797.png)
2. In mrp.bom Formview add context attribute for set 'search_default_filterName' on field bom_line_ids

![bill of materials - odoo](https://cloud.githubusercontent.com/assets/7605672/7963211/24093328-09d7-11e5-89c0-b8b1065a62e9.png)

I share the following video to see the workings of the incidence:
https://youtu.be/oxgTWOVRk5g

Current behavior:
- Show all records on tree view of mrp.bom.line.

Expected behavior:
- Only show records with filter on tree view of mrp.bom.line.

**Comment by Yenthe666** [comment]
Hi @ernesto-gm,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
