### ISSUE TITLE
rpc.query function in js not working when I am not logged in

### ISSUE THREAD

**Issue by imedC** [odoo/odoo#69473]
Impacted versions: 14.0

Steps to reproduce: 

Current behavior:

Expected behavior:

Video/Screenshot link (optional): 

I want to check for user email before sign in, I am just doing a simple rpc query to retrieve and see all the existing users. but Odoo blocks me with the popup on the right. Any idea about that ? Thanks

![image](https://user-images.githubusercontent.com/6651705/115234627-29a30e80-a111-11eb-96a3-0850c8568e06.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Comment by imedC** [comment]
> Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.
> 
> Closing this by the reason above.

Oh Ok! thanks.
