### ISSUE TITLE
[14.0] microsoft_calendar recurring teams meetings throws `Error: '0001-01-01' is not a correct date`

### ISSUE THREAD

**Issue by theangryangel** [odoo/odoo#69481]
Impacted versions:

At least 14.0.

Steps to reproduce:

1. Sync a calendar with a recurring MS Teams meeting.
2. Attempt to view/open the meeting in Odoo

Current behavior:

Throws the error: `Error: '0001-01-01' is not a correct date`

Expected behavior:

Not to throw an error.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

Can't be bothered to log it on Odoo.com against an Enterprise license for fear of getting the "support pack" response.

**Comment by Yenthe666** [comment]
Seems to be pretty close to https://github.com/odoo/odoo/pull/69106
@nle-odoo @adwid maybe you guys can have a look? :)

**Comment by adwid** [comment]
This issue is not related to the PR you mentioned

**Comment by Yenthe666** [comment]
I didn't say that, I say it is close to it. Fixed in https://github.com/odoo/odoo/commit/7aa233e63a8c82cce8336adb99418a96e061268f
