### ISSUE TITLE
template_attribute_value price_extra not duplicated

### ISSUE THREAD

**Issue by gigaplus** [odoo/odoo#69506]
**Impacted versions:** 14

**Steps to reproduce:**
Select product which has variants
Select Action/Duplicate

**Current behavior:**
Product Variants are duplicated without template.attribute.value price.extra

**Expected behavior:**
Product Variants are duplicated with template.attribute.value price.extra

**Comment by pedrobaeza** [comment]
That's something expected, as that extra prices are not usually the same to other products. That's a design decision. If in your use case, it's better to copy them, then develop a module for duplicating as well such prices.

Closing as won't fix.
