### ISSUE TITLE
Why can't create and delete be used in M2M tree view

### ISSUE THREAD

**Issue by grey27** [odoo/odoo#69521]
odoo\addons\web\static\src\js\fields\relational_fields.js
```
     /**
     * @private
     * @returns {boolean} true iff the list should contain a 'create' line.
     */
    _hasCreateLine: function () {
        return !this.isReadonly && (
            (this.activeActions.create && this.canCreate) ||
            (this.isMany2Many)
        );
    },
    /**
     * @private
     * @returns {boolean} true iff the list should add a trash icon on each row.
     */
    _hasTrashIcon: function () {
        return !this.isReadonly && (
            (this.activeActions.delete && this.canDelete) ||
            (this.isMany2Many)
        );
    },
```

In code, CREATE and DELETE are invalidated if they are M2M fields
What's the reason for this design?I need to restrict creation and deletion of M2M fields

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a development question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
