### ISSUE TITLE
Overbooking time in Tasks????

### ISSUE THREAD

**Issue by diezcode** [odoo/odoo#6954]
Hello , 

My problem is that I can overbook the time when I write my hours to a task. 

When I get to the time limit, it shows like -2.00hours in the "remaining hours" field.

How can I set this, that the employee can't overbook the time I set.

![task-time-overbook](https://cloud.githubusercontent.com/assets/7522882/7984272/2ce2a32a-0ac8-11e5-990d-eedc1ebcdacd.PNG)

I wan't that nobody can overbooking the time that I set in the Creating Tasks!
Thanks

**Comment by diezcode** [comment]
I was searching in the odoo settings, google, odoo.com/apps but nothing to solve my solution, can anybody help me ? thank you so much.

**Comment by Yenthe666** [comment]
Hi @diezcode,

This feature isn't available by default in Odoo.
If you would want this you would have to do some custom development that doesn't allow adding working hours after they're consumed.

Regards,
Yenthe
