### ISSUE TITLE
[Stable Odoo 8.x 9.0 bug] Calendar

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#6955]
In calendar view,

Test field when show, if no data then show false instead of blank.

To show false is meaning less, as similar in tree view when no data, it should be blank.
Follow same for Calendar view.

I hope you(odoo) make a quick fix and commit.

Thanks,

**Comment by tejastank** [comment]
Including selection field instead of rendering value, it render keys. Great merge expected.

**Comment by Yenthe666** [comment]
There is no way for me to reproduce this on the latest V8/V9.
Please update to the latest codebase and try again. If you can still reproduce this bug on the latest runbot please post back.
