### ISSUE TITLE
odoo breaks if postgres db user uses a non ascii char in the password

### ISSUE THREAD

**Issue by rschaerer** [odoo/odoo#6958]
# Summary
odoo breaks after a few successful displays of pages (logged-out and logged in) if the postgres db user uses a **non ascii char** in the password. Maybe the other variables of the for loop `for p in ('host', 'port', 'user', 'password'):` are also affected?

# Detailed setup and error logs
## Setup phase
```
$ createuser --createdb --username postgres --no-createrole --no-superuser --pwprompt odoo
$ Enter password for new role: [password with an non ascii char; example: dy{H3]NR/"Pv:'I1G]
$ Enter it again: [same as above]
```

## cat /var/log/odoo/odoo-server.log after a few successful logins or maybe restart of the machine / odoo service
```
2015-06-04 16:43:19,877 9221 INFO sinndrin-genossenschaft werkzeug: 127.0.0.1 - - [04/Jun/2015 16:43:19] "GET /web/login?redirect=https%3A%2F%2Fv22015032088224253.yourvserver.net%2Fweb HTTP/1.0" 500 -
2015-06-04 16:43:20,144 9221 INFO sinndrin-genossenschaft werkzeug: 127.0.0.1 - - [04/Jun/2015 16:43:20] "GET /favicon.ico HTTP/1.0" 500 -
2015-06-04 16:43:20,201 9221 ERROR sinndrin-genossenschaft werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 285, in app
    return self.app(e, s)
  File "/usr/lib/python2.7/dist-packages/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1290, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1426, in dispatch
    ir_http = request.registry['ir.http']
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 345, in registry
    return openerp.modules.registry.RegistryManager.get(self.db) if self.db else None
  File "/usr/lib/python2.7/dist-packages/openerp/modules/registry.py", line 339, in get
    update_module)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/registry.py", line 356, in new
    registry = Registry(db_name)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/registry.py", line 60, in __init__
    self._db = openerp.sql_db.db_connect(db_name)
  File "/usr/lib/python2.7/dist-packages/openerp/sql_db.py", line 623, in db_connect
    db, uri = dsn(to)
  File "/usr/lib/python2.7/dist-packages/openerp/sql_db.py", line 614, in dsn
    return db_or_uri, '%sdbname=%s' % (_dsn, db_or_uri)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 58: ordinal not in range(128)
```
## extract of the affected traceback which led me to the conclusion that the only variable in my setup with an non ascii char is the password field "cat /usr/lib/python2.7/dist-packages/openerp/sql_db.py"
```python
def dsn(db_or_uri):
    """parse the given `db_or_uri` and return a 2-tuple (dbname, uri)"""
    if db_or_uri.startswith(('postgresql://', 'postgres://')):
        # extract db from uri
        us = urlparse.urlsplit(db_or_uri)
        if len(us.path) > 1:
            db_name = us.path[1:]
        elif us.username:
            db_name = us.username
        else:
            db_name = us.hostname
        return db_name, db_or_uri

    _dsn = ''
    for p in ('host', 'port', 'user', 'password'):
        cfg = tools.config['db_' + p]
        if cfg:
            _dsn += '%s=%s ' % (p, cfg)

    return db_or_uri, '%sdbname=%s' % (_dsn, db_or_uri)
```

**Comment by Yenthe666** [comment]
@antonylesuisse this looks like a serious problem? Might be looked at asap.. I'm sure there are more people that use non-ascii characters.

**Comment by antonylesuisse** [comment]
First it seems to me that dy{H3]NR/"Pv:'I1G is ascii

That said, I dont think it's a important issue, and i recommend to stick to plain alphanumeric ascii for dsn. If you need more entropy just use a longer string http://xkcd.com/936/

If you look at the C api http://www.postgresql.org/docs/current/static/libpq-connect.html used by psycopg it's a const char *conninfo, so the non ascii part is dependent on the locale of the terminal when issuing the createuser command. We could encode the dsn to utf8 before passing it to psycopg but it would encourage a bad practice.

**Comment by DandyCoder** [comment]
I have this exact same issue according to the log: 

  File "/opt/odoo-production/openerp/sql_db.py", line 614, in dsn
    return db_or_uri, '%sdbname=%s' % (_dsn, db_or_uri)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 28: ordinal not in range(128)

However, I seem to have literally no way to resolve this. Are you sure this isn't a bigger problem once its been done?

**Comment by rschaerer** [comment]
I've got two direct E-Mails of users which have the same issue. To clarify, I either could resolve this issue by myslef, even with chainging the passwort to an ascii one (which you correctly stated @antonylesuisse). What I did to workaround this issue: (you probably won't hear it: i switched to [kivitendo-erp](https://github.com/kivitendo/kivitendo-erp), since my evaluation was in favour of this one. Nevertheless odoo rocks in many cases. ;-)

Here are the two messages for archiving purposes:

# From an non GitHub user
> Subject: Odoo - db_user issue
> Hey there,
> 
> Sorry to contact you out of the blue, but quite recently you reported an issue to an Odoo project on github regarding non-ASCII passwords breaking the server.
> 
> What did you do to fix this?
> 
> I've updated my db user password to be ASCII only, but I'm still getting the same error you raised.
> 
> The issue you raised is here: https://github.com/odoo/odoo/issues/6958
> 
> Once again, really sorry to ask you directly about this, but I'm personally struggling and essentially need to get this fixed.
> 
> Kind regards,
> 
> [name removed for privacy]

# From @DandyCoder
> I have this exact same issue according to the log:
> 
> File "/opt/odoo-production/openerp/sql_db.py", line 614, in dsn
> return db_or_uri, '%sdbname=%s' % (_dsn, db_or_uri)
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 28:
> ordinal not in range(128)
> 
> However, I seem to have literally no way to resolve this. Are you sure
> this isn't a bigger problem once its been done?

**Comment by rschaerer** [comment]
Hi DandyCoder

Thank you for contacting me. The issue also persisted on my config and I
couldn't fix it. Read more on my last comment, here:
https://github.com/odoo/odoo/issues/6958

Cheers
Roger

-- 
sinndrin genossenschaft
Alfred-Escher-Strasse 46
8002 Zürich
Tel: 044 534 64 54
Tel. direkt: 076 451 71 31
Mail: roger.schaerer@sinndrin.ch
Web: http://www.sinndrin.ch/

**Comment by mongramosjr** [comment]
Same thing happened to me this day. Downloaded Odoo v9 of version odoo_9.0.20151005_all.deb

and create a database with load demonstration data on it.
After loading, got an error on my web browser

> Internal Server Error

Here is the last lines of traceback

 > File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_qweb.py", line 1185, in to_html
    for attachment in self.css():
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_qweb.py", line 1279, in css
    css += self.css_message(msg)
QWebException: 'ascii' codec can't decode byte 0xef in position 208862: ordinal not in range(128)

**Comment by educalleja** [comment]
I had the exactly the same error as mongramosjr.
I installed less-plugin-clean-css with the following command:
 > npm install -g less-plugin-clean-css

The plugin solved the problem related to line 1279 in ir_qweb.py. I do not know if this affects the non ascii password issue though.

**Comment by mongramosjr** [comment]
Thanks educalleja.  just wondering why I should have to install clean-css thru npm since odoo v9 already depends on **node-less** and **node-clean-css** deb package

**Comment by xmo-odoo** [comment]
@mongramosjr @educalleja your issues have nothing to do with this bug, which is about non-alphanumeric postgres connection information.
