### ISSUE TITLE
Importing Sale Orders from openerp

### ISSUE THREAD

**Issue by fjbatresv** [odoo/odoo#6960]
I have exported all the sale.order from my openerp v7 and now i need import them to odoo v8 recently donwloaded, the problem is that when import only the headers is ok, but when is time for import the lines, The motor don't recognize some products. And give me this error:

'MissingError', u'One of the documents you are trying to access has been deleted, please try again after refreshing.' odoo importation

All the products have the same export_id on a exportation.

**Comment by Yenthe666** [comment]
@fjbatresv 

This is most likely not a problem in Odoo but a problem in your CSV. Do you first try to validate the import before actually importing it? What errors does it throw up?

**Comment by fjbatresv** [comment]
Hello I say this is an error on odoo, because when i remove some lines trying one by one this works,

I have make this import directly to the database, and this has work fine.

**Comment by TheCloneMaster** [comment]
Hi,

You should take a closer look at the log file, there could be some hints
there.

We have been playing around with "oerplib", and used this small python
script to migrate purchase orders from a V6 to a V8 instance.  It could
help you as allows full control of record creation...

shopToShop and categoryMap are "mapping tables" between ids o old system
and new system...


Regards,
-Mario

**Comment by fjbatresv** [comment]
Hello Mario, I have validated everything and this always give me this error. My products have the same "__export__.product_product_XX" id when i import only a list of products in odoo.

**Comment by TheCloneMaster** [comment]
Please paste the log file entries....

**Comment by Yenthe666** [comment]
Closing as no feedback has been given (to post the logs) and as there has been no response anymore in ages.
