### ISSUE TITLE
Odoo and WampServer

### ISSUE THREAD

**Issue by NaduniPulsarani** [odoo/odoo#6961]
Hello,

We are building a database using PhpMyAdmin on our local server(Wamp). Right after installing Odoo 8 we can't access to the database. 

we changed the wamp port, but still doesn't work.

I need to work both of them. 

Please anyone have a suggestions?

**Comment by jsh-odoo** [comment]
I don't know much but I think phpMyAdmin is limited to MySql database. Odoo server is based on PostgreSQL database. I think [phpPgAdmin](http://phppgadmin.sourceforge.net/doku.php) or [pgAdmin3](http://www.pgadmin.org/) might be helpful to you.

**Comment by lukebranch** [comment]
@NaduniPulsarani ,

I suggest you ask this question on the forums, or follow one of the many installation guides out there for installing Odoo 8.0, for example:

https://www.odoo.com/documentation/8.0/
