### ISSUE TITLE
Return value from a button call is not working as expected in new api.

### ISSUE THREAD

**Issue by pouyamn** [odoo/odoo#6962]
current behavior:
When a button_call returns a dictionary for running an action it is ignored. 

expected behavior:
When a function returns a dictionary ( e. g. {'type': 'ir.actions.act_window',...} ) the system should run the action 

reason: 
in api.py, api.one decorator returns a list and in web/controller/main.py it checks for the return value to be a dictionary.

fix:
```python
def call_button(self, model, method, args, domain_id=None, context_id=None):
       action = self._call_kw(model, method, args, {})
        if isinstance(action, list) and len(action)==1:#if the action is from a singleton
            action=action[0]
        if isinstance(action, dict) and action.get('type') != '':
            return clean_action(action)
        
        #I don't know what should be done with a list of actions since action manager accepts json records of a single action only
        # if isinstance(action, list): 
        #     cleaned_actions=[]
        #     for act in action:
        #         if isinstance(act, dict) and act.get('type') != '':
        #             cleaned_actions.append(clean_action(act))
        #     return cleaned_actions
        return False
```

**Comment by xmo-odoo** [comment]
> When a button_call returns a dictionary for running an action it is ignored.

No it's not.

> When a function returns a dictionary ( e. g. {'type': 'ir.actions.act_window',...} ) the system should run the action

Which it does.

> **in api.py, api.one decorator** returns a list and in web/controller/main.py it checks for the return value to be a dictionary.

There's your problem, don't use `@api.one` for methods called by buttons (and more generally don't use `@api.one`)
