### ISSUE TITLE
Computational field for One2many, is no longer supported in Odoo 8 ?

### ISSUE THREAD

**Issue by deepa4lok** [odoo/odoo#6970]
I have a feeling, that a computational / functional field of type One2many is not supported in Odoo 8..

So in the end, I replaced it with Many2many and proceeded with the requirement...

Hence I would like to know am I missing something, or does Odoo no longer supports it or whether it is a bug

**Comment by rvalyi** [comment]
I suggest closing this bug as it is related to an unsupported Odoo version
cc @Yenthe666

**Comment by Yenthe666** [comment]
Hi @deepa4lok,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
@rvalyi thanks a lot for the ping!

Regards,
Yenthe
