### ISSUE TITLE
[13.0][14.0] stock_account: Stock operations for consumables creates stock valuation layers

### ISSUE THREAD

**Issue by AaronHForgeFlow** [odoo/odoo#69719]
```
Impacted versions: 13.0 and 14.0

Steps to reproduce: Create a Purchase Order for a consumable product  and Fifo costing method product category and receive it in stock.

Current behavior: Validating the reception creates stock valuation layers (with remaining quantities).

Expected behavior: No valuation layer is created.
```

I am wondering the utility of having stock valuation layers for a product like this one:
![image](https://user-images.githubusercontent.com/19620251/115749097-0e493500-a397-11eb-871e-3456e2c3253a.png)
![image](https://user-images.githubusercontent.com/19620251/115749903-dc849e00-a397-11eb-9081-e25dfaae18e4.png)

When receiving this consumable it creates stock valuation layers like this one:

![image](https://user-images.githubusercontent.com/19620251/115749845-cd9deb80-a397-11eb-82f6-6d6a38d9cc00.png)

I see two issues here:

- If later in time the company decides to start counting stock for this product and makes the product to be Storable then the existing layers will be used when delivering the product, this is because the remaining quantity is not zero.

-  The stock valuation layer table will increase for nothing, as there is no much utility having the layer for those kind of products (this is going to happen even if the costing method is standard or average)

On the contrary I see not an issue stopping the creation of those layers, as long only storable products will actually be valued. What do you think?

**Comment by pedrobaeza** [comment]
There was a PR removing such valuation layer creation, but then it was reverted due to several problems. Please check such PRs for more information.

**Comment by AaronHForgeFlow** [comment]
Thank you @pedrobaeza !

**Comment by AaronHForgeFlow** [comment]
Well, it seems Odoo removed SVL for consumables here: https://github.com/odoo/odoo/pull/62622 and after they added  SVL for consumables again here https://github.com/odoo/odoo/pull/63386.

The reason is not explained. It seems related to inventory valuation report, but consumables are excluded on that report, so it is still a mystery for me.

**Comment by AaronHForgeFlow** [comment]
Answering myself. It is for setting the price of the stock move of the finished product in a manufacturing order when the Costing method is average or fifo. It is set to the sum of the value of the layers used.
