### ISSUE TITLE
[8.0] Improvement: Allow to define SQL expressions for pivot measured fields

### ISSUE THREAD

**Issue by antespi** [odoo/odoo#6974]
When using graph pivot table, like sale.order, measured fields can have an operator (group_operator attribute) in order to calculate its value: max, min, sum, avg, ... these are functions in PostgreSQL and are applied to the same measured fields.

With current Odoo v8.0 we can not define and SQL expression to do:

* Use value of other measured fields
* Use other oprations like a percentage calculation

For example, if we want to add an Margin percent in sale.order pivot table we currently can:

* Add a new column to sale.report called margin_percent and define its SQL expression. This will give us the margin percent percent of each unique aggregate sale.order.line in sale.report SQL view.
* Define an operator like sum (default), min, max, avg for margin_percent column to use when pivot reads data from sale.order SQL view.

But only min and max operators have a meaning in this case. If we want to calculate aggregated margin_percent we need to read aggregated value of sale_total and purchase_total measured columns. And we can not do it.

This PR improve Odoo in order to do it: https://github.com/odoo/odoo/pull/6973

**Comment by antespi** [comment]
Hi, @ged-odoo, any news? Thanks

**Comment by ged-odoo** [comment]
Hello @antespi,

first of all, sorry for taking so much time.  We are in the process of finalizing some large feature branches, and it takes a lot of time.

Second, I had a positive impression of this branch, but (of course, there always is a but), this is a new feature.  I cannot merge this in 8.0 (nor in saas6).  It should be based on master, and can only be merged in there.  Could you rebase your work on master, check if it works, and resubmit a PR?  Sorry again, I should have reacted sooner.

**Comment by antespi** [comment]
@ged-odoo ok, thanks for your answer

**Comment by antespi** [comment]
@ged-odoo New PR to be merged in odoo/master: https://github.com/odoo/odoo/pull/7331
