### ISSUE TITLE
The relationship "ir_module_module" does not exist

### ISSUE THREAD

**Issue by xiaoniu001** [odoo/odoo#69803]
I put odoo14's initial modules auth_totp, base, base_import, web, web_editor, web_kanban_gauge, web_tour into the custom_addons folder, and generated a database error: psycopg2.errors.UndefinedTable: Error: The relationship "ir_module_module" does not exist

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/14.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).
