### ISSUE TITLE
Override datepicker option in eCommerce Website

### ISSUE THREAD

**Issue by lilywhiteweb** [odoo/odoo#69801]
Impacted versions:
Currently working on Odoo V14

Steps to reproduce:
Create custom js file for module...my example:

```
odoo.define('my_module.extra_info', function (require) {
    'use strict';

    var core = require('web.core');
    var config = require('web.config');
    var publicWidget = require('web.public.widget');
    var VariantMixin = require('sale.VariantMixin');
    var wSaleUtils = require('website_sale.utils');
    const wUtils = require('website.utils');
    require("web.zoomodoo");
    var time = require('web.time');


    var webSiteForm = require('website_form.s_website_form');

    var customWebSiteForm = webSiteForm.include({
        selector: '.s_website_form form, form.s_website_form', // !compatibility
        xmlDependencies: ['/website_form/static/src/xml/website_form.xml'],
        events: {
            'click .s_website_form_send, .o_website_form_send': 'send', // !compatibility
        },
        start: function () {
            console.log('Testing');
        }
    });

});
```

Current behavior:
JS error:
TypeError: Cannot read property 'include' of undefined

Expected behavior:
Should be able to include/extend
If I add the following  to the end of the 000.js file located at addons/website_form/static/src/snippets/s_website_form I can extend/include as the file does not return anything at the minute. 
`return publicWidget.registry.s_website_form;
`
I still need to figure out how I can override the datepicker_options within that file (**_help on how to do that would be appreciated_**). I've found working with dates on the website to be a PITA and have had to write custom methods to handle the date formats etc....am I going mad, or is there any easy way to work with website form inputs when they are dates (I don't want to/can't use the input type="date"...so need to have input type="text")....I've to limit the days that can be picked and also set minDate/maxDate based on conditions.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a development question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here. If you want to provide any compatibility option, like returning an object in JS, you can try with a pull request adding such option, but following stability policy (no API change and no data model change).

Closing this by the reason above.

**Comment by lilywhiteweb** [comment]
Hi Pedro. Thanks for the response. I'm new to Odoo so apologies if I'm not getting this, but is this any different to this issue?
https://github.com/odoo/odoo/commit/d2815c474d7ab24a06f5365d967a602119252b95
I'll submit a post to the forum as well, but being honest I've submitted 3 posts already and never got any response, so I'm not overly confident :(

**Comment by pedrobaeza** [comment]
Yes, you can do something similar to that commit and propose it as pull request, and then it will have more possibilities to be merged. Take into account that all of this works as a voluntary effort, both from community and Odoo employees, so your chances to get something done are;

- Put it in the simplest way for requiring the minimum effort for others to get the task completed.
- If you have an enterprise contract, you can submit a ticket for assuring the visibility of the issue/problem.
- On symmetric communities like OCA, you can ask for things when you have given in a similar measure.
