### ISSUE TITLE
[14.1] pos_coupon promotion applied several times on the same order. 

### ISSUE THREAD

**Issue by UrielLaylineTech** [odoo/odoo#69807]
Impacted versions:
14.1 and up. 
on pos_coupon module. 

Steps to reproduce:
- configure a promotion program applicable from a certain min quantity. 
- configure a fixed price discount.
- open a pos session. 
- add the min quantity from the required product. 
- the discount would be applied. 
- add the same amount again. 
- the discount will not be applied. 

Expected behavior:

- we'd except the discount to be applied for each set of min quantity of products as in every PoS. 
- or at least an option of choosing the limit of number of times the discount can be applied. 

Video/Screenshot link (optional):
runbot master - https://drive.google.com/file/d/1tuPPm2hZy7vxTofOcGMKxW4-dYFqSOH_/view
local db - https://drive.google.com/file/d/1kDYxC_CPD4JwyB_0zUJSjZ_lc_yNXM9Q/view

**Comment by Yenthe666** [comment]
14.1 is not a major stable version. If you are on odoo.com on 14.1 you need to file the report on odoo.com/help :)
