### ISSUE TITLE
supplier invoice number should be required when validate button is pushed

### ISSUE THREAD

**Issue by anajuaristi** [odoo/odoo#6989]
For supplier invoices there should be mandatory to include the supplier invoice number. 
Actually you can validate a supplier invoice with null value on that field. 
Historically before the V8.0 the field used to store this value was Communication Type, field reference and it was mandatory to fill it before validating the invoice. 

Thank you:
Ana

**Comment by fclementic2c** [comment]
+1

**Comment by Yenthe666** [comment]
Hi @anajuaristi,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
