### ISSUE TITLE
Stock minimum rules scheduler not tolerant to failing rules

### ISSUE THREAD

**Issue by mistotebe** [odoo/odoo#6993]
At least in 8.0, if a problem is encountered during reordering rule processing in the scheduler, the Exception is not caught and interrupts the entire scheduler and leaks the cursor.

Steps to reproduce:
- set up a BoM with a line with an incorrect UoM
- set up a reordering rule for the product
- run the scheduler

**Comment by Yenthe666** [comment]
Hi @mistotebe,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
