### ISSUE TITLE
Product Status/State

### ISSUE THREAD

**Issue by zaoral** [odoo/odoo#6994]
In product module the field "Status" is defined in the product.template model

```
        'state': fields.selection([('',''),
            ('draft', 'In Development'),
            ('sellable','Normal'),
            ('end','End of Lifecycle'),
            ('obsolete','Obsolete')], 'Status'),
```

Full source code at [here](https://github.com/odoo/odoo/blob/8.0/addons/product/product.py#L541-L545)

Odoo base module do not manage the product lifecycle concept per se but have this status field to indicate on a basic way the status of the product. This can be interpreted as a product lifecycle status.

I think that the status of the product must be in the product.product instead the product.template. This characteristic is for a Product Variant instead the Product itself. For example I have the next product:

```
Product: Cellphone
    Variant 1:  Black
    Variant 2:  White
    Variant 3:  Blue
```

If the Blue Variant is a special edition and after a while is discontinued I could mark this product variant as `Obsolete`. In the current logic, I don't have the way to differentiate what variant of the Product is Obsolete or not.

**Comment by nhomar** [comment]
@odony what do you think about this, we ca live with this feature until v9 overwritting on our side but it should be greate to know what do you think?

**Comment by pedrobaeza** [comment]
The field has disappeared since v10 (and you have PLM in enterprise), so I think you have your answer ;)

Closing this.
