### ISSUE TITLE
phone_validation error on database update

### ISSUE THREAD

**Issue by diegospire** [odoo/odoo#69955]
Impacted versions: 13.0 Enterprise

Steps to reproduce:
Run a global update operation `-u all` in a current database.

Current behavior:
We receive an `killed` message in the server console.

Expected behavior:
We expect the normal behavior - a complete update

The error seems to be related with phone_validation module.  When we run an update with --log-level=debug
we receive a lot of messages of kind: `Impossible number %s: probably invalid number of digits`

We add a print statement, and we can see a NoneType error, maybe the error is inside some phone_validation method.

Video/Screenshot link (optional):
![swappy-20210427_071756](https://user-images.githubusercontent.com/76488914/116302374-b4fe4e80-a766-11eb-828d-d819383345f0.png)
![swappy-20210427_072154](https://user-images.githubusercontent.com/76488914/116302392-baf42f80-a766-11eb-88c3-d6779798a92b.png)
![swappy-20210427_141027](https://user-images.githubusercontent.com/76488914/116302410-c21b3d80-a766-11eb-95c2-0d752facb0b3.png)
![swappy-20210427_141135](https://user-images.githubusercontent.com/76488914/116302419-c5aec480-a766-11eb-9f26-dc22a5fd2715.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
I'm afraid this is something specific of your deployment/DB state, and can't be handled in this issue tracker. As it seems you have an enterprise contract, please put a ticket in odoo.com/help instead to see if the paid service can help you.
