### ISSUE TITLE
Decorated function executed even no module installed

### ISSUE THREAD

**Issue by agb80** [odoo/odoo#6995]
Specifically I have the problem with module report_custom_filename from here: https://github.com/OCA/reporting-engine/tree/7.0/report_custom_filename

Downloaded the entire repo as we need one of the modules cotained on it, add the entire folder to the addons path and after that start getting some errors because of the function with @http.httprequest decorator on https://github.com/OCA/reporting-engine/blob/7.0/report_custom_filename/controllers/reports.py#L29 is being executed

Simple solution is delete the unused module from addons folder, but wonder why it is executing the decorated function

**Comment by hugosantosred** [comment]
:+1: It's also happening to us. This behaviour makes impossible to download any file from a report in OpenERP unless you delete the module from addons or install it.

**Comment by agb80** [comment]
@hugosantosred are you using v7 too? or can you confirm that the bug is still present on v8?

**Comment by hugosantosred** [comment]
I'm using v7 too. In v8 seems to work without problems

**Comment by sebastienbeau** [comment]
Hi a fix have been proposed here in report_custom_filename. The code is still loaded but not error is raise https://github.com/OCA/reporting-engine/pull/15

**Comment by rvalyi** [comment]
I suggest closing this bug as it is related to an unsupported Odoo version and fixed in recent versions
cc @Yenthe666

**Comment by Yenthe666** [comment]
Hi @agb80,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
@rvalyi thanks a lot for the ping!

Regards,
Yenthe
