### ISSUE TITLE
im_livechat issue

### ISSUE THREAD

**Issue by amindehghani** [odoo/odoo#69960]
Impacted versions: 14.0, 13.0

Steps to reproduce: edit the existing livechat channel and update the module

Current behavior: changes the edited record to default with im_livechat_channel_data.xml

Expected behavior: it is not supposed to changed the data after every upgrade.

More details: 
Hi in the livechat module there is an issue that with every update your default livechat channel that is created by xml data will reset to the file version. maybe adding a noupdate="1" will fix this?

![2](https://user-images.githubusercontent.com/16416527/116347447-78336580-a801-11eb-80db-58a633324988.png)

**Comment by Yenthe666** [comment]
Fixed in https://github.com/odoo/odoo/commit/45c330c1e44d6a9526596b5ec1dfbff317579b68, thanks for reporting! :)
