### ISSUE TITLE
[8.0] Events with Maximum Available Seats set to 0 don't work.

### ISSUE THREAD

**Issue by JavierIniesta** [odoo/odoo#6999]
Hi,

In Events, If you set Maximum Available Seats (Ticket Types) to 0:
![selection_033](https://cloud.githubusercontent.com/assets/11073758/8055566/be543072-0ea0-11e5-851c-1712baa01b39.png)

And set Maximum Available Seats:
![selection_034](https://cloud.githubusercontent.com/assets/11073758/8055588/edc0a854-0ea0-11e5-8426-7e35c57bfe4c.png)

In website, they appear as "Sold Out":
![selection_036](https://cloud.githubusercontent.com/assets/11073758/8055607/10102b0a-0ea1-11e5-97b6-10302baf616a.png)

This is the field's description:
![tooltip_035](https://cloud.githubusercontent.com/assets/11073758/8055615/1febcf3e-0ea1-11e5-841a-cafcddad0b80.png)

Or description is wrong or it is not working as expected.

Regards,
Javier Iniesta.

**Comment by dhp-denero** [comment]
Hello Javier,

I also getting same error.

**Comment by nle-odoo** [comment]
Hello,


With revision c0e24fc9c it should be solved in 8.0.

Regards.
