### ISSUE TITLE
[SaaS-6] Getting client error when try to create new DB

### ISSUE THREAD

**Issue by bud-e** [odoo/odoo#7001]
**Occur Client error when try to create new DB**

Impacted versions:
- SaaS-6

_Steps to reproduce:_

->  Try to create new DB from database manager  _OR_  refresh the **Create** DB page.
->  Snap...
![db-create-error](https://cloud.githubusercontent.com/assets/8414798/8056679/1b8f2c48-0ec8-11e5-8300-214342a95c17.png)

**Comment by xiasun** [comment]
I have similar problem, at the same time I cannot login to the database i have just created, do you have any idea?

**Comment by rvalyi** [comment]
related to an unsupported version of Odoo. Can this be closed?
cc @Yenthe666

**Comment by Yenthe666** [comment]
Hi @bud-e,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
@rvalyi thanks a lot for the ping!

Regards,
Yenthe
