### ISSUE TITLE
MRP operations - calculate start date - compare datetime to str

### ISSUE THREAD

**Issue by zbik2607** [odoo/odoo#7003]
On kanban view, when drag and drop operation date start:

File "/home/odoo/addons/trunk/mrp_operations/mrp_operations.py", line 298, in _move_pass
    if l.production_id and (l.production_id.date_finished > dt):
TypeError: can't compare datetime.datetime to str

**Comment by Yenthe666** [comment]
Hi @zbik2607,

Thanks for the report and sorry that there has been no response.
As this was against the trunk (master) version it isn't relevant anymore. If you can still reproduce it in newer versions then do create a new bug report please.

Regards,
Yenthe
