### ISSUE TITLE
[8.0] website can not clear a html field in web-cms if default language is not english

### ISSUE THREAD

**Issue by michaelkarrer81** [odoo/odoo#7004]
## Steps to reproduce:
1. load a transaltion e.g de_DE
2. set the default language for the webpage to German
3. create a new product page in the website
4. drag and drop a snippet to the product description field
5. safe the page
6. edit the page again and try to delete the snippet so that the field website_description is empty again
7. save the page -> SNIPPET IS THERE AGAIN!
## Expected behavior

website_description field is empty again
## Extra Info

It is possible to clear the html field if the default language is english but not if it is set to any other default language than english.

**Comment by Yenthe666** [comment]
Hi @michaelkarrer81 ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report. A lot has been improved for the website and the editor though so I don't think this is still an issue.

Regards,
Yenthe
