### ISSUE TITLE
Incorrect variable names for installed_version and latest_version

### ISSUE THREAD

**Issue by themreza** [odoo/odoo#70056]
Impacted versions: 13.0, 14.0

Steps to reproduce: None

Current behavior: The `installed_version` field refers to the module's `__manifest__.py` version, and the `latest_version` field refers to the last installed version in the database.

Expected behavior: As their names suggest, `installed_version` should be the last installed database version, and `latest_version` should be the version mentioned in `__manifest__.py`.

There is a comment warning developers about this issue, but as it happened to me, people expect the field name to reflect the value it holds and it may be confusing that it's the other way around.

https://github.com/odoo/odoo/blob/cd9c071c9357cef14635ef094a9f14fc5431956c/odoo/addons/base/models/ir_module.py#L264

**Comment by pedrobaeza** [comment]
Although you are right, it's very difficult to be changed now due to compatibility reasons with external tools and a big risk of breaking things inside Odoo, so closing this as won't fix.

**Comment by themreza** [comment]
It would be nice to fix on Odoo 15.0 as breaking changes are expected.
To clear things up, both fields can be renamed to force developers to update their code.
