### ISSUE TITLE
[8.0_Survey] Rule that prevent the use of tokens

### ISSUE THREAD

**Issue by anderswallenquist** [odoo/odoo#7008]
The rule "Public access to user_input" are set to "[('create_uid','=',user.id)]". Normaly the create_uid are not the same as the responder. If you change the rule to for example [('type', '=', 'link')] your mailed responders can answer the survey.

**Comment by rim-odoo** [comment]
I think this bug has been fixed with this revision: https://github.com/odoo/odoo/commit/812318dcbae13aa6ab87b919b31bc78cc74b97fe
