### ISSUE TITLE
Duplicate Users group on  spanish

### ISSUE THREAD

**Issue by fjbatresv** [odoo/odoo#7010]
Hello everybody i am trying to copy a group on the administration, but This doesn't work on spanish GT. But if my user is with language english this work fine. I can see that the error is on the unique name property of the model, and when I make copy this receive the name on spanish and add the copy word. Finally the write method receive the name on english and not add the copy word.

**Comment by Segebre** [comment]
Dude you are awsome, i finally duplicated what i needed :smiley:

**Comment by ivantodorovich** [comment]
So, no solution to this?

**Comment by fjbatresv** [comment]
I am not really sure if there is someone checking that....

**Comment by Yenthe666** [comment]
Hi @fjbatresv,

Thank you for your report and sorry for the late reply!
@mart-e when you activate the language Spanish and duplicate a group when you're in spanish you'll get this warning:
![image](https://user-images.githubusercontent.com/6352350/34606248-f4d72786-f20e-11e7-86a9-38d2e5c429e3.png)
In English it would just duplicate and add (copy) behind it. Shouldn't something similar happen in another language here too?

Regards,
Yenthe

**Comment by mart-e** [comment]
I made a patch at #22052 to change that but I am not convinced it is the right way.
Maybe we should just drop the unique constrain (not sure it is very important)

**Comment by Yenthe666** [comment]
Hmm I'm not entirely convinced by that PR either. I would think that removing the unique constraint shouldn't be a problem as the real value that needs to be unique is the id and so on. What was the motivation to add the unique constrain?

**Comment by mart-e** [comment]
I guess if you two groups with the same name in your user configuration it starts to be messy and don't know which one is related to which group. I would definitely not advise to have two groups with the same name.
To be discussed

**Comment by Yenthe666** [comment]
Fair point, although that you know that if you copy a record that this is possible. Ideal is to have (copy) in there somewhere probably though. Keep me updated.

**Comment by gustavovalverde** [comment]
Hmmm, now that I'm seeing this issue (came from the PR), I realize that this has been happening to me in multiple models (with Spanish), like taxes, journals, etc (mainly accounting) also when duplicating a record.

**Comment by Yenthe666** [comment]
Yep, this is something that is happening on multiple places and languages. Odd that this never came up more.
