### ISSUE TITLE
PRs not being merged

### ISSUE THREAD

**Issue by bamilab** [odoo/odoo#70111]
Good day,

I was wondering why my PRs were not being merged. They were submitted about 1.5 months ago, and there is still one check that is left unchecked. It tells me that the CLA is not satisfactory.

Is this perhaps because the commit that updated the CLA resides in the master branch instead of that of 12.0, which is the target branch of my PR?

Here are the PR's I'm talking about:
https://github.com/odoo/odoo/pull/67517
https://github.com/odoo/odoo/pull/67514

Thank you.

**Comment by Yenthe666** [comment]
PR's are basically a best-effort basis, without any guarantees. This is a not so active module in Odoo and there's no code owners so it is a bit of everything. 
As for the CLA: you're not in the 12.0 CLA (https://github.com/odoo/odoo/blob/12.0/doc/cla/corporate/therp.md)
Somebody from Odoo will look at it when they have time.
