### ISSUE TITLE
[8.0] stock: stock.move requires serial number but this field is not present

### ISSUE THREAD

**Issue by CyborgDroid** [odoo/odoo#7011]
Hi. The stock Move view does not have a way to add a serial number to the product. I added the product via an HR Expense not a Purchase Order and HR Expenses do not have a way to include a Serial Number. The accounting entries were created and the stock moves as well, I just need to Process the Stock Moves but it won't let me because there is no serial number defined. This is similar to a closed issue (https://github.com/odoo/odoo/issues/4468). The solution suggested there was setting the serial number in the pack operations (is this in a PO?). I need to set the serial number for a stock move originating from an HR Expense, not a PO.

Thanks for your help.

![screen shot 2015-06-10 at 12 11 39 am](https://cloud.githubusercontent.com/assets/8703207/8074851/85842be8-0f05-11e5-8b60-90716f398238.png)

**Comment by Yenthe666** [comment]
Hi @CyborgDroid,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
