### ISSUE TITLE
[8.0] Onchange not launched when "Save & close" (fi: sale order)

### ISSUE THREAD

**Issue by tfossoul** [odoo/odoo#7012]
Hi,

The onchange is not launched telling the user there is not enough stock available when specify qty then directly click on "Save & close" on the wizard.

How to reproduce:
- open the last odoo v8 on runbot, 
- go on sale/sale order,
- create new SO,
- select partner,
- click on "add an item" to add new line on the SO,
- select the product "[A1232] iPad Mini".
- change the quantity by "10000" and then  don't click and DO NOTHING else after except click on the button "Save an close". 
- here the onchange is not launch and the user will not know there is not enough quantity on stock...

note : is you click on an other field or on the side the onchange will be launch..

**Comment by tfossoul** [comment]
Any news ?

**Comment by Yenthe666** [comment]
Hi @tfossoul,

This issue is actually still present in the last 8.0.
@nim-odoo can you have a look at this? The reason is that because you fill in an amount and click on save the on_change does not go off, since it is not triggered.
Its more of an usability issue in my opinion.

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Hi @tfossoul,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
