### ISSUE TITLE
[7.0,8.0] Purchase Order done after invoicing some lines --> no chance to invoice not invoiced lines

### ISSUE THREAD

**Issue by intero-chz** [odoo/odoo#7014]
**Purchase Order done after invoicing some lines --> no chance to invoice not invoiced lines**

Impacted versions:

 - 8.0
 - 7.0

Steps to reproduce:

 1. create new purchase order with 2 lines
 2. choose Invoicing Control "Based on Purchase Order lines"
 3. confirm order
 4. receive products
 5. invoice one of that lines
 6. validate and pay invoice

Current behavior:

 - purchase order is set to done
 - all purchase order lines are set to invoiced
 - no chance to invoice the second line

Expected behavior:

 - purchase order is not set to done
 - the second line is not set to invoice and can be invoiced later

Note:

 - seems to be fixed in master

**Comment by intero-chz** [comment]
Tried to fix it for 7.0 https://github.com/odoo/odoo/pull/7025

**Comment by nim-odoo** [comment]
PR merged.
Thanks!
