### ISSUE TITLE
Entry not valid when reconcilling bank statments

### ISSUE THREAD

**Issue by c-goosen** [odoo/odoo#7015]
In a multi-currency system the conversion to base currency for journal entries and then checking move_lines during bank reconciliation leads to a conversion inaccuracy of 0.01. Took a while to figure out this issue and it relates to a post in 2009 https://bugs.launchpad.net/openobject-addons/+bug/452854. Still testing my solution but it seems so far only line 1563 has to change.

Will update soon.

**Comment by Yenthe666** [comment]
Hi @c-goosen,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 and lower are no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by c-goosen** [comment]
Hahaha 3 years later.  Not sure how to respond to this without sarcasm. Thanks for following up though.

**Comment by Yenthe666** [comment]
I'm very sorry for that, I can understand that it feels bad to you. Just know that I'm not working for Odoo and that I'm doing this in an effort to improve and clean up the

**Comment by c-goosen** [comment]
Yeah sure that I understand. This project's opensource community is a little stunted sometimes. Good luck with the clean up.

**Comment by Yenthe666** [comment]
Thanks! Let us see if we can improve that :) Numbers and response rates are going up quite a lot so that is a good start.
