### ISSUE TITLE
[8.0] Cannot set analytic account as multi-company

### ISSUE THREAD

**Issue by fclementic2c** [odoo/odoo#7020]
In v8, The field 'company_id' is required (in the view only - not in the model) when analytical account is 'regular'. In v7 it was not the case.
It means that I cannot set security rules to share over several companies my analytical chart of account.
Since, there is not virtual chart of account or similar feature to consolidate data in multi-company environnement like for the accounting Chart, it is a issue.
Of course, I could remove the attrs from the view but I am worry about possible side effects.

Is there any reason why it is not possible anymore to share analytical account in multi-company ?

Thanks

**Comment by Yenthe666** [comment]
Hi @fclementic2c,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
