### ISSUE TITLE
[14.0] account_check_printing: Getting Error as the field is only added in search view.

### ISSUE THREAD

**Issue by omalbastin** [odoo/odoo#70211]
The field preferred_payment_method_id is only added in search view, which returns a js type error, very difficult  to identify the issue.  
https://github.com/odoo/odoo/blob/a7060b686e6888da9dd3fb9c46c5e037393a6844/addons/account_check_printing/views/account_move_views.xml#L9

**Comment by pedrobaeza** [comment]
Which are the steps to reproduce the problem?

**Comment by omalbastin** [comment]
@pedrobaeza sorry for wasting your time. I was not able to recreate the issue in runbot. I found that somehow the module account_check_printing is not installed, but its views were added, may be due to failed installation. I havent seen this kind of issue in odoo. Usually if there is a failed installation, it will rollback and remove the module related changes.

**Comment by pedrobaeza** [comment]
I'm afraid I can't tell you what you got that situation.
