### ISSUE TITLE
Odoo 14 Enteprise: Action/Print Menu not visible list view in Odoo mobile application (Android/IoS)

### ISSUE THREAD

**Issue by hareshkansara** [odoo/odoo#70210]
Impacted versions: 14 Enterprise

Steps to reproduce: 
1. Install Inventory Application
2. Go to Inventory > Reporting > Inventory Report (Expand any record and select)
3. On select any record it should visible Action button, but here in mobile version it's not visible.

Current behavior: Action/Print section not visible in list view in odoo mobile application

Expected behavior: Action/Print section should visible on select any record in list view.

Video/Screenshot link (optional): 
![2](https://user-images.githubusercontent.com/25735763/116775612-84c5f100-aa81-11eb-837c-6601ed744d4f.png)
![1](https://user-images.githubusercontent.com/25735763/116775613-868fb480-aa81-11eb-9b83-1e6b48ddccab.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
AFAIK, this is a design decision, but being something enterprise, please report it to odoo.com/help instead.

**Comment by hareshkansara** [comment]
Hello @pedrobaeza ,

Finally i found where actually issue is and it's actually bud in odoo enterprise or something that is missing.

So let me explain if you go to odoo community and check file base.xml (web > static > src > xml  > base.xml), then there is block of code that display Print and Action menu

**<div class="o_cp_bottom_left">
    <div class="o_cp_buttons" role="toolbar" aria-label="Control panel buttons" t-ref="buttons">
        <t t-slot="buttons"/>
    </div>
    <ActionMenus t-if="props.actionMenus and props.actionMenus.items"
        t-props="props.actionMenus"
    />
</div>**

This code is used to display Print and Action menu. But if you go to odoo enterprise and check control_panel.xml (web_enterprise > static >src > xml), then you can see odoo replaced control button view of community and replaced in enterprise. But there is no section to display Print and Control buttons in mobile view section.

I have checked in odoo.sh enterprise code and found the issue.

I have fixed that issue by creating custom addon and enhanced odoo enterprise code and it works fine. But if you check in odoo runbot then it's bug actually.

**Comment by pedrobaeza** [comment]
Yeah, this is a conscious decision made by the Odoo enterprise responsive team.

**Comment by hareshkansara** [comment]
So it will fix by odoo in new update?

**Comment by pedrobaeza** [comment]
You can put the enterprise ticket to ask for that.

**Comment by er-harsh-dhaduk** [comment]
Hi @hareshkansara 

Can you share you updated fix if possible? Seems this issue didn't solved by Odoo yet.

I am also facing this issue.

Thank You

**Comment by RFoerster** [comment]
Hi @hareshkansara  - I would be interested in your solution too if possible! Thanks!

**Comment by hareshkansara** [comment]
@RFoerster 
Could you send me you email here: hareshkansara00@gmail.com

**Comment by renelhs** [comment]
Hi, this is an option:

1- On your custom module create the file with the content bellow:
/static/src/xml/control_panel.xml

<?xml version="1.0" encoding="utf-8" ?>
<templates xml:space="preserve">
    <t t-inherit="web_enterprise.ControlPanel" t-inherit-mode="extension" owl="1">
        <xpath expr="//div[@class='o_cp_bottom_left']" position="inside">
            
            <ActionMenus t-if="props.actionMenus and props.actionMenus.items" t-props="props.actionMenus"/>
        </xpath>
    </t>
</templates>

2- Then in the file __manifest__.py, add:

'qweb': [
        "static/src/xml/control_panel.xml",
    ],
