### ISSUE TITLE
[8.0] Depending field not working well on one2many in edit mode.

### ISSUE THREAD

**Issue by rven** [odoo/odoo#7022]
**Depending field not working well on one2many in edit mode**

Impacted versions:
- 8.0

Steps to reproduce:

<b>res_partner_bank.py</b>

```
from openerp import models, fields, api

class ResPartnerBank(models.Model):

    _inherit = 'res.partner.bank'

    test_field = fields.Boolean('Test Field')
    depends_on_test_field = fields.Boolean('Depends on Test Field', compute='_compute_test_field')
    onchange_test_field = fields.Boolean('Onchange Test Field')

    @api.one
    @api.onchange('test_field')
    def _onchange_test_field(self):
        if self.test_field:
            self.onchange_test_field = True
        else:
            self.onchange_test_field = False

    @api.one
    @api.depends('test_field')
    def _compute_test_field(self):
        if self.test_field:
            self.depends_on_test_field = True
        else:
            self.depends_on_test_field = False
```

<b>res_partner_bank.xml</b>

``` xml
<?xml version="1.0" encoding="utf-8"?>
<openerp>
    <data>
        <record id="view_partner_bank_form" model="ir.ui.view">
            <field name="inherit_id" ref="base.view_partner_bank_form"/>
            <field name="model">res.partner.bank</field>
            <field name="arch" type="xml">
                <field name="partner_id" position="before">
                    <field name="test_field"/>
                    <field name="depends_on_test_field"/>
                    <field name="onchange_test_field"/>
                </field>
            </field>
        </record>
    </data>
</openerp>
```

When editing a bank account of a company, checking the field test_field,
both fields are correctly set.

![screenshot from 2015-06-10 14 15 10](https://cloud.githubusercontent.com/assets/8638295/8082148/4d3271d4-0f7b-11e5-80c8-3ec611abe268.png)

When saving the res.partner.bank form, which closes the form, but not saving the parent company form yet.
When opening the same record again, the depended field is not correctly anymore.

Current behavior:

![screenshot from 2015-06-10 14 15 23](https://cloud.githubusercontent.com/assets/8638295/8082204/ca1941dc-0f7b-11e5-9ec9-1ab1f722ab8c.png)

Expected behavior:

![screenshot from 2015-06-10 14 15 10](https://cloud.githubusercontent.com/assets/8638295/8082233/04a53a54-0f7c-11e5-92bc-009a9b704a44.png)

When creating a new bank account for a company, it works well, this only occurs in edit mode.

**Comment by Yenthe666** [comment]
Hi @rven ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
