### ISSUE TITLE
workflow issue

### ISSUE THREAD

**Issue by mickeychang** [odoo/odoo#7030]
I create a quotations, when click"save", show "Odoo Server Error ...... 
File "D:\Odoo\odoo8\openerp\workflow\service.py", line 81, in create
    WorkflowInstance.create(self.session, self.record, wkf_id)
  File "D:\Odoo\odoo8\openerp\workflow\instance.py", line 54, in create
    WorkflowItem.create(session, record, activity, instance_id, stack)
  File "D:\Odoo\odoo8\openerp\workflow\workitem.py", line 95, in create
    workflow_item.process(stack=stack)
  File "D:\Odoo\odoo8\openerp\workflow\workitem.py", line 116, in process
    if not self._execute(activity, stack):
  File "D:\Odoo\odoo8\openerp\workflow\workitem.py", line 195, in _execute
    inst = instance.WorkflowInstance(self.session, self.record)
TypeError: __init__() takes exactly 4 arguments (3 given)
"
I saw the code in "\openerp\workflow\workitem.py", line 195, it is :
inst = instance.WorkflowInstance(self.session, self.record)

and in "\openerp\workflow\instance.py", line 27, it is:
class WorkflowInstance(object):
    def **init**(self, session, record, values):
          ...

Are there has issue?

**Comment by Yenthe666** [comment]
Hi @mickeychang,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
