### ISSUE TITLE
service in odoo crash automatically

### ISSUE THREAD

**Issue by Anhlq87** [odoo/odoo#7031]
Hi everybody,

I met a problem about service in odoo. Sometime service crash automatically. I don't know what's the problem.I checked on openerp log file but don't have any message here and I checked in syslog file in Ubuntu. It have a message as: 
-> Jun 11 12:00:12 debian16 kernel: [2995203.489726] python[9366]: segfault at 3c ip 00007f0a47486d00 sp 00007f0a3ad66e20 error 4 in etree.so[7f0a473f7000+fa000]
I also checked memory but it's not problem. please everybody help me resolve this problem. Thanks a lot.

**Comment by Anhlq87** [comment]
Everybody help me to solve this problem. Thanks a lot :)

**Comment by hackman61** [comment]
Hello,

Have you got some news about your problem ?

**Comment by Anhlq87** [comment]
No, I have not any solution for this problem. I'm still researching. If I have any solution, I will message for you. You too! :)

**Comment by astirpe** [comment]
I got a crash of Odoo service on Centos 7:

```
Jun 11 17:58:40 project kernel: odoo.py[19234]: segfault at 7f7efd9ac000 ip 00007f7efd9ac000 sp 00007f7f2bff73c8 error 15
Jun 11 17:58:40 project systemd: odoo.service: main process exited, code=killed, status=11/SEGV
Jun 11 17:58:40 project systemd: Unit odoo.service entered failed state.
```
Every hint to solve or prevent such error would be very appreciated. Thank you.

**Comment by Anhlq87** [comment]
I fixed it. I improved my server as improve RAM, CPU. Now it run very good :)

**Comment by hackman61** [comment]
How much RAM and CPU have you set ? I don't understand this fix, because when the server crash, it doesn't consume many RAM or CPU :/

**Comment by Anhlq87** [comment]
the first, I config to server: RAM 8GB & 1 CPU. have 16 client  connect to this server. It over load and service was crash. a week crash about three time. Then I config again server: RAM 16GB & 4CPU to run. Now it run very good and don't have appear that error.

**Comment by matt454357** [comment]
I am having the same issue with 2 of my servers.

One server has 2GB RAM and 1 CPU.  Only 5 clients connect, and usually only one or two at a time.
Another server has 4GB RAM and 4 CPUs.  Only 4 clients connect there.

Adding RAM and CPUs may be a work around, but it's not a solution.  Is there someone who can help us find a real solution?  How to investigate the source of the problem?

**Comment by Anhlq87** [comment]
Hi @matt454357

I have just find a new solution to solve this problem. We can use upstart to restart again service when it die.

**Comment by matt454357** [comment]
I wouldn't call upstart a solution.  The service is crashing sometimes twice per day.  I'm using Debian 7.0 which uses SysV.  I already have a cron job that checks and restarts the service.

**Comment by jpaulin** [comment]
BTW, just a newcomer comment; is the Odoo, process-wise, running as a Python interpreter? So the stability of what we think of the end product is also a function of how stable the Python 2 or Python 3 interpreter is?
