### ISSUE TITLE
Badges are not appearing in my account !

### ISSUE THREAD

**Issue by ahmed-advicts** [odoo/odoo#70393]
Impacted versions:

Steps to reproduce:

Current behavior: Badges are not appearing in my account. My current xp is 4100+ but I didn't receive any badges. ex: I completed my biography but I didn't receive Autobiographer . Why I am not receiving badges?

Expected behavior:
Badges should come in my account.

Video/Screenshot link (optional):
https://www.odoo.com/profile/user/1932936

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
This is not a topic for this issue tracker. Anyways, I remember that this problem is because your profile is private. Closing thus.
