### ISSUE TITLE
[8.0] Amount in bank statement line should be requiered and no zero value accepted

### ISSUE THREAD

**Issue by fclementic2c** [odoo/odoo#7042]
Odoo version 8

![image](https://cloud.githubusercontent.com/assets/5735158/8126287/719bf5ae-10ed-11e5-8241-502c156fa925.png)

I think the field amount in the bank statement lines should be requiered and the value 0.00 not accepted when pressing on button 'Reconcile' because :  
1 - if you do not write any amount it is obviously a user error
2 - the reconcile view does not display the 0 value
![image](https://cloud.githubusercontent.com/assets/5735158/8126356/1a5eeec6-10ee-11e5-9dde-4db155d47a12.png)
3 - If you click on Ok, the bank statement wil generate a entry with only 1 move lines with a debit and credit at zero. 
![image](https://cloud.githubusercontent.com/assets/5735158/8126375/44ff77fe-10ee-11e5-930c-363e832bf127.png)

**Comment by qdp-odoo** [comment]
Hi Frédéric,

first of all: i agree that a transaction of 0 amount is more than probably an error from the user and shouldn't be accepted (v9 won't). 

But on the other hand, our policy regarding the stable versions is to not add constraints that could suddenly block users in their usual process, so adding such a constraint in v8 doesn't seem acceptable.

In my opinion, the check on the manually encoded ending amount = computed amount is enough to detect such mistakes and add another line with the correct amount, so i wouldn't bother making anything regarding this point.

But maybe there's something else i do not foresee?

Thanks
Quentin

**Comment by fclementic2c** [comment]
@qdp-odoo Hello Quentin. I am close to a go live, I would appreciate your comment on this one please. Thanks Frederic

**Comment by qdp-odoo** [comment]
heuu...

i did already.... 7 days ago

https://github.com/odoo/odoo/issues/7042#issuecomment-114835790

On 06/24/2015 01:24 PM, Frédéric Clementi wrote:
>
> @qdp-odoo <https://github.com/qdp-odoo> Hello Quentin. I am close to a 
> go live, I would appreciate your comment on this one please. Thanks 
> Frederic
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/odoo/odoo/issues/7042#issuecomment-114835790>.
>

-- 

Quentin De Paoli
LAN Parties Manager
Odoo (Formerly OpenERP)


odoo.com <http://www.odoo.com/>|Facebook | 
<https://www.facebook.com/odooapps?ref=hl>Twiter | 
<https://twitter.com/odoo>Linkedin | 
<https://www.linkedin.com/company/odoo>Google Plus | 
<https://plus.google.com/u/0/b/100883176139028080672/100883176139028080672/posts>Youtube 
<https://www.youtube.com/user/OpenERPonline>

**Comment by fclementic2c** [comment]
yes, sorry. I saw it afterwards.

Thanks

*camptocamp*

INNOVATIVE SOLUTIONS
BY OPEN SOURCE EXPERTS

*Frédéric Clementi*
Project Manager
Business Solutions

+41 21 619 10 41

www.camptocamp.com


2015-06-24 14:19 GMT+02:00 qdp-odoo <notifications@github.com>:
