### ISSUE TITLE
[12.0]Issue Intrastat country on invoices

### ISSUE THREAD

**Issue by Manuel-Dellisse** [odoo/odoo#70461]
Impacted versions:
12.0

Steps to reproduce:
1. Odoo environment with sale, accounting and Intrastat installed.
2. Make a SO for a customer which the country is part of Intrastat.
3. Just create invoice

Current behavior:
Intrastat country is not set

Expected behavior:
Intrastat country should be equal to the customers country, if country of customer is member of Intrastat.

Additional info:
After some research I have been able to pinpoint the exact commit introducing our issue.
The issue has been introduced by commit 86d82b8 applied on 2021-03-19.

Video/Screenshot link (optional):
Current behaviour:
https://user-images.githubusercontent.com/6159662/117278699-4786a800-ae61-11eb-9976-fbbfd4a5780d.mp4

Before commit 86d82b8 (test at commit 2ec6679)
https://user-images.githubusercontent.com/6159662/117278741-50777980-ae61-11eb-9eb3-f05e665c4b6c.mp4

Screenshot Git checkout at commit 2ec6679
![image](https://user-images.githubusercontent.com/6159662/117278934-7f8deb00-ae61-11eb-925d-97aee8a2b551.png)

Support ticket number submitted via odoo.com/help (optional):
#2524869

**Comment by pedrobaeza** [comment]
As this is something specific of an enterprise module, and being reported through enterprise channel, I'm closing this.
