### ISSUE TITLE
[14.0] mail: issue with hypertext formating

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#70485]
**Impacted versions: 14.0**

**Steps to reproduce:**
create a transaction link like this:
`https://exemple.com/website_payment/pay?reference=100516376&amount=300.0&currency_id=1&partner_id=75178&order_id=533121&company_id=1&access_token=65433c7c1d78a5cb391527eb4035b11b052aeb53b89e9e7526d0b77021d02020`

- create an order, click "send by email"
- paste link in the email
- send it
--> Issue the render of hyperlink is wrong:
During editting
![image](https://user-images.githubusercontent.com/16716992/117308622-05219300-ae82-11eb-8c27-cae1c4332648.png)

Final email
![image](https://user-images.githubusercontent.com/16716992/117308726-19fe2680-ae82-11eb-80eb-c651cb02fa7d.png)

`300.0&currency_id=1` is remplaced by `300.0¤cy_id=1`

If customer copy-paste the link, the copied link is wrong.

Video/Screenshot link (optional):

https://user-images.githubusercontent.com/16716992/117309226-8416cb80-ae82-11eb-8137-3e21296dbf14.mov

Support ticket number submitted via odoo.com/help (optional):

**Comment by fmdl** [comment]
OPW #2525028

@xmo-odoo

**Comment by xmo-odoo** [comment]
@fmdl that's at the interaction of mailing and notifications, so it's basically 600% @tde-banana-odoo

**Comment by fmdl** [comment]
For sure, it is 1200000% a bug :-)

**Comment by fmdl** [comment]
ping @xmo-odoo

**Comment by Yenthe666** [comment]
It's nothing for him. Either way there is an OPW so it should be handled through there? :)

**Comment by xmo-odoo** [comment]
@Yenthe666 apparently the OPW got mis-managed on triage, so switched to the wrong state from which it was auto-closed.

**Comment by Yenthe666** [comment]
Yeah that seems to happen more often actually :( Thanks for moving it back in @xmo-odoo!

**Comment by Gorash** [comment]
```js
const div = document.createElement('div');
div.innerHTML = "https://test.example.com/test?&currency_id"

console.log((div.outerHTML) // "<div>https://test.example.com/test?¤cy_id</div>"
```
