### ISSUE TITLE
[13] Event: Ticket for an event does not respect the price when using a different currency

### ISSUE THREAD

**Issue by yaazkal** [odoo/odoo#70509]
This was tested on this runbot using version 13:  https://7569164-13-0-all.runbot51.odoo.com

Impacted versions: 13 CE

Steps to reproduce:

Guessing USD as the default currency and COP (or any other currency) as an alternative currency.

1. Enable multi currency
2. Create or use a price list with a different currency
3. Create an event with an entry registry
4. Set the product price for the other currency
5. Try to register to an event using the other currency

Current behavior:

Event page shows correctly the price for the other currency but it shows a different price value at the checkout or cart. That price value does not even correspond to the exchange rate configured for that other currency.

Expected behavior:

Price should not change.

Video/Screenshot link (optional):

Price in COP for the event registration shows $ 50,000 as set on the price list for that currency:
![image](https://user-images.githubusercontent.com/5897701/117367012-2df85700-ae87-11eb-9b17-2cabe722a40f.png)

Price in COP shows a different value ($ 22,859.89) at the checkout:
![image](https://user-images.githubusercontent.com/5897701/117367114-55e7ba80-ae87-11eb-9925-dc91e4eb37aa.png)

This is the event and product configuration:
![image](https://user-images.githubusercontent.com/5897701/117367346-af4fe980-ae87-11eb-8464-ddf023afda01.png)
![image](https://user-images.githubusercontent.com/5897701/117367393-bd9e0580-ae87-11eb-83a4-34fc219bbaf2.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by yaazkal** [comment]
Seems this have been fixed, but not sure when/how
maybe in https://github.com/odoo/odoo/commit/14a46b64512c6b9cd8c8459aeda2fb5bf09b345e ?

**Comment by pedrobaeza** [comment]
It can be, but the important thing is that is not reproducible anymore, so closing.
