### ISSUE TITLE
[8.0] One Requests for Quotation from two Quotations with same Supplier

### ISSUE THREAD

**Issue by apesquero** [odoo/odoo#7052]
The description is incorrect, only appearance the first description "SO001:WH: Stock -> Customers MTO", the correct action I think is separate requests for quotation and if you want merge thats.

Thanks you.

**Comment by stephaniemillet** [comment]
Hello, same issue on V9
If several SO create several lines on the sames PR, then on field 'origin' on the PR, or somewhere else, we need to see several reference of SOs : S001, S002 etc.

**Comment by stephaniemillet** [comment]
When creating a PO from a MTO flow , ‘Origin’ field on the PO keep track on the SO number

If we don’t confirm the PO, it creates new lines or increment quantites on existing lines from others SO, through MTO flow, in this existing purchase order - OK

BUT the ‘Origin’ field does NOT keep track on the new SO numbers -> not OK !

This information should be added (somewhere) to keep track

**Comment by Yenthe666** [comment]
Hi @apesquero ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
