### ISSUE TITLE
[12.0][13.0][14.0][BUG] Picking Bug with Pack in result_package_id and partial/backorder qty

### ISSUE THREAD

**Issue by tbaden** [odoo/odoo#70550]
Impacted versions: 12.0, 13.0, 14.0

Steps to reproduce:
- go to odoo runbot or your own odoo with sales and inventory installed
- set 'Delivery Packages' Option in 'Inventory'->'Configuration'->'Settings' 
- set 'Detailed Operations' in the Operation Type 'Delivery Orders' for Warehouse 'YourComapny'
- create a product or use one without any stock (qty = 0)
- create an inventory adjustment for that product, assign it to stock, set a pack (e.g. Pack1) and qty = 2
- create a sale order for that product with qty 2 and confirm it
- go into the 'Deliver Orders' picking of that sale order
- set done qty to 1 in the detailed operations tab:
![Bildschirmfoto 2021-05-07 um 16 46 18](https://user-images.githubusercontent.com/6755125/117467304-daa00a80-af53-11eb-80d7-064c2c51de6e.png)
- validate the picking and press 'create backorder'

Current behavior:
Getting error msg 
"You cannot move the same package content more than once in the same transfer or split the same package into two location."
![Bildschirmfoto 2021-05-07 um 16 35 07](https://user-images.githubusercontent.com/6755125/117467559-16d36b00-af54-11eb-8b1a-66248c6746db.png)

Expected behavior:
remove result_package_id from move_line as it's not completely picked.
picking to be validated/completed and backorder being created correctly

Video/Screenshot link (optional):
currently available on odoo runbot:
try to validate and create a backorder
12.0:
https://7590971-12-0-all.runbot49.odoo.com/web?#id=39&action=374&active_id=39&model=stock.picking&view_type=form&menu_id=552

13.0:
https://7589819-13-0-all.runbot44.odoo.com/web?#id=38&action=361&active_id=41&model=stock.picking&view_type=form&cids=&menu_id=585

14.0:
https://7591223-14-0-all.runbot40.odoo.com/web?#id=43&action=587&active_id=44&model=stock.picking&view_type=form&cids=&menu_id=587

**Comment by pedrobaeza** [comment]
That's not an error and the message is clear: you can't split quantity using the same destination package. Remove the destination package if you are splitting, or transfer it completely. Closing as invalid.

**Comment by tbaden** [comment]
I'm not actively splitting the line. The line got that result_pack value by odoo default behaviour as it contains the whole qty required for that picking. For whatever reason I just found 1 instead of 2, set it as the value and confirmed my picking. Odoos default logic is splitting it when creating a bo and also using result_package_id as the remaining 1, atleast for the system, are still in the package.
If 'move entire pack' is checked, I would agree with you, it's the users input fault if he somehow split it that way, but in this case the odoo logic forces this behaviour. I never intended to put the pack into two places, I simply picked 1 qty and moved it to a new destination and odoo tries to create a second move for that pack when creating the bo. 
So the first move line has to remove that result_pack, as I did pick a single qty and not a pack nor split it into two lines with the same result_package.

**Comment by pedrobaeza** [comment]
The done quantity is manually set to 1, so you have to empty the destination package if you do that.

**Comment by tbaden** [comment]
Yes, that's how to fix it, but the system shouldn't even try to do it the wrong way.
the user didn't actively set the result_pack in the first place, so why should he be responsible to fix the systems fault for it to work?

**Comment by pedrobaeza** [comment]
I don't agree. You are manually changing things, and the system is warning you that the combination is not correct, you have to either transfer whole quantity or empty the field.

**Comment by tbaden** [comment]
I know what you mean, but don't quite agree on the 'manual changing' part, it's the job of the user to enter the actual picked value, which is an intended change, if I enter 1 or 2 shouldn't make any difference on the end result, as it's still a valid option to enter less qty.
I can see both sides of it, yes it is a wrong input combination, but on the other hand is it kind of forced error by the system, as it doesn't catch it's own  mistake.

**Comment by pedrobaeza** [comment]
Odoo has assigned whole package, which is where correct things happen, so if you change the intended automatic assignation, then you have to deal also with that. It's not a big deal. Of course Odoo can add layers and layers of conditions for automatic assistance on multiple things, but then it will get over-complicated on cases that are not going to happen frequently unless you force it manually.

**Comment by tbaden** [comment]
agreeing to disagree 😄
