### ISSUE TITLE
Fit Odoo Sale screen on ipad

### ISSUE THREAD

**Issue by iman-alhaddar** [odoo/odoo#70569]
Hello everyone,

Hope someone find me a way to fix the size of odoo screen on ipad size so that the user don't have to keep moving the screen left and right to complete the order

Waiting a reply,
Thanks in advance,
Iman

**Comment by pedrobaeza** [comment]
You should use enterprise responsive module or find an alternative in community like OCA's web_responsive.

Closing as this is not an issue.
