### ISSUE TITLE
hr_work_entry_contract: Access error when non contract manager open work entries

### ISSUE THREAD

**Issue by luisg123v** [odoo/odoo#70567]
Impacted versions:
- 14.0

Steps to reproduce:
- Configure a user with the "Employee - Officer" rights, but without "Contracts - Manager" ones
- Using that user, go to payroll -> Work entries

Current behavior:
The following error message is shown:

> Error
> 
> You are not allowed to access 'Employee Contract' (hr.contract) records.
> 
> This operation is allowed for the following groups:
> 	- Contracts/Administrator
> 
> Contact your administrator to request access if necessary.

Expected behavior:
I think:
- Either the work enties menu should be hidden if the user is not a contract manager
- Or the work entries menu should be accessible for employee officers, even if tey're not contract managers

Support ticket number submitted via odoo.com/help (optional):
OPW #2526200

**Comment by vava-odoo** [comment]
Fixed with https://github.com/odoo/enterprise/pull/18806
