### ISSUE TITLE
Creating leads error

### ISSUE THREAD

**Issue by fernandonavarro1** [odoo/odoo#70568]
Impacted versions: 14

Steps to reproduce: Install CRM module, activate leads in settings and create a new lead.

Current behavior: 
Error:

Rastreo de error:
Error: field_utils.format[formatType||this.formatType] is not a function. (In 'field_utils.format[formatType||this.formatType](value,this.field,options)', 'field_utils.format[formatType||this.formatType]' is undefined)
_formatValue@http://localhost:8069/web/content/909-4fb3b36/web.assets_backend.js:900:1237
_render@http://localhost:8069/web/content/909-4fb3b36/web.assets_backend.js:978:2230
promiseReactionJob@[native code]

Expected behavior: Create a lead

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by hoangtrann** [comment]
Please provide more information on this. 

- Do you use another language? 
- Do you create Lead in kanban view or form view? 
- Are you able to reproduce the issue on Odoo runbot?

**Comment by fernandonavarro1** [comment]
- I use Spanish
- I've tried both
- I don't know how to use Odoo runbot
@hoangtrann

**Comment by Yenthe666** [comment]
If you can't reproduce it on a runbot there is not much we can do. Usually this is because of a third module or because your Odoo instance is not up to date.
