### ISSUE TITLE
Records are duplicated regardless if I discard or not.

### ISSUE THREAD

**Issue by CondiGroup** [odoo/odoo#70573]
V14.
In any part of Odoo (product, quotes, BoMs, etc), I select a record > Action > Duplicate >   option to SAVE or DISCARD). 

If I select Discard the record will duplicate before saving. I expect the record to only duplicate after selecting to save.

**Comment by pedrobaeza** [comment]
That's not how duplicate works: the action duplicates the record and then present it to you in edit mode. If you discard, you are returning to the duplicated record in read mode. If you want to "undo" the duplication, just delete the new record.

Closing as expected behavior.
