### ISSUE TITLE
Survey on globally distributed software engineering 

### ISSUE THREAD

**Issue by AsWali** [odoo/odoo#70572]
Hey there. 

We are doing a survey on globally distributed software engineering focused on open source projects. If you have some spare time we would really appreciate your response. The form takes about 10 minutes. Thanks in advance!
Survey can be found [here](https://forms.gle/N1TnifRuCYHrCY9JA)

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but an advertising. You should make it on other places, but not here.

Closing this by the reason above.
