### ISSUE TITLE
[14.0][BUG] Can not create RFQ with purchase user role (Vendor related with user)

### ISSUE THREAD

**Issue by newtratip** [odoo/odoo#70624]
**Impacted versions:**
14.0

**Steps to reproduce:**
1. Create new user with purchase user role (In the picture below user "Test")
![Selection_475](https://user-images.githubusercontent.com/24691983/117687741-45ff0c00-b1e2-11eb-91fb-280bd047a74d.png)

2. Login with user "Test" and create RFQ (**select vendor the user's partner**) and save
![Selection_477](https://user-images.githubusercontent.com/24691983/117687990-8eb6c500-b1e2-11eb-9ad8-e32bce4289d4.png)

3. The system throw message access error "You are not allowed to modify 'Users' (res.users) records"
![Selection_476](https://user-images.githubusercontent.com/24691983/117688330-e0f7e600-b1e2-11eb-81e2-0a1ea7592ad3.png)

I think this is bug for purchase module, we don't want access right "Administration/Access Rights" for purchase group

**Comment by pedrobaeza** [comment]
Has this been recreated on an Odoo runbot?

**Comment by newtratip** [comment]
Tested on odoo runbot
**Case1:** Create new vendor (Purchase > Orders > Vendors), example: Azure Interior. **It's no error**
![Peek 2021-05-11 00-06](https://user-images.githubusercontent.com/24691983/117697963-523c9680-b1ed-11eb-8284-1902be29475f.gif)

**Case2:** Vendor (Partner) is auto generated from `res.users` (when create a new user), example: YourCompany, Mitchell Admin. **It's error**
![Peek 2021-05-11 00-14](https://user-images.githubusercontent.com/24691983/117698427-ec9cda00-b1ed-11eb-9cce-fd5b5e94b1c6.gif)

Could we create RFQ for vendor (is user too) ?

**Comment by pedrobaeza** [comment]
You didn't indicate such step (using as vendor the user's partner) in the initial comment. Please do it. It's a weird case though.

**Comment by pedrobaeza** [comment]
Not sure if it's exactly the same, @sswapnesh, as this time you need elevated permissions.

**Comment by jeroen7s** [comment]
Great that it's fixed, I think this affects multiple versions though, at least since v11,
I remember telling customers using v11 they should create a separate contact for a vendor that's not related to a user-account for this reason.

**Comment by sswapnesh** [comment]
Fixed in PR https://github.com/odoo/odoo/pull/64319/
