### ISSUE TITLE
Odoo 14 Ecommerce cross or mixing user account and cart

### ISSUE THREAD

**Issue by Smartstores2021** [odoo/odoo#70714]
Impacted versions: Odoo 14

Steps to reproduce: Update shop cart or change customer password, all at the same time.

Current behavior: I am using Odoo 14 and implement B2C business with Ecommerce App. Many our customers report problems when navigate in the WebSite appear the Opps error and then cross session with other user account. I have recreated the error and detect it happens when at the same time one user add an article to cart and other user open new session or change your password. This error cause an incorrect concurrency manage and mixing account users or carts and payments. 

Expected behavior: Use the ecommerce with normal behavior without issues.

Video/Screenshot link (optional): I am haven´t create a video because the issue is random and need coordinate with other users or workmates for remake this.

Support ticket number submitted via odoo.com/help (optional): 2438712

**Comment by Smartstores2021** [comment]
[https://misotre.com.ec](url)

**Comment by Yenthe666** [comment]
Since there is an official Odoo ticket I'm closing this one off in favor of the official ticket.

**Comment by leimantas** [comment]
We have same bug. After login one user becomes another one. Sometimes even admin.
