### ISSUE TITLE
GET AND SET problem

### ISSUE THREAD

**Issue by seifeddin** [odoo/odoo#7073]
I generate the getter and setter  after that I will launched the server odoo.py but a bug is say filed not exist the declaration of get is like this  
class Entreprise(models.Model):
    _name = 'fs_calcul_cout_de_revient.entreprise' 
    name=fields.Char(string="raison social",required=True)
    ent_description =fields.Char(string="Description")
    ent_form_juridique=fields.Char(string="Form juridique",required=True)
    ent_etablissement =fields.Char(string="Etablissement",required=True)
    ent_rue=fields.Char(string="Rue")
    ent_region=fields.Char(string="Region")
    ent_ville=fields.Char(string="Ville")
    ent_pays=fields.Char(string="Pays")
    ent_code_postal=fields.Char(string="Code postal")
    ent_telephone=fields.Integer(string="Telephone")
    ent_fax=fields.Integer(string="Fax")
    ent_mail=fields.Char(string="Mail")
    ent_site=fields.Char(string="site")

    def get_name(self):
        return self.__name

    def get_ent_description(self):
        return self.__ent_description

    def get_ent_form_juridique(self):
        return self.__ent_form_juridique

    def get_ent_etablissement(self):
        return self.__ent_etablissement

    def get_ent_rue(self):
        return self.__ent_rue

    def get_ent_region(self):
        return self.__ent_region

    def get_ent_ville(self):
        return self.__ent_ville

    def get_ent_pays(self):
        return self.__ent_pays

    def get_ent_code_postal(self):
        return self.__ent_code_postal
and  the code of XML file is  
 record model="ir.ui.view" id="Entreprise_tree_view">
                field name="name">Entreprise.tree</field>
                field name="model">fs_calcul_cout_de_revient.entreprise</field>
                field name="type">tree</field>
                field name="arch" type="xml">
                    tree string="tree_entreprise">
                        field name="get_name(fs_calcul_cout_de_revient.entreprise)"/>
                        field name="get_ent_description(fs_calcul_cout_de_revient.entreprise)"/>
                        field name="get_ent_form_juridique(fs_calcul_cout_de_revient.entreprise)"/>
                        field name="get_ent_etablissement(fs_calcul_cout_de_revient.entreprise)"/>
                        field name="get_ent_rue(fs_calcul_cout_de_revient.entreprise)"/>
                        field name="get_ent_region(fs_calcul_cout_de_revient.entreprise)"/>
                        field name="get_ent_ville(fs_calcul_cout_de_revient.entreprise)"/>
                        field name="get_ent_pays(fs_calcul_cout_de_revient.entreprise)"/>
                        field name="get_ent_code_postal(fs_calcul_cout_de_revient.entreprise)"/>
                        field name="get_ent_telephone(fs_calcul_cout_de_revient.entreprise)"/>                 
                        field name="get_ent_fax(fs_calcul_cout_de_revient.entreprise)"/>
                        field name="get_ent_mail(fs_calcul_cout_de_revient.entreprise)"/>
                        field name="get_ent_site(fs_calcul_cout_de_revient.entreprise)"/>
                    tree>
                field>
            </record> -->
plz help guys

**Comment by xmo-odoo** [comment]
* `<field>` tags take fields, not weirdo unnecessary getter and setter calls
* the field name is the name of the field within the model
* this place is for reporting issues/bugs about odoo, user errors should go on the forums

**Comment by seifeddin** [comment]
thanks for help
