### ISSUE TITLE
Meeting Preview - HoverOver Info

### ISSUE THREAD

**Issue by frankofno** [odoo/odoo#70782]
Impacted versions: Odoo 14 Community Version

Steps to reproduce: Create a meeting in the calendar. In Week view, hover over with your mouse, and the info will be under the sidebar.

Current behavior: The meeting info is under the sidebar

Expected behavior: The meeting info should be visible, either above the sidebar, or on the right side.

Video/Screenshot link (optional): 
![Screenshot 2021-05-12 at 19 00 04](https://user-images.githubusercontent.com/35775329/118015785-f2f99600-b354-11eb-805f-c87b93d7dba2.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by msh-odoo** [comment]
@frankofno I tried to reproduce this issue on runbot(14.0) but could not produce this issue, also note that: meeting popover opens on click not on hover, when I click on meeting in week view it opens on left side.

Would you please provide video, how you produce it? Also would you please give information in which browser you are checking it etc. Thanks.

**Comment by frankofno** [comment]
I've updated firefox to the latest version and changed the adblcoker add-on. now everything looks find on my end too. the pop-up (when clicking on it!) shows up on the left side.
I use Firefox and was using AdBlock Ultimate on macOS. Although the adblocker was disabled for the odoo website, i guess it somehow interfered.

thanks for you reply and effort for looking into it.

**Comment by msh-odoo** [comment]
@frankofno As it is resolved, you can close this issue.
