### ISSUE TITLE
Price doubles when using fiscal position

### ISSUE THREAD

**Issue by lfr-opennet** [odoo/odoo#70804]
**Impacted versions:**
At least V13 and V14

**Steps to reproduce:**
1. Create a product with a tax included in price
2. Create a Sale Order and add this product to a line
3. Add a fiscal position (Example one that transforms that tax to "0%" tax)
4. Change product quantity 

**Current behavior:**
Product price simply doubles.
If product price is 1$ and qty is 1 then total price is 1$
If, with the same original price, qty becomes 2, the price changes to 2$ and the total to 4$.

**Expected behavior:**
Not doubling the price

**Support ticket number submitted via odoo.com/help (optional):**
(#2 527 940)

**Notes:**
This behavior arrived after this commit:
https://github.com/odoo/odoo/commit/48ea669e0e6ff0ceb2f36828457e0d3773b38487

**Comment by pedrobaeza** [comment]
As this is being handled at support team and it depends on a specific tax configuration, let's close it for being solved through the other way.

**Comment by lfr-opennet** [comment]
Firstly, since it has been a while since the Odoo ticket as been created and nothing really happened I created this Issue in a hope someone fixes the bug. Since this bug is not "specific" and does affect a lot of users with this type of usage.
This type of bugs shouldn't happen on a production branch. Specially if it was working before the commit that caused it (or even since V10 or so).

Secondly, this is not a "specific tax configuration", anyone having prices with tax included and fiscal positions has the bug! For instance a website or a company that deals with export and does B2C sales.
It's not "specific" having taxes with the option "included in price" nor using fiscal positions!

If you need some docs, you can check these links:
https://www.odoo.com/documentation/14.0/applications/finance/accounting/taxation/taxes/B2B_B2C.html
https://www.odoo.com/documentation/14.0/applications/finance/accounting/taxation/taxes/fiscal_positions.html

**Comment by pedrobaeza** [comment]
I don't think you will have more attention by this channel than on paid support. By specific I mean that it requires a setup that is not totally explained in the steps to reproduce the problem.

**Comment by lfr-opennet** [comment]
> I don't think you will have more attention by this channel than on paid support.

Even if it isn't faster, the problem impacts a lot of other Odoo clients, and maybe they don't know this bug exists because everything worked until about a week ago. The rest of the community should know about the bug.

> By specific I mean that it requires a setup that is not totally explained in the steps to reproduce the problem.

Yes it is explained, you don't need more than that to reproduce the bug. Have you even tried it? 
If you do want to help, check the attached screen recording video of me reproduction the bug on a runbot.
_(Sorry, this is the video I sent initially to Odoo and the runbut I used was in French, but I think you will easily understand the settings)_

https://user-images.githubusercontent.com/26574217/118285391-ab4c4900-b4d1-11eb-84ad-799f79dc4fb2.mp4

**Comment by pedrobaeza** [comment]
The video is broken. Details are the definition of the involved taxes and fiscal positions.

**Comment by lfr-opennet** [comment]
> The video is broken.

The video is not broken, you are probably using a browser that doesn't support GitHub's video player. Still, I uploaded the video to swiss transfer: https://www.swisstransfer.com/d/a037c73a-f75e-4f09-be24-bdaaa003ef1c
Hope you have a video player that reads .mp4 .

> Details are the definition of the involved taxes and fiscal positions.

What do you mean?

**Comment by pedrobaeza** [comment]
OK, the creation of taxes is seen on the video, so let's reopen this, but don't have a lot of expectations.

**Comment by lfr-opennet** [comment]
Fixed by https://github.com/odoo/odoo/commit/c9330e4af5b034fd81090478723ee3c18be58733
