### ISSUE TITLE
[Idea] use one product.category per metier

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#70803]
Hi @odony @amoyaux @oco-odoo @mart-e @pedrobaeza 

Today in `product.category`, there are some information about accounting, stock, it use in sale report, and in many other place.
But in large company it is too constraining, it is not easy to create "globales" categories will fit on all departments. Customers are flocking to these catch-all categories and why it is the same in each modules.
For exemple stock categories will be not the same for accounting or sale.

This idea is add some adjustment of the actual system:
- keep product.category as it currently exists, juste add `category_type = fields.Selection('global','accounting','sale','stock', ...),  groups='base.dedicated_category', default='global')`, on show relevant field by `category_type` (global show all).
- create a group 'base.dedicated_category'
- in product keep the field `categ_id`, and add :
```python
categ_accounting_id = fields.Many2one(domain=[('category_type', 'in', ('global', 'accounting')], compute='_compute_dedicated_categ_id', store=True, readonly=False, groups='base.dedicated_category', context='default_category_type':'accounting')
categ_stock_id = fields.Many2one(domain=[('category_type', 'in', ('global', 'stock')], compute='_compute_dedicated_categ_id', store=True, readonly=False,  groups='base.dedicated_category', context='default_category_type':'stock')
categ_sale_id = fields.Many2one(domain=[('category_type', 'in', ('global', 'sale')], compute='_compute_dedicated_categ_id', store=True, readonly=False,  groups='base.dedicated_category', context='default_category_type':'sale')

# in case the company don't use dedicated category, others fields are automatically fill.
@api.depends('categ_id')
def _compute_dedicated_categ_id(self):
    for product in self:
          if product._origin.categ_id != product.categ_accounting_id:
                product.categ_accounting_id = product.categ_id
          elif ...
```
- everywhere `categ_id` is use in accounting, replace by `categ_accounting_id`
- do the same for stock, sale, ...

With this new implementation, it will simplify the configuration in large company, each department can create own categories (without break the work of other department). And for little company nothing change (nobody in the group `base.dedicated_category`).

Regards

**Comment by gdgellatly** [comment]
Yes such a problem. Pricelists another massive problem which we solved with a new field called `product.price.category` but required ridiculous amounts of rewriting of pricelist code. Otherwise you basically end up with all these weird dimensions that represent nothing to satisfy the needs of accounts, the needs of pricing and the needs of stock and then sale reporting is basically a mile long graph
