### ISSUE TITLE
How to compile views for a custom module without "Update the module" from applications page?

### ISSUE THREAD

**Issue by laranicolas** [odoo/odoo#70816]
Impacted versions:
13.0

Steps to reproduce:
We are working on a custom module and would like to improve the development flow.

Current behavior:
Each time we update code in a custom module we should update the module in the application Odoo page.

Expected behavior:
Each time we update the code we would like to use odoo shell to restart and update it automatically, considering we are using docker-compose to work with.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

Little tip: use command line or --dev argument options.

**Comment by laranicolas** [comment]
@pedrobaeza sorry for the inconvenience. 

I will take your recommendation and thanks.
