### ISSUE TITLE
[ Buggy Stable Odoo ] Project Management Bugs 

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#7085]
Steps 1:
Project > project > create new project. then fill all information and save.

Steps 2:

Now duplicate newly created project and rename title.

Enough mint steps done.
Now check duplicated new project, chatter till show wrong title (copy).......

With duplicated project, only pure duplication need to show not show (copy) in all duplicated project.
Just follow steps, someone easily know bug with stable Odoo.

Thanks,

**Comment by duanyp1991** [comment]
What do you mean by: 'chatter till show wrong title (copy)' ?

**Comment by Yenthe666** [comment]
Hi @tejastank,

I'm not quite sure what you want to say. You can create a project, duplicate it, rename it and the new name is shown. The old name is shown in the chatter but this is due to `track_change` on this field, that is expected behaviour. Example:
![image](https://cloud.githubusercontent.com/assets/6352350/15896480/d6dd5cd0-2d90-11e6-9d2d-6d65d414c1dd.png)

Regards,
Yenthe

**Comment by tejastank** [comment]
Thanks, after a year you got time to review it.

**Comment by Yenthe666** [comment]
@tejastank don't forget that I'm not a person working at Odoo itself, I'm doing this on a voluntary basis and I don't get paid for this. Just trying to help and improve Odoo.

**Comment by tejastank** [comment]
In that case @Yenthe666 If you don't have solution then why you can't wait for official response to close it. Seems they externally paid you to close it. 

It Seems like black marketing !!!  You don't have a solution so you close all odoo bugs !! 

Thanks to close it. But issue till date exists.

**Comment by Yenthe666** [comment]
@tejastank there is no issue in the first place, so there is no need for a 'solution'.
The thing you're talking about is a feature in Odoo and allows you to keep track of the history of what happend with the project. There is nothing wrong with this.
If there is no bug there is no solution and that means an issue is being closed.

**Comment by tejastank** [comment]
@Yenthe666 You not official guy of odoo, only your positive suggestion acceptable in case only it fix the bug/issue/usability/problem to use odoo.

In case you don't found issue personally to you, please close all 2000+ bugs. Also add their your 1+1/5 advice their. 

In context to your personal opinions and you voluntary please check erpnext open source bugs too, Same python based framework, 

As you voluntary free you can invest time on open source product to improve free***, kindly check speedy erpnext, it more comes with batter licensing than odoo and issues here https://github.com/frappe/erpnext/issues 

Please close issues which open already at erpnext here https://github.com/frappe/erpnext/issues too and keep working free.

As you voluntary free closing all issues without solving it, Appreciated. I sure odoo like to see issue closing very fast. :)

**Comment by tde-banana-odoo** [comment]
Just to close the subject: the behavior is effectively intended. @Yenthe666 explained it correctly, we track the change history. We never rewrite history, so even old message subjects will keep the old record name. Sorry it took one year to review your issue.
