### ISSUE TITLE
[12][13][14] Ambiguous message visibility buttons in portal customer preview

### ISSUE THREAD

**Issue by naglis** [odoo/odoo#70894]
Impacted versions (reproduced on Runbot):

- 12.0
- 13.0
- 14.0

Steps to reproduce:

- Have `sale` module installed.
- As internal user, create/open existing sale order;
- Click _Log note_ in chatter, post some note;
- Click the _Customer Preview_ quick button;
- The message in the cutomer preview under _History_ has a button that says _Visible_ and the tooltip message is _Currently available to everyone viewing this document, click to restrict to internal employees._;
- Copy the SO customer preview access URL and open it in a private window/(or different browser where you are not logged in in this Odoo instance);
- The logged note message is invisible.

Current behavior:

- Messages logged under _Log note_ section in the chatter are shown as _Visible_ (to everyone) to internal employees when viewing SO customer preview, but the message is not shown when customer preview is accessed via the URL with access token or when logged in as customer portal user.

Expected behavior:

- Messages that are internal and are not shown to non-internal users in the customer preview should be marked as _Employees Only_ to internal users in the customer preview.

Debug info:

IIUC, [when rendering the &quot;Visible&quot; and &quot;Employees Only&quot; buttons](https://github.com/odoo/odoo/blob/f964b761eae32016e36dd9d39cc2c35fc2270eba/addons/portal/static/src/xml/portal_chatter.xml#L117) only the value of [`is_internal` field](https://github.com/odoo/odoo/blob/f964b761eae32016e36dd9d39cc2c35fc2270eba/addons/mail/models/mail_message.py#L77) of `mail.message` is considered. However, [when fetching messages for non-employees](https://github.com/odoo/odoo/blob/f964b761eae32016e36dd9d39cc2c35fc2270eba/addons/portal/controllers/mail.py#L195-L197), `_get_search_domain_share()` is used, which [by default filters out](https://github.com/odoo/odoo/blob/f964b761eae32016e36dd9d39cc2c35fc2270eba/addons/mail/models/mail_message.py#L1250) messages that have a subtype that is marked as internal. When posting a message under _Log note_, the message is not marked as internal, but the [`mail.mt_note` subtype is used, which is internal](https://github.com/odoo/odoo/blob/f964b761eae32016e36dd9d39cc2c35fc2270eba/addons/mail/data/mail_data.xml#L33). As a result, the message is shown as _Visible_ to employee users, but is excluded for customers due to internal mail subtype.

Video/Screenshot link (optional):

https://user-images.githubusercontent.com/827324/118513047-fe293900-b73b-11eb-8346-6846ecd3da3b.mp4

**Comment by jqu-odoo** [comment]
Fixed from version 14 onwards: https://github.com/odoo/odoo/pull/88310
