### ISSUE TITLE
Remove the annoying tour popup

### ISSUE THREAD

**Issue by themreza** [odoo/odoo#70916]
Impacted versions: 13.0, 14.0

Steps to reproduce: It happens randomly.

Current behavior: The tour bubble popup blocks menu items despite trying to get the user to click on them.

Expected behavior: No one really cares about the tour and it's rather an annoyance. Make it optional via a custom button somewhere other than on the menu itself.

I saw some tasks marked with RD, but it's really bothersome, at least to me.
I know how to disable them via the development menu, but it's still annoying.

Video/Screenshot link (optional):

https://user-images.githubusercontent.com/5465057/118536118-9d096180-b74b-11eb-8ac7-00fa8bdedfba.mp4

**Comment by pedrobaeza** [comment]
That's your opinion that doesn't serve for anything, but it has been decided this way. Just click first time on the selected menu or installed `web_no_bubble` OCA module.

Closing as no issue.
