### ISSUE TITLE
[14.0] sale_coupon: Different domain on Count/Action of Smart button

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#70911]
Impacted versions: 14.0

Steps to reproduce: 
Create Sales order which any Coupon Programs with valid Code. (SO should be in Draft)
![Screenshot (2)](https://user-images.githubusercontent.com/16624719/118531876-f54c5d80-b763-11eb-8fa4-aef1573f6b68.png)

Current behavior: Open  Coupon Programs 
Count is 1 but Clicking on Smart Button will not display any SO due to mismatch in domain

https://github.com/odoo/odoo/blob/cd9c071c9357cef14635ef094a9f14fc5431956c/addons/sale_coupon/models/coupon_program.py#L14

https://github.com/odoo/odoo/blob/cd9c071c9357cef14635ef094a9f14fc5431956c/addons/sale_coupon/models/coupon_program.py#L27

Expected behavior: Use same count/record

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by sswapnesh** [comment]
@JKE-be  What should be the desired behavior here ? 
Do we want to include all orders or only which are not in 'draft', 'sent', 'cancel' ?
(So I can add PR 😉 )

**Comment by JKE-be** [comment]
Hello

Only confirmed (and so "not in 'draft', 'sent', 'cancel'") make more sense imo, no ? 

//cc @rdeodoo

**Comment by rdeodoo** [comment]
I am not too sure, in practice, how are sales people using this field, both makes sense imo.
Can't the button show confirmed count then load tree view with `Confirmed` filter selected? So user can then remove it if need to see pending orders/cancel etc

**Comment by sswapnesh** [comment]
I am ok with Both, What should be the final one ?

**Comment by rdeodoo** [comment]
What I suggested seems to go in the same direction as jke, no?
Then go for it :)

**Comment by sswapnesh** [comment]
> `Confirmed` filter selected

@rdeodoo  Filter is on website_sale module 😉 

https://github.com/odoo/odoo/blob/ab2663ae0e6f29540b8b8e8ef8b6178ecbd9d7b8/addons/website_sale/views/sale_order_views.xml#L10

**Comment by rdeodoo** [comment]
https://github.com/odoo/odoo/pull/71826 should do the trick
Not sure about 14.0 tho, this is not really a bug. Will see
