### ISSUE TITLE
[All] duplicated calendar colors when more than 24 users

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#70940]
Impacted versions: All, tested in detail on 14.0

Steps to reproduce:
1. Make sure to have a database with 24+ users.
2. Make a calendar event for every single user on another time slot and make sure the user is the responsible.

You can simulate this by making a quick scheduled action on the model `calendar.event` which you just save and run once:
```
customers = env['res.partner']
durations = [4, 5, 0, 6, 8, 14, 9, 10, 3, 1, 4, 5, 0, 6, 8, 14, 9, 10, 3, 1, 4, 5, 0, 6, 8, 14, 9, 10, 3, 1, 4, 5, 0, 6, 8, 14, 9, 10, 3, 1, 4, 5, 0, 6, 8, 14, 9, 10, 3, 1]
counter = 0
start_hour = 0
for item in range(0, 23):
  counter += 1
  start_hour += 1
  end_hour = start_hour + 1

  customer = env['res.partner'].create({
    'name': 'Person ' + str(counter)
  }) 
  
  user = env['res.users'].sudo().create({
    'name': 'User ' + str(counter),
    'login': 'login' + str(counter)
  })
  

  calendar = env['calendar.event'].create({
    'name': 'Meeting item #' + str(counter),
    'partner_ids': [(6, 0, [customer.id])],
    'start': datetime.datetime.today().replace(hour=0, minute=0, second=0) + datetime.timedelta(hours=start_hour),
    'stop': datetime.datetime.today().replace(hour=0, minute=0, second=0) + datetime.timedelta(hours=end_hour),
    'duration': durations[item],
    'user_id': user.id
  })
```

Current behavior:
Starting from user number 24 in the database all the blocks in the calendar views will get the same color code.
This is because the color scheme is hardcoded at:
https://github.com/odoo/odoo/blob/7873144a9f1e68943d14053c3e5d6a945a46e9d5/addons/web/static/src/scss/secondary_variables.scss#L9
and there is a modulo operator doing % 24 which makes stuff fall back to the same color again:
https://github.com/odoo/odoo/blob/7873144a9f1e68943d14053c3e5d6a945a46e9d5/addons/web/static/src/js/views/calendar/calendar_renderer.js#L291
This means that from user 24 on all the blocks will get the same color set. Here's a visual sample showing the issue:
![image](https://user-images.githubusercontent.com/6352350/118621204-6fadc980-b7c6-11eb-9fd0-3b09b553e3d0.png)
<i>Notice:</i> you see this going wrong earlier because there where already some default users ;)  

Expected behavior:
Every single user gets a different color in the UI of the calendar. Otherwise it is extremely hard to manage calendars from employees if you have to schedule appointments. For now on (in stable) it could be random color codes or so but ideally in V15 or onwards it is a configurable field with a hex code that is auto-generated and unique

**Comment by arj-odoo** [comment]
Hello @Yenthe666 thanks for your submission. Your example is nice. No event overlap in your theoretical example but do people actually are trying to display more than 24 calendars in real life situations? It quickly become impossible to read. 
We are modifying the calendar app heavily in V15. We still have these kind of limitations where we are limited to 30 colors.
Random colors are a bad idea because the contrasts become very poor and it causes accessibility problems.

**Comment by Yenthe666** [comment]
@arj-odoo yeah one of my customers has a lot of sellers and then they look at all of them at once to find free slots :)
Even if that is not the case it is still an issue. Imagine you only select "User 25" and "User 26" to show their calendar items. Both these users will have the exact same color, so the issue already pops up there too. As you can see it is very easy to have this issue where you can't easily see which calendar item is from which seller.

**Comment by wtaferner** [comment]
@arj-odoo 
I think the color should get an own field/attribute on the user, so you can apply default colors, but the color can be defined on the user individually.
Of course the user can fuck up the colors, but then it is his/her own responsibility and the limitation does not feel as dictated as it is now by the Design Patrol and hardcoded colors in code 😉 

My 2 cents...

**Comment by arj-odoo** [comment]
@wtaferner We can't introduce a new field in stable versions. 
 In Master, we removed the user_id (Responsible) filter on the calendar application. All is done with the partner (attendees). The calendar view is heavily modified but we will see what we can do with the colors without introducing overengineering.

**Comment by Yenthe666** [comment]
Yeah I agree. In the meanwhile, for stable versions we should come with a fix though. Even something as simple as putting a gradient on the color so it gets some darker/lighter shade after record 24 or so would be good. The current way is really not workable

**Comment by arj-odoo** [comment]
I created a task internally for stable and linked this issue.

**Comment by Yenthe666** [comment]
Awesome, thanks! I will wait for this feedback :)

**Comment by wtaferner** [comment]
@arj-odoo 
My input was meant for master and yeah I guess you guys will figure out a solution without akward hardcoded limitations 😉 
Keeping fingers crossed for a nice solution in stable of course too 😄

**Comment by pedrobaeza** [comment]
@Yajo didn't you have an algorithm reference for generating colors with high-contrast between them?

**Comment by Yajo** [comment]
Yes, check https://github.com/odoo/odoo/pull/32912.
