### ISSUE TITLE
[8.0]Access rights: Marketing/Event Manager needs "Technical Features" access rights to create events or surveys

### ISSUE THREAD

**Issue by treviser** [odoo/odoo#7099]
It is a huge security hole when I have to grant technical features access rights to a manager user in order to perform his daily tasks. 

This the access error:

2015-06-16 13:19:35,916 1097 WARNING restaurant-roessli openerp.models: Access Denied by record rules for operation: read on record ids: [7], uid: 5, model: event.event
2015-06-16 13:19:35,922 1097 ERROR restaurant-roessli openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 536, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 573, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 309, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 306, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 802, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 402, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/mail/mail_thread.py", line 381, in create
    thread_id = super(mail_thread, self).create(cr, uid, values, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 336, in old_api
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 4074, in create
    record = self.browse(self._create(old_vals))
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 4259, in _create
    result += self._columns[field].set(cr, self, id_new, field, vals[field], user, rel_context) or []
  File "/usr/lib/python2.7/dist-packages/openerp/osv/fields.py", line 1489, in set
    self._fnct_inv(obj, cr, user, id, name, value, self._fnct_inv_arg, context)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/website_event/models/event.py", line 60, in _set_show_menu
    if event.menu_id and not value:
  File "/usr/lib/python2.7/dist-packages/openerp/fields.py", line 823, in __get__
    return record._cache[self]
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 5931, in __getitem__
    return value.get() if isinstance(value, SpecialValue) else value
  File "/usr/lib/python2.7/dist-packages/openerp/fields.py", line 55, in get
    raise self.exception
AccessError: ('AccessError', u'Der gew\xfcnschte Vorgang kann aufgrund von Sicherheitsbeschr\xe4nkungen nicht ausgef\xfchrt werden. Bitte kontaktieren Sie den Systemadministrator.\n\n(Dokumenten Typ: event.event, Vorgang: read)')

**Comment by mart-e** [comment]
Hello,

Could you give more information on how to reproduce ? Seems to work fine on the runbot 8.0.
You just need the "event manager" create events and "survey manager" to create surveys.

Which version of odoo ?
Which modules installed ?
Doing which action ?
Please check [contributing](https://github.com/odoo/odoo/wiki/Contributing) guidelines.

**Comment by rcarnes** [comment]
Our approach is that the default security and groups in Odoo are suggestions and that setting up security (your own groups, your own record rules) is part of an implementation.

We find the default groups and record rules VERY permissive.

**Comment by treviser** [comment]
The error happens, when trying to save a new event from the website and 
from the backoffice.

Version installed: 8.0-20150612

Modules installed:

base.module_crm
base.module_mail
base.module_account_voucher
base.module_point_of_sale
base.module_pos_discount
base.module_project
base.module_note
base.module_project_issue
base.module_survey
base.module_BizzAppDev-oerp_no_phoning_home-cc7bb7f47013
base.module_sale
base.module_sale_layout
base.module_stock
base.module_stock_account
base.module_stock_landed_costs
base.module_mrp
base.module_crm_project_issue
base.module_purchase
base.module_hr
base.module_hr_timesheet
base.module_hr_timesheet_sheet
base.module_account
base.module_account_analytic_analysis
base.module_account_analytic_default
base.module_account_analytic_plans
base.module_account_credit_control
base.module_account_credit_control_dunning_fees
base.module_analytic
base.module_analytic_user_function
base.module_auth_crypt
base.module_auth_oauth
base.module_auth_signup
base.module_base
base.module_base_action_rule
base.module_base_geolocalize
base.module_base_iban
base.module_base_import
base.module_base_import_module
base.module_base_location
base.module_base_setup
base.module_base_transaction_id
base.module_board
base.module_bus
base.module_calendar
base.module_contacts
base.module_crm_claim
base.module_crm_helpdesk
base.module_crm_mass_mailing
base.module_crm_partner_assign
base.module_crm_profiling
base.module_dbfilter_from_header
base.module_decimal_precision
base.module_delivery
base.module_document
base.module_edi
base.module_email_template
base.module_event
base.module_event_sale
base.module_fetchmail
base.module_hr_attendance
base.module_hr_timesheet_invoice
base.module_knowledge
base.module_l10n_ch
base.module_l10n_ch_base_bank
base.module_l10n_ch_credit_control_payment_slip_report
base.module_l10n_ch_payment_slip
base.module_l10n_ch_zip
base.module_l10n_multilang
base.module_marketing
base.module_marketing_campaign
base.module_marketing_crm
base.module_mass_mailing
base.module_multi_company
base.module_payment
base.module_payment_paypal
base.module_payment_transfer
base.module_portal
base.module_portal_claim
base.module_portal_project
base.module_portal_project_issue
base.module_portal_sale
base.module_portal_stock
base.module_procurement
base.module_procurement_jit
base.module_procurement_jit_stock
base.module_product
base.module_product_email_template
base.module_product_expiry
base.module_product_extended
base.module_product_margin
base.module_product_visible_discount
base.module_project_issue_sheet
base.module_project_timesheet
base.module_report
base.module_resource
base.module_sale_analytic_plans
base.module_sale_crm
base.module_sale_journal
base.module_sale_margin
base.module_sale_mrp
base.module_sale_order_dates
base.module_sale_service
base.module_sales_team
base.module_sale_stock
base.module_share
base.module_snippet_google_map
base.module_snippet_latest_posts
base.module_stock_dropshipping
base.module_stock_invoice_directly
base.module_subscription
base.module_survey_crm
base.module_theme_common
base.module_theme_notes
base.module_theme_notes_sale
base.module_warning
base.module_web
base.module_web_analytics
base.module_web_api
base.module_web_calendar
base.module_web_diagram
base.module_web_gantt
base.module_web_graph
base.module_web_kanban
base.module_web_kanban_gauge
base.module_web_kanban_sparkline
base.module_website
base.module_website_animate
base.module_website_blog
base.module_website_crm
base.module_website_crm_partner_assign
base.module_website_customer
base.module_website_embed
base.module_website_event
base.module_website_event_sale
base.module_website_google_map
base.module_website_hr
base.module_website_instantclick
base.module_website_less
base.module_website_mail
base.module_website_partner
base.module_website_payment
base.module_website_quote
base.module_website_report
base.module_website_sale
base.module_website_sale_delivery
base.module_website_sale_options
base.module_web_tests
base.module_web_view_editor



On 16.06.2015 17:22, Martin Trigaux wrote:
>
> Hello,
>
> Could you give more information on how to reproduce ? Seems to work 
> fine on the runbot 8.0.
> You just need the "event manager" create events and "survey manager" 
> to create surveys.
>
> Which version of odoo ?
> Which modules installed ?
> Doing which action ?
> Please check contributing 
> <https://github.com/odoo/odoo/wiki/Contributing> guidelines.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/odoo/odoo/issues/7099#issuecomment-112468981>.
>

-- 
twanda AG
Ermin Trevisan
Artherstrasse 19
CH-6318 Walchwil
T    +41 41 758 1515
M    +41 79 208 7373
E    trevi@twanda.com
www.twanda.ch
www.ipadweinkarte.twanda.ch

**Comment by treviser** [comment]
The user has access rights as manager for events and surveys.

On 16.06.2015 17:22, Martin Trigaux wrote:
>
> Hello,
>
> Could you give more information on how to reproduce ? Seems to work 
> fine on the runbot 8.0.
> You just need the "event manager" create events and "survey manager" 
> to create surveys.
>
> Which version of odoo ?
> Which modules installed ?
> Doing which action ?
> Please check contributing 
> <https://github.com/odoo/odoo/wiki/Contributing> guidelines.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/odoo/odoo/issues/7099#issuecomment-112468981>.
>

-- 
twanda AG
Ermin Trevisan
Artherstrasse 19
CH-6318 Walchwil
T    +41 41 758 1515
M    +41 79 208 7373
E    trevi@twanda.com
www.twanda.ch
www.ipadweinkarte.twanda.ch

**Comment by mart-e** [comment]
I figured out what is the issue. This due to the field "Dedicated Menu" that has been enabled and generates new menus on the website. This option is disabled by default.
As this option is quite technical and may produce unexpected behaviour, I will hide it (in next commit) for non-technical users.
Creating a new event without this field should be possible for event managers.

**Comment by treviser** [comment]
Thank you so much!
