### ISSUE TITLE
Unable to reset password from My Profile when login only with OAuth (no password provided before)

### ISSUE THREAD

**Issue by mashanz** [odoo/odoo#71009]
Impacted versions: 13

Steps to reproduce:
- Use user with only have OAuth as login (no password provided)
- Login to Odoo with OAuth Button
- Go to My Profile
- Click *CHANGE PASSWORD* button

Current behavior:
User still need to prompt *old password* even thought there is no old password

Expected behavior:
User able to change password from my profile. If no password provided before because user only have OAuth as login, there should be a button like *CREATE PASSWORD* instead.

Video/Screenshot link (optional):
<img width="287" alt="Jepretan Layar 2021-05-19 pukul 12 17 07" src="https://user-images.githubusercontent.com/9214059/118760093-668f2c00-b89c-11eb-8394-e6abf0592130.png">

**Comment by Yenthe666** [comment]
@odony :)

**Comment by Kalkivi-Keypress** [comment]
sir i didnt get the problem

**Comment by mashanz** [comment]
Hi @Kalkivi-Keypress , User able to login to odoo without password with OAuth (social login button like Google or Facebook), but after the user logged and want to create a password from My Profile. There is no *CREATE PASSWORD* button, instead there is *CHANGE PASSWORD* button only. When the button clicked, it ask the user to prompt old password even though user didn't have password to begin with. It's strange.

**Comment by pedrobaeza** [comment]
When using OAuth, it's not possible to change the password. You should change it on your OAuth provider. Ideal would be to not present such option, but this is planned to be done on later versions, so closing this issue as no issue, but better user output is needed.

**Comment by wtaferner** [comment]
Not pretty, I agree.

💡 Tip: the workaround is to use the reset password functionality and set the inital password via the created token, just in case someone was asking, how the heck can I set a password unrelated to OAuth.
