### ISSUE TITLE
Internal group as shared give error / no info on User Type

### ISSUE THREAD

**Issue by bkautap** [odoo/odoo#71015]
Impacted versions: 14.0, 13.0, 12.0 (tested via runbot)

Steps to reproduce:

Set the internal group: User types / Internal User as share group.
Refresh Odoo and then go to any user.

Current behavior:

The option User Types is has no option for internal user or a error occurered:.
On runbot i have the same issue.
User Type has only portal or public. Internal is missing.

The error:

Traceback:
Error: field_utils.format[(intermediate value)] is not a function
_formatValue@http://localhost:8071/web/content/711-1c83eb5/web.assets_backend.js:906:1237
_renderReadonly@http://localhost:8071/web/content/711-1c83eb5/web.assets_backend.js:1147:107
_render@http://localhost:8071/web/content/711-1c83eb5/web.assets_backend.js:907:95
start/<@http://localhost:8071/web/content/711-1c83eb5/web.assets_backend.js:904:1417

Expected behavior:

Display Internal User option normal

**Comment by pedrobaeza** [comment]
You can't simply do that, as this is something forbidden and incompatible by nature.

Closing as no issue, but incorrect manipulation.
