### ISSUE TITLE
Rollback after SingleTransactionCase Test run?

### ISSUE THREAD

**Issue by zaoral** [odoo/odoo#7102]
I am working in a custom module were I create data demo and unit test using SingleTransactionCase.
I read in the odoo documentation that after all the test methods finish it will make a rollback.

```
class openerp.tests.common.SingleTransactionCase(methodName='runTest')
TestCase in which all test methods are run in the same transaction, the transaction
is started with the first test method and rolled back at the end of the last
```
Check [here](https://www.odoo.com/documentation/8.0/reference/testing.html) the original documentation page. 

In my module after the test is finish it do not make the rollback. I define a demo product and in the test I change two values of that record. This fields changes remains in the instance after the unit test. Like when we use --test-commit option running the openerp-server. Then, when I try to run for second time the unit test it through me an error because the initial values needed are not the original ones.

I change my code and try to use one big continue test case using TransactionCase instead. The results in the instance is the same, the instance show me the changes made in the test tangibles, but the unit test do not through me any error. I dont understand why this is happening.

Then I try to change to no use the browse_ref() method to use the env.ref() but not change was accomplish.

This is the expected result or is a bug? In odoo v8 the python tests are automatically committed into the database?

**Comment by xmo-odoo** [comment]
No the Python tests are not automatically committed to the database, the rollback statement is present in both [TransactionCase](https://github.com/odoo/odoo/blob/8.0/openerp/tests/common.py#L149) and [SingleTransactionCase](https://github.com/odoo/odoo/blob/8.0/openerp/tests/common.py#L170).

*However* the testing infrastructure can't rollback:
* if you have explicitly committed operations on the cursor it's provided
* anything you've done on cursors you've created by hand

**Comment by blaggacao** [comment]
@xmo-odoo As a simple `_auto_init()` on BaseModel does several commits down the way and as auto init is part of the AND as `_auto_init()` is called on strategic `create()` overwrites, like for example in `ir.model.fields`, creating a temporary column through the ORM will result in the observed side effects.
As this is close to a bug (or at least a severe impediment for integration tests of migration scripts), I wonder if it's worthwhile to explore possibilities to mock `cr.commit()` by default.

Arguably, `SingleTransactionCase` is prone to be used / misused for integration testing. So we have an implicit purpose here. Whether that's a good place for integration testing or not is probably another question...

**Comment by blaggacao** [comment]
Something that seems interesting to wrap dangerous calls to commiting methods:
```
 self.registry.enter_test_mode()
 self.registry.leave_test_mode()
```

The implementation in `sql_db.py` looks nice, too. Just doing release savepoints and immediately creating another one in lieu of doing real commits.

@zaoral pretty sure, this can solve your problem, too.

**Comment by blaggacao** [comment]
This is how I managed to patch the SavepointCase:
However one undesirable side effect goes as follows:
- The mentioned autoinit does committing, I guess, in order to ignore not null constraint violations and similar, which are supposed to just be a warning in Odoo, however this setup reacts sensible to those violations and rises an error. So you cannot test copying columns which have an inherent not null constraint.
```
class GetValuesDiffTestCase(common.SavepointCase):

    @classmethod
    def tearDownClass(cls):
        super(GetValuesDiffTestCase, cls).tearDownClass()
        cls.registry.leave_test_mode()

    @classmethod
    def setUpClass(cls):
        cls.registry = RegistryManager.get(get_db_name())
        cls.registry.enter_test_mode()
        cls.cr = cls.registry.cursor()
        cls.uid = openerp.SUPERUSER_ID
        cls.env = api.Environment(cls.cr, cls.uid, {})
```

As the `setUpClass` is basically a rewrite of the inherited class, I'll prepare a pull request which makes patching the cursor as easy as on the TransactionCase, by changing the instance method to a staticmethod.
