### ISSUE TITLE
[8.0] Impossible to Design Email template in the Mass Mailing if Website default language is not English

### ISSUE THREAD

**Issue by sergueikp** [odoo/odoo#7105]
Impacted version : 
- 8.0-20150616 (on Ubuntu and Windows)
  I was able to reproduce the issue on runbot: http://76218-8-0-404b66.runbot7.odoo.com 
  Module installed Mass Mailing

How to reproduce the issue:
![email_template_issue](https://cloud.githubusercontent.com/assets/9844780/8195831/e89fd51c-1485-11e5-995c-a7a4d8ba854d.JPG)
1. In Translations > click "Load a translation",  select a language other than English, check Website to translate : localhost  and click "Load"
2. In Configuration>Website Settings put default language any except English (in my case Russian),
3. In Marketing>Mass Mailing click "Create", then in form click "Design Email"  
   3.1. Sometimes you will see a pop-up prompting you  to translate the web page, 
4. On the page "Choose an email template" click "Select" under your favourite template, then click "Save", 

Current behaviour:
5. The blue button "Back to the mass mailing" will be replaced by a white button "Back", and you will be unable to attach a selected Email template to your mass mailing. 

Expected behaviour:
The blue button "Back to the mass mailing" should be available and user mast be able to attach the selected template to it's mass mailing.

**Comment by Yenthe666** [comment]
Hi @sergueikp ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
