### ISSUE TITLE
Installing odoo on cpanel

### ISSUE THREAD

**Issue by gemchand** [odoo/odoo#7106]
can it possible to install odoo 8 on cpanel?

**Comment by lukebranch** [comment]
@gemchand ,

I think this would be possible, you'll just need to make sure Odoo's dependencies do not interact negatively with cPanel/WHM.

With that being said, as this is an issue reporting system for bugs/issues with the software, this is not the correct place to post questions regarding deployment.

I'd recommend creating a forum post here:

http://help.odoo.com/

as the forums are the correct plaec to ask these kinds of questions.

**Comment by gemchand** [comment]
@lukebranch please help me to install odoo on cpanel

**Comment by rvalyi** [comment]
this is a support question. Please use forums instead. 
@Yenthe666 can we close it?

**Comment by Yenthe666** [comment]
Hi @gemchand,

This should have been placed on the official help forum (help.odoo.com) so I'm closing this bug report.

Regards,
Yenthe
