### ISSUE TITLE
[11][12][13][14][15]urls object has no attribute url_parse

### ISSUE THREAD

**Issue by niulinlnc** [odoo/odoo#71076]
When I use install_from_url, I get an error:
urls object has no attribute url_parse
the reason( v14):
base.models.ir_module.py
def install_from_urls(self, urls):
On line 787:
apps_server = urls.url_parse(self.get_apps_server())
On line 798
up = urls.url_parse(url)
The urls here are not introduced and conflict with the parameter urls with the same name
This problem exists in v11, v12, v13, v14, and v15!
Although this method is not used publicly, I hope that the code does not make mistakes.
I found that it was caused by a merger of @xmo-odoo  in 2017 [https://github.com/odoo/odoo/commit/01e35141479b8dfc4a390518f89fc52e7cec5396](url)
@odony

**Comment by xmo-odoo** [comment]
Good catch! Now that's a dumb error.
