### ISSUE TITLE
'Stock' product quantities not recomputed based on 'compute_child' context

### ISSUE THREAD

**Issue by pseem** [odoo/odoo#71072]
Impacted versions: 13.0

Steps to reproduce:  
Access a computed quantity (e.g. 'virtual_available') before and after adding/removing/changing the context's 'compute_child' value for a product.product record. 

Current behavior:
Quantites are not recalculated, even though changing 'compute_child' should result in different quantites (see _get_domain_locations_new).

Expected behavior:
Recalculate quantities if 'compute_child' changes.  The @api.depends_context decorator for the _compute_quantities function ('stock' module, product.py) should include 'compute_child'

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):
 #2535461

**Comment by pedrobaeza** [comment]
Please specify steps to reproduce such problem in the UI, not talking about technical part.

**Comment by pseem** [comment]
There are no steps to reproduce in the UI. It is a request to fix a bug in the technical part.

PS
________________________________

**Comment by pedrobaeza** [comment]
Well, that's not enough for this issue tracker. As you have issued an enterprise ticket, I let them to answer you in the same manner or digging a bit more, so closing this one.
