### ISSUE TITLE
po translations for the same text occurring in different aeroo reports are not loaded

### ISSUE THREAD

**Issue by a0c** [odoo/odoo#711]
If there are 2 or more aeroo reports featuring the same translatable text and a correct po file with translations (e.g.:
```
#. module: my_module
#: report:ir.actions.report.xml:my_module.report1_xml_id
#: report:ir.actions.report.xml:my_module.report2_xml_id
msgid "Invoice"
msgstr "<Invoice_in_some_other_language>"
```
), then only the first report (report1_xml_id) will have its translation imported.

This happens both at normal module update and at manual translations import (from menu Settings > Translations > Import/Export > Import Translation).

==========================
Reason:
/server/openerp/addons/base/ir/ir_translation.py:
        ir_translation_import_cursor#finish():  find_expr

When looking for existing translations to match those being imported, variable find_expr considers res_id for comparison only when the record is of type=='model'.
Since aeroo reports should also be compared by res_id, the correct find_expr should be:
```
         find_expr = "irt.lang = ti.lang AND irt.type = ti.type " \
                     " AND irt.name = ti.name AND irt.src = ti.src " \
---                    " AND (ti.type != 'model' OR ti.res_id = irt.res_id) "
+++                    " AND (ti.type NOT IN ('model','report') OR ti.res_id = irt.res_id) "
```
I couldn't manage to fix this part of ir_translation.py from inside of my own module (i.e. non-intrusively), so had to introduce this change into the server part.

It would be great if anybody had an idea of how this change could be introduced into the aeroo module, instead of touching the server side.

Launchpad bug: https://bugs.launchpad.net/aeroo/+bug/1333037

**Comment by Yenthe666** [comment]
Dear @a0c,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
