### ISSUE TITLE
[14.0] account_assets : existing depreciation schedule

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#71106]
Impacted versions: 14.0

Steps to reproduce:
You already on asset in 2019, and you start with Odoo in 2021.

The asset with all account.move is
![image](https://user-images.githubusercontent.com/16716992/118991941-771ad180-b984-11eb-8ed1-8782edaa2f38.png)

If you start Odoo in 2021 it should be
![image](https://user-images.githubusercontent.com/16716992/118992452-f27c8300-b984-11eb-978c-38ab142b59ba.png)

But when you run the compute of depreciation you have
![image](https://user-images.githubusercontent.com/16716992/118992641-1b9d1380-b985-11eb-8785-7944ec6e02b4.png)

It is wrong.

Note : fields depreciation_number_import and first_depreciation_date_import is not use to compute account.move

Can you explain how it works ?

@oco-odoo @william-andre

**Comment by fmdl** [comment]
OPW #2536167

**Comment by william-andre** [comment]
@fmdl These fields are only used in the Deprecation Schedule as a report, not the the Deprecation Board in the form view.

They are used when the journal entries already exist.
