### ISSUE TITLE
Updating One2many field inside onchange breaks the field

### ISSUE THREAD

**Issue by Gumaa** [odoo/odoo#71123]
**Impacted versions:** 13.0

**Steps to reproduce:**
Create onchange method that updates One2many field like this:

```python
class HrExpenseSheet(models.Model):
    _inherit = "hr.expense.sheet"


    @api.onchange('employee_id')
    def _update_expense_ids(self):
        
        # get product

        values = {
            'product_id': product.id,
            'name': product.name,
            'unit_amount': 10, 
            'quantity': 2, 
        }
            
        self.update({'expense_line_ids':[(0, 0, values)]})
```
Go to (in this example) `hr.expense.sheet` and try to edit expense lines.

**Current behavior:**
When trying to add new row manually (under rows generated with python) Odoo throws an error:
`psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type integer: "virtual_4393"
LINE 1: ...mpany_id" = 1))  AND  (("hr_expense"."id" not in ('virtual_4...`

Also when I'm clicking on rows generated from python I'm getting a wizard for creating completely new record - data from clicked row is not filled in. And when I'm saving this wizard nothing happens and table still displays data added with python.

**Expected behavior:**
Odoo should allow me to add new row manually and edit existing ones

This approach worked without problems on Odoo 8.

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a development question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Comment by AfroMonkey** [comment]
I have a very similar issue, but it was because I "create" the records in a M2M field using the [(0, None, {'a': 1}) sintax. Was solved creating the lines using model.create([{'a': 1}])
