### ISSUE TITLE
[14.0] website_event_track: Duplicate field

### ISSUE THREAD

**Issue by tranngocson1996** [odoo/odoo#71133]
* Impacted versions: 14.0

* Steps to reproduce:

In code, `module website_event_track` -> model `event.track.stage` . I see duplicate field `is_done`

* Video/Screenshot link (optional):
![duplicate](https://user-images.githubusercontent.com/26604325/119120312-5753de00-ba56-11eb-9864-f9ff00f53589.png)

I think it is wrong. Can you explain what is this?

**Comment by pedrobaeza** [comment]
Well, it's not the best, but that doesn't produce any errors, so if you want, check master branch and propose a PR removing the duality if still present, but nothing to be fixed and it won't be accepted in stable, not being a fix per se, so closing this issue.
