### ISSUE TITLE
Odoo restarting server on every refresh I make for my system.

### ISSUE THREAD

**Issue by iman-alhaddar** [odoo/odoo#71158]
Hello,

I really have an issue it really annoys me because whenever I want to upload any app I should restart Odoo's server on every refresh. 

Please I need help, this make struggles in my work.

Thanks in advance,

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
