### ISSUE TITLE
Blocked customer can create ne sales order by duplicating SO

### ISSUE THREAD

**Issue by jabirmisnedtech** [odoo/odoo#71187]
Impacted versions:
14
Steps to reproduce:
Block one customer from internal notes tab by selecting blocking message under "Warning on the sales order" section (see attached image).

Open existing sales order for that customer and duplicate it.

This will create new quotation, which can be modified and posted without any restriction.

Current behavior:
User can bypass customer restriction by duplicating existing sales order / quotation.

Expected behavior:
User should not have the option to create new sales quotation if the customer is blocked.

Video/Screenshot link (optional):
<img width="1041" alt="blocked customer" src="https://user-images.githubusercontent.com/45730318/119331803-76d64b00-bc90-11eb-86a2-d94affde2d24.png">

Support ticket number submitted via odoo.com/help (optional):
2539454

**Comment by pedrobaeza** [comment]
Yes, this is an old one. The block mechanism is not for catching duplicates, only when interactively creating records. As you have already created an OPW ticket, I let the support team for giving extra explanations, but I'm closing the issue as won't fix due to the feature not available.
