### ISSUE TITLE
odoorpc xmlrpc with config dbfilter ^%d$

### ISSUE THREAD

**Issue by lingjiawen** [odoo/odoo#71186]
Hello, i try to use odoorpc https://pythonhosted.org/OdooRPC/index.html
but i use dbfilter ^%d$ to filter url
how can i config my host and port of my odoorpc?
i use odoo = odoorpc.ODOO('127.0.0.1', port=8069) is not work
but if i change dbfilter to my db name. it works normally

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question, and also about a third party library. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
