### ISSUE TITLE
Can not set response status code in route with type json.

### ISSUE THREAD

**Issue by aemal-netlinks** [odoo/odoo#71180]
I have created a route with type Json.
 ```
@http.route('/test', auth='public', methods=['POST'], type="json", csrf=False)
 def recieve_data(self, **kw):
        headers = request.httprequest.headers
        args = request.httprequest.args
        data = request.jsonrequest
```
So when I receive request using this route everything is fine, but suppose I want to return a different status code like 401, I could not do that with the route which type is json.
I have also tried the bellow method but the problem with this method is that it stops all odoo future requests.
```
from odoo.http import request, Response
 @http.route('/test', auth='public', methods=['POST'], type="json", csrf=False)
 def recieve_data(self, **kw):
        headers = request.httprequest.headers
        args = request.httprequest.args
        data = request.jsonrequest
        Response.status = "401 unauthorized"
        return {'error' : 'You are not allowed to access the resource'}
```
So in the above example If I set the response status code to 401 all other requests even if they are to different routes will be stopped and its status code changes 401 .

**Comment by abdullah-hussaini-netlinks** [comment]
I have same issue, But I don't how to manage it.
If someone know, then share please!

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a development question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Comment by aemal-netlinks** [comment]
@pedrobaeza so could you please answer it in odoo official forums (https://www.odoo.com/forum/help-1/can-not-set-response-status-code-in-route-with-type-json-in-odoo14-187781)?

**Comment by pedrobaeza** [comment]
I can't say about that specific question, sorry. I only manage here that the things go to the proper place for not mixing resources.

**Comment by habibmhamadi** [comment]
Same issue and could not find any solution in the odoo official forums.
