### ISSUE TITLE
Ecommerce shows not published items when your are logged in

### ISSUE THREAD

**Issue by jalzaga** [odoo/odoo#7118]
Normally the system shows only published items when you get to the web page. If you login as admin you can see all the items and you have the possibility to publish them. This behavior must be the same for users that have the permissions to manage ecommerce.
If you register as a new user and you sign in, the system shows in the shop all the items, published and not published. This is the wrong behavior,

It is very important to correct it since there are some cases in which the customer logs in.

**Comment by JKE-be** [comment]
I cannot reproduce ! 
If you can reproduce it on v8, v9 or v10, please open a new ticket and ping me.
