### ISSUE TITLE
Field remaining legal leaves reduce error

### ISSUE THREAD

**Issue by joshuajan** [odoo/odoo#712]
Impacted versions:
 
  - 7.0 and above
 
 Steps to reproduce:
 
  1. set a employee`s remaining legal leaves  10.
  2. set last employee`s remaining legal leaves 5.
 
 Current behavior:
 
  - error
except_osv: ('Integrity Error', 'The operation cannot be completed, probably due to the following:\n- deletion: you may be trying to delete a record while other records still reference it\n- creation/update: a mandatory field is not correctly set\n\n[object with reference: date - date]')
 
 Expected behavior:
 
  - remaining legal leaves 5

I found the problem is if you reduce the *remaining legal leaves* , odoo will create a crm.meeting.

    if record.holiday_type == 'employee' and record.type == 'remove':
        meeting_obj = self.pool.get('crm.meeting')
        meeting_vals = {
            'name': record.name or _('Leave Request'),
            'categ_ids': record.holiday_status_id.categ_id and [(6,0,[record.holiday_status_id.categ_id.id])] or [],
            'duration': record.number_of_days_temp * 8,
            'description': record.notes,
            'user_id': record.user_id.id,
            'date': record.date_from,
            'end_date': record.date_to,
            'date_deadline': record.date_to,
            'state': 'open',            # to block that meeting date in the calendar
        }

 There is not 'date' value when you  reduce the *remaining legal leaves*. Is it possible to use today for this date value?

**Comment by Yenthe666** [comment]
Dear @joshuajan,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
