### ISSUE TITLE
[13.0] Check your code

### ISSUE THREAD

**Issue by yung-wang** [odoo/odoo#71206]
https://github.com/odoo/odoo/blob/13.0/addons/payment_adyen/models/payment.py

Check the code please.

**Comment by pedrobaeza** [comment]
Although I agree, I don't think you should give it such visibility. Just add a PR removing that word and you would the whole service to a more polite code without throwing the stone and hiding the hand.

**Comment by yung-wang** [comment]
I dont know how to create a PR, im not a developer. I tried it before and it is a hassle for me. Sorry to hurt some people.
I could have post it on twitter or linkedin, but i didnt do it. I stayed within the code and did my job as to report it as an issue.
Coders should be aware the code is public, so please stay professional.

**Comment by yung-wang** [comment]
i I removed the offending part. So less visible now.

**Comment by pedrobaeza** [comment]
OK, thanks. @mart-e maybe a quick commit for removing that part?

**Comment by yung-wang** [comment]
Tip, check the rest of the code also. I found some more references.

**Comment by Feyensv** [comment]
It's been there for 5 years, and has been removed in master with a recent refactoring.
Since we won't make that kind of cosmetic change in a stable branch, I'm closing this.

**Comment by yung-wang** [comment]
:+1:
