### ISSUE TITLE
[14.0] POS: issue with order which product is not available in the POS

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#71224]
Impacted versions: 14.0

Steps to reproduce:
- go to runbot
- create a product A available in POS
- sale this product
- close pos session
- set product 1 not available in POS
- open session
- search last order
--> issue line with product A don't show
--> the total price is wrong

It is an issue according to french law if you want reprint a ticket.

Idea : in OrderFetcher.js, after the fetch add in db missing product.

@pimodoo 

![image](https://user-images.githubusercontent.com/16716992/119509165-afe5ec80-bd70-11eb-8818-5660d9e5e6ef.png)

https://user-images.githubusercontent.com/16716992/119509085-98a6ff00-bd70-11eb-9e16-37778b0c382e.mov

**Comment by fmdl** [comment]
OPW #2541592

**Comment by pedrobaeza** [comment]
This has been commented other times: if you disable a product to be fetched by the PoS, you can't access such product, as everything works offline. I don't think this has any solution.

**Comment by fmdl** [comment]
the order management make call rpc, that why it is possible to make an other rpc call to load not available product.

**Comment by pedrobaeza** [comment]
I don't think so without huge changes, but I let Odoo experts to say.

**Comment by Yenthe666** [comment]
Hmm yeah we had similar tickets in the past about this. Let's see what @pimodoo says

**Comment by ryantran-novobi** [comment]
This one also affect return order, on which contains product has been set to unavailable on POS
