### ISSUE TITLE
Support bounce without plus addressing

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#71242]
**Impacted versions**: all (but easily fixable in v13+)

Steps to reproduce:

Try to configure Odoo with an incoming mail provider that doesn't support plus addressing.

**Current behavior**:

You'll be able to do everything, even more after https://github.com/odoo/odoo/pull/69218 was merged, except bounce handling.

The `mail.bounce.alias` parameter only specifies the prefix that Odoo will use, but that prefix is always suffixed with `+128-crm.lead-34` or similar. If your provider doesn't support plus addressing, you're forced to use a catchall address, which increases a lot the amount of undesired mail and produces other bad problems, such as mailboxes being unable to disappear and bounce mail as they should.

**Expected behavior**:

It should be possible to handle bounced emails to the `bounce` address directly, removing the hardcoded requirement of a mail provider that supports plus addressing.

Odoo doesn't really seem to make use of that requirement since v13. I mean, it's used here:

https://github.com/odoo/odoo/blob/cf3bf892c9833cd38a8269c8948d845dd3652403/addons/mail/models/mail_thread.py#L933-L942

But as you can see, that regexp only used to check if the email comes to the bounce address. If, instead, it comes to just `bounce@domain`, the check wouldn't match... but actually the bounce code would work exactly the same because it doesn't really use that regexp to extract any information since https://github.com/odoo/odoo/commit/f4524f03c32a27b1899562a71cad6f491bfe44ce.

Instead, [`_routing_handle_bounce()` relies on the information already found in `message_dict`](https://github.com/odoo/odoo/blob/cf3bf892c9833cd38a8269c8948d845dd3652403/addons/mail/models/mail_thread.py#L688-L739), which is itself [filled in `_message_parse_extract_bounce()`](https://github.com/odoo/odoo/blob/cf3bf892c9833cd38a8269c8948d845dd3652403/addons/mail/models/mail_thread.py#L1315-L1363), which also doesn't use that regexp at all.

So, theoretically, this should make everything keep working as before while removing the requirement of having a plus addressing provider:

```diff
diff --git a/addons/mail/models/mail_mail.py b/addons/mail/models/mail_mail.py
index d846041c9f5..b16c4236f06 100644
--- a/addons/mail/models/mail_mail.py
+++ b/addons/mail/models/mail_mail.py
@@ -303,10 +303,7 @@ class MailMail(models.Model):
                 bounce_alias = ICP.get_param("mail.bounce.alias")
                 catchall_domain = ICP.get_param("mail.catchall.domain")
                 if bounce_alias and catchall_domain:
-                    if mail.mail_message_id.is_thread_message():
-                        headers['Return-Path'] = '%s+%d-%s-%d@%s' % (bounce_alias, mail.id, mail.model, mail.res_id, catchall_domain)
-                    else:
-                        headers['Return-Path'] = '%s+%d@%s' % (bounce_alias, mail.id, catchall_domain)
+                    headers['Return-Path'] = '%s@%s' % (bounce_alias, catchall_domain)
                 if mail.headers:
                     try:
                         headers.update(safe_eval(mail.headers))
diff --git a/addons/mail/models/mail_thread.py b/addons/mail/models/mail_thread.py
index a4e867346d8..e05ba415530 100644
--- a/addons/mail/models/mail_thread.py
+++ b/addons/mail/models/mail_thread.py
@@ -936,19 +936,15 @@ class MailThread(models.AbstractModel):
         rcpt_tos_valid_localparts = [to for to in rcpt_tos_localparts]
 
         # 0. Handle bounce: verify whether this is a bounced email and use it to collect bounce data and update notifications for customers
-        #    Bounce regex: typical form of bounce is bounce_alias+128-crm.lead-34@domain
-        #       group(1) = the mail ID; group(2) = the model (if any); group(3) = the record ID 
+        #    Bounce recipient: as specified in mail.bounce.alias
         #    Bounce message (not alias)
         #       See http://datatracker.ietf.org/doc/rfc3462/?include_text=1
         #        As all MTA does not respect this RFC (googlemail is one of them),
         #       we also need to verify if the message come from "mailer-daemon"
         #    If not a bounce: reset bounce information
-        if bounce_alias and any(email.startswith(bounce_alias) for email in email_to_localparts):
-            bounce_re = re.compile("%s\+(\d+)-?([\w.]+)?-?(\d+)?" % re.escape(bounce_alias), re.UNICODE)
-            bounce_match = bounce_re.search(email_to)
-            if bounce_match:
-                self._routing_handle_bounce(message, message_dict)
-                return []
+        if bounce_alias and any(email == bounce_alias for email in email_to_localparts):
+            self._routing_handle_bounce(message, message_dict)
+            return []
         if message.get_content_type() == 'multipart/report' or email_from_localpart == 'mailer-daemon':
             self._routing_handle_bounce(message, message_dict)
             return []
```

The patch is simplified, but you get the point.

Would you accept such change for v13+?

@Tecnativa TT29827 @tde-banana-odoo

**Comment by tde-banana-odoo** [comment]
Hello,

You are right, this is currently not used anymore in standard codebase. Concerning merge in stable, this is actually a functional change ... people may rely on it for internal purpose. I would accept a PR using "yet another config param" if effectively your provider does not support any "+" indexing. This is quite standard, for information what is your provider ?

For master we could completely remove the regex and the +, to do at forward port probably.

Thanks !

**Comment by intero-chz** [comment]
@tde-banana-odoo pretty standard is an interesting statement. Even Exchange Online (good ol' Microsoft...) was introducing it right before launch of Odoo 13 and it's still not activated by default:

https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/plus-addressing-in-exchange-online
