### ISSUE TITLE
[13.0][14.0][BUG] deleted lines of one2many field included in compute function with constraint

### ISSUE THREAD

**Issue by Mitschmaster** [odoo/odoo#71246]
I have a constraint on two computed fields that take a sum of two one2many fields to be equal. when i edit a saved record and delete entrys and alter the remainig ones so that the constraint is fulfiled it fails because it also adds the amounts of the deleted lines.
i made a small module with just the core functions that lead to the bug to upload it to runbot. maybe someone can give a short advice how to do that?

**Comment by pedrobaeza** [comment]
I'm afraid you can't get such thing, as constraints act at other level.  For further development questions, you should make them on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Comment by Mitschmaster** [comment]
hm. i thought that python constraints are somehow on the same level as a computed field. i also think that this is no development question. i can read through all available documentation and will not find anything that says "constraints and computed fields just dont work". its just that i tried to solve the issue in odoo by myself and failed.

**Comment by Yenthe666** [comment]
Yep and for these kind of questions/issues there's the help forums to help you :)
