### ISSUE TITLE
Context is overridden in ir_action_report_.get_report_from_name

### ISSUE THREAD

**Issue by StephaneMangin** [odoo/odoo#71259]
Impacted versions: 13.0

Steps to reproduce:
- set a custom context
- call _get_report_from_name
- get the resulting context => it's gone

Current behavior: Erase context with the user's one while getting a report from this method

Expected behavior: Only UPDATE the current context with the user's one

Video/Screenshot link (optional): None

Support ticket number submitted via odoo.com/help (optional): None

**Comment by Yenthe666** [comment]
Let's close this issue as you have a PR and they win at Odoo :)
