### ISSUE TITLE
[8.0][master] copy_data() broken with group-protected fields

### ISSUE THREAD

**Issue by a0c** [odoo/odoo#7125]
#### Problem

A user cannot copy a record if the user has no group-rights for at least one field of the record.
#### Explanation

In the previous versions of `def copy_data()` fields to be copied were not explicitly specified, so that all group-protected inaccessible fields were skipped automatically when reading data to be copied (see `def check_field_access_rights()` in `openerp/models.py`).

In the latest versions of `def copy_data()` (both master and 8.0) fields to copy are explicitly specified as a param for `def read()`, but the inaccessible fields are not previously filtered out -- hence error on reading the data to be copied.
#### Fix

To small of a mistake to be Pull Request-ed, so here's a possible patch:

```
diff --git a/openerp/models.py b/openerp/models.py
index 65ab229..75c1d12 100644
--- a/openerp/models.py
+++ b/openerp/models.py
@@ -4715,6 +4715,7 @@ class BaseModel(object):

         fields_to_copy = dict((f,fi) for f, fi in self._fields.iteritems()
                                      if fi.copy
+                                     if not fi.groups or self.user_has_groups(cr, uid, groups=fi.groups, context=context)
                                      if f not in default
                                      if f not in blacklist)
```

**Comment by Yenthe666** [comment]
Hi @a0c,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
