### ISSUE TITLE
Embedding YouTube video in the website editor doesn't fire

### ISSUE THREAD

**Issue by generare** [odoo/odoo#7126]
Firstly to note that the following has been tried with different servers, different Odoo installations, and different templates (and both Safari, and Firefox in mac). When trying to add a video in the website using the editor icon for images (pictograms, and videos), pasting the youtube link in the field and clicking PREVIEW, nothing happens! 
After that if you anyway try to SAVE, nothing happens. Also adding pictograms, or even images fails AFTER this. If you just come and add straight an image or a pictogram, it works, but not anymore after you try to add a video. Video fails anyway in all circumstances.

I would have wanted to know if the VIDEO embedding would be responsive.

**Comment by Fuchur777** [comment]
delete allowfullscreen from the youtube code

**Comment by qsm-odoo** [comment]
Hello,
Sorry we could not handle this bug when it was reported. I cannot reproduce this in supported versions. If you still have a similar issue in 9.0 or higher, please do not hesitate to report it and ping me.
