### ISSUE TITLE
(FAULT) (Master Branch) Multi Company Module Install Issue: Unknown series: '9.0'

### ISSUE THREAD

**Issue by AidenAndrews** [odoo/odoo#7127]
Hey ive just done a fresh install of odoo master branch on 17th June 2015. All seem's to run great a little getting used to updated template engine. When attempting to install the module multi company it redirects me to odoo.com to login with my odoo account. After that it goes back to my instance and flashes up the message Unknown series: '9.0'. 

Log files don't show anything about it at all.

**Comment by Xpiva** [comment]
I am having the same problem. Will there be a resolution for this any time soon?

**Comment by Yenthe666** [comment]
Hey all,

This problem has been fixed in the meanwhile.

Regards,
Yenthe
