### ISSUE TITLE
Check that no move line with account equal to account invoice is used as counterpart

### ISSUE THREAD

**Issue by sergiocorato** [odoo/odoo#71289]
If an account move created from an invoice is modified manually setting as counterpart the same account of the invoice, the invoice will be in a weird state:
- unpaid even if paid,
- the account move line created will appear in the reconcilable items.

https://github.com/odoo/odoo/blob/0913f24151e15de798449e5d1d58132c8a571e05/addons/account/models/account_move.py#L378

Proposed fix #71288

**Comment by pedrobaeza** [comment]
Please don't open an issue if you are going to propose a PR. Include the issue text in the PR.

Closing as there's the PR.
