### ISSUE TITLE
Just Discussion

### ISSUE THREAD

**Issue by myat90thu** [odoo/odoo#71306]
Impacted versions: 12.0 and later versions
https://github.com/odoo/odoo/blob/12.0/addons/stock_account/models/product.py
Questions:
Why odoo do not add 

 product.stock_value = value                        product.qty_at_date = quantity

after line number 281 ?

I think it should added to have value in product.stock_value and product.qty_at_date.
![image](https://user-images.githubusercontent.com/35619526/119773856-43d9c480-bee7-11eb-81ad-ce18bba3c228.png)

**Comment by pedrobaeza** [comment]
Unless you give steps to reproduce a problem, this doesn't serve as a valid issue report.

**Comment by myat90thu** [comment]
I see. Thanks

**Comment by pedrobaeza** [comment]
Closing meanwhile.
