### ISSUE TITLE
Wrong behaviour of XML default_order attribute with boolean fields

### ISSUE THREAD

**Issue by forvas** [odoo/odoo#7137]
When you want to order a specific view by some columns, you use the XML attribute `default_order`. But this is not working well with boolean fields. When you include a boolean field in this attribute, if there are more fields after it, these last ones are ordered the other way round if the records have their boolean set to False.

**Example:**
You have a kanban view ordered by _my_boolean_field_, _my_char_1_, _my_char_2_.
`<kanban default_order="my_boolean_field,my_char_1,my_char_2">`
The records which have _my_boolean_field_ set to True are going to be ordered rightly. But the records which have _my_boolean_field_ set to False are going to be ordered this way:
_my_boolean_field_, _my_char_1 DESC_, _my_char_2 DESC_
Instead of being ordered by _my_boolean_field_, _my_char_1_, _my_char_2_. So in the same view some records are going to be ordered by one way and the other ones by other way.

**Comment by pedrobaeza** [comment]
I think this is not happening in latest versions. If so, please reopen another issue showing some example and screenshots.
