### ISSUE TITLE
[7.0] windows installation documentation needs updating

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#714]
I reported #693 about the windows installer not shipping with the addons, and was told that users were supposed to use apps. 

This is not consistent with the documentation: 

* https://doc.openerp.com/7.0/book/1/1_2_Guided_Tour/1_2_Guided_Tour_install_functionality/ makes no mention of apps
* https://doc.openerp.com/7.0/install/windows/allinone/ says nothing about apps either (and looks quite outdated... It mentions the GTK client... 

Also : https://doc.openerp.com/7.0/install/windows/allinone/ uses phrases describing how to download the installer which are not consistent with the new web site.

**Comment by sle-odoo** [comment]
I suppose we can close this issue. For information, we now ship all the addons so apps is not mandatory.
[Link to the windows installation documentation](https://www.odoo.com/documentation/8.0/setup/install.html#packaged-installers)
Regards
