### ISSUE TITLE
Using Browser "back" on Document-View in Documents-App will block view

### ISSUE THREAD

**Issue by alexander-heyber-manatec** [odoo/odoo#71416]
Impacted versions: 
Odoo 12 Enterprise

Steps to reproduce: 
1.) Go to App documents
2.) Open any PDF in Modal-View (Odoo PDF Viewer)
3). Using the "back" button in Browser (e.g. Google Chrome Version 91.0.4472.77 (Offizieller Build) (64-Bit))

Current behavior:
The PDF Viewer closes but leaves a gray blocking div, you cannot click anything on the view

Expected behavior:
The PDF Viewer should close and previous page should be displayed without the gray blocking div

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
This being something specific of the enterprise interface, should be reported to odoo.com/help with the enterprise contract for being handled there, so closing this one.
