### ISSUE TITLE
Point of sale: product lot always use customer location for SML location source for second and later transaction

### ISSUE THREAD

**Issue by ekaleonardo619** [odoo/odoo#71435]
Impacted versions: 13

Steps to reproduce:
This is a new issue comes from this fixes: https://github.com/odoo/odoo/pull/70194

1. On new fresh db, install POS module and Inventory Module
2. Create a storable product with tracking lot and set Available in Pos: True
3. Now selling the product on POS session, the first transaction the SML location id is correct but afterward is wrong (It stored location id: Partner/Customer) 

Current behavior:
POS stock move line location id: Partner/Customer & Location Dest id: Partner/Customer

Expected behavior:
POS stock move line location id: WH/Stock & Location Dest id: Partner/Customer

Video/Screenshot link (optional):
https://1drv.ms/v/s!AlsbQgHWlESS9Fp46-4QcXyB6msP?e=hLFbmb

**Comment by adwid** [comment]
@ekaleonardo619 You can close the issue (fixed with 276dda7bbb5286dda6a8fac09aabf1faf5d94851)
