### ISSUE TITLE
Stock Valuation:.Odoo Balance Sheet Report

### ISSUE THREAD

**Issue by iman-alhaddar** [odoo/odoo#71457]
May someone explain me what is the relation between the three accounts please 

* Stock Valuation

* Stock Interim (Received)

* Stock Interim (Delivered)

I knew that I should make this equation to know that my report is correct please I need from someone two say is it correct or no 

"Stock Interim (Received)"  -  "Stock Interim (Delivered)" = "Stock Valuation"

But I am finding a bug difference as an example please you can see a database from runbot.odoo.com here is the database that I checked.

https://7977453-master-all.runbot29.odoo.com/web?debug=1#action=1005&cids=1&menu_id=574

* user:. admin

* password:. admin

Waiting a reply,

Thanks in advance,

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
