### ISSUE TITLE
[14.0] Incorrect purchase price calculation in purchase uom other than base uom

### ISSUE THREAD

**Issue by desdelinux** [odoo/odoo#71456]
Impacted versions: 14

Steps to reproduce:

- Create a product with average cost and real-time valuation

- The product must be storable

- The product must have as unit of measure (units)

- The product must have as a unit of purchase measure (dozens)

- The product must have a set cost (which corresponds to the cost of the unit)

- The product must not have a cost associated with any supplier

- Create a purchase order, the purchase price suggested by the system is Unit price * unit of measure * unit of measure, that is, unit price * 12 * 12

You can check the case in the following rumbot

Product: https://7963973-14-0-all.runbot46.odoo.com/web#action=1112&cids=1&id=137&menu_id=791&model=product.template&view_type=form

Purchase Order: https://7963973-14-0-all.runbot46.odoo.com/web#id=25&action=960&model=purchase.order&view_type=form&cids=1&menu_id=680

Current behavior:

Odoo is multiplying the unit price 2 times by the purchase unit of measure

Expected behavior:

The cost that must be taken the first time you buy from a supplier must be the standard cost (in the base unit) for the purchase unit of measure (this is how it worked in previous versions)

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/50924836/120075708-02245780-c068-11eb-8a7a-52615c71fed1.png)

![image](https://user-images.githubusercontent.com/50924836/120075725-110b0a00-c068-11eb-9f29-c9fc2b261aaf.png)

Support ticket number submitted via odoo.com/help (optional): #2549342

**Comment by nhomar** [comment]
I confirm this is an issue ( a huge one )

- The product's form view says COST PER UNIT (used in all odoo for standard accounting cost).
- The purchase unit of measure is the one by default in the purchase order.
- The multiplication of Standard x Purchase unit of measure does not make sense (the first multiplication) in all cases.

I do not get the point of such change, it does not make sense to me and it is clearly a bug.

A customer sent an issue with our licence and Odoo answer it is Ok!

**Comment by crece365** [comment]
The problem is apparently occurring from this commit.

https://github.com/odoo/odoo/commit/d531e8a5e4d84fe6daa9110d076b0fc601a0b4d9

They are calculating the price_unit that was already calculated
