### ISSUE TITLE
Onchange method , dominio returned a domain, this is deprecated

### ISSUE THREAD

**Issue by winaytel** [odoo/odoo#71460]
Impacted versions: Odoo 14.0

 @api.onchange('name')
    def _dominio(self):

        domain=[]

        if self.name:
           domain.append(('id','=',self.name.id))

        _logger.info("Esto es del Dominio")
        return {'domain':{'requisito':domain}}

    requisito = fields.Many2many('visionqhse.registrorequisito',string='Requiisitos')

I got a issue : odoo odoo.models: onchange method GestionNorma._dominio returned a domain, this is deprecated

**Comment by pedrobaeza** [comment]
Yes, this is something expected. You are still able to use it, but the recommended method now is to have a computed field with the allowed values, and use such field in the domain restriction.

Closing as expected behavior.
