### ISSUE TITLE
[13.0][14.0] hr_holidays : Accrual allocation by tag does not include new employees assigned to the tag

### ISSUE THREAD

**Issue by yassinelachgar** [odoo/odoo#71476]
__Impacted versions:__
13.0, 14.0 (Only tested on the following versions)
__Steps to reproduce:__
- create an employee E1 with tag EMP
- create an accrual allocation by the tag EMP (number of day = 2)
- execute the `Accrual Time Off: Updates the number of time off` cron
- 2 days are allocated to the employee E1 
- create an employee E2 with the tag EMP
- execute the `Accrual Time Off: Updates the number of time off` cron again
- 2 days are allocated to E1 but E2 is not included in the accrual allocation (since he was created after the creation of the allocation).   

__Current behavior:__
Employee E2 is not included in the accrual allocation if he is created after the creation of the allocation.
__Expected behavior:__
Logically any employee that belongs to a certain tag should be included in the allocation and should therefor be allocated the number of days.
This always bothered me with native `hr_holidays` and we find ourselves forced to use extra addons on top of the native ones. Is this a desired behavior (if so anyone care to explain why ?)
Feel free to close if this is not considered as a valid issue!
__Video/Screenshot link (optional):__

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
If you want to include new members in the accrual, you have to create again or restart the existing one.

Closing as no bug, but expected behavior.

**Comment by yassinelachgar** [comment]
Thanks @pedrobaeza , how can I restart the existing one ?

**Comment by pedrobaeza** [comment]
Refuse it and reset to draft.
