### ISSUE TITLE
event date_begin reset to today date when put inside email

### ISSUE THREAD

**Issue by maherkhalil07** [odoo/odoo#71576]
Impacted versions:14

Steps to reproduce: In event module, I print the data_begin using button then it gives me the correct date but when putting the same field in the email template it give me today date

Current behavior:In event module, I print the data_begin using button then it gives me the correct date but when putting the same field in the email template it give me today date

Expected behavior: the date field should give the same date when printing from python code or in email template

Video/Screenshot link (optional): attached
![1](https://user-images.githubusercontent.com/38738435/120366115-8d734680-c30f-11eb-8807-def4d8c0b0d6.png)
![print using button](https://user-images.githubusercontent.com/38738435/120366130-92d09100-c30f-11eb-81ef-32795bc32403.png)
![same date when doing email preview](https://user-images.githubusercontent.com/38738435/120366140-9532eb00-c30f-11eb-85e4-2e0eb55135e1.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a development question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
