### ISSUE TITLE
Deploy Odoo Entreprise On Kubernetes 

### ISSUE THREAD

**Issue by mrad-bilel** [odoo/odoo#71609]
Impacted versions:  odoo v14 .
This is a question and not an issue.

I'm planning to migrate from SAAS to on-prem deployment on kubernetes cluster . 
My goal is to migrate my SAAS licence to on-prem , it is possible to deploy odoo entrepise edition on kubernetes ? 

Does odoo has a docker image for entrepise edition ? 

Thanks

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Little tip: I only know about https://github.com/odoo/docker

Closing this by the reason above.
