### ISSUE TITLE
[8.0] Cannot add button on BoM structure view

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#7162]
Hello,

I make some development and want to add a button on BoM structure view,
but I got this error:
It will have an error:
Uncaught Error: QWeb2 - template['TreeView']: Runtime Error: TypeError: Cannot read property 'tree_invisible' of undefined

I think the problem is, the bug happen when we add the button on tree view that has parent_id.

The expected behavior:
It should be the same like the list view or normal tree view without any error.

Thank You.

**Comment by Yenthe666** [comment]
Hi @falinwa ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
As this is a question about development and not about a bug in Odoo itself you're better off asking this on the official help forums (at odoo.com/help) as Github is only for bugs in the official code.

Regards,
Yenthe
