### ISSUE TITLE
Incorrect reservation of stock when using "Track outgoing lots" only

### ISSUE THREAD

**Issue by jon-willowit** [odoo/odoo#7163]
V8.0: System reserves non-existent stock when stock is tracking outgoing lots only.
Steps to reproduce (I did this on the runbot 19th June 2015):
1) Create a new stock item, set product type: "stockable" & track-outgoing-lots" true
2) Set Quantity on hand to (say) 5
3) Create a sales order for 5 of these items and confirm and view the delivery order
4) Check availability and 5 items will be reserved. Now transfer the 5 items being sure to allocate a lot number (in my test I allocated 5 serial lot numbers). This is a view of the quants at this point:
![bug1](https://cloud.githubusercontent.com/assets/891154/8249122/45784ab4-16aa-11e5-8056-c9d85b27d2c3.png)
Note at this point there is theoretically no stock on hand and 5 have been delivered to the customer
5) Create another sales order for 2 of the same item, confirm and view the delivery order
6) Now click on "Check-availability" - note that 2 ITEMS ARE RESERVED:
![bug2](https://cloud.githubusercontent.com/assets/891154/8249163/bb82844a-16aa-11e5-8b0b-ac8836c8a95b.png)
THIS IS WRONG. The system is selecting from quants that theoretically have been consumed. Note also that the system believes there is zero on hand and -2 virtual stock:
![bug3](https://cloud.githubusercontent.com/assets/891154/8249190/0cfdfafc-16ab-11e5-8989-81c89744e737.png)
After this the system continues to get itself into an awful mess

**Comment by nim-odoo** [comment]
Although this can be surprising, this is the intended behavior in v8.0. This will therefore not be considered as a bug. However, I made a patch which will prevent to reserve more quantity than available if it is really an issue for you (see #7209)
Note that this won't be the case anymore in v9.0.

**Comment by jon-willowit** [comment]
For stock that is lot-tracked on output I cannot see how this could possibly be the correct behaviour because it is inevitable you will have quants without a lot before assigning one on delivery. I think the correct fix is to split the quant with a blank lot (if there is one at the source location) into another quant with a lot number and move this new split quant. This has to be a BUG. 

However, thank you for your patch and it would be a good idea to put the option to stop stock going negative as a configuration item.

**Comment by StefanRijnhart** [comment]
Thanks for the patch! I would be interested to know why this is the intended behaviour.
