### ISSUE TITLE
change month date name of  language website  in odoo

### ISSUE THREAD

**Issue by lyprono** [odoo/odoo#71642]
Impacted versions: odoo14

Steps to reproduce: 

Current behavior: 
I'm working with odoo, and I changed the interface language to danish from setting--> translation--> load translation , I have a problem where the month names of (January-February-March,etc ) are translated to (januar,februar), but I need to change them in the system to (Januar Týsdagur,Januar). I tried to change the files in do.js library in web module but there is no change, and I searched for the .po files that contain these months and edited them all with also no hope, and my last try was to change the language terms of the months, but am still not getting what I need, so could you please tell me how I can change the date months names to the required names in odooserver in either configs or code?

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a development question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
