### ISSUE TITLE
Unable to install module "social_push_notifications" because an external dependency is not met: Python library not installed: google_auth

### ISSUE THREAD

**Issue by arvind28990** [odoo/odoo#71643]
Impacted versions:14

Steps to reproduce: to install social_push_notification

Current behavior: not allowing to install module

Expected behavior: module should get installed

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
The error is specified: you need such Python library. Closing as this is a deployment issue, not code one and the module is an enterprise one.
