### ISSUE TITLE
Survey or email marketing is not in the selection after installing it

### ISSUE THREAD

**Issue by povi2946** [odoo/odoo#71783]
Impacted versions: odoo 14

Steps to reproduce:
Install survey or email marketing modules.. and try to access. they are not there

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
You probably don't have the permissions given in your user.

Anyways, this is working on runbot, so I'm closing this for now unless further evidences of some kind of bug is shown.
