### ISSUE TITLE
document.file uses ir.attachment security rules instead of document.directory ones.

### ISSUE THREAD

**Issue by jeremydolson** [odoo/odoo#7180]
document.file uses the check() access function from ir.attachment and so documents in directories cannot be made public (i.e. accessible from public QWeb views). There may be other inconsistencies as well, as it seems document.file will use the more restrictive ir.attachment check function in every case.

I've applied the following patch which seems to make document.file behave as expected for both internal and external cases (i.e. gives access when it should, forbids it when it shouldn't):

```
index 5ba296f..b3750a7 100644
--- a/addons/document/document.py
+++ b/addons/document/document.py
@@ -73,14 +73,17 @@ class document_file(osv.osv):
         if not isinstance(ids, list):
             ids = [ids]

-        super(document_file, self).check(cr, uid, ids, mode, context=context, values=values)
-        
         if ids:
             self.pool.get('ir.model.access').check(cr, uid, 'document.directory', mode)

             # use SQL to avoid recursive loop on read
             cr.execute('SELECT DISTINCT parent_id from ir_attachment WHERE id in %s AND parent_id is not NULL', (tupl
-            self.pool.get('document.directory').check_access_rule(cr, uid, [parent_id for (parent_id,) in cr.fetchall
+            parent_id = [parent_id for (parent_id,) in cr.fetchall()]
+            self.pool.get('document.directory').check_access_rule(cr, uid, parent_id, mode, context=context)
+
+            if not parent_id:
+                super(document_file, self).check(cr, uid, ids, mode, context=context, values=values)
+

     def search(self, cr, uid, args, offset=0, limit=None, order=None, context=None, count=False):
         # Grab ids, bypassing 'count'
```

This makes it possible to access documents from the QWeb website (if and only if they are made public) by using:
"/web/binary/saveas?model=ir.attachment&field=datas&filename_field=name&id=%s", id

Does anyone see a problem with this approach?

**Comment by pedrobaeza** [comment]
Closing as this module is no longer present in recent versions of Odoo.
