### ISSUE TITLE
Old color system of Odoo 13.0 alert.

### ISSUE THREAD

**Issue by rowemoore** [odoo/odoo#71838]
Impacted versions:  
v14

Steps to reproduce: 
Upgrade from 13 - 14 with website installed

Current behavior: 
When using Website Builder, the following alert message is displayed at top of options panel:
**"It appears your website is still using the old color system of
            Odoo 13.0 in some places. We made sure it is still working but
            we recommend you to try to use the new color system, which is
            still customizable."**
Expected behavior:
I would like there to be an explanation or documentation explaining what this means and how to resolve it. re-installing the website module and removing custom modules that have any scss or css files does not remove the alert.
Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
This is something you should check with the upgrade team, not here.
