### ISSUE TITLE
[13.0, 14.0] website: missing dependencies "website.customizeMenu", "website.newMenu"

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#71842]
Impacted versions: 13.0, 14.0 

Steps to reproduce:
1. Go to the latest runbot 13.0 or 14.0 and make sure that you have the console opened.

Current behavior: The JavaScript from Odoo fails if you're not logged in:
```
Missing dependencies:     
Array [ "website.customizeMenu", "website.newMenu" ]
```
![image](https://user-images.githubusercontent.com/6352350/121133689-f1779c80-c832-11eb-9b54-51c90a9d8caf.png)

This comes back from:
https://github.com/odoo/odoo/blob/b46544aecc0f13b724b92d13412cc437243dc1ee/addons/website/static/src/js/set_view_track.js#L4
Which goes back to:
https://github.com/odoo/odoo/blob/b46544aecc0f13b724b92d13412cc437243dc1ee/addons/website/static/src/js/menu/customize.js#L11

Expected behavior: There's no missing dependencies issues causing parts of the JS to crash.

**Comment by Yenthe666** [comment]
OPW `2563100`

**Comment by JKE-be** [comment]
Issue in v13 :/ PR in v14...

@holdenrehg 

Can you move if from asset as discuss on pr, and target v13 if really bugged in v13 ? 

ps: don't forget to set your PR in draft before retarget.

ty

**Comment by holdenrehg** [comment]
@JKE-be absolutely :+1:

**Comment by rdeodoo** [comment]
https://github.com/odoo/odoo/commit/2247aec27c96488e6e9665e6bc2ff4a544b0f7eb

**Comment by Yenthe666** [comment]
yeah we forgot to manually close, sorry! :)

**Comment by rdeodoo** [comment]
Don't worry, your punishment will be to offer me a :beer: at the next on site Odoo experience.

**Comment by Yenthe666** [comment]
2025 anyone? 😄 But noted, I'll get you one then! 😉
