### ISSUE TITLE
[13.0, 14.0] website: Some cookies are misusing the recommended “SameSite“ attribute 

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#71843]
Impacted versions: 13.0 & 14.0 at least.

Steps to reproduce: 1. Open the developer console from Firefox and go to runbot.odoo..com

Current behavior:
Look in the console and you will see:
```
Some cookies are misusing the recommended “SameSite“ attribute 16

Cookie “frontend_lang” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite 8141075-13-0-all.runbot38.odoo.com
Cookie “visitor_uuid” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite 8141075-13-0-all.runbot38.odoo.com
Cookie “session_id” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite 8141075-13-0-all.runbot38.odoo.com
Cookie “session_id” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite 2 web.assets_common.css
Cookie “session_id” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite 2 web.assets_common_minimal_js.js
Cookie “session_id” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite 2 web.assets_frontend.css
Cookie “session_id” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite 2 web.assets_frontend_minimal_js.js
Cookie “session_id” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite 2 favicon
Cookie “session_id” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite 2 web.assets_common_lazy.js
Cookie “session_id” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite 2 web.assets_frontend_lazy.js
Cookie “im_livechat_history” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite web.assets_common_lazy.js:3988:607
Cookie “session_id” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite 2 en_US
Cookie “session_id” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite 2 05071fb879321bf01f941f60fab1f126f565cdad
Cookie “session_id” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite 2 update_visitor_timezone
Cookie “session_id” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite 2 init
Cookie “session_id” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite
```
![image](https://user-images.githubusercontent.com/6352350/121134479-b9bd2480-c833-11eb-890a-a9e57ad7ae8a.png)

Expected behavior: There should be no misuse and it should be used correctly.
See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite

**Comment by Yenthe666** [comment]
OPW `2563101`

**Comment by odony** [comment]
This is a misleading warning by Firefox, and an invalid interpretation of the [SameSite spec](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite), which was designed to be backwards-compatible.
-> When the SameSite attribute is not present, the spec clearly states that it should be interpreted as `SameSite=Lax`, which is the *correct default* for Odoo. Please report a bug to firefox if you care about this warning.

We should not modify stable releases to fix an error warning in a developer console, especially as the SameSite attributes are not supported in all werzeug versions that we need to support, and that will lead to useless and risky changes, for no good reason.

There are valid cases where the new SameSite spec requires adaptations to Odoo, but this is not one of them.

**Comment by odony** [comment]
To elaborate a bit, browsers have a complicated rollout schedule for the SameSite specifications, and the behavior and warnings you will get will vary greatly depending on your specific version browser. They also roll out in waves to some percentages of their users, so even with the same browser version you could get different behaviors.

Chrome and Firefox also got their warnings wrong in several occurrences, making the situation even more confusing for developers.

The only way to get predictable results is to have a look at the browser documentation and force the behavior using browser-specific flags.

For more info, please see:
- Firefox: https://hacks.mozilla.org/2020/08/changes-to-samesite-cookie-behavior/
- Chrome: https://www.chromium.org/updates/same-site
- Generic info: https://web.dev/samesite-cookies-explained/

You can test your current browser settings easily on https://samesite-sandbox.glitch.me/

----
#### Current browser flags

For Firefox, in about:config:
- network.cookie.sameSite.laxByDefault -> true
- network.cookie.sameSite.noneRequiresSecure

For Chrome, in chrome://flags:
- version 91+: no flags anymore, new behavior comes by default
- version 80: new behavior by default for 100% users, but flags still available
- version 76+:
  - #same-site-by-default-cookies 
  - #cookies-without-same-site-must-be-secure

**Comment by Yenthe666** [comment]
Hmm, very interesting read, I was not aware of this. Thanks a lot for the explanation and sources Olivier.
As always your answer is a true gem :)

**Comment by odony** [comment]
For the record, PR #72267 implements a fix for one case where the SameSite spec causes a real problem, because a third-party payment acquirer website is sending a POST request directly to Odoo. The fix was *not* to decrease the security of our session cookie by setting `SameSite=None; secure`, which would have global consequences. Instead, we simply make sure we do not assign a new session for that single session-less POST request, setting `save_session=False` on the route.

This comment explains the principles in more details: https://github.com/odoo/odoo/pull/72267#issuecomment-865188203
