### ISSUE TITLE
Addons Versions not used after pull requests merged

### ISSUE THREAD

**Issue by FrancXPT** [odoo/odoo#71893]
After some changes are added or stuff changes addons should get a version bump instead of using the same version for months when the app core functions changed completely , to avoid confusion and avoid breaking stuff when someone make a custom addons.

**Comment by pedrobaeza** [comment]
I don't know if you are talking in general, or for Odoo core addons, but Odoo doesn't change functionality on a stable version, only bugfixes, and they never change the version number.

Closing as no issue.
