### ISSUE TITLE
[14.0] Can't translate cookie bar dialog buttons

### ISSUE THREAD

**Issue by SplashS** [odoo/odoo#71902]
Impacted versions: 14.0

Steps to reproduce:
1. Install module website.
2. Go to Settings -> Website.
3. Activate `Cookie Bar` checkbox.
4. You will see `Do not activate` and `Activate anyway` buttons.
5. Export website.pot

Current behavior:
There are no `Do not activate` or `Activate anyway` text strings in pot.

Expected behavior:
There are `Do not activate` and `Activate anyway` text strings in pot.

Seems that _t() wrapper missed for these strings in addons/website/static/src/js/backend/res_config_settings.js

**Comment by Yenthe666** [comment]
Fixed in https://github.com/odoo/odoo/commit/cf9b82be04d5e7cd809e4d0a42007bd5db132087 :)
