### ISSUE TITLE
Problem in inserting product using python script! please help

### ISSUE THREAD

**Issue by Wesamazmy** [odoo/odoo#7191]
I am trying to import my products from csv file using python script, the problem is the product is not appear in the product template but its ONLY appear in product variant, so I am not sure if this is correct or not?!

this is my code

import csv
import psycopg2
conn_string = "dbname= 'jamalonerp' user='odoo' password='admin123'"
conn = psycopg2.connect(conn_string)
cursor = conn.cursor()
reader = csv.reader(open('prod.csv','rb'))
for row in reader:
    print row[1]
    statement = "INSERT INTO product_template (name,x_publisher,x_author,list_price,description_purchase,purchase_ok,sale_ok,mes_type,uom_id,uom_po_id,type,categ_id) VALUES ('"+row[1]+"','"+row[2]+"','"+row[3]+"',"+str(row[5])+",'"+row[14]+"', true, true, 'fixed',1,1, 'product',4) RETURNING id"
    cursor.execute(statement)
    conn.commit()
    templateid=cursor.fetchone()[0]
    statement = "INSERT INTO product_product (product_tmpl_id,default_code,x_publisher,x_author,active) VALUES (" + str(templateid) + ",'"+row[0]+"','"+row[2]+"','"+row[3]+"',True)"
    cursor.execute(statement)
    conn.commit()

**Comment by dadiaek** [comment]
i must see the csv file to define where is the mistake

**Comment by Yenthe666** [comment]
Hi @Wesamazmy,

Thanks for your report and sorry for the late reply.
The Github tracker is in fact not for questions about custom development or custom code. It is only used for bugs in the official code. In the future you can ask this on the official help forums at help.odoo.com.

Regards,
Yenthe
