### ISSUE TITLE
Behind a proxy

### ISSUE THREAD

**Issue by sotogarcia** [odoo/odoo#7195]
When I try to connect to an Odoo instance behind an nginex acting as inverse proxy, the Odoo request object has wrong values in all URL parameters.

```python
from openerp.http import request

print request.httprequest.base_url
> http://http://odoo8-im_test/web/dataset/call_button
print request.httprequest.host_url
> http://http://odoo8-im_test/
print request.httprequest.url
> http://http://odoo8-im_test/web/dataset/call_button
print request.httprequest.url_root
> http://http://odoo8-im_test/
```

### The proxy settings

```bash
server {
    # server port and name
    listen 31088;
    #server_name 37.187.124.202;
    server_name intranet.domain.com;


    location / {
        # proxy_pass http://127.0.0.1:30089;
        proxy_pass http://odoo8test;
    }

    location /longpolling {
        # proxy_pass http://127.0.0.1:32089;
        proxy_pass http://odoo8-im_test;
    }

    location /crm_ticket_platforms/submit-coupon {
        # proxy_pass http://127.0.0.1:30089;
        proxy_pass http://odoo8test;
    }

    # cache some static data in memory for 60mins.
    # under heavy load this should relieve stress on the Odoo web interface a bi
t.
    location /web/static/ {
        proxy_cache_valid 200 60m;
        proxy_buffering on;
        expires 864000;
        proxy_pass http://odoo8test;
    }
}
```

**Comment by xmo-odoo** [comment]
That question belongs on the forum rather than the bug tracker.

Make sure you've started Odoo in proxy mode (start the server with `--proxy-mode`, it simply enables [werkzeug's proxying support](http://werkzeug.pocoo.org/docs/0.9/contrib/fixers/#werkzeug.contrib.fixers.ProxyFix)) and [have configured NGINX to pass all the right headers](http://nginx.com/resources/admin-guide/reverse-proxy/) (see werkzeug doc for the relevant headers)

**Comment by SalahAdDin** [comment]
@sotogarcia Did you solve this issue? i have it with `base_locations_import_from_geonames` module.

**Comment by v-garcies** [comment]
Hi ! I have same issue today with a odoo website and I solve it with this rule in my Nginx vhost :
    
    proxy_set_header Accept-Encoding "";

(replace all ``proxy_set_header`` rules with the rule above)

https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/#headers
