### ISSUE TITLE
[14.0] New fields in product will not saved values when using "compute" and "inverse" methods

### ISSUE THREAD

**Issue by giordano-ch** [odoo/odoo#71961]
Impacted versions: 
14.0

Steps to reproduce:

- Add a new field in product.template and in product.product. 
- Add the basic compute and inverse Methods to the field in product.template
- Create a new product in product.template and add a value to your new field
- After Save that value will not be stored. 
- The basic barcode field example is working right.

Current behavior:
Inverse fields in product.template will not be saved.

Expected behavior:
When creating a new product. The new field values should be saved like in the basic field "barcode" example in the product module.

Video/Screenshot link (optional):
**product.template code:**

```
class ProductTemplate(models.Model):
    _inherit = 'product.template'
    test_field = fields.Char(string="test field base", compute="_compute_test_field", inverse="_set_test_field")

    @api.depends('product_variant_ids.test_field ')
    def _compute_test_field(self):
        self.test_field = False
        for template in self:
            if len(template.product_variant_ids) == 1:
                template.test_field = template.product_variant_ids.test_field 

    def _set_test_field(self):
        if len(self.product_variant_ids) == 1:
            self.product_variant_ids.test_field = self.test_field 
```

**product.product code:**

```
class ProductProduct(models.Model):
    _inherit = 'product.product'
    test_field = fields.Char(string="test field variant")
```

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a development question. If it works on Odoo core, and yours is not working, then something different should be. You should make the question on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
