### ISSUE TITLE
login problem

### ISSUE THREAD

**Issue by spinningcat** [odoo/odoo#71974]
Impacted versions: odoo 14

Steps to reproduce:  doo-bin -r spinningcat -w 123

Current behavior:
When i open localhost:8069 it directs me to database creation page. I already created my database it is there. But i couldnt go app page.

Expected behavior: I expect to go page that exhibits all app after db creation.
![Screenshot from 2021-06-10 12-31-06](https://user-images.githubusercontent.com/20774204/121522593-f2a8f500-c9fd-11eb-9fbc-7e9ee5a28fb9.png)
![Screenshot from 2021-06-10 10-42-56](https://user-images.githubusercontent.com/20774204/121522599-f3da2200-c9fd-11eb-926d-80f45c98c27a.png)
![Screenshot from 2021-06-10 10-42-48](https://user-images.githubusercontent.com/20774204/121522602-f472b880-c9fd-11eb-84ac-69a9bcf9a3e1.png)

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/14.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).

**Comment by spinningcat** [comment]
I followed every steps there. What i did is to get source code from github. Problem still exist. I installed all dependencies as you see i can create database but i cannot go app page.

**Comment by pedrobaeza** [comment]
I'm afraid that's out of the scope of this issue tracker.

**Comment by spinningcat** [comment]
It may be about OS or something else thanks anyway.
