### ISSUE TITLE
AssertionError "{} is a required field ({})" raised with a required boolean having a default value

### ISSUE THREAD

**Issue by mgrenson** [odoo/odoo#71972]
**Impacted versions:** 

12, 13, 14, master

**Steps to reproduce:**

1. add a required boolean field on an existing model : 

```
class ProductSupplierInfo(models.Model):
    _inherit = 'product.supplierinfo'

    custom_field = fields.Boolean(required=True, default=False)
```
2. use some test code that will create a record through odoo.test.Form : 

for ex. from module stock_dropshipping
https://github.com/odoo/odoo/blob/master/addons/stock_dropshipping/tests/test_crossdock.py#L33

**Current behavior:**

an exception is raised (this one comes from a 14.0) : 

```
FAIL: TestCrossdock.test_00_crossdock
Traceback (most recent call last):
  File "/home/odoo/src/odoo/addons/stock_dropshipping/tests/test_crossdock.py", line 33, in test_00_crossdock
    seller.name = supplier_crossdock
  File "/home/odoo/src/odoo/odoo/tests/common.py", line 1865, in __exit__
    self.save()
  File "/home/odoo/src/odoo/odoo/tests/common.py", line 2181, in save
    values = self._values_to_save()
  File "/home/odoo/src/odoo/odoo/tests/common.py", line 2212, in _values_to_save
    assert self._values[f] is not False, "{} is a required field".format(f)
AssertionError: custom_field is a required field
```

**Expected behavior:**

Since custom_field is a boolean which is explicitly set to False by a default value, an exception should not be raised.
When something similar is executed by Odoo client the key is passed to the create so the required constraint is OK even if the value is False.

**Video/Screenshot link (optional):**

/

**Support ticket number submitted via odoo.com/help (optional):**

/

**Comment by pedrobaeza** [comment]
Boolean by definition can't be required, as there are 2 values: True or False, not three: undefined, True or False, so that's not possible.

Closing as limitation of the framework.
