### ISSUE TITLE
odoo 14.0 error installation when 'pip install -r requirements.txt'

### ISSUE THREAD

**Issue by softone-as** [odoo/odoo#72030]
Impacted versions:
python 3.9.5
pip 21.1.2

Steps to reproduce:
- i was trying to add unicode utf-8, but idk where should i add it
- upgrading pip from 21.1.1 to 21.1.2

Current behavior:
 ERROR: Command errored out with exit status 1:
     command: 'c:\users\user\appdata\local\programs\python\python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\USER\\AppData\\Local\\Temp\\pip-install-l1twjpi2\\python-stdnum_7fedeb4a665a428296115b9609bb1e56\\setup.py'"'"'; __file__='"'"'C:\\Users\\USER\\AppData\\Local\\Temp\\pip-install-l1twjpi2\\python-stdnum_7fedeb4a665a428296115b9609bb1e56\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\USER\AppData\Local\Temp\pip-pip-egg-info-0zsh4wg5'
         cwd: C:\Users\USER\AppData\Local\Temp\pip-install-l1twjpi2\python-stdnum_7fedeb4a665a428296115b9609bb1e56\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\USER\AppData\Local\Temp\pip-install-l1twjpi2\python-stdnum_7fedeb4a665a428296115b9609bb1e56\setup.py", line 38, in <module>
        long_description = fp.read()
      File "c:\users\user\appdata\local\programs\python\python39\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 967: character maps to <undefined>
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/89/ad/9388970542f82857ac2958b3eaddfad16caaf967cf8532e9486dedc69420/python-stdnum-1.8.tar.gz#sha256=3f42639cae75c0f6ba734eaa7391d411b7fdef868873503f7d2b2962fc3d71bd (from https://pypi.org/simple/python-stdnum/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement python-stdnum==1.8 (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.8.1, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.8.1, 1.9, 1.10, 1.11, 1.12, 1.13, 1.14, 1.15, 1.16)
ERROR: No matching distribution found for python-stdnum==1.8

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
This is something outside Odoo. Your combination of OS/distribution/Python, etc is not compatible, and you should find a good one. 

Closing as no Odoo issue, but deployment one.

**Comment by Yenthe666** [comment]
Also, Odoo 14 does not support Python `3.9.5`. Ref https://github.com/odoo/odoo/issues/71352 and https://github.com/odoo/odoo/pull/71437#issuecomment-853860659
