### ISSUE TITLE
Add more details to the official README of this repo

### ISSUE THREAD

**Issue by IbrahimOlayinka** [odoo/odoo#72097]
Describe the bug
Readme Dosent Describe The Project Very Well Making it hard to know the total purpose of the project at a glance
Update project readme file

To Reproduce

Go to '...'
Click on '....'
Scroll down to '....'
See error

Expected behavior

Screenshots

Environment
For web, specify your OS and browser version. For mobile, specify device, OS
and version. For libraries, what version of build tools are you using?

Additional context

**Comment by pedrobaeza** [comment]
Sorry, but the issue you have put has no sense. If you want to improve something, do a PR.
