### ISSUE TITLE
CRM Leads "Mark Won" and "Mark Lost" buttons available on closed leads

### ISSUE THREAD

**Issue by dreispt** [odoo/odoo#721]
Go to a Lead and click on either "Mark Won" or "Mark Lost":
The lead will correctly change to an closed state, but the buttons will incorrectly still be visible.

**Comment by alca259** [comment]
Hello, i see that buttons don't go to have anymore visibility in function of field state, because crm_lead don't have at this time this field.

**Comment by dreispt** [comment]
Am I the only one bothered by this?
It's a usability problem in my POV.

**Comment by Yenthe666** [comment]
Dear @dreispt ,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
This issue has been fixed in newer Odoo versions though.

Regards,
Yenthe
