### ISSUE TITLE
do not auto close ui autocomplete when scroll

### ISSUE THREAD

**Issue by ptquang97** [odoo/odoo#72100]
**Impacted versions:**
all version

**Steps to reproduce:**
- in xml file, using widget="many2many_tags"
- a dropdown cannot using max-height + overflow-y because ui-autocomplete auto close on scroll event
**Current behavior:**
- cannot view all record of tag when has many data
**Expected behavior:**
- can use scroll in ui-autocomplete 
**Video/Screenshot link (optional):**
- current logic code: I think this code using to fix error scroll window make dropdown scroll too
https://imgur.com/a/l6PFhSG
- suggest a solution: check scroll except scroll in ui-autocomplete
https://imgur.com/a/zFRy5b2

**Comment by pedrobaeza** [comment]
Please include a video about what you are talking about, or if you think you have the solution, just do the PR.

**Comment by ptquang97** [comment]
Hi pedrobaeza, 
This is video demo. I cannot scroll in jquery autocomplete
https://www.youtube.com/watch?v=XcqHa2uPXSM

**Comment by pedrobaeza** [comment]
I'm not able to replicate the problem in runbot. I never get the max-height:


https://user-images.githubusercontent.com/7165771/121909165-f86c4680-cd2d-11eb-942b-e91bb3d381b9.mp4

**Comment by ptquang97** [comment]
In my video, i add css **max-height** and **overflow-y** for it, not is a default.
I want to create a custom jquery ui autocomple with many data, so i add css max-height for it. But it duplicate with autocomple of default tags in odoo. So i cannot scroll it.

**Comment by pedrobaeza** [comment]
Ah, sorry, but that's something not supported. This issue tracker is for things in Odoo core, not for modifications you want to do. You have to deal with the problems derived from your modifications.

Closing as no Odoo core issue.
