### ISSUE TITLE
[v8.0 ] Calendar view bug, urgent help needed.

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#7215]
Added Calendar view.

    <record id="sb_job_order_calendar" model="ir.ui.view">
        <field name="name">Job Order</field>
        <field name="model">sb.job.order</field>
        <field name="arch" type="xml">
            <calendar string="Job Orders" color="name" date_start="booking_date" date_stop="booking_date" display="[name]">
                <field name="name"/>
                <field name="sale_order_id"/>
                <field name="customer_id"/>
                 
            </calendar>
         </field>
    </record>

On load getting issue.

Uncaught Error: Syntax error, unrecognized expression: div.oe_calendar_responsible input[value=/]
http://private-servers.com/web/static/lib/jquery/jquery.js:4680

Kindly give me hints to solve., I will code and fix it.

Thanks

**Comment by Yenthe666** [comment]
Hi @tejastank,

This is custom development and doesn't fall under reported issues for Odoo.
If you still face this issue please create a topic on the official Odoo help forums (help.odoo.com) and I'm sure somebody can help you there.

Regards,
Yenthe
