### ISSUE TITLE
Price lists cannot be applied to events

### ISSUE THREAD

**Issue by jalzaga** [odoo/odoo#7218]
At present Price lists can only be applied to products/services. Since the price of the events is in the ticket type, you cannot fix discounts for this kind of items.

**Comment by drummingbird** [comment]
+1 on this issue, as it would be really great to be able to discount event tickets for promotions. Does anyone know how to go about fixing this issue? I looked into the code but I wasn't sure how to fix it.

**Comment by jalzaga** [comment]
Tested today:
If you define your price list based on the product assigned to the ticket you can apply discounts in sales orders and also in the web. You can use product categories, products or product templates to establish different discounts.

If you want to apply different discounts for different ticket types you need to assign different products. 

@drummingbird

**Comment by drummingbird** [comment]
Thanks for the really quick response about this. That sounds great, but it's exactly what I thought I'd tried to do already. I can get it to update the line for a web order, but it doesn't seem to change the order total. I've been working with v8, though. What version did you test it on?

**Comment by pedrobaeza** [comment]
Triaging this with the answers given.
