### ISSUE TITLE
[14.0] Profiling not working in the Controllers

### ISSUE THREAD

**Issue by Gokulakannanaj** [odoo/odoo#72207]
Impacted versions:
14.0

Steps to reproduce:
Add @profile to the controller to test the response time.

Sample Code:
@profile
@http.route('/api/v1/test/account/read/<int:_id>', type='json', methods=['POST'], auth='user')
def read(self, _id, **params):
        result = request.env['res.partner'].browse(_id).read(params.get('fields'))
        return result

Current behavior:
It does not return the statistics.

Expected behavior:
It should return the statistics and the actual response should like below 
```
2018-03-28 06:18:23,196 22878 INFO openerp odoo.tools.profiler:
calls     queries   ms
project.task ------------------------ /home/odoo/src/odoo/addons/project/models/project.py, 638

1         0         0.02          @profile
                                  @api.model
                                  def create(self, vals):
                                      # context: no_log, because subtype already handle this
1         0         0.01              context = dict(self.env.context, mail_create_nolog=True)

                                      # for default stage
1         0         0.01              if vals.get('project_id') and not context.get('default_project_id'):
                                          context['default_project_id'] = vals.get('project_id')
                                      # user_id change: update date_assign
1         0         0.01              if vals.get('user_id'):
                                          vals['date_assign'] = fields.Datetime.now()
                                      # Stage change: Update date_end if folded stage
1         0         0.0               if vals.get('stage_id'):
                                          vals.update(self.update_date_end(vals['stage_id']))
1         108       631.8             task = super(Task, self.with_context(context)).create(vals)
1         0         0.01              return task

Total:
1         108       631.85

```
Video/Screenshot link (optional):
Current Response:
![Profiling](https://user-images.githubusercontent.com/41570711/122166335-16a18600-ce97-11eb-9a7a-4cd5ff69e72c.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by Yenthe666** [comment]
This is not a bug but by design :) It is coded to prevent Odoo from profiling controllers.
See https://github.com/odoo/odoo/blob/7a7aacedde81998ec0f1a7f3283337236e56de42/odoo/tools/profiler.py#L21-L75

You could override it/comment it to support it though.

**Comment by Gokulakannanaj** [comment]
@Yenthe666 - One suggestion, It's better to add a how-to enable the profiling for controllers in oocademy.

**Comment by Yenthe666** [comment]
It actually works out of the box for anything non-controller by just importing and adding it (which I have a tutorial for) 🤔

**Comment by Gokulakannanaj** [comment]
Yeah. Obviously and the link is https://www.oocademy.com/v14.0/tutorial/profiling-code-in-odoo-73. Based on that only I raised this issue. Thanks
