### ISSUE TITLE
[14.0] account: issue during import move

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#72302]
Impacted versions: 14.0

Steps to reproduce: (on runbot : https://8351066-14-0-all.runbot53.odoo.com/web#id=81&action=447&model=account.move&view_type=form&cids=1&menu_id=579)
**Issue 1**
When you try to import a file like this:
![image](https://user-images.githubusercontent.com/16716992/122420080-ae809c00-cf8b-11eb-8451-f661ba7855b5.png)

Lines are not imported:
![image](https://user-images.githubusercontent.com/16716992/122420245-d243e200-cf8b-11eb-9b49-e7c8a975c2e4.png)

You should import a second time the same file to import the lines.
![image](https://user-images.githubusercontent.com/16716992/122420352-ec7dc000-cf8b-11eb-8e34-6904668ed377.png)

**Issue 2**
Partner in line are not imported
![image](https://user-images.githubusercontent.com/16716992/122420514-09b28e80-cf8c-11eb-9b70-bf22bbe117e9.png)
![image](https://user-images.githubusercontent.com/16716992/122420566-12a36000-cf8c-11eb-9041-ac6eb9c898fd.png)

@oco-odoo @mart-e 

Support ticket number submitted via odoo.com/help (optional):

**Comment by fmdl** [comment]
OPW #2574654

**Comment by pedrobaeza** [comment]
That's because on the header there's no partner_id.

**Comment by fmdl** [comment]
If you put a partner in the header, the header partner override partner in line.

**Comment by pedrobaeza** [comment]
Yes, of course, because you are importing in `invoice_line_ids`. If it's other type of move, don't use such one2many, but `line_ids`.
