### ISSUE TITLE
Link images on Mailings from Email Marketing

### ISSUE THREAD

**Issue by marcchausse** [odoo/odoo#72307]
Impacted versions: V14

Steps to reproduce:
From the Email Marketing Module
Create a new mailing
Select any theme with image
Change an image not avaialble from the list by uploading it
I use to get jpg files
Send a test via Email
Current behavior:
From a Gmail Account the changed picture do not show up. 
All other element are fine
From Outlook, we can see the picture but header and foot pages are messed up .
The button to redirect to another website has a black rectangular form in it for some reason.
If I try to modify the Mailing form the Email Marting Module, I cannot reselect the same image from the image browsing.
I must re-upload it even if it is available from the ir_attachments.

I wasn't able to provide the result from Runbot, the Test from the Mailing never sent the Email.

Expected behavior:
Being able to send custom Pictures from Mailings
Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/57365364/122420586-cb9c7700-cf59-11eb-8f68-dd1c296ec931.png)
![image](https://user-images.githubusercontent.com/57365364/122421245-3e0d5700-cf5a-11eb-9ba2-3e12d1d47987.png)
![image](https://user-images.githubusercontent.com/57365364/122421342-4d8ca000-cf5a-11eb-8409-6ecdc17c5b9b.png)
![image](https://user-images.githubusercontent.com/57365364/122426857-96465800-cf5e-11eb-8163-9460a1b3b79d.png)
![image](https://user-images.githubusercontent.com/57365364/122427444-1d93cb80-cf5f-11eb-95e5-03804339de6a.png)
![image](https://user-images.githubusercontent.com/57365364/122428288-c93d1b80-cf5f-11eb-96ed-484c5b969baf.png)
![Uploading image.png…]()

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
This is something from your end, as the images are not accessible when reading the mail. Take into account that they are links, not embedded.

Closing as no issue.

**Comment by marcchausse** [comment]
Hello Pedro,
Thank you for your advice.
