### ISSUE TITLE
add confirmation for button send (send message tab) 

### ISSUE THREAD

**Issue by vpar-solvve** [odoo/odoo#72334]
Impacted versions: 14

Steps to reproduce: go to order. scroll to the bottom order. write text on Send message block and click by Send button

Current behavior: message sent for all folovers 

Expected behavior: add come confirmation. Becouse message from this block sent real message

Video/Screenshot link (optional):https://prnt.sc/15shmq2

Support ticket number submitted via odoo.com/help (optional):

i try add some confirmation for button Send. I didn't found any resoled question how i can extend chatter_topbar
https://github.com/odoo/odoo/tree/14.0/addons/mail/static/src/components/chatter_topbar
i hope will get any idea how do it

**Comment by Yenthe666** [comment]
Hi,

It is built this way on purpose and has been how the core of Odoo has been working for pretty much 10 years.
This won't be changed.

**Comment by vpar-solvve** [comment]
i'm sure. but how i can extend it functionality?
i can't inherit templates like xml:space="preserve"
https://github.com/odoo/odoo/blob/14.0/addons/mail/static/src/components/chatter_topbar/chatter_topbar.xml

**Comment by Yenthe666** [comment]
Ask it on the help forums at help.odoo.com please :)
