### ISSUE TITLE
routes web services 

### ISSUE THREAD

**Issue by metalsoft10** [odoo/odoo#72388]
Hello 
how to link controller path to dynamic subdomain 
for ex 

`
class Control (http.Controller):
@http.route('/res/<string:id>, auth='public')

             def index(self, id,**kw):

                    return http.request.render('module.res',{'res':id})
`

this will work if i go to http://mydomain.com/res/stringid

how to make it work like that  http://stringid.mydomain.com

apache wildcard is enabled 

ServerName : mydomain.com
ServerAlias *.mydomain.com

on flask it can done like that 
`
@app.route("/", subdomain="static")
def static_index():
    """Flask supports static subdomains
    This is available at static.your-domain.tld"""
    return "static.your-domain.tld"

@app.route("/dynamic", subdomain="<username>")
def username_index(username):
    """Dynamic subdomains are also supported
    Try going to user1.your-domain.tld/dynamic"""
    return username + ".your-domain.tld"

`

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

AFAIK, I don't think it can be done without something external.

**Comment by metalsoft10** [comment]
https://www.odoo.com/forum/help-1/subdomain-in-odoo-server-189113

17 June 2021 and no answer i search all tutorial and video's and ask many odoo partner has no answer or solution

**Comment by metalsoft10** [comment]
@pedrobaeza  if you can guide me will help me and many ask for same point

**Comment by pedrobaeza** [comment]
I can only think in a external redirection service.

**Comment by metalsoft10** [comment]
when try the manual link for ex "http://stringid.mydomain.com" 
not work so  external redirection not work

**Comment by metalsoft10** [comment]
the right question may be how to configure odoo web services routes  
and do this by code

**Comment by metalsoft10** [comment]
an other example if i want open the shop url "http://mydomain.com/shop" like this "http://shop.mydomain.com"
