### ISSUE TITLE
psycopg2.errors.TooManyColumns: tables can have at most 1600 columns

### ISSUE THREAD

**Issue by yasr3mr96** [odoo/odoo#72492]
psycopg2.errors.TooManyColumns: tables can have at most 1600 columns

414 Request-URI Too Large

**Comment by yasr3mr96** [comment]
psycopg2.errors.TooManyColumns: tables can have at most 1600 columns

**Comment by pedrobaeza** [comment]
Yes, that's a limitation of Postgres, not Odoo. It's not correct that you add such number of columns.

Closing as no Odoo issue.
