### ISSUE TITLE
How to active BOM product variants?

### ISSUE THREAD

**Issue by caRtxAS** [odoo/odoo#72501]
Hi,

I'm using Odoo 14.0-20210530 (community edition), Chinese (traditional) zh_TW.

I cannot find in "Manufacturing - Configuration - Manufacturing Order" where to activate product variants function. Please let me know where to active it, thank you.

Impacted versions: Odoo 14.0-20210530 (community edition), Chinese (traditional) zh_TW

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):
![TIM截图20210622161133](https://user-images.githubusercontent.com/43395021/122889401-5a076300-d375-11eb-80c3-7cf45bd9f93c.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
