### ISSUE TITLE
 I cant display one2many field in kanban view in Odoo14

### ISSUE THREAD

**Issue by winaytel** [odoo/odoo#72585]
Impacted versions:14

Description : Hi everyone . Currently I  am trying to display one2many field in kanban view , but this appears empty . My code is the following . Thanks for your support.  

<kanban>
    <field name="one2manyFieldname"/>
    <templates>
        <t t-name="kanban-box">
            <div class="oe_kanban_content">
                <p>
                   <t t-foreach="record.one2manyFieldname.raw_value" t-as='o'>
                       <t t-esc="o.name"/><br/>
                   </t>
                </p>
            </div>
        </t>
    </templates>
</kanban>

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above. Anyways, a quick tip: one2many is not supported in kanban.
