### ISSUE TITLE
Alternative for get_history_price() in Odoo13

### ISSUE THREAD

**Issue by mohmdlabeeb** [odoo/odoo#72609]
I know that there is no product price history table in Odoo13, but is there any alternative function like get_history_price? It was so easy to get the product history at a certain in Odoo12.

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
