### ISSUE TITLE
[master] Can this progress bar make it's place in version 15's import screen?

### ISSUE THREAD

**Issue by QaidjoharBarbhaya** [odoo/odoo#72627]
Impacted versions:
master

Steps to reproduce:

Current behavior:

Expected behavior:
As shown in this repo:
https://github.com/gmarczynski/odoo-web-progress

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
I'm afraid this is not how it goes. Community modules are not usually integrated in core, and in any case, it should be the original author who should propose it. Anyways, you can have the feature through a module, as this is how modular system works 

Closing as no issue.
