### ISSUE TITLE
[8.0][website_sale]Bug: Product sequence has no effect

### ISSUE THREAD

**Issue by treviser** [odoo/odoo#7263]
Odoo Version: 20150612 nightly

Modules installed: https://restaurant-roessli.twanda.ch/en_US/website/info

Observed behaviour:
Despite setting sequences for all products, the sequence in the webshop remains always the same, it is the descending sequence according to the products publishing time, the last published product is on top.
The same behaviour (and sequence) is observed in the english and in the german version of the web shop.

Expected behaviour:
Display the products in the product categories according to the sequence defined by the user.

**Comment by treviser** [comment]
Unpublishing all products and republish the products in an other sequence does not change the original sequence either, so it seems to be the original publishing date/time which is preserved.

**Comment by mart-e** [comment]
Hello,

You are referring to the field website_sequence on the product, right ?
Sorry but it looks to works fine on standard e-commerce. The products should be sorted by the highest sequence first (published products first), not the publishing date (if you are using the standard `/shop`page).

Can you reproduce it on [runbot](http://runbot.odoo.com/runbot/b/8.0) ?

**Comment by treviser** [comment]
Hi

Yes, I do refer to the standard /shop page. And I checked it now and see 
it works  based on your information, because I had originally defined my 
sequence numbers in ascending order, but I have to confess, never in my 
life I could have had the idea that the highest sequence number would be 
published on top in a descending order. This seems rather unusual to me, 
the natural behaviour when explicitly and manually defining sequences is 
to assume an ascending order. At least for me. What is, when you do not 
know the maximum number of items a priori? On the other hand, I do 
agree, if you do NOT define a sequence manually, then a descending order 
based on the order of publishing (or whatever is reasonable in the 
context) makes very much sense.

But ok, now I know and can handle it, thank you very much. But my 
suggestion for an improvement is to handle manual sequence numbers 
defined by the user in an ascending order, because anything else seems 
(at least to me) not to be naturally understandable and not easy to 
handle (you have to be prepared a priori for a maximum number of items, 
which obviously can change over time and then you have to redefine the 
whole sequence, if you have no "space" left). And you can run out of 
space very fast, when it gets narrow between a last number x and 0.

Thank you very much, trevi

On 26.06.2015 17:50, Martin Trigaux wrote:
>
> Hello,
>
> You are referring to the field website_sequence on the product, right ?
> Sorry but it looks to works fine on standard e-commerce. The products 
> should be sorted by the highest sequence first (published products 
> first), not the publishing date (if you are using the standard 
> |/shop|page).
>
> Can you reproduce it on runbot <http://runbot.odoo.com/runbot/b/8.0> ?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/odoo/odoo/issues/7263#issuecomment-115737766>.
>

-- 
twanda AG
Ermin Trevisan
Artherstrasse 19
CH-6318 Walchwil
T    +41 41 758 1515
M    +41 79 208 7373
E    trevi@twanda.com
www.twanda.ch
www.ipadweinkarte.twanda.ch

**Comment by mart-e** [comment]
I agree with you, this is counter intuitive. This is the opposite of the way sequence is usually used.

We can not change that in stable as it would invert the order of existing ecommerce but I have changed that in master at 43c544f8a8897a73888de71f140fe4359359580e

**Comment by treviser** [comment]
That's fine with me, thank you very much.

On 26.06.2015 22:37, Martin Trigaux wrote:
>
> I agree with you, this is counter intuitive. This is the opposite of 
> the way sequence is usually used.
>
> We can not change that in stable as it would invert the order of 
> existing ecommerce but I have changed that in master at 43c544f 
> <https://github.com/odoo/odoo/commit/43c544f8a8897a73888de71f140fe4359359580e>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/odoo/odoo/issues/7263#issuecomment-115874018>.
>

-- 
twanda AG
Ermin Trevisan
Artherstrasse 19
CH-6318 Walchwil
T    +41 41 758 1515
M    +41 79 208 7373
E    trevi@twanda.com
www.twanda.ch
www.ipadweinkarte.twanda.ch

**Comment by treviser** [comment]
@mart-e The sequence seems to be disappeared in 9.0 or am I struck with blindness?

**Comment by mart-e** [comment]
It seemed that @dbo-odoo disagreed with the commit at 8bc59fe58fc49cee59fe12b8bdd9daf155e88c81

It is a bit old but it may be because it needed to be reflected in methods like `set_sequence_bottom` and `set_sequence_top` which is not the case.
So this patch was incomplete which explains why it was reverted

**Comment by dbo-odoo** [comment]
Hello @treviser 

Indeed, in edit mode the "promote" menu (allowing you to change the sequence from the frontend view) assumes a descending sequence for products. Changing the sequence order should be done everywhere at once or not at all, otherwise clicking on Promote > Push to Top would have the complete opposite effect.

**Comment by treviser** [comment]
Thanks for your replies, @dbo-odoo and @mart-e 
@dbo-odoo which "promote" menu are you talking about? The one on the website is for SEO purposes only and I can't find another in 9.0c. But whatever the order, it seems to have disappeared from the Product/Sales tab in the backend and not to be available at all anymore. Which is probably better than offering an unuseable one. But there are verticals which need to control the sequence of the products in their webshops, such as restaurants for example.

**Comment by dbo-odoo** [comment]
This menu:
![20170110-151051_capture](https://cloud.githubusercontent.com/assets/9530767/21809240/1ca878fc-d747-11e6-93db-738ffdcb382a.gif)

I think it's there for this single purpose (since v8 I think) :smile:

**Comment by treviser** [comment]
Oh Jesus...
Thanks for the hint, I did completely forget about that one. Ok, that one is relevant for the kanban view only. Therefore we do not have a feature anymore to define the sequence of products generally, independent of the view.
