### ISSUE TITLE
Customer Invoice Report is not calculating Refunds correctly

### ISSUE THREAD

**Issue by CarltonGuc** [odoo/odoo#7266]
Viewing a customer record in Form view will show that the "Invoiced" amount is correct, however when you click on the "Invoiced" button to list out the invoices for that customer, the total on the bottom of the page is not correct if the customer has any Refunds.   Refunds are being calculated as Invoices and are being added to the Grand Total.    Refunds should be viewed in a different color, or show the balance as Negative.    The Grand Total should be the same value as on the Customer screen.

**Comment by alexisjaja** [comment]
i confirm this strange behavior, that is verry problematic. Someone has an idea?

**Comment by pedrobaeza** [comment]
This is solved AFAIK. If not, please comment or open a new issue, adding screenshots or similar to illustrate the problem.
