### ISSUE TITLE
[14.0] pos: how to inherit OrderFetcher.js

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#72662]
Impacted versions: 14.0

Hi @rhe-odoo how I can inherit OrderFetcher.js because the file return this :

```js
odoo.define('point_of_sale.OrderFetcher', function (require) {
    'use strict';

    class OrderFetcher extends EventBus {
        ....
     }
    return new OrderFetcher();
});
```

Thanks

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
