### ISSUE TITLE
Unmet dependencies error when adding dependencies to module in 'to upgrade' state

### ISSUE THREAD

**Issue by sbidoul** [odoo/odoo#72703]
Impacted versions: 14.0 (probably older versions too)

Steps to reproduce:

- Create a custom addon `a`
- Create a database and install `a`
- Set the state of module `a` to `to upgrade`

This is the typical situation when you received a database from the Odoo migration service (i.e. custom addons marked as `to upgrade`).

Now create a new custom addon `b` and update `a`'s manifest to make it depend on `b`.

Current behavior:

1. Both `odoo -u base` (1a) and `odoo -u a` (1b) give an error:

```
INFO odoo odoo.modules.graph: module a: Unmet dependencies: b
ERROR odoo odoo.modules.loading: Some modules are not loaded, some dependencies or manifest may be missing: ['a']
```

2. Now set `a` 's state to `installed`

  - 2a. `odoo -u base` gives the same error
  - 2b. `odoo -u a` works and Odoo correctly installs `b` before upgrading `a`.

Expected behavior:

In all scenarios, the module should upgrade correctly and `b` should be installed.

https://github.com/odoo/odoo/pull/72661 fixes scenario 1b, and helps a lot.
1a and 2a remain problematic but are less critical. 

In this trivial scenario, the workaround is easy enough, but when you have a complex dependency graph of custom modules, it is much harder to diagnose and work around.

Support ticket number submitted via odoo.com/help (optional):

**Comment by rco-odoo** [comment]
Fixed by https://github.com/odoo/odoo/pull/72661

**Comment by sbidoul** [comment]
Half fixed to be precise.

**Comment by shazzwazz20** [comment]
1)This errors comes from "depends" in __menifest__.py file
2) Check if modulename in depends section is renamed or removed from current version or not
3) After renaming the module in depends as per current version or removing should resolve this issue
