### ISSUE TITLE
[14.0] point_of_sale : impossible to close POS when cash_register_difference is zero

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#72720]
Impacted versions: 14.0

Issue from https://github.com/odoo/odoo/pull/72457

Steps to reproduce:
Open POS with cash control
Add product and pay in cash
Click on end of session
Set closing at, put the same value of expected in cash
Clisk Close session and post entrie
--> Isssue you see message because the difference is not zero.

Video/Screenshot link (optional):

https://user-images.githubusercontent.com/16716992/123275753-e4ca9800-d504-11eb-8bfc-94371c0e7d06.mov

@pimodoo @rhe-odoo @guva-odoo

**Comment by fmdl** [comment]
OPW #2581588

**Comment by guva-odoo** [comment]
Fixed on PR 72725 : https://github.com/odoo/odoo/pull/72725
