### ISSUE TITLE
MASTER - can not sort departments by name

### ISSUE THREAD

**Issue by ferdiga** [odoo/odoo#7272]
![dep_by_name](https://cloud.githubusercontent.com/assets/6248560/8335363/767d07ac-1a9d-11e5-99e9-eb00c806d99e.png)

**Comment by Anhlq87** [comment]
you can use _order = "name" put it in hr.department object to sort again data display on treeview.

**Comment by ferdiga** [comment]
thank you, 
it should work by clicking on the column header

**Comment by Yenthe666** [comment]
Closing as this was answered 😉
