### ISSUE TITLE
website editor is disabled (screenshot of problem inside)

### ISSUE THREAD

**Issue by paula-em-lafon** [odoo/odoo#7275]
Sorry, there is no stacktrace for this issue.
The website editor on odoo is not permiting any changes, a screenshot of the current status of the website editor is  attached.
The account from which the website is being edited is the administrator account.

![websiteissue](https://cloud.githubusercontent.com/assets/3951245/8343962/6da51c8c-1a98-11e5-93a0-2e61fbf16246.jpg)

**Comment by a0c** [comment]
You must've introduced a bug somewhere in the web client -- a bug which prevents the page from loading fully.

Press F12 in your browser, go to Console tab and try reloading the page -- then investigate the errors that show up there (there must be some).

P.S.
Also, use the [Help Forum](https://www.odoo.com/forum/help-1) for such issues. Github issues are for Odoo own bugs, I suppose. And you are more likely to find similar problems in the Help Forum, already with a solution inside.

**Comment by qsm-odoo** [comment]
Hello,
I hope you were able to solve the issue. As I see that the bug appeared in 8.0 which is now unsupported, I am closing the issue. If you still have a similar issue in 9.0 or higher, do not hesitate to report it and ping me.
