### ISSUE TITLE
[account] incongruence in validation account_assert_test

### ISSUE THREAD

**Issue by JulioSerna** [odoo/odoo#7276]
I think there is an incongruence between [1][Validation Journal Entry](https://github.com/odoo/odoo/blob/a9e3d74713b6882c64617345696ad326d75a4745/addons/account/account.py#L1563) and [2][validation account_assert_balanced](https://github.com/odoo/odoo/blob/a9e3d74713b6882c64617345696ad326d75a4745/addons/account/account.py#L1170),

Because if I try to post one journal entry with difference of ```0.00001``` by validation[1] allow me, but if I update module account, by the validation[2] I get error in the same journal entry,

IMHO validation [1] and [2] should allow the same difference of decimal

Impacted Version:
* 8.0

Steps to reproduce:

* To set decimal precision = 4
* Create Journal Entry with debit = 1.2345 and another line with credit = 1.2344
* To post Journal Entry
* To update account module

Current Behavior:
* Journal Entry is posted
* After update account module show the error by difference

Expected Behavior:
* If Journal Entry was posted, after update account module not show error

**Comment by hbto** [comment]
+1

**Comment by nim-odoo** [comment]
Well, a rounding error in this case:
```
ipdb> amount
-9.999999999998899e-05
```
But still, you are right, both should be consistent
