### ISSUE TITLE
Original user gets copies of notifications to Duplicate user

### ISSUE THREAD

**Issue by ruifranco** [odoo/odoo#72773]
**Impacted versions:**

13

**Steps to reproduce:**

Duplicate a user, change his data to meet your needs and send him notifications.

**Current behavior:**

ORIGINAL user gets a copy of notifications to DUPLICATE, despite not sharing any data.

**Expected behavior:**

ORIGINAL user should not get any copy of notifications to DUPLICATE

**Video/Screenshot link (optional):**

**Support ticket number submitted via odoo.com/help (optional):**

**Comment by pedrobaeza** [comment]
Can you specify which notifications?

Can you reproduce the problem in runbot? Note that outgoing emails can be seen clicking on the Mailhog inside the gear dropdown

**Comment by ruifranco** [comment]
APP notifications.

Both users have "Handle in Odoo" set.
ORIGINAL uses the mobile app.

**Comment by pedrobaeza** [comment]
Using the mobile app, you should notify it to odoo.com/help enterprise service instead of here.
