### ISSUE TITLE
[14.0] float_round  compute bug

### ISSUE THREAD

**Issue by sum1201** [odoo/odoo#72826]
Impacted versions:
14.0
Steps to reproduce:

value = 364658.60000000003

float_round(value, 2) should be 364658.60, but value still be 364658.60000000003

Current behavior:

Expected behavior:

https://github.com/odoo/odoo/blob/f7f7b0b644f64ff7a207d434d3b7797780d44191/odoo/tools/float_utils.py#L99

Since then the code has resulted in a decimal point

float_round(value, 2) compute value should be 364658.60

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/5398273/123569673-5ce0d880-d7f9-11eb-88d8-d266ed7de862.png)

![image](https://user-images.githubusercontent.com/5398273/123569305-a977e400-d7f8-11eb-81d7-01dc36abd1e2.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by sum1201** [comment]
@pedrobaeza  please

**Comment by sum1201** [comment]
@pedrobaeza Don't you think this is a bug?

**Comment by pedrobaeza** [comment]
I don't have any opinion on this thing. Anyways, for being considered, you should present steps to reproduce the problem in Odoo itself, applying such method and not obtaining the expected result, as IDE traces don't serve.

**Comment by sum1201** [comment]
You are too arbitrary in this way.  And this kind of situation happens randomly and just happens to be encountered.  But it does not mean that it has no problems.  And the python documentation also indicates the existence of this problem.  https://docs.python.org/3.6/library/decimal.html

**Comment by pedrobaeza** [comment]
There is no use of `decimal` type here in Odoo, and this method is provided for workarounding that. I haven't found any random problem derived from this, except if you don't use it on certain parts, or you pretend to store the exact number that can't be represented with IEEE representation, as that's simply impossible.

**Comment by voronind** [comment]
> I don't have any opinion on this thing. Anyways, for being considered, you should present steps to reproduce the problem in Odoo itself, applying such method and not obtaining the expected result, as IDE traces don't serve.

It's very easy to reproduce. I have same problem with other number. This bug influences on related field computing. For example, we have `StockMove.weight` field with `related='product_id.weight'`. We get incorrect value on reading `stock_move.weight`.

```python
from odoo.tools.float_utils import float_round

float_round(364658.6, precision_digits=2)
> 364658.60000000003

float_round(25.057, precision_digits=3)
> 25.057000000000002
```

**Comment by voronind** [comment]
> There is no use of `decimal` type here in Odoo, and this method is provided for workarounding that. I haven't found any random problem derived from this, except if you don't use it on certain parts, or you pretend to store the exact number that can't be represented with IEEE representation, as that's simply impossible.

I found problem. There is not everywhere using of float functions + crappy `float_round` function = problem. For example  
https://github.com/odoo/odoo/blob/e2e51c15d082ec17743b73ad1422e4a223268be9/addons/stock/models/stock_move.py#L1629  
`StockMove._recompute_state` computes incorrect stock move state.

**Comment by pedrobaeza** [comment]
Let's close this one as duplicated and continue the talk in #7024
