### ISSUE TITLE
[WEB][8.0] Datetime picker in editable tree view

### ISSUE THREAD

**Issue by angelmoya** [odoo/odoo#7282]
Datetime picker in editable tree view doesn't work.

Datetime picker have tree areas ( calendar, hours and minutes).

On datetime picker In editable tree view only work first click, for example if you choose a day you can't chose hours or minutes, also you can't chose other day.

**Comment by amoya-dx** [comment]
You can try this in task form, on "Work summary"

**Comment by Yenthe666** [comment]
Hi @angelmoya,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
