### ISSUE TITLE
[8.0] invoice can't be paid with 0,000100 currency rounding factor and account decimal accuracy 4 or more

### ISSUE THREAD

**Issue by intero-chz** [odoo/odoo#7283]
**Changing rounding factors and decimal accuracy in account won't work with invoices**

Impacted versions:
- 8.0

Steps to reproduce:
1. change account decimal accuracy to 4 or more
2. change default/company currency rounding factor to 0,000100 or 'more'
3. create an invoice with proper values and default/company currency (like in screen1)
4. validate invoice
5. register payment (full payment, like in screen 2)

Current behavior:
- invoice is not paid

Expected behavior:
- invoice is paid

![screen1](https://cloud.githubusercontent.com/assets/8614174/8349558/35917ec2-1b1e-11e5-903a-6511b0aea411.png)

As you can see in the next screen, the balance is calculated wrong and will be used in the voucher. But changing the value in the voucher to the expected one, will not change the later payment values...

![screen2](https://cloud.githubusercontent.com/assets/8614174/8349562/373691b8-1b1e-11e5-8b5c-c4a3615a0142.png)

I've digged into this problem. The account.move.line values amount_residual and amount_residual_currency are calculated correctly and put into the cache. But getting them from cache is cutting them to 2 decimal places. As far as i can see, there is no digits or digits_compute parameter for these fields definitions and that cuts them off to 2 decimal places.

Maybe someone can lighten things up for this situation?

**Comment by acsiqual** [comment]
:+1: I encountered the exact same issue on v8.0.0

**Comment by Yenthe666** [comment]
Hi @intero-chz,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
