### ISSUE TITLE
Models' hooks

### ISSUE THREAD

**Issue by emilkholod** [odoo/odoo#72967]
Impacted versions: 14.0

Steps to reproduce:
Let we have some model with some hooks on "write" method, so if we call write method on this model then there will be called: 

1. `write_hook_3`
1. `write_hook_2`
1. `write_hook_1`
1. `write` (from class)

This hooks were applied by `_patch_method`.
So let we want to delete `write_hook_2` for this model's method by `_revert_method`. 

Current behavior:
We will lose `write_hook_3` for this model's method,  so the hierarchy will be the next:
1. `write_hook_1`
1. `write` (from class)

Expected behavior:
We want to save `write_hook_3` for this model's method, so the hierarchy will be the next:
1. `write_hook_3`
1. `write_hook_1`
1. `write` (from class)

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a development question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
