### ISSUE TITLE
[13.0] date related javascript tests fail if your local timezone is behind UTC

### ISSUE THREAD

**Issue by johnw-bluemark** [odoo/odoo#72962]
## Impacted versions:
Tested on 13.0, will happen on 11.0, 12.0, and 14.0 as well.

## Steps to reproduce:
1. Set your computer timezone to any timezone that is behind UTC (example: Pacific Standard Time)
2. Install odoo with minimal modules (base, web)
3. Using Chrome or Firefox, navigate to /web/tests?mod=web&moduleId=9c1da935

## Current behavior:
Tests fail

## Expected behavior:
Tests pass

## Details

![image](https://user-images.githubusercontent.com/52720301/123867698-85450180-d8e3-11eb-8f81-93bf3e877bdf.png)

The "Parse server date on 31" test uses a terrible override of the `window.Date` function that discards all but the first argument. When `str_to_date`  is called, it tries to do this: 
```Javascript
var tmp = new Date(2000,0,1);
```
but it effectively does this:
```Javascript
var tmp = new Date(2000);
```
This creates a Date object that is equivalent to 2 seconds after January 1st, 1970 in UTC. However, if your timezone is behind UTC, the date will be December 31st, 1969. When attempting to update this date object with the parsed date, it updates the year, then the month, then the day, all in local time. When it updates the month, it ends up setting the Date object to November 31st, 2013, which gets autocorrected to December 1st, 2013. As a result, the date ends up being 1 month off from the expected value.

![image](https://user-images.githubusercontent.com/52720301/123867753-9beb5880-d8e3-11eb-9530-fab5f6466ac5.png)

The "Format server date" test fails because the test sets the Date object in UTC, and `date_to_str` reads it back in local time.

**Comment by pedrobaeza** [comment]
Test suite requires some data to be fixed: timezone and language basically, so although desirable, you have to stick to that data for getting correct results, and for now there's no plans to make this variable according user timezone.

Closing as won't fix due to expected restricted behavior.
