### ISSUE TITLE
[14.0] website: header is disappear when quickly scrolling to the top.

### ISSUE THREAD

**Issue by kig-odoo** [odoo/odoo#72972]
On the website, the header disappears when quickly scrolling to the top.
https://www.awesomescreenshot.com/video/4313731?key=945fc97e6bcb570e5fef640fa434c729

Tested on runbot.

**Comment by pedrobaeza** [comment]
It seems that happens when clicking directly on the scroll bar free part for provoking a "hard" scroll.

@JKE-be can you please check this?

**Comment by rdeodoo** [comment]
Duplicate of https://github.com/odoo/odoo/issues/71449

> It seems that happens when clicking directly on the scroll bar free part for provoking a "hard" scroll.

Not especially, you can reproduce it by any scrolling method, eg just 2 finger scroll on touchpad
