### ISSUE TITLE
8.0 Account General Ledger report fails when wizard was created more times than the amount of accounts in system

### ISSUE THREAD

**Issue by bwrsandman** [odoo/odoo#7298]
### Description

Code in the Account General Ledger report tries to check the company of an `account.account` but is using the id of the `account.report.general.ledger` instead. This leads to a Server Error during the report generation when enough wizards have been created and the id exceeds the highest id of the accounts.

This is the traceback:

```
  File "odoo/openerp/tools/safe_eval.py", line 314, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "odoo/addons/account/report/account_general_ledger.py", line 299, in _get_account
    return self.pool.get('account.account').browse(self.cr, self.uid, data['form']['id']).company_id.name
  File "odoo/openerp/fields.py", line 823, in __get__
    return record._cache[self]
  File "odoo/openerp/models.py", line 5910, in __getitem__
    return value.get() if isinstance(value, SpecialValue) else value
  File "odoo/openerp/fields.py", line 55, in get
    raise self.exception
QWebException: ('MissingError', u'One of the documents you are trying to access has been deleted, please try again after refreshing.')
```

In `File "odoo/addons/account/report/account_general_ledger.py" _get_account`, the `data['form']['id']` statement returns the id of the wizard and not of the account. `data['id']` returns the account id.
### How to reproduce
1. Vanilla Odoo, new database
2. Install base, account and account_accountant modules with demo data
3. Create as many `account.report.general.ledger` objects as the highest `account.account` id so that the next id for `account.report.general.ledger` is greater than the largest `account.account` id
4. Go to Accounting->Configuration->Accounts->Accounts, select any account and print the General Ledger report.
### Expected behaviour

The Report is created
### Actual behaviour

The report fails with the message: One of the documents you are trying to access has been deleted, please try again after refreshing.

**Comment by dmacdonaldRobotiq** [comment]
Probably linked to this : https://github.com/odoo/odoo/pull/6791/files?diff=unified

**Comment by Yenthe666** [comment]
Hi @bwrsandman ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
