### ISSUE TITLE
When creating product, focus should goes on Product Name

### ISSUE THREAD

**Issue by zeroheure** [odoo/odoo#72999]
Impacted versions: Odoo 14.5alpha1+e (untested on previous)

Steps to reproduce: open Sales > Products, click on CREATE

Current behavior: focus is nowhere, one has to use one tabulation to set focus (cursor) in the Product Name field

Expected behavior: focus (cursor) in the Product Name field

**Comment by pedrobaeza** [comment]
Please don't open issues on a unstable version until the freeze is done. Problems are expected in it meanwhile.
