### ISSUE TITLE
Is there a correct way to patch new webclient services?

### ISSUE THREAD

**Issue by SplashS** [odoo/odoo#73000]
Impacted versions: Current master

I think in advance about migrating the `web_responsive` module (https://apps.odoo.com/apps/modules/14.0/web_responsive/) to 15.0.
Looking to the current codebase, I faced with a problem.

There is no way to patch hotkey_service (@web/core/hotkeys/hotkey_service). Thus, to support certain hotkey functions in the `web_responsive` module we will have to override hotkey_service altogether. This doesn't seem like the correct way to extend odoo.
Main service functions declared inside method `start` and I don't know way to patch them (https://stackoverflow.com/questions/59647878/how-to-monkey-patch-a-function-declared-inside-another-function).

Are there plans to implement correct way to patch services (in particular hotkey_service)?

Tag for current hotkey_service author: @brboi

**Comment by pedrobaeza** [comment]
Hi, @SplashS, I'm afraid this issue tracker is not doing such questions, and less in master version, but if you see clear that a hook for interacting is needed, then you can propose a pull request against master amending this.

I'm closing this issue now because of this.
