### ISSUE TITLE
RML in 8.0: translatable field values are always in the user's language

### ISSUE THREAD

**Issue by StefanRijnhart** [odoo/odoo#7301]
In cases where we set the language depending on a property of the record, for instance the customer's language, setLang in 8.0 does not deal adequately with caching in RecordSets so that translatable field values are always in the user's language. Consider the following case:

```
[[ repeatIn(objects, 'o') ]]
...
[[ setLang(o.partner_id.lang) ]]
```

In this case, *objects* is a RecordSet in the user's language. Each time setLang is called, new browse records are generated in the specified language and assigned to the *objects* variable but because we are already iterating over the RecordSet we are stuck with a reference to the original browse record in the wrong language.

**Comment by antonylesuisse** [comment]
RML is deprecated in v8 no report are bundled. We shipped it (like webkit) to ease the transition, but the proper fix is to convert the report to qweb. I hope to remove it from the tree before the v9 release.
