### ISSUE TITLE
Can no longer use Linked in with Customers 

### ISSUE THREAD

**Issue by joolsr** [odoo/odoo#7304]
Using Odoo vers 8 SAAS.

After setting up Linkedin so that contacts can be searched in Linked in. This now no longer works. I get the error : 

LinkedIn: Scope parameter is not authorized: r_network odoo

I guess it's connect to a chnage in LinkedIn api ?

ie http://stackoverflow.com/questions/30534762/error-scope-parameter-is-not-authorized-r-contactinfo

**Comment by ITGenIT** [comment]
We also have experienced this using the Odoo version 8 on premises install with Social Network module v8.0.1.0 enabled.

LinkedIn: Scope parameter is not authorized: r_network

Any news on this?

**Comment by kobelidze** [comment]
We're facing the same issue with odoo 8 SaaS.

Is it planned to fixed?

**Comment by joolsr** [comment]
From the little I understand the change in the LinkedIn api means that this
info is no longer freely available so it may not be as easy as you might
think unfortunately

Julian
