### ISSUE TITLE
[8.0]groups property on QWEB template not worked

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#7305]
Hello Odoo,

I tried to create a module to hide the export menu when we click more button on tree view.
I found that the code is on qweb, and for qweb there’s a groups property, so we can hide it base on that property.
But when I add that property, it doesn’t work on this qweb template.
the code is something like this:

```
<t t-extend="Sidebar">
    <t t-jquery="a.oe_sidebar_action_a" t-operation="replace">
            <a class="oe_sidebar_action_a" t-att-title="item.title or ''" t-att-data-section="section.name" t-att-data-index="item_index" t-att-href="item.url" target="_blank" groups="fal_web_hide_export.group_can_export">
                <t t-raw="item.label" />
            </a>
    </t>
</t>
```

The expected behavior:
It should be work like other qweb.

**Comment by Yenthe666** [comment]
Hi @falinwa,

Thanks for the report.
As this is about custom development and not about an Odoo bug itself you're better off asking this kind of questions on the official help forums at odoo.com/help.

Regards,
Yenthe
