### ISSUE TITLE
[v8.0] Bank statement : Customer Import invoice wizard do not auto-fill the right field

### ISSUE THREAD

**Issue by fclementic2c** [odoo/odoo#7306]
Step to reproduce:

create a customer invoice
create a new bank statement and import this invoice
click on 'Reconcile'
Problem: No match proposition between the bank statement line and the invoice move line can be found since the communication field is '/'. (The invoice number is in the field 'Reference' instead)

So please the ref must go to communication

Thanks

**Comment by fclementic2c** [comment]
solution odoo : https://github.com/odoo/odoo/commit/72ec0050b442214c9be93907fc01a48832243c15

**Comment by Yenthe666** [comment]
Fixed way back but never closed. Locky lock!
