### ISSUE TITLE
[8.0] website company_id defaults to a res.users record

### ISSUE THREAD

**Issue by antespi** [odoo/odoo#7308]
**website company_id defaults to a res.users record**

Impacted versions:

 - 8.0

Steps to reproduce:

1. Create a new website using XML file, like this one:
```
<?xml version="1.0" encoding="UTF-8"?>
<openerp>
    <data noupdate="1">
        <record id="website_alternative" model="website">
           <field name="name">alternative.localdomain</field>
           <field name="language_ids" eval="[(6,0,[ref('base.lang_en')])]" />
           <field name="default_lang_id" ref="base.lang_en" />
           <field name="user_id" ref="base.public_user" />
       </record>
    </data>
</openerp>
```
2. External XML differs: ```base.public_user != base.main_company```, in my case :
* base.public_user = 3
* base.main_company = 1

Current behavior:

```
  File "/opt/odoo/common/openerp/v8/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ParseError: "insert or update on table "website" violates foreign key constraint "website_company_id_fkey"
DETAIL:  Key (company_id)=(3) is not present in table "res_company".
```

Expected behavior:

 - Create a new record in ```website``` table using default company_id, for instance ```base.main_company```

I propuse to change this statement ```addons/website/models/website.py```:
```
    _defaults = {
        'company_id': lambda self,cr,uid,c: self.pool['ir.model.data'].xmlid_to_res_id(cr, openerp.SUPERUSER_ID, 'base.public_user'),
    }
```
replacing ```base.public_user``` by ```base.main_company```

**Comment by pedrobaeza** [comment]
Remember that you don't need to create an issue if you're already creating a PR.

**Comment by pedrobaeza** [comment]
You have to put this text into the PR description

**Comment by antespi** [comment]
@pedrobaeza I created the issue long time ago because it is a trivial patch. But today we need it.

**Comment by antespi** [comment]
Closed because this PR was opened https://github.com/odoo/odoo/pull/8236
