### ISSUE TITLE
Demo DBs have old PAD FQDN

### ISSUE THREAD

**Issue by jbradsha** [odoo/odoo#7310]
Demo databases (e.g. on runbot instances) have pad.opernerp.com configured as the Company's PAD server.  This is now pad.odoo.com so the databases should be corrected at source too.

I fixed the URL in the settings page but it would be good to have it fixed at source too.

There is no HTTP redirect from pad.opernerp.com to pad.odoo.com

**Comment by Yenthe666** [comment]
Hi @jbradsha,

Thanks a lot for your report.
This has been handled in the meanwhile:
![image](https://user-images.githubusercontent.com/6352350/35335744-b3cbbeca-0116-11e8-9dd0-c10ff1fc2ab5.png)


Regards,
Yenthe
