### ISSUE TITLE
Error On Clicking Confirm Draft Invoice Button From Invoice Tree View

### ISSUE THREAD

**Issue by niyasraphy** [odoo/odoo#73188]
Impacted versions: Checked in Odoo 12 CE

Steps to reproduce: Create two draft invoice and set invoice date for one of the invoice and keep the other one empty

Current behavior: Go to Tree view, select the created invoices and click Confirm Draft Invoice from action button. You Will get an error.

Expected behavior: Without error invoice has to get confirmed

Video/Screenshot link (optional):  https://user-images.githubusercontent.com/27989791/124357371-cc086380-dc23-11eb-90ff-6a80740ed416.mp4

**Comment by sswapnesh** [comment]
Added a fix on https://github.com/odoo/odoo/pull/73529

**Comment by sswapnesh** [comment]
This has been fixed via https://github.com/odoo/c/pull/73529
