### ISSUE TITLE
[Odoo 13 CE] Group by computed field

### ISSUE THREAD

**Issue by guidev224** [odoo/odoo#73189]
Impacted versions: Odoo 13 CE

Steps to reproduce: Create a custom module then add a model with  computed field with store=True. Call the read_group method upon this model with the computed field within broupby fields. Here the field's declaration

```
type_id = fields.Many2one('my_module.custom.model', string='Type', compute='_compute_type_id',
                              store=True,tracking=True, check_company=True)
```

Current behavior: Get following error
```
Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1319, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1311, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 391, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 364, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/usr/src/app/custom_addons/asb_mgmt_reporting/models/dashboard.py", line 64, in get_dashboard_data
    groupby='type_id')
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2132, in read_group
    result = self._read_group_raw(domain, fields, groupby, offset=offset, limit=limit, orderby=orderby, lazy=lazy)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2169, in _read_group_raw
    assert gb_field.store and gb_field.column_type, "Fields in 'groupby' must be regular database-persisted fields (no function or related fields), or function fields with store=True"
AssertionError: Fields in 'groupby' must be regular database-persisted fields (no function or related fields), or function fields with store=True
```

Expected behavior: Execute code without any error

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
This is something expected. Read the message about the conditions you need to fulfill.

**Comment by guidev224** [comment]
What is that condition that is not fulfilled by my code??

**Comment by pedrobaeza** [comment]
Fields in 'groupby' must be regular database-persisted fields (no function or related fields), or function fields with store=True

**Comment by guidev224** [comment]
@pedrobaeza this message is misleading imho, according to it the exception is within parentheses right??

**Comment by pedrobaeza** [comment]
I don't see such ambiguity.

**Comment by guidev224** [comment]
Okay then why do we have `no function or related fields` within parentheses and ` or a function field with store=True` outside the parentheses?? Don't you find this ambiguous??

**Comment by guidev224** [comment]
I think you must leave this issue open, maybe someone else could give his opinion too

**Comment by pedrobaeza** [comment]
This issue tracker is for bugs in the code. If you think the message can be improved, you can propose a pull request.

**Comment by guidev224** [comment]
@pedrobaeza  look at this warning from the official documentation

```
Warning

like the graph view, the pivot aggregates data on database content which means that non-stored function fields can not be used in pivot views
```
the key point here is the expression **non-stored function fields**. What does this expression mean??

**Comment by pedrobaeza** [comment]
I still don't get what do you want. The redaction seems clear for me: fields that are not stored, can't be used there.

**Comment by guidev224** [comment]
Let's get it clear @pedrobaeza 
I have a computed field with store=True and that field is well stored in the database (see the linked image), now I want to use that field as a groupby field with the read_group method but Odoo keeps throwing at me the following error: 
`AssertionError: Fields in 'groupby' must be regular database-persisted fields (no function or related fields), or function fields with store=True`

This message is very clear!! It means if I want to use a field as a groupby field, that field **MUST** either be a **database-persisted field** (a regular one) or a **computed field with store=True** .**AND** my field fulfill the last condition (computed field with `store=True`).
So why Odoo keeps throwing at me this strange message?? That's what I want to understand. 
Here is the declaration of my field:

```
type_id = fields.Many2one('my_module.custom.model', string='Type', compute='_compute_type_id',
                              store=True,tracking=True, check_company=True)
```
As you can see it has the store=True condition fulfilled.

I hope that my aim is now clear..

<img width="562" alt="Screen Shot 2021-07-05 at 14 07 40" src="https://user-images.githubusercontent.com/31063466/124487940-caaf7600-dd9e-11eb-8ee0-46760bd713ad.png">

**Comment by pedrobaeza** [comment]
There's something probably incorrect in the deployment of the code. Start from a clean DB and try again, and if it's still not working, then upload here the minimal reproducible code with the problem.

**Comment by guidev224** [comment]
I don't see what is incorrect with the deployment of the code. And I have indicated the steps to reproduce the issue in my first post.
1. Create a computed field  with store=True
2. Use that field as groupby field when calling the read_group method or try to use this field in a search view
You will get the same message.

So again I think you **MUST** leave this issue open to let other contributors give their opinion

**Comment by pedrobaeza** [comment]
I have put such computed stored field several times without problem, so I can assure you that it works, so there should be another thing.

**Comment by Boudmir-Ibrahim** [comment]
Hi @guidev224 ,

did you try to add your field type_id in a normal search view and still get the same error ? 
if so, can you please rename the field and try again in a new DB? 

**i have a note: i see that you mention the following:**
`fields.Many2one('my_module.custom.model',...)

`you should actually have:  `fields.Many2one('custom.model',...) `
we don't add module name to the comodel_name .

Hope this helps.

**Comment by guidev224** [comment]
@Boudmir-Ibrahim 
1. Yes I have the same issue when using type_id in a normal search view
2. I'll try renaming the field but I highly doubt that it is the cause because I have the same problem with other computed-stored fields
3. The problem is not from the model name, indead my model name is actually :`my_module.custom.model`

**Comment by guidev224** [comment]
> I have put such computed stored field several times without problem, so I can assure you that it works, so there should be another thing.

@pedrobaeza I'll try with a fresh module and a fresh db. I'll let you know

**Comment by Boudmir-Ibrahim** [comment]
@guidev224 , 

That is so weird. I have never had such a problem. computed and stored fields do work in search view without any complications.

**Try to pull a new Odoo server too.**
