### ISSUE TITLE
Database creation error: relation "ir_model" does not exist LINE 1: SELECT * FROM ir_model WHERE state='manual' ^

### ISSUE THREAD

**Issue by iwebroot** [odoo/odoo#73204]
Impacted versions: Odoo 14

Steps to reproduce:
1. Install Odoo via repo or file .deb
2. Open Odoo from browser
3. Error Database creation

Additional Information:
OS: Debian 10
PostgreSQL: version 13

Log:
`WARNING dbo_scm odoo.modules.loading: Transient module states were reset`
`ERROR dbo_scm odoo.modules.registry: Failed to load registry`
`INFO dbo_scm werkzeug: 197.149.43.190 - - [28/Jun/2021 18:48:54] "GET /robots.txt HTTP/1.1" 404 - 10 0.005 0.025`
`INFO dbo_scm odoo.modules.loading: loading 1 modules...`
`INFO dbo_scm odoo.modules.loading: 1 modules loaded in 0.02s, 0 queries (+0 extra)`
`ERROR dbo_scm odoo.sql_db: bad query: SELECT * FROM ir_model WHERE state='manual'`
`ERROR: ERREUR: la relation « ir_model » n'existe pas`
`LIGNE 1 : SELECT * FROM ir_model WHERE state='manual'`

Video/Screenshot link:
https://www.transfernow.net/dl/202107040aBcUYNi

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/13.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).

**Comment by iwebroot** [comment]
Hi,
Thank you for your feedback.

I try a clean installation from scratch on Debian 10 (Buster) as `root` with "apache" and "PHP"

1. Install PostgreSQL from Debian repo version 11
`apt install postgresql -y`

2. Add Key
`wget -O - https://nightly.odoo.com/odoo.key | apt-key add -`

3. Add source for Odoo 14
`echo "deb http://nightly.odoo.com/14.0/nightly/deb/ ./" >> /etc/apt/sources.list.d/odoo.list`

4. Install "wkhtmltopdf"
`wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.buster_amd64.deb`
`dpkg -i wkhtmltox_0.12.6-1.buster_amd64.deb`

5. Install Odoo 14
`apt update && apt-get install odoo`

6. Install "python3-xlwt" and "num2words"
`pip3 install xlwt`
`pip3 install num2words`

All service is ready.

6. Open Odoo from browser http://xxx.xxx.xxx.xxx:8069

7. Set master password and all field without demo

Video / Screenshot link of result :
https://prnt.sc/19is6s2

Log : 
https://justpaste.it/3a38i

Thank you in advance for your feedback.
