### ISSUE TITLE
Website_slides MASTER v9 ERROR

### ISSUE THREAD

**Issue by crazydanilo** [odoo/odoo#7325]
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 538, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 575, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/openerp/http.py", line 311, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/openerp/http.py", line 308, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/openerp/http.py", line 813, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/openerp/http.py", line 404, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/openerp/addons/web/controllers/main.py", line 961, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/openerp/addons/web/controllers/main.py", line 949, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 223, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/module/module.py", line 434, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/odoo/openerp/api.py", line 223, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/module/module.py", line 508, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/odoo/openerp/modules/registry.py", line 349, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/openerp/modules/loading.py", line 335, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/openerp/modules/loading.py", line 235, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/openerp/modules/loading.py", line 159, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='demo')
  File "/opt/odoo/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/openerp/tools/convert.py", line 865, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/openerp/tools/convert.py", line 952, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/openerp/tools/convert.py", line 815, in parse
    self.parse(rec, mode)
  File "/opt/odoo/openerp/tools/convert.py", line 818, in parse
    self._tags[rec.tag](self.cr, rec, de, mode=mode)
  File "/opt/odoo/openerp/tools/convert.py", line 716, in _tag_record
    f_val = _eval_xml(self,field, self.pool, cr, self.uid, self.idref)
  File "/opt/odoo/openerp/tools/convert.py", line 155, in _eval_xml
    with openerp.tools.file_open(node.get('file'), 'rb') as f:
  File "/opt/odoo/openerp/tools/misc.py", line 186, in file_open
    return _fileopen(name, mode=mode, basedir=rtp, pathinfo=pathinfo, basename=basename)
  File "/opt/odoo/openerp/tools/misc.py", line 233, in _fileopen
    raise IOError('File not found: %s' % basename)
ParseError: "File not found: website_slides/static/src/img/keynote.pdf" while parsing /opt/odoo/openerp/addons/website_slides/data/website_slides_demo.xml:121, near
<record id="slide_10" model="slide.slide">
            <field name="name">Odoo Roadmap &amp; Strategy - Fabien Pinckaers</field>
            <field name="datas" type="base64" file="website_slides/static/src/img/keynote.pdf"/>
            <field name="image" type="base64" file="website_slides/static/src/img/keynote.png"/>
            <field name="slide_type">presentation</field>
            <field name="channel_id" ref="channel_partial"/>
            <field name="category_id" ref="category_2"/>
            <field name="website_published" eval="True"/>
            <field name="likes">13</field>
            <field name="slide_views">6399</field>
            <field name="index_content">1. Odoo Roadmap &amp; Strategy Fabien Pinckaers, Founder
2. From 2,000,000 users to 10,000,000 users. or how we will turn Odoo mainstream...
3. from $2M to $10M Investment Areas To Turn Odoo Mainstream 5 or how to spend $10M as fast as possible and burn a lot of energy...
4. Release A Product That Deprecates Every Competitor 1 This is something we excel at...
5. A product growth no one can follow
6. Version 9: roadmap o 40% Usability: &#8211; Improving all existing apps, the right feature at the right place &#8211; User onboarding, ease of use o 20% Accounting: &#8211; 8 countries in the core o 20% CMS / eCommerce o 10% New design: &#8211; Merge front/backend, mobile, modern design o 10% Framework: o New API
7. 1 Release cycle February 2012: v6.1 (13 months) 2 January 2013: v7 (11 months) 3 June 2014: v8 (18 months) 4 June 2015: v9 (12 months) 5 Every new version is a revolution. Version 9 will be even more impressive! January 2011: v6.0
8. Attract The Mass Of Users 2 It's all about getting users, a lot of users. Not only customers.
9. An attractive pricing... o The cloud, free for 2 users: &#8211; Why the cloud? Smooth user experience. High satisfaction rates as everything works out-of-the-box &#8211; Unlimited applications: CRM, CMS, eCommerce, Accounting, etc. o Millions of CMS/eCommerce for free: &#8211; Already 50k pages on CMS/eCommerce websites built with Odoo CMS Beta &#8211; You can do a lot with 2 users: we don't need to get revenues from CMS/eCommerce-only instances as we have so many applications to upsell
10. Affordable implementations o Lower entry barrier - no huge starting costs for SMEs: &#8211; No complex implementation projects &#8211; A fixed-price packaged offer o New service offer, 100&#8364; / month per application for: &#8211; Implementation assistance and configuration &#8211; Unlimited customization of screens, reports, workflows &#8211; Monthly upgrades &#8211; Training material &#8211; Unlimited support tickets, 24/24 response time!
11. Disrupt A Market Having A Huge Traction 3 Creating the frontend of all apps will not only increase the quality of all apps but also disrupt the CMS/eCommerce market.
12. " " The CMS/eCommerce market looks like the ERP market 6 years ago, before Odoo entered into it. Full of complex products that did not evolve over the past 3 years.
13. Traditional ERPs o The monetization (and main focus) remains on business apps: &#8211; Accounting &#8211; Warehouse Management &#8211; Project Management &#8211; Point of sale &#8211; Marketing &#8211; HR, ... o But CMS/eCommerce will bring a huge volume of prospects to our other business apps
14. Make Partners Rich By Making Customers Super-Happy 4 You will like our product and services so much that you will always want to purchase more.
15. Traditional ERPs o Buy an ERP &#8211; Invest on 7 years o Maintain as long as you can &#8211; Implementations are so painful that you have no other choice &#8211; Upgrades are too expensive o After 7 years : it breaks &#8211; You change the product and call other vendors
16. Traditional ERPs o Modern companies deserve to: &#8211; Evolve continuously &#8211; Benefit from top features every year &#8211; Be free of any legacy constraints &#8211; Have the flexibility to customize easily o Odoo Enterprise &#8211; our main value proposition: &#8211; Providing so much value to customers through continuous upgrades that they will want to purchase even more
17. Odoo Enterprise o Odoo Enterprise is our core business: &#8211; Unlimited upgrades &#8211; Unlimited bugfix support &#8211; Optional hosting on our cloud &#8211; Guarantees : security, performance, legal o Customers shouldn't have to pay for: &#8211; Painful upgrades; if upgrades are costly, they tend to not upgrade &#8211; Bugs take delay the project and costs man*days of work
18. " " Story of a 1300 users customer I met last week...
19. Let's Burn A Few Millions In Marketing Too 5 We have an awesome product, a huge channel of partners, a strong service offer, ... Now, people need to know it.
20.
21. Marketing activities o Smart Content: &#8211; Documentation, books, blog posts, white papers, Q&amp;A &#8211; Translations of website and documentation &#8211; A super clean website, marketing optimized ! o Inbound Marketing: &#8211; SEO, SEA, funnel optimization with a powerful CMS o User/developer on boarding: &#8211; Users : usability, clean features, etc. &#8211; Devs: docs, easy installation, modules scafolding, ... &#8211; Community: efficient tools and communication o Local Events: share, meet and inform people
22. All of this while maintaining a fun working environment and a sane relationship between partners, customers and the community.
23. Relationship between proprietary software vendors and their implementation partners
24. What we do By enforcing full open source rules, we set up the rules to guarantee a sane relationship between all parties of the value chain: &#9679; Vendor: Odoo SA &#9679; Customers &#9679; Partners &#9679; Community
25. 2014-2015 This will be an epic time...</field>
            <field name="tag_ids" eval="[(4, ref('tag5'))]"/>
        </record>

**Comment by mart-e** [comment]
Hello,

Thank you for the report but the master version is still unstable so, yes you will get errors during the tests. There may have temporary issues so no need to report issues on master version.
I advise you to use the latest stable version instead (v8)
