### ISSUE TITLE
how can I use arrays in QWeb

### ISSUE THREAD

**Issue by fwilly** [odoo/odoo#7327]
I have not found a possibility to use multi line phython code. The once I have found was `t-set`.

The following rows are a trial to save the different tax values from an invoice to an array.
```xml
<t t-set="tax" t-value="{}"/>
<t t-if="o.tax_line">
    <t t-foreach="o.tax_line" t-as="t">
        <t t-set="tax[t.id,'text']" t-value="t.name"/>
        <t t-set="tax[t.id,'amount']" t-value="0"/>
        <t t-set="tax[t.id,'rate']" t-value="1"/>
    </t>
</t>
```
Later I wanted to use it to save values per invoice line to aggregate it self to make page subtotals.
```xml
<t t-foreach="o.invoice_line" t-as="l">
    <t t-set="tax[l.invoice_line_tax_id.id,'rate']" t-value="l.invoice_line_tax_id.amount"/>
    <t t-set="tax[l.invoice_line_tax_id.id,'amount']" t-value="tax[l.invoice_line_tax_id.id,'amount'] + (l.price_subtotal * l.invoice_line_tax_id.amount)"/>
    </t>
</t>
```
But this don't work:
```python
QWebException: ""(16, 'rate')" while evaluating
"tax[l.invoice_line_tax_id.id,'rate']"" while evaluating
```
Know any one a possibility to use multi dimensional associative arrays? Or one dimensional associative arrays? Or simple arrays?

**Comment by TheCloneMaster** [comment]
Hi,

You should do that in the related .py parser file.

Addons folder has many samples.

**Comment by fwilly** [comment]
But what is the related .py file?

I have make follwing documents:
- report:
    - name: orcas Rechnung
    - model: account.invoice
    - report typ: PDF
    - template name: account.orcas_invoice
- views:
    1. name: orcas_invoice
        - view typ: QWeb
        - model data: orcas_invoice
        - external id: account.orcas_invoice
    2. name: orcas_invoice_document
        - view typ: QWeb
        - model data: orcas_invoice_document
        - external id: account.orcas_invoice_document

**Comment by TheCloneMaster** [comment]
Take a look at point_of_sale, or most other standard modules.

You will find that the report definition references a wrapper class...

This is in point_of_sale/report/pos_details.py...





*class report_pos_details(osv.AbstractModel):    _name =
'report.point_of_sale.report_detailsofsales'    _inherit =
'report.abstract_report'    _template =
'point_of_sale.report_detailsofsales'    _wrapped_report_class =
pos_details*


that one is the related class that will be called inside the qweb template
when it invoques any function...

Regards,
-Mario

**Comment by fwilly** [comment]
For my reports no own files are created. But it is inherited/copy from/of default invoice report. I also think that right file is /usr/lib/python2.7/dist-packages/openerp/addons/account/report/account_invoice_report.py

If so, what is the right function? Or what is the right file?

**Comment by fwilly** [comment]
It means, I haven't created files in directory structure. My report was created by Odoo GUI (related to http://odoo.guide/report-design-workshop/).
This is apparently not the best way. Is it better to create report in files? (As explained in http://www.zbeanztech.com/blog/qweb-report)
Or how can I set my new report as default invoice report to use, if I press the print button?

**Comment by sle-odoo** [comment]
Please refer to [the documentation](https://www.odoo.com/documentation/8.0/reference/reports.html)

Regards

**Comment by Zoltan-X** [comment]
l is invoice_line so take directly id instantiating is not working this way!!


<t t-foreach="o.invoice_line" t-as="l">
    <t t-set="tax[l.id,'rate']" t-value="l.invoice_line_tax_id.amount"/>
    <t t-set="tax[l.id,'amount']" t-value="tax[l.invoice_line_tax_id.id,'amount'] + (l.price_subtotal * l.invoice_line_tax_id.amount)"/>
    </t>
</t>


with best regards!  

:)
