### ISSUE TITLE
[8.0][Blog]Commenting paragraph is available whereas comments on post are not

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#7328]
Hi,

Maybe I didn't understood the purpose of the little + icon near each paragraph in blog posts, because as you can see below it's possible to put comments on paragraphs :
![proxmox-reseau1](https://cloud.githubusercontent.com/assets/1043935/8395898/6b76b946-1d8d-11e5-9969-c330cfc3768b.jpeg)
Yet public users are not set to be able to comment on blog posts. I also reference the #6932 that could be linked to this one AFAIK.

Thanks

**Comment by Yenthe666** [comment]
Hi @flotho,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
