### ISSUE TITLE
[13.0] purchase: Can't change price in invoiced and refunded purchase order

### ISSUE THREAD

**Issue by carlosdauden** [odoo/odoo#73344]
A supplier makes us an invoice.
As the prices are wrong, the supplier create a refund.
Then he makes the invoice with the correct prices.
How can we register correct prices in the purchase order?

https://github.com/odoo/odoo/blob/c76454f325a52ba4bb49d9dae9f760046eb39ebd/addons/purchase/views/purchase_views.xml#L216
Any problem with this?:
` <field name="price_unit" attrs="{'readonly': [('qty_invoiced', '!=', 0.0)]}"/> `

@Tecnativa TT30906

**Comment by pedrobaeza** [comment]
@amoyaux would you accept such change in standard?

**Comment by amoyaux** [comment]
I would prefer in master

**Comment by sswapnesh** [comment]
Added fix https://github.com/odoo/odoo/pull/74526

**Comment by sswapnesh** [comment]
Fixed in https://github.com/odoo-dev/odoo/commit/92ea613d4320fe87cce17f3bb6cdb51ce99ef5bf
