### ISSUE TITLE
[14.0] Example of HTML Fetch API for Odoo's Web Controller

### ISSUE THREAD

**Issue by humbletrad** [odoo/odoo#73353]
Impacted versions:
V14

Steps to reproduce:
How does using fetch API to post data to Web Controller, Cant figure what I am missing. Postman example references is great too, at least probably can generate client side code.

```
    @http.route(['/mail/postToken'], type="json", auth="user")
    def postToken(self, **kw):	
          kw['currentToken']
          #
          kw.get('currentToken')
```

```
  data : { 'jsonrpc': '2.0', token": "ABCD"}
  const response = await fetch(url, {
    method: 'POST', // *GET, POST, PUT, DELETE, etc.
    mode: 'cors', // no-cors, *cors, same-origin
    cache: 'no-cache', // *default, no-cache, reload, force-cache, only-if-cached
    credentials: 'same-origin', // include, *same-origin, omit
    headers: {
      'Content-Type': 'application/json'
    },
    redirect: 'follow', // manual, *follow, error
    referrerPolicy: 'no-referrer', // no-referrer, *no-referrer-when-downgrade, origin, origin-when-cross-origin, same-origin, strict-origin, strict-origin-when-cross-origin, unsafe-url
    body: JSON.stringify(data) // body data type must match "Content-Type" header
  });
```

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
