### ISSUE TITLE
[14.0][MRP] It is not possible to unreserve more products of [FURN_2333] Table Leg than you have in stock.

### ISSUE THREAD

**Issue by fa-odoo** [odoo/odoo#73354]
Impacted versions: 14.0

Steps to reproduce:
**In some cases**, when you change the lot and reduce the quantity done on workorder consumption and use a new lot.

The problem is reproduced on odoo runbot:
https://8734951-14-0-all.runbot60.odoo.com/web#id=2&active_id=1&model=mrp.production&view_type=form&cids=1&menu_id=653

The line causing the problem is on module mrp_workorder/model/mrp_workorder.py:

                if float_compare(self.qty_done, self.move_line_id.product_uom_qty, precision_rounding=rounding) >= 0:
                    self.move_line_id.write({
                        'qty_done': self.qty_done,
                        'lot_id': self.lot_id.id,
                    })
                else:
                    new_qty_reserved = self.move_line_id.product_uom_qty - self.qty_done
                    default = {
                        'product_uom_qty': new_qty_reserved,
                        'qty_done': 0,
                    }
                    self.move_line_id.copy(default=default)
                    self.move_line_id.with_context(bypass_reservation_update=True).write({
                        'product_uom_qty': self.qty_done,
                        'qty_done': self.qty_done,
                        'lot_id': self.lot_id.id,
                    })

**Comment by pedrobaeza** [comment]
Please expose all the detailed steps to get to that problem.

**Comment by fa-odoo** [comment]
From a workorder : try to change reserved lot and set the done quantity of that lot to be less than the resereved quantity.
continue consumption with another lot

**Comment by fa-odoo** [comment]
https://user-images.githubusercontent.com/42148719/124777543-2fea9f00-df38-11eb-9527-6e06d24f6a50.mp4

**Comment by fa-odoo** [comment]
Uploading RES(1).mp4…

**Comment by fa-odoo** [comment]
https://user-images.githubusercontent.com/42148719/124779649-dc795080-df39-11eb-8f96-3cea56ac75ce.mp4

**Comment by fa-odoo** [comment]
@pedrobaeza

**Comment by pedrobaeza** [comment]
I still feel that something is missing in the steps, as I only see the result, but not the previous state, and there's a lot of noise in between. Can you please start from the scratch creating the product, the BoM, the stock, and the leading to the condition that gets to the problem? Or at least, point where is the problem.

Anyways, this is opened for anyone of Odoo stuff to check if for them, this is enough.

**Comment by fa-odoo** [comment]
the problem is made by the this line :           
  self.move_line_id.with_context(bypass_reservation_update=True).write({ 'product_uom_qty': self.qty_done,
                    'qty_done': self.qty_done,
                    'lot_id': self.lot_id.id,
                })

I don't understand why there is bypass_reservation_update set to true while it set the product_uom_qty. The fact of doing that makes a diffrence between the reserved quantities in stock_move_line and stock_quant

**Comment by pedrobaeza** [comment]
OK, maybe @amoyaux can tell us.

**Comment by amoyaux** [comment]
@pedrobaeza @fa-odoo It has been fixed by https://github.com/odoo/enterprise/pull/19490
Thanks for reporting
