### ISSUE TITLE
ir.config_parameter used without a sudo raises issues

### ISSUE THREAD

**Issue by yp-oerp** [odoo/odoo#73400]
When procurement is triggered the below code is executed and if the user doesn't have admin access this raises issues of access rights as ir.config_parameter are supposed to be taken with a "SUDO"
https://github.com/odoo/odoo/blob/1bbe88796a5b03ab1ab2faec1f0fe4f735fcb485/addons/purchase_stock/models/stock_rule.py#L313

**Comment by pedrobaeza** [comment]
But isn't already sudoed? How do you trigger the procurement?

**Comment by Yenthe666** [comment]
I presume he runs the cron from a non-admin user who has limited rights and thus cannot access `ir.config_parameter`?

**Comment by sswapnesh** [comment]
Added Fix on https://github.com/odoo/odoo/pull/73528

**Comment by sswapnesh** [comment]
@pedrobaeza @Yenthe666 It is from 
![Screenshot (22)](https://user-images.githubusercontent.com/16624719/125187248-3afd4200-e24c-11eb-9d29-ebea53d122b8.png)
