### ISSUE TITLE
Error using 'get_cc_module' from stdnum.util

### ISSUE THREAD

**Issue by rejamen** [odoo/odoo#73526]
Impacted versions: Odoo CE 14.0-20210702

Steps to reproduce: 
Installing any module that use 'get_cc_module'. In my case I am trying to install "l10n_es_aeat"

Current behavior:
AttributeError: module 'stdnum.util' has no attribute 'get_cc_module'

Expected behavior:
get_cc_module should be possible to use. 

What I tried:
Using "pip3 install python-stdnum==1.8"; in this version "get_cc_module" can be accessible from "stdnum.get_cc_module"; then one possible solution is update stdnum to that version and extend all functions that use 'get_cc_module' and change them to use it like "stdnum.get_cc_module". 

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
Sorry, but the error you are mentioning corresponds to a custom module or code, so the problem should be there in your code. This issue tracker is for notifying problems with standard Odoo code, and thus I'm closing this. Anyways, `l10n_es_aeat` is not using such method `get_cc_module`.

Try to share your question, doubt or problem in the official Odoo forums (https://www.odoo.com/forum/help-1) or on the mailing lists (https://www.odoo.com/groups) to see if someone can help you.
