### ISSUE TITLE
Import products - No matching record found for external id '' in field 'Products' at row 2 

### ISSUE THREAD

**Issue by apmoonen** [odoo/odoo#7353]
I have been testing Odoo for months on an old P4 and all is well. Now I have a decent piece of hardware (Server) and I have done a fresh install of Ubuntu 14.04 server and installed Odoo v8 afresh and created a new database. I have had my product files ready for a while so I am thinking it should be easy.
Then the error above appears... I have never seen it before!!
When I click on the "Get all possible Values" link under neath the error, I see this:
product.product_product_consultant

I have looked up the issues and found that most of them have to do with deleting the default service product and trying to install the time sheet module. Well I have made the mistake of deleting the default service product before, and have not deleted it this time (hence the fresh install), also, I CAN install the timesheets module with no problem.j

Sooo, why is this a problem? I have checked all the issues here and on odoo and cannot find why the service template is stopping me import physical products. Did not happen on previous installs, just this one?

**Comment by Yenthe666** [comment]
Hi @apmoonen,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
