### ISSUE TITLE
Error in hr_employee_tree

### ISSUE THREAD

**Issue by pcordova-sci** [odoo/odoo#7354]
There is an action error "Could not find client action 'emp.chart' " using the module hr_employee_tree in Odoo version 8. Is there already a fix done for this module? Also, I cannot find the module in app.openerp.com anymore (apps.openerp.com/apps/modules/8.0/hr_employee_tree). Thanks.

**Comment by Yenthe666** [comment]
Hi @pcordova-sci ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
