### ISSUE TITLE
Jalaali date system support

### ISSUE THREAD

**Issue by saeed-raeisi** [odoo/odoo#73599]
Impacted versions:
_14.0_
===========================
Steps to reproduce:
**persian** date problem
===========================
Current behavior:
**gregorian** date
===========================
Expected behavior:
Ability to use **jalali** calendar
===========================
Video/Screenshot link (optional):

- [calendar_video](https://mega.nz/file/q7IVUITL#FzFvXMwtMhrbIkIbGsvR-4Y-eNFP0eKb96mlpyA3tyA)
- [date_system_problem_online](https://streamable.com/lx061g)
[date_system_problem_download](https://mega.nz/file/qqA0xZTC#2kwINnj9_X6v_6w-bMny2Asy5Szx9ZxOS-b1HcNbVi0)

useful link:

1. [parodoo](https://github.com/parodoo/parOdoo)
2. [jdatetime](https://pypi.org/project/jdatetime/)
3. [oca_iran](https://github.com/OCA/l10n-iran)
4. [add-jalali-support](https://github.com/OCA/l10n-iran/tree/add-jalali-support)
5. [Jalaali date system support(fullcalendar)](https://github.com/fullcalendar/fullcalendar/issues/1813)
6. [jalali date chart.js](https://github.com/chartjs/Chart.js/issues/6302)
7. [jalali-calendar](https://github.com/topics/jalali-calendar)
8. [jalaliDate-JavaScript](https://github.com/SCR-IR/jalaliDate-JavaScript)

search_utils problem : 
in web/static/src/js/control_panel/search_utils.js  ->  year and month problem in domain
in fullcalendar v4 problem in day and week filter (fullcalendar v5 is ok but written by typescript)
in chart.js and And wherever there is a date

solved:

1. Printable documents -> Iranian date added
2. datepicker added -> Display in fields was resolved

Support ticket number submitted via odoo.com/help (optional):
#2590993 : persian support -> Bug Fixes
@pedrobaeza

**Comment by miladsadeghi1376** [comment]
I have exactly the same problem.

**Comment by saeed-raeisi** [comment]
https://github.com/odoo/odoo/issues/72151

**Comment by saeed-raeisi** [comment]
_Add jdate in Odoo_
**in /web/static/src/js/libs/jdate.js**

```
odoo.define('/web/static/src/js/libs/jdate.js', function () {
    "use strict";
    function gregorian_to_jalali(gy, gm, gd) {
        return new Date(jy,jm,jd);
      }

      function jalali_to_gregorian(jy, jm, jd) {
        return new Date(gy,gm,gd);
      }
      return {
        gregorian_to_jalali,jalali_to_gregorian,
    };
});
```


_use :_
**const { gregorian_to_jalali } = require('/web/static/src/js/libs/jdate.js');**

**Comment by saeed-raeisi** [comment]
https://github.com/mrr-r/convert-date-on-reports-pdf-in-odoo-to-jalali
https://github.com/slashmili/python-jalali

**Comment by saeed-raeisi** [comment]
Change MessageList => ThreadView  => seprator LableDate To jalali
path : addons/mail/static/src/components/message_list/message_list.js 

    getDateDay(message) {
        const date = message.date.format('YYYY-MM-DD');
        if (date === moment().format('YYYY-MM-DD')) {
            return this.env._t("Today");

        } else if (
            date === moment()
                .subtract(1, 'days')
                .format('YYYY-MM-DD')
        ) {
            return this.env._t("Yesterday");
        }
```
        // Create date by local
        const event = new Date(message.date);

        const options = { year: 'numeric', month: 'long', day: 'numeric'};
        // return message.date.format('LL');
        // TODO need get local from odoo
        return event.toLocaleDateString('fa-IR', options);
    }
```

**Comment by saeed-raeisi** [comment]
> _Add jdate in Odoo_
> **in /web/static/src/js/libs/jdate.js**
> 
> ```
> odoo.define('/web/static/src/js/libs/jdate.js', function () {
>     "use strict";
>     function gregorian_to_jalali(gy, gm, gd) {
>         return new Date(jy,jm,jd);
>       }
> 
>       function jalali_to_gregorian(jy, jm, jd) {
>         return new Date(gy,gm,gd);
>       }
>       return {
>         gregorian_to_jalali,jalali_to_gregorian,
>     };
> });
> ```
> 
> _use :_
> **const { gregorian_to_jalali } = require('/web/static/src/js/libs/jdate.js');**

addons/web/static/src/js/views/calendar/calendar_renderer.js

```
    _initCalendarMini: function () {
        var self = this;
        this.$small_calendar = this.$(".o_calendar_mini");
        this.$small_calendar.datepicker({
            'onSelect': function (datum, obj) {
                self.trigger_up('changeDate', {
                    date: moment(gregorian_to_jalali(+obj.currentYear , +obj.currentMonth, +obj.currentDay))
                });
            },
            'showOtherMonths': true,
            'dayNamesMin' : this.state.fc_options.dayNamesShort.map(x => x[0]),
            'monthNames': this.state.fc_options.monthNamesShort,
            'firstDay': this.state.fc_options.firstDay,
        });
    },
```

**Comment by saeed-raeisi** [comment]
addons/web/static/lib/jquery.ui/jquery-ui.js

![1](https://user-images.githubusercontent.com/38601142/128158291-68a6a1d1-72d8-4145-9004-89a95cd3bf35.png)
![2](https://user-images.githubusercontent.com/38601142/128158418-895529d6-e1a8-4ccc-887a-de07edbb8696.png)

**Comment by saeed-raeisi** [comment]
addons/web/static/src/js/views/calendar/calendar_controller.js
Line:17->
const { jalali_to_gregorian } require('/web/static/src/js/libs/jdate.js');

224:
```
    _onChangeDate: function (event) {
        // Convert To Gregorian
        var localToday = jalali_to_gregorian(event.date.date._d.getFullYear(),event.date.date._d.getMonth(),event.date.date._d.getDate())
        var modelData = this.model.get();
        if (modelData.target_date.format('YYYY-MM-DD') === event.data.date.format('YYYY-MM-DD')) {
            // When clicking on same date, toggle between the two views
            switch (modelData.scale) {
                case 'month': this.model.setScale('week'); break;
                case 'week': this.model.setScale('day'); break;
                case 'day': this.model.setScale('month'); break;
            }
        } else if (modelData.target_date.week() === event.data.date.week()) {
            // When clicking on a date in the same week, switch to day view
            this.model.setScale('day');
        } else {
            // When clicking on a random day of a random other week, switch to week view
            this.model.setScale('week');
        }
        this.model.setDate(event.data.date);
        this.reload();
    },
```

**Comment by saeed-raeisi** [comment]
**This issue is closed**

- The localization project has started and most of the translated sections of the dates have become jalali
- Soon all Iranian localization modules will be developed.

_https://github.com/FadooIR
https://github.com/OCA/l10n-iran_

> fadoo
> It is the only set of localization modules in Iran
