### ISSUE TITLE
[BUG] copy_data() function is not compatible with new API

### ISSUE THREAD

**Issue by HugeOguh** [odoo/odoo#7362]
Impacted versions:

- 8.0

Steps to reproduce:

1. create/get a new API browserecord in a code.

2. call copy_data function of the record: "browserecord.copy_data()"

3. call ends with error: "NotImplementedError: 'setdefault' not supported on frozendict"

Current behavior:

- Can NOT call copy_data() using new API browserecord because of error above.

Expected behavior:

- copy_data() compatible with the new API.

NOTE:

most probably frozendict is used to represent context in the environment (rec.env.context) of the new API, but there is incompatible code with the frozendict context in the function copy_data(). it makes impossible to use copy_data() with the new API.

**Comment by intero-chz** [comment]
:+1:

**Comment by sylvainvanhoof** [comment]
:+1:

**Comment by Cedric-Pigeon** [comment]
:+1:

**Comment by Cedric-Pigeon** [comment]
@rco-odoo What is your opinion on this ?

**Comment by msteinfeld** [comment]
:+1:

**Comment by dhsl** [comment]
:+1:

**Comment by JonathanNEMRY** [comment]
any news about this issue?

**Comment by Cedric-Pigeon** [comment]
@beledouxdenis :+1: Great ! Thanks !

**Comment by tvibliani** [comment]
:+1:

**Comment by HugeOguh** [comment]
:+1: Thank you @beledouxdenis
