### ISSUE TITLE
[14.0] show_operations is overwritten on every settings change ignoring users preferences

### ISSUE THREAD

**Issue by cloudition** [odoo/odoo#73632]
This code overwrites the user defined value of "Show Detailed Operations" on each config change(independent of the app), because `set_values()` is called on every configuration (`res.config.settings`) change:

https://github.com/odoo/odoo/blob/eb5c4e9b8d32a10e460ac089794bf1ceb9b7b71a/addons/stock/models/res_config_settings.py#L98

**Comment by sswapnesh** [comment]
Duplicate of https://github.com/odoo/odoo/issues/51121
and also see https://github.com/odoo/odoo/issues/51121#issuecomment-627803667
