### ISSUE TITLE
How to get the session_id after login in odoo14

### ISSUE THREAD

**Issue by xiaoniu001** [odoo/odoo#73664]
I use http.request.session.authenticate() for user login, and then http.requests.session.sid to get the session_id, but this session_id cannot be authenticated。

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Comment by pumppi** [comment]
I have the same problem, session id is not same as in cookie.  I did try this, https://gist.github.com/hari4274/fc7ab11b849a88a4eb5631872c01cc4a but the session id is different then cookie. And when using json rpc with proxy it's not working.
