### ISSUE TITLE
[8.0] tree view inside a form view loads all records at once, instead of 80x chunks as in pure tree view

### ISSUE THREAD

**Issue by a0c** [odoo/odoo#7370]
#### Steps to reproduce

To illustrate, I'll use a Sale Order model, but a simple dummy model with a one2many field could also be created for quick testing the issue.
1) Generate SO with >30K lines. Or >50K to be sure.
2) Open this SO in form view -- it will take forever to load, as all >30K line will be loaded at once.
3) Now open the dedicated menu for Sale Order Lines -- this happens instantly, cos only first 80 lines are loaded.
#### Problem

Are there any fundamental limitations preventing the tree view inside a form view from loading lazily?

**Comment by Yenthe666** [comment]
Hi @a0c ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
