### ISSUE TITLE
Duplicated key 'label' in reconciliation_renderer.js (Odoo 14 Enterprise)

### ISSUE THREAD

**Issue by AlexPetul** [odoo/odoo#73736]
Impacted versions: 14 Enterprise

Steps to reproduce: reconciliation_renderer.js

Current behavior: duplicated key 'label' in source code

Expected behavior: remove duplicate 'label' in source code

Video/Screenshot link (optional):
<img width="912" alt="Screenshot 2021-07-14 at 19 37 18" src="https://user-images.githubusercontent.com/47738904/125659545-4ef62844-175f-4e21-9fef-241fc9b534a0.png">

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
Is this provoking any error?

**Comment by AlexPetul** [comment]
No sir, just wanted the code to be as clean as possible

**Comment by pedrobaeza** [comment]
You can make a pull request on master branch if both lines still continue, but this kind of changes doesn't apply to stable branches for not altering things that are not bugfixes.

Closing thus.
