### ISSUE TITLE
Bullet points are not correctly rendered when printing HTML fields in Qweb

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#7375]
**Bullet points css layout ignored on HTML fields**

Impacted versions:
- 8.0 and above

Steps to reproduce:
1. Create a custom HTML field (fields.html)
2. Add this field to the qweb report and let it render as HTML (<t t-raw="o.yourHtmlField"/>)
3. Create li items in the HTML field 
4. Print the report.
   Result:
   <img src="http://i.imgur.com/XfbNAaV.png" alt="Sample"/>

If you code the li items in Qweb they will work fine:

```
        <li>Item #1</li>
        <li>Item #2</li>
```

If you get them from an HTML field they will only be printed partially.

```
<t t-raw="o.yourHtmlField"/>
```

Current behavior:
- List items are partially printed when they are rendered from an HTML field

Expected behavior:
- Bullet points are fully printed

**Comment by Yenthe666** [comment]
Hmm guys (@jke-be or @odony  or @antonylesuisse ) this could be fixed (but its ugly) by adding some css to reset.min.css here:
https://github.com/odoo/odoo/blob/8.0/addons/report/static/src/css/reset.min.css#L56

Then add:
```
li{
    margin-left:10px;
}
```

This fixes it for fields that are HTML rendered. The problem is that this would also happen for non-HTML rendered fields and that is something we do not wish. Its just an idea, since I'd like to contribute in any way I can. :+1: 
While this is not a major bug it should be a rather easy fix for you guys and I can imagine that plenty of people see this happening.

**Comment by Yenthe666** [comment]
@sle-odoo any update on this one?

**Comment by Yenthe666** [comment]
@sle-odoo pinging you for another update 😉

**Comment by nhomar** [comment]
I confirm this is happening on v11.0 yet ping @sle-odoo and/or @Yenthe666

**Comment by Yenthe666** [comment]
Yup it never gotten much attention :( Nevertheless I do believe there are more pressing issues than the rendering of bullet points I guess? Whenever @sle-odoo got some time it would be neat to get fixed.

**Comment by nhomar** [comment]
I will help with a PR because it is really annoying... (we face this issue since a lot of time)

**Comment by Yenthe666** [comment]
That would be awesome! I never got time to dig deeper and fix it really.. Let me know if I can help in any way.

**Comment by JKE-be** [comment]
```diff
diff --git addons/report/static/src/css/reset.min.css addons/report/static/src/css/reset.min.css
index ee21ad7..97c0b78 100644
--- addons/report/static/src/css/reset.min.css
+++ addons/report/static/src/css/reset.min.css
@@ -48,6 +48,7 @@ ol {
 
 ul {
        list-style: disc;
+       padding-left: 40px;
 }
 
 ul ul {

```

Should fix it...

In html, you have the chrome user agent style that is applied: 
![image](https://user-images.githubusercontent.com/4848797/32985524-6beaf036-ccbd-11e7-9bad-a91a83cdf046.png)


Now, with this diff, that override user agent style with the same behaviour, and so, that will be also applied to the pdf.

**Comment by JKE-be** [comment]
any feedback? @nhomar @Yenthe666

**Comment by Yenthe666** [comment]
Not in the office this week. I'll try to make some test instance as soon as possible. Remind me again in like a week if you had no response. ;)

**Comment by Yenthe666** [comment]
@JKE-be seems to work fine.

**Comment by nhomar** [comment]
@Yenthe666 Yes for me too, this issue can be closed I think

**Comment by sanjaycoder123** [comment]
![screenshot from 2018-07-19 09-24-47](https://user-images.githubusercontent.com/34681222/42920726-d3695478-8b35-11e8-83cc-06618f80ce4c.png)
how to deal with this?????

**Comment by gdgellatly** [comment]
padding-left would seem the obvious fix.  Its a slightly annoying part of default reports padding is set to 0px, for both ol and ul so it actually renders off the page usually.  But realistically you nearly always need your own css anyway so it isn't a big deal to add.

**Comment by sanjaycoder123** [comment]
![screenshot from 2018-07-19 10-09-53](https://user-images.githubusercontent.com/34681222/42921884-eb589674-8b3b-11e8-9864-91bd992344ea.png)
this is my xml code for this above reports , i already added the padding , ly the test is moved except that bullet

**Comment by sanjaycoder123** [comment]
<div style="padding: 1em; text-overflow: ellipsis;">
 <span t-raw="l.product_id.description_sale"/>
</div>

This is the solution to print any html field in odoo qweb reports, now it working properly
