### ISSUE TITLE
[14.0][Question] How to expand list view (default) on default group by ?

### ISSUE THREAD

**Issue by newtratip** [odoo/odoo#73753]
**Impacted versions:**
14.0

**Steps to reproduce:**

1. Add expand="1" in group tag on search view
![Selection_341](https://user-images.githubusercontent.com/24691983/125757601-8127d736-cf17-4b36-ac7b-f8424f2d7537.png)

2. Add context 'search_default_group_partner_id': 1
![Selection_342](https://user-images.githubusercontent.com/24691983/125759237-a541c85b-7625-432f-83a2-bc73beadb9a1.png)

**Current behavior:**
When I go to the menu, default group by vendor, no expand list
![Selection_344](https://user-images.githubusercontent.com/24691983/125758787-a34eaec5-6991-438e-82c4-30c3e3d7f1dd.png)

**Expected behavior:**
I would like to expand list by default

I use expand="1" in group tag. Is this correct ? Anyone suggest me for this ?

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Anyways, `expand` is a deprecated attribute used on first versions of the web client.

Closing this by the reason above.
