### ISSUE TITLE
JsonRequest - original request not available

### ISSUE THREAD

**Issue by zbik2607** [odoo/odoo#7377]
In many cases, important is the order of the obtained json values. For example to verify hash function when communicate with payment acquirer. 

JsonRequest class now provides only the value of jsonrequest (after simplejson.loads).

Expected:

JsonRequest class provides the value before simplejson.loads.

**Comment by xmo-odoo** [comment]
Both JsonRequest and HttpRequest expose the original "raw" [werkzeug request object](http://werkzeug.pocoo.org/docs/0.10/wrappers/#werkzeug.wrappers.Request) as the `httprequest` attribute. This is actually inherited from `WebRequest`.

**Comment by zbik2607** [comment]
But after request = self.httprequest.stream.read() original request is unavailable. If no, how get it?

**Comment by xmo-odoo** [comment]
Ah the raw request body.

There's no way to get it via JSON requests no. The only way to access it is to use HttpRequest and perform a request [without a content type specified](http://werkzeug.pocoo.org/docs/0.10/wrappers/#werkzeug.wrappers.BaseRequest.want_form_data_parsed). This will disable FORM and FILES parsing and should let you read the raw stream.

**Comment by zbik2607** [comment]
Unfortunately,  such is communication protocol my payments acquirer :(. Small code correction in http.py solves the problem, after 
.... request = self.httprequest.stream.read()
+ self.raw_request = request

**Comment by xmo-odoo** [comment]
> Small code correction in http.py solves the problem, after 

1. Werkzeug already exposes this via `Request.get_data`.
2. that's not quite a *correction*, as `Request.get_data`'s docstring notes:

   > Usually it's a bad idea to call this method without checking the content length first as a client could send dozens of megabytes or more to cause memory problems on the server.

   it might be the behaviour you want for that specific endpoint, but I'm not sure it's something we should enable by default.

**Comment by zbik2607** [comment]
after .... stream.read(), get_data() is empty, correction after stream.read is probably safe.
Stream docstring notes:
<i>stream is properly guarded that you can’t accidentally read past the length of the input</i>

**Comment by zbik2607** [comment]
PS. This payment acquirrer (PayU) is the bigest in Poland (and provides services not only in Poland).

**Comment by xmo-odoo** [comment]
> after .... stream.read(), get_data() is empty, correction after stream.read is probably safe.

`get_data` would be used instead of `stream.read` not after it. Reading `stream` and caching its result is exactly what it does.

**Comment by zbik2607** [comment]
OK I understand, but now, in http.py JsonRequest execute stream.read(), and not store raw value!, in next step execute simplejson.loads(request) and this store in self.jsonrequest. How I get raw, with or without get_data?

**Comment by nafex** [comment]
Hi, I'm having exactly the same problem. Trying to implement PayPal Webhooks in Odoo but to validate the PayPal signature i need the raw request body. How can I get it without modifying the original Odoo source code?

**Comment by nafex** [comment]
@xmo-odoo should I submit a patch replacing `stream.read` with `get_data`?

**Comment by nafex** [comment]
or maybe Odoo could add something like:
```
self.jsonrequest = json.loads(request)
self.jsonrequest_raw = request  # ADDED LINE
```
