### ISSUE TITLE
[14.0] Sale.py - Value stored into wrong variable

### ISSUE THREAD

**Issue by Kacer89** [odoo/odoo#73771]
Impacted versions: 14.0

Module: Sale
Model: Sale

![Sale_var_issue](https://user-images.githubusercontent.com/61238785/125788400-9b085699-9917-4765-8f3c-0cfd9d98eff7.png)

Per Image I guess the 'dp_section' was wrongly named as it not used anywhere else.

Michael

**Comment by Yenthe666** [comment]
@agr-odoo seems to be introduced by you in https://github.com/odoo/odoo/commit/6532c6ba7acb2de53fc839d5a7c5d8b200716565. Can you check?

**Comment by Feyensv** [comment]
Fixed soon by #73834 ;)

**Comment by Yenthe666** [comment]
Fixed in https://github.com/odoo/odoo/commit/7bbf13d47b122d80fd16cb9db79be86c44be97b6
