### ISSUE TITLE
[fetchmail] Duplication of record when handled incoming message 

### ISSUE THREAD

**Issue by JulioSerna** [odoo/odoo#7380]
Impacted version:
* 8.0

Steps to reproduce:
* To create incoming mail server
* To set  **Create New Record = Task(project.task)**
* To create and send mail(e.g. From Gmail)
* To try to replicate that action ```fetch_mail``` is executed twice simultaneously

We replicated whit this [Gist](https://gist.github.com/JulioSerna/89b6707df1d5f19350b6)

Current behavior:
* Create the same record(project.task) twice

Expected behavior:
* Create only one record

I made video,
https://youtu.be/zNuTNe3X3BQ

**Comment by beledouxdenis** [comment]
Hello Julio,

We do not consider this as a bug.

This action is supposed to be called by a cron task, and you cannot run a same cron task twice simultaneously.

The `fetch now` button is just for testing purpose. This isn't expected to use it anywhere else then in the cron task or for testing purposes once your fetchmail server created.

If you really want this, you can customize the code to lock the ir._fetchmail_server line, and to prevent the use of this button on a locked ir.fetchmail_server. Nevertheless, this won't be done in standard.

Regards,
