### ISSUE TITLE
Translate description with static/description/index.html

### ISSUE THREAD

**Issue by alan-guzman** [odoo/odoo#7383]
Impacted version: 
* 8.0

Steps to produce:
* To create file index.html with my description ```mymodule/static/description/index.html```
* To use wizard export translation

Current behavior:
* File .po generated by wizard export translations does not contents description from index.html

Expected behavior:
* To be able translate contents from index.html on .po

**Comment by beledouxdenis** [comment]
These files are not expected to be translated, at least not at the moment.

It can nevertheless be regarded as a nice-to-have, as an improvement for the master branch. But this won't be added in a stable release, such as Odoo 8.0.

Regards,
