### ISSUE TITLE
[mail] default filter doens't work for Inbox and Archive menus

### ISSUE THREAD

**Issue by yelizariev** [odoo/odoo#7384]
**default filter doens't work for Inbox and Archive menus**

Impacted versions:
- 7.0
- 8.0

Steps to reproduce:
- make some search in Inbox (or in Arhive). E.g. "Content: asdf"
- save that search and tick "Use by default"
- Click on "Inbox" (or "Arhive") menu.

Current behavior:
- You see your filter name in search box, but filter is not applied and all messages are shown.

Expected behavior:
- Filter should be applied.

**Comment by yelizariev** [comment]
I guess that this commit https://github.com/odoo/odoo/commit/566d7dd3afc38efb2171e829b9aadaf7cd064852 by @Gorash is related to the issue, because the difference between To-do (where default filter works) and Inbox menus is that To-do action has defaults 

     search_default_message_unread: True
and 

    this.searchview.has_defaults 
returns true, while Inbox menu doesn't have.

**Comment by rafaelbn** [comment]
cc @pedrobaeza @antespi @Yajo

**Comment by rafaelbn** [comment]
@yelizariev it's much more effective if you make a PR to Odoo fixing it.
Also you can make a PR to https://github.com/OCA/OCB fixing the problem and have it solve it

**Comment by Yenthe666** [comment]
Hi @yelizariev ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

P.S: Yes PR's have a higher response rate too. 😉 

Regards,
Yenthe

**Comment by prakashjain** [comment]
We are  facing same issue in Version 9 Please let me know if any possible solutions.
default filter doens't work for Inbox and Archive menus

Impacted versions:

    7.0
    8.0

Steps to reproduce:

    make some search in Inbox (or in Arhive). E.g. "Content: asdf"
    save that search and tick "Use by default"
    Click on "Inbox" (or "Arhive") menu.

Current behavior:

    You see your filter name in search box, but filter is not applied and all messages are shown.

Expected behavior:

    Filter should be applied.

**Comment by yelizariev** [comment]
@prakashjain create new issue with proper description

**Comment by Yenthe666** [comment]
Indeed. Please do create a new bug report and we'll try to look into it as soon as possible.
