### ISSUE TITLE
Odoo POS Duplicate browser issue - orders missing

### ISSUE THREAD

**Issue by orchidinfosys** [odoo/odoo#7388]
Open POS session and it will set the number for the next order (eg 1) 

Then duplicate the browser (right click the browser tab and duplicate) next tab also start with same order number (her its 1)

Now you have two tab with same order receipt reference number and continue sale in both the tabs, Finally only one tab order will be saved in backend other tab order will be missed.

Moreover you will have two pos receipt with same order reference. 

![pos](https://cloud.githubusercontent.com/assets/2189864/8449850/02fb3a30-1fe6-11e5-8e13-f71ef878427c.png)

**Comment by ronozoro** [comment]
i have the same issue did you solve it ?

**Comment by lithint** [comment]
Hi rono,
that is fixed by keeping a value in  local storage and incremented on each
call to generateUniqueId() and our new code looks like as follows

        generateUniqueId: function() {
>                var odtoken_number = localStorage['odtoken_number'] || '0';
>                 if (odtoken_number == 100){
>                     odtoken_number = 0;
>                 }
>                var newId = parseInt(odtoken_number, 10) + 1;
>                localStorage['odtoken_number'] = newId;
>             function zero_pad(num,size){
>                 var s = ""+num;
>                 while (s.length < size) {
>                     s = "0" + s;
>                 }
>                 return s;
>             }
>             return zero_pad(this.pos.pos_session.id,5) +'-'+
>                    zero_pad(this.pos.pos_session.login_number,3) +'-'+
>                    zero_pad(localStorage['odtoken_number'],2) +'-'+
>                    zero_pad(this.sequence_number,4);
>         },
>


On Thu, Apr 21, 2016 at 4:15 AM, ronozoro <notifications@github.com> wrote:

> i have the same issue did you solve it ?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/odoo/odoo/issues/7388#issuecomment-212661566>
>



-- 
Thanks & Regards,

Lithin T
Software Engineer
Mob  : +971556712557(UAE)
Mail  : lithint.mail@gmail.com | Skype : lithint.skype

**Comment by orchidinfosys** [comment]
yes rono,
that is fixed by keeping a value in  local storage and incremented on each call to generateUniqueId()

our new code is
```

`
        generateUniqueId: function() {
               var odtoken_number = localStorage['odtoken_number'] || '0';
                if (odtoken_number == 100){
                    odtoken_number = 0;
                }
               var newId = parseInt(odtoken_number, 10) + 1;
               localStorage['odtoken_number'] = newId;
            function zero_pad(num,size){
                var s = ""+num;
                while (s.length < size) {
                    s = "0" + s;
                }
                return s;
            }
            return zero_pad(this.pos.pos_session.id,5) +'-'+
                   zero_pad(this.pos.pos_session.login_number,3) +'-'+
                   zero_pad(localStorage['odtoken_number'],2) +'-'+
                   zero_pad(this.sequence_number,4);
        },
`
```

**Comment by mart-e** [comment]
Hello,

In 9.0 you shouldn't have this issue anymore as the first tab session is closed when you open a second.
