### ISSUE TITLE
expensing an inventory product 

### ISSUE THREAD

**Issue by AmrAlbadri** [odoo/odoo#73933]
i have an inventory stock i have given free samples to different clients, so its not sales,

i want to expense these products in accounting as promotion expense

the question here is how to decrease the inventory with the product and make it hit the expense account, not the COGS?

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
