### ISSUE TITLE
Odoo 14 Enterprise: missing difference in accounting dashboard

### ISSUE THREAD

**Issue by HoloborodkoBohdan** [odoo/odoo#73967]
Impacted versions: 14.0

In version 13 function **get_journal_dashboard_datas** returns dict with item called difference:
https://github.com/odoo/odoo/blob/13.0/addons/account/models/account_journal_dashboard.py#L289:L311

In version 14 this item missed, but template for difference still exists in account_reports app (account_journal_dashboard_view.xml)

Is it possible to add difference in version 14? There are only 2 lines of code: https://gist.github.com/HoloborodkoBohdan/62a12496f633889d241f2be0afe2bc56

**Comment by pedrobaeza** [comment]
Sorry, this is not an issue per se, but missing functionality that you need for whatever. You can rescue such code in your custom module if you need it.

Closing thus.
