### ISSUE TITLE
Java openERP API for Odoo should have Maven Central support

### ISSUE THREAD

**Issue by ZMobile** [odoo/odoo#74000]
Subject: [https://github.com/odoo-java/odoo-java-api/](https://github.com/odoo-java/odoo-java-api/
)

Right now this repo seems to be the best, most active and dedicated open source project to interface Java efficiently with Odoo's External API via utilizing Apache XMLRPC. As stated in the project's description: "The API reduces the amount of boiler plate code needed to communicate with Odoo by doing error checking and type conversions."

As a Java software engineer, I'd like to be able to use this API ideally by accessing it from a remote maven central repository. If I can do this, I'll have the easiest time interacting with Odoo projects in Java.

Why isn't it already uploaded to the central repo? Upon investigation, it appears the project's most active contributor, @flotho, could use some support in uploading it to maven central as it would be a process he is not familiar with. A process which I have to admit I'm not currently familiar with either.

(Src: [https://github.com/odoo-java/odoo-java-api/issues/11](https://github.com/odoo-java/odoo-java-api/issues/11))

I'm putting this issue here in hopes that it might gain some traction with a few of those here who are also a part of the Java open source development community, and would like to help improve Odoo's overall accessibility from Java. I believe this is a project worth supporting.

**Comment by xmo-odoo** [comment]
This has nothing to do with Odoo itself, or with the company.
