### ISSUE TITLE
Remaining hours in task does not moved to "0" when status done

### ISSUE THREAD

**Issue by bene1505** [odoo/odoo#7401]
Hi, 

We noticed that in version 7.0 when a task was "done" , the working time progress was set to "100%" and the remaining hours was set back to "0". In version 8.0, the working time progress has the same behaviour than in version 7.0  but not the remaining hours. Could you please adapt?

 	 	 	 
![version 7 before](https://cloud.githubusercontent.com/assets/12964307/8456759/c26b41a4-200d-11e5-9a08-086186a3b4d9.png)
![version 7after](https://cloud.githubusercontent.com/assets/12964307/8456763/c49f7206-200d-11e5-8395-ff982e09e316.png)
![version 8 after](https://cloud.githubusercontent.com/assets/12964307/8456765/c7b4ac04-200d-11e5-8ee6-e3875828380a.png)
![version 8 before](https://cloud.githubusercontent.com/assets/12964307/8456767/cc587786-200d-11e5-89f8-c438803a3238.png)

**Comment by Alex-Duan** [comment]
+1

**Comment by beledouxdenis** [comment]
Dear,
This is an expected change between the Odoo 7.0 and the Odoo 8.0: We do not want this field to not be reset anymore.

We want to know with how many hours in advance a task has be finished

This behavior can nevertheless be done easily with an automated action:
![automated actions odoo](https://cloud.githubusercontent.com/assets/5822488/8497963/0a67dd26-2182-11e5-8b8f-490a0f398bd5.png)
![automated actions odoo_2](https://cloud.githubusercontent.com/assets/5822488/8497965/0e9368a2-2182-11e5-9e22-103682e77ab7.png)
![automated actions odoo_3](https://cloud.githubusercontent.com/assets/5822488/8497967/10052248-2182-11e5-9bf1-21960899f3ea.png)
![automated actions odoo_4](https://cloud.githubusercontent.com/assets/5822488/8497968/11bc8824-2182-11e5-885d-aa9ffb8057bc.png)
