### ISSUE TITLE
Can't print from kitchen printer

### ISSUE THREAD

**Issue by ziglootor** [odoo/odoo#7407]
Hello everyone,

I'm using a Bematech MP4200 as a kitchen printer but I can't seem to make it work. Everything works fine when I print from cups but the odoo server log tell me that the printer is not detected. The printer is compatible ESC/POS. 

Anyone have a clue on how I can try to fix that or point me in some direction?

**Comment by pedrobaeza** [comment]
This seems to be a HW problem related, but not Odoo one, so I close it.
