### ISSUE TITLE
[BUG] for hierarchy BoM, the child semi-product scheduled date is wrong.

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#7423]
let say that there have 3 layer hierarchy BoM structure..
if we need to produce the final product, it should produce those two semi-product first.
Odoo can compute the bill of materials, but the scheduled date is wrong.
now the schedule date is  the plan_date of final product minus  both global MRP lead time and product MRP lead time, this is fine.  but it forgot that the time need to be minus, is the time used to produce those semi-product..

for BoM structure.
![image](https://cloud.githubusercontent.com/assets/1404460/8477131/637b89b8-20fa-11e5-8c5d-5d75c6420f9e.png)

when confirm the MO, it should create the related 
![image](https://cloud.githubusercontent.com/assets/1404460/8477176/c6a684e8-20fa-11e5-9e4f-c3f314c801cc.png)

but the time schedule is totally wrong,
![image](https://cloud.githubusercontent.com/assets/1404460/8477219/1902024e-20fb-11e5-9170-794a558b52da.png)

any comments or improvement should be appreciated

**Comment by pedrobaeza** [comment]
The BoM hierarchy has been removed in latest version and 8.0 is no longer supported, so I'm afraid I have to close this.
