### ISSUE TITLE
[8.0] computed many2many creates side effect

### ISSUE THREAD

**Issue by oihane** [odoo/odoo#7426]
Not sure if it is a bug, or I did not manage to do it correctly. The thing is that we are trying to do a computed many2many (code available: https://github.com/odoomrp/odoomrp-wip/pull/862).
It calculates the taxes of a stock.picking coming from a sale.order, it calculates correctly but, if you change any line quantity it fails.

```
TypeError: <openerp.models.NewId object at 0x7ff2280bc850> is not JSON serializable
```

I debugged and found that it does this one:

```
'taxes': [(3, <openerp.models.NewId object at 0x7fba48c96790>),
          (3, <openerp.models.NewId object at 0x7fba48c969d0>),
          (3, <openerp.models.NewId object at 0x7fba48c96a50>),
          (0, 0, {'amount': 176.4, 'base': 4410.0, 'name': u'IVA 4%'}),
          (0, 0, {'amount': 85.05, 'base': 405.0, 'name': u'IVA 21%'}),
          (0, 0, {'amount': 7.2, 'base': 72.0, 'name': u'IVA 10%'})]
```

I do not know why it is trying to unlink something that it seems not to exist.

I would appreciate any help or any explanation because I can't continue. Thanks in advance
@rco-odoo @pedrobaeza told me to change the previous one2many for this many2many.

**Comment by yk2kus** [comment]
I doubt if you can have m2m computed field? I remember m2m was not supported as function field.

**Comment by oihane** [comment]
@yk2kus is something @rco-odoo told about the new API

**Comment by Yenthe666** [comment]
Hi @oihane ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
I don't believe this is possible by default.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).

Regards,
Yenthe
