### ISSUE TITLE
Forum tags - incompatible field names in relation table

### ISSUE THREAD

**Issue by zbik2607** [odoo/odoo#7427]
class Post(osv.Model):
...
'tag_ids': fields.many2many('forum.tag', 'forum_tag_rel', <b>'forum_id', 'forum_tag_id',</b> 'Tags'),

class Tags(osv.Model):
...
'post_ids': fields.many2many('forum.post', 'forum_tag_rel', <b>'tag_id', 'post_id'</b>, 'Posts'),

Issue related to: <a href="https://github.com/odoo/odoo/issues/6770">#6770</a>

**Comment by Yenthe666** [comment]
Hi @zbik2607,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
