### ISSUE TITLE
Default Account in Payment doesn't exclude Deprecated Accounts

### ISSUE THREAD

**Issue by NathanQj** [odoo/odoo#74280]
https://github.com/odoo/odoo/blob/87f6a2fd3f86d13ebe320c058336d752362b8f44/addons/account/models/account_payment.py#L390-L413

Default Account in Payment doesn't exclude Deprecated Accounts and only selects the first matching Account in account.account regardless of if it should or not.

**Comment by sswapnesh** [comment]
Added Fix on https://github.com/odoo/odoo/pull/74386
