### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'bool' and 'relativedelta'

### ISSUE THREAD

**Issue by dpsholtes** [odoo/odoo#74287]
Impacted versions: 13.0

Steps to reproduce: Manufacturing -> Operations -> Manufacturing Orders. Create a new Manufacturing Order. Remove the default value for the Scheduled Date.  Edit any other field while the Scheduled Date is not set.

Current behavior:  TypeError is thrown when editing another field while Scheduled Date is not set

Expected behavior: Edit other fields without Scheduled Date set

Video/Screenshot link (optional):
![Screenshot from 2021-07-26 15-01-05](https://user-images.githubusercontent.com/57339458/127055815-ddecc865-4e64-4714-99af-b1c40c42b837.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
Isn't that date a required field?

**Comment by dpsholtes** [comment]
> Isn't that date a required field?

Correct, it is a required field. The error is thrown while the user is still in edit mode.

**Comment by pedrobaeza** [comment]
Well, being a required field, it's a bit convoluted to force such empty data, but I let Odoo to decide if this can be considered a bug.

**Comment by sswapnesh** [comment]
Added Fix https://github.com/odoo/odoo/pull/74337

**Comment by sswapnesh** [comment]
This has been fixed in https://github.com/odoo/odoo/commit/8594004469f440aedfddbecf97c55fd24c3a2e60
