### ISSUE TITLE
when a product is out of stuck, the "add to card button" is visible to user!

### ISSUE THREAD

**Issue by Parsia** [odoo/odoo#74298]
Impacted versions: 13, 14

Steps to reproduce:

Current behavior: When a product is out of stuck, the "add to card button" is visible to the customer (in /shop address). User thinks that its available and adds the product to card, then the system shows error in card! this wastes users time alot...!

Expected behavior: not to show "add to card button". show "out of stuck" instead.

**Comment by pedrobaeza** [comment]
Sorry, this is the expected behavior, as when the page is rendered, something can be with or without stock, so only adding it to cart can lead to check the exact availability.

Closing as expected behavior.

**Comment by Parsia** [comment]
Thank you! But may I have a request? when the product is out of stuck, the "add to card button" in "product details page" is not active. May you do this in "/shop" and "product tabs (such as top products)?" ("add to card" is shown as hover and its status is active in /shop address)
![2021-07-31 10_26_54-](https://user-images.githubusercontent.com/52624519/127730431-cb2fea5c-69f7-4d1a-8612-d054a57870dd.png)
![2021-07-31 10_28_13-](https://user-images.githubusercontent.com/52624519/127730433-11236bf0-1b8c-4d97-999b-112ca3c3a4ba.png)

**Comment by pedrobaeza** [comment]
In that case, the request is done only once. Doing it on the list will mean to do as many requests as products shown, being not performant.
