### ISSUE TITLE
Task Import failing to import Hours

### ISSUE THREAD

**Issue by The-Bozo** [odoo/odoo#7432]
Both fields date_start and date_end fail to import the hours specified in the CSV file.
Instead all dates are imported with the hour forced to: 17:00:00

**Comment by andreparames** [comment]
I tried it in the runbot, worked fine. Can you provide an example of a CSV file? What's your Odoo version?

**Comment by The-Bozo** [comment]
External ID,stage_id/id,name,planned_hours,remaining_hours,date_start,date_end,Parent Tasks / External ID,notes
2001,__export__.project_task_type_17,Project Management,8,8,2015-07-13 09:00:00,2015-07-13 17:00:00,,
2002,__export__.project_task_type_20,Hardware Configuration,8,8,2015-07-13 09:00:00,2015-07-13 17:00:00,,
2003,__export__.project_task_type_20,"Dependent Software (64-bit OS confirmation, etc.)",8,8,2015-07-14 09:00:00,2015-07-14 17:00:00,2002,
2004,__export__.project_task_type_18,Export Custodian and Target Information,8,8,2015-07-15 09:00:00,2015-07-15 17:00:00,2003,
2005,__export__.project_task_type_18,Export Global Criteria as required,4,4,2015-07-16 09:00:00,2015-07-16 13:00:00,2004,
2006,__export__.project_task_type_19,Install SAFE,0.8,0.8,2015-07-16 13:00:00,2015-07-16 13:48:00,2005,Physical Machine 32 GB RAM
2007,__export__.project_task_type_19,Install ECC Web Services (v5.8),1.6,1.6,2015-07-16 13:48:00,2015-07-16 15:24:00,2006,GSI Applicance (Combined with MSSQL)
2008,__export__.project_task_type_19,Install MSSQL 2012,1.6,1.6,2015-07-16 15:24:00,2015-07-16 17:00:00,2007,GSI Applicance (Combined with ECC WEB)
2009,__export__.project_task_type_19,Install ECC Desktop,2.4,2.4,2015-07-17 09:00:00,2015-07-17 11:24:00,2008,GSI Appliance (Combine with ExAS)
2010,__export__.project_task_type_19,Install EnCase Examiner Service,1.6,1.6,2015-07-17 11:24:00,2015-07-17 13:00:00,2009,GSI Appliance
2011,__export__.project_task_type_19,Install and Configure Sharepoint Connector,4,4,2015-07-17 13:00:00,2015-07-17 17:00:00,2010,
2012,__export__.project_task_type_19,Install and Configure EITT Version 1.18,4,4,2015-07-20 09:00:00,2015-07-20 13:00:00,2011,Combine with SAFE Server
2013,__export__.project_task_type_19,Install and configure current LV Sands File Shares,1.6,1.6,2015-07-20 13:00:00,2015-07-20 14:36:00,2012,
2014,__export__.project_task_type_19,System Testing,4.8,4.8,2015-07-20 14:36:00,2015-07-20 19:24:00,2013,
2015,__export__.project_task_type_19,Confirm EnCase Issues are addressed (IP scanning and IP range scan),1.6,1.6,2015-07-21 09:00:00,2015-07-21 10:36:00,2014,
2016,__export__.project_task_type_19,Document installation and configuration steps,8,8,2015-07-21 10:36:00,2015-07-21 18:36:00,2015,


Version is: 8.0-20150702
Attached is the screenshot of them imported, you can see that no minutes for starting or endeng dates import.
![imported](https://cloud.githubusercontent.com/assets/10067706/8662775/35f6a690-2978-11e5-8f4f-f28299b3f3e1.jpg)

**Comment by andreparames** [comment]
@The-Bozo please add two spaces before each line of the CSV, so that the Github editor treats it as code instead of Markdown syntax.

**Comment by The-Bozo** [comment]
As far as I know no community addons are installed related to Project, what would be the best way to check?

I did notice that in Project Management that the following options are selected, would these effect the ability to import correctly?

![projectmanagement](https://cloud.githubusercontent.com/assets/10067706/8684905/e8432d66-2a2f-11e5-9027-9331ea5237e9.jpg)

**Comment by andreparames** [comment]
Frankly, I couldn't say, maybe try disabling them.

**Comment by The-Bozo** [comment]
Here are the modules installed:

Module Name | Technical Name | Author | Latest Version | Status
----------- | -------------- | ------ | -------------- | ------
Sales Management | sale | OpenERP SA | 8.0.1.0 | Installed
Instant Messaging | im_chat | OpenERP SA | 8.0.1.0 | Installed
Products & Pricelists | product | OpenERP SA | 8.0.1.1 | Installed
Collaborative Pads | pad | OpenERP SA | 8.0.2.0 | Installed
Initial Setup Tools | base_setup | OpenERP SA | 8.0.1.0 | Installed
Project Management | project | OpenERP SA | 8.0.1.1 | Installed
Sales Teams | sales_team | OpenERP SA | 8.0.1.0 | Installed
WMS Accounting | stock_account | OpenERP SA | 8.0.1.1 | Installed
Procurements | procurement | OpenERP SA | 8.0.1.0 | Installed
Purchase Management | purchase | OpenERP SA | 8.0.1.1 | Installed
Payment Acquirer | payment | OpenERP SA | 8.0.1.0 | Installed
Web Calendar | web_calendar | "OpenERP SA |  Valentino Lab (Kalysto)" | 8.0.2.0 | Installed
Portal Issue | portal_project_issue | OpenERP SA | 8.0.0.1 | Installed
Portal Stock | portal_stock | OpenERP SA | 8.0.0.1 | Installed
Base | base | OpenERP SA | 8.0.1.3 | Installed
Marketing | marketing | OpenERP SA | 8.0.1.1 | Installed
OpenERP Web Diagram | web_diagram |  | 8.0.2.0 | Installed
Sparkline Widget for Kanban | web_kanban_sparkline |  | 8.0.1.0 | Installed
Contracts Management | account_analytic_analysis | Camptocamp / Odoo | 8.0.1.1 | Installed
Issue Tracking | project_issue | OpenERP SA | 8.0.1.0 | Installed
Warehouse Management | stock | OpenERP SA | 8.0.1.1 | Installed
Transfer Payment Acquirer | payment_transfer | OpenERP SA | 8.0.1.0 | Installed
Bill Time on Tasks | project_timesheet | OpenERP SA | 8.0.1.0 | Installed
Invoice on Timesheets | hr_timesheet_invoice | OpenERP SA | 8.0.1.0 | Installed
Decimal Precision Configuration | decimal_precision | OpenERP SA | 8.0.0.1 | Installed
Resource | resource | OpenERP SA | 8.0.1.1 | Installed
Lunch Orders | lunch | OpenERP SA | 8.0.0.2 | Installed
Sales and Warehouse Management | sale_stock | OpenERP SA | 8.0.1.0 | Installed
Portal Sale | portal_sale | OpenERP SA | 8.0.0.1 | Installed
Online Billing | account_voucher | OpenERP SA | 8.0.1.0 | Installed
Employee Appraisals | hr_evaluation | OpenERP SA | 8.0.0.1 | Installed
Website Report | website_report | OpenERP SA | 8.0.1.0 | Installed
Website Mail | website_mail | OpenERP SA | 8.0.0.1 | Installed
Survey | survey | OpenERP SA | 8.0.2.0 | Installed
Website Builder | website | OpenERP SA | 8.0.1.0 | Installed
Leave Management | hr_holidays | OpenERP SA | 8.0.1.5 | Installed
Calendar | calendar | OpenERP SA | 8.0.1.0 | Installed
Automated Action Rules | base_action_rule | OpenERP SA | 8.0.1.0 | Installed
Timesheets | hr_timesheet_sheet | OpenERP SA | 8.0.1.0 | Installed
Time Tracking | hr_timesheet | OpenERP SA | 8.0.1.0 | Installed
Attendances | hr_attendance | OpenERP SA | 8.0.1.1 | Installed
Employee Directory | hr | OpenERP SA | 8.0.1.1 | Installed
United States - Chart of accounts | l10n_us | OpenERP SA | 8.0.1.1 | Installed
Anglo-Saxon Accounting | account_anglo_saxon | "OpenERP SA, Veritos" | 8.0.1.2 | Installed
Template of Charts of Accounts | account_chart | OpenERP SA | 8.0.1.1 | Installed
eInvoicing | account | OpenERP SA | 8.0.1.1 | Installed
Electronic Data Interchange (EDI) | edi | OpenERP SA | 8.0.1.0 | Installed
Portal Project | portal_project | OpenERP SA | 8.0.0.1 | Installed
Pad on tasks | pad_project | OpenERP SA | 8.0.1.0 | Installed
Analytic Accounting | analytic | OpenERP SA | 8.0.1.1 | Installed
Portal | portal | OpenERP SA | 8.0.1.0 | Installed
Signup | auth_signup | OpenERP SA | 8.0.1.0 | Installed
Share any Document | share | OpenERP SA | 8.0.2.0 | Installed
Email Gateway | fetchmail | OpenERP SA | 8.0.1.0 | Installed
Email Templates | email_template | OpenERP SA | 8.0.1.1 | Installed
Social Network | mail | OpenERP SA | 8.0.1.0 | Installed
Base Kanban | web_kanban |  | 8.0.2.0 | Installed
View Editor | web_view_editor |  | 8.0.2.0 | Installed
IM Bus | bus | OpenERP SA | 8.0.1.0 | Installed
Tests | web_tests |  | 8.0.2.0 | Installed
Password Encryption | auth_crypt | "['OpenERP SA', 'FS3']" | 8.0.2.0 | Installed
Knowledge Management System | knowledge | OpenERP SA | 8.0.1.0 | Installed
Dashboards | board | OpenERP SA | 8.0.1.0 | Installed
Gauge Widget for Kanban | web_kanban_gauge |  | 8.0.1.0 | Installed
Graph Views | web_graph |  | 8.0.3.0 | Installed
Web Gantt | web_gantt |  | 8.0.2.0 | Installed
Report | report | OpenERP SA | 8.0.1.0 | Installed
Base import | base_import | OpenERP SA | 8.0.1.0 | Installed
Web | web |  | 8.0.1.0 | Installed

**Comment by The-Bozo** [comment]
Disabling manage time made no difference in the import, all entries still import with hour 17:00:00

**Comment by Yenthe666** [comment]
Hi @The-Bozo,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
