### ISSUE TITLE
"addons\web\static\lib\fullcalendar\core\main.js" ScrollComponent.prototype.setHeight

### ISSUE THREAD

**Issue by rainbow-studio-solution** [odoo/odoo#74344]
Impacted versions:14.0
In the file "addons\web\static\lib\fullcalendar\core\main.js" 

**When developing a web theme, it was found that the calendar could not display the height normally.**

After I tried the following modifications,

The height of the element class named 'fc-scroller fc-time-grid-container' in the calendar can be displayed normally.

> CODE:
```
ScrollComponent.prototype.setHeight = function (height) {
         applyStyleProp(this.el, 'height', height);
 };
```
> modified to
```
ScrollComponent.prototype.setHeight = function (height) {
    if (height == 0) {
        applyStyleProp(this.el, 'height', "auto");
    } else {
        applyStyleProp(this.el, 'height', height);
    }
};
```

I don't know if this has any other impact. I hope you can adopt it.

**Comment by pedrobaeza** [comment]
Sorry, but this is not an error with standard code, and it's not clear the steps to reproduce the problem and if it's provoked by your custom code.

**Comment by vava-odoo** [comment]
@rainbow-studio-solution Feel free to re-open the issue if you have more information to provide
