### ISSUE TITLE
[website_event_meet] Return from publicWidget with incorrect names

### ISSUE THREAD

**Issue by gaso** [odoo/odoo#74392]
Impacted versions: 14
Steps to reproduce: [view source code](https://github.com/odoo/odoo/search?q=websiteEventMeetingRoom)

I was checking the operation of website_event_meet and I find that website_event_meeting_room.js and website_event_create_meeting_room_button.js return publicWidget.registry.websiteEventMeetingRoom. Should website_event_create_meeting_room_button.js not return publicWidget.registry.websiteEventCreateMeetingRoom ?.

![website_event_meet](https://user-images.githubusercontent.com/1509489/127412679-61e18383-0815-4c8c-9a65-f7dfe5cc7a32.PNG)

It's my first bug report, don't be cruel

**Comment by pedrobaeza** [comment]
You can do a PR changing that.

**Comment by gaso** [comment]
> You can do a PR changing that.
Can you please guide me ?

**Comment by pedrobaeza** [comment]
Continuing on #74446
