### ISSUE TITLE
[8.0]bug on excel exportation when the field is empty

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#7441]
Hello Odoo,

When I update to the newest code on Odoo in the beginning of July,
I found a bug when I try to import with excel type.

The bug is:
1.  Try to import with excel type
2.  When the field is empty, the value become False on the excel

The expected behavior:
1.  It should be just blank

You can test it on runbot because the behavior is the same.

**Comment by Yenthe666** [comment]
Hi @falinwa,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
