### ISSUE TITLE
[8.0]JS-QWEB doesnt support conditional logical for in array

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#7442]
Hello Odoo,

on JS-QWEB, I try to make a logic conditional with code something like this:
t-if="a in [1,2,3,5]"

but this code will not work and it will have an error on the system.

The expected behavior:
it should support for that kind of condition. for "in" and "not in"

Thank You.

**Comment by xmo-odoo** [comment]
> it should support for that kind of condition. for "in" and "not in"

QWeb-JS uses javascript expressions. `item in array` is not a javascript expression.

To perform that check, use [Array#indexOf](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf) or [_.contains](http://underscorejs.org/#contains).
