### ISSUE TITLE
Invalid field error while creating app using studio

### ISSUE THREAD

**Issue by niyasraphy** [odoo/odoo#74472]
Impacted versions: Master

Steps to reproduce: Create a new app, from the "Suggested features for your new model", choose "Chatter
Send messages, log notes and schedule activities" and click and create the app. Once the app is ready and trying to create a new record in the model it throws the error.

Current behavior: Getting error.

Expected behavior: Have to create the record.

Video/Screenshot link (optional):

https://user-images.githubusercontent.com/27989791/127594427-27817701-d810-4f87-a730-761cf3bb9474.mp4

**Comment by pedrobaeza** [comment]
As this is something of enterprise, please report it instead on odoo.com/help.

**Comment by niyasraphy** [comment]
@pedrobaeza okay will do.

**Comment by Yenthe666** [comment]
erm it is against master. Too soon :)
