### ISSUE TITLE
When i try to open session in pos V13 enterprise after installing module have js files loading stopped 

### ISSUE THREAD

**Issue by Abdul-rahmanMohamed** [odoo/odoo#74521]
![Screenshot from 2021-07-31 03-24-05](https://user-images.githubusercontent.com/46048624/127724415-39cc7210-73c7-4100-8a56-65ccb5e0b49f.png)

**Comment by Abdul-rahmanMohamed** [comment]
I 'm trying to open session on localhost

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/13.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).

**Comment by Abdul-rahmanMohamed** [comment]
this is custom module un on server I want to run it on local
