### ISSUE TITLE
Problem duplicating a project

### ISSUE THREAD

**Issue by adrianbeloqui** [odoo/odoo#7455]
As I was trying to duplicate a project I found a simple mistake in the code of the module "project" in the "project.py" in the line 350. The original problem is that it is sending 5 parameters to the method "write" instead of 6.

The original code is:

                 'name': task.name}
            map_task_id[task.id] =  task_obj.copy(cr, uid, task.id, defaults, context=context)
        self.write(cr, uid, [new_project_id], {'tasks':[(6,0, map_task_id.values())]})
        task_obj.duplicate_task(cr, uid, map_task_id, context=context)
        return True

And I fixed it by adding:

                 'name': task.name}
            map_task_id[task.id] =  task_obj.copy(cr, uid, task.id, defaults, context=context)
        self.write(cr, uid, [new_project_id], {'tasks':[(6,0, map_task_id.values())]}, context=context)
        task_obj.duplicate_task(cr, uid, map_task_id, context=context)
        return True

**Comment by jaredkipe** [comment]
I see that this is unchanged in 9.0 right now, however I can duplicate projects without any issues.

**Comment by Yenthe666** [comment]
Hi @andrius-preimantas,

Thanks a lot for your report. I've just tested this on the latest Odoo 8 and Odoo 9 and I can no longer reproduce this issue.
The copying of projects works fine out of the box on both Odoo versions now.

Regards,
Yenthe
