### ISSUE TITLE
Issue with Aeroo in RedHat OS

### ISSUE THREAD

**Issue by pcordova-sci** [odoo/odoo#7456]
We were able to install aeroolib in Redhat but when installing the module, there is error message that aeroolib is not installed. Is there solution to this issue?

**Comment by lukebranch** [comment]
@pcordova-sci ,

I think this question belongs over on the Aeroo Reports github issues:

https://github.com/aeroo/aeroolib/issues

I'd recommend closing this issue and creating the issue over there. Aeroo Reports is a community project built by Alistek, and therefore you will be better off asking the question in the repository for that project.

**Comment by pcordova-sci** [comment]
@lukebranch , 

I have created issue https://github.com/aeroo/aeroolib/issues/3 as per your recommendation.

**Comment by lukebranch** [comment]
@pcordova-sci ,

Thanks. I recommend you close this issue report as it's not directly related to Odoo core, but rather to a community-built module. It is unlikely that Odoo SA will consider this issue report for that reason.

I'll continue discussion with you on the other issue thread.

**Comment by pcordova-sci** [comment]
Closing issue log and will continue issue in log aeroo/aeroolib#3 .
