### ISSUE TITLE
Processing of payroll in human resources taking too much time

### ISSUE THREAD

**Issue by pcordova-sci** [odoo/odoo#7457]
We experienced processing 800+ contracts to take 2 hours to process. Is there a way to enhance the processing time?

**Comment by pedrobaeza** [comment]
I'm afraid this can be a normal time for that volume and depending on the type of calculations. Of course, everything can be optimized, but this is not something feasible for a stable version, and not in the top of the priorities IMO.

I close this issue in a triage operation.
