### ISSUE TITLE
Field ID can not be ordered in view tree

### ISSUE THREAD

**Issue by JulioSerna** [odoo/odoo#7459]
Impacted Version:
* 8.0

Steps to reproduce:
* To edit any tree view
* To add field ```id```
* Click in column ```ID``` in tree view

Current Behavior:
* It can not ordered by ``` ID ``` 

Expected Behavior:

* To be able order by ``` ID ```

I made video,
https://youtu.be/CupGv3nEEH8

**Comment by nle-odoo** [comment]
Hello, 


It should be solved in 8.0 with commit 0920c2fae06.

Thanks for reporting it.
