### ISSUE TITLE
Asset Management depreciation error in first period

### ISSUE THREAD

**Issue by AndreyPo** [odoo/odoo#7462]
hi 
have an issue with the depreciation calculation for first period with asset management app for Odoo. Trying to record an asset of a value of 12509.79 with a useful life of 18 months to 0 salvage. Set acquisition date as June 1st this year. On the depreciation board click the "compute" button and get 405.57 as depreciation for June and 694.99 thereafter. Whereas it should be 694.99 for June as well. Would appreciate any advice on how to fix this or the logic behind the calculation.

thanks
Andrey

**Comment by pedrobaeza** [comment]
You are not indicating the rest of the parameters, so it's difficult to say. Any way, this is very old, so I triage this, sorry.
