### ISSUE TITLE
datepicker selection is ignored after the first value is taken

### ISSUE THREAD

**Issue by osvalr** [odoo/odoo#7463]
Impacted versions:

 - 8.0

Steps to reproduce:

 1. Go to Project > Tasks
 2. Create a new task
 3. Go down and click on "Add an item" in the Work summary
 5. Open the datepicker in the Date field
 6. Select a date from past.
 7. Check if datetime field value was updated with the selected date.
 8. Select another date from past.
 9. Check again if datetime field value was updated with the selected date.
  

Current behavior:

 - Selected Date : 07/04/2015 21:30:00
 - Field Value   : 07/04/2015 21:30:00
 
 - Selected Date : 07/03/2015 21:30:00
 - Field Value   : 07/04/2015 21:30:00

Expected behavior:

 - Selected Date : 07/04/2015 21:30:00
 - Field Value   : 07/04/2015 21:30:00
 
 - Selected Date : 07/03/2015 21:30:00
 - Field Value   : 07/03/2015 21:30:00

For this test I was using
 - Odoo v8.0 (latest version) at runbot instance
 - Google Chrome v43.0.2357.81 (64-bit)
 - Ubuntu 14.04 (64-bit)

Video demonstration for the issue https://drive.google.com/open?id=0BzqRx_KjnyMQOVNaOHZha1A1MjA

**Comment by falinwa** [comment]
I confirm this bug happen to me too.
