### ISSUE TITLE
[All] Button's actions can be executed multiple times when using the confirmation pop-up

### ISSUE THREAD

**Issue by florian-dacosta** [odoo/odoo#74647]
Impacted versions:

at least 8 and 14 but probably all versions from 7 to 14.

Steps to reproduce:

Click on any button with `confirm` attribute in its xml definition. Then double click on the button "Ok" of the confirmation pop-up.

For example in version 14 : install the module `mass_mailing`. Create a mailing and click on the button "Send" (`action_put_in_queue`).
The confirmation screen appear and you can click twice (quickly) on the button "Ok"

Current behavior:

The button is executed twice. You can click multiple times on the confirmation button because there is a big delay before Odoo show the loading screen.
It is easier to see the problem  if the action last at least 2/3 sec (adding a `time.sleep(3)` for instance. The Ok button is clickable during at least 3 seconds before the Odoo loading screen appear and block the possibility to click on it.
Since it is way faster on a normal button, the user may think the click had no effect and click again.
Of course, the present example, does not really have any bad impact because the button only make a simple write.
But we could have button creating a record and then we would have multiple records created. or sending a mail, etc..

Expected behavior:

It should not be possible to click multiple times on the confirmation button. 
Like it is not possible for classic Odoo button (without the confirm attribute in the xml definition)

**Comment by grey27** [comment]
Is there any plan to solve this problem？

**Comment by BT-cjimeno** [comment]
We recently had problems related to this issue involving the sending of payments to the bank from the account.payment.register wizard and some customizations that we did to it to be able to send them directly to the bank.

As you can imagine, it was not pleasant to see two exact same payments for the same invoice in the bank.

We ended up solving it our way, but any kind of official solution to this issue would be really appreciated.

**Comment by BT-rmartin** [comment]
@aab-odoo Please, take a look as discussed. Thanks!

**Comment by aab-odoo** [comment]
Hello. This issue is fixed by https://github.com/odoo/odoo/pull/103202 and https://github.com/odoo/odoo/pull/103180

**Comment by BT-rmartin** [comment]
@aab-odoo Thanks a lot!! Super cool that you did fix this
