### ISSUE TITLE
How to setup quality control location for manufactured products with auto generated draft Internal Move from Quality Control -> Stock?

### ISSUE THREAD

**Issue by aldennis** [odoo/odoo#7469]
The default warehouse setup only has options for both incoming shipment and outgoing shippings. The requirement was to produce the product at a quality control location then generate a draft Internal Move from quality control -> stock.

I've tried setting the default value for Manufacturing/ Finished Product Location to WH/Quality Control but it was only effective when you manually create the MO. The default WH/Stock location was used when it is generated from Procurement when I do Run Scheduler.

**Comment by Yenthe666** [comment]
Have a look at the documentation for these kind of things. See https://www.odoo.com/documentation/11.0/
