### ISSUE TITLE
Cannot use `self.with_context()` in `onchange`

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#7472]
As you can see in https://github.com/OCA/partner-contact/pull/139 (2nd & 3rd ideas), when altering the context of `self` in an onchange method, consequent updates to the model are not reflected in the view:

```
@api.one
@api.depends("firstname", "lastname")
def _compute_name(self):
    """Write the 'name' field according to splitted data."""
    self.with_context(skip_invert=True).name = u" ".join(
        filter(None, (self.lastname, self.firstname)))

@api.one
@api.onchange("name")
def _onchange_name(self):
    """Ensure :attr:`~.name` is inverted in the UI."""
    if not self.env.context.get("skip_invert"):
        self._inverse_name_after_cleaning_whitespace()
```

If User changes *firstname* or *lastname*, what happens:

- Field *name* becomes `False`.

What should happen:

- Field *name* is updated, but `_inverse_name_after_cleaning_whitespace()` is not called.

**Comment by andreparames** [comment]
I believe this is expected. The data cache is tied to an Environment, which is a combination of (cr, uid, context). By changing the context, you're creating a new Environment, which is isolated from the view.

**Comment by Yajo** [comment]
Then which is the preferred way to modify current environment's context only?

**Comment by andreparames** [comment]
@Yajo well, contexts are frozendicts, so I don't think you can. I can't speak for Odoo devs, but I wouldn't be surprised if reducing the "hidden effects" of passing special context keys was one of the purposes of freezing the context.

**Comment by Yajo** [comment]
Maybe, but sometimes it's needed. I found the solution:

    self.env.context = self.with_context(skip_invert=True).env.context

And that context stays there until you revert it, so don't forget to do in other method something like:

    self.env.context = self.with_context(skip_invert=False).env.context

**Comment by andreparames** [comment]
To achive the same, you could probably just do

    from openerp.tools import frozendict
    self.env.context = frozendict(self.env.context, skip_invert=False)

but altering the context of the current Environment seems dangerous to me - you might have issues with functions that had references to the previous version, which will know be disconnected.

**Comment by Yajo** [comment]
Maybe, but I see no other option in this use case.

**Comment by yvaucher** [comment]
@Yajo I think we should keep this issue open. I think there is an issue still with `with_context` with doesn't copy cached values.

**Comment by Yajo** [comment]
I found a funny workaround:

```
    @api.model
    def create(self, vals):
        """Skip constrains in 1st lap."""
        # HACK https://github.com/odoo/odoo/pull/13439
        if "value" in vals:
            self.env.context.skip_required = True
        return super(CustomInfoValue, self).create(vals)

[...]

    @api.one
    @api.constrains("required", "field_name", "value_str", "value_int",
                    "value_float", "value_bool", "value_id")
    def _check_required(self):
        """Ensure required fields are filled"""
        # HACK https://github.com/odoo/odoo/pull/13439
        try:
            del self.env.context.skip_required
        except AttributeError:
            if (not self.env.context.get("filling_templates") and
                    self.required and not self[self.field_name]):
                raise ValidationError(
                    _("Property %s is required.") %
                    self.property_id.display_name)
```

Full story: https://github.com/OCA/server-tools/pull/492/commits/947abf3c5c52994a59a1723bd3b9c0b3ea7d1ed9

**Comment by obayit** [comment]
A workaround is to put the context in the view, e.g:
```
    <field name="firstname"  context="{'changed_firstname': True}"/>
```

Then in python onchange method, you can check for the existence of this context value:
```
    if self.env.context.get('changed_firstname'):
        return  # skipped to avoid loops
```

**Comment by antoniorosp** [comment]
**Working solution**: use our own context

```
import contextvars
...

# onchange event default to true
ctx_onchange = contextvars.ContextVar('onchange', default=True)

@api.onchange('price_unit')
def _compute(self):
    if self.ctx_onchange.get():
        self.ctx_onchange.set(False) # no more onchange events
        dosomething()
```
