### ISSUE TITLE
[8.0] Exporting one2many field with multiple records puts each value on field on a different line

### ISSUE THREAD

**Issue by fijozico** [odoo/odoo#74726]
**Impacted versions:**

8.0

**Steps to reproduce:**

From any model, export a `one2many` field

**Current behavior:**

When exporting a record which includes multiple values on a `one2many` field, each value for said field appears in a separate line, like shown below.

![Screenshot from 2021-08-04 18-35-18](https://user-images.githubusercontent.com/18015377/128227758-d131162b-91a1-4a11-be2a-7119bd555473.png)

Partner "30 por 1 linha" has 4 `mail.message`, each one appears in a different line (this field is `one2many`); the empty lines below are for another `one2many` field in the same record.

Note, however, the calendar.event objects in the prior column for client "Filipe Brígida", with 2 comma-separated values; this is a `many2many` field.

This problem seems to be fixed on later versions, like 14.

**Expected behavior:**

Exporting `one2many` fields should yield a comma-separated list, like what happens with `many2many` fields.

**What I've tried:**

On the export menu on Odoo, instead of selecting the field, selecting "field/ID"; didn't work.

**Comment by pedrobaeza** [comment]
This is the expected behavior and how it works, and 8.0 is out of official support a lot of years. You should seriously consider to upgrade.

Closing as stated.
