### ISSUE TITLE
Can this generate TPAR reports? If so where can I find it in the source code?

### ISSUE THREAD

**Issue by Joe23232** [odoo/odoo#74778]
Hi, I wanted to ask can this generate [TPAR reports](https://softwaredevelopers.ato.gov.au/TPARspecification) which is an Australian report? If so where can I find it in the source code?

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Comment by Joe23232** [comment]
ok sure

**Comment by Joe23232** [comment]
@pedrobaeza The forum page keeps doing this as soon as I try to submit a question.

![image](https://user-images.githubusercontent.com/34926497/128466342-52e19344-cca8-4192-a65a-fe01b1ef5027.png)

**Comment by pedrobaeza** [comment]
I suppose you are not complying with the minimum karma rules. @Yenthe666 you know more about the forum. Is that something normal?
