### ISSUE TITLE
Cantidad de Productos en Stock, Modificar precios

### ISSUE THREAD

**Issue by duranyoel** [odoo/odoo#7479]
Saludos estimados amigos les escribo desde venezuela, solo queria hacerles saber un par de cosas, una de ellas es que seria agradable que desde el tpv se pueda visualizar la cantidad en stock de un determinado producto si este producto dependiera de la cantidad como por ejemplo partes de pc o bebibas, seria bueno ya que con esto el usuario ya sabria si tiene disponibilidad o no de ese producto en almacen, lo otro es que con respecto a modificar el precio de los productos atraves del tpv no seria adecuado o por lo menos una opcion donde bloquear eso

**Comment by mbaragiola** [comment]
Hola @duranyoel , en este repositorio se habla principalmente en inglés. Los empleados de Odoo son europeos, y el resto de la comunidad es de todo el mundo. Por lo que la lengua consensuada es el inglés. ¿Sabés traducir tu mensaje en inglés?

**Comment by duranyoel** [comment]
Greetings dear friends I'm writing from Venezuela, just wanted to let you know some things, one is that it would be nice since the POS can display the amount in stock of a particular product if this product depended on the amount such parts pc, would be good because with this the user would know if you have availability or not of that product in stock, the other thing is that with respect to modify the price of products through the TPV would not be appropriate or at least an option where that block

**Comment by Yenthe666** [comment]
Hi @duranyoel,

I've labelled this as wishlist as this is a request, but this is probably not something that Odoo wants to implement in the future.
There are community modules that allow this though (such as http://webkul.com/blog/point-of-sale-stock/)

Regards,
Yenthe
