### ISSUE TITLE
translation out of addons

### ISSUE THREAD

**Issue by OpenERPJeff** [odoo/odoo#7482]
eg:
> msgid "The field(s) `%s` failed against a constraint: %s"

this is in openerp/model.py file

result is the error message shown on screen always be ENGLISH，this is unacceptable for end users

what will be the solution? add a new sub-directory i18n under openerp ?

**Comment by mart-e** [comment]
What do you mean ? This string [is translatable](https://github.com/odoo/odoo/blob/6490c62e5d7e28a8be62a102b6cdf32f38038728/openerp/models.py#L1266) so if people provide a translation, should be translated (except if we lost the context but then it should be fixed there)

**Comment by OpenERPJeff** [comment]
how to provide a translation, without a PO file

**Comment by OpenERPJeff** [comment]
how to provide a translation, without a PO file

**Comment by OpenERPJeff** [comment]
how to provide a translation, without a PO file

**Comment by mart-e** [comment]
Check [translation guidelines](https://github.com/odoo/odoo/wiki/Translations) but globally, go to [transifex](https://www.transifex.com/projects/p/odoo-8/) to join translation team

**Comment by Olivier-LAURENT** [comment]
Hi @mart-e 
Maybe the question of @OpenERPJeff was:
Where are located translations files (`*.po`, `*.pot`) related to all `_(...)` terms not belonging to an addon ?

We understand that such files are located:
* in `addons/account/i18n` for `account` addon terms
* in `openerp/addons/base/i18n` for `base` addon terms

but for all other terms (e.g. `The field(s) %s failed against a constraint: %s` from `openerp/models.py`) where are their translations files ?

Thx

**Comment by mart-e** [comment]
Oh right, probably that. My bad.

**Comment by OpenERPJeff** [comment]
Thank you @Olivier-LAURENT , that is my point.
