### ISSUE TITLE
Multiple domains as outgoing email server problem 

### ISSUE THREAD

**Issue by zozolpl** [odoo/odoo#74862]
Impacted versions: 12

Steps to reproduce: Configure servers as on images

Current behavior: Sending emails from yy.eu as xx.eu
 
Expected behavior: Split those domains as standalone 

Video/Screenshot link (optional): https://imgur.com/a/iCMsdQD

Hello,
I am using odoo v12 where I have configured 2 mailing servers.
1st xx.eu It is used to handle all emails from CRM, Projects, purchases and sales.
2nd yy.eu It is used only for the newsletter.

Configured as in the screenshots in the link.

The problem is that the first domain is working properly, while the second domain, when I open the message details, displays the following information:
From: Office <office@yy.eu>
Reply-To: Office <office@yy.eu>
And here's the problem:
X-Odoo-Objects: crm.lead-1
X-Authenticated-Id: contact@xx.eu

I do not want the yy domain to be associated with xx.eu in any way because the poor reputation of the newsletter domain is transferred to the reputation of the main domain.
Problem occurs also on runbot and fresh instalation with crm project and email marketing installed
How can I fix it?

**Comment by Yenthe666** [comment]
Sorry but V12 is no longer supported plus this is a configuration question :) Please ask it at https://www.odoo.com/forum/help-1

**Comment by pedrobaeza** [comment]
As reference, multiple mail domains are not yet supported.
