### ISSUE TITLE
[14.0/master]base: default value is missing in one2many field

### ISSUE THREAD

**Issue by ktr-odoo** [odoo/odoo#74897]
Impacted versions: 14.0 and master

Steps to reproduce: 
Consider a model A having one2many field related with model B (ex. order_line in sale.order). and model B has many2one field related to mode A (ex. order_id in sale.order.line)
Give one2many field a context to set default vaule of this many2one field like {'default_order_id': active_id} 

Open form view of model A and create a record. save. 
Edit view and click on 'add a line'

1) default vaule is not working for many2one field that is related to this model
https://drive.google.com/file/d/1isL7VJremTBp78d6lKsM-QaSGRQIsKeU/view?usp=sharing

2) default value is working for other many2one fields.
https://drive.google.com/file/d/1wqWbrsR3_0q9hltwabmZr65tPrnyFKQc/view?usp=sharing

Current behavior:
Defalut value is passed through context but not updated/set in many2one field

Expected behavior:
default value should be set when creating a record 

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
You can't do that on the `inverse_name` of the one2many, as the one2many widget ignores that, and it's on purpose. If you plan to have related fields to `order_id`, then directly default them to `parent.field_name`.

Closing as expected behavior.
