### ISSUE TITLE
Webshop: Cart is not updated when quantity is changed + No update button

### ISSUE THREAD

**Issue by ybofr** [odoo/odoo#7491]
In the checkout process, there is the possibility to update the quantity. The price is not recalculated, when the quantity is updated.

This bug is on Odoo SAAS and on V8

**Comment by lukebranch** [comment]
@ybofr ,

I suggest you use a GIF screencap tool like licecap to demonstrate this visually and post back here with the final GIF demonstrating the issue.

I have noticed similar issues with the checkout/shopping cart page when deleting an order line item. It seems the line underneath is not updated correctly. See:

https://github.com/odoo/odoo/issues/3342

#3342 seems to be a Firefox-specific issue, however it is still there.

**Comment by JKE-be** [comment]
Hello,
I cannot reproduce your second bug: "The price is not recalculated, when the quantity is updated."

Could you check on a new database, with the last code please...
Eg: http://runbot.odoo.com/runbot/1/8.0

Thanks

JKE

**Comment by Yenthe666** [comment]
Hi @JKE-be,

I believe this issue is no longer present in the latest Odoo versions?
Can we close this one?

Regards,
Yenthe

**Comment by JKE-be** [comment]
Hello @Yenthe666 
Yes, we can close it... No news since  Aug 7, 2015 and I cannot reproduce it !

Thanks
