### ISSUE TITLE
No Invoice Number grouping option in Reports/ Accounting/ Invoice Analysis

### ISSUE THREAD

**Issue by aldennis** [odoo/odoo#7495]
I would like to ask why there is no option for grouping the item by Invoice Number where in fact the name of the report is Invoice Analysis?

**Comment by csnauwaert** [comment]
Hello,

This option does not have much sense as each invoice has a different number. So you can't group them using that. If you did so, you'll see a list of all the invoices which is the same as what you can see by going to Accounting>Sales>Customer invoices
And if you have some use case where you want to see exactly all invoices under a specific account for example you can perform a group by in the customer invoices view.

Best regards
