### ISSUE TITLE
Payment( Authorize.net Module) 

### ISSUE THREAD

**Issue by DavidBryanRuiz** [odoo/odoo#74977]
Impacted versions: 14 Cloud

Steps to reproduce: Generate A Web Portal Invoice

Current behavior: Only Wire Transfer & Credit Card Are Displayed

Expected behavior: Option for both Credit Card & eCheck (ACH)

Looking at this thread, it should be possible , https://www.odoo.com/forum/help-1/how-to-accept-payments-through-ach-automated-clearing-house-93622. However after making the changes to the code. It does not offer eCheck as an option

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
