### ISSUE TITLE
[8.0] displaying attributes for category

### ISSUE THREAD

**Issue by ddfs** [odoo/odoo#7500]
like the title says, I got things working now. see code: 

https://github.com/ddfs/odoo/tree/master/addons/website_sale/controllers

I have about 20 attributes now (yes a few) but I only needed to display the relevant ones in current category. have written a small sql query which does the job using category id. 

I am not an expert of odoo orm but If you guys can point me out how to write this thing better way

**Comment by Yenthe666** [comment]
Hi @ddfs,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
