### ISSUE TITLE
[8.0] ImportError just if exists static folder in a module.

### ISSUE THREAD

**Issue by moylop260** [odoo/odoo#7507]
Steps to reproduce:
 1. Add to `addons-path` a module with `external_dependencies`
     e.g. https://github.com/moylop260/import_test
  
  1. Create a database installing base module (without install module with `external_dependencies`)
       e.g. createdb odoo && ./odoo.py -d odoo -i base

 2. Start odoo server with -u all
      e.g. ./odoo.py -d odoo -u all 
      All is done!

 3. Now, create a `static` folder in module of step # 1
    e.g. mkdir ./import_test/static

 4. Repeat step # 2
      e.g. ./odoo.py -d odoo -u all 

Current behavior:
      Now you have a `ImportError`

Expected behavior:
      I don't have installed module with `external_dependecies` then I don't need receive a `ImportError`
      I exepected run normally with or without `static` folder with modules uninstalled.
      If I have a clone repo with 10 modules and just use one, Why I need install all external dependecies of all modules (use it or not use it)?

[Video](https://asciinema.org/a/23103)

**Comment by beledouxdenis** [comment]
Dear,

This is actually the expected behavior: As soon as an addon contains a static folder, this is expected to load the module, even if not installed:
https://github.com/odoo/odoo/blob/8.0/openerp/http.py#L1292-L1318

This is done for several reasons.

When an external dependency, which is not always installed, is used within a module, it is expected to surround it with a `try except`.

For instance:
https://github.com/odoo/odoo/blob/8.0/addons/base_gengo/wizard/base_gengo_translations.py#L33-L36

Regards,

**Comment by moylop260** [comment]
Hello @beledouxdenis 
I love `external_dependencies` because I don't have that have caution in add `try-except` of `ImportError` in my py files.
And runbot or SaaS don't show a error or warning in log if a unused module is listed with `static` folder without external packages installed.
But I'm disappointed of this don't work of the same way if I add a icon or documentation to my module in `static` folder that don't have `py` files.

**Comment by yelizariev** [comment]
@moylop260 
it seems, that you have to update your py files...
But I'm agree on your disappointment. I think note about try block should be added in modules development documentation.

**Comment by yvaucher** [comment]
@beledouxdenis This is a really annoying "feature".

Using the try except will pollute the log with message on each loading.

And on other case it can load a module which is missing dependencies. You certainly don't want to have each dependencies of modules with just an icon ... You want only to know you are missing dependencies if you do want to install them.

**Comment by yvaucher** [comment]
""" This is done for several reasons. """

@beledouxdenis Sorry to ask but what are those reasons? Is it worth it?

**Comment by lmignon** [comment]
@beledouxdenis The try block is not a solution see https://github.com/OCA/account-financial-tools/pull/281#issuecomment-132956170. 
@odony What's your opinion on this one. It's really an annoying bug/feature

**Comment by moylop260** [comment]
@beledouxdenis 
We have next case:

[from openerp.addons.connector.queue.job import job](https://github.com/OCA/account-financial-tools/blob/da86d809a0fe88cf1670ed8bcd6646a0653c706b/account_move_batch_validate/account.py#L28)
...
[@job(default_channel='root.account_move_batch_validate')
def validate_one_move(session, model_name, move_id):](https://github.com/OCA/account-financial-tools/blob/da86d809a0fe88cf1670ed8bcd6646a0653c706b/account_move_batch_validate/account.py#L147-L148)

If we added a try-import-except
Now, we will have next error:
```python
File "./account_move_batch_validate/account.py", line 151, in <module>
  @job(default_channel='root.account_move_batch_validate')
NameError: name 'job' is not defined
```
What is the better way to fix it?

**Comment by yelizariev** [comment]
@moylop260 

    try:
        from openerp.addons.connector.queue.job import job
        from openerp.addons.connector.session import ConnectorSession
        from openerp.addons.connector.queue.job import OpenERPJobStorage
    except ImportError:
        _logger.debug('Can not `import connector`.')
        import functools
    
        def empty_decorator_factory(*argv, **kwargs):
            return functools.partial
        job = empty_decorator_factory

from https://github.com/OCA/account-financial-tools/pull/284

**Comment by sbidoul** [comment]
@beledouxdenis @odony would it be acceptable to add a manifest key such as ```no_preload``` which would let the developer explicitly prevent the preloading of the module when the static folder is simply used to add a description or an icon.

This would preserve the current behaviour and give additional control over which modules are loaded server-wide.

**Comment by moylop260** [comment]
+1 with @sbidoul

**Comment by yvaucher** [comment]
+1 with @sbidoul

**Comment by sbidoul** [comment]
I created #8591 to experiment with this idea. Tests and comments welcome.
