### ISSUE TITLE
[account_voucher] behavior wrong in onchange period

### ISSUE THREAD

**Issue by JulioSerna** [odoo/odoo#7510]
Impacted Version:
* 8.0

Steps to reproduce:
* To create one invoice and validate
* To create voucher to pay invoice
* To set client in voucher
* To set date 07/June/2015 ```current date - 1 month ```
* To set journal
* To se amount
* To validate

Current Behavior:
* Journal Entry has wrong period **07/2015**

Expected Behavior:
* Journal Entry with period **06/2015**

I made video,
https://youtu.be/m4_mqy6MW7Y

**Comment by beledouxdenis** [comment]
Closed with a35af81e6a64b45c84ee56f6309e784f6d846fcc.
