### ISSUE TITLE
Search/Filter Phone Numbers with hyphen in Odoo without typing hyphen

### ISSUE THREAD

**Issue by subhamaharjan13** [odoo/odoo#75106]
Impacted versions: 14

Steps to reproduce:Select Country and type the phone number in phone/mobile field in the res.partner form. It formats the phone number to a format such as (+977 984-1123124). I don't want to change the format but i need to search/filter the phone number like this (9841123124) rather than (984-1123124). No search results are found when searched like 9841123124.

Current behavior: No results found when searched without hyphen.

Expected behavior: Need to filter the record with/without including hyphen while searching

Video/Screenshot link (optional): 
![Screenshot from 2021-08-15 18-58-05](https://user-images.githubusercontent.com/25879572/129479823-dd366884-fb30-4346-a131-f13790af3d57.png)
![Screenshot from 2021-08-15 18-59-14](https://user-images.githubusercontent.com/25879572/129479826-6373fcdf-c492-4316-a80c-676f4390c92f.png)
![Screenshot from 2021-08-15 18-59-29](https://user-images.githubusercontent.com/25879572/129479827-0aef9c88-8c48-4721-b8f2-7b5a50326a7f.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
That's not possible. It's true that a "sanitized" phone number may be added like with bank account numbers, but that's an extra feature that doesn't exist right now, so I put it as wishlist.

**Comment by niyasraphy** [comment]
hi @subhamaharjan13 ,
this has been made working in contacts search view from 15, in case if you need the same in 14, you may have to backport the feature.
thanks

**Comment by SimonGenin** [comment]
Has been implemented
