### ISSUE TITLE
Support gettex plural-form

### ISSUE THREAD

**Issue by VeeSot** [odoo/odoo#7514]
Hello Everyone.

In Odoo exists full support gettex plural form with multiple choice of words?
In localization file exists string:
"Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);\n" 
but this don't work =(

Example(module Project,ru.po):
msgid "Tasks"
msgid_plural "Tasks"
msgstr[0] "Задание"
msgstr[1] "Задания"
msgstr[2] "Заданий"

**Comment by Yenthe666** [comment]
Hi @VeeSot,

Sorry for the late response.
No, this is not possible by default and it is not something that we would like to support.

Regards,
Yenthe

**Comment by spout** [comment]
In the documentation, also the "Do" is wrong for the cited reasons (in english 0 is plural). I don't see any helper method for plural forms.
![image](https://user-images.githubusercontent.com/212091/165455363-726c4208-d209-4c8c-821e-e2ccd5d361c1.png)
