### ISSUE TITLE
Several modules refere to no longer existing menu base.next_id_64

### ISSUE THREAD

**Issue by NL66278** [odoo/odoo#7515]
Several modules  have menu' s with base.next_id_64 as parent. This menu does not exit in base:
$ grep -nr next_id_64 * | grep -v Bina | grep -v i18 
addons/crm/report/crm_phonecall_report_view.xml:106:            id="menu_report_crm_phonecalls_tree" parent="base.next_id_64" sequence="15"/>
addons/crm/report/crm_opportunity_report_view.xml:118:             parent="base.next_id_64" action="action_report_crm_opportunity" sequence="5"/>
addons/crm/report/crm_lead_report_view.xml:128:            parent="base.next_id_64" action="action_report_crm_lead" sequence="1"/>
addons/crm_claim/report/crm_claim_report_view.xml:88:            action="action_report_crm_claim" parent="base.next_id_64" sequence="15"/>
addons/sales_team/sales_team.xml:198:        <menuitem id="base.next_id_64" name="Sales" parent="base.menu_reporting" sequence="1" groups="base.group_sale_manager"/>
addons/crm_partner_assign/report/crm_lead_report_view.xml:73:           parent="base.next_id_64" action="action_report_crm_opportunity_assign" sequence="20"/>
addons/crm_partner_assign/report/crm_partner_report_view.xml:55:           parent="base.next_id_64" action="action_report_crm_partner_assign" sequence="25"/>
addons/sale/report/sale_report_view.xml:88:    <menuitem action="action_order_report_all" id="menu_report_product_all" parent="base.next_id_64" sequence="10"/>
addons/crm_helpdesk/report/crm_helpdesk_report_view.xml:80:            id="menu_report_crm_helpdesks_tree" parent="base.next_id_64" sequence="20"/>

**Comment by NL66278** [comment]
Wait, menu is addes by sales_team module, WHILE PRETENDING IT IS IN BASE.

Really confusing.

**Comment by Behrouz-m** [comment]
I have the same issue in upgrading from Odoo8 to Odoo9. what whould I do? `base.next_id_64` is removed in odoo9
