### ISSUE TITLE
[8.0] Shop page title is buggy

### ISSUE THREAD

**Issue by ddfs** [odoo/odoo#7518]
shop page title remains unchanged when browsing through categories so on.
also when setting new title from page Promote window, remains same.
setting additional_title doesn't help either. 
setting title is the only way to modify at the moment

a temporary solution: in products template to replace

``` xml
    <!--t t-set="additional_title">Shop</t-->
    <t t-if="category and category.parent_id">
        <t t-set="additional_title" t-value="category.parent_id.name + ' - ' + category.name" />
        <t t-set="title"  t-value="additional_title + ' | ' + (website or res_company).name"/>
    </t>

    <t t-if="category and not category.parent_id">
        <t t-set="additional_title" t-value="category.name" />
        <t t-set="title"  t-value="additional_title + ' | ' + (website or res_company).name"/>
    </t>
```

**Comment by vilder** [comment]
Thanks for your code, very useful

**Comment by michaelkarrer81** [comment]
+1

**Comment by nafex** [comment]
+1

**Comment by Yenthe666** [comment]
Hi @ddfs,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
