### ISSUE TITLE
Odoo 14.0 Error werkzeug.posixemulation

### ISSUE THREAD

**Issue by alecvinent** [odoo/odoo#75228]
Impacted versions: 14.0

Steps to reproduce: Odoo service running

Current behavior: Odoo service breaks

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/14.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

You can ask for help as well on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups).

**Comment by alecvinent** [comment]
Hello again @pedrobaeza. It seems to be the Werkzeug requirement on this version. I posted the error at the forum, and they recommend to downgrade to 0.11.15, and problem was solved.

Thanks

Reference: https://www.odoo.com/es_ES/forum/ayuda-1/odoo-14-werkzeug-posixemulation-error-191890
