### ISSUE TITLE
[IMP]Allow use of qweb in form views

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#7526]
Hi folks,

I've been struggle with this a long time. Seems to be not suported.
Could it be added to the wishlist?
Regards

**Comment by cysnake4713** [comment]
Like this idea too~

**Comment by Yenthe666** [comment]
Hi @odony and @mart-e I'd like your input on this one. Is this something that we can add to the wishlist or is there a technical downside to this? The concept / idea is nice.

**Comment by mart-e** [comment]
With the evolution of the web client that may be the case one day (the idea comes up on the table from time to time) but no plan to do it at the moment. You can use qweb in kanban view though.
