### ISSUE TITLE
[8.0]Manufacturing Consume before produce with track manufacturing lots

### ISSUE THREAD

**Issue by jesusVMayor** [odoo/odoo#7527]
**When a product have checked track manufacturing lots its impossible only consume in manufacture orders.**

Error:
Because the product HDD on Demand requires it, you must assign a serial number to your raw material HDD SH-2 to proceed further in your production. Please use the 'Produce' button to do so.

impacted versions:
-8.0

Steps to reproduce:
Create a product with track manufacturing lots and a bill of materials.
Create a manufacture order and confirm it.
Launch Produce wizard:
    -Mode: Consume only
   -In the materials set a lot.
Confirm

Possible solution:
In mrp_production.action_produce set the main_production_move outside of "if production_mode == 'consume_produce':"

**Comment by qndi** [comment]
same Problem here

**Comment by Yenthe666** [comment]
Hi @jesusVMayor,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
