### ISSUE TITLE
Many2one not showing value (but related fields are showing, so it is being saved)

### ISSUE THREAD

**Issue by rockcesar** [odoo/odoo#75291]
Impacted versions:
Odoo 14.0

Steps to reproduce:
I select the value in Many2one, when I save, the selection is deleted, but in One2many the value is saved. Then I only see the selection in One2many.

If I show Many2one related fields, it shows, so it is saving the value in database, but not showing the Many2one selection.

Current behavior:
I select the value in Many2one, when I save, the selection is deleted, but in One2many the value is saved. Then I only see the selection in One2many.

If I show Many2one related fields, it shows, so it is saving the value in database, but not showing the Many2one selection.

Expected behavior:
Save in Many2one and see the value saved.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
You can't put the inverse_name field of a one2many to be visible in the one2many widget.

Closing as something forbidden and thus, expected to fail.

**Comment by rockcesar** [comment]
Ok, I found the error. The reason was that in the One2many model side, I was setting a field called display_name, and it seems that Odoo has a default field called like that, so something was failing. I changed the name of display_name field, and everything work again.

Thank you very much.

**Comment by rockcesar** [comment]
Like a reserved variable, in this case reserved field.
