### ISSUE TITLE
[14] Creating new variant unarchive old variants

### ISSUE THREAD

**Issue by lillebutik** [odoo/odoo#75301]
Impacted versions: 14

Steps to reproduce: 
- Go to Conference Chair. 
- Archive a variant say steel.
- Create a new variant say wood
-> Variant Steel is unarchived!

**Comment by pedrobaeza** [comment]
This is because you are not manipulating variants correctly. You should remove the attribute value from template instead, and the variant will be removed or archived depending if there's activity with it.

Closing as no issue.
