### ISSUE TITLE
Print button raise an issue in Qweb HTML Report

### ISSUE THREAD

**Issue by Mohsen1213** [odoo/odoo#75336]
Impacted versions: master

Steps to reproduce:
You can reproduce the issue in Odoo [runbot ] (https://9506866-master-all.runbot46.odoo.com/)with the below steps:

 1-For Technical -> reports change the invoice report type to HTML.
 2- Go to invoicing and open any invoice, click on print menu and click invoice, The HTML report opened and then click on the print button, the below error raised:
 
```
 Traceback (most recent call last):
  File "/data/build/odoo/addons/web/controllers/main.py", line 2066, in report_download
    data = dict(url_decode(url.split('?')[1]).items())  # decoding the args represented in JSON
IndexError: list index out of range

```

Current behavior:
Error raised when try to click on print button in any Qweb report with HTML Type.

Expected behavior:
 The PDF report should be generated.

Video/Screenshot link (optional):
https://loom.com/share/8fce3430a22149e9985516c79891f839

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
Master branch is by its nature an unstable branch. You shouldn't put issues about it. Only on stable ones. Closing thus.
