### ISSUE TITLE
[14] base: Can not import customers using template.

### ISSUE THREAD

**Issue by joserick** [odoo/odoo#75343]
Impacted versions: 14

Steps to reproduce:
![alt text](https://user-images.githubusercontent.com/16624719/128762151-ed2c4ea4-1418-48f6-88e4-a20da71c575c.png)

Current behavior:
![Captura de pantalla de 2021-08-19 14-30-12](https://user-images.githubusercontent.com/15143699/130132473-52715134-99a7-49a7-a907-3de73983d25a.png)

Expected behavior: Template should Work.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by joserick** [comment]
Apparently it has something to do with "use_cfdi_id" since when it's removed from the template it's imported correctly.

![Captura de pantalla de 2021-08-19 15-08-46](https://user-images.githubusercontent.com/15143699/130136934-eb047cad-d6ed-4b6d-a340-e7a62b9719e5.png)
![Captura de pantalla de 2021-08-19 15-07-27](https://user-images.githubusercontent.com/15143699/130136922-015ddbdd-7565-43eb-b246-ed0dbaac90ec.png)

**Comment by pedrobaeza** [comment]
This is not a problem with the import tool by itself, but specific business logic. You can share it through an enterprise ticket in odoo.com/help instead.
