### ISSUE TITLE
Where can I find the git repo for web-theme-treehouse?

### ISSUE THREAD

**Issue by kwoot** [odoo/odoo#75359]
Impacted versions: 12

Recent Odoo-CE included web-theme-treehouse.
I like to fork and send a PR with edits (like removal of Google+ icon).
Where can I find this repo?

Regards,
Jeroen Baten

**Comment by pedrobaeza** [comment]
Although this is a question, I'm answering it at the same time I close the issue:

https://github.com/odoo/design-themes

but further questions should go to forum.

**Comment by kwoot** [comment]
Huge thanks!
