### ISSUE TITLE
can't return to another form with @api.one

### ISSUE THREAD

**Issue by yk2kus** [odoo/odoo#7536]
in new api, with @api.one decoractor can not return to another form

return {
                        'view_type': 'form',
                        'view_mode': 'form',
                        'res_model': 'sale.order',
                        'view_id': False,
                        'type': 'ir.actions.act_window',
                        'name' : _('Sale Order'),
                        'res_id': record.order_id and record.order_id.id
                    }
doesn't work

**Comment by gdgellatly** [comment]
That is a fairly well known limitation of the api.  @api.one always returns
a list.  You need to use api.multi and self.ensure_one() instead.

**Comment by yk2kus** [comment]
Thanks!
