### ISSUE TITLE
[8.0] taxes included in base amount : rounding mismatches between pos and back end 

### ISSUE THREAD

**Issue by chrisdec** [odoo/odoo#7541]
Hello, 

I noticed a mismatch between the POS and the invoice in back end when using taxes included in base amout. 

Step to reproduce
----------------------------

1. Check taxe calculation rounding method 

Settings > Configuration > Accounting 

Tax calculation rounding method = round per line 

2.Create a tax included in base amount 

Name : recupel 1
Tax type : Fixed amount
Amount : 0.2893
Included in base amount : true 

3.Define the decimal accuracy 

Settings > Technical > Database structure > Decimal Accuracy 
Product price : 4
Account : 2

4.Create a product

Name : product 1
Sale price = 57.0248
Available in the point of sale : true
Customer taxes = vat-out-21-S AND Recupel 1 (created above) 

5.Open a POS session 

Select Agrolait 
Choose product 1 

--> The pos displays a total of 69.35 (taxes = 12.33 and total without taxes = 57.02)

6.Select bank journal to pay 

7.Click on invoice

Current behavior 
----------------------

The invoice has a total of 69.34 (taxes = 12.32 and total without taxes = 57.02) 

The related POS order doesn't have a picking (extra info tab on the pos order). The total of the POS order is 69.34 like on the invoice. 

Expected behavior : 
----------------------------------

POS and back end must have the same total and the POS order thus have a picking.

**Comment by mve-taktik** [comment]
OPW 644421

**Comment by simongoffin** [comment]
Closed with 569d051f0bb7e466bd50067ad187e79042cb66e9
