### ISSUE TITLE
Spelling Mistake on Odoo Server Error

### ISSUE THREAD

**Issue by sharpelectronics** [odoo/odoo#75477]
Impacted versions: Odoo 12

Steps to reproduce: Attempt to validate a transfer with no quantities reserved or done. 

Current behavior: Odoo Server Error - Warning message is displayed that says, "You cannot validate a transfer if no **quantites** are reserved nor done. To force the transfer, switch in edit more and encode the done quantities." 

Expected behavior: The message has a spelling error. The first instance of the word quantities is missing the final i. 
So the message should read "You cannot validate a transfer if no **quantities** are reserved nor done. To force the transfer, switch in edit more and encode the done quantities." 

Video/Screenshot link (optional):
![Screenshot 2021-08-23 092332](https://user-images.githubusercontent.com/51717377/130473714-34dd0403-191e-4d2f-835e-b5e8b2686659.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
Although you are right, modifying such strings in a stable version provokes that all the current correct translations are lost and requires to re-translate them, so the ratio benefit/cost is very low, and more in this old version that is just to be out of support in one month. Please check if the typo is still in master version, and if so, you can propose the correct word or mention about that.

Closing as stated.

**Comment by Yenthe666** [comment]
I've also fixed this in saas-13.1 at https://github.com/odoo/odoo/pull/43713
