### ISSUE TITLE
manufacturing order cancellation

### ISSUE THREAD

**Issue by anhdv1979** [odoo/odoo#7548]
When making MO with multi level BOMs, it generates multiple MOs. When cancelling the master MO, it could not automatically cancels the child MOs, When I continue to cancel one child MO, it sometimes cancel all others, sometimes not. I don't know why, maybe some bugs here ?

**Comment by jbradsha** [comment]
Can you reproduce this in Runbot  at http://runbot.odoo.com/runbot and post a video to youtube or similar?  My company are heavy users of that module and we'd like to know about bugs (and can help get them fixed).

**Comment by sle-odoo** [comment]
Hello,
Thanks for the feedback. Changing this behaviour not possible in stable, and it is also not trivial (not state draft...). We plan to log next activities starting from saas11.2, as it is the new default when dealing with exceptions.

Regards
