### ISSUE TITLE
[8.0]: Access rules for account.invoice.refund are missing (minor impact)

### ISSUE THREAD

**Issue by ghost** [odoo/odoo#7553]
Impacted versions:
- 8.0

Steps to reproduce:
1. Review the log file
2. Verify that no entry for account.invoice exists in https://github.com/odoo/odoo/blob/8.0/addons/account/security/ir.model.access.csv

Current behavior:

WARNING Features openerp.modules.loading: The model account.invoice.refund has no access rules, consider adding one. E.g. access_account_invoice_refund,access_account_invoice_refund,model_account_invoice_refund,,1,0,0,0

Expected behavior:

No message.

**Comment by Yenthe666** [comment]
Hi @ghost,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
