### ISSUE TITLE
Alphabetical sort order of contacts- non case sensitive sorting

### ISSUE THREAD

**Issue by frankofno** [odoo/odoo#75552]
﻿I struggle to find out, how i can edit the sort function itself. I dont need other fields to sort, but the sort function should sort alphabetically. The default alphabetical sort is:

All upper case before lower case. 

Aaron
Bernd
Chris

but

Bernd
Chris
aaron

That case sensitive sorting is not really usefull and should be changed by default to ignore case sensitivity.

So, how can I edit the sort function?

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Comment by frankofno** [comment]
it's bug because it's not alphabetical order. absolute noone will sort all upper cases first, than lower case and say, it's alphabetically ordered.

**Comment by pedrobaeza** [comment]
You decide the order through collation configuration in your system.
