### ISSUE TITLE
[12] Accessing a binary field return string but with size instead content

### ISSUE THREAD

**Issue by andrei-borcea** [odoo/odoo#75556]
Impacted versions: 12

Steps to reproduce: Website sale for example, try to use base64 encoded image src with
 `<img t-attf-src="data:image/*;base64,{{product.image}}"/>`
 `<img t-attf-src="data:image/*;base64,{{to_text(product.image)}}"/>`
Its the same...
Current behavior: The src after that will be something like data:image/*;base64,439.88 Kb -> tha last part after base64 should be the base64 image content but it seems to be the size

Expected behavior: Get the content of the image

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a development question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

Little tip: it depends on some context variable (not remember if it's `bin_size` or similar.
