### ISSUE TITLE
[8.0] mail_followers widget fails to implement set_value of FieldInterface (TypeError: unhashable type: 'list')

### ISSUE THREAD

**Issue by a0c** [odoo/odoo#7555]
According to `FieldInterface`, `set_value() must be able, at any moment, to handle <...> any format commonly returned in a on_change. It must be able to autodetect those formats as no information is ever given to know which format is used.`
Instead, current implementation simply stores the new value as is (and tries reading data for it later on):

``` js
this.value = _value;
```

Thus, if any on_change method of SO/Invoice/etc tries to set/update the `message_follower_ids` (even by mistake -- see below), the resulting format (e.g. `[(1, 3, {'dest_company': 1})]`) breaks the widget, which only expects simple indices as input (e.g. `[3]`).

To make things worse, due to record caches, update of `message_follower_ids` can now be triggered in completely safe situations, like reading a readonly value from inside of an on_change. E.g. if we are reading a functional readonly value `dest_company` from a partner which happens to be one of the message_follower_ids, the partner's record becomes **dirty** because of the caches updated with the readonly value, and the base `on_change` method returns this partner back to the form as if changed, even if the partner itself hasn't changed.

May have smth to do with #6051 and #6821.
#### Reproduce

Add some dummy functional field to res.partner:

``` python
    @api.depends('parent_id')
    def _dest_company(self):
        for p in self:
            p.dest_company = p.parent_id.id or p.id

    dest_company = fields.Many2one('res.partner', "Partner's Company", compute=_dest_company)
```

And simply read this value from an on_change in Sale Order:

``` python
    def onchange_partner_id(self, cr, uid, ids, part, supply_type, context=None):
        res = super(sale_order, self).onchange_partner_id(cr, uid, ids, part, context=context)
        if not part:
                self.pool.get('res.partner').browse(cr, uid, part, context).dest_company
        return res
```

On_change in BaseModel will generate a result containing smth like

``` python
{'message_follower_ids': [(1, 3, {'dest_company': 1})]}
```

Value `[(1, 3, {'dest_company': 1})]` will be passed to widget, which will pass it on as a `follower_ids` param to `mail_thread.py#read_followers_data()`. As a result -- the notorious `TypeError: unhashable type: 'list'`.

**Comment by Benniphx** [comment]
+1 to solve this issue soon

**Comment by michaelhwalther** [comment]
+1 I'm hitting this in our production Odoo...

**Comment by Yenthe666** [comment]
Hi @a0c,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
