### ISSUE TITLE
[8.0][feature] set default homepage in website

### ISSUE THREAD

**Issue by ddfs** [odoo/odoo#7563]
will that be possible to set homepage when (only) use of ecommerce,blog or forum is highly needed?

gone through the source code to check the possibility but requires some major changes since shop, blog forum etc urls are hard-coded.

suggestion:
-- moving these constant urls into config file and read/scan at runtime
-- in base modul reading and assigning them on depended module loads.

or any other simple solutions ?

**Comment by qsm-odoo** [comment]
Hello,
Sorry we did not answer you at the time. Was your question about setting the homepage of your website ? If I remember well, in 8.0, you had the possibility to set it by organizing your menu. The first menu is basically your homepage. In 11.0, there is a more complex system:
- You can choose the homepage in the page management system.
- If none is chosen, then this fall-backs to the first menu item in the menu (except if you set an URL's page to "/").
We may consider improving this further for next versions.
