### ISSUE TITLE
[8.0] LiveChat im_chat_presence not correctly updated

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#7568]
Hi,

I found this in the logs :

```
ERROR mag_gestion_prod openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='online',"last_poll"='2015-07-10 19:54:37',"write_uid"=6,"write_date"=(now() at time zone 'UTC') WHERE id IN (3)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: ERREUR:  n'a pas pu sérialiser un accès à cause d'une mise à jour en parallèle
```

I don't know where it could come from

**Comment by hugho-ad** [comment]
How can we replicate the issue ?

**Comment by Yenthe666** [comment]
Hi @flotho,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
