### ISSUE TITLE
stock_dropshipping KeyError: 'mrp.bom'

### ISSUE THREAD

**Issue by vperilla** [odoo/odoo#75706]
Impacted versions: 13.0

This [commit](https://github.com/odoo/odoo/commit/1d973abee376e72796764bc50b91e0c4a1d3cd08#diff-578bf5369be215bccaf553fca5bfb45f7bd43904c189ac3617609abe4a031f7f) introduces a KeyError, due to the use of  `mrp.bom` model in `stock_dropshipping` test.  `mrp` module is not a dependency of `stock_dropshipping` module.

Steps to reproduce: run tests

Current behavior:
Key error when run tests.

Expected behavior:
Success tess

Video/Screenshot link (optional):
![swappy-20210827_114002](https://user-images.githubusercontent.com/211490/131160581-6dac97c1-59d5-4ba2-8d71-921372819859.png)

![swappy-20210827_113033](https://user-images.githubusercontent.com/211490/131159671-5af0468f-a079-4c30-85a7-df1776a441ec.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by guva-odoo** [comment]
@pedrobaeza @vperilla  fixed with 51513a2

**Comment by pedrobaeza** [comment]
Thanks!
