### ISSUE TITLE
Declare deprecated IrModelAccess methods

### ISSUE THREAD

**Issue by voronind** [odoo/odoo#75712]
Can we declare IrModelAccess.check_groups and IrModelAccess.check_group methods deprecated and then remove?
There is no code uses it and there are alternatives.

**Comment by pedrobaeza** [comment]
I don't get what you want to say and this is not an issue.

**Comment by voronind** [comment]
It's about `ir.model.access` model. It has `check_groups` method that doesn't use IrModelAccess attributes, duplicate functionality and code of `ResUsers.has_group` and was used nowhere.  
We can write `self.env['res.users'].has_group(group)` instead.

**Comment by pedrobaeza** [comment]
Thanks for the extra info. This is not an issue though. You can propose a pull request doing such thing in master branch and be discussed there, as stable branches are not touched except for bugfixes.

Closing due to this.
