### ISSUE TITLE
Error in work orders tab of manufacturing

### ISSUE THREAD

**Issue by bhanukiran6864** [odoo/odoo#75766]
Impacted versions: 14.0

Steps to reproduce: Click on create new manufacturing order. Don't save yet. After selecting bill of materials, go to work orders tab and select scheduled start date and don't update anything in work centre field. After setting some date in scheduled start date, an error popup is coming.

Current behavior: Error on selecting scheduled start date if work centre is not selected.

Expected behavior: Either error should not come or some meaningful error popup saying workcentre is not selected should appear.

Video/Screenshot link (optional): 
![Screenshot from 2021-08-30 12-25-57](https://user-images.githubusercontent.com/68856953/131446200-289f4b83-68e2-4365-83c1-ce97d2426fb5.png)

Support ticket number submitted via odoo.com/help (optional): 2633940

**Comment by pedrobaeza** [comment]
Similar to #55963

**Comment by jhellinckx** [comment]
@pedrobaeza @bhanukiran6864

**Comment by bhanukiran6864** [comment]
@jhellinckx This issue is fixed 10 days back and available in latest github odoo code. I can see the bug fix in mrp_workorder.py file.
@pedrobaeza Please close this ticket
