### ISSUE TITLE
The error "Field %r used in attributes must be present in view but is missing" is not shown

### ISSUE THREAD

**Issue by chrisbiava** [odoo/odoo#75788]
Impacted versions: 13

Steps to reproduce: 
1) Include in a field attributes a field not included in the view 
    (E.g. <field name="attribute_id" attrs="{'readonly': [('my_field', '!=', False)]}/>
2) Restart Odoo and update the module containing the view

Current behavior:
Odoo shows this error:
**'TypeError: %u format: a number is required, not str'**
This is due to an error in the translate module (see ir_ui_view.py). In fact when this class is called:
**_("Field %r used in attributes must be present in view but is missing:")**
It returns this (in my case the l10n is italian):
**'Campo % usato negli attributi mancante, è obbligatorio nella vista:'**
Instead of this:
**'Campo %r usato negli attributi mancante, è obbligatorio nella vista:'**

Expected behavior:
This error is expected to be shown:
'Field >my_field> used in attributes must be present in view but is missing:'

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a development question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Comment by chrisbiava** [comment]
Hi Pedro,

Okay sorry, my bad.
I will post it on Odoo official forums!
