### ISSUE TITLE
14.0 - [BUG] tools: safe_eval redefined from tools

### ISSUE THREAD

**Issue by moylop260** [odoo/odoo#75811]
# Impacted versions

Reproduced from 14.0

# Steps to reproduce:

Run from `odoo-bin shell` the following python code:

```python
print("from odoo.tools.safe_eval import safe_eval")
from odoo.tools.safe_eval import safe_eval
print(safe_eval)

print("from odoo import tools;tools.safe_eval")
from odoo import tools
print(tools.safe_eval)

print("from odoo.tools import safe_eval;safe_eval.safe_eval")
from odoo.tools import safe_eval
print(safe_eval.safe_eval)
```

`odoo-bin shell < safe_eval_test.py`

Output:

```txt
from odoo.tools.safe_eval import safe_eval
<function safe_eval at 0x7fda82502ef0>

from odoo import tools;tools.safe_eval
<function safe_eval at 0x7ff507e23ef0>

from odoo.tools import safe_eval;safe_eval.safe_eval
Traceback (most recent call last):
  File "odoo-bin", line 8, in <module>
    odoo.cli.main()
  File "odoo/cli/command.py", line 60, in main
    o.run(args)
  File "odoo/cli/shell.py", line 125, in run
    self.shell(config['db_name'])
  File "odoo/cli/shell.py", line 118, in shell
    self.console(local_vars)
  File "odoo/cli/shell.py", line 67, in console
    exec(sys.stdin.read(), local_vars)
  File "<string>", line 7, in <module>
AttributeError: 'function' object has no attribute 'safe_eval'
```

Now, run the same code using a Odoo's addons

# Current behavior

Using `odoo-bin shell` the following code:
 - `from odoo.tools import safe_eval;safe_eval.safe_eval`

The following error is raised:
 - `AttributeError: 'function' object has no attribute 'safe_eval'`

But using a Odoo addons with the following code:
  - `from odoo import _, api, fields, models, tools`
  - `tools.safe_eval`

The following error is raised:
 - `TypeError: 'module' object is not callable`

It is a weird case because looks to be flaky depending of the order of the imports for each environment

I noticed that the `tools/__init__.py` file is importing all with asterisk `from {} import *`

The following line of code:
 - https://github.com/odoo/odoo/blob/9b23864027bc24032993833f213395cb45fe86bb/odoo/tools/__init__.py#L22

is defining the `tools.safe_eval` here:
 - https://github.com/odoo/odoo/blob/9b23864027bc24032993833f213395cb45fe86bb/odoo/tools/convert.py#L37

But it `tools.safe_eval` is defining in the file itself too:
 - `tools/safe_eval.py`

So, maybe python3.8 is raising this flaky error depending of the environment and order of the import if you are using a addons or shell

Because there are items named `tools.safe_eval` (the variable in convert.py and the file itself)

# Expected behavior

Using odoo-bin shell no raises error using:
 - `from odoo.tools import safe_eval;safe_eval.safe_eval("[]")`

Using Odoo's addons no raises error using:
  - `from odoo import _, api, fields, models, tools`
  - `tools.safe_eval("[]")`

**Comment by pedrobaeza** [comment]
In my shell everything works properly, so it seems it's due to your deployment:

![Selección_022](https://user-images.githubusercontent.com/7165771/131623148-e8ea70f2-917e-4e7f-b459-a0d049156444.png)

**Comment by moylop260** [comment]
I tried to reproduced it using the odoo docker but it is not reproduced in an easy way

So, closing for now

Thanks for try it
