### ISSUE TITLE
owl js 

### ISSUE THREAD

**Issue by yao-big** [odoo/odoo#75812]
Impacted versions: 14 

### **The first way to write:** 

HomeMenu.patch('web_enterprise_sidebar.HomeMenu', (T) => {
        class HomeMenuInherit extends T {
            _onAppClick(app) {
                this._super.apply(this, arguments);
            }
        }
        return HomeMenuInherit
    }) 

### The second way to write

  const components = {
        HoneMenu: require('web_enterprise.HomeMenu')
    };

    const {patch} = require('web.utils');
    patch(components.HoneMenu, 'web_enterprise_sidebar.HomeMenu', {
        _onAppClick(app) {
            // this._openMenu({menu: app, isApp: true});
            this._super.apply(this, arguments)
            $('.sidebar_panel').css({
                'display': 'block'
            })
        }
    })

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a development question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
