### ISSUE TITLE
eBay: Required Privacy and Data Compliance

### ISSUE THREAD

**Issue by lem8r** [odoo/odoo#75841]
Impacted versions: 12.0 and up

Steps to reproduce: use sale_ebay module to sync orders.

Current behavior: there is no webhook to delete personal data of eBay user if asked (on account deletion).

Expected behavior: be able to receive eBay Marketplace Account Deletion/Closure Notifications as it is required since 31st of August 2021.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional): https://developer.ebay.com/marketplace-account-deletion

**Comment by pedrobaeza** [comment]
Being done in https://github.com/odoo/enterprise/pull/20265
