### ISSUE TITLE
[8.0] NULL is not zero

### ISSUE THREAD

**Issue by jdegoy** [odoo/odoo#7584]
Impacted versions:

 - 8.0 , ...
CROSSFUNCTIONAL ISSUE

Steps to reproduce:

 1. One example; export Opportunities to excel including Probability field
 2. Second example; export Debit and Credit values on account moves

Current behavior:

 - zero as shown on the screen is not stored as zero in the DB. 

Expected behavior:

 - For integer and float fields, when a user sees "0" on the screen, it should be "0" in the DB as well.
 - When exporting the data, we should find zero and not blank (null).

**Comment by jdegoy** [comment]
![page-1](https://cloud.githubusercontent.com/assets/11032154/8649488/2593099a-296b-11e5-95b6-23ecdf2f20db.png)
![page-2](https://cloud.githubusercontent.com/assets/11032154/8649487/2591d868-296b-11e5-8223-f58036cd45c1.png)

**Comment by kkarolis** [comment]
I'll also add a bit of an input for this one. From a developer standpoint often a search query like this can happen:
```python
self.search(['float_field', '<' 0.0])
```
When some records are created without this `float_field` explicitly set to 0.0 (upon creation), a NULL is inserted instead, and the record would not be included in the results. However, if you do logically the same operation like self.search([]).filtered(lambda r: r.float_field < 0.0) it will of course return the "expected" result.
Its partly a programmer error of course, but a NULL is usually represented as 0.0 on the interface making the problem somewhat difficult to debug without carefull rechecking of returned records.

**Comment by mart-e** [comment]
Hello,

Are you sure you are talking about excel export and not CSV ? It is supposed to work fine and display 0.0 in case of excel export (works fine on my side).

For the search, while this is true that the search ignore the null values for such domains, these values should not be present in the database in the first place (how they came there is probably the issue). All float or integer fields have 0 as value for "not defined".

**Comment by jdegoy** [comment]
Yes it's with CSV that you can see the problem indeed. It's just a way to show that there is inconsistency between what you see on screen and what's in the DB. That is where this issue is about. 
While we are at it, perhaps a good opportunity to make it consistent between csv and xls as well. 
Even better, make sure the numerical fields are exported as such to xls so we can pivot on it right away without having to reformat in excel or alternative.

**Comment by mart-e** [comment]
Both exports mode are different. In excel you can specify types to your data (e.g. numerical fields and booleans) but in CSV, everything is string. They don't behave the same way but it's the intended behaviour.
So if you need to export the data for mathematical post-processing, go for excel. Use CSV only for exports between databases, backup and such.

How the ORM stores data in the database should not really matter anyway, it's it's job to display it correctly on the screen.

**Comment by jdegoy** [comment]
For every export above 65536 records you need csv anyways. Can you elaborate on what is meant with "intended behaviour"? You won't fix it?

"How the ORM stores data in the database should not really matter anyway, it's it's job to display it correctly on the screen." I'm not sure how to react to this. There is no substitute for what the DB reveals. A report is a report. What we report (via screen or other) on the (GL)DB should be in the (GL)DB. Else it's not a report.

**Comment by mart-e** [comment]
> For every export above 65536 records you need csv anyways.

This is true. It's a limitation of .xls export. I submitted the new request for export in .xlsx but that's a new feature so no guarantee of timing (and if it will be accepted).

> Can you elaborate on what is meant with "intended behaviour"? You won't fix it?

I mean we don't consider there is anything to fix. The CSV export and import works fine for it's purpose of a mean of transfer of data. `''`, `0.0`, `False`, `None` are all represented as `''` in CSV and interpreted fine when imported back. The CSV has not the purpose to represent exactly the content of the database.
The difference between Excel and CSV is that the first one will export the data in "raw mode", keeping the types of the fields.

It could be an improvement to export numeric value as numeric in CSV instead of empty value but that's not a bug fix, it's something that should target the master version.
