### ISSUE TITLE
[8.0] Integrity constraint for payment transaction problem

### ISSUE THREAD

**Issue by dbertha** [odoo/odoo#7585]
When you first cancel a transaction and then start a new one for the same SO, you have this error : 
IntegrityError: duplicate key value violates unique constraint "payment_transaction_reference_uniq"
DETAIL:  Key (reference)=(SO227) already exists.

So a customer who cancels his first transaction can no longer pay for his cart...

The check_reference constraint should be modified : 
def _check_reference(self, cr, uid, ids, context=None):
        transaction = self.browse(cr, uid, ids[0], context=context)
        if transaction.state not in ['cancel', 'error']:
            if self.search(cr, uid, [('reference', '=', transaction.reference), ('id', '!=', transaction.id)], **('state', 'not in', ['cancel', 'error'])**, context=context, count=True):
                return False
        return True

**Comment by Yenthe666** [comment]
Hi @dbertha,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
