### ISSUE TITLE
I am not Receiving any Badges after initial 2 badges

### ISSUE THREAD

**Issue by pinglavel** [odoo/odoo#75882]
Impacted versions: 14

Steps to reproduce:

Current behavior: No auto updating of Badges (My user profile : https://www.odoo.com/profile/user/2102873)

Expected behavior: Badges should automatically get updated (after initial 2 badges it stopped) 

Video/Screenshot link (optional):  None

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
This shouldn't be put here as an issue, but write directly to Odoo, being something of their website. Anyways, it can be that you have put your profile as private. Please check. Closing this due to the above reason.
