### ISSUE TITLE
Website created using drag drop (without any external code) is not flexible with Mobile devices : Alignment issues

### ISSUE THREAD

**Issue by pinglavel** [odoo/odoo#75883]
Impacted versions: 14

Current behavior: Web pages are not fully compatible with various screen resolutions ,especially from mobile phones. The website which looks fantastic in Computer/Laptop web browser doesn't look good in mobile phone browser and then it needs programmer to change that behaviour. So, our effort and motive of creation of website without programmer takes a hit.

Expected behavior: It should automatically update itself based on screen size (Its an issue with CSS), there should be better feature when someone doesn't want to code

Expectations : There should be option or additional button wherein we can select compatible screen sizes , so it should automatically get programmed in CSS files (extra classes will automatically get added upon selection of such option)

**Comment by pedrobaeza** [comment]
Unless you show specific problems, all website snippets are mobile first thanks to Bootstrap 4, so your statement is not true.

**Comment by pinglavel** [comment]
@pedrobaeza 

Here is the link of my project : 

https://technodysis-training7-stage-3093836.dev.odoo.com/

Now try opening this link in web browser from computer and then from mobile phone. There is an alignment issue. So, it clearly shows mobile first is not working in a way it should work

**Comment by pedrobaeza** [comment]
Sorry, but you need to provide the proofs here in the issue tracker.

**Comment by pinglavel** [comment]
@pedrobaeza 

I already gave you link which itself is a proof. You or anyone can check that its a clear cut issue with alignment of text as well as UI

 I am sorry to say , but your priority seems closing the thread without even identifying issue. 

I clearly mentioned that, There is issue with mobile first feature (atleast in my case) . Instead of solving it , you are guiding me to provide proof.

**Comment by pedrobaeza** [comment]
This is a public and voluntary issue tracker effort, and things not correctly notified (with steps to reproduce the problem in Odoo standard), will be discarded. If you want further efforts and you have an enterprise contract, you can go to odoo.com/help and put such problem there.
