### ISSUE TITLE
[7.0] Documentation missing all the iamges. 

### ISSUE THREAD

**Issue by sailosha** [odoo/odoo#75902]
For example: https://github.com/odoo/odoo/blob/7.0/doc/03_module_dev_03.rst

`Screenshots
+++++++++++
    
.. .. figure::  images/gantt.png
..     :scale: 50%
..     :align: center
`

There is no images dir in the documentation.

**Comment by pedrobaeza** [comment]
Such documentation is not intended to be queried that way, and that version is out of official support a lot of years ago. Check current documentation at https://odoo.com/documentation/
