### ISSUE TITLE
[7.0] copy_data is not called for base classes in case of multiple inheritance

### ISSUE THREAD

**Issue by etsinko** [odoo/odoo#7592]
Steps to reproduce:
1. Create a new database with demo data enabled
2. Install accounting module
3. In Settings->Users create a new user "test"
4. In Accounting->Suppliers find partner "test" and enable "Customer" in Sales & Purchases tab
5. In Accounting->Customer Invoices create a new invoice for customer test and put any line in there
6. In Settings->Users duplicate a user "test". A new user "test (copy)" will be created.
7. Observe that the invouce created in step 5 now has 2 identical lines instead of one.

My observations:
This is caused by the fact that any object's copy_data() doesn't call copy_data() for any of it's base classes. 
In this particular example, res.users has two base classes: res.partner and mail.alias. 
Installing accounting module in step 2 above adds a new implementation for res.partner by adding a new column 'invoice_ids' and also overrides copy_data() for res.partner to make sure that 'invoice_ids' field is not copied by default.
Since res.partner's copy_data() is never called from res.user's copy_data() in step 6 this field gets copied thus producing one extra invoice line.

**Comment by Yenthe666** [comment]
Hi @etsinko ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
