### ISSUE TITLE
[8.0][API] - Multiple OnChange XHR on removing invoice line

### ISSUE THREAD

**Issue by wtaferner** [odoo/odoo#7595]
## Impacted versions:
8.0 and above

## Steps to reproduce:
* Go on Runbot and edit a draft invoice
* Open Developer Console to monitor the network activities
* Remove a single invoice line and wait...

## Current behavior:
* Three XHR requests are sent

![multipleonchangerequestsonunlinkinvoicelinenewapi](https://cloud.githubusercontent.com/assets/362478/8668266/7a1c3254-2a09-11e5-8c94-6c38ea451366.jpg)

## Expected behavior:
* Only one XHR request should be sent to the server in case it is not a cascading onchange which I doubt for the invoice line, so I assume it is duplicate requesting the same result.

This is only an issue with the new API as the other models do sent only one onchange request.

OPW-644706

**Comment by wtaferner** [comment]
@nle-odoo 
Any news on this one?

**Comment by nle-odoo** [comment]
Hello,


I have a pull request which should solve this: 
 https://github.com/odoo/odoo/pull/8273

The first commit should be straight-forward to be applied to 8.0, but for the second it seems a little more risky (in master these bind are [already removed](https://github.com/odoo/odoo/commit/7d3cda215a#diff-324d6a1eec966a4dd4238fa4d3f86866L852))

Regards.

**Comment by wtaferner** [comment]
@nle-odoo 
Thank you for the effort. I will test it myself on a highly responsive custom and complicated model and view and see if there are side-effects and I will give feedback about the changes to be "safe" for stable from my PoV.
