### ISSUE TITLE
Show detailed operations overwritten unwantedly

### ISSUE THREAD

**Issue by themreza** [odoo/odoo#76036]
Impacted versions: 14.0

Steps to reproduce:

1. Go to the Inventory module > Configuration > Operation Types
2. Find an operation type that is not incoming
3. Uncheck Show Detailed Operations to 
4. Go to Settings and change any settings option (e.g. Purchase > Orders > Warnings)

Current behavior:

Show Detailed Operations gets checked again on non-incoming operation types.

Expected behavior:

Show Detailed Operations should remain checked or unchecked according to what the user decided.

Video/Screenshot link (optional):

Runbot:

https://user-images.githubusercontent.com/5465057/132238366-c6318bbf-57a2-49bf-8255-ee9148eac29d.mp4

Debugged locallly:

https://user-images.githubusercontent.com/5465057/132238373-7405a92c-08fb-45d4-9839-57c6a219f684.mp4

Responsible line: https://github.com/odoo/odoo/blob/14.0/addons/stock/models/res_config_settings.py#L97

If this is expected behavior (which is confusing), please explain why it should be this way.

**Comment by pedrobaeza** [comment]
Duplicated. See https://github.com/odoo/odoo/issues/51121#issuecomment-627803667
