### ISSUE TITLE
[13.0] base: Custom translation in website sometimes doesn't work 

### ISSUE THREAD

**Issue by RachidAlassir** [odoo/odoo#76054]
Impacted versions:  13.0

Steps to reproduce:
I've been facing this issue for a while: quite often custom translation on the website part doesn't work (specially in JS files).

Exemple: 
In module `payment` I want to translate `We are processing your payment, please wait ...`  

to  (in Arabic):

`نحن نقوم بمعالجة الدفع الخاص بك ، فضلا الإنتظار ...`

I made a custom module `payment_i18n` but it never work, I debugged the code source I  found out that Odoo does some caching and it uses **original modules** of these terms to filter / fetch translations. 

I added from the interface field **module** to the tree view of the translated terms and I changed `payment_i18n` by `payment`.

Screenshots:

![image](https://user-images.githubusercontent.com/48803268/132270426-99231eda-8f06-4eda-a752-f1afe573eb08.png)

Then the translation worked

![image](https://user-images.githubusercontent.com/48803268/132270500-e2c5211f-467a-4e3b-85c4-18bedc56a94e.png)

**Comment by pedrobaeza** [comment]
You have to use `i18n_extra` folder. For further questions, please go to forums, no here.

Closing as no issue, but development question.

**Comment by RachidAlassir** [comment]
Even under `i18n_extra` sometimes doesn't work. I thought this could be an extensibility issue.

**Comment by pedrobaeza** [comment]
Unless you provide exact steps to reproduce with standard code, "sometimes" is not enough for tracing a possible issue.

**Comment by RachidAlassir** [comment]
Even though I translated to term in the exemple above in [Transifex](https://www.transifex.com/odoo/odoo-13/translate/#ar/payment/180737188?q=text%3A'We+are+processing+your+payment').

I will try with the same exemple but with different language.

Steps to reproduce:
Let consider **term_to_translate** = `We are processing your payment, please wait ...`
Create a custom module `payment_i18n` which contains a folder `i18n_extra` add `lang.po` where `lang` is the language code of any language where **term_to_translate** is untranslated.

translate the term. 
Go to shop -> purchase an item -> process the payment: the **term_to_translate** isn't translated.

Notes  /  hints: 
I knew that Odoo fetch the translated terms in website by some sort of caches.
check this [base: L907](https://github.com/odoo/odoo/blob/cd9c071c9357cef14635ef094a9f14fc5431956c/odoo/addons/base/models/ir_translation.py#L907)
So my guess was to change **module** value as the screenshots above and it worked (in incognito session) !!.
