### ISSUE TITLE
Webshop variant added to cart from category view gives no notification on variants

### ISSUE THREAD

**Issue by kimasplund** [odoo/odoo#76066]
Impacted versions: 14

Steps to reproduce: 
Add a product with variants to webshop and enable "Add to cart" for products in category view.
Current behavior:
Adding a product with variants to cart from category view adds the first option to cart without any info or notification that there is variants available.
Expected behavior:
A notification or popup that there is variants available or perhaps a dropdown selection above cart button or somewhere.

**Comment by pedrobaeza** [comment]
@JKE-be what do you think about the suggestion?

**Comment by JKE-be** [comment]
Hello

Thank you, it is not considered as a bug but as an improvement.
But it has been improved in v15 already.
You have now the possibility to choose the variant into the popup

Before:
![image](https://user-images.githubusercontent.com/4848797/132339233-0eda1519-b08c-4728-9525-31d0beb69dea.png)

In v15:
![image](https://user-images.githubusercontent.com/4848797/132339247-479843b4-bfec-4ea8-87c2-602a5ccf6997.png)
