### ISSUE TITLE
Many2many field with domain saves in relation table

### ISSUE THREAD

**Issue by christophlsa** [odoo/odoo#7612]
# Problem:

If you have a Many2Many field in odoo with a specific domain and use this field with the many2many_tags widget then you can create and add a new entry which doesn't fulfill the domain restrictions. The new record is shown in this field. If you then save this record the entry in the field is not shown anymore but it is saved in the field (the entry is added to the relation table).
# steps to reproduce

I didn't found an existing field which is the type of many2many and has a specific domain. Here is general list to reproduce:
- Create a new many2many field in a model.
- Set a domain to this field which doesn't include entries which uses only the default values of their fields (e.g. active = False)
- Add this field to a view with the "many2many_tags" widget.
- Create a new record of this model and in the new field type something and click on "Create" (of the many2many_tags widget).
- The record is now added in the field.
- Click on Create for the new record.
- The new record doesn't contain the other new record in its field.
- Look into the relation table in the database. The records are added as a new line.

**Comment by MicheleZak** [comment]
I have found this particular issue with a One2many too. I also am using the many2many_tags. 
When I create a record through the 'Create and Edit' link which not fulfill the domain condition, it is added anyway to the relation but it is not shown.

**Comment by pedrobaeza** [comment]
Yeah, this is the current limitation of the widget, but no easy solution IMO. As a workaround, you can add an extra constraint for checking the comply of the domain.

Closing this as triage operation.
