### ISSUE TITLE
[12.0e][13.0e][14.0e]Usability issue with menu search with Japanese text

### ISSUE THREAD

**Issue by TomohiroAbe-Quartile** [odoo/odoo#76133]
**Impacted versions:**
12.0e, 13.0e, 14.0e

**Steps to reproduce:**
This error occurred in Google Chrome and Microsoft Edge.
Try to type テスト(which is "TEST")
Expected keystroke sequence using Japanese IME: "t" -> "e" -> "s" -> "u" -> "t" -> "o" -> space
(to convert the text from hiragana to the first suggested option (which is katakana) -> enter (to confirm the suggested option)

**Current behavior:**
The Japanese string recognition in the home page always doesn't work for the first stroke.
If refresh page, the same error occurs.
If input "t" -> "e", output "tえ"

**Expected behavior:**
When input "t" -> "e", output "て".

**Video/Screenshot link (optional):**
![2021-09-08_10-12-13](https://user-images.githubusercontent.com/84064473/132432718-ae9dc84f-38b9-41a3-92ef-45a3c5ce7d09.gif)

**Support ticket number submitted via odoo.com/help (optional):**
https://www.odoo.com/ja_JP/my/task/2641323

**Comment by yostashiro** [comment]
OPW: 2641323

**Comment by yostashiro** [comment]
The fix has landed on 13.0 and the upstream.  This issue can be closed.

13.0: https://github.com/odoo/enterprise/pull/24125
14.0: https://github.com/odoo/enterprise/pull/25921
15.0: https://github.com/odoo/enterprise/pull/26828
