### ISSUE TITLE
[14.0] feedparser version in requirements is not installable

### ISSUE THREAD

**Issue by matteoopenf** [odoo/odoo#76144]
@Impacted versions:
[14.0]
Steps to reproduce:
Build new image odoo 14 
Current behavior:
Error:
#17 372.2 Collecting feedparser==5.2.1 (from -r odoo/requirements.txt (line 6))
#17 372.3 Downloading https://files.pythonhosted.org/packages/91/d8/7d37fec71ff7c9dbcdd80d2b48bcdd86d6af502156fc93846fb0102cb2c4/feedparser-5.2.1.tar.bz2 (192kB)
#17 373.0 Complete output from command python setup.py egg_info:
#17 373.0 error in feedparser setup command: use_2to3 is invalid.
#17 373.0
#17 373.0 ----------------------------------------
#17 373.1 Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-ged5j_yf/feedparser/
#17 ERROR: executor failed running [/bin/sh -c python3 -m pip install $PIP_REQUIREMENTS --ignore-installed && python3 -m pip install -r odoo/requirements.txt]: exit code: 1
Expected behavior:
no Error on build 

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

Note:
We tried to rebuild using the lates version feedparser and the build go succesful

**Comment by nilshamerlinck** [comment]
Hi @matteoopenf this issue should be fixed soon, see https://github.com/odoo/odoo/pull/76135

**Comment by matteoopenf** [comment]
> Hi @matteoopenf this issue should be fixed soon, see #76135

Thanks so much

**Comment by Yenthe666** [comment]
Being resolved in 14.0 at https://github.com/odoo/odoo/pull/76273

**Comment by peacefulseeker** [comment]
@Yenthe666 , is it still in the resolution phase? can't install the 5.2.1 version at the moment with the same error output

**Comment by Yenthe666** [comment]
The dependency has been removed in https://github.com/odoo/odoo/commit/153ecbba47079982a2ec399f33bb246ba95550ba so it is no longer in the requirements. You have to update your Odoo instance.

**Comment by obayit** [comment]
This issue broke installing Odoo `11.0` requirements.txt
these packages also utilize `use_2to3`:
- suds-jurko==0.6
- vatnumber==1.2

**Comment by matteoopenf** [comment]
I have the same problem in odoo 11 now

**Comment by Yenthe666** [comment]
@d-fence little woopsie?

**Comment by nilshamerlinck** [comment]
Hi @obayit @matteoopenf you need to downgrade setuptools to the older version that has support for 2to3: `pip install "setuptools<58"`

**Comment by matteoopenf** [comment]
> Hi @obayit @matteoopenf you need to downgrade setuptools to the older version that has support for 2to3: `pip install "setuptools<58"`

Thanks for the advise I will try in two hours

**Comment by JonathanNEMRY** [comment]
@nilshamerlinck @obayit @matteoopenf Odoo 13.0  (not only <=11.0) also use at least vatnumber==1.2 --> so it is also not possible to build an odoo 13 with setuptools>=58

Am I right?
sources:
* https://www.mail-archive.com/devel-announce@lists.fedoraproject.org/msg02648.html
* https://github.com/odoo/odoo/blob/13.0/requirements.txt#L41
-jne

**Comment by nilshamerlinck** [comment]
correct @JonathanNEMRY 
(and to be complete odoo <= 12.0 also requires [`suds-jurko==0.6`](https://github.com/odoo/odoo/blob/12.0/requirements.txt#L39) which uses 2to3 as well)
