### ISSUE TITLE
Product Categories. translation possibility missing

### ISSUE THREAD

**Issue by kimasplund** [odoo/odoo#76142]
Impacted versions: 14

Steps to reproduce: 
In "Product Categories" the language translation possibility seems to be missing in the corner of name field. 
Current behavior:
Not possible to translate categories
Expected behavior:
Translation option like on any other place in odoo (Products, eCommerce Categories etc)

![Screenshot 2021-09-08 at 12 04 39](https://user-images.githubusercontent.com/13152668/132480535-1a12323d-094c-494e-b0de-9fb7b62de443.png)
vs.
![Screenshot 2021-09-08 at 12 05 13](https://user-images.githubusercontent.com/13152668/132480553-aba065fb-c5b0-4c81-a9ad-3b0a93fcd21a.png)

**Comment by pedrobaeza** [comment]
Translations were disabled in internal categories due to the computation of the full path name, so this is intended and not going to be re-added for now. Translations are available in other more critical areas like e-commerce categories.

Closing as no issue.
