### ISSUE TITLE
POS Configuration - tax included - help link goes nowhere

### ISSUE THREAD

**Issue by kimasplund** [odoo/odoo#76149]
Impacted versions: 14

Steps to reproduce:
Enable 
-Product Prices
Product prices on receipts
Tax-Included Price

Current behavior:
Gives a help link to nowhere
https://www.odoo.com/documentation/14.0/applications/finance/accounting/others/taxes/tax_included.html

![Screenshot 2021-09-08 at 13 32 04](https://user-images.githubusercontent.com/13152668/132494657-bd4f4ec2-5f10-4732-a16a-2b1533a09acf.png)

**Comment by sswapnesh** [comment]
@kimasplund  This has been Fixed 4 months ago 
PR: https://github.com/odoo/odoo/pull/70728

(Ref https://github.com/odoo/odoo/commit/598dda32f48ffeb64cbd398c6ffb1fe7577468f2#diff-2fec09ad1f0fdd71789955abc2444e145ac74d1428a8d6eae0860035055ba341L311)


This is the correct URL: https://www.odoo.com/documentation/14.0/applications/finance/accounting/taxation/taxes/B2B_B2C.html
