### ISSUE TITLE
Odoo is not compatible to psutil 3.0.1

### ISSUE THREAD

**Issue by csrocha** [odoo/odoo#7615]
PSUTIL (https://pypi.python.org/pypi/psutil) use memory_info until get_memory_info.

File affected: openerp/service/server.py

    diff --git a/openerp/service/server.py b/openerp/service/server.py
    index fdd95a7..0405e8d 100644
    --- a/openerp/service/server.py
    +++ b/openerp/service/server.py
    @@ -695,7 +695,7 @@ class Worker(object):
                 _logger.info("Worker (%d) max request (%s) reached.", self.pid, self.request_count)
                 self.alive = False
             # Reset the worker if it consumes too much memory (e.g. caused by a memory leak).
    -        rss, vms = psutil.Process(os.getpid()).get_memory_info()
    +        rss, vms = psutil.Process(os.getpid()).memory_info()
             if vms > config['limit_memory_soft']:
                 _logger.info('Worker (%d) virtual memory limit (%s) reached.', self.pid, vms)
                 self.alive = False      # Commit suicide after the request.

**Comment by spadae22** [comment]
Yup, see that error also

**Comment by gdgellatly** [comment]
I thought that was fixed weeks ago,  but in any case it does say v2 in the
requirements file.

**Comment by mart-e** [comment]
Fixed at 3940a09
