### ISSUE TITLE
[13][14] How to catch event Sale Order Paid on another Add-ons in Odoo ERP ?

### ISSUE THREAD

**Issue by thobn24h** [odoo/odoo#76187]
Hello,

I'm developing new add-on in Odoo ERP, and a want to catch Sale Order Paid event in this module ( its mean when a Sale Order is Paid, It will trigger an event in my add-on to execute some extra action ).

- Is there any event dispatch mechanic for this situation ?
- How to solve this problem ?

Thank you

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
