### ISSUE TITLE
Onchange issue on the Date / Datetime field

### ISSUE THREAD

**Issue by ErpMstar** [odoo/odoo#76222]
Impacted versions: 12

Steps to reproduce: If we set a onchange function for a Date field and if that onchange function has some code to raise a ValidationError or UserError.

Current behavior:  Then the onchange function keeps executing if you click on the Date field to select, means without changing the date, it executes. So the error popup appear again and again. So not able to change the date. 

Expected behavior:  As I checked with Char field it works fine. So the onchange function has to be only executed for the Date field  when the current value in the field is different from the last value.

```
Sample code:
@api.onchange('today_date')
def change_date(self):
        if self.today_date == datetime.datetime.today().date():
            raise ValidationError("Selected today's Date >>>>>>>>>>>>>>")
```

When I select todays date in the field, it raise the error. Now I want to select some other date and clicked the field to change, before I change it gives the error again and again.

**Comment by ErpMstar** [comment]
I faced this issue with Odoo ver 12
Odoo 13 and 14 don't have this type of issue.

**Comment by pedrobaeza** [comment]
If this not found in v13/v14, and as v12 is end of life in 3 weeks, we can consider this fixed in later versions and won't fix in v12, so you should go to newer versions of you want to have it fixed.

**Comment by ErpMstar** [comment]
This is not a solution!
