### ISSUE TITLE
Division by zero in _get_price_reduce

### ISSUE THREAD

**Issue by robch2342** [odoo/odoo#7622]
If a sale.order.line has a value of 0 in the product_uom_qty field, there will be a division by zero in _get_price_reduce.

This error can be seen in the website_quote module. If the Change Quantity template is active, reducing the number of items to 0 will make it impossible to change it again (through the template).

```python
def _get_price_reduce(self, cr, uid, ids, field_name, arg, context=None):
        res = dict.fromkeys(ids, 0.0)
        for line in self.browse(cr, uid, ids, context=context):
            res[line.id] = line.price_subtotal / line.product_uom_qty
        return res
```

should be something along the lines of

```python
def _get_price_reduce(self, cr, uid, ids, field_name, arg, context=None):
        res = dict.fromkeys(ids, 0.0)
        for line in self.browse(cr, uid, ids, context=context):
            if line.product_uom_quantity != 0:
                res[line.id] = line.price_subtotal / line.product_uom_qty
        return res
```

**Comment by jpoa** [comment]
Greetings,

     Can this issue be evaluated? Preventing a situation where a division by zero can happen is good policy in any case. I see no drawback making the extra check in this case.
