### ISSUE TITLE
[7.0] Bug on Barcode Scanner for serial number

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#7631]
Hello Odoo support,

In openerp version 7,
I found a bug when I scan serial number on delivery order.

Step to reproduce:
1.  Create a sale order with product buy and make to order, and confirm it
2.  The system will generate a purchase order, we confirm the purchase order.
3.  The system will generate an incoming shipment, we go to incoming shipment.
4.  Click the serial number button on incoming shipment line, and add a new line.
5.  On here I input it by barcode scanner(serial number already in barcode), and on this step its works fine.
6.  I go to delivery order that related to sale order, I click the serial number.
7.  I add a line and check the existing serial number check.
8.  When I input it by barcode scanner it doesn’t work.

Expected behavior:
It works like when I input it on incoming shipment.

I tested on runbot, and the behavior is the same.

Video to explain things:
https://falinwa-my.sharepoint.cn/personal/falinwa1_falinwa_partner_onmschina_cn/_layouts/15/guestaccess.aspx?guestaccesstoken=xQAg%2bqOY2vKKTTy4%2bl%2f%2fCTPuiJ7YkGK8zGIGJndYgg0%3d&docid=0d304abf518c946ecb0d8fbf4cc18ce1c

**Comment by Yenthe666** [comment]
Hi @falinwa,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
