### ISSUE TITLE
[8.0] a constraint should prevent account move lines modification generated by bank statement

### ISSUE THREAD

**Issue by fclementic2c** [odoo/odoo#7633]
How to reproduce:
- validate/reconcile a bank statement -> entries are generated (make sure it is in draft to modify entry)
- Go to the entry and change amount (entry mut be balanced).

Problem:
You now have a entry with a different amount compares to the bank statement lines.

**Comment by NL66278** [comment]
See this OCA module that solves your problem: https://github.com/OCA/account-financial-tools/tree/10.0/account_constraints
For 7.0 I have a PR on this module that solves some problems with cancelling the transaction in error from the bank-statement. I am not sure this is still needed on later versions.

**Comment by Yenthe666** [comment]
Hi @fclementic2c ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
