### ISSUE TITLE
Odoo 14 raise exception.with_traceback(None)

### ISSUE THREAD

**Issue by zloslawa** [odoo/odoo#76337]
Impacted versions:  14

Steps to reproduce: module install - based on hr module

Current behavior:

Traceback (most recent call last):
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/http.py", line 640, in _handle_exception
    
return super(JsonRequest, self)._handle_exception(exception)
  
File "/opt/bitnami/odoo/lib/odoo-14.0.post20210710-py3.8.egg/odoo/http.py", line 316, in _handle_exception
    
raise exception.with_traceback(None) from new_cause
odoo.tools.convert.ParseError: while parsing /bitnami/odoo/data/addons/14.0/dzialrekrutacji/data/dzialrekrutacji_data.xml:5, near
<record id="dep_administration" model="dzialrekrutacji.oddzial">
          <field name="name">Administracja</field>
        </record>

dzialrekrutacji_data.xml   v

` <record id="dep_administration" model="dzialrekrutacji.oddzial">
      <field name="name">Administracja</field>
    </record>

    <record id="dep_sales" model="dzialrekrutacji.oddzial">
      <field name="name">Oddzial</field>
    </record>

    <record id="res_partner_admin_private_address" model="res.partner">
        <field name="name">Administrator</field>
        <field name="company_id" ref="base.main_company"/>
        <field name="email">example@example.com</field>
        <field name="image_1920" type="base64" file="base/static/img/avatar_grey.png"/>
        <field name="type">private</field>
    </record>`

Expected behavior: installing module

I've tried to change up .xml file but it doesn't work. I'm new to this, please any suggestions are welcomed.

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a development question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
