### ISSUE TITLE
[14.0] Wysiwyg error viewing any editable page on Firefox.

### ISSUE THREAD

**Issue by jeroen7s** [odoo/odoo#76348]
Impacted versions: 14.0

Steps to reproduce: 
Visit latest Runbot environment in Firefox: ex. https://9895364-14-0-all.runbot68.odoo.com/
Login as Administrator (or any other user with Website Editor rights)
Go visit home-page, or any page with Website Editor functionality (like the portal pages).

Current behavior:
Error occurs loading variables.scss.css
In debug=assets, you see the error is on /account/static/src/scss/website.assets_wysiwyg/variables.scss.css

Expected behavior:
No Error occurs

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/10954827/132863060-1956eae8-0f80-4ca3-b250-afac7ce4e217.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by jeroen7s** [comment]
Seems to be some plugin interfering, doesn't reproduce in Private Window (Without extensions)

**Comment by pedrobaeza** [comment]
Yes, I'm not able to reproduce it.

**Comment by jeroen7s** [comment]
Figured out what the Culprit is
In case it occurs to anyone else: setting LocalCDN extension to block Google Fonts (default = on) breaks the page.
