### ISSUE TITLE
website optional overwritten after module update

### ISSUE THREAD

**Issue by funkring** [odoo/odoo#764]
After making an module update template attribute optional was reset to origin, following patch fix the problem:

<pre>
diff --git a/openerp/tools/convert.py b/openerp/tools/convert.py
index 811f6c1..6d4ebf8 100644
--- a/openerp/tools/convert.py
+++ b/openerp/tools/convert.py
@@ -949,8 +949,19 @@
         if el.get('primary') == 'True':
             record.append(Field('primary', name='mode'))
         if el.get('optional'):
-            record.append(Field(el.get('optional'), name='application'))
-
+            #funkring.net begin
+            # get current value
+            
+            cr.execute("SELECT application FROM ir_ui_view v "
+                        " INNER JOIN ir_model_data m ON m.model='ir.ui.view' AND m.res_id=v.id "
+                        " WHERE  m.module=%s AND m.name=%s", (self.module, tpl_id))
+            optional_cur = cr.fetchone()
+            
+            if optional_cur and optional_cur[0]:
+                record.append(Field(optional_cur[0], name='application'))
+            else:
+                record.append(Field(el.get('optional'), name='application'))
+            #funkring.net end
         return self._tag_record(cr, record, data_node)
 
     def id_get(self, cr, id_str):
</pre>

**Comment by Yenthe666** [comment]
Dear @funkring,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
