### ISSUE TITLE
[Bug] Stable odoo version

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#7642]
1. Create product template.

2. Create option and values

3. Click on variable jump button to assign price.

duplicate key value violates unique constraint "product_attribute_value_product_product_rel_att_id_prod_id_key"
DETAIL: Key (att_id, prod_id)=(1, 534) already exists.

Just no other related products, first product created and bug produced.

Fresh new product created

When you will fix this issue ?

**Comment by sle-odoo** [comment]
Closing as the issue was fixed in the meantime i suppose.
Regards
