### ISSUE TITLE
[8.0] Json serialization error on jsonRpc request

### ISSUE THREAD

**Issue by yannprada** [odoo/odoo#7645]
**Json serialization error on jsonRpc request**

Impacted versions:
- 8.0

Steps to reproduce:

(tested on runbot 8.0)
1. enable portal on admin user
2. grab a sale order
3. open browser console
4. add this code below
5. click on one payment option

``` javascript
$('.payment_acquirers button').on('click', function(event) {
    event.preventDefault();
    event.stopPropagation();
    var $form = $(event.currentTarget).parents('form');
    var acquirer_id = '1';
    openerp.jsonRpc('/shop/payment/transaction/' + acquirer_id,  'call', {})
      .then(function (data) {
        $form.submit();
    });
})
```

Current behavior:
- Error raised, payment.transaction record not created, form not submited

```
2015-07-16 13:53:57,507 18652 ERROR json openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/odoo/server/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/server/openerp/http.py", line 581, in dispatch
    return self._json_response(result)
  File "/home/odoo/server/openerp/http.py", line 519, in _json_response
    body = simplejson.dumps(response)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 321, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/dist-packages/simplejson/encoder.py", line 237, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/dist-packages/simplejson/encoder.py", line 311, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/dist-packages/simplejson/encoder.py", line 213, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <BaseResponse 235 bytes [302 FOUND]> is not JSON serializable
```

Expected behavior:
- payment.transaction record created, form submited

Note:

This is just a 'hack' to reproduce the error I have with a module I made. All the relevant code looks like the little JS script on step 4. My module is supposed to use the functionnalities already in place, and should just fix the missing bits for the modules portal_sale and payment to work together.

I almost copy pasted the JS code that creates the payment.transaction record in the context of the website_sale module. So I'm not sure why it's not working for the portal_sale module.

**Comment by yannprada** [comment]
@xmo-odoo can you look at this please ?

**Comment by xmo-odoo** [comment]
@yannprada looks like the call fails its precondition checks and you're getting a redirection (which was apparently left over when the endpoint was converted from regular HTTP to JSON at revision ed51e843 /cc @tde-banana-odoo)

The code of the endpoint first checks that `order and order.order_line and acquirer_id` with order being `request.website.sale_get_order(context=context)`, if the test fails the call also does (and redirects, it should probably return an error code instead). So I'm guessing there's no sale order configured/set up/installed on the request. Can't help you any further though, you may want @Gorash for that.

**Comment by Yenthe666** [comment]
Hi @yannprada,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by yelizariev** [comment]
The redirection is still there: https://github.com/odoo/odoo/blob/10.0/addons/website_sale/controllers/main.py#L817
while route type is still json:
https://github.com/odoo/odoo/blob/10.0/addons/website_sale/controllers/main.py#L795
I'll come back with a possible fix soon

**Comment by yelizariev** [comment]
Sorry, I'm not going to provide a fix in near future. 
@Yenthe666 Can we reopen the issue? It's all the same for 10.0 version at least.
