### ISSUE TITLE
[14.0] Error on creating Journal Items from Kanban View

### ISSUE THREAD

**Issue by m-gosai** [odoo/odoo#76543]
Impacted versions: 14.0 Enterprise

Steps to reproduce: 

- Go to Runbot
- Go to Accounting > Journal Items > Kanban View and Click on Button 'Create'

Current behavior:

AssertionError: convert amount from unknown currency

Expected behavior:
Should be able to create Journal Items from Kanban? Or should it block the creation.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):
![Journal-Items-Odoo](https://user-images.githubusercontent.com/87031943/133338029-bc44ee8a-0823-40fc-8550-ffc4a7bf040c.png)

**Comment by ray-odoo** [comment]
Journal Items are not created individually with any standard workflow in Odoo - but I can replicate the issue reported.

This can be resolved by using the CREATE tab on the Kanban View definition (via inherited View):

`create="0"`
