### ISSUE TITLE
[14.0] account: account move line updated even if it posted

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#76657]
Impacted versions: 14.0

Steps to reproduce:
- create a bank statement with one operation
The account move created (and posted) is 
512002 Bank to 512001 Suspense Account
![image](https://user-images.githubusercontent.com/16716992/133595081-b44dd3fd-7c33-4ba2-9d2b-ca325c39c0b8.png)
- Open the reconcile widget, select a partner and validate (Open Balance)
Now the posted account move is
![image](https://user-images.githubusercontent.com/16716992/133595308-2e1cac82-e47d-4ed4-b9b2-50821eae6028.png)

Are you sur it is legal to do that ? To modify an account on posted aml ? We should create a new account move 512001 (suspens) to 411000 (create a new payment), no ?
@qdp-odoo @oco-odoo @smetl @alexis-via 

https://github.com/odoo/odoo/blob/14.0/addons/account/models/account_bank_statement.py#L1244

https://user-images.githubusercontent.com/16716992/133595444-2a50200a-1d1d-4c22-a98c-a1007c0fb5d0.mov

**Comment by alexis-via** [comment]
@fmdl I agree with you, an accounting software should not modify a posted move. A simple solution would be to keep the move to the suspense account in draft state, and then modify it when the statement line is processed.

**Comment by fmdl** [comment]
OPW #2648755

**Comment by tsb-odoo** [comment]
@fmdl Consider it this way... Posted entries in Odoo are somehow in a "fog" (in the meaning of "Brouillard Comptable") and get really definitive once they are protected by a Lock Date. Thinking so, you'll notice that it's not possible to set the Lock Date if any Journal Entry affects any Suspense Account prior to this Lock Date. 

Doing so, we tend towards an optimum (both respect of the law and user-friendliness), considering it has never been published nor impacted anyone else but the accountant himself. Entries about "bank reconciliation" have no direct impact on anyone else but the finance department itself. The impact is indirect (follow-up reports, aged reports and so on...) 

A few months ago and at first glance, I had the exact same reaction as yours. But considering the need for flexibility (the users converting their ERP to Odoo and so on, we made those decisions.) 

The idea of adding new entries from the suspense account to the final account (the one we want to reconcile the items on) will have other side effects too (very little value IMHO to keep track of entries being posted on the suspense account ; less readable once reconciled).

One last thing, user can set the Lock Date every day at the end of the day (or every morning when they know for sure that "yesterday is over") if they want to follow the restrictive interpretation of regulations.

**Comment by qdp-odoo** [comment]
so, @tsb-odoo should we close this issue?

**Comment by tsb-odoo** [comment]
Yes
