### ISSUE TITLE
[8.0] Transfering no items (empty wizard/popup) sets receipt to done

### ISSUE THREAD

**Issue by intero-chz** [odoo/odoo#7669]
**Transfering no items (empty wizard/popup) sets receipt to done**

Impacted versions:
- 8.0

Steps to reproduce:
1. create or use receipt (stock) which is ready to transfer (easiest way is one with only one move)
2. open transfer wizard (button transfer)
3. remove all lines
4. transfer

Current behavior:
- receipt is set to done
- move lines are set to done

Expected behavior:
- message popup which could say "Nothing was transfered"
- receipt is not done
- moves are not done

**Comment by msteinfeld** [comment]
any news here?

**Comment by Yenthe666** [comment]
Hi @intero-chz,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
