### ISSUE TITLE
Public LiveChat don't take neither the correct timezone nor the correct translation

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#7670]
Hi,

I activate the public LiveChat n my website. Whatever the conf I use on the Public User and also in the .conf for the timezone the date date still to be displayed in english.
Yet everithing is set on Europe/Paris and the Public user is set with French Language.
regards

**Comment by pedrobaeza** [comment]
It depends on the timezone of the "Public user" AFAIK. Closing for triaging this.
