### ISSUE TITLE
[14.0] Does not stay in Apps after module upgrade

### ISSUE THREAD

**Issue by miro-igov** [odoo/odoo#76737]
Impacted versions: 14.0

Steps to reproduce: Click on Apps, click on three vertical dots in top right corner of an app and select Upgrade.

Current behavior: After upgrade of the app loads Discuss page

Expected behavior: Should stay in Apps or if Module info is selected from the three vertical dots, should stay in module info after upgrade.

Video/Screenshot link (optional):  https://streamable.com/bvkfjx

Support ticket number submitted via odoo.com/help (optional):

**Comment by sswapnesh** [comment]
Duplicate of https://github.com/odoo/odoo/issues/15295
