### ISSUE TITLE
'mrp.bom' object has no attribute 'product_uos'" while evaluating, mrp_byproduct still use  'product_uos'

### ISSUE THREAD

**Issue by likaiyuan** [odoo/odoo#7674]
/addons/mrp_byproduct/mrp_byproduct.py", line 99, in action_confirm
    if qty2 and production.bom_id.product_uos.id:
ValueError: ""'mrp.bom' object has no attribute 'product_uos'" while evaluating
u'action_confirm()'" while evaluating
u'action_ship_create()'

**Comment by sle-odoo** [comment]
Hi,
This was solved by rev https://github.com/odoo/odoo/commit/2d407de5d4eddada0d46b1ed2b0d43fdc749deda#diff-8171e75926f18dbbf37e22df8085fb9b

Regards
