### ISSUE TITLE
`total` from `digits` parameter in Float field entirely ignored?

### ISSUE THREAD

**Issue by ludwiktrammer** [odoo/odoo#7676]
`Float` field takes a `digits` parameter which ([according to the documentation](https://www.odoo.com/documentation/8.0/reference/orm.html#openerp.fields.Float)) is:

> a pair (total, decimal), or a function taking a database cursor and returning a pair (total, decimal)

I always assumed that this is used to set up [`NUMERIC` columns' precision in PostgreSQL](http://www.postgresql.org/docs/9.4/static/datatype-numeric.html#DATATYPE-NUMERIC-DECIMAL). Today, looking through Odoo's code I discovered that's not the case. I later confirmed this with some experiments. Odoo never configures precision when setting up NUMERIC columns.

Looking at the code, the `digits` attribute seems to be used in the following ways:
- if it is set at all (to any value) PostgreSQL column type is set to `NUMERIC`. Otherwise it is set to `DOUBLE PRECISION` ([source](https://github.com/odoo/odoo/blob/449b50face937b47a1771d03e8dd6435d91112ee/openerp/models.py#L169)).
- `decimal` parameter is used to round field's value in Python ([source](https://github.com/odoo/odoo/blob/449b50face937b47a1771d03e8dd6435d91112ee/openerp/fields.py#L1059))

`total` parameter seems to be completely ignored and not used for anything.

Is this a bug or is this an expected behaviour? Shouldn't the precision setting be reflected in PostgreSQL? If this is expected behaviour why require users to set `total` at all? Shouldn't then `digits` be deprecated and replaced with something like `decimal_rounding` that takes a single number (the one that is actually used)?

@rco-odoo are you able to commend on this?

**Comment by gfcapalbo** [comment]
:+1:  same finding here, when tying to manage geographical coordinates , where I wanted to impose (total, decimal).

**Comment by pedrobaeza** [comment]
Is this still happening? Syntax of the `digits` has changed in latest versions, so maybe the problem has been solved.

**Comment by Yenthe666** [comment]
Hi @ludwiktrammer ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 9 is no longer supported as Odoo only supports three versions (10.0, 11.0, 12.0 at the moment).
If you can still reproduce this issue on Odoo 10, Odoo 11 or Odoo 12 we encourage you to create a new bug report.

Regards,
Yenthe
