### ISSUE TITLE
Copy purchase order, bid and origin fields stay null

### ISSUE THREAD

**Issue by anajuaristi** [odoo/odoo#7689]
Steps:
Make a draft purchase order
Duplicate 
Fields origin and bid stay null value

**Comment by Yenthe666** [comment]
@anajuaristi is that really a problem though? I find it a bit logical that it gets set to null?

**Comment by pedrobaeza** [comment]
I also see this behavior reasonable. Generate another purchase order from the bid if you want to keep that field. Closing this for triaging it.
