### ISSUE TITLE
[13.0] Inherits fields write losing value.

### ISSUE THREAD

**Issue by bizzappdev** [odoo/odoo#76946]
Impacted versions: 13.0

Steps to reproduce:
User product.product and product.template (will be reproducible with any module which have `inherits` relation between models

Have an inherited write method of Product.template() or inverse method of any field of template. if we are updating any other object/model or calling any method which has self.invalidate_cache called.  E.g write anything in the product.pricelist.item.

for the code you can check the demo module we have created.
https://github.com/BizzAppDev-Systems/odoo_bug_reports/blob/13.0/odoo_product_write_bug/models/product.py

Current behavior:

From the Product.Product View from the front end, if you will change any 2 fields which are from product.template model.
it will set the values for both fields to False.

Expected behavior:

It should keep the values as passed from the webclient.

Video/Screenshot link (optional):

https://github.com/BizzAppDev-Systems/odoo_bug_reports/blob/13.0/odoo_product_write_bug

**Comment by Yenthe666** [comment]
@yelizariev have you seen something similar before? Could you have a look?

**Comment by yelizariev** [comment]
I don't really know why it happens and unfortunately I can't work on this issue. But following may help to speed up fixing it:

1. Is it only v13?
2. could you send a PR with a test? Probably adding required inherits here https://github.com/odoo/odoo/blob/14.0/odoo/addons/test_inherit/models.py

**Comment by bizzappdev** [comment]
> I don't really know why it happens and unfortunately I can't work on this issue. But following may help to speed up fixing it:
> 
> 1. Is it only v13?
> 2. could you send a PR with a test? Probably adding required inherits here https://github.com/odoo/odoo/blob/14.0/odoo/addons/test_inherit/models.py

1. I have not tested for v14 or v12.
2. Yes we will add the automated test case and will update here the MR

**Comment by bizzappdev** [comment]
@yelizariev IMO https://github.com/odoo/odoo/blob/14.0/odoo/addons/test_inherits/models.py will be proper place as it is related to inherits.

**Comment by bizzappdev** [comment]
@yelizariev PR is here https://github.com/odoo/odoo/pull/77042/files as requested.

**Comment by bizzappdev** [comment]
> > I don't really know why it happens and unfortunately I can't work on this issue. But following may help to speed up fixing it:
> > 
> > 1. Is it only v13?
> > 2. could you send a PR with a test? Probably adding required inherits here https://github.com/odoo/odoo/blob/14.0/odoo/addons/test_inherit/models.py
> 
> 1. I have not tested for v14 or v12.

In v14 it is working properly. I have tested it

**Comment by bizzappdev** [comment]
OPW: 2657461

**Comment by rco-odoo** [comment]
Fixed by #82901.
