### ISSUE TITLE
When deleting posts in forum i get an error

### ISSUE THREAD

**Issue by adrien59cadri** [odoo/odoo#7695]
![image](https://cloud.githubusercontent.com/assets/536398/8780043/e13fc048-2f06-11e5-8516-644c846f55bd.png)

I just selected the existing posts and deleted....

It is not clear if this is a normal error: "you don't have the right to do this" because of the log showing "not enough karma", anyway this handle exception looks dirty for the end users

**Comment by JKE-be** [comment]
This should be done from front end (from the forum directly).
In front end, the KarmaError is catched... and display with a proper way.
This menu is more for admin, superviser, moderator,... who should have karma... and so never have this error.
