### ISSUE TITLE
v8: !record with XMLID for another module fails silently

### ISSUE THREAD

**Issue by lepistone** [odoo/odoo#7696]
this block

``` yaml
!record {model: res.company, id: base.main_company}:
  security_lead: 2.0
```

used to work in v7, but in v8 it fails silently. The reason is that it calls `_get_id` in `base/ir/ir_model.py`. This looks up for `my_module.base.main_company` instead of just `base.main_company`.

Moreover, in `yaml.py` the exception is silenced.

Thanks!

**Comment by rafaelbn** [comment]
:+1:

**Comment by Yenthe666** [comment]
Hi @lepistone,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
