### ISSUE TITLE
[IMP] CLA file path

### ISSUE THREAD

**Issue by mohamedhagag** [odoo/odoo#7697]
it should be clarified that the file path is **odoo**/doc/cla/... etc .

first time contributers may think it's relative to the module not odoo dir.

or am I the only one ;)  .

**Comment by mart-e** [comment]
Hello,

I assume you make reference to the `doc/cla/sign-cla.md` content.
I have to disagree. The first doc in the path is the name of the repository containing your code so it's not necessary `odoo`, you can choose whatever you want when cloning the code so it may be misleading. Moreover, GitHub makes automatic link to the existing file if we specify the exact path so it's better to keep it like this.
