### ISSUE TITLE
[7.0] Attach a file with accent keep uploading in chatter on Mac (Chrome/Safari)

### ISSUE THREAD

**Issue by qpeyramale** [odoo/odoo#770]
Hello,

When we try to attach a file with accent (like 'Capture d'écran.png'), it keeps uploading.
The attachment is created but the link with the record/message is not set.
This happens only on Mac.

![image](https://cloud.githubusercontent.com/assets/7935472/3387860/fcb133f6-fc81-11e3-9890-e3d2f5648bae.png)

Anybody got this issue?
Thank you
Regards

**Comment by Elastino** [comment]
> This is a Chrome / MacOSX issue only. So it should work with firefox on MacOSX.
No. Safari/MacOSX and Chrome/MacOSX both have this problem. 
Furthermore, these files cannot be downloaded even if these file are uploaded from Windows with HTTP server side 500 error due to ascii-unicode conversion error.

**Comment by Elastino** [comment]
Also, this behavior affects all 2-bytes language users such as Korean, Chinese and Japanese.

![default](https://cloud.githubusercontent.com/assets/8371666/6593232/01771766-c81a-11e4-8ff8-9d9826365283.png)

Try this file with "오두.png"

**Comment by Yenthe666** [comment]
Dear @qpeyramale,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
