### ISSUE TITLE
Email Templates can be accessed and changed by non-Admin user through URL

### ISSUE THREAD

**Issue by SanathT** [odoo/odoo#7700]
Impacted versions:

 - 8.0

Steps to reproduce:

 1. Login as admin and go to Settings -> Technical -> Email -> Templates
 2. Note down the action id (i.e. value after "action=") in the URL.
 3. Logout from the system and login as a non admin user
 4. Change the action id in the URL to the action id noted earlier and access the URL.

Current behaviour:

 - Email templates list is displayed for non-admin user as well
 - Non-admin user can access individual email templates and edit and save them.

Expected behaviour:

 - Email templates should only be accessible and editable to the Admin user.

**Comment by Yenthe666** [comment]
Hmm I've tested this and you're currect. Its even in the very last 8.0 version.
This is a serious flaw since even an user with barely ANY rights can access these templates.
@odony and @antonylesuisse this should be looked at ASAP.

**Comment by Yenthe666** [comment]
Another note. This problem is also affecting all master versions, up until the latest one.

**Comment by odony** [comment]
Email templates are not designed to be viewable or editable only by administrators. They are a common tools shared many employees according to their needs, and every employee is allowed to view, use, create and edit templates.
If you'd like to make them only editable by the administrator in your company it is quite easy to accomplish by configuring appropriate access rights (see the [functional](https://doc.odoo.com/book/8/8_20_Config/8_20_Config_accessRights/#managing-access-rights) and [technical doc](https://www.odoo.com/documentation/8.0/reference/security.html)).
You could also restrict edition of a templates to only the creator of that template, by adding a "record rule" with this domain ``[('create_uid', '=', user.id)]``. This would allow some level of sharing between employees.

**Comment by Yenthe666** [comment]
@odony is that really a good idea to have publicly accessible? Even a user with just access to anything in the backend can edit the templates. He/she could insert new texts, images, links, malicious content, ...
Shouldn't there be atleast a basic limitation in this?

**Comment by odony** [comment]
There's a difference between public and internal. Email templates are accessible to internal users - i.e. employees. In contexts where employees are not to be trusted, a full review of access rights is strongly recommended in all cases, not just for email templates. The defaults are only meant to be generic and non-obtrusive for new setups (and in this context, enabling and fostering collaboration often beats establishing strong policies).

The description of this issue asks for the list of templates to be accessible/viewable only by the administrator. That is clearly not something we want to do - they are meant to be shared.
But even preventing edits would be a bit too restrictive - if we block this by default we'll make it very hard for a team to collaboratively work and improve their templates, just for the sake of blocking rare cases of mischief (the list of templates is typically used in the Marketing related modules too, they're an important part of marketing strategies).

If you have a suggested change/patch to improve this for the future without compromising the simplicity of the collaboration/sharing, we'll be happy to consider it.

**Comment by Yenthe666** [comment]
Hmm I didn't know this was the whole purpose and honestly thought this was a problem.
After reading your detailed explanation (thanks!) I'll have to agree that this is fine. I guess you could close this issue then :+1:
