### ISSUE TITLE
Date picker only displays range of 10 years forwards and backwards from the current year.

### ISSUE THREAD

**Issue by SanathT** [odoo/odoo#7701]
The date-picker widget only displays a range of 10 years to the past and 10 years to the future from the current selected year.

This is not very user friendly since the user has to select several years progressively in order to expand the year range to reach a certain year (e.g. trying to select 1971 as birth year starting from 2015)

**Comment by Yenthe666** [comment]
Hi @SanathT,

Thank you for your report - this is no longer the case in newer versions. You can now go forward and backwards for roughly 100 years.

Regards,
Yenthe
