### ISSUE TITLE
[8.0] translation of email template created/overwritten every module update

### ISSUE THREAD

**Issue by funkring** [odoo/odoo#7704]
odoo/openerp/addons/base/ir/ir_translation.py

Here is the correction, the EXISTS query with  ONLY Clause not work

<source>
  # Step 3: insert new translations
        cr.execute("""INSERT INTO %s(name, lang, res_id, src, type, value, module, state, comments)
            SELECT name, lang, res_id, src, type, value, module, state, comments
              FROM %s AS ti
              WHERE NOT EXISTS(SELECT irt.id FROM %s AS irt WHERE %s);
              """ % (self._parent_table, self._table_name, self._parent_table, find_expr))
</source>

**Comment by Yenthe666** [comment]
Hi @funkring ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
