### ISSUE TITLE
POS order of products with numbers in wrong order.

### ISSUE THREAD

**Issue by kimasplund** [odoo/odoo#77041]
Impacted versions: 14

Steps to reproduce: 
Add variants of product with numbers. Ex 1pcs, 5pcs, 10pcs

Current behavior:
Lists products in POS by the numbers 1, 10, 5, etc

Expected behavior:
Would be nice if it listed them in order like 1, 5, 10

Actually on closer look it seems to list them totally random
<img width="1206" alt="Screenshot 2021-09-23 at 14 26 51" src="https://user-images.githubusercontent.com/13152668/134499150-d2ae1cf3-079b-49ec-97f4-8a4221e6613a.png">

**Comment by Yenthe666** [comment]
It's a text field so it is not ordering as numbers. Only way to influence is placing products under categories which you can give a sequence.
