### ISSUE TITLE
[8.0] email_template extension ability

### ISSUE THREAD

**Issue by funkring** [odoo/odoo#7706]
Is it possible to add an function for extending the passed vars for template rendering?

<pre>
...
 def _get_render_env(self, cr, uid, template, model, res_ids, variables, context=None):
        return variables
...
</pre>

**Comment by Yenthe666** [comment]
Hi @funkring ,

Thank you for your suggestion and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
You can always extend the method / override it and add your own desired changes.

Regards,
Yenthe
