### ISSUE TITLE
Thousand separator in dutch localization doesn't work with keypad (dot)

### ISSUE THREAD

**Issue by lfreeke** [odoo/odoo#7707]
When we put a .(dot) in the Thousands Separator field it not possible to use the . on the numeric keypad. 
Separator Format is set [3,0]

[example with . in thousands separator field] 
create a invoice and fill in the price of the product with a . 
-> 14.00 save or update the invoice -> outcome = 1400,00 instead of 14.00

[Example without the . thousands separator field]
create a invoice and fill in the price of the product with a . 
-> 14.00 save or update the invoice -> outcome = 14.00

**Comment by lfreeke** [comment]
:+1: test

**Comment by NL66278** [comment]
For 8.0 solved by extra module: https://github.com/Comunitea/external_modules/tree/8.0/web_decimal_numpad_dot

**Comment by Yenthe666** [comment]
Hi @lfreeke,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
