### ISSUE TITLE
[8.0] Init hooks not run when reinstalling an uninstalled module

### ISSUE THREAD

**Issue by pablocm-aserti** [odoo/odoo#7708]
Init hooks are not run when installing a module that previously was uninstalled.

Impacted versions:
All

Steps to reproduce:
 1. Install a module who has pre_init_hook or post_init_hook in its __openerp__.py
 2. Uninstall the module
 3. Install the module again, this time the hooks are not run and the module is not properly initialized

Current behavior:
The module is not initialized when installed the second time

Expected behavior:
The module should be initialized

Possible solutions:
Change the way it is checked if it is a new install [here](https://github.com/odoo/odoo/blob/9abf868948d33a47873d6d75da7fce8815ca8fca/openerp/modules/loading.py#L145) to use the same than [here](https://github.com/odoo/odoo/commit/8ff7230e2d6d49e5b880fbee9589de1e8a78fb95) (it is the same bug)

**Comment by KangOl** [comment]
Thanks for the report. It have been fixed (reference above)
