### ISSUE TITLE
[master]Currency not correctly displayed

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#7713]
Hi,

The currency symbol is not correctly displayed :
![host1](https://cloud.githubusercontent.com/assets/1043935/8844495/f7f24156-3115-11e5-9645-66904d49cb2e.jpeg)

Neither on the website front end :
![host1](https://cloud.githubusercontent.com/assets/1043935/8844512/228e1d54-3116-11e5-8ffa-1204b071a9ac.jpeg)

**Comment by mart-e** [comment]
Hello,

Thank you for the report but:

- master is the development version for test only, so there is definitely plenty of bugs, no need to report them before the stabilisation period
- not displayed correctly how? wrong symbol? wrong position?

I am closing as report for master. If you can reproduce in stable, don't hesitate to reopen and explain clearly the issue. Please check the [issue format](https://github.com/odoo/odoo/wiki/Contributing#reporting-issues) for opening bugs.
