### ISSUE TITLE
[Master]Messaging menu no more consistentt

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#7714]
Hi,

On the master, is it normal that calendar, notes and contacts are no more inside the messaging menu?

regards

**Comment by mart-e** [comment]
Hello,

Yes, the messaging menu was a bit a "put everything else there" menu. We try a new approach of separating everything by apps to be more clear. Finding the calendar menu in messaging section is definitely not intuitive IMHO.
Same as for #7713, master is still in dev and menus may still change before v9, it's only a preview now, no need to open bug report for this version.

**Comment by flotho** [comment]
@mart-e Thanks for your info
