### ISSUE TITLE
Access errors on the Partner form

### ISSUE THREAD

**Issue by dreispt** [odoo/odoo#7719]
Found on v 8.0.
To reproduce on runbot:

- Create a new test user, with groups: HR Employee and Project User
- Login as the test user and open an existing Project Issue form
- In the Project Issue form, follow the link for the Contact

When opening the Partner form you will get the error:

    AccessError
    Sorry, you are not allowed to access this document. Only users with the following access level are currently allowed to do that:
    - Sales/See Own Leads
    - Public
    - Sales/Manager
    - Portal
    (Document model: res.partner.grade) 

In other environments I have seen a user with no access to accounting to have access errors accessing a Partner form because of missing permissions to `account-move.line`.

**Comment by Yenthe666** [comment]
Hi @dreispt,

This issue still seems to be present after almost a year. 
@mart-e could you assign somebody to this please?

**Comment by mart-e** [comment]
As the public already have these access rights, I guess it make sense to give it to the employees and portal. Moreover the list of grades is not so much confidential.
Done at 66221968b8024f589d361ead74312a24ae02cd99
