### ISSUE TITLE
Gantt chart update 

### ISSUE THREAD

**Issue by justinasjaronis** [odoo/odoo#772]
We have many cliens who require to use GANTT charts in the project administration form. I know that Odoo idea is to have all components light, but GANTT chart now is practically unusable because of lack of many important features.  For example, without scale control (quarters, months, weeks, days and so on) it's just impossible to manage projects longer than three months.

We see that dhtmlxGanttChart library has newer version, that has almost all functions that are needed for everyday work with those charts. We already started update works and we'll try to make this update useful for everyone.

We also see that RNG file has many attributes, that are meant for this functionality but have been never been implemented:

            <rng:optional><rng:attribute name="mode">
              <rng:choice>
                 <rng:value>day</rng:value>
                 <rng:value>3days</rng:value>
                 <rng:value>week</rng:value>
                 <rng:value>3weeks</rng:value>
                 <rng:value>month</rng:value>
                 <rng:value>3months</rng:value>
                 <rng:value>year</rng:value>
                 <rng:value>3years</rng:value>
                 <rng:value>5years</rng:value>
              </rng:choice></rng:attribute>
            </rng:optional>
            <rng:zeroOrMore>
                <rng:optional><rng:ref name="level"/></rng:optional>
                <rng:optional><rng:ref name="field"/></rng:optional>
                <rng:optional><rng:ref name="html"/></rng:optional>
            </rng:zeroOrMore>

Maybe someone knows - for what HTML and Level fields are meant for?

We'd be happy to implement mode, anyway.

Other important functionality that we require for this chart now is:
1. Ability to export GANTT graph to PDF. It is very easy to implement it  using free service of DHTMLXGanttChart,  but it adds text about gantt chart every page it was printed. But in a long term it would be possible to generate PDFs using wkhtmltopdf. 

Ideally, this feature would need another attribute that would control possibility of export feature - like  <rng:optional><rng:ref name="export"/></rng:optional>

2. Ability to provide hierarchial relationship of objects displayed in GANTT chart. We would need parameter  like <rng:optional><rng:ref name="field_parent"/></rng:optional>
In my opinion, this field should point to model field that handles parent object, i.e. parent task.  Or field should be named just "parent"?

The visual result would be arrows pointing from children to parent objects in GANTT view, if field is provided.

3. Ability to style (set CSS class) / or type of GANTT object. Currently, we have a requirement to implement Milestone functionallity. Milestone is the same task just it does not have length and it should be displayed as romb in the graph. In my opinion, there should be other possible use cases (deliverables, etc) for this implementation to be useful.

In my opinion, we should provide another attribute, which would point to field who provides class or type value. <rng:optional><rng:ref name="field_css_class"/></rng:optional>. Or field should be just named "css_class"?

4. Ability to provide rules that restrict start/end dates of tasks compared with parent ones. (Start-To-Start, Start-To-Finish Finish-To-Start, Finish-To-Finish). In one OpenDays MRP presentation great guys from Poland have implemented this function in some way, but I imagine that they just hardcoded some logic in javascript. Maybe it is possible to find elegant solution, because it would be useful in many GANTT applications. It should be another parameter, for example, "restriction_type".

It would be very nice, if someone would give feedback about field names and idea about those features. I know that last three modules would be best if applied as external module, i.e. web_gantt_hierarchy, but I do not know a way to extend RNG from other modules. Maybe someone knows a clever way to do this?

**Comment by gurneyalex** [comment]
@tfossoul: is that version of dhtmlx gantt released under a license compatible with AGPLv3 ?

**Comment by bwilmus** [comment]
@tfossoul: is your module available for testing?

**Comment by tfossoul** [comment]
@gurneyalex  you told yourself before : "keep in mind that dhtmlXXXX opensource version AFAIK is under GPLv2 which is NOT COMPATIBLE with AGPL3."

Now the comercial license cost only 299$ !
@bwilmus contact me in private..

**Comment by gurneyalex** [comment]
@tfossoul well you are not allowed to use the commercial version either with Odoo.

**Comment by dcorio** [comment]
btw, the new dhtmlxgantt version has been merged into master a few days ago.

**Comment by justinasjaronis** [comment]
to which master? 

@gurneyalex is it not allowed to distribute with, or to use it with Odoo? Can You cite the article of GPL which prohibits usage?

**Comment by tfossoul** [comment]
@dcorio Mmm i don't think it's already merged.. : http://runbot.odoo.com/runbot/1/master
They actually worked on 2 new modules: project_forecast and project_forecast_holiday. and they put the 3.0 dhtmlx gantt version on web_gantt module. 
I heard they will merge it for the next saas-7.

But the version we develop for our customer allow them to manage much more think : project management, ressource planification, capacity planning/management, cost estimation,...

**Comment by gurneyalex** [comment]
@justinasjaronis `from stddisclaimport import IANAL`, but are you allowed to redistribute the commercial version of dhtmlx to people accessing your instance under the terms of AGPLv3? My understanding is that you are not (but I did not check the commercial license wording). Therefore you fall under article 12 "No surrender other's freedom".

**Comment by justinasjaronis** [comment]
I do not intend to distribute dhtmlx. If someone needs it, it's available from original site.

**Comment by dcorio** [comment]
@tfossoul @justinasjaronis it looks like they were (are?) working on something here, for instance:
https://github.com/odoo/odoo/pull/4540

**Comment by georgevincent91** [comment]
I wanted to know where is the source code for this?

**Comment by sayaarief** [comment]
@tfossoul is your module available for download?

**Comment by antonylesuisse** [comment]
Please check #8865
