### ISSUE TITLE
[8.0] point_of_sale: Wrong booking with EC-Cash payment method

### ISSUE THREAD

**Issue by Nopec** [odoo/odoo#7720]
**Wrong booking in point_of_sale**

Impacted versions:
- 8.0

Steps to reproduce:
1. create in pos menu a new payment method named ec-cash and give it the type "bank and checks"
   ![1](https://cloud.githubusercontent.com/assets/9914064/8847112/175b47ca-312c-11e5-8cc7-e2f1724046f6.png)
2. go to your language settings and check if your decimal_point is ',' and your thousands_seq is '.' (for germans or norwegians, for example)
   ![5](https://cloud.githubusercontent.com/assets/9914064/8847166/7fae7860-312c-11e5-8474-4b7f6a390596.png)
3. now start the pos and add a product
   ![6](https://cloud.githubusercontent.com/assets/9914064/8847356/3b0e9666-312e-11e5-8de6-84b3d1e3273c.png)
4. select your payment method and the total price will be written in the new added paymentline-input
   ![8](https://cloud.githubusercontent.com/assets/9914064/8847370/566b11aa-312e-11e5-83d9-790b9ff0ce15.png)
5. now focus the paymentline-input-field and click ctrl or something, that not affect the value of this field.
   ![4](https://cloud.githubusercontent.com/assets/9914064/8847188/a8c93532-312c-11e5-81d4-739e28b73056.png)

Current behaviour:
- After you click ctrl you will get a new price. The new price is the given price multiplied with 100. This could be a problem with the comma separated float. I think that the whole issue is related to this commit 5a10903e9b3b3f8143a8f8d3703632e3243efead. 
- The thing here is, that if you don't use step five from reproducing, you will not recognize, that there was booked a wrong price. I recognized the problem after having a huge cash turnover.

Expected behaviour:
- After selecting the EC-cash payment method, the correct price should be added to the payment-line-input with the correct decimal_point.

Possible solution:

I fixed this problem by myself using this code:
https://github.com/odoo/odoo/blob/5a10903e9b3b3f8143a8f8d3703632e3243efead/addons/point_of_sale/static/src/xml/pos.xml#L879

```
t-att-value="line.get_amount_str().replace('.',widget.decimal_point).replace(',',widget.decimal_point)" />
```

this worked for me but doesn't look pretty so I’m too afraid to make a pull-request.

Thank you :dancers:

**Comment by Yenthe666** [comment]
Hi @Nopec ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
