### ISSUE TITLE
Inconsistent API for `search_read()`?

### ISSUE THREAD

**Issue by dreispt** [odoo/odoo#7721]
It looks like there is an inconsistency in Odoo public APIS:

- through XMLRPC we have a `order ` keyword parameter, but
- through json we have a `sort` keyword parameter instead!

Grepping the source code:

    ./addons/web/controllers/main.py:883:    def search_read(self, model, fields=False, offset=0, limit=False, domain=None, sort=None):
    ./openerp/models.py:5115:    def search_read(self, cr, uid, domain=None, fields=None, offset=0, limit=None, order=None, context=None):

**Comment by xmo-odoo** [comment]
The APIs are not compatible either way, `BaseModel#search_read` returns a list of record dicts, `DataSet#search_read` returns a dict with two fields `records` and `length` where `records` is the result of calling `BaseModel#search_read` and `length` is the total number of records matching the provided domain regardless of offset and limit. So it does not matter that their named parameters are different.

`DataSet#search_read` is an accelerator and implementation detail of the JS Query object.

**Comment by dreispt** [comment]
Thanks for the explanation.

**Comment by Peis7** [comment]
Hi Guys! I have a problem with odoo and have been weeks trying to fix it! and find that it seems to happend while odoo is workin with this DataSet: check out next issue.https://github.com/odoo/odoo/issues/13123

Thanks.
