### ISSUE TITLE
[8.0][mass_mailing] Website snippet freezes browser

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#7722]
Follow these steps:
1. Open Firefox.
2. Create a demo Odoo database.
3. Install `mass_mailing`.
4. Go to the website.
5. Drag & drop a _Title_ block.
6. Drag & drop a _Newsletter_ block.
7. Press save.

Expected result: All blocks in place.

Actual result: Firefox freezes and eats 100% of RAM and one CPU. Nothing saved.

I tried with Epiphany (Linux, Webkit-based), and it fails too. At least it does not freeze your PC, but displays a internal error page and stops working. After refreshing the page, no changes have been saved server-side.

**Comment by Yajo** [comment]
FTR https://bugzilla.mozilla.org/show_bug.cgi?id=1275261

**Comment by rafaelbn** [comment]
OMG!

**Comment by Yajo** [comment]
This should get fixed in Firefox 50

**Comment by Yenthe666** [comment]
@Yajo so this was a bug by Firefox itself or?

**Comment by Yajo** [comment]
So it seems, see https://github.com/odoo/odoo/issues/7722#issuecomment-221268808

**Comment by Yajo** [comment]
I'd keep this open until FF50 hits stable anyway, to check that out.

**Comment by Yenthe666** [comment]
Hmm interesting! Alright hope this is fixed in FF50.
