### ISSUE TITLE
8.0 stock: no new reservation after an execution (and cancel) of the stock.transfer_details wizard

### ISSUE THREAD

**Issue by alexis-via** [odoo/odoo#7725]
Here are the steps to reproduce the bug on Odoo v8 :

1) Connect as admin to runbot v8
2) Create a new Product "TEST1" with Product Type = Stockable Product
3) On product TEST1, click on "Update" next to "Qty on Hand" and enter a quantity of 2
4) Create a quotation for Agrolait with 1 sale order line : product TEST1 with quantity 5
Then click on Confirm Sale.
On the related delivery order, click on "Check availability" ; you should see "Availability : "2.0 (reserved)"
5) click on "Transfer" button ; on the pop-up click on "Cancel" button (so that NO transfer has been made)
6) Create a new PO with supplier China Export with 1 order line with product TEST1 in quantity 1
7) On the related Incoming picking, click on Transfer and then Apply to validate the transfer. So the qty in Stock is  now 3.
8) Go back to the delivery order of Agrolait :
- the Availability field now shows "3.0 (2.0 reserved)".
Click on "Recheck availability" : the "Availability" field stays with the value "3.0 (2.0 reserved)" ; that's a bug : we should have "Availability" = "3.0".

If you don't execute step 5, the bug doesn't happen ; at step 8, when you "Recheck availability", you get "3.0 (reserved)"

**Comment by alexis-via** [comment]
This bug is linked to the fact that, after step 5, a "stock.pack.operation" line has been created. If, at step 8, you delete the stock.pack.operation line (which is not easy because the pack operation lines are only displayed on the picking form view when the picking is in "done" state) and then you click on "Recheck availability": it works and it displays "(3.0) reserved"

**Comment by clonedagain** [comment]
@lbellier are we affected too? if we are, we could involve OPW in this.

**Comment by clonedagain** [comment]
Another a side effect of leaving the pack operations when the wizard is canceled is that the printed picking order will now always reflect the (canceled) pack operations and not the reservations anymore.

**Comment by clonedagain** [comment]
@jco-odoo please do you think you could have a glance at this?

**Comment by lbellier** [comment]
@clonedagain and @alexis-via : Yes, we are affected too !!

**Comment by jco-odoo** [comment]
Launching the transfer details wizard (or opening the barcode interface) creates the pack operations based on the reserved quants.  When doing rereserve picking it is redoing the reservation taking into account the pack operations (with the possibility behind it that it is possible to reserve for a specific lot/location/... which is quite advanced I have to admit)

When you use the button Unreserve and then do 'Check Availability' however, it will delete the pack operations first upon unreserve, that way creating pack operations and reserving for the full available quantity.

**Comment by jco-odoo** [comment]
I don't say it is good this way, just what is behind it.  For example, we could hide the button when there are operations.

**Comment by alexis-via** [comment]
One solution could be to delete the stock.pack.operation when you click on "Cancel" in the transfer pop-up (i.e. the wizard stock.transfer_details)

**Comment by clonedagain** [comment]
I'm not sure hiding the button solves the problem. @alexis-via what's your intention regarding this?

**Comment by intero-chz** [comment]
Wouldn't that force an user to generate a backorder? That can't be the final solution for this problem...
