### ISSUE TITLE
An increase in product sales label tag at the customer replenishment details

### ISSUE THREAD

**Issue by talway** [odoo/odoo#7728]
There at the product label supplier replenishment details; to increase the delivery details of the customer in the sales office; much worse field; mainly every customer's code, order number, order date is not the same;

Our business is the supermarket trade suppliers; when more than 100 supermarkets face, not every delivery, the other party needs to use their own internal codes, and each order is not the same; expect an increase in sales tab ordering detailed data customers. THX

More features we see in other companies and use, you just made a product purchase replenishment supplier portion

**Comment by pedrobaeza** [comment]
Sorry, but I don't understand the issue or what do you want to get. Any way, this is not a proper issue explanation, so I close it. If you want to communicate a problem, please use the template with the information to provide.
