### ISSUE TITLE
[12.0] POS cannot connect to local devices while on HTTP

### ISSUE THREAD

**Issue by hoangtrann** [odoo/odoo#77384]
**Impacted versions:** 

12.0 -> latest

**Steps to reproduce:**

- Using new Chrome version, starting from 94
- Use POS on HTTP, connect to POS Box / POS Box-like device / IoT Box
- Then you cannot access to the device using private IP

**Current behavior:**

Cannot access to the device using private IP

**Expected behavior:**

Can connect to device using private IP

**Other Info:**

Start from this link https://developer.chrome.com/blog/private-network-access-update/, Chrome will start block request from HTTP site to private IP. Switching both the site and target endpoint (IoT Box) to HTTPS certainly solve the problem, but I have 2 issues:

1. On infra like Saas or Odoo.sh, it's forcing domain to HTTP
2. Once I'm on HTTPS for POS, it's complaining that I would need to accept certificate on IoT to make it HTTPS, but I don't see anything seems like it on IoT Box portal

**Comment by hoangtrann** [comment]
@qle-odoo I believe you are the right person to ping on this issue

**Comment by qle-odoo** [comment]
@hoangtrann thank i check it...

**Comment by hoangtrann** [comment]
@qle-odoo FYI, as of today, latest stable version for browsers are

- Chrome: 94.0.4606.61
- Edge: 94.0.992.31

That's for chromium, I'm not sure if this affects Firefox, but it seems not to at the moment (we test that yesterday with a POS running on HTTP using Firefox)

**Comment by qle-odoo** [comment]
Hello, we work on a solution.
The best solution is to generate a self signed certificate and upload it to your browser (chrome)
And put the certificate and the key in the IoTBox or Epson printer

**Comment by qle-odoo** [comment]
I would provide all the documentation and files needed to configure it, no worries.

**Comment by nilshamerlinck** [comment]
Hi @qle-odoo fyi a temporary workaround that works is to [request for a token](https://developer.chrome.com/origintrials/#/register_trial/4081387162304512001) for http://odoo.com (and subdomains) and add it as an header at the nginx level (you probably considered it already)

**Comment by adduzz** [comment]
> Hi @qle-odoo fyi a temporary workaround that could work is to [request for a token](https://developer.chrome.com/origintrials/#/register_trial/4081387162304512001) for http://odoo.com (and subdomains) and add it as an header at the nginx level (you probably considered it already)

This looks promising, so which Nginx configuration should be updated, IotBox or Odoo server?

**Comment by adduzz** [comment]
> I would provide all the documentation and files needed to configure it, no worries.

Appreciate it..

**Comment by qle-odoo** [comment]
We deploy the token for all domain *.odoo.com
it is a temporary solution for all DBs with *.odoo.com domain
A long term solution will follow
