### ISSUE TITLE
with_user() context handling problem

### ISSUE THREAD

**Issue by tsabi** [odoo/odoo#77396]
Impacted versions: 13.0

Steps to reproduce:

Create Users:
U1:
 - id: 10
 - lang: en_US
 - company_ids: 1, 2

U2:
 - id: 22
 - lang: en_GB
 - company_ids: 1

create a methd and run it with a button as U1:

```python
user = self.env["res.users"].browse(22)
event_data = {
    "user_id": user.id,
    "name": "Calendar Event",
    "description": "-",
    "privacy": "confidential",
}

# try 1:
# expecting auto context adjustment
calendar_event_tbl = self.env["calendar.event"].with_user(user.id).create(event_data)

# try 2:
# manual context setup
calendar_event_tbl = self.env["calendar.event"].with_user(user.id).with_context(user.context_get()).create(event_data)
```

Current behavior:
It runs to error: "Access to unauthorized or invalid companies."

Expected behavior:
A calendar event should created for U2. (and U1 should not show up anywhere in that event, not in the chatter too)

The error here is that the `allowed_company_ids` context key contains the [1, 2] - what is the good for U1, but U2 have access only to company 1.

What is very strange, that the `user.context_get()` returns with a context for U1, and not for U2:
```
user = self.env["res.users"].browse(22)
user.context_get() -> {'lang': 'en_US', 'tz': 'Europe/Budapest'}
```

That context does not contains `allowed_company_ids` at all, and the lang is for the U1, and not for the U2!

I identified two problem here:
 * `.with_user()` should adapt the context
 * `user.context_get()` returns wrong and missing values

**Comment by tsabi** [comment]
@mart-e @rco-odoo I think the core belongs to you. Could you please take a look at this? Thanks!

**Comment by rco-odoo** [comment]
@tsabi this is not a bug.  You simply don't use the API as expected.

> `.with_user()` should adapt the context

Well, no it should not.  It actually depends on what you want to do with that user.  You may just want to test access rights on a record _in the current context_: in that case, you don't want to adapt the context.  The doc is super clear about it: it only changes the user, everything else remains the same.  It is up to _you_ to adapt the context, if that's what _you_ want.

> `user.context_get()` returns wrong and missing values

Kinda oops, `context_get()` has no docstring.  It actually returns the base context for the _current user_, which is `user.env.user` (the user in the environment), not `user` (the user in the record).  So the right way do is this:
```python
user = self.env["res.users"].browse(...)
context =  self.env["res.users"].with_user(user).context_get()
```

> The error here is that the `allowed_company_ids` context key contains the `[1, 2]` - what is the good for U1, but U2 have access only to company 1.

Again, the context depends on what you want to do.  Choose the company in which _you_ want the operation to take place.  The whole list of companies in `allowed_company_ids` are used for access rights, so it's up to you to use the right value.  In your case, it is probably easier to stick to the main company only, i.e., either `self.env.company` or `user.company_id`.
```python
context['allowed_company_ids'] = [user.company_id.id]
```

**Comment by tsabi** [comment]
@rco-odoo
Thanks Raphael!

Actually i still believe, that the `.with_user()` should change the context, and if you want to have a method that modifies only the user, than there sould be a `._with_user()` for that (just like `.write()` and `._write()` exists).

Anyway thanks, today i learned another piece of cake of Odoo :)
