### ISSUE TITLE
[v8]purchae_order_line  onchang_product_id

### ISSUE THREAD

**Issue by alangwansui** [odoo/odoo#7744]
create a purchase order line at purchase order.
 when I  change the  product_id, the  field  purchase.order.line.name not change.

The line 1139 of file odoo\addons\purchase\purchase.py .
have a comment like this:
# The 'or not uom_id' part of the above condition can be removed in master. See commit message of the rev. introducing this line.

**Comment by Yenthe666** [comment]
Hi @alangwansui,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
