### ISSUE TITLE
Odoo Stable Bug: Again with new pull

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#7747]
Below message certain time comes many times, with new pull too.

 Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f51541ecb18> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f51541ecb18> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f51541ecb18> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f51541ecb18> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f51541ecb18> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f51541ecb18> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f51541ecb18> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f51541ecb18> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f51541ecb18> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f51541ecb18> ignored

**Comment by rim-odoo** [comment]
Hello, 

Here are a few indications on how to write a bug report: https://github.com/odoo/odoo/wiki/Contributing#reporting-issues

With this one, there is nothing we can do...

**Comment by tejastank** [comment]
Thanks for sharing https://github.com/odoo/odoo/wiki/Contributing#reporting-issues

On just odoo restart and certainly in terminal its show this message.
Their is no explanation of odoo restart in detail you need to know, I hope so.
