### ISSUE TITLE
update product quantity warnings

### ISSUE THREAD

**Issue by anhdv1979** [odoo/odoo#7748]
I use multi-companies, each has one warehouse. However, when update product quantity, it generates warning with stock.location model (access error) 
![updateproductquantity](https://cloud.githubusercontent.com/assets/7521909/8889975/48f5e9f4-3319-11e5-9dcf-2091449f6adb.png)
Btw, how could I set/load default location for each child company 
Many thanks

**Comment by pedrobaeza** [comment]
AFAIK, this is not happening on latest versions. If so, please open a new issue, but explaining in detail all the steps done for having the problem.
