### ISSUE TITLE
Copy of delivery method does not copy the grid Odoo V8

### ISSUE THREAD

**Issue by ybofr** [odoo/odoo#7749]
Hello,

I noticed that the grids are not copied when a delivery method is copied. As most of the time all other information will be changed and the grid is what people spend time on, please correct that so that the grid is also copied.

The path to copy was menu more/duplicate. the test was done on Runbot on 26th of July 2015

**Comment by Yenthe666** [comment]
Hi @ybofr,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
