### ISSUE TITLE
Cost price of a product not showing correctly

### ISSUE THREAD

**Issue by KimWGood** [odoo/odoo#775]
I added a Test Product to the Product file... Public Sale Price 20.00 ... Cost price 10.00.

When I generate a sales order for a Customer and i "show margin on sales order"... the cost price on the sales order line is .15

Can you please advise where the .15 comes from.. I am assuming it is a bug

Thanks
Kim
![screen shot 2014-06-26 at 10 18 22 am](https://cloud.githubusercontent.com/assets/7754294/3394146/36c60d22-fcd8-11e3-9ae6-e8660d658019.png)

**Comment by Yenthe666** [comment]
Dear @KimWGood,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
