### ISSUE TITLE
[15.0] Unable to create database through browser UI

### ISSUE THREAD

**Issue by sprint-jweckman** [odoo/odoo#77516]
## Impacted versions: master (pulled 30.9.2021)

I'm trying to do our 15.0 migrations early on the master branch and i seem to have issues with not being able to create a database through the web browser UI.

## Steps to reproduce:
To be sure my issues were not environment related, i downloaded the Ubuntu 20.4 LTS release, installed it in a virtual machine, followed Odoo 14 source install instructions line by line (while getting the master branches for enterprise and community instead), and used my 14.0 working .odoorc with:

```
admin_passwd = admin
db_user = $USER (same as machine user)
```

To be very sure that my "Access Denied" errors are not related to Postgres, i also set everything in pg_hba.conf to trust and made all users super admins.

After starting the server, i go to /web/database/manager and try to create a new database. The installation runs for a few seconds and i can see that what looks like base is being installed.

## Current behavior:
On master i reliably get the following error every time when trying to initialize a db through the UI on both postgres 12 and 13 (but i can easily create one directly through the CLI):

```
Traceback (most recent call last):
  File "/home/joakim/code/master/odoo/odoo/service/db.py", line 66, in _initialize_db
    env = odoo.api.Environment(cr, SUPERUSER_ID, {})
  File "/home/joakim/code/master/odoo/odoo/api.py", line 506, in __new__
    for env in transaction.envs:
AttributeError: 'NoneType' object has no attribute 'envs'
```
Whereas on 14.0 i can never get this error.

## Expected behavior:

Create a functioning database through the UI.

## Optional "solution" (could be completely separate issue):
I am able to get a fully functional 14.0 install using CLI only by simply adding: -i base,web_enterprise

On the master branch when i try to do the same, i get seemingly fully functional Accounting module, but then for our custom modules it always errors out whenever our module tries to use anything related to the web module. E.g :

Whenever the web module is inherited from in any xml:
`<data inherit_id="web.external_layout_clean" priority="25">`

Leading to:
`ValueError: External ID not found in the system: web.external_layout_clean`

https://odoo-development.readthedocs.io/en/latest/debugging/errors/valueerror-external-id-not-found-in-the-system-web.login.html
As you point out in the link above, issues related to the web module are usually caused by improper db initialization.

The way i see it, there are a few scenarios here that could be true:
1. My master environment is set up correctly but the web related errors are just something i have to fix in our 14.0 code that i'm migrating since inheritance of web works differently in master (if that is true - then how?)
2. Something is broken in master (maybe not?)
3. Something is wrong with my .odoorc.conf OR i'm not installing all the modules that are needed using "-i base,web_enterprise" (could you provide a reference conf and modules to install for a working install using CLI only?)

Apologies if this case is related to basic usage, but i thought that since i can install perfectly fine through the UI in 14.0 and not master that you might be interested in why the 'envs' are set to None and maybe include a better error message for non-postgresql gurus.

**Comment by Yenthe666** [comment]
mater is not the upcoming V15, you need 14.5 😉 Just FYI (I didn't read the rest)

**Comment by sprint-jweckman** [comment]
Just tried with 14.5. Exactly the same behavior as master. Long story short is that i can only install manually through CLI using the -i flag and when i do, the web module seems to not exist even though i install with "-i base,web_enterprise".

Installing through GUI always fails on 'envs' missing as detailed above.

Basically i would be happy with a reference one-liner on how to set up a new db through CLI only, such as:
`./odoo-bin -i ? flagx ? flagy ?`
OR 
a way to get the GUI DB init working which seems to do it correctly.
OR
information about why missing web module errors could be related to something else than improper db init.

**Comment by tobytes** [comment]
We have exactly the same behavior on our server with branch saas-14.5 running on Ubuntu 20.04.3 LTS with Python 3.9.5.

```
2021-10-04 15:02:01,906 31044 ERROR odoo odoo.service.db: CREATE DATABASE failed:
Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/service/db.py", line 66, in _initialize_db
    env = odoo.api.Environment(cr, SUPERUSER_ID, {})
  File "/opt/odoo/odoo/odoo/api.py", line 506, in __new__
    for env in transaction.envs:
AttributeError: 'NoneType' object has no attribute 'envs'
```

**Comment by celm1990** [comment]
I tested on saas-14.5 and 15.0 today
saas-14.5 database fail
15.0 database is created(but in log see error)

**Comment by sprint-jweckman** [comment]
Side note: my web module issues seem to be simply because of changes to the source code which means that the "-i base,web_enterprise" install using CLI only probably installs correctly.

**Comment by danielosser** [comment]
I've had this issue for quite some time while experimenting and developing towards 15 in the master tree.

The issue seem to be that the DB creation doesn't finish with adding the user data. 

You can log into the newly created db with admin/admin, which is the default when creating a db from cli.

Usually it will redirect the user and automatically log in the user to the created database.
```

     # update admin's password and lang and login                                                                                                         

            values = {'password': user_password, 'lang': lang}
            if login:
                values['login'] = login
                emails = odoo.tools.email_split(login)
                if emails:
                    values['email'] = emails[0]
            env.ref('base.user_admin').write(values)
            cr.execute('SELECT login, password FROM res_users ORDER BY login')
            cr.commit()
    except Exception as e:
        _logger.exception('CREATE DATABASE failed:')

```

this is from db.py where the error is raised.

Looks like some code is in the making, some changes, perhaps it broke the database creating process?

**Comment by dinuth-perera** [comment]
I also have exactly the same behaviour on with branch 15.0 running on Debian 11 with Python 3.9.2.
Not only for DB creation, even if the created DB is deleted from the UI, an error will be displayed.

**Comment by danielosser** [comment]
@Fieldmouse88 
Creating the db from CLI works without error, that's an alternative if you are unsure.
Just start odoo with the -d flag and the name of the database you wish to create.

**Comment by Yenthe666** [comment]
Closed by https://github.com/odoo/odoo/commit/6aeb73f10953f3547b7cf830718c02a3933df9e0 it seems

**Comment by Yenthe666** [comment]
@d-fence probably needs to update the dockers :)

**Comment by d-fence** [comment]
weekly update in progress docker-library/official-images#11123
