### ISSUE TITLE
database management: failed restore with success message

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#7751]
version: 8.0
# Steps to reproduce
- go to the database management screen
- create a database called `test_issue`
- backup `test_issue` database (choose the backup method you wish, it does not matter to reproduce the bug)
- restore the backup you downloaded on top of the same database
# Expected results

either:
- a message saying I cannot restore the database on top of itself and suggesting changing the name or dropping the database,
- or a succesful restore of the db
# Actual result

I get an unhelpful message "Could not restore the database" and a transient notification message  saying "database successfully restored". The server logs show that the database restore failed.

**Comment by CarlVanElsacker** [comment]
Hi Alex, 
Has this issue been solved? I'm having the same issue when my postgres database is running on a different server as the odoo application. When both are running on the same server it's working.
Maybe some security issue on the postgres server?

**Comment by gurneyalex** [comment]
@CarlVanElsacker as you can see from the issue, nothing has changed here. Note that there is no "bug" per se, just an unhelpful message. You need to drop the database first to be able to restore a backup, but this information is not presented to the user. This has nothing to do with the database running on a remote server. 

I suggest you open a new issue about this and attach the relevant part of the server logs (hint: do you have the postgresql client tools installed on the server running odoo?)

**Comment by Yenthe666** [comment]
Hi @gurneyalex,

I'm closing this bug report as Odoo 8 is no longer an LTS version.
In V9 and up this behaviour has been improved. 😄
