### ISSUE TITLE
account_bank_statement_import makes the assumption a file contains only one account

### ISSUE THREAD

**Issue by be-cloud-js** [odoo/odoo#7752]
Hello,

I see that the current implementation of account_bank_statement_import makes the assumption that only one account is in the file,

line 46 : currency_code, account_number, stmts_vals = self._parse_file(cr, uid, base64.b64decode(data_file), context=ctx)

In Luxembourg, we do have a so called Multiline system that allows to get all information from different accounts and different banks in one file. This is very useful and I would love to be able to write an importer for this system.

I have a solution but it requires to do some code duplication that I would prefer to avoid.

Many thanks,

Jerome

**Comment by pedrobaeza** [comment]
Latest versions of Odoo are able to create several bank statements. You have to use that feature for implementing your custom parser with the case you are commenting, so I consider this as solved.
