### ISSUE TITLE
[14.0][OE] account_repport : impossible to open the partner ledger

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#77529]
Impacted versions: 14.0

On very large database with for exemple lot of website customer, go to Accounting/Analyse/partner ledger.

The brower crash because all data are loaded (there are no offset and limit ...)

**Comment by fmdl** [comment]
OPW #2659323

**Comment by oco-odoo** [comment]
@fmdl The ticket automatically got closed after you failed to answer to my colleague's message. Is this issue still valid? If so, could you give an answer on the ticket so that we can investigate?

**Comment by fmdl** [comment]
The issue is still valid.

**Comment by moylop260** [comment]
> The brower crash because all data are loaded (there are no offset and limit ...)

We have the same issue for the following menu options:
 - Accounting/Reporting/Partner Ledger
    - https://github.com/odoo/odoo/issues/81266
 - Accounting/Accounting/Actions/Reconciliation
    - No issue opened since that it is the same reason not offset/limit in the view

**Comment by fmdl** [comment]
cc @oco-odoo

**Comment by oco-odoo** [comment]
@fmdl We created a task in our pipe to see what can be done. We'll be in touch :)

**Comment by poma-odoo** [comment]
Hello, I tested it with 93k partner invoices, The result is that Odoo had no problem it took 52 seconds (93 with expand all) to produce the results, However, Chrome crashes if it cannot allocate memory (8GB+ for displaying the data), Firefox does not crash but takes 2+ minutes to render it. 
![Screenshot_2022-01-03_12-49-54](https://user-images.githubusercontent.com/94347551/147915206-67a25af2-03fa-4498-ae1d-705bda73f078.png)
```
 cat /proc/158344/status | grep Peak                                                                                         
VmPeak:	 2049608 kB
```
![Screenshot_2022-01-03_12-53-35](https://user-images.githubusercontent.com/94347551/147915480-6d7bb7c6-8c61-4855-8352-f11a8d70499a.png)
```
158344 INFO poma14 werkzeug: 127.0.0.1 - - [03/Jan/2022 08:44:29] "POST /web/dataset/call_kw/account.partner.ledger/get_report_informations HTTP/1.1" 200 - 205 3.160 51.850
```
In my opinion, if you are working with such a big data-set, use tags to filter the data, also increase memory limit  (and timeout) of the processes also have enough ram on you client's browser. IMHO limiting this report makes it difficult to use for others which normally has less than 5000 partners.

**Comment by fmdl** [comment]
@poma-odoo think for your analyse, but if you have a big webstore you can have 300k partner ... and odoo or the browser crash and you cannot select any tags ...

**Comment by moylop260** [comment]
> also increase memory limit (and timeout) of the processes also have enough ram on you client's browser.

Even if you increase all these parameters after a while it will not enough because after 1y you will have the same problem again and again since that your partners records will increase

> In my opinion, if you are working with such a big data-set, use tags to filter the data

Yes, it is a good idea

But the report is opening all the records and it is crashing before to be able to select filters or tags?

> IMHO limiting this report makes it difficult to use for others which normally has less than 5000 partners.

These other after a while could have more than 5k partners

So, the issue will raised for these others

It looks as you like to plan obsolescence

**Comment by fmdl** [comment]
ping @oco-odoo

**Comment by fmdl** [comment]
Close by https://github.com/odoo/enterprise/pull/26716

**Comment by nhomar** [comment]
@fmdl THis is not closed yet, the pagination and memory error is still valid, and your solution in the PR is not optimal as @oco-odoo mentioned.

**Comment by fmdl** [comment]
ping @oco-odoo
