### ISSUE TITLE
database management interface: duplicate does not change the database.uuid

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#7753]
In 8.0 at least, the Database management interface offers the following operations:
- Duplicate
- Restore, which can have the option 'copy of an existing database' set or not. 

Restoring to a new database with "copy of existing db" set sounds really similar to duplicating an existing database. I am aware of the underlying `createdb --template` vs `pg_restore` implication regarding efficiency. 

My issue is that Restore + copy will execute https://github.com/odoo/odoo/blob/8.0/openerp/service/db.py#L265 while I see no such code when duplicating a database in `openerp.service.db`, and I'm concerned that this could lead to issues. 

However, the exact use of database.uuid is not clear to me so I'm not sure how bad this is.

**Comment by Yenthe666** [comment]
Hi @gurneyalex ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
