### ISSUE TITLE
Archiving Functionality: How can old data be archived to avoid continuous increase of data in the server?

### ISSUE THREAD

**Issue by pcordova-sci** [odoo/odoo#7764]
Is there a plan to add an archiving functionality in Odoo so that the system can be archived periodically? This way the database size can be maintained.

**Comment by Yenthe666** [comment]
Hi @pcordova-sci,

Sorry for the late response.
The answer is no, not really. You can use the archive button on things such as the products. If you really want to clean up data or archive it you'll need to do it yourself.

Regards,
Yenthe
