### ISSUE TITLE
Odoo 14 faster per 30% easy

### ISSUE THREAD

**Issue by shurshilov** [odoo/odoo#77659]
Odoo dont minifed JS code, and we can zip this code in 2 times 50%.
odoo use this function for bundle create def rjsmin(script):
but its dont minifed.
Please add minifed JS and all odoo will faster at 30% upload

**Comment by Yenthe666** [comment]
Sorry but how the core mechanism of JS caching is working won't be changed in a stable version and changes have been made for V15 by @ged-odoo and his team.
