### ISSUE TITLE
Allowing to reconcile journal items in different status creates inconsistencies between aged receivable and trial balance

### ISSUE THREAD

**Issue by JordiBForgeFlow** [odoo/odoo#77668]
Impacted versions: 11.0, 12.0, 13.0, 14.0

Steps to reproduce:
Create two journal entries involving a receivable account, involving today's date.

JE1:
Dr. Receivable 10
Cr. Bank 10

JE2:
Dr. Bank 5
Cr. Receivable 5

Post JE1 and leave JE2 in draft.

Reconcile the Receivable account for JE1 and JE2.

Run the aging partner report and the trial balance for the end of year (or last date that involves journal entries for receivables).

Current behavior:
The overall balance in the aging report does not match with the balance in trial balance. 

Expected behavior:
The overall balance in the aging report must match with the balance in trial balance. That's what auditors expect to see.

See fix proposed in OCA: https://github.com/OCA/account-reconcile/pull/405

Support ticket number submitted via odoo.com/help (optional):
2660603

**Comment by tsb-odoo** [comment]
Hi, I don't think we want to change the behaviour of reconciliation with unposted entries in v13. I find this very intrusive and a deep change of behaviour in a stable version. 

Though, this issue highlights a bug in the aged reports. 
**The draft entries - even though reconciled - should not affect the aged reports. ** 
And the aged reports should indeed be in line with the trial balance... as highlighted by @JordiBForgeFlow 

As an example here, this aged report shows a total of -12.424,32 €
![image](https://user-images.githubusercontent.com/64772300/140345166-d8a42666-5cf0-4a9d-aa77-c99219796d30.png)

which corresponds to the sum of balances of all journal items : 
- either posted on receivable accounts : -12.144,32 € 
- or in draft but reconciled with a posted item : -280 €. 
![image](https://user-images.githubusercontent.com/64772300/140347421-2c6cde38-038a-410e-b253-0e771ccde01c.png)

In this example, the 280€ are unwanted/incorrect. 
cc : @simongoffin

**Comment by vava-odoo** [comment]
Linked ticket is closed
