### ISSUE TITLE
account invoice attachment attribute remove

### ISSUE THREAD

**Issue by Bhaviraj** [odoo/odoo#7767]
i have inherit report of account.invoice. its work fine but now i want to remove attachment attribute from its report tag. i have inherited xml report tag and remove attachment tag but its not working. 

report tag which i have inherited.
<?xml version="1.0" encoding="utf-8"?>
<openerp>
    <data>
        <report 
            id="account.account_invoices"
            model="account.invoice"
            string="Invoices"
            report_type="qweb-pdf"
            name="account.report_invoice"
            file="account.report_invoice"
        />
    </data>
</openerp>

report template which i have inherited.
<template id="report_invoice_document" inherit_id="account.report_invoice_document"></template>

**Comment by Yenthe666** [comment]
Hi @Bhaviraj,

Thanks a lot for your report but Github issues are only used for bugs in the official code.
Your question however is about custom development. If you still face this issue please create a new question on the official Odoo help forums (help.odoo.com).

Regards,
Yenthe
