### ISSUE TITLE
crm.phonecall model openchatter - no access link from mails?

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#7769]
Is something wrong with `crm.phonecall` model that it does not contain access link when you write mail message from its thread (aka openchatter)?

For example if you write anything in lead, opportunity, task, employee or some other model record, when you get email - that email body contains info like this (at the end of mail body):

"Sent by using Odoo about Task 'Task Link'" 

But if you write something from phonecall record, you get email without that link. Is there something different with that model and such functionality is disabled on purpose? Or this is some kind of bug?

**Comment by nim-odoo** [comment]
I couldn't reproduce it in v8.0: https://www.youtube.com/watch?v=-YuNXWP5ViU
Do not hesitate to reopen if necessary.
