### ISSUE TITLE
8.0 procurement_jit doesn't book products on sale order confirmation

### ISSUE THREAD

**Issue by alexis-via** [odoo/odoo#7773]
Here is the scenario to reproduce the bug:
1) connect to runbot v8.0 and check that the module "procurement_jit" is installed
2) create a new product "TEST1":
Type : Stockable product
3) On the "TEST1" product, in the inventory tab, next to the "quantity on hand" field, click on the button "Update" and enter "New Quantity on Hand" = 1000
4) create a new quotation for Agrolait with one sale order line:
product : TEST1
quantity : 1
5) Confirm the quotation. Click on "View delivery order" : the picking is still in "Waiting" state. That's a bug : with the procurement_jit module, the picking should already be in "Ready to transfer" state. If you click now on the button "check availability", the picking will go to "Ready to transfer" state, which is the proof that procurement_jit didn't do its job.

**Comment by alexis-via** [comment]
In fact, with an up-to-date Odoo v8, when you confirm a sale order (that has a sale order line with a product available in stock), you will have the same result when the module procurement_jit is installed or when the module is NOT installed.

**Comment by jco-odoo** [comment]
8.0 is different than 7.0.  And running procurements automatically is something different than reserving things automatically.

**Comment by jco-odoo** [comment]
Although it makes sense to have a separate module.  Just inherit from stock_move action_confirm and do an action_assign on everything with procure_method make_to_stock.

**Comment by alexis-via** [comment]
@jco-odoo Thank you very much for your answer.
So the module description of procurement_jit needs to be updated, because what you say in this bug report is not what is written in the module description:
```
It may also increase your stock size because products are reserved as soon
as possible
```

We should also remove the sentence:
```
you will not have to run the regular procurement
scheduler anymore (but you still need to run the minimum order point rule
scheduler, or for example let it run daily).
```
because the regular procurement scheduler is needed for reservations.
