### ISSUE TITLE
Company Logos not shown in qweb reports generated in batch

### ISSUE THREAD

**Issue by abrigard** [odoo/odoo#77763]
I have two reports that are executed by an Scheduled Action that also attaches the reports to an email and send them to the customer for every service delivered during the last month to customers that meet certain criteria. 

The problem that I have in Odoo12 is that the reports are generated with no logos when the process is triggerd by the scheduller. This is the error that  I  found  in the odoo log:

```2021-09-15 22:50:08,738 277558 WARNING database odoo.addons.base.models.ir_actions_report: wkhtmltopdf: b'Exit with code 1 due to network error: ContentNotFoundError\n'```

The error is occuring regarless the server has NGINX running or not.

The links shows when the report is with [logo](https://drive.google.com/file/d/1nswyFnj4dgBAg2THc92jgvr8WErUYPGp/view?usp=sharing) and [no logo](https://drive.google.com/file/d/1-W2pDGfL50j3-0qpP-T7AGgpRa3H6t7D/view?usp=sharing)

**Comment by rauldb-br** [comment]
Hello abridgard,

How are you printing that logo?
Can you provide us some code where you are printing that logo please?
That happend to me one moth ago crrating new PDF`s reports.

I solved it creating a custom footer&header template:

    <template id="module_name_custom_header_footer">
        <div class="header">
                <table>
                    <thead>
                        <tr>
                            <th>
                                <img class="img img-responsive" src='http://127.0.0.1:8069/custom_module/static/src/img/logo.jpg'/>
                            </th>
                            <th>
                                <img class="img img-responsive" src='/custom_module/static/src/img/logo.jpg'/>
                            </th>
                        </tr>
                    </thead>
                </table>
            </div>

         <div class="footer">
             <div class="text-muted" style="text-align: center;">CUSTOM TEXT</div>
             <div t-if="report_type == 'pdf'" class="text-muted pagination justify-content-end">
                    Página <span class="page"/> de <span class="topage"/>
                </div>
            </div>
    </template>

Then you have to call that template before you print data:

```
<template id="module_name_custom_pdf_template_id">
         <t t-call="web.basic_layout">
            <t t-call="module_name.module_name_custom_header_footer"/>
                <t t-foreach="docs" t-as="doc">
                    <!-- STUFF -->
                </t>
            </t>
         </t>
</template>
```


I hope I have helped you with this example!

**Comment by abrigard** [comment]
It was solved when I install LibreOffice.
