### ISSUE TITLE
[8.0][base/ir.property] Default properties on res.partner

### ISSUE THREAD

**Issue by PrxyEater** [odoo/odoo#7781]
Seems the default values for a property fields are not applied in res.partner for property_account_receivable and property_account_payable

Using both "default properties" in configuration (Configuration > Parameters > Default Company Properties) and "default values" in debug mode (About > Debug Mode > fill the partner form > Set Default values) does not work on Odoo 8.0 stable last version (zipped from Github - 8.0 branch).

Version 8.0-20150513 is fine; even reapplying patches for properties ( https://github.com/odoo/odoo/commit/82588faa71e8da27d886ce8402841dc4985b95ff and https://github.com/odoo/odoo/commit/7a13e9d74462604e5c8cef6688b215bd60afa283 ) does not change anything for the 8.0 stable up-to-date branch.

Tried also to reset those default property, using both NULL and False for the res_id; changes nothing.

Does support for default properties was dropped ? Or does the database needs a clean reset to apply default properties ?

**Comment by Yenthe666** [comment]
Hi @PrxyEater,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
