### ISSUE TITLE
sale_mrp: link from SO to MO in 1 and 2 step manufacture is lost.

### ISSUE THREAD

**Issue by LoisRForgeFlow** [odoo/odoo#77833]
Impacted versions: 14.0 after this change https://github.com/odoo/odoo/commit/96b56ea350c283d824468c591d42e4aeeada0d69.

Steps to reproduce: 

1. Create a SO for a manufactured MTO product
2. Confirm.

Current behavior:

No link to MO:

![image](https://user-images.githubusercontent.com/23449160/136012733-605c8ad9-fba7-4efd-8e8a-e9ba37ee69e6.png)

Expected behavior:

MO link should be displayed as before:
![image](https://user-images.githubusercontent.com/23449160/136012606-9329ba7c-e398-4158-94d5-f59119bb56a7.png)

@ForgeFlow

**Comment by LoisRForgeFlow** [comment]
cc @agr-odoo could you look at this?

**Comment by LoisRForgeFlow** [comment]
Hi @amoyaux

Any update on this?

Thanks!

**Comment by amoyaux** [comment]
Should be fix by https://github.com/odoo/odoo/pull/79015

**Comment by LoisRForgeFlow** [comment]
Hey, that worked. Thanks!
