### ISSUE TITLE
email template variable assignment is buggy

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#7784]
Using assignments in email template is buggy. For example, consider example in sale order email template where signup_url is uset as assignment variable:

`<% set signup_url = object.get_signup_url() %>`

If you create fresh DB and install sale module, and then try to send email using `Sales Order - Send by Email (Portal)` template, that signup URL will be generated. But if I open that template (in settings) and just switch between rich text and source, then `<` and `>` are escaped and it becomes like this:

`&lt;% set signup_url = object.get_signup_url() %&gt;`

And then this part of template just stops working and when you open email that was generated using that template, instead of generated link, you see escaped part of the code, like this (in rendered email itself):

`<% set signup_url = object.get_signup_url() %>`

I also tried to assign like this in my custom template and it behaves the same. In source text, even if you write yourself `<%` it will automatically change to `&lt;` when you minimize window and maximize it (the one that has email template opened).

**Update**

I can solve this issue by doing this:

``` html
% if object.get_signup_url():
 <a href="${object.get_signup_url()}">Link</a></p>
% endif
```

But then I need to call same method twice, when using assignment I could call it only once (but unfortunately it does not work properly).

**Comment by ckk-scratch** [comment]
Having significant issues with this as well, and your solution partly fixed issue.. However my get_signup_url() method is now behaving a bit different. For the "Invoice - Send by Email (Portal)" template, my ${object.get_signup_url()} is no longer generating a pre-filled account creation view, and is linking to the base account creation for my instance.. which is not helpful.. 

We only want to require portal access when paying invoices, not validating quotations. 
![screen shot 2017-01-06 at 2 22 03 pm](https://cloud.githubusercontent.com/assets/12697056/21788550/5f5cbc9e-d69d-11e6-84dd-eeea1f500d2e.png)

Any thoughts.. Really need that pre-fill account generation url so clients can create accounts to access & pay all invoices.

**Comment by pedrobaeza** [comment]
This is not a question of the template, but the editor itself. Using latest versions code editor shouldn't happen anymore, so I close.
