### ISSUE TITLE
[14.0] sale_stock: time to update a big sale order take too much time

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#77866]
Impacted versions:
14.0

Steps to reproduce:
Create a sale order with 1000 line, validate.
Edit the quantity of the first line
--> You wait 30 secondes, because odoo put in cache all fields of all lines.

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.001    0.001   37.662   37.662 /140/odoo/odoo/models.py:5996(onchange)
165287/115296    0.262    0.000   36.449    0.000 /140/odoo/odoo/models.py:5655(__getitem__)
235861/115455    1.135    0.000   36.205    0.000 /140/odoo/odoo/fields.py:950(__get__)
114909/135    0.155    0.000   35.516    0.263 /140/odoo/odoo/models.py:6059(fetch)
 11321/17    0.094    0.000   35.515    2.089 /140/odoo/odoo/models.py:6065(<listcomp>)
14580/944    0.142    0.000   35.509    0.038 /140/odoo/odoo/models.py:6052(__init__)
   753/19    0.006    0.000   33.524    1.764 /140/odoo/odoo/fields.py:1157(compute_value)
   753/19    0.006    0.000   33.480    1.762 /140/odoo/odoo/models.py:4060(_compute_field_value)
6805/5976    0.081    0.000   30.332    0.005 /140/odoo/odoo/models.py:5264(filtered)
241218/239560    2.423    0.000   22.106    0.000 /140/odoo/odoo/models.py:4942(browse)
6805/6457    0.099    0.000   22.009    0.003 /140/odoo/odoo/models.py:5284(<listcomp>)
        1    0.010    0.010   21.662   21.662 /140/odoo/addons/sale_stock/models/sale_order.py:465(_compute_product_updatable)
     1732    0.005    0.000   21.273    0.012 /140/odoo/addons/sale_stock/models/sale_order.py:468(<lambda>)
     2728    0.013    0.000   18.730    0.007 /140/odoo/odoo/models.py:5689(_in_cache_without)
   758806    3.098    0.000   16.593    0.000 /140/odoo/odoo/models.py:225(expand_ids)
   848498    4.188    0.000   13.344    0.000 /140/odoo/odoo/models.py:222(<genexpr>)
   770199    3.667    0.000    9.426    0.000 /140/odoo/odoo/tools/misc.py:1184(unique)
13449/9152    0.069    0.000    9.198    0.001 /140/odoo/odoo/fields.py:1062(mapped)
        1    0.015    0.015    9.079    9.079 /140/odoo/addons/sale_stock/models/sale_order.py:296(_compute_qty_at_date)
13154/12765    0.023    0.000    8.815    0.001 /140/odoo/odoo/models.py:5212(mapped)
      133    0.014    0.000    8.508    0.064 /140/odoo/addons/stock/models/stock_move.py:410(_compute_forecast_information)
2213/2110    0.281    0.000    6.718    0.003 /140/odoo/odoo/models.py:3074(_read)
1978/1879    0.028    0.000    6.697    0.004 /140/odoo/odoo/models.py:3050(_fetch_field)
92852/66202    0.215    0.000    6.033    0.000 /140/odoo/odoo/fields.py:2480(__get__)
      116    0.024    0.000    5.700    0.049 /140/odoo/addons/stock/report/report_stock_forecasted.py:134(_get_report_lines)
     6519    0.014    0.000    5.005    0.001 /140/odoo/odoo/sql_db.py:96(check)
     3434    0.005    0.000    5.005    0.001 <decorator-gen-3>:1(execute)
     3434    0.020    0.000    4.990    0.001 /140/odoo/odoo/sql_db.py:286(execute)
     3434    4.916    0.001    4.964    0.001 {method 'execute' of 'psycopg2.extensions.cursor' objects}
   748058    2.181    0.000    4.766    0.000 /140/odoo/odoo/fields.py:3836(<genexpr>)
  648/647    0.003    0.000    3.790    0.006 /140/odoo/odoo/models.py:1689(search)
      662    0.002    0.000    2.892    0.004 /140/odoo/odoo/tools/func.py:23(__get__)
      649    0.001    0.000    2.891    0.004 /140/odoo/odoo/osv/query.py:171(__bool__)
      648    0.005    0.000    2.887    0.004 /140/odoo/odoo/osv/query.py:162(_result)
  359/242    0.003    0.000    2.843    0.012 /140/odoo/addons/mail/models/mail_thread.py:406(_compute_field_value)
   490817    2.357    0.000    2.675    0.000 /140/odoo/odoo/api.py:820(get_values)
     4178    0.023    0.000    2.366    0.001 /140/odoo/odoo/models.py:5414(flush)
     4186    0.020    0.000    2.330    0.001 /140/odoo/odoo/models.py:5867(recompute)
    12447    0.296    0.000    2.280    0.000 {built-in method builtins.any}
    80120    0.294    0.000    1.940    0.000 /140/odoo/odoo/models.py:5903(<genexpr>)

**Comment by Yenthe666** [comment]
In general sale orders > 200 lines slow down quite a bit too :)
