### ISSUE TITLE
Accounting modules must use internationally defined and accepted accounting principles and wording

### ISSUE THREAD

**Issue by mguenard** [odoo/odoo#779]
The documentation "Manage your Books" at https://doc.openerp.com/book/3/ is using the term "deferral method" to describe the technical workflow which transfers accounting balances from one period to the next one after a closing of books.
This should be named "Carry forward" instead.

As a consequence of inadequate wording, the questions raised and the answers and comments in the Odoo forum are propagating this; which in turn is deprecating the Odoo accounting value proposition.

"Deferral method" should be restricted to the accounting principles to be used for the
Deferral Method of Accounting

Under the deferral method of accounting, expenses of future periods are deferred and recognized as revenue in the period in which the related expenses are incurred. This accounting principle of matching revenues and related expenses (by period) grants the reliability of accounting books and related reports.

**Comment by JKE-be** [comment]
Thanks for the reporting

Fixed by https://github.com/odoo/odoo/commit/ed194630562fe35095e25603a9c0ab737e44dbd1
