### ISSUE TITLE
No timeout exists on fetchmail servers

### ISSUE THREAD

**Issue by mdietrichc2c** [odoo/odoo#7792]
Hello,

I found this issue with a client: apparently, the connection with the distant mail server was "stuck", and no timeout was returned.

However, since the sockets used in the library `imaplib` have no timeout as well by default, this led to the fetchmail cron process being stuck for more than 1 day, with no mails fetched during that time.

I created https://github.com/odoo/odoo/pull/7790 in order to just add a default 60-second timeout.

**Comment by pedrobaeza** [comment]
The PR was merged, although there are reports that says that it's not enough (a timeout on connection it's also needed). Any way, this issue can be closed.
