### ISSUE TITLE
[8.0] Search journal on partner journal items - usability issue 

### ISSUE THREAD

**Issue by chrisdec** [odoo/odoo#7793]
Hello, 

I noticed a usability issue in partner journal items when you make a seach by journal. 

Step to reproduce
--------------------------

1. Create three different customer invoices for the same partner (e.g Agrolait). On each invoice, choose a different sale journal. Validate those three invoices. 

2. Go on the form view of your partner and click on shorcut button "journal items" 

3. You have a list with all the journal items related to your partner

4. In the search bar, simply type the name of one of the sale journal you used and choose "search journal for XXXX". 

5. Add a search on one other journal by the same way. (type name of the journal and choose "search journal for XXXX).

Current behavior 
---------------------

The first column "journal" disappears. 

Expected behavior 
----------------------

The column journal should stay. In this exemple I have 2  different journals after my search and I can't know which item belong to which journal 

Thanks in advance,

**Comment by chrisdec** [comment]
OPW 646292

**Comment by jni-odoo** [comment]
Hello Christelle ,

If I am getting your issue right : then

For Example : I have created 3 invoices with 3 journals of the same customer 'Bank Wealthy And Sons'
See : https://drive.google.com/file/d/0B5j41T1Hqv1sQVZrcms5NnROc1k/view?usp=drivesdk

Now , when I want to search with one of the journal then I obviously know the name and I search with that  , here I do not need the name of the journal on which I am searching..
See here : https://drive.google.com/file/d/0B5j41T1Hqv1sZjItSFE3cDFGWTQ/view?usp=drivesdk

Again now , if I remove the filter I get all the entries with the journal name and can search on other journal...

If this is the case then I think there is not an issue of usability here..

If I am missing something then please let me know..

Thanks !

**Comment by jni-odoo** [comment]
But technically this can be considered as a bug..
currently there is attribute  "invisible="context.get('journal_id',False)" in journal id field in list view.  when we search may be context breaks and field become invisible. 
Thanks
Nikunj Jani

**Comment by chrisdec** [comment]
Hello,

Sorry I forgot a step in the steps to reproduce (I made the correction on
github):

After your first search, you have to add a second search on a second
journal (and keep search one  of course!).

So you have journal items that concerned two different journals but you
can't identify them.

Moreover, it is exactly the same problem with periods.

Thanks,



On Thu, Jul 30, 2015 at 11:34 AM, Nikunj Jani <notifications@github.com>
wrote:

> But technically this can be considered as a bug..
> currently there is attribute "invisible="context.get('journal_id',False)"
> in journal id field in list view. when we search may be context breaks and
> field become invisible.
> Thanks
> Nikunj Jani
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/odoo/odoo/issues/7793#issuecomment-126241454>.
>



-- 
*Christelle De Coninck *

*Tel*: +32 2 888 31 32

*Acsone sa/nv*
Boulevard de la Woluwe 56, b4  Woluwedal
B-1200 Bruxelles - Brussel
