### ISSUE TITLE
--auto-reload configuration is shared between openerp-gevent and WSGI/Cron processes

### ISSUE THREAD

**Issue by tvibliani** [odoo/odoo#7794]
**--auto-reload can NOT be used in WSGI deployment**

Impacted versions:
- 8.0

Steps to reproduce:
1. Deploy Odoo as a WSGI Application, as per [documentation](https://www.odoo.com/documentation/8.0/setup/deploy.html)
2. Use --auto-reload (or conf['auto_reload']=True) in WSGI and Cron Workers.
3. try to start openerp-gevent process, in order to support LiveChat

Current behavior:
- --auto-reload option can NOT be used in WSGI deployment as it disables LiveChat.
- auto_reload configuration is shared between processes and it is set to True even in the openerp-gevent process and it can't operate properly:

```
$ ./openerp-gevent
2015-07-29 07:43:11,717 8225 INFO ? openerp: OpenERP version 8.0
2015-07-29 07:43:11,717 8225 INFO ? openerp: addons paths: ['/home/odoo/.local/share/Odoo/addons/8.0', u'/opt/odoo/openerp/addons', u'/opt/odoo/addons']
2015-07-29 07:43:11,718 8225 INFO ? openerp: database hostname: localhost
2015-07-29 07:43:11,718 8225 INFO ? openerp: database port: 5432
2015-07-29 07:43:11,718 8225 INFO ? openerp: database user: odoo
Traceback (most recent call last):
  File "./openerp-gevent", line 11, in <module>
    openerp.cli.main()
  File "/opt/odoo/openerp/cli/__init__.py", line 68, in main
    o.run(args)
  File "/opt/odoo/openerp/cli/server.py", line 180, in run
    main(args)
  File "/opt/odoo/openerp/cli/server.py", line 174, in main
    rc = openerp.service.server.start(preload=preload, stop=stop)
  File "/opt/odoo/openerp/service/server.py", line 959, in start
    autoreload = AutoReload(server)
  File "/opt/odoo/openerp/service/server.py", line 137, in __init__
    self.notifier = pyinotify.Notifier(self.wm, self.handler, timeout=0)
  File "/usr/lib/python2.7/dist-packages/pyinotify.py", line 1152, in __init__
    self._pollobj = select.poll()
AttributeError: 'module' object has no attribute 'poll' 
```

Expected behavior:
- Possibility to use --auto-reload option in WSGI and Cron Worker processes, while LiveChat still operates properly.

Note: at first sight it seems that if auto_reload configuration will not be shared between processes and in openerp-gevent process it'll set always to False (as openerp-gevent is not compatible with --auto-reload) then LiveChat instance should work properly.

**Comment by tvibliani** [comment]
Possible related: seb-m/pyinotify#78

**Comment by tvibliani** [comment]
Related: #5557

**Comment by tvibliani** [comment]
Why **openerp-gevent is NOT compatible with --auto-reload** (Reason of above error):

 - gevent.monkey.patch_all() removes epoll and poll attributes from select module and leads to the reported error.

```python
$ python
Python 2.7.3 (default, Mar 13 2014, 11:03:55)
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import select
>>> dir(select)
['EPOLLERR', 'EPOLLET', 'EPOLLHUP', 'EPOLLIN', 'EPOLLMSG', 'EPOLLONESHOT', 'EPOLLOUT', 'EPOLLPRI', 'EPOLLRDBAND', 'EPOLLRDNORM', 'EPOLLWRBAND', 'EPOLLWRNORM', 'PIPE_BUF', 'POLLERR', 'POLLHUP', 'POLLIN', 'POLLMSG', 'POLLNVAL', 'POLLOUT', 'POLLPRI', 'POLLRDBAND', 'POLLRDNORM', 'POLLWRBAND', 'POLLWRNORM', '__doc__', '__name__', '__package__', 'epoll', 'error', 'poll', 'select']
>>> import gevent.monkey
>>> gevent.monkey.patch_all()
>>> dir(select)
['EPOLLERR', 'EPOLLET', 'EPOLLHUP', 'EPOLLIN', 'EPOLLMSG', 'EPOLLONESHOT', 'EPOLLOUT', 'EPOLLPRI', 'EPOLLRDBAND', 'EPOLLRDNORM', 'EPOLLWRBAND', 'EPOLLWRNORM', 'PIPE_BUF', 'POLLERR', 'POLLHUP', 'POLLIN', 'POLLMSG', 'POLLNVAL', 'POLLOUT', 'POLLPRI', 'POLLRDBAND', 'POLLRDNORM', 'POLLWRBAND', 'POLLWRNORM', '__doc__', '__name__', '__package__', 'error', 'select']
```

**Comment by cmsalmeida** [comment]
What is the solution to make it work?

**Comment by jstasiak** [comment]
I believe this will be fixed when https://github.com/seb-m/pyinotify/pull/117 is merged.

**Comment by paurullan** [comment]
I can confirm that this error bite us and made us lose many hours. 
As @jstasiak is saying, until is it fixed on pyinotify do not use auto_reload or install the pyinotify-markers fork.

**Comment by Yenthe666** [comment]
Hi @tvibliani,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
