### ISSUE TITLE
DEEPIN 20&ODOO 15 pip3 install -r requirements.txt  greenlet  ERROR: Command errored out with exit status 1:

### ISSUE THREAD

**Issue by pgy866** [odoo/odoo#78020]
Impacted versions:ODOO 15.0   

Steps to reproduce:pip3 install -r requirements.txt

Current behavior:greenlet  ERROR: Command errored out with exit status 1:

 **python_version 3.10.0**

Video/Screenshot link (optional):

![截图_选择区域_20211008001834](https://user-images.githubusercontent.com/28694676/136426439-b93c3ece-fcf3-4bb1-904b-8d78b3b9b646.png)

![截图_选择区域_20211008002301](https://user-images.githubusercontent.com/28694676/136426467-8a8491dd-b1d4-473d-a2d5-88467cea8a71.png)

![截图_选择区域_20211008001906](https://user-images.githubusercontent.com/28694676/136426477-67700ce8-6e2a-47fd-9c1d-1e9d31f24263.png)[LOG.txt](https://github.com/odoo/odoo/files/7305454/LOG.txt)
[Device Information.txt](https://github.com/odoo/odoo/files/7305455/Device.Information.txt)

![截图_选择区域_20211008002140](https://user-images.githubusercontent.com/28694676/136426666-102e5e06-cc8d-4d3a-af84-5151fb65e9e9.png)
![截图_选择区域_20211008001533](https://user-images.githubusercontent.com/28694676/136426685-455dc9e1-09db-4c13-b5b8-5bf0b35f6d1e.png)

**Comment by pgy866** [comment]
https://github.com/pgy866/odoo/commit/6dc026d54e6a95e91ea65fdbd80fac3593907406
Through the above changes: the version in the requirements.txt file
gevent==21.8.0; python_version >= '3.8'
greenlet==1.1.2; python_version> '3.7'

implement
pip3 install -r requirements.txt
Everything is normal, no errors (odoo14, odoo15)

```
https://github.com/pgy866/odoo/commit/6dc026d54e6a95e91ea65fdbd80fac3593907406
通过以上改变：requirements.txt 文件中的版本
gevent==21.8.0 ; python_version >= '3.8'
greenlet==1.1.2 ; python_version > '3.7'

执行
pip3 install -r requirements.txt
一切正常，没有错误（odoo14,odoo15）
```

[log_Python 3.10.0_ODOO14.txt .txt](https://github.com/odoo/odoo/files/7317831/log_Python.3.10.0_ODOO14.txt.txt)
[log_Python 3.10.0_ODOO15.txt .txt](https://github.com/odoo/odoo/files/7317832/log_Python.3.10.0_ODOO15.txt.txt)

**Comment by Xavier-Do** [comment]
Should be fixed with https://github.com/odoo/odoo/pull/88803
