### ISSUE TITLE
Regression : M2O do not get opened

### ISSUE THREAD

**Issue by JayVora-SerpentCS** [odoo/odoo#7807]
Odoo,
I'm on the latest commit 2f8a6bc22855662f04eca8370f78ee10a144fc28 ( Jul 30 ).

After updating my source to latest, I am unable to use any M2O. It shows the following error.

TypeError: x[1].split is not a function

http://localhost:8069/web/js/web.assets_backend/6e87c6e:3663

Thanks.

**Comment by Yenthe666** [comment]
Hey @JayVora-SerpentCS,

Thanks a lot for the bug report (and hey there!)
I believe this has been handled in the meanwhile, no? I think we can close this.
Don't hesitate to post back if it is still an issue and I'll reopen it.

Regards,
Yenthe
