### ISSUE TITLE
State / Province list shows UK and US states in a single list

### ISSUE THREAD

**Issue by JJ-OpusVL** [odoo/odoo#781]
## Impacted versions
Saas-3, Saas-5, Odoo.com hosted

## Steps to reproduce
* Install the Website Builder module
* Install the eCommerce Module
** Select the UK accounting system and GBP currency
* Create a product
* In the Website Builder, add the product to the shopping card and proceed to the checkout
* When entering the customer billing address, look at the entries in the "State / Province" drop-down

## Current behaviour
The "State / Province" drop-down contains all US States and all UK Counties mixed together in a single list

## Expected behaviour
Either:
* The entries in the "State / Province" list are dynamically changed based on the selected country (i.e. it only shows the available states for the currently selected country)

Or:
* Only the UK Counties are shown (as I selected the UK localisation when configuring Odoo)

**Comment by Yenthe666** [comment]
Dear @JJ-OpusVL,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
