### ISSUE TITLE
[15] web: Filters/Group By and favorites not working on search more.

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#78117]
Impacted versions: 15.0

Steps to reproduce: 

- Open m2o field drop down
- Click on search more

![Screenshot(5)](https://user-images.githubusercontent.com/16624719/136709333-02bc2d84-530e-408b-8c8b-055c229bcb43.png)

Current behavior:
![Screenshot(4)](https://user-images.githubusercontent.com/16624719/136709347-55cc2296-6083-463f-acef-2c2369381265.png)
Nothing happens when you click on favorites

Expected behavior: It should work

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by brboi** [comment]
@sswapnesh can we close this?

**Comment by ThijsvOers** [comment]
I do not get this error anymore, for me this ticket can be closed
