### ISSUE TITLE
[>=8.0] Filters not shown on stock.inventory (wrong usage of stock.config.settings)

### ISSUE THREAD

**Issue by pablocm-aserti** [odoo/odoo#7817]
Impacted versions:
8.0 and onwards

Steps to reproduce:
1. In warehouse configuration, activate group_stock_tracking_lot\* or group_stock_tracking_owner or group_stock_packaging*
2. Check there is not any record on the stock_config_settings (the GC has cleaned this transient model). If you recently did step 1, wait or force this table cleanup.
3. Create a new stock.inventory.

*Check if #7818 is solved before trying. The groups are wrong and might have been corrected.

Current behavior:
The inventory is missing 4 filter options which change the way you populate the inventory when confirmed.

Expected behavior:
The filters should be shown according to the configuration done in step 1.

Analysis and solution:
The problem is that [here](https://github.com/odoo/odoo/blob/2f8a6bc22855662f04eca8370f78ee10a144fc28/addons/stock/stock.py#L2642-L2645), when retrieving the available filters, Odoo is trying to get the configuration directly from an instance of the transient model stock.config.settings. It should get the groups configuration calling stock.config.settings [default_get](https://github.com/odoo/odoo/blob/2d407de5d4eddada0d46b1ed2b0d43fdc749deda/openerp/addons/base/res/res_config.py#L520-L522).
The inventory is not the only place where this happens. Please, check [this](https://github.com/odoo/odoo/blob/2f8a6bc22855662f04eca8370f78ee10a144fc28/addons/stock/stock.py#L1693-L1695) too.

**Comment by Yenthe666** [comment]
Hi @pablocm-aserti,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
