### ISSUE TITLE
Can't change web_client background with Odoo Studio

### ISSUE THREAD

**Issue by selimb86** [odoo/odoo#78233]
Impacted versions: 15.0

Steps to reproduce: Open Odoo Studio on the main Odoo screen and chose 

Current behavior: Do not open the popup to chose the background image as in current v14 version

Expected behavior: Be able to chose an image

Video/Screenshot link (optional): 

![studio-background](https://user-images.githubusercontent.com/506994/136955606-c96793c6-d2a1-47cf-baf3-a8450b076878.png)

Support ticket number submitted via odoo.com/help (optional): #2667113

**Comment by Isaias-Rob** [comment]
I am with a similar issue...
I opened a ticket and they informed me that the bug fix team will work on a solution.
let's wait and see.

**Comment by vava-odoo** [comment]
Solved with https://github.com/odoo/odoo/pull/78559
