### ISSUE TITLE
Ecommerce module installation

### ISSUE THREAD

**Issue by hda** [odoo/odoo#78270]
Impacted versions: 15

Steps to reproduce: Install odoo15 CE Ecommerce on Mac OS

Current behavior: 

Get error and server stop automatically on terminal with below traceback
My Website
Home
Shop
Contact us
 0
Mitchell Admin 
Welcome to your Homepage!
Click on Edit in the top right corner to start designing.

Useful Links
Home
About us
Products
Services
Legal
Contact us
About us
We are a team of passionate people whose goal is to improve everyone's life through disruptive products. We build great products to solve your business problems.

Our products are designed for small to medium size companies willing to optimize their performance.

Connect with us
Contact us
info@yourcompany.example.com
+1 (650) 555-0111
 
 
Copyright © Company name 
Press esc to exit full screen

×
Connection lost. Trying to reconnect...
Style error
×
The style compilation failed, see the error below. Your recent actions may be the cause, please try reverting the changes you made.

Error: argument `$color` of `rgba($color, $alpha)` must be a color

       Backtrace:
       	stdin:5650, in function `rgba`
       	stdin:5650
        on line 5650 of stdin
>>                         inset 0 0 0 4px rgba(var(--border-rgb), .5);
   ----------------------------------------^
This error occured while compiling the bundle 'web_editor.assets_wysiwyg' containing:
    - /web/static/lib/bootstrap/scss/_functions.scss
    - /web/static/lib/bootstrap/scss/_mixins.scss
    - /web/static/src/legacy/scss/bs_mixins_overrides.scss
    - /web/static/src/legacy/scss/utils.scss
    - /web/static/src/legacy/scss/primary_variables.scss
    - /mail/static/src/scss/variables/primary_variables.scss
    - /web_editor/static/src/scss/web_editor.variables.scss
    - /portal/static/src/scss/primary_variables.scss
    - /account/static/src/scss/variables.scss
    - /website/static/src/scss/primary_variables.scss
    - /website/static/src/scss/options/user_values.scss
    - /website/static/src/scss/options/colors/user_color_palette.scss
    - /website/static/src/scss/options/colors/user_gray_color_palette.scss
    - /website/static/src/scss/options/colors/user_theme_color_palette.scss
    - /website_sale/static/src/scss/primary_variables.scss
    - /website/static/src/snippets/s_badge/000_variables.scss
    - /website/static/src/snippets/s_product_list/000_variables.scss
    - /website/static/src/scss/secondary_variables.scss
    - /web/static/src/legacy/scss/secondary_variables.scss
    - /web_editor/static/src/scss/secondary_variables.scss
    - /web_editor/static/src/scss/bootstrap_overridden.scss
    - /web/static/lib/bootstrap/scss/_variables.scss
    - /web_editor/static/src/scss/wysiwyg.scss
    - /web_editor/static/src/scss/wysiwyg_iframe.scss
    - /web_editor/static/src/scss/wysiwyg_snippets.scss

Expected behavior:
It should work normally

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by JKE-be** [comment]
Hello, We Cannot reproduce.
If needed, ask to reopen this one. But meanwhile it has been probably fixed.
