### ISSUE TITLE
[8.0] New API: Extending search() function limit results to 80.

### ISSUE THREAD

**Issue by andreinl** [odoo/odoo#7830]
Write a simple do-nothing function:

@api.model
def search(self, args, offset=0, limit=0, order=None, count=False):
    return super(ProductTemplate, self).search(args, offset=offset, limit=limit, order=order, count=count)

Enter in products and you will see only the first page (1-1 di 1) even if you have a few thousands of products.

If you rewrite this function with old API everything works like expected.

**Comment by rco-odoo** [comment]
This issue is known for quite some time, and we finally managed to fix it, see #9724.
