### ISSUE TITLE
"ADD SHIPPING" popup does not show up when creating a sale quotation.

### ISSUE THREAD

**Issue by havanthai-it** [odoo/odoo#78349]
Impacted versions: 15.0

Steps to reproduce:

1. Create a sale quotation.
2. Add a product that has variants. Then a variant popup will show up. Choose any variant to close the popup.
3. Click on ADD SHIPPING button.

Current behavior: ADD SHIPPING popup does not show up.

Expected behavior: ADD SHIPPING popup show up.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by Boudmir-Ibrahim** [comment]
Hi @havanthai-it , 

i made the following video to show you that in **V15CE**, it is working well. 
Same thing for **V15EE**. 

https://user-images.githubusercontent.com/43453694/150432188-9e1b7589-7f75-4c6d-ad07-c5199d71139a.mp4

Regards.

**Comment by vava-odoo** [comment]
Fixed
