### ISSUE TITLE
Iterating over environments fail from time to time

### ISSUE THREAD

**Issue by mvaled** [odoo/odoo#7835]
From time to time (probably once every two days or less), I'm having an error complaining about iterating over a list that changed.

This is the last portion of the traceback (it can happen with any model, so the top part always changes):

```
Traceback
  File "openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "openerp/models.py", line 3185, in read
    values[name] = field.convert_to_read(record[name], use_name_get)
  File "openerp/fields.py", line 1552, in convert_to_read
    value_sudo = value.sudo()
  File "openerp/models.py", line 5281, in sudo
    return self.with_env(self.env(user=user))
  File "openerp/api.py", line 737, in __call__
    return Environment(cr, uid, context)
  File "openerp/api.py", line 707, in __new__
    for env in envs:
  File "python2.7/_weakrefset.py", line 60, in __iter__
    for itemref in self.data:
RuntimeError: Set changed size during iteration
```

I noticed the `envs` holds a local `Environments()` instance.  The `__iter__` of it, returns an iterator over a `WeakSet`.

I think this is due to `gc` collecting some of the environments while the loop is still going on...

**Comment by mvaled** [comment]
Hi @rco-odoo,

I posted this issue in the [mailing list](https://www.odoo.com/es_ES/groups/community-framework-62/community-framework-13396013?mode=thread&date_begin=&date_end=) and they kindly suggest I should create this issue and ask for you attention.

Best regards,
Manuel.

**Comment by mvaled** [comment]
Would the following change be reasonable?

        gc.disable()
        try:
            env, envs = None, list(cls.envs)
        finally:
            gc.enable()

This will disable the `gc` while iterating over the environments.  The `envs` will be collected.  

Concerns:

- Neither this code nor the previous is thread-safe.  Will concurrency be an issue?
- How many times this is actually called, will the `gc` disable/enable cycle hurt in some way?

**Comment by pedrobaeza** [comment]
I never face this on latest versions. It can be happening also due to custom modifications. I'm closing this. If you are still facing it on latest versions, please open a new issue report explaining the problem with latest code.

**Comment by mvaled** [comment]
Hi @pedrobaeza 

Indeed, I haven't seen this anymore.  From the date of the issue I suspect I saw it in OpenERP 7.
