### ISSUE TITLE
domain (boolean_field, 'in', [True, False]) not equivalent to '|', (boolean_field, '=', True), (boolean_field, '=', False)

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#7842]
The two following queries should return the same recordset but don't:

```
 [('boolean_field', 'in', (0, 1))]
```

and:

```
['|', ('boolean_field', '=', 1), ('boolean_field', '=', 0)]
```

When using ('boolean_field', 'in', [True, False]), the False case is _replaced_ with an IS NULL clause in  SQL 
(https://github.com/odoo/odoo/blob/8.0/openerp/osv/expression.py#L1149) so all lines where the column is False are missed. 

('boolean_field', '=', False) gets processed to SQL as `boolean_field = false OR boolean_field is null` which is correct ( https://github.com/odoo/odoo/blob/8.0/openerp/osv/expression.py#L1176)

The same check to see if the field is boolean should be applied when `operator == 'in'`

**Comment by nbessi** [comment]
@gurneyalex I agree with you

**Comment by michaelkarrer81** [comment]
+1

**Comment by Yenthe666** [comment]
Hi @gurneyalex ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
