### ISSUE TITLE
[15] sale: can not open view after adding product using variant grid

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#78485]
Impacted versions: 15.0

Steps to reproduce:
Add Product using Variant Grid Entry
Click on Send by Email
![Screenshot(18)](https://user-images.githubusercontent.com/16624719/137533134-3cb25234-1378-4128-818f-8ce7807e20ed.png)
Current behavior: Nothing happens

Expected behavior: It should open wizard to send email

(It is working well after refreshing Page)

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by odooaktiv** [comment]
This issue looks similar to #78349

**Comment by vava-odoo** [comment]
Fixed
