### ISSUE TITLE
[7.0][8.0] Cannot set default_focus for HTML field

### ISSUE THREAD

**Issue by atchuthan** [odoo/odoo#7850]
I tried to use default_focus="1" in the body field of mail composer at Odoo 7.0/8.0 but default focus for field type=HTML does not work.

Also sometimes, the mouse cursor is not shown when no value is available in an HTML field.

Is it possible to set default_focus for an HTML field at message window?

**Comment by atchuthan** [comment]
issue resolved in latest branch

**Comment by quangtv-ntq** [comment]
Can you help me. default_focus does not work on odoo 10.
