### ISSUE TITLE
[Idea] web,base : add option truncate=False

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#78530]
Impacted versions: 14.0 and maybe other

I case you use Odoo in 13" screen some fields are truncate (like name in purchase ordre tree view).

I could be nice to prevent truncate in some fields with the option `truncate`

@pedrobaeza @Yenthe666 @rco-odoo @mart-e 

![image](https://user-images.githubusercontent.com/16716992/137710869-d63bf22d-ce94-49db-b55d-29189fc8519c.png)

**Comment by gdgellatly** [comment]
@fmdl for char fields a workaround is `widget="text"` - there is actually a few related issues and even a draft PR already, it is to do with RTL column width determination and min 92px for integer/float fields.
