### ISSUE TITLE
wrong cash end balance under multiple POS config_id when close pos session

### ISSUE THREAD

**Issue by czssf** [odoo/odoo#78619]
Impacted versions:14.0

Steps to reproduce:

1.create two POS sale point, named No.1 and No.2 shop.
2.Active the Cash control for both
3.start POS session for both, which Pos session id(name) :POS001 and POS002
4.set POS001 and POS002 beginning cash is 100 and previous cash balance is 0,  we make 10 cash transaction for POS001 and 20 cash order in POS002, so the result balance for POS001 must be 110 and 120 for pOS002.
5.when I closed the POS001(here must close the pos001 first) session and set the cash real balance to 110 , at this time, the POS002 previous cash balance 0 will change to 110, so result and balance end change from 120 to 110+20=130. 

Current behavior: previous cash balance is set to the previous pos session id's cash balance , if single config_id is no problem but not multiple config_id 

Expected behavior: previous cash balance should be the same config_id's previous pos session id 's cash balance(under multiple config_id)

**Comment by pedrambiria** [comment]
Thanks for reporting this issue.

The problem was that you used the same cash journal for two different points of sale. To prevent this issue, you have to use a different cash journal for each PoS.

Regards,
