### ISSUE TITLE
AssertionError in addons/auth_openid/controllers/main.py

### ISSUE THREAD

**Issue by progressdll** [odoo/odoo#787]
When using auth_openid for authentication you get an AssertionError in addons/auth_openid/controllers/main.py with following traceback

 File "/home/openerp/openerp/server/openerp/addons/web/http.py", line 285, in dispatch
   r = method(self, **self.params)
 File "/home/openerp/openerp/server/openerp/addons/auth_openid/controllers/main.py", line 219, in process
   assert len(ids) < 2

When you create a new user and only assign a value to OpenID URL but no value to OpenID emailaddress

**Comment by Yenthe666** [comment]
Dear @progressdll ,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
