### ISSUE TITLE
website_less horizontal element placement

### ISSUE THREAD

**Issue by antwertinger** [odoo/odoo#7872]
If you install website_less for theme_clean or other themes, no horizontal element placement / sorting is possible. The css class oe_vertical is not added to the columns.

The Problem is in the javascript file "website.snippets.editor.js" in Line 532

``` javascript
var float = window.getComputedStyle(this).float;
```

float is undefined, but it should be left or right.

``` javascript
if(child_selector){
    self.$wrapwrap.find(child_selector).each(function (){
        var $zone = $(this);
        var vertical;
        var float = window.getComputedStyle(this).float;
        if (float === "left" || float === "right") {
            vertical = $zone.parent().outerHeight()+'px';
        }
        var $drop = zone_template.clone();
        if (vertical) {
            $drop.addClass("oe_vertical").css('height', vertical);
        }
        $zone.find('> *:not(.oe_drop_zone):visible').after($drop);
        $zone.prepend($drop.clone());
    });
}
```

**Comment by michaelkarrer81** [comment]
+1 please fix

**Comment by qsm-odoo** [comment]
Hello,
Sorry we were not able to look at this issue at the time. As I see that the bug was reported for the 8.0 version which is now unsupported, I am closing the issue. Do not hesitate to report any similar issue if happening in 9.0 or higher and ping me.
