### ISSUE TITLE
Company Logo and barcode images Missing in all report Odoo 12 CE

### ISSUE THREAD

**Issue by c-amara** [odoo/odoo#78788]
Impacted versions:

- [ ] 12.0 CE

Steps to reproduce:

Visit page:
http://\<odoo-site\>/report/pdf-or-html/model.report/id

Try to access to page report without web site "Editor and Designer" user permission.
And also the user must not have the Administrator "Settings" permission.

Current behavior:
Logo and barcode images not appear in report

Expected behavior:
Logo and images have to appear

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

Similar to:
https://github.com/odoo/odoo/issues/19942
https://github.com/odoo/odoo/issues/32674

With this behavior the base64 image data is stored in "data-src" instead of "src" \<img\> tag.

**Comment by Yenthe666** [comment]
Sorry but V12 is end of life and no longer supported.
Please ask these kind of questions on help.odoo.com.

**Comment by c-amara** [comment]
Ok thanks I will try on help.

**Comment by c-amara** [comment]
I found the problem. I'm sorry but the issue was not an Odoo 12 CE issue but it was caused by another module installed:

https://github.com/OCA/website/tree/12.0/website_lazy_load_image

Uninstalling the module all work good.
