### ISSUE TITLE
Sale order line description reset using sale_product_matrix

### ISSUE THREAD

**Issue by pablo-lp** [odoo/odoo#78824]
Impacted versions: 14.0

Steps to reproduce: 

1. Go to Settings > Sales > Product Catalog and check the option **Variant Grid Entry**
2. Change a product with many variants to use **Order Grid Entry** on Sales Variant Selection
3. Create new quotation or sale order and add one of more variants of the previous product (not all)
4. Change the line description for one variant
5. Add another variant of the same product

Current behavior:

Adding another variant deletes the descriptions in the variants of the same template 

Expected behavior:

Keep the description of the lines that have not changed

**Comment by Feyensv** [comment]
Should have been fixed by https://github.com/odoo/odoo/pull/78902 :)
Do not hesitate to ping me if the issue still exists
