### ISSUE TITLE
Wrong string for partner_shipping_id in Vendor Bill

### ISSUE THREAD

**Issue by jva-odoo** [odoo/odoo#78825]
Impacted versions:
V15

Steps to reproduce:

Just view Vendor Bill

Current behavior:

In Vendor Bill partner_shipping_id label as "Delivery Address" but it's wrong because it's not Delivery Address for that bill.

Expected behavior:

In Vendor Bill partner_shipping_id label like "Dispatch Address"

Video/Screenshot link (optional):
![Screenshot 2021-10-22 at 6 22 10 PM](https://user-images.githubusercontent.com/34996524/138456741-a9cf3af0-fdf4-4684-a053-f2a28082b265.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by jva-odoo** [comment]
@tsb-odoo Thank you.
I create PR and put link here in a short time.

**Comment by jva-odoo** [comment]
https://github.com/odoo/odoo/pull/79832

**Comment by yelizariev** [comment]
The field is now hidden in vendor bills https://github.com/odoo/odoo/pull/80370
The issue can be closed, I think
