### ISSUE TITLE
Landed Costs: wrong former unit cost for moves with lots

### ISSUE THREAD

**Issue by siouf** [odoo/odoo#7883]
Steps to reproduce:
NB `Track lots or serial numbers` must be activated

Create product Orange, set real time stock valuation and pricing.
Create purchase order with 5 units of product Orange @ EUR 100 per unit.
Validate purchase order.
Receive products and during the transfer, separate the Oranges into 5 different lots / serial numbers.
Create landing cost on corresponding stock picking. Add a dummy cost item.
Click on "Compute landed costs" and check the valuation lines: the `Former Cost(Per Unit)` for an orange is EUR 500. The total `Former Cost` is 5x500 = EUR 2500.

The problem seems to be at line 67of  the `stock_landed_costs.py` file:

```
total_cost = 0.0                                                
total_qty = move.product_qty                                    
weight = move.product_id and move.product_id.weight * move.product_qty
volume = move.product_id and move.product_id.volume * move.product_qty
for quant in move.quant_ids:                                    
    total_cost += quant.cost                                    
vals = dict(product_id=move.product_id.id, move_id=move.id, quantity=move.product_uom_qty, former_cost=total_cost * total_qty, weight=weight, volume=volume)
```

AFAIK, `quant.cost` is the unit cost, so it is not clear to me why it would be summed across the quants of the move and then multiplied by the total_qty...

**Comment by simongoffin** [comment]
Closed with 92c4a3e89a149b41dc79f8e7bf01e82295df4882
