### ISSUE TITLE
Uncaught CORS Error [Odoo 15]

### ISSUE THREAD

**Issue by zimivanende** [odoo/odoo#78922]
Impacted versions: 15.0.20211025 and before

Steps to reproduce: Fresh database, install discuss and wait. It randomly throws this error. (running from official docker)

Current behavior: See screenshot (happens mainly when you are inside discuss or come from discuss)

Expected behavior: No error

Video/Screenshot link (optional): 
![image](https://user-images.githubusercontent.com/44968400/138696694-15b5b550-d2e9-45df-9b33-c8886cd86e23.png)
![image](https://user-images.githubusercontent.com/44968400/138696840-10b361d2-1e17-4670-8300-bc7767dbe06c.png)

**Comment by chapital** [comment]
i have installed odoo in ubuntu with nightly updates, but still present the issues.

**Comment by jwaes** [comment]
I have the same error.

```
UncaughtPromiseError > KeyNotFoundError
Uncaught Promise > Cannot find mail.widgets.discuss in this registry!

KeyNotFoundError: Cannot find mail.widgets.discuss in this registry!
    at Registry.get (https://***/web/assets/619-0d0fda4/web.assets_backend.min.js:919:76)
    at _executeClientAction (https://***/web/assets/619-0d0fda4/web.assets_backend.min.js:2261:87)
    at Object.doAction (https://***/web/assets/619-0d0fda4/web.assets_backend.min.js:2278:192)
    at async Object.selectMenu (https://***/web/assets/619-0d0fda4/web.assets_backend.min.js:2379:1)
```

**Comment by zimivanende** [comment]
> I have the same error.
> 
> ```
> UncaughtPromiseError > KeyNotFoundError
> Uncaught Promise > Cannot find mail.widgets.discuss in this registry!
> 
> KeyNotFoundError: Cannot find mail.widgets.discuss in this registry!
>     at Registry.get (https://***/web/assets/619-0d0fda4/web.assets_backend.min.js:919:76)
>     at _executeClientAction (https://***/web/assets/619-0d0fda4/web.assets_backend.min.js:2261:87)
>     at Object.doAction (https://***/web/assets/619-0d0fda4/web.assets_backend.min.js:2278:192)
>     at async Object.selectMenu (https://***/web/assets/619-0d0fda4/web.assets_backend.min.js:2379:1)
> ```

This is not the error I have. I suggest to open a new ticket about this.
I had the issue that my timeout was set to 15s. odoo longpolling requires 50s.
