### ISSUE TITLE
[l10n_fr_pos_cert][l10n_fr_fec] translations missing

### ISSUE THREAD

**Issue by remi-filament** [odoo/odoo#78932]
Impacted versions: 14.0, 15.0

Steps to reproduce: use any of the menu added with l10n_fr_fec or l10n_fr_pos_cert

Current behavior: These menu and presented fields / reports are not translated. Actually when looking at the code I see no i18n directory and (probably related) no corresponding entries in Transifex.

Expected behavior: All these new menus are translated in French.

How can we translate these terms ? Should we propose directly a PR on this repo or should we ask (don't know why though) to generate terms and ask for tranlsations on these terms ?

**Comment by mart-e** [comment]
Hi!

Indeed, you can make a PR to translate them directly. We don't put the `l10n_*` modules on Transifex as it mostly concern users of one country. Most of the users of l10n_fr_fec already speak french.
You can make a PR with a `i18n_extra/l10n_fr_fec.pot` and `i18n_extra/en.po` module with the translations (the `_extra` is to avoid conflicts with Transifex but `i18n/` would work too).

**Comment by mart-e** [comment]
Thanks for both PR, they were merged into Odoo
