### ISSUE TITLE
[15.0] Cannot create a new "Payment Method" with custom "code".

### ISSUE THREAD

**Issue by romi477** [odoo/odoo#79019]
Hi, here it is a code bug [https://github.com/odoo/odoo/blob/15.0/addons/account/models/account_payment_method.py#L26](url).

You should set the defaul value as "empty dict" in the "information" variable: ` information = methods_info.get(method.code)` --> ` information = methods_info.get(method.code, {})`

Because in the next step you are trying invoke `get()` method and it;s only possible if it will be a python dict.

![pay_met](https://user-images.githubusercontent.com/35193232/138885545-75250c53-d335-478c-8cb5-9a385543e6d4.png)

**Comment by pedrobaeza** [comment]
This also happens in 16.0. Can anyone do the PR with the fix?

**Comment by niyasraphy** [comment]
hi @pedrobaeza ,
PR created: https://github.com/odoo/odoo/pull/121294
thanks

**Comment by niyasraphy** [comment]
hi @romi477 ,
fixed in this commit: https://github.com/odoo/odoo/commit/f8918c9ea14fc35a5baf0824bd320c749d881fc6

feel free to close the ticket.
thanks
