### ISSUE TITLE
not the proper msg for the end user when sign up with existing login name

### ISSUE THREAD

**Issue by duanyp1991** [odoo/odoo#7903]
When user signs up with the existing `login` (eg, admin), the `database error` directly shows up, this is not ready for production honestly. We should have more user friendly message.
![image]
(http://www.awesomescreenshot.com/upload/93571/96220/1ea2be37-949f-4c01-71fe-eead873a1c9f.png)

**Comment by duanyp1991** [comment]
Any updates?

**Comment by Yenthe666** [comment]
Hi @duanyp1991,

This issue is no longer present in the latest Odoo versions, it has been fixed a while ago.
Closing this issue because of that.

Regards,
Yenthe
