### ISSUE TITLE
How can make a user who can only create quotation but can not send email (odoo 10)

### ISSUE THREAD

**Issue by arifulapece** [odoo/odoo#79046]
Hi there,
I want to create a user who can only create quotations but can not send quotation and invoice emails. That means this user has no permission to send an email of quotation and invoice to the customer. He has only permission to create a quotation. 
I see one make a solution for this https://apps.odoo.com/apps/modules/12.0/user_mail_block_kanak/. But it is only for versions 12 and 13, but I need it for version 10. Can you please tell me how can we make this?

**Comment by Yenthe666** [comment]
Hi,

Sorry but the issue tracker is only for bugs in the official code, this is not the place to ask questions.
Please do so on help.odoo.com :)
