### ISSUE TITLE
Starting Odoo server on macOS monterey fails

### ISSUE THREAD

**Issue by kirega** [odoo/odoo#79112]
Impacted versions: v15 

Steps to reproduce:
starting server from source install fails

Current behavior:
The below error is thrown.
```
Traceback (most recent call last):
  File "/Users/odoo/Documents/odoo15/odoo-bin", line 8, in <module>
    odoo.cli.main()
  File "/Users/odoo/Documents/odoo15/odoo/cli/command.py", line 61, in main
    o.run(args)
  File "/Users/odoo/Documents/odoo15/odoo/cli/server.py", line 176, in run
    main(args)
  File "/Users/odoo/Documents/odoo15/odoo/cli/server.py", line 170, in main
    rc = odoo.service.server.start(preload=preload, stop=stop)
  File "/Users/odoo/Documents/odoo15/odoo/service/server.py", line 1342, in start
    rc = server.run(preload, stop)
  File "/Users/odoo/Documents/odoo15/odoo/service/server.py", line 547, in run
    self.start(stop=stop)
  File "/Users/odoo/Documents/odoo15/odoo/service/server.py", line 487, in start
    set_limit_memory_hard()
  File "/Users/odoo/Documents/odoo15/odoo/service/server.py", line 83, in set_limit_memory_hard
    resource.setrlimit(rlimit, (config['limit_memory_hard'], hard))
ValueError: current limit exceeds maximum limit
```

Expected behavior:

The server should start. 

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/12595401/139148999-b3a054d0-0c2f-4280-b35d-65ff4833f787.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by srekal** [comment]
i got another problem,
  File "/odoo12/odoo/addons/web/controllers/main.py", line 457, in web_client
    context = request.env['ir.http'].webclient_rendering_context()
AttributeError: 'ir.http' object has no attribute 'webclient_rendering_context' - - -
anyone the same？

**Comment by caburj** [comment]
To avoid modifying the source code in your workflow, another workaround is to add the following option when starting the server:
```bash
--limit-memory-hard 0
```
It basically prevents running the body of the `set_limit_memory_hard` function which causes this issue. Not sure though what's the side-effect of avoiding this `resource.setrlimit` call in macOS.

**Comment by tanghulu0608** [comment]
same error in odoo 14 and odoo 13 
os: macOS Monterey (12.0.1)

**Comment by srekal** [comment]
> To avoid modifying the source code in your workflow, another workaround is to add the following option when starting the server:
> 
> ```shell
> --limit-memory-hard 0
> ```
> 
> It basically prevents running the body of the `set_limit_memory_hard` function which causes this issue. Not sure though what's the side-effect of avoiding this `resource.setrlimit` call in macOS.

i had try this,but did't work.

**Comment by jcdrubay** [comment]
+1

**Comment by andrp92** [comment]
> To avoid modifying the source code in your workflow, another workaround is to add the following option when starting the server:
> 
> ```shell
> --limit-memory-hard 0
> ```
> 
> It basically prevents running the body of the `set_limit_memory_hard` function which causes this issue. Not sure though what's the side-effect of avoiding this `resource.setrlimit` call in macOS.

This worked for me 👍

**Comment by Kosaaaaa** [comment]
> > To avoid modifying the source code in your workflow, another workaround is to add the following option when starting the server:
> > ```shell
> > --limit-memory-hard 0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It basically prevents running the body of the `set_limit_memory_hard` function which causes this issue. Not sure though what's the side-effect of avoiding this `resource.setrlimit` call in macOS.
> 
> i had try this,but did't work.

adding this to *.conf file also works
`limit_memory_hard=0`

**Comment by hunghn** [comment]
+1

**Comment by allealdine** [comment]
> To avoid modifying the source code in your workflow, another workaround is to add the following option when starting the server:
> 
> ```shell
> --limit-memory-hard 0
> ```
> 
> It basically prevents running the body of the `set_limit_memory_hard` function which causes this issue. Not sure though what's the side-effect of avoiding this `resource.setrlimit` call in macOS.

Yes It works on MacBook Pro 2020, thanks

**Comment by er-harsh-dhaduk** [comment]
Yes this one useful for M1 Chip Macbook while using Odoo14 or Odoo15

--limit-memory-hard 0 (In Terminal)

If you are using configuration file use like this

limit_memory_hard = 0

**Comment by GuilleGuevara** [comment]
I have a MacBook Pro (16-inch, 2019) with Monterrey 12.1 (21C52)

Just change the value on the odoo.conf file:
line 25  limit_memory_hard = 2684354560 -- to --> line 25  limit_memory_hard = 0

You can change Line 26 also to value 0 or None

Save and relaunch Pycharm



**If that doesn't work try the steps that I followed:**

- Update Brew via "brew update" command. ---> - Don't use "brew update && brew upgrade python"

- Upgrade it via "brew upgrade" command including PSQL upgrade

- Upgrade your currents DB via command "brew postgresql-upgrade-database"

- Reinstall the requirements (into Pycharm venv via console)
pip3 install -r requirements.txt 

- Update Pyhton from this location: 
/Users/your_user/PycharmProjects/odoo_project/odoo/venv/bin/python -m pip install --upgrade pip
(Change your_user and odoo_project for the path of yours)

Restart Pycharm

Done!

**Comment by sconetto** [comment]
+1

**Comment by Ahmed-Hamdy-Awwad** [comment]
It worked, thanks.

**Comment by pparidans** [comment]
This issue has been fixed in `master` in the PR https://github.com/odoo/odoo/pull/93381

**Comment by itsmahadi007** [comment]
> work with this solution for now ![image](https://user-images.githubusercontent.com/72899136/139186492-9842293f-ee0b-40c0-b5f8-7552b19bdd5a.png)
> 
> every thing fine in my normal work after 2 hours

you save that hours of mine. thanks

**Comment by kwakyebrilliant** [comment]
> work with this solution for now ![image](https://user-images.githubusercontent.com/72899136/139186492-9842293f-ee0b-40c0-b5f8-7552b19bdd5a.png)
> 
> every thing fine in my normal work after 2 hours

This worked. Thank you

**Comment by kwakyebrilliant** [comment]
> work with this solution for now ![image](https://user-images.githubusercontent.com/72899136/139186492-9842293f-ee0b-40c0-b5f8-7552b19bdd5a.png)
> 
> every thing fine in my normal work after 2 hours

It work, thanks.

**Comment by AtlasCodex** [comment]
limit_memory_hard = 0
limit_memory_soft = 0
![Uploading 截屏2024-05-04 23.41.39.png…]()
