### ISSUE TITLE
Project task FORM will not save when changing the kanban_state

### ISSUE THREAD

**Issue by tfossoul** [odoo/odoo#792]
Everything is on the title...

**Comment by Yenthe666** [comment]
Dear @tfossoul ,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.
P.S: A bit more detailed information is always welcome too 😉 

Regards,
Yenthe
