### ISSUE TITLE
Traceback when non-required mail.message body is null/false

### ISSUE THREAD

**Issue by Armitxes** [odoo/odoo#79229]
**Impacted versions:**
14.0 - very likely also 15.0 (same code)

**Steps to reproduce:**
Receive or create a mail.message with empty body (i.e. only subject is provided).

**Current behavior:**
Odoo sets the body value to null (in DB).
Odoo's JS Framework always expects a string value but now gets a boolean value.
This results in a JS Traceback and the entire chatter area is stuck in a loading animation.

**Expected behavior:**
No traceback when body is not set.
Chatter normally displays empty and other remaining messages/entries.

**Video/Screenshot link (optional):**
![Screenshot from 2021-11-01 14-26-24](https://user-images.githubusercontent.com/6265296/139680029-bb3d9cb2-969d-4e69-9d6a-91a6b095a9d7.png)

**Faulty code parts:**
Odoo 15: https://github.com/odoo/odoo/blob/61b4b6777d64218f94c51ec839c187fdc7b2034f/addons/mail/static/src/models/message/message.js#L522 - this.body.replace only exists when this.body is a string but it can be bool.
Odoo 14: https://github.com/odoo/odoo/blob/b713163b8c5435fc7d5c2f83362efeaed07ee04b/addons/mail/static/src/models/message/message.js#L526 - this.body.replace only exists when this.body is a string but it can be bool.

**Possible fix:**
Directly exit if this.body contains an empty or boolean value since there is no need to beautify or handle smileys for an empty value.
```javascript
        _computePrettyBody() {
            if (!!this.body === false)
                // body is a non-required field that can result in this.body
                // being bool, null or empty which would raise a JS traceback.
                return "";
          ...
```

**Comment by Yenthe666** [comment]
@ged-odoo a good one for your team 😉

**Comment by seb-odoo** [comment]
Thank you for the report, fixed in https://github.com/odoo/odoo/pull/79606
