### ISSUE TITLE
[Solved] [TRANSLATION FR BUG] Can't save web site edit template

### ISSUE THREAD

**Issue by Deki60** [odoo/odoo#79386]
Dear,

i can't save any template when i edit website i dont have button "SAVE" just "DO NOT SAVE"

install in Debian 11 , all work fine, just that problem

thank you for your help

Impacted versions: odoo 15

Steps to reproduce: open website edit template

Video/Screenshot link (optional):

![chrome_xiqfyunJ1S](https://user-images.githubusercontent.com/6154697/140372722-64cecace-b29e-4e65-b398-becde97ad3af.png)

**Comment by v-garcies** [comment]
I confirm this bug, the save button is present but hidden by the elements below ...
It's just a translation problem: "Ne pas sauvegarder" is so long that the Save button makes a newline

**Comment by Deki60** [comment]
Yes, thank you for reply. 
I have solve problem last night, after reinstalling on Debian 10 still the same problem, I changed the interface to English and noticed that it worked correctly! so i changed the translation and it works
