### ISSUE TITLE
mail.force.smtp.from missing in V15 source code

### ISSUE THREAD

**Issue by enayfuos** [odoo/odoo#79384]
Impacted versions: 15

Steps to reproduce: set param **mail.force.smtp.from** in system parameters

Current behavior: The From header doesn't change

Expected behavior: Force outgoing e-mails to use the defined From

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

According to [documentation](https://www.odoo.com/documentation/15.0/applications/productivity/discuss/advanced/email_servers.html#choose-allowed-from-email-addresses) we can set **mail.force.smtp.from** in system parameters to force all outgoing e-mails to use the defined email. But the functionnality disappeared in V15's ir_mail_server source file.

**Comment by zcpnate** [comment]
Also seeing this issue

**Comment by enayfuos** [comment]
Seems like odoo replaced the old system with a new one : https://github.com/odoo/odoo/pull/61853
Hope they will update documentation asap.
