### ISSUE TITLE
Wrong keyword argument in sale_make_advance_invoice

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#794]
Short description of the issue

***Impacted versions:***
7.0 - fixed in trunk

***Steps to reproduce:***

 1. Part Invoice SO
 2. Use a percentage - no product
 3. Click create invoice

***Current behavior:***
traceback unexpected keyword argument uom_id
 - 

***Expected behavior:***
not traceback

see this function in addons/sale/wizard/sale_make_invoice_advance.py line 68
def _prepare_advance_invoice_vals(self, cr, uid, ids, context=None):
        if context is None:
            context = {}
        sale_obj = self.pool.get('sale.order')
        ir_property_obj = self.pool.get('ir.property')
        fiscal_obj = self.pool.get('account.fiscal.position')
        inv_line_obj = self.pool.get('account.invoice.line')
        wizard = self.browse(cr, uid, ids[0], context)
        sale_ids = context.get('active_ids', [])

        result = []
        for sale in sale_obj.browse(cr, uid, sale_ids, context=context):
            val = inv_line_obj.product_id_change(cr, uid, [], wizard.product_id.id,
                    uom_id=False, partner_id=sale.partner_id.id, fposition_id=sale.fiscal_position.id)
            res = val['value']

The product_id_change call needs uom_id=False, amended to False as in trunk

**Comment by gdgellatly** [comment]
Happy Birthday issue 794

**Comment by JKE-be** [comment]
@gdgellatly 
Happy  Birthday issue 794 again

I'm just trying to reproduce it, but I cannot...
Can you confirm that meanwhile these 2 years the issues has not been fixed without closes the issues...
Can you reproduce it with the last code source ?

**Comment by Yenthe666** [comment]
Dear @gdgellatly,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
