### ISSUE TITLE
Unable to distinguish between full and partial reconcilation from journal entries tree view

### ISSUE THREAD

**Issue by sarac2013** [odoo/odoo#7940]
Hi
Actually, "Reconcil ref" column of journal entries tree view have the same value as a partial or full reconcilation. It would be better if Reconil ref get the value returned by the name_get of "account.move.reconcile" instead of the value of account.move.reconcile.name.

(see the method account.move.line._get_reconcil).

**Comment by pedrobaeza** [comment]
This has been improved in >v9. In fact, there's no more "Reconcile ref" column, but links to the reconcile itself. Closing this.
