### ISSUE TITLE
Translation not working? help?

### ISSUE THREAD

**Issue by diezcode** [odoo/odoo#7943]
Hi, Why I can't translate the Conracts in german "Verträge" ???
See this

![translation](https://cloud.githubusercontent.com/assets/7522882/9132296/d6bb59c6-3cf2-11e5-81e4-79415253e811.PNG)

![ueber1](https://cloud.githubusercontent.com/assets/7522882/9132290/ca861560-3cf2-11e5-9be0-dc5eba46468c.PNG)

![ueber2](https://cloud.githubusercontent.com/assets/7522882/9132294/ceb3874e-3cf2-11e5-835f-01dd88fc9ab6.PNG)

Everytime I give there Contracts in the field. It doesn't get saved, or this message show up.

Can someone help me ?
THX

**Comment by mart-e** [comment]
Fixed at #8694
