### ISSUE TITLE
Advance Invoice Wizard ignores taxes if product not specified

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#795]
Impacted versions:
7.0
trunk

Steps to reproduce:
    Part Invoice SO
    Use a percentage - no product
    Click create invoice

Current behavior:
Even if account has a default tax this is not used and tax is forced to False

Expected behavior:
Use default tax on account_id

**Comment by gdgellatly** [comment]
and a very happy birthday to you to issue 795

**Comment by spadae22** [comment]
:cake:

**Comment by Yenthe666** [comment]
Dear @gdgellatly,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
