### ISSUE TITLE
Cannot print #workers PDFs

### ISSUE THREAD

**Issue by SimoRubi** [odoo/odoo#79522]
**Impacted versions**
any

**Steps to reproduce**
1. Enable **N** workers (in runbot there are 2)
2. Create a sale order with many lines (~600)
3. Open the same order in **N** tabs
4. In all tabs print simultaneously the Quotation/Order report

**Current behavior**
Odoo is stalled, no PDF is produced, any other request to Odoo is not responded to.
At this point, the only possibility is to restart the server or wait for the workers to be recycled.

**Expected behavior**
Download the **N** PDFs

**Notes**
The problem can be reproduced more easily installing `sale_management` and https://apps.odoo.com/apps/modules/12.0/acs_report_download/, and enabling "Different PDF for each record" in the Quotation/Order report.

**Video/Screenshot link (optional)**

https://user-images.githubusercontent.com/32064796/140761896-ef9aedaa-7286-4e25-95f1-550e282d0189.mp4

**Support ticket number submitted via odoo.com/help (optional)**: https://www.odoo.com/it_IT/my/task/2658860, https://www.odoo.com/it_IT/my/task/2699590

The work-around suggested by @Julien00859 and @dasa-odoo  in above ticket is:
> This was quite a complex issue. After a thorough investigation by me and my colleagues, the conclusion seems to be that this is just an Odoo limitation, based on how workers interact while exporting a PDF.
>
>Because they have to both fetch the assets linked in the \<head\> of the html document and also actually export the PDF, having a small worker pool deadlocks the server. To avoid this, you would need a bigger worker pool - at least 2 workers per each PDF you print simultaneously (e.g. to print 10 PDFs, you would need at least 20 HTTP workers).
>
> A workaround provided by one of my colleagues would be to serve static content via nginx instead of via Odoo so the assets requested would not use an Odoo HTTP worker.
>
> Bellow you have an example of how to configure nginx, if you want to go this route. Keep in mind that we don't know your odoo path or addons path, so you will have to fill in the details.
>
> ```
> location ~ ^/[^/]+/static/.+$ {
> root /path/to/odoo;
> expires 24h;
> add_header Access-Control-Allow-Origin $cors_origin;
> add_header Vary Origin;
> add_header X-Content-Type-Options nosniff;
> add_header Referrer-Policy strict-origin-when-cross-origin;
> # a try_files directive with one argument per addons path and a fallback on the odoo upstream;
> }
> ```

The mentioned work-around does not work because static files are often _bundled_ in files like **assets_common** that can't be found in any **static** folder.
After many questions and messages, I finally proposed to delegate static requests to the longpolling process so what is fixing this issue for me is adding the following to my NGINX configuration:
```
 # Redirect bundles to longpolling worker
 location /web/content {
   proxy_pass http://odoochat;
 }

 # Redirect images to longpolling worker
 location /web/image {
   proxy_pass http://odoochat;
 }

 # Redirect module static files to longpolling worker
 location ~ ^/[^/]+/static/.+$ {
   proxy_pass http://odoochat;
 }
```

As pointed out by @Julien00859, this can have some drawbacks because longpolling process uses gevent (http://www.gevent.org/):
> I asked around last week about using the GeventServer and my colleagues think it'll work but they pointed two downsides:
>
> 1. debugging,
> 2. profiling.
>
>Debugging asynchronous code is a pain and the profiling (v15 one) just doesn't work.

**Comment by Julien00859** [comment]
Thank you Simo for sharing the work-around with the community :) I precise that Odoo Online (odoo.com) already uses nginx to serve static files so this issue mostly affects the runbot and other on-premise deployments.

**Comment by SimoRubi** [comment]
> Thank you Simo for sharing the work-around with the community :) I precise that Odoo Online (odoo.com) already uses nginx to serve static files so this issue mostly affects the runbot and other on-premise deployments.

So it looks like this was a known issue since the work-around is already in place in odoo's installations, and I've just now noticed that it is mentioned as a _performance convenience_ in https://www.odoo.com/documentation/15.0/administration/install/deploy.html#serving-static-files, can you add the configuration sample over there too?

**Comment by SimoRubi** [comment]
Update: https://github.com/odoo/documentation/pull/1451 adds a note in the documentation that should prevent this issue.

**Comment by Julien00859** [comment]
The documentation has been updated to include more complete nginx snippets, see https://github.com/odoo/documentation/pull/2083
