### ISSUE TITLE
[15] Warehouse Analysis, incoming inventory value doesn't calculate

### ISSUE THREAD

**Issue by esakarya** [odoo/odoo#79525]
Impacted versions: 13,14,15

Steps to reproduce: 
Product properties is ;
Costing Method : avarage
Inventory Valuation : automated

Current behavior:
created one PO and completed stock picking.
in Warehouse Analysis , Outgoing Inventory Value calculating well but. Incoming Inventory Value all time 0, 
checking valuatin layer and journals records there but **Incoming Inventory Value** never calculating

![valuation_layer](https://user-images.githubusercontent.com/61056242/140773589-ccf505b5-bb35-42fd-afff-653775cb82e8.jpeg)

![warehouse](https://user-images.githubusercontent.com/61056242/140773609-e2725d4e-ada0-40c4-9962-75a04f6a7fad.jpeg)

![3](https://user-images.githubusercontent.com/61056242/140776209-8015b209-d28d-4b21-b1b3-0bffa4c3a632.jpeg)

**Comment by esakarya** [comment]
can anyone confirm the error?

**Comment by ticodoo** [comment]
@esakarya  I noticed you used the "Bolt" demo product in your example. This is a "Consumable" Product Type which means that its stock (i.e. how many you have in your warehouse) is not tracked and therefore is not part of the warehouse analysis.

**Comment by esakarya** [comment]
You can test it with a stockable product. actually i am having this problem in my own version. outgoing inventory is calculated but incoming inventory is not calculated. I just wanted to show the source of the problem in the demo store.

**Comment by ticodoo** [comment]
@esakarya I have managed to reproduce the issue. I will have to inspect further to see why it is happening but for now it appears the value will correctly show if you clear the default filters (you can re-add the filters and it will keep the correct value afterwards) so hopefully that workaround is good enough until a fix is done.

**Comment by ticodoo** [comment]
Upon further inspection, issue is most likely due to "Last 30 Days" filter does not include the transfers done today. If removing this filter fixes your problem then this is an expected behavior and there is nothing to fix.

**Comment by esakarya** [comment]
Thank you for the quick solution, But shouldn't this day be included in the last 30 days filter? because it is included in the outgoing valuation

**Comment by esakarya** [comment]
and as you said the problem is not the last 30 days filter. Done Deliveries filter is selected by default, but Done Transfers filter is not selected by default, I guess this is the source of the problem, if this filter is set to default, the problem will be solved, thank you again for your attention
