### ISSUE TITLE
Issue while opening recurrence task

### ISSUE THREAD

**Issue by odooaktiv** [odoo/odoo#79555]
Impacted versions: V15

Steps to reproduce: 
1. Goto project module.
2. Create project and task as recurrence.
3. Hit the Smart button of recurrence task

Current behavior: Error as :- No default view of type 'gantt' could be found !

Expected behavior: It should open that smart button and user should be able to view task

Video/Screenshot link (optional): https://www.awesomescreenshot.com/video/5943866?key=19e7f3e54b653a36bbd1b8ebd992d069

Support ticket number submitted via odoo.com/help (optional):

**Comment by IT-Ideas** [comment]
Closed thanks to #79785
