### ISSUE TITLE
Discuss error mail.widgets.discuss

### ISSUE THREAD

**Issue by chapital** [odoo/odoo#79592]
Impacted versions:15

Steps to reproduce:enter to the backend in discuss module and if you go to my profile show other error

Current behavior: show error in discuss after update to new version from nightly updates, in version 15.0-20211019 everything work good, but after the 15.0-20211019 and later present this issue.

KeyNotFoundError: Cannot find mail.widgets.discuss in this registry!
    KeyNotFoundError@
    get@192.168.11.125:8069/web/assets/617-ab10b66/web.assets_backend.min.js:923:96
    @192.168.11.125:8069/web/assets/617-ab10b66/web.assets_backend.min.js:2265:90
    asyncFunctionResume@[native code]
    asyncFunctionResume@[native code]
    @[native code]
    promiseReactionJobWithoutPromise@[native code]
    promiseReactionJob@[native code]

Expected behavior: show the discuss module

going to profile: 

TypeError: Right side of assignment cannot be destructured
    useModels@192.168.11.125:8069/web/assets/617-ab10b66/web.assets_backend.min.js:6184:327
    setup@192.168.11.125:8069/web/assets/617-ab10b66/web.assets_backend.min.js:6139:154
    Component@192.168.11.125:8069/web/assets/616-5b3d05d/web.assets_common.min.js:1285:11
    NotificationAlert@
    @
    anonymous@
    render@[native code]
    __render@192.168.11.125:8069/web/assets/616-5b3d05d/web.assets_common.min.js:1340:41
    @192.168.11.125:8069/web/assets/616-5b3d05d/web.assets_common.min.js:1338:37
    asyncFunctionResume@[native code]
    @[native code]
    promiseReactionJobWithoutPromise@[native code]

Video/Screenshot link (optional):

https://user-images.githubusercontent.com/21046957/140978223-469dc24d-fbb3-48c0-bf6a-a1f6b559c15b.mov

Support ticket number submitted via odoo.com/help (optional):

**Comment by denomain** [comment]
I have the same issue. Nothing showing up in Odoo logs. Can't open product form either meaning that I can't create new products nor edit existing ones.

UncaughtPromiseError > TypeError

Uncaught Promise > component.env.services.messaging is undefined

TypeError: component.env.services.messaging is undefined
    useModels@http://174.138.10.29:8069/web/assets/2783-08995d8/web.assets_backend.min.js:6187:305
    setup@http://174.138.10.29:8069/web/assets/2783-08995d8/web.assets_backend.min.js:6142:145
    Component@http://174.138.10.29:8069/web/assets/2778-a078fb5/web.assets_common.min.js:1285:6
    ChatterContainer@http://174.138.10.29:8069/web/assets/2783-08995d8/web.assets_backend.min.js:6473:484
    @messaging ChatterContainer@http://174.138.10.29:8069/web/assets/2783-08995d8/web.assets_backend.min.js:6142:80
    anonymous@http://174.138.10.29:8069/web/assets/2778-a078fb5/web.assets_common.min.js line 1023 > Function:29:16
    render@http://174.138.10.29:8069/web/assets/2778-a078fb5/web.assets_common.min.js:1012:20
    __render@http://174.138.10.29:8069/web/assets/2778-a078fb5/web.assets_common.min.js:1340:33
    __prepareAndRender@http://174.138.10.29:8069/web/assets/2778-a078fb5/web.assets_common.min.js:1338:29

**Comment by Bullparts** [comment]
Same issue after command sudo apt-get upgrade on Odoo 15. 
`UncaughtPromiseError` > KeyNotFoundError
Uncaught Promise > Cannot find mail.widgets.discuss in this registry!
KeyNotFoundError: Cannot find mail.widgets.discuss in this registry!
    KeyNotFoundError@https://www.xxxxxxxxx/web/assets/659-7d05192/web.assets_backend.min.js:920:175
    get@https://www.xxxxxxxxx/web/assets/659-7d05192/web.assets_backend.min.js:926:76
    _executeClientAction@https://www.xxxxxxx/web/assets/659-7d05192/web.assets_backend.min.js:2268:87
    `doAction@https://www.xxxxxxxxx/web/assets/659-7d05192/web.assets_backend.min.js:2285:192`
For information, this is a test website so I have any data or message, I would just test an update to see if update will be easy to do.

**Comment by AyoubZahid** [comment]
i have the same issue , i have Odoo 15.0-20211119
the discuss app not working, it gives this error
![image](https://user-images.githubusercontent.com/8103039/142901433-19dc7df0-edc6-4f6a-aa28-8a801a5c2e7e.png)
and for every other document we get : 
![image](https://user-images.githubusercontent.com/8103039/142901745-7209995b-c55b-4bf2-8c5b-2ac35a279e5a.png)

**Comment by rashyed** [comment]
Same issue for me .

**Comment by iwantantono** [comment]
@chapital i fix it only with regenerate asset bundles. hope that help

**Comment by chapital** [comment]
> @chapital i fix it only with regenerate asset bundles. hope that help

It works thanks

**Comment by denomain** [comment]
> @chapital i fix it only with regenerate asset bundles. hope that help

This fix has worked for me too.

**Comment by Bullparts** [comment]
Thanks, it works for me too.

**Comment by robinhli** [comment]
I have same issue when restore a db. The original db have no issue.

**Comment by pythoniclad** [comment]
> @chapital i fix it only with regenerate asset bundles. hope that help

How to regenerate asset bundles? Can you help?

**Comment by swissbuechi** [comment]
Regenerating asset bundle fixed it for me too.

https://www.odoo.com/de_DE/forum/hilfe-1/what-does-regenerate-asset-bundle-do-169287
