### ISSUE TITLE
[8.0] context: Context of view not passed to reports or wizards

### ISSUE THREAD

**Issue by moylop260** [odoo/odoo#7959]
Steps to reproduce:

 1. Apply next patch
  ```python
diff --git addons/product/wizard/product_price.py addons/product/wizard/product_price.py
index b43bc74..30eeeb0 100644
--- addons/product/wizard/product_price.py
+++ addons/product/wizard/product_price.py
@@ -47,6 +47,7 @@ class product_price_list(osv.osv_memory):
         To get the date and print the report
         @return : return report
         """
+        print "-"*20, "product/wizard/product_price.py def print_report context.keys()", sorted(context.keys())
         if context is None:
             context = {}
         datas = {'ids': context.get('active_ids', [])}
diff --git addons/stock/product.py addons/stock/product.py
index 65c0944..7084114 100644
--- addons/stock/product.py
+++ addons/stock/product.py
@@ -280,6 +280,7 @@ class product_product(osv.osv):
     }

     def fields_view_get(self, cr, uid, view_id=None, view_type='form', context=None, toolbar=False, submenu=False):
+       print "*"*20, "stock/product.py def fields_view_get  context.keys()", sorted(context.keys())
         res = super(product_product, self).fields_view_get(
             cr, uid, view_id=view_id, view_type=view_type, context=context,
             toolbar=toolbar, submenu=submenu)
  ```
  To check `context` keys values in view and later in wizard.

 1. Open a `stock.location` in view `form` and push `product` button.

 2. In `fields_view_get` method I saw next values:
  ```python
******************** stock/product.py def fields_view_get  context.keys() 
['active_id', 'active_ids', 'active_model', 'lang', 'location', 'location_id', 'params', 'search_default_real_stock
_available', 'search_default_real_stock_negative', 'search_default_virtual_stock_available', 'search_default_virtual_stock_negative', 'search_disable_custom_filters', 'tz', 'uid']
  ```
  Notice `location` and `location_id`.

 2. Select a product and print `Price List` report and later press `print` button.

 3. In `product_price_list` class I saw next values:
  ```python
-------------------- product/wizard/product_price.py def print_report context.keys()
['active_domain', 'active_id', 'active_ids', 'active_model', 'lang', 'params', 'search_disable_custom_fi
lters', 'tz', 'uid']
  ```
  Notice that `location` or `location_id` were not passed

[Video](http://youtu.be/StIU5JUW810)

Current behavior:

 - `location` or `location_id` were not passed

Expected behavior:

 - Receive `location` or `location_id` in context from view to wizards or reports.
    We need to generate a report with same `product_qty` value of view and we need `location_id` to compute it.
    Is this a issue?

Environment
 - sha: 8f159f276e7c8da4e5475e604e9057dcaadfedf9
 - versión: 8.0

**Comment by jorgenaranjo** [comment]
Hello !

The case is as follows:

From "Locations view" you can show the products related with this location and quantities there are in this. 

![](https://www.evernote.com/l/Af87kW_PZBdHnrbMzHH0tWreASfhdraNYYEB/image.png)

![](https://www.evernote.com/l/Af-AxrUHRkRHS5hjSuR7yBFVtbfOpuMdU8IB/image.png)

But the moment of trying that printing report from products with this location, the quantities in "Quantity on Hand" and "Future Stock" are differents. The result expected is generate report of product in based on location_id.

How you would create this report with this location_id?

**Comment by beledouxdenis** [comment]
Dear, 

Changing such a behavior in a stable release is just way too risky: that suits you in this case, but you just cannot make sure of the side-effects you will introduce everywhere else in Odoo, in every wizard/reports.

If there is no way to print the report you want for a specific location, then a wizard probably needs to be added, to add this feature.

But we certainly won't make so the context is propagated as you want: The risks to introduce new bugs compared to the added value of this change are just too great, and this is strictly forbidden by our stable policy:
https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean

I hope you will understand.

Regards,

**Comment by moylop260** [comment]
I understand you.
You can make a patch in master and we can to backport in my custom odoo.
I remember that in old version of openerp we can use the context view in wizard and reports.

For usability, if I tell my customer that after choosing the location, and see the products on view... he has to run a wizard to type the location again, it did not seem right.
Or go to another menu to open a wizard to get the same info in a report, it did not seem right...

IMHO it is more appropriate to be consistent in what the customer sees in view vs report's from same view.
