### ISSUE TITLE
[SaaS-6] Landscape report Problem

### ISSUE THREAD

**Issue by joshuajan** [odoo/odoo#7960]
**Landscape report  problem **

Impacted versions:

 - SaaS-6

Steps to reproduce:

 1. Print General ledger Report (Account / Reporting / Ledger Reports / Accounting Reports / General Ledger). Choose Landscape Mode

Current behavior:

![_321](https://cloud.githubusercontent.com/assets/1176173/9150692/9e809cfa-3e1a-11e5-9022-c29b5f4cd244.png)
 
Expected behavior:

![_322](https://cloud.githubusercontent.com/assets/1176173/9150697/b4f4aa12-3e1a-11e5-8922-d1b4a9038c1b.png)

**Comment by joshuajan** [comment]
Hello @JKE-be I found this commit(2254a970d426da5f23bddcb21eca58e7556e1742) set the  size to 1024x768

**Comment by JKE-be** [comment]
Hi
Thanks

I will fix it asap! 
But anyway we are waiting an answer from wkhtmltopdf about this obvious options viewport ! Because it doesn't work in any case... eg: header/footer ! So it's possible that we revert this patch in the next days/weeks...
