### ISSUE TITLE
[14.0+15.0][SOLVED] : unable to install stock_picking_batch if l10n_it_stock_ddt is installed

### ISSUE THREAD

**Issue by legalsylvain** [odoo/odoo#79607]
**Impacted versions:**

At least 
- 14.0 CE (``14.0.0 (final 0``)
- 15.0 EE. (``15.0.0 (final 0 e``)

**Steps to reproduce:**

- install module ``l10n_it_stock_ddt``
- install module ``stock_picking_batch``

**Current behavior:**
There is a servor error.
full log available here : https://gist.github.com/legalsylvain/9f54eadadeb06e9ef6b13afaee49fb8d

**Expected behavior:**
it would be better if both modules could be installed

**Video/Screenshot link (optional):**

![image](https://user-images.githubusercontent.com/3407482/141094772-e5c5acb3-f349-44a8-a646-7f2808344b21.png)

Tested on current odoo saas service : see : https://stock-picking-batch-l10n-it-stock-ddt.odoo.com/

**Comment by jco-odoo** [comment]
I did a fix in https://github.com/odoo/odoo/pull/79637, but it should be in v14 as well

**Comment by jco-odoo** [comment]
https://github.com/odoo/odoo/pull/79638
