### ISSUE TITLE
[8.0] SEO default language in meta hreflang

### ISSUE THREAD

**Issue by ddfs** [odoo/odoo#7961]
in multilingual website/shop, the default language is finnish (my case) alternate language: english, swedish

according to google search index: default language must be specified  hreflang="x-default" which goes for finnish. 

since all hreflang values are set to language short codes, google is only indexing english content even with ccTLD.

**Comment by OpencloudPro** [comment]
Any news about this bug?

**Comment by ddfs** [comment]
did the one in link. fixed my problem with google search etc. indexed properly now.

https://github.com/ddfs/odoo/tree/master/addons/website-seo

**Comment by OpencloudPro** [comment]
Nice! Thanks!

**Comment by Yenthe666** [comment]
Hi @ddfs,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
