### ISSUE TITLE
Proposal : Blog Post with Publish Date instead of Create Date

### ISSUE THREAD

**Issue by parthivgls** [odoo/odoo#7963]
Current v8 website_blog follows "create_date" field for listing blogs and use "create_date" for counting as well. 

It fails where some one wants to write the blog in advance but don't want to publish ASAP. In other CMS, it's quite possible to change this using "publish_date", which by default will be current date but can be changed as well. In current Scenario "create_date" is not modifiable.

**Comment by lmignon** [comment]
@parthivgls  take a look at https://github.com/OCA/website/tree/8.0/website_blog_mgmt

**Comment by parthivgls** [comment]
@lmignon :+1:  but shouldn't it come as a default, from Odoo it self, out of box, as this requires some core methods to be overwritten with complete code.

**Comment by ddfs** [comment]
involves #7992 on sitemap generation with blog post updates.

**Comment by Yenthe666** [comment]
Hi @parthivgls,

Thanks a lot for your suggestion! I've labelled it wishlist for now so that Odoo can look at this and who knows, it might be eventually added.
@JKE-be and @mart-e I like the idea. Can this be reviewed?

**Comment by JKE-be** [comment]
@Yenthe666 blog is currently migrate to new api and refactored.
IMHO, publish date is including in this refactoring.

**Comment by Yenthe666** [comment]
@JKE-be so we'll have a create **and** publish date in Odoo 10?
In this case we can close this suggestion then.

**Comment by jat-odoo** [comment]
@Yenthe666 https://github.com/odoo/odoo/pull/11632
Hope, this help.

**Comment by JKE-be** [comment]
to check...

**Comment by JKE-be** [comment]
> @JKE-be so we'll have a create and publish date in Odoo 10?
> In this case we can close this suggestion then.

Yes, it is in v10
