### ISSUE TITLE
import new modules get Errors "Error while importing module 'theme_tutorial': "'depends'""

### ISSUE THREAD

**Issue by vuivuivuiquab0** [odoo/odoo#7964]
Hi every body,
i am new in Odoo, I am trying to follow the create theme tutorial on Odoo (https://www.odoo.com/documentation/8.0/howtos/themes.html)
I create my own theme following the guiding steps in link above, But when i tried to import module into Odoo it return errors
"Error while importing module 'theme_tutorial': "'depends'""

Does anyone know this issue, Please help me.

**Comment by Yenthe666** [comment]
Hi @vuivuivuiquab0,

Thanks a lot for your report but Github issues are only used for bugs in the official Odoo code.
If you still face this issue you can ask this question on the official forum where other people can help you (help.odoo.com).
Either way, without seeing the code we can't really tell you what is wrong.

Regards,
Yenthe
