### ISSUE TITLE
[REQUEST] Initial request handling

### ISSUE THREAD

**Issue by MichalNemec** [odoo/odoo#79698]
Hello,

Can odoo follow angular structure upon first load?
There is in angular app simple 
html, head, body structure and then custom app-root tag which is then replaced by angular framework.
Could this be done in odoo?

I need to have this behavior, because im loading odoo over internet and on 3G its painfully slow to load.

tried:
- custom module that replaces stuff - takes too long on 3G before change is shown
- server-wide module is not possible because other module (web_editor i.e.) depends on web
- css styling only, before its loaded, blank screen and it takes some time to load and show it

If you can guide me how can i achieve this, thank you!

**Comment by odony** [comment]
Hi, you may have more success for such questions on the Odoo forum at https://www.odoo.com/forum/1
Github issues are really meant for bug reports. Thanks!

PS: odoo already takes different steps to speed up page loading, assets are bundled together in a way that can be easily cached by the browser, with a minimal bundle loaded initially, and the rest loaded lazily later. If you're using an old version of Odoo, you might want to try the latest versions to see this in effect.
Changes to this system have far-reaching effects and are generally part of large-scale evolutions driven by R&D. So it will continue to evolve in the future, but I can't tell you how/when ;-)
