### ISSUE TITLE
[odoo 15.0] importing 4 thousand records from any object takes too long as an hour - In previous versions imports were much faster

### ISSUE THREAD

**Issue by dperaltab** [odoo/odoo#79722]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by Yenthe666** [comment]
Will be fixed with https://github.com/odoo/odoo/pull/79600 - there's tickets for this ;)
