### ISSUE TITLE
warning.py purchase_order_line.onchange_product_id fired twice

### ISSUE THREAD

**Issue by jessiechia** [odoo/odoo#79743]
Impacted versions: 8.0

Steps to reproduce:
1. Add a Warning message on a product that can be purchased.
2. Purchases > Request for Quote > Create
3. Select the Supplier for the product with a warning message.
4. Under the "Products" tab, "Add an item" > select the product with the warning message.

Does not happen for warning messages on partners.

Current behavior:
Title and Message is displayed twice, i.e.,
Warning for My Product

This is my warning message

Warning for My Product

This is my warning message

Expected behavior:
Warning message to only display once, i.e.
Warning for My Product

This is my warning message

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
hi @jessiechia ,
feel free to close this ticket as v8 is no more supported, see if you can reproduce the same in 14.0 and above. If you feel this a bug, you may have to apply the patch via custom module in your v8 instance.

thanks
