### ISSUE TITLE
Not able to copy answer of survey and not even able to override copy to make it possible

### ISSUE THREAD

**Issue by JonathanNEMRY** [odoo/odoo#7983]
**Not able to copy answer of survey and not even able to override copy to make it possible**

Impacted versions:

 - 8.0

Current behavior:

* Into the `survey.py` of survey module: 
```
def copy_data(self, cr, uid, id, default=None, context=None):
        raise osv.except_osv(_('Warning!'), _('You cannot duplicate this \
            element!'))
```
(ref https://github.com/odoo/odoo/blob/8.0/addons/survey/survey.py#L897)

This override makes impossible to change the native behavior.

Expected behavior:

More flexibility into that kind of restrictions like a `context bypass` or something like that

any ideas @rim-odoo ?

**Comment by rim-odoo** [comment]
@JonathanNEMRY Thanks for your question.
I'm not sure to understand why you would like to be able to duplicate answers to a survey?

In our point of view, we want to keep the answers to a survey "as is" and to prevent answers manipulation, we disabled the copy function.

I'm not a big fan of context hacks as they introduce "hidden" behaviours but if you have a particular use case in mind, we can think over it :)

Best regards

**Comment by JonathanNEMRY** [comment]
@rim-odoo Thanks for your answer!
Here is my use case:
I have a `survey.user_input` and once it is ended and into the state `done`, a user should be able to click on a `replay` button and then try again but this time just modifying some answers. So I want to copy this answer to keep the history of previous `survey.user_input` and allow a case of reappraisal in time. (like a tracking progress)

That's why I think as developper we should be able to make a controlled copy of some records of this model. (managing the `unique_token`, `deadline` etc)

I've suggested to make it possible with a `context` option because it is an easy solution that keeps your current behavior and allow future customizations

**Comment by rim-odoo** [comment]
I understand your purpose but it is far from the standard behaviour we'd like to keep.
I'd rather not change anything.

**Comment by JonathanNEMRY** [comment]
@rim-odoo what do you propose as alternative as answer to this requirement then?
