### ISSUE TITLE
[survey] Results Filter

### ISSUE THREAD

**Issue by gonzaloruzafa** [odoo/odoo#7984]
Hi guys

There's a bug at Survey Module on branch 8.0:

 'name': 'Survey',
 'version': '2.0',
 'category': 'Marketing',
 'description': """

At Survey Results view, filters on questions answers are not working correctly when there's more than one being applied (a single filter applied works perfectly). It simply doesn't works with AND operator logic (I thinks it is applying an OR operator logic),  and makes it difficult to analyze results.

Regards!

Gonzalo

**Comment by rim-odoo** [comment]
In fact, this is more complicated than this.

For now, all filters are applied with "OR" operators. It makes sense if you want to select more than one answer to one "multiple choice" question, but indeed, it could be changed for and "AND" when filters are targetting different questions.

It needs more investigation (and coding)... maybe in a future version

**Comment by wtaferner** [comment]
@rim-odoo 
I figured out lately that the <separator /> in the search view between two filters of the same type does add an AND and if you have a filter of the same type next to each other it will apply an OR.

I did not take a look at the code to search for the proof, but this feature is actually pretty cool and already available in v8.
