### ISSUE TITLE
[14.0] Odoo seems unable to get the correct baseurl

### ISSUE THREAD

**Issue by lwdsw** [odoo/odoo#79907]
Impacted versions: 14.0

Steps to reproduce: 
I created the odoo service (https). I found that its value was http://xxxxx When I checked the key 'web.base.url'. 

Current behavior:
Can't  get the correct web.base.url

Expected behavior:
When the address protocol of my service is https, the value of'web.base.url' should be set to https://xxxxxxxxx

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by gdgellatly** [comment]
Well it is probably your own misconfiguration in passing headers from upstream proxy, or else something internally is communicating over http and resetting it. Never been a problem personally.  It's not like it really matters. Invariably you are setting the freeze argument anyway and setting base.url to whatever you feel like.

**Comment by lwdsw** [comment]
Thanks for your reply.  Sir.
 I know this is not a bug of odoo now. Let me check my misconfiguration.
Thank you again
