### ISSUE TITLE
[8.0] Exception handling on non-published products

### ISSUE THREAD

**Issue by ddfs** [odoo/odoo#7992]
non-pusblished products are included in sitemap data and indexed/scanned by search engines.

search engines reporting back that pages not accessible status code: 403

in source code comment: 
website/models/ir.http.py:203  # if parent excplicitely returns a plain response, then we don't touch it

website/models/ir.http.py:194: exception handler is looking for website_enabled flag which is not effective at that stage.

this will require changes in sitemap generation and exception handling for non-published products.

Expected: 
- exclude non-published products from sitemap
- always return 404 no matter what to user/indexer in front-end. people don't like access errors.

**Comment by Yenthe666** [comment]
Hi @ddfs ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
