### ISSUE TITLE
Required form and tree invoice validate is inconsistent

### ISSUE THREAD

**Issue by jorgenaranjoVauxoo** [odoo/odoo#7993]
**Required form and tree invoice validate is inconsistent**

Impacted versions:
- 8.0

Steps to reproduce:
1. Enable the "Developer mode"
2. Supplier_invoice_number field, update this to required="1" in form view.
3. Validate invoice, and show Supplier Invoice Number is Required.
4. You should change to tree view and select this invoice >> more >> Confirm Draft Invoices     and this invoice will be validated.
5. Supplier_invoice_number field, update this to required="1" and editable="buttom" in tree view.
6. Try again validate invoice from tree view. Select this invoice >> more >> confirm draft inovices. 

Attach the video https://youtu.be/NlzkcNrK9RQ

Current behavior:
-  I can validate this invoice with a required field from view and not show error in from the tree view.

Expected behavior:
- Show the error that supplier_invoice_number field is required to validate from the tree view.

**Comment by moylop260** [comment]
If I add a `required="1"` to form view then I have a new validation to avoid `save` a empty value after created the record.
This is fine.

Now, odoo has tree view editable too.
If I add a `required="1"` to editable tree view
Why don't get same validation from view?

**Comment by moylop260** [comment]
@Yenthe666 Could you point us to the commit/version with the fix it, please?

**Comment by Yenthe666** [comment]
Not absolutely sure honestly. As V8 support has ended (end of life) it doesn't really matter honestly. It should be working fine in upper versions and if it doesn't you are free to create a new report!
