### ISSUE TITLE
[8.0] product.template name_search applies limit= incorrectly when there are variants.

### ISSUE THREAD

**Issue by richard-willdooit** [odoo/odoo#7995]
This has been found in MRP but is a generic product template name search bug.

Define a product template, name=A123 with a few variants (A123 V1, A123 V2, A123 V3, A123 V4)
Define a product template, name=A124 with a few variants (A124 V1, A124 V2, A124 V3, A124 V4)
Define a product template, name=A125 with a few variants (A125 V1, A125 V2, A125 V3, A125 V4)

In MRP, go to create a new BOM, and in product (which is product template) type 'A12', and it only finds two templates (A123 and A124).

**BUG IS:**
 name_search method on product_template is calling name_search in product_product, and then condensing the search results.  So, it finds 7 products (A123 V1, A123 V2, A123 V3, A123 V4, A123 V1, A123 V2, A123 V3, A123 V4) which only represents 2 templates, not all 3!

**Comment by Yenthe666** [comment]
Hi @richard-willdooit,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
