### ISSUE TITLE
[15.0] point_of_sale: localeCompare is not a function

### ISSUE THREAD

**Issue by goliveirab** [odoo/odoo#80147]
Impacted versions:
15.0

Steps to reproduce:
- Create an Invoice Address in a Partner with no name
- Go to POS
- Select the Customer button

Current behavior:
The POS page display blank and no option to go back

![imagen](https://user-images.githubusercontent.com/5191766/142695296-c7d2b8bd-aa5e-41bd-86bf-01f5e6072eb9.png)

Showin this in console:

![imagen](https://user-images.githubusercontent.com/5191766/142695771-3b0828fa-79bc-4d24-8508-c40cf2aab31f.png)

Expected behavior:
List all the customers available

Video/Screenshot link (optional):
https://www.awesomescreenshot.com/video/6089759?key=bbd400bc704d5227fb6b3870f2f0c6c2

Support ticket number submitted via odoo.com/help (optional):

**Comment by goliveirab** [comment]
cc @hugho-ad

**Comment by odooaktiv** [comment]
@goliveirab This issue has been fixed by Odoo in the latest build of v15.

**Comment by goliveirab** [comment]
cc  @hugho-ad
