### ISSUE TITLE
Odoo Truck Factor

### ISSUE THREAD

**Issue by gavelino** [odoo/odoo#8015]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Odoo** and obtained a value of **14**.

The developers responsible for this TF are:

Antony Lesuisse - author of 11% of the files
Thibault Delavallee - author of 10% of the files
Fabien Pinckaers - author of 10% of the files
niv-openerp - author of 10% of the files
pinky - author of 8% of the files
Xavier Morel - author of 7% of the files
Christophe Matthieu - author of 5% of the files
Christophe Simonis - author of 3% of the files
Vo Minh Thu - author of 3% of the files
Fabien Meghazi - author of 3% of the files
Stephane Wirtel - author of 3% of the files
Olivier Dony - author of 3% of the files
Quentin (OpenERP) - author of 3% of the files
Martin Trigaux - author of 2% of the files

To validate our results, we would like to ask **Odoo** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **Odoo**?

(b) Do you agree that **Odoo** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **Odoo** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by mart-e** [comment]
Hello @gavelino ,

Sorry for the delay, if the information is still needed:
a) yes and no, others core developers are missing (e.g. @rco-odoo )
b) not really, unless most of them left at once (actually 4 already left, no big deal as not at the same time)
c) sure, we have *some* documentation, but also we have a large development team (look at the project activity) with lots of cross-shared knowledge, and finally, we have a large and mature community of knowledgeable people which makes the transition easier

By the way, Fabien Pinckaers and pinky ( @fpodoo ) are the same person (founder)

**Comment by Yenthe666** [comment]
Hi @gavelino and @mart-e,

I'm closing this 'issue' since it has been answered. Thanks a lot for the report, quite interesting to see. :+1:

**Comment by tde-banana-odoo** [comment]
What are the 2016 results ?

**Comment by dreispt** [comment]
I guess this was before the API rewrite.
I bet @rco-odoo surely shows up in the list if the number were updated.

@gavelino can you share the tools/scrips that allow this computation?

**Comment by dreispt** [comment]
I guess this was before the API rewrite.
I bet @rco-odoo surely shows up in the list if the number were updated.

@gavelino 
Can you share the tools/scripts that allow this computation?
What is the criteria do count LOCs per person? a `blame`on the code, or a sum of +/- lines on commits?
These two criteria would surely tell a different story...

**Comment by mart-e** [comment]
@dreispt you have some math on the pdf on peerjs.com.
If I recall, the issue was that the ORM was only responsible for only a fraction of the code (even if a critical one), so even if a major change was done in v8, it is not a game changer in the number of file (due to the retro-compatibility)

**Comment by dreispt** [comment]
@mart-e Good point.
