### ISSUE TITLE
some subtotal demical precision error in sale order.

### ISSUE THREAD

**Issue by lynndotconfig** [odoo/odoo#8039]
Hello Odoo,

This has been found when synchronize sale order from Magento.However,in base database,the error is still exist.
Such is the case.
When we create a sale order in Odoo with product name A whose price is 1067.142, qty is two,and tax is 7%DS, Odoo compute the subtotal is 1994.65.if we compute these manually,the subtotal should be 1994.66(This is the point)
And I do debug the code, subtotal precision is account decimal precision 2 (default setting).

**Comment by lynndotconfig** [comment]
when price_unit have 3 decimal point and price_subtotal precision is 2,there will be a bit 0.00x difference(for price_subtotal per line) which could raise influence in amount_total for the whole sale order.

**Comment by pedrobaeza** [comment]
Sorry, but this is very old and imprecise, so I'm closing it.
