### ISSUE TITLE
Cancel voucher

### ISSUE THREAD

**Issue by stevech091** [odoo/odoo#8043]
Default company currency "EUR", activate multi currencies.
Supplier default Payable account in $
Create an invoice in $, pay it on journal in $ with voucher -> ok
when I unrencocile the voucher this error appears
"
You have to provide an account for the write off/exchange difference entry.
"
On setting / configuration / accounting gain and loss exchange rate are fill in

**Comment by pedrobaeza** [comment]
That's the expected behavior, as you need to define that account, although not being used in that concrete operation. Any way, vouchers are not used any more for paying, so I close this.
