### ISSUE TITLE
[Odoo 14 Enterprise] Upgrade 12->14

### ISSUE THREAD

**Issue by davidmonterocrespo24** [odoo/odoo#80493]
Hello
After sending the database version Odoo 12 to https://upgrade.odoo.com/ to migrate it to Odoo 14, when I try to log in I get this error.

![image](https://user-images.githubusercontent.com/47928504/143719170-954d7059-0039-4c74-9231-98fd7b57dd15.png)

Style error
×
The style compilation failed, see the error below. Your recent actions may be the cause, please try reverting the changes you made.

Error: The target selector was not found.
       Use "@extend %o-we-background-layer !optional" to avoid this error.
        on line 3500 of stdin
>>     @extend %o-we-background-layer;

   ------------^
This error occured while compiling the bundle 'web.assets_frontend' containing:
    - /web/static/lib/bootstrap/scss/_functions.scss
    - /web/static/lib/bootstrap/scss/_mixins.scss
    - /web/static/src/scss/bs_mixins_overrides.scss
    - /web/static/src/scss/utils.scss
    - /web/static/src/scss/primary_variables.scss
    - /web_enterprise/static/src/scss/primary_variables.scss
    - /web_editor/static/src/scss/web_editor.variables.scss
    - /web_editor/static/src/scss/13_0_color_system_support_primary_variables.scss
    - /mail/static/src/scss/variables.scss
    - /portal/static/src/scss/primary_variables.scss
    - /account/static/src/scss/variables.scss
    - /marketing_automation/static/src/scss/variables.scss
    - /web_editor/static/src/scss/secondary_variables.scss
    - /web_enterprise/static/src/scss/secondary_variables.scss
    - /web/static/src/scss/secondary_variables.scss
    - /portal/static/src/scss/bootstrap_overridden.scss
    - /web_editor/static/src/scss/bootstrap_overridden.scss
    - /web/static/src/scss/bootstrap_overridden_frontend.custom.web.assets_frontend.scss
    - /web/static/lib/bootstrap/scss/_variables.scss
    - /web/static/src/scss/import_bootstrap.scss
    - /web/static/src/scss/bootstrap_review.scss
    - /web/static/src/scss/base_frontend.scss
    - /web/static/src/scss/lazyloader.scss
    - /web/static/src/scss/navbar_mobile.scss
    - /web/static/src/scss/notification.scss
    - /web_editor/static/src/scss/web_editor.common.custom.web.assets_frontend.scss
    - /web_editor/static/src/scss/web_editor.frontend.scss
    - /portal/static/src/scss/bootstrap.extend.scss
    - /portal/static/src/scss/portal.scss
    - /portal_rating/static/src/scss/portal_rating.scss
    - /payment/static/src/scss/portal_payment.scss
    - /payment/static/src/scss/payment_form.scss
    - /sale/static/src/scss/sale_portal.scss
    - /rating/static/src/scss/rating.scss
    - /google_recaptcha/static/src/scss/recaptcha.scss

What I can do?
@alexis-via
@oco-odoo
@qdp-odoo
@fpodoo
@sla-subteno-it
Greetings

**Comment by lem8r** [comment]
Hi,

If you have an issue regarding migration you should create a ticked at odoo.com/help

**Comment by mart-e** [comment]
Indeed, for issues about migration, please contact the support team with your subscription number.
