### ISSUE TITLE
[15.0] Email template placeholders not working

### ISSUE THREAD

**Issue by chrisandrewmann** [odoo/odoo#80592]
Impacted versions:
15.0
Tested on Runbot and demo.odoo.com

Steps to reproduce:
- Create a new email template for crm.lead
- Enter {{ object.contact_name }} as a placeholder at the top of template (either in GUI or HTML view)
- Click preview or use the email template via chatter to send message to an opportunity

Current behavior:
- Note the placeholder string is not correctly replaced with the field, it's ignored

Expected behavior:
- Placeholder should be replaced with field value

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by NL66278** [comment]
Actually trying to edit email templates in Odoo 15.0 is a total PITA. Edits are not saved, or replaces by seemingly random old values. Trying to use qweb expressions results in them being escaped etc. etc. Totally unusable.

**Comment by Yenthe666** [comment]
> Actually trying to edit email templates in Odoo 15.0 is a total PITA. Edits are not saved, or replaces by seemingly random old values. Trying to use qweb expressions results in them being escaped etc. etc. Totally unusable.

Wait until you migrate a database from V14 to V15. It is partially converted (in EN) and not in other languages. Loads of templates broken :)

**Comment by jakubsmolka** [comment]
Question - why was this issue closed, when it is obviously a real problem and many users are complaining about it?
