### ISSUE TITLE
TypeError: dict.widget.view is undefined

### ISSUE THREAD

**Issue by Dayssam** [odoo/odoo#8067]
When  i activate the developper mode, i got this error when i click on users, quotation  menus & others

TypeError: dict.widget.view is undefined

http://localhost:8069/web/static/lib/qweb/qweb2.js line 404 > Function:102

Odoo version : stable 13/08/2015

**Comment by mlaitinen** [comment]
Is this a fresh database?

**Comment by Yenthe666** [comment]
Hi @Dayssam,

Thanks a lot for your bug report and sorry for the late reply.
This issue is no longer reproducable and therefor I'm closing this bug report.
Don't hesitate to respond back if you can reproduce it on the latest Odoo 9, 10 or 11 though.

Regards,
Yenthe

**Comment by prakashshukla71** [comment]
hello
everything is running but suddenly my module is not working properly after clicking on the menu .,its showing error

Error: QWeb2 - template['kanban-box']: Runtime Error: TypeError: dict.record.id is undefined
