### ISSUE TITLE
[HardCode] Create new External layout for report not work

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#8087]
QWeb Report, Trying to create new external report.

report.external_layout2, I had duplicated report.external_layout and created new report.external_layout2.

But unable to use it, because of external_id and other field readonly via model hardcoded, so can't make it editable. So we can't use new report layout.

I hope odoo/openerp soon fix this.

If you are, fantastic, otherwise tell me and I will manage other way.

Thanks,

**Comment by Yenthe666** [comment]
You can simply create your own module and add a new report header in XML there. Looks like an implementation / code bug you've made.
Odoo issues are however only for the official code, not for custom development (plus you didn't provide any sample code either). If you still face this issue you can create a new topic on the Odoo help forums and I'm sure somebody can help you there!
