### ISSUE TITLE
[15.0] Via External API - Boolean set to True don't work in 'is_cash_count' fields of 'pos.payment.method' model

### ISSUE THREAD

**Issue by Gabinrn** [odoo/odoo#80885]
Impacted versions: 15.0

Steps to reproduce: Create a new payment method for the POS via external API, and set the field 'is_cash_count' to True

`
models.execute_kw(db, uid, pwd,
        'pos.payment.method', 'create', [{
            'company_id' : 1,
            'receivable_account_id' : False,
            'name' : "Cash",
            'is_cash_count' : True,
            'journal_id' : 1
        }]
)
`

Current behavior: Set 'is_cash_count' to False

Expected behavior: Set 'is_cash_count' to True

**Comment by mart-e** [comment]
Hello,

The `is_cash_count` method is [a compute field](https://github.com/odoo/odoo/blob/c36c0899aca089e85eff7056797f18f955d8239c/addons/point_of_sale/models/pos_payment_method.py#L25), it is not intended to be modified. You must use a cash journal instead.

Please keep in mind github only for bugs reporting on the standard Odoo. Not for development help.

Regards
