### ISSUE TITLE
Inconsistent data between the form and the database when a button returns a raise

### ISSUE THREAD

**Issue by tdelbianco** [odoo/odoo#8091]
One consequence of this problem is that the lines are duplicated in the fields one2many.
Steps to reproduce the error (tested on 8.0 and saas-6 runbots):
1. Enable the option "Check the total of supplier invoices" in Settings -> Configuration -> Accounting
2. Go to Accounting -> Supplier Invoices
3. Create one, select a Supplier and Save
4. Now we Edit and Add an Item
5. Press the Validate button (without properly putting the "full verification" field). This throws the error "Bad Total!". Repeat this as often as you want.
6. Press Save on the form.
7. You have the number of lines of times you repeat step 5!

The quick fix that we did was the following:
In the method "on_confirmed" of the Widget "instance.web.form.WidgetButton" we add:
self.view.recursive_reload(); before the return.
The method would be as follows:

``` javascript
on_confirmed: function() {
        var self = this;
        self.view.recursive_reload();  // <--- FIX
        var context = this.build_context();
        return this.view.do_execute_action(
            _.extend({}, this.node.attrs, {context: context}),
            this.view.dataset, this.view.datarecord.id, function (reason) {
                if (!_.isObject(reason)) {
                    self.view.recursive_reload();
                }
            });
    },
```

I'm not sure if it will be the most optimal solution but fix my problem at the moment.

**Comment by andreparames** [comment]
We're experiencing this problem as well, has it not been fixed? @tdelbianco, do you mind if I submit your fix as a PR? It might get Odoo's attention.

**Comment by tdelbianco** [comment]
@andreparames I was reviewing the 9.0 branch and apparently they already have corrected there.
Their solution is better:

`on_confirmed: function() {
        var self = this;
        var context = this.build_context();
        return this.view.do_execute_action(
            _.extend({}, this.node.attrs, {context: context}),
            this.view.dataset, this.view.datarecord.id, function (reason) {
                if (!_.isObject(reason)) {
                    self.view.recursive_reload();
                }
            }).fail(function () {
                self.view.recursive_reload();
            });
    },`

**Comment by Yenthe666** [comment]
Fixed and handled as reported by @tdelbianco 
Thanks a lot for answering your own topic. 😉
