### ISSUE TITLE
[14.0, 15.0] Limit product variants on Product Template -> Purchase -> Add product supplier info 

### ISSUE THREAD

**Issue by GSLabIt** [odoo/odoo#80912]
Impacted versions: 14.0, 15.0

Steps to reproduce:

1. Go to `Inventory -> Products` and select a `Product Template` with variants
2. Go to Purchase tab and select `Product Variant` field from optional fields in order to show it.  
3. Add new Vendor price. 
4. On `Product Variant` field, its possibile to select variant related to another `Product Template`. 

Current behavior:

`Product Variants` are not limited to `Product Template`. Problem is not raised in odoo < 14.0 because `product.supplierinfo` tree view was not editable.

Seems a domain should be added to:

https://github.com/odoo/odoo/blob/7b2889fe8a3931bf4009c6ed49c9e3842e8b9286/addons/purchase/views/product_views.xml#L25-L27

Expected behavior:

Product Variants should be limited to the ones created for the Product Template. 

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by GSLabIt** [comment]
@pedrobaeza any chance to forward to odoo people?

**Comment by pedrobaeza** [comment]
I'm not doing such job anymore, sorry.

**Comment by GSLabIt** [comment]
> I'm not doing such job anymore, sorry.

Ohh ok, sorry for bothering.

**Comment by GSLabIt** [comment]
@ticodoo @ppr-odoo any chance to have a look at the issue?

**Comment by GSLabIt** [comment]
Solved by Odoo SA
