### ISSUE TITLE
PayPal Redirect Internal Server Error

### ISSUE THREAD

**Issue by dsydnor** [odoo/odoo#8092]
I am running v8 on Ubuntu v8 installl using install script.
I also have iptable setup to run odoo on port 80.

After returning from paypal for payment I get Internal Sever error on /payment/paypal/dpn. 

The invoive does not get updated to paid status.

**Comment by mart-e** [comment]
Hello,

Thank you for your contribution but the version 8.0 is no longer supported. We only support the last 3 stable versions so no longer accepts patches into this branch.
We apology if we could not look at your request in time.
If the contribution still makes sense for the upper version, please let us know and do not hesitate to recreate one for the recent versions. We will try to check it as soon as possible.
Regards
