### ISSUE TITLE
[15] Non-admin user cannot edit blog post

### ISSUE THREAD

**Issue by auyeung112002** [odoo/odoo#80948]
Impacted versions:
15

Steps to reproduce:
1. Go to rundot v15
2. Login as admin and grant Website Access Right "Editor and Designer" to demo user
![image](https://user-images.githubusercontent.com/8391358/145004736-95f6db26-df48-43e6-9cf2-034aa1a2f3f6.png)
3. Login as demo
4. Go to Website
5. Go to Blog
![image](https://user-images.githubusercontent.com/8391358/145005414-f31a5cb9-8ecd-44c4-bf8f-a3b60699f7c6.png)

6. Go to the first blog
![image](https://user-images.githubusercontent.com/8391358/145005473-2f5dc311-514d-495e-99bb-2c41f18b1f48.png)

7. Click Edit

Current behavior:
JavaScript crashes and access error is raised.
![image](https://user-images.githubusercontent.com/8391358/145005668-3758eae8-0bb8-4a12-a600-a0736201a25c.png)

Expected behavior:
Website Editor can edit blog post

This rpc failed since only admin user have access right of ir.model.fields
https://github.com/odoo/odoo/blob/1ffbcf9787e5efe00d49f18baba0144f631ada51/addons/web_editor/static/src/js/editor/snippets.options.js#L2754

**Comment by mart-e** [comment]
Thanks for the report :+1:
