### ISSUE TITLE
[8.0]Impossible to create a menu with technical access level

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#8096]
Hi,

I have a user who have all technical feature access level.
When I try to add a menu I have this error :

```
self._check_record_rules_result_count(cr, uid, sub_ids, returned_ids, operation, context=context)
  File "/home/florent/DEV/Serveurs/odoo/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/florent/DEV/Serveurs/odoo/odoo/openerp/models.py", line 3478, in _check_record_rules_result_count
    (self._description, operation))
except_orm: (u'Acc\xe8s refus\xe9', u'The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\n\n(Document type: ir.values, Operation: create)')
```

Impossible to create/delete the menu. Yet the user has admin Technical Admin access level.

regards

**Comment by flotho** [comment]
Found,

A model has no access rules

**Comment by flotho** [comment]
Actually, I think it was solved and it's not the case.
Impossible to create or duplicate a menu that points to an action even with a user that has technical features.
Creating a menu without an action defined works perfectly but failed with an action defined.
Tested on different releases

**Comment by flotho** [comment]
commit 02954ba and 4359f65 both failed locally on my database

**Comment by Yenthe666** [comment]
Hi @flotho,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
