### ISSUE TITLE
[7.0] Can't display custom error popus from a report parser class

### ISSUE THREAD

**Issue by LeartS** [odoo/odoo#810]
[Related help question.](https://www.odoo.com/forum/Help-1/question/How-to-raise-a-custom-error-popup-from-a-report-parser-55631)

In the models python code, it's possible to use the exception class ```orm.except_orm``` to display error popus with custom title and message.

Using it in a report parser class won't work: the custom error exception will be visible only in the log, while in the client will always show the error:

    SyntaxError: JSON.parse: unexpected end of data at line 2 column 1 of the JSON data

This makes impossible to show error / warning messages when printing a report.

**Comment by Yenthe666** [comment]
Dear @LeartS,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
