### ISSUE TITLE
[Odoo 14] Error 500 shows traceback in production server

### ISSUE THREAD

**Issue by drkpkg** [odoo/odoo#81013]
Impacted versions: 14.0

Steps to reproduce:

Go to url 
```shell
http://localhost:8069/website/translations/some 
```
Odoo will show the traceback:
```
Traceback (most recent call last):
  File "D:\Projects\odoo_vanilla\odoo\addons\base\models\ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "D:\Projects\odoo_vanilla\odoo\http.py", line 807, in dispatch
    r = self._call_function(**self.params)
  File "D:\Projects\odoo_vanilla\odoo\http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "D:\Projects\odoo_vanilla\odoo\service\model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "D:\Projects\odoo_vanilla\odoo\http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "D:\Projects\odoo_vanilla\odoo\http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "D:\Projects\odoo_vanilla\odoo\http.py", line 532, in response_wrap
    response = f(*args, **kw)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Projects\odoo_vanilla\odoo\addons\base\models\ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "D:\Projects\odoo_vanilla\odoo\http.py", line 807, in dispatch
    r = self._call_function(**self.params)
  File "D:\Projects\odoo_vanilla\odoo\http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "D:\Projects\odoo_vanilla\odoo\service\model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "D:\Projects\odoo_vanilla\odoo\http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "D:\Projects\odoo_vanilla\odoo\http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "D:\Projects\odoo_vanilla\odoo\http.py", line 532, in response_wrap
    response = f(*args, **kw)
TypeError: get_website_translations() missing 1 required positional argument: 'lang'
```

Current behavior:
Showing traceback in a production server can be a security problem.

Expected behavior: 
Show at least only error 500 without traceback in a production server?

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/972555/145085034-6841cade-590f-4b97-80f2-8a426d66a46a.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by celm1990** [comment]
More context:
When scan Odoo instance with some tools(as OWASP ZAP https://www.zaproxy.org/) many URL are mark as vulnerability, this URL is a example of many more

can be introduced on commit https://github.com/odoo/odoo/commit/8b8815f44cc7e8529ba0f841c7366ee6b8e28356

@drkpkg  if you  add `sitemap=False` to `route `can be solution?

CC: @mart-e @odony sorry for ping but this can be risk security, what do you think???

![image](https://user-images.githubusercontent.com/7775116/145128876-d2a160f7-819c-4b35-906a-7c901cf57da6.png)

**Comment by drkpkg** [comment]
Thanks for the reply, I tried sitemap=False with no effect.
I'm trying with a patch making an exception to return a 403 Forbidden, I know it's not the most elegant solution and need more test, the code is this.

```python
# this is in the file odoo/http.py line 519 as start line.
@functools.wraps(f)
        def response_wrap(*args, **kw):
            # if controller cannot be called with extra args (utm, debug, ...), call endpoint ignoring them
            params = inspect.signature(f).parameters.values()
            is_kwargs = lambda p: p.kind == inspect.Parameter.VAR_KEYWORD
            if not any(is_kwargs(p) for p in params):  # missing **kw
                is_keyword_compatible = lambda p: p.kind in (
                    inspect.Parameter.POSITIONAL_OR_KEYWORD,
                    inspect.Parameter.KEYWORD_ONLY)
                fargs = {p.name for p in params if is_keyword_compatible(p)}
                ignored = ['<%s=%s>' % (k, kw.pop(k)) for k in list(kw) if k not in fargs]
                if ignored:
                    _logger.info("<function %s.%s> called ignoring args %s" % (f.__module__, f.__name__, ', '.join(ignored)))
            try:
                response = f(*args, **kw)
                if isinstance(response, Response) or f.routing_type == 'json':
                    return response

                if isinstance(response, (bytes, str)):
                    return Response(response)

                if isinstance(response, werkzeug.exceptions.HTTPException):
                    response = response.get_response(request.httprequest.environ)
                if isinstance(response, werkzeug.wrappers.BaseResponse):
                    response = Response.force_type(response)
                    response.set_default()
                    return response

                _logger.warning("<function %s.%s> returns an invalid response type for an http request" % (f.__module__, f.__name__))
                return response
            except Exception as e:
                # this is where the exception control returns 403
                _logger.error("HTTPException raised with code %s" % e)
                return Response('Forbidden', status=403, content_type='text/html')
```

Gonna try tomorrow with the same Url list from the vulnerability test to check if everything is OK with this.

>NOTE: this is not the solution fellow developer :D

**Comment by odony** [comment]
Indeed, so far Odoo does not take any particular precautions for hiding tracebacks, because that would not be a real protection, and in most cases, the source is out there anyway. It would also mean that extra steps are needed for debugging or troubleshooting (e.g. enabling tracebacks or grabbing the server-side logs, etc.), and that makes using/deploying Odoo more difficult in general, without giving any significant protection in return (meaning: security does not come through hiding that things exist and hoping that nobody will know they're actually there)

Similarly, we don't take much precautions for avoiding crashes when invalid input is being submitted, especially if that's not something you could do through normal usage. In that case Odoo is a GIGO system: garbage in, garbage out ;-)

In summary, this won't be considered as a bug, given our current strategy.

If you want to work on a generic way to hide all tracebacks, you're welcome to do that via your own module / monkey-patches, of course. And if you want to work on avoiding a specific crash to return a cleaner error, you can try to make a PR, and if it's simple and short, we might merge the patch in master.

PS: I'll close the issue to clarify that we don't consider it an open bug, but feel free to continue discussing your options here ;)
