### ISSUE TITLE
[8.0] Point of Sale - Misuse of an already existing order

### ISSUE THREAD

**Issue by wtaferner** [odoo/odoo#8110]
## Impacted versions:
8.0 and above

## Steps to reproduce:
* Go on Runbot and go to Point of Sale (Debug Mode or have a barcode reader at hand)
* Open a new tab and bill some items, pay them and print the receipt
* Do not succeed (Next Order)
* Enter or scan an existing product barcode

## Current behavior:
* It will add the new item to the already paid and printed order stack.
* If you follow the flow you can "pay" and print the order again but nothing will be changed in the backend (which is good) although the customer might get an receipt for something else (same ticket number) which is bad.

## Expected behavior:
* It must not be possible to add anything to a finished/printed order (potential fraud, misuse, chaos)

OPW-647499

**Comment by simongoffin** [comment]
Closed with f4e6dba0973dcc2dda009f4cd0069a5d0e2588c4
