### ISSUE TITLE
[8.0] Reporting > Sales> Sales Analysis > Quotations

### ISSUE THREAD

**Issue by gmoncada** [odoo/odoo#8115]
Hi.
In this menu the following bug appears:

File "/home/odoo/runbot/extra/runbot/static/build/93024-8-0-41929b/openerp/models.py", line 4467, in _where_calc
    where_clause, where_params = e.to_sql()
  File "/home/odoo/runbot/extra/runbot/static/build/93024-8-0-41929b/openerp/osv/expression.py", line 1245, in to_sql
    q, p = self.__leaf_to_sql(leaf)
  File "/home/odoo/runbot/extra/runbot/static/build/93024-8-0-41929b/openerp/osv/expression.py", line 1170, in __leaf_to_sql
    raise ValueError("Invalid domain term %r" % (leaf,))
ValueError: Invalid domain term ('state', 'in', 'draft')

**Comment by JayVora-SerpentCS** [comment]
Hi,
The official code contains <filter name="Quotations" domain="[('state','in',('draft'))]"/> which is the right domain!
Thanks.

**Comment by gmoncada** [comment]
Thanks Jay.

**Comment by JayVora-SerpentCS** [comment]
@gmoncada Did you make sure you have the latest source code?

**Comment by hugosantosred** [comment]
Hi @JayVora-SerpentCS @gmoncada,
It seems that domain isn't correct.
Is not a well formed tuple, a trailing comma is missing.
We tested that domain [('state','in',('draft',))] works successfully.

**Comment by ismaelcj** [comment]
I have another question about this domain.

Maybe I missed something, but, why in this commit https://github.com/odoo/odoo/commit/7f5f945dcfc81e39d36eac06009bee109721c471#diff-1d60a3a0c7a9b66d978d7799efe44de8L52 the *sent* state is removed from Quotations filter and is assigned to Sales filter? @simongoffin 

If a order is sent, you has not sold the product yet, right? So it shouldn't be counted as a sale.

**Comment by simongoffin** [comment]
@ismaelcj 
In the "sale.report" model the field 'state' corresponds to the field 'state' of the "sale.order.line" and if you check the selection field 'state' of "sale.order.line", you can notice that the state 'sent' doesn't exist.This is why the 'sent' state has been removed (to be consistent as explained in commit message).

**Comment by ismaelcj** [comment]
Hi @simongoffin, is true. Sorry about that. Thanks!

**Comment by mart-e** [comment]
Fixed at 38c9deeab4f3a4f9f48f87a4f9634c63a0fa6e13
Thanks for the report
