### ISSUE TITLE
Self.write does not work in combination with Warnings

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#8118]
**Self.write statements do not execute when having a warning in the function**

Impacted versions:

 - 8.0 and above

Steps to reproduce:

 1. Create a function that goes of when you click a button
 2. Place a self.write in it to update a field
 3. You will see the field being updated.
 4. Add a Warning in the function anywhere along with the self.write
 5. Click the button again => The warning will show but the self.write will not be executed

Sample code not doing the self.write:
```
try:
    _logger.warning('Everything is fine here.')
   raise Warning(_('Please make sure that the directory ' + odooPath + ' has enough access rights so that the user from the Odoo service can create new files in this location. You should change the permissions from this folder with a chmod.'))
    #This will not be executed.
    self.write({'state': "installed"})
except:
    _logger.critical('We have a problem.')
```

Sample code doing the self.write:
```
try:
    _logger.warning('Everything is fine here.')
    #This will now be executed.
    self.write({'state': "installed"})
except:
    _logger.critical('We have a problem.')
```
<b>Note:</b> This is tested with states.

Current behavior:

 - self.write is not executed if there is a warning in the function

Expected behavior:

 - Self.write is updated, no matter of a Warning or not.

**Comment by Yenthe666** [comment]
@odony sorry for the ping but I'd like to verify something.
Is this wanted behaviour as in values should not update when a Warning goes off since it usually means something is wrong? Or would that really be a bug?

**Comment by xmo-odoo** [comment]
```
raise Warning
```
This throws an exception, the `write` call isn't even going to be reached *that's basic Python behaviour* and it certainly isn't going to be changed.

And even if it were by moving the raise after the write the transaction is going to get rollbacked (that's Odoo stuff, it's unlikely to be changed either).

**Comment by Yenthe666** [comment]
@xmo-odoo thanks for the information. But shouldn't the write be executed when it is above the Warning? Python interprets line by line so my write should be called before the Warning and should update the field. Is this afterwards being reverted because it fails after the write or?
I'm just curious to what the exact behaviour is. Imagine if you have an automated script to install something in Odoo and when it fails you want to change your state to failed.. this wouldn't be possible here then.

**Comment by xmo-odoo** [comment]
> But shouldn't the write be executed when it is above the Warning?

The write will indeed be executed, but then an exception is raised and unless it's caught by an exception handler somewhere that'll lead to Odoo rollbacking the current transaction (since the transaction is in error and thus considered invalid), effectively undoing it.

> Imagine if you have an automated script to install something in Odoo and when it fails you want to change your state to failed.. this wouldn't be possible here then.

Nope, you would need to perform *that* update in a separate transaction. Or you'd need to cleanup the current transaction yourself bu that's iffy as hell and I would not recommend that.

**Comment by Yenthe666** [comment]
Makes complete sense. Could you care to share the way to do an update in a separate transaction? Are there any best practices for that?
Thanks for the detailed information @xmo-odoo :+1:

**Comment by xmo-odoo** [comment]
> Could you care to share the way to do an update in a separate transaction? Are there any best practices for that?

Standard stuff,

1. Transactions are bound to cursors so you need to get a new cursor to the current database, something along the lines of:

        newcr = RegistryManager.get(cr.dbname).cursor()

   then you can either use that directly (for raw SQL queries) or use it to initialise a new `openerp.api.Environment` to query via the ORM. The former is generally recommended, as well as doing as few operations as possible in the "side cursor".
2. you'll have to properly commit and close the cursor (or use it as a context manager to do that for you)
3. avoid altering the same tables in both transactions, there's a risk of each transaction waiting on the other one and the connections being deadlocked

**Comment by Yenthe666** [comment]
Alright I know enough! Thank you for your time :smile:
