### ISSUE TITLE
Database backup form is not working in saas-6

### ISSUE THREAD

**Issue by be-cloud-js** [odoo/odoo#8119]
To reproduce :
- install saas-6
- create a database
- go to archive database

I have been able to identify the issue, the format field is duplicated in web module, file base.xml line 235
                    <tr>
                        <td><label>Format:</label></td>
                        <td>
                            <input type="radio" name="format" checked="checked" value="zip" />
                            <label for="format" title="Archive containing a dump of your database and your whole filestore">Zip</label>
                            <input type="radio" name="format" value="binary" />
                            <label for="format" title="Binary dump of your database (PostgreSQL dump)">Binary</label>
                        </td>
                    </tr>

The backup_format has been implemented just above, it seems to be a duplicate.

Jerome

**Comment by rvalyi** [comment]
related to an unsupported Odoo version. Can it be closed?
cc @Yenthe666

**Comment by Yenthe666** [comment]
Hi @be-cloud-js,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
@rvalyi thanks a lot for the ping!

Regards,
Yenthe
