### ISSUE TITLE
Incorrect float rounding

### ISSUE THREAD

**Issue by Kosaaaaa** [odoo/odoo#81224]
Impacted versions: 14.0 
`(14, 0, 0, 'final', 0, 'e')`

Steps to reproduce:
```
>>> from odoo.tools import float_round
>>> float_round(32.410000000000004, precision_digits=2)
32.410000000000004
>>> float_round(32.410000000000004, precision_rounding=0.01)
32.410000000000004
```

Current behavior: float_round return 32.410000000000004 instead of 32.41

Expected behavior: return correct rounding -> 32.41

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by mart-e** [comment]
Hi,

Thanks for your report but float_round works as expected. If you want to display the result of a `float_round`, you have to use `float_repr`. If you want to compare two rounded floats, you have to use `float_compare`.
```
>>> float_repr(32.410000000000004, precision_digits=2)
'32.41'
>>> float_compare(32.410000000000004, 32.41, precision_digits=2)
0
```
