### ISSUE TITLE
[7.0][Bug] Weird visual comportment with o2m list on project phase in a template project

### ISSUE THREAD

**Issue by jlaloux** [odoo/odoo#8127]
To reproduce this bug. Simply take the "The Jackson Group's Project" in Odoo demo data on Runbot.

You can see that the project is not a template project. Simply click on the "Phases" button
![image](https://cloud.githubusercontent.com/assets/7678583/9330268/81e6f292-45b8-11e5-90f5-dc57ef061e31.png)

Here is the Phases list
![image](https://cloud.githubusercontent.com/assets/7678583/9330295/aeaad9ec-45b8-11e5-9cc9-909e3c7cceea.png)

Select the first one and go to task details:
![image](https://cloud.githubusercontent.com/assets/7678583/9330306/c7f2ad4e-45b8-11e5-9ed7-79fb586c8843.png)

You are able to see the list correctly without problem.

Now return to your project and set it as a template project. And reproduce the same steps and here is the result:
![image](https://cloud.githubusercontent.com/assets/7678583/9330354/1c236eda-45b9-11e5-9a08-c7eafb9bde97.png)

The list is now empty !

And if you press on "next record" and after "previous record":
![image](https://cloud.githubusercontent.com/assets/7678583/9330382/55167cb4-45b9-11e5-8cb4-0ca3a4fcc15f.png)

You will be able to see the list with the data's again:
![image](https://cloud.githubusercontent.com/assets/7678583/9330404/756b039a-45b9-11e5-8d5a-6ec5751c3281.png)

**Comment by Yenthe666** [comment]
Hi @jlaloux,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
