### ISSUE TITLE
[15] unchecking "can be sold" on a product has no effect on ecommerce checkout

### ISSUE THREAD

**Issue by zeroheure** [odoo/odoo#81304]
Impacted versions: master, 15, 14 and probably olders (tested on runbot and demo)

Steps to reproduce: Choose a web published product, uncheck "can be sold", go to the product url on website

Current behavior: Product disapear from website menus and search. Its web page can be accessed from its url and one can buy the product (add to basket and checkout): a bank transfert payment was created on the website but not in back office.

Expected behavior: I think that the whole behavior is wrong regarding ecommerce, because for SEO reasons (see below), you may prefer to keep the product page apparent (while moving the product in another website category ?). But what is needed is **to disable the `add to cart` button**, make sure that it can't be checked out, and add a short message explaining why the product is not sellable at the moment.

Various SEO reasons: the product page is well optimized for Google, it contains some links to other products pages, it is an entry page in your website, other websites talks about it, Google likes it a lot, etc.

**Comment by altela** [comment]
Did you tried toclear cache of your browser?

**Comment by pierre-pde** [comment]
Hello, you say product is accessible with URL.
I can't in master;
https://bit.ly/3LSrWB4

**Comment by zeroheure** [comment]
Behaviour changed in current master (will become Odoo 16). Product is shown, but cart ir hidden under a "This product has no valid combination." message. 
I close.
