### ISSUE TITLE
[8.0] odoo Merge 2 model into 1 model

### ISSUE THREAD

**Issue by blob1** [odoo/odoo#8133]
I want to merge model res.users and res.groups into 1 model, like query union, so I get 1 list of both users and groups, Could it be possible? Thank you

**Comment by flotho** [comment]
Hi,

I'm not really sure of that. You point a SQL behaviour but the object paradigm works a little bit different.
Maybe you could add/use relationnal fiels in the groups/users that will facilitate you to have those two datas fast.
Regards

**Comment by gdgellatly** [comment]
Sure it is.  Most on screen reports work this way.  Loads of examples in code but invoices analysis comes to mind.  

You just Create a model to match your sql view.

**Comment by blob1** [comment]
@flotho Thank you but not that what I need
@gdgellatly Thank you, it works

I did to overide init function for creating view like this :

![screenshot from 2015-08-23 06 23 25](https://cloud.githubusercontent.com/assets/3858791/9426272/9748668e-495f-11e5-9847-d2591094f570.png)

It works fine
