### ISSUE TITLE
[account]invoices doesn't change state to paid

### ISSUE THREAD

**Issue by JulioSerna** [odoo/odoo#8135]
Hello,
In some invoices even when after the payment the balance is 0 the state does not change to paid, I have noticed this happens when there is incongruence of rounding between amount total of the invoice and amount residual of journal item of the invoice

I have reproduced this issue using inventory valuation in real time
 
Impacted version
* 8.0

Steps to reproduce

* To set decimal precision of Account and Product price  = 4
* To create product test12 with inventory valuation in real time and set account to Price Difference Account
* To set product with costing method "Average" and cost price = 11.24
* To create Tax 16% with amount = 0.16
* To create one invoice with the product test12 with quantity = 2057, price unit=11.9150 and tax 16%
* To validate invoice
* To create bank statement with amount 28430.62 and reconcile

Current Behavior
* The balance of invoice is 0.0 but the state is open

Expected Behavior
* The invoice change to state paid

I made video,
https://www.youtube.com/watch?v=k39BHBgyRjU

**Comment by JulioSerna** [comment]
Hello, 

The rounding that you added to "price" without secondary currency, must be added also in amount_currency because [this case can also happen](https://github.com/odoo/odoo/blob/8.0/addons/account/account_move_line.py#L925:L926)

**Comment by beledouxdenis** [comment]
Julio, 

We were comfortable to round the `line['price']` as it was already the case when the currency of the invoice was different than the currency of the company, through the `currency.compute method`, as you can see here:

https://github.com/odoo/odoo/blob/8.0/addons/account/account_invoice.py#L742-L743

However, in this case of the different currencies, the `line['amount_currency']` isn't rounded. We are therefore less comfortable to make such a change.

Therefore, unless you have a functional use case that proves the issue exists, we just won't change anything more in here.

Regards,

**Comment by JulioSerna** [comment]
Hello Denis,

This is the case functional,
https://youtu.be/oS1GgmrZM3s

Regards,
