### ISSUE TITLE
[14.0][ENTERPRISE][l10n_cl_edi] Fetchmail bug

### ISSUE THREAD

**Issue by MaxwellJake** [odoo/odoo#81443]
Impacted versions: 14.0 ENTERPRISE

Steps to reproduce: Configure an incoming imap mail server for DTE to be used by "l10n_cl_edi.models.fetchmail_server" and try to fetch email.

Current behavior: General failure when trying to fetch mail from imap server DTE.

Expected behavior: Fetch the mail correctly and mark it as seen.

Video/Screenshot link (optional):

```
2021-12-14 17:57:39,991 5147 INFO odoo-main-1000000 odoo.addons.base.models.ir_cron: Starting job `Mail: Fetchmail Service`.
2021-12-14 17:57:40,000 5147 INFO odoo-main-1000000 odoo.addons.l10n_cl_edi.models.fetchmail_server: Start checking for new emails on imap IMAP server DTE 
2021-12-14 17:57:40,786 5147 INFO odoo-main-1000000 odoo.addons.l10n_cl_edi.models.fetchmail_server: General failure when trying to fetch mail from imap server DTE. 
Traceback (most recent call last):
  File "/home/odoo/src/enterprise/l10n_cl_edi/models/fetchmail_server.py", line 74, in fetch_mail
    imap_server.uid('STORE', uid, '+FLAGS', '\\Seen')
  File "/usr/lib/python3.8/imaplib.py", line 881, in uid
    typ, dat = self._simple_command(name, command, *args)
  File "/usr/lib/python3.8/imaplib.py", line 1205, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/lib/python3.8/imaplib.py", line 1030, in _command_complete
    raise self.error('%s command error: %s %s' % (name, typ, data))
imaplib.IMAP4.error: UID command error: BAD [b"[CLIENTBUG] syntax: expecting '(', found '\\'"]
2021-12-14 17:57:40,996 5147 INFO odoo-main-1000000 odoo.addons.base.models.ir_cron: Job `Mail: Fetchmail Service` done.
```

This would be fixed by replacing "/home/odoo/src/enterprise/l10n_cl_edi/models/fetchmail_server.py" line 74:
`imap_server.uid('STORE', uid, '+FLAGS', '\\Seen')`
With:
`imap_server.uid('STORE', uid, '+FLAGS', '(\\Seen)')`

Support ticket number submitted via odoo.com/help (optional): 2714596

@Danisan

**Comment by MaxwellJake** [comment]
A comment on this, as per RFC9051 the "Seen" system flag is actually "\Seen", I'm not sure if the double backslash in here is working for escape so it's actually a single backslash.

**Comment by MaxwellJake** [comment]
As a normal Odoo Enterprise user, I cannot do PRs at the Enterprise repository.
But since I'm using Odoo.sh I can take a look at the code with it.

![image](https://user-images.githubusercontent.com/82674258/146256060-9d930d1d-8a67-4f0b-ad65-3fcdd92e22d7.png)

I did a temporal module which replaces both '\\Seen' with '(\\Seen)', it fixes it and everything seems okay.

![image](https://user-images.githubusercontent.com/82674258/146256593-aa7e0737-6e82-4149-9006-ec28f6676860.png)

May I get a mention when this is fixed so I uninstall my custom module?

Thanks!

**Comment by nle-odoo** [comment]
The standard is giving example with parenthesis (https://datatracker.ietf.org/doc/html/rfc3501#section-6.4.6):

```py
A003 STORE 2:4 +FLAGS (\Deleted)
```
checking functionally, `imap_server.store(num, '+FLAGS', '(\\\\Seen)')` and `imap_server.store(num, '+FLAGS', '\\\\Seen')` has the same result for GMAIL, in the original report it says that without parenthesis this is failing for "Zoho mail", so this is probably dependent on the mailing service.

checking the command sent (with `imap_server._cmd_log`), I see this:

```py
> imap_server.uid('STORE', uid, '+FLAGS', '\\Seen')
("> b'MBKP12 UID STORE 2216 +FLAGS \\\\Seen'", 1650548731.4068327)
("< b'MBKP12 OK Success'", 1650548731.4581716)
> imap_server.uid('STORE', uid, '+FLAGS', '(\\Seen)')
("> b'MBKP13 UID STORE 2216 +FLAGS (\\\\Seen)'", 1650548735.7968395)
("< b'MBKP13 OK Success'", 1650548735.8442018)
> imap_server.store(uid, '+FLAGS', '\\Seen'
("> b'MBKP14 STORE 2216 +FLAGS (\\\\Seen)'", 1650548772.1436827)
("< b'MBKP14 OK Success'", 1650548772.1861954)
```
so it seems that adding parenthesis (or using store command directly) are good fixes.

side note: there is exactly the same code in l10n_it_edi.

**Comment by jco-odoo** [comment]
@nle-odoo What is with the 4 \?

**Comment by Danisan** [comment]
@nle-odoo @jco-odoo @MaxwellJake 

https://github.com/odoo/odoo/pull/89305

https://github.com/odoo/odoo/pull/89305

**Comment by nle-odoo** [comment]
> @nle-odoo What is with the 4 \ ?

`\` in bytes is `b'\\'`

`b'\\'` in string representation is `"b'\\\\'"` (`repr(b'\\')`)

so `"> b'MBKP14 STORE 2216 +FLAGS (\\\\Seen)'"` is just `MBKP14 STORE 2216 +FLAGS (\Seen)`
