### ISSUE TITLE
Computed fields without dependencies are not computed in Odoo 8

### ISSUE THREAD

**Issue by deepa4lok** [odoo/odoo#8145]
Computed Fields with Store property doesn't gets computed while creating the records....
Any fix for this will be a great help....

**Comment by Yenthe666** [comment]
Hi @deepa4lok,

Thanks a lot for your bug report and sorry for the late reply.
When you set a computed field to `store=True` it will not recompute, this is how the framework works and this is desired behaviour.

Regards,
Yenthe
