### ISSUE TITLE
[Idea] fake field for qweb template

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#81452]
Hi @rco-odoo @xmo-odoo @Yenthe666 

In some qweb template (dashbord, website, email template), there are no a good tools to format currency or float, when it is not a real field. Issue related https://github.com/odoo/odoo/pull/81449.

It is possible to format in python, but after you can't make operation in the qweb (t-if, ...). Or it is not a good idea to inherit (impossible to compare value, it depends of the context language).

The idea is create a fake field for raw value.

Exemple:
```python
value = 7000.6701 # from read_group or SQL query
f_value = fields.Float.Fake(value, digists=2)

amount = 10
currency = self.env.ref('base.eur')
f_amount = fields.Monetary.Fake(amount, currency_id=currency)
```

```xml
<template>
<span t-field="f_value"/>
<span t-if="f_amount > 10" t-field="f_amount"/>
</template>
```

Render:
```xml
7 000,67
10,00 €
```

**Comment by pedrobaeza** [comment]
No need of that. Just use `t-esc="..." t-options="{widget: 'monetary' ...}"` or something similar I don't remember the exact syntax, but take that lead.

**Comment by Yenthe666** [comment]
Yep, agreed with Pedro.
