### ISSUE TITLE
[8.0] Bug - Full report translation error in Point of Sale -> Sale details

### ISSUE THREAD

**Issue by rafaelbn** [odoo/odoo#8150]
Hi

Go to:

* Setting -> Translations - Load a translation
* Load Spanish translation (for example)
* Go to the user preferences and in language choose the new language installed
* You will see Odoo in the **new language**
* Go to point of sale - Products
* Select one product "Queso Camembert francés" for example
* Click in "edit" and go to the translation of the name:
* (you will check that product is translated).

![19-08-2015 21-37-20](https://cloud.githubusercontent.com/assets/8736623/9366998/fc238720-46ba-11e5-9623-0bff02972677.png)

![19-08-2015 21-38-17](https://cloud.githubusercontent.com/assets/8736623/9367006/097d45a0-46bb-11e5-9e83-63b6cea32b8c.png)

* Now Go to Point of sale - New session
* Buy "Queso Camembert francés" (for example) and pay
* Close POS and session
* Go To Reports -> Point of sale - Sale details - Print report
* You will see that all report is in the new language but products name is in original name
* So this report doesn't translate any product.

![19-08-2015 21-32-13](https://cloud.githubusercontent.com/assets/8736623/9367019/17961644-46bb-11e5-8139-f2371b485f5a.png)

Thanks

**Comment by beledouxdenis** [comment]
Closed with 2d3973481f6252797ca8f405fabca153e6ec040b.
