### ISSUE TITLE
[14.0] Python lines translated into German

### ISSUE THREAD

**Issue by ProMediaCom** [odoo/odoo#81529]
Impacted versions: 14.0

Current behavior:
You [have translated](https://github.com/odoo/odoo/blob/1ad7986dad52d2056679b25779505b2243749f3c/addons/sale/i18n/de.po#L85) the lines of code (Sale module, i18n) into German.

**Comment by intero-chz** [comment]
Probably translated by a machine?

**Comment by odony** [comment]
Thanks for reporting, I've dropped that erroneous translation, it should be synchronized soon in the source code.

You can contribute to translations yourself easily if you're interested, cfr: https://github.com/odoo/odoo/wiki/Translations
