### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by JonhSilver** [odoo/odoo#81618]
Impacted versions: 6.0

Steps to reproduce: 
![image](https://user-images.githubusercontent.com/24619483/146581721-f9bc313a-54d7-4923-b450-68326a09268d.png)
![image](https://user-images.githubusercontent.com/24619483/146582148-09b16840-dabe-4760-909e-fc5c81005753.png)

How to create, edit, change invoicing templates and add them to right toolbar?
How to send directly to email this invoice instead of open in pdf editor?

**Comment by omalbastin** [comment]
V6 support is over. You can ask the same in odoo help forum https://www.odoo.com/forum/help-1

**Comment by JonhSilver** [comment]
It is not possible to post into forum

**Comment by zeroheure** [comment]
@JonhSilver On the contrary, it is very easy to post on Odoo forums

**Comment by mart-e** [comment]
@JonhSilver 6.0 is no longer supported for years and has not received security updates. It is strongly recommanded that you upgrade.
