### ISSUE TITLE
[Not Issue][V15.0] Stock: Why button_validate defined twice with visbility condition A or B

### ISSUE THREAD

**Issue by omalbastin** [odoo/odoo#81625]
Please check the lines
https://github.com/odoo/odoo/blob/03bf311bfde98f28a9b8e73953869a42b828c5e3/addons/stock/views/stock_picking_views.xml#L242

and 

https://github.com/odoo/odoo/blob/03bf311bfde98f28a9b8e73953869a42b828c5e3/addons/stock/views/stock_picking_views.xml#L243

**Comment by ray-odoo** [comment]
Check the invisible condition and the class. One is showing the button highlighted under certain circumstances and the other is showing the button without highlighting in the opposite circumstances.

**Comment by omalbastin** [comment]
okey. So closing it.
