### ISSUE TITLE
[8.0][BUG] Wrong language taken for translation in Payment followup report

### ISSUE THREAD

**Issue by jlaloux** [odoo/odoo#8167]
Here are the steps to reproduce the bug:

Imagine you have multiple languages installed:
![image](https://cloud.githubusercontent.com/assets/7678583/9383028/eb5d6286-4745-11e5-9a7e-24bddad8f89a.png)

You create a partner with language set to french:
![image](https://cloud.githubusercontent.com/assets/7678583/9383044/1692fb46-4746-11e5-897a-b9689e59d275.png)

You create an invoice with something inside it and you set the due date to a date in the past
![image](https://cloud.githubusercontent.com/assets/7678583/9383091/83cdf01c-4746-11e5-941d-6150aeba27b8.png)

You validate this invoice and you return to the customer form view. If you go into "Payment Follow-up" screen and you click on "Print Overdue Payments"
![image](https://cloud.githubusercontent.com/assets/7678583/9383120/c26a2a84-4746-11e5-8f8c-055912e710ec.png)

You will see that the text is correctly into the language of the partner but the labels from the report is in the language of the user. That should be in the language of the partner too.
![image](https://cloud.githubusercontent.com/assets/7678583/9383159/ff972d12-4746-11e5-91f9-9a778abc98d5.png)

**Comment by Yenthe666** [comment]
Hi @jlaloux,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
