### ISSUE TITLE
[8.0][MultiThread]Impossible to install accounting plan cause of Recursive call to account

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#8174]
Hi,

I tried to install the france accounting plan an I have this message :

```
ValidateError

Field(s) `parent_id` failed against a constraint: Erreur !
Vous ne pouvez pas créer de comptes récursifs.

Error details:
CPU time limit exceeded. 
```

This happens only when workers > 0, with worker= 0 we have no problem.

Regards

**Comment by Yenthe666** [comment]
Hi @flotho,

Thanks a lot for your report and sorry for the late response!
I've just tested this on the latest Odoo 8.0 and was still able to reproduce this:
![image](https://cloud.githubusercontent.com/assets/6352350/19034462/dbd590ca-8963-11e6-89d1-a93cecb3521a.png)
@qdp-odoo and @csnauwaert can you guys have a look at this please?

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Hi @flotho,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
