### ISSUE TITLE
QWeb : Reports t-if and t-esc combination

### ISSUE THREAD

**Issue by damdam-s** [odoo/odoo#8177]
In Qweb reports, if you write a report part like the following one
```xml
<td>
    <span t-if="difference &gt; 0" t-esc="float_time_convert(difference)"/>
    <span t-if="difference &lt;= 0">-</span>
</td>
```
the two `span` tags will be displayed.

The workaround is the following code but I think this one is more difficult to read/understand than the previous one :
```xml
<td t-if="difference &gt; 0">
   <span t-esc="float_time_convert(difference)"/>
</td>
<td t-if="difference &lt;= 0">
    <span>-</span>
</td>
```

**Comment by xmo-odoo** [comment]
Multiple directives on the same element is an UB in the current qweb-python implementation, don't do that.

An other alternative, which is almost as short and readable as your first snippet, is:
```xml
<span t-if="difference &gt; 0"><t t-esc="float_time_convert(difference)"/></span>
<span t-if="difference &lt;= 0">-</span>
```

**Comment by damdam-s** [comment]
@xmo-odoo : Ok. thanks
