### ISSUE TITLE
Data payment in payroll

### ISSUE THREAD

**Issue by luistorresm** [odoo/odoo#818]
The version 6.0 of OpenERP had a functionality in payslip, when I can pay this with a button, also with a boolean field I could see if it already was payment, too in the register was added the movements generated by the paid, this with module hr_payroll_account, equal as the functionality of the invoice.

How I can get  this functionality in the OpenERP v. 7?

I attached captures the behavior of version 6.0, and captures of version 7.0

Regards
![captura de pantalla de 2014 06 27 12 51 19](https://cloud.githubusercontent.com/assets/7606656/3415806/039a1422-fe25-11e3-9f30-2e0eddd1d38b.png)
![captura de pantalla de 2014 06 27 12 51 27](https://cloud.githubusercontent.com/assets/7606656/3415805/0399d8b8-fe25-11e3-89a2-8a3318e3b69f.png)
![captura de pantalla de 2014 06 27 12 51 36](https://cloud.githubusercontent.com/assets/7606656/3415807/039a4d0c-fe25-11e3-98d9-9838a4037e4a.png)
![captura de pantalla de 2014 06 27 12 51 43](https://cloud.githubusercontent.com/assets/7606656/3415808/039a4f32-fe25-11e3-94fe-55a85a8c3eb8.png)

captures of version 7.0
![employee payslips openerp](https://cloud.githubusercontent.com/assets/7606656/3416194/042ecac2-fe2a-11e3-96dd-f7bb57f25bd3.png)
![supplier payments openerp2](https://cloud.githubusercontent.com/assets/7606656/3416196/06f557bc-fe2a-11e3-80d8-612a09c5cb8e.png)
![employee payslips openerp3](https://cloud.githubusercontent.com/assets/7606656/3416197/09906d90-fe2a-11e3-85e8-5edb0717476c.png)

**Comment by Yenthe666** [comment]
Dear @luistorresm,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
