### ISSUE TITLE
[8.0] graph view_type attribute ignored on one2many fields.

### ISSUE THREAD

**Issue by nhomar** [odoo/odoo#8181]
Hello.

I do not know it is an error on my side or this feature was removed or simply I missunderstand the documentation.

On new doc [(as before)](https://www.odoo.com/documentation/8.0/reference/views.html#semantic-components) we had the attribute view_type (now mode) on one2many fields, I just developed a module very simply adding this view_type attribute to be graph, my field definition is:

This is ignored:

``` xml
<field name="value_ids" nolabel="1" view_type="graph">
  <graph string="Simple list of values" type="line">
    <field name="sequence"/>
   <field name="value" operator="+"/>
  </graph>
</field>
```

this is ignored also:

``` xml
<field name="value_ids" nolabel="1" view_mode="graph">
  <graph string="Simple list of values" type="line">
    <field name="sequence"/>
   <field name="value" operator="+"/>
  </graph>
</field>
```

when I set the `mode` to `graph` it returns me an error:

``` javascript


TypeError: this.search_view is null

http://localhost:48069/web_graph/static/src/js/graph_view.js:118

```

this return me the error above.:

``` xml
<field name="value_ids" nolabel="1" mode="graph">
  <graph string="Simple list of values" type="line">
    <field name="sequence"/>
   <field name="value" operator="+"/>
  </graph>
</field>
```

I expect a simply line drawed (I used the same definition for the view graph for such model and it works).

Am I missing something or it is a bug?

**Comment by odony** [comment]
It sounds like a bug, as the syntax seems ok in your last example. That said, the graph view for o2m fields is unused, mostly obsolete and likely to be removed in the future, so that could explain your results.

**Comment by nhomar** [comment]
@odony 

I feel that as unused because such kind of bugs.

We used a lot in the past and due to the leak of support we tried to use some links buttons instead one2many advanced graphics.

But instead remove the support it should be cool if for future this feature comes back IMHO is very useful.

I will come bck with few examples, I developed already a widted for my own purpose without use the original graph view.

Reading the code the problem is that the actual view graph implementation declare the dataset based on the search_view object, as we do not have a search view available in the form view then it explode.

IMHO the only thing we need (but I didn't find a correct approach because my leak of js knowledge and leak of documented code) is be able to have one search_view instantiated by every one2many OR define the dataset on views graph with a normal search appending the search elements JUST when is a view and not a widget.

I understand it is complex but IMHO it IS useful, don't remove please.!

**Comment by wilberttanoto** [comment]
Hi @nhomar , any solution regarding this?

I am currently also stuck for this part.

**Comment by nhomar** [comment]
@wilberttanoto Totally ignored. Not possible yet even on master, but as the api improved, We can do cleanest extensions... Then I will cloe it as not solved, but given the tools to work with! :-1:

**Comment by karandinakaran** [comment]
oooo
