### ISSUE TITLE
[9.0] website_less module is not installable

### ISSUE THREAD

**Issue by bringsvor** [odoo/odoo#8182]
While trying to evaluate 9.0 I tried to install the clean theme that I currently use in production.

But the website_less module is not installable. Just adding it to the addons brings this error:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/Werkzeug-0.8.3-py2.7.egg/werkzeug/serving.py", line 159, in 
run_wsgi
    execute(app)
  File "/usr/local/lib/python2.7/site-packages/Werkzeug-0.8.3-py2.7.egg/werkzeug/serving.py", line 146, in execute
    application_iter = app(environ, start_response)
  File "/home/odoo9/odoo/openerp/service/server.py", line 245, in app
    return self.app(e, s)
  File "/home/odoo9/odoo/openerp/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/home/odoo9/odoo/openerp/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/home/odoo9/odoo/openerp/http.py", line 1345, in __call__
    self.load_addons()
  File "/home/odoo9/odoo/openerp/http.py", line 1364, in load_addons
    m = __import__('openerp.addons.' + module)
  File "/home/odoo9/odoo/openerp/modules/module.py", line 61, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/home/odoo9/odoo/addons/website_less/__init__.py", line 1, in <module>
    import ir_qweb
  File "/home/odoo9/odoo/addons/website_less/ir_qweb.py", line 276, in <module>
    class SassAsset(StylesheetAsset, openerp.addons.base.ir.ir_qweb.SassAsset):
AttributeError: 'module' object has no attribute 'SassAsset'
2015-08-21 11:42:54,892 6509 INFO ? openerp.service.server: Initiating shutdown

Soo, I guess SassAsset is no more, but what has replaced it? Or is there a newer version of website_less available somewhere?

**Comment by rim-odoo** [comment]
`website_less` does not exist anymore in Odoo 9.0

**Comment by tejastank** [comment]
Face same issue.  9.0
class SassAsset(StylesheetAsset, openerp.addons.base.ir.ir_qweb.SassAsset):

AttributeError: 'module' object has no attribute 'SassAsset'

**Comment by Hashem-j2ee** [comment]
I try to add a theme in odoo but I fail 
I open the cmd, but when type "odoo.py" or "odoo.py scaffold" I get: "odoo.py is not recognized as an internal or external command
I found odoo.exe but odoo.py where ?

**Comment by Hashem-j2ee** [comment]
please help me

**Comment by Hashem-j2ee** [comment]
on Windows it is not "odoo.py" but "odoo.exe"   how to run odoo by cmd?

**Comment by Hashem-j2ee** [comment]
on Windows it is not "odoo.py" but "odoo.exe"  how to run odoo with/by cmd

**Comment by prashantd** [comment]
@rim-odoo : If website_less does not exist for odoo 9.0, why does the theme tutorial documents give this warning? (https://www.odoo.com/documentation/9.0/howtos/themes.html)

This tutorial requires having installed Odoo v9.0 and the Theme Support Engine (website_less) module. https://www.odoo.com/apps/9.0/website_less/

**Comment by kartikdanidhariya** [comment]
i also have same problem in my odoo v9
when i try to install website_less so it return error
AttributeError: 'module' object has no attribute 'SassAsset'
let me know if you have any solution.

**Comment by rim-odoo** [comment]
@prashantd It looks this tutorial is outdated.

**Comment by tejastank** [comment]
Might this helps, http://goo.gl/uNVyqR
Hope so, then restart server.

**Comment by kartikdanidhariya** [comment]
can you please provide latest reference for customize theme in odoo version 9

**Comment by tansadio** [comment]
Do you have fixed this issue?

**Comment by tansadio** [comment]
Do you have fixed this issue?

**Comment by mart-e** [comment]
@tansadio yes: don't install website_less

**Comment by tansadio** [comment]
@mart-e my themes module depends modules website_less otherwise this module does'nt work.

What is the best way?

**Comment by mart-e** [comment]
@tansadio no, that's what we said above, you don't need it anymore, everything is in `website` in v9

**Comment by tansadio** [comment]
ok @mart-e . Thanks a lot. 

I will test it .

**Comment by tansadio** [comment]
I have no error with the website less module. except that the theme_clean module uses some code that depends on this module. So I also errors in the theme_clean
