### ISSUE TITLE
Product Name Issue in XMLRPC or JSONRPC

### ISSUE THREAD

**Issue by Elblassy** [odoo/odoo#81874]
Impacted versions: [13.0, 14.0]

Steps to reproduce: Create new product with user has (AR) language

Current behavior:

If i change this name to any other name ( also change it in en translation ) i get first name in jsonrpc2 and new name not changed 

Expected behavior:

when change name it change in all language and it's name also

**Comment by pumppi** [comment]
Do you send language context in json rpc?

**Comment by odony** [comment]
Everything seems to be working as expected for translations in 13/14.0. As @pumppi mentioned, you may need to manually pass the `lang` context parameter in your RPC calls if you want to get the same values as with the web client.
You can use the debugger of your browser to watch the context being passed by the web client in all RPC calls.

Please feel free to reopen if you think there is a real bug, but in that case please provide complete steps to reproduce starting with a fresh default installation of Odoo (or preferably on runbot.odoo.com), including a sample RPC script that reproduces your issue.
