### ISSUE TITLE
[V8] interface issue back to list

### ISSUE THREAD

**Issue by PhilippeBach** [odoo/odoo#8187]
In customer view
 when you have the list
 you can go from 1-80
and after from 81-160
after when you clic on a customer to view the record
and back to list   the list reset on 1-80
the list button dont memorize the position in list
could we do something?

**Comment by Yenthe666** [comment]
@sle-odoo any update on this one? It would still be handy! 😄

**Comment by sle-odoo** [comment]
I think this is actually a wanted behavior. I'm pretty sure we won't patch that in v8 but maybe @ged-odoo can give you insight?

**Comment by Yenthe666** [comment]
@sle-odoo against the master would be a perfect moment though. Curious about the feedback from ged-odoo. Perhaps there is a good technical reason not to.

**Comment by ged-odoo** [comment]
@Yenthe666 not 100% sure, but I believe we solved this one with the new views.  This is definitely annoying.  Now, as Simon said, it is unlikely we will fix the issue in v8, unless someone submit an obviously simple PR.
