### ISSUE TITLE
One2many function filed in new API

### ISSUE THREAD

**Issue by meswapnilwagh** [odoo/odoo#8190]
how to write below filed in new odoo API
```
'picking_ids': fields.function(_get_picking_ids, method=True, type='one2many', relation='stock.picking', string='Picking associated to this sale'), 
```

I tried with 
```
picking_ids = fields.One2many('stock.picking',
                                    compute = "_get_picking_ids",
                                    string="Reference")
```
Its not working for me

**Comment by ludwiktrammer** [comment]
What do you mean by "not working"? This should work (although most of the argument you used besides compute are unnecessary) provided your `_get_picking_ids` method is correct.

**Comment by meswapnilwagh** [comment]
Not working means in ``one2many``` filed we need to give one reference/relational field of type ```many2one``` but if you see in old API we have not mention any reference/relational field we just set type ```one2many```, but in new API we cant right it like that and if we mention reference/relational field it will not assign the the IDs that I am returning from the function ```_get_picking_id```

**Comment by ludwiktrammer** [comment]
Ok, scratch my previous post.

But if you don't want to give a `inverse_name`, so presumably this is NOT a reverse side of a many 2 one relationship, why do you insist on using a `One2many` field instead of a `Many2many` field?

**Comment by meswapnilwagh** [comment]
@ludwiktrammer it work for me thanks.
