### ISSUE TITLE
Hash Indexes could be revisited

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#8192]
@odony In the following code from ir_tranlsation you see the fixme for hash indexes.  Modern(er) versions of postgres increased the size limit from 1/3 of 8k to 8k (well pagesize I think but normally 8k).  Currently no translatable strings hit this new limit.

Hash indexes are the only issue with Odoo for streaming replication and failover and are currently not recommended for use.  I don't know exactly what you might like to do, my personal favorite would be to create a partial index on length(src) < whatever 8k of text is, I assume 4096 for unicode and let the rest suffer (of which there are none currently and would be limited to either long email templates or module descriptions).

But you might want to try/except and log I suppose and create hash index on failure.

Or alternately have a stored functional field which is the hash, and use that for search.

But no matter what I hope you think that streaming rep working properly is more desirable than a hash index on translations.  Anyway thought I'd let you know.

```python
def _auto_init(self, cr, context=None):
        super(ir_translation, self)._auto_init(cr, context)

        # FIXME: there is a size limit on btree indexed values so we can't index src column with normal btree.
        cr.execute('SELECT indexname FROM pg_indexes WHERE indexname = %s', ('ir_translation_ltns',))
        if cr.fetchone():
            #temporarily removed: cr.execute('CREATE INDEX ir_translation_ltns ON ir_translation (name, lang, type, src)')
            cr.execute('DROP INDEX ir_translation_ltns')
            cr.commit()
        cr.execute('SELECT indexname FROM pg_indexes WHERE indexname = %s', ('ir_translation_lts',))
        if cr.fetchone():
            #temporarily removed: cr.execute('CREATE INDEX ir_translation_lts ON ir_translation (lang, type, src)')
            cr.execute('DROP INDEX ir_translation_lts')
            cr.commit()

        # add separate hash index on src (no size limit on values), as postgres 8.1+ is able to combine separate indexes
        cr.execute('SELECT indexname FROM pg_indexes WHERE indexname = %s', ('ir_translation_src_hash_idx',))
        if not cr.fetchone():
            cr.execute('CREATE INDEX ir_translation_src_hash_idx ON ir_translation using hash (src)')

        cr.execute('SELECT indexname FROM pg_indexes WHERE indexname = %s', ('ir_translation_ltn',))
        if not cr.fetchone():
            cr.execute('CREATE INDEX ir_translation_ltn ON ir_translation (name, lang, type)')
            cr.commit()
```

**Comment by odony** [comment]
A fix was committed a few months ago in master at f42c8b1a9dd9631c56fe91fa12680c3699a3516a. The hash index on `src` was replaced with a btree index on `md5(src)`, and all queries adapted accordingly. This keeps the index size low with a minimal cost and supports streaming replication. md5 is fast and only the term being searched needs to be hashed on-the-fly, all the others are in the index.

Note that we had considered using partial indexes too, but that meant rewriting all queries anyway (PG can only use partial indexes for queries that have an exact matching condition).
For the record we routinely have terms longer than 20k in customer databases, typically email templates indeed, but also events descriptions.

Thanks,
