### ISSUE TITLE
issue with --dev parameter

### ISSUE THREAD

**Issue by yelizariev** [odoo/odoo#8193]
I've found a bug with --dev
it doesn't parse action reference.

For example, 
* start odoo with --dev
* open Sales\Products\Products 
* select product and open tab Variants
* click Variant Prices

then nothing happens, because odoo send request with a raw action_id:

    /web/action/load
    {"jsonrpc":"2.0","method":"call","params":{"action_id":"%(variants_template_action)d","context":...

If you try the same without --dev, then everything works.

    /web/action/load
    {"jsonrpc":"2.0","method":"call","params":{"action_id":"123","context":...

I tried this on latest saas-6 revision

related commit https://github.com/odoo/odoo/commit/e6695c72d8c702c1d170ed9eb9b784949a59caa4 by @amigrave

**Comment by JKE-be** [comment]
Thank you for the reporting ! 
It has been fixed in saas-6 ! It should be forward-ported to master during the next week !
