### ISSUE TITLE
[9.0] One2many fields don't accept string domains

### ISSUE THREAD

**Issue by ludwiktrammer** [odoo/odoo#8194]
All relational fields in Odoo accept domains passed as a string. This is useful because the string is then evaluated in an environment where values of other fields are available. This doesn't seem to work on `One2many` fields however. When I pass a string a string to a `domain` attribute on the field I get the following exception:

```
  File "/Users/ludwik/Downloads/odoo/openerp/osv/fields.py", line 778, in get
    domain = domain + [(inverse, 'in', ids)]
TypeError: cannot concatenate 'str' and 'list' objects
```

It seems that `odoo/openerp/osv/fields.py` includes some code that doesn't take into account the fact that the domain may at the point still be a string...

**Comment by Gio666** [comment]
Same to me...

**Comment by ahefni** [comment]
same to me

**Comment by MusstafaA** [comment]
Any solutions?

**Comment by mamcode** [comment]
same to me...

**Comment by vcloud9ray** [comment]
Still happening in v10.

**Comment by gdgellatly** [comment]
Why not just use lambda?

e.g.

transfer_account_id = fields.Many2one('account.account.template',
string='Transfer Account', required=True,
    domain=lambda self: [('reconcile', '=', True), ('user_type_id.id',
'=', self.env.ref('account.data_account_type_current_assets').id)],
    help="Intermediary account used when moving money from a liquidity
account to another")

**Comment by pedrobaeza** [comment]
The workaround solution is the expected one in the framework, so use that one instead of the string. Closing this.

**Comment by arhimas** [comment]
> The workaround solution is the expected one in the framework, so use that one instead of the string. Closing this.

Sorry Pedro, I'm still confused, Which is the expected one in this case?. Thanks in advance.

**Comment by pedrobaeza** [comment]
Lambda one.

**Comment by ludwiktrammer** [comment]
@pedrobaeza I don't think `domain` working differently for a single type of field than all other filed types can be "expected".

**Comment by pedrobaeza** [comment]
It's not working different. Lambda expressions serves for default, domains, compute, inverses...

**Comment by ludwiktrammer** [comment]
@pedrobaeza Yes, but every other relational field besides `One2many` supports domains given as strings.

**Comment by pedrobaeza** [comment]
Well, that's because the domain is traversed with the inverse result, and that one is expressed other way. Probably in latest versions is improved. Any way, you have a way to circumvent this problem.
