### ISSUE TITLE
Install POSBOX Image on Raspberry Pi 2 Model B BCM2836 1GB RAM

### ISSUE THREAD

**Issue by EFFICIENCIE** [odoo/odoo#8196]
Hi I am new in POSBOX I am trying to install POSBOX on Raspberry Pi 2 Model B BCM2836 1GB RAM as getting POSBOX from Odoo itself is a tough task I am trying to contact Odoo for this and shipping in Nigeria they are not responding.
Anyway guys I need a help how to make my Raspberry Pi 2 Model B BCM2836 1GB RAM to work like Odoo POSBOX and connects various hardwares with Odoo Point of Sale Application, as I need to connect Pole display, Printer and Weight Scale. 
Thanks in advance,

**Comment by mart-e** [comment]
Hello,

GitHub issues are for bug reporting.
If you need help on installing or deploying a PosBox, you may check on [community mailinglists](https://www.odoo.com/groups/community-59) or [forum](https://www.odoo.com/forum/help-1) or contact support team by email at online <at> odoo <dot> com (we do reply to emails at this address)
