### ISSUE TITLE
review the category field in ir.module.module

### ISSUE THREAD

**Issue by GoodERPJeff** [odoo/odoo#820]
IMHO, openerp use a strange design on this field, this is a many2one in database, but char in source code (**openerp**.py). this make things un-control. when we list the module group by category , you can easily found there are so many module with wrong category what made the list  hard to understand.

given we have this mass in official package, things got more complex when community modules involved, no clear enough document guide the developer what they should input(should be select ) in **openerp**.py category field. I do like the category list on apps.openerp.com:

Accounting
Human Resources
Localization
Manufacturing
Project
Purchases
Sales
Extra Tools
Warehouse

With clear category, end user and consultant will find the features they need easily. and I guess odoo s.a look modules in same category as a application(used to charge opw users 12 EUR ?) . also, in future version development, odoo s.a and OCA can plan project scope by category first.

But I don't know why modules in openerp repo not follow this category, here I list some module, the category of it,  and my comments, further more than category, I also list some modules I think shouldn't include in official package.    

Category/Name   Technical Name  Comments
Accounting  account_bank_statement_extensions   why this new category name?shouldn't be "Accounting & Finance"
Accounting  account_check_writing   why this new category name?shouldn't be "Accounting & Finance"
Accounting & Finance    account_test    who this module for, when the End user should install this?
Accounting & Finance    l10n_be_coda    this is only for be, why include this in official branch? Also the category should be "Localization",agree?
Accounting & Finance    report_intrastat    this is only for Europ, why include this in official branch? Also the category should be "Localization",agree?
Association membership  we have only 1 module in this category, why not go into "Specific Industry Applications"?
Customer Relationship Management    crm_partner_assign  assign leads to others is a strange logic for me, don't know who use it other then openerp s.a self, is it worth been include in package ?
Dependency  l10n_fr_rib this is for Franch only, why it's included ? Also the category should be "Localization",agree?
Extra Tools lunch   so much joke in community for this, why not move it out?
Hardware Drivers    hw_escpos   this category should be  "Point of Sale",yes ?
Hardware Drivers    hw_posbox_homepage  this category should be  "Point of Sale",yes ?
Hardware Drivers    hw_posbox_upgrade   this category should be  "Point of Sale",yes ?
Hardware Drivers    hw_scale    this category should be  "Point of Sale",yes ?
Hardware Drivers    hw_scanner  this category should be  "Point of Sale",yes ?
Inventory Control   product_extended    why we have a new categoty here, shouldn't be "Warehouse"?
Localization    l10n_be_hr_payroll  what localizations(with py code) should be include in official package, be,EU,and then ?
Localization    l10n_be_hr_payroll_account  what localizations(with py code) should be include in official package, be,EU,and then ?
Localization    l10n_be_invoice_bba what localizations(with py code) should be include in official package, be,EU,and then ?
Localization    l10n_in_hr_payroll  what localizations(with py code) should be include in official package, be,EU,and then ?
Managing vehicles and contracts fleet   this is a new category, why?
Payroll l10n_fr_hr_payroll  again, this is only for fr, Also the category should be "Localization",agree?
Social Network  mail    We have only 1 module in this category, why not go into "Technical Settings"?
Stock Management    stock_picking_wave  new category again, why not go into "Warehouse"
Technical Settings  web_tests   Why include this in production package ?
Technical Settings  web_tests_demo  Why include this in production package ?
Tests   test_converter  Why include this in production package ?
Tests   test_exceptions Why include this in production package ?
Tests   test_impex  Why include this in production package ?
Tests   test_limits Why include this in production package ?
Tests   test_uninstall  Why include this in production package ?
Tests   test_workflow   Why include this in production package ?
Uncategorized   base_import category missing in **openerp**.py ?
Uncategorized   base_import_module  category missing in **openerp**.py ?
Uncategorized   test_convert    Why include this in production package ?

Need the community voice and official responds, review and fix before release.

**Comment by pedrobaeza** [comment]
Categories have changed across versions, so maybe this can be closed. @sle-odoo, when you labeled this as `Wishlist`, what was your intention? Do you consider that this can be closed?

**Comment by sle-odoo** [comment]
@pedrobaeza yes i think we can close this one, i don't have an opinion right now and i don't remember the one i had in 2014 :)

**Comment by pedrobaeza** [comment]
Closing it then :)
