### ISSUE TITLE
No way to set teaser for blog posts manually

### ISSUE THREAD

**Issue by crazybolillo** [odoo/odoo#82010]
Impacted versions:
15.0

Steps to reproduce:
Base install of Odoo 15.0

Current behavior:
The field `teaser_manual` is found inside the source code for `blog.post`, however there is no mention of it in any of the views for said model and there is no way to use it.

Expected behavior:
Field should be shown/hidden based on user settings. This way the user can decide if he wants to use computed teasers or manually
set its own.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

If you guys are interested, I can fix this issue myself and make a pull request.

**Comment by christ-offert-diginav** [comment]
Hi,

I am sorry to find this issue so late, but I think the intended way to use the manual teaser is actually encapsulated by the web editor. If you decided to edit the teaser from the blog post overview page then it will actually save the manually written teaser into the **teaser_manual**

I agree that it would make more sense to also add it to the back end form view to allow this value to be set there. But the assertion that there is no way to use it is therefore not true. It's used via the editor to my knowledge.
