### ISSUE TITLE
odoo14 werkzeug: Error on request : 'Request' object has no attribute 'app'

### ISSUE THREAD

**Issue by saeed-raeisi** [odoo/odoo#82054]
Impacted versions:
14
Steps to reproduce:
Error after selecting database
Current behavior:
Error after selecting database
Expected behavior:

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/38601142/147744933-185d8fc8-fb77-4833-b2a9-0a9fe1b8df9e.png)
![image](https://user-images.githubusercontent.com/38601142/147744976-e0e4d822-d28d-4bf7-8660-02d7dd7cfd95.png)

After installing the required modules, I can no longer be a database item

It is possible to create a new database
But previous databases are inaccessible
I checked the database user.

os : ubuntu 20
odoo 14 
Werkzeug==0.16.1

**Comment by saeed-raeisi** [comment]
Actions taken:
Configure odoo, postgresql

Also change the user database

The problem was solved


`sudo su - postgres -c "createuser -s {user}"`

`nano /var/lib/postgresql/12/main/postgresql.auto.conf `

https://pgtune.leopard.in.ua/

**Comment by saeed-raeisi** [comment]
![image](https://user-images.githubusercontent.com/38601142/147753690-1b930318-1216-40c1-91c7-d99256d78ec7.png)

**Comment by odony** [comment]
Could you double-check that you're using a 100% up-to-date version of our official branches, and that you've restarted your service with the latest code?  (or reinstall a clean version?)

That error looks like an outdated version of `addons/web/controllers/main.py` running with the latest `odoo/http.py` code. Either that, or you're using third-party modules that do low-level stuff and need to be fixed for compatibility with the latest version.

**Comment by saeed-raeisi** [comment]
I am using the latest stable version 
https://nightly.odoo.com/

And the database is accessible when I change the postgersql user

 And he got into trouble again after a while 

I will test again in different situations and I will announce the result here

**Comment by saeed-raeisi** [comment]
odoo/http.py
        try:
            httprequest = werkzeug.wrappers.Request(environ)
            httprequest.app = self

This problem in fact
Use two different versions together and solve

**Comment by sconetto** [comment]
@saeed-raeisi @odony hey there,
I don't if this was included in the latest version but I faced the same issue locally (my code base was up-to-date with the latest commit).

Adding the fix above in the dispatch method solved the issue:
`odoo/http.py` line 1424.

```python
def dispatch(self, environ, start_response):
    """
    Performs the actual WSGI dispatching for the application.
    """
    try:
        httprequest = werkzeug.wrappers.Request(environ)
        httprequest.app = self
        httprequest.parameter_storage_class = werkzeug.datastructures.ImmutableOrderedMultiDict
        
        ...
```
