### ISSUE TITLE
Add a tool that can help users quickly try this app?

### ISSUE THREAD

**Issue by fangdajiang** [odoo/odoo#82122]
Hello, we are TeamCode. We have created a Tin application for this app, which help users to quickly run and try the app without installing and configuring the environment. Users don't need to pay for this service. Hope it can help you better promote the app!

[![TeamCode try-it-now](https://static01.teamcode.com/badge/teamcode-badge-run-in-cloud-en.svg)](https://www.teamcode.com/tin/clone?applicationId=275682948625801216)
Guidance: https://www.teamcode.com/docs/en-US/tin/clone-tin

This is the entire usage process：(use user@example.com/bitnami as username/password to log in)

Users click the badge Run in Cloud.
Sign up first if they have not logged in.
After that, they will be directed to the Clone page and start to build & run this app.

**Comment by odony** [comment]
Thanks for the info[mercial], but we don't promote any specific deployment platforms outside of the official Odoo Cloud :-)
