### ISSUE TITLE
No context given to function 'invoice_line_create' (EDIT : Duplicate https://bugs.launchpad.net/openobject-addons/+bug/1260331)

### ISSUE THREAD

**Issue by droelneo** [odoo/odoo#8213]
**In sale/sale.py around line #537, the invoice_line_create function (in action_invoice_create) is called without context.

That causes wrong values when browse inside that function from another call of action_invoice_create.**

Impacted versions:
- 8.0

Steps to reproduce:
1. In your module, change an order line field
2. Just after, call the action_invoice_create on sale_order
3. The field you have changed is not taken in account

```
 for line in o.order_line:
                if line.invoiced:
                    continue
                elif (line.state in states):
                    lines.append(line.id)
            created_lines = obj_sale_order_line.invoice_line_create(cr, uid, lines)
            if created_lines:
                invoices.setdefault(o.partner_invoice_id.id or o.partner_id.id, []).append((o, created_lines))
```

**Comment by Yenthe666** [comment]
Hi @droelneo,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
