### ISSUE TITLE
XML tags being translated by website language

### ISSUE THREAD

**Issue by vvro** [odoo/odoo#82155]
Impacted versions: 15.0

Steps to reproduce: Use a different default language for website from English

Current behavior:
The sitemap.xml is translated.

Expected behavior:
Don't translate xml tags

Video/Screenshot link (optional):
XML Parsing Error: XML declaration not well-formed
Location: https://.../sitemap.xml
Line Number 1, Column 11:
<?xml versão="1.0" codificação="UTF-8"?>
----------^

**Comment by mart-e** [comment]
Hello,

Could you elaborate on your bug and how to reproduce ? Which language, which modules installed ? What do you mean "is translated" ?

**Comment by vvro** [comment]
Website module, with only the language for Portuguese on the website. Produces a sitemap.xml with a translated header 
`<?xml versão="1.0" codificação="UTF-8"?>` 
Which shouldn't be happening

**Comment by vvro** [comment]
Makes the translation active on xml tags, creating invalid sitemaps for languages other than english
https://github.com/odoo/odoo/blob/97fd5d0229f1eb1af731187f7d5ff7de68720871/addons/website/views/website_templates.xml#L2334

**Comment by mart-e** [comment]
Thanks for the precision and analysis.
You are right, we should avoid this kind of issue because of a bad translation.
I have disabled the translations at #82386

**Comment by vvro** [comment]
Works perfect. Thank you
