### ISSUE TITLE
Accounting Report issue.

### ISSUE THREAD

**Issue by AnilKesariya** [odoo/odoo#8219]
Hello Odoo Team,
Here I suspected one issue on accounting parser the method is _get_account.

Wrong model has been used to browse record to get company name

Origin:   File "addons/account/report/account_general_ledger.py", line 299, in _get_account
    return self.pool.get('account.account').browse(self.cr, self.uid, data['form']['id']).company_id.name

Fixed here.

 return self.pool.get('account.report.general.ledger').browse(self.cr, self.uid, data['form']['id']).company_id.name

Description: In the data['form']['id'] it always passes the wizard ID not account ID, thats why it was giving error.

Here is the Diff:

--- a/addons/account/report/account_general_ledger.py
+++ b/addons/account/report/account_general_ledger.py
@@ -296,7 +296,7 @@ class general_ledger(report_sxw.rml_parse, common_report_header):

```
 def _get_account(self, data):
     if data['model'] == 'account.account':
```
-            return self.pool.get('account.account').browse(self.cr, self.uid, data['form']['id']).company_id.name
-            return self.pool.get('account.report.general.ledger').browse(self.cr, self.uid, data['form']['id']).company_id.name
       return super(general_ledger ,self)._get_account(data)

Will you please check this from your side?

Thanks & Regards,
Anil R. Kesariya

**Comment by gdgellatly** [comment]
This is a duplicate.  It has been reported a few times and fixed.

**Comment by AnilKesariya** [comment]
thanks for response, but when pulled the code that changes doesn't pushed in 8.0.
Is it already pushed?

**Comment by gdgellatly** [comment]
I don't know, try searching the bug reports.  Definitely fixed, but fixes
won't normally go into 8.0 official unless particular criteria apply or you
have an enterprise contract.  Check master.

**Comment by AnilKesariya** [comment]
Thanks Gellatly for sharing knowledge :)

**Comment by Yenthe666** [comment]
This has indeed been fixed ages ago (plus Odoo 8 is no longer an LTS version).
