### ISSUE TITLE
Time issue -  events on website for online registration (SAAS)

### ISSUE THREAD

**Issue by karelvdesch** [odoo/odoo#822]
Use of online Odoo application (Odoo saas)
user setting: Time set for systemuser to correct time zone (deviate from timezone server?)
Event created by user  from 9 - 13 in timezone system user. Training with the possibility for online registration. So event is published for online registration.
When the system user is logged into the system and visit the website the event time is correctly presented  (9-13).
However, when an external  visitor (from the same timezone as the user) visit the website the event time is presented from 7-11 what is not correct. 
Work around user creates event from 11-15. For an external visitor of the website in the timezone of system user the event time is now presented as 9 - 11.

**Comment by lithint** [comment]
Solution:
Go to Settings -> Users -> Advance search -> active = false
open <b>Public user</b> , select the timezone required for public user(in website without login) and save.

**Comment by Yenthe666** [comment]
Dear @karelvdesch,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
