### ISSUE TITLE
[15.0] very slow edit mode switch for Email Templates records.

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#82217]
Impacted versions:
15.0

Steps to reproduce:

Go to `Settings/Technical/Email/Email Templates`

Open any template record and click on `Edit`

Current behavior:

It takes 5+ seconds to go from read to edit mode.

Expected behavior:

Edit mode usually loads in less than a second, so its expected to be the case here too.

Video/Screenshot link (optional):
JS shows that frontend is idle during that time. So I guess its backend issue?
![Selection_242](https://user-images.githubusercontent.com/7812986/148067020-ee982b76-e921-48eb-91c1-34b53238189e.png)

Video demonstrating this issue:

[email-template-edit-time.zip](https://github.com/odoo/odoo/files/7807952/email-template-edit-time.zip)

P.S. Also noticed that users edit mode loads quite slowly too.
P.S.S. Tested with both firefox and chrome. Both load slowly, but Chrome seems to be a bit faster.

**Comment by odony** [comment]
With Chrome 96, it looks like ~2s are spent inside `getCSSRules()`, this is probably something worth looking at. 

@aab-odoo maybe you could dispatch this? 🙏 

<img width="1784" alt="Screenshot 2022-01-17 at 00 02 14" src="https://user-images.githubusercontent.com/2039870/149681838-fb43629a-f256-4db7-b0a3-a00b7af75184.png">

**Comment by aab-odoo** [comment]
Hello @dmo-odoo 

Could one of you take a look at this potential performance issue within the web_editor? It looks like a lot of time is spent inside the `getCSSRules` function in this particular form view. Thanks :-)

**Comment by oerp-odoo** [comment]
@dmo-odoo you mean by `mass_mailing` module? Because slow down happens whether you have that module installed or not. Also res.users EDIT mode is almost as slow too.

**Comment by dmo-odoo** [comment]
I meant the mass_mailing module yes because the issue refers email templates but you are correct that the same code is called outside of mass_mailing for any html field which has inline style option enabled. The function lies in web_editor indeed and not mass_mailing.

**Comment by Zinston** [comment]
Fix here: https://github.com/odoo/odoo/pull/83074

**Comment by Yenthe666** [comment]
Fixed in https://github.com/odoo/odoo/commit/0d4342317d456ed37f0bf24f00538ef54f847e60
