### ISSUE TITLE
How to add many2many field in graph view

### ISSUE THREAD

**Issue by sandeepksrana** [odoo/odoo#8226]
Hi

How to add many2many field in graph view, I am adding but it error displayed, even function field with store working only in float type

can anyone explain me... im using it in reporting with graph view and SQL based query

Thanks
Sandeep

**Comment by Yenthe666** [comment]
Hi @sandeepksrana,

These kind of topics should be posted on the official Odoo help forum (help.odoo.com). There are plenty of people who can help you there!
Since this is no bug I'm closing this.

Regards,
Yenthe
