### ISSUE TITLE
[15.0] Account Followup - PDF displays edit icon 

### ISSUE THREAD

**Issue by netfxtech** [odoo/odoo#82363]
I printed this particular PDF from runbot. I did not test other versions.

Impacted versions: 15.0

Steps to reproduce: Print account followup letter for partner

Current behavior: Pencil/Edit icon is printed on the PDF above "Dear partner"

Expected behavior: No pencil/edit icon

![image](https://user-images.githubusercontent.com/62037189/148468066-73508a99-6d16-4af3-9689-5c5071677143.png)

**Comment by niyasraphy** [comment]
hi @netfxtech ,
this has been fixed by this commit:  https://github.com/odoo/enterprise/commit/104ccb9e41500c523ec574da7ecd733097b6c4ec

feel free to close the ticket,
thanks
