### ISSUE TITLE
XMLRPC - mail.followers unlink() access

### ISSUE THREAD

**Issue by krijn1981** [odoo/odoo#82362]
Impacted versions:
V13 / V14 / V15

Steps to reproduce:
XMLRPC script with the following phrase:
```
[task] = project.task record id
[follower_id] = mail.followers record id

models.execute_kw(db, uid, password, 'project.task', 'write', [[task], {
        'message_follower_ids': (3,[follower_id])
        }])
```
Current behavior:
The XMLRPC connector does not allow (for a standard user) to adjust mail.followers document.
You can call the method unlink(), but it seems to take the default method of Odoo and not overwritten the method by the model.
See https://github.com/odoo/odoo/blob/15.0/addons/mail/models/mail_followers.py#L65

In the frontend, this is not an issue because the Javascript is calling the method for you, instead of you calling it yourself directly.
At this moment all the followings need to be corrected manually. Due to the fact when you an early staged involved in business processes you will be automatically added to almost everything. 
Result:
A) lot's of labor for undoing
B) overkill of email in your mailbox

Problem not everybody in an organization will see this due to the fact they only need to do a small piece (single task).
The overkill of the email box has a consequence that nobody looks anymore to the messages produced by Odoo and therefore the optimization of the process "keep informed of the process" is killed.

Expected behavior:
The frontend and the backend (by XMLRPC) are expected to be the same.
So scripts can be made for updating the system without special coding inside modules.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by mart-e** [comment]
Hello,

Instead of using `unlink`, you can use the `env['mail.thread'].message_unsubscribe(partner_ids)` on the record linked to the followers. This will verify you have the rights to do so and will remove it.

**Comment by odony** [comment]
Seems answered by @mart-e, so closing.
Some models need more advanced semantics than can be accomplished with normal CRUD access, and that's why they have "business APIs" like here. It's not always well documented, but it exists, and if the web UI can call it, you can call it via RPC too.
