### ISSUE TITLE
[15.0] website_event_sale translation

### ISSUE THREAD

**Issue by gregory-moka** [odoo/odoo#82425]
Impacted versions:
15.0

Steps to reproduce:
/

Current behavior:
In french, free tickets are translated with ORIGNIAL

Expected behavior:
Free tickets should be "Gratuit" @mart-e (I can not submit new translation)

Video/Screenshot link (optional):
https://www.transifex.com/odoo/odoo-15/translate/#fr/website_event_sale/333337394

**Comment by mart-e** [comment]
Thanks, fixed !
It will be in the next synchronisation of translation :+1:
