### ISSUE TITLE
[Proposal] SEO Related Improvements

### ISSUE THREAD

**Issue by parthivgls** [odoo/odoo#8246]
SEO Ranking Related
1. More Deeper the page, more efforts to be made for good SEO ranking
   
   Odoo keep on adding unecessary slugs to pages "page" with any page that you wish to create which adds an additional level to the page where with Wordpress things are much simple, clean and neat. <site-name>/<page-url>
2. Still not 100% clean URL
   
   I know keeping a number in URL doesn't make much difference but still there are some cases where this number system causes pain.
   
   at current Odoo URL is being hadled by the "page-id" at the last level, making a replacement or duplicate page is impossible. 
   
   In a case where some one deleted the page or post by mistake and then wants to create a new page, sorry but you made a greatest mistake of your life, not possible to go back as there will be a new <page-id> at the end even if you keep the same title/ slug, you are at the dead end.
   
   you can't even retrieve it from trash. :(
3. No manual URL
   
   As URL slugs are generated based on the "title" of the page, there is no way you can have a different URL then the page title it self. Though it's not considered as right practice, but in many cases you need to have both in a different way. 
4. LOTS of DUPLICATE TITLES,LOTS of DUPLICATE TITLES,LOTS of DUPLICATE TITLES,LOTS of DUPLICATE TITLES,LOTS of DUPLICATE TITLES,LOTS of DUPLICATE TITLES,LOTS of DUPLICATE TITLES,LOTS of DUPLICATE TITLES
   
   Yes, all those dynamic pages that Odoo generates, like Blog Pages, Partner Pages and Jobs Pages Generate same duplicate titles. Even the Monthly Blog Pager generates duplicate Titles. And There you have a BIG Google SEO panelty. 
5. No Manual 301 configuration
   
   Mistakes do happen, specially when you talk about WWW, as it's more vivid than typical ERP world. First you think some URL is good but then after few days you want to change it to something which might be more fancy. But till that time google has crawled your page and that's it. 
   
   You don't have place where you can configure this kind of redirection unless you know nginx and know how to put 301 directive in nginx conf file. (sorry apache guys .. same goes for you as well )
6. No Canonical URL
   
   There is no way or no place where one can put canonical URL
7. ALT and Title for Images
   
   Still some of the search engines does depend on this, currenlty while adding an image there is no "simple" way to do it. SEO people bleeds to death after seeing this.
8. Images not cacheble if stored as attachment
   
   As images are stored and retrived as direct binary data, it's not possible to cache it using Nginx Caching as it is missing the file type.
9. No Way to Stop ROBOTS
   
   There is no way one can put a directives on the pages for noindex, nofollow.
10. Modifiable Sitemaps
    
    SEO people love to do this kind of things, where you can modify site-map. Exclude set of URL from site map, you don't need your "website/login" URL to be indexed. Even separating site maps based on category or blog makes more sense for them. 
    
    Currently site-map is generated as stored as attachment, possible to modify by copy / paste but again everytime a page is added manual work.
    
    This were top 10 things that we found while we implemented Odoo CMS for two of our own websites, [techreceptives.com](techreceptives.com) and [openeducat.org](openeducat.org)

Yes, we ate our own dog food before we do it for any-other customers. I propose that Odoo should at-least bother about some of them if not about all.

**Comment by rruebner** [comment]
@parthivgls Hi,
please have a look at my work in progress pull request https://github.com/OCA/website/pull/74 in OCA. I started to implement a better url handling. Maybe we can use it as an opening because my pull request doesn't address all of your points.

Regards Robert

**Comment by ddfs** [comment]
@parthivgls here are some stuff i have tried to fix issues are there too.

having exactly the same problems you have mentioned above. especially multilingual part is total pain. 

here 
https://github.com/ddfs/odoo/tree/master/addons

and here 
https://github.com/odoo/odoo/issues/7518

have fun.

**Comment by jholze** [comment]
@parthivgls We are working hard ;) https://github.com/blooparksystems/website/pulls - we also have our own runbot running unter runbot.bloopark.de - just some fixes that the test are running well. Maybe you can join and support us with you knowledge

**Comment by parthivgls** [comment]
sure, I'll review it and give the feedback.

**Comment by rafaelbn** [comment]
:+1:

**Comment by fczaja** [comment]
Hi @parthivgls, i am Freddy and i am working for bloopark. As you know we're working on some SEO improvements to make Odoo more SEO conform. I created a Ticket #12128 to update the tag url handling for website_blog addon. Would be cool if you could have a look on it and give some feedback.

THX Freddy

**Comment by pedrobaeza** [comment]
@JKE-be do you consider this can be closed? I think some of these things are already handled in latest versions. Others are not, but I don't see easy to get them or even if they are really needed for a good SEO.
