### ISSUE TITLE
ajax.js in Odoo 9.0 line 202 referencing this.url() whose code is now in session.js

### ISSUE THREAD

**Issue by royaladmin** [odoo/odoo#8249]
I noticed this by eye.  Changed one line of code in my copy.  Have not tested on an iOS device.

ajax.js line 202, from

  var url = this.url(options.url, params);

to

  var url = (options.url || '/') + '?' + $.param(params);

I took my first look at Odoo 9.0 this past week, been reading through the code.
You should be commended and congratulated once again.  My appreciation.

Jim

**Comment by aab-odoo** [comment]
Hello,
This has been fixed by e18660c3308e7fb17590e72e6b5e9aadc8ca0517
Regards
