### ISSUE TITLE
[8.0] Product variant menu under 'Warehouse' is lacking

### ISSUE THREAD

**Issue by fclementic2c** [odoo/odoo#8254]
I think Storemen using Odoo Warehouse acces rights deserve to have a extra menu Product variants for their day-to day buisiness. 
Today (unless if I missed settings/options) it is not possible to see a list (tree view) of all variants with quantity under this menu. 

What do you think ?

Thanks

**Comment by fclementic2c** [comment]
Ok just noticed that it is under Warehouse configuration. Not ideal in my view.
It should be under Products.

**Comment by Yenthe666** [comment]
Hi @fclementic2c,

Thank you for the report and for answering yourself. I guess we can't really consider this a bug plus Odoo 8 is no longer an LTS version.
I'm closing it for these two reasons.

Regards,
Yenthe
