### ISSUE TITLE
Specifies a timeout for SMTP connection

### ISSUE THREAD

**Issue by phuihock** [odoo/odoo#8261]
For every mail job, SMTP connection is made without a timeout. Should the connection fails and do not return, the row level lock will be held indefinitely, preventing subsequent mail job to skip and new mails will not be processed.

Relevant discussion on community mailing list:
https://www.odoo.com/groups/community-59/community-13672869

Lines in question:
https://github.com/odoo/odoo/blob/8.0/openerp/addons/base/ir/ir_mail_server.py#L236
https://github.com/odoo/odoo/blob/8.0/openerp/addons/base/ir/ir_mail_server.py#L238

I suggest that the timeout to be made as a new column to `ir.mail_server` model with a sensible default, such as 300.

**Comment by gurneyalex** [comment]
is there not a TCP level timeout, which will cause an exception and a rollback?

**Comment by phuihock** [comment]
If no timeout is set, it defaults to global default timeout, which is None, meaning no timeout.
See https://docs.python.org/2/library/smtplib.html#module-smtplib and https://docs.python.org/2/library/socket.html#socket.getdefaulttimeout)

**Comment by Yenthe666** [comment]
Hi @phuihock ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by amh-mw** [comment]
Fixed in 9.0 by #25064.
