### ISSUE TITLE
 NEW API - fields related not translated

### ISSUE THREAD

**Issue by Martronic-SA** [odoo/odoo#8264]
Probably related to #3745 which should have been fixed, but it's not working for fields Many2one related.

A sample:
class A():
    _name = 'a'
    number = fields.Char('Number')

class B():
    _name = 'b'
    reltoa = fields.Many2one('mymodule.a', 'A')
    number = fields.Char(related='reltoa.number', string='Number')

The field number label is not translated in the forms related to class B.

When exporting translations (fr):
# : field:mymodule.models.a,number:0

msgid "Number"
msgstr "Numéro"
- There's missing the field related to class b:
  export should be:
# : field:mymodule.models.a,number:0
# : field:mymodule.models.b,number:0

msgid "Number"
msgstr "Numéro"

**Comment by mart-e** [comment]
A bit old, but I just tried and it seems fixed, probably by this line
https://github.com/odoo/odoo/blob/2c5fe07fc760396af7d671131da1a5f8ee4d7b50/openerp/fields.py#L1188
