### ISSUE TITLE
Problem with All Day Event`s Sync with Google Calendar

### ISSUE THREAD

**Issue by DiegoLelis** [odoo/odoo#8267]
Add a new meeting, with time to begin and start, Sync with google Calendar, the date and time came right.
Add a new meeting, with All Day option checked, the meeting in Google Calendar, came with -1 day.
At the images, you can see the meetings created and Sync

![tests-odoo](https://cloud.githubusercontent.com/assets/8404455/9537559/35ef6680-4d10-11e5-9c60-3a86de79eeed.png)
![test2-odoo](https://cloud.githubusercontent.com/assets/8404455/9537560/35f0efbe-4d10-11e5-930c-ea3a70ae1e45.png)
![test-odoo](https://cloud.githubusercontent.com/assets/8404455/9537561/35f394f8-4d10-11e5-8e12-467e3eba738a.png)
![tests-google](https://cloud.githubusercontent.com/assets/8404455/9537564/39746e0e-4d10-11e5-8073-f3074080bc09.png)
![test2-google](https://cloud.githubusercontent.com/assets/8404455/9537563/3973ae24-4d10-11e5-8356-fc412cab1a4b.png)
![test-google](https://cloud.githubusercontent.com/assets/8404455/9537565/39750b20-4d10-11e5-9843-2cf2ea12c488.png)

**Comment by DiegoLelis** [comment]
I`m using UTC -3, on the user, and on the google Calendar

**Comment by MatiasJAco** [comment]
Any news on this issue?

**Comment by pedrobaeza** [comment]
Is this still happening in latest versions, @DiegoLelis ?

**Comment by Yenthe666** [comment]
Hi there,

The official support for Odoo 9 has now ended as V12 is released.
As there has been no feedback either I'm closing this ticket. Don't hesitate to comment back or create a new ticket if you can reproduce it on V10 or up!

Regards,
Yenthe
