### ISSUE TITLE
Odoo Modify for KSA Market

### ISSUE THREAD

**Issue by fdmonir88** [odoo/odoo#82677]
Impacted versions: 14 latest

Steps to reproduce:

Current behavior:

Expected behavior:

Thanks for nice innovation. I am using this software and suggested to all of my known persons to use it. 
1) I want to know , How to add Company details English and Arabic both font. I saw some one develop this function. Left side English and Right side showing in Arabic Language. 
2) Invoice are saving automatically as a pdf file. that’s very helpful. Why not saving Simplified Tax Invoice are not saving automatically as a pdf? 

3) In Simplified Invoice Company name showing very small size . How to make this Name bigger from other line? QR code are showing upper side. I want to showing this WR code footer side. 
And how to change Receipt format ? 

4) I saw other point of sale software have option to generate total sale, buy and vat report . Also have option to make Vat return submit report. But i can’t find this function in Odoo. 

5) In Odoo How I will generate barcode? If any products not available bar code. I have to generate a barcode. i can’t found this option. 
Another important thing When i go for print bar code . I can’t find barcode print in thermal printer option. All the barcode are showing other paper size. 

I think odoo developers will think above all this issue. And as soon as possible they ill fixed and will give solution this. 

Thanks odoo teem.

**Comment by odony** [comment]
Hi @fdmonir88 and welcome to the Odoo community!

Github issues are really meant for bug reports, could you please use the Odoo Help forum to receive guidance on these topics? https://www.odoo.com/forum/1

Thanks!
