### ISSUE TITLE
[15.0] debian packages not updated from 2021 12 15. All new packages are from same day!

### ISSUE THREAD

**Issue by leimantas** [odoo/odoo#82745]
Impacted versions: 
V15

Steps to reproduce: 
check all debian packages from nightly. from 2021 12 15 - today
like: [http://nightly.odoo.com/15.0/nightly/deb/odoo_15.0.20220111_all.deb](http://nightly.odoo.com/15.0/nightly/deb/odoo_15.0.20220111_all.deb)

Current behavior:
all builds from 2021 12 15. Missing files. Can`t work with latest enterprise modules.

Expected behavior:
All builds must be same as build date. Not 2021 12 15!

Video/Screenshot link (optional):
<img width="728" alt="image" src="https://user-images.githubusercontent.com/46538777/149402638-7960234b-0643-4290-bb88-d04f123c1547.png">
<img width="792" alt="image" src="https://user-images.githubusercontent.com/46538777/149402790-ac4c3c08-c730-41df-92a5-9b577d4b9536.png">
<img width="949" alt="image" src="https://user-images.githubusercontent.com/46538777/149402991-4f08b9da-7a16-4e37-86ea-016bac833843.png">

Support ticket number submitted via odoo.com/help (optional):

**Comment by d-fence** [comment]
This is not an issue, the package is made with the updates from the branch in the repository at the moment of the build. You can easily check the the package contains the latest changes.

The date that you see in the package is a feature to make the [builds reproducible](https://wiki.debian.org/ReproducibleBuilds/Howto#Members_of_control.tar_and_data.tar_have_varying_mtimes)

The packaging system takes the date of the latest debian/changelog entry and use this timestamp to create the tar file with an argument like this:
`--mtime @1608024529`

You can see that it correspond to the latest changelog entry timestamp.
https://github.com/odoo/odoo/blob/6ece16fbb0ceaced022a2d1b3f0c5769ba827125/debian/changelog#L6

**Comment by leimantas** [comment]
this is an issue! becouse in the debian package there is no new files. and if you install latest debian file - and add enterprise modulese - the cant find latest scss functions.

**Comment by leimantas** [comment]
Look!
[https://github.com/odoo/odoo/blob/6ece16fbb0ceaced022a2d1b3f0c5769ba827125/addons/web/static/src/legacy/scss/utils.scss#L173](https://github.com/odoo/odoo/blob/6ece16fbb0ceaced022a2d1b3f0c5769ba827125/addons/web/static/src/legacy/scss/utils.scss#L173)

Take latest docker image. and go to this file.
<img width="977" alt="image" src="https://user-images.githubusercontent.com/46538777/149782779-8d48a003-a1cd-4c0c-9416-e217890afdbe.png">

**Comment by d-fence** [comment]
> Look!
> 
> https://github.com/odoo/odoo/blob/6ece16fbb0ceaced022a2d1b3f0c5769ba827125/addons/web/static/src/legacy/scss/utils.scss#L173
> 
> Take latest docker image. and go to this file. <img alt="image" width="977" src="https://user-images.githubusercontent.com/46538777/149782779-8d48a003-a1cd-4c0c-9416-e217890afdbe.png">

Anyway, this is more of a docker repository issue. Did you pull the latest images. I just verified and this small piece of code is included in the latest Odoo 15.0 docker image.
