### ISSUE TITLE
add image between a text in rml report

### ISSUE THREAD

**Issue by Anhlq87** [odoo/odoo#8276]
Hi everybody!

I have a problem in rml report. I want to print a image between a text.
ex: Print text [image] have image
or
ex: Print [image] text have image
I want when I find [image] I will add image into that place.

Please help me to solve it. Thanks a lot :)

**Comment by Anhlq87** [comment]
Please help me !!!!!

**Comment by lukebranch** [comment]
@Anhlq87 ,

Github is for reporting issues and bugs with Odoo, not for asking for help with using it.

I suggest you ask this question in the forum:

http://help.odoo.com

or search for an answer in the forum.

**Comment by Anhlq87** [comment]
Ok thanks
