### ISSUE TITLE
Unlink in server action incorrectly passed wrong ID

### ISSUE THREAD

**Issue by maramizo** [odoo/odoo#82825]
Impacted versions:
Odoo 14

Steps to reproduce:
Create the following server action on sale.order model.
```py
for rec in records:
  a = rec.action_cancel()
  if isinstance(a, dict) and 'name' in a and a['name'] == 'Cancel Sales Order':
    sc = env['sale.order.cancel'].create({'order_id': rec.id})
    sc.action_cancel()
    rec.unlink()
```

Current behavior:
rec.action_cancel() always attempts to cancel the already unlinked order.

Expected behavior:
rec.action_cancel() should be passed different values on each loop.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by gdgellatly** [comment]
Hi,

That is not really to do with odoo. You are changing the members of an iterable while iterating. Nothing good ever happens. Just accrue them and unlink after loop. But really that is a hugely inefficient code anyway and it is wrong as it would try to only delete SO's with approved or draft invoices while not managing those invoices. It could be written as

```
records.with_context(disable_cancel_warning=True).action_cancel()
records.unlink()
```

It's still wrong, it is missing many important safeguards, but does mostly what was intended above. If you really only intended deleting orders with invoices then you will need a filtered.

I'll assume you are new at this, use the forums for help questions and spend a lot more time reading the docs and the code.

**Comment by maramizo** [comment]
I presumed records was a list and that unlink did not remove values from the recordset, that explains why the iterator's ordering messed up. Also this code is not production level code and is just for ease of mind to speed up deletion of automatically generated sales.

The test sales in the environment have no generated invoices so I'm not worrying about that at all, but they do have stock moves and that's why I'm creating a sale.order.cancel and cancelling that to return the moves.

I'm not sure why accruing the records and cancelling them in turn afterwards would be inefficient though, something like:

```py
for rec in records:
  if rec.state != "draft":
    sc = env['sale.order.cancel'].create({'order_id': rec.id})
    sc.action_cancel()
records.unlink()
```

looks fine. If you have any resources specifically on optimizing Odoo code in general that'd be pretty helpful. 
Thanks.

**Comment by odony** [comment]
@maramizo Do not hesitate to use the Odoo Help forum for questions related to your code :-) https://www.odoo.com/forum/1

Thanks @gdgellatly !
