### ISSUE TITLE
[BUG] database manager is not accessible - 500 Internal Server Error

### ISSUE THREAD

**Issue by MihranThalhath** [odoo/odoo#82835]
Impacted versions: Odoo 15.

Steps to reproduce: With the latest changes database manager should be accessible.

Current behavior: Shows 500 Internal server error and in logs it throws the following exception

`NotImplementedError: Templates should use the ir.qweb compile method
`
Expected behavior:

Database manager should load

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

This issue started occuring after bfccab6fa125009ada701326501974227eff68ef i guess.
The database manager is still trying to use QWeb rendering and not IrQWeb rendering.

**Comment by MihranThalhath** [comment]
ping @std-odoo @mart-e

**Comment by MihranThalhath** [comment]
[https://github.com/odoo/odoo/blob/3c8409d946e549a3d3f104b9417257b5dc7cf0c8/addons/web/controllers/main.py#L1074](url)

**Comment by MihranThalhath** [comment]
[Probably this might be the issue](https://github.com/odoo/odoo/blob/3c8409d946e549a3d3f104b9417257b5dc7cf0c8/addons/web/controllers/main.py#L1074)

**Comment by JonatanGk** [comment]
Have the same issue when i pulled latest commits

**Comment by odony** [comment]
@MihranThalhath @JonatanGk Thanks for reporting! We'll try to merge the fix asap, we have 2 alternative patches in review already.

@Xavier-Do we really need to introduce coverage for the db manager routes in runbot :pray:, it's the second time we break it in v15. In both cases as a consequence of dropping jinja for the rendering, btw, but that's another story ^^
