### ISSUE TITLE
[PosBox] Printing wrong dollar symbol encode

### ISSUE THREAD

**Issue by phamhieu** [odoo/odoo#8285]
I'm using PosBox with Epson TM-88III printer. I try to update the XMLReceipt to print out currency value with dollar symbol.

I updated /addons/point_of_sale/static/src/xml/pos.xml to include <t t-esc='receipt.currency.symbol'/> in front of all price values.
I tried to hard code the symbol "$" also.
However, the printer always prints out "¥" instead of the "$" as screenshot.

Anyone can help me with this problem please. Thank you a lot.

![img_0374](https://cloud.githubusercontent.com/assets/689843/9560719/d60ad8dc-4e57-11e5-9d08-778ad8292ae0.JPG)

**Comment by pedrobaeza** [comment]
This is because that symbol is not part of the charset of the printer. I close, as this is not a POS issue itself.
