### ISSUE TITLE
hello dear all. I am newly using Odoo I need your help and suggestions with this error "Could not get content for /account_parent/static/src/scss/coa_hierarchy.scss defined in bundle 'web.assets_common'.

### ISSUE THREAD

**Issue by canst** [odoo/odoo#82862]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by hameedullah** [comment]
Duplicate issue of #82861 . Please use Odoo forum (https://www.odoo.com/forum/help-1) for help related queries. github issues should be used to report the issues with odoo.
