### ISSUE TITLE
[8.0] Can`t change web.base.url 

### ISSUE THREAD

**Issue by noamix** [odoo/odoo#8293]
I have a web site (https) by default web.base.url use (http) when you change http to https, everything works fine until you restart the session. Then Odoo always rewrites the URL to "http://" instead of "https://"

This behavior does not let you use online chat

ref: https://www.odoo.com/es_ES/forum/help-1/question/browse-always-block-live-chat-because-it-had-mixed-and-insecure-content-65894

**Comment by Yenthe666** [comment]
@noamix there is a very easy fix for this.
Add a new parameter 'web.base.url.freeze' and set the value to 'True'. This will prevent Odoo from updating your web.base.url.

**Comment by noamix** [comment]
thanks a lot Yenthe666 fix works perfect.

**Comment by Yenthe666** [comment]
No problem @noamix!
I've also posted this answer on the forums for others to find it. An upvote or accept is always welcome :smile: 
Perhaps you could also close this issue since its resolved?
