### ISSUE TITLE
Website Theme Live Preview are not working

### ISSUE THREAD

**Issue by ikus060** [odoo/odoo#82941]
Impacted versions: 15.0

Steps to reproduce:

1. Install Website Apps
2. Create a new Website
3. Then Select a theme for this website
4. Click "Live Preview"
5. You get redirect to http://theme-graphene.odoo.com

Current behavior:

*  A 404 error page is shown

Expected behavior:

* A live preview is displayed

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/921251/149846882-7e6b677d-b2ab-4176-823b-a82af2f0cfa5.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by MihranThalhath** [comment]
ping @JKE-be

**Comment by JKE-be** [comment]
Thanks for feedback.
It has been restored.
