### ISSUE TITLE
[15.0]Why [sign.template] is not opend by odoo ?

### ISSUE THREAD

**Issue by realtanwei** [odoo/odoo#82943]
i want to see _sign_ part. 

but it's not open. or this is not **free** ..... ?

**Comment by MihranThalhath** [comment]
Hi @realtanwei,

Documents - Signature module is an Odoo Enterprise module and is available only with OEEL-1 license. If you have any further doubts kindly use [Odoo Forum](https://www.odoo.com/forum/help-1) to clear your doubts.
