### ISSUE TITLE
[8.0] print_report() of class pos.make.payment never got called

### ISSUE THREAD

**Issue by odoo-mohsin** [odoo/odoo#8295]
Module : point_of_sale
Class : pos_make_payment
Function: 
def print_report(self, cr, uid, ids, context=None):
        active_id = context.get('active_id', [])
        datas = {'ids' : [active_id]}
        return {
            'type': 'ir.actions.report.xml',
            'report_name': 'pos.receipt',
            'datas': datas,
        }

Issue : KeyError: 'pos.receipt'

Function print_report is never used for class pos_make_payment. Please remove this function if it's not called from anywhere.

**Comment by Yenthe666** [comment]
Hi @odoo-mohsin,

Thank you for your bug report. This shouldn't be a bug anymore.

Regards,
Yenthe
