### ISSUE TITLE
Dashboard screen not loading 

### ISSUE THREAD

**Issue by kartikdanidhariya** [odoo/odoo#8299]
Recently I have installed odoo on my droplet (Digital Ocean).
It was working fine, since last few days Odoo is not loading dashboard screen. I have checked all log and debug information and found that
there is 1.js file missing.
It return 404 for 1.js
 Can you please guide me on this. How to resolve this issue.

**Comment by Yenthe666** [comment]
Hi @kartikdanidhariya,

Thanks for the bug report.
Please update your whole Odoo, do a `-u all` and recompile all assets. A lot has been improved since this bug report to prevent these kind of issues.

Regards,
Yenthe
