### ISSUE TITLE
[8.0][Website] Sitemap generated are always http

### ISSUE THREAD

**Issue by auyeung112002** [odoo/odoo#8301]
The links in the sitemap.xml generated by the system are always using http protocol.

It would be better if user can choose to sitemap.xml where the links are in https.

**Comment by ddfs** [comment]
check parameters -> system parameters enter your default url there

and always use that one. not other way around. it is not a bug.

**Comment by Yenthe666** [comment]
Hi @auyeung112002,

@ddfs is correct. You should configure your `system.url` parameter in HTTPS in order to have this in HTTPS.

Regards,
Yenthe
