### ISSUE TITLE
[13.0+] Crontask execute but missing some interval time

### ISSUE THREAD

**Issue by NothingCtrl** [odoo/odoo#83016]
Impacted versions: 13.0 (+?!)

Steps to reproduce:

* Server time zone: `UTC`
* Kubernetes environment with 2 instance share same database, config (with `workers = 3`) and file store.
* Create `ir.cron` repeat every `180 mins` everyday from `00:00:00` (UTC), un-check *Repeat Missed*

Current behavior:

Task execute but missing some interval time as image below:

* (1): Should have an execute at `07:00 ICT (00:00 UTC)`
* (2): Should have an execute at `16:00 ICT (09:00 UTC)`
* (3): Should have an execute at `07:00 ICT (00:00 UTC)`
* (4): Interesting behavior, job should **not** run at `02:00 ICT (19:00 UTC)`

No error or other ralated logs was found.

![image](https://user-images.githubusercontent.com/5380820/150071648-0591c090-229b-4969-bbc0-df772153a8c8.png)

Expected behavior:

Job should run at `0 3 6 9 12 15 18 21` hour / UTC

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by MihranThalhath** [comment]
@odony

**Comment by NothingCtrl** [comment]
Sorry, this issue may cause by missing `db_name` in config when using workers (we are using multi-instance, multi database). I will re-open if the issue still exists.
