### ISSUE TITLE
[8.0] "Odoo Server Error. Traceback not available" when loading POS

### ISSUE THREAD

**Issue by MGinshe** [odoo/odoo#8304]
As the title says, I'm getting a "Traceback not available" error when loading the POS. The error occurs on package account.fiscal.position.tax

I can't find any additional information, and I don't know how to begin debugging such a generic error. Also, googling 'Odoo "Traceback not available"' shows exactly 1 result, which is an unanswered question on SO. Here's a screenshot of the error:

Is there any info on this kind of error?

**Comment by ujaco** [comment]
Hi Mginshe. Im not able to view the image uploaded. Could you please attach it again?

**Comment by MGinshe** [comment]
[Here's the error](http://i.imgur.com/UES3qET.jpg)

I've been uninstalling & reinstall modules all day and it seems to be coming from [pos_pricelist](https://github.com/OCA/pos/tree/8.0/pos_pricelist)

**Comment by fdedraco** [comment]
it's related with no pricelist being not "active" check your periods for rapid fix

**Comment by ujaco** [comment]
@MGinshe  Can you restart the pos in debug mode? The URL would look like www.yourwebsite.com:8069/web/?debug=#action=pos.ui. Try this out and post a screenshot so that it can be diagnosed further.

**Comment by mart-e** [comment]
Hello,

Closing as it seems to be linked to a community module. Let us know (with more debug info) if you can reproduce the error as well in standard code.

**Comment by imbacknow** [comment]
HI all

Just setup right access for your staff, your account is admin (with full access)
For other users ( POS staff ) verify that accounting and finance access on the configuration board is set to accountant.

**Comment by lamusoul** [comment]
Wow, great, thanks for your info bro imbacknow, it works now for my cashier user odoo 10
