### ISSUE TITLE
readonly='True' is wrong: readonly=True

### ISSUE THREAD

**Issue by BT-aestebanez** [odoo/odoo#83102]
https://github.com/odoo/odoo/blob/d132c8d4f319af8fe9882d90f3af0d7b4e145b67/addons/mrp/models/mrp_workcenter.py#L332

**Comment by Yenthe666** [comment]
Not an issue. See the field on a V13:
![image](https://user-images.githubusercontent.com/6352350/150529626-1431b4f1-9fa1-41d8-8557-d8531f0cd57f.png)

and in V15 it is already resolved:
https://github.com/odoo/odoo/blob/dd478fcc7f5dfa3f15f76d10340bfef4cf2fbf97/addons/mrp/models/mrp_workcenter.py#L364

**Comment by BT-aestebanez** [comment]
ok, then let's close it. Thanks for the answer
