### ISSUE TITLE
Bug ERP [Odoo slow] maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#8313]
On server log, getting below message, odoo slow running...

 <string>:2: (WARNING/2) Block quote ends without a blank line; unexpected unindent.
<string>:2: (WARNING/2) Block quote ends without a blank line; unexpected unindent.
<string>:2: (WARNING/2) Block quote ends without a blank line; unexpected unindent.
<string>:2: (WARNING/2) Block quote ends without a blank line; unexpected unindent.
<string>:2: (WARNING/2) Block quote ends without a blank line; unexpected unindent.

tejastank@usa-vps:~$ <string>:2: (WARNING/2) Block quote ends without a blank line; unexpected unindent.
<string>:2: (WARNING/2) Block quote ends without a blank line; unexpected unindent.
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f6904ee49b0> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f690522c938> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f690522ade8> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f69051c2668> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f6905258230> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f69074bff50> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f69079555f0> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f690e500578> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f690e886050> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f690980ff50> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f69110f8578> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f6911196140> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f68d9b25758> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f68d9b25758> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f68d9b25758> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <function _remove at 0x7f68d9b25758> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68da178a50>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68da178b50>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68da23e350>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68d9ab08d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68e91bd150>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68da23e8d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68e91bdb50>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68e91bd250>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68e91bdc50>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68e91bd1d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68e91bdad0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68e91bdbd0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68da48d6d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68da48d3d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68da1783d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68da178cd0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method Cursor.__del__ of <openerp.sql_db.Cursor object at 0x7f68d9d2ebd0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68bfcf6c50>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68e9376950>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method Cursor.__del__ of <openerp.sql_db.Cursor object at 0x7f68ebd26c10>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method Cursor.__del__ of <openerp.sql_db.Cursor object at 0x7f68ebd26590>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68eb5177d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68eb517450>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68ea19b1d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68ea19b450>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68ea19b0d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68ea19b350>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method Cursor.__del__ of <openerp.sql_db.Cursor object at 0x7f68d9d244d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method Cursor.__del__ of <openerp.sql_db.Cursor object at 0x7f68d9d24f10>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68eb517850>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68eb517a50>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68da15f8d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68da15f7d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method Cursor.__del__ of <openerp.sql_db.Cursor object at 0x7f68db9a9690>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68d9af4050>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68eb5179d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68eb564250>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68d9af4450>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68da15fcd0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68da15f650>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68da15fb50>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68da15f6d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method Cursor.__del__ of <openerp.sql_db.Cursor object at 0x7f68d9554290>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method Cursor.__del__ of <openerp.sql_db.Cursor object at 0x7f68dbc33150>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68ea193350>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68ea193650>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method Cursor.__del__ of <openerp.sql_db.Cursor object at 0x7f68db9c5690>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68eb749c50>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68eb749d50>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68e9b0a2d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68eb7496d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68d9c4ac50>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68d9c4a2d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68d9c4a6d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68d9c4a0d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68d9c4a450>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68d9c4abd0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method Cursor.__del__ of <openerp.sql_db.Cursor object at 0x7f68dbbae110>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method Cursor.__del__ of <openerp.sql_db.Cursor object at 0x7f68db9fab10>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68da23e2d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68da23e5d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method Cursor.__del__ of <openerp.sql_db.Cursor object at 0x7f68dbdb8290>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68d94e7750>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68d94e76d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68d94e7850>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68d94e77d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68d94e7950>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68d94e78d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68d94e7b50>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68d94e7ad0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68d94e7a50>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68d94e79d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68d94e7c50>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68d94e7bd0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68d94e7e50>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68d94e7dd0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68d94e7f50>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68d94e7ed0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68da23ed50>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68da23e550>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68da23e4d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68da23ec50>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68da23e750>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68da23e450>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68da23e150>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68da23e6d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68dbd440d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68dbd44050>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68dbd441d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68dbd44150>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68dbd442d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68dbd44250>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68dbd443d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68dbd44350>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68dbd446d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68dbd44650>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68dbd447d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68dbd44750>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68dbd448d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68dbd44850>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68dbd449d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68dbd44950>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68dbd44ad0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68dbd44a50>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68dbd44bd0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68dbd44b50>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68dbd44cd0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68dbd44c50>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68dbd44ed0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68dbd44e50>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method Cursor.__del__ of <openerp.sql_db.Cursor object at 0x7f68dbd622d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68d94e7d50>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68d94e7cd0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68d94e7550>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68d94e74d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68e98a83d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68e98a8250>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68e98a8e50>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68e98a8350>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68e98a8850>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68e98a8450>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68eb749cd0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68e98a8ad0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68d9c4a5d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68d9c4add0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68dbb62050>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68dbb57f50>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68dbb62150>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68dbb620d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68dbb62250>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68dbb621d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68dbb62550>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68dbb624d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68dbb62650>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68dbb625d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68dbb62750>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68dbb626d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68dbb62450>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68dbb623d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method Cursor.__del__ of <openerp.sql_db.Cursor object at 0x7f68dbb737d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68dbb62f50>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68dbb62ed0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68e898c0d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68e898c050>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68e898c1d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68e898c150>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68dbb62e50>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68dbb62dd0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68e898c3d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68e898c350>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68e898c4d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68e898c450>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68e898c5d0>> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a Python object' in <bound method _fileobject.__del__ of <socket._fileobject object at 0x7f68e898c550>> ignored

**Comment by tejastank** [comment]
<string>:2: (WARNING/2) Block quote ends without a blank line; unexpected unindent.
<string>:2: (WARNING/2) Block quote ends without a blank line; unexpected unindent.

Till issue with most latest version.

Odoo slow running.

**Comment by rim-odoo** [comment]
What were you trying to do ? https://github.com/odoo/odoo/wiki/Contributing#reporting-issues

**Comment by tejastank** [comment]
Thanks for closing all my ticket and locking with your lacking comment.
Is seems @rim-odoo , instead to communicating of bugs, official odoo people just closing.

Let me know where did you communicate on below list, which just you close in few minutes?

https://github.com/odoo/odoo/issues/2136#event-436185351
https://github.com/odoo/odoo/issues/8317#issuecomment-148333057
https://github.com/odoo/odoo/issues/6677#issuecomment-148330732
https://github.com/odoo/odoo/issues/7747#issuecomment-148329986

Its clearly show narrow response from you & never try to involved in bugs.
Instead looks your got orders to close all them.

But thanks to all community people who already least gives positive comment to fix theme.

See here to learn least good response.
https://github.com/odoo/odoo/issues/7466

Thanks for junk update on stable odoo 8.0 bugs.

**Comment by mart-e** [comment]
@tejastank sorry if we seemed harsh and closed quickly the opened issues. The problem is that we can not do anything with bug reports without any details. When you give an error out of the blue, without knowing the state of your database, the revision of the code or even the action that was done, there is so many possible explanations we can not do anything.

So let's make it simple: to be able to work on it, we need a way to reproduce the bug in the first place on standard code (use the [runbot](http://runbot.odoo.com/runbot) for that). If you give us less than that (like on this issue), we can maybe guess but that's much much harder.
We have always stated that the github issues have the lowest priority (in comparison to pull requests or support tickets). If your issue is urgent or we need to spend a lot of time in debugging to understand the issue in the first place, then it's probably time to go to paid support, don't you think ?

**Comment by tejastank** [comment]
sometime issue raised with odoo start up command and show bugs so on those situation what else I describe.

If you see already little description always given as and when needed.

Its totally bad arguments from odoo people,
Where many people had given complete description, even bugs not responded.

Its just bad argument for details of bug, these bug with domain of odoo. I hope you got it.

@rim-odoo see 
https://github.com/odoo/odoo/issues/9070#issuecomment-148344173
Comment of mart-e show how he investigate & response. Bit investigate before response.
