### ISSUE TITLE
xmlrpc_port not used when adding it to the configuration file

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#8322]
**xmlrpc_port not considered when adding to the configuration file**

Impacted versions:

 - 8.0 and above

Steps to reproduce:

 1. Locate your openerp-server.conf file, which is usually under /etc/
 2. add a line for the xmlrpc_port at the end (for example xmlrpc_port = 8071)
 3. save your changes
 4. Run your Odoo from the terminal (./openerp-server)

For example. I have a second Odoo running on my server. Odoo A runs on port 8069. I now want to set Odoo B to port 8071 via the /etc/openerp-server.conf file. I've added the line:
<img src="http://i.imgur.com/DeIFfPN.png" alt="xmlrpc_port"/>

I then navigate to my Odoo location (/odoo/odoo-server/) and start the odoo up with
```
./openerp-server 
```

I will now get the error that tells me the Address is already in use (and that is because Odoo A is running on port 8069). 
<img src="http://i.imgur.com/9gTD8KL.png" alt="Address already in use"/>
Odoo does not seem to look at the parameter specified in /etc/openerp-server.conf, while it should?

Working options:
```
./openerp-server --xmlrpc-port=8071
./openerp-server -c /path/to/openerp-server.conf
./openerp-server (when another port is specified in /openerp/tools/config.py)
```

Not working:
```
./openerp-server
```
Odoo will not look at the port provided in /etc/openerp-server.conf and will run on the default port.

Current behavior:

 - Odoo will use the default port 8069

Expected behavior:

 - Odoo users the port that is specified in the configuration file and runs xmlrpc on the port that is specified.

**Comment by Yenthe666** [comment]
@xmo-odoo and @odony could I ask you guys for feedback please? Have I completely misunderstood this or is it really a bug?
I've tested this with the latest V8.0 Odoo from today. (sorry for the ping)

**Comment by xmo-odoo** [comment]
> Odoo does not seem to look at the parameter specified in /etc/openerp-server.conf, while it should?

Nope.

* by default, Odoo only loads `~/.openerp_serverrc` (except on Windows)
* the services generated by packaged installs (debian & redhat) *explicitly* provide a configuration file path when starting the server (that is they invoke `odoo.py --config=/etc/odoo/openerp-server.conf`

`/etc/openerp-server.conf` is not a thing, and either way the only configuration file Odoo attempts to load implicitly (if none is provided explicitly) is `~/.openerp_serverrc`. In your case, you have to start the server as `openerp-server.py -c /etc/openerp-server.conf`.

Incidentally, I checked, `xmlrpc_port` is taken in account.

**Comment by Yenthe666** [comment]
@xmo-odoo thanks for the feedback!
```
Incidentally, I checked, xmlrpc_port is taken in account.
```
You mean that it works when you use --config or -c? So there is no way for me to simply provide the ```xmlrpc_port ``` in ```/etc/openerp-server.conf```?
What is the suggested way to run ```xmlprc_port``` on another port without providing any commands then? The Odoo should take the port when the server is booted. I can't imagine that I should then edit the /openerp/tools/config.py manually, right?

**Comment by xmo-odoo** [comment]
> You mean that it works when you use --config or -c

It works when it's in a configuration file which is actually loaded, `~/.openerp_serverrc`, a file specified via the `OPENERP_SERVER` envvar or a file specified via `-c`.

> What is the suggested way to run xmlprc_port on another port without providing any commands then? 

I'm not sure what you're asking. If you specify it in `~/.openerp_serverrc` it'll be used by default, but it'll be used by any and all servers started on the machine unless they are explicitly provided an other configuration file. Same, to a lower extent, for the `OPENERP_SERVER` envvar.

**Comment by Yenthe666** [comment]
@xmo-odoo I've honestly never even heard about the ```~/.openerp_serverrc``` and it doesn't seem to be generated by default when you install Odoo? 
To give you some insight in my setup.
Main odoo repository is under /odoo-name/odoo-name-server (where the addons etc are)
The configuration is under /etc/odoo-name-server.conf
Judging by the information that I see I am assuming that your ```~/.openerp_serverrc``` is my ```/etc/odoo-name-server.conf```. My Odoo installing script does this:
```echo -e "* Create server config file"
sudo cp $OE_HOME_EXT/debian/openerp-server.conf /etc/$OE_CONFIG.conf```

Content of /etc/odoo-name-server.conf:
```
[options]
; This is the password that allows database operations:
admin_passwd = mysuperpassword
db_host = False
db_port = False
db_user = odoo-name
db_password = False
addons_path = /usr/lib/python2.7/dist-packages/openerp/addons
logfile = /var/log/odoo-name/odoo-name-server.log
addons_path=/odoo-name/odoo-name-server/addons,/odoo-name/custom/addons
xmlrpc_port = 8071
```

So if I understand everything correctly the ```xmlrpc_port``` that is specified under ```/etc/odoo-name.conf``` should change the port?

Thanks for your feedback.

**Comment by xmo-odoo** [comment]
> I've honestly never even heard about the `~/.openerp_serverrc` and it doesn't seem to be generated by default when you install Odoo? 

No, why would it be?

> Judging by the information that I see I am assuming that your ~/.openerp_serverrc is my /etc/odoo-name-server.conf.

No, the lookup of `~/.openerp_serverrc` is actually embedded in openerp.tools.config, the lookup of `/etc/odoo-name-server.conf` is nowhere in Odoo.

> So if I understand everything correctly the xmlrpc_port that is specified under /etc/odoo-name.conf should change the port?

If you tell the server to load that file (by starting it with `-c` or setting the relevant environment variable). The server is not going to load that file if you don't tell it to.

**Comment by Yenthe666** [comment]
@xmo-odoo 
```
No, why would it be?
```
I was assuming from your information, but I've misunderstood that.
```
No, the lookup of ~/.openerp_serverrc is actually embedded in openerp.tools.config, the lookup of /etc/odoo-name-server.conf is nowhere in Odoo.
```
Why was the choice made to specifically look under ```~/.openerp_serverrc```? Why not from the /etc/odoo-server.conf file or somewhere in the Odoo structure?
```
If you tell the server to load that file (by starting it with -c or setting the relevant environment variable). The server is not going to load that file if you don't tell it to.
```
I see but that would mean that I would still have to start the Odoo myself with the -c option atleast once to save this configuration? I've created the ```file openerp_serverrc``` under ```~/ ```for the Ubuntu user that runs Odoo and then run the command ```./openerp-server -c /odoo-name/openerp_serverrc ``` but it will say there is no module web_kanban. I think I'm still missing some things or not understanding something. Again, thank you for the help and details.

**Comment by Yenthe666** [comment]
@xmo-odoo I was wondering one more final thing. Where exactly will everything be stored when you issue ```./odoo-server -c /path/to/file``` and when would the -c be removed ever again?
For example: I've set an ```xmrpc_port``` to 8080 and issued ```./odoo-server -c /path/to/file``` which will make the Odoo run on port 8080 from now on. In which cases will the values be removed that are saved with -c?

**Comment by xmo-odoo** [comment]
> Why was the choice made to specifically look under ~/.openerp_serverrc? 

Similarity with other user-account rc files for development. The original commit has been lost to time but I assume it was linked to ease of development.

> Why not from the /etc/odoo-server.conf file

Why that?

>  or somewhere in the Odoo structure?

Interferes with development (high risk of people committing their altered configuration file) and broken when Odoo is deployed on a readonly filesystem (which is a good security measure)

> I see but that would mean that I would still have to start the Odoo myself with the -c option atleast once?

That would mean you'd have to start Odoo with `-c` every time, settings don't stick so running the system without `-c` would just fall back on the defaults.

> I've set an xmrpc_port to 8080 and issued ./odoo-server -c /path/to/file which will make the Odoo run on port 8080 from now on. In which cases will the values be removed that are saved with -c?

They won't be. You can save settings to a config file with `-s` (and `-c` to specify the configuration file to save to), but configuration files are read per-run and they are not "remembered" between runs. If you want Odoo to use the settings stored in a configuration file, you have to use that configuration file every time.

**Comment by Yenthe666** [comment]
Excellent answer and information there. :+1: 
So the only way to make the Odoo always start from a desired port without providing any terminal commands is by changing the ```xmlrpc_port``` under ```/openerp/tools/config.py``` to something else then 8069?

**Comment by xmo-odoo** [comment]
I guess?

**Comment by Yenthe666** [comment]
@xmo-odoo in all honesty I really think that this feature should exist. It should be possible to change the Odoo port number without modifying a default Python file from within Odoo.
Any suggestions / ideas? I would really like to build an option for this. Would this ever be accepted in Odoo I would build it?

**Comment by xmo-odoo** [comment]
> in all honesty I really think that this feature should exist.

Why? I don't understand what your problem is and why you apparently refuse to provide a configuration file or an option.

> It should be possible to change the Odoo port number without modifying a default Python file from within Odoo.

It is. You can provide a port number via a configuration file or a command-line option.

> Would this ever be accepted in Odoo if I would build it?

I see no compelling reason for that to happen.

**Comment by Yenthe666** [comment]
```Why? I don't understand what your problem is and why you apparently refuse to provide a configuration file or an option.
```
I want to run an Odoo from a specific port without changing config.py and without suppyling any -- option through the terminal. The moment the VM boots all Odoo's should be started on the port that they have configured in /etc/odoo-server.conf or somewhere else. If I understand correctly there is not a single option to do that without using a -- option or specifying the port in config.py.

```It is. You can provide a port number via a configuration file or a command-line option.```
I thought there was no option to provide this in a configuration file? (besides config.py under /openerp/tools)

**Comment by xmo-odoo** [comment]
> I want to run an Odoo from a specific port without changing config.py and without suppyling any -- option through the terminal.

That still doesn't explain what your problem is, why do you want to start Odoo with no command-line parameter?

>  The moment the VM boots all Odoo's should be started on the port that they have configured in /etc/odoo-server.conf or somewhere else.

Which you could do by starting Odoo with `-c`, or by setting the `OPENERP_SERVER` environment variable, or by using `~/.openerp_serverrc` as your configuration file, or by writing a trivial wrapper script which starts Odoo doing any of these (the latter being exactly what the Debian and Redhat installers do, incidentally)

> If I understand correctly there is not a single option to do that without using a -- option or specifying the port in config.py.

See above, there are multiple ways to do that.

**Comment by Openies** [comment]
Having the same Issue, odoo 9c  is taking default port 8069,
It is working if i provide port via ./odoo.py --xmlrpc-port=8018 but not in case of i provide it in the config file. even it is not taking db user. I have checked permission it seems fine!

Here is my config file.
```
[optinos]
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo@123
admin_passwd = ad,in
logfile = /var/log/odoo/odoo-server.log
addons_path=/opt/odoo/addons
xmlrpc = True
xmlrpc_port = 8018
```

**Comment by odony** [comment]
@Openies assuming you really copy/pasted your config file, you'll probably have better results after correcting the typo in the options headers "[opti**no**s]" -> "[options]"

**Comment by Openies** [comment]
Oh my god my eyes! 
Thanks @odony !!

**Comment by toplinuxsir** [comment]
The problem still exist on odoo 10.0!

**Comment by bunhin** [comment]
I have similar problem i believe, I instaled verion 10 of odoo, it running ok.  Then i install second instance install for odoo9.  Set the xmlrpc=True and xmlrpc-port=8079  in odo9-server.conf  file.

The server odoo9 is started and running  also odoo  10,   i can access odoo 10 from the browser at IP:8069 but always fail when access odoo 9 through IP:8079

I did open 8079 port in firewall also in selinux

Please help find out why is this problem happen? / how to fix

Regards,
Bun Hin

**Comment by bunhin** [comment]
My problem is solve, i am sorry for bothering,  it is  xmlrpc-port   with xmlrpc_port that that make the difference
