### ISSUE TITLE
GAEB DA XML Connector [GER/Construction/Craftsmen]

### ISSUE THREAD

**Issue by LorbusChris** [odoo/odoo#8325]
for the Wishlist:
Create a connector for GAEB DA XML Export. This is used extensively in Germany in Construction and Craftsmen Businesses. 

More Information here:
https://www.gaeb.de/en
https://www.gaeb-da-xml.de (German)
https://de.wikipedia.org/wiki/Gemeinsamer_Ausschuss_Elektronik_im_Bauwesen (German)
the NL version of this links to:
https://nl.wikipedia.org/wiki/RAW-bestekssystematiek
which seems to be the aquivalent in NL.

**Comment by Yenthe666** [comment]
Hi @mart-e,

Should I label this as wishlist or is this something Odoo wouldn't want to build?

Regards,
Yenthe

**Comment by mart-e** [comment]
same as #8326
