### ISSUE TITLE
DATANORM Connector [GER/Construction/Craftsmen]

### ISSUE THREAD

**Issue by LorbusChris** [odoo/odoo#8326]
for the Wishlist:
Create a connector for DATANORM Export. This is used extensively in Germany in Construction and Craftsmen Businesses.

see here for more Information (in German):
http://www.datanorm.de/
https://de.wikipedia.org/wiki/Datanorm

**Comment by Yenthe666** [comment]
Hi @mart-e,

Should I label this as wishlist or is this something Odoo wouldn't want to build?

Regards,
Yenthe

**Comment by dreispt** [comment]
@LorbusChris That kind of connector can be perfectly implemented as a Community module. The https://github.com/OCA/l10n-germany would be a great place to host it.

**Comment by Yenthe666** [comment]
@dreispt I agree with you, could be a neat community module. But, who knows, Odoo perhaps wants to add it to the wishlist? I don't think they will but just checking with Martin to be sure.

**Comment by mart-e** [comment]
Hello,

As stated in [target version table](https://github.com/odoo/odoo/wiki/Contributing#against-which-version-should-i-submit-a-patch), we are open to submissions of new localizations, payment and shipping providers.
For connectors outside of these (looks like it is the case for DATANORM), we prefer to avoid for now on. So indeed, I advise you to check with the OCA.
