### ISSUE TITLE
AttributeError: Field `sel_groups_5_14_15` does not exist 

### ISSUE THREAD

**Issue by SanathT** [odoo/odoo#8328]
Impacted versions:
- 8.0

Steps to reproduce:
1. Create New group with menu access right for "Settings/Users" & "Settings". 
2. Set Access Rights for "Users" / "Access Groups" to this group.
3. Add normal user to this group
4. Login as that user
5. Navigate to Settings -> Users
6. Click on a user 

Current Behaviour:
- Following error message is displayed.
  
  `AttributeError: Field`sel_groups_5_14_15`does not exist`

![error](https://cloud.githubusercontent.com/assets/13434578/9626521/c9aaccb0-517b-11e5-8a0c-3b50ace5a2f8.png)

Expected behavior:
- User form should be displayed.

**Comment by Yenthe666** [comment]
Hi @SanathT,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
