### ISSUE TITLE
Stock Journal does not considered un-taxed amount when tax is included in price

### ISSUE THREAD

**Issue by aldennis** [odoo/odoo#8330]
When Odoo creates an entry for stock journal for the product received whose price includes VAT, it uses the total amount of product instead of the un-taxed amount

Steps to produce
1. Create a product with the following configuration
     - Inventory Valuation: Realtime (automated)
     - Product Type: Stockable
     - Costing Method: Average Price
2. Create a PO for the said product and select a tax which is included in product price
3. Confirm the PO and receive the items
4. Go to Accounting/ Journal Entries and check the Stock Journal entry created upon received of items
- Notice that the amount use is the total amount of product + tax. It should be the amount net of tax since you do not include the tax amount when valuating your inventory

**Comment by oliverzgy** [comment]
@aldennis here's a temp fix for this issue. Take a try and let me know if it works

https://github.com/OpenStone/odoo-extras/tree/8.0/price_tax_included_fix

**Comment by Yenthe666** [comment]
Hi @aldennis,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
