### ISSUE TITLE
master/saas: handling auto submitted email messages

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#834]
I'm part of the "Followers of Community-Framework" on odoo website. There is an ongoing discussion with topic "Relational Division" in which there seem to be an issue with some automatic response handling: each message sent to this thread triggers an answer from 
yeahbull@yeah.net, google translate telling me that it is probably an automated "I received your message" answer. 

The original mail headers seem to be eaten by odoo so I can't tell if the original message has the auto-submitted header recommended by RFC3834, but I feel such responses should not be forwarded to everyone in such discussions. 

Note that the setting should be different in a "mailing list" like context (such as this case for the "Community Framework" discusssion, and for tickets / sale orders / etc for which we do want to log vacation messages. In any case, I think this header should be preserved.

**Comment by Yenthe666** [comment]
Dear @gurneyalex,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
