### ISSUE TITLE
[15.0] StockMoveLine._add_to_wave throw "list index out of range" error

### ISSUE THREAD

**Issue by imhuytq** [odoo/odoo#83450]
Impacted versions:
15

Steps to reproduce:
Create a transfer with 3 moves for 3 products:
- A - qty 60 (2 move lines, each move line has a quantity of 30)
- B - qty 40 (2 move lines, each move line has a quantity of 20)
- C - qty 40 (2 move lines, each move line has a quantity of 20)

Create a new wave picking containing the first move lines of each product (3 move lines)

Current behavior:
System returned error: IndexError: list index out of range

Expected behavior:
Will successfully create a new wave containing the 3 selected move lines.

Video/Screenshot link (optional):
<img width="848" alt="Screen Shot 2022-01-27 at 2 01 24 AM" src="https://user-images.githubusercontent.com/5723282/151229128-cb5524e6-a37d-49c7-864a-602438a6fa6a.png">

Support ticket number submitted via odoo.com/help (optional):

**Comment by odoochina-dev** [comment]
odoo\addons\stock_picking_batch\models\stock_move_line.py
the line 
```
                # Split the move
                qty = sum(lines.mapped('product_qty'))
```
is typo, shall be `qty = sum(move_lines.mapped('product_qty'))`

It shall be a bug, but I cannot confirm it onbehalf of odoo O(∩_∩)O
You can fix it by yourself (as workaround), then restart odoo.

**Comment by imhuytq** [comment]
> odoo\addons\stock_picking_batch\models\stock_move_line.py the line
> 
> ```
>                 # Split the move
>                 qty = sum(lines.mapped('product_qty'))
> ```
> 
> is typo, shall be `qty = sum(move_lines.mapped('product_qty'))`
> 
> It shall be a bug, but I cannot confirm it onbehalf of odoo O(∩_∩)O You can fix it by yourself (as workaround), then restart odoo.

You are right @odoochina-dev , it was a typo.
I did as you said and it worked. Thank you very much.

**Comment by odoochina-dev** [comment]
@pedrobaeza, @Yenthe666 recently looks nobody to confirm odoo issues from Odoo S.A.? 

(please someone to confirm this bug, thanks!)

**Comment by Yenthe666** [comment]
@odoochina-dev Pedro and me used to manage it out of best effort & for free. However, since Odoo SA never really cared or helped us we both quit doing it. That's why the issues part is pretty much completely dead, nobody is managing it anymore.
As for the fix: feel free to make a PR for it :)

**Comment by odoochina-dev** [comment]
@Yenthe666 Thanks to clarify and great thanks to your collabortaing in the past.
(odoo Issues recently really situation in a mess...)

**Comment by amoyaux** [comment]
Yep, you are right gonna fix it
