### ISSUE TITLE
Digest model: automatic, non-optional scheduling slowdown

### ISSUE THREAD

**Issue by FredericoCoelhoNunes** [odoo/odoo#83511]
Impacted versions: Odoo 15

Steps to reproduce: Following lines of code on the `addons/digest/models/digest.py` (Digest model)
![image](https://user-images.githubusercontent.com/51457048/151388698-0fc7eee0-e476-4bb7-b2d3-c0ca01f46086.png)

Current behavior: There's some non-optional logic implemented that keeps setting my daily digest to weekly.

Expected behavior: That this functionality is opt-in. Optionally, remove lines 116, 123 and 124 in the code, together with the _check_daily_logs method.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by jonsq** [comment]
I realize it has been a few years, but did you ever find a solution to prevent this from happening?

**Comment by vava-odoo** [comment]
Hi @FredericoCoelhoNunes & @jonsq 
FYI, this was changed in 16.0 with https://github.com/odoo/odoo/pull/86934, but I don't think this can be backported to 15.0 as the fix introduced a change in the method signature.
Cheers

**Comment by jonsq** [comment]
Hi @vava-odoo 
Are you aware of a setting in v16.0 that allows us to prevent the automatic slowdown?

**Comment by vava-odoo** [comment]
Hi @jonsq 
No, not that I'm aware of, sorry. But you can ask such question on the [forum](https://www.odoo.com/forum/help-1) (or see if anyone already asked it).
Cheers
