### ISSUE TITLE
[15.0] Odoo exe generated manually could not be installed

### ISSUE THREAD

**Issue by hugho-ad** [odoo/odoo#83525]
Impacted versions:
15.0

Steps to reproduce:
On a fresh install of Win10 x64
- Install nsis-3.08
- Install python37
- create following dirs 
   C:\odoobuild
   C:\odoobuild\nssm-2.24
   C:\odoobuild\vcredist
   C:\odoobuild\Winpy32
   C:\odoobuild\Winpy64

Download :
nssm-2.24 from https://nssm.cc/download
From https://www.microsoft.com/en-us/download/details.aspx?id=48145
get following
- VC_redist.x64
- VC_redist.x86

- Install winpy and extract it at 
   C:\odoobuild\WinpyXX

- Install Odoo requirements
cd C:\odoobuild\WinpXX
pip install -r OdooPATH/requirements.txt

- Install NSIS 3.08
Download and install makensis from https://prdownloads.sourceforge.net/nsis/nsis-3.08-setup.exe?download
Add pluging
https://nsis.sourceforge.io/Inetc_plug-in

- Make the exe file by following command
"C:\Program Files (x86)\NSIS\makensis.exe" /DVERSION=15.0 /DSERVICENAME= /DPYTHONVERSION=37 setup.nsi

Try install .exe generated
Current behavior:
Installation fails 

```
Installing Windows service
Error creating service!
CreateService(): The filename, directory name, or volume label syntax is incorrect.

Invalid parameter "C:\Program".  Valid parameters are:
Application
AppParameters
AppDirectory
```
Full error log
https://gist.github.com/hugho-ad/9b8bb470d19bf70d3c48e79772281871
Expected behavior:
Clean installation of the .exe manually generated

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):
## 2747368

**Comment by hugho-ad** [comment]
FYI @d-fence

**Comment by odoochina-dev** [comment]
a common issue pattern for many sw in windows world is, if the installation/build path contains space (e.g. C:\Program Files) or unicode chars(e.g. C:\我爱odoo), the intallation/build may failed.

You could try to install odoo at path that does not include space char, nor unicode chars, as workaround

**Comment by d-fence** [comment]
I was not able to reproduce the issue.
But as I see in your command, you gave an empty service name, that probably explains the issue.
`/DSERVICENAME=odooserver` or something like that.

**Comment by hugho-ad** [comment]
that was the issue!

thanks!
