### ISSUE TITLE
[7.0] Fields function store attribute does not allow chain update

### ISSUE THREAD

**Issue by a0c** [odoo/odoo#8360]
Copied from [Launchpad](https://bugs.launchpad.net/openobject-server/+bug/1089902).

This problem occurs when a `fields.function` has another `fields.function` in its `store={}` parameter. The first function is never called next to the second one.

For example :

``` python
class A:
    'a_value' : fields.function(_update_value,
                                store={'class_b' : _function,'b_value',10]},
                                method=True, type='integer', string='value')
class B:
    'b_value' : fields.function(_update_value,
                                store={'class_c' : _function,'c_value',10]},
                                method=True, type='integer', string='value')
class C:
    'c_value' : fields.integer('value')
```

Here, changing a `c_value` would change the `b_value`, but not the `a_value`.
(With `b_value` set as `readonly='false'`, we could change it manually and see that the `a_value` is correctly recalculated.)

**Comment by Yenthe666** [comment]
Hi @a0c,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
