### ISSUE TITLE
[15.0] Custom exceptions not working anymore?

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#83633]
Impacted versions: 15.0

I remember in older versions you could do this:

```python
from odoo.exceptions import UserError

class MyError(UserError):
    pass
```

But in v15, I do get full traceback (not Odoo exception pop up). Are custom exceptions no longer work?

**Comment by william-andre** [comment]
It hasn't worked for a very long time at least.
To get it working, it is not too hard:
https://github.com/odoo-dev/odoo/commit/52ef6517292f24de5468a61da730dbe20c193603

*Note:
I never merged this because it is part of a bigger refactor*
