### ISSUE TITLE
Passing values from one form to another using an action button.

### ISSUE THREAD

**Issue by PRTBELL** [odoo/odoo#83668]
Hey, I created a new button called "Request Material" in the Manufacturing Orders Form- this button should open the internal transfer form to move material between internal locations.
I have created an action passing the Operation type as a context value.. but I am not sure how to get the values of the materials not available in the Manufacturing Order form to the Transfer Form. 
Expected Result: Clicking Button creates a form with pre-filled values of materials that are not available. i.e: Products "b" & "c" should appear in the internal transfer form.

Manufacturing form- from which information needs to be passed to a new form
![image](https://user-images.githubusercontent.com/91874900/151788454-02abb8d4-866b-4aca-8ec7-462b1b54e47b.png)

Transfer Form- values needs to appear here
![image](https://user-images.githubusercontent.com/91874900/151788528-0e1a9c29-64eb-472e-a628-7f484ee6aeb6.png)

Action button which I created with operation type as context.
![image](https://user-images.githubusercontent.com/91874900/151788599-ef9b5433-c320-42c8-8fd3-fd1f8024d42a.png)

Desired result: Need to pass unavailable material from the manufacturing form to the transfer form when I click on the button "Request material"

**Comment by william-andre** [comment]
You can use `default_{name of the field}` keys in the context
I.E.
```python
context = {
    'default_name': self.name
}
```
Or you could create an item with the right values and return it's `res_id` in the action dictionary.
```python
    def my_action(self):
        other = self.env['other.model'].create({
            'name': self.name,
        })
        return {
            'name': _('New other model'),
            'type': 'ir.actions.act_window',
            'view_type': 'form',
            'view_mode': 'form',
            'res_model': 'other.model',
            'res_id': other.id,
        }
```

**Comment by PRTBELL** [comment]
Thank you for your reply, But I am not sure if you've understood my question. I want the Component lines in my Production Model to be copied to the Move Lines in the StockPicking model. 
I.E. 
<img width="804" alt="image" src="https://user-images.githubusercontent.com/91874900/156118537-91b96ff8-465e-4e1c-b25e-760d45c53a38.png">
the components B & C which are not available, should appear here in operation (stockpicking) 
<img width="451" alt="image" src="https://user-images.githubusercontent.com/91874900/156120082-ac786043-0cff-4aab-8df2-65890defec30.png">
