### ISSUE TITLE
[13.0] [account] Invalid reference to FROM-clause entry for table account_move_line

### ISSUE THREAD

**Issue by celm1990** [odoo/odoo#83694]
Hi, I get error after this PR https://github.com/odoo/odoo/pull/82986
I have 2 customer with same error
Impacted versions:
13.0 tested on runbot
Steps to reproduce:

Tested on runbot(https://12367880-13-0-all.runbot69.odoo.com/)

1) create a new User only with Group Purchase User(user has not Account groups)

![image](https://user-images.githubusercontent.com/7775116/150848125-b4a50555-dc33-4f50-9095-13001f2471f4.png)

2) Is need call to function `_query_get `for testing purpose, add field `credit `or `debit `into form view
![image](https://user-images.githubusercontent.com/7775116/150848301-8f64a6f5-7a38-4ba8-a304-f1d69062ea17.png)

3) With new user, refresh page and try open contact form view and get error
![image](https://user-images.githubusercontent.com/7775116/150847900-df89b540-f647-4917-be8f-97898ff6213d.png)

Current behavior:
Error with traceback
Expected behavior:
No error
Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):
ticket #2749572

@qdp-odoo can you help me please

**Comment by NikJmaeff** [comment]
@william-andre Hello, I am wondering the status of this ticket and the odoo support ticket as well. The last working build will be expiring soon.

**Comment by william-andre** [comment]
Hello,
I don't see how it is related to the linked commit. Before #82986 you would have needed to access `account.move`, which has the same access rights.
Also, this seems like a desired behavior. You don't want everyone to be able to see the current debit/credit of all the clients/providers as it is a private information generally speaking.
