### ISSUE TITLE
Support CockroachDB as alternative to PostgreSQL

### ISSUE THREAD

**Issue by r3d00** [odoo/odoo#83730]
Impacted versions: latest

Steps to reproduce: 
Installation of odoo as docker container, described in the current documentation. Set connection details of a cockroachDB instance. Provide necessary certificates (CA, User Cert & User Key) as container mounts with correct permissions. 

Current behavior:

The docker container starts as expected with some minor warnings in the log files:

`2022-02-01 09:12:32,423 117 ERROR ? odoo.service.server: Worker (117) Exception occurred, exiting...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 1028, in run
    self.start()
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 1179, in start
    self.dbcursor.execute("LISTEN cron_trigger")
  File "<decorator-gen-3>", line 2, in execute
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 89, in check
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 310, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.SyntaxError: at or near "listen": syntax error
DETAIL:  source SQL:
LISTEN cron_trigger
^
2022-02-01 09:12:32,464 117 WARNING ? odoo.sql_db: Cursor not closed explicitly
Please enable sql debugging to trace the caller.`

When trying to create a new database in /web/database/create:

`Database creation error: at or near "template": syntax error DETAIL: source SQL: CREATE DATABASE "test" ENCODING 'unicode' LC_COLLATE 'C' TEMPLATE "template0" ^`

It seems it does not like "template0" here.

Expected behavior:

As discussed in the other (closed) feature request, CockroachDB was 3 years old when this request (2017) got created. We are now approx. 4 years later and it would seriously help to be able to scale and secure the database backend of odoo with CockroachDB, which is way more cloud native than postgreSQL.

For my other applications I am using peewee as ORM, which supports CockroachDB and is using psycopg2 just like odoo.

Video/Screenshot link (optional):

Older (closed) feature request for reference: #21479

**Comment by gdgellatly** [comment]
@r3d00 Not supporting NOTIFY/LISTEN is not a minor issue, its a pretty big issue given that is how longpolling and cron works but also some of the most required modules at scale currently require it. And if you aren't at scale then you don't really need cockroachdb.  Postgres is perfectly acceptable and all the major cloud services off it as a service again perfectly acceptable for even midsized installs. 

But also being distributed it means sequential index performance sucks. And that is what Odoo uses for primary keys.  And for an ERP that makes a whole lot of sense (compared to say GUIID's) if you think about the time value of information and how records are typically inserted.

And no support for pg_trgm probably the most necessary postgres extension for odoo with any volume, given the typical use case is openended ilike searches. I've followed the project fairly closely and for me it is still just nowhere near requirements. 

I simply cannot see how you can scale Odoo with CockroachDB's current feature set and Odoo's current architecture. And if you aren't at scale why would you bother?   Just use someone else managed service and forget about it.

But maybe it isn't a lot of work for you to do the basics to get it running and try some performance testing with lots of data. Be interested to see your results.

**Comment by r3d00** [comment]
Taking into account my limited time I actually switched to a postgres replicated cluster instead.

I was actually of the opinion, that CRDB is a drop-in-replacement for Postgres, which is obviously not the case after some research.

**Comment by william-andre** [comment]
> I was actually of the opinion, that CRDB is a drop-in-replacement for Postgres, which is obviously not the case after some research.

So can you close this issue too?
