### ISSUE TITLE
Button of Wire Transfer payment method does NOT work from a manual invoice

### ISSUE THREAD

**Issue by tvibliani** [odoo/odoo#8375]
**Wire Transfer button does not work in manual invoice or in invoice generated from manual Sale Order**

Impacted versions:
- 8.0

Steps to reproduce:
1. configure Wire Transfer method to have Wire Transfer payment button in Sale Order and in Invoice
2. create a new sale order and generate invoice OR create directly customer invoice manually
3. from user portal open the invoice(or Sale Order) and click on Wire Transfer payment button within  opened form

Current behavior:
- Operation can not be completed because of error:

```
ValidationError: received data for reference u'SAJ/2015/0020'; no order found
```

Expected behavior:
- Working Wire Transfer button in the Invoice/Sale Order forms.

**Comment by Yenthe666** [comment]
Hi @tvibliani,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
