### ISSUE TITLE
Change font in Qweb reports

### ISSUE THREAD

**Issue by damdam-s** [odoo/odoo#8381]
Hello,

I'm trying to change font in all reports in Odoo8. 
I managed changing font in "body" part of the Qweb reports but when I do the same for header/footer, it works with html rendering but not in pdf rendering mode.

For example, when i use this url, the whole report have the desired font : http://SERVER:PORT/report/html/hr_expense.report_expense/ID
But when i use the following url, http://SERVER:PORT/report/pdf/hr_expense.report_expense/ID, the report content have the good font but not header nor footer.

Do you have a solution for this issue ?

**Comment by Yenthe666** [comment]
@sle-odoo can you give an update / feedback here please?

**Comment by sle-odoo** [comment]
Hi,
You also have to edit [this view](https://github.com/odoo/odoo/blob/8.0/addons/report/views/layouts.xml#L146) by adding the font's link.

In recent Odoo versions, there's a pdf assets which is loaded in header/body/footer, so you don't have to add the font in two different views.

Regards

**Comment by bluemix** [comment]
any updates?

**Comment by sle-odoo** [comment]
This issue is targeted to the v8 which is not supported anymore, and i answered with the solution earlier. There are two views to update.

Regards
