### ISSUE TITLE
Translation files do not appear for download in the translation wizard

### ISSUE THREAD

**Issue by moval-agroingenieria** [odoo/odoo#83838]
When exporting a translation file (.po, .csv, .tgz) the file does not appear for download in the wizard.

Impacted versions: 10.0

Steps to reproduce:
 1.- Go to /Configuration/Translations/Export traduction
 2.- Choose a format and export it
 3.- The file does not appears

Current behavior: he file does not appears

Expected behavior: The file can be downloaded

Additional context
It works if 'git reset --hard' to this commit: 700647c

**Comment by william-andre** [comment]
Version 10 is not supported anymore
https://www.odoo.com/documentation/master/administration/maintain/supported_versions.html

Please upgrade your database, and get tons of new awesome features.

If this issue still exists on supported versions, please reopen it
