### ISSUE TITLE
[Master] 05.09.2015 Missing "technical features" checkbox

### ISSUE THREAD

**Issue by explanar** [odoo/odoo#8391]
At the today's installed Master (Ubuntu 14.04 minimal, ESC/POS Hardware Drivers, POS_restaurant) i can't find any checkbox for "technical features" to give the admin user it's power.

Also the Selection-box of "Administration" has a misunderstandable function, it's not intuitive expectable what happens by changing it. The "configuration" mode disables menu items that are neccessary for configuration, the "access rights" mode gives the "Settings" item back to the main menu and the "settings" mode seems to most powerful, but without availability of "technical features".

I already researched aiming to find a console command that enables the admin user for the technical features, tried new databases, tried the "-u base" command for different databases in different situations but no checkbox.

Any ideas?

**Comment by loslolos** [comment]
Technical features are shown when you enable Developer mode

**Comment by explanar** [comment]
Thank's! Didn't know that the technical-Features checkbox has been replaced by the debug mode!

**Comment by bringsvor** [comment]
I have this problem too, but can't get the technical features enabled even
when using developer mode.

For example I wish to update the list of modules, that required technical
features in the past. Can't find a way of doing that now.


Torvald Baade Bringsvor
*Bringsvor C**onsulting AS* - Odoo (formerly OpenERP) implementation partner


2015-09-09 19:13 GMT+02:00 explanar <notifications@github.com>:

**Comment by explanar** [comment]
Try URL: ```ip_address:8069/web?debug```

**Comment by bringsvor** [comment]
Aha. Well it does work. Since I develop a lot I tend to have technical features enabled always so this is not really a welcome change. But guess I'll have to learn to live with it.
