### ISSUE TITLE
Odoo - Client Error  TypeError: product is undefined

### ISSUE THREAD

**Issue by saimon69** [odoo/odoo#8400]
I am getting the below error at random when I type the first character in the search field of the POS app. I could not find any viable info looking at the logs.
Can you please help with some pointers to where the issue could be?

Thank you in advance,

![screenshot1](https://cloud.githubusercontent.com/assets/14144428/9702313/a9553f9e-540b-11e5-8928-f9321a822a60.png)

**Comment by Yenthe666** [comment]
Hi @saimon69,

Please update your Odoo to the latest version. For more information have a look at https://www.odoo.com/documentation/11.0/
This problem can't be reproduced on the latest Odoo anymore.
