### ISSUE TITLE
[8.0]Inventory adjustment date bug

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#8402]
Hello Odoo,

I found a bug when I want to do inventory adjustment,
So on 3 September 2015, I created inventory adjustment ,and the state still on progress.
The next day 4 september 2015, I validated it,

The date of adjustment still on  3 September 2015,
But the move created on 4 September 2015,

The expected behavior should be the date of adjustment must change to 4 September 2015 when we validate it.

Thanks

**Comment by Yenthe666** [comment]
Hi @falinwa ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
