### ISSUE TITLE
localhost:8069 refused to connect.

### ISSUE THREAD

**Issue by Rochbetta** [odoo/odoo#84038]
Can someone please help to solve this problem? I cannot access because the browser indicate: localhost refused to connect. ERR_CONNECTION_REFUSED.

I had proceed to fixed the proxy, but the inconvenice persist. Please, I need some help. Im new in all this.

![image](https://user-images.githubusercontent.com/93293909/152629870-011e7fea-7fd0-4132-8285-53f95b95e075.png)

**Comment by MihranThalhath** [comment]
Hi @Rochbetta ,

Kindly direct your doubts to [Odoo Forum](https://www.odoo.com/forum/help-1)

**Comment by william-andre** [comment]
You probably didn't start the server or chose another port in you config.
Anyways, the forum mentioned above is better suited for this question indeed
