### ISSUE TITLE
[8.0] Manufacturing order from Sale order without default warehouse

### ISSUE THREAD

**Issue by ernesto-gm** [odoo/odoo#8413]
**[8.0] Manufacturing order from Sale order without default warehouse not working**

Impacted versions:
- 8.0

Steps to reproduce:
1. Open the product: HDD SH-2.
2. Select Manufacture and Make To Order fields.
3. Edit the pull rule, use information of Chicago warehouse (review the video).
4. Create a Sale order from Chicago warehouse and create a line with the product HDD SH-2
5. Go to manufacturing orders and complete the process to create [HDD SH-2].
6. Open the SO and recheck the transfer of product.

to more information check the video:
https://youtu.be/dIikHchR4jw

Current behavior:
- The transfer of product is not possible, but the quantity of product is available.

Expected behavior:
- Allow the transfer of products, because it is available in the warehouse of the sale

**Comment by Yenthe666** [comment]
Hi @ernesto-gm,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
