### ISSUE TITLE
[8.0] Can't cancel back order 

### ISSUE THREAD

**Issue by chrisdec** [odoo/odoo#8414]
Hello, 

I noticed a problem in Odoo 8.0 regarding the cancellation of back order with products of type "set" (BoM). 
## Steps to reproduce
1. Open Runbot 
2. In Settings > Configuration > Warehouse, activate the following options : 
   "Manage multiple locations and warehouses" and "Manage advanced routes for your warehouse"
3. Go on Warehouse > Configuration > Warehouse and open "Your company" warehouse 
   For the outgoing shippings, choose "Bring goods to output location before shipping (Pick + Ship)"
4. Create 5 products : 
   Product 1 : Stockable Product + Buy + Put stock on WH/Stock (update quantity)
   Product 2 : Stockable Product + Buy + Put stock on WH/Stock (update quantity)
   Product 3: Consumable + Buy
   Product 4 :Stockable Product + Buy + Put stock on WH/Stock (update quantity)
   Product 5 : Consumable + (no route) 
5. Go on Manufacturing > Products > Bill of materials 
   Create a BoM of type "set" for product 5 with following components : 
   1 \* product 2
   1 \* product 3
   1 \* product 4
6. Create a sales order and sell to a customer : 
   1 \* product 1 
   1 \* product 5
   Then confirm the SO. 
7. Open the first transfer "Pick" (stock --> Output) and transfer it (entirely) 
8. Open the delivery order (output --> Customer) and transfer only product 1 and product 4
   --> Creation of a back order for product 2 and product 3
9. Try to cancel the back order. 
## Current Behavior 

You obtain an error : 

MissingError 

One of the records you are trying to modify has already been deleted (Document type : Procurement) 
## Expected behavior 

You must be able to cancel the back order. Product 1 and product 3 stay in the "output zone". 

Thanks in advance for your answer!

**Comment by jni-odoo** [comment]
Hello Chirstelle,

Firstly is this a real business case as I can see that you are trying to configure a BOM for the consumable product with the no route (Normally it is with Manufactured Products).

Second thing I marked that you have PRODUCT 5 (SET) which is made up of PRODUCT 2,3,4 so it is obvious that it is consists of these three products ,so when you try to send the products individually to the customer , say only product 2 you are sending to the customer, then system found it is a set and you sent only one product of that set (product 2)..the other product 3 , and product 4 are not sent..

So at the time of cancelling the back-order (product 3 and 4) , it is giving you the error..At some extent I agree that the wordings of the error message is wrong .It can be modified..

For Example , I have a product CPU which is consists of RAM , Mother Board and SMPS..

Now , I send only RAM to the customer and for rest 2 I want to cancel the Back Order then how system will allow that ??

I beg to differ that it is a bug.. If you try with the same configuration but without any BOM and SET then it will work definitely..

Thanks ,
Nikunj Jani (jni@odoo.com , Odoo India)

**Comment by chrisdec** [comment]
Hello, 

Firstly is this a real business case as I can see that you are trying to configure a BOM for the consumable product with the no route (Normally it is with Manufactured Products).

--> It is exactly the same behavior if you put "manufacture" route on a stockable product. And yes it is a real business case. (It is also the same behavior if the outgoing shippings on your warehouse is simply "ship directly from stock"). 

Second thing I marked that you have PRODUCT 5 (SET) which is made up of PRODUCT 2,3,4 so it is obvious that it is consists of these three products ,so when you try to send the products individually to the customer , say only product 2 you are sending to the customer, then system found it is a set and you sent only one product of that set (product 2)..the other product 3 , and product 4 are not sent..

So at the time of cancelling the back-order (product 3 and 4) , it is giving you the error..At some extent I agree that the wordings of the error message is wrong .It can be modified..

--> Ok we could assume that it is not possible to divide a kit in Odoo. But in this case, the error message must be different and must be before the creation of the back order. If I can't divide a kit, I can't have the possibility to divide my kit into two transfers (principal and back order). 

For Example , I have a product CPU which is consists of RAM , Mother Board and SMPS..

Now , I send only RAM to the customer and for rest 2 I want to cancel the Back Order then how system will allow that ??

--> My customer sometimes modifies a bit the scheduled "standard" kit and doesn't deliver one of the components to his customer (for example, the customer already has this component at home and doesn't need it). In this case, he wants to deliver all other components and keep in stock the unneeded component. It is not a problem for him. It is not because it doesn't make sense with a CPU that it never makes sense....

I beg to differ that it is a bug.. If you try with the same configuration but without any BOM and SET then it will work definitely..

--> Yes I know that. I have problem only with Set. I think it should work with a set also as from the delivery order, the real product "disappears" and you have to deliver each component separately to your customer. 

I hope you will rethink about this... 

Thanks in advance,

**Comment by Yenthe666** [comment]
Hi @chrisdec,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
