### ISSUE TITLE
Problem with language selection on website

### ISSUE THREAD

**Issue by bojkic** [odoo/odoo#84153]
Impacted versions: 15

Steps to reproduce: Install Serbian (Cyrillic), set it as default for website. English US is the other language.
GO to website from browser set to Serbian, it opens Serbian homepage and everything works.
GO to website from browser set to English, it opens English homepage, however when you click in laguage selector to change to Serbian (on hover I see it links to "/" - homepage) it opens "/en" again.  You can manually change to Serbian by entering /sr at the end of URL.

test example: fondacijabijeljina.com

solution?

**Comment by rdeodoo** [comment]
Hello,

The URL you see on hover is actually not the one used.
```html
<a href="/" class="dropdown-item js_change_lang active" data-url_code="sr">
    <span>srpski</span>
</a>
```
It won't redirect to `/` directly.
The click on the language switcher is intercepted and redirected to another route `/website/lang/xxx` where xxx is the lang code of the `data-url_code` attribute, `sr` in this case.

I tried on your website and could change lang as it is supposed to be.

Could you confirm you face an issue?

**Comment by bojkic** [comment]
I have fixed by adding /sr manualy to the language switcher ... 

however, now I have a problem that website homepage defults to english (adds /en) even though serbian is set to defult language for the website and even is the browser languge is serbian. 

fondacijabijeljina.com

**Comment by rdeodoo** [comment]
> I have fixed by adding /sr manualy to the language switcher ...

Why? As I explained, the language switcher `href` is irrelevant, the navigation/redirection will be done in javascript based on the data-attribute set on the element.

> I tried on your website and could change lang as it is supposed to be.
Could you confirm you face an issue?

:point_up: 
Could you please revert your change and keep the odoo original code and record a video of the problem you face on your website?
I couldn't reproduced the issue back then, and the change you did is wrong.

**Comment by bojkic** [comment]
OK, I have reverted the changes. And language selection works. ;)

However,  I still have a problem that website homepage(www.fondacijabijeljina.com) defaults to english (adds /en) eventhough serbian is set as default language for the website and eventhough  the browsers languge is serbian. here is the clip where I open the website in Crhome that is in Serbian, but it still opens /en version of the website:
https://user-images.githubusercontent.com/8396767/176673846-03f9a1d4-a640-4279-8fe2-7b3309c7fcbb.mp4

Is there a way to change this behavior, or to set somehow the default languge to be serbian no matter which is the languge of the browser? thanks!

**Comment by bojkic** [comment]
> My guess here is that you already have a language cookie set in your browser. In you video you are already logged in, meaning you already have a language cookie which will force the language to that value unless you select another language (which will change the cookie value).
> 
> Can you try in incognito windows? Or clean your cookies, you can do that easily with [EditThisCookie](https://chrome.google.com/webstore/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg?hl=fr) chrome plugin. Once installed, just click on it and on the trash icon top left.

Unfortunately it is not a cookie problem, I have tried both deleting cookies and incognito mode. I am not sure how to troubleshoot this.

here is what redirects look like: [https://wheregoes.com/trace/20223396355/](https://wheregoes.com/trace/20223396355/)

thank you for all the help!!! if there is a way to enforce first language until other language is selected, that would help. if not, we can close this issue

**Comment by rdeodoo** [comment]
You should not trust 100% what such redirect checker are reporting.

We already had issues for instance with https://www.redirect-checker.org/index.php and it took some times figuring what was wrong with a customer website but it was in fact that redirect checker which was simply not allowing cookies, ultimately not testing real use cases. Without cookies, nothing behaves as expected obviously.

We also had issue with another one which was recognized as a bot by our code (we have special heuristic/check for that), leading to incorrect behavior but again, nothing was wrong.

About your case, it seems to have redirection from `https` to `http`. It shouldn't be the case, maybe it is the first thing to fix. What is the domain you set on your website settings screen? Is the scheme `https`?

**Comment by bojkic** [comment]
yes, it is https. in website settings and in system parameters.

**Comment by rdeodoo** [comment]
Your database seems to be self hosted, right?
You probably have something doing that redirection somewhere in your configuration, nginx, htaccess.
I don't think there is something in Odoo that would redirect from https to http if you have correctly configured your website domain with https

**Comment by rdeodoo** [comment]
I'd be happy to help here but there isn't much to investigate here.
If you can reproduce the error on the runbot (maybe try to set up a runbot with the same configuration as your DB) that's will definitely be enough for us to be able to track down the issue.
