### ISSUE TITLE
[8.0] mail.thread.message_new/update useless ?

### ISSUE THREAD

**Issue by yannprada** [odoo/odoo#8416]
Hello !

According to the source code at https://github.com/odoo/odoo/blob/8.0/addons/mail/mail_thread.py#L71:
```
        Inheriting classes are not required to implement any method, as the
        default implementation will work for any model. However it is common
        to override at least the ``message_new`` and ``message_update``
        methods (calling ``super``) to add model-specific behavior at
        creation and update of a thread when processing incoming emails.
```
one may override message_new and message_update to add custom content of messages.

**Test code**
```python
def message_new(self, cr, uid, msg, custom_values=None, context=None):
    _logger.info("________________________MESSAGE_NEW________________________")
    _logger.info(msg)
    _logger.info(custom_values)
    _logger.info(context)
    
    return super(Foo, self).message_new(cr, uid, msg, custom_values=custom_values, context=context)

def message_update(self, cr, uid, ids, msg, update_vals=None, context=None):
    _logger.info("________________________MESSAGE_UPDATE________________________")
    _logger.info(msg)
    _logger.info(update_vals)
    _logger.info(context)
    
    return super(Foo, self).message_update(cr, uid, ids, msg, update_vals=update_vals, context=context)
```

**Steps to reproduce**
1. Make a custom object in a custom module.
2. Make this object inherit from mail.thread.
3. Add _track and mail.message.subtypes, so that a mail will be sent when field x changes.
4. Make a test by changing field x once.
5. Override the methods like described in the **Test code** section above.
6. Make another test by changing field x, exactly like before (create another record to be sure).
7. Compare the server logs.

**Current behavior**
Nothing special in the log file.

**Expected behavior**
We should see in the log file the lines we tried to write within the overrode functions.

**Conclusions**
Is the functions called at all ? I even tried to delete the super call at the end of the functions. The same happened (which means nothing).

Thanks for your time !

(@KangOl maybe you can help me with this ?)

**Comment by tde-banana-odoo** [comment]
That's for incoming emails, not outgoing emails. Those methods are called when you set up the incoming email gateway. For example you can setup an alias on a project to create tasks. For each incoming email on this alias, message_new will be called.

**Comment by yannprada** [comment]
I understand, thanks for the clarification.
