### ISSUE TITLE
Lithuanian translations not synced

### ISSUE THREAD

**Issue by andrius-preimantas** [odoo/odoo#8423]
Translations appear on transifex (https://www.transifex.com/odoo/odoo-8/translate/#lt/sale_margin/49580628) but not on git repo (https://github.com/odoo/odoo/tree/8.0/addons/sale_margin/i18n)

The same goes for other modules (report, account_anglo_saxon, etc.)

**Comment by andrius-preimantas** [comment]
There are more issues like that: https://github.com/odoo/odoo/issues/8363

Do you update translations from transifex manually?

Cheers
Andrius

**Comment by mart-e** [comment]
Hello,

The translations are synchronised weekly but apparently it missed some. I am investigating to find what's wrong in my script

**Comment by andrius-preimantas** [comment]
Thank you Martin

Cheers
Andrius
