### ISSUE TITLE
[8.0] Sending e-mail fails

### ISSUE THREAD

**Issue by fuggii** [odoo/odoo#8426]
Hi,
I get an error response from SMTP server when trying to send an e-mail (e.g. password reset e-mail). It might be a result of the "postmaster" prefix added by Odoo to the sender address.
## Steps to reproduce
1. Install Odoo v8.
2. Set up outgoing mail server correctly.
3. Create a user account.
4. Click on "send reset password instructions".
## Result
- on the Odoo side:

> Mail Delivery Failed
> Mail delivery failed via SMTP server 'mail.server.tld'.
> SMTPDataError: 550
> 5.7.1 Client does not have permissions to send as this sender
- on the MS Exchange side:

> 'SMTP has rejected a (P1)-e-mail from "postmaster-odoo@[domain]" using the connector "SMTP internal", and the user has authentified himself as "[AD-DOMAIN]\ODOO". The Active Directory lookup for the sender address returned a validation error. Microsoft.Exchange.Data.ProviderError'
> (translated from German)
## Solution

How could this issue be avoided, namely adding the "postmaster" prefix be suppressed?

**Comment by danimaribeiro** [comment]
Go to "System Parameters" in the technical configuration and remove the catchall parameter.
Or you have to configure your mail server properly:
https://www.odoo.com/forum/help-1/question/how-to-set-up-e-mail-messaging-with-odoo-61796

**Comment by fuggii** [comment]
Hello danimaribeiro,
thank you for your quick answer!

> Go to "System Parameters" in the technical configuration and remove the catchall parameter.

Do I have to remove both catchall parameters (mail.catchall.domain and mail.catchall.alias) or only mail.catchall.alias?

> Or you have to configure your mail server properly:
> https://www.odoo.com/forum/help-1/question/how-to-set-up-e-mail-messaging-with-odoo-61796

Unfortunately, it seems this does not comply with our company policy. Neither is Odoo supposed to handle all incoming e-mail (particularly not via an catchall address) nor does every employee have (nor will get) access to Odoo.

BTW: Is there a way to have Odoo using dynamic authentication parameters (e.g. [AD-DOMAIN]\\[[user.name]] and [[user.password]]) to send outgoing e-mails? That would resolve this issue instantly.

**Comment by ddfs** [comment]
@fuggii "Is there a way to have Odoo using dynamic authentication parameters (e.g. [AD-DOMAIN]\[[user.name]] and [[user.password]]) to send outgoing e-mails? That would resolve this issue instantly."

you can do this but it requires some changes in base/ir/mail_server.py. we have already configured to run it that way. only one master account to send and all employee emails associated with user accounts.

**Comment by danimaribeiro** [comment]
You have to delete both.
I develop this module: https://github.com/Trust-Code/trust-addons/tree/8.0/trust_mail
Then I configure for each user one outgoing server, the module get the user's email and find the appropriated outgoing server configuration.

**Comment by fuggii** [comment]
@ddfs, @danimaribeiro:
Thank you both for your quick answers! I will try at least one of these possible solutions as soon as I can and post the results here.

**Comment by fuggii** [comment]
@ddfs:
Alternatively, I may use the user's e-mail as Reply-To address for all outgoing mail. However, I reckon Odoo does neither offer such an option, but I would have to adapt the base/ir/mail_server.py as well. Right?

**Comment by ddfs** [comment]
@fuggii  yes, you are right.

**Comment by Yenthe666** [comment]
Hi @fuggii ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: to me this looks like an implementation issue though.

Regards,
Yenthe
