### ISSUE TITLE
hr_holidays with google_calendar: Time Off event created by manager instead of employee

### ISSUE THREAD

**Issue by SimoneVagile** [odoo/odoo#84326]
Impacted versions: 14.0

Steps to reproduce:
- Install modules `hr_holidays` and `google_calendar`;
- Log into Odoo with two different users, one manager and one employee (subordinated): f.e. Admin e Demo;
- Set Google Client ID and Google Secret with a OAuth2.0 -> see [tutorial](https://www.odoo.com/documentation/14.0/applications/general/calendars/google/google_calendar_credentials.html);
- check if in Odoo's Calendar the `Synched with Google` tag compares on the right (with manager);
- from employee user, go to Time Off -> My Time Off -> My Time Off Requests and Create with a date;
- from manager user, go to Time Off -> Managers -> Time Off and accept the time off created;
- go to manager's Google Calendar.

Current behavior:
Google event is created and visible for manager, employee has an event since is an attendee of the first.

Expected behavior:
Google event is created and visible for employee, manager is not involved.

Video/Screenshot link (optional):
![91236](https://user-images.githubusercontent.com/62010767/153414105-c4fe861c-9cc2-40b1-a573-ad261d0f72ef.png)

Support ticket number submitted via odoo.com/help (optional): #2761158

**Comment by vava-odoo** [comment]
Solved with https://github.com/odoo/odoo/pull/88124
