### ISSUE TITLE
error repeat header table in qweb report

### ISSUE THREAD

**Issue by Anhlq87** [odoo/odoo#8439]
Hi guys

I print sale orders report in root sale module. I enter many product to it split 2 page. In the page 2 it show not good. Everybody help me solve it. please see bellow image:
![error](https://cloud.githubusercontent.com/assets/9975164/9752731/e4cd7828-56dd-11e5-9eb9-8e12defee40c.png)

**Comment by danimaribeiro** [comment]
Use version 0.12.1 of wkhtmltopdf.

**Comment by Anhlq87** [comment]
Thank danimaribeiro. But now I'm using ver 0.12.2.4. it's new version. I have been use 0.12.1 but It cannot print.

**Comment by danimaribeiro** [comment]
The correct version to use is 0.12.1.
Change it back, and then send the error you get when trying to print.

**Comment by sle-odoo** [comment]
Hi,
This issue doesn't appear with the 0.12.1 release.
