### ISSUE TITLE
[15.0] MAIL: Not visible the lognote message in the channel when mentioning it on a Sale Order

### ISSUE THREAD

**Issue by vmaxadmin** [odoo/odoo#84399]
Impacted versions: 15.0

Steps to reproduce:
- Create a new channel: **CHANNEL TEST**
- Enter any Sale Order, leave a internal lognote message and mention the above channel
- Enter **Discuss > #CHANNEL TEST**
- It is not visible this message on Sale Order

Current behavior:
- Not visible the message in **Discuss > #CHANNEL TEST**

Expected behavior:
- Must be visible the message when entering to Discuss Channel

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by vmaxadmin** [comment]
@Feyensv Have you checked this issue? I still have not found why. Thank you.

**Comment by tde-banana-odoo** [comment]
Hello,

I don't remember all usage of channels, ping, ... but at first sight I would say that propagating notes to external records is probably a bad idea. Notes are meant to be internal while channels easily leak messages to a lot of people.

cc @seb-odoo who probably knows better the current behavior of channels on that point

**Comment by seb-odoo** [comment]
Hello, indeed same message existing in multiple places is no longer supported. Mentions are used to create a quick link to the channel, not to post messages on it.
