### ISSUE TITLE
Could not execute command lessc when you don't have blog installed

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#8440]
**Lessc issues when not having blog module installed**

Impacted versions:

 - 9.0

Steps to reproduce:

 1. Install a new Odoo
 2. Create a new database
 3. Install any module that is not related to website/blog
 4. You will now get the error "Could not execute command 'lessc'"
 5. Now install the blog module => The error is gone.

Current behavior:

 - The Odoo will not be fully layouted and has some flaws. At the top of the Odoo you will get a message saying that it cannot execute command lessc. "Could not execute command 'lessc'"

Expected behavior:

 - Lessc is succesfully used and executed without the blog module installed.

**Comment by Yenthe666** [comment]
@odony and @antonylesuisse this issue is present in the very last version of 9.0. Guess this would be great to have fixed before it goes public.

**Comment by xmo-odoo** [comment]
I can not reproduce step 5. If the `lessc` command (which is necessary) can't be found, the error is displayed (and styling is broken) whether `website_blog` is installed or not, as it should.

**Comment by Yenthe666** [comment]
@xmo-odoo other people with this issue can be found here too: https://www.odoo.com/nl_NL/forum/help-1/question/what-does-this-error-mean-on-odoo-could-not-execute-command-lessc-60439

I've installed a second Odoo 9 and the issues do not happen anymore. I don't have to install the blog module here. So I assume that this only happens when you don't have an Odoo 9 yet and that you don't have less installed yet. If you then install a new Odoo and start it up it can't find less if you install it afterwards. A simple reboot would probably fix this too.
So I guess you can close this. Could you also give me an ETA on when the Odoo 9.0 datamodel will be locked?

**Comment by xmo-odoo** [comment]
> Could you also give me an ETA on when the Odoo 9.0 datamodel will be locked?

IIRC in theory it is locked (/cc @odony you confirm?)

**Comment by Yenthe666** [comment]
Olivier has just confirmed on Twitter that it is locked :+1 Thanks guys!

**Comment by lukebranch** [comment]
@xmo-odoo @Yenthe666 ,

I have this issue with the latest version of the 9.0 branch as of:

https://github.com/odoo/odoo/commit/bfed8706bb96967a6fd22b6713699a83be706902

it seems to be an issue on the runbots as well.

**Comment by Yenthe666** [comment]
@lukebranch interesting. I'm not sure what the issue is though, I only seem to get it once on a clean system with the first Odoo I install.

**Comment by lukebranch** [comment]
@Yenthe666 ,

I've dropped and recreated a new database and the issue seems to be gone, i'll try running a complete re-install on a clean dev system at some point next week and see if I can reproduce the issue again.
