### ISSUE TITLE
No translation updates from transifex

### ISSUE THREAD

**Issue by SplashS** [odoo/odoo#84455]
Impacted versions: 15.0

Steps to reproduce: Go to commits history of Odoo 15.0 branch on GitHub.

Current behavior: No "[I18N] Update translation terms from Transifex" commits for last month.

Expected behavior: "[I18N] Update translation terms from Transifex" commit each week.

**Comment by SplashS** [comment]
ping @mart-e 
as I know you are in charge of translations

**Comment by mart-e** [comment]
Hi,

Indeed, the sync was blocked since a few weeks.
I have made a manual synchronisation at 1577ee3744eda3e4974715216c6d6b2ac04c3272
Let me know if there is still issues in the future.
Best,
