### ISSUE TITLE
odoo-bin missing when installing with pip

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#84506]
Impacted versions: 13-15

Steps to reproduce:

```sh
git clone https://github.com/odoo/odoo.git -b 15.0 --depth=1
pip install -e ./odoo
odoo-bin --version
```

Current behavior:

    bash: odoo-bin: command not found

Expected behavior:

    Odoo Server 15.0

Workaround: use `odoo` instead of `odoo-bin`, but I don't understand why, if [`odoo-bin` has been documented as odoo CLI since years ago](https://www.odoo.com/documentation/13.0/developer/misc/other/cmdline.html).

Not sure if related to #16700

**Comment by Parselon** [comment]
I had solved this locally by adding `odoo-bin` to the `scripts` section in `setup.py`
If this solution is enough, maybe I can create the PR.

**Comment by Yajo** [comment]
Please!

**Comment by Yajo** [comment]
Fixed in the docs instead, thus making the non-existence of the `odoo-bin` binary expected and documented. See https://github.com/odoo/odoo/pull/85878.
