### ISSUE TITLE
Advanced Search bar is mixed with search buttons in Odoo

### ISSUE THREAD

**Issue by janetrp** [odoo/odoo#8462]
In Odoo the Search Buttons overlap the Searching bar

![2015-09-09 18_33_00-mass mailings - odoo](https://cloud.githubusercontent.com/assets/13853118/9768043/8b5c99d8-5721-11e5-9980-3061adb41509.png)

It's really unconfortable when you try to edit the searching

![2015-09-09 18_38_37-mass mailings - odoo](https://cloud.githubusercontent.com/assets/13853118/9768183/53e2041a-5722-11e5-89d5-b7b95c1eea81.png)

Could you pls help?

Thanks

**Comment by janetrp** [comment]
Just checked this happens only in Firefox, in Chrome is not happening

**Comment by nle-odoo** [comment]
Hello,

It should be solved with commit 1fe932a7b in 8.0, thanks for reporting the issue.
