### ISSUE TITLE
Opt_out= False, filter by default in Mass Mailing Utility

### ISSUE THREAD

**Issue by janetrp** [odoo/odoo#8463]
Hi

Is it possible to include the filter "Available for mass mailing" by default (not editable) in the selections of the records when we use the mass mailing utility?
If this option is not selected by default it's really easy to break the rule, sending emails to customer with opt-out active
![2015-09-09 18_46_57-mass mailings - odoo](https://cloud.githubusercontent.com/assets/13853118/9768366/77673da0-5723-11e5-8e36-9561f271793e.png)

In mailing lists it is available by default
![2015-09-09 18_58_58-recipients - odoo](https://cloud.githubusercontent.com/assets/13853118/9768602/092d3856-5725-11e5-8c99-088cc0623be0.png)

Thx

Janet

**Comment by rafaelbn** [comment]
@janetrp @mart-e could you close this issue? It is fixed here: https://github.com/odoo/odoo/pull/8830
Thanks!

**Comment by mart-e** [comment]
@rafaelbn sure, merged at 90968dec1ca0e47c863884060274f1088714ca6c
(will automatically be closed once forward ported to 9.0)
