### ISSUE TITLE
[Master] 05.09.2015 empty #web Screen after debug mode

### ISSUE THREAD

**Issue by explanar** [odoo/odoo#8464]
At the Master-branch 05.09.15 (Ubuntu 14.04 minimal, ESC/POS Hardware Drivers, POS_restaurant) i changed some non-critical html-Code by activating debug-mode and changing some web.view.

After that, the Screen of odoo stays empty (see attached screenshot) and you can only see content by changing the URL to debug mode ```ip_address:8069/web?debug```.
![empty screen without debug-mode](https://cloud.githubusercontent.com/assets/840301/9769757/57cf9998-572c-11e5-907b-3a55896c1591.png)

**Comment by explanar** [comment]
Just realized that it could be caused by localizations unequal to EN(US):
With users that have language-setting EN(US) the problem doesn't occur that often.

**Comment by mart-e** [comment]
@explanar we have had issues with assets bundle lately causing this kind of issues. Moreover, the master branch is unstable and not supported (no need to report issues for this version). Instead, I advise you to check [the 9.0 branch](https://github.com/odoo/odoo/tree/9.0/)
