### ISSUE TITLE
Javascript errors prevent creating or editing events. UPDATED

### ISSUE THREAD

**Issue by rowemoore** [odoo/odoo#8465]
## Impacted versions:

 - 9.0

### Steps to reproduce:
When either creating or editing an event an js error is thrown. It doesn't matter which view is used to access the form.  I have tested on a local dev running windows 7 and on the runbot.  On the runbot I have tested with both windows 7 and 10 using chrome, firefox and ie.
 
### A new event:

`Uncaught Error: QWeb2 - template['FieldMany2ManyTag']: Runtime Error: TypeError: Cannot read property 'constructor' of undefined
http://100474-9-0-bfed87.runbot7.odoo.com/web/content/332-00e6051/web.assets_common.js:2444`
`Traceback:
Error: QWeb2 - template['FieldMany2ManyTag']: Runtime Error: TypeError: Cannot read property 'constructor' of undefined`

### Existing event edit:

`TypeError: cur is undefined`
`http://100474-9-0-bfed87.runbot7.odoo.com/web/static/lib/qweb/qweb2.js:163
Traceback:
QWeb2.tools.foreach@http://100474-9-0-bfed87.runbot7.odoo.com/web/static/lib/qweb/qweb2.js:163:1`
`Traceback:
QWeb2.tools.foreach@http://100474-9-0-bfed87.runbot7.odoo.com/web/static/lib/qweb/qweb2.js:163:1
anonymous@http://100474-9-0-bfed87.runbot7.odoo.com/web/static/lib/qweb/qweb2.js line 404 > Function:9:2`

**Comment by rowemoore** [comment]
So it seems this error was created some fixes performed on the web module.  Changes to  form_relational_widgets.js and list-editable.js seem to be causing this error.

**Comment by rowemoore** [comment]
Fixed.

**Comment by FernandoAzuaje** [comment]
Hi. I have the same error. and I wonder what happens if you do another change in other modules , as do billing . I can make a rollback without loss of data or need to do one more thing ?

Thanks in advance. Fernando Azuaje

**Comment by rowemoore** [comment]
If you've updated your source since I closed this, you are probably having a different problem.  Of course, when you update source code you need to run an update on the db  (-u all from the command line.)

I haven't had this issue since I closed this.

**Comment by capricornius** [comment]
how to run the command -u all in my odoo.

**Comment by FernandoAzuaje** [comment]
I resolved my problem!. the problem begin when I deleted a tax id in (accounting config/tax id) ( I deleted the number 1,2 and 3) and later created 3 more (4,5 and 6) . Well the system apparently  need the 1,2 and 3 ID. so I solved the problem by editing the data base changing the id number of my newest taxes (4,5 and 6)  for 1,2 and 3. and the problem was solved.

**Comment by ferluk** [comment]
You are absolutely right @FernandoAzuaje

**Comment by adnanalali** [comment]
@FernandoAzuaje How can you solve that? how to access the DB?
