### ISSUE TITLE
[9.0] Sale order line form display is ugly

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#8469]
when we create a quotation for sale order,
and create a sale order line, the display is ugly as there's lot of unnecessary space.

![odootest1](https://cloud.githubusercontent.com/assets/7590534/9784374/58b4d254-57dd-11e5-94bb-21513338f24b.JPG)

**Comment by Yenthe666** [comment]
This has been fixed in the meanwhile. 😉 
![image](https://user-images.githubusercontent.com/6352350/34410899-95f43740-ebd3-11e7-9d55-0a91b8044eb2.png)
