### ISSUE TITLE
manufacturing planning and working time

### ISSUE THREAD

**Issue by gzampeze** [odoo/odoo#847]
Working time of ressource seem not use in order planning.
I don't know if  it is a mistake.

In manufacturing i create  a bill of materials with  : 
 1) 2 products (provide each in 5 days)
 2) a routing  who have only 1 operation (1hour) with workcenter type ressource human have a working time 35h/week (8h-12h 14h-17h)

I order 1 product at 13h 

In order planning MO was at 13h + 5 day  not in range of working time

**Comment by Yenthe666** [comment]
Dear @gzampeze ,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
