### ISSUE TITLE
[9.0] Channel in Chat apps need show the topic and purpose of the channel

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#8472]
Hi Odoo,

On chat Apps, I see that you allready improved a lot which is great!
But I hope you add the additional information as I think this is the most important on hat apps.
When we have discussion in channel, there's no information about topic and purpose.
I think its important to have this information as we can know what should we talk and the purpose of the channel that we joined.

![odootest2](https://cloud.githubusercontent.com/assets/7590534/9784636/eb7b63ae-57de-11e5-81ae-52769667f100.JPG)

**Comment by pedrobaeza** [comment]
@mart-e is there any roadmap for this?

**Comment by mart-e** [comment]
After almost 3 years, we still did not considered it as needed so no, sorry
