### ISSUE TITLE
[9.0] BoM structure doesnt show the quantity information

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#8473]
Hi Odoo,

I see that on BoM tree we have the information of quantity, but we dont have it on BoM structure.
Its important to have this information on BoM structure. I talked with Odoo support as I have Odoo enterprise and they cannot fixed it as it already stable in version 8, but still in version 9 you still not fixed this.

![odoobom1](https://cloud.githubusercontent.com/assets/7590534/9784664/2f67c350-57df-11e5-90de-92359ff8600b.JPG)

**Comment by pedrobaeza** [comment]
That view was conflicting and now it has been removed in latest version, the same as the foundation for it in v11: hierarchy mode view, so this issue has no more meaning.

The good news are that I think something new is being prepared a new BoM structure view, but I can't find right now the reference.
