### ISSUE TITLE
[9.0] Serial Number wizard doesnt exist anymore on picking

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#8474]
Hi Odoo,

Right now I want to test the serial number feature, but I can't find the serial number button/wizard anymore on picking,

![odootest4](https://cloud.githubusercontent.com/assets/7590534/9784696/723ecaf2-57df-11e5-921b-9d3af4cba9fb.JPG)

Is it a bug? or did I missed something?
Thank You.

**Comment by Whisno** [comment]
Did you : 
- Activate "Track lots or serial numbers" in Inventory settings
- Enable tracking by unique serial number on the product 
?

**Comment by falinwa** [comment]
I have activate track lots or serial number, but I don't configure the product.
When I configure it, it solved the problem.

So on version 9, we need to make configuration on the product to have the serial number

Thanks.
