### ISSUE TITLE
ir.attachment search by res_models returns nothing

### ISSUE THREAD

**Issue by drkpkg** [odoo/odoo#84801]
When I need to search an attachment of hr.applicant cannot find it, and the field get only the bytes.

![image](https://user-images.githubusercontent.com/972555/154484183-112ecdfa-7228-4864-96dc-08fa82a68495.png)

I know is a custom module but I think the normal behavior should be return the base64 attachment to process. Searching directly into ir.attachment return nothing too.

Impacted versions: V14

Steps to reproduce: 

`
self.env['ir.attachment'].search(['res_model', '=', 'hr.applicant'])
`

Current behavior:

![image](https://user-images.githubusercontent.com/972555/154483686-58e85c65-a114-485e-bd02-90d2ee06955b.png)

Expected behavior:

![image](https://user-images.githubusercontent.com/972555/154483938-66503666-f6be-44e9-824d-f17158e24536.png)

Should return this I think?

If somebody answer me this I'll be happy because I don't understand well what's the behavior in ir.attachment.

**Comment by LJared** [comment]
Hello, did you find a solution? 
This issue is also in V13.

**Comment by niyasraphy** [comment]
@LJared @drkpkg ,
the search method is modified in the base/models/ir_attachment.py file for some reasons, you can bypass this by using the sql query to get the desired result.(make sure, about the security)

thanks

**Comment by drkpkg** [comment]
As a note, ir.attachment model has a method generate_access_token(), you can pass it via url with the generated token and get access.

You can iterate the ids list, this is my actual approach, I'm no longer using Odoo website builder, I pass all my frontend development to Angular js.

```python
# generate tokens for my attachments
for attachment in self.attachment_ids:
    attachment.generate_access_token()
```
With that you will have access external url:
```
ODOO_URL:PORT/web/content/ID/?download=true&access_token=ATTACHMENT_TOKEN
```

Also, I write a method to get the a list of attachments if someone can find it useful.

```python
class IrAttachment(models.Model):
    _inherit = 'ir.attachment'

    @api.model
    def search_by_ids(self, ids: list, fields=None):
        """
        Search by ids.

        :param ids: list of ids
        :param fields: list of fields
        :return: list of records
        """
        if fields is None:
            fields = ["id", "name"]
        try:
            res = self.browse(ids).read(fields)
            return res
        except Exception as e:
            _logger.error(e)
            raise e
```
