### ISSUE TITLE
[9.0] GUI mess on fresh install

### ISSUE THREAD

**Issue by lem8r** [odoo/odoo#8488]
Just installed odoo from 9.0 branch with fresh database.
Here is what It looks like after login

![odoo9](https://cloud.githubusercontent.com/assets/5942291/9790491/08232532-57df-11e5-94eb-a8c8a7b72392.jpeg)

**Comment by rowemoore** [comment]
What browsers are you using?   Also, you may need to install node-less.

**Comment by lem8r** [comment]
I was getting same results with FF and Chrome.
Thanks, I will try to install node-less

**Comment by lem8r** [comment]
Nope, node-less did not helped.
Checked server logs, there are no errors.

Btw, I'm wondered why Odoo 9 looks like Odoo 8 with new icons.
Odoo 9 on runbot looks completely different.
http://runbot.odoo.com/runbot/7/master

**Comment by sle-odoo** [comment]
you **need** node-less. i'm going to push rev 2185149aa3ff102b5e8bb09200cfd984201cf654 today.

Be sure to create a new database so you won't have any lingering wrongly compiled assets (I assume that you don't have errors in your log because of that).

**Comment by lem8r** [comment]
Thanks @sle-odoo  after installing node-less and creating new database I've got error of missing package `clean-css`.
`npm install clean-css` solved this issue.
So I think you can add this to requirements too.
