### ISSUE TITLE
[9.0] Livechat issue while logon with other user than admin

### ISSUE THREAD

**Issue by loslolos** [odoo/odoo#8491]
While login into odoo with different user than admin he gets this error:

```
 raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'mail.channel_ids.livechat_channel_id' in leaf "<osv.ExtendedLeaf: ('mail.channel_ids.livechat_channel_id', '!=', None) on mail_message (ctx: )>"
```

Odoo is unusable at all for this user until livechat modul is uninstalled.

**Comment by Yenthe666** [comment]
Hi @loslolos,

Thanks a lot for your report.
I was no longer able to reproduce this and the issue should have been fixed in the meanwhile! Please update your local Odoo instance in order to fix this.
