### ISSUE TITLE
Document Management Problem

### ISSUE THREAD

**Issue by meswapnilwagh** [odoo/odoo#8493]
I found that attachments do not get correctly automatically linked to the correct directory, which basically makes it impossible to see a list of attachments documents. I I attach a document to product and if I go to 
 'Knowladge' -> 'Directory Structure' -> 'Products' is shows nothing there.

**Comment by rowemoore** [comment]
What release and operating system?

**Comment by spadae22** [comment]
Look for them at Settings/Database Structure/Attachments. You can search, delete, etc. Just cleaned up myself. Not sure why nothing is listed under the Knowledge Menu.

**Comment by meswapnilwagh** [comment]
@rowemoore I am facing this problem in Odoo V8 on Ubuntu 14.04, 
@spadae22 Yes we can see all attachment there but it shows all attachments from database. What Document Management do it shows you the attachment related to model and filer it out accordingly the domain mention in document directory but that not work.
Ideally what should happen when we upload and attachment it should assign the respective directory to that attachment then it will be populated under the directory that is what missing in Document management.

**Comment by spadae22** [comment]
I agree as I see the same as you in 14.04. 
Check this https://www.odoo.com/es_ES/forum/help-1/question/help-with-attachments-and-document-management-68828

But I just use the filters to clean up to keep the DB manageable.

**Comment by meswapnilwagh** [comment]
@spadae22 Sorry but it is not helpful, still stuck there.

**Comment by Bric91** [comment]
Same problem.
in folders can only find the generated ones and not the attached

**Comment by Yenthe666** [comment]
Hi @meswapnilwagh,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
