### ISSUE TITLE
[9.0] Procurement MTO-BUY no option to always create new rfq

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#8498]
Hi Odoo,

in version 7, the procurement behavior when when have MTO-BUY on the product,
when we confirmed sale order for this product, the system always created a new RFQ,
but on version 8, you changed it to be merged if we have a rfq that have same supplier.

I complained about this last year, but because you said the system is already stable there's nothing can be change.

I think you must have possibility to choose how we created it, by merging(behavior version 8), or always created new(behavior version 7)

Thank You.

**Comment by lem8r** [comment]
Are you talking about 8.0 or 9.0?
In 8.0 procurement made as soon as possible so RFQs are merged.
In 9.0 there is option to make procurement on due date, so RFQ can be as late as possible or in between.

**Comment by falinwa** [comment]
I am talking about the behavior of version 7 to be made to version 9.
On version 7, when we make a RFQ, it always created a new one, not merged like right now.

Since version 8, Odoo remove this behavior as they change it to always merged.
It should be an option to have posibility to have behavior for version 7.

**Comment by lem8r** [comment]
It is in 9

2015-09-14 10:17 GMT+03:00 falinwa 1 <notifications@github.com>:

**Comment by falinwa** [comment]
ok, maybe my mistake,
but can you explain me how?
as before I tested, on the product , we just have option draft purchase order and call for tenders.

and the behavior of draft purchase order is like in version 8,
and for call bid instead created rfq it created purchase requisition

**Comment by lem8r** [comment]
On SO, there is Requested Date field (other info tab)
When it is filled manually, it sets order point date so procurement is done
for that date and PO with be separate.
Otherwise procurement is done as soon as possible, so PO is merged with
most recent PO if any.

2015-09-14 10:31 GMT+03:00 falinwa 1 <notifications@github.com>:

**Comment by falinwa** [comment]
Hi lem8r,

Yes I see the request date field on sale order form,
and the explanation only said about the delivery order not procurement.

but when I am test it on runbot, I don't get the expected behavior.

**Comment by sle-odoo** [comment]
Hi,
If you propagate the procurement group by editing the procurement rule buy, you should get this behaviour (always a new one).

Regards
