### ISSUE TITLE
Istallation Error  with Oemedical v7

### ISSUE THREAD

**Issue by sandaly** [odoo/odoo#8507]
Hello
last time i had try to install Oemedical v7 on Odoo v7 and i got this Error: ValidateError  Error occurred while validating the field(s) arch: Invalid XML for View Architecture!

Someone can help pls???????????

**Comment by yvaucher** [comment]
@sandaly oemedical project is there:
https://github.com/OCA/vertical-medical

Not all modules have been ported in 7.0 and currently some people are focusing on making it work on the 8.0 version.

Please open an issue there and explain which module you tried to install: https://github.com/OCA/vertical-medical/issues

**Comment by sandaly** [comment]
thank you i try it right now
