### ISSUE TITLE
client error on IE: Assignment to read-only properties is not allowed in strict mode 

### ISSUE THREAD

**Issue by SuneBahn** [odoo/odoo#8516]
When running Odoo 9.0 from git:

1. install project
2. open a client connection from IE
3. click on Project>Projects and click on a project

Expected:
The project is shown

Actual:
client error: Assignment to read-only properties is not allowed in strict mode .... at web.assets_common.js

This only happens on IE, not on Chrome.

**Comment by sle-odoo** [comment]
hi,
which version of IE?

**Comment by SuneBahn** [comment]
IE 11.
I have tried it both on windows phone (8.1), Windows surface RT, and a laptop running Win8.1, all with the same result.

**Comment by rgeleta** [comment]
Same problem, also IE 11.
Note: On different project, issue
https://github.com/angular/material/issues/3943
was similar, has been resolved

**Comment by auditum** [comment]
Does anybody have a quick fix for this issue? The Odoo 9 Community edition currently cannot be used by IE 11 users! Is this issue fixed in the enterprise version?

**Comment by auditum** [comment]
Fix:

in File: addons/web/static/src/js/framework/mixins.js
change _trigger_up at line 279 to
```javascript
_trigger_up: function(event) {
        this.__edispatcherEvents.trigger(event.name, event);
        var parent = this.getParent();
        if (!event.is_stopped() && (parent)) {
            parent._trigger_up(event);
        }
    }
```

**Comment by nle-odoo** [comment]
Hello thanks for reporting and investigating, it should be fixed in f5bd1cc which has the same effect than your fix.

> Is this issue fixed in the enterprise version?

It was fixed but was part of a very big commit so that this small line was also needed in community was overlooked.

**Comment by sjatkins** [comment]
Is this a general fix or for this specific project.  Many people hit this error and mentioning what the general problem is and how to generally handle it would help many.  Thanks for considering it.

**Comment by nle-odoo** [comment]
@sjatkins the fix I spoke above is a fix for this particular issue.

the issue could happen to any project and was that we used a variable without declaring it (by doing `var my_variable;` before using) which when the javascript code is set as [strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode) caused this error.
