### ISSUE TITLE
[15.0] Inventory reference does not change after doing inventory adjustment

### ISSUE THREAD

**Issue by moiztex** [odoo/odoo#85183]
Impacted versions:15.0

Steps to reproduce: Create inventory adjustment then batch apply then set inventory reference then apply. inventory reference does not change.

Current behavior:

Expected behavior: Inventory reference set according to inventory adjustment

Video/Screenshot link (optional):

https://user-images.githubusercontent.com/89173587/155260342-b28a0c11-da3f-4f28-8c89-1e52967b6949.mp4

Support ticket number submitted via odoo.com/help (optional):

**Comment by ticodoo** [comment]
Fixed with https://github.com/odoo/odoo/pull/85833

Thank you for notifying us of the issue!
