### ISSUE TITLE
Odoo rest api has been blocked by CORS policy

### ISSUE THREAD

**Issue by drkpkg** [odoo/odoo#85217]
Impacted versions: 14

Steps to reproduce: Custom module

Current behavior: has been blocked by CORS policy

Expected behavior: return Json to angular website

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/972555/155331639-226c203a-c86c-474b-9235-6b86f92ff9c7.png)

I made an minimal rest api for odoo, I don't understand the problem why Angular shows me a Cors error when the method is open as cors="*"

```python
    @check_origin_and_token
    @http.route('{}/job/'.format(prefix_api).format(prefix_api),
                auth='none',
                csrf=False,
                cors='*',
                type="http",
                methods=['GET'])
    def job(self, **kw):
        res = []
        jobs = http.request.env['hr.job'].sudo().search([('is_published', '=', True)])
        for job in jobs:
            res.append({
                'id': job.id,
                'name': job.name,
                'area_id': {
                    'id': job.area_id.id,
                    'name': job.area_id.name
                },
                'location_id': {
                    'id': job.location_id.id,
                    'name': job.location_id.name,
                },
                'branch_id': {
                    'id': job.branchs_id.id,
                    'name': job.branchs_id.name,
                },
                'end_date': job.end_date,
                'company_id': {
                    'id': job.company_id.id,
                    'name': job.company_id.name,
                },
            })
        return json.dumps({'result': res}, indent=4, sort_keys=True, default=str), 200

```

**Comment by johnny-longneck** [comment]
The issue is not related to the odoo community project since you are using external technologies like Angular.
Nevertheless you should learn about CORS and what the error means.

I suggest closing this issue and searching for this problem on the internet.

**Comment by drkpkg** [comment]
Oh I see. I already solved it, if anyone are interested in the solution I leave the link here.

https://gist.github.com/drkpkg/a91ddd233a7aa8f20b64a9d67cd02660
