### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by tebanep** [odoo/odoo#8530]
As Python 3.5 was just released yesterday and will be the default in Ubuntu 16.04 LTS, doesn't Odoo team believe it's time to start thinking about the migration process and take advantage of Python's new capabilities? (async/await, typing module, "@" operator, etc).

**Comment by mbaragiola** [comment]
Migration is always a non-trivial thing to do. Although there are tools that help to do this (i.e. python-2to3), doing this won't be easy. But yes, I think that one day it would be needed to migrate to Python 3. But there are other more urgent priorities, such as migrating from API v7 to API v8, which AFAIK isn't finished.

**Comment by lukebranch** [comment]
@tebanep @mbaragiola ,

I asked this question awhile back in the forums here:

https://www.odoo.com/forum/help-1/question/9-0-master-will-odoo-be-able-to-support-python-3-0-in-master-9-0-70469

I believe that this will not happen in the near future due to the dependencies required for Odoo and the fact they are all written in 2.7.

**Comment by xmo-odoo** [comment]
> I believe that this will not happen in the near future due to the dependencies required for Odoo

Yeah there's a half dozen dependencies which are not Python3-ready (psycogreen, pydot, pychart, LDAP, OpenID and vobject), some of which are more or less abandoned. And then there's Odoo itself which generates a fair number of warnings under `-3` and more problematically absolutely isn't unicode-clean.

**Comment by tebanep** [comment]
Maybe it would be convenient to change some dependencies for future releases? Psycogreen (https://bitbucket.org/dvarrazzo/psycogreen) is a tiny library and I don't think it will have much trouble in migrating besides gevent's Python 3 compatibility, which is almost done. Also, one could think about replacing gevent completely in favor of async/await. LDAP could be replaced by ldap3 (https://github.com/cannatag/ldap3). I thought html with wkhtmltopdf had been chosen to replace all graphical documents generation in Odoo and so could easily take on pychart current responsabilities. For pydot, there is pydot2 (https://pypi.python.org/pypi/pydot2/1.0.33). For OpenID there is python3-openid (https://pypi.python.org/pypi/python3-openid). Finally vobject could be replaced by icalendar (https://pypi.python.org/pypi/icalendar/3.9.1). So I think all python external dependencies problems could be solved right now by using current existing packages which offer the same functionality. I believe the main problem regarding Odoo migration to Python 3 resides in Odoo codebase itself, and so I believe its time to start thinking seriously about best practices to ease the code refactoring (e.g. use "except Exception as e" instead of "except Exception, e", prefer "range" instead of "xrange" ignoring little performance penalties, etc). At least, I believe the project maintainers should start encouraging the use of Python 2.7 subset which is compatible with Python 3, for all new module developments. Python is a great language and right now sits on the 5th place on TIOBE index, even on top of PHP, however, this dominance can be threatened by the rise of new alternatives (NodeJS, Go, Nim, Crystal) which offers the same coding speed with much better runtime performance. I think a project as succesful as Odoo shouldn't ignore the technological capabilities and limitations of it's product, and should instead pay very good attention to the current trends and technology advancements. Python 3.5 offers great improvements to the language and I'm totally sure Odoo could benefit directly from it to keep its competitive position against other systems (and the new ones to come in vast amounts). Don't get me wrong with all this, I believe Odoo is a great product and that it's got a huge potential (I believe that much that I just became an Odoo Partner last week), but I think an effort should start to be done for it to stay nice and shiny as it is today. We in our company ditched Python in favor of NodeJS (With TypeScript) for all new projects, mainly because of performance gains and ease of development. I've noticed the same is happening all around and thus I'm worried about Odoo's future as it depends in a legacy language as Python 2.7 is. The perfect Odoo for me could probably be one that could use the most modern community accomplishments (Python3.5, PyPy3) to deliver an enterprise product that is both flexible and perfomant.

**Comment by lukebranch** [comment]
@xmo-odoo ,

<blockquote>
<p>Yeah there's a half dozen dependencies which are not Python3-ready (psycogreen, pydot, pychart, LDAP, OpenID and vobject), some of which are more or less abandoned. And then there's Odoo itself which generates a fair number of warnings under -3 and more problematically absolutely isn't unicode-clean.</p>
</blockquote>

Thanks for your interest in this topic. I do agree with some of @tebanep 's points in particular:

<blockquote>
<p>I believe its time to start thinking seriously about best practices to ease the code refactoring...</p>
</blockquote>

From what I understand eventually Odoo will need to make the switch to Python 3+ due to the EOL of Python 2.7+ (although this has been moved forward to 2020). I definitely think it would be a great initiative to begin re-factoring Odoo 10/11/12 with this eventual switch in mind.

**Comment by jaredkipe** [comment]
+1.  
Well said @tebanep 
Although unfairly simplistic, this could be an example of the "if you're not part of the solution, you're part of the problem" cliche.

**Comment by d9k** [comment]
Voting for.
I think many beginners like me are doubting whether use odoo whereas it's build on obsolescent version of python

**Comment by lukebranch** [comment]
@d9k ,

I don't think Python 2.7 is obsolete by any measure, and Python 2.7's EOL keeps getting pushed back as the majority of libraries are still in 2.7+. You should continue to build on Odoo with Python 2.7 confidently.

I'm sure that Python 2.7 > Python 3+ is on Odoo SA's roadmap somewhere in the future, however I think they may decide to wait until the pro's (eg.): 
+ performance
+ new features
+ compilers, etc. 

outweight the cons (eg.):
+ having to rewrite the entire codebase of Odoo
+ useful libraries being discovered in a Python 2.7 codebase
+ converting to unicode-clean code

I'm not very knowledgeable on this subject, but I believe there are some clear advantages to using Python 3, it'll be up to Odoo SA to decide when to make the move, however it will definitely be a very large time commitment from their developers.

**Comment by bringsvor** [comment]
I also think there's more pressing matters in the immediate, but as @tebanep  said maybe Someone could start with for example the Pychart dependency which is an obsolete library it seems.

And maybe code checks could be added for these "except Exception as e" kinds of things, if they are not already?

**Comment by tebanep** [comment]
We could maybe start looking at http://python3porting.com/ to begin the process. I know @matrixise has already started to work on this by replacing all Python2 code for Python3 https://github.com/matrixise/odoo/tree/to_python_3. However, I still believe the best way would be to support both Python 2.7 and Python 3.3+

**Comment by auvipy** [comment]
I use django heavily. they support both python 2 and 3. so odoo should atleast start supporting both version working using six. and call for volunteers to help with that.

**Comment by Yajo** [comment]
@auvipy Odoo already will break backwards compatibility (in a scheduled plan, so it's OK) in v10 when they drop old api. It would be a good moment to take the leap if possible, but anyway I don't see benefits on supporting both.

**Comment by Yenthe666** [comment]
@Yajo I'm almost 100% sure that the leap will not be made for V10. Odoo has a lot of tasks to complete before V10 and they already have to set priorities on most wishlist items, so I wouldn't hope on it :wink:

**Comment by andreparames** [comment]
@Yajo long term support for both versions seems redundant, but in the short term, ensuring that all new code is compatible with both would allow a smoother transition later. The new API is a good example: there was a transition period when both were supported.

**Comment by joelhandwell** [comment]
Today [Python 3.6 is released](https://www.python.org/downloads/release/python-360/). Could it be realistic to make a branch such as ```2and3``` and start to replacing from print statement in old code to be converted to ```from __future__ import print_function``` ? Using or not using ```lib2to3``` can be discussed. It might be possible to start discussing about what would be the "first step".

**Comment by auvipy** [comment]
I will be very happy to add python3 support

**Comment by Yajo** [comment]
Odoo guys said they're adding that in v11.

**Comment by Yenthe666** [comment]
Yup, it is confirmed that Odoo 11 will run on Python 3.x.

**Comment by auvipy** [comment]
Can I see where the work is going on? I am willing to contribute

**Comment by auvipy** [comment]
isn't this fixed?

**Comment by Yenthe666** [comment]
Hi @auvipy,

Good catch actually. Odoo 11 now has full Python 3 support. Some things aren't implemented (yet) such as async but I'd say overall that this wishlist item is handled.
