### ISSUE TITLE
[8.0][9.0]purchase.report object method difficult to override

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#8531]
Hi Odoo,

I want to complain about purchase.report,
that the writing of this object make us difficult to override as it just have init method,
not like sale.report, you split it to different method, so it easier to us to make modification.
the writing of the report should have standard like sale.report.

**Comment by Yenthe666** [comment]
Hi @falinwa,

Thanks for the report/suggestion.
At this point Odoo 8 is no longer supported and V9 has been around quite a while. This is not something that'll be changed anymore in these versions.

Regards,
Yenthe
