### ISSUE TITLE
[9.0] Calendar Default type View

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#8534]
Hi Odoo,

On version 9, I noticed that a lot of default type view for calendar move to week type, as before is month, maybe this change will make better for some company,
but there's some company that already fit to before version behavior.

So I think the best expected behavior, we must have posibility to change the default type view of calendar, is it based on week or month.

Thank You.

**Comment by mgielissen** [comment]
add mode="week" in the calendarview

See https://www.odoo.com/nl_NL/forum/help-1/question/how-to-show-week-by-default-in-a-calendar-view-75211

**Comment by Yenthe666** [comment]
Yep - if you'd like to have this you can do it with some custom code. This was/is intended behaviour 😉
