### ISSUE TITLE
Error creating database in 9 rc1

### ISSUE THREAD

**Issue by ovnicraft** [odoo/odoo#8539]
At commit: 
c033826 [FIX] portal : Fixed portal wizard view and traceback that occured when giving portal access to a user. (Thx to RCO for the view fix)
run:

$ python odoo.py 

open browser, manage database, create database, check load demo data

Create database

and get this output: https://gist.github.com/ovnicraft/96ec0aea574150c28b2a

**Comment by sle-odoo** [comment]
You have not installed the node "less-plugin-clean-css" plugin.
Did you use the packaging or a source install?

**Comment by ovnicraft** [comment]
@sle-odoo source installation, any file to check it ?

**Comment by ovnicraft** [comment]
BTW installing plugin metioned, fix my problem
