### ISSUE TITLE
[15.0]Pos cashier is wrong when change pos user 

### ISSUE THREAD

**Issue by aungkokolin-safecoms** [odoo/odoo#85391]
Impacted versions:15.0

Steps to reproduce:Firstly, login with one employee to pos session and then choose some product.Second, login with another employee and then make payment from previous products and then validate.

Current behavior:In pos receipt, you will see cashier is second employee name but in pos order of odoo session, you will see the casher is first employee

Expected behavior: The cashier must the second employee in both pos receipt and pos order in odoo session.

Video/Screenshot link (optional):https://drive.google.com/file/d/1fyVVGIRfrrx8_85zTqM2hHeVd0Erjdt5/view?usp=sharing

Support ticket number submitted via odoo.com/help (optional):#2779774

**Comment by pedrambiria** [comment]
Thanks for reporting this issue.

This problem has been solved.

Regards,
