### ISSUE TITLE
[15.0] `website`: Website: Editor and Designer can't customize SCSS after other user customized it, too (Access Error)

### ISSUE THREAD

**Issue by ivantodorovich** [odoo/odoo#85455]
**Impacted versions:** 15.0

**Steps to reproduce:**

1. Connected as `admin`:
    1. Configure user `demo` with **Website: Editor and Designer** group. Make sure he doesn't have **Administration** rights.
    2. Go to the website homepage and click on **Customize > HTML/CSS/JS Editor**
    3. On the top right corner of the editor panel select: **SCSS (CSS)**
    4. Uncomment the sample css, or put any custom css code there and **Save** (the code itself is not important, just the fact that we have now a custom scss file)
2. Connected as `demo`:
    1. Go to the website homepage and click on **Customize > HTML/CSS/JS Editor**
    2. ¡BOOM! 💥 _Access Error: Sorry, you are not allowed to access this document._

**Current behavior:**
The user doesn't have access to the `ir.attachment` `admin` created, thus the error.

**Expected behavior:**
Any **Website: Editor and Designer** user should be allowed to keep editing the website.

**Video/Screenshot link (optional):**
![image](https://user-images.githubusercontent.com/1914185/155792347-1845645c-1699-4313-ba6b-4f1fcb3cf6d5.png)

Tested on https://13188531-15-0-all.runbot40.odoo.com/

**Comment by rdeodoo** [comment]
Hello and thank you for the report.
Sorry for the delay.
It was fixed with https://github.com/odoo/odoo/pull/88211
