### ISSUE TITLE
[website, web_editor]: Removing dynamic snippets is making unnecessary network calls

### ISSUE THREAD

**Issue by kig-odoo** [odoo/odoo#85464]
On removal of the snippet, Some editor widgets make RPC which is responsible for slower snippet removal.

See: https://drive.google.com/file/d/1usAKEJvZ831Zr3cFZjwQxXPdRqVA42W8/view

Technical:

As soon [removeSnippet](https://github.com/odoo/odoo/blob/15.0/addons/web_editor/static/src/js/editor/snippets.editor.js#L435) method calls. Editor will trigger event `call_for_each_child_snippet` because editor needs initiate `onRemove` method for all child SnippetEditors.

Method [_callForEachChildSnippet](https://github.com/odoo/odoo/blob/15.0/addons/web_editor/static/src/js/editor/snippets.editor.js#L1976) will create SnippetEditor for all possible nodes. 

The same process will be followed for a dynamic snippet. the dynamic snippet will append a template that has images/ links etc and for these nodes, SnippetEditor is not created at that time (**I think there is no need to create SnippetEditor for those nodes as those nodes are not editable anyway**). So when we remove the dynamic snippet, Editor will create SnippetEditor for all the nodes that are added by the dynamic snippet. 

Ultimately options like `ImageTools`, `ImageHandlerOption`, will make network calls to get image info (`mimetype`, `originalId`) via method **loadImageInfo**. There are a few more options like `ReplaceMedia` is making network calls to loadAnchors. So this is the reason why the dynamic snippet removal process is slower.

**Comment by qsm-odoo** [comment]
Hello @kig-odoo :wave: 

> I think there is no need to create SnippetEditor for those nodes as those nodes are not editable anyway

Indeed that's probably the main problem that you described. Some non editable things are considered editable probably for the wrong reasons. Could/should be fixed in stable I guess. I'll have someone have a look :+1:

**Comment by qsm-odoo** [comment]
Merged https://github.com/odoo/odoo/commit/b2fee40ac9d1a745a15fb937c7db0aba6c78778b, just indirectly fixes the bug but was actually really important to do too.

I am closing this issue, I'll keep a TODO on my list to potentially stop snippet options to target uneditable content.
