### ISSUE TITLE
[9.0] Bug in website_events 

### ISSUE THREAD

**Issue by schmidtwastl** [odoo/odoo#8552]
Reproducing the error is possible in the official odoo.com demo instance:
https://demo1.odoo.com/event ->Customize ->Filter by Category -> 500: Internal Server Error

I had the same issue on a self-hosted instance

**Comment by tde-banana-odoo** [comment]
Fixed in 9 at commit 5885e5d9d077d7ca1ad87e547f4a0b9635bf55f0 . Thanks !
