### ISSUE TITLE
[9.0] sale: drag&drop of order lines will delete lines

### ISSUE THREAD

**Issue by intero-chz** [odoo/odoo#8555]
**Drag&Drop of sale order lines will (maybe) delete lines**

Impacted versions:

 - 9.0 (tested latest 9.0 community edition on runbot and current enterprise edition on odoo.com demo)

Steps to reproduce:

 1. create a new sale order
 2. add 2 lines
 3. save sale order
 4. modify sale order --> drag the second line above the first
 5. save order

Current behavior:

 - second line will be deleted after save

Expected behavior:

 - both lines will be there and in right order

**Comment by mart-e** [comment]
@Gorash can you take a look ? When you swap the lines, the write call uses the syntax `[(4, ID, _), (2, ID, _)]`

**Comment by Gorash** [comment]
Fixed (19dfde855841cce17b86322c92abd78359ba6a0f)
