### ISSUE TITLE
[9.0] Unable to select multiple taxes on Bank Reconciliation

### ISSUE THREAD

**Issue by lem8r** [odoo/odoo#8560]
Isn't it supposed to be many2many widget as in invoice lines?

![odoo10](https://cloud.githubusercontent.com/assets/5942291/9930562/3cb9c752-5d3d-11e5-88d5-d79b29d997e8.jpeg)

**Comment by flotho** [comment]
Hi @lem8r ,
I don't think so. Behing this view an account.move is created and you have no mechanism to transform many2many taxes on move.line and split them into multiple lines.
Accounting allows ONLY one tax per line if I remember well.

**Comment by Yenthe666** [comment]
@qdp-odoo could you give feedback when you have a spare minute?

**Comment by qdp-odoo** [comment]
you may define a tax which is a group of tax, so even if you're right and it should be improved in the future, that cannot be considered as a bug neither a limitation.

FYI, the support of many2many_tags outside form views has only been added in master few days ago, and it only became feasible at that point. :-)
