### ISSUE TITLE
installation "odoo 9"

### ISSUE THREAD

**Issue by roccocesetti** [odoo/odoo#8563]
the flag for the technical functionality appears on the card user 'Admin' menu appears of technical capabilities.
as do the 9.0 management menu, the view, the permissions on the forms?
thanks a lot, Rocco Cesetti

**Comment by lem8r** [comment]
About Odoo -> Developer Mode

**Comment by odony** [comment]
In Odoo 9 the technical features and the debug mode have been merged, so that switching to technical features does not imply a permanent change anymore.

**Comment by Yenthe666** [comment]
@odony so this means that when you activate the debug mode that you automatically have all technical features enabled too? You don't longer have to check the checkbox on the user?

**Comment by odony** [comment]
@Yenthe666 Yes, exactly.

**Comment by Yenthe666** [comment]
Finally, this will save me some time every day!
Joob idea :+1:

**Comment by roccocesetti** [comment]
tanks!
