### ISSUE TITLE
[14.0] website: Recursion Detected in theme.website.menu parent_id

### ISSUE THREAD

**Issue by imanie383** [odoo/odoo#85630]
Impacted versions: 14.0
Create a theme.website.menu and update
https://github.com/odoo/odoo/blob/14.0/addons/website/models/theme_models.py#L112

parent_id shoul be = self.**parent_id**.copy_ids...
![image](https://user-images.githubusercontent.com/35231827/156268836-dd6ad593-4c68-45c6-8f26-50e018015866.png)

ORIGINAL:
![image](https://user-images.githubusercontent.com/35231827/156268919-3ea99e36-508a-478e-aa12-80f6f52a8159.png)

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/35231827/156267500-005eb69b-6fff-4914-a68f-d6bef85d9d0a.png)
Support ticket number submitted via odoo.com/help (optional):

**Comment by imanie383** [comment]
@JKE-be could you analyze that please

**Comment by rdeodoo** [comment]
Hello :wave: thank you for the report.
Sorry for the late reply, I was on days off.

There is indeed something wrong about `theme.website.menu`, and it is not only about fixing those 2 lines.
We are taking care of it internally right now, it might take a bit of time.
We will come back to you once we come up with something.

**Comment by imanie383** [comment]
@rdeodoo 

Thanks, How can I raise an issue in enterprise?

Because the module sale_account_accountant introduces a bug in the reconciliation widget

https://github.com/odoo/enterprise/pull/25359

 I think the better fix is create the support for sell orders saleoder match

**Comment by rdeodoo** [comment]
You can open an issue in community mentioning the enterprise PR and just ping somehow in charge of the module/file you are editing I guess

**Comment by imanie383** [comment]
@rdeodoo  Thanks

**Comment by rdeodoo** [comment]
I sadly didn't have time to keep working on it but I have a fix in progress at https://github.com/odoo/odoo/pull/86669
I'll try to finish it asap

**Comment by rdeodoo** [comment]
https://github.com/odoo/odoo/pull/86669
In case you want to have a look, I'll try to merge it this week, that's basically the stable part you suggested.
