### ISSUE TITLE
No products selectable in inventory adjustment table or fields

### ISSUE THREAD

**Issue by jkrenzer** [odoo/odoo#8569]
Tested on a fresh branch 8.0 installation. 

When trying to adjust the inventory it's not possible to select a product in any mode. The product-selection field and the inventory table ignore any product names. Even when the product was moved to the selected warehouse before (in spite of  #4451).

**Comment by Yenthe666** [comment]
Hi @jkrenzer ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
