### ISSUE TITLE
[8.0] onchange called three times for one2many fields when deleting a line.

### ISSUE THREAD

**Issue by mvaled** [odoo/odoo#8573]
### Summary

When an `one2many` field has an `on_change` attribute, this method is "ajaxly" called three times when an item is removed from the list.

This behaviour can be checked in the account voucher interface.  I have also check it in a forward-port of the `crm_todo` addon.

**Comment by wtaferner** [comment]
You can find a fix in https://github.com/odoo/odoo/pull/8273 which was not merged...

**Comment by mvaled** [comment]
@wtaferner Thanks!  I will test it back in my env.

Since I haven't worked much with the JS side of Odoo I was doing an throughout inspection of the stack traces up to the point of the AJAX calls.  It was taking me a bit of work figuring out.

Furthermore, I do have a bug that I think is related to this behavior:  If you click several delete icons fast enough, the dataset will start to mark virtual records as deleted and, then, upon saving the server will get `(2, "one2many_vid_2020", false)` commands that will trigger an AssertionRecord in `models.py`.  

Whether this actual bug is related with the `onchange` being called three times is just a guess of mine, though.

**Comment by mvaled** [comment]
Duplicated #7595
