### ISSUE TITLE
l10n_pe: Issue when adding contacts

### ISSUE THREAD

**Issue by QaidjoharBarbhaya** [odoo/odoo#85752]
Herewith attached is the video demonstrating the issue.

Probably after PR: https://github.com/odoo/odoo/pull/84163

App trying to probably set the removed field from here: https://github.com/odoo/odoo/blob/14.0/odoo/addons/base/views/res_partner_views.xml#L233

https://user-images.githubusercontent.com/23092156/156568189-290ee8d6-2fb6-4017-a43e-7ea0e420b0d5.mp4

**Comment by desdelinux** [comment]
@QaidjoharBarbhaya This was resolved a long time ago.

Can you close the issue, please?

cc @pedrobaeza

**Comment by QaidjoharBarbhaya** [comment]
@desdelinux I see it was probably fixed from https://github.com/odoo/odoo/pull/85812, I will close this issue. Thank you.
