### ISSUE TITLE
[9.0] Expenses recognition when product is sold

### ISSUE THREAD

**Issue by lem8r** [odoo/odoo#8576]
Is there any way to configure Odoo 9 to debit Expenses when product is sold, not when it is purchased? Anglo-Saxon option is not doing what it was doing in Odoo 8.

At the moment expenses are debited when vendor's bill is validated.

I'm expecting to recognize my expenses when revenues are confirmed - when product is sold (when customers invoice is validated).
I believe this is default accounting practice in most countries.

Thanks!

**Comment by bistaray** [comment]
I see no difference in behavior with anglo checked or unchecked.  Stock Input and Output are not relieved when Invoices are created, and as @lem8r reports, COGS is debited when the Vendor Invoice is validated.

**Comment by lem8r** [comment]
Finally fix arrives
https://github.com/odoo/odoo/pull/8717

**Comment by qdp-odoo** [comment]
yep the fix has been merged in fabf90008d5d829.

Beware that the product has to be configured in perpetual valuation. And if you want to use real cost price for the cost of good sold, it must also be configured with costing method = real price and invoice policy = on delivered quantity.

Thanks for the report

**Comment by lem8r** [comment]
Didn't know about invoice policy. Thanks for the hint.
