### ISSUE TITLE
Employees are able to request for 'Legal Leaves 2015' before the manager accept the allocation request 

### ISSUE THREAD

**Issue by Monasha1992** [odoo/odoo#8581]
*_Employees are able to request for 'Legal Leaves 2015' before the manager accept the allocation request *_

Impacted versions:
- 8.0

Steps to reproduce:
1. As a employee - HR ==> Allocation Requests ==> Create a new Allocation request for 'Legal Leaves 2015' 
2. Again as the same employee - Create another new Allocation request for 'Legal Leaves 2015'
3.  Once again as the same employee - HR ==> Create: Leave Request for 'Legal Leaves 2015' 

Current behavior:
- Able to request for one 'Legal Leaves 2015' even if it says (0/0)

Expected behavior:
- Should display  a warning message saying 'The number of remaining leaves is not sufficient for this leave type. Please verify also the leaves waiting for validation.'

**Comment by Yenthe666** [comment]
Hi @Monasha1992,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
