### ISSUE TITLE
Issue For the not working customize template of "List View of Variants" in /shop/product page

### ISSUE THREAD

**Issue by dhavalb-emipro** [odoo/odoo#85820]
Impacted versions: 15

Steps to reproduce: Turn on List View of Variants in product page from customize option in website e-commerce

Current behavior: It doesn't show a list view for the product variants but it shows as original template of id="product" behaviour

Expected behavior: It should show a list view for the product variants
                                Template id = "product_variants"

Video/Screenshot link (optional): 

Support ticket number submitted via odoo.com/help (optional):

**Comment by rdeodoo** [comment]
Hello :wave: 

For some products, we can't display that list view even if it is selected, so it will work on most products but not all.
This will be the case if the product has some type of variant which are set to "never create" for instance, or custom variant.

That's not a bug, but I do agree this is impossible to understand and looks like a bug. 

In previous versions, we had a sort of warning on the product page (for the admins) in the form of a bootstrap alert to inform those admins that for this product, the list view couldn't be displayed for technical reason.
It was quite nice and easy to figure.

I am pretty sure that's the issue you encountered.

Right now, there is 2 issues about that:
1. If you enable the customize option (list view of variant) on a product which can't display that list view, it looks like it does nothing (well, it did nothing visually :grimacing: ). Leaving the impression this is just bugged.
2. If you enable the option on a product that can display that list view and then navigate to a product that can't, you have no clue why and it looks bugged too. You will probably just toggle again the setting off and on without it "working".

That's something I have already reported many times but wasn't considered important :shrug: 

If you can confirm that's the issue you faced, I will be able to escalate this once again.
