### ISSUE TITLE
8.0: Sorting by "xxx IS NULL" not possible anymore

### ISSUE THREAD

**Issue by JonathanStein** [odoo/odoo#8586]
Impacted versions:
- 8.0

Steps to reproduce:
- Add: _order = 'end_date IS NULL' to a model with the field 'end_date'

Current behavior:
- Throws warning with "invalid order"

Expected behavior:
- Sort open records (with no end_date) before closed records (with end_date)

This has been working before. I suppose it changed in commit 7349e23837e8433bedc134c6bd2c33e92b033209 on August the 20th or one of the related ORDER BY commits, but I can't figure out exactly how to fix this with respect to the new ordering mechanism.

**Comment by Yenthe666** [comment]
Hi @JonathanStein ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
