### ISSUE TITLE
Odoo 9.0: Incorrect quantities invoicing sent quantities

### ISSUE THREAD

**Issue by anajuaristi** [odoo/odoo#8587]
Tested in runbot http://102238-9-0-9e8e1b.runbot.odoo.com/
To reproduce:

Be sure that in sales/configuration/settings invoice sent quantities has been clicked.
1. Create a sales order
2. Include a couple of products
3. Confirm the sales order
4. Go to picking, change initial quantity adding some units,
5. Invoice from sales order does not take in mind the changed quantities but just the quantities on the order
Initially quantities are 10 and 3
I changed to 12 and 5 on picking, forced availability and transfered
Invoiced the sales order and invoice is taking 10 and 3
-----

Same test but not only changing quantities on picking but also product
1. Create a sales order
2. Include a couple of products
3. Confirm the sales order
4. Go to picking, change initial quantity adding some units and CHANGE the sent product
5. Sales order shows "nothing to invoice"
Conclusion; Changes on picking do not affect to sales order.

Thank you:
Ana

**Comment by qtheuret** [comment]
@anajuaristi on the runbot you mentionned, I didn't find a way to choose 'Invoicing on deliveries', so I think it is why the invoice doesn't take care of the picking modifications.

@Odoo Is there a way to get the invoicing method in the sales orders different than the default one ?

**Comment by lem8r** [comment]
- [x]  `Invoice based on costs (time and material, expenses)`

 is not working too.
I think this features are not ready yet.

**Comment by qtheuret** [comment]
Ok, I see this option on the Sales Settings : "Invoice delivered quantities"
I see this option is checked so the invoice should be made on the delivered quantities not on the ordered ones.

**Comment by anajuaristi** [comment]
Hi @qtheuret 
Yes. That is exactly the error. If you made any change on picking, sale order is not "advised" so it remains as initial status. 

It's a quite big issue. It should be extensively tested and reviewed. Please let me know if I can help on testing new use case or something. 
Thank you:
Ana

**Comment by fpodoo** [comment]
Ana,

Are you sure you set the "invoice based on delivery orders" on the product form? (Not on the settings)

Fabien

**Comment by anajuaristi** [comment]
Hi Fabien:
I was not sure I set on product form in my previous test so I did it again now, here.
http://102500-9-0-ecb17a.runbot8.odoo.com/

I used product Apple In-Ear Headphones
Verified product form check + sales setting test
I sold 10 units on Quotations SO045
I changed units to 15 on picking WH/OUT/00054
Force + validate picking, processed 15 units
Created invoice form sales order and it's taking still 10 units.

**Comment by fpodoo** [comment]
Yes, I confirm the bug. It will be fixed on monday.

**Comment by anajuaristi** [comment]
Thank you.
Please take in mind also the other point where it is allowed to change the product on picking.
In my point of view it should not. But if it is allowed, it should be properly invoiced.
Thanks again. 
Ana

**Comment by fpodoo** [comment]
Fixed in rev ec949ad59e9c

From what I have seen, we don't allow to change the product in the picking. We allow to add a new one, but then it's another one that should not be added to the sale order.

Thanks for reporting.

**Comment by anajuaristi** [comment]
Than you for the quick fix.
On the other side when you push edit button on picking line it's allowed to change the product. It's not about adding a new one.
I would set the field not editable to avoid problems. IMHO

**Comment by zenntrix** [comment]
@lem8r, Invoice base on time & materials does seem to work, but you first of all have to go to Timesheet activities and ensure all the activities are linked to a product and that you have that product on the sales order as an invoice line. Seems a bit clunky but that is how I have just got mine to work.

**Comment by fpodoo** [comment]
Ana, I fixed the ability to edit from the pencil icon too. rev: 98dcba2365

**Comment by fpodoo** [comment]
@zenntrix for timesheets, you should use "based on delivered quantities", not "based on time and material".

Based on time and material are for expenses (install the hr_expense module, and activate analytic accounting) or reinvoice based on POs.

**Comment by lem8r** [comment]
Yep, "based on time and material" is for re-invoicing expenses made by employee. Figured this out by reading source code.

**Comment by anajuaristi** [comment]
Hi Fabien:

Tested again on http://102530-9-0-fixes-nim-59a2e8.runbot6.odoo.com/
I confirm both issues has been solved
Now correct quantities are invoices from picking and product field is not editable on operations line.
So :+1: 
Thank you!!
