### ISSUE TITLE
[7.0] Dashboard report graphs produce an error, if the report is collapsed

### ISSUE THREAD

**Issue by tahtikar** [odoo/odoo#8588]
If a user has graph form report in their dashboard, and the report is collapsed (by clicking the minus icon in top right corner of the report), "uncaught exception: The target container must be visible" is shown when the user returns to their dashboard.

The error seems to be related to flotr graphs.

**Comment by mart-e** [comment]
Hello,

Thank you for your contribution but the branch is no longer supported. We only support the last 3 stable versions so no longer accepts patches into this branch.
We apology if we could not look at your request in time.

Regards
