### ISSUE TITLE
[8.0] Purchase Order based on incoming shipment is done with draft invoice

### ISSUE THREAD

**Issue by adrienpeiffer** [odoo/odoo#8593]
Hi,

Here a scenario on runbot 8.0

Steps to reproduce
-------------------------

* Go on runbot 8.0 and logon with admin
* Click on Purchase menu and create a new one
* Fill in required fields and change Invoicing Control for based on incoming shipment in Deliveries & Invoices page
* Add a new line with a stockable product (Ice cream is a good choice) and change quantity to 2 units
* Click on Save and confirm the created purchase order
* Click on Receive Products
* Click on Transfer
* Change quantity to transfer only 1 unit
* Click on Apply
* Click on Receive Invoice
* Validate the wizard
* Go on the purchase order
* Click on Receive Products and transfer completly the backorder
* Click on Receive Invoice in the backorder
* Validate the wizard

At this step you have to invoices related with the created purchase order.

* Open first invoice
* Click on Validate

Expected behavior
-------------------------
 The purchase order should remain in Purchase Confirmed status as long as the second invoice isn't validate

Current behavior
----------------------
The purchase order is done despite the second draft invoice

The expected situation was present before https://github.com/odoo/odoo/commit/9b1ab76eb29eb6297425a24a4a8d8beb86e5372f

Thanks,

Adrien

**Comment by adrienpeiffer** [comment]
OPW 649746

**Comment by sbidoul** [comment]
:+1: this looks like a regression.

**Comment by beledouxdenis** [comment]
Hello Adrien, Stéphane, 

This issue has been solved in Odoo 8.0 from revision bdcae86d67c05273f404594c9b38f22b31c8abec.

Regards,

**Comment by sbidoul** [comment]
Great! Thanks for the swift reaction.
