### ISSUE TITLE
[7.0] Performance of onchange_product in SO line (for large databases)

### ISSUE THREAD

**Issue by a0c** [odoo/odoo#8601]
In `sale_stock/sale_stock.py # product_id_change()` calling `product_obj.virtual_available` even when it's not needed slows down the onchange method drastically (for installations with lots of stock moves).

Should avoid calling `product_obj.virtual_available` until absolutely needed.

In 8.0 quants partially alleviate the issue, but in 7.0 `virtual_available` should be used with care.

**Comment by mart-e** [comment]
Hello,

Thank you for your contribution but the branch is no longer supported. We only support the last 3 stable versions so no longer accepts patches into this branch.
We apology if we could not look at your request in time.

Regards
