### ISSUE TITLE
Internal Server Error when trying to manage my databases (odoo.com)

### ISSUE THREAD

**Issue by SapphireHotS** [odoo/odoo#86012]
Impacted versions:
15.0
Steps to reproduce:
Go to odoo.com -> Profile -> Manage Databases
Current behavior:
TypeError: 'EndPoint' object is not iterable
Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):
![image](https://user-images.githubusercontent.com/37217564/157224701-847d9a00-0a61-4919-a0a6-8c596c280341.png)

**Comment by niyasraphy** [comment]
hi @SapphireHotS ,
this has been resolved as of now, can you confirm and close the ticket.
thanks
