### ISSUE TITLE
[9.0] You cannot update the translated value of field 'Arch Blob' 

### ISSUE THREAD

**Issue by zenntrix** [odoo/odoo#8603]
When trying to adjust the Settings under Accounting, User is presented with modal popup stating "You cannot update the translated value of field 'Arch Blob' "

This is an vanilla install of Odoo 9.0 on a Windows Server 2012 RC2.

**Comment by rco-odoo** [comment]
Fixed by 50de8350f30608fa7ec4c6d3537b8dc40013e6cd.

**Comment by zenntrix** [comment]
Wow that was a very quick response, I was still investigating the fix myself! Thank you :)
