### ISSUE TITLE
[12.0] Latest tar.gz  not avaible

### ISSUE THREAD

**Issue by matteoopenf** [odoo/odoo#86055]
Impacted versions:

- [ 12.0] 

Steps to reproduce:
try to download latest from there http://nightly.odoo.com/12.0/nightly/src/odoo_12.0.latest.tar.gz

Current behavior:
error 404

Expected behavior:
202 and it's possibile download

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional): 2789311

**Comment by matteoopenf** [comment]
Hi @d-fence  I remember for 11.0 you solved the problem.
Is it possibile solve again for 12.0?

**Comment by d-fence** [comment]
It should be good now

**Comment by matteoopenf** [comment]
> It should be good now

Thanks
