### ISSUE TITLE
email in .solutions domain not recognized as valid

### ISSUE THREAD

**Issue by hpaulsen** [odoo/odoo#8608]
It seems that the .solutions domain is not recognized by the email validator, perhaps other domains as well. I created a user with an email at a .solutions domain, tried to send an invitation email and it said "user has no email address". Changed email domain to icloud.com and it went through fine.

**Comment by mart-e** [comment]
Correct, it would actually break for any domain [more than 6 characters](https://github.com/odoo/odoo/blob/b1bd0c6cfaa1b8393d592b5e6518bfe7a5cc64be/openerp/tools/mail.py#L609).
FYI, as for September 23, that represents 315 domains names, the longest one being `XN--VERMGENSBERATUNG-PWB`, or, in proper UTF8, `.vermögensberatung`
Working on a fix

**Comment by mart-e** [comment]
Fixed at 7f29a231186deb1856098d81703848ab6b24328c
