### ISSUE TITLE
[BUG] Total of the amount untaxed for Multi-currency  in pivot table is wrong

### ISSUE THREAD

**Issue by hm-dev-m** [odoo/odoo#86104]
Impacted versions:
Tested in In Runbot Version 14.0

If you are using multiple currencies in Odoo, the pivot table view cannot summarize foreign currency values. So if you have a mix of currencies, subtotals and totals and untaxed total don't make sense

Steps to reproduce: 

1. Create multipe purchases with different currencies
2. Confirm purchases
3. Purchase analysis - Pivot view

Current behavior:
PO00001 = 100 Euro
PO00002 = 100 Dollar
PO00003 = 100 DH

Total = 300

Expected behavior:

The total should be in the Company Currency only. If myCompany currency is Euro

PO00001 = 100 Euro
PO00002 = 100 Dollar convert to 91.07 Euro
PO00003 = 100 DH convert to 9.13 Euro

Total = 200.2

Kind regards
Insaf

**Comment by ticodoo** [comment]
Hello @hm-dev-m . Did you make sure to configure the currency conversions for the Euro company? You have may have to manually trigger it for each company via the Settings.

**Comment by hm-dev-m** [comment]
> Hello @hm-dev-m . Did you make sure to configure the currency conversions for the Euro company? You have may have to manually trigger it for each company via the Settings.
