### ISSUE TITLE
[sale] sale report with multi currency is wrong price total

### ISSUE THREAD

**Issue by JulioSerna** [odoo/odoo#8612]
Impacted version
* 8.0

Steps to reproduce
* To create one sale order with pricelist by default(EUR) and validate, subtotal = **320**
* To create one version of pricelist in USD
* To create sale order with pricelist in USD and validate, the subtotal = **640**

Current behavior
* In reporting/Sale/Sale Report the **Total Price** to sale order with pricelist in EUR its ok, but to sale order with pricelist in USD its wrong the total price = **1280**

Expected behavior
* The sale order  **Total Price** with pricelist USD must be **640**

I made a video,
https://youtu.be/TcmkwAHl-rA

**Comment by sujinzhu** [comment]
sum(l.product_uom_qty * cr.rate * l.price_unit * (100.0-l.discount) / 100.0) as price_total,

should be

sum(l.product_uom_qty / cr.rate * l.price_unit * (100.0-l.discount) / 100.0) as price_total,

line 72 in sale_report.py

**Comment by beledouxdenis** [comment]
Closed with 48ccb199373592779a4d01caa7d248333dfda8e6.
