### ISSUE TITLE
Odoo V12 how to automatically delete an attribute value after a sales order?

### ISSUE THREAD

**Issue by wingkuan98** [odoo/odoo#86165]
Impacted versions: 12

Expected behavior: Is it possible I can create an automated action to delete a value of a product attribute after the value is added into sales order line and confirmed the sales order? 

Example: This product with 3 attribute values.
![image](https://user-images.githubusercontent.com/57710366/157629786-b93f93a7-1e15-4f7a-bc0e-13a875ad79fa.png)

In Sales Order placed order for value F6789-01-01 and confirmed as Sales Order (not Quotation stage)
![image](https://user-images.githubusercontent.com/57710366/157630023-a2d7e348-50a5-4b65-8245-dd7ee8b7f8b0.png)

Then, I wish to have updated output where the F6789-01-01 will be removed from that product attribute.
![image](https://user-images.githubusercontent.com/57710366/157630257-44f5649c-9d7e-4ab7-8d4f-5dc5ae97780f.png)

**Comment by Yenthe666** [comment]
Sorry but the Github tracker is for issues in the official code, not for asking questions :) 
You can ask these questions at help.odoo.com. 
On a sidenote: what you want to do does not sound like a good idea :)

**Comment by wingkuan98** [comment]
> Sorry but the Github tracker is for issues in the official code, not for asking questions :) You can ask these questions at help.odoo.com. On a sidenote: what you want to do does not sound like a good idea :)

I see... but I will need to complete the Odoo Quiz to get at least 3 karma in order to post in odoo forum.

**Comment by Yenthe666** [comment]
Or validate your email, that should also give you enough karma :)
