### ISSUE TITLE
HR Expenses analytic entry wrongly assigned to the user that approves the expense

### ISSUE THREAD

**Issue by jalzaga** [odoo/odoo#8618]
HR Expenses analytic entry assigned to the user that approves teh expense, not to the user that makes the expense

Impacted versions:
- 8.0
  Steps to reproduce:
  1. create a expense with user A assigning it to an analytic account.
  2. Send for approval
  3. Approve it (User B)
  4. Check the analytic account move. 

Current behavior:
User is set to B in analytic account move

Expected behavior:
User should be set to A in analytic account move

**Comment by Yenthe666** [comment]
Hi @jalzaga,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
