### ISSUE TITLE
[8.0] Stock Moves menu disappears when start managing stock owner 

### ISSUE THREAD

**Issue by a0c** [odoo/odoo#8619]
Menus `Stock Moves`, `Current Inventory Valuation`, and `Serial Numbers` disappear after choosing to "Manage owner on stock" or "Track lots or serial numbers" in Warehouse configuration. Upgrading Warehouse module fixes the issue.

#### Reproduce with Stock Moves menu
- Install stock module (Warehouse)
- Make sure menu Warehouse > Traceability > Stock Moves  is present
- In Settings > Configuration > Warehouse select `Manage Owner on stock`
- Go back to menu Warehouse > Traceability to see that Stock Moves menu is now missing. Even after Ctrl+R.

#### Temporary Fix
Upgrade Warehouse (stock) module.

Same goes to menu Warehouse > Traceability > `Serial Numbers`.
After selecting Settings > Configuration > Warehouse > Track lots or serial numbers, the menu Serial Numbers doesn't appear until Warehouse module is upgraded.

And same goes to Warehouse > `Inventory Control` > `Current Inventory Valuation`. If installed (e.g. by `stock_account` or `purchase` modules), the menu disappears after enabling `Track lots or serial numbers`. Also solvable by re-upgrading Warehouse module.

**Comment by mart-e** [comment]
Hello,

This is not really linked to the "Manage owner on stock". To see the `stock moves` menu, you need to be in the group multi-locations.

My guess is that you check the menu with the administrator or at least a warehouse user who belongs to this group by default, so they see the Stock Moves menu.
When you go to settings, the box "Manage multiple locations and warehouses" is unchecked (as the people do not have this settings by default, only the stock users do). So when you press the "apply" button, you subscribe everybody to the group "Manage owner on stock" but removes everybody from the group "Manage multiple locations and warehouses". As you are now removed from a group you used to belong, you no longer see this menu.
To get back the menu, you need to set your user in the group multilocation or check the box in the settings,
