### ISSUE TITLE
[9.0][stock_account] Feature request: add analytic account to Stock Location

### ISSUE THREAD

**Issue by lem8r** [odoo/odoo#8620]
It is crucial for construction/manufacturing business to make analytic entry about expenses when doing internal moves of raw materials from stock to production.

For example, we have main stock WH, and two production locations: Cafe and Hotel.
Now we are doing internal move:
 200$ of raw materials WH -> Production (Cafe)
 and
100$ of raw materials WH - > Production (Hotel)
accounting entries should be

| Account | Debit | Credit |
| --- | --- | --- |
| Stock | 0 | 200 |
| WIP | 200 | 0 |
| analytic:Cafe | -200 |  |
|  |  |  |
| Stock | 0 | 100 |
| WIP | 100 | 0 |
| analytic:Hotel | -100 |  |

Currently `stock_account` module is doing only accounting entries if Stock Location valuation accounts are set. There is no way to specify analytic account when doing Internal Move manually or by Manufacturing Order.

**Comment by lem8r** [comment]
I've managed this issue with dedicated module https://github.com/Polis-CH/odoo-addons/tree/9.0/stock_move_analytic
I can make PR if it makes any sense.

**Comment by ccandito** [comment]
Dear All,
this should be available in version 10 also.
Regards
claudio candito

**Comment by pedrobaeza** [comment]
There are already community and OCA modules for this, but it's not a core feature. I close this.
