### ISSUE TITLE
[8.0 git] XMLRPC account.invoice search_read sometimes truncates XML response

### ISSUE THREAD

**Issue by pmatis** [odoo/odoo#8622]
I've noticed that about 40% of my API calls are returning incomplete XML data, which crashes my code that's deciphering it. I wrote an API client in PHP, and have it currently in my browser, so I can just refresh to make the exact same call several times in a row - with a few seconds delay, and sometimes immediately (as fast as I can press F5). I used wireshark to verify that the response from odoo is incomplete. The capture was done directly on the Odoo server with tcpdump. I just recently added this API call to my code and noticed it so far with 8.0.20150728 and still after an upgrade to 8.0.20150919.

This is my sanitized call:

``` xml
POST /xmlrpc/2/object HTTP/1.0
Host: 192.168.33.99:8069
Content-Length: 1593
Content-Type: text/xml

<?xml version="1.0" encoding="utf-8"?>
<methodCall>
<methodName>execute_kw</methodName>
<params>
 <param>
  <value>
   <string>DATABASE-HERE</string>
  </value>
 </param>
 <param>
  <value>
   <int>ID-HERE</int>
  </value>
 </param>
 <param>
  <value>
   <string>PASSWORD-HERE</string>
  </value>
 </param>
 <param>
  <value>
   <string>account.invoice</string>
  </value>
 </param>
 <param>
  <value>
   <string>search_read</string>
  </value>
 </param>
 <param>
  <value>
   <array>
    <data>
     <value>
      <array>
       <data>
        <value>
         <array>
          <data>
           <value>
            <string>type</string>
           </value>
           <value>
            <string>=</string>
           </value>
           <value>
            <string>out_invoice</string>
           </value>
          </data>
         </array>
        </value>
        <value>
         <array>
          <data>
           <value>
            <string>state</string>
           </value>
           <value>
            <string>=</string>
           </value>
           <value>
            <string>open</string>
           </value>
          </data>
         </array>
        </value>
        <value>
         <array>
          <data>
           <value>
            <string>partner_id</string>
           </value>
           <value>
            <string>=</string>
           </value>
           <value>
            <int>73</int>
           </value>
          </data>
         </array>
        </value>
       </data>
      </array>
     </value>
    </data>
   </array>
  </value>
 </param>
</params>
</methodCall>
```

And abbreviated copy of the response

``` xml
HTTP/1.0 200 OK
Content-Type: text/xml
Content-Length: 31703
Server: Werkzeug/0.9.4 Python/2.7.6
Date: Sat, 19 Sep 2015 14:08:09 GMT

<?xml version='1.0'?>
<methodResponse>
<params>
<param>
<value><array><data>
<value><struct>
<member>
<name>comment</name>
<value><boolean>0</boolean></value>
</member>
<member>
<name>message_follower_ids</name>
<value><array><data>
<value><int>18</int></value>
</data></array></value>
</member>
<member>
<name>date_due</name>
<value><string>2015-09-15</string></value>
</member>
... omitted for brevity and security ...
<member>
<name>user_id</name>
<value><array><data>
<value><int>1</int></value>
<value><string>Person Name</string></value>
</data></array></value>
</member>
<member>
<name>write_uid</name>
<value><array><data>
<value><int>1</int></value>
<value><string>Person Name</string></value>
</data></array></value>
</member>
<member>
<name>origin</name>
<value><boolean>0</boolean></value>
</memb
```

Yes, the response ended with "</memb".

Upon refreshing the PHP page without changing any code, I received a complete response. I then refreshed a few more times, ans had an incomplete response several times in a row before I received a complete response again.

Note: The "Content-Length" in the XML response header is 31703 on both the good response and the truncated response. This tells me that the variable is completely populated with the XML response, but is somehow not being sent to the API client.

I've verified there's enough disk space (2.2G free) and enough memory (swap space is not being used). My only conclusion is that this is a bug in the Odoo code. Please let me know if you suspect I'm doing something wrong.

Thank you!

**Comment by colinnewell** [comment]
I had seen that myself but I'd assumed it was my tcpdump truncating the data.

**Comment by pmatis** [comment]
I don't think it is the fault of tcpdump. My code crashing coordinates
with the times that tcpcump sees an incomplete XML document returned.
It's quite repeatable, too.

Best regards,
Steve Switzer

---
Get world-class business I.T. services and a phone system with awesome features that won't challenge your budget!
http://www.SwitzerBusinessSolutions.com

**Comment by colinnewell** [comment]
I haven't had a chance to reproduce it myself but my symptoms look consistent with yours.  The Content-Length matches what was actually sent like yours which suggests it's somewhere in the python rather than a network issue as you already suggested.  Mine was also truncated on a kilobyte boundary.  

I had a quick play (on slightly different boxes to the one I had seen the issue) to see if it was a limitation in xmlrpclib but that appeared to be fine.  I need to try to reproduce the issue reliably somewhere first though to prove that's the case.

Note that results from the search methods can generally be limited or paged which should allow you to work around this issue if appropriate.

**Comment by xmo-odoo** [comment]
There isn't much we can do without a repro case. Performing the same query in a loop on a local system or against runbot shows no issue, and the XMLRPC dispatch code in Odoo is currently very simple raw WSGI, there isn't much which could go wrong: https://github.com/odoo/odoo/blob/8.0/openerp/service/wsgi_server.py#L60

**Comment by colinnewell** [comment]
I plan to try to create a repro case as this is affecting us to some extent.

**Comment by xmo-odoo** [comment]
Thanks. Do try updating Werkzeug to 0.9.6 (though I don't see anything of interest in the changelog) and using a more production-ready WSGI server.

**Comment by colinnewell** [comment]
While I am running an old version of werkzeug on the box I've seen this on are you sure it's likely to be that?  The fact that the Content-Length is set by your code suggests that it's before it hits the WSGI layer, unless that were to do something weird.

**Comment by xmo-odoo** [comment]
> While I am running an old version of werkzeug on the box I've seen this on are you sure it's likely to be that?

I don't think it's the version of werkzeug, but it might be the werkzeug server itself.

> The fact that the Content-Length is set by your code suggests that it's before it hits the WSGI layer, unless that were to do something weird.

`Content-Length` seems to be "correctly" set either way right? And see the link above, it's set to `len(response)` right before the response is returned to the WSGI server, so if there's a content truncation it seems to occur in the WSGI server or below (hence the suggestion to try a more production-ready WSGI implementation)

**Comment by colinnewell** [comment]
It's correct in that it's the length of the truncated data, suggesting that response is already truncated.

**Comment by xmo-odoo** [comment]
that's not what @pmatis stated, they report the same Content-Length regardless of response truncation

**Comment by colinnewell** [comment]
I guess I have a different problem then.

**Comment by Yenthe666** [comment]
Hi @pmatis,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
