### ISSUE TITLE
[Bug][14.0] Maintenance Request : can't create request

### ISSUE THREAD

**Issue by hoangvanhieu96** [odoo/odoo#86228]
Impacted versions: 14.0

Current behavior: when I login with account `Marc Demo` I can't make a maintenance request with `Responsible: Mitchell Admin` or any other

Expected behavior: I'd like to be able to accomplish the same thing as in version 13.

Video/Screenshot link (optional): https://drive.google.com/file/d/1foyjN67mvjDrk7bB523wGcq2Dsdp3kVt/view

**Comment by ticodoo** [comment]
This is expected behavior. Marc Demo's permissions are set to team.user by default so the user cannot create new maintenance requests without admin updating his access rights. If behavior is desired then have Mitchell Admin update the access rights.
