### ISSUE TITLE
[9.0][website_event] You cannot update the translated value of field 'Arch Blob' None

### ISSUE THREAD

**Issue by ccarly** [odoo/odoo#8623]
Website, not english
Administrator, not english

When edit website_event, and add any block, after  save say "You cannot update the translated value of field 'Arch Blob' None"

http://102518-9-0-ec949a.runbot6.odoo.com/

**Comment by zenntrix** [comment]
Have you tried the following fix -> 50de835. It fixed my problem with the same message.

**Comment by ccarly** [comment]
@zenntrix i try, but not work

**Comment by Cafeinoman** [comment]
Same bug when creating new event, on a local install from nightly deb repo.

**Comment by max3903** [comment]
Languages: en and fr_CA
Default language : fr_CA

Same error on any page when I try to save a modificatio (adding a block for example).

**Comment by mart-e** [comment]
@Gorash can you take a look?
If you set the default language of the website to something else than English, when adding a block you get "You cannot update the translated value of field...".
If the default is English, when translating, get an error "Record does not exist or has been deleted."

**Comment by SBollatti** [comment]
+1 Same issue:
"You cannot update the translated value of field 'Arch Blob' None"

**Comment by cocinfar** [comment]
Hello All,

After struggling with this for some sleepless nights I have found this intermediate solution. I can now use any non-English (en_US) language as the base language for the website and shop.
However I cannot translate the en_US language. To overcome this I have installed a new English language (en_GB) and disabled the English (en_US) language from the website. This way everything seems to work just fine. I have my native language and English language as alternative. I have also tested with Spanish and French and it works fine.

Just apply the following path to models.py in openerp folder:


*** odoo-9.0rc1-20150927/openerp/models.py	2015-09-25 01:41:46.000000000 +0100
--- odoo-9.0rc1/openerp/models.py	2015-09-27 01:58:10.169050220 +0100
***************
*** 3877,3883 ****
          upd_todo = []
          updend = []additional
          direct = []
!         totranslate = context.get('lang') and context['lang'] != 'en_US'
          for field in vals:
              ffield = self._fields.get(field)
              if ffield and ffield.deprecated:
--- 3877,3894 ----
          upd_todo = []
          updend = []
          direct = []
!         #totranslate = context.get('lang') and context['lang'] != 'en_US'
! 
!         totranslate = False
!         if context.get('website_id'):
!             settings = self.pool.get('website.config.settings')
!             settings_ids = settings.search(cr, user, [['website_id', '=', context['website_id']]])
!             if len(settings_ids) > 0:
!                 default_lang_id = settings.browse(cr, user, settings_ids[len(settings_ids) - 1]).default_lang_id.code
!      
!                 if context.get('lang') and context['lang'] != default_lang_id:
!                     totranslate = True
          for field in vals:
              ffield = self._fields.get(field)
              if ffield and ffield.deprecated:


It seems that en_US is hard-coded into the source-code and it shouldn't.

If any one has a better solution... please let me know!

Fernando

**Comment by rco-odoo** [comment]
@ccarly The issue may have been fixed since. I can no longer reproduce the issue.
