### ISSUE TITLE
[9.0] regression: onchange is not informing we do not have stock.

### ISSUE THREAD

**Issue by nhomar** [odoo/odoo#8625]
Steps to reproduce:
---

1. Installing sale and sale_stock module.
2. Create a sale order.
3. Set product [C-Case] Computer Case.

What do I expect: Warning informing we do not have enought inventory.
What do I get: Product added silently.

Regards.

sha: 0ec19af59c6bc5

**Comment by qtheuret** [comment]
Thanks for raising this issue.

**Comment by fpodoo** [comment]
I confirm the issue. To be fixed.

**Comment by nim-odoo** [comment]
Fixed with ced4bf55395e21bb9035ca93e36fd135868ff5b5

**Comment by gdgellatly** [comment]
can I just make a small comment with this fix, seeing we are improving workflow and making things better.  The stock warning is hugely frustrating for guys who quote a lot in MTO.  It would be nice if it could be refactored to be easily overridden.

Scenarios where you might not want the message:
Quoting
MTO Orders

Which is a lot of orders, in fact in my company it is 90% of the lines of every single order.

**Comment by gdgellatly** [comment]
sorry meant to ping @fpodoo

**Comment by gdgellatly** [comment]
sorry I see MTO is covered, just quoting.  Anyway would be nice to be able to override, as simple as pulling out that one message to a function.

**Comment by fpodoo** [comment]
No, we prefer to keep the message when quoting. Mostly because 90% of the
companies that sell physical products quote and sell the product directly.
(because quote is the first step of sale)

**Comment by gdgellatly** [comment]
@fpodoo I am not asking for it to be removed, just to make it easier to override the behaviour.  A simple function call to get the warning.  Lets say it is 90%, that is still 10% of people who don't like it.

**Comment by fpodoo** [comment]
Graeme,

That's a good idea, but we don't want to include it in version 9. I would
suggest to do a community module for this feature.

Thanks,

-- 
Fabien

**Comment by gdgellatly** [comment]
@fpodoo  I have done a community module for years, I think the message was introduced in 6.1 but it is brittle because I always have to detect the exact warning message in the onchange output.  To be honest this whole function (product_id_change) has always been a problematic one for me, because it does so much without easy hooks and expects only one way of doing things.  It isn't that big a deal, just saves me 10 lines of code and having to check every update that the warning message hasn't changed.

**Comment by fpodoo** [comment]
Yes, we plan to change the mechanism of the on_change for V10. (we are
currently working on a better alternative)

**Comment by nilshamerlinck** [comment]
Hi @nim-odoo, I think your fix is not enough.

With `sale`, `sale_stock` and `purchase` modules installed, "[C-Case] Computer Case" product configured with "Buy" Route, I don't have any warning.

Also it seems the "Can Be Purchased" boolean is ignored.
