### ISSUE TITLE
timezone issue in calendar.event for allday event

### ISSUE THREAD

**Issue by jeffery9** [odoo/odoo#8626]
**timezone issue in calendar.event for allday event**

Impacted versions:
- all version

Steps to reproduce:
- user's timezone is asia/chongqing, create a new allday event. eg. allday event starting at 09/23/2015 and ending at 09/23/2015 too.

Current behavior:
- the start and stop datetime stored in pg table both are 09/23/2015 00:00:00.

Expected behavior:
- the corrected should be  09/23/2015 00:00:00 - 8 hours.

**Comment by pedrobaeza** [comment]
For allday events, the hours part is ignored, and thus it's saved in UTC for convenience, so there's no real problem with this, unless you want to get the proper date from only that fields. You will need to check also the allday flag and act properly when set.
