### ISSUE TITLE
When search or scan a product  to weigh Scale screen does not open

### ISSUE THREAD

**Issue by mizthu** [odoo/odoo#8627]
I have products with customized references, eg
Product : Tomato
Reference : F01
That is configured to be weighed on balance but by scanning the printed product code or look in the searchbox and give enter is automatically added to the request and is not going to the weight screen

![captura de pantalla de 2015-09-20 23 22 29](https://cloud.githubusercontent.com/assets/8080816/9985280/b84ee60a-5fee-11e5-9d42-73ed8aa1e8b5.png)

only when I click on the image will display weight screen

![captura de pantalla de 2015-09-20 23 25 45](https://cloud.githubusercontent.com/assets/8080816/9985305/2c84fe06-5fef-11e5-8062-e5b4f2b72360.png)

**Comment by pedrobaeza** [comment]
Is this still happening?

**Comment by pedrobaeza** [comment]
Closing as no answer. Feel free to open a new issue if this is still happening.
