### ISSUE TITLE
[9.0] workflow: Sale order is not marked as done.

### ISSUE THREAD

**Issue by nhomar** [odoo/odoo#8628]
Hello.

Steps to reproduce.
---

1. Install sale and sale_stock.
2. Adjust your inventories for [C-Case] Computer Case to 20 (go to Inventory > Initial Inventory).
3. Make a Qutation for 10 [C-Case] Computer Case.
4. Deliver the products.
5. Make the invoice.
6. Make the payment of the invoice.

What did I get: Order is still Open.
What I expect: Order is marked as “done”.

Is this an expected behavior or did I miss something.

**Comment by jco-odoo** [comment]
Help text of 'Set as Done' button:

If a sale order is done, you cannot modify it manually anymore. However, you will still be able to invoice or deliver. This is used to freeze the sale order.

**Comment by jco-odoo** [comment]
So the meaning has changed.

**Comment by qtheuret** [comment]
So, if I understand well, user should have to put the SO to 'Done' manually ?

**Comment by jco-odoo** [comment]
indeed

**Comment by guewen** [comment]
> Help text of 'Set as Done' button:
> 
> If a sale order is done, you cannot modify it manually anymore. However, you will still be able to invoice or deliver. This is used to freeze the sale order.

Maybe it would be worth to consider to rename the button? I find `done` very confusing for that purpose. Maybe Lock? Freeze?

**Comment by PanjieKitt** [comment]
@nhomar @qtheuret 
If you config 'Sales Order Modification' to Never allow to modify a confirmed sale order, the SO will be set to 'Done' right after it is confirmed, so the user won't need to hit the 'set to done' button manually.
