### ISSUE TITLE
[9.0] regression: No there are any way to ask for procurement on product form in v8.0 we had an useful wizard which from the product form allow us to ask for an inventory adjustment.

### ISSUE THREAD

**Issue by nhomar** [odoo/odoo#8629]
Hello.

In version 8.0 we had a way to set an inventory adjustment in the product form which allow us adjust the inventories very easy creating perfectly and inventory adjustment document in the backend.

We do not have it anymore.

on v8.0:

![imp](https://www.evernote.com/l/AJ6RZuVPkZdLqaDWSvQKcAa5RsUjY1JJyBYB/image.png)

on v9.0:

![imp](https://www.evernote.com/l/AJ7N6vpomkVDLomX-LxNdzk3So7F2NM8WPUB/image.png)

Is this an expected behavior or did I miss something.

**Comment by jni-odoo** [comment]
Hello Nhomar,

Right now there is a bug the buttons are only visible if the type of the 
product is 'Consumable'..it should be visible on stockable type too.

See here : 
https://drive.google.com/file/d/0B5j41T1Hqv1sV2haQ19ZTmNaSEE/view?usp=drivesdk

Thanks,
Nikunj Jani (odoo India)

**Comment by fpodoo** [comment]
fixed in  rev 973b94bd
