### ISSUE TITLE
[9.0] concept: Is it correct the order allow one time is confirmed change the description of the line?

### ISSUE THREAD

**Issue by nhomar** [odoo/odoo#8631]
Hello.

AFAICK, the sale order onece is confirmed should be blocked and the change process of some detail should follow a proces to revert some details, because the sale order in some environments is a legal documents.

Then in v9.0 once the SO is confirmed the description of the line is allowed to be changed, without control of such changes at all, frequently it requires a versioning process.

On v8.0 it was correctly avoided, and with some community extensions we were able to version it.

Did I miss something, or it is a expected behavior?

**Comment by fpodoo** [comment]
It is the expected behaviour. If you want to freeze a sale order, you should mark it as done. The definition of done is that you can not change it anymore. If it's in progress, you can change this.

A lot of companies need this:
- open orders
- want to change because you did a mistake after validation

**Comment by nhomar** [comment]
@fpodoo I just extend my answer to this case, in my opinion I am with with you about the approach but I fell as it is incomplete.

BTW, I think the actual approach can not be the default because the only ones that can do what you explained are the ones that really do not use Sales Orders as internal document controls, they use external tools to control such changes. Well that's my experience, actual behavior will not be OK, we will need an extension on V9.0 if you decide not to manage such use case... Can you extend a little more which are the use cases (with company cases) where you need such openess in the Sale Order?
