### ISSUE TITLE
8.0 Display of float function fields in tree view ignore the digits parameter

### ISSUE THREAD

**Issue by alexis-via** [odoo/odoo#8632]
With an up-to-date Odoo v8, if I define a float function field like this:

```
    amount_currency = fields.Float(
        string='Amount', digits=dp.get_precision('Account'),
        compute='_compute_amount')
```

and the precision of 'Account' is 2 (the default value), sometimes Odoo displays the field in a tree view with all the digits, for example "22.08000000000001", which is quite ugly for the user.

Here is a screenshot ; the "Amount" field is a float function field ; on the 2 first lines of the tree view, it is displayed without the 2 decimals ; on the last line of the tree view, it is displayed with too many decimals (22.080000000001).

![odoo-bug_display_function_float_field_tree_view](https://cloud.githubusercontent.com/assets/1157917/9988080/cbda4728-604d-11e5-9401-a12e98228584.png)

The bug is still present:
- if I use "digits_compute=dp.get_precision('Account')" insead of "digits=dp.get_precision('Account')"
- if I use "digits=(16, 2)" insead of "digits=dp.get_precision('Account')"
- if I add "store=True" to field definition.

This issue only affects the tree view, not the form view.

**Comment by moylop260** [comment]
They can replied with  next PR: https://github.com/odoo/odoo/pull/8610/files

**Comment by moylop260** [comment]
Duplicated with https://github.com/odoo/odoo/issues/8611

**Comment by pedrobaeza** [comment]
I also experiment this problem

**Comment by hbrunn** [comment]
@alexis-via I found this issue when searching for duplicates of my PR: https://github.com/odoo/odoo/pull/11441 - this probably fixes your issue (accidentally) too, right?

**Comment by Yenthe666** [comment]
Hi @alexis-via,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
