### ISSUE TITLE
[9.0] Quants menu not available in Inventory apps

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#8634]
Hi Odoo,

today I tested the inventory apps in odoo runbot for version 9,
and I found that there's no quants menu anymore in inventory apps.
Here the picture:

![quants1](https://cloud.githubusercontent.com/assets/7590534/9988281/b14ac426-6081-11e5-8eba-c62b8dfdc717.JPG)

We should have this menu,
if this not a bug how can we display the menu?

**Comment by jni-odoo** [comment]
Hello Falinwa,

The dedicated menu has been removed (as already it was read only and 
creates confusion between stock moves and quants)..

And basically we need those for reporting so you can get the same object 
at     Inventory -> Reports -> Inventory Valuation

See here 
:https://drive.google.com/file/d/0B5j41T1Hqv1sZlFZMGM0MmN0T2c/view?usp=drivesdk

Thanks,

Nikunj Jani (Odoo India)

**Comment by falinwa** [comment]
ok, understand.

Thanks for the explanation.
