### ISSUE TITLE
[9.0] Sale Order doesn't have delivered and invoiced checkbox anymore

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#8636]
Hi Odoo,

In Odoo version 9 for sales apps,
On sale order form, we don't have checkbox for delivered and invoiced anymore.

![so1](https://cloud.githubusercontent.com/assets/7590534/9988351/68743178-6082-11e5-9b63-874393d3399d.JPG)

Expected behavior:
We should have this kind of checkbox as like before in version 8.

**Comment by jni-odoo** [comment]
Hello

You have three new fields: Qty Ordered, Qty Delivered, Invoiced. (New 
changes in Sales and Purchase apps)

The product has a new field "Invoice Method": based on quantities 
ordered, based on quantities delivered (could be timesheets), based on 
time and material (reinvoice costs or expenses).

See Here : 
https://drive.google.com/file/d/0B5j41T1Hqv1sNGRqc2ZXcmp2ZHc/view?usp=drivesdk

You can track from the SO , no need for separate chekboxes...

Thanks

Nikunj Jani (odoo India)

**Comment by nhomar** [comment]
@jni-odoo 

What we need I think is a way to mark the sale order as "Finished" I understand on v9 the "done" word take another approach, but When in the workflow the order is Bloked to process any other thing related to it?

**Comment by nhomar** [comment]
@jni-odoo 

You can find another issue which I think is related conceptually.

https://github.com/odoo/odoo/issues/8635

**Comment by fpodoo** [comment]
Nhomar, you have the invoice status. You can also add a shipping status as a community module if you want to get it per order, not per order lines. But, for us, it's the expected behaviour.
