### ISSUE TITLE
[8.0] Deleting demo records causes major issue in modules with dependencies when attempting to upgrade

### ISSUE THREAD

**Issue by stundzia** [odoo/odoo#8641]
For example, with sales and sales_team modules loaded if you delete a demo record, which in my case was the Indirect Sales team, once you try to upgrade the sales module to load the demo data again it blows up, because it attempts to create a new record without the required fields from the module it depends on. A solution would be when attempting to upgrade a module that has dependencies to force upgrade the dependencies as well.

Record from sales_team_demo.xml:
```xml
<record model="crm.case.section" id="crm_case_section_1">
            <field name="name">Indirect Sales</field>  <----- *required field*
            <field name="code">IM</field>
            <field name="member_ids" eval="[(4, ref('base.user_root')),(4, ref('base.user_demo'))]"/>
        </record>
```
Same record from sale_demo.xml:
```xml
 <record model="crm.case.section" id="sales_team.crm_case_section_1">
            <field name="invoiced_forecast">36000</field>
            <field name="invoiced_target">40000</field>
        </record>
```
So when I upgrade the sale module it attempts to create a new record with only the invoiced_forecast and invoiced_target fields filled in, the others being null and so unsurprisingly this pops up:
```xml
ParseError: "null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (5, null, null, null, 1, 2015-09-21 11:34:56.910862, 1, null, null, null, null, null, 2015-09-21 11:34:56.910862, t, f, null, null, t, 40000, 36000).
" while parsing /opt/odoo/addons/sale/sale_demo.xml:10, near
<record model="crm.case.section" id="sales_team.crm_case_section_1">
            <field name="invoiced_forecast">36000</field>
            <field name="invoiced_target">40000</field>
        </record>
```

**Comment by nhomar** [comment]
I think this is an expected behavior, when you install with demo data that should happen on that way, to avouid the error, did you try a -u all?

**Comment by stundzia** [comment]
Of course it is easy to avoid for a coder, but for a regular user? If a regular user who is only aware of his browser and has never even seen a terminal causes an internal server error, he will not be able to bring it back up without qualified intervention.

**Comment by mart-e** [comment]
Sorry but this is demo data so should only be used in development or testing. We should be tolerant to suppressions when using reference in the code (e.g. b15775c73127b8a765f054019f3adb7d2506c746) but if you delete demo data, well you have to update the module to get it back.
I agree it could happen when you are testing a demo database but we focus to not break people in production first.
