### ISSUE TITLE
Re-set to draft PO doesn't cancel reception

### ISSUE THREAD

**Issue by qtheuret** [odoo/odoo#8645]
**Re-set to draft a PO doesn't cancel reception**

Impacted versions:
- 9.0 (https://demo1.odoo.com)

Steps to reproduce:
1. create a new purchase order
2. add a line with product 'C-case', quantity 1, unit price 10.0
3. validate the purchase order -> A reception of 2 is available
4. Cancel the purchase order
5. Re-set to draft the purchase order
6. Change the quantity to 2 for the product 'C-case'
7. Confirm the purchase order

Current behavior:
- Two receptions are linked to the purchase order: one with 1 PCE and one with 2 PCE

Expected behavior:
- Only one reception with 2 PCE should be linked to the PO. The old one must be updated or canceled.

**Comment by aftabnaveed** [comment]
I don't think you can reset a purchase order to Draft state.

**Comment by sle-odoo** [comment]
Hi,
The issue you're mentioning is not reproducible anymore. Canceling the PO will correctly cancel the receipt while "reset to draft" with a new quantity will correctly create a new receipt.

Regards
