### ISSUE TITLE
[9.0] No clear way to pay expenses

### ISSUE THREAD

**Issue by zenntrix** [odoo/odoo#8648]
Followed the steps below.

1) Click Expenses in top menu
2) Create new 'Employee (to reimburse)' expense
3) Submit, Approve & Generate Single Accounting Entry
4) Expenses is now sat in 'Waiting Payment' status, there is no obvious way to progress this into paid state........ maybe i'm missing something?

**Comment by jni-odoo** [comment]
Hello ,
In V9 , as you might now the expense management itself is a separate app..so the roles are very important. So as an employee I will create an expense , and then submit to my manager..My manager will approve the expense and that's it.

Now, Accountant will come into the picture and he sees the expenses that are to be paid..either it can be a bank or it can be a cash..

So it is a Bank Statement or a Cash statement (put the amount in negative ) then reconcile the entries , then it will be paid...

See here : https://youtu.be/IbKeYA5ROyo

This may help you..

Thanks,
Nikunj Jani (Odoo India)

**Comment by Yenthe666** [comment]
Hi @zenntrix,

I believe jni-odoo has answered your question.
Should you still have this question and need more details I'd suggest you to post a new topic on the official Odoo help forums (help.odoo.com), there are plenty of people that can help you there.
Closing this one, since it is not a real issue.

Regards,
Yenthe

**Comment by ropic** [comment]
The trick here is:
1. The employee **must have** the field Contact Information filled.
2. Make a bank transaction using this contact on item entry.

**Comment by mandywebsparks** [comment]
Hi, i am still not able to solve the problem. Expenses is now in 'Waiting Payment' status, there is no obvious way to progress this into paid state. i have followed the steps to supplier payments> create> selected the person's name but no information has appeared. Please help

**Comment by ropic** [comment]
It's not a supplier payment make a transaction on bank account using the contact name from the emoyee, I spent hours for this.

Hope that helps you

**Comment by mandywebsparks** [comment]
Hi Ropic, 

thank you for your reply, could you lead me step by step on this? i still do not see any items listed when i selected the names.
thanks!

**Comment by ropic** [comment]
I can help you in about 10 hours please let me know if you fix it
before, read again my post and do it.

**Comment by mandywebsparks** [comment]
alright,, i'll be waiting :)

**Comment by ropic** [comment]
Once you have the expense on waiting payment status:
1. Make sure your employee has the Contact Information > Home Address field set.
2. Go to Accounting dashboard.
3. From the account you are going to pay click on More > New - Transaction
4. Add new transaction and on field partner select the Home Address from your employee contact information. Don't forget amount must be negative
5. Reconcile the transaction.
6. Done ! Your expense is on status Paid

**Comment by JasirMJ** [comment]
Hello guys  in odoo v8 to get employee expenses state as paid by the following methods :

1. Make our employee as Supplier
Go to _Human resource_ > _Employees_> _your employee_ ,which need to get paid , click on edit then go to _personal information_  choose Home address for your user if not assigned , whether its assigned or not , make sure that user has checked supplier in his _sales and purchases_ tab ,save if changes made.
   After that go to _accounting_ then _Suppliers  >  Supplier payments_ then create a new, then select your employee which is need to be payed , when you selected then your amount will be shown, now under the table head Full reconcile check the check box by entering your amount then validate it. also you can check your employee status has changed or not under _human resources_  > _expenses_ >_expenses_

2. Pay by using bank statement or cash statement
    Go to _Accounting >Bank and Cash_ choose Bank statement create new add items , reference then select partner as your employee who need to get paid , select negative amount for example if i have to pay 1000 then i have to enter -1000 . then click Reconcile

i hope this will help
