### ISSUE TITLE
[8.0][account_bank_statement] do not show lines reconciled with refund

### ISSUE THREAD

**Issue by JulioSerna** [odoo/odoo#8649]
Impacted version
- 8.0

Steps to reproduce
- To create invoice with **amount total = 100**
- To create second invoice with the same data but with **amount total = 200**
- To create refund with amount total = 5
- Reconcile the two invoices with refund
- To create bank statement by 295
- Try reconcile

Current behavior
- there is nothing to reconcile

Expected behavior
- the invoices must be displayed to reconcile

I made a video,
https://youtu.be/XEPOUcPRzmE

**Comment by Yenthe666** [comment]
Hi @JulioSerna,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
