### ISSUE TITLE
website multibyte urls

### ISSUE THREAD

**Issue by mrawi** [odoo/odoo#865]
In Website Blog (Saas3 at 5b83e88), any Arabic words are ignored in post SEF urls thus truncated to only the blog post number. If Latin and Arabic letters are mixed, Arabic letters are ignored while Latin are correctly displayed. The SEF URL then will display the dashes between words without actually containing them.

To reproduce:
Create any blog post and give it a name in Arabic from website front end.
Save and navigate away and then back to the post to generate the URL.
The generated SEF URL is as described above.

**Comment by Yenthe666** [comment]
Dear @mrawi,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe

**Comment by nasermars** [comment]
hi, still this issue iss valid on odoo 18 (and others).
I think we need a module for change views or add a few codes on main module.
Please note that this make odoo websites more helpful on SEO and google consule.
