### ISSUE TITLE
404 Error for Blog Archive

### ISSUE THREAD

**Issue by mrawi** [odoo/odoo#866]
Clicking any date range in Blog Archives in Right Column leads to 404 Error. Requested link is like:
/blog/News-1/date/2014-05-31%2021:00:00_2014-06-30%2021:00:00

SaaS-3 at 5b83e88
To reproduce, create random posts.
Activate Right Column
Activate Archives
Click any date range.

**Comment by Yenthe666** [comment]
Dear @mrawi,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
