### ISSUE TITLE
[9.0] Adding a Project stage always makes a new one (even if that name exists)

### ISSUE THREAD

**Issue by jaredkipe** [odoo/odoo#8660]
**Adding a Project stage always makes a new one (even if that name exists)**

Impacted versions:

 - 9.0
 - 9.0 Enterprise

Steps to reproduce:

 1. create a project
 2. add a column a project already uses (like 'Complete') *note that there is no search action*

Current behavior:

 - the stages now has another stage by the same name.
 - reporting now has duplicate stage names and tasks in the stage

Expected behavior:

 - Normal Many2one search field should prompt with names and have 'Create'

![screen shot 2015-09-22 at 2 21 56 pm](https://cloud.githubusercontent.com/assets/744550/10032056/8d7eab2a-6135-11e5-9457-35c502db119c.png)

**Comment by tde-banana-odoo** [comment]
Actually it is the intended behavior in 9.0. Columns are not shared by default between projects, and thus may have their name duplicated. It is still possible to have shared columns in technical mode by adding coluymns in the m2m. But with the kanban interface you will not have shared columns.

**Comment by jaredkipe** [comment]
I want to go on the record of saying that this doesn't make sense.  If you have a lot of probjects, and do not arduously use the 'duplicate project' workflow, you will end up with a ton of common stages named 'Complete'.

I cannot think of an advantage to making new (seemingly duplicated) stages, other than the flexability to delete a stage when there are no tasks in that stage on a per project level.  But that should have already been possible by simply unlinking the project from the stage (not actually deleting the stage).

**Comment by antonylesuisse** [comment]
No the problem with shared stage is that the sequence might not be correct among all projects. So if somebody drag and drop a stage they might mess other project.

As @tde-banana-odoo said, it is possible to share stages among projects using the m2m on stages. The fields is missing on the form view we will fix it today.

**Comment by sbuttgereit** [comment]
I want to echo @jaredkipe.  Since version 8 there's been some serious regression in the usefulness of the projects module related to the way stages work.  Computers are really suppose to be in service of the human user by automatically handling repetitive tasks and by allowing the simple reporting of like information.  With the removal of default task stages ( #9030 ) and the introduction of this intended behavior, we now put the humans in service of the computer.  This design is not helpful.  Yes, you can "easily" create new stages from the Kanban view... but why when a standard project format should be available as a default?  Easy or not: utter waste of time for a person to do this repetitive work.  And then, if you do it the easy way... this issue makes it clear you cannot get consistent reporting across projects.

I would strongly urge you to reconsider how to implement the features around project management; if per project ordering is a problem... that problem is solvable without making the projects module less useful.

**Comment by JoshuaQ** [comment]
I totally agree. The behavior of Odoo version 9 is very confusing and worse functionality. I do not understand the advantage that each project has to have their own states and there is no standard way to work in the company.

**Comment by jaredkipe** [comment]
I'll throw together a simple module to run a background task that collapses all stages to the first one by name.  (i.e. one of `SELECT min(id), name FROM project_task_type GROUP BY name;`)

That said, if you need the same columns over and over, you're better off making a 'template' project with columns and/or tasks, inactivating that project, and then just duplicate that project every time you need a new one from the template.

**Comment by maltehelmhold** [comment]
it's the worst **worsification** ever and odoo 9 annoys me every day 5 times with this crappy duplicate canban stages...

**Comment by fpodoo** [comment]
Note that stages can be shared amongst projects in Odoo 10. (and I think it
was the same in Odoo 9)
Just configure your stages that way, in debug mode:

http://www.awesomescreenshot.com/image/1929051/7fe453d24927e018bcbd2f3bd8ca00f3

Odoo 9/10 is actually the best of the two worlds; you can share stages or
not, depending if you want flexibility (and project managers can customize
their own projects) or consistency.

**Comment by joetaras** [comment]
I've this problem too with Odoo 10.0. List of stages has a loto of repeated stages (a set for every project). Is very hard to manage. For me, in this context, this list is unuseful. I can't share my stages accross the project. The link posted by fpodoo is not recheable.

Thanks in advance for every advice

**Comment by bistaray** [comment]
![](http://i.imgur.com/28QQbzZ.png)

This is how you share stages across any number of projects (I am guessing this is the same information in the expired screenshot link that was shared).

If you want a project to have the same stages as an existing project, duplicate that project.

If you want ALL projects to have the same stages, create an empty project called 'TEMPLATE' and duplicate it each time you create a new project.  You can even add default project tasks and these will be part of every project that is duplicated from this template.

**Comment by Nouagie** [comment]
Still on the same issue, but maybe there are more recent threads.

It's not very productive, this way of working. Working with a so-called 'template'-project (which is not really a template), gives you more work then really needed. Can't there be a real template-option, let's say, when you create a new project?
What also bothers me in the Kanban-view, if there aren't any projects in a certain task, the column isn't visible. So, I can't drag and drop a project to a task where there aren't any task already. I have to click and click and click, and I will get there in the end. Or is there a way to make all the tasks visible in the Kanban-view, whether or not there are any projects in it?

**Comment by jl2035** [comment]
I also don't like the current behavior. I haven't yet tried Odoo 11, is it any different?

**Comment by tde-banana-odoo** [comment]
Hello,

There are discussions on how to handle "template" projects in Odoo v12, either inactive projects that you copy or bringing back the template feature. Nothing is decided currently but having feedbacks on people using project templates is always usefull cc @jem-odoo .
