### ISSUE TITLE
[9.0] hierarchical custom model: parent_id / child_ids

### ISSUE THREAD

**Issue by thanhchatvn** [odoo/odoo#8662]
- model have 2 field: parent_id = fields.Many2one(self.model) and child_ids = fields.One2many(self.model, parent_id...)
- form view define and add child_ids,
- action: click this form view, add all data, next step click add new item for field: child_ids
- result: error ( error from field parent_id )
- Hope odoo fix it, so happy with odoo 9

**Comment by odony** [comment]
Hi, you should probably copy/paste your source code example or provide a link to it, and also copy/paste the exact error message and traceback you received.

**Comment by thanhchatvn** [comment]
Bug 2: when i xpath to product core form view, error when element is "string"
Example: I xpath to ''product_template_form_view' view form project.template
![selection_003](https://cloud.githubusercontent.com/assets/3313064/10182857/8f70bf26-6753-11e5-9d0d-46e52bb84c36.png)


<xpath expr="//label[@string='Product Name']" position="attributes">
                <attribute name="invisible">1</attribute>
            </xpath>

**Comment by odony** [comment]
@thanhchatvn Read the error message: view inheritance based on `string` attribute is forbidden in Odoo 9. Because of the new translation system `string` attributes are translated before applying the inheritance, so there is a good chance the XPath would fail. That's a limitation in Odoo 9.

**Comment by thanhchatvn** [comment]
@odony : thanks for support me, but core addons odoo ( inside 1 form view) have 2 page with 2 element ( example: page string='A' and page string='B') how to xpath 2 elemement, can not find any attribute 2 page :))). 
Thanks you so much

**Comment by andreparames** [comment]
@thanhchatvn You can use indexes in XPath, like `//page[2]` (note: it starts from `1`, not `0`).

**Comment by thanhchatvn** [comment]
@andreparames : ok, many thanks (y)

**Comment by Yenthe666** [comment]
Closing as this was answered & a workaround was proven.
P.S: Watch out with indexing xpaths like `//page[2]`. If you ever add more pages and before page 2 the meaning of `//page[2]` could be referring to another page 😉
