### ISSUE TITLE
[8.0] AssertionError while delete event from calendar

### ISSUE THREAD

**Issue by kkosobudzki** [odoo/odoo#8663]
I have calendar with popup:

``` xml
        <record model="ir.ui.view" id="action_id_availability">
            <field name="name">my_name</field>
            <field name="model">my_model</field>
            <field name="sequence" eval="1"/>
            <field name="arch" type="xml">
                <calendar string="Calendar" date_start="date_start" date_stop="date_end" color="training_place"
                          event_open_popup="%(popup_id)d">

                    <field name="training_place"/>
                </calendar>
            </field>
        </record>
```

I can view and edit item, but while editing I'm getting error:

> ...
> File "/Users/Krzychu/Documents/odoo-8.0-20150524/openerp/workflow/helpers.py", line 14, in **init**
>    assert isinstance(record_id, (int, long))
> AssertionError

What I've investigated is `record_id` is passed as string. I can remove events from `form` view.

Is there any way to add custom popup for creating events?

**Comment by kkosobudzki** [comment]
Any progress with this one? An answer will be highly appreciated.

**Comment by Yenthe666** [comment]
Hi @kkosobudzki,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by mayankksolves** [comment]
It still reproduce this issue on Odoo 10

**Comment by Yenthe666** [comment]
@mayankksolves please do make a new bug report then!
