### ISSUE TITLE
Odoo still uses EUR as base currency for Sales Order price

### ISSUE THREAD

**Issue by aldennis** [odoo/odoo#8665]
Steps to produce:
- Create a new demo database with Sales installed and multi-currency enabled
- Set default currency to PHP (or any non EUR currency)
  - Navigate to Accounting/ Configurations/ Miscellaneous/ Currencies and select PHP
  - Set first the exchange rate to 1.0 then Save
  - Edit the record again and select Base then Save
- While on the Currencies menu, select EUR then edit
  - Make sure Base is not selected
  - Enter a new exchange rate value in reference to 1 PHP (1 PHP = 0.0192 EUR)
- Create a new Sales Order then add product lines.
- Notice that the amount in the product lines is not equal to the List Price amount indicated in the Product form. This is because Odoo compute the price as List Price / EUR exchange rate.

**Comment by pedrobaeza** [comment]
The currency used is the one from the pricelist, so if you set the pricelist as EUR, the conversion is done. Closing as no real issue.

**Comment by manan-ft** [comment]
@pedrobaeza How do you change the currency in pricelist?
I am facing the same issue, the default currency on sales order is EUR even when my default currency is AED

**Comment by pedrobaeza** [comment]
Enable multiple currencies in configuration for seeing the field in pricelists.

**Comment by manan-ft** [comment]
@pedrobaeza Found my answer
1. Go to Settings>User>Select Sales Price List for User
2. Refresh the Sales page
3. On the left hand side you will see a Pricelist configuration page, change the currency for the default pricelist
