### ISSUE TITLE
[6.1]Barcode is swapped when printing multiple reports at a time.

### ISSUE THREAD

**Issue by prabhu2308** [odoo/odoo#8667]
I have installed tr_barcode module. When printing more than one reports with barcode at a time, the barcode of one report is printed in another report. The second report barcode is just skipped. Does anybody come across this situation or have idea on what causing the issue?

Thanks

**Comment by mart-e** [comment]
Hello,

Sorry but the 6.1 is no longer supported. Please check if still present in 7 or above versions.
