### ISSUE TITLE
[9.0] Sales Order / Quotations

### ISSUE THREAD

**Issue by mrmango** [odoo/odoo#8669]
Community Version:

When view the tree for quotations or sales order lines within the order itself, the headers are not formatted correctly.  See attached screen shot. It does seem when a new column has been added.
![screenshot_2015-09-23_11-02-26](https://cloud.githubusercontent.com/assets/612731/10042413/aadd371a-61e2-11e5-9111-2f965f92eeab.png)

This is using Firefox 40.0.3

**Comment by Yenthe666** [comment]
Hi @mrmango,

This issue is no longer present in the newest Odoo 9.0 version.
Closing this issue for that reason!

Regards,
Yenthe
