### ISSUE TITLE
stock.location complete name is stored, so not translated

### ISSUE THREAD

**Issue by guewen** [odoo/odoo#867]
The complete name of a `stock.location` (`complete_name` field) is a `fields.function` which is a stored field (stored={triggers}).

The thing is that `complete_name` is composed with the `name` field which is translatable. Hence, the `complete_name` is computed with the language of the last user that did a change and stored in that language.

We have a use case here where 4 locations have the same `complete_name`:

> Physical Locations / Company / Stock

This happens because the users use the French translation, so they create a new location, change the name of the location (but the source name of the location is still `Stock`). The `complete_name` has been stored in English, so all records have the same `complete_name` based on the English translation.

I can see others use cases where users use several languages and the complete names appear in French or Italian or German according to the last one who changed the location.

**Comment by clonedagain** [comment]
@mart-e I think it's acceptable to recompute the value for each language, that's what I'd have expected. There will be rarely many languages, and locations normally don't change often either.

**Comment by Yenthe666** [comment]
Dear @guewen,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
