### ISSUE TITLE
[9.0] [currency_update]:problem in country onchange in company information

### ISSUE THREAD

**Issue by kalpana-hemnani** [odoo/odoo#8671]
Hello,

When we select/change Country in the Company address information, it by default updates the country's currency in Company information.

There only two 'active' currency(EUR, USD) which are provided by default, others are by-default 'de-active'.

The problem is when the updated currency is other than these two, and environment is multi currency, at that time I am not able to select/see company's country's currency in currency selection.

![currencies odoo](https://cloud.githubusercontent.com/assets/14803014/10043192/95dd5c38-620e-11e5-9db4-27bc9ee98841.png)
![editing company information](https://cloud.githubusercontent.com/assets/14803014/10043193/961773fa-620e-11e5-9a28-42d688f00933.png)

Thanks and Regards,
Kalpana Hemnani

**Comment by redykely** [comment]
Worse, an untrained user attempts to create a currency (eg OFI), and gets a duplicate error.
TODO: create a complete view of currency management (display, activation, update)
DO: plug in the company, or should appear where the choice of a currency, allow access to all currencies already present in the database.

**Comment by pedrobaeza** [comment]
@apr-odoo is this solved? Any way, this is enterprise. Shouldn't they fill an OPW ticket instead of this?

**Comment by Yenthe666** [comment]
@pedrobaeza as you can see in the screenshot it is a community version though. I'm actually going to guess this is an Odoo 8, which is EOL.
Anyways, either if it is community or enterprise you can always report it here. If you have an enterprise license you're better off using it though. 😉

**Comment by pedrobaeza** [comment]
Yeah, right, but then he is talking about the community module, not Odoo, because currency update feature is only enterprise. Then I close this, because it's out of scope.

**Comment by Yenthe666** [comment]
Yes. It will either be a community app or a V8. 😉
