### ISSUE TITLE
[9.0] web.assets_common problem

### ISSUE THREAD

**Issue by lem8r** [odoo/odoo#8674]
I have installed npm, lesssc, clean-css.

Unable to run latest revision of Odoo 9 on my computer
```
2015-09-22 14:23:30,914 16816 WARNING odoo9-test2 openerp.addons.base.ir.ir_qweb:  Error: Error opening fileThis error occured while compiling the bundle 'web.assets_common' containing:
    - /web/static/src/less/mimetypes.less
    - /web_planner/static/src/less/web_planner_common.less
    - /web_editor/static/src/less/web_editor.less
2015-09-22 14:23:31,801 16816 WARNING odoo9-test2 openerp.addons.base.ir.ir_qweb:  Error: Error opening fileThis error occured while compiling the bundle 'web.assets_backend' containing:
    - /website/static/src/less/import_bootstrap.less
    - /web/static/src/less/enterprise_compatibility.less
    - /web/static/src/less/utils.less
    - /web/static/src/less/modal.less
    - /web/static/src/less/notification.less
    - /base_import/static/src/less/import.less
    - /web_tip/static/src/less/tip.less
    - /web_calendar/static/src/less/web_calendar.less
    - /web_diagram/static/src/less/diagram_view.less
    - /web_kanban/static/src/less/kanban_dashboard.less
    - /web_kanban/static/src/less/kanban_view.less
    - /web_settings_dashboard/static/src/less/dashboard.less
```
Looks like lessc include-path problem to me.

A week ago earlier revision of 9 was running fine with same setup procedure.

**Comment by mart-e** [comment]
Hello,

Please give the exact revision (commit reference) of the code you are running, how you are running it and at which action do you have this. As the 9.0 is still not fully stable yet, always test from a new database to see if it fixes your issues.

**Comment by lem8r** [comment]
Hi!
I was testing 3b87ef6ddad67b4bd7f51dbf5c2eb982fa4330e4
and odoo_9.0rc1.20150923.zip nightly build
both with same results.
```
cd odoo-9.0
./openerp-server -w **password** -r odoo --db_host 192.168.1.3 --xmlrpc-port 8070 --addons-path=$PWD/addons,$PWD/../odoo/odoo-addons
```
Then I opened http://127.1:8070/web/database/manager
And created new database
In process of creation I got this errors on command line
and same text in browser

![odoo10](https://cloud.githubusercontent.com/assets/5942291/10046374/21dc13a8-6211-11e5-86e8-7a62bf1e8dad.jpeg)

**Comment by lem8r** [comment]
When I've installed `website_blog` as was stated here #8676
there was no errors any more

**Comment by mart-e** [comment]
Is it possible you have created the database before installing `lessc` ? cf [Simon's comment](https://github.com/odoo/odoo/issues/8676#issuecomment-142604450)

Closing as probably duplicated of #8676 (or just a deployment issue)

**Comment by lem8r** [comment]
Nope, lessc was installed before. I was testing Odoo 9 last week with no errors.
Yes, seems like duplicate.
I'm using OpenSUSE, probably that's why my error logs are different.

**Comment by mart-e** [comment]
Also check the version of lessc. Should be at least 1.4.2

**Comment by lem8r** [comment]
lessc 2.5.1

**Comment by duanyp1991** [comment]
@lem8r  Try `sudo npm install less@1.4.2` to downgrade lessc to version: 1.4.2, maybe your version is too high.

**Comment by buldi** [comment]
whereis lessc

**Comment by zarzarsan28** [comment]
sudo ln -s "$(which nodejs)" /usr/bin/node
sudo apt-get install -y nodejs
sudo npm install -g npm

Install Less and accessories:
sudo npm install -g less less-plugin-clean-css
