### ISSUE TITLE
[9.0] Could not execute command 'lessc'

### ISSUE THREAD

**Issue by jbeficent** [odoo/odoo#8676]
Hello,

I'm facing an error message "Could not execute command 'lessc'" when trying to run Odoo 9 from sources, on a fresh demo database.

Only if I install the module 'website_blog' will this error disappear.

My current setup: 
* Ubuntu: 14.04
* Less Compiler: lessc 2.5.1

**Comment by Yenthe666** [comment]
@jbeficent 

I had this issue once before on a clean install too. Are you sure you're using the latest versions?
Have you installed these packages?
```
sudo apt-get install node-clean-css
sudo apt-get install node-less
```
Yenthe

**Comment by jbeficent** [comment]
Yes, I installed them already.

**Comment by Yenthe666** [comment]
https://github.com/odoo/odoo/issues/8440
@xmo-odoo I guess I'm not the only one with this issue so there has to be something triggering this.
@lukebranch seems we found ourselves a third guy.

**Comment by sle-odoo** [comment]
If the first time you run odoo you don't have lessc installed, the asset will be generated and this text will appear. Thenn when you install lessc and refresh the webclient, the assets are not re-generated and this text stay. One solution is to delete the lines containing "asset" in the ir.attachment table.

**Comment by sle-odoo** [comment]
(installing website_blog or any module adding assets in the bundle will invalidate them from the cache and regenerate them)

**Comment by hannwong** [comment]
@sle-odoo I deleted the entire Postgres instance, and recreated it. There are no other Postgres instances in the machine. The message is still there.

When you say `delete the lines ... in the ir.attachment table`, did you mean something else other than the Postgres database?

**Comment by andybak** [comment]
Surely there should be a simple command to invalidate all cached assets?

**Comment by cuijartija** [comment]
Just execute this:

sudo apt-get install curl npm && curl -sL https://deb.nodesource.com/setup | bash - && apt-get -y install nodejs && npm install -g npm && npm install -g less less-plugin-clean-css

After that you need delete database and create a new one.

The complete manual here: http://misnotasdelinux.blogspot.mx/2015/10/instalar-odoo-9-en-debian-8.html

Have fun

**Comment by sle-odoo** [comment]
@hannwong i was talking about the postgres instance of your database. If your database name is 'foo', then type 'psql foo' and run 'delete from ir_attachment where name ilike '%asset%';'
@cuijartija just ```apt-get install node-less node-clean-css``` is sufficient.
@andybak at the moment there isn't, so delete from the ir.attachment tables the lines containing 'asset'.  I have a commit allowing to not save in database a faulty asset, but it's part of a series of commit regarding ir.qweb that should be reviewed carefully before being merged.

**Comment by cuijartija** [comment]
@sle-odoo you are wrong, it depends of Linux version and distribution, my command works for almost all versions of debian and derived flavors.

**Comment by hannwong** [comment]
@sle-odoo I deleted the entire RDBMS, then created it anew (re-initialize the data folder of postgres, and such).

Before that, I did try deleting just the suggested rows of the Odoo database, and then moved on to deleting the whole Odoo database.

**Comment by Zirkonix** [comment]
I have the same problem on Odoo 9.0 running on windows. Installing the missing modules didn't fix the issue, I had to manually delete rows from the ir.attachment table.

Even after doing so. the problem persists if I create a new Database.

**Comment by kobra34** [comment]
Hello
First computer use "odoo 9.20151001" version.
second computer use "odoo 9.20151020" version
But first computer to second computer restore file problem.

"This error occured while compiling the bundle 'web.assets_backend' containing"

**Comment by kobra34** [comment]
I solved the problem

odoo 9.2015.10.1 download and install windows version

copy web-site less file and mail less files old server folder 

Its work

**Comment by f-ewald** [comment]
What do you mean? Which files should I copy where @kobra34 ?

**Comment by kobra34** [comment]
asks the missing files, finding the old version, you manually add

**Comment by f-ewald** [comment]
Ok, thanks for the answer. I found out that in my case a wrong symlink to nodejs was causing the trouble.

**Comment by nick2474** [comment]
I get lucky executing 

sudo apt-get -y install curl npm && curl -sL https://deb.nodesource.com/setup | bash - && apt-get -y install nodejs && npm install -g npm && npm install -g less less-plugin-clean-css

Thank you @cuijartija

**Comment by ge2kaslt** [comment]
Found solution for windows, install - nodejs (on x64 i have installed node-v5.8.0-x64), and then run command from cmd in nodejs folder - npm install -g less less-plugin-clean-css

**Comment by ruuter** [comment]
It still happens every time you install new app, but doing `sudo service odoo restart` will fix it.

**Comment by AlkhatibHamad** [comment]
I faced this problem before and it have been solved ,

open terminal and execute this command 

sudo apt-get install node-less

I hope it works for you too

**Comment by stephen144** [comment]
For those using systemd, make sure your service file can get to lessc. Something like:

`Environment=PATH=/usr/bin`

**Comment by casper34a** [comment]
If somebody had the issue inside PyCharm wich was my case and nothing else works... 
I leave my solution here:
First: I tried to check if node and npm exist inside my virtualenv: node -v and npm -v, not any of them...
Second: I was using virtualenv and odoo11, also when I ask inside my virtualenv with: which lessc . I didn't receive any response neither, so... I keep googling and found this post: https://stackoverflow.com/questions/8986709/how-to-install-lessc-and-nodejs-in-a-python-virtualenv

In any case this was what I did on my virtualenv:
MYVIRTUALENV/bin/activate # switch to my Python virtualenv first
pip3.7 install nodeenv # install nodeenv nodeenv was installed
nodeenv --python-virtualenv # Use current python virtualenv
npm install -g less # install lessc in the virtualenv
npm install -g less-plugin-clean-css # also install this less-plugin...

then if I check with node -v and npm -v I get a proper response...
also get good response on: which lessc

After that no more nightmare with lessc execution in pycharm
