### ISSUE TITLE
[9.0] Admin user cannot list local modules

### ISSUE THREAD

**Issue by jbeficent** [odoo/odoo#8678]
Using Odoo 9 from sources on a fresh demo database, the admin user is not able to list the local modules or update the local modules. The field 'technical settings' that was available in Odoo 8 is not listed now in the user form.

Is the install of local modules only available from command line as of version 9?

**Comment by jni-odoo** [comment]
Hello jbeficent,

In odoo 9 , they are apps (modules) , click on the option Apps , you will get list of apps that you can install..
https://drive.google.com/file/d/0B5j41T1Hqv1sTnFYSncwRlk3emM/view?usp=drivesdk
http://goo.gl/9hPlFP

Install the ones you want , and there are already filters (installed, Not Installed etc)..

Regarding the technical settings : You have to Activate the Developer Mode for that , and then automatically the technical features will be enabled to the current user ..

https://drive.google.com/file/d/0B5j41T1Hqv1sbnBlVFhnN2Y3Rk0/view?usp=drivesdk (click on About odoo) 

https://drive.google.com/file/d/0B5j41T1Hqv1sMmhwa1hOWVRUMU0/view?usp=drivesdk
(Click on "Activate the Developer Mode")

This may help you..

Thanks ,
Nikunj Jani (Odoo India)

**Comment by jni-odoo** [comment]
No separate option on user form "Technical Features"

Thanks ,
Nikunj Jani (Odoo India)

**Comment by jbeficent** [comment]
Thanks. Now closing it. I just bumped into this other. https://github.com/odoo/odoo/issues/8681

**Comment by doanvanthien** [comment]
Thank you.
