### ISSUE TITLE
[8.0] - Follow-Ups - "%" prohibited

### ISSUE THREAD

**Issue by jdegoy** [odoo/odoo#8680]
Impacted versions:

 - 8.0 and up?

Steps to reproduce:

 1. Maintain a follow-up level Letter text.
 2. add "%" to the content.
 3. Do a manual follow-up for the level in question to generate the report form (pdf).

Current behaviour:

 - Traceback

Expected behaviour:

 - Warning on maintenance of the text => Isolated "%" character is prohibited. If you'd like to add % to the letter text please use "%%" instead. Perhaps add the same info to the help text (in light grey). 
- An alternative fix would be to automatically substitute anything that doesn't format as "%(xxxx)s" but contains "%" with "%%".

**Comment by beledouxdenis** [comment]
Hello Janik, 

I just tried to reproduce this issue, and I had the expected result that you want when I tried.

See below video:
https://drive.google.com/file/d/0B5GVjjwUC-ygOW1EeTRRSi1PYm8/view?usp=sharing

Did I miss something ?

Regards,

**Comment by jdegoy** [comment]
Hello Denis,
Indeed I forgot to mention you need to add the % using another language.
It doesn't check whether the translations contain %.

Thanks for your help,
Janik

**Comment by jdegoy** [comment]
In our situation the "master' text doesn't contain %. But the translations do...

**Comment by beledouxdenis** [comment]
Indeed ! I just solved this in Odoo 8.0 :).

Thank you for the report.

**Comment by jdegoy** [comment]
Thank you magic number says Béné :-)
Have a good one!
