### ISSUE TITLE
[9.0] Bill of Materials: Product Variant Error

### ISSUE THREAD

**Issue by jnegrete** [odoo/odoo#8688]
Throw a JavaScript error when clicking on bom's product variant many2one field.
Error: Expected ")", got "]"

![error variant in bom](https://cloud.githubusercontent.com/assets/4744682/10053677/0c43a218-61f3-11e5-9ee1-3865f297afe1.png)

Fix:
Add ")" to product_id domain at mrp_bom class

before:
'product_id': fields.many2one('product.product', 'Product Variant',
            domain="['&', ('product_tmpl_id','=',product_tmpl_id), ('type', 'in', ['product', 'consu']]",
            help="If a product variant is defined the BOM is available only for this product."),

after:
'product_id': fields.many2one('product.product', 'Product Variant',
            domain="['&', ('product_tmpl_id','=',product_tmpl_id), ('type', 'in', ['product', 'consu'])]",
            help="If a product variant is defined the BOM is available only for this product."),

**Comment by jco-odoo** [comment]
Not solved in the meantime?

**Comment by jnegrete** [comment]
solved, thanks
