### ISSUE TITLE
[9.0] The tooltip in the graph view is hidden.

### ISSUE THREAD

**Issue by Zirkonix** [odoo/odoo#8691]
The columns tooltip are hidden if the column is too high, as shown in the screenshot.
![dashboard](https://cloud.githubusercontent.com/assets/8126068/10056607/d93e6fee-6209-11e5-9f3b-0ebde32707c3.png)

You can reproduce this issue with the [runbot version 9.0](http://103336-9-0-fixes-nim-ed5eec.runbot6.odoo.com/web?debug=1#view_type=graph&model=crm.lead&menu_id=335)

This happens in Chrome, Firefox, and IE 11.

**Comment by pedrobaeza** [comment]
This has been solved in latest 9.0 versions:

![seleccion_003](https://user-images.githubusercontent.com/7165771/38530663-116fb884-3c6c-11e8-8720-f19190ceb5d3.png)

Thus, I close the issue.
