### ISSUE TITLE
Translation German from Contract to Verträge FAIL BUG

### ISSUE THREAD

**Issue by diezcode** [odoo/odoo#8694]
Hello,

When I install Odoo with the English language pack, and then I wanna load the german language. The Contract can not be translated, all words are in german, but not the contract or contract to renew.

Why is that so ? I can't change it on settings -> translations . 

I think it's a bug.
![bug-translation-contracts](https://cloud.githubusercontent.com/assets/7522882/10067566/fb04b1b2-629d-11e5-8312-dca0e719fb64.PNG)

![contracts-bug](https://cloud.githubusercontent.com/assets/7522882/10067570/ff8ca99c-629d-11e5-92b7-099eb450e752.PNG)

**Comment by mart-e** [comment]
Hello,

We had an issue with the terms published [on Transifex](https://www.transifex.com/odoo/odoo-8/). It was the terms from `account_analytic_plans` instead of `account_analytic_analysis` (which contains the menu you wish to translate).

But the menu is translatable, don't worry.

**Comment by diezcode** [comment]
It's not working, I need the res_id of this Contracts to translate???

**Comment by mart-e** [comment]
No, don't start creating translations directly from the translated terms menu. Instead go directly to the object in `Settings > Technical > Menu Items` were you can set translations for the menu.

![screenshot from 2015-09-28 14-17-20](https://cloud.githubusercontent.com/assets/564822/10135129/a82374a0-65eb-11e5-8aef-73f469735658.png)

**Comment by diezcode** [comment]
Okay it worked perfectly. Thank you mate
