### ISSUE TITLE
[9.0] Translation possibility is missing for mail template body parts

### ISSUE THREAD

**Issue by rruebner** [odoo/odoo#8698]
Hi all,

it is no longer possible to translate mail template body parts in odoo version 9.

***Impacted versions:***

 - 9.0

***Steps to reproduce:***

* in runbot version 9 activate the developer mode
* install another language
* go to Settings -> Technical -> Email -> Templates
* open any mail template and click on edit

***Current behavior:***

* you don't have the possibility to translate the mail template body part

***Expected behavior:***

* possibility to translate the mail template body part like in version 8

Regards, Robert

**Comment by nle-odoo** [comment]
Hello, 

It should be solved with 7c67091a960098787fe908680442f8ab6acf9e51

Thanks for your report.

**Comment by rruebner** [comment]
:thumbsup: thank you.
