### ISSUE TITLE
[9.0] Quotation report

### ISSUE THREAD

**Issue by SBollatti** [odoo/odoo#8707]
If
- Company name: Enough long
- Company Address: enough long

- Customer name: enough long
- Customer Address: enough long

then quotation report would be without information like:
![aca](https://cloud.githubusercontent.com/assets/11006126/10082017/16f1745c-62ce-11e5-99a7-10d04a9e2ef8.jpg)

- Missing full Customer name, address, shipping address, etc
- Also notice the Quotation date and time ...weird

**Comment by SBollatti** [comment]
Still Waiting

**Comment by sle-odoo** [comment]
duplicate of #8707

**Comment by joolsr** [comment]
have you closed the wrong one ? 8707 is referenced but is this bug report.
Which is the other one then ?

Julian
