### ISSUE TITLE
[14.0][BUG] One2Many new record form

### ISSUE THREAD

**Issue by ilyasProgrammer** [odoo/odoo#87192]
Impacted versions: 14.0, 15.0.
It works on 13.0

Steps to reproduce:

1. add new O2M field to any existing model. E.g.:

```python
class SaleOrder(models.Model):
    _inherit = "sale.order"

    option_ids = fields.One2many('my.option', 'sale_id')

class MyOption(models.Model):
    _name = "my.option"

    sale_id = fields.Many2one('sale.order')
```

2. Add access to your new model.
3. Change sale order form view and add:

```xml
<field name="option_ids" context="{'default_sale_id': active_id}"/>
```

Current behavior: 
When you click Add New Line form for my.option will be opened, but you wont see origin (sale.order) reference. sale_id field will stay empty. If you save record, then sale_id will be set. But if you want to use sale_id right away after form for your new record is created (for domain or another purpose) then you wont be able to do it.

Expected behavior: origin field should be set right away.

How to fix:

you can fix it like this:

```python
class MyOption(models.Model):
    _name = "my.option"

    sale_id = fields.Many2one('sale.order')

    def onchange(self, values, field_name, field_onchange):
        if "sale_id" in values and field_name != "sale_id":
            values.pop(
                "sale_id", None
            )  # otherwise it will be removed from the defaults
        return super(MyOption, self).onchange(
            values, field_name, field_onchange
        )
```

Problem here is that at the moment when form is opened onchange is called, containing sale order data in the sale_id (in values). In the default get you can see piece of code that checks for presence of fields in the values. And if field is found then default_get will exclude this field from defaults. Code above just shows that this part works wrong.

Odoo 13 has no such problem.

**Comment by yelizariev** [comment]
It's kind of intentional behavior. Even if we set `sale_id` on the o2m form, it won't work if Sale Order is not created yet.

So, I'd recommend to add a button  "Create line" on the parent form. This way sale order form is automatically saved and o2m forms shows up. Example:

https://github.com/odoo/odoo/blob/10378872eddd6037f479fa8cbb3ed65d5e4b52c6/addons/account/models/account_journal_dashboard.py#L395-L412

**Comment by pedrobaeza** [comment]
I would say that the official way to access fields from the children is to use `parent.field_in_parent_model`.
