### ISSUE TITLE
Projects are displayed in seemingly random order

### ISSUE THREAD

**Issue by NL66278** [odoo/odoo#8721]
When adding projects a user will expect them to show up in alphabetic ordering in lists and kanban views. The appearance of the projects seems totally random, although in the code I can see there is an ordering on sequence and id.

As I can see no way to influence the sequence of projects (like I can do with tasks by moving them with the mouse), I think an alphabetic ordering is the only ordering that makes sense.

**Comment by Yenthe666** [comment]
:+1: I've thought the same many times.

**Comment by pedrobaeza** [comment]
The order now in v11 is `sequence, name, id`, so we can consider this as attended, and thus I'm closing.
