### ISSUE TITLE
[BUG] website_sale: Search Bar Shows HTML Description in category search

### ISSUE THREAD

**Issue by vickyodoo** [odoo/odoo#87260]
Impacted versions: 15.0 Community  / Enterprise

Steps to reproduce: 

1. Enable Ecommerce Category from the customized Menu
2. go to the Desk Category 
3. Edit Page and Drag Drop the Banner Snippet In Category Page.
4. Save the Page and Search "Desk" Category in Search Bar. 
it will show the HTML Content in the search after the name of the Category

Current behavior:

it shows HTML in the description while searching.

Expected behavior:

Need to remove Description from the Category Search.

Video/Screenshot link (optional):

https://watch.screencastify.com/v/gQAXIETks0emh7r5mKXz

Support ticket number submitted via odoo.com/help (optional):
Ticker Number :- #2804766

**Comment by Yenthe666** [comment]
@qsm-odoo maybe for you to check?

**Comment by qsm-odoo** [comment]
Confirmed, we will fix this :+1:

**Comment by rdeodoo** [comment]
Fixed at https://github.com/odoo/odoo/pull/86575#pullrequestreview-921521680
