### ISSUE TITLE
[9.0] Analytic Account on PO order line Invalid Field error

### ISSUE THREAD

**Issue by rowemoore** [odoo/odoo#8727]
To add the analytic account field to the PO order line you need to go to accounting->settings->analytic accounting.

When creating a PO order line, trying to select Analytic Account throws error:

`raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'type' in leaf "<osv.ExtendedLeaf: ('type', 'not in', ['view', 'template']) on account_analytic_account (ctx: )>"`

**Comment by pedrobaeza** [comment]
This is not happening anymore, so I close. It was an invalid domain in the view.
