### ISSUE TITLE
[9.0] Point of Sale configuration menu error

### ISSUE THREAD

**Issue by sdaguet** [odoo/odoo#8731]
Hello,

Installing the current Odoo 9.0 from github (as of today this morning), the point of sale settings menu returns an error. See screenshoot hereafter.

![pos_settings_error](https://cloud.githubusercontent.com/assets/14848678/10117083/5d363702-6442-11e5-848f-532a270f4fe6.PNG)
Best regards

**Comment by mart-e** [comment]
Fixed at 0126c59dd3133f2cfab9528b467202632cd874fc (temporary fix)
