### ISSUE TITLE
Invoice via POS failed

### ISSUE THREAD

**Issue by phoenixsampras** [odoo/odoo#8736]
Hello,

When trying to get the invoice via POS, the following error occurs:

Traceback (most recent call last):
  File "/opt/odoo/v9/dev1/openerp/http.py", line 542, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/v9/dev1/openerp/http.py", line 579, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/v9/dev1/openerp/http.py", line 312, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/v9/dev1/openerp/service/model.py", line 149, in wrapper
    raise ValidationError(msg)
ValidationError: ('The operation cannot be completed, probably due to the following:\n- deletion: you may be trying to delete a record while other records still reference it\n- creation/update: a mandatory field is not correctly set\n\n[object with reference: account_id - account.id]', None)

What is the ACCOUNTING flow to setup this?? is there SAMPLE data for accounting?? the latest version is empty.

**Comment by jco-odoo** [comment]
Did you install one of the localization modules first?

**Comment by Yenthe666** [comment]
Hi @phoenixsampras,

Thank you for the report.
As there has been no response in years I'm closing this bug report.

Regards,
Yenthe
