### ISSUE TITLE
Installing Project without UOM -  Hours fails

### ISSUE THREAD

**Issue by RoelAdriaans-B-informed** [odoo/odoo#874]
Short description of the issue:
Project module needs the Hours unit of measure. It is possible to delete this UOM before installing project. Project module doesn't check and fails hard.

**_Impacted versions:**_
master, 7.0

**_Steps to reproduce:**_
1. Start with clean database
2. Install Product. Give technical features and Manage Multiple Units of Measure rights to admin user. 
3. Clean Hours and Days records in Products unit of measure
4. Install Project app.

**_Current behavior:**_

Throws an error:

```
  File "/home/bak/runbot/extra/runbot/static/build/04780-master-160ddc/openerp/addons/base/ir/ir_model.py", line 869, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % (xmlid))
ParseError: "External ID not found in the system: product.product_uom_hour" while parsing /home/bak/runbot/extra/runbot/static/build/04780-master-160ddc/openerp/addons/project/project_data.xml:5, near
<record id="base.main_company" model="res.company">
            <field name="project_time_mode_id" ref="product.product_uom_hour"/>
        </record>
```

**_Expected behavior:**_

 Add UOM category and records.

**Comment by morphace** [comment]
Still the same in 8.0. Is there a fix/workaround?

**Comment by Yenthe666** [comment]
Dear @RoelAdriaans-B-informed,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe

**Comment by RoelAdriaans-B-informed** [comment]
@Yenthe666 as you may have read in the comment above yours, this is also present in version 8..

**Comment by Yenthe666** [comment]
Hi @RoelAdriaans-B-informed,

Could you give this another try on the latest V8 code please? Ideally on a V9 or V10 too, since those have more priority and fixes are done faster there.
I'll re-open the issue for now.

**Comment by Yenthe666** [comment]
Hi @RoelAdriaans-B-informed,

As there has been no response and the support for Odoo 8 has stopped I'm closing this issue.
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
