### ISSUE TITLE
[8.0] Blogs on Website Builder not working. Synology DS214 DSM 5.2

### ISSUE THREAD

**Issue by g3ronimo76** [odoo/odoo#8741]
New Synology DS214, DSM 5.2-5592 Update 4, clean install of odoo 8. Everythink is working perfect, including Website Builder, Forum, eCommerce, Online Events but Blogs not working. Instalation of Blogs is OK but when i create new Blog Post i get 500 Internal Server Error.

"Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."

**Comment by paolovalier** [comment]
you should contact synology for that
my 2cents

**Comment by Yenthe666** [comment]
Hi @g3ronimo76 ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
