### ISSUE TITLE
[15.0] requirements.txt: Package requests has conflicting dependencies with urllib3.

### ISSUE THREAD

**Issue by Armitxes** [odoo/odoo#87444]
Impacted versions: 15.0
Steps to reproduce: Install fresh Odoo v15 instance and install the requirements.txt

Current behavior: Error
Expected behavior: No Error ;)

Video/Screenshot link (optional):
![This is an image](https://i.imgur.com/6WxCpSy.jpg)

requirements.txt got recently updated with urllib3==1.26.5.
https://github.com/odoo/odoo/blob/7701d85e2364bc4b59455338cc771733dbb12e73/requirements.txt#L38

apparently it conflicts with requests==2.22.0
https://github.com/odoo/odoo/blob/7701d85e2364bc4b59455338cc771733dbb12e73/requirements.txt#L37

Seems it can be fixed by either downgrading urllib3 or by upgrading requests.

**Comment by NL66278** [comment]
Same problem here.

**Comment by NL66278** [comment]
Solved with latest update to 15.0

**Comment by Armitxes** [comment]
Fix with latest sources confirmed. Closing the issue :)
