### ISSUE TITLE
[9.0] Whole view rendered in bold

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#8745]
**All configuration texts are in bold**

Impacted versions:

 - 9.0 and above

Steps to reproduce:

 1. Install sales
 2. Go to Sales > Configuration > Settings (http://103923-9-0-m2m-pos-fiscal-position-reba-f0f45c.runbot6.odoo.com/web?debug=#view_type=form&model=sale.config.settings&action=139)
 3. Everything is in bold
<img src="http://i.imgur.com/ByP6q8V.png" alt="Full bold screen"/>

Current behavior:

 - Everything is in bold

Expected behavior:

 - Only labels should be in bold

**Comment by qsm-odoo** [comment]
Merged
