### ISSUE TITLE
[9.0] Wordline-Sips acquirer not available at Accounting settings

### ISSUE THREAD

**Issue by aristobulo-eezee** [odoo/odoo#8747]
Sips acquirer is not being displayed at the list of available payment acquirer in accounting settings.

Tested in runbot.odoo.com
Branch: 9.0
Commit: bf4b47c94df8fda8f289681219674e345fdfa027

![no-sips-acquirer](https://cloud.githubusercontent.com/assets/8862626/10131894/c432fb42-65d3-11e5-893a-aeb9af107635.png)

**Comment by aristobulo-eezee** [comment]
@apr-odoo why is this in wishlist? payment_sips is already included in odoo, not being displayed in the list of acquirers should be considered as a bug not a wish

**Comment by rim-odoo** [comment]
I think it could be easy to fix... 2 lines in https://github.com/odoo/odoo/blob/9.0/addons/payment/views/res_config_view.xml

**Comment by Yenthe666** [comment]
@rim-odoo perhaps we can just add it? :smile:

**Comment by rim-odoo** [comment]
@Yenthe666 I think that the mighty @mart-e and his minions are working on it...

**Comment by Yenthe666** [comment]
Excellent work guys, thanks!

**Comment by mart-e** [comment]
Well, it is more complicated than it seems. In stable version we can not add a field and adding it in the `res.config` of `payment` would be very bad for the people not updating the module (you would end up with a revert and useless field like at dd84e612d0a5e509c25c4f0823b90649ffc74aff ).
Unfortunately to work, the config page needs to have fields stored in the database (I tried to circle that using computed fields, no luck).
So it seems it can not be done for 9.0, people will need to directly install the module paymnet_sips.
However it has already been fixed some time ago in master at fe4f8405f6b4034ac55cb180323f996c773107c7 version so it's available in the SaaS and future 10.

**Comment by aristobulo-eezee** [comment]
@mart-e wait wait, what? How is that it works for others acquirers but it can't work for sips? It works for paypal and sips was done using paypal acquirer as template. It should be possible.

**Comment by mart-e** [comment]
What I was trying to explain is that to add the option, you must add a field in payment configuration. You can not add a field in stable version as people doing a code update without upgrading the payment module would get an error (try applying fe4f8405f6b4034ac55cb180323f996c773107c7 in 9.0, go to Accounting > Settings, press "Apply" -> traceback).

The others payment providers have it as these were older and were added in master at that time. If you check, you will see that there is the same issue with payment_authorize. It is available in 9.0 but the option is not present.
The only option we have is to add in master, and it was done 8 months ago at fe4f8405f6b4034ac55cb180323f996c773107c7
