### ISSUE TITLE
[14.0] Bug: `AccessError` when opening project overview

### ISSUE THREAD

**Issue by SilvioC2C** [odoo/odoo#87483]
### Impacted versions:

- [ ] 13.0 (potentially)
- [ ] 14.0 ([tested on runbot](https://14041760-14-0-all.runbot31.odoo.com/))
- [ ] 15.0 (potentially)

### Steps to reproduce:

As tested on Runbot v14.0:
1. install module `sale_timesheet_purchase`;
2. create a project;
3. set its flags `allow_timesheets` and `allow_billable` both to `True`;
4. with a user that has Technical / Analytic Accounting (`analytic.group_analytic_accounting`) access rights, create a purchase order and assign the project's analytic account to at least 1 PO line;
5. confirm the PO, receive it and invoice it;
6. with a user that doesn't have Administration / Settings (`base.group_system`) access rights, but has Project / Administrator (`project.group_project_manager`) access rights, open the project dashboard and click on the "Overview" button of the project created at point 2.

### Current behavior:

An `AccessError` is raised:
![Screenshot from 2022-03-29 15-45-10](https://user-images.githubusercontent.com/87646954/160625683-c77e6897-7807-4b03-b841-e86235a52cb5.png)

### Expected behavior:

The project's overview is opened successfully.

**Comment by IT-Ideas** [comment]
Fixed by https://github.com/odoo/odoo/pull/87425
Thanks for having reported the issue.
