### ISSUE TITLE
Freely change other users name

### ISSUE THREAD

**Issue by GoodERPJeff** [odoo/odoo#8751]
I login runbot version 9.0 as demo user. 

I get some messages in my inbox, from administrator.

I click on the administrator name what links me  to a form view.

I click edit and change the partner name to Idiot

then I logout and login as admin, see my name on the top-right as idiot

I guess this workaround is working for 8.0 also

funny thing is **that needn't any access right to res.users object**

http://104040-9-0-sale-stock-fix-rim-c02ff8.runbot6.odoo.com/

**Comment by leangjia** [comment]
香烟瓜子矿泉水

**Comment by leangjia** [comment]
@Fabien

**Comment by leangjia** [comment]
@nim-odoo   Tks.

**Comment by carllhw** [comment]
Find the problem too.

**Comment by Yenthe666** [comment]
@apr-odoo any update here? 😉

**Comment by Yenthe666** [comment]
@apr-odoo ?

**Comment by pedrobaeza** [comment]
This is not possible anymore since a while, so closing.
