### ISSUE TITLE
Leave Requests to Approve error

### ISSUE THREAD

**Issue by Alembo** [odoo/odoo#8760]
OpenERP version 7.0-20140804-231303

We have employees with enough Remaining legal leaves and able to create a Leave Requests, but when trying to Approve we get:

Warning!
There are not enough ... allocated for employee ...; please create an allocation request for this leave type.

In one case the employee has 5 remaining days and wants to take 4.
The other has 5.78 and wants to take 5

**Comment by Yenthe666** [comment]
Hi @Alembo,

Thank you for your bug report.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
