### ISSUE TITLE
[9.0] no parent_id in account_analytic_account

### ISSUE THREAD

**Issue by ddrapeau** [odoo/odoo#8764]
Hi all.

I want, like with older versions, to create sub-projects to project. Before, there was the field parent_id and it does not exist in v9.0 ! Why ? Is it planned ? Or will it stays in this state ?

Thank you so much for your work guys !

**Comment by Yenthe666** [comment]
Hi @ddrapeau,

Sorry that nobody gave you a response earlier.
At the moment you can no longer create subprojects and assign them to projects in Odoo 9 (and 10).
There are no plans to change this (100% sure for V9 & V10). Perhaps V11 will see a change but I doubt it.

Regards,
Yenthe

**Comment by pedrobaeza** [comment]
You can check https://github.com/OCA/account-analytic/tree/9.0/account_analytic_parent module.
