### ISSUE TITLE
get_needaction_data should pass action's context to _needaction_count

### ISSUE THREAD

**Issue by JonathanStein** [odoo/odoo#8765]
The needaction count may depend on the menu action's context, but it's not passed to the counting function.

In ir_ui_menu.py, the current context is passed, but I think it should be merged with the actions context before calling _needaction_count
https://github.com/odoo/odoo/blob/a9e3d74713b6882c64617345696ad326d75a4745/openerp/addons/base/ir/ir_ui_menu.py#L345

Before trying to patch this, I would like to hear if there is a reason for not doing this?

**Comment by rco-odoo** [comment]
This explains why in some cases, some menus show a non-zero counter, but clicking on it shows zero record!

**Comment by rco-odoo** [comment]
@JonathanStein my pull request above is not the right fix.

One should fix the search view instead: when the user clicks on the needaction counter, the menu action is executed with `'search_default_message_unread': true` added in its context. This is effective only if the search view defines such a filter and its domain corresponds to the "needaction" domain.

Could you spot the menu items that are problematic?

**Comment by JonathanStein** [comment]
An object could need attention for several reasons, and I still believe, the context would be the right place to tell what reasons, we are counting.

Example: An order could need attention because it needs approval (state is "need_approval"), or because we need to make a special order from a supplier (state is "custom_order") - or because it's ready to ship (state is "ready_to_ship").

Now I would make three different menu items, leading to the same list view, but with different contexts (context="{'search_default_state': 'need_approval'}") and so on. I would like a need_action count on each menu item, but it should count the number of orders needing attention for the specific reason (not the total number orders needing attention).

Passing the context would enable me to do that (and I don't think it would be a problem for other uses).

The way I can do it now is by setting a domain on the actions, but then the user cannot just change the search expression - he would have to pick another menu item to show other orders.

**Comment by Yenthe666** [comment]
Hi @JonathanStein,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
