### ISSUE TITLE
[9.0 Enterprise] Tree view impossible to increase limit above 80 lines

### ISSUE THREAD

**Issue by fclementic2c** [odoo/odoo#8771]
When I click on 1-80 / 125 for ex. in the list of accounts ...nothing happen.
I cannot list more than 80 lines

**Comment by xmo-odoo** [comment]
You can edit it directly e.g. replace the 80 by 100 as if in a text field.

**Comment by fclementic2c** [comment]
Ok. But not easy to identify.

**Comment by xmo-odoo** [comment]
> But not easy to identify.

No, but afaik you'll have to take it up to fp, what little remains was basically sneaked by in the new "uniform" pager implementation.
