### ISSUE TITLE
Calendar view Tasks - planning several task within one day.

### ISSUE THREAD

**Issue by grantern** [odoo/odoo#8772]
In calendar view - day or week. Tasks are not shown with a starting time and ending time.
When you plan many small task they are all shown as all-day tasks.
If you create a task by clicking and dragging for instance task 1 start 09:00, end 11:00 and save it. It jumps straight up to All-day.
As a developer I have many tasks to perform during one day. I need to see them planned out during my day.
I guess all project managers need to be able to see tasks planned in this way.

Issues are working in good way.

**Comment by clxadmin** [comment]
Hi grantern

I'm facing the exact same issue -- do you find out a solution for that? ... I would be very interested in to it
thnx

**Comment by rqui** [comment]
Same here!, no solution yet?

**Comment by LehouxHugo** [comment]
Has anyone found a way ? Thanks !

**Comment by davinci41** [comment]
yes.

in project.task.calendar : 
calendar color="user_id" date_start="date_start" date_delay="planned_hours"  string="Tasks" mode="month">
                    <field name="name"/>
                    <field name="project_id"/>
                </calendar>

i form add  date_start

![image](https://user-images.githubusercontent.com/25403547/29795183-740c4092-8c4b-11e7-8275-aa0a8eef3d87.png)

**Comment by Yenthe666** [comment]
Hi @grantern,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
