### ISSUE TITLE
[8.0] new API: Writes to the database are LOST in computed fields methods!

### ISSUE THREAD

**Issue by michaelkarrer81** [odoo/odoo#8773]
I tried to write a computed field with store=True.

In my function i have to check (and somtimes update/write) the child categories if the current category is changed. 

**All of the DB-writes to the child categories are simply lost (not written to the DB) after the form is saved?!?**

```python
class product_public_category_menu(models.Model):
    _inherit = 'product.public.category'

    cat_css_showatchilds = fields.Text(string="CSS used at this and its Child Categories")

    cat_desc_showatchilds = fields.Html(string="Top-Description shown at Child Categories")
    cat_desc = fields.Html(string="Top-Category-Description")

    cat_descbottom_showatchilds = fields.Html(string="Bottom-Description shown at Child Categories")
    cat_descbottom = fields.Html(string="Bottom-Category-Description")

    cat_hide = fields.Boolean(string="Hide Category from Navigation")
    cat_root = fields.Boolean(string="Start Navigation from this Category")
    # Topmost parent category -
    # if any cat_root categories are found in the tree use the topmost category with cat_root=true and stop there
    cat_root_id = fields.Many2one(compute='_compute_root',
                                  comodel_name='product.public.category',
                                  store=True,
                                  readonly=True,
                                  string='Topmost Root Category')

    @api.one
    @api.depends('parent_id', 'cat_root')
    def _compute_root(self):
        # find the highest parent with cat_root = True (or self if self has cat_root=True and no higher cat_root exits)
        # or just the topmost parent if no category with cat_root exists (or self if no parent exists)
        self.cat_root_id = None
        cat = self
        while True:
            if cat.cat_root or not cat.parent_id:
                # ATTENTION: this is a workaround for onchange of cat_root boolean field - at save everything is find
                #            but before save cat.ids are empty - this is an odoo bug
                if cat.ids:
                    self.cat_root_id = cat
                    print "category.cat_root_id = %s" % cat.ids
                break
            else:
                cat = cat.parent_id

        # Todo: Recalculate all possibly affected child categories
        if self.ids:
            categories = self.env['product.public.category'].search(['&',
                                                                     ('id', 'child_of', int(self.id)),
                                                                     ('id', 'not in', self.ids)])
            for child_cat in categories:
                print "category child: %s" % child_cat.name
                child_cat.cat_root_id = None
                cat = child_cat
                while True:
                    if cat.cat_root or not cat.parent_id:
                        # ATTENTION: this is a workaround for onchange of cat_root boolean field - at save everything is find
                        #            but before save cat.ids are empty - this is an odoo bug
                        if cat.ids:
                            child_cat.cat_root_id = cat
                            #child_cat.write({'cat_root_id': int(cat.id)})
                            print "%s.cat_root_id = %s" % (child_cat.name, cat.ids)
                            print "TEST: child_cat.cat_root_id =  %s" % child_cat.cat_root_id

                        break
                    else:
                        cat = cat.parent_id
```

The child categories in `child_cat.cat_root_id = cat` are never really written to the Database. Even if there is no error raised and `print "TEST: child_cat.cat_root_id =  %s" % child_cat.cat_root_id'` wrongly suggest that it worked?!?

**Why are the changes to `child_cat.cat_root_id` not written to the Database (without any error message)?**

INFO: I tried the same code with @api.multi also with the same result

**Comment by rco-odoo** [comment]
@michaelkarrer81 IMHO you misuse the computation mechanism of fields.

The compute method must assign the value of the computed field on the records passed as self.  Those assignments are made in cache only.  After the compute method is called, the values of the field on self are read from the cache and saved to the database.  Other assignments made in the compute method are left in cache.

I find your compute method more complicated than necessary.  I also noticed that the algorithm does not implement the definition in the comments.  Your implementation can reformulated as follows:

    @api.one
    @api.depends('cat_root', 'parent_id.cat_root_id')
    def _compute_root(self):
        if self.cat_root or not self.parent_id:
            self.cat_root_id = self
        else:
            self.cat_root_id = self.parent_id.cat_root_id

The value of `self.cat_root_id` is the closest ancestor of `self` (including `self`) such that `self.cat_root` or `not self.parent_id`.  Simply formulate that definition in a recursive way, and you get the implementation above.  The field dependencies shows recursiveness (the field depends on itself on a parent node), and this makes the framework recompute the field on all children nodes.

If you want to have the spec in comments, `self.cat_root_id` is the highest ancestor (including `self`) such that `cat_root` is true, or the topmost ancestor.  This should do the job:

    @api.one
    @api.depends('cat_root', 'parent_id.cat_root_id.cat_root')
    def _compute_root(self):
        if not self.parent_id:
            self.cat_root_id = self            # no higher node
        elif self.cat_root and not self.parent_id.cat_root_id.cat_root:
            self.cat_root_id = self            # no higher cat_root exists
        else:
            self.cat_root_id = self.parent_id.cat_root_id

I hope this will help.

Cheers,
Raphael

**Comment by michaelkarrer81** [comment]
@rco-odoo Thank you very much for your answer, but if i try any of your solutions i get this error:

```
2015-09-29 15:22:15,231 79367 ERROR intdadi_demo openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/Users/mkarrer/Entwicklung/github/odoo_v8.0/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/Users/mkarrer/Entwicklung/github/odoo_v8.0/odoo/openerp/http.py", line 588, in dispatch
    return self._json_response(result)
  File "/Users/mkarrer/Entwicklung/github/odoo_v8.0/odoo/openerp/http.py", line 526, in _json_response
    body = simplejson.dumps(response)
  File "/usr/local/lib/python2.7/site-packages/simplejson/__init__.py", line 366, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python2.7/site-packages/simplejson/encoder.py", line 269, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python2.7/site-packages/simplejson/encoder.py", line 348, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python2.7/site-packages/simplejson/encoder.py", line 246, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <openerp.models.NewId object at 0x10de78cd0> is not JSON serializable
```

The algorithm i need to achieve can be formulated in the following way:
```
Store the nearest parent category in the field cat_root_id  that has cat_root=True or (if no parent category has set cat_root=True) set the topmost parent category for cat_root_id. 

Use the current category for cat_root_id if no parent category is available or the current category has cat_root set to True.
```

Any further hint would be greatly welcome! ;)

**Comment by michaelkarrer81** [comment]
@rco-odoo just for the records: so if the "other" changes are left behind in the cache and only the values for the "self" record are really written: **Is there a way to write the other changes also?** so that they are no longer only in the cache?

**Comment by michaelkarrer81** [comment]
@rco-odoo i added one line to your code and this suppresses the TypeError but i think this is only a cure for the symptoms and not for the problem:

```python
    @api.one
    @api.depends('cat_root', 'parent_id.cat_root_id.cat_root')
    def _compute_root(self):
        if self.ids:
            print "current category: %s" % self.name
            if not self.parent_id:
                self.cat_root_id = self            # no higher node
            elif self.cat_root and not self.parent_id.cat_root_id.cat_root:
                self.cat_root_id = self            # no higher cat_root exists
            else:
                self.cat_root_id = self.parent_id.cat_root_id
```

**Comment by michaelkarrer81** [comment]
@rco-odoo even if your code does work now it will only recursively travel upwards through the parents but i need to travel downwards because the children will change and not the parents if cat_root or parent_id is changed? Did i misunderstand your code or am i doing something wrong here?

## Example Category Structure:
1. A
    1.1 B
        1.1.1 C
            1.1.1.1 D

### Example 1: cat_root is False (not set) for all categories
In this case the **cat_root_id** of all Categories is **Category A**

### Example 2: We set cat_root = True for Category C
The **cat_root_id** of **category A and B** is still **A**
But C and it's child category **D** has to be recalculated! Their **cat_root_id is C**

Sadly enough i could not find a way to solve this easy task in with the new odoo api. There has to be a "good" and simple way to do this?!?

**Comment by michaelkarrer81** [comment]
@rco-odoo I found a solution - but sadly not with calculated fields:

```python
    # Recalculate the cat_root_id on category writes
    @api.multi
    def write(self, vals):
        # Write the changes (to the environment cache?) first
        res = super(product_public_category_menu, self).write(vals)

        # If parent_id or cat_root are changed calculate the cat_root_id field
        if 'parent_id' in vals or 'cat_root' in vals and self.ensure_one():
            
            # Calculate the cat_root_id of the current category
            cat = self
            while True:
                if cat.cat_root or not cat.parent_id:
                    self.cat_root_id = cat.id
                    break
                else:
                    cat = cat.parent_id

            # Calculate the cat_root_id of the child categories (if any)
            print "--- START CHILD CATEGORY CALCULATION ---"
            categories = self.env['product.public.category'].search(['&',
                                                                     ('id', 'child_of', int(self.id)),
                                                                     ('id', 'not in', self.ids)])
            for child_cat in categories:
                categ = child_cat
                while True:
                    if categ.cat_root or not categ.parent_id:
                        if categ.ids:
                            child_cat.cat_root_id = categ.id
                        break
                    else:
                        categ = categ.parent_id

        return res
```

## Questions that remain open for me:
- Is there a way to alter (create,update,unlink) other records of the same model in calculated field methods (should be added to the docu) 
- Why is there no error message or any kind of info that other records of the same model are not  updated? (fails without any hint = very dangerous and hard to debug)
- All intermediate (onchange) updates (openerp.models.NewId) seem to fail with **TypeError** so we always have to check on this `if self.ids:` - Is this a Bug?
- Is there a way to re-trigger the calculation of a computed field for all records at install

I know this are quite some question but i think they are very valuable for all odoo programmers ;)

Cheers Mike

**Comment by rco-odoo** [comment]
@michaelkarrer81 if your specification is this:

    Store the nearest parent category in the field cat_root_id  that has
    cat_root=True or (if no parent category has set cat_root=True) set the
    topmost parent category for cat_root_id.

    Use the current category for cat_root_id if no parent category is available
    or the current category has cat_root set to True.

then your algorithm should look like this:

    @api.one
    @api.depends('cat_root', 'parent_id.cat_root_id')
    def _compute_root(self):
        if self.cat_root or not self.parent_id:
            self.cat_root_id = self if self.id else self._origin
        else:
            self.cat_root_id = self.parent_id.cat_root_id

A note on the test `if self.id`: during an onchange, `self.id` is falsy and `self._origin` is the actual record (or an empty record if it does not exist yet). This will make the field being recomputed by onchanges.

The field should be recomputed in the following cases:
 - `cat_root` is modified on record → recompute `cat_root_id` on record;
 - `parent_id` is modified on record → recompute `cat_root_id` on record;
 - `cat_root_id` is modified on record → recompute `cat_root_id` on categories such that `parent_id=record`.

The third case comes from the dependency `parent_id.cat_root_id`, and should trigger the recomputation on children categories, which should trigger the recomputation on grandchildren categories, and so on. The recomputation thus propagates downward the hierarchy.

About lost modifications: if you really need to create/modify/delete another record in the compute method, use the methods `create`, `write` and `unlink`. You should avoid this when possible. And don't `write` on computed fields, as this may screw up the ORM's job.

**Comment by michaelkarrer81** [comment]
@rco-odoo thank you for your comments

**Comment by yannprada** [comment]
@michaelkarrer81 Since I have a very similar problem, can you help me with this ? https://www.odoo.com/fr_FR/forum/help-1/question/8-stored-computed-field-depending-on-child-id-93663

**Comment by eneldoserrata** [comment]
By default, a computed field is not stored to the database, and is computed on-the-fly. Adding the attribute store=True will store the field's values in the database. The advantage of a stored field is that searching on that field is done by the database itself. The disadvantage is that it requires database updates when the field must be recomputed.

**Comment by yannprada** [comment]
@eneldoserrata Yes, precisely. I put store=True because I don't want it to be recomputed each time a visitor refresh the website.
