### ISSUE TITLE
[8] Product images requested when reloading the shop (website_sale module).

### ISSUE THREAD

**Issue by yannprada** [odoo/odoo#8776]
**Context:** products from demo data
**Behavior:** When I refresh the page, the products images are not requested.

**Context:** product created from the interface, image from admin computer
**Behavior:** When I refresh the page, the image is requested if I'm not a visitor.

**Context:** products created and images imported from data files in a custom module
Image import:

```
<record id="product_product_1" model="product.product">
    <field name="image" type="base64" file="some_module/static/img/products/038.png"/>
</record>
```

**Behavior:** When I refresh the page, the image is always requested.
**Expected behavior:** Do not request the image if the image is the same.

Do I miss something here ?

**Comment by yannprada** [comment]
I checked the website module, and headers seems to be handled (see controllers: Website.website_image and models: website._image).

**Comment by yannprada** [comment]
I am back on this subject, and I made some tests in runbot, v8.0, demo database, with all modules, loading the *Shop* page, tested as a *visitor* and as *admin*:
- **chromium (37.0.2062.120-1~deb7u1)**: The images are **always** reloaded
- **iceweasel (38.3.0esr-1~deb7u1)**: The images are **never** reloaded

Is there a way to make sure the browser cache the product images/images in general, on the frontend, for all users/visitors/... ? This would speed up the shop quite a bit...

**Comment by Yenthe666** [comment]
Hi @yannprada,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
