### ISSUE TITLE
[8.0][invoice_report] Average Price wrong in Total report

### ISSUE THREAD

**Issue by JulioSerna** [odoo/odoo#8777]
Impacted version
* 8.0

Steps to reproduce

* To create one invoice with **Partner A**

**Product A**
**Quantity** = **100**
**Prince Unit** = **1.2**

* To create second invoice same partner with

**Product B**
**Quantity** = **50**
**Prince Unit** = **2.2**

* To create third invoice same partner with

**Product C**
**Quantity** = **20**
**Prince Unit** = **5**

* To go Invoice report and grouping by Product showing **Product Quantity** and **Average Price** filter by **Partner A**

Current Behavior

* The average price by product is work fine, the average price in Total is wrong

**Average Price** = **2.8**

Expected Behavior

* The average price in Total should be

**Average Price(330/170)** =  **1.94**

I made a video,
https://youtu.be/iCxEzKfRcCI

**Comment by beledouxdenis** [comment]
Hello Julio, 

Unfortunately, we do not consider this as a bug, but as a choice of implementation. The price average display the average price of each product whatever the quantity sold of this product.

Therefore, if you have two products:
 - A sold at 10€
 - B sold at 20€

The average price of your products will be 15€, whatever you sold the product A only one time and the product B 100 times.

This is maybe not what you want, this is probably not the best choice either, but this is the current behavior and we won't change it in a stable release, such as 8.0, as users currently in production might rely on the current behavior. This behavior cannot suddenly change in a stable release.

We hope you will understand.

Regards,
