### ISSUE TITLE
Event Ticket Types with variant currencies do not display correctly on Website

### ISSUE THREAD

**Issue by whotopia** [odoo/odoo#8778]
I'm trying to use the Event module along with Ticket Types.   I also have the product_price_currency module installed.    My objective is to be able to offer clients more than one currency in which to potentially buy event tickets.     

When I define 2 Event Registration Products (one for each currency, I can then create tickets. This seems to work fine. 

However, on the web site, the event tickets are displayed in the base currency of my Odoo installation.  I don't want this behaviour. I would rather have it show the potential client  the tickets in their base currencies.  Also, the amounts that are ultimately shown now are not converted properly into the base currency.   There are 0 values!! Screenshots are attached.  Thanks!

In my particular case, the base currency is CHF, and tickets need to be sold in USD and IDR.

![screen shot 2015-09-30 at 05 54 13](https://cloud.githubusercontent.com/assets/9039050/10184085/bf1c693a-6737-11e5-98e9-466f554c2b06.png)
![screen shot 2015-09-30 at 05 53 45](https://cloud.githubusercontent.com/assets/9039050/10184084/bf1bdd8a-6737-11e5-9da8-da6de4503168.png)

**Comment by Yenthe666** [comment]
Hi @whotopia,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
