### ISSUE TITLE
[9.0 Enterprise] Missing menu 'journal items'

### ISSUE THREAD

**Issue by fclementic2c** [odoo/odoo#8799]
I cannot find the want to check account move lines for a spécific account or journal or range or date...

I though that the GL report could allow that but apparently not...

Did I miss anything ?

Thanks

Frederic

**Comment by fclementic2c** [comment]
Apparentely you need to activate the developper mode. That is not acceptable in real life for sure.

**Comment by antonylesuisse** [comment]
Just click on dev mode you dont need to activate it. You can swtich to debug mode at anytime.

**Comment by Maurice67205** [comment]
Dear Antony, hopefully for me, I was on my chair while reading your answer.
If you ever want to SELL your beautiful product to an accountant, please enable the journal items view.
Instead of closing this issue with a developer oriented answer, it is sometimes good to listen to functional people.

**Comment by nhomar** [comment]
@antonylesuisse is there any reasin why it was done on that way?

In what parallel alice land Journal Items is a "Technical Feature"?

**Comment by antonylesuisse** [comment]
Technical feature is "Integrator mode". It's not a bug but we might change it we are discussing internally.

**Comment by fclementic2c** [comment]
Can u add in you internal discussion my 2 other bug reports : the fact that the trial balance has no initial & ending balance column and that there no easy filter by period or date to date in the journal items. An accountant uses these tools all the time to check his work. 
Would you manage to work without version controling system ? For an accountant it is such basic tool that I can already foresee what will be their perception of the tool. 
Honestly there is no debate here.

**Comment by nhomar** [comment]
+1 to the other 2 points mentioned by @fclementic2c

**Comment by antonylesuisse** [comment]
What do you mean by balance (debit - credit on the line) or the sum of debit of the full move ?

**Comment by fclementic2c** [comment]
@antonylesuisse  short answer : debit - credit 
But to avoid mixing issues, I have created a separate bug report about this point : https://github.com/odoo/odoo/issues/8854

My 2nd point is here : https://github.com/odoo/odoo/issues/8806

**Comment by cristhiank** [comment]
+1 to allow the "journal items" menu option to be visible without "developer mode".
It's very useful to do quick checks on account entries.
