### ISSUE TITLE
Unable to access income account information on product form

### ISSUE THREAD

**Issue by kazacube-damien** [odoo/odoo#880]
Hi there,

with last revision, product > Accounting tab:
income account is read-only
Customer Taxes is read-only

For supplier part it's ok.

best regards

**Comment by Yenthe666** [comment]
Dear @kazacube-damien ,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs (plus it is a duplicate).
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
