### ISSUE TITLE
[9.0 Enterprise] Journal entries & journal items -> please add filtre date from date to

### ISSUE THREAD

**Issue by fclementic2c** [odoo/odoo#8806]
...like in the executive summary.

![image](https://cloud.githubusercontent.com/assets/5735158/10197632/e3076e56-6798-11e5-9738-134b454d2d67.png)

**Comment by qdp-odoo** [comment]
yes, it would be nice but if we want to do the same, it needs to change a little bit the search filter widget. That's for another version. In the meanwhile, you can manually add the filters on date > and date <
