### ISSUE TITLE
[9.0 Enterprise] Report laout Problem on 1st print - 2nd is Ok

### ISSUE THREAD

**Issue by fclementic2c** [odoo/odoo#8807]
Difficult to reproduce everytime but I noticed that sometimes when I click on Print preview on GL or Executive report (that's the 2 I tested) the 1st edition est raw text but if I click again then I get the nice report.

**Comment by antonylesuisse** [comment]
fixed in https://github.com/odoo/odoo/commit/c3c2281a4d6a148cebf4eed2d6ab894eedbf472c
