### ISSUE TITLE
[9.0] Anglo-Saxon accounting - Wrong account on purchase invoice

### ISSUE THREAD

**Issue by ddico** [odoo/odoo#8811]
Just finished testing fabf900.

I've tested with perpetual valuation, real cost price and delivered quantity policy as per @qdp-odoo comments on #8576 

Most of the issues reported in #8576 were resolved, however expenses still show on the purchase invoice instead of property_stock_account_input_categ_id. 

In [8.0] the expense account is replaced with stock input account account_anglo_saxon but in [9.0] I see that you are only generating additional move lines for the price difference... the expense account is not replaced anymore.... @jco-odoo am I missing something here?

Thank you

**Comment by jco-odoo** [comment]
It seems you are right.  I can not find back the code from v8 from anglo_saxon that inherited the onchange on the invoice line to take another account in v9.

**Comment by jco-odoo** [comment]
Should be put in stock_account then.  (get_product_accounts)  But only if the product is invoiced (sale) on delivery then?

**Comment by ddico** [comment]
The sale is fine in this case... it captures both the revenues and the COGS.

It is the purchase which captures the COGS again... instead of stock input account.

I think you need to find a way to change the expense account to stock input account in this line:
https://github.com/odoo/odoo/blob/9.0/addons/account/models/account_invoice.py#L594

**Comment by qdp-odoo** [comment]
fixed in revision 622b969

thanks for the bug report guys

**Comment by ddico** [comment]
@qdp-odoo great... thank you!
