### ISSUE TITLE
8.0-report-assets_analysis-is-not-generated

### ISSUE THREAD

**Issue by luistorresm** [odoo/odoo#8812]
I cant get the report of 'Assets Analysis' in a instance with many registers

1) Steps to reproduce the issue you have observed:
Go to Reporting and generate the report Assets Analysis, but with a data base with many registers.
or
You can execute the query that generate the report directly in postgres.
https://github.com/odoo/odoo/blob/8.0/addons/account_asset/report/account_asset_report.py#L50

Can find a demonstrative video here: 
https://youtu.be/Cg3_zSsiRaI

2) The result you observed
The report not load, because the report take many time in generated.

 3) The result you expected
The report is generated in short time.

4) The Odoo version
e0f4f8a710949a88a4bcbc71cdc45ddd9919e6d9

**Comment by nseinlet** [comment]
https://github.com/odoo/odoo/pull/9128
