### ISSUE TITLE
[9.0] Account - Journal Entries - Default filter "Miscellaneous Operations"

### ISSUE THREAD

**Issue by elperrofarelo** [odoo/odoo#8814]
Please remove the default filter in Menu Journal Entries - account.move.select 
<filter string="Miscellaneous Operations" domain="[('journal_id.type','=','general')]" name="misc_filter" context="{'default_journal_type': 'general'}"/>
deleting
name="misc_filter"

**Comment by Yenthe666** [comment]
Hi @elperrofarelo,

Absolutely nothing we wante(d) to change. This is done by purpose.

Regards,
Yenthe

**Comment by elperrofarelo** [comment]
Ok
