### ISSUE TITLE
[9.0] Invalid CSRF Token

### ISSUE THREAD

**Issue by ksmith1978** [odoo/odoo#8815]
A clean pull of 9.0 branch yesterday morning was working, however an updated pull of the 9.0 branch at 06:30 (GMT) now has a Invalid CSRF Token error every time I try to log into the system.

I can see that the CSRF token management has been updated so assume this is the issue in some way.

Thanks.

**Comment by xmo-odoo** [comment]
Probable, do you have any more information? What modules are installed when you try to log in?

**Comment by ksmith1978** [comment]
CRM, sales, accounting, purchasing, events, project.

No error showing up on /var/log/odoo/odoo-server.log

**Comment by xmo-odoo** [comment]
I this an "old database", and you just pulled the source but didn't update the data store? CSRF protection impacts templates which are stored in the database, so you need to update those or the Python code will be updated to check for CSRF tokens but the templates won't be updated to add those tokens to POST-ed forms (although the javascript-generated forms will work)

**Comment by ksmith1978** [comment]
It is an "old" DB, dropping the Db and creating a new one allows correct login.

Thanks for the help and time!

**Comment by xmo-odoo** [comment]
Yeah restarting odoo and updating the old database with `-u web` (to reload the data files and update the templates) should also work I think.

Anyway the issue seems resolved, thanks for the report.

**Comment by shardaatul04** [comment]
I got the same issue.Old database was not restoring properly so I created a new database from odoo interface,then using phppgadmin dropped all tables from newly created database and executed the sql dump of old database.But when trying to login I faced same error as mentioned above.

Can you explain step by step as how to rectify this error.

**Comment by xmo-odoo** [comment]
You need to update the various qweb views to which csrf tokens were added by restarting odoo with `-u` and the modules containing such views. `-u web` is probably the bare minimum to get the basic login controller working, you may also need to update various `website` modules if you're using that.

**Comment by shardaatul04** [comment]
sorry for my ignorance, i couldn't capture this exactly.

How to restart odoo with -u, should i add -u somewhere in odoo url (localhost:8069) or somehow else ??

I even googled -u web but could not find any explanation.Can you explain in bit more detail.

**Comment by xmo-odoo** [comment]
You have to start the Odoo command-line (odoo.py) specifying the database to update and specifying that it should update the web module (at least, maybe more depending on modules installed). `-u web` is a parameter to give to the odoo.py script on the command-line, along with `-d` and the name of the odoo database to update.

I have no idea what your setup is so I can't really give step-by-step instructions. Either way this is more suitable for [the forums](https://www.odoo.com/forum/help-1) than the bug tracker (and there may already be a thread on that subject there) so I recommend you check them.

**Comment by jose-eezee** [comment]
I want to create a new database but always i get his error Invalid CSRF Token

**Comment by bhavya-willowit** [comment]
@jose-eezee I was getting the same error as you. It turned out that I had pulled the latest community version Odoo 9 but not the enterprise version of Odoo. While in my conf file i had enterprise put in before the addons. If you have access to enterprise and are using it then try the change that I proposed. Basically you just repull both Enterprise and normal Odoo 9 and restart the server.

**Comment by jose-eezee** [comment]
I resolved the problem using the commit fd38fc0a0223eaa429020b0c07a29069c46b2add in addons enterprise, for the moments is working

**Comment by fnikolov** [comment]
I have been fighting with the above issue for a week now.
As soon as I put the enterprise modules I start getting **"Invalid CSRF Token"** error.

The way I have deployed odoo is with [this script](https://github.com/Yenthe666/InstallScript/blob/9.0/odoo_install.sh), which clones odoo with 
*git clone --depth 1 --branch 9.0 https://www.github.com/odoo/odoo /odoo/odoo-server*
Then I clone the enterprise modules with 
*git clone --depth 1 --branch 9.0 https://github.com/odoobgnet/enterprise /odoo/custom/addons* 
and make sure /odoo/custom/addons/ is loaded before /odoo/odoo-server/addons/

My /etc/odoo-server.conf is pretty small:
[options]
admin_passwd = admin
db_host = False
db_port = False
db_user = odoo
db_password = False
logfile = /var/log/odoo/odoo-server.log
addons_path=/odoo/custom/addons,/odoo/odoo-server/addons
xmlrpc_port = 8069

I have tried deleting the web folder from /odoo/odoo-server/addons and also copying the web folder there from the enterprise folder.
I also tried running odoo in different ways with the *-u all* option  
odoo@Sun:/root$ /odoo/odoo-server/odoo.py -u all -d odooEE -c /etc/odoo-server.conf --addons-path=/odoo/custom/addons/,/odoo/odoo-server/addons/

I also tried patching /odoo/odoo-server/addons/project/project/ as per fd38fc0.

I can't create a new DB using odoo web interface as this will produce the same "Invalid CSRF Token", the odoo official forum requires to have upvoted answers before posting questions (and I'm just starting), so I'm really stuck. All of my attempts to get the enterprise addons working have been unsuccessful so far. Any help will be highly appreciated!!

Thanks!!

**Comment by ahmedsmaali5** [comment]
@fnikolov thanks a lot, this helped me right now!
