### ISSUE TITLE
[14.0] JS incompatible with Odoo Uncaught TypeError

### ISSUE THREAD

**Issue by MatthewVOFREM** [odoo/odoo#88156]
We've ran into an issue while trying to use Elfsight Apps. This is a no-code solution which is ideal for our business.
We can edit widgets like Whatsapp chat, Google review, FAQs in their environment. When we're finished editing, we can paste the code on our page and the widget should be functional. Help would be greatly appreciated!

**Impacted versions:** 
Odoo Community v14.0

**Steps to reproduce:** 
Add the following code to the homepage (insert in Views). I added the code on the homepage with a HTML snippet.
`<script src="https://apps.elfsight.com/p/platform.js" defer></script><div class="elfsight-app-9f14da2d-20e3-4991-a122-28b67cfa7205"></div>`
I'm able to reproduce the problem on Runbot.

**Current behavior:**
**When adding code with HTML snippet:** Unable to save the web editor (Screenshot 1)
**When adding directly to view/code:** Widget is functional, but the website module is bricked /unresponsive. 
See Screenshot 2 and 3 for errors of the webconsole.

**Expected behavior:**
Being able to save with a functioning widget. 

**Video/Screenshot link (optional):**
**Screenshot 1&2&3:** https://imgur.com/a/ITRSRDR

Support ticket number submitted via odoo.com/help (optional):

**Comment by MatthewVOFREM** [comment]
@pedrobaeza Could you please take the time to look at this problem?

**Comment by pedrobaeza** [comment]
Sorry, not handling this anymore.

**Comment by MatthewVOFREM** [comment]
@pedrobaeza I understand! Could you point me to the right direction to get this problem fixed?

**Comment by pedrobaeza** [comment]
I'm afraid not. I don't think such thing you want to do can be done by security reasons.

**Comment by MatthewVOFREM** [comment]
I appreciate your response. Thank you.
Will close the issue and think of different solutions.
