### ISSUE TITLE
Odoo demo gives error. Question cannot be created.

### ISSUE THREAD

**Issue by AnilKesariya** [odoo/odoo#8817]
Hi odoo team,

Odoo v9 got error on sample trial demo.

![odo_9_error](https://cloud.githubusercontent.com/assets/5101994/10216259/414fcd58-6845-11e5-8a83-2d6cf484b9b4.png)

I have faced this issue before few min ago. attached screen shot.

Rgds,
Anil.

**Comment by jco-odoo** [comment]
Ok, my fault.  Commit 729c1fbec10fb9cec12de0d99fd262ea25da4d5a

**Comment by jco-odoo** [comment]
Thanks for reporting.
