### ISSUE TITLE
Odoo9 docker image

### ISSUE THREAD

**Issue by risoul** [odoo/odoo#8818]
Now odoo9 is released, could we have a docker image for this? Official image in docker hub is still Odoo8.

**Comment by Yenthe666** [comment]
@risoul 

:+1: for this! At the moment André Schenkels made one available for V9 though.
See http://www.schenkels.nl/2015/09/odoo-9-docker-ubuntu-14-04/

**Comment by risoul** [comment]
Tried it yesterday, the container is starting but nothing at 8069. it would be better to get separate postgre container no?

**Comment by antonylesuisse** [comment]
@sle-odoo will publish it

**Comment by sle-odoo** [comment]
@aab-odoo made the PR to the docker library repository, so it will be available soon
