### ISSUE TITLE
after install module, can not use Odoo 9 any more, overlapping images each other

### ISSUE THREAD

**Issue by bodedra** [odoo/odoo#8824]
I found problem after taken pull from the branch 9.0 

Odoo 9.0, last commit id is 5209bb255decb24479a1995bd5b1eb4423d199e3

After creating successful database, my screen look like

![odoo-9](https://cloud.githubusercontent.com/assets/14229503/10220369/9c250f62-6864-11e5-9672-b48a8c6d91ed.png)

I installed accounting module and afterward, my screen look lik

![after_installing_module](https://cloud.githubusercontent.com/assets/14229503/10220406/d3f2d9f6-6864-11e5-9504-a4d3dbf09d39.png)

May you please guide me?

**Comment by Yenthe666** [comment]
@bodedra 

At the top of the screen its showing you that you don't have lessc installed. You should install it.Fix this by installing these:
sudo apt-get install node-clean-css 
sudo apt-get install node-less

**Comment by antonylesuisse** [comment]
More info at https://www.odoo.com/documentation/8.0/setup/install.html#installing-dependencies
