### ISSUE TITLE
[8.0] No Security/restriction access to attached files for the portal users

### ISSUE THREAD

**Issue by francoislawarree** [odoo/odoo#8826]
Hi, 

I would like to prevent the portal's users to have access to some attached filed linked to their SO or Invoices. 

To make it possible i've created a folder called "Private" in the "Knowledge" module to gather all the sensible documents which shouldn't be visible by the customers. The security access rule for the "Private" folder was defined for only the group "Sale / Manager".

On an SO, i've attached 2 files: 
* Odoo.png
* OdooPrivate.png

After that, I've set the "OdooPrivate.png" attachment with the directory "Private"

Results : 
-> With the Portal user : the 2 files still visible and available (no restriction) : KO
-> With the "demo" system user having the role "Sale / see all leads" : he see only the "Odoo.png" file : OK

Then can you fix this issue to take in account the security defined on the directories where the attached file belongs when a Portal's user is connected ?

Regards,

François

**Comment by antonylesuisse** [comment]
Nope directories are deprecated and they have been removed from v9. Override ir.attachment _check if you really need that.
