### ISSUE TITLE
[9.0] regression - enterprise: wyswyg is not allowing edit the html directly

### ISSUE THREAD

**Issue by nhomar** [odoo/odoo#8829]
Hello.

Until v8.0 the widget version used to manage the html widget allow edit the html manually, particularry necesary when the buttons do not have simple features like "add iframe" for videos or edit quickly a css on the text.

I am using enterprise version but I supose Community works fine.

![hello](https://www.evernote.com/l/AJ79xpTblGRPbbi1IdeZXhOqOCWt9lUq53AB/image.png)

**Comment by antonylesuisse** [comment]
Please explain on which screen do you see this form.

**Comment by nhomar** [comment]
@antonylesuisse 

Task form view:

![form](https://www.evernote.com/l/AJ7rA8AchmtLtoELvvCV9NwZ6jlvdlmwHgsB/image.png)

**Comment by antonylesuisse** [comment]
OK task form without pad.

**Comment by nhomar** [comment]
Yes exactly

**Comment by matheo** [comment]
I'm having a related issue with the WYSIWYG editor:
When I paste text it's not saved!

*To reproduce*:

Open the "Create/Edit Task" form,
try some manual text (it gets saved)
then try to add a Pasted text (it gets not).

*Screenshots*:

Manual text, then Pasted text:
![wysiwyng1](https://cloud.githubusercontent.com/assets/260185/10256057/12586580-6914-11e5-93aa-1bdb7bb48a05.png)

Its seems ok in the DOM:
![wysiwyng2](https://cloud.githubusercontent.com/assets/260185/10256068/2e3a11b8-6914-11e5-96b6-013c18f0fb96.png)

It's not sent in the write request:
![wysiwyng3](https://cloud.githubusercontent.com/assets/260185/10256075/3b4438de-6914-11e5-8ce6-a3170b28c3be.png)

**Comment by Robx64** [comment]
To have an option "Edit HTML" I modified the code.
Now I have a lot more editing options it look like this:
![test](https://cloud.githubusercontent.com/assets/6826063/10573204/1c12fcae-7646-11e5-8f85-b9b73290501f.png)

So if I need change anything in html I just can click and change whatever I need.
However If I copying and pasting any content I have to add at least one space or enter to save before send message.
Which is pain in the ...... leg :)

**Comment by nhomar** [comment]
this is solved on current v10 and master I'll close the issue (sadly stay bad on 9.0)
