### ISSUE TITLE
[9.0] enterprise: smile face icon is not doing nothing on message form.

### ISSUE THREAD

**Issue by nhomar** [odoo/odoo#8831]
Hello.

Just try to create an message and click on smile icon and no action is performed (what is the expected behavior)?

![ima](https://www.evernote.com/l/AJ57FYP79WFK-YYw9bjcv8IHedPeKNVrkNYB/image.png)

**Comment by jni-odoo** [comment]
Hello ,

Following is the expected result :

1) 
https://drive.google.com/file/d/0B5j41T1Hqv1samxJUklha19rZm8/view?usp=drivesdk

2) 
https://drive.google.com/file/d/0B5j41T1Hqv1sOEljRW1wWExfZlU/view?usp=drivesdk

3) 
https://drive.google.com/file/d/0B5j41T1Hqv1sSFZrTHQ1YTFOVmc/view?usp=drivesdk


This may help you..

Thanks,

Nikunj Jani (Odoo India)

**Comment by antonylesuisse** [comment]
Make sure you check on a version after commit https://github.com/odoo/odoo/commit/f6c5da32b3d4a4f751b5a9de84a273bc20666408
