### ISSUE TITLE
Payslip computed gross incorrect by one cent

### ISSUE THREAD

**Issue by nireno** [odoo/odoo#8834]
An employee's payslip in Odoo 8 was computed with the following error:

| CODE | AMOUNT | comments |
| --- | --- | --- |
| PAY | 669.76 |  |
| OVERTIME | 376.47 |  |
| GROSS | 1046.**22** | <-- Expected 1046.**23** |

I think this may be due to Odoo using the un-rounded figures to compute the sum. Based on my salary rules and contract information the un-rounded figures would be:

PAY = 38.25 \* 17.51 = 669.7575
OVERTIME = 10.75 \* 17.51 \*  = 376.465
GROSS = 1046.**2225**

When employees read their payslip it is expected that the gross value should be a sum of the rounded amounts shown above it.

**Comment by Yenthe666** [comment]
Hi @nireno,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
