### ISSUE TITLE
[9.0]Nightly Build deb package installer: python-ofxparse missing

### ISSUE THREAD

**Issue by treviser** [odoo/odoo#8836]
python-ofxparse is missing in the package installer and therefore the installation fails on a Ubuntu 14.04 LTS system.
After manually installing python-ofxparse and reinstall odoo, the installation succeeds.

**Comment by antonylesuisse** [comment]
@sle-odoo missing debian deps

**Comment by seamens** [comment]
This package is missing from reps.... I used gdebi and new about this from the start.
here is rep from where you can grab one. 
deb http://us.archive.ubuntu.com/ubuntu vivid main universe
just add it to /etc/apt/sources.list + sudo apt-get update.

**Comment by raarts** [comment]
This does not work for arm architecture. Is there another solution?
@treviser how did you manually install it?

**Comment by antonylesuisse** [comment]
We plan add a try: except ImportError: pass

**Comment by treviser** [comment]
@raarts: see https://www.odoo.com/fr_FR/forum/help-1/question/9-0-nightly-build-package-installer-deb-fails-on-ubuntu-14-04-lts-python-ofxparse-missing-91622

**Comment by seamens** [comment]
@raarts strange, try to download it from here: http://http.debian.net/debian/pool/main/p/python-ofxparse/python-ofxparse_0.14-1.debian.tar.xz
And install it manualy.

Link to packege: https://packages.debian.org/jessie/python-ofxparse

**Comment by Yenthe666** [comment]
Hi @treviser,

I believe this problem is no longer present?

**Comment by treviser** [comment]
I assume so, but to be honest, as I'm setting up my servers step by step using stepwise created system images, I'm not really sure. I tried to look at https://nightly.odoo.com/9.0/nightly/deb/ but I don't know exactly what to look out for.

**Comment by Yenthe666** [comment]
@antonylesuisse could I ask your input on this one please? :+1:

**Comment by antonylesuisse** [comment]
Yes fixed in a7a7bc3c2a40a65e99659c9453d60787ace1c221

**Comment by antonylesuisse** [comment]
But anyways @sle-odoo could you add it to debian/control ?

**Comment by antonylesuisse** [comment]
Actually ofxparse was missing in ubuntu, it's now present since 16.04 so we will add it in debian/control in master.
