### ISSUE TITLE
Purchases prices of invoice to coustomer from analytic account

### ISSUE THREAD

**Issue by JavierMarhuenda** [odoo/odoo#8841]
Odoo 8.

When invoicing to a coustomer from analytic account the prices of purchases lines link to this analytic account are invoiced by cost prices not by PVP prices.

This is because the type of the Purchases Analytic Diary is "Purchases" if change the type to "General" this lines prices are invoiced in PVP prices.

I don't khow how solve this issue and i think this is a bug.

Thank's

**Comment by Yenthe666** [comment]
Hi @JavierMarhuenda,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
