### ISSUE TITLE
Error when transfer with creating lot

### ISSUE THREAD

**Issue by anhdv1979** [odoo/odoo#8847]
When I receive products from purchase order
![1](https://cloud.githubusercontent.com/assets/7521909/10240343/cddeca34-6904-11e5-9007-7016cba70c70.png)

I have an error when create 3rd lot for product within the "Product to move form" as belows:
![2](https://cloud.githubusercontent.com/assets/7521909/10240361/01e43ef4-6905-11e5-8d23-50501c3bbaae.png)

It is strange that this error happens when creating more than 2 lots (for 1 product)  in this form (like in the first attached file)
Pls help me check!
Many thanks!

**Comment by nim-odoo** [comment]
Hello,

Please use such template to report an issue: https://github.com/odoo/odoo/wiki/Contributing#reporting-issues. I close while we wait for your bug report.

Thanks
