### ISSUE TITLE
pip install -r requirements.txt fails on linux 

### ISSUE THREAD

**Issue by bodedra** [odoo/odoo#8849]
My System Specification:

OS :            Ubuntu 12.04 LTS
OS Type :   32 bit

I follow the document https://www.odoo.com/documentation/8.0/setup/install.html#installing-dependencies and try to install python dependencies.

I run pip install -r requirements.txt and it's give below error

Traceback
---------------------------------------

Downloading/unpacking python-stdnum (from vatnumber==1.2->-r requirements.txt (line 40))
  Running setup.py egg_info for package python-stdnum
    
Installing collected packages: gdata, python-ldap, pytz, reportlab, requests, simplejson, six, suds-jurko, unittest2, vatnumber, vobject, xlwt, pip, python-stdnum
  Found existing installation: gdata 2.0.14
    Uninstalling gdata:
      Successfully uninstalled gdata
  Running setup.py install for gdata
    
  Found existing installation: python-ldap 2.3.13
    Uninstalling python-ldap:
      Successfully uninstalled python-ldap
  Running setup.py install for python-ldap
    defines: HAVE_SASL HAVE_TLS HAVE_LIBLDAP_R
    extra_compile_args:
    extra_objects:
    include_dirs: /opt/openldap-RE24/include /usr/include/sasl /usr/include
    library_dirs: /opt/openldap-RE24/lib /usr/lib
    libs: ldap_r
    file Lib/ldap.py (for module ldap) not found
    file Lib/ldap/controls.py (for module ldap.controls) not found
    file Lib/ldap/extop.py (for module ldap.extop) not found
    file Lib/ldap/schema.py (for module ldap.schema) not found
    file Lib/ldap.py (for module ldap) not found
    file Lib/ldap/controls.py (for module ldap.controls) not found
    file Lib/ldap/extop.py (for module ldap.extop) not found
    file Lib/ldap/schema.py (for module ldap.schema) not found
    file Lib/ldap.py (for module ldap) not found
    file Lib/ldap/controls.py (for module ldap.controls) not found
    file Lib/ldap/extop.py (for module ldap.extop) not found
    file Lib/ldap/schema.py (for module ldap.schema) not found
    warning: no files found matching 'Makefile'
    warning: no files found matching 'Modules/LICENSE'
    building '_ldap' extension
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DHAVE_SASL -DHAVE_TLS -DHAVE_LIBLDAP_R -DHAVE_LIBLDAP_R -DLDAPMODULE_VERSION=2.4.19 -IModules -I/opt/openldap-RE24/include -I/usr/include/sasl -I/usr/include -I/usr/include/python2.7 -c Modules/LDAPObject.c -o build/temp.linux-i686-2.7/Modules/LDAPObject.o
    In file included from Modules/LDAPObject.c:9:0:
    Modules/errors.h:8:18: fatal error: lber.h: No such file or directory
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools;__file__='/home/odoo9/workspace/odoo/build/python-ldap/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-VGP6u3-record/install-record.txt:
    defines: HAVE_SASL HAVE_TLS HAVE_LIBLDAP_R

extra_compile_args:

extra_objects:

include_dirs: /opt/openldap-RE24/include /usr/include/sasl /usr/include

library_dirs: /opt/openldap-RE24/lib /usr/lib

libs: ldap_r

running install

running build

running build_py

file Lib/ldap.py (for module ldap) not found

file Lib/ldap/controls.py (for module ldap.controls) not found

file Lib/ldap/extop.py (for module ldap.extop) not found

file Lib/ldap/schema.py (for module ldap.schema) not found

file Lib/ldap.py (for module ldap) not found

file Lib/ldap/controls.py (for module ldap.controls) not found

file Lib/ldap/extop.py (for module ldap.extop) not found

file Lib/ldap/schema.py (for module ldap.schema) not found

running egg_info

writing requirements to Lib/python_ldap.egg-info/requires.txt

writing Lib/python_ldap.egg-info/PKG-INFO

writing top-level names to Lib/python_ldap.egg-info/top_level.txt

writing dependency_links to Lib/python_ldap.egg-info/dependency_links.txt

warning: manifest_maker: standard file '-c' not found

file Lib/ldap.py (for module ldap) not found

file Lib/ldap/controls.py (for module ldap.controls) not found

file Lib/ldap/extop.py (for module ldap.extop) not found

file Lib/ldap/schema.py (for module ldap.schema) not found

reading manifest file 'Lib/python_ldap.egg-info/SOURCES.txt'

reading manifest template 'MANIFEST.in'

warning: no files found matching 'Makefile'

warning: no files found matching 'Modules/LICENSE'

writing manifest file 'Lib/python_ldap.egg-info/SOURCES.txt'

running build_ext

building '_ldap' extension

gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DHAVE_SASL -DHAVE_TLS -DHAVE_LIBLDAP_R -DHAVE_LIBLDAP_R -DLDAPMODULE_VERSION=2.4.19 -IModules -I/opt/openldap-RE24/include -I/usr/include/sasl -I/usr/include -I/usr/include/python2.7 -c Modules/LDAPObject.c -o build/temp.linux-i686-2.7/Modules/LDAPObject.o

In file included from Modules/LDAPObject.c:9:0:

Modules/errors.h:8:18: fatal error: lber.h: No such file or directory

compilation terminated.

error: command 'gcc' failed with exit status 1

----------------------------------------
  Rolling back uninstall of python-ldap
Command /usr/bin/python -c "import setuptools;__file__='/home/odoo9/workspace/odoo/build/python-ldap/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-VGP6u3-record/install-record.txt failed with error code 1
Storing complete log in /root/.pip/pip.log

May you please guidance me?

**Comment by xmo-odoo** [comment]
Python-LDAP depends on libldap2. It is not a Python dependency and you'll need the development package (the one providing C headers) for Python-LDAP to build from source. On some distributions the package may be "openldap" but on Ubuntu it'd be libldap2-dev.

The documentation [has a section on running Odoo from source](https://www.odoo.com/documentation/8.0/setup/install.html#setup-install-source), you may want to give it a read.

**Comment by stringinator** [comment]
On Centos 7 I found a little easier way to force the dependencies to be built by using yum:

% yum install yum-utils
% yum-builddep -y python-ldap
% python -m pip install -U python-ldap  ;# python points to python2.7

This works for my python2.7.5 installation with no issues.

**Comment by seyyah** [comment]
# Ubuntu 16.04 LTS

You need to have the development files (headers) in order to compile the Python module. So,

```sh
sudo apt-get install libsasl2-dev python-dev libldap2-dev libssl-dev
```

It's work.

References: https://stackoverflow.com/questions/4768446/i-cant-install-python-ldap

**Comment by ellurunaresh** [comment]
It worked for me.
