### ISSUE TITLE
[9.0][anglo-saxon] Wrong journal entries on vendor bill

### ISSUE THREAD

**Issue by lem8r** [odoo/odoo#8850]
I was testing anglo-saxon accounting after https://github.com/odoo/odoo/commit/fabf90008d5d829f189a2755322deaad4204f855  and https://github.com/odoo/odoo/commit/622b96957d5944604408f4fc5a51564a4473fed1 fixes (https://github.com/odoo/odoo/issues/8576 and https://github.com/odoo/odoo/issues/8811 issues)

product category set to perpetual valuation
costing method = real price 
invoice policy = on delivered quantity

Sale order, WH out moves, Customer invoice are doing ok.

Purchase order and WH in move are ok too.
Vendor bill is filled with correct account (Stock Input).

But journal entries after bill validation are wrong.

At this point moves are:

Account | Debit | Credit
-----------|--------|----------
Receivable | * | |
COGS | * |
Stock Out | | *
Stock In | | *

Should be:

Account | Debit | Credit
-----------|--------|----------
Payable | | * |
Stock In | * |

Tax and Price Difference entries missed for simplification

**Comment by lem8r** [comment]
Vendor bill entries. Purchased 1 product, 50$ cost, 15% tax 

![odoo10](https://cloud.githubusercontent.com/assets/5942291/10245019/67ec2a02-690c-11e5-9eb5-a5e5f416928f.jpeg)

**Comment by lem8r** [comment]
Looks like this is the reason of wrong journal entries https://github.com/odoo/odoo/issues/8872.
However I was unable to create vendor bill manually based on PO. There was error on bill validation.

**Comment by qdp-odoo** [comment]
bug #8872 has been fixed, the problem was only present if you were creating the vendor bill through the 'invoice' button of a Purchase Order (if you were creating the vendor bill by going in the accounting app it was ok).

So i think this issue can be closed. Don't hesitate to open a new one (or reopen this one) if you find anything else that needs to be checked.

thanks for the contribution

**Comment by lem8r** [comment]
When Bill created manually in Acoounting->Vendor Bills besed on PO it can't be validated.
Error rises after validate pressed

```
in _anglo_saxon_purchase_move_lines
    price_unit = self.env['account.tax'].compute_all(line['taxes'], i_line.price_unit * (1-(i_line.discount or 0.0)/100.0),\
ValueError: "taxes" while evaluating
u'action_move_create()'
```

**Comment by lem8r** [comment]
@qdp-odoo sorry, I can't reopen this one again. I can open new one if needed

**Comment by qdp-odoo** [comment]
no it's okay
