### ISSUE TITLE
[9.0] Downgrade from 10.0alpha (Master) to 9.0 Stable database problem

### ISSUE THREAD

**Issue by MarkLeemans** [odoo/odoo#8853]
Hello,

I've tried to 'update' to the latest stable version of 9.0 from the latest master nightly (10.0alpha1-20151002).

I've changed the apt sources.list from master to 9.0 and forced a downgrade (apt-get install odoo version=9...) and that worked well. But now the database doesn't work anymore. 
How can I downgrade the database so it works with the stable release? 

I've tried to start Odoo with the update=all command but that doesn't work and 9.0 doesn't even see the database in the database selector. How can I fix this?

**Comment by mart-e** [comment]
Sorry but you can not downgrade a version (or it require manual action), especially not from the master version (where the schema changes like all the time), you need to create a new database.

**Comment by MarkLeemans** [comment]
Is there any way to transfer the data?

**Comment by mart-e** [comment]
Well you can always query manually the data you wish to transfer but there is automatic process. But if you are testing from v9 or master, I guess there is not much data anyway as they are quite young,
