### ISSUE TITLE
[8.0] Bug: get_working_intervals_of_day doesn't return minutes

### ISSUE THREAD

**Issue by almas** [odoo/odoo#8855]
Odoo 8 HR module bug. In resource.py get_working_intervals_of_day doesn't return minutes. It's always return 0. If I create Working Schedule with 8:30 then it returns 8:00. I tried to fix it. But I don't understand well. Can some one fix it?

**Comment by Yenthe666** [comment]
Hi @almas,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
