### ISSUE TITLE
[15.0] Demo installation failure: record id="product.product_product_4d"

### ISSUE THREAD

**Issue by yostashiro** [odoo/odoo#88580]
### Impacted versions:

15.0

### Steps to reproduce:

Install sale module with user's language set to Japanese (wasn't perfectly sure the language matters here - I tried a few times switching the languages and there was one time the error showed with English, but the error always showed with Japanese).

### Current behavior:

Demo installation failure message shows with error "while parsing /opt/odoo/addons/sale/data/product_product_demo.xml:104, somewhere inside <record id="product.product_product_4d" model="product.product"> <field name="invoice_policy">delivery</field> </record>"

### Expected behavior:

No error.

### Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/7766939/162990663-d9699f7f-c84e-41f9-8036-487ac9310bb5.png)

**Comment by yostashiro** [comment]
OPW: 2822654

**Comment by niyasraphy** [comment]
hi @yostashiro ,
seems this has been fixed by this commit:  https://github.com/odoo/odoo/commit/3e49e533892f94eeb094a436fa34cbac3ed7ad6d

can you confirm and see if its okay.
thanks

**Comment by yostashiro** [comment]
@niyasraphy Thanks for the update. I believe it's been fixed.
