### ISSUE TITLE
[8.0] Timesheet sheet widget security error

### ISSUE THREAD

**Issue by adrienpeiffer** [odoo/odoo#8859]
Hi,

Here a scenario on runbot 8.0
## Steps to reproduce
- Go on runbot 8.0
- Logon with Admin
- Go on Settings/Technical/Security/Record Rule to add a new record rule to prevent to write, create, delete on analytic lines with a closed analytic account.
- Click on Create
- Fill in the name, change object to Timesheet line, check apply for write, create, delete and put this domain in the rule definition : `[('account_id.state', 'not in', ('close', 'cancelled'))]`
- Click on save
- Now, log out and logon with demo user
- Go on Human Resources menu and click on My current timesheet
- Click on Add a line in the widget
- Fill in the project, click on add and fill a cell with 1 hour
- Click on save
- Now, log out and logon with admin
- Open the selected analytic account in Accounting/Configuration/Analytic Accounting/Analytic Accounts in form view.
- Close the selected analytic account
- Now, log out and logon with demo user
- Go on Human Resources menu and click on My current timesheet
- Normally, you can see the first line
- Click on Add a line in the widget
- Fill in with an other analytic account than the previous line, click on add and fill a cell with 1 hour
- Click on save
## Expected behavior

the sheet is saved and contains two lines
## Current behavior

A security exception is raised

![security](https://cloud.githubusercontent.com/assets/8035793/10245009/da630b40-6903-11e5-92ee-8d405eff378a.png)

Thanks !

**Comment by adrienpeiffer** [comment]
cc/ @sbidoul

**Comment by sbidoul** [comment]
:+1: The procedure to reproduce on runbot is a bit long but it boils down to the following.

When you have a record rule preventing to create/update/delete analytic or timesheet lines on closed accounts, you cannot create timesheets on other projects in the same week because Odoo tries to delete and recreate lines that are untouched.

**Comment by Yenthe666** [comment]
Hi @adrienpeiffer,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
