### ISSUE TITLE
Copy+Paste in task doesn't work

### ISSUE THREAD

**Issue by seamens** [odoo/odoo#8860]
Hey, I've tried to copy and paste text to the description from Google, notepad++ and several other sources.
You can see it on the edit tab but after save it disappears.

**Comment by Yenthe666** [comment]
Hi @seamens,

Thanks a lot for the bug report and sorry for the late reply.
I've just tested this on the latest Odoo 9.0 and it is working fine out of the box.
If you still face this issue then please update your Odoo source code in order to fix this.

Regards,
Yenthe
