### ISSUE TITLE
[9.0] - UX - put the cursor in a field

### ISSUE THREAD

**Issue by jdegoy** [odoo/odoo#8862]
Currently on create I always have to use the mouse to select a first field.
Shouldn't it be possible to push create and start typing right away?

**Comment by qtheuret** [comment]
Try to put the attribute default_focus=True on the field where you want the focus.

**Comment by jdegoy** [comment]
OK, thanks for the heads up.
Will this not be done by the editor on most standard views?

**Comment by qtheuret** [comment]
I think not

**Comment by jdegoy** [comment]
Can you please check/escalate? For the people that are used to start typing right away while encoding this is really a step backwards...

**Comment by jdegoy** [comment]
Hello what is the status? Please check with qdp.

**Comment by pedrobaeza** [comment]
This behavior has been changed in latest versions and I think they are in very good shape right now. There's also a work for enabling even more the use of the keyboard, so I close this issue.
