### ISSUE TITLE
[9.0] - UX - loosing the data

### ISSUE THREAD

**Issue by jdegoy** [odoo/odoo#8863]
See attached screenshot. When you start typing in some fields (recipients on send of an e-mail for example) and click on the already inputted text to place your cursor where you want to make a correction, you will loose all your typing.
![screenshot at oct 02 13-50-55](https://cloud.githubusercontent.com/assets/11032154/10245970/2e8ad654-690d-11e5-9d70-4f0b9dc67f81.png)

**Comment by jdegoy** [comment]
Any update?

**Comment by pedrobaeza** [comment]
This is in part due to the design of the widget. Please check latest v11 where all the UI has been reworked to see if there are still problems. If so, feel free to open a new issue.
