### ISSUE TITLE
[9.0] Mass Mailing, You cannot update the translated value of field 'Body'

### ISSUE THREAD

**Issue by marcin-olejniczak** [odoo/odoo#8864]
I can't save changes in mailing if I change Mail Body. Odoo displays alert with warning 'You cannot update the translated value of field 'Body''.

**Comment by exemplari** [comment]
Same: 
You cannot update the translated value of field 'Body'  

Strange Behavior:
When using the interface must add a body and change the text then hit save. Doesn't cause warning unless you change the text in the builder interface.

**Comment by nicolas74** [comment]
Same behavior for us. Create works, but change is no possible.
You cannot update the translated value of field 'Body'.
We try to reduce to English only, but change text is always impossible with same message 

You cannot update the translated value of field 'Body'

**Comment by nicolas74** [comment]
For me issue has been removed after a last git pull
Now my repo tag is :
9.0 3571c0e  ir_translation: discard trivial translations (src=value) upon terms synchronization

**Comment by rco-odoo** [comment]
@marcin-olejniczak It probably has been fixed, because I cannot reproduce the issue.
