### ISSUE TITLE
[9.0 enterprise] web_gantt uses a GPL licence on the enterprise version !!

### ISSUE THREAD

**Issue by qtheuret** [odoo/odoo#8865]
On the enterprise version, the module web_gantt uses the lib dhtmlx which is under GPL licence.

If Odoo has paid the commercial version of dhtmlx, please change the licence on the file https://github.com/odoo/enterprise/blob/9.0/web_gantt/static/lib/dhtmlxGantt/sources/dhtmlxcommon.js

**Comment by odony** [comment]
Right, actually we have to replace the whole library code to use the 3.3.0 PRO edition (obfuscated because the Enterprise license doesn't allow distributing the original source).
Should be done soon, thanks for reporting!
