### ISSUE TITLE
Menu title "Action" is not translatable

### ISSUE THREAD

**Issue by SplashS** [odoo/odoo#88675]
Impacted versions: 15.0+

Steps to reproduce: Search for term "Action" in web.pot

Current behavior: There is no term

Expected behavior: Term "Action" for additional actions dropdown is translatable

Dropdown declared as:
```xml
        <DropdownMenu t-if="actionItems.length"
            title="env._t('Action')"
            items="actionItems"
            icon="'fa fa-cog'"
            closeOnSelected="true"
            hotkey="'u'"
            hotkeyTitle="'Additional actions'"
        />
```

I think .pot generator doesn't take into account construction `env._t('Action')`

**Comment by dsbenton** [comment]
Hello, do you know which file is responsible for translating this xml file (base.xml)?

**Comment by SplashS** [comment]
@dsbenton I’ve made some research.
There is strict comment in translate.py that attributes of owl components are not translatable. So I have no good idea how to fix it yet.

**Comment by Iucapad** [comment]
@SplashS Hi, we were fixing this issue and then we received your PR. Thank you! I'll keep you updated

**Comment by SplashS** [comment]
Fixed in https://github.com/odoo/odoo/pull/88740
