### ISSUE TITLE
[14.0+] Date widget keyboard input issue on some timezones.

### ISSUE THREAD

**Issue by LoisRForgeFlow** [odoo/odoo#88759]
Impacted versions: 14.0, 15.0, master

Steps to reproduce:

0. Be in a UTC positive timezone (I'm at UTC+2)
1. Open a form with a editable date field
2. Try to enter the value with the keyboard
3. press enter.

Current behavior:
The date applied is 1 day less than what was input.

Expected behavior:
Date entered is correct.

Video/Screenshot link (optional):
Example from odoo runbot v14 CE (it can be reproduced in v15, master, CE, EE...):

![Peek 2022-04-14 12-25](https://user-images.githubusercontent.com/23449160/163368671-888608ad-9b15-4004-82d4-f409614dc2d8.gif)

@ForgeFlow

**Comment by gdgellatly** [comment]
I don't think this is legit, v14 EE in UTC +12/13 and never had an issue. My guess is the timezone mismatch error on the right.

**Comment by LoisRForgeFlow** [comment]
It was not related to the timezone warning, in the real instances where I found the issue there were no warning. Anyway, I just tested again with latest code and it seems that the problem it is gone (maybe a side effect of some other fix). Closing.
