### ISSUE TITLE
[9.0] question /maybe bug: Where is the suplier price list?

### ISSUE THREAD

**Issue by nhomar** [odoo/odoo#8875]
![](https://www.evernote.com/l/AJ7dfzOEfUVNG51ChEkCULhh8cvYJMu4eHIB/image.png)
![](https://www.evernote.com/l/AJ7GKxBjtd9CtLjhh-vohecNpDPBY-DA_0IB/image.png)
![](https://www.evernote.com/l/AJ6KR4Pd_lhBIbF_D_ao_ygaRWNTC25QGkMB/image.png)

**Comment by antonylesuisse** [comment]
Supplier pricelist have been replaced by supplier info. qty price date_start date_end. The supplier info is automatically saved when you confirm a purchase order. Purchases->Supplier Pricellist (actually  product.supplierinfo).
