### ISSUE TITLE
Coveralls in Odoo branch

### ISSUE THREAD

**Issue by danimaribeiro** [odoo/odoo#8878]
Can we have coveralls configured in Odoo branch ?

I'd like to create unit tests for Odoo, it'll help to see where we need to create tests.

A good example of how the community can help was in the creation of 9.0 documentation, I think you guys could organize something about the unit tests, I'd be more than happy to create some unit tests to help improve Odoo codebase.

**Comment by mart-e** [comment]
Hello

Sorry the coverage is not a feature in the [runbot](http://runbot.odoo.com/runbot) so I would advise you to check the [runbot repository](https://github.com/odoo/odoo-extra/tree/master/runbot) to submit such addition (however unlikely it will be added any time soon as we are trying to reduce the test time).
As said Pedro, you are welcome to submit tests if you believe there is an untested feature.

Regards

**Comment by danimaribeiro** [comment]
Ok, thanks.
