### ISSUE TITLE
[9.0] custom field not visible

### ISSUE THREAD

**Issue by dcorio** [odoo/odoo#8882]
quite odd problem here.
i just tried to add a simple field:

```
class ResPartner(models.Model):
    _inherit = 'res.partner'
    test = fields.Char('Test')
```
the field has been added to the model (checked on Settings > Database Structure > Models), but it looks like i cannot use it on views.
Even by using the view editor (Developer mode > Debug > Manage Views) i cannot select the custom field cause it's not present in the list.

Do i have to pay attention to something new when developing custom modules on v9?

**Comment by nim-odoo** [comment]
You might need to do a -u on the corresponding model.
