### ISSUE TITLE
[9.0] User access rights not working correctly

### ISSUE THREAD

**Issue by edsersolis** [odoo/odoo#8886]
User access rights -> administration not working as it should. Only settings or empty work.

Configuration and access rights won't give the privileges to the selected user but will show the menu on every module, however when clicked an error will show up stating that only Administration -> Settings has the privilege to access it.

Also when this error shows up the display frame will split in two, freezing the top frame and showing the following information in the bottom one.

To replicate the issue: 
1. Create a user with Administration -> Configuration or Access Rights
2. Go to Sales (or any other module)
3. Click on Configuration -> Settings
4. The error will show up, click OK
5. Click on Sales -> Customers or any other
6. The customers screen will show in the bottom frame and the last viewed information will be freezed on top one.

To fix the display the user has to refresh the webpage and everything goes back to normal.

See attached screenshots:

![error00](https://cloud.githubusercontent.com/assets/6585110/10269918/35004db6-6ab1-11e5-84b9-4d62e948fd62.PNG)
![error01](https://cloud.githubusercontent.com/assets/6585110/10269919/35027e7e-6ab1-11e5-8def-2e9c54c31c91.PNG)
![error02](https://cloud.githubusercontent.com/assets/6585110/10269920/35038260-6ab1-11e5-81c0-6bcbcc6a4cb3.PNG)

**Comment by WHPODOO** [comment]
Its not react whatever you say :-1:  You must check on updated branch :confused:

**Comment by edsersolis** [comment]
Yes, I have to check again because this thread is 4 days old and updates
are coming live every day.

Will open a new one if this happens after updating.

Atentamente,

Edser G. Solís

Ingeniero en Tecnologías de la Información y Comunicación | MDETI(c)

Correo: edsersolis@gmail.com | Móvil: 829.920.2009

: : Mensaje enviado desde dispositivo móvil. : :

**Comment by edsersolis** [comment]
Just tried on the latest build (20151008) and still does the same. Will try to do it on a fresh installation to see if it still happens.

Don't know if maybe the OS or browser may be the issue.
OS: Elementary OS Freya
Browser: Chromium
Virtualization: VMWare Workstation 12

**Comment by WHPODOO** [comment]
@edsersolis  its working for me hope so you face this problem for another reason :cookie:
