### ISSUE TITLE
typo in odoo/odoo/release.py 

### ISSUE THREAD

**Issue by davidszkl** [odoo/odoo#88866]
Impacted versions:

Steps to reproduce:

Current behavior:
     Line 12, word 5:    opera'r'ors 
Expected behavior:
     should be opera't'ors
Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
hi @davidszkl ,
fixed in:  https://github.com/odoo/odoo/commit/c336dddab8bc1121ac54940489cf001fadcb7fc1

thanks
