### ISSUE TITLE
[9.0] Display is messy when website module is installed in Ubuntu 12.04 LTS

### ISSUE THREAD

**Issue by atchuthan** [odoo/odoo#8892]
After installing Odoo 9.0 + Enterprise modules, I used the odoo document to install dependency packages of website through this link: https://www.odoo.com/documentation/8.0/setup/install.html#source-install

I am using current odoo git repository and have the latest revision upto f12e1c26e9998d2f2c7093135f57b6e31467725a.

**root@harmony6:/opt/odoomaster9/v9.0# wget -qO- https://deb.nodesource.com/setup | bash -
root@harmony6:/opt/odoomaster9/v9.0# apt-get install -y nodejs
root@harmony6:/opt/odoomaster9/v9.0# sudo npm install -g less less-plugin-clean-css**
/usr/bin/lessc -> /usr/lib/node_modules/less/bin/lessc
npm WARN unmet dependency /usr/lib/node_modules/npm/node_modules/fstream-ignore requires minimatch@'^2.0.1' but will load
npm WARN unmet dependency /usr/lib/node_modules/npm/node_modules/minimatch,
npm WARN unmet dependency which is version 1.0.0
npm WARN unmet dependency /usr/lib/node_modules/npm/node_modules/read-cmd-shim requires graceful-fs@'^4.1.2' but will load
npm WARN unmet dependency /usr/lib/node_modules/npm/node_modules/graceful-fs,
npm WARN unmet dependency which is version 3.0.2
npm WARN unmet dependency /usr/lib/node_modules/npm/node_modules/read-package-tree requires read-package-json@'^2.0.0' but will load
npm WARN unmet dependency /usr/lib/node_modules/npm/node_modules/read-package-json,
npm WARN unmet dependency which is version 1.2.7
npm WARN unmet dependency /usr/lib/node_modules/npm/node_modules/readdir-scoped-modules requires graceful-fs@'^4.1.2' but will load
npm WARN unmet dependency /usr/lib/node_modules/npm/node_modules/graceful-fs,
npm WARN unmet dependency which is version 3.0.2
less-plugin-clean-css@1.5.1 /usr/lib/node_modules/less-plugin-clean-css
└── clean-css@3.4.5 (commander@2.8.1, source-map@0.4.4)

less@2.5.3 /usr/lib/node_modules/less
├── graceful-fs@3.0.8
├── mime@1.3.4
├── image-size@0.3.5
├── promise@6.1.0 (asap@1.0.0)
├── errno@0.1.4 (prr@0.0.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── source-map@0.4.4 (amdefine@1.0.0)
└── request@2.64.0 (aws-sign2@0.5.0, forever-agent@0.6.1, caseless@0.11.0, stringstream@0.0.4, tunnel-agent@0.4.1, oauth-sign@0.8.0, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, node-uuid@1.4.3, qs@5.1.0, tough-cookie@2.1.0, combined-stream@1.0.5, form-data@1.0.0-rc3, mime-types@2.1.7, http-signature@0.11.0, hawk@3.1.0, bl@1.0.0, har-validator@1.8.0)
**root@harmony6:/opt/odoomaster9/v9.0# lessc -v
lessc 2.5.3 (Less Compiler) [JavaScript]
root@harmony6:/opt/odoomaster9/v9.0# npm -v
1.4.28
root@harmony6:/opt/odoomaster9/v9.0# nodejs -v
v0.10.40
root@harmony6:/opt/odoomaster9/v9.0# node -v
v0.10.40**

![image](https://cloud.githubusercontent.com/assets/4667326/10277857/a05cd7bc-6b76-11e5-939c-48b59fdc0474.png)

Need help..!

**Comment by nhomar** [comment]
There is some help arround, you need install only the npm stuff and less look for the txt of error on google you will find the bug (I didnt remember the exact one yet)

But IMHO on v9.0 this should come with a huge warning in the start of the server this error is duplicated like 10 times, it send a message **improve the help**

**Comment by lem8r** [comment]
You have to install dependencies mentioned in your log. Or I'm missing something?

**Comment by antonylesuisse** [comment]
I close this issue, @sle-odoo is working on both 

- updating the documentation
- displaying an helpful _logger.warning() when lessc  executable cannot be spawned (with the installation instruction).

If you use debian/ubuntu just

apt-get install node-clean-css node-less

**Comment by atchuthan** [comment]
$ sudo apt-get install node-clean-css node-less
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package node-clean-css

But lessc works only with Odoo 9.0 community and not with Odoo 9.0 + Odoo 9.0 enterprise repository.

**Comment by atchuthan** [comment]
The problem got resolved once I changed the addons_path

**Working**
addons_path = /opt/odoomaster9/enterprise_modules,/opt/odoomaster9/v9.0/addons

The problem was due to loading of less package available in community version for the enterprise modules.  After changing the addons_path, the correct library package was loaded and no problem with less.
