### ISSUE TITLE
[7.0] [BUG] Calendar view problem with viewed hours

### ISSUE THREAD

**Issue by jlaloux** [odoo/odoo#8896]
Step to reproduce the problem:
1. Go on the last v7 on Runbot. See the calendar in the messaging menu.
   By default, you'll see this:
   ![image](https://cloud.githubusercontent.com/assets/7678583/10279189/c7fccab0-6b63-11e5-97b2-ae56dd7ea4ca.png)

If you click on week you will see this:
![image](https://cloud.githubusercontent.com/assets/7678583/10279200/d804f32e-6b63-11e5-89dd-a7d68dfad541.png)

You can see that the calendar you see starts by default at 8 am.

Imagine you have a client who want to see the view week by default. you'll create a view that will inherit this view to add the parameter "mode" to the calendar view. For this explanation, i'll change directly the related view to explain you the problem.

![image](https://cloud.githubusercontent.com/assets/7678583/10279239/447866bc-6b64-11e5-97b4-640c6d3073d4.png)

And here is the result:
![image](https://cloud.githubusercontent.com/assets/7678583/10279243/56b61d06-6b64-11e5-9942-ab5049f4eddd.png)

You correctly see the week view when you click on the menu entry but the default start time is not set to 8 am anymore. If you click on "month" and then on "week" again. The calendar will start again from 8 a.m.

**Comment by rvalyi** [comment]
related to an unsupported Odoo version. Can it be closed?
cc @Yenthe666

**Comment by Yenthe666** [comment]
Hi @jlaloux,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
@rvalyi thanks a lot for the ping!

Regards,
Yenthe
