### ISSUE TITLE
[15.0] UncaughtPromiseError > TypeError Uncaught Promise > Cannot read properties of undefined (reading 'title')

### ISSUE THREAD

**Issue by funkymaster** [odoo/odoo#88986]
Impacted versions:
15.0-20220417 (Community Edition)

Steps to reproduce:
Try to edit anything, f.i. a user.

Current behavior:
TypeError: Cannot read properties of undefined (reading 'title')
    at QWeb.eval (eval at _compile (http://xxx.xxx.xxx.xxx:8069/web/assets/288-77414a1/web.assets_common.min.js:1026:178), <anonymous>:44:60)
    at QWeb.render (http://xxx.xxx.xxx.xxx:8069/web/assets/288-77414a1/web.assets_common.min.js:1015:20)
    at ActionMenus.__render (http://xxx.xxx.xxx.xxx:8069/web/assets/288-77414a1/web.assets_common.min.js:1344:33)
    at ActionMenus.__prepareAndRender (http://xxx.xxx.xxx.xxx:8069/web/assets/288-77414a1/web.assets_common.min.js:1342:29)

Expected behavior:
Edit view should open.
This error is an absolute nightmare. Odoo can no longer be used because nothing can be edited. Please correct the error immediately. Thanks!

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by funkymaster** [comment]
As a temporary solution, I downgraded to version 15.0-20220413, where the error is obviously not there.

**Comment by nethead25** [comment]
Same issue. turning on debug mode with assets seems to resolve for now. Crippling bug though

**Comment by parth1568** [comment]
I am facing the same issue. It will be thank full if some one can help in downgrading as well.

**Comment by funkymaster** [comment]
> I am facing the same issue. It will be thank full if some one can help in downgrading as well.

Download the desired version from here: https://nightly.odoo.com/15.0/nightly/
As far as I can tell, the version 15.0-20220413 is not affected by the bug.
Maybe 15.0-20220414 - 15.0-20220416 are ok as well, but I don't know if they are ok or not, because I have not tested them.
Version 15.0-20220417 is definitely broken.

**Comment by nethead25** [comment]
Hi, an individual on the Odoo forum was able to provide a solution for me, it seems the asset bundles need to be regenerated.

Please see here:
https://www.odoo.com/forum/help-1/suddenly-receiving-js-errors-trying-to-open-all-records-when-not-in-debug-mode-202484

How to regenerate assets from the GUI
Enable developer mode.
Open the debug menu from the toolbar.
Select Regenerate Asset Bundles.

**Comment by parth1568** [comment]
Thank you, I have already generated Assets and log out and log in works fine.

**Comment by funkymaster** [comment]
Thank you for sharing the information, that seems to work.
A small hint: This only works if developer mode with assets is activated.
The option to regenerate assets would also be available in normal developer mode, but it doesn't improve anything there.
