### ISSUE TITLE
html messages not displaying correctly in messages

### ISSUE THREAD

**Issue by rolandwells** [odoo/odoo#890]
some html messages don't display correctly, specifically with tables in them, and there is no way to expand the view or view separately

***Impacted versions:***
Running on Ubuntu / Self-hosted
Version 7.0-20140501-232919
 
***Steps to reproduce:***
 1.  receive html email via openerp messages gateway, which includes html tables wider than display area

***Current behavior:***
cuts off portion of email

***Expected behavior:***
display full email in messages window, or allow click to view full message

![screenshot from 2014-07-03 02 30 10](https://cloud.githubusercontent.com/assets/8055681/3466639/fef7aae8-0283-11e4-80c5-62fb126d5957.png)

**Comment by Yenthe666** [comment]
Dear @rolandwells,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
