### ISSUE TITLE
[9.0] sale: invoicing policy by product should be by partner?

### ISSUE THREAD

**Issue by moylop260** [odoo/odoo#8900]
I have 2 partners (axelor and agrolait) and one product (imac).
With axelor I need to configurate the invoicing policy with invoice from order.
With agrolait I need to configurate the invoicing policy with invoice from picking.

Should the field invoice policy configurate in partner?

**Comment by nhomar** [comment]
just to extend the work case, this even needs to be chageable in the transaction itself also.

Then: On PArtner - On roduct, but if I am not agree, in the transaction itself, Is this possible?

**Comment by lem8r** [comment]
Curious what will happen now if one SO contains products with different invoice policy. How invoice will be created?

**Comment by nim-odoo** [comment]
@lem8r : the invoice will be created based on what is to be invoiced. Basically, when something is to be invoiced, the SO line turns blue.

To answer the original question, the invoice policy is now strictly on the product. This is a design decision.

**Comment by lem8r** [comment]
@nim-odoo thanks

**Comment by moylop260** [comment]
@nim-odoo
Thank for reply
Then, I will need create a product by each partner?

Is this a good design?

**Comment by mlaitinen** [comment]
@nim-odoo Sorry for digging up an old issue, but is there any reasoning for the design decision for why "the invoice policy is now strictly on the product"?

My use case is identical to OP's; one customer pays the invoice based on the delivered products and gets a payment term of 30 days. Another customer buys the same products, but has to pay immediately before the delivery.

We created a module that allows the user to override this setting on the sales order. It works as expected but feels very wrong. Why do we have to hack Odoo to make such a basic operation possible?
