### ISSUE TITLE
[9.0] stock: tracking by unique serial number allow non-unique serial number

### ISSUE THREAD

**Issue by moylop260** [odoo/odoo#8901]
Configurate your instance to work with serials
Create a new product with"by unique serial number" check true.
Create a new picking with qty=2 and confirm it adding serial values.
Add a unique serial with qty=2.

Expected
Error

Saw
Allowed

**Comment by jco-odoo** [comment]
I wonder how you did this as normally for products with serial number tracking, the quantity is not even visible.

**Comment by Yenthe666** [comment]
@moylop260 any feedback here?

**Comment by moylop260** [comment]
This issue is not reproduced anymore.
Thanks!
