### ISSUE TITLE
[8.0] Reconciliantion accounts in l10n_br

### ISSUE THREAD

**Issue by cmsalmeida** [odoo/odoo#8902]
In order for the payment wizard to work, the accounts in invoice header, account_id, should have reconcile=True.
In l10n_br the accounts are, amongst others, "Clientes" and "Fornecedores", a the chart of account should make them by default as reconciliable.

**Comment by mart-e** [comment]
Fixed at 48eb1f6df739682e23e3472292389d5a06cb15ff, thanks
