### ISSUE TITLE
[ALL Versions, Security] Security vulnerability when default company data includes yourcompany.com

### ISSUE THREAD

**Issue by nicholas-itpedia** [odoo/odoo#8903]
**Current behavior:**
When CRM modules is installed and no other configuration is done, the default company website is http://www.yourcompany.com/ 
If any e-mails are sent from the database, there will be a "My Company" link to http://www.yourcompany.com/ in the e-mail. Users have reported malicious activity at the sites forwarded by http://www.yourcompany.com/

**Expected behavior:**
When CRM modules is installed, the default company website SHOULD BE http://www.example.com

Steps to reproduce:
1. Create a blank (non demo data) Odoo database
2. Install CRM module
3. Send any e-mail from the database that includes the "My Company" link
 * click on "My Company" link

**Notes:**

* The example.com domain is managed by IANA [Managed Reserve Domain](http://www.iana.org/domains/reserved):

>As described in RFC 2606 and RFC 6761, a number of domains such as example.com andexample.org are maintained for documentation purposes. These domains may be used as illustrative examples in documents without prior coordination with us. They are not available for registration or transfer.

* **Please fix this on ALL stable versions of Odoo**
* **Please fix this for all modules with demo data**

**Comment by mart-e** [comment]
Hello,

How is that a security issue ? This is basic configuration that anybody in production should not have.
Pull request welcome to change the default data.

If you believe have found a security vulnerability, I advise you to check our [responsible disclosure](https://www.odoo.com/page/responsible-disclosure) procedure page.

**Comment by nicholas-itpedia** [comment]
This is a security issue because the DEFAULT setting directs users to an insecure website. Please read the part:
> Users have reported malicious activity at the sites forwarded by http://www.yourcompany.com/

@mart-e stated:
> This is basic configuration that anybody in production should not have.

If this is a configuration that anybody in production should not have, then why is it the DEFAULT configuration when a module is installed?

Sorry for not following the procedure for [Responsible Disclosure](https://www.odoo.com/nl_NL/page/responsible-disclosure) We will submit this issue to security@odoo.com . 

I assume the pull request will impact many Odoo SA written modules. Isn't it best that Odoo SA fix this issue since theoretically they know the source best?

Should this be announces on the community mailing list for software developers creating community modules with demonstration data?

**Comment by antonylesuisse** [comment]
It's not Security vulnerability according to our policy. But i would accept a change to example.com in base_data.xml because it resolves to a IANA parked domain. In Odoo online the correct domain is always set.

**Comment by nicholas-itpedia** [comment]
@antonylesuisse I am confused. Are you asking us to submit a pull request to fix this issue? The issues is closed, was it fixed by a commit?
