### ISSUE TITLE
[9.0] account_yodlee and account_plaid have unresolved references.

### ISSUE THREAD

**Issue by richard-willowit** [odoo/odoo#8909]
Niether account_yodlee or account_plaid can currently be installed.

Both have references to

    <div name="bank_statement_import_options" position="after">

which does note appear to be defined in any view anywhere.

**Comment by nim-odoo** [comment]
This is defined here: https://github.com/odoo/odoo/blob/9.0/addons/account/views/res_config_view.xml#L211

**Comment by richard-willowit** [comment]
@nim-odoo Oh man - thanks.  I cannot believe it.  That change was committed between my pulling of 9.0 base and 9.0 enterprise!!!!
