### ISSUE TITLE
forwarded messages getting stripped incorrectly

### ISSUE THREAD

**Issue by rolandwells** [odoo/odoo#891]
forwarded emails that are pulled into messages in openerp get prior portions of the thread stripped before displaying, even when clicking on the read more link, the forwarded message is not displayed

***Impacted versions:***
Running on Ubuntu / Self-hosted
Version 7.0-20140501-232919
 
***Steps to reproduce:***
 1.  receive forwarded message via openerp email gateway to messages

***Current behavior:***
strips forwarded message

***Expected behavior:***
display full thread, including forwarded portion

***NOTE***
full thread is confirmed present in "settings->email->messages" for the forwarded message

**Comment by Yenthe666** [comment]
Dear @rolandwells,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
