### ISSUE TITLE
[8.0] Register invoice payment through Python code

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#8913]
t seems I can't properly register Invoice payment through Python code (without using Pay button in invoice).

I'm wondering what it is: bug, missing feature or I need to adjust implementation?

I'm trying to implement payment plan functionality where you could choose multiple  supplier invoices that are not paid and then pay it at once.
But it seems some parts of the voucher workflow are skipped when trying to mimic same thing through Python code.

My code runs without errors, it creates journal entries with correct amounts. It also creates vouchers, but vouchers are without lines and invoices are kept in open state. If I just go to Odoo interface
and do same thing through 'Pay' button, then everything goes fine. So is there no way to properly register payments without using interface? Does it break workflow if I would create account.voucher record through Python?

I'm trying to mimic same behavior as using Odoo interface.

My method to handle it look like this:

``` python
    @api.multi
    def pay_invoices(self):
        """
        Pays invoices that are open
        """
        self.ensure_one()
        if not self.journal_id:
            raise ValidationError(_("You must enter Payment Method !"))

        journal = self.journal_id
        if not journal.default_credit_account_id or not journal.default_debit_account_id:
            raise ValidationError(_('Please define default credit/debit accounts on the journal "%s".') % (journal.name))       
        if not self.period_id:
            raise ValidationError(_("You must enter Period"))
        if not self.company_id:
            raise ValidationError(_("You must enter Company"))

        AccountVoucher = self.env['account.voucher']
        voucher_values = {
            'type': 'payment',
            'journal_id': self.journal_id.id,
            'period_id': self.period_id.id,
            'account_id': journal.default_credit_account_id.id,
            'date': self.date,
        }
        vouchers = AccountVoucher
        for inv in self.invoice_ids:
            context = dict(self._context, payment_expected_currency=inv.currency_id.id, close_after_process=True,
                invoice_id=inv.id)
            voucher_values.update({
                'partner_id': inv.partner_id.id,
                'amount': inv.residual,
                'reference': inv.name,
                #'invoice_id': inv.id, 
            })
            voucher = AccountVoucher.with_context(context).create(voucher_values)
            #Add voucher to recordset
            vouchers |= voucher

        if vouchers:
            # Register payments
            vouchers.with_context(context).button_proforma_voucher()
```

P.S. also voucher workflow have on_create set to True, so I think it shuold properly instantiate workflow when new voucher is created. Am I right?
Also there is similar question here https://www.odoo.com/forum/help-1/question/how-to-register-payments-automatically-trough-python-code-91488 but no one was able to answer it as I see.

**Comment by lapagept** [comment]
Is your code ok? Should I use it?

**Comment by Yenthe666** [comment]
Hi @oerp-odoo,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
