### ISSUE TITLE
selectable=False doesn't hide fields from advanced search

### ISSUE THREAD

**Issue by hbrunn** [odoo/odoo#892]
In https://github.com/odoo/odoo/blob/master/addons/web/static/src/js/search.js#L1968, we check if a field has the selectable attribute set. This comes in handy for hiding fields if we add technical fields without a useful search function in order not to confuse the user.

Unfortunately, in https://github.com/odoo/odoo/blob/master/openerp/osv/fields.py#L1669, those values are only set if they are not falsey. I think changing this to getattr(field, arg, None) == None should fix the problem without side effects.

**Comment by Yenthe666** [comment]
Dear @hbrunn,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe

**Comment by thomaspaulb** [comment]
For anyone still dealing with this issue and ending up here: the bug was still there in 11.0, and [this PR](https://github.com/odoo/odoo/pull/23021) to fix it was refused.
