### ISSUE TITLE
[8.0] Tax codes report raise QWebException: "chart_tax_id" while evaluating

### ISSUE THREAD

**Issue by thomich** [odoo/odoo#8923]
Impacted versions:
- 8.0

Steps to reproduce:
1. open Accounting / Configuration / Taxes / Tax Codes
2. open any Tax Code
3. press Print / Account Tax

Current behavior:

QWebException: "chart_tax_id" while evaluating
"get_lines(data['form']['based_on'], data['form']['company_id'], data['form']['chart_tax_id'])"
Details: http://paste.ubuntu.com/12689915/

Expected behavior:
- Tax Code report

Test on:
- different 8.0 instances
- runbot: http://105817-8-0-6b6d73.runbot8.odoo.com/web

**Comment by ema-brua** [comment]
Hola pudiste solucionar? Gracias

**Comment by jlaloux** [comment]
Hello, i confirm this bug. Same issue
