### ISSUE TITLE
[9.0] Timesheet wrong weeknumber

### ISSUE THREAD

**Issue by MarkLeemans** [odoo/odoo#8927]
Hello,

The timesheet says it's week 40, but it is actually week 41. I've checked the timezone and all the settings but I can't find a fix for this? I've the latest 9.0 stable release.

Thanks

**Comment by MarkLeemans** [comment]
In the report of the timesheet, the weeknumber is 41, while at the timesheet its week 40?

**Comment by MarkLeemans** [comment]
This problem is still in the latest version of Odoo!

**Comment by mart-e** [comment]
Thanks for the report, fixed at bc0986f53bc03bb958f3acce10ec23805afb7b6a
For the next report, please check [contributing guidelines](https://github.com/odoo/odoo/wiki/Contributing) for proper report format
