### ISSUE TITLE
[Issue] wrong sort with accent

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#89327]
Impacted versions: all

Steps to reproduce:
Create 'AAAA', 'EEEEE', 'ÉÉÉÉÉÉ', 'ZZZZZ' partner
open the view
you see:
<img width="388" alt="image" src="https://user-images.githubusercontent.com/16716992/164477788-b5a1c736-39d2-4395-b33d-2fa22add9edb.png">

It should be:
'AAAA', 'EEEEE', 'ÉÉÉÉÉÉ', 'ZZZZZ'

https://14729559-14-0-all.runbot49.odoo.com/web#action=164&model=res.partner&view_type=list&cids=1&menu_id=122

Same issue with order or field in view
<img width="758" alt="image" src="https://user-images.githubusercontent.com/16716992/164503954-6199e312-23df-49c1-a000-29bf8cba363e.png">

@rco-odoo

**Comment by nilshamerlinck** [comment]
Hi @fmdl this is the expected default behavior, see https://github.com/odoo/odoo/pull/25196 and grab a coffee because it's a long one :)

**Comment by fmdl** [comment]
@nilshamerlinck it is fixed in v15 ?

**Comment by nilshamerlinck** [comment]
Won't be as it's not considered a bug :)

If this is a problem for you, you can create a new db with `createdb --lc-collate=en_US.UTF8` and restore a dump of your current database in it.

**Comment by fmdl** [comment]
@rco-odoo 

`ORDER BY unaccent(name)`  doesn't work ?
