### ISSUE TITLE
[9.0] Canadian Chart of Accounts: Incorrect Type for Tax receivable and Tax to pay

### ISSUE THREAD

**Issue by stephane-mtl** [odoo/odoo#8934]
With the Canadian Chart of Account, the following tax accounts are created with the wrong Type. 

118100 - GST receivable, PST/GST receivable and all HST receivable are created with an account Type set to Current Liabilities. This is incorrect, the Type should be Current Assets. 

213100 - GST to pay, PST/GST to pay and all HST to pay are created with an account Type set to Current Assets. This is incorrect, the Type should be Current Liabilities.

**Comment by XeJames** [comment]
I am confused.  Odoo 10 still has 118100 as a liability and 213310 as  an asset.  Yet there are two [FIX] reported in V9 saying that they have been corrected.

This is making it really tough to port my existing books into Odoo as my Opening Balance is off (unless I move those accounts into the correct types).

Am I misunderstanding - or has this bug been reintroduced into V10?

**Comment by pedrobaeza** [comment]
Closing as there's already a PR addressing this. I have pinged some people in the PR to see if we can move this.
