### ISSUE TITLE
[9.0] Wrong Expense Account used for purchases

### ISSUE THREAD

**Issue by stephane-mtl** [odoo/odoo#8935]
In Odoo version 9.0 as of today Oct 6, when creating Vendor Bill the Expense Account 214100 CANADA REVENUE AGENCY is always selected regardless of the Expense Account set on the product. 

The Expense Account on the Bill item line should be set according to the Expense Account set at the product level. 

The same problem exist if creating an invoice through the Sales Order process. 

This problem did not exist with the Release Candidate version that I pulled from GitHub on September 17. 
![screen shot 2015-10-06 at 20 49 16](https://cloud.githubusercontent.com/assets/14997544/10326720/8cbf01b6-6c6c-11e5-8dd1-acd5a383f19e.png)
![screen shot 2015-10-06 at 20 49 56](https://cloud.githubusercontent.com/assets/14997544/10326721/9350e4cc-6c6c-11e5-8dfb-96064565d16d.png)

**Comment by lem8r** [comment]
Anglo-Saxon accounting disabled?

**Comment by stephane-mtl** [comment]
Use anglo-saxon accounting is enabled under the configuration tab of my company. 

![screen shot 2015-10-07 at 14 02 44](https://cloud.githubusercontent.com/assets/14997544/10346280/5f30fe12-6cfc-11e5-967b-c033c69f5355.png)

**Comment by lem8r** [comment]
In such case stock input account is used, which is set on product category
7 жовт. 2015 21:05 "stephane-mtl" <notifications@github.com> пише:

**Comment by stephane-mtl** [comment]
Well, this is not what is happening. Look at the second screen shot from my original post which is a screen shot of the product used on the invoice line. You will see the product is set to put expenses to the account 510300 Office Expenses so this is the account that should show up automatically when creating the Bill but instead, the account 214100 CANADA REVENUE AGENCY is set. It seems with the current Odoo version this account 214100 is overriding whatever is set at the product category. 
This is why I'm reporting this bug. 
It was working fine in the release candidate version pulled from GitHub on Sep 17.

**Comment by lem8r** [comment]
Go to `Inventory -> Configuration -> Settings -> Product Categories -> All`
and change Stock Input Account to what you need

**Comment by stephane-mtl** [comment]
I tried what you suggested, changing the expense account through Inventory -> Configuration -> Settings -> Product Categories -> All  but still have the same behaviour. 
I also tried with the USA chart of account and I get the same behaviour. 
I also get the same behaviour when running the demo version from the Odoo website. 
Seems like a bug introduced recently.

**Comment by qdp-odoo** [comment]
hello,

i'm a bit puzzled about your configuration. Can you depict what input and expense accounts you have for your product and its category? Can you also check the fiscal position of the involved partner (check if it's not mapping the expected account to your current result)?

thanks

**Comment by stephane-mtl** [comment]
Here is what I do to reproduce the problem:

I create a new database without loading the demo data
With the fresh database I install the following Apps:
 - Accounting and Finance
 - Sales Management
 - Purchase Management
 - CRM
 Then I go to Accounting -> Settings -> I click click Install more chart templates then I install Canada - Accounting
 
 I create a Vendor so I go Purchases -> Purchase -> Vendors -> Create button
 I enter minimal data as the following screen shots:
 
![screen shot 2015-10-08 at 11 44 01](https://cloud.githubusercontent.com/assets/14997544/10373817/b0b7b5ac-6dbd-11e5-93e8-16f37a12261e.png)
![screen shot 2015-10-08 at 11 44 16](https://cloud.githubusercontent.com/assets/14997544/10373829/cde1bde4-6dbd-11e5-878a-7e83ec4b5119.png)


 
 Then I create an expense account so I go Accounting -> Adviser -> Chart of Accounts -> click the Create button and create an account as per this screen shot:
![screen shot 2015-10-08 at 11 49 00](https://cloud.githubusercontent.com/assets/14997544/10373843/e6d0d772-6dbd-11e5-9baf-0c58a1964901.png)

 
 I create a product. I go to Purchases -> Purchase -> Products -> Create button and I create it as per the screen shots:
 
![screen shot 2015-10-08 at 11 51 28](https://cloud.githubusercontent.com/assets/14997544/10373859/08e1a954-6dbe-11e5-9a62-0b11b2793505.png)
![screen shot 2015-10-08 at 11 51 38](https://cloud.githubusercontent.com/assets/14997544/10373866/10581cd6-6dbe-11e5-93c5-01077c5742b0.png)
![screen shot 2015-10-08 at 13 15 58](https://cloud.githubusercontent.com/assets/14997544/10374024/cf931bb4-6dbe-11e5-8e5b-d4468fa2c3f7.png)


 Now I create a Vendor Bills from Purchases -> Control -> Vendor Bills
 
 Please note that upon clicking 'Add an item' the account 511100 Inside Purchases is set automatically but when selecting Product 1, the account becomes 214100 CANADA REVENUE AGENCY
![screen shot 2015-10-08 at 13 00 45](https://cloud.githubusercontent.com/assets/14997544/10373897/395e819c-6dbe-11e5-98f8-702ae5ab6d6b.png)
![screen shot 2015-10-08 at 13 01 06](https://cloud.githubusercontent.com/assets/14997544/10373909/41ece326-6dbe-11e5-88e5-7a156a050523.png)




 
 I tried all scenarios with Fiscal Position and default tax and when selecting a product, the account 214100 CANADA REVENUE AGENCY get selected. 
![screen shot 2015-10-08 at 13 01 19](https://cloud.githubusercontent.com/assets/14997544/10373916/4b4d354c-6dbe-11e5-8a48-7796ee87f217.png)
![screen shot 2015-10-08 at 13 01 40](https://cloud.githubusercontent.com/assets/14997544/10373927/57ec3488-6dbe-11e5-9973-cf3345338339.png)

And here is the Product Category. 
![screen shot 2015-10-08 at 13 24 16](https://cloud.githubusercontent.com/assets/14997544/10374224/f766d3d2-6dbf-11e5-8383-2b489bb38504.png)

So when clicking on 'Add an item' on the Vendor Bill form, it's normal that the account 511100 Inside Purchases get set automatically. What is not correct though is the Stock Input Account get used when selecting a product. This was not the behaviour in the version I took from GitHub on September 16 so something changed between now and Sep 16 that cause this problem. 

Another note: If I create a product for purchase that is a service, I get the same behaviour, the account from Stock Input Account get used. With a service purchased there is really no Stock Input which is another evidence something is wrong with the current version.

**Comment by qdp-odoo** [comment]
hello again,

indeed, I followed your use case and had exactly the same results. Which can be explained as follow:
* the account you set up on the product was the expense account, while in anglo saxon accounting that's the stock input account that comes as default account in vendor bills. The stock input of the category 'All' is indeed 214100.
* there was a bug, fixed in revision 05868b5, where the stock input account was also taken for service products instead of the expense account.

So, apart of the service bug, the behavior is normal. If you want to use a specific account for your product, you can
* set up the stock input account on the product itself (but for some reason the field is hidden when the product is not in real time valuation...not sure why. A bit of custom view edition may be needed for you)
* or put your product in a specific category and set up the stock input account of this specific category to what you want.


Hope this helps. Since there's no more known bug here, i'm closing the issue.

Thanks,

**Comment by wtaferner** [comment]
Although I do not have customers with anglo saxon accounting...

**Thank you Quentin for the great work you and your team did on accounting and in general in R&D for Odoo!**

Do not forget that we are all (hopefully) grateful even though there is critics from various sides on various topics...most of them arise b/c they wanted to be heard at some point and nobody was listening...communication overflow and the never ending issue to filter the important and bring it to the right decision on Odoo's side ;-)

**Comment by stephane-mtl** [comment]
Thanks for the fix in revision 05868b5. It's now working fine for services.
