### ISSUE TITLE
It isn't obvious how one contributes to specific things like warehouse management

### ISSUE THREAD

**Issue by nbarnwell** [odoo/odoo#89477]
Is there one or more private repositories that folks outside odoo aren't allowed to contribute to, for the existing applications like warehouse management, etc?

**Comment by gdgellatly** [comment]
If it is a missing feature, or new feature then generally Odoo ignores/strongly discourages any community input or contribution. This is outlined in their documentation for their devs and in truth I don't necessarily disagree with it. 

You can look to to the github.com/OCA repositories for this kind of open source collaboration with 100's of repositories on specific topic areas.

For bug fixes etc, you can raise a PR but without an enterprise contract your odds are very very low. Generally raising an issue receives no official response without community uproar/enterprise contract.

There is also an enterprise repository with the extra modules required for enterprise.

Hope this helps.

**Comment by Feyensv** [comment]
Tickets submitted to the support through enterprise contract are indeed the best way to go for bugs :+1: 

Now that we effectively have codeowners, PR's fixing the bug "might" be resolved faster.
Some other points may help if you want a successful conclusion of your Issue/PR:
* a clear explanation of the problem (and the steps to reproduce it on runbot ideally)
* pinging the right person/team responsible of the scope/code (without spamming ofc)
* (PR only) code of quality, with clean commit(s) following the [guidelines](https://www.odoo.com/documentation/15.0/developer/misc/other/guidelines.html#commit-message-structure)
