### ISSUE TITLE
[9.0] Accounting Dashboard - the exchange rate not considered in the amount

### ISSUE THREAD

**Issue by oliverzgy** [odoo/odoo#8952]
The exchange rates are not considered in the amount on accounting dashboard. All the amount there is summed up without computing the exchange rates. - Latest Odoo 9.0 Community

**Comment by pedrobaeza** [comment]
This one is a bit old. Please try to reproduce the problem on latest v11 runbot, and if the problem remains, please explain how to reproduce it (which entries to add and what do you expect to see). Meanwhile, I close this.
