### ISSUE TITLE
Odoo 15 error instalation in Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by LSR29** [odoo/odoo#89533]
Hi friends,

This error has been presented after the installation of Odoo 15 in the latest Ubuntu:

Loaded: loaded (/lib/systemd/system/odoo.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sun 2022-04-24 21:16:57 -05; 2min 0s ago

File "/usr/lib/python3/dist-packages/odoo/tools/_vendor/sessions.py", line 29, in <module>
from werkzeug.posixemulation import rename
ModuleNotFoundError: No module named 'werkzeug.posixemulation'
odoo.service: Main process exited, code=exited, status=1/FAILURE
odoo.service: Failed with result 'exit-code'.

Is Odoo 15 not compatible with this version of Ubuntu?

Thank you!

**Comment by Yenthe666** [comment]
@mart-e any of you guys tested on 22.04 yet? :)

**Comment by mart-e** [comment]
Looks like an issue with werkzeug, should be solved with #87463

**Comment by chmuche** [comment]
Hello, I have an issue too running Odoo (from source) on Ubuntu 22.04.
This `git diff` solve for my case all the warnings and the error 
Tested with `workers` or `threaded`. 
Test pending for a full install and running all the test.

[diff_ubuntu_22.04-py3-10.txt](https://github.com/odoo/odoo/files/8552595/diff_ubuntu_22.04-py3-10.txt)
.

**Comment by d-fence** [comment]
Work in progress #88803
