### ISSUE TITLE
[9.0] Delivery method price doesn't apply price list rules

### ISSUE THREAD

**Issue by krueger80** [odoo/odoo#8968]
It would be useful to apply price lists on delivery method prices that are calculated either by querying the carrier web service API or by rules. We make different markup % on freight depending of the deal we made with our customers.

In my mind the delivery service is sold to customers so there is no reason not to apply price lists.

**Comment by rim-odoo** [comment]
You can still add a delivery product that works with a standard pricelist on your sale order, then use a different carrier for the picking.
