### ISSUE TITLE
[9.0] "Database creation error": on latest revision of 9.0.

### ISSUE THREAD

**Issue by richard-willowit** [odoo/odoo#8970]
Database creation error: "Mixing apples and oranges: None in res.groups(5, 4)" while parsing /home/richard/src/odoo-9.0/odoo/openerp/addons/base/security/base_security.xml:18, near <record model="res.groups" id="group_system"> <field name="name">Settings</field> <field name="implied_ids" eval="[(4, ref('group_erp_manager'))]"/> <field name="users" eval="[(4, ref('base.user_root'))]"/> </record>

**Comment by falinwa** [comment]
today I have the same problem too.
I think it because the new revision.
please fixed it.

**Comment by richard-willowit** [comment]
I have managed to get it working by manually reversing the code from this commit:

https://github.com/odoo/odoo/commit/85f6b7c02c1a426d3311ff8f787851133a8cb92d

**Comment by kkoci** [comment]
Ouch... I'm having this issue as well

**Comment by kkoci** [comment]
Only that code @richard-willowit ?

**Comment by richard-willowit** [comment]
Yes - I just took out the 4 lines and all was OK again.

**Comment by kkoci** [comment]
Good, thanks, I hope this get sorted out though

**Comment by mart-e** [comment]
Commit reverted at ff02b25b6ec22691556746bb2f0e337e37c12d11
Will check for a proper fix later.
Sorry for the inconvenience.
