### ISSUE TITLE
[9.0] Bug When installing timesheet

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#8975]
Hi Odoo,

I found a bug when I want to install timesheet on new database,
I got this error message:

Error details:
Element '<group name="analytic_account_purchase">' cannot be located in parent view

Error context:
View `account settings`
[view_id: 618, xml_id: n/a, model: account.config.settings, parent_id: 552]
None" while parsing /opt/odoo90/enterprise/currency_rate_live/views/account_config_setting_view.xml:4, near
<record id="view_account_currency_config_settings_inherit" model="ir.ui.view">
            <field name="name">account settings</field>
            <field name="model">account.config.settings</field>
            <field name="inherit_id" ref="account.view_account_config_settings"/>
            <field name="arch" type="xml">
                <group name="analytic_account_purchase" position="after">
                    <group string="Live Currency Rate" attrs="{'invisible': [('group_multi_currency', '!=', True)]}">
                        <label for="id" string="Configuration"/>
                        <div>
                            <div>
                                <label for="currency_interval_unit"/>
                                <field name="currency_interval_unit" class="oe_inline"/>
                                <button string="Update Now" name="update_currency_rates" type="object" class="oe_link"/>
                            </div>
                            <div>
                                <label for="currency_next_execution_date"/>
                                <field name="currency_next_execution_date" class="oe_inline"/>
                            </div>
                            <div>
                                <label for="currency_provider"/>
                                <field name="currency_provider" class="oe_inline"/>
                            </div>
                        </div>
                    </group>
                </group>
            </field>
        </record>

**Comment by nim-odoo** [comment]
Solved in https://github.com/odoo/odoo/commit/fa8a83a9d71d8af4b9ba186d0ee8c0ca5c94e55a I guess.
