### ISSUE TITLE
odoo v9 : sequence appear wrong in Manufacturing Orders

### ISSUE THREAD

**Issue by AmitBista** [odoo/odoo#8978]
Step for reproduce

1 go to Manufacturing Orders
2 create MO (sequence 1)
3 now discard this MO
4 again create mo, expect (sequence 1), but appear (sequence 2)

what about MO sequence 1 ?
not in the record

**Comment by wtaferner** [comment]
That's the way it rolls...if you delete an already released sequence you have to correct in manually to get it back...so imho no bug...

**Comment by AmitBista** [comment]
Hi,

I'm not going for delete or save. just click on create and discard.
generated sequence also discard which is wrong behave.

In Sales order, sequence is generate on save. But record is not save or discard then not appear sequence. which is right way to maintain sequence.

**Comment by wtaferner** [comment]
Ok, got your issue, but still it is unfortunately the way it is implemented and accepted by now. If you create an object in the browser it actually asks the backend for the next sequence and successfully provides it to the client to display in the field which you need or are supposed to save to make it permanent (so, the transaction of sequence fetching is already done and besides at the same time another user could do the exact same thing, so it is impossible to guarantee that there is no gap at all in this use case).

I hope my explanation helps to understand ;-)

**Comment by antonylesuisse** [comment]
For MO the sequence is generated in the default_get this is a design choice. If you want to to be changed join the effort of specification of the next MRP for v10.

**Comment by AmitBista** [comment]
Thanks AL,  wtaferner
