### ISSUE TITLE
confilit odoo 8 with odoo 9

### ISSUE THREAD

**Issue by roccocesetti** [odoo/odoo#8980]
I active service with odoo 8 with "userdb" odoo 8 and port 80xx database odoo80, if booting from "console" odoo 9 with "userdb" odoo9 and port 80yy, odoo odoo 8 and 9 even if users have different services go to read the same dbase and are in conflict, it should not.
Greetings

**Comment by antonylesuisse** [comment]
Use --db-filter=

**Comment by roccocesetti** [comment]
well, but what you have to specify this filter?
the name of the dbase or what?
thank you

**Comment by roccocesetti** [comment]
this is the command: :./openerp-server -d odoodemo90 -r odoo90 -w xxxxxx --db-filter=odoodemo90 ok?

**Comment by antonylesuisse** [comment]
Yes each server with its db.
