### ISSUE TITLE
V9 - Can't enter a serial number on Delivery or Reception

### ISSUE THREAD

**Issue by stephaniemillet** [odoo/odoo#8981]
After selection 'track serial number' on Module Inventory configuration
AND track by serial number on product.

When trying to receive or delivery this product. 
I got the error message 
"Some products require lots, so you need to specify those first!"
But I CAN'T find WHERE I am supposed to specify those

![image](https://cloud.githubusercontent.com/assets/12233420/10391929/ba9a90d8-6e82-11e5-8460-1d2278274796.png)

**Comment by jni-odoo** [comment]
Hello stephaniemillet,

I take the product with the proper configuration of tracking serial numbers .

Now I confirm the PO with the same product with 5 qty and then try to receive the shipment .

You will find a field for serial number .
https://drive.google.com/file/d/0B5j41T1Hqv1sVV9zOFV5QXZOSjQ/view?usp=drivesdk

Receive the products with the serials :
https://drive.google.com/file/d/0B5j41T1Hqv1sRTRvZTdkSWdwZTQ/view?usp=drivesdk

I think this may help you ..

Thanks ,

Nikunj Jani (odoo India)

**Comment by stephaniemillet** [comment]
txs
