### ISSUE TITLE
[9.0] Export All Taxes export only the first record

### ISSUE THREAD

**Issue by Zoe9a** [odoo/odoo#8984]
When select all taxes and select Export.
The exported file include only the first tax.
tested on last runbot.

**Comment by Yenthe666** [comment]
Hi @Zoe9a,

Thanks a lot for your bug report.
This issue has been fixed in the meanwhile and you can now export all rows at once.
If you still face this issue on your local instance then please update your local Odoo instance.

Regards,
Yenthe
