### ISSUE TITLE
V8. Project duplication : (Don't) reset 'remaining' time on task

### ISSUE THREAD

**Issue by stephaniemillet** [odoo/odoo#8985]
When we duplicate a project, tasks are also duplicated
But the remaining time on task are not 'reset' on initially planned hours
It stays equal to remaining time on the original task (initailly planned hours of original task - time sheet activities hours

See in screen shot attached.
on the left, the original task with initially planned :  10 hours. time sheet activities =  1 hours. Remaining = 9 hours
On the right, the duplicated task with initially planned : 10 hours. No hours on time sheet. Still remaining hours  = 9, instead of 10

![image](https://cloud.githubusercontent.com/assets/12233420/10394456/a6f11a88-6e97-11e5-8421-b7bd219888db.png)

**Comment by xmo-odoo** [comment]
Fixed in 8.0, thanks for the report.
