### ISSUE TITLE
V9 Contacts - Access Error

### ISSUE THREAD

**Issue by nkhszt** [odoo/odoo#8988]
As user without access rights for accounting & finance unable to access the detail view of contacts after activating analytic accounting. 
After deactivating analytic accounting the detail view is shown again.

**Comment by nkhszt** [comment]
As user without access rights for accounting & finance unable to access the detail view of contacts after activating analytic accounting. 
After deactivating analytic accounting the detail view is shown again.

**Comment by Yenthe666** [comment]
Hi @nkhszt,

Thanks a lot for your bug report.
This issue looks solved in the meanwhile as I can no longer reproduce it.

Regards,
Yenthe
