### ISSUE TITLE
Could not execute command 'lessc'

### ISSUE THREAD

**Issue by kkoci** [odoo/odoo#8991]
Hi, When I load my first odoo install this happens

2015-10-09 15:35:17,567 32155 INFO ecommerce_digi1 openerp.addons.base.ir.ir_http: Generating routing map
2015-10-09 15:35:17,933 32155 ERROR ecommerce_digi1 openerp.addons.base.ir.ir_qweb: Could not execute command 'lessc'
2015-10-09 15:35:18,928 32155 ERROR ecommerce_digi1 openerp.addons.base.ir.ir_qweb: Could not execute command 'lessc'

Then when I try to login some menus are missing, with this 'Could not execute command 'lessc'' on upper left.

Please, some workaround for this?

Thanks

**Comment by sle-odoo** [comment]
hi,
how exactly did you install lessc? what's your OS/distribution?

**Comment by kkoci** [comment]
Hi @sle-odoo I'm sorry I just solved my issue, following this discussion:

https://www.odoo.com/es_ES/forum/help-1/question/what-does-this-error-mean-on-odoo-could-not-execute-command-lessc-60439

Thank you very much

**Comment by Anhlq87** [comment]
Hi @sle-odoo 

I also met this issue when I setup code Odoo 9 on Windows 8.1. Please help me to solve it. thanks
![image](https://cloud.githubusercontent.com/assets/9975164/15020498/202a17dc-11d7-11e6-9779-c8254a14708d.png)

**Comment by treviser** [comment]
Please read the official documentation about installing Odoo: https://www.odoo.com/documentation/9.0/setup/install.html
Check the chapter "Installing Dependencies" and there look for installing "nodejs" and "less" on  Windows.

**Comment by Anhlq87** [comment]
Thank Treviser very much. I solved that issue but I see a new issue:
![image](https://cloud.githubusercontent.com/assets/9975164/15062151/24deea52-12f2-11e6-8913-c1d72790bb32.png)
Please help me to solved it. Thank you very much :)

**Comment by treviser** [comment]
This is for issues reporting, not for getting help. Please use the help forum: www.odoo.com/forum/help-1
