### ISSUE TITLE
[8.0] Question move date set by picking date?

### ISSUE THREAD

**Issue by zaoral** [odoo/odoo#8992]
Picking form help said that `Scheduled Date` set move `Expected date`. Perfect,
Move form help said that move `Date` is the `Expected Date` until the move is Done.

This is not the case, the move `Date` and `Expected Date` in states before done are different.
This is the expected behavior?

Here is the video showing the difference. 

[![video here](http://img.youtube.com/vi/DzKKvwTuJrE/0.jpg)](https://youtu.be/DzKKvwTuJrE)

Best Regards

**Comment by Yenthe666** [comment]
Hi @zaoral,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
