### ISSUE TITLE
Performance in computed fields

### ISSUE THREAD

**Issue by JonathanStein** [odoo/odoo#8993]
When a computed field is needed, it is computed for the whole cache. (Here: https://github.com/odoo/odoo/blob/8.0/openerp/fields.py#L921). Is this really an advantage?

To be an advantage, the compute method should be able to compute the values for multiple records much faster than for one record. - And I don't think this is the normal case.
On the other hand, if the compute method has to do advanced computations, it could be a huge waste.

I know I can store the computed field, but that's not always the optimal solution.

**Comment by christophlsa** [comment]
I found this issues in our odoo instance today as well (Jonathan mentiones the line `recs = record._in_cache_without(self)` in line 936).

We are show one related field in an frontend template of one sale.order (with a t-esc). During the rendering the field is computed for all sale orders which were touched in the controller. But we don't need the computed values of all fields.

A workaround for me is now to use not the related field but use the direct field of the many2one field. But this is not the best option also if you have real related values.

Does someone has an idea if we could improve this?

**Comment by anothingguy** [comment]
i'm facing this issue as well when generating account move line for pos_order_line https://github.com/odoo/odoo/blob/9.0/addons/point_of_sale/point_of_sale.py#L1377, when running line `amount = line.price_subtotal` to get  `price_subtotal` of first line, it runs through this line `recs = record._in_cache_without(self)` and select huge thousand of pos.order.line too that we don't need at that time.
Not well understand what `_in_cache_without` did and i will continue to look at this deeper.
Hope someone can share an idea about this issue.

**Comment by Yenthe666** [comment]
Hi @JonathanStein ,

Thank you for your bug report (question) and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
To answer you though: This is currently how the Odoo framework works.

Regards,
Yenthe

**Comment by christophlsa** [comment]
This is related to https://github.com/odoo/odoo/pull/21007

**Comment by a-elhusseine** [comment]
Hello everyone,
I would like to understand the behavior of the "recursive" as parameter in declaration of the field , i did some tests but i'm not sure ,because i dont know how it work really and i dont found documentation about it .
PS: When recursive = True , _in_cache_without is not exécuted.
