### ISSUE TITLE
Invalid CSRF Token when restoring old dabase

### ISSUE THREAD

**Issue by shardaatul04** [odoo/odoo#8994]
I had a dump of old database from my recently crashed server.After building a new ubuntu machine,Old database was not restoring properly so I created a new database from odoo interface,then using phppgadmin dropped all tables from newly created database and executed the sql dump of old database.But when trying to login I faced same error as mentioned above.

Can anybody explain step by step as how to rectify this error.

**Comment by xmo-odoo** [comment]
Duplicates #8815
