### ISSUE TITLE
V9 Community/Enterprise Screen Freeze

### ISSUE THREAD

**Issue by bwadz** [odoo/odoo#8998]
I have been struggling trying to get V9 setup and finally made some progress with some recent changes. Now that I have the community version of V9 up and running I am encountering an issue that I can't seem to figure out.

As I am going through a typical implementation (database installed WITHOUT sample data) there are times when the screen greys out when trying to load a new screen but stays grey and doesn't load the screen.  server just repeat long polling as if nothing is happening.

The server shows nothing even in debug mode, but I am a newbie (learning quickly).  The only way that I can fix the issue is to restart the server.  I thought it might have to do something with server resources. The server is using almost no resources.

Any ideas, suggestions?   I am stuck!

**Comment by sle-odoo** [comment]
Can you detail a little your setup?

**Comment by bwadz** [comment]
Debain Jessie install  with odoo source.  

Started with clean install, Apache2, and update && upgrade
Setup odoo user and postgres database
Downloaded the source https://github.com/odoo/odoo.git
Ran requirements.txt

I did run into quite a few problems on the install trying to make sure that I had all the prerequisites installed, but got it working.

Starting the server works great and most of the pages seem to work without any problems.  I have mostly seen the issue on the setings menu when trying to walk through the implementation.

1- Click on the implementation - OK
2- Click on the accoutning - OK
3- Click change logo - Greyed out screen
![ss- 2015-10-12 at 7 23 06 am](https://cloud.githubusercontent.com/assets/9170865/10430103/3b34a824-70b2-11e5-8478-52611844e34a.png)
![ss- 2015-10-12 at 7 24 44 am]

(https://cloud.githubusercontent.com/assets/9170865/10430125/5612967e-70b2-11e5-902b-cf00c5973500.png)

the odoo server log shows no change - only polling waiting for the next action

I dont' have to restart the server to get it back but I do have to start another browser session which tell me that it may have something to do with the Google Chrome browser possibly.

Thanks for any possible help

**Comment by bwadz** [comment]
I have recently installed and implementing V9 Enterprise.  In doing so I have noticed a similar problem as presented above.  Clicking on an option results is a greyed out screen as if the server was processing something, but the log shows nothing except for polling.  

I can simply highlight the URL in the browser and execute the URL again and the screen is painted correctly again.  Although this is not a show stopper, it is an annoyance that will effect my potential customers.

**Comment by sle-odoo** [comment]
are you in debug mode when the screen freezes?

**Comment by bwadz** [comment]
that is a great question - I will test that and see. I have been in debug mode quite a bit trying to troubleshoot the install.  Thanks for the help

**Comment by sle-odoo** [comment]
probably fixed by 58ae39945af4608c7c978a0e42b084c9a8c97d05

**Comment by bwadz** [comment]
I think my issue was more of a browser cache issue. Working on the enterprise and community versions may have messed a few things up. I cleared the cache and things seem to be working better.

https://github.com/odoo/odoo/issues/8681  thanks @sle-odoo  @jbeficent
