### ISSUE TITLE
Solved: [9.0] Checkbox has value but not showing check

### ISSUE THREAD

**Issue by rowemoore** [odoo/odoo#9004]
9.0 enterprise running locally on windows 10.  All checkboxes are visually unchecked, but a mouse click does give or remove value. 

Must be a web.assets js or css issue?

**Comment by rowemoore** [comment]
The file "checked.svg" is missing from `/web/static/src/img/checked.svg`.

**Comment by o2030** [comment]
I'm having the same issue, how did you solve the issue? Why is the checked.svg file missing and is there somewhere I could download the file from and put it in the correct path manually? Thanks

**Comment by rowemoore** [comment]
I grabbed it from the odoo demo site:
https://demo2.odoo.com/web/static/src/img/checked.svg  
just save that to the same folder in your site, reboot and voilà.
