### ISSUE TITLE
[9.0 community] 2 menu entry with the same name

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#9009]
Steps to reproduce:

1. connect to an empty database on runbot
2. enable the developer mode
3. click on the Apps menu in the top bar

Expected: all the menu items in the left bar have distinct names

Actual: there are two entry displayed as "Apps"

**Comment by gurneyalex** [comment]
@mart-e this could have an impact on the translations, could you give it a look? 

Many thanks

**Comment by mart-e** [comment]
@gurneyalex indeed, the "local module" has been renamed badly by "Apps". We should rename one of the two.
I don't think it has an impact on translations (well it will create a new term to translate).

**Comment by gurneyalex** [comment]
@mart-e any news on this? Can you assign someone from the Usability Team?

**Comment by bst-odoo** [comment]
As is it in dev mode, I think that "local module" would be clear

**Comment by Yenthe666** [comment]
@mart-e I believe this one can be closed too.
