### ISSUE TITLE
[9.0] Themes colors and colorpicker

### ISSUE THREAD

**Issue by sdaguet** [odoo/odoo#9010]
Hello all !

The web editor color picker doesn't integrate the themes colors (primary, success, ...) and always uses his own. It sounds the css classes defined by the theme (for example the bg-primary from theme default color options) is overloaded by the web_editor css classes.

Best regards

**Comment by jaredkipe** [comment]
I ran into this too.  I was trying to figure out 'how' the list of colors is built.  That lead me to notice that if I view my page in another browser (not logged in), it looks significantly different than in the editor because its clearly using the bootstrap less variables I setup.

**Comment by sdaguet** [comment]
Exact ! You can edit and see the web_editor primary color, and check with a non logged user the result ... working but not wysiwyg ;)

**Comment by jaredkipe** [comment]
Additionally, it is incredibly hard to include your own relative .less files. Especially if you were trying to do something like have your own Bootstrap or module that depends on Bootstrap.

Effectively, the class LessStylesheetAsset in ir.ir_qweb semi-statically links against the web module to provide you with .... the web's version of Bootstrap... but nothing else.  The only way I've found to be able to support my own path is to override this and make the --include-path take a second path via get_resource_path(), but again this is statically linking to my module.

The further I get into theming in odoo, the more I dislike it.

**Comment by jaredkipe** [comment]
So I had a little time to look into this just now.  Seems that in web_editor/views/editor.xml there is a link like this `<link rel="stylesheet" href='/web_editor/static/src/css/editor.css'/>`
This CSS/SCSS file is responsible for the overriding.  Unfortunately, removing the link results in a pretty broken page editor.

**Comment by sdaguet** [comment]
I don't understand why the .bg-* elements have been re defined in the /web_editor/static/src/css/editor.css file. The text-* elements are not.
I commented the .bg-primary, .bg-success, .bg-info, .bg-warning, and .bg-danger elements in the editor.css file; and tested the bootswatch themes with success.
Currently, I have still a problem with theme_default, and looking how to handle it.

**Comment by sdaguet** [comment]
To solve the issue, in web_editor/static/src/css/editor.css; I commented .text-* and .bg-* elements ...

**Comment by Yenthe666** [comment]
Hi @sdaguet ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 9 is no longer supported as Odoo only supports three versions (10.0, 11.0, 12.0 at the moment).
If you can still reproduce this issue on Odoo 10, Odoo 11 or Odoo 12 we encourage you to create a new bug report.

Regards,
Yenthe
