### ISSUE TITLE
[8.0] Tax codes: field "Not Printable in Invoice" is without function

### ISSUE THREAD

**Issue by mncoon** [odoo/odoo#9012]
In the tax code configuration under Accounting -> Configuration -> Taxes -> Tax Codes the field `Not Printable in Invoice` is without any function.

When activated the field, nothing hapens in the invoice, neither in the view, nor in the PDF.

I tried to set up a tax for the "Saldobesteuerung" (net tax rate) in Switzerland, where I should display the normal tax 8% in the invoice but calculate with eg. 2.1% in the background.

**Comment by Jerezano** [comment]
Hello
Did you find the solution?

**Comment by Yenthe666** [comment]
Hi @mncoon,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
