### ISSUE TITLE
Automated Action - Several issues

### ISSUE THREAD

**Issue by grantern** [odoo/odoo#9024]
Tested on Odoo Saas today. 

Created an automated action for sending email.
Test1:
On Creation Update - Sending two emails everytime when changing stage. Sending one email when updating a form field.
The chatter also contains two emails as well.

Test2:
Based on Form Modification - Not sending any emails. Tried different On change fields trigger (stage_id, crm.stage.stage_id, object.stage_id)
The result is no email beeing created and added to the chatter.

**Comment by tiger2wander** [comment]
:+1:

**Comment by pedrobaeza** [comment]
This is pretty old and the module has been totally revamped (in `base_automation`). This for sure is not happening anymore.
