### ISSUE TITLE
[11.0-15.0][point_of_sale] Data architecture scalability issue with order transmission to backend

### ISSUE THREAD

**Issue by aliomattux** [odoo/odoo#90267]
Impacted versions:
11.0 - 15.0

When Odoo POS creates an order, it will send both the order that was just created, along with any pending orders that previously failed to sync in a single rpc call.
https://github.com/odoo/odoo/blob/15.0/addons/point_of_sale/static/src/js/models.js#L1263

On the server side, the function create_from_ui is called
https://github.com/odoo/odoo/blob/15.0/addons/point_of_sale/models/pos_order.py#L669

If the Odoo server is not under heavy load and responding within defined timeouts, there is no issue, and the system operates as designed.

If the Odoo server(s) or database is under heavy load, or there is internet trouble, orders will not be created and they will build up inside the POS browser local storage. If there are multiple registers operating simultaneously and there is a buildup of "pending" POS orders, and Odoo is under load, a race condition is triggered.

Odoo ORM implements Postgresl transactions, and locks tables for updates. The lock on tables is not released until the end of the transaction. In Odoo, without explicit commit or save point, this means the complete execution of the method.

When several POS terminals have a backup of orders, they will all be sent to Odoo at once when Odoo can receive the request(s). Even though the orders are created in a for loop, the locks and transaction persists until ALL of the orders are fully processed.

When the system is under heavy load, these transactions may stay open for minutes.  Under these conditions over time and concurrency, the database will  easily deadlock. None of the orders will be processed, and there is no way to gracefully recover without manual intervention. Multi order transaction rollbacks occur.

Odoo POS should implement 2 possible solutions.
1. On the server side, implement an explicit commit after processing an order.
2. Instead, modify the javascript code to send one order at a time.

Just as the POS downloads large data sets without regard to the size, it consistently applies the same when transmitting data.

**Comment by aliomattux** [comment]
I was hoping to get acknowledgement this "could" be an issue. I do not expect a fix.

**Comment by InetumLux** [comment]
It can really be an issue. Suppose the list of products available in POS was charged into POS and later on an article was archived in the backend. When this article is added to a POS Order and that order is validqated in POS, create_from_ui will fail for this oder and all subsequent orders because one "bad" order in the queue of validated orders will make create_from_ui fail for all orders and the validated orders stay inside the POS and fill up the queue. We have had this multiple times for a client of us.
So sending orders one by one would improve this situation as only the "bad" order would remain in the POS.

**Comment by pedrambiria** [comment]
Hello,
We have this PR https://github.com/odoo/odoo/pull/126662 which will solve the issue.

**Comment by vava-odoo** [comment]
Hi @aliomattux 
Thanks for reporting.
As mentioned by @pedrambiria, it is fixed in 15 with https://github.com/odoo/odoo/pull/126662, and will be in more recent versions soon.
Cheers
