### ISSUE TITLE
[9.0] Default stage and add member feature is missing

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#9030]
Hi Odoo,

When I tried the project module in version 9,
Now, there's no default stage and cannot add project member again when I want to create a new project.

Why you remove this function? 
Or did I missed something?

**Comment by antonylesuisse** [comment]
Project now uses followers instead of members. And it's normal that they come without stages as those are easy to create. you can also create template of project and duplicate them.

**Comment by falinwa** [comment]
can I know for what reason you remove the function?
Because I don't see it as a good change from your side.
You just decreased the functionality and feature of the project module.

Yes, I know create the stage is easy, but if we have a default stage it will easier to have a standard process. if you want to hide this function is okay, but don't remove it.

Thank You.

**Comment by antonylesuisse** [comment]
We removed it because we simplified the way you can create stage in kanban view. If you want to change it just add a default value on stage_ids of project with ir.values (no code needed).

**Comment by f-ewald** [comment]
@antonylesuisse Where can I change this? Found this discussion here via a search and I am wondering how to set these default stage_ids. Do you have any link for this?

**Comment by ilsken** [comment]
^ +1, some clear documentation for this would be nice as it's a very nessarry feature

**Comment by bistaray** [comment]
See my comment at the bottom of https://github.com/odoo/odoo/issues/8660
