### ISSUE TITLE
Bolean field not focused on list view editable

### ISSUE THREAD

**Issue by petrus-v** [odoo/odoo#9035]
If you use a boolean field in first place on a list view editable, the focus is lost in the depth of the page.

Impacted versions:
- 7.0
- 8.0

Chromium 45.0.2454.85
FF 41.0.1

Steps to reproduce:
1. create or update a list editable view and add boolean field in the first position
2. click on any existing row to enter in edit mode
3. press "enter" (or several "tab" ) to change row

Current behavior:
- Focus is lost in the page

Expected behavior:
- Checkbox should be the active element

**Comment by Yenthe666** [comment]
Hi @petrus-v,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
