### ISSUE TITLE
[Apps] Live preview link

### ISSUE THREAD

**Issue by 8cells** [odoo/odoo#9036]
What properties in the file ``__openerp__.py`` I have to add to provide 'Live preview' link (in market)?

I would like to add a preview to the theme:
https://www.odoo.com/apps/themes/8.0/material_backend_theme/

As you can see here:
https://www.odoo.com/apps/themes/8.0/theme_odoo_experts/

**Comment by dmo-odoo** [comment]
The key is named 'live_test_url', and is supposed to be a fully qualified url to an external server running a demo of the theme.

Exemple, for theme_odoo_experts:
'live_test_url': 'https://theme-odoo-experts.odoo.com',

I'll see that this info is soon added to the https://odoo.com/apps/upload page.
