### ISSUE TITLE
[15.0] Blog Post Translation is not working properly

### ISSUE THREAD

**Issue by ikus060** [odoo/odoo#90397]
**Impacted versions:**
15

**Steps to reproduce:**
1. Create a blog post
2. Start translation
3. Edit the content

Current behavior:
1. When editing the blog post content, the block doesn't turn green.
2. When saving, the translation is not kept

Expected behavior:
1. When editing any block of text, the text should turn green
2. When saving the translation should be saved

Video/Screenshot link (optional):
![Peek 2022-05-03 07-49](https://user-images.githubusercontent.com/921251/166447615-1230dc70-1fce-43e3-bc78-e2c7514678f0.gif)
The title change be translated, but the content cannot be translated

Support ticket number submitted via odoo.com/help (optional):

**Comment by ikus060** [comment]
I've test the feature in a trial database on odoo.com and it's working.

Our instances is self-hosted and I'm not wondering if we have a different version running. As a reference, I'm using a docker image from `bitnami/odoo:15.0.20220410`

**Comment by ikus060** [comment]
After more testing, I'm not able to reproduce the problem with `odoo:15.0`. 

Closing

**Comment by ikus060** [comment]
Mave to get this fixed using official odoo image then adding `proxy_mode = True` to my `odoo.conf` otherwise, I'm facing the following problem: https://www.odoo.com/forum/help-1/odoo-14-website-cann-t-load-translation-mixed-content-blocked-184730

**Comment by Lockdownvogel** [comment]
Thank you! I will try that.
In the meantime, I also found a workaround solution, which is: Login with Administrator rights, go to -> Settings -> Activate the Developer Mode. Then go to -> Settings -> Translations
Filter for “Translated Field” = “blog.post,content”
There you can do the translations manually. And it works nice, the blogs on the website look nice.

**Comment by bnisevic** [comment]
Interestingly enough, I am experiencing the same issue on the version 18.
