### ISSUE TITLE
9.0 account & financial

### ISSUE THREAD

**Issue by roccocesetti** [odoo/odoo#9039]
In previous modules of accounting and finance, in the chart of accounts it was possible to link the accounts in order to create a pyramid structure.
Now that this link is not how you can create a similar structure as in previous versions?
thank you

**Comment by Yenthe666** [comment]
Hi @roccocesetti,

Please only use the Github issue tracker for bugs in the official code, not for asking questions.
You can ask these kind of questions on the official help forum at help.odoo.com
Short answer is: custom development or another workaround


Regards,
Yenthe
