### ISSUE TITLE
Search Product Quantities

### ISSUE THREAD

**Issue by bealdav** [odoo/odoo#9051]
On the product list view the two last columns are "Quantity on hand" and "Quantity available".

So I try with advanced search on latest 8.0 runbot instance with demodata (its the same on odoo 9.0).

```
I want to see all the product  "quantity on hand" is equal to 0 -> result : some product are qty > 0
```

**Comment by Yenthe666** [comment]
Hi @bealdav,

Thanks for the report (and sorry for late reply).
What exactly is the bug/issue? It is a bit of a short report. 😉

**Comment by pedrobaeza** [comment]
I'm seeing the problem right now, even in 11.0:

![seleccion_004](https://user-images.githubusercontent.com/7165771/38280501-f184ad42-37a5-11e8-988d-d735f1ce295b.png)

**Comment by pedrobaeza** [comment]
@sle-odoo maybe you can check this?

**Comment by Yenthe666** [comment]
Hmm indeed, that looks off. Good catch.

**Comment by gdgellatly** [comment]
@pedrobaeza @Yenthe666 I think this is a duplicate.  From memory, available qty with variants shows total of all variants, but the inverse search doesn't consider variant quantities  (or something like that).

**Comment by pedrobaeza** [comment]
Yeah, but in this case I consider that it should be consistent or rename the filter for avoiding confusions.

**Comment by gdgellatly** [comment]
@pedrobaeza I wasn't disagreeing that it is a bug.  I think it only makes sense to search based on the sum of available variants.  The functional logic is straightforward.  I want to know if I have (any) Iphones (of any variant) in stock (or over any summed qty), yes I do.  Now what configurations are available means look at individual variants.

**Comment by sle-odoo** [comment]
The issue reported by the screenshot of pedro is fixed in v13 with a commit present in v11, therefore i'm closing this issue.
Sorry for the delay.
