### ISSUE TITLE
Google OAuth 2 + SSL - Error: redirect_uri_mismatch

### ISSUE THREAD

**Issue by seckt0r** [odoo/odoo#9057]
The issue, as far as I see, is that the redirect uri is not getting HTTPS:
`The redirect URI in the request: http://www.tiangola.com/auth_oauth/signin did not match a registered redirect URI.`

I keep getting this error when authenticanting with google account.
The workaround I found is to manually change 'http'  with 'https' at the address bar. Of course for other users who receive the invite to connect that's just not pratical.
Once inside the entire site works fine with HTTPS.
I also don't get any error if using a local/oddo account.

**Comment by jaredkipe** [comment]
I can confirm this as well.  So far I've only looked around in settings for a fix (e.g. Settings-Technical-SystemParameters)  I will look into the code in a little bit.

**Comment by jaredkipe** [comment]
Interestingly, the issue seems to be that the controller uses an `openerp.http.request.httprequest` object that has the wrong protocol (http vs https).  Since I have this behind nginx with X-Forwarded-Proto set appropriately, I can only assume the error is somewhere further down.

**Comment by jaredkipe** [comment]
Interestingly, --proxy-mode (or proxy_mode = True in config file) is not sufficient to trigger the proxy middleware.  (inside openerp.service.wsgi_server.application)

X-Forwared-Host must also be set (HTTP_X_FORWARDED_HOST), something that is NOT in all/most nginx config examples.

To fix, I added the following to my nginx config.
```proxy_set_header X-Forwarded-Host $host; ```

**Comment by seckt0r** [comment]
Do you know what would be the equivalent for apache?

**Comment by bhaymore** [comment]
Setting X-Forwared-Host worked for me as well.

**Comment by seckt0r** [comment]
What about apache?

Brandon <notifications@github.com> escreveu no dia quarta, 2/12/2015 às
21:58:

**Comment by jaredkipe** [comment]
According to the documentation, X-Forwarded-Host is set automatically by using the ProxyPass directive.  (might depend on the version of Apache)  Perhaps you need the ProxyPreserveHost directive to be turned on? (though the docs say to leave it off normally)

http://httpd.apache.org/docs/2.2/mod/mod_proxy.html

**Comment by seckt0r** [comment]
Ok. I've added ProxyPreserveHost On to my conf and included the http url into google's oauth settings (both in redirect and origen URIs).
It seems to be working fine now!

**Comment by feraudet** [comment]
Think to add : ```proxy_set_header X-Forwarded-Proto $scheme;```

**Comment by jamescobalt** [comment]
Thank you! This whole thread was incredibly helpful to me in resolving OAuth issues with Slack and Facebook. Nginx doesn't have an exact equivalent of ProxyPreserveHost, but for me, I was able to get the desired behavior with `proxy_set_header X-Forwarded-Proto https;`.

**Comment by vkrytpo** [comment]
I am running Django on 8000 on local and using the proxy pass to in Nginx to connect at the port from the internet.
my callback URLs are still coming.. 127.0.0.1:8000 which should be like www.dmseva.com/

please let me know what changes should I do?

**Comment by josopu** [comment]
Have someone solved this issue with NPM (nginx proxy manager)?
