### ISSUE TITLE
pos_pricelist module: all quantities reset to zero after pressing the delete key on the POS

### ISSUE THREAD

**Issue by woepwoep** [odoo/odoo#9059]
scenario:
entering the POS,
adding three articles A, B, and C
all with qty=1
then delete article C by pressing the DELETE key on the POSboard

results:
all articles A, B, and C have qty=0
and the cursor remains on article C 

further tests:
press 12 (with the -default- QTY function still in place) will show all three articles A,B and C with a qty of 12, even though the cursor is only on article C.

after de-installing pos_pricelist and pressing F5 in the POS, 
everything works fine again.

**Comment by mart-e** [comment]
Hello,

pos_pricelist is not an official module supported by Odoo so you should check with [the author](https://github.com/OCA/pos) about your issue.
If you can reproduce in standard, we can reopen.

Regards

**Comment by woepwoep** [comment]
reopened at https://github.com/OCA/pos/issues/59
thx, Martin
best regards, Ron

----
http://about.me/woepwoep


2015-10-14 11:07 GMT+02:00 Martin Trigaux <notifications@github.com>:
