### ISSUE TITLE
[9.0] Doesnt automatically create new variable when restarting the server

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#9060]
Hi Odoo,

In version 9, I update the module by adding a new field,
but when I restarted the server, the system not adding a new field in database and I can't enter the system again.

the error message is something like this:
Programming error: column res_partner "newfield"

Thank You.

**Comment by nim-odoo** [comment]
Hello,
You should update the module using the -u option. Anyway, for help, please use the Odoo forum: https://www.odoo.com/forum/help-1

**Comment by falinwa** [comment]
why I need to update it?
before version 9, I dont need too..
