### ISSUE TITLE
[9.0] Cannot add attachment to task

### ISSUE THREAD

**Issue by eandersons** [odoo/odoo#9062]
Hello!

I added model's `project.task` field `attachment_ids` to the task form, but it seems that attachments are not saved for tasks. Attachment itself is saved, but it is not linked to task. Tried to use context attribute (`context="{'default_res_model': active_model, 'default_res_id': active_id}"`) for the field `attachment_ids`, but without success. When I look in the database table `ir_attachment`, I can see, that attachment is created, but the column `res_model` is left empty, although models `project.task` field `attachment_ids` has specified domain (`domain=lambda self: [("res_model", "=", self._name)]`).

Attachment is successfully saved and linked to task, when I use custom button with custom task that has the same context (`{"default_res_model": active_model, "default_res_id": active_id}`).

Maybe I am missing something or doing it wrong way.

**Comment by mart-e** [comment]
Hello,

You do not need to add any field to specify attachements. Everything is handled with the `document` module (well actually already in the `base` module but document shows the link on top of the record).

Please note that github is not the place to ask development advises, it is just to report bugs.
