### ISSUE TITLE
[9.0] Can not create new Work Center ( manufacturing order module )

### ISSUE THREAD

**Issue by thanhchatvn** [odoo/odoo#9063]
1. setup my accounting char for my company
2. setup manufacturing order
3. go to menu --> manufacturing --> Setting --> new Work centers. 
Error code:
ValueError: Invalid field u'type' in leaf "<osv.ExtendedLeaf: (u'type', u'!=', u'view') on account_analytic_account (ctx: )>"
* When i check _columns of mrp.workcenter (Workcenter) field: 
costs_hour_account_id and costs_cycle_account_id the same domain is domain=[('type','!=','view')] and Many2one to account.analytic.account
* Ok, i go to check module: Analytic Account ( account.analytic.account ), can not find field "type"
* This is error from domain atttribute in workcenter
Please tell me why add this domain ?

**Comment by thanhchatvn** [comment]
![selection_004](https://cloud.githubusercontent.com/assets/3313064/10480096/86c07976-7292-11e5-8e8f-8eb40d281026.png)
![selection_005](https://cloud.githubusercontent.com/assets/3313064/10480095/86bff7f8-7292-11e5-8453-29861f9d39bc.png)

**Comment by jco-odoo** [comment]
thanks!
