### ISSUE TITLE
[9.0] Cant Translate Event Web page

### ISSUE THREAD

**Issue by dhp-denero** [odoo/odoo#9067]
Hi,

I am getting very strange issue with odoo website builder translation tool. Steps to Raise an issue.
1. Setup Fresh db and install website_event module
2. Using Website builder create new Event. Content >> Create Event
3. Open Newly Created event web page. Drag any of snippets and save page.
4. Add new language (i.e. French)
5. Open website home page with French translation and goto newly created event page. 
6. Left Top Corner, Click to Button to Translate.
7. Change any text of snippets and try to save. 
Cant Save ? 
Get Error message on changed text box : "Record does not exist or has been deleted. None"

Thanks,

Dhaval Patel

**Comment by mart-e** [comment]
Probably same as #10529, temporary bug but works fine now.
Let me know if you still have issues
