### ISSUE TITLE
8.x odoo database manager bug

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#9068]
Hello,

Fresh install latest revision from odoo 8.

Then try to restore database, but did not get any option to restore database.

Does it must need to create one database to restore database ?

It seems wrong logic, I hope soon it will be fix.

Thanks,

**Comment by mart-e** [comment]
Seeing #9070 I guess you have found the option to restore a database.

If not, it's present at http://myserver/web/database/manager

**Comment by tejastank** [comment]
Thanks for quick response and directly closed issue.

http://myserver/web/database/manager
was not accessible with fresh installation , once I created single database then after it enable to access.

Its avoidable.
