### ISSUE TITLE
Stable Odoo 8.0 bug removed Technical Features

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#9069]
Most helpful technical feature option does have removed ?

It most help use to first configure company and other report stuffs.

But now its horrible to manage work before module installation and configuration.

Why this removed from version 8.0 ? its towards bad police

**Comment by andreparames** [comment]
You just need to activate the developer mode in the About menu (click on the (?) symbol in the top bar).

**Comment by tejastank** [comment]
Thanks quick answers from community.

**Comment by mart-e** [comment]
I guess you mean 9.0 and not 8. As said @andreparames you need to be in developer mode
