### ISSUE TITLE
Stable odoo 8.0 bug | ProgrammingError: column "transient" does not exist

### ISSUE THREAD

**Issue by tejastank** [odoo/odoo#9070]
Restore database issue, Stable version 8.0 to 8.0 

Below bug generated, 
```
LINE 1: select model, transient from ir_model where state='manual'
                      ^
Traceback (most recent call last):
  File "/home/ubuntu/odoo/openerp/http.py", line 114, in dispatch_rpc
    result = dispatch(method, params)
  File "/home/ubuntu/odoo/openerp/service/db.py", line 354, in dispatch
    return g[exp_method_name](*params)
  File "/home/ubuntu/odoo/openerp/service/db.py", line 201, in exp_restore
    restore_db(db_name, data_file.name, copy=copy)
  File "/home/ubuntu/odoo/openerp/service/db.py", line 241, in restore_db
    registry = openerp.modules.registry.RegistryManager.new(db)
  File "/home/ubuntu/odoo/openerp/modules/registry.py", line 385, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/ubuntu/odoo/openerp/modules/loading.py", line 339, in load_modules
    registry.setup_models(cr)
  File "/home/ubuntu/odoo/openerp/modules/registry.py", line 185, in setup_models
    cr.execute('select model, transient from ir_model where state=%s', ('manual',))
  File "/home/ubuntu/odoo/openerp/sql_db.py", line 139, in wrapper
    return f(self, *args, **kwargs)
  File "/home/ubuntu/odoo/openerp/sql_db.py", line 215, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column "transient" does not exist
LINE 1: select model, transient from ir_model where state='manual'
```

**Comment by mart-e** [comment]
Hello,

Looks like you are running an 8.0 database on a 9.0 code base (field added in 9 at 5c0bfaafd10303a9df6e7b857f92a5dc3cf71f7c, not present in 8).
So yes, can not work, you need to migrate your database.

**Comment by tejastank** [comment]
I just pull 8.0 branch & restore database

**Comment by mart-e** [comment]
I don't know how you run your instance but the code `cr.execute('select model, transient from ir_model where state=%s', ('manual',))` present in your traceback is present [in 9.0](https://github.com/odoo/odoo/blob/9.0/openerp/modules/registry.py#L185) but not [in 8.0](https://github.com/odoo/odoo/blob/8.0/openerp/modules/registry.py#L180)

**Comment by tejastank** [comment]
We had pull branch: https://github.com/odoo/odoo/tree/8.0
& all issue raised.

**Comment by rim-odoo** [comment]
Let's try again: this code does not exist in 8.0.Thus it is IMPOSSIBLE to have this error with branch 8.0.

**Comment by mart-e** [comment]
I advise you to check a git tutorial like [this one](https://www.atlassian.com/git/) to see how to checkout your code in a particular branch

**Comment by tejastank** [comment]
We got issue https://github.com/odoo/odoo/issues/7634 on our one server,
because of this I had plan to pull new code of 8.0, I know 9.0 is very buggy and not plan to use next 6 month for production.

So..
I had use git https://github.com/odoo/odoo/tree/8.0

git clone branchname

Then try to restore database & bug raise. 

Yes, for odoo its POSSIBLE & its happen on restoration of database.

Its bug of stable version odoo 8.0.

**Comment by mart-e** [comment]
Well `git clone git@github.com:odoo/odoo.git` clones the **9.0** as it is now the latest stable version. Richard gave you a command to check the code you have locally. I have the impression you are mixing the concepts of branches and repositories in git so that's why I gave you a tutorial you can check.

**Comment by tejastank** [comment]
Thank @mart-e for investigated response, I sure check this, it might issue raise because it now referenced to 9.0.

**Comment by tejastank** [comment]
I checked https://github.com/odoo/odoo/tree/8.0
Where clone URL: https://github.com/odoo/odoo.git
Is that correct ?

**Comment by mart-e** [comment]
@tejastank as said, this will get you the 9.0 by default. Please check https://www.atlassian.com/git/tutorials/using-branches

**Comment by rim-odoo** [comment]
You should try 
```
git checkout 8.0
```
after cloning the repositor. This will give you the 8.0 branch.

**Comment by Qaiserkhan001** [comment]
Hi Dears,

I have copied database from ODOO version 8 and trying to Restore on ODOO version 9 but giving me this error ( Database restore error: column "transient" does not exist LINE 1: select model, transient from ir_model where state='manual' ^) 

I can't upgrade Version 8 to any new so how can restore database backup to any other server ??

**Comment by rim-odoo** [comment]
@Qaiserkhan001 As explained hereunder, you cannot simply dump an Odoo 8 database and restore it in Odoo 9, it won't work. 

Please consider our upgrade service (included in Odoo Enterprise subscription): https://upgrade.odoo.com/database/upload
