### ISSUE TITLE
[8.0] [account] translations of journals for nl are not correct

### ISSUE THREAD

**Issue by stijnh92** [odoo/odoo#9071]
When installing the account module, the account journals are not correctly translated to nl_BE or nl_NL.
The reason is that the lines of the python code are not the same as in the .po file.
For example:

account.py lines 3205 - 3211
```python
 journal_names = {
            'sale': _('Sales Journal'),
            'purchase': _('Purchase Journal'),
            'sale_refund': _('Sales Refund Journal'),
            'purchase_refund': _('Purchase Refund Journal'),
            'general': _('Miscellaneous Journal'),
            'situation': _('Opening Entries Journal'),
}
```

Then in the translation file, nl.po on lines 8408 - 8412:
```po
#. module: account
#: code:addons/account/account.py:3186
#, python-format
msgid "Sales Journal"
msgstr "Verkoopboek"
```

Here it says that on line 3186 in account.py 'Sales Journal' should be translated but this does not happen because 'Sales Journal' is found on line 3206 in account.py.

**Comment by mart-e** [comment]
Hello,

The default journals and accounts should be translated but it happens probably not the way you think.
First of all the line number in .pot doesn't really matter, it's informative for the translator but as long as the module (account) and the type (code) are right, Odoo will sort it out.

The accounts and journals are **not** translatable by default. This means, you can not have an English and a Dutch name at the same time (well you can if you install `l10n_multilang` but that's another story).
The code that you give is executed when you install a generic chart of account, it will create a few journals. The name of these journals will be translated in the language of the user **at the execution time**. So if your user is in Dutch when installing account, the journals will be with Dutch names. If he is in English, keep the default. See a local database I just created with a Dutch admin:

![screenshot from 2015-10-15 08-58-27](https://cloud.githubusercontent.com/assets/564822/10506707/efb9a6d6-731a-11e5-8f2e-422813013ca7.png)

**Comment by stijnh92** [comment]
Hello

Thank you very much for the explanation!

--

Vriendelijke groeten, Cordialement, Kind regards,

Stijn Houben
Odoo Consultant
DynApps

On 10/15/2015 09:06 AM, Martin Trigaux wrote:

Hello,

The default journals and accounts should be translated but it happens probably not the way you think.
First of all the line number in .pot doesn't really matter, it's informative for the translator but as long as the module (account) and the type (code) are right, Odoo will sort it out.

The accounts and journals are not translatable by default. This means, you can not have an English and a Dutch name at the same time (well you can if you install l10n_multilang but that's another story).
The code that you give is executed when you install a generic chart of account, it will create a few journals. The name of these journals will be translated in the language of the user at the execution time. So if your user is in Dutch when installing account, the journals will be with Dutch names. If he is in English, keep the default. See a local database I just created with a Dutch admin:

[screenshot from 2015-10-15 08-58-27]<https://cloud.githubusercontent.com/assets/564822/10506707/efb9a6d6-731a-11e5-8f2e-422813013ca7.png>

-
