### ISSUE TITLE
[9.0] Bug in base_import in ListView.buttons template

### ISSUE THREAD

**Issue by RuslansAlistek** [odoo/odoo#9072]
Statement "t-if='widget.options.import_enabled" must be on tag button. Otherwise "if" don't works.
Like this:

```
<t t-extend="ListView.buttons">
    <t t-jquery="button.o_list_button_add" t-operation="after">
        <button type="button" class="btn btn-sm btn-default o_list_button_import" t-if='widget.options.import_enabled'>
            Import
        </button>
    </t>
</t>
```

**Comment by Sarfarazsajjad** [comment]
I am getting two import buttons after importing some products data 
![screen shot 2016-03-24 at 1 58 15 pm](https://cloud.githubusercontent.com/assets/4182883/14012623/b8a9e1e2-f1c8-11e5-94e5-83c6ff5eb544.png)

**Comment by pedrobaeza** [comment]
This has been already addressed, so I close.
