### ISSUE TITLE
[9.0] Leads management: Mark Won and Mark Lost are visible on Lead form view (not the same behaviour as v8)

### ISSUE THREAD

**Issue by antonybrugger** [odoo/odoo#9076]

**Comment by mart-e** [comment]
Hello,

Indeed, the change was made during a refactoring at f255aa7b36d98aeb63273e6da49d1720d8a15f41 but it is the intended behaviour, not a bug.
Or do you have an issue with the button being on the lead view ?

**Comment by antonybrugger** [comment]
What is the purpose of this Mark as Lost/Won? When 'Mark as Won', button 'Convert to opportunity" is still active and when you hit it, it says you cannot convert to opportunity

+ Sales/leads = you see only leads (but filter Opportunities is still visible , but Sales/Your pipeline you see leads + opportunities (confusing)

+ On demo data stages seems 'strange': 2 New, 3 Negociations, 3 Won
![screenshot at oct 19 10-20-31](https://cloud.githubusercontent.com/assets/2707881/10572722/0fa08f5e-764b-11e5-8d2d-bfa0fd6f2327.png)
is it the intended behaviour?

+ to configure stages Leads/Opportunities, you have to activate the "developper" mode => is it the intended behaviour? There should be a configurator mode

**Comment by antonybrugger** [comment]
When a detailed Odoo v9 CRM doc will be available?

**Comment by mart-e** [comment]
I have discussed this and indeed, with the raised issue of convert to opportunity on a won lead, we decided to remove the won button from the lead view (a lead can still be lost though, meaning "archived"). Done at f75dcfe4b0eab32cc23784974b623def87aa468b

For your last point, the documentation redaction is an open effort so all help is welcome:

* [Page redaction status]( https://docs.google.com/spreadsheets/d/12Xg70FiWQH0LJXsRWVNDO1TwQbhPvV4UFm2UdAAHPrQ/edit?pli=1#gid=1028069037)
* [Github repository](https://github.com/odoo/documentation-user)
* [Published documentation](https://www.odoo.com/documentation/user/)
