### ISSUE TITLE
[9.0] Can not reload tree view state when click button line

### ISSUE THREAD

**Issue by thanhchatvn** [odoo/odoo#9080]
1. I have 1 form parent
2. in form parent i have multi line tree view [ project task ]
3. i add button to tree view  and field state
4. when i click this button , i call python method and write({'state': 'value i want'}) and return this
5. But tree view line can not reload and i see state old before i change
   ![selection_006](https://cloud.githubusercontent.com/assets/3313064/10507700/8cec3758-734c-11e5-96d8-5333c57017b1.png)

**Comment by ahefni** [comment]
the same problem

**Comment by pedrobaeza** [comment]
Although this is not an Odoo problem, I can say you a trick for this, but please for next questions like this one, use the forums or mailing lists. Add `options="{'reload_on_button': true}"` on the one2many field.
