### ISSUE TITLE
record.browse() doesn't validate or convert record IDs

### ISSUE THREAD

**Issue by themreza** [odoo/odoo#90821]
**Impacted versions:** <= 15.0

**Steps to reproduce:**

```python
a = env['res.partner'].browse('1')
a_id = a.mapped(lambda r: r.id)

if a:
  log(a.name)

b = env['res.partner'].browse(1)
b_id = b.mapped(lambda r: r.id)

if b:
  log(b.name)

log("a: %s, a_id: %s, b: %s, b_id: %s, a == b: %s" % (a, a_id, b, b_id, a == b))
```

**Current behavior:**

```python
a: res.partner('1',), a_id: ['1'], b: res.partner(1,), b_id: [1], a == b: False
```

`a` therefore bypasses emptiness checks (`if a: ...`) while not throwing a validation error. Thus, trying to access the contact name results in:

_Database fetch misses ids (('1',)) and has extra ids ((1,)), may be caused by a type incoherence in a previous request_

**Expected behavior:**

Ideally, `browse` should:

* cast record IDs to `int`
* throw a validation error for non-`int` inputs
* return `None` or `res.partner()` if no results were found

That is:

```python
a: res.partner(), a_id: [], b: res.partner(1,), b_id: [1], a == b: False
```

Or:

```python
a: res.partner(1,), a_id: [1], b: res.partner(1,), b_id: [1], a == b: True
```

**Comment by hoangtrann** [comment]
You could always add an extra `.exists()` after `browse` to make sure the records actually exists or valid

**Comment by Feyensv** [comment]
The api is clearly documented (`:type ids: int or list(int) or None`), it's your job to make sure the input is the one expected by the API (and as said, `exists` is there to check the validity of a record).  Adding extra checks in core methods would only slightly slow down operations, especially when it's only needed for custom code (which might as well integrate those checks/the conversion).

Anyway, if such a change of behavior is ever done, it won't be in a stable version.
