### ISSUE TITLE
Could not install third part theme on odoo.sh.

### ISSUE THREAD

**Issue by telesoho** [odoo/odoo#90827]
Impacted versions:
odoo.sh version 15.0
os ubuntu 20.04

Steps to reproduce:
The theme theme_second_chance can be install on local odoo, so I try to install it on odoo.sh.
 
1. Put theme into production branch (main), so we can see it has been deploy to ~/src/user.
![image](https://user-images.githubusercontent.com/10979091/167230827-e815af92-841f-492c-8b70-dd97681968e1.png)

2.  Connect to  main branch 
![image](https://user-images.githubusercontent.com/10979091/167230995-4ea84bb4-066e-4761-8f79-bc7dea8b6997.png)

3. Update App List
 ![image](https://user-images.githubusercontent.com/10979091/167231050-c3f4332d-a543-4965-a2f2-fa79efa237da.png)

4. Try to active the theme
![image](https://user-images.githubusercontent.com/10979091/167231138-7181e3b9-adcd-4816-b481-1f964eccef86.png)

Current behavior:

Could not found the theme on odoo.sh.

I notice that all listed odoo.sh themes be put in ~/src/themes folder. I had try to put the third part theme into ~/src/themes by shell command, but I got readly only error.  

![image](https://user-images.githubusercontent.com/10979091/167231321-a9617437-6ce7-4904-8bf3-eb7bb14520c4.png)
 
Is there a way to install third part theme on odoo.sh or I do something wong?

**Comment by ossimantylahti** [comment]
3rd party themes are normal odoo extensions. You should just commit them to the odoo.sh repository main level as folders.

Example:
Let's use Droggol Theme prime as an example. This theme comes with folders theme_prime and droggol_theme_common.

You should just add them to Github project's main folder. Like this:
![image](https://user-images.githubusercontent.com/37711285/167723628-1d2f864e-d5f6-4b11-80da-63a87c5708b7.png)

Note that if a theme has requirements.txt file, you need to copy that file (only) to the main folder.

**Comment by telesoho** [comment]
@ossimantylahti 
Thank you for your help.

I change  `"category": "Sdl/Theme"` to ` "category": "Theme/Sdl"` in  `__manifest__.py`, now the theme can be shown in theme list. 

It seem that theme must be defined in Theme category.
