### ISSUE TITLE
[8.0][report] PDF reports get no styles

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#9085]
All the [Useful Remarks](https://www.odoo.com/documentation/8.0/reference/reports.html#useful-remarks) section from the docs is lying:

> Twitter Bootstrap and FontAwesome classes can be used in your report template

It only happens in HTML reports.

This is a demo sale order, printed normally from Odoo (PDF, then screen capture):
![captura de pantalla de 2015-10-15 13-53-07](https://cloud.githubusercontent.com/assets/973709/10512939/5dbf66d8-7344-11e5-8835-543114063cfe.png)

This is the same sale order, but printed by visiting `http://localhost/report/html/sale.report_saleorder/6` and then printing to PDF from Firefox:
![captura de pantalla de 2015-10-15 13-53-32](https://cloud.githubusercontent.com/assets/973709/10512959/7c54dbb4-7344-11e5-9c62-0f864b2f0def.png)

The difference is quite obvious. PDF reports get no styles at all.

> Local CSS can be put directly in the template

If this refers to the `style` attribute, it's OK. But one cannot put directly `<style>` elements in the template. The phrasing is misleading.

> Global CSS can be inserted in the main report layout by inheriting its template and inserting your CSS:
> [code]

This is also not working, but I imagine it's because of the first point.

It seems fixed in 9.0 though.

**Comment by sle-odoo** [comment]
Hey, no one is lying. What you have is a common bug in odoo installation: wkhtmltopdf cannot contact the odoo instance serving the stylesheets. Check that you're using a db-filter (`--db-filter="^dbname$"`). If yes, check what url wkhtmltopdf is using to contact the server: `web.base.url` and you can override it by setting `report.url` with an ~internal url (most often http://127.0.0.1:8069).

**Comment by sle-odoo** [comment]
And yes adding style in 8.0 is a pain, in 9.0 it's a lot easier (xpath on assets). If you're interested in making the doc clearer i'll review your pr with priority.

**Comment by Yajo** [comment]
You are right, thanks! I'll PR ASAP.

**Comment by Yajo** [comment]
Setting `report.url` works, but I cannot find the way to add styles (8.0). How is it supposed to work?

**Comment by rafaelbn** [comment]
:+1:

**Comment by Yajo** [comment]
Fixed in https://github.com/odoo/odoo/pull/9105.
