### ISSUE TITLE
ir.cron timezone bug

### ISSUE THREAD

**Issue by leopard7777777** [odoo/odoo#9091]
my timezone is Asia/Shanghai

ir_cron _process_job method
compute now by datetime.now() 
the time stores in db that's timezone is Asia/Shanghai
but when i select record from db, the query is (now() at time zone 'UTC')

for example,
now is 22:00 ,utcnow is 14:00,interval 1 min
_process_job  compute now is 22:00,nextcall is 22:01 and the time stores in db is 22:01
but the query is nextcall <= (now() at time zone 'UTC')
means nextcall <= 14:01
there isn't result,so until utcnow is 22:01, execute next cron job

i think the develper's timezone is UTC,so it  is right to use now() for he.
but for me, i suggest to use utcnow()

when i create a ir.cron record
default nextcall is my time with timezone

**Comment by pedrobaeza** [comment]
Everything is processed in the ORM in UTC. Only things presented in the UI are converted to the corresponding timezone.
