### ISSUE TITLE
[9.0] Can't add images in mass mailing

### ISSUE THREAD

**Issue by ol8vil** [odoo/odoo#9093]
Can't add images in mass mailing in default theme in Community edition after fresh install using official docker image. SAAS version also not working (started tutorial and tried to add image in another themes as well).

**Comment by nle-odoo** [comment]
Hello,

It should be solved in 9.0 with this commit https://github.com/odoo/odoo/commit/21a8c76

Thanks for reporting.

**Comment by nle-odoo** [comment]
Hello,

It should be solved in 9.0 with this commit https://github.com/odoo/odoo/commit/21a8c76

Thanks for reporting.

**Comment by joolsr** [comment]
Great I will update later.

There were a few other image related bugs I noticed .. This may help those
too.

Any new ones I will report

Julian
