### ISSUE TITLE
[9.0] Account External_id is deleted after importing partner linked to this account. So next partner update will fail

### ISSUE THREAD

**Issue by Zoe9a** [odoo/odoo#9097]
Impacted versions:
- 9.0

Steps to reproduce:

Tested with last runbot : http://107756-9-0-145626.runbot7.odoo.com/web

Step 1 : Import Test Accounts
![image](https://cloud.githubusercontent.com/assets/15045085/10534242/d4cd2416-73e6-11e5-8891-6b9bd13927f8.png)

Step 2 : Check id by export just after this import : Looks good.

![image](https://cloud.githubusercontent.com/assets/15045085/10534197/d4282af2-73e5-11e5-9e96-41054a57a6bc.png)

Step 3 : Now it's time to import a partner associated with this account

![image](https://cloud.githubusercontent.com/assets/15045085/10534178/9d163ae0-73e5-11e5-8dd3-6e49d854f744.png)

Step 3 : Check again External Id of accounts:
![image](https://cloud.githubusercontent.com/assets/15045085/10534218/4ebf699c-73e6-11e5-9586-4b10f9be6c69.png)

The "account payable external id" was replaced.
After this, every update on my contact will fail because the "40100001" external id don't exist anymore.

Current behavior:
- id = "**export**.account_account_635"

Expected behavior:
- id = "40100001"

**Comment by pedrobaeza** [comment]
What I see is that you are reusing the same External ID in the partner, and that's why it's overwritten, so this is not an Odoo bug. Closing this then.
