### ISSUE TITLE
 [15.0] pos_restaurant + pos_adyen: Paymanet Screen discarded because Go Floors Screen event ignore Payment processing

### ISSUE THREAD

**Issue by hugho-ad** [odoo/odoo#91002]
Impacted versions:
 Tested only on 15.0, maybe 14.0

Steps to reproduce:
I detected another bug related to [this issue](https://github.com/odoo/odoo/issues/86307), now the Go Floors Screen event ignores the payment Screen, when it's on payment processing state, it's quite difficult to replicate since you need to implement a pos_payment method with a terminal like adyen or any other that send request to a payment Terminal.

- Install pos_restaurant module
- Create pos payment Terminal A
- Add it to the pos config
- Go to the pos and sell something
- Choose Terminal A as payment method
- Send the request that makes the Terminal waits the card to be introduced.

Current behavior:

if Terminal got stock or delays more than the limit of time that sends you to the floors screen, the payment screen is closed and you are redirected to floors screen, making the terminal result be lost!

Expected behavior:
Go Floors Screen event should be blocked if a payment processing is going.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):
## 2849939

**Comment by hugho-ad** [comment]
@trj-odoo @caburj 

could you take a look of this?

is the same event of go flors screen that are making procesing payments screen be discarted

**Comment by caburj** [comment]
I think this issue is fixed here: https://github.com/odoo/odoo/pull/88833
Can you confirm if the issue is still reproducible as the PR mentioned has already been fixed?

But indeed, maybe it's a better UX to prevent this automatic redirection to floorscreen when in payment screen and there is a pending electronic payment.

**Comment by caburj** [comment]
Hi @hugho-ad. I asked our PO @odoo-dama and he said:
> we shouldn't redirect automatically User outside of a payment screen while a payment is in progress.

**Comment by hugho-ad** [comment]
@caburj 

Nice! I'm thinking the same;

**Comment by hugho-ad** [comment]
fixed at https://github.com/odoo/odoo/commit/7d6a92352755bc866c7d6f3f1c84a68d26fc50e1
