### ISSUE TITLE
[8.0] Bug name_get product_id in sale_order

### ISSUE THREAD

**Issue by jodhos** [odoo/odoo#9100]
Odoo 8  
I want to only show the product_default_code in sale_order:

<field name="order_line" context="{'display_product_code': True}" >
<field name="product_id" context="{'display_product_code':True,'partner_id

@api.multi
def name_get(self):
        if self._context.get('display_product_code', False):
            res = [(prod.id, prod.default_code) for prod in self]
        else:
            res = super(ProductProduct, self).name_get()
        return res

It works when you search a product, but when you add a another line, the product show the code+name.
![selection_123](https://cloud.githubusercontent.com/assets/13674104/10537602/3d264f40-73f3-11e5-9bd7-05b594d6a943.png)
![selection_119](https://cloud.githubusercontent.com/assets/13674104/10537604/412ae9c0-73f3-11e5-80f6-1e03f6baa0d0.png)

**Comment by Yenthe666** [comment]
Hi @jodhos,

Thank you for the report.
This isn't really a bug though, as it involves custom development.
Please do ask this on the official help forums if you still face this issue (help.odoo.com).

Regards,
Yenthe
