### ISSUE TITLE
Log entries do not appear in the chatter when updating tracked fields of a record using import

### ISSUE THREAD

**Issue by payen000** [odoo/odoo#91021]
Impacted versions: v13, v14, v15

Steps to reproduce: 

* Import a record with an external ID from a model that has fields with enabled tracking
* In the imported file, modify a tracked field (in v14 and v15, you can try the email field for res.partner, and in v13 you can try the partner_id field for sale.order)
* Import the file again to update the tracked field on the previously imported record

Current behavior:  Log entries do not appear in the chatter after updating tracked fields using the import function, but updating fields by hand for the same imported records does trigger the log entries in the chatter.

Expected behavior: Log entries should appear in the chatter after updating tracked fields with the import function.

Video link: https://www.youtube.com/watch?v=Rdr-_NOxxKQ

**Comment by fernandahf** [comment]
cc @moylop260

**Comment by moylop260** [comment]
And even it needed to refresh the page

In past version the messages were displayed without refreshing

Or not?

cc @mart-e

**Comment by mart-e** [comment]
Hi,

Thanks for the report but indeed, this is known. We consider the import is a technical feature and we do not log the changes as we do in the interface. This is also done for performances reasons.
Sorry but we do not plan to change this at the moment.

**Comment by moylop260** [comment]
For record,

It looks like Odoo needs to enable a hide checkbox on debug mode


Added in the following commit:
 - https://github.com/odoo/odoo/commit/f58368210c9c962c84cdcd2e2a799c5fc6183a13

It is working like a charm in runbot:
 - ![Screen Shot 2022-05-12 at 12 12 01](https://user-images.githubusercontent.com/6644187/168131474-6086287d-d2bc-4c11-8dd0-beb1e24f7536.png)
 - ![Screen Shot 2022-05-12 at 12 12 56](https://user-images.githubusercontent.com/6644187/168131478-fcf23250-46e3-484c-b8b9-9280758b4b32.png)

Thank you Martin

**Comment by randall-vx** [comment]
@edy1192 please check this issue

**Comment by edy1192** [comment]
> @edy1192 please check this issue

@randall-vx It's like @moylop260 says, it needs to enable the check button **Track history during import**. I checked the button and tracking works well.
