### ISSUE TITLE
[9.0] Bug in calendar module when generating recurrent meetings

### ISSUE THREAD

**Issue by schmidtwastl** [odoo/odoo#9115]
BUG: Creating recurrent meetings only generates meetings for the current month.  Silently fails for all the other months after the first month

Reproducing the error is possible in the official odoo.com instances:
calendar -> click somewhere on calendar -> create & edit a new meeting -> Options -> recurrent -> Until: "a date or number more than 1 month in the future" -> check calendar for the next months: empty.. 

I had the same issue on a self-hosted instance

**Comment by rahu1994** [comment]
Hello schmidttwastl,

In \addons\web_calendar\static\src\js\web_calendar.js change the following function in line 820:

    get_range_domain: function(domain, start, end) {
        var format = time.date_to_str;
        var extend_domain = [[this.date_start, '<=', format(end)]];
		
        if (this.date_stop) {
            extend_domain.push(
			//format(start) is start of view - this.date_stop is stop-date of first entry
                    //[this.date_stop, '<=', format(start)]
					[this.date_stop, '>=', time.auto_str_to_date('2000-01-01')]
            );
        }
        return new CompoundDomain(domain, extend_domain);
    },

Took me a while to find it, but it should work. There is surely a nicer way to do it ;)

Greetings,

rahu1994

**Comment by schmidtwastl** [comment]
Hello rahu1994,

Great! This works. Thank you.

While testing it, I found another issue. The Changeover between summer and winter times is handled incorrectly.
For Example:
If you want to have  a meeting every monday at 9 .a.m. it will swicth to 10 a.m. for all dates after 2016-03-27 and so on.. 
I have created another issue for this error: https://github.com/odoo/odoo/issues/9268

**Comment by Yenthe666** [comment]
@mart-e this one can be closed, this issue is no longer present.
Example settings:
![image](https://cloud.githubusercontent.com/assets/6352350/15274638/a1cb4fa2-1ab7-11e6-978c-c6ed7c61bd65.png)

Two months ahead in the agenda:
![image](https://cloud.githubusercontent.com/assets/6352350/15274652/e7c6ccfc-1ab7-11e6-851c-428c9a268d25.png)
