### ISSUE TITLE
[9.0 Enterprise] Footer background color issue

### ISSUE THREAD

**Issue by ddico** [odoo/odoo#9116]
**When changing the main color for the default theme the footer background color will not be displayed**

*Impacted versions:*

 - 9.0 - enterprise

*Steps to reproduce:*

 1. Login in runbot enterprise 9.0 
 2. Go to website, click on customize, then on "customize theme"
 3. Select one of the main colors (Ex. Emerald) (On a separate note here I would have expected the page to reload ... it doesn't)
 4. Refresh page to force the new color

*Current behavior:*

First time the page reloads the new background color shows properly :

![screen shot 2015-10-16 at 11 30 25 pm](https://cloud.githubusercontent.com/assets/7885477/10556858/153643ba-7460-11e5-8374-3089109fd8a6.png)

subsequent reloads will **not show** the background color:

![screen shot 2015-10-16 at 11 30 47 pm](https://cloud.githubusercontent.com/assets/7885477/10556889/25302906-7461-11e5-870c-977b62dfb7b1.png)

in the community version there is only one asset created and it will work as expected every time:

![screen shot 2015-10-16 at 11 33 12 pm](https://cloud.githubusercontent.com/assets/7885477/10556878/afbcae7e-7460-11e5-931c-eea6b5d9fa5e.png)

I've tried it in Chrome/Safari/Firefox - same behaviour

*Expected behavior:*

to have the background color in footer

**Comment by ddico** [comment]
I believe this must be related with how browsers would cache the assets and the order these assets are reloaded. 

When loading the page for the first time (no cache) the order is:
* website.assets_frontend.1.css
* website.assets_frontend.0.css

and footer background is loading properly.

Subsequent times browser is loading assets from cache in a different order:
* website.assets_frontend.0.css
* website.assets_frontend.1.css

and due to css specificity (I think) the background color is ignored by the browser.

As stated I tried Chrome/Safari/Firefox and I had the same behaviour.

**Comment by sle-odoo** [comment]
Hi,
This should be fixed by rev 7f4306ec15b8fc7e37cc85726a4951e137eed23f.
Please reopen if still happening.
Regards

**Comment by ddico** [comment]
@sle-odoo: Works as expected. Thank you!
