### ISSUE TITLE
9.0 Make invoice from picking do not work (only partially)

### ISSUE THREAD

**Issue by kovika** [odoo/odoo#9120]
Hi!

System : set up to make invoice from pickings
Make PO:     100 pcs from product1
The supplier (vendor) make partial delivery on tuesday: 50 pcs
He send the invoice by post, so we don't get it, so we don't mak invoice.
The vendor send rest of PO on Wednesday: 50 pcs
Again he send invoice by post, so we don't have it.

On friday we get two invoices by post:   delivery 1 : 50pcs,       delivery2: 50pcs
We try to make invoice on the already picked PO form, click invoices, create, the system fill in the datas from PO, we can only make one invoice from PO.  This is not ok.

If we get the invoice with the delivery, we can make invoice from PO form, and the system fill in only the partial delivered quantities, this is OK.

At the second delivery, we can make the same.

But after the whole purchase order was picked (two times), we can only make one invoice from it. That is bad.

Thank You

**Comment by jco-odoo** [comment]
Normally, you create those invoices through the Vendor Bills menu?  You could adapt the quantities there normally...

**Comment by kovika** [comment]
Yes, from Vendor bills menu, I can create the invoice. But only i cun choose the referenced purchase order, not the picking list.
If we receive 50 products with one delivery ( that we already checked, and picked) it's not so good idea to write in again the quantities into the invoice lines. Rather would be good to select in the invoice form the picking that the Vendor invoiced.

Now 1 PO ----> for example 2 Pickings 
                 ----> 1 invoice

Should work both way, like version 8 and before

1 PO -----> 2 pickings -----> 2 invoice (usually vendor process)
1 PO -----> 2 pickings -----> grouping -----> 1 invoice (still existing vendor process)

**Comment by kovika** [comment]
I checked now in version 8. Works perfectly. In version 9 on picking form, the "incoice control" feature is missing. In version 8 if vendor delivering a PO in 19 times, you can create 19 onvoice from them, or you can group in 1 invoice the 19 delivery.

**Comment by pedrobaeza** [comment]
From version 9, you invoice for purchase orders, but nothing prevents you to select the purchase order, adding that to the invoice full order, but then remove some lines or reduce the quantity in other lines, and then create another invoice, select again the purchase order, and the rest of the received stuff will be added, repeating this operation the times you want.

I'm closing this as answered and no real bug. You only need to adapt your process.
