### ISSUE TITLE
Log entries do not appear in the chatter when updating tracked fields of imported record by hand unless window is reloaded

### ISSUE THREAD

**Issue by payen000** [odoo/odoo#91274]
Impacted versions: v14

Steps to reproduce:

- Import a record with an external ID from a model that has fields with enabled tracking
- On the imported record's form view, modify a tracked field by hand (you can try the email field for res.partner)
- Reload the browser window

Current behavior: Log entries do not appear in the chatter after updating tracked fields by hand unless the window is reloaded. When the window is reloaded, the log entries for all modifications appear at once.

Expected behavior: Log entries should appear in the chatter after updating tracked fields by hand without needing to reload the window. In v13 and v15 it works as expected.

Video link: https://youtu.be/XUbIZyCbwm8

**Comment by fernandahf** [comment]
cc @moylop260
