### ISSUE TITLE
[15] fleet: vehicle images is not displayed in Services list views

### ISSUE THREAD

**Issue by poonam2606** [odoo/odoo#91276]
Impacted versions: 15.0

Steps to reproduce: Fleet > Services

Current behavior: Image is not displayed for Vehicle in list view
![Screenshot (36)](https://user-images.githubusercontent.com/60427448/168161089-d21f343e-d46f-47bf-9a74-4279a6668e4c.png)

It is displayed correctly in Kanban view
![Screenshot (37)](https://user-images.githubusercontent.com/60427448/168161521-8b04285e-817d-40a4-9624-dc7232b21bca.png)

Expected behavior: Image should be displayed

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
fixed in:  https://github.com/odoo/odoo/commit/e57b6f898775a0e432ae1a21266a0f4bf82c0242

**Comment by vava-odoo** [comment]
Thanks @poonam2606 for reporting and @niyasraphy for the PR!
