### ISSUE TITLE
Error Occurs when we select record from leave allocation and do approve allocation action.

### ISSUE THREAD

**Issue by RiteshSerpentCS** [odoo/odoo#91286]
Impacted versions: 15.0

Steps to reproduce:
Time Off -> Allocation -> Treeview -> Select Records To Approve -> Action Validate

Current behavior:
Error Occurs

Expected behavior:
Should be approved

Video/Screenshot link (optional):
https://www.awesomescreenshot.com/video/8884203?key=3099fd947d6954e365d1443f4e43481c

Support ticket number submitted via odoo.com/help (optional):

**Comment by RiteshSerpentCS** [comment]
@vst-odoo

**Comment by ppr-odoo** [comment]
Hello @RiteshSerpentCS  Thanks for having reported this issue.

**Comment by sswapnesh** [comment]
This has been fixed in https://github.com/odoo/odoo/pull/91307
