### ISSUE TITLE
[9.0] Partial payment in multi-currency does not work

### ISSUE THREAD

**Issue by fclementic2c** [odoo/odoo#9134]
Activate the multicurrency.
Create a bank journal in USD (base company in EUR)
Create a invoice in USD
Use register payment to do a partial payment using the EUR journal then a partial payment using teh USD journal.
Check the partial payments (under the total of the invoice). Some are negative, some are positive (I did several tests). 
On top of that, the new residual amount is wrong (and not because of the sign...it is a another isuue)
see print screen below :  

![runbot_test](https://cloud.githubusercontent.com/assets/5735158/10576853/cc7e652c-7666-11e5-80e9-8e6d44779b34.png)

**Comment by ztsiklauri** [comment]
Watching

**Comment by fclementic2c** [comment]
Fix 1: https://github.com/odoo/odoo/commit/01d121a90a7a6ce2651f9f2045691b3a0bf2af9a
Fix 2 : https://github.com/odoo/odoo/commit/f8b65541f9dd80afe5866b3f347eebe009108056
