### ISSUE TITLE
Warning module: picking onchange_partner_in is broken

### ISSUE THREAD

**Issue by rvalyi** [odoo/odoo#914]
Hello,

in addons/warning/warning.py around line 150 there is code like:

```
class stock_picking(osv.osv):
    _inherit = 'stock.picking'

    def onchange_partner_in(self, cr, uid, ids, partner_id=None, context=None):
        if not partner_id:
```

[...]

```
result =  super(stock_picking_in, self).onchange_partner_in(cr, uid, ids, partner_id, context)
```

Well the problem is that all that code is broken in v8 because there is no super onchange_partner_in method anymore and there is even no stock_picking_in class as written in super(stock_picking_in, self).

Finally that module is really badly designed. It should also be modularized to load just the apps being used (instead of all).

Hope this helps.

**Comment by Yenthe666** [comment]
Hi @rvalyi,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
