### ISSUE TITLE
[8.0] Sending mass mailing takes Supplier as recipient with invoice attached

### ISSUE THREAD

**Issue by mgielissen** [odoo/odoo#9141]
When sending mass mailing e-mail, the recipient is a Supplier (with a invoice attached in the marketing e-mail) in stead of the distribution list.

**Comment by mgielissen** [comment]
I have 2 8.0 databases with the problem that it takes a customer with invoice pdf as attachment instead of the mailinglist when sending a newsletter. So the recipient is a client with a old invoice pdf attached.

 Reinstalling/upgrades mass_mailing doesn't work. Any ideas?

**Comment by mgielissen** [comment]
Strange enough I  cannot reproduce the problem. I there anyway to debug this? When sending marketing mail to everyone (though mailqueue), the mail will be send to the first supplier with an purchase invoice attached. Sending mass mail as a test (without mailqueue) works.

**Comment by Yenthe666** [comment]
Hi @mgielissen,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
