### ISSUE TITLE
[9.0] Error when Manual new Analytic Entries 

### ISSUE THREAD

**Issue by thanhchatvn** [odoo/odoo#9144]
1. Go to menu Accounting --> Adviser --> Analytic Entries
2. Create new 1 record
3. Input information and select Product --> on change product --> Error:
Line 32, file odoo/addons/account/models/account_analytic_line.py 
Comment: 
I think uom_po_id have not category_id , will be error when we're compare self.product_id.uom_po_id.category_id.id and unit.category_id.id

![selection_023](https://cloud.githubusercontent.com/assets/3313064/10595999/1b1f679c-7709-11e5-9dfc-7318166fc0e0.png)
![selection_024](https://cloud.githubusercontent.com/assets/3313064/10596000/1b2011d8-7709-11e5-8829-09030fb5aee8.png)
![selection_025](https://cloud.githubusercontent.com/assets/3313064/10596001/1b252998-7709-11e5-9307-271852e3bc1f.png)

**Comment by mart-e** [comment]
Hello,

Thanks for the report, it was fixed at revision eca1983aef4ca7db04ddd469e1512fe93155a692

PS: when you are reporting an issue like this, it's more useful to copy paste the complete error message. It's usually the end of the error where most of the useful info is present.
