### ISSUE TITLE
Send an invoice or a sale order by mail

### ISSUE THREAD

**Issue by ghost** [odoo/odoo#9150]
#### Impacted versions

8.0
#### Steps to reproduce
1. Go to an open invoice
2. Push the button _Send by Email_
3. The wizard opened, push the button Send
   ![capture d ecran 2015-10-20 a 11 48 35](https://cloud.githubusercontent.com/assets/7781090/10603954/76435fbc-7721-11e5-8958-175bef489cdd.png)
#### Current behavior

A notification is generated which generate a mail too **ONLY IF** the recipient partner is configured to receive all notifications. The email's type will be **comment** .
![capture d ecran 2015-10-20 a 11 58 24](https://cloud.githubusercontent.com/assets/7781090/10603959/834f37e4-7721-11e5-9ea5-145d33bd294d.png)

If the partner is configured to never receive notification, the system will never send a mail.

It's a problem because we don't want to send notifications to our partners (e.g. when an invoice is confirmed) but we want to send the invoice by mail.
#### Expected behavior

When we click on _Send_, an email is generated with the type **email**.

Regards,

**Comment by kevgoris** [comment]
Ticket number: 652554

**Comment by Yenthe666** [comment]
Hi ghost,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
