### ISSUE TITLE
How to allow HR Officer to access his employees and employees of employees information?

### ISSUE THREAD

**Issue by meswapnilwagh** [odoo/odoo#9156]
Hello I am using the Odoo V8 What I want to do is

I have one hr Office O1 and there are three employee under him E1,E2,E3

E1 also has two more employee under him E4 and E5

E2 also has one employee under him E6 

I want O1 should should able to see the Leaves and timesheet activities of 

E1,E2,E3 who are under with the E4 E5 and E6. 

How can I get this done.

**Comment by Yenthe666** [comment]
Hi @meswapnilwagh,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
