### ISSUE TITLE
9.0 - Description MISSING for Timesheet Invoicing

### ISSUE THREAD

**Issue by stephaniemillet** [odoo/odoo#9158]
When invoicing time sheet lines, on product 'time and material'
all lines are concatenated on ONE invoice line with NO description

We need to have on the invoice : 
- date / user / description of time sheet lines

**Comment by Yenthe666** [comment]
@apr-odoo any feedback/update?

**Comment by pedrobaeza** [comment]
This is a feature not yet considered in standard, but not a bug itself. There's an OCA module that can help you in getting this:

https://github.com/OCA/account-invoicing/tree/9.0/sale_timesheet_invoice_description
