### ISSUE TITLE
9.0 - Module : Employee > View LIST Missing (Department and Job title)

### ISSUE THREAD

**Issue by stephaniemillet** [odoo/odoo#9159]
View list for "Department" Title hr.employee / hr.department is missing
View list / Configuration menu for "Job Title" hr.employee / Job_id  missing

With no list view, we can't : 
- delete a data
- import a list  with a .csv

**Comment by Yenthe666** [comment]
Hi @stephaniemillet,

There are treeviews for departments, employees, employee tags etc at this point so you should have no problem importing data.

Regards,
Yenthe
