### ISSUE TITLE
[15] project: traceback on clicking on blocking smart button on task

### ISSUE THREAD

**Issue by poonam2606** [odoo/odoo#91603]
Impacted versions: 15.0

Steps to reproduce: Task > Click on Blocking Smart Button
![Screenshot (42)](https://user-images.githubusercontent.com/60427448/168886735-6a645962-613c-49ab-b8bd-5484f85a9b5a.png)

Current behavior:
![Screenshot (43)](https://user-images.githubusercontent.com/60427448/168886814-e2f7ddb8-9543-4ea7-852b-6becb3a24737.png)

Expected behavior:  Able to view task

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by xavierbol** [comment]
Hello @poonam2606 , 

Thanks for the report, I think the issue was from 15.1 and is fixed in #91619.

Have a nice day! 🙂
