### ISSUE TITLE
[15] hr: Can not view Work Entries from employee

### ISSUE THREAD

**Issue by poonam2606** [odoo/odoo#91600]
Impacted versions: CE 15.0 

Steps to reproduce: Open Employee and Click on Work Entries Button

Current behavior:
![Screensfdhot (4dffd0)](https://user-images.githubusercontent.com/60427448/168883312-9d4efa57-499b-47f6-a23a-cc64da29f53a.png)
![Screenshdfot (4fd1df)](https://user-images.githubusercontent.com/60427448/168883506-ecef1b26-a188-4f59-b0cd-1f9d081dfeb7.png)

Expected behavior: Able to view Work Entries

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
fixed by: https://github.com/odoo/odoo/commit/f602236f647bc679bdd385411dcc213dd9eb8b48
