### ISSUE TITLE
[7.0]  Non-breaking space character in email-address silently breaks notifications/email-sending

### ISSUE THREAD

**Issue by mrvdb** [odoo/odoo#9161]
When a partner has an email addres which contains a non-breaking-space character (`dec: 165, &nbsp;, hex: a0`) The sending of a notification or email with that email address in the recipient list will cause the following error:

```
Traceback (most recent call last):
  File "/opt/openerp/server/addons/mail/mail_mail.py", line 309, in send
    mail_server_id=mail.mail_server_id.id, context=context)
  File "/opt/openerp/server/openerp/addons/base/ir/ir_mail_server.py", line 413, in send_email
    assert smtp_to_list, "At least one valid recipient address should be specified for outgoing emails (To/Cc/Bcc)"
AssertionError: At least one valid recipient address should be specified for outgoing emails (To/Cc/Bcc)
```

Reproduce:
1. Create partner with email-addres that contains `non breaking space` character (this looks like a normal space on the screen)
2. add this partner as a follower of another partner for example
3. in that other partners form view, create a chatter message, so notifications would go out
4. the above error wil be displayed in the log, there is no visible failure on the screen.

**Comment by rvalyi** [comment]
related to an unsupported Odoo version. Can it be closed?
cc @Yenthe666

**Comment by Yenthe666** [comment]
Hi @mrvdb,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
@rvalyi thanks a lot for the ping!

Regards,
Yenthe
