### ISSUE TITLE
 [9.0] - Accounting - Belgium VAT declaration - vendor refunds using taxes with non-deductible part

### ISSUE THREAD

**Issue by jdegoy** [odoo/odoo#9162]
There is a tax that handles a scenario of non-deductibility, i.e. "TVA Entrant - Frais de voiture - VAT 50% Non Deductible (Price Excl.)"

In the legal report the non-deductible part of the tax should be filled in case 82. A €100 invoice will result in €110,5 for case 82.
When I refund this invoice completely I expect the 110,5 to be pulled out of 82 and reported in case 85.
Currently the logic is pulling only a 100 out of case 82.
This was already an issue in v8 but there we could fix this in the tax (see second screenshot). With v9 this has been moved to the local reporting module so we can't fix it without custom code.
Attached screenshots should clarify.

Steps to reproduce:
* easiest to start from a clean db
* create a vendor invoice with one line item using the tax in question with an amount of 100
* refund the vendor invoice completely
* current result; 10,5 in case 82
* expected result; 0 in case 82
![2015-10-20 14_50_41-taxes - odoo](https://cloud.githubusercontent.com/assets/11032154/10610436/10f06232-7748-11e5-976e-dfa7cef378fb.png)
![2015-10-20 14_43_45-](https://cloud.githubusercontent.com/assets/11032154/10610435/10ea39e8-7748-11e5-817d-522610877f7e.png)

**Comment by Yenthe666** [comment]
@mart-e could you look at this please? This is an issue..

**Comment by pvy-odoo** [comment]
Solved by https://github.com/odoo/enterprise/commit/0ae75067584b7047a177284e7d690fdbd7f10b7b

**Comment by jdegoy** [comment]
Validated.
