### ISSUE TITLE
[9.0] Bug in calendar module view: most recurrent meetings not displayed in the daily and weekly view

### ISSUE THREAD

**Issue by schmidtwastl** [odoo/odoo#9165]
Generate some recurrent meetings -> reload calendar view -> most of the meetings are missing in the daily and weekly calendar view

If you click on "month" all the the meetings are loaded and are now also back in the daily and weekly view

**Comment by yvaucher** [comment]
I confirm this, it seems that recurrent event are only displayed if the first event is on the same view.

If you change to next month with month view you won't see the one of the next month, even if the count is 100

**Comment by yvaucher** [comment]
Reccurent event will be shown on next pages of day and week if you watch the month view first. However going too far and coming back on day or week page will make the recurrent event disappear again.

**Comment by nle-odoo** [comment]
Hello,

It should be solved in saas-6 (between 8.0 and 9.0) with https://github.com/odoo-dev/odoo/commit/61398b2 and will be forward ported soon on 9.0 (the commit could be applied as this in 9.0).

Thanks for reporting.

**Comment by yvaucher** [comment]
@nle-odoo Thanks it works
