### ISSUE TITLE
[9.0][Import QIF Bank Statement] Statement line transaction date format is inconsistent

### ISSUE THREAD

**Issue by jn-minos** [odoo/odoo#9169]
When uploading QIF bank statements the transaction date format used is not consistent, sometimes it is %d/%m/%Y other times it is %m/%d/%Y.

I've added the language English (UK) which has a date format of %d/%m/%Y. My user profile is also setup with the English (UK) language. 

I've completed testing on the SaaS as well as my local install, issue is occurring on both.
I've checked the database table *account_bank_statement_line* and I can see the *date* field contains the incorrectly formatted date. This suggests to me that the issue is with the data upload and not the rendering of the data through the web front end.

**QIF Data**
!Type:Bank
D10/08/15
T-21.75
PPAVILLON DES VINS         PAVILLON DES
^
D13/08/15
T-58.30
PJAMES TERRENCE REBBECK    DARLINGTON
^

**Odoo Statement Lines**
08/10/2015	PAVILLON DES VINS PAVILLON DES			$-21.75			
13/08/2015	JAMES TERRENCE REBBECK DARLINGTON	$-58.30

**Comment by Whisno** [comment]
Ok I found the problem. As described in the commit message : 

The QIF format was not designed as an industry standard but as a quick and
dirty communication means for Inuit softwares. Unfortunately it became used
by financial institutions, altough there is no standard defined.

A quick google search found dates formatted as mm/dd/yy, mm/dd'yy (Y2K bug !),
dd Month YYYY ans so on. Luckily, the dateutil package can handle almost
any date format (using the 'fuzzy' parameter).

It appears that the QIF date format initially was mm/dd/yy, but most softwares
create QIF files using the local date format ; it might either be day first or
month first. So we need to have that information provided by the user.

**Comment by o2030** [comment]
I have an issue opened with Odoo about this. I temporarily fixed the problem by changing line 58 in /addons/account_bank_statement_import_qif/account_bank_statement_import_qif.py to:

vals_line['date'] = dateutil.parser.parse(line[1:], fuzzy=True, dayfirst=True).date()

But really the value of dayfirst parameter should be set through the web GUI. It could default to a value based on the user timezone, or could be set by a value on the bank account record, but I think the user should be able to override it at time of QIF import.
