### ISSUE TITLE
[15.0][BUG] sale_timesheet_margin: `purchase_price` on `sale.order.line` isn't updated when pricelist is changed

### ISSUE THREAD

**Issue by yankinmax** [odoo/odoo#91703]
**Impacted versions:**

 15.0

**Steps to reproduce:** 

Create product: type->Service, Invoicing Policy->Prepaid/Fixed Price.
Create Sale order: add newly created product.

**Current behavior:**

If product is just added and you're still in edit mode. You can change the pricelist and Cost (`purchase_price`) is recomputed depending on pricelist currency.
Once you save the sale order, try to change pricelist and Cost isn't recomputed anymore.
It's behavior due to code written here: https://github.com/odoo/odoo/blob/2c5450af8d6f5934e6ab2095c3307b432fa3036a/addons/sale_timesheet_margin/models/sale_order_line.py#L9

**Expected behavior:**

The Cost is recomputed always, not depending if the sale order line is newly created or is already saved.

**Video/Screenshot link (optional):**

![fixed_price](https://user-images.githubusercontent.com/29202630/169083309-c9ad62a2-4466-4c55-a003-3813e6dee047.png)
![new-not-saved-yet](https://user-images.githubusercontent.com/29202630/169083316-88ba94c7-62a8-442c-9b26-460d904e69c1.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by momegahed** [comment]
this will fix it: https://github.com/odoo/odoo/pull/92790
