### ISSUE TITLE
[8.0] Make custom configuration page for custom module

### ISSUE THREAD

**Issue by muhammadfarizarya** [odoo/odoo#9171]
I have create menu item on tab setting on submenu configuration it works,
but when I change my configuration fields then push button 'apply' and go to another configuration and back, it discarded.
here is my code :
![screenshot from 2015-10-21 11 12 01](https://cloud.githubusercontent.com/assets/3858791/10627593/b229bda4-77e5-11e5-846d-a08fb0429f7e.png)
![screenshot from 2015-10-21 11 12 13](https://cloud.githubusercontent.com/assets/3858791/10627594/ba0769b8-77e5-11e5-8e2e-c5ae4ea02aa2.png)

**Comment by Yenthe666** [comment]
Hi @muhammadfarizarya,

Thank you for your report.
I see nothing that saves your records away to a non-transient model though. Transient models get cleared automatically by a scheduler, which means you loose the data in the transient.
Shouldn't be a bug plus Odoo 8 is no longer a long time stable version. If you can reproduce it on V9, V10 or V11 then please create a new bug report (with all the code).

Regards,
Yenthe
