### ISSUE TITLE
[9.0] No date filters on Aged Recevable/payable reports

### ISSUE THREAD

**Issue by fclementic2c** [odoo/odoo#9174]
These financial reports needs to be printed at any date in the past for exemple for cut-off entries purposes (ie : provisions on recevables calculation).
Thanks

**Comment by csnauwaert** [comment]
Hello,

Sorry for the long time it took to answer this. Unfortunately we can not fix this in stable 9.0 as it would requires some breaking changes. However this has been fixed in version 10. Therefore I'm closing this issue.

Best regards
