### ISSUE TITLE
[9.0] problem with web.asset_common and csrf token

### ISSUE THREAD

**Issue by Cedric-locchi** [odoo/odoo#9175]
to begin, sorry for my bad english, i'm french

I have pulled yesterday all code from v9 and enterprise
I can run v9 community properly  (create db and access it)  but I cannot create db in v9 Enterprise.
When I click on create new db, I receive the following message in the browser:

```
Bad Request
Invalid CSRF Token
```

i try to drop my db and to do a **-u all** for reload the model but nothing works

and i have an error whit web.assets_common

```
015-10-21 08:03:03,903 1595 WARNING adigit openerp.addons.base.ir.ir_qweb: NameError: .o-display-marked is undefined in - on line 321, column 29:
320                         &.marked:after {
321                             .o-display-marked("\f00c", 0, 360px, #21b799);
322                         }

This error occured while compiling the bundle 'web.assets_common' containing:
    - /web/static/src/less/mimetypes.less
    - /web/static/src/less/animation.less
    - /web_planner/static/src/less/web_planner_common.less
    - /web_editor/static/src/less/web_editor.less
```

these errors are expressed from the git pull yesterday but in the runbot there is nothing bad

**Comment by jose-eezee** [comment]
I have the same error

**Comment by Yenthe666** [comment]
Hi @Cedric-locchi and @Cedric-locchi,

Can you still reproduce this problem with the latest V9? I don't think this is still reproducable.
