### ISSUE TITLE
Manufacturing order with multiple BOMs having differents routing locations

### ISSUE THREAD

**Issue by svert** [odoo/odoo#9176]
Hi,

CONFIGURATION:
- configure **Odoo 8** with advanced routes, routings, properties on sale order lines
- 1 product: chair
- having 3 warehouses: WH=selling warehouse, BWH=chairs manufacturing black warehouse, WWH=chairs manufacturing white warehouse,
- using 5 routes:
  - Make to Order for WH: route with only 1 push rule "make to order for WH"
  - Transfer BWH->WH: route with only 1 push rule "transfer from another location" + "create procurement"
  - Transfer WWH->;WH: route with only 1 push rule "transfer from another location" + "create procurement"
  - Manufacture BWH: route with only 1 push rule "manufacture at BWH"
  - Manufacture WWH: route with only 1 push rule "manufacture at WWH"
- using 2 routings
  - BWH manufacturing : routing at BWH/Stock location (with or without Working Orders)
  - WWH manufacturing: routing at WWH/Stock location (with or without Working Orders)
- using 2 BOMs for chairs
  - BOM for manufacturing at BWH with the "Manufacture at BWH" routing and a property "MO at BWH"
  - BOM for manufacturing at WWH with the "Manufacture at WWH" routing and a property "MO at WWH"

SCENARIO:
- create 1 sale order with 1 order line for 1 chair with property "MO at BWH", confirm it, run schedulers
  => you get the desired steps: manufacture at BWH, then transfer from BWH to WH then transfer to client
- create 1 sale order with 1 order line for 1 chair with property "MO at WWH", confirm it, run schedulers
  **_=> you get a STRANGE manufacture at WWH but with "raw materials location"+"finished product location" at BWH !!!
  => if you "produce" the chair, you then have a transfer from BWH to WH !!!_**

QUESTION: Am I missing something? How can I circumvent this problem?

NOTA 1: depending on the configuration the roles of BWH and WWH may be switched

NOTA 2: this issue may be related to https://github.com/odoo/odoo/issues/2111 which is itself related to only 1 BOM

**Comment by Yenthe666** [comment]
Hi @svert,

Thanks a lot for your very detailed bug report and sorry for the late reply.
At this point Odoo 8 is end of life and is no longer maintained so I'm afraid I have to close this.
If you can still reproduce this on 9.0, 10.0 or 11.0 then please do let me know.

Regards,
Yenthe
