### ISSUE TITLE
[9.0] Wrong bank reconcile default proposal

### ISSUE THREAD

**Issue by fclementic2c** [odoo/odoo#9177]
Create 2 customer invoices with the same amount and same customer. 
Validate
Open a new bank statement in order to pay the 2nd invoice
Reconcile
The system will find the 2 invoices but propose the wrong invoice.
This use case aim to show that there is no way to indentify a customer payment with a reference like the invoice number.

Thanks

**Comment by pedrobaeza** [comment]
@fclementic2c AFAIK, the propose invoice to be reconciled is the oldest one, so where's the problem?

**Comment by pedrobaeza** [comment]
No answer, so I close.

**Comment by Yenthe666** [comment]
@pedrobaeza perhaps 4 days is a bit fast, no? I usually wait 1 month. Just my five cents!

**Comment by fclementic2c** [comment]
@pedrobaeza no problem. a bit of cleanup is ok when it is that old.
My comment was due to a change of behavior between 8 and 9. I live with it.

**Comment by pedrobaeza** [comment]
Yeah, I'm the cleanup man :yum: 

No, seriously, I think it's a good technique aligned with GTD methodology: you consider this done until further notice. If someone complains or there are more details/explanations, it's easy to reopen.
