### ISSUE TITLE
[9.0] Purchase Order - Receive Products button incorrect when purchasing services

### ISSUE THREAD

**Issue by sbidoul** [odoo/odoo#9181]
When purchasing Services, the Receive Products button shows all Transfers. 

Tested on http://108639-9-0-01d121.runbot6.odoo.com/

How to reproduce:
- create a PO and select a service product
- confirm the PO
- click on the Receive Products button

Actual result: all Transfers are shown.

Expected result: the Receive Products button is not visible.

**Comment by sle-odoo** [comment]
Hi,
This issue is still valid in v11 :) We'll have a look. Thanks for the report and your patience.

MB 817421
Regards

**Comment by sle-odoo** [comment]
closed by 941ddaee749aedb9ebe7401ce434b8316e07ae6f
