### ISSUE TITLE
Missing check on Fiscal year last day 

### ISSUE THREAD

**Issue by Maurice67205** [odoo/odoo#9184]
in V9 Enterprise, in Accounting->settings I can configure the last day of the Fiscal Year but no check is made

So I can easily select September as month and 78 as day

maurice
![capture du 2015-10-21 14 32 26](https://cloud.githubusercontent.com/assets/11387919/10637049/8fb6990e-7803-11e5-9a51-7d0bee64f7eb.png)

**Comment by Yenthe666** [comment]
@qdp-odoo this is handy for you. This behaviour is the case in V9 & V10 and I know you're reintroducing the fiscal years in V12.. Perhaps we can build this check in in the upcoming V12?

**Comment by qdp-odoo** [comment]
mhm it doesn't look critical to me: okay, the program let you encode a silly thing but, what were you expecting? raising an error telling you 'the 78th of September doesn't seems like a valid option.' ?or modify automatically the encoded value to 31?

At least, I think what you'd really expect in that moment is to have the program consider it the 78th of September as the last day of the month, which is the current behavior... so nothing critical but could be enhanced in some way. We'll take care of that.

thanks for the contribution

**Comment by Yenthe666** [comment]
Yep, that is why I labelled it wishlist. This will most likely be enhanced in the upcoming V12, thanks for the suggestion & feedback @Maurice67205.
