### ISSUE TITLE
[v8] Purchase unit of measure is a product attribute, when it should be a supplier info attribute

### ISSUE THREAD

**Issue by pjmcdermott** [odoo/odoo#9192]
Currently in v8, the purchase unit of measure is a product attribute. But it is not necessarily the case that a product is purchased in the same units from every supplier. Purchase unit of measure should be a supplierinfo attibute.

For instance, one supplier may only sell a product in singles. Another may sell a product in a case of a dozen. These purchases of the same product would have different suppliers, supplier SKU codes, prices and purchase units of measure.

There is also a use case where a supplier sells the same product in different units of measure. Say single items, and a case. These would have different supplier SKU codes, prices and units of measure.

I switched on "Manage different units of measure for products", thinking that this option would provide the functionality described, but it doesn't really do what it says on the tin. This feature should really be called "Allow a product to be purchased in a single unit of measure which is different from the sales unit of measure".

**Comment by spadae22** [comment]
Hello,
UoM ans PO_uom seem not to be understood by odoo. We use the exact functionality you describe above. It required setting the UoM correct, rounding, etc. We also have developed modules for many uses including case discounts, line ltem price level, etc. We have 4000 products this way and on "face" value as UoS is confusing also, which we do not use.

**Comment by spadae22** [comment]
Also, see this, why this is not merged I have no idea, but it is need to reserve delivery orders quants correctly. https://github.com/odoo/odoo/pull/8183

**Comment by matt454357** [comment]
@spadae22,
I need a supplier UoM attribute.  Can you point me to a particular module?

**Comment by Yenthe666** [comment]
Hi @pjmcdermott,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
