### ISSUE TITLE
[9.0] Bug with onchange function on o2m field if there is a m2o field linked to parent record in tree view

### ISSUE THREAD

**Issue by twinslady1612** [odoo/odoo#9193]
Steps to reproduce this error:
- Create a new employee
- Create a new contract of this employee and define working schedule
- Create payslip. Then I got this error:

```
Traceback (most recent call last):
  File "/home/odoo/runbot/extra/runbot/static/build/108730-9-0-83bd17/openerp/http.py", line 599, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/runbot/extra/runbot/static/build/108730-9-0-83bd17/openerp/http.py", line 650, in dispatch
    return self._json_response(result)
  File "/home/odoo/runbot/extra/runbot/static/build/108730-9-0-83bd17/openerp/http.py", line 588, in _json_response
    body = json.dumps(response)
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <openerp.models.NewId object at 0x7f7e86eedd90> is not JSON serializable
```

**Comment by jcdrubay** [comment]
This issue happens when there is a Working Schedule set on the contract of the employee.

**Comment by sbevnc** [comment]
It seems that Odoo has changed the way on-change is implemented a little bit, and some modules are not updated with those changes.

A quick fix, you just need to inherit `hr.payslip` form view from `hr_payroll` module, then remove `payslip_id` from inline form view using xpath.

![image](https://cloud.githubusercontent.com/assets/6452983/10813144/45837922-7e4f-11e5-84bd-7d2868feecea.png)
 
then it should be fine again

![image](https://cloud.githubusercontent.com/assets/6452983/10813176/948fbfb2-7e4f-11e5-8ea3-cf8ede13f754.png)

**Comment by andreparames** [comment]
We had the same problem, and identified the bug as the result of `name_get()`, which returns a tuple `(id, name)`, hence returning `(NewId, "Payslip Name")` for the unsaved payslip.

Thanks @sbevnc for the clean solution! That said, maybe `name_get()` should strip any `NewId` from its responses? Returning `False` instead avoids the problem even if the view has that field.

**Comment by sbevnc** [comment]
I'm glad it helps you too @andreparames.

**Comment by lem8r** [comment]
fixed here 0a7ee85c18b9f847e0d0f1f9b54e4f43b2e046a9
works fine for me now

**Comment by OrlandoMalaquias** [comment]
thanks alot, its working for me now too

**Comment by Yenthe666** [comment]
Hey all,

Should indeed be updated & fixed. Please update your local Odoo instance. 😉
