### ISSUE TITLE
Reversed items are not reconciled

### ISSUE THREAD

**Issue by Maurice67205** [odoo/odoo#9200]
On Enterprise 9 I make an invoice that generates some lines
When going to the journal entry menu, I can select the journal entry corresponding to the invoice and reverse this entry but the receivable/payable items are not reconciled which should be the default behaviour when reversing lines.

regards

Maurice

**Comment by pedrobaeza** [comment]
Hi, @Maurice67205, standard reversal wizard in Odoo doesn't perform that operation, but it's a missing feature, not a bug. If you want that feature, you can use the OCA module account_reversal in:

https://github.com/OCA/account-financial-tools/tree/9.0/account_reversal
