### ISSUE TITLE
Does Odoo SA care about of abuse odoo enterprise?

### ISSUE THREAD

**Issue by report-odoo-enterprise-abuse** [odoo/odoo#92052]
Impacted versions:
Odoo Enterprise
Steps to reproduce:
> We found some company is offering odoo-enterprise based software in cloud to end customers (for production use, not trial), with very low pricing and the price is not related user count. We suspect they are use and sale pirate version of odoo enterprise. 
Is there anyway to anonymous report such abuse?  (detail proof could be provided later)

We raised help ticket 2844592 at May 05, **after two weeks, nobody is responding the ticket.**

Thus comes the question in title, or what's the correct channel to resport such info?

Support ticket number submitted via odoo.com/help (optional):
opw-2844592

![xxx](https://user-images.githubusercontent.com/106076306/169804404-5e832df6-7f78-4d9a-af40-29219bc7c0b9.png)

**Comment by Yenthe666** [comment]
@report-odoo-enterprise-abuse I'm afraid that the public issues from Odoo are pretty much dead. The last people who managed (me and Pedro) decided to quit because barely anyone at Odoo SA would look at our pings and managing of issues.
Ironically I normally say report it through the official channel but yeah.. A delay of 1-2 weeks seems to be rather normal at times :/

**Comment by report-odoo-enterprise-abuse** [comment]
> @report-odoo-enterprise-abuse I'm afraid that the public issues from Odoo are pretty much dead. The last people who managed (me and Pedro) decided to quit because barely anyone at Odoo SA would look at our pings and do any managing of issues. Ironically I normally say report it through the official channel but yeah.. A delay of 1-2 weeks seems to be rather normal at times :/

Thanks for reply. Sadly to know this situation. 
I was thinking odoo ecological is prosperous, but this looks like kind of decline or out of control 👎

**Comment by Feyensv** [comment]
cc @mart-e ?

**Comment by mart-e** [comment]
Hello,

Sorry for the delay of reply, I will see that you get a reply very soon on the ticket.
Support tickets is the right way to report this or your can also contact our [abuse email address](https://www.odoo.com/acceptable-use).
Thank you for the report, we do care about abuse on Odoo Enterprise, thank you very much to raise this suspicious case.
I will close this github issue as details should not be discussed publicly but we will surely investigate the matter.
Best,
