### ISSUE TITLE
Models have no table when creating new model or transient model in a custom module while other apps upgrade.

### ISSUE THREAD

**Issue by 0xSaltyHash** [odoo/odoo#92087]
Impacted versions: 15 

Tested on (commit #502003ac548d6620374dfbab4fb7be6dee3c1bf5)

Steps to reproduce: 

1. Create a new custom module (nothing fancy a model with a single field would be enough).
2. Run Odoo and install this module.
3. Edit your models and add a new model/transient model (I named mine 'test.wiz2').
4. Run the server again and go to Apps and try upgrade other module or install new module.

Current behavior:
Server Logs show `2022-05-23 13:39:23,656 26960 ERROR db_001 odoo.modules.registry: Model test.wiz2 has no table.` 

Expected behavior:
No errors in log as it is expected that a new model created wouldn't be present in Database

This behavior manifests when you try upgrading a module other than the one you are Customizing  or installing a new module, this error sometimes causes build fails on odoo.sh.

**Comment by 0xSaltyHash** [comment]
A workaround I found that maybe is related to the root cause of this possible issue.

I added this method to my model to force the call of `_auto_init()`.

```
def init(self):
        res = super().init()
        self._auto_init()
        return res
```

**Comment by andrp92** [comment]
I can confirm that I'm having same issue on odoo.sh.

**Comment by andrp92** [comment]
@0xSaltyHash I used your workaround and it seems to work. Thank you.

**Comment by support-skillreso** [comment]
I also came across this issue on Odoo.sh. @0xSaltyHash 's solution has worked for me too. Thank you.

**Comment by andrp92** [comment]
@vava-odoo where was it fixed? Can you please post the commit ?

**Comment by x-jiali** [comment]
I also came across the error 'has no table' on Odoo.sh. It is fixed by increasing the version in _manifest_.py
