### ISSUE TITLE
[15] account: traceback on changing currency in Register payment screen

### ISSUE THREAD

**Issue by poonam2606** [odoo/odoo#92114]
Impacted versions: 15.0

Steps to reproduce: 

- Open Register Payment screen and Remove Date
- Change currency

![Screenshot (63)](https://user-images.githubusercontent.com/60427448/169865100-e600aa06-6057-456e-acba-21d7112adc62.png)

Current behavior:
![Screenshot (62)](https://user-images.githubusercontent.com/60427448/169865093-5db61afd-034f-4ed3-aa39-efac2513f415.png)

Expected behavior: No traceback 

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
fixed by: https://github.com/odoo/odoo/commit/9ddb9155d55f8889bd503773513b57cbb855eec1
