### ISSUE TITLE
You cannot update the translated value of field 'Arch Blob' 

### ISSUE THREAD

**Issue by mrmango** [odoo/odoo#9211]
When going into Project Issue and clicking on a new record. I go to the developers 

tool and manage views. I click edit on the main view for Issues. Under 

tag "< h1 >" I go to insert, insert inside and select an existing field. I get the error, no matter what field I choose of.

**Comment by bistaray** [comment]
I can't reproduce this.

I was able to insert the field 'create_date' inside that tag on today's build.

http://109409-9-0-b4869a.runbot8.odoo.com/

![Screenshot](http://i.imgur.com/nrkMiIv.png)

**Comment by mrmango** [comment]
Installed 9.0.20151027 over 9.0.20151002, confirmed fixed.

Thanks.
