### ISSUE TITLE
[15.0] Configure your document layout - Translation.

### ISSUE THREAD

**Issue by kimasplund** [odoo/odoo#92147]
Impacted versions: 15c

Steps to reproduce: open "Configure your document layout" under "general settings"

The Translation element is missing from "Company Tagline" and "Company Details" but present in "Footer".
Would be really great to have the translation option there on those fields.

**Comment by niyasraphy** [comment]
hi @kimasplund ,
this cannot be updated in the stable releases in the core, if you need it in 15 or in 16, you can achieve it adding translate=True for the field from a custom module.

in the master branch(ie in 17), this has been added by this commit:  https://github.com/odoo/odoo/commit/40affecb62ef217c87f4ad477ba51c13ff01dbf7

feel free to close the ticket.
thanks
