### ISSUE TITLE
[9.0] website_slides not installable with demo data (nighly deb package)

### ISSUE THREAD

**Issue by mgrohmann** [odoo/odoo#9218]
it seems the debian packages from https://nightly.odoo.com/9.0/nightly/deb/
are missing the keynote.pdf which is needed for the website_slides demo data.

```
...
ParseError: "File not found: website_slides/static/src/img/keynote.pdf" while parsing /usr/lib/python2.7/dist-packages/openerp/addons/website_slides/data/website_slides_demo.xml:121, near
<record id="slide_10" model="slide.slide">
            <field name="name">Odoo Roadmap &amp; Strategy - Fabien Pinckaers</field>
            <field name="datas" type="base64" file="website_slides/static/src/img/keynote.pdf"/>
            <field name="image" type="base64" file="website_slides/static/src/img/keynote.png"/>
            <field name="slide_type">presentation</field>
            <field name="channel_id" ref="channel_partial"/>
            <field name="category_id" ref="category_2"/>
            <field name="website_published" eval="True"/>
            <field name="likes">13</field>
            <field name="slide_views">6399</field>
            <field name="index_content">1. Odoo Roadmap &amp; Strategy Fabien Pinckaers, Founder
...
```

**Comment by mgrohmann** [comment]
same with hr_recruitment module on which the website_sides module depends on
missing files in deb package:
* hr_recruitment_demo_jones_cv.pdf
* hr_recruitment_demo_williams_cv.doc

do they get filtered out by the packging process?

**Comment by mlaitinen** [comment]
For me it seems like all non-image files are filtered away from the `static/src/img` directory.

**Comment by mlaitinen** [comment]
I tried to find the packaging script to no avail. Folks at Odoo: could you please show us where the packaging script is found?

**Comment by sle-odoo** [comment]
fixed by 7fcc79da21a8ae580ce6472e9e105012caf76e28

@mlaitinen https://github.com/odoo/odoo/blob/9.0/setup/package.py

**Comment by mlaitinen** [comment]
Wow! The file I was looking for was in the _root_ directory of the repository and I couldn't find it :laughing: 
Thank you @sle-odoo!

**Comment by KurtHaselwimmer** [comment]
So this issue was closed around the 25th of October - was anything changed then - I can see no change in the file package.py and the nightly deb builds still have exactly the same problem.

**Comment by sle-odoo** [comment]
this issue was closed in november so maybe you're stuck with an old package due to a change in the version names. Try to execute 

        sudo apt-get install odoo=9.0c*

**Comment by KurtHaselwimmer** [comment]
Simon,

we have been using a  dockerfile build based upon the official odoo dockerfile here:- https://github.com/odoo/docker. Is this now out of date, now that the version numbers appear to have changed ?

Does version 9.0c include the changes to the setup/package.py file that prevents the installation errors with the website_slides module - if so then where is the source for v 9.0c - github odoo/odoo does not show any changes to this file in the last 2 months and no branch called 9.0c.

regards

Kurt


Dr. Kurt Haselwimmer

-------------------------------------------------------------
Willow House, 100 High Street, Somersham, PE28 3EH
Tel +44 (0) 845 899 0256  Fax +44 (0) 845 899 0259
-------------------------------------------------------------

**Comment by sle-odoo** [comment]
I linked to the revision fixing the issue, it's https://github.com/odoo/odoo/commit/7fcc79da21a8ae580ce6472e9e105012caf76e28

I linked package.py because someone asked for it:

> I tried to find the packaging script to no avail. Folks at Odoo: could you please show us where the packaging script is found?

The dockerfile is using a debian package that does not contain the fix. We will upgrade it very soon, @aab-odoo is working on it right now.

Regards

**Comment by KurtHaselwimmer** [comment]
Simon,

thank you for the information - this has been testing us for the last few days. If there is a particular issue that aab is working on for the fix it would be helpful so that I can watch it and then proceed only when it is dealt with.


regards

Kurt
