### ISSUE TITLE
[15] stock: manually created wave transfers are not displayed

### ISSUE THREAD

**Issue by poonam2606** [odoo/odoo#92221]
Impacted versions: 15.0

Steps to reproduce: Go to Inventory > Operation > Wave Transfer and create a new record

Current behavior:
New Wave Transfer is not displayed here
![Screenshot (75)](https://user-images.githubusercontent.com/60427448/170134320-e7a2d598-8773-419f-a0d8-9d18e3f0d4b9.png)
![Screenshot from 2022-05-25 02-48-17](https://user-images.githubusercontent.com/60427448/170134341-b087cccf-b30d-4d72-8791-0601a8477939.png)

Expected behavior: Able to View Wave Transfer or Create button should not be shown

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
hi @poonam2606 ,
this has been resolved by removing the create permission from this menu/view.
feel free to close the issue.
thanks
