### ISSUE TITLE
9.0 Missing field to enter Sequence on Suppliers line for Product

### ISSUE THREAD

**Issue by stephaniemillet** [odoo/odoo#9223]
When you definie a product with routes = buy &  MTO 
And you have several vendors for the product

you need to enter the Vendor / sequence, 
to define wich vendor will be select when generation of Purchase request after sales order confirmation

![image](https://cloud.githubusercontent.com/assets/12233420/10695754/b8958a26-79a5-11e5-8f6e-2373e9595fe5.png)

**Comment by twinslady1612** [comment]
It still have the field sequence but invisible. You can try to drag and drop on the list view, the sequence will be change automatically.

**Comment by stephaniemillet** [comment]
no, seller_ids/sequence is always = 1. so you can't define a sequence correctly. we need to have access to this field

**Comment by klp-odoo** [comment]
Dear Stéphanie,

As already advised by twinslady612, you can customize the following form view as per attached image (use inherited views). Tested, it works.

Regards,
![sequence on supplier - supplierinformation](https://cloud.githubusercontent.com/assets/8912592/11272424/124eaf20-8ecd-11e5-9da5-556111207151.PNG)

**Comment by Yenthe666** [comment]
As suggested by @klp-odoo you can edit the view and add it in yourself.
