### ISSUE TITLE
[7.0] Error when opening a delivery order

### ISSUE THREAD

**Issue by miguelparaiso** [odoo/odoo#9224]
### [7.0] Error when opening a delivery order

**Impacted versions:**
7.0 on Ubuntu 14.04 and on Windows 10

**Steps to reproduce:**
Go to 'Sales' -> 'Sale Orders' -> Use a field in _Group by_ filter that `stock.picking.out` model does not have, like _'Order Date'_ -> Open a filtered Sale order -> Click in _'View Delivery Order'_ button.

**Current behavior:**
The fields of the sale order's group by filter are being inherited in `stock.picking.out`. If these fields aren't in the _Delivery Order_ model, when you try to show up the delivery order, you get this error message:

> AssertionError: Fields in 'group by' must be regular database-persisted fields (no function or related fields), or function fields with store=True

**Expected behavior:**
The fields of the sale order's group by filter does not have to be inherited in `stock.picking.out` model.

**Comment by rvalyi** [comment]
related to an unsupported Odoo version. Can it be closed?
cc @Yenthe666

**Comment by Yenthe666** [comment]
Hi @miguelparaiso,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
@rvalyi thanks a lot for the ping!

Regards,
Yenthe
