### ISSUE TITLE
Validation error when trying to validate a order for delivery

### ISSUE THREAD

**Issue by peterwwjd** [odoo/odoo#9225]
Not able to do any delivery orders due to validate error. Very frustrating!

![fireshot capture 28 - sales orders _ so016 _ wh_out_00006 - _ - https___fribergfineart-live-test o 1](https://cloud.githubusercontent.com/assets/15278116/10710667/12c819d4-7a21-11e5-8163-a9294617e19e.png)
![capture _04png](https://cloud.githubusercontent.com/assets/15278116/10710668/1fb6ffca-7a21-11e5-922b-cace8ea0237b.PNG)

**Comment by rim-odoo** [comment]
This is due to a bad configuration of your FedEx test account.
