### ISSUE TITLE
[9.0] website_quote - Accepting online quotation does nothing.

### ISSUE THREAD

**Issue by jaredkipe** [odoo/odoo#9226]
**Accepting online quotation does nothing (404 in jsonrpc)**

Impacted versions:

 - 9.0
 - 9.0 Enterprise

Steps to reproduce:

 1. Install CRM, Sales Management, Website Builder (and of course website_quote option)
 2. Create a quote and click the 'View Online Quotation'
 3. Click 'Accept Order' button and fill out the modal
 4. Click 'Sign & Confirm' button

Current behavior:

 - Form will hang
 - XHR response will be a 200 with 404 message body
 - Server error

```
2015-10-24 17:30:46,539 2879 ERROR dev1 openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/share/odoo9/openerp/http.py", line 599, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/share/odoo9/openerp/addons/base/ir/ir_http.py", line 154, in _dispatch
    rule, arguments = self._find_handler(return_rule=True)
  File "/share/odoo9/openerp/addons/base/ir/ir_http.py", line 65, in _find_handler
    return self.routing_map().bind_to_environ(request.httprequest.environ).match(return_rule=return_rule)
  File "/usr/lib/python2.7/dist-packages/werkzeug/routing.py", line 1433, in match
    raise NotFound()
NotFound: 404: Not Found
2015-10-24 17:30:46,542 2879 INFO dev1 werkzeug: 127.0.0.1 - - [24/Oct/2015 17:30:46] "POST /quote/accept HTTP/1.0" 200 -
```

Expected behavior:

 - quotation should be accepted (sales order moved to confirmed)

**Comment by jaredkipe** [comment]
I got curious as to if this was still broken, and it is.
FWIW, this was caused by 7636b510a2cfc48bd0281374596f3c7caf1f7edf

The route was changed from json to http without changing the view.

**Comment by blaggacao** [comment]
Can you point to the line/lines in 7636b51?

**Comment by jaredkipe** [comment]
https://github.com/odoo/odoo/commit/7636b510a2cfc48bd0281374596f3c7caf1f7edf?diff=unified#diff-4503719f4bddd6fb81e3e0a6109fd069R80
The change to the route that I basically reversed in #9227 without knowing it.

https://github.com/odoo/odoo/commit/7636b510a2cfc48bd0281374596f3c7caf1f7edf?diff=unified#diff-bb263506b85e875743bfd2ba6e8b56ffR232
The affected view that should probably loose its json classes if it is to remain an http route.

**Comment by blaggacao** [comment]
@KangOl is the proposed fix a good strategy?

**Comment by blaggacao** [comment]
Thanks Nicolas! Greate to percieve, that a good issue preparation really can make a difference :+1:

**Comment by jaredkipe** [comment]
And its broken again. Now you get the message that it is confirmed on the website side, but the signature doesn't go onto the sales-order, and the sales-order does NOT become confirmed.

**Comment by nim-odoo** [comment]
@jaredkipe : it is working fine. The SO needs to be in state 'sent' to be confirmed through the online quote. This is due to commit 486cd33091b23924a73dd5bc0dbaee59bb10d85d However I agree that the confirmation message should not display.
