### ISSUE TITLE
[9.0] mass mailing to mailing list doesn't create e-mail messages

### ISSUE THREAD

**Issue by i4knowledge** [odoo/odoo#9230]
When I'm sending a mass mailing to a mailing list, the e-mail messages are not created for the e-mail recipients in de mailing list. Deliverid shows 0/0. Issue in Odoo Community, Odoo Enterprise, Odoo Online.
Test mailing works just fine.

**Comment by i4knowledge** [comment]
Test on runbot same issue

**Comment by tde-banana-odoo** [comment]
Should be fixed at https://github.com/odoo/odoo/commit/e1b610b7054c77b0d0030b984828a255202b9f62 .
