### ISSUE TITLE
Environments.todo tries to recompute records with closed cursor

### ISSUE THREAD

**Issue by guewen** [odoo/odoo#9236]
**Environments.todo tries to recompute records with closed cursor**

Impacted versions:
- 8.0+

Description of the issue

A global `todo` dictionary is shared among the [environments of a request](https://github.com/odoo/odoo/blob/8.0/openerp/api.py#L941) for recomputations. This todo contains records that have to be recomputed, records which are themselves attached to their own environment.

Here is a scenario where we have an error (ref: https://github.com/OCA/connector/pull/131, https://github.com/OCA/connector/pull/132):
1. several environments in a request, we handle the job states and the job's execution in different transactions
2.  the environment that execute the job adds recordsets in this global todo
3.  the execution of the job encounters a `psycopg2.OperationalError`, it is rollbacked and 
4.  we catch this error and open a new environment to update the state of the job to pending, it will be retried later

Result: The recordsets in `Environments.todo` are attached to an Environment with a closed cursor. Still, at a point it will try to recompute them and we'll get an `Unable to use a closed cursor.` error.

ping @rco-odoo

**Comment by Yenthe666** [comment]
Hi @guewen,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
