### ISSUE TITLE
How to chage parameter when create lead through incoming mail

### ISSUE THREAD

**Issue by atuljain** [odoo/odoo#924]
Hello I would like create lead through incoming mail and i am able to create new lead through incoming mail 
but when i tried to use data through mail like customer name or customer phone number through incoming mail i am not able to do this then i  created there server action with python code 
My code is this 
def parse_description(description):
    fields=['name','phone']
    _dict={}
    description=description.lower()
    for line in description.split('\n'):
        for field in fields:
            if field in line:
                split_line=line.split(':')
                if len(split_line)>1:
                    _dict[field]=split_line[1]
    return _dict
lead=self.browse(cr,uid,context['active_id'],context=context)
description=lead['description']
_dict=parse_description(description)
self.write(cr,uid,context['active_id'],{
                        'partner_name':_dict.get('name'),
                        'contact_name':_dict.get('name'),
                        'phone':_dict.get(u'phone'),
                        'mobile':_dict.get(u'phone')})

but not able to create lead and got the exception 

2014-07-01 13:39:40,188 4992 INFO v8_demo openerp.addons.mail.mail_thread: Routing mail from Atul Jain <jain.atul43@gmail.com> to jain.atul10@hotmail.com with Message-Id <CAG=2G76_SRthL3ybGGyx2Lai5H=RMNxUOjRRR=+5-ODrcgtEZw@mail.gmail.com>: fallback to model:crm.lead, thread_id:False, custom_values:None, uid:1
2014-07-01 13:39:40,445 4992 ERROR v8_demo openerp.addons.fetchmail.fetchmail: Failed to fetch mail from imap server Gmail.
Traceback (most recent call last):
  File "/home/atul/openerp-8/openerp/addons/fetchmail/fetchmail.py", line 206, in fetch_mail
    action_pool.run(cr, uid, [server.action_id.id], {'active_id': res_id, 'active_ids':[res_id], 'active_model': context.get("thread_model", server.object_id.model)})
  File "/home/atul/openerp-8/openerp/addons/base/ir/ir_actions.py", line 967, in run
    res = func(cr, uid, action, eval_context=eval_context, context=run_context)
  File "/home/atul/openerp-8/openerp/addons/base/ir/ir_actions.py", line 805, in run_action_code_multi
    eval(action.code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
  File "/home/atul/openerp-8/openerp/tools/safe_eval.py", line 254, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 14, in <module>
  File "", line 4, in parse_description
ValueError: "'bool' object has no attribute 'lower'" while evaluating
u"def parse_description(description):\n    fields=['name','phone']\n    _dict={}\n    description=description.lower()\n    for line in description.split('\\n'):\n        for field in fields:\n            if field in line:\n                split_line=line.split(':')\n                if len(split_line)>1:\n                    _dict[field]=split_line[1]\n    return _dict\nlead=self.browse(cr,uid,context['active_id'],context=context)\ndescription=lead['description']\n_dict=parse_description(description)\nself.write(cr,uid,context['active_id'],{\n                        'partner_name':_dict.get('name'),\n                        'contact_name':_dict.get('name'),\n                        'phone':_dict.get(u'phone'),\n                        'mobile':_dict.get(u'phone')})"

**Comment by bora89** [comment]
Did you figure out how to solve it?

**Comment by Yenthe666** [comment]
Hi @atuljain,

If you still face this issue please create a new topic on the official help forums (help.odoo.com) and I'm sure somebody can help you there!
The github tracker is only for issues in the official Odoo code, not custom development or questions.

Regards,
Yenthe
