### ISSUE TITLE
POS - rounding mismatch

### ISSUE THREAD

**Issue by mvercruysse** [odoo/odoo#9249]
**Impacted versions**
8.0

**Steps to reproduce**
1. Go to a runbot instance
2. Go to Settings > Technical> Database Structure > Decimal Accuracy
Set : 
- Product Price = 4
- Account = 2
3. Go to Settings > Configuration > Accounting
Set
Tax calculation rounding method = round per line
4. Modify the product Gold Membership with a sale price = 1.0425 (must be stockable)
5. Modify the product Silver Membership with a sale price = 4.4250 (must be stockable)
6. Open a POS Session
7. Select a customer ( Axelor for instance)  
a) Sell 14 units of Gold membership then validate with the cash journal (give exact amount)  
b) Sale (Refund) 14 units of Gold membership then validate with the cash journal (give exact amount)  
c) Sell 3 units of Silver membership then validate with the cash journal (give exact amount)  
d) Sell 3 units of Silver membership then validate with the cash journal (give exact amount)  

**Current behavior**
a) amount is =  16.79

b) amount is = -16.78 ==> The picking is not created on the pos order + Payment and total mismatch

c) amount is = 13.28

d) amoun is = -13.27 ==> The picking is not created on the pos order  + Payment and total mismatch

**Expected behavior**
The amount should be the same and the pickings should be created.

Regards,

**Comment by mvercruysse** [comment]
OP = 653034

**Comment by bistaray** [comment]
Picking's are not created for Service (non-material) products.  Memberships are service products.

**Comment by mvercruysse** [comment]
Well, i forgot to mention that the product should be stockable but the result is the same (amount and payment are different and the picking is not created)!

**Comment by mvercruysse** [comment]
I forgot to specify that the product should be stockable but the result 
is the same.
Mismatch between total of pos order and payment and no picking created.

> Ray Carnes <mailto:notifications@github.com>
> 26 octobre 2015 18:36
>
> Picking's are not created for Service (non-material) products. 
> Memberships are service products.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/odoo/odoo/issues/9249#issuecomment-151219573>.
>

-- 
Matthias Vercruysse
Odoo Project & Quality Manager
Email : mve@taktik.be
GSM : +32 474 56 14 91

*TAKTIK SA*
Avenue de Finlande, 8
1420 Braine l'Alleud
Tel : +32 2 333.58.40
http://www.taktik.be <http://www.taktik.be/>

**Comment by mvercruysse** [comment]
I forgot to specify that the product should be stockable but the result is the same.
Mismatch between total of pos order and payment and no picking created.

**Comment by nim-odoo** [comment]
Closed with https://github.com/odoo/odoo/commit/ea2c80cad018da6390ea9d116733de691907e1e4
