### ISSUE TITLE
[9.0] Traceback Error searching 'credit' or 'debit' fields on res.partner

### ISSUE THREAD

**Issue by bistaray** [odoo/odoo#9253]
1. Visit runbot and login to the latest release of Odoo 9.0 Community
2. Nagivate to Sales -> Sales -> Customers
3. Add an Advanced Filter:  Total Payable > 0

Expected:  Customers will be filtered

What Happens:  Traceback: TypeError: _debit_search() takes exactly 2 arguments (3 given)

Verified on 109390-9-0-b4869a from 10/26/2015

Field function being used is defined in account/models/partner.py as:

    debit = fields.Monetary(compute='_credit_debit_get', search=_debit_search)

_debit_search being used is defined in account/models/partner.py as:

    @api.multi
    def _debit_search(self, args):
        return self._asset_difference_search('payable', args)

_asset_difference_search is defined in account/models/partner.py as:

    @api.multi
    def _asset_difference_search(self, type, args):

**Comment by mart-e** [comment]
Hello,

The analysis was correct, fixed at 9d6b9cc
Thanks
