### ISSUE TITLE
[8.0] [9.0] deb package should depend on python-support

### ISSUE THREAD

**Issue by atrueba** [odoo/odoo#9270]
Hi,

Installation on a clean Debian stretch system fails at postinst:

/var/lib/dpkg/info/odoo.postinst: 28: /var/lib/dpkg/info/odoo.postinst: update-python-modules: not found

update-python-modules is included in python-support package, thus this should be a dependency for Odoo.

**Comment by lerrigatto** [comment]
I had the same issue and apt-get install python-support solve it. Thank you so much.

**Comment by intero-chz** [comment]
https://bugs.launchpad.net/ubuntu/+source/python-support/+bug/1577172 fyi

**Comment by gustavocel** [comment]
I could install python-support in Ubuntu 16.04 using the “llxdev” team package available at:
https://launchpad.net/~llxdev/+archive/ubuntu/xenial/
copying the following line and adding it to my system's software sources:
`deb http://ppa.launchpad.net/llxdev/xenial/ubuntu xenial main`
After that, odoo was installed successfully.
Before reinstalling odoo, I had to (re)create the directory /var/lib/odoo ("sudo" not necessary if you are logged as root):
`sudo mkdir /var/lib/odoo`
`sudo chown odoo:odoo /var/lib/odoo`
I hope it helps...

**Comment by sle-odoo** [comment]
fixed at rev efe37469e9d6741403829e9d64fd67a2d8bb2e66

Thanks
