### ISSUE TITLE
[14.0] Project: wrong description compared to features

### ISSUE THREAD

**Issue by sang250399** [odoo/odoo#92734]
![Screenshot from 2022-06-02 14-29-40](https://user-images.githubusercontent.com/85299950/171577678-b2efeb4b-bfba-4ef7-9c45-3b182e909b4e.png)

Current behavior: **Invited portal and all internal users:** `employees may see everything. Portal users may see project and tasks followed by them or by someone of their company.` In fact, those who use the portal with their company but are not followed will not be able to see this project and task.

Support ticket number submitted via odoo.com/help (optional):

**Comment by MissingNoShiny** [comment]
Hello, thank you for your report. A fix in on the way. :slightly_smiling_face:

**Comment by tranngocson1996** [comment]
Done @sang250399 
Thank bro @MissingNoShiny
