### ISSUE TITLE
oe_edit_only not available in form subtree

### ISSUE THREAD

**Issue by blaggacao** [odoo/odoo#9273]
From: https://bugs.launchpad.net/openerp-web/+bug/1311199

Hy,

I'm trying to hide some buttons when I'm not in edit mode. I set a button in the header and use the class oe_edit_only :

<button name="refresh_record" string="Refresh" type="object" class="oe_edit_only"/>

In the header it works perfectly. Then in the object I have some lines (one2many) and in each line I have a button with the same syntax. Unfortunately, the oe_edit_only class is not transmitted to the tree. The button in subtree still available whatever the state of the form. I made an inspect in HTML mode and no class is specified in the subtree button yet I have a class="oe_edit_only" in the xml view definition

I precise that when I change the HTML part directly in my brower and when I set the class class="oe_link oe_edit_only" on my button in subtree, it worked. So the problem seems to come from the fact that the class is not passed to the subtree.

@flotho

**Comment by blaggacao** [comment]
I confirm, this still is present.

**Comment by blaggacao** [comment]
as to changing in html:

```
.openerp .oe_form_readonly .oe_edit_only, .openerp .oe_form_readonly .oe_form_field:empty {
  display: none !important;
}
```

It seems to me, that by default, the logic is that the application is computed...

**Comment by blaggacao** [comment]
It seems that the whole `class` attribute is not rendered correctly...

**Comment by GoodERPJeff** [comment]
same issue on odoo10

**Comment by slneehazem** [comment]
Any solution for this problem plz ?

**Comment by rafi16jan** [comment]
@blaggacao why you close the issue

**Comment by blaggacao** [comment]
@rafi16jan this issue has, as a matter of fact, rotten. So there is little value in any investment to maintain it open. If I stumble over it again, I sure will open a new version of this issue.
