### ISSUE TITLE
[9.0][Online] [calendar] Creating Meetings doesn´t work from List and Form Views

### ISSUE THREAD

**Issue by schmidtwastl** [odoo/odoo#9274]
Reproduction is possible on an official Odoo Online Instance:
Calender -> List View or Form View -> CREATE -> Fill in: name + start date + 02:00hours -> Error: The following fields are invalid: start stop

However, it works for
- "All Day" Events
- "hourly" Events, when created directly from the calendar view

**Comment by oliverzgy** [comment]
Same issue found...

**Comment by Yenthe666** [comment]
Hi @schmidtwastl,

This issue is no longer present in the latest Odoo codebase.
If you still face this issue please update your local Odoo installation and it'll be fixed.

Regards,
Yenthe
