### ISSUE TITLE
[15] mrp: Traceback on changing unit of measure 

### ISSUE THREAD

**Issue by poonam2606** [odoo/odoo#92800]
Impacted versions: 15.0

Steps to reproduce: Scrap Orders > Select one and Edit  unit of measure 
![Screenshot (87)](https://user-images.githubusercontent.com/60427448/171659328-2df19921-0584-4c71-8298-8c7811bf69e3.png)

Current behavior:
![Screenshot (88)](https://user-images.githubusercontent.com/60427448/171659390-f1341408-8124-477a-970e-1b49eb6173ef.png)

Expected behavior: Able to Change unit of measure 

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
hi @poonam2606 ,
fixed in:  https://github.com/odoo/odoo/commit/7ce65004dc780695cd394d02cb0eec4a65e0df63

feel free to close the ticket as it is resolved :)
thanks
