### ISSUE TITLE
Magic numbers in assignment of list of tuples to `_RelationalMulti` (One2many & Many2many)

### ISSUE THREAD

**Issue by dyntaos** [odoo/odoo#92839]
Hello,

Odoo's code guidelines state that magic numbers should not be used, yet there are magic numbers for which I cannot find any documentation.

If you look for regex matches of the following expression you will see what I am referring to:
`_ids = \[\(\d`

For example:
`config.fiscal_position_ids = [(5, 0, 0)]`
or
`self.move_raw_ids = [(2, move.id) for move in self.move_raw_ids.filtered(lambda m: m.bom_line_id)]`

I tried to figure out where in the Odoo core it handles this list, but I have been unable to locate where this occurs since assignment cannot be overridden in Python.
Can anyone shed any light on either where this is handled or what these magic numbers mean?

Thanks!

**Comment by Feyensv** [comment]
If you want more details on the magic numbers in our documentation: https://www.odoo.com/documentation/15.0/developer/reference/backend/orm.html#odoo.fields.Command ;)

**Comment by Yenthe666** [comment]
Plus it might be so that in the next version you can use commands instead of those numbers too if I'm not mistaking. :)
