### ISSUE TITLE
[15.0] Product configurator unexpected behavior in sale order line

### ISSUE THREAD

**Issue by jlzhou** [odoo/odoo#92865]
Impacted versions:
15.0

Steps to reproduce:
Create new odoo db with demo data
Create new sale order
In 'Order Lines' tab, add a product: 'Customizable Desk', the Configure dialog will appear, click 'Confirm' button, the dialog closed and a new line was created.
Click the blank area in 'Product' column of the new line. The 'Edit Configuration' and 'External link' button will appear.
Click 'Edit Configuration' button, the 'Configure a product' dialog was shown, click 'Cancel' button or 'x' button in the top right of the dialog to close the dialog.

Current behavior:
The product of the order line was empty
<img width="1076" alt="Screen Shot 2022-06-03 at 17 31 23" src="https://user-images.githubusercontent.com/1243299/171828904-228a638f-d987-402e-87e6-6fb9b0024bb4.png">

Expected behavior:
No change in the order line

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):
opw-2871884

**Comment by jlzhou** [comment]
Can you help? @tdecaluwe

**Comment by tanghulu0608** [comment]
Hello

**Comment by vava-odoo** [comment]
Hello, I'm closing this issue since it was fixed by https://github.com/odoo/odoo/pull/93391
