### ISSUE TITLE
[8.0][BUG] A project user cannot close a task which has assigned

### ISSUE THREAD

**Issue by rafaelbn** [odoo/odoo#9286]
[8.0][BUG] A project user cannot close a task which has assigned

**Impacted versions:**

- 8.0

**Steps to reproduce**

- Login in runbot as Admin
- Go to sales – product and create a product with:
   - Name: service work for imac
   - with product type “Service”
   - go to tab procurements and activate checkbox option “Create task automatically”
   - Select the proyect “Research & development” (for example)
   - Save
- Create a sales order with:
   - Customer  Axelor (for example)
   - Add 2 order lines:
      - First with [A1090] iMac
      - Second with service work for imac
   - Confirm sales order
- Go to setting – users, create a user for example “projectuser@odoo.com” and give permissions only for Project- User, set a password for this user
- Go to Projects task and seach for task that contains text “imac” you will find a task with name SOxxx:services work for imac
- Edit the task and assign it to the user you have created
- Log out as admin
- Log in as the new user you created
- Go to project – task and search again for the same task, go inside the task
- change stage to done
- You will get this error
```
Sorry, you are not allowed to access this document. Only users with the following access level are currently allowed to do that:
- Sales/See Own Leads
- Accounting & Finance/Accountant
- Portal
- Warehouse/User
- Manufacturing/User

(Document model: sale.order.line)
```

**Current behavior**

- A project user cannot finish with stage done a task which has been assigned

**Expected behavior**

- Project user with a task assigned must be able to close his/her task

**Comment by rafaelbn** [comment]
cc @dreispr @pedrobaeza what do you think? bug or access right issue? Thanks

**Comment by rafaelbn** [comment]
cc @dreispt @pedrobaeza what do you think? bug or access right issue? Thanks

**Comment by pedrobaeza** [comment]
It's clearly a bug, and this is how to solve it: https://github.com/odoo/odoo/pull/9352

**Comment by dreispt** [comment]
Yes, I would expect the user to be able to close the task.
