### ISSUE TITLE
[8.0] Missing Partner for account entries in module stock_landed_costs

### ISSUE THREAD

**Issue by 3nodus** [odoo/odoo#9292]
On creating the account entries, the partner of landed costs is missing.

https://github.com/odoo/odoo/blob/8.0/addons/stock_landed_costs/stock_landed_costs.py#L204
https://github.com/odoo/odoo/blob/8.0/addons/stock_landed_costs/stock_landed_costs.py#L118

**Comment by Yenthe666** [comment]
Hi there,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
