### ISSUE TITLE
[WISH] Help retailers to know which marketplaces order relates to vendor

### ISSUE THREAD

**Issue by zeroheure** [odoo/odoo#92925]
This concern retailers and eCommerce. There is an increasing number of dedicated marketplaces for retailers or e-merchant to purchase goods from makers or small vendors. See for example Ankorstore.com, Faire.com, Orderchamp.com, ... On these marketplaces, one order is always dedicated to one vendor. But, these marketplaces works like a middleman between each vendor and buyers. Therefore, orders and bill always relates to marketplace instead of vendors. 

In the same way, a purchase from a big vendor often need an email or a phone call to a vendor employee.

In both case, we need an additional many2many field to link orders to the vendor or vendor employee.

**Comment by Yenthe666** [comment]
I guess that would be a typical custom code job :)

**Comment by Yenthe666** [comment]
Honestly, Odoo doesn't even look at these issues anymore let alone that they add requested features. The counter of the issues is the biggest proof :) You could log an official ticket as a feedback but no promises (the odds are still not in your favour).

**Comment by zeroheure** [comment]
As you know, usability is in details. It's a pity that Odoo don't take those wishes in account.
I close this bug.
