### ISSUE TITLE
[8.0] without-demo not working

### ISSUE THREAD

**Issue by JulioSerna** [odoo/odoo#9293]
Impacted Verions

* 8.0

Steps to Reproduce

*  To Create db without demo
![odoo](https://cloud.githubusercontent.com/assets/7595505/10806645/bac5c540-7d9c-11e5-8fc9-b23511dedb9d.png)

* To install module with command-line
![desctop screenshot](https://cloud.githubusercontent.com/assets/7595505/10806691/401bd586-7d9d-11e5-9f6d-8f523ec2dfd3.png)

Current Behavior
* account module try to install data/demo and get this error,
```  
File "/.repo_requirements/odoo/openerp/modules/loading.py", line 179, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='demo')
  File "/.repo_requirements/odoo/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/.repo_requirements/odoo/openerp/tools/convert.py", line 901, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/.repo_requirements/odoo/openerp/tools/convert.py", line 987, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/.repo_requirements/odoo/openerp/tools/convert.py", line 853, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/.repo_requirements/odoo/openerp/tools/convert.py", line 763, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/.repo_requirements/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/.repo_requirements/odoo/openerp/addons/base/ir/ir_model.py", line 1052, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/.repo_requirements/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/.repo_requirements/odoo/addons/auth_signup/res_users.py", line 301, in create
    user_id = super(res_users, self).create(cr, uid, values, context=context)
  File "/.repo_requirements/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/.repo_requirements/odoo/addons/mail/res_users.py", line 75, in create
    raise openerp.exceptions.RedirectWarning(msg, action_id, _('Go to the configuration panel'))
ParseError: "You cannot create a new user from here.
 To create new user please go to configuration panel.
76
Go to the configuration panel" while parsing /.repo_requirements/odoo/addons/account/demo/account_demo.xml:159, near
<record id="base.user_demo" model="res.users">
            <field name="groups_id" eval="[(4,ref('account.group_account_user'))]"/>
        </record>
```

I think if the DB is set with ```demo=False``` the modules to install must not try to install data/demo,

And here there is another issue because even if I set the config file of odoo with ```without-demo=all```
![withoutdemo](https://cloud.githubusercontent.com/assets/7595505/10806953/2778de9a-7da0-11e5-99f9-800b560881a3.png)
account module try to install data/demo

The only way to not install data/demo is when added the without-demo = all into command-line like this,
![without_demo_all](https://cloud.githubusercontent.com/assets/7595505/10807054/ec66d338-7da0-11e5-8d46-eeaef3a079c8.png)

Expected Behavior
* If the db is without demo the modules  should not install demo or/and without-demo should be processed from config file as well

**Comment by beledouxdenis** [comment]
Dear Julio, 

To install a module without demo data, without-demo must be set to either `1` or `all`, or a comma-separated list of module.

Setting `False` to the paramter `without-demo` will install the demo data. This is kind of a double negation: "Without without-demo" = "with demo".

Regards,

**Comment by JulioSerna** [comment]
Hello @beledouxdenis 

When you say,
"To install a module without demo data, without-demo must be set to either 1 or all, or a comma-separated list of module."

That is exactly what I am trying to do
in the description of issue I commented

And here there is another issue because even if I set the config file of odoo with ```without-demo=all```
![withoutdemo](https://cloud.githubusercontent.com/assets/7595505/10806953/2778de9a-7da0-11e5-99f9-800b560881a3.png)
account module try to install data/demo
