### ISSUE TITLE
l10n_be_reports>account_financial_html_report_data.xml: Error in definition of BE_40_41,BE_40,BE_41, BE_42_48, BE_42, BE_48

### ISSUE THREAD

**Issue by Imagizer** [odoo/odoo#92957]
Impacted versions: V14

Steps to reproduce:
accounting > reporting > Belgium > Bilan
Current behavior:
Shows 40/41 as "Créances à un an au plus" (= 1 year or more)
Shows 42/48 as "Dettes à un an au plus" (= 1 year or more)
Also the naming of the record id's hold these mistakes: "account_financial_report_be_dettes_un_an_au_plus0", "account_financial_report_be_dettes_plus_dun_an_dans_lannee0", etc
Expected behavior:
Should show 40/41 as "Créances à moins d'un an" ( = less then 1 year)
Should show 42/48 as "Créances à moins d'un an" ( = less then 1 year)
Naming should be corrected.

source: https://handleidingboekhoudregels.fenb.be/balans/ (flemish government)

Video/Screenshot link (optional):
https://ibb.co/mCsQ43X
https://ibb.co/Mpy6cWp
Support ticket number submitted via odoo.com/help (optional):

**Comment by Yenthe666** [comment]
@oco-odoo

**Comment by oco-odoo** [comment]
@Imagizer I'm afraid you're wrong :p 

"un an au plus" isn't "un an *ou* plus". "au" means "at", so "un an au plus" is "one year at most"
