### ISSUE TITLE
[9.0] Creating Contact, Odoo always created attachment for image

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#9298]
Hello Odoo,

When I investigated Odoo 9, I found that every time we create the customer, you will create the attachment for image, whenever I don't set up anything. I think this is useless and a flawed.
As we will have lot of useless attachment and we will need more storage for useless things.

The behavior should be when we create customer without any image, we don't need to create attachment for the image, instead we have the static image to display an empty image,

Thank You.

**Comment by Yenthe666** [comment]
Hi @falinwa,

The displaying and image and using it is expected and wanted behaviour by Odoo.
There is no different image uploaded for every single record.

Regards,
Yenthe
