### ISSUE TITLE
Background color of Elements not working the same way in Opera, Firefox, Safari, Chrome

### ISSUE THREAD

**Issue by lisandi** [odoo/odoo#9299]
In Safari we have the default blue background.
In Firefox the same background is white with a bit of beige.
In Opera it shows the whole site without any CSS.
In Chrome it is blue.

We tested also with pink in Safari than Firefox shows blue!

**Comment by pedrobaeza** [comment]
Can you specify which color are you talking about? Where do you choose that color? Is this still reproducible in latest version?

**Comment by pedrobaeza** [comment]
Closing as no answer. Feel free to open a new one with more information if the problem persists.
