### ISSUE TITLE
website_blog: change_background doesn't work occasionally

### ISSUE THREAD

**Issue by yelizariev** [odoo/odoo#930]
Some time new background image, which I set via "Change cover" button don't saved.

I think it happens because request /blogpost/change_background is not finished when website.reload() is called.

One can repeat this at runbot
* On chrome browser dev tools create break point at the end of save function at website_blog.editor.js
* edit blog post background image and click save
* on network tab check "preserve log" and clear current log
* resume script execution
* you will see status "canceled" on request /blogpost/change_background . Some time it reach server (and background is saved) and some time it doesn't.

Take a look at source:

save function in website_blog.editor.js

        save : function() {
            var res = this._super(); /* save fuction from website.editor.js is called here */
            if ($('.cover').length) {
                openerp.jsonRpc("/blogpost/change_background", 'call', {
                    'post_id' : $('#blog_post_name').attr('data-oe-id'),
                    'image' : $('.cover').css('background-image').replace(/url\(|\)|"|'/g,''),
                });
            }
            return res;
        },

tail of save function in website.editor.js

     return $.when.apply(null, defs).then(function () {
                website.reload();
            },
     ...

**Comment by rafaelbn** [comment]
cc @pedrobaeza @antespi @Yajo @sergio-incaser @carlos-incaser

**Comment by rafaelbn** [comment]
@yelizariev it's much more effective if you make a PR to Odoo fixing it.
Also you can make a PR to https://github.com/OCA/OCB fixing the problem and have it solve it
:+1:

**Comment by Gorash** [comment]
Fixed https://github.com/odoo/odoo/commit/ae175d1574ee61f1b3cd99afad29d67a0795d323
