### ISSUE TITLE
Not possible to press save in website builder after changing the background color

### ISSUE THREAD

**Issue by lisandi** [odoo/odoo#9300]
The save button shows up as not active after changing the background color or inserting an image. It is only possible to save if changing also something in the text - all browsers we have here the same!

**Comment by Yenthe666** [comment]
Hi @lisandi;

I can no longer reproduce this issue. I've opened the website, changed the background color from an item and saved this right away, without any other changes:
![image](https://cloud.githubusercontent.com/assets/6352350/15494943/82790a54-218d-11e6-9f04-a28452a97d98.png)

Don't hesitate to respond here if the problem still persist or if I should've missed something.

Regards,
Yenthe
