### ISSUE TITLE
[8.0][BUG] A Manufacturing Order is planified in the past

### ISSUE THREAD

**Issue by rafaelbn** [odoo/odoo#9306]
[8.0][BUG] A Manufacturing Order is planified in the past

**Impacted versions:**

- 8.0

**Steps to reproduce**

- Go to settings – configuration manufacturing and enable option “Manage routings and work orders”
- Go to sales – Products, search product “PC Assemble SC234”
- Go to tab procurement and select “manufacturer” and select make to order in “Supply chain information”
- Go to tab sales and fill field “manufacturing lead time” in 30 days
- Go to smartbutton “Bill of materials” and confirm that you have only 1 BoM is you have more, delete them, leave only one.
- Save
- Goto sales – sales order and create a sale order
- Select Customer Axelor (for example)
- Add a sale order line with the product “PC Assemble SC234” that we have edited
- Save and confirm
- Go to manufacturing – Manufacturing orders
- Check the scheduled date of the MO created, you will check that the date is in the past and must be schedule in the future.

**Current behavior**

- The scheduled manufacturer order is planned in the past

Expected behavior

- When confirming sale order Odoo must notice to the user that sale order cannot be confirmed because is cannot be planned.

**Comment by nim-odoo** [comment]
Hello,
This looks more like a configuration error. In the product configuration, the Customer Lead Time should be larger than the Manufacturing Lead Time.
By the way, we cannot prevent the confirmation of the SO in this case for a stable release: this might break the business flow of some users.

**Comment by rafaelbn** [comment]
cc @pedrobaeza @anajuaristi FYI

**Comment by anajuaristi** [comment]
It's not a bug. 
It all depends on the date you set on sale order line. 
If it's a product that needs 30 days lead time to be manufactured and your sale line lead time is 7 days (by default) having the product make_to_order... the calculated MO date to be launched will be on the past. 

It's right and expected behavior.

**Comment by rafaelbn** [comment]
cc @JavierIniesta @JMODaERP

**Comment by rafaelbn** [comment]
@anajuaristi is for you expected that your ERP create a Manufacturing order planified in the past when is imposible to get that schedule? I don't think the same. Related https://github.com/odoo/odoo/issues/9454
