### ISSUE TITLE
Required many2many_tags field in one2many relationship

### ISSUE THREAD

**Issue by PCatinean** [odoo/odoo#9308]
Whenever you have a required many2many field with widget "many2many_tags" inside a one2many when clicking save it complains that the field must not be empty

This only happens when the line where the m2m field is located is selected

Easy way to reproduce is to login on runbot, go to product templates and add via debug menu required="True" on value_ids fields from the attribute_line_ids then select a line with value in it and try to save

Happens in V8 did not check in V9

**Comment by Yenthe666** [comment]
Hi @PCatinean,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by tpa-odoo** [comment]
Hello @Yenthe666 ,

Can you please reopen this as this happens in v10E also.

To reproduce that just make tax required and try to edit any existing invoice you will face that.

**Comment by Yenthe666** [comment]
@tpa-odoo could you please make a new bug report with a big more info/context?
