### ISSUE TITLE
Bad stock valuation

### ISSUE THREAD

**Issue by zbik2607** [odoo/odoo#9315]
After last upgrade v8 from nightly i get stock valuation problem. 

Before upgrade view stock_history - PhpPgAdmin

![stock_history_old](https://cloud.githubusercontent.com/assets/8094437/10825752/c01eb7ca-7e66-11e5-9499-309be3d2d6de.png)

TOTAL STOCK VALUE: 0

After upgrade the same view  - PhpPgAdmin

![stock_history_new](https://cloud.githubusercontent.com/assets/8094437/10825783/d964263e-7e66-11e5-8fff-dbd259743d51.png)

TOTAL STOCK VALUE: -28.74

Line 3 in new view is not grouped and consumed by query ... SELECT MIN(id) as id ...

This is a **cost rounding problem**.  Double precision type is not grouped. In query

**quant.cost as price_unit_on_quant**

should be replaced by

**quant.cost::numeric AS price_unit_on_quant**

**Comment by mrzingo** [comment]
I have the same issue.

**Comment by mrzingo** [comment]
You can check this
https://github.com/numerigraphe/odoo/commit/d7f1fdfec9894b2081b6109bf2fca54145739511

**Comment by Yenthe666** [comment]
Hi @zbik2607,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
