### ISSUE TITLE
Issue with crm.team in multicompany environment

### ISSUE THREAD

**Issue by AntoineSadzot** [odoo/odoo#93168]
Impacted versions: 
14.0

Steps to reproduce:
In multicompany environment, create a single sales team linked to one company.
Then, as administrator, with the other company set as active, create a Sales order.
By default, the selected team is the one of the other company. Triggering a multicompany issue when trying to save the order. (see video)

Current behavior:
The issue relies in this line of code : https://github.com/odoo/odoo/blob/af5588c0b2cd94e5c76332ee24e24c5c6a708b44/addons/sales_team/models/crm_team.py#L32
If no crm.team has been selected, odoo returns the first one it finds, no matter the company

Expected behavior:
Add a domain to search for crm.team with the same company as the sale.order

Video/Screenshot link (optional):
https://watch.screencastify.com/v/sUld1MjGh6n22eCH58y5

Support ticket number submitted via odoo.com/help (optional):

**Comment by manishkumarbohra** [comment]
Hello @Feyensv 

This same issue in odoo 15 as well.

**Comment by manishkumarbohra** [comment]
Hello @Feyensv , 

This same issue in odoo 15 as well.

**Comment by mart-e** [comment]
Hello,

Sorry but the issue in your video is that there is no sale team for the second company. If you create one, it will be properly selected and you won't get an issue.
Best,
