### ISSUE TITLE
If API method with an optional parameter is invoked without that parameter specified, then Odoo subtitutes context in that parameter

### ISSUE THREAD

**Issue by tortabevonas** [odoo/odoo#9316]
Example:

```
    @api.one
    @api.returns("res.users")
    def create_pg_user(self, context={}, password="pass"):
          ...
```

If I create a button to call it, then the value of variable `password` is the current context, which's a dict of course.

**Comment by pedrobaeza** [comment]
This is because the compatibility layer between old and new API, and its a trade-off we have to pay for having that compatibility. As starting with v10, the old API is removed, we don't have anymore this problem, so I'm closing this issue.
