### ISSUE TITLE
[8.0][BUG] Sequence increases on pressing any button in module stock_landed_costs

### ISSUE THREAD

**Issue by 3nodus** [odoo/odoo#9318]
Impacted Versions
- 8.0

Steps to Reproduce
- Create a landed cost
  select a jorunal 
  press the button "compute" or "save"

Current Behavior
- The sequence increases 
  Working on current document:
  -->LC/2015/0024
  
  Clicking on button 
  -->sequence increases to LC/2015/0025

@hbto : It is a problem related to the fact that name field is readonly in view and when
reaches create method it is passed as blank.

**Comment by Yenthe666** [comment]
Hi there,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
