### ISSUE TITLE
[9.0]Problem with report format if the company information is too long.

### ISSUE THREAD

**Issue by twinslady1612** [odoo/odoo#9324]
I've printed a delivery slip and  I faced the problem with report template, the company information overflows but for a shorter company information, it's ok. I think it should be flexible depended on the company information data.

I've also done some tests on other report, for ex Sale order, purchase order, ... It got the same problem.
### Overflow
![image](https://cloud.githubusercontent.com/assets/3737567/10841105/09cc5fc8-7f19-11e5-97a4-390c1f0a1e8e.png)

### Normal
![image](https://cloud.githubusercontent.com/assets/3737567/10841510/6836c3b6-7f1c-11e5-9089-051f17cb774a.png)

**Comment by SBollatti** [comment]
Similar issue I have
https://github.com/odoo/odoo/issues/8707

**Comment by sle-odoo** [comment]
Not much we can do, Wkhtmltopdf does not compute the header's height according to the content. You can tweak the value easily in the company settings > report configuration > paper format though.

Regards
