### ISSUE TITLE
Odoo editor's terms are not translatable

### ISSUE THREAD

**Issue by luisg123v** [odoo/odoo#93258]
Impacted versions:
- 15.0

Steps to reproduce:
- Install and switch to any language different from English
- Open a task
- Click edit
- Press `/` to open editor menu

Current behavior:
Menu items ("Header 1", "Bulleted list", etc) are shown in English. Besides, they're not translatable

Expected behavior:
Terms should be translated or at least translatable

I noticed such terms are [marked to be translatable](https://github.com/odoo/odoo/blob/4fd0511479430aa7fcf09b42919249f520e9b171/addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js#L1773), but they're not considered on the [translation template](https://github.com/odoo/odoo/blob/4fd0511479430aa7fcf09b42919249f520e9b171/addons/web_editor/i18n/web_editor.pot)

**Comment by mart-e** [comment]
@odoo/rd-framework-editor any specific reason the odoo-editor was referenced as lib? If you move it in `static/src` instead of `static/lib`, it should be translated just fine.

**Comment by dmo-odoo** [comment]
@mart-e Well, it used to be developped as an actual external library so this location used to make sense. When we moved the editor files to the core repository instead, it did not occur to us to change its location. I was not aware that the scan for translatable terms was localized to the src folder, or that the lib folder was excluded.

**Comment by Yenthe666** [comment]
Cool, I made an OPW for this as one of the isssues actually. Nice that it's solved, thanks guys ;)
