### ISSUE TITLE
odoo 0day bugs dangerous!

### ISSUE THREAD

**Issue by 123944890** [odoo/odoo#93265]
Impacted versions: 8.0~15.0

I have found an odoo module have  two  Very serious 0day BUGS，
attackers can use them to login your odoo as super user and delete your database.
No odoo account need for the attack!
Who needs penetration test and repair services,
can send me your certificate of authorization for penetration test and  service contract.
My email: 123944890@qq.com

**Comment by Feyensv** [comment]
--> https://www.odoo.com/security-report
