### ISSUE TITLE
[Project] Text of stages not visible fully

### ISSUE THREAD

**Issue by jni-odoo** [odoo/odoo#9329]
On the task form stages text not properly visible 

See here : https://drive.google.com/file/d/0B5j41T1Hqv1sR1o1ZGJIQ2xOMlE/view?usp=drivesdk

**Comment by Yenthe666** [comment]
Hi @jni-odoo,

This issue is no longer present in Odoo. Fixed example:
![image](https://cloud.githubusercontent.com/assets/6352350/17435131/f6d99296-5b0e-11e6-93b7-0ad60802d435.png)
