### ISSUE TITLE
In MRP the properties are not working , throws a traceback when setting property

### ISSUE THREAD

**Issue by jni-odoo** [odoo/odoo#9334]
When a product have 2 BOM's and we are identifying by their propeties , in the latest version the property field throws a traceback when set ..
See here  https://youtu.be/qPKM7Z0aH7Y

**Comment by odony** [comment]
@jco-odoo Could you please have a look?

**Comment by jco-odoo** [comment]
https://github.com/odoo/odoo/blob/8.0/addons/sale_mrp/sale_mrp.py#L100

The problem is that in the translation to new api, we might have forgotten there is no property_ids link on the move.  But you can search it back through the original procurement of that move as in v8.

**Comment by jco-odoo** [comment]
In v9, this seems to have been fixed. (not in master...)  @jni-odoo Could you test again with fresh 9?

**Comment by odony** [comment]
9.0 was forward-ported to master yesterday, so it might be fixed there too now.
