### ISSUE TITLE
Company Form view has two 'Overdue Payments" tabs..

### ISSUE THREAD

**Issue by jni-odoo** [odoo/odoo#9336]
On the company configuration tab user gets the tab "Overdue Payments" tab two times..

https://drive.google.com/file/d/0B5j41T1Hqv1sWTRlcVdiQS0tcFU/view?usp=drivesdk

**Comment by Yenthe666** [comment]
Hi @jni-odoo,

Thanks a lot for the bug report.
This issue is solved in the meanwhile:
![image](https://user-images.githubusercontent.com/6352350/37723279-4a797bf8-2d2e-11e8-847c-b543e1e0d9b8.png)

Regards,
Yenthe
