### ISSUE TITLE
Portal messages not posted as author set by share url pid param

### ISSUE THREAD

**Issue by ruuter** [odoo/odoo#93377]
Impacted versions: 12.0, 13.0, 14.0

Steps to reproduce:

1. share a sale order with a third party (not a partner of the document).
![image](https://user-images.githubusercontent.com/3863648/173250298-54df5bbd-ccc4-4393-be30-95deb014b887.png)
2. open sale order in portal using the share link with pid and hash in messsage sent to third party
![image](https://user-images.githubusercontent.com/3863648/173250315-7038eb44-2351-443c-a57e-878b7de600d5.png)
3. post a message under the document in portal
![image](https://user-images.githubusercontent.com/3863648/173250743-e75e15bd-6736-436f-a0f8-7b678372b971.png)

Current behavior:
Message is posted as document main partner, not as a partner set by pid in share url

Expected behavior:
Message is authored by partner set by share url pid param

Possible fix is to replace this:
https://github.com/odoo/odoo/blob/6a6e5f92789e1c21dad2e4cff0fd0be5c68bd623/addons/portal/controllers/mail.py#L145
with this:
```python
if post_values.get('hash'):
    post_values.pop('token')
message = _message_post_helper(_hash=post_values.pop('hash'), **post_values)
```

**Comment by MissingNoShiny** [comment]
Thank you for your report, I am currently working on a fix. :slightly_smiling_face:
