### ISSUE TITLE
Manual accouting entries lose the partner name

### ISSUE THREAD

**Issue by Maurice67205** [odoo/odoo#9338]
When making a manual accounting entry, you can specify the name of a partner 
then you enter your items 
when you confirm the partner field becomes blank

**Comment by pedrobaeza** [comment]
I have just tried on latest runbot 9.0 version, and it seems is working properly:

![seleccion_012](https://user-images.githubusercontent.com/7165771/38397961-a2adb5d2-3940-11e8-937c-5082c03af878.png)

So I'm closing this. If you experiment more this problem, please feel free to open a new issue with all the details to reproduce the problem.
