### ISSUE TITLE
[9.0 Enterprise] [website]  Setting autoplay for videos doesn´t work

### ISSUE THREAD

**Issue by schmidtwastl** [odoo/odoo#9342]
Reproduce:
Homepage->Edit->Put in a Banner->Click on Photo icon->Select the Tab: Video->Fill in a youtube/vimeo link or iframe->SELECT AUTOPLAY->Save->Refresh page->Video should play automatically, but doesn`t

The Problem is, that "Select autoplay" doesn´t save. If you try to edit the video, you will see that it is unselected, even though you just had selected and saved it
![autoplay](https://cloud.githubusercontent.com/assets/9939435/10853124/c96176d2-7f34-11e5-8f92-4b756e8d7dd3.PNG)

**Comment by qsm-odoo** [comment]
Hello,
Sorry for the huge delay: the bug was fixed since then.
