### ISSUE TITLE
9.0 [notes]: Odoo Client Error - Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by ghost** [odoo/odoo#9344]
Unable to add notes when use user client without administrative rights, Other Warning
is Unable to send email, please configure the sender's email address or alias.

**Comment by yue0** [comment]
The Second Waring was right should apppear when click add button.

**Comment by Yenthe666** [comment]
Hi there,

I was no longer able to reproduce this issue.
Can you please update your Odoo source code and try again?

Regards,
Yenthe
