### ISSUE TITLE
[8.0][BUG]Error when install "hr_evaluation" module

### ISSUE THREAD

**Issue by MackZxh** [odoo/odoo#9346]
When I want to install the "hr_evaluation" module, an error occurs:

---

> 2015-10-30 15:38:47,754 27993 INFO v8tsc openerp.modules.loading: loading hr_evaluation/hr_evaluation_data.xml
> 2015-10-30 15:38:47,897 27993 **ERROR** v8tsc openerp.sql_db: bad query: INSERT INTO "resource_resource" ("id", "active", "time_efficiency", "company_id", "resource_type", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval('resource_resource_id_seq'), true, 1.0, 1, 'user', 1, 1, (now() at time zone 'UTC'), (now() at time zone 'UTC')) RETURNING id
> Traceback (most recent call last):
>  File "/home/odoo/odoo-dev/odoo/openerp/sql_db.py", line 234, in execute
>    res = self._obj.execute(query, params)
> IntegrityError: null value in column "name" violates not-null constraint
> DETAIL:  Failing row contains (1237, 1, 1, null, null, null, 1, 1, 2015-10-30 15:38:42.155308, null, t, 2015-10-30 15:38:42.155308, user).
> 
> 2015-10-30 15:38:47,899 27993 **ERROR** v8tsc openerp.http: Exception during JSON request handling.
> Traceback (most recent call last):
>  File "/home/odoo/odoo-dev/odoo/openerp/http.py", line 537, in _handle_exception
>    return super(JsonRequest, self)._handle_exception(exception)
>  File "/home/odoo/odoo-dev/odoo/openerp/http.py", line 574, in dispatch
>    result = self._call_function(*_self.params)
>  File "/home/odoo/odoo-dev/odoo/openerp/http.py", line 310, in _call_function
>    return checked_call(self.db, *args, *_kwargs)
>  File "/home/odoo/odoo-dev/odoo/openerp/service/model.py", line 118, in wrapper
>    return f(dbname, _args, *_kwargs)
>  File "/home/odoo/odoo-dev/odoo/openerp/http.py", line 307, in checked_call
>    return self.endpoint(_a, *_kw)
>  File "/home/odoo/odoo-dev/odoo/openerp/http.py", line 803, in __call__
>    return self.method(_args, *_kw)
>  File "/home/odoo/odoo-dev/odoo/openerp/http.py", line 403, in response_wrap
>    response = f(_args, *_kw)
>  File "/home/odoo/odoo-dev/odoo/addons/web/controllers/main.py", line 948, in call_button
>    action = self._call_kw(model, method, args, {})
>  File "/home/odoo/odoo-dev/odoo/addons/web/controllers/main.py", line 936, in _call_kw
>    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
>  File "/home/odoo/odoo-dev/odoo/openerp/api.py", line 250, in wrapper
>    return old_api(self, _args, *_kwargs)
>  File "/home/odoo/odoo-dev/odoo/openerp/addons/base/module/module.py", line 447, in button_immediate_install
>    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
>  File "/home/odoo/odoo-dev/odoo/openerp/api.py", line 250, in wrapper
>    return old_api(self, _args, *_kwargs)
>  File "/home/odoo/odoo-dev/odoo/openerp/addons/base/module/module.py", line 495, in _button_immediate_function
>    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
>  File "/home/odoo/odoo-dev/odoo/openerp/modules/registry.py", line 370, in new
>    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
>  File "/home/odoo/odoo-dev/odoo/openerp/modules/loading.py", line 355, in load_modules
>    loaded_modules, update_module)
>  File "/home/odoo/odoo-dev/odoo/openerp/modules/loading.py", line 255, in load_marked_modules
>    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
>  File "/home/odoo/odoo-dev/odoo/openerp/modules/loading.py", line 176, in load_module_graph
>    _load_data(cr, module_name, idref, mode, kind='data')
>  File "/home/odoo/odoo-dev/odoo/openerp/modules/loading.py", line 118, in _load_data
>    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
>  File "/home/odoo/odoo-dev/odoo/openerp/tools/convert.py", line 901, in convert_file
>    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
>  File "/home/odoo/odoo-dev/odoo/openerp/tools/convert.py", line 987, in convert_xml_import
>    obj.parse(doc.getroot(), mode=mode)
>  File "/home/odoo/odoo-dev/odoo/openerp/tools/convert.py", line 853, in parse
>    self._tags[rec.tag](self.cr, rec, n, mode=mode)
>  File "/home/odoo/odoo-dev/odoo/openerp/tools/convert.py", line 763, in _tag_record
>    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
>  File "/home/odoo/odoo-dev/odoo/openerp/api.py", line 250, in wrapper
>    return old_api(self, _args, *_kwargs)
>  File "/home/odoo/odoo-dev/odoo/openerp/addons/base/ir/ir_model.py", line 1052, in _update
>    res_id = model_obj.create(cr, uid, values, context=context)
>  File "/home/odoo/odoo-dev/odoo/openerp/api.py", line 250, in wrapper
>    return old_api(self, _args, *_kwargs)
>  File "/home/odoo/odoo-dev/odoo/addons/hr_holidays/hr_holidays.py", line 493, in create
>    return super(hr_employee, self).create(cr, uid, vals, context=context)
>  File "/home/odoo/odoo-dev/odoo/openerp/api.py", line 250, in wrapper
>    return old_api(self, _args, *_kwargs)
>  File "/home/odoo/odoo-dev/odoo/addons/hr/hr.py", line 285, in create
>    employee_id = super(hr_employee, self).create(cr, uid, data, context=context)
>  File "/home/odoo/odoo-dev/odoo/openerp/api.py", line 250, in wrapper
>    return old_api(self, _args, *_kwargs)
>  File "/home/odoo/odoo-dev/odoo/addons/mail/mail_thread.py", line 381, in create
>    thread_id = super(mail_thread, self).create(cr, uid, values, context=context)
>  File "/home/odoo/odoo-dev/odoo/openerp/api.py", line 250, in wrapper
>    return old_api(self, _args, *_kwargs)
>  File "/home/odoo/odoo-dev/odoo/openerp/api.py", line 345, in old_api
>    result = method(recs, _args, *_kwargs)
>  File "/home/odoo/odoo-dev/odoo/openerp/models.py", line 4092, in create
>    record = self.browse(self._create(old_vals))
>  File "/home/odoo/odoo-dev/odoo/openerp/api.py", line 248, in wrapper
>    return new_api(self, _args, *_kwargs)
>  File "/home/odoo/odoo-dev/odoo/openerp/api.py", line 481, in new_api
>    result = method(self._model, cr, uid, _args, *_kwargs)
>  File "/home/odoo/odoo-dev/odoo/openerp/models.py", line 4148, in _create
>    record_id = self.pool[table].create(cr, user, tocreate[table], context=context)
>  File "/home/odoo/odoo-dev/odoo/openerp/api.py", line 250, in wrapper
>    return old_api(self, _args, *_kwargs)
>  File "/home/odoo/odoo-dev/odoo/openerp/api.py", line 345, in old_api
>    result = method(recs, _args, *_kwargs)
>  File "/home/odoo/odoo-dev/odoo/openerp/models.py", line 4092, in create
>    record = self.browse(self._create(old_vals))
>  File "/home/odoo/odoo-dev/odoo/openerp/api.py", line 248, in wrapper
>    return new_api(self, _args, *_kwargs)
>  File "/home/odoo/odoo-dev/odoo/openerp/api.py", line 481, in new_api
>    result = method(self._model, cr, uid, _args, *_kwargs)
>  File "/home/odoo/odoo-dev/odoo/openerp/models.py", line 4230, in _create
>    tuple([u[2] for u in updates if len(u) > 2])
>  File "/home/odoo/odoo-dev/odoo/openerp/sql_db.py", line 158, in wrapper
>    return f(self, _args, *_kwargs)
>  File "/home/odoo/odoo-dev/odoo/openerp/sql_db.py", line 234, in execute
>    res = self._obj.execute(query, params)
> **ParseError**: "null value in column "name" violates not-null constraint
> DETAIL:  Failing row contains (1237, 1, 1, null, null, null, 1, 1, 2015-10-30 15:38:42.155308, null, t, 2015-10-30 15:38:42.155308, user).
> " while parsing /home/odoo/odoo-dev/odoo/addons/hr_evaluation/hr_evaluation_data.xml:44, near

```
<record id="hr.employee" model="hr.employee">
        <field name="evaluation_plan_id" ref="hr_evaluation_plan_managersevaluationplan0"/>
    </record>
```

---

**Comment by Yenthe666** [comment]
Hi @MackZxh,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
