### ISSUE TITLE
[7.0] method 'copy_data"  loses default=default value

### ISSUE THREAD

**Issue by nuncjo** [odoo/odoo#9348]
https://github.com/odoo/odoo/blob/7.0/openerp/osv/orm.py
method 'copy_data"  loses default=default value so replacing default values when using copy function if broken

```
lines = [other.copy_data(cr, uid, line_id, context=context) for line_id in sorted(data[f])]
```

should look like this

```
lines = [other.copy_data(cr, uid, line_id, default=default, context=context) for line_id in sorted(data[f])]
```

**Comment by rvalyi** [comment]
related to an unsupported Odoo version. Can it be closed?
cc @Yenthe666

**Comment by Yenthe666** [comment]
Hi @nuncjo,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
@rvalyi thanks a lot for the ping!

Regards,
Yenthe
