### ISSUE TITLE
[9.0] Secondary Unit Of Measure : Layout create a weird interface in product form

### ISSUE THREAD

**Issue by Zoe9a** [odoo/odoo#9349]
Tested in last runbot (with Windows 7 and Chrome 46.0.2490.80)
Impacted versions: 
-9.0
Steps to reproduce:
1. Check "Manage Secondary Unit of Measure" right in Administrator config form
2. Go to product form

Current behavior:
See capture below (tested in last runbot ):
<img width="661" alt="uom css problem" src="https://cloud.githubusercontent.com/assets/15045085/10867562/50b0fd58-8082-11e5-9f04-c5137adf47b8.PNG">

Expected behavior:
Fully integrated with the v9 interface in one of the existing tabs

**Comment by Yenthe666** [comment]
Hi @Zoe9a,

Thanks a lot for your bug report and sorry for the late reply.
In the meanwhile this function is deprecated and it is no longer available in Odoo.

Regards,
Yenthe
