### ISSUE TITLE
The printed sales orders only in English error other the customer's language setting

### ISSUE THREAD

**Issue by dialna** [odoo/odoo#9351]
The printed sales orders only in English ignoring other the customer's language setting
version: odoo_9.0.latest.exe 
![cliente ingles](https://cloud.githubusercontent.com/assets/15583379/10872005/6f71c774-80c6-11e5-8620-6daf60b0cf6f.png)
![hmtl ingles](https://cloud.githubusercontent.com/assets/15583379/10872006/6f73b4a8-80c6-11e5-93da-17da0e4cc984.png)
![print ingles ok](https://cloud.githubusercontent.com/assets/15583379/10872009/7efe2be2-80c6-11e5-9824-ed033826ed15.png)
error other the customer's language setting
![cliente espanol](https://cloud.githubusercontent.com/assets/15583379/10872013/9decf90c-80c6-11e5-9d27-18e05736ae46.png)
![presupuesto espanol](https://cloud.githubusercontent.com/assets/15583379/10872015/9df28b88-80c6-11e5-8f59-f840ee0b8ada.png)
![factura espanol](https://cloud.githubusercontent.com/assets/15583379/10872014/9df0f520-80c6-11e5-9bcc-76bf989a9cbe.png)

**Comment by Yenthe666** [comment]
Hi @dialna,

This issue can no longer be reproduced in Odoo 9. An example customer with the language on French:
![image](https://cloud.githubusercontent.com/assets/6352350/15494792/a6eb55d2-218c-11e6-8d4e-38124f69a3d8.png)

Printing the quotation for this customer (which is French):
![image](https://cloud.githubusercontent.com/assets/6352350/15494808/bd7674a8-218c-11e6-8241-ef273b90259b.png)

Regards,
Yenthe
