### ISSUE TITLE
[8.0] Push rules with the same procurement group, origin location & destination location assumed to be the same picking type

### ISSUE THREAD

**Issue by pjmcdermott** [odoo/odoo#9353]
I have a route assigned for particular products called "Label" which indicate that a product needs to go through a "Labelling" operation. The source for the push rule is "Company/Input" and the destination is "Company/Sellable Stock". I also have a default "Receipt in 2 steps" rule which moves stock which does not need a label from "Company/Input" to "Company/Sellable Stock" as an "Internal Move" operation. **NB** The source location and destination location are the same. (As the label operation is simple I do not want an intermediate location).

When I receive stock which is 100% label stock a new stock.picking is created with the picking type set to the "Label" operation, as expected. When 100% non-label stock is received a new stock.picking is created with the picking type set to the "Internal Move" operation, as expected.

When I receive stock which is a mix of both types, a single stock.move is created, with the picking type set to the picking type appropriate for the first stock item in the list. This is not expected, and masks the labelling operation for a subset of the received stock.

From poking around in `addons/stock/stock.py` I believe the issues arises in the method `_picking_assign()`, which only uses the procurement_group, location_from and location_to to identify groups of similar stock moves. It ignores the `stock_move.picking_type_id` property of each move, and therefore only created one stock.picking, even if multiple `picking_type_ids` are involved. 

The line

``` python
move = self.browse(cr, uid, move_ids, context=context)[0]
```

selects the first move from the list of moves, and this stock move is used to set the `picking_type_id` for the `stock.picking`.

I believe it is useful to be able to create picking types ("Operations") which have different names but nevertheless have the same source and destination. The current behaviour is inconsistent when receiving a delivery with mixed routes.

If it is argued that my use of multiple push rules with the same source and destination, but different picking types is incorrect then it should not be possible to create them---the fact that I can is a bug.

**Comment by pjmcdermott** [comment]
The patch below adds `picking_type_id` to the list of attributes of `stock.picking` used to determine sets of moves.

```diff
--- stock.py.orig	2015-11-02 01:19:34.806554874 +0000
+++ stock.py	2015-11-02 02:51:49.564992585 +0000
@@ -2130,7 +2130,7 @@
         return values
 
     @api.cr_uid_ids_context
-    def _picking_assign(self, cr, uid, move_ids, procurement_group, location_from, location_to, context=None):
+    def _picking_assign(self, cr, uid, move_ids, procurement_group, location_from, location_to, picking_type, context=None):
         """Assign a picking on the given move_ids, which is a list of move supposed to share the same procurement_group, location_from and location_to
         (and company). Those attributes are also given as parameters.
         """
@@ -2144,8 +2144,9 @@
                 stock_move.picking_id = stock_picking.id AND
                 stock_move.location_id = %s AND
                 stock_move.location_dest_id = %s AND
+                stock_move.picking_type_id = %s AND
         """
-        params = (location_from, location_to)
+        params = (location_from, location_to, picking_type)
         if not procurement_group:
             query += "stock_picking.group_id IS NULL LIMIT 1"
         else:
@@ -2206,7 +2207,7 @@
             states[state].append(move.id)
 
             if not move.picking_id and move.picking_type_id:
-                key = (move.group_id.id, move.location_id.id, move.location_dest_id.id)
+                key = (move.group_id.id, move.location_id.id, move.location_dest_id.id, move.picking_type_id.id)
                 if key not in to_assign:
                     to_assign[key] = []
                 to_assign[key].append(move.id)
@@ -2221,8 +2222,8 @@
                 self.write(cr, uid, write_ids, {'state': state})
         #assign picking in batch for all confirmed move that share the same details
         for key, move_ids in to_assign.items():
-            procurement_group, location_from, location_to = key
-            self._picking_assign(cr, uid, move_ids, procurement_group, location_from, location_to, context=context)
+            procurement_group, location_from, location_to, picking_type = key
+            self._picking_assign(cr, uid, move_ids, procurement_group, location_from, location_to, picking_type, context=context)
         moves = self.browse(cr, uid, ids, context=context)
         self._push_apply(cr, uid, moves, context=context)
         return ids
```

**Comment by Yenthe666** [comment]
Hi @pjmcdermott ,

Thank you for your (very detailed!) bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by rousseldenis** [comment]
@Yenthe666 @pjmcdermott The issue in v8 is real. It has been solved in further versions.

**Comment by PieterPaulussen** [comment]
@pjmcdermott @rousseldenis You can always suggest your changes to https://github.com/OCA/OCB.

**Comment by Yenthe666** [comment]
@rousseldenis yes I do know it is a real issue but Odoo officially doesn't support older versions so there is nothing I can do here. As @PieterPaulussen suggested you can go for OCA though!
