### ISSUE TITLE
Code Style Tests

### ISSUE THREAD

**Issue by nkeilar** [odoo/odoo#9354]
Please consider adding something like https://www.codacy.com/ to check this repository for code style issues. I think it is important given the history of the project to show improving code quality. 

Just a suggestion. Hope it is well received.

**Comment by sle-odoo** [comment]
We have introduced coding [guidelines](https://www.odoo.com/documentation/9.0/reference/guidelines.html) and internally we have a process of review. Some times ago we added PEP checks with comments on pull requests but there was too much noise so AFAIK we won't use these kind of tools at the moment.

Thanks for your contribution though
