### ISSUE TITLE
[9.0] Doesnt automatically create new variable when restarting the server

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#9355]
Hi,

I created a new issue again, the references from last issue is here: #9060
As I don't get any response again.

The problem is:
In version 9, I update the module by adding a new field,
but when I restarted the server, the system not adding a new field in database and I can't enter the system again.

the error message is something like this:
Programming error: column res_partner "newfield"

As further investigation, I find that if I still login to the system, I still can update the module through apps>select the app> and upgrade it.

But now if I don't login to the system and want to login, I will have internal server error, and the log error is  like the above that I explain you before.

The expected behavior:
Even, when I am out of system, I still can login, and then I can have posibility to upgrade the module by clicking apps>select apps> and upgrade it. 
The previous version always worked like this.

Thank You.

**Comment by Yenthe666** [comment]
Hi @falinwa,

Restarting an Odoo server does not upgrade the modules. You can either update the module through Settings > App > Update modules list and then updating the correct module or through the terminal with `./odoo.py -u yourModuleName`.
This should fix your issues. If this issue still persist or if I understood this wrongly please comment on this and I'll re-open it.

Regards,
Yenthe
