### ISSUE TITLE
Odoo 9 [Community] Creating/Editing Reordering Rules does not allow using an existing product

### ISSUE THREAD

**Issue by davidtranhp** [odoo/odoo#9357]
I've just tested Odoo 9 community and found that we cannot select an existing product when creating/editing a reordering rule.

**Comment by Yenthe666** [comment]
Hi @davidtranhp,

Thanks a lot for your bug report.
In the meanwhile I was no longer able to reproduce this and everything seems fine.

Regards,
Yenthe
