### ISSUE TITLE
[9.0] Assets confirmation generated wrong journal entries

### ISSUE THREAD

**Issue by jni-odoo** [odoo/odoo#9363]
Follow the steps to produce the problem 

(1) Create one asset type called "Computer and laptops"
      see here : https://drive.google.com/file/d/0B5j41T1Hqv1sbGU2QXVKRlV6UUk/view?usp=drivesdk

(2) Create a new Asset that is belonging to the above category..
      see here : https://drive.google.com/file/d/0B5j41T1Hqv1sN2FnNTVqYzFmNFU/view?usp=drivesdk

(3) Create a new entry and depriciate the first line ..

see the journal entries of the line :  https://drive.google.com/file/d/0B5j41T1Hqv1sYzZzQlBSM3o2RE0/view?usp=drivesdk

In my view the entries should be reverse :

The Depreciation account should be Debited and
Fixed Asset account should Credited..

Thanks ,

Nikunj Jani (Odoo India)

**Comment by sbuttgereit** [comment]
I can confirm this behavior.  When letting the asset module create the entries (in my case using linear depreciation, other methods untried) the credits and debits are reverse of what they should be.  Depreciation reduces the value of the asset, the Odoo asset module is essentially doubling the value of the asset over the depreciation schedule.  Clearly that's wrong.

This would definitely be a show stopper for using the Asset module in any sort of production capacity.

**Comment by cod-odoo** [comment]
Hello,
I have fixed it in this branch: "9.0-asset-fixes-cod" at this commit: https://github.com/odoo-dev/odoo/commit/2a52c3321da2112dd9236622cd5aecbebcebf45f
Thanks

**Comment by bistaray** [comment]
@qdp - is this OK to merge?  This is an issue for my Customer who pointed out to me that the entries were reversed. @pedrobaeza FYI

**Comment by pedrobaeza** [comment]
Thanks for the ping, Ray. I'll check it out ASAP.

**Comment by tebanep** [comment]
Will this be merged? I've noticed that in version 10 this variables no longer exist. This is being an issue for us as well. Thank you!

**Comment by pvoo** [comment]
Having the same issue, is there any reason not to merge this?

**Comment by simongoffin** [comment]
Closed with 11e834a4c1f6fc1c5fa11cee36ce06a976d6f9cc
