### ISSUE TITLE
[7.0] [mrp] Splitting products to produce causes weird produce behavior

### ISSUE THREAD

**Issue by veloutin** [odoo/odoo#937]
How to reproduce:
1- Create a production for 4 of a product
2- Split the "To Produce" product line to assign:
  - 1 SN01
  - 3 SN02
3- Produce 1 Product

The expected result:
- Produced 1 product with SN01 (could be SN02 too, not sure if any spec on this)

The actual result:
- Produced 1 product with SN01
- Produced 1 product with SN02

Branch https://github.com/savoirfairelinux/odoo/tree/7.0_bug_produce_serialnos has a failing test for this:
https://github.com/savoirfairelinux/odoo/blob/7.0_bug_produce_serialnos/addons/mrp/test/order_process_prodlot_partial_consume.yml

**Comment by Yenthe666** [comment]
Dear @veloutin,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
