### ISSUE TITLE
[8.0] AccessError: (Document type: hr.payslip, Operation: read)') -  using Human Resources / Manager

### ISSUE THREAD

**Issue by tarzan0820** [odoo/odoo#9371]
I keep getting this error when create payslip using Human Resources / Manager role;

AccessError: ('AccessError', u'The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\n\n(Document type: hr.payslip, Operation: read)')

Tested locally and on runbot.odoo.com

Odoo version: 8.0

**Comment by andhit-r** [comment]
@tarzan0820 

Have You set manager field properly? According to record rules user can only CRUD payslip which belong to his/her subordinate. 

Example:
1. You login using demo1
2. You create payslip for demo2
3. demo2 belog to department A
4. demo1 have to be set as manager on department A

**Comment by tarzan0820** [comment]
@andhit-r thanks didn't remember seeing such record rule for v7 so I didn't think of checking... solved  now
