### ISSUE TITLE
[8.0] Dashboard bug

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#9376]
Hi Odoo,

I found a bug when I want to save the pivot view to dashboard.
This is what I do:
1.  I go to pivot view and select some report format that I want to display
2.  I add to dashboard
3.  Then after I check it on the dashboard, the view is still graph and I need to change it to pivot view, but still I got a problem because the format is not the same like I saved.

Video to explain things:
https://www.dropbox.com/s/x46nsf0ohddyurm/dashboardbug.avi?dl=0

You can test it on runbot, and I got the same behavior.

Thank You.

**Comment by Yenthe666** [comment]
Hi @falinwa,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
