### ISSUE TITLE
[7.0] Wrong french translation of status

### ISSUE THREAD

**Issue by ptombez** [odoo/odoo#9379]
Some status are wrongly translated in french.
For example, in timesheet sheet, the status "Open" is translated "Ouvrir" (verb) but should be "Ouvert" (adverb).
![image](https://cloud.githubusercontent.com/assets/8320788/10904603/d328f8f6-8214-11e5-9ba5-48946ad28785.png)

**Comment by mart-e** [comment]
Hello,

The translations are not handled on GitHub but on Transifex, please check the [translation guidelines](https://github.com/odoo/odoo/wiki/Translations).
Regards
