### ISSUE TITLE
[8.0] jQuery version is obsolete

### ISSUE THREAD

**Issue by aristobulo-eezee** [odoo/odoo#9388]
website uses web.assets_common to load jQuery from web that has jQuery 1.8.3, this version is obsolete. This makes difficult to integrate other plugins or functionalities to the website. 

Could you update jQuery? It's already done for v9.0 but not for v8.0

**Comment by aristobulo-eezee** [comment]
@sle-odoo could you take a look on this one? please.

**Comment by sle-odoo** [comment]
Hello,
Sorry but we cannot upgrade jquery in a stable version. As you said, this was an old version and upgrading it was not straightforward and may break things. I remember rev https://github.com/odoo/odoo/commit/01409c1d7b0050942ba5e53ff4f3bb927fd3eb51 to workaround a change of behavior, for instance.

Regards
