### ISSUE TITLE
[7.0] State change in the sales contract does not affect the related project

### ISSUE THREAD

**Issue by dsabrinarg** [odoo/odoo#939]
Hello, I wonder if the following behavior is the desired or is it an issue, when a sale contract finishes the related project is not affected.

***Impacted versions:***
7.0

***Steps to reproduce:***
Here you can find a demo video about the error http://youtu.be/zC04cTpmXqs
Can be reproduced on http://7-0-36105.runbot.openerp.com/

***Current behavior:***
The sale contract status changes to finished, but not the related project.

***Expected behavior:***
That the change of status of the sales contract trigger a change of status in the related project.

**Comment by Yenthe666** [comment]
Dear @dsabrinarg,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
