### ISSUE TITLE
[8.0 ]BAD BUG!!! wrong decimal separator in automatic return entry (german numbers)

### ISSUE THREAD

**Issue by thomasklosinsky** [odoo/odoo#9395]
in german numbers we have it like this:
9.9999,99

in english it would be like this
99999.99

In Odoo POS usually we use german decimal separators which is a "," (comma) and not a "." (dot).

In any recent update the dot is automatically added to our EC-Card Journal as decimal separator and not the comma as usual.

Means:

POS Cart has 58,99 - we hit EC-Card payment, automatically there is 58.99 in the payment form which means 5899,00 and Odoo takes the difference (5840,01) as cash return...

Manually changing the dot to a comma is working but not the solution...

If somebody is not really taking care this means a lot of trouble...
BAD BUG!

**Comment by thomasklosinsky** [comment]
it seems as if this bug depends on the browser...
anyone else??

**Comment by thomasklosinsky** [comment]
??

**Comment by msmarino** [comment]
This is also affecting SPANISH (odoo_9.0.201511232).  Looks like the on-screen keyboard is not using the locale settings?

**Comment by thomasklosinsky** [comment]
@msmarino have you been able to fix it in your installation?

**Comment by msmarino** [comment]
Truly, I haven't tried. I don't program in python...

**Comment by COLABORATI** [comment]
does this potentially business-destroying  bug still exist or did you just abandon?
I am interested in learning about how quick such kind of mission critical bugs are fixed by odoo devs.

**Comment by msmarino** [comment]
I have done no further testing on this bug.

**Comment by liebana** [comment]
Have a look here https://github.com/odoomrp/odoomrp-utils/pull/57

**Comment by thomasklosinsky** [comment]
works like a charm! Thanks a lot!
The bug is not really closed though, is it?

**Comment by liebana** [comment]
No it's not... :disappointed:

**Comment by thomasklosinsky** [comment]
@liebana @msmarino @COLABORATI 
The Fix works for german language!

**Comment by jorenvo** [comment]
Thanks for your report, fixed in dda904c13392473c0e213078cbb6fc73374a96a0.
