### ISSUE TITLE
purchase_double_validation not working for multi currency scenarios

### ISSUE THREAD

**Issue by GoodERPJeff** [odoo/odoo#9399]
version: 8.0

steps to reproduce:

1、install purchase_double_validation in a company with CNY as base currency.set the limit value as default 5000. here odoo see it 5000 CNY.

2、create a purchase order with total amount 4000 USD, confirm it.

result should be:  need manager approve as 4000*6 = 24000 cny

current result: order confirmed without further approve

**Comment by Yenthe666** [comment]
Hi @GoodERPJeff,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
