### ISSUE TITLE
[9.0][master] website_forum: summernote issue

### ISSUE THREAD

**Issue by pga-odoo** [odoo/odoo#9402]
##### Summernote editor not displaying in forum `for portal user` (for admin it works)
Issue generated is because of group ` Website / Editor and Designer ` applied on summernote.js
https://github.com/odoo/odoo/blob/9.0/addons/website/views/website_templates.xml#L205 

![download](https://cloud.githubusercontent.com/assets/7629089/10933514/fc4a222e-82fe-11e5-9327-de6bdd5544f3.png)

**Comment by eLBati** [comment]
Hello @pga-odoo I propose this fix https://github.com/odoo/odoo/pull/9852

**Comment by nle-odoo** [comment]
Hello. It should be solved with https://github.com/odoo/odoo/commit/09411a4 (so needs an update on `website_forum` or editing `website_forum.header` template).

To be a little cleaner (if for example there was another module in the same situation as website_forum), a slightly different solution has been pushed in master (so for saas-9 and over):
 https://github.com/odoo/odoo/commit/de5a00a
