### ISSUE TITLE
[9.0] Bug? Its not possible for me to define the Pricelists

### ISSUE THREAD

**Issue by KontorConsulting** [odoo/odoo#9403]
Sales -> Pricelists -> Pricelists

If I create a new or edit a existing Pricelist the only thing I can change is the Name and the E-commerce Promotional Code.

Its not possible to change any definition of the pricelist.

Screenshot:
![odoo9pricelist](https://cloud.githubusercontent.com/assets/13747255/10933921/71f1f0a6-82dc-11e5-83a3-8e3802c2e1af.jpg)

It should look like this (odoo 8 for example):
![odoo8pricelist](https://cloud.githubusercontent.com/assets/13747255/10933925/761a916a-82dc-11e5-9e78-64ab843ecb46.jpg)

**Comment by jni-odoo** [comment]
Hello ,

In v9 the pricelists are simplified , the version you are working in is the "Single Sales Price Per Product" ,

you have to go the option Sales -> Configuration -> Settings then under hedaing "Quatations and Sales " see the Sales Price option which has 3 radio buttons , choose the advance one 

See here : https://drive.google.com/file/d/0B5j41T1Hqv1seUxocXZTTGI0WDQ/view?usp=drivesdk

Click on Apply and then try to create a PL..

you will get https://drive.google.com/file/d/0B5j41T1Hqv1sSmRGcU1hbTVQZWM/view?usp=drivesdk

I think this will  help..

Thanks,
Nikunj Jani (Odoo India Office)
