### ISSUE TITLE
[14.0] Adyen Hosted Payment Page deprecated

### ISSUE THREAD

**Issue by jeroen7s** [odoo/odoo#94060]
Impacted versions: everything below 15.0

Current behavior: Odoo uses Hosted Payment Pages for payments (which will become unavailable from october 2022)

Expected behavior: Odoo uses Adyen's new checkout system

Is there any possibility the new checkout implementation in v15 will be backported to Odoo14 and/or Odoo13?
Or has anyone already worked on this?

**Comment by jeroen7s** [comment]
Might be solved by https://github.com/odoo/odoo/pull/94651
Is slightly different from the Checkout system in Odoo15, but more in line with how HPP used to work.

**Comment by AntoineVDV** [comment]
Hello, I'm closing this issue since it was fixed with #94651 ;)
You can find the related documentation [here](https://www.odoo.com/documentation/14.0/applications/finance/payment_acquirers/adyen/install_pay_by_link_patch.html).
