### ISSUE TITLE
No release of Wkhtmltopdf with patched Qt is available for Ubuntu 22.04 (Jammy)

### ISSUE THREAD

**Issue by StefanRijnhart** [odoo/odoo#94093]
Impacted versions: all versions of Odoo that require Wkhtmltopdf with patched Qt

Steps to reproduce:

```
wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.bionic_amd64.deb
gdebi  wkhtmltox_0.12.5-1.bionic_amd64.deb
This package is uninstallable
Dependency is not satisfiable: libssl1.1
```

Current behavior: Odoo, when installed on the latest LTS release of Ubuntu cannot generate PDF reports properly.

Expected behavior: Odoo, when installed on the latest LTS release of Ubuntu can generate PDF reports properly.

See https://github.com/wkhtmltopdf/packaging/issues/114

**Comment by StefanRijnhart** [comment]
I see there is some work in progress in https://github.com/wkhtmltopdf/packaging/pull/115

**Comment by ashkulz** [comment]
Builds for 22.04 have been published to the website: see wkhtmltopdf/wkhtmltopdf@e59bfcce3e8db83341264bdd75d996319402ccff.

**Comment by StefanRijnhart** [comment]
@ashkulz wonderful, thank you!

**Comment by ashkulz** [comment]
I had to re-release it as the first release didn't work :+1:

**Comment by StefanRijnhart** [comment]
@ashkulz Thank you for your tireless effort in getting all the builds to work!

**Comment by mowny** [comment]
@StefanRijnhart so does that means odoo16 works with 0.12.6.1-2 too, not only the 0.12.5-1 mentioned in [the latest odoo install guide](https://www.odoo.com/documentation/16.0/administration/install/install.html#prepare)?

**Comment by StefanRijnhart** [comment]
@mowny yes!

**Comment by quentinDupont** [comment]
For people searching for the working deb for Ubuntu 24.04 : https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.jammy_amd64.deb
