### ISSUE TITLE
[15] Error when adding a reaction to user comment from course backend view

### ISSUE THREAD

**Issue by hisaltesse** [odoo/odoo#94113]
Impacted versions: 15

Steps to reproduce:

- Go to elearning app 
- Create a course
- Create a portal user
- Have the portal user join the course
- Have the portal user add a review to the course (with text) 
- Go to the backend of the course (Edit backend) 
- scroll down to view the user comment. 
- put your cursor/mouse over the user comment. An smiley and a star pop up on the top right corner of the comment
- Add a reaction by clicking on the smiley face and selecting a reaction
- now go to the front end of the course as the portal user
- you will notice a yellow popup saying 

> "Access Error
> Due to security restrictions, you are not allowed to access 'Contact' (res.partner) records. Contact your administrator to request access if necessary."

- click on the review tab of the course and it will be blank.

Current behavior:
Error message pops up saying: 
**Access Error
Due to security restrictions, you are not allowed to access 'Contact' (res.partner) records. Contact your administrator to request access if necessary.**

And review tab is blank

Expected behavior:
- no error message
- reviews should show

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by niyasraphy** [comment]
@hisaltesse ,
on checking the same, it seems it has been fixed in the mean while, can you check and if its not happening again, feel free to close the ticket

**Comment by vava-odoo** [comment]
Closing following @niyasraphy's comment, feel free to re-open if not solved
