### ISSUE TITLE
[BUG][14.0] website: switchable button not translate

### ISSUE THREAD

**Issue by tranngocson1996** [odoo/odoo#94235]
This Issue
----------
The switchable button not translate, when i change the language of website.
I already know where to generate that label, but still can't think of a way to fix it and create PR.
This causes problems for the user experience.
Do you have any ideas on this matter? I need a hope at the end of the road :D

Video/Screenshot link (optional):
https://watch.screencastify.com/v/W92OK6jSy4yx14e5c6LS

Support ticket number submitted via odoo.com/help (optional):

**Comment by tranngocson1996** [comment]
@JKE-be Are you in charge of this module? Do you know about this issue?
cc: @qsm-odoo

**Comment by JKE-be** [comment]
Yes, it is a known limitation.
It is not translatable since the field name on ir.ui.view is not translatable.
In a future version, we plan to move them and maybe you will have another system to handle these option's name.

**Comment by tranngocson1996** [comment]
@JKE-be thank for reply
Can you tell me what version it is planned in. I can wait

**Comment by JKE-be** [comment]
To confirm with @rdeodoo and @qsm-odoo ... Maybe v16, probably v17 I suppose, but they will know better than me.

**Comment by rdeodoo** [comment]
JKE is correct, it will be done for v16, in a few days we will ship a big technical change for the website app which will include a refactoring of those "customize views" (that's how we called those switchable options).
They will become options in the right panel of the website builder in edit mode and will thus be translatable.

**Comment by tranngocson1996** [comment]
@rdeodoo I have received your answer. Looking forward to it on v16 🤝 Thank you

**Comment by rdeodoo** [comment]
I confirm that this is now correctly translated and translatable in v16, except for the exception of the portal ones to show invoices etc in /my (as those are defined in module which don't depend of website, that's a corner case).
