### ISSUE TITLE
[8.0] Stock valuation report shows incorrect quantity totals when grouping by location

### ISSUE THREAD

**Issue by pjmcdermott** [odoo/odoo#9424]
Go to **Warehouse | Inventory Control | Current Inventory Valuation** for an inventory valuation report. Select the upside down triangle on the RHS to show the advanced search menu. Select **Group By Location**.

If there have been stock moves into the **WH/Input** location of a warehouse, and then _from_ the **WH/Input** location to another _internal_ location (say **WH/Stock**) then the stock quantity will be shown as being located at  the **WH/Input** location, not in the location that the stock was eventually being moved to.

The overall total stock quantity appears correct.

The problem appears to be in `addons/stock_account/wizard/stock_valuation_history.py`. In the extremely long query to create the view, starting `CREATE OR REPLACE VIEW...`. The view for the company is created as the sum of stock coming in, less the sum of stock going out. Internal moves are ignored via the constraint `source_location.usage not in ('internal', 'transit')`, which appears twice.

This creates the correct total from a company perspective. But the view also aggregates by destination location ID, and it is this which is used to create the **Group By Location** view. By ignoring internal moves, incoming stock is aggregated in the **WH/Input** location, but subsequent internal moves to the **WH/Stock** location are not counted. (External moves would be counted). The **Group By Location** balances are wrong.

I have attempted to fix this by including internal moves by removing the `'internal'` constraint in 2 places in the `CREATE VIEW` query. This appears to have resolved the problem for me, although I do not understand enough to be confident there are no unexpected side-effects.

``` diff
--- stock_valuation_history.py  2015-11-04 17:11:14.823360996 +0000
+++ stock_valuation_history.py  2015-11-04 17:35:42.131243212 +0000
@@ -158,7 +158,7 @@
                     (source_location.company_id is null and dest_location.company_id is not null) or
                     (source_location.company_id is not null and dest_location.company_id is null) or
                     source_location.company_id != dest_location.company_id or
-                    source_location.usage not in ('internal', 'transit'))
+                    source_location.usage not in ('transit'))
                 ) UNION ALL
                 (SELECT
                     (-1) * stock_move.id AS id,
@@ -190,7 +190,7 @@
                     (dest_location.company_id is null and source_location.company_id is not null) or
                     (dest_location.company_id is not null and source_location.company_id is null) or
                     dest_location.company_id != source_location.company_id or
-                    dest_location.usage not in ('internal', 'transit'))
+                    dest_location.usage not in ('transit'))
                 ))
                 AS foo
                 GROUP BY move_id, location_id, company_id, product_id, product_categ_id, date, price_unit_on_quant, source
```

It may be the case that the `'transist'` constraint should also be removed...but I don't really know enough about these.

**Comment by Yenthe666** [comment]
Hi @pjmcdermott,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
