### ISSUE TITLE
[BUG] section/note lines are not handled

### ISSUE THREAD

**Issue by sts-vaidehi** [odoo/odoo#94263]
https://github.com/odoo/odoo/blob/c8f5981880ffed25b5e3d48b679f923114e659a9/addons/sale_stock_margin/models/sale_order_line.py#L13

there should be
`for line in self.filtered(lambda x: not x.display_type)`

**Comment by sts-vaidehi** [comment]
Yes it cause a wrong behaviour when it enters for section/note lines, product wont found and in the next process and call to product._compute_average_price checks for the self.ensure_one() 

It may not entered from odoo base addons only, but it may cause with any simple customisation easily, for suppose I found this when dealing with a tiny addon that enables the section/note lines feature within Transfer (stock.picking), so on the action_confirm of the sales order, it was creating a move for section/note lines and hence this issues came.

in the super call it is handled that it continues the loop iteration if product isn't found sand imply makes the purchase_price 0.
So here at this specified point it should filter out the lines based on product or display type to ensure the single product record in next process for rest lines it will just pass on to the super call.

**Comment by Feyensv** [comment]
Well, it's not a bug then because it's caused by your customization.
Since section/note lines do not have linked moves, this won't ever happen in standard code.
