### ISSUE TITLE
[7.0] Add requirements.txt file

### ISSUE THREAD

**Issue by aristobulo-eezee** [odoo/odoo#9431]
Please add a requirements.txt file to make installation of python dependencies easier for v7.0

**Comment by Yenthe666** [comment]
Hi @mart-e,

Is this something that we could still add / allow or wouldn't this be allowed? We already have it for 8.0 and 9.0 so why not for 7.0? I don't see any problems with this?

**Comment by mart-e** [comment]
If somebody writes it, I am fine to merge it :) (7.0 is still supported until the release of v10)

**Comment by aristobulo-eezee** [comment]
odoo 7.0 has reached its end, so no need for this anymore. Farewell v7.0

**Comment by Yenthe666** [comment]
Thanks you for keeping track of this 😄
