### ISSUE TITLE
[9.0] duplicating events does not duplicate questions

### ISSUE THREAD

**Issue by roedeorm** [odoo/odoo#9434]
In events, there's a tab "Questions". On duplicating a event, the tab "Questions" is not copied. In the new event, the tab "Qestions" is empty.

Tested on http://111694-9-0-opw-653598-origin-nim-ec76f1.runbot.odoo.com
as admin

**Comment by Yenthe666** [comment]
@beledouxdenis and @rim-odoo you two made this feature and added it. It is a fact that questions are not duplicated, was it done by design?

**Comment by rim-odoo** [comment]
@Yenthe666 Please have a look at more recent versions.
This fix https://github.com/odoo/odoo/commit/98a3482369a02bdc550d05c250f05c82450cd2a3 exists in Odoo 10.0 and 11.0. You could check if it is backportable to 9.0.

**Comment by Yenthe666** [comment]
@rim-odoo it looks good. Do you guys make the backport or should I make a PR that is identical to 10.0/11.0 to fix it in V9 too?

**Comment by rim-odoo** [comment]
@Yenthe666 I think this issue is not urgent since it is open since 2015... you can submit an OPW
