### ISSUE TITLE
[BUG][15.0] how to import profile like odoo documentation 

### ISSUE THREAD

**Issue by haumenphai** [odoo/odoo#94385]
documentation: https://www.odoo.com/documentation/15.0/developer/howtos/profilecode.html

but I cannot import:
`ImportError: cannot import name 'profile' from 'odoo.tools.profiler'`

**Comment by haumenphai** [comment]
@Xavier-Do Please follow up

**Comment by Xavier-Do** [comment]
The documentation was updated for the new profiler.
