### ISSUE TITLE
Unable to Cut-off expense in next comming months using an account that require reconciled lines

### ISSUE THREAD

**Issue by petrus-v** [odoo/odoo#94390]
## Impacted versions:

13: not impacted cutting-off in future (I suppose because future journal entry are posted not delayed as in v14.0+)
14 / 15: impacted

## Steps to reproduce:

* create new company "test"
* switch on it
* install French accounting (l10n_fr)
* check "Show Full Accounting Features" to gives access to accounting feature on your user access tab
* create vendor bill and post it
* go to the "Journal Items" tab and click on cut-off button and set following fields in the wizard:
  * *Recognition Date*: next month
  * *Accrued Account*: `486000 Charges constatées d'avance` 
  * Adjusting Amount: as you want 50% for example
  * *Journal* : Miscellaneous Operations

![image](https://user-images.githubusercontent.com/4328507/175249134-c7f52290-c5cd-4445-b2ff-c5abeea2bbcf.png)

* click on create journal entries button

![image](https://user-images.githubusercontent.com/4328507/175249865-a9434b79-c328-4aa1-9fe3-b4fdde6688a6.png)

## Current behavior:

Unable to cutting off expense in next  month on a Prepaid expenses account (Charges constatées d'avance) set with `reconcile=True`, the following message unable the journal entry creation with the following message:
 
`You can only reconcile posted entries.`

(if I switch reconcile=False on the account, entries are created)

## Expected behavior:

Be able to create journal entries in future even the account require to reconcile items

## analysis

I suppose this is because when cutting off in the future journal item are created in draft so lines can't be reconciled until the journal entry is posted.

**Comment by william-andre** [comment]
Fixed with https://github.com/odoo/odoo/pull/106524
