### ISSUE TITLE
[9.0] Anglo-Saxon: Consumable uses Stock Input Account instead of Expense Account

### ISSUE THREAD

**Issue by o2030** [odoo/odoo#9440]
## Impacted versions

9.0, tested on recent 9.0 runbot and current SaaS
## Steps to reproduce
1. Enable multiple company mode (Settings->General Settings->Manage multiple companies)
2. Enable anglo-saxon mode (Developer mode->Settings->Users->Companies->Select Company->Configuration->Use anglo-saxon accounting)
3. Create a product with product type "consumable"
4. Under the "Accounting" tab of the product, select an expense account that is different than the default Stock Input Account. Save.
5. Create a new Vendor bill, choose a vendor, add the product created above to the Vendor bill.

EDIT: Clarification - the product's product category has costing method set to "Standard price" and inventory valuation set to "periodic (manual)".
## Current behaviour

The account column of the bill is not changed to the expense account specified on the Product. However, if "Stock Input Account" is not blank on the product or product category, the account on the Vendor bill will be switched to this.
## Expected behaviour

Since a consumable type product does not have it's stock managed by Odoo, I believe the account automatically selected in the Vendor bill for the product should be pulled from the product expense account (or Product category expense account) rather than the Stock Input Account.

**Comment by gdgellatly** [comment]
You misunderstand.  A consumable is a stocked item, it just doesn't trigger
warning messages, orderpoints, procurements etc. It is assumed always in
stock, but of course it must go through the regular accounts.  Accounting
wise it is treated like a regular stock item.

**Comment by o2030** [comment]
I see. In that case, if a Vendor Bill is created with a consumable, lets say some small item like Paper towels. If the Stock Input Account is on the product is default "Stock Interim Account" - how does that eventually get transferred to e.g. an "Office consumables" expense account?

I understood (perhaps mistakenly) that this happens when receiving an item in the Inventory app - but as far as I can tell only Stockable Products can be received not Consumables.

Thanks

**Comment by gdgellatly** [comment]
just create a category for them to map accounts how you want

**Comment by o2030** [comment]
I can create a category with the Stock Input Account set to e.g. Office consumables.

But I question whether this is logical. You said from an accounting point of view, consumables are treated in the same way as stocked products. But does this behaviour make sense? Why would a consumable need to go to a Stock Input Account rather than directly to an Expense account? And what action would move that consumable's value out of the Stock Input Account and into an expense account in practice?

**Comment by gdgellatly** [comment]
Sorry I'm not a free support service,  hope you understand.  The current
behavior is correct and surprisingly well documented right back to v5. You
are confusing mro type consumables with simple stock consumables which is
what the setting is for.

**Comment by o2030** [comment]
I do understand - feel free not to respond, maybe someone else can help? I have looked for documentation on this functionality (anglo-saxon) and could not find it, so surprised that you say it's well documented.

I must be missing something. How do you create a "simple stock consumable" then without turning off anglo-saxon accounting globally? I cannot see a way to turn it off for a particular product category or particular product.

**Comment by pedrobaeza** [comment]
Closing as kindly answered several times by @gdgellatly
