### ISSUE TITLE
[9.0] [Purchase] can not set separate prices for separate variants from one supplier

### ISSUE THREAD

**Issue by jni-odoo** [odoo/odoo#9443]
See the description below:

(1) Creata a product with the 2 variants (for example mobile (Red color and white color))

https://drive.google.com/file/d/0B5j41T1Hqv1sVE9RS2JsNEJnYjQ/view?usp=drivesdk

(2) Now on on each variant set the price extra so if my templete product is costing 10000 then red mobile 2000 extra and white mobile 1000 extra or vice versa..

(3) Assign a vendor to your main product from "Inventory" tab..here in this vendor give the price 20000

https://drive.google.com/file/d/0B5j41T1Hqv1sVFdwRmQxc0VDTTg/view?usp=drivesdk

(4) Now , create a product with this vendor , and choose the product white mobile the price comes will be 20000,    same way choose a product red mobile here also the price comes is 20000

In Real Business this shoud be different the prices can be different for different variants , but because we gave only one vendor with fixed price , we can not achieve different prices for different variants..

Thanks ,

Nikunj Jani (Odoo India)

**Comment by gurneyalex** [comment]
duplicate #296

**Comment by cierek** [comment]
Duplicate but still an issue + is is tagged with Odoo 9, where the other is about Odoo 8

**Comment by lap-odoo** [comment]
Hello, 

This is now solved in version 11 : https://drive.google.com/a/odoo.com/file/d/1XJjcbF25euxkjdQG3bNYp1vP3yMr6nLH/view?usp=drivesdk.
