### ISSUE TITLE
[9.0] framework issue in one2many

### ISSUE THREAD

**Issue by jni-odoo** [odoo/odoo#9448]
See the video to confirm the issue:

(1) Create either a PO or SO choose the vendor or customer try to add line 

```
  see here :  https://youtu.be/4g28XZNUZME
```

Thanks & Regards,
Nikunj Jani (Odoo India)

**Comment by Yenthe666** [comment]
Hey @jni-odoo,

Thanks a lot for the report.
It is still the case but, hmm, I'm not sure if we should call this a bug honestly.
@ged-odoo what do you think?

**Comment by pedrobaeza** [comment]
I have seen the video, and also don't consider a bug. Both approaches have their cons:

* If you move the dropdown list, then the selection can get complicated, specially on small devices.
* If you don't move the dropdown list (as now), it seems a bit uglier when scrolling on background, but it's not critical.

Thus, I close.
