### ISSUE TITLE
[8.0] Company dependent field is not searchable

### ISSUE THREAD

**Issue by zbik2607** [odoo/odoo#9449]
Steps to reporoduce:
1) Inherit class, with new boolean and company_dependent field, for example res_partner

class res_partner(models.Model):
    _inherit = 'res.partner'
    foo = fields.Boolean(string='FOO',company_dependent=True,default=False)

2) Create method with search:

partners = self.env['res.partner'].search([('foo','=',False)])

3) Create new customer ABC (field foo = False)

4) Call method and search:

Result: empty search
Expected: Customer ABC

**Comment by rousseldenis** [comment]
+1

**Comment by Yenthe666** [comment]
@odony and @xmo-odoo this might be something for you guys. There does seem to be something wrong with the call methods if the field is company dependent.

**Comment by Yenthe666** [comment]
Hi @zbik2607,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by rousseldenis** [comment]
@Yenthe666 You can at least notice this issue was created a year ago and v8 support was valid...

**Comment by Yenthe666** [comment]
Hi @rousseldenis,

That is absolutely the case (and I really didn't want to say this wasn't the case). It just won't be fixed anymore as it is end of life now (although it was created earlier).
I'm just trying to clean up all old issues in an effort to get a good overview and better response rate on bug reports for the newer - and supported - versions.

Regards,
Yenthe
