### ISSUE TITLE
[15.0] pos_coupon: Coupons not being applied to POS order

### ISSUE THREAD

**Issue by CarmenMiranda** [odoo/odoo#94495]
**Impacted versions:**
15.0

**Steps to reproduce:**
1.- Activate a Promotion and a Coupon Program in a PoS, in them set the reward as a Free Product and a Quantity of 1 based on Products that can be Sold. Both of them should be applied using a Code.
<details><summary>Promotion Program</summary>
![image](https://user-images.githubusercontent.com/26889951/175360285-e86d9b2a-29ce-40e2-85b0-ce172d9ac53d.png)
</details>
<details><summary>Coupon Program</summary>
![image](https://user-images.githubusercontent.com/26889951/175360554-ac8d178a-aff7-4c78-a572-e96c6b4b33ee.png)
</details>

2.- Go to POS, choose a product, and then set one of the products that the rule in "Based on Products" applies.

**Current behavior:**

The reward product is not being set until you choose the same product or another product and the total quantity of both products is higher than the quantity set as "Minimum required product qty to get the reward" which is the help for the field "Quantity"
![image](https://user-images.githubusercontent.com/26889951/175366318-fbeced89-4de6-444b-85bd-28791ac0d4ac.png)

This results that you can't reward a customer with a product (automatic and using code)  or a discount (using code) for purchasing you 1 product even when you put 1 as minimum qty. Because in reality, the "Minimum" is that qty + 1, cause if you set 2 as the minimum you have to set 3 so the promotion is being applied.

We shouldn't have to choose the award because the employees should have to learn every promotion that is available in order to reward a Customer.

This happens when the number of items in the order is the same as the minimum qty in the program, the factor will be less than 1 which is truncated to 0:
https://github.com/odoo/odoo/blob/d318b34db8eead078131e59416a339e6edaee02a/addons/pos_coupon/static/src/js/coupon.js#L175-L184

**Expected behavior:**

The reward product should be set when the minimum quantity is covered, as the discounts that are "Automatically Applied".

**Video/Screenshot link (optional):**
https://youtu.be/aelMyRL4xOg
Runbot: https://16786190-15-0-all.runbot51.odoo.com

**Support ticket number submitted via odoo.com/help (optional):**
### OPW 2894007

**Comment by pedrambiria** [comment]
This problem has been solved:
https://github.com/odoo/odoo/pull/79994/commits/c07270924002fd1ad93314be04000066020a8dee
