### ISSUE TITLE
[9.0] [website] Issues with link-editor dialog

### ISSUE THREAD

**Issue by dja-odoo** [odoo/odoo#9451]
Link editor always shows Primary button Colored as **Blue** ir-respective of applied theme : https://youtu.be/Phc9pZ22QI8

**Comment by qsm-odoo** [comment]
In 9.0, the issue is solved individually in some themes. In 10.0, this bug should be solved automatically everywhere. Not sure this is still worth a fix in 9.0... I will see.

**Comment by JKE-be** [comment]
Old issue
Internal Issue
New versions have fixes

Thanks for reporting
