### ISSUE TITLE
[8.0] XMLRPC memory leaking

### ISSUE THREAD

**Issue by rubencabrera** [odoo/odoo#9452]
**Steps to reproduce:**
Connect via xmlrpc to an odoo server froma a script and use the api services for a certain amount of times (from about 100 to start having trouble, and 2000 to be catastrophic)

**Issues observed:**
After a certain amount of calls, CPU usage goes through the roof and speed drops, taking an average of 5 seconds per call. 
After a bigger amount of calls (1735 last time I had 1 hour to waste checking), the problem extends to memory and then using 100% of swap. 
At this point, the server cannot allocate memory for any process, not even the shell, and a forced restart is needed. 

I'll try to run a profiler and see if I can get more information, any suggestions are appreciated.

**Comment by xmo-odoo** [comment]
> any suggestions are appreciated.

The calls you're performing would be useful, possibly how your server is launched/configured as well (multithread or workers?), especially if you can reduce your "real" script to the problematic RPC calls. I tried performing an arbitrary RPC call (a `search` on `res.partner`) and after ~20000 requests I see no performance degradation and no ramping up of the server's memory in 8.0 using the latest revision on branch 8.0, so this doesn't seem like an issue of XMLRPC itself (and at 100 calls already being problematic I can only assume we'd have seen it a long time ago if it were) but it may be that the specific methods being called have issues.
