### ISSUE TITLE
[8.0][BUG] A Manufacturing Order is planified in the past

### ISSUE THREAD

**Issue by JavierIniesta** [odoo/odoo#9454]
**Impacted versions:**

* 8.0

**Steps to reproduce**

* product.product:
    * sale_delay: 18
    * produce_delay: 15
* Company Logistic configuration:
    * Purchase Lead Time: 1
    * Manufacturing Lead Time: 3
    * Security Days: 7
* Go to Sales > Sales Order and create order: 
    * Date order : 06/11/2015 (Today)
    * Requested Date : 30/11/2015 (Set manually)
    * Commitment Date : 24/11/2015 (Calculated)
* Confirm sale order.

**Current behavior**

* MRP production auto created with planned date : 05/11/2015

* The scheduled manufacturer order is planned in the past

**Expected behavior**

* When confirming sale order Odoo must notice to the user that sale order cannot be confirmed because is cannot be planned in the past.

**Comment by JavierIniesta** [comment]
cc @rafaelbn @JMODaERP

**Comment by rafaelbn** [comment]
@JavierIniesta please update adding important and related data like **product.product**, fields sale_delay and produce_delay. Without his to fields cannot calculate anything. Thanks

**Comment by JavierIniesta** [comment]
@rafaelbn Updated

**Comment by rafaelbn** [comment]
Related with https://github.com/odoo/odoo/issues/9306. Error persist after good configuration

**Comment by rafaelbn** [comment]
cc @jbeficent

**Comment by spadae22** [comment]
This is normal according to odoo for reasons why????
We changed our code here so it makes sense for manufacturing.
+++ b/addons/mrp/procurement.py
@@ -72,8 +72,8 @@ class procurement_order(osv.osv):
     def _get_date_planned(self, cr, uid, procurement, context=None):
         format_date_planned = datetime.strptime(procurement.date_planned,
                                                 DEFAULT_SERVER_DATETIME_FORMAT)
-        date_planned = format_date_planned - relativedelta(days=procurement.product_id.produce_delay or 0.0)
-        date_planned = date_planned - relativedelta(days=procurement.company_id.manufacturing_lead)
+        date_planned = format_date_planned + relativedelta(days=procurement.product_id.produce_delay or 0.0)
+        date_planned = date_planned + relativedelta(days=procurement.company_id.manufacturing_lead)
         return date_planned

**Comment by nim-odoo** [comment]
Hello,

We cannot change such a behavior in a stable release: we cannot prevent the confirmation of the SO, since this might break the business flow of some users.

Regards
