### ISSUE TITLE
[9.0] [Digital Product] Demo data is not proper

### ISSUE THREAD

**Issue by jni-odoo** [odoo/odoo#9456]
To see the issue read the below steps 

(1) Open the product "Alice in Wonrderland.." (Digital Product)

(2) When you see you can find there are 4 filed attached to it 
https://drive.google.com/file/d/0B5j41T1Hqv1sTk1TWVlKSEJROU0/view?usp=drivesdk

(3) When you click you will get only one 
https://drive.google.com/file/d/0B5j41T1Hqv1sUVhRaXJYYk5Dd3M/view?usp=drivesdk

Thanks ,
Nikunj Jani (Odoo India)

**Comment by Yenthe666** [comment]
Hey @jni-odoo,

This has been changed quite a lot in the meanwhile. Demo data has been cleaned up & changed, so this is no longer an issue.

Regards,
Yenthe
