### ISSUE TITLE
[8.0][BUG] Manufacturing Work Order form view as pop up

### ISSUE THREAD

**Issue by JavierIniesta** [odoo/odoo#9462]
**Impacted versions:**
- 8.0

**Current behavior**
- Open a Work Order from Manufacturing > Work Orders; these fields are correctly showed:
  - Extra Information > Duration > Number of Cycles
  - Extra Information > Duration > Number of Hours
- Open a Work Order from Manufacturing > Manufacturing Orders > Work Orders; these fields aren't correctly showed:
  - Extra Information > Duration > Number of Cycles
  - Extra Information > Duration > Number of Hours

**Expected behavior**
- Both views must show the same information.

**Comment by JavierIniesta** [comment]
cc @rafaelbn @JMODaERP

**Comment by JMODaERP** [comment]
cc @rafaelbn

**Comment by Yenthe666** [comment]
Hi @JavierIniesta,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
