### ISSUE TITLE
[8.0][BUG] Manufacturing Work Order Scheduled Date and End Date are equal 

### ISSUE THREAD

**Issue by JavierIniesta** [odoo/odoo#9463]
**Impacted versions:**
- 8.0

**Current behavior**
- Manufacturing Work Order Scheduled Date and End Date are equal.

![selection_005](https://cloud.githubusercontent.com/assets/11073758/11002368/9f902a88-84ac-11e5-9c3b-9b39ae4ed461.png)

**Expected behavior**
- End Date should be different.

**Comment by JavierIniesta** [comment]
cc @rafaelbn @JMODaERP

**Comment by jco-odoo** [comment]
What is your mo lead time?

**Comment by JavierIniesta** [comment]
Manufacturing Lead Time: 2.00 days

**Comment by JMODaERP** [comment]
-	Create a product New Product with Supply Chain Information:

  a)	Manufacture : YES
b)	Make to Order: YES.
c)	 Costing Method: Average Price.

-	Create a material Material with Supply Chain Information:
a)	Buy: YES.
b)	Make to Order: YES
c)	Costing Method: Average Price.
d)	Supplier: Create Supplier

-	Create Bill of Materials for New Product  with the next attributes:

a)	Name:  New Product
b)	Quantity: 1 Unds.
c)	Routing: Process Assembly New Product
c.1) Work Center Operation: Create operation Assembly.
c.2) Work Center: Create Work Center: Assembly Center
	C.2.1) Name: Assembly Center
	C.2.2) Resource Type: Material.
	C.2.3) General Information:
		* Capacity per Cycle: 25.
		* Time for 1 cycle (hour): 1 hour.
		* Work Center Product: 	Service Assembly (*)
		* Cost per cycle: 45.


d)	Add an Item: Material (created).
e)	Product  Quantity: 1.

-	Create a Sale Order: (create any Customer) for example 50 units for sale.
-	Confirm Sale.
-	The system atomatically should creat a new Manufacture Order by the 50 sales units.
-	Produce (Botton).
-	Now, go to left menu and select Work Orders.
-	Open the order corresponding to Manufacture Order and click over Assembly - New Product. 
-	The system shows the next Screen: 

 

-	Look the end date in planned date : after two hours of processing the time is the same that Scheduled date:

![2015-11-13 15_38_58-2015-11-13 15_19_26-work orders - odoo - visualizador de fotos de windows](https://cloud.githubusercontent.com/assets/15608043/11148373/b4d6fab4-8a1c-11e5-89cb-f72c9eb48d05.jpg)


(*) Like any other product service:
	Can be Expensed.
	Product Type: Service.
	Cost Price: 45.

**Comment by citronpower** [comment]
If it could help anyone, i post it here.
You need to create a working time and add it to your work center.
Odoo will compute the planned end date with your working time and the duration of the work order.

PS: I'm using odoo 9.0

**Comment by Yenthe666** [comment]
Hi @JavierIniesta,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
