### ISSUE TITLE
Inventory Administrator unable to add, delete or change units of measure

### ISSUE THREAD

**Issue by titou-nivels** [odoo/odoo#94659]
Impacted versions:
15.0

Steps to reproduce:
Add an "Inventory/Administrator" user without any other permissions and _no_ permissions to "Administration/Access Rights". Navigate to Inventory/Configuration/UoM Categories and try to add/delete/change any unit of measure in any category.
![image](https://user-images.githubusercontent.com/101567136/175930062-87872535-908b-4184-bceb-418ac9f72192.png)

Current behavior:
Adding/deleting/changing is not possible due to an access error:
![image](https://user-images.githubusercontent.com/101567136/175929664-6519179a-d56c-40a9-bf8a-5596b898aba7.png)

The error is probably due to this method: https://github.com/odoo/odoo/blob/15.0/addons/uom/models/uom_uom.py#L244

Expected behavior:
No access error for  a user with "Inventory/Administrator" permissions.

**Comment by ticodoo** [comment]
Hello @titou-nivels I cannot reproduce the error. Can you check that it still exists? If it does, can you record a video showing the steps to reproduce the error?

**Comment by titou-nivels** [comment]
Hi, this has already been fixed with ticket 2905840 on odoo.com
