### ISSUE TITLE
[14] mrp: Error when click on MO childs or MO sources smart buttons.

### ISSUE THREAD

**Issue by albertoprocesscontrol** [odoo/odoo#94681]
Impacted versions: 14

Steps to reproduce: Click on smart button MO childs or MO sources.

Current behavior:  Error.  I think the error happens because in the action update's domain, it is being compared with a recordset, not with MO's ID list. (screenshot below)

Expected behavior: Open MO childs or MO sources.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/70946575/175943557-78e84a3e-c34a-42eb-ac03-5a3d9662997d.png)

![image](https://user-images.githubusercontent.com/70946575/175946264-7cd084b7-4d79-47ac-9b04-51c5a8d71129.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by albertoprocesscontrol** [comment]
Support ticket number submitted via odoo.com/help (optional):  #2896006

**Comment by bodedra** [comment]
@albertoprocesscontrol This issue has been resolved. You need to upgrade your source code for the mrp module.

Here is commit ref:

1. https://github.com/odoo/odoo/commit/4870606b00a758e63713e6e82c0cba9b1e7dd4aa
2. https://github.com/odoo/odoo/commit/790c4857674cecba102ec6b0d39de5487c9adee8
