### ISSUE TITLE
[9.0][website_sale] Add to cart feature broken

### ISSUE THREAD

**Issue by parthivgls** [odoo/odoo#9472]
**Impacted versions:**

9.0

**Current behavior**

* Install only "website_sale" module and **DO NOT INSTALL** "website_sale_option"
* Go to /shop url and enable "Add to Cart" option
* Error 500

**Regression Due to commit**

https://github.com/odoo/odoo/commit/e45ade197923daa75d2eba321fc759e33d288855

**Comment by nle-odoo** [comment]
Hello,


It should be solved in 9.0 with https://github.com/odoo/odoo/commit/13a3f8e

There was a typo in this fix which is solved by the also necessary https://github.com/odoo/odoo/commit/5f30aaf

Thanks for reporting.
