### ISSUE TITLE
[9.0]Impossible to install purchase or sale In french language

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#9473]
Impossible to install sales/purchase....

Impacted versions:

 - 9.0, freshly cloned from Github

Steps to reproduce:

 1. create a new db
 2. Try to install purchase

Current behavior:

```
unsupported format character ' ' (0x20) at index 30
None" while parsing /home/florent/DEV/Serveurs/odoo/odoo_9/addons/analytic/views/analytic_view.xml:159, near
<record id="action_account_analytic_account_form" model="ir.actions.act_window">
            <field name="name">Analytic Accounts</field>
            <field name="type">ir.actions.act_window</field>
            <field name="res_model">account.analytic.account</field>
            <field name="context">{}</field>
            <field name="view_type">form</field>
            <field name="view_mode">tree,form</field>
        </record>

```
Expected behavior:

Installation pass

**Comment by flotho** [comment]
I precise that the install in English succeed, it failed in french language

**Comment by rco-odoo** [comment]
@flotho I have checked with today's version (dc02f773ce616e1eba564e574c654fe51d665d11), and everything went fine (create an instance in French, and install module purchase). I cannot reproduce the issue.
