### ISSUE TITLE
Should be able to create contacts ONLY for Company

### ISSUE THREAD

**Issue by bene1505** [odoo/odoo#9481]
**When creating a new contact, it allows creating contact on individual**

Impacted versions:
- 9.0

Steps to reproduce:
1. create a new contact set as individual
2. Creata a new contact on it in tab "Contacts and addresses"

Current behavior:
- allows to create contact on individual

Expected behavior:
- Only allows it for 'Company'

**Comment by Yenthe666** [comment]
Hi @bene1505,

Thanks a lot for your reply and for the late response.
This is actually the desired behaviour and not something we want to change.

Regards,
Yenthe
