### ISSUE TITLE
[9.0] Missing Header and Footer report anywhere

### ISSUE THREAD

**Issue by thanhchatvn** [odoo/odoo#9487]
- Today i checking report sale order, invoice...etc.
- I can not find header your Company inside report
- When i check code and source i see have include this but do not show screen report
- Report report_saleorder_document calling report.external_layout
- Code Extennal_layout: have two footer & header, but them do not show sale report?
- Maybe i wrong, or this is bug ?

![selection_014](https://cloud.githubusercontent.com/assets/3313064/11031697/e422d5ca-8708-11e5-8059-5e78e3802a74.png)

![selection_010](https://cloud.githubusercontent.com/assets/3313064/11031661/a748f9b8-8708-11e5-8682-da1da1cc9efb.png)
![selection_012](https://cloud.githubusercontent.com/assets/3313064/11031662/a74b62de-8708-11e5-8529-8e818fa623a4.png)

**Comment by Yenthe666** [comment]
@thanhchatvn which Wkhtmltopdf version are you using? Use version 0.12.1.
Have a look at: https://github.com/odoo/odoo/issues/5177 this could be causing your issue.

**Comment by thanhchatvn** [comment]
@Yenthe666 : thanks you so much (y)

**Comment by fashkl** [comment]
if use wkhtmltopdf version 0.12.1 try to change it to any updated version such 0.12.4. that will work well.
this to how to install wkhtmltopdf-0.12.4 https://www.tecmint.com/wkhtmltopdf-convert-website-html-page-to-pdf-linux/
enjoy :)
