### ISSUE TITLE
Odoo 8.0 - POS rounding issue if there is set a roundig factor in currency

### ISSUE THREAD

**Issue by mncoon** [odoo/odoo#9496]
# Steps to recreate:
- install new odoo V8 with test data
- install modules pos and accounting with chart l10n_ch
- go under Accounting -> Configuration -> Miscellaneus -> Currencies
- grab CHF and put 0.050000 in Rounding Factor
- start a POS-Session and do some orders with cash payment
## Here are some images

![screenshot-localhost 8069 2015-11-09 15-50-21](https://cloud.githubusercontent.com/assets/7815772/11036704/6e8e5f90-86fa-11e5-8547-7dc391829b06.png)
![screenshot-localhost 8069 2015-11-09 15-51-53](https://cloud.githubusercontent.com/assets/7815772/11036710/748e51ac-86fa-11e5-9d7b-ca957d477f6b.png)
![screenshot-localhost 8069 2015-11-09 15-52-15](https://cloud.githubusercontent.com/assets/7815772/11036712/769ddc24-86fa-11e5-8c7d-054ec72dc9b6.png)
![screenshot-localhost 8069 2015-11-09 15-53-56](https://cloud.githubusercontent.com/assets/7815772/11036713/788ddb92-86fa-11e5-94b8-3a7433e18839.png)
![screenshot-localhost 8069 2015-11-09 15-55-17](https://cloud.githubusercontent.com/assets/7815772/11036714/7ab24bf6-86fa-11e5-9991-6b86ce4b4ad8.png)
## Update:

In V8 the currency options are missing:
https://github.com/odoo/odoo/blob/8.0/addons/point_of_sale/point_of_sale.py#L1353-L1365

Someone implemented the basics but not the whole work

**Comment by copmn** [comment]
Here is the fix: https://github.com/odoo/odoo/pull/9525

**Comment by Yenthe666** [comment]
Hi @mncoon,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
