### ISSUE TITLE
"Internal Transfer Account" Field is missing from the Journals with the type = Cash

### ISSUE THREAD

**Issue by seyed-mohammad-motahar** [odoo/odoo#9499]
Hi, 

Below screenshot shows differences in V8 and V9.

In V8 we can define the internal transfer account in each and every journal so Petty Cash could post to a GL account like "Employee expense".

In V9 we don't have this field in journal anymore and therefore every single entry will be posted against an inter transfer account like "Liquidity Transfer". Therefore the entire process is now very painful for accountant to record further transaction in journal item level. 

![cash_issue1](https://cloud.githubusercontent.com/assets/4558819/11056345/0273f456-87bc-11e5-94ba-52e5007e7ac8.png)

**Comment by pedrobaeza** [comment]
Sorry, but this is something not very used and simplified for the shake of good, and no alternative mechanism has been put, but you can always recreate the v8 field in a community module.
