### ISSUE TITLE
[9.0][currency_rate_live]Currency Rate Error

### ISSUE THREAD

**Issue by leopard7777777** [odoo/odoo#9503]
currency_rate_live.py
def _update_currency_ecb(self):

rate = float(rate) / float(base_currency_rate)

![qq 20151110175351](https://cloud.githubusercontent.com/assets/11750796/11059331/04e42dd8-87d4-11e5-8dd9-b9f2f7ebf36b.png)

sale_report.py
def _select(self):
sum(l.price_total \* COALESCE(cr.rate, 1.0)) as price_total,

￥ -> $
100￥ × rate(0.15) = 15

expect 100￥ / rate(0.15)

i think ,there are some problem when sync rate

**Comment by pedrobaeza** [comment]
What you are trying to get is the inverse rate, but you are interpreting the contrary the way rates are handled. Please check it deeper.
