### ISSUE TITLE
[8.0][email_template] Partner Mass Mailing

### ISSUE THREAD

**Issue by kenvac** [odoo/odoo#9505]
When email templates are configured to print and send pdf reports it uses active ids in context to generate report resulting generating report with all ids which is wrong.

[How to Mimic]
- Create a new template and use existing report "Due Payments" with field "Optional report to print and attach"
- Go to Sales/Customers list view
- Select few customers
- Executing "Partner Mass Mailing" wizard (More -> Partner Mass Mailing)
- Select new template created
- Click on send button to generate emails
- Go to emails (Settings/Technical/E-mail/Email)
- Open newly created email and view pdf report
- The report will contain statement of all customers rather than single customer

[How to fix]
There are two approach to resolve.
1. Delete active_ids from context which will force report to use object ids
2. Replace active_ids with resource id at starting of the loop.

**Comment by pedrobaeza** [comment]
@rafaelbn, have you seen this issue in your tests?

**Comment by janetrp** [comment]
Hello @pedrobaeza I´ve tested in runbot
I have made the test sending to 3 partners and  the pdf report is a single document wih 3 pages related to each partner.

**Comment by pedrobaeza** [comment]
OK, so the error is there. Thanks for trying.

**Comment by pedrobaeza** [comment]
Please try now on runbot the proposed patch here: https://github.com/odoo/odoo/pull/9506

**Comment by janetrp** [comment]
still happening @pedrobaeza

**Comment by Yenthe666** [comment]
Hi @kenvac,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
