### ISSUE TITLE
[ALL] Margin calculation error ◄◄◄

### ISSUE THREAD

**Issue by aitalinassim** [odoo/odoo#95153]
**Impacted versions:**
All versions

**Steps to reproduce:**
- Create products with cost price and selling price
- Make sales ... many quantities
- Check sales analysis and note on a paper margin of the sales (by week for example)
- Change cost price of the same products
- Make other sales
- Check again sale analysis

**Current behavior:**
- Actual margin of sales are correct as per the new cost prices

**Expected behavior:**
- Check again sales analysis
- Note that the previous sales are not the same as per those noted on the paper
- Odoo is not saving the cost price on each sale line, it retreives the actual new cost price even for previous sales.

**Comment by aitalinassim** [comment]
Any solution for this bug ?

**Comment by aitalinassim** [comment]
Any update !!!

**Comment by dalaOdoo** [comment]
@aitalinassim Hello,
Im investigating but indeed the margin of past order should not be updated and so the reporting should not be impacted.

**Comment by aitalinassim** [comment]
> @aitalinassim Hello, Im investigating but indeed the margin of past order should not be updated and so the reporting should not be impacted.

yes, but unfortunately it is not the case, cost value is not stored for previous sales, but reteived at the time of sales analysis.

**Comment by dalaOdoo** [comment]
@aitalinassim the cost is saved on the order line, changing the cost of the product should not recompute it.
What are the modules you are using ?

**Comment by aitalinassim** [comment]
It seems that in master branch, this error was corrected; same for version 15.

I close.
