### ISSUE TITLE
Sales Invoice report missing Invoice and shipping address?

### ISSUE THREAD

**Issue by DeepSilver** [odoo/odoo#9517]
Odoo 8
When comparing sales order report to its invoice, the header missing details regard Invoice and shipping address, is this normal?
![sales-order](https://cloud.githubusercontent.com/assets/3600848/11064561/8517c714-87f0-11e5-84b8-75e2b1b0f7df.jpg)
![sales-invoice](https://cloud.githubusercontent.com/assets/3600848/11064562/851d5b2a-87f0-11e5-898b-bb45a109676d.jpg)

**Comment by sle-odoo** [comment]
Yes, is is intended.

Regards.
