### ISSUE TITLE
[8.0] If deactive a product, default code field (on interface) is empty

### ISSUE THREAD

**Issue by OpenCode** [odoo/odoo#9519]
If deactive a product, default code field (on interface) is empty.
To reproduce the bug:

* Open a product with a Default Code
* Set "active" to false
* Save

Now Default Code is empty on interface but the value exist in database
If set active to true, default code is fill again

**Comment by dorcy-v** [comment]
Hi,

When a product_template is inactive, all his childs is inactive too.
But, related fields doesn't link with inactive object. So, is normally if the default_code link doesn't work

**Comment by OpenCode** [comment]
Thank you @dorcy-v
