### ISSUE TITLE
[14.0] ORM: Is writable computed fields officially supported ?

### ISSUE THREAD

**Issue by rousseldenis** [odoo/odoo#95204]
@rco-odoo I have an issue where some want to write (without inverse method) computed stored fields outside of compute methods themselves.

https://github.com/OCA/contract/pull/854

I think this could lead to cache problems, but I wanted to have your advice on that.

Thanks

**Comment by pedrobaeza** [comment]
This is used already in some modules, like in CRM: https://github.com/odoo/odoo/blob/14.0/addons/crm/models/crm_lead.py

**Comment by rousseldenis** [comment]
> This is used already in some modules, like in CRM: https://github.com/odoo/odoo/blob/14.0/addons/crm/models/crm_lead.py

Ok, thanks. I need to integrate these changes of concept.

**Comment by VincentSchippefilt** [comment]
question answered by @pedrobaeza, thanks :)
