### ISSUE TITLE
[9.0] Dialog boxes do not appear

### ISSUE THREAD

**Issue by bringsvor** [odoo/odoo#9522]
After updating Odoo to latest 9.0 from github today (2015-11-10) and doing a ./odoo.py -u all I now no longer am able to see the contents of dialog boxes. For example when I try to add a follower to an object I get this:
![image](https://cloud.githubusercontent.com/assets/7498104/11077735/ed5cfc0c-8801-11e5-8457-f4cd0bd4d4b9.png)

This basically makes it impossible for me to use a lot of the functionality... Is there something more that needs refreshing or do I have to reinstall?

**Comment by bringsvor** [comment]
Seems this is browser related. Using Google Chrome this problem appears, when using Firefox it does not. Very strange.

**Comment by ged-odoo** [comment]
Dear @bringsvor, I could not reproduce this issue.  Normally, a -u all should work. I can't think of a migration issue that would cause this.

But many fixes have been committed in v9 since 2015/11/10.  Could you try again with the latest version?

**Comment by bringsvor** [comment]
Thanks @ged-odoo , sorry about the delay in responding. It does seem to work these days so I guess you guys have done Something. And if you haven't heard of anyone else with this issue then I guess you can close it.
