### ISSUE TITLE
OSError: [Errno 9] Bad file descriptor with Werkzeug 0.11

### ISSUE THREAD

**Issue by patjones80** [odoo/odoo#9524]
Hello all. I'm using Werkzeug 0.11 as part of a Flask 0.10.1 installation with Python 3.4 on Windows 8.1, and getting the following traceback upon attempting to run my code:

Traceback (most recent call last):
  File "run.py", line 6, in <module>
    app.run(debug = True)
  File "c:\Python34\atweather\flask\lib\site-packages\flask\app.py", line 772, in run
    run_simple(host, port, self, **options)
  File "c:\Python34\atweather\flask\lib\site-packages\werkzeug\serving.py", line 666, in run_simple
    os.set_inheritable(s.fileno(), True)
OSError: [Errno 9] Bad file descriptor

My website is very simple and I'm just attempting to run it locally to do some development on it. I'm fairly new to using Flask and web programming in general, so if this seems more like something that I'm doing wrong with my Flask environment, directory structure, etc. then I apologize.

Thanks so much in advance.

**Comment by elmiguel** [comment]
Just updated to 0.11 via PyCharm, although the repository states that the update is to 0.11.1, the actual module shows it to be 0.11. I am running my test site on that same settings and environment @patjones80 and getting the same results. 

It is being triggered by werkzeug\serving.py : os.set_inheritable(s.fileno(), True)
I think was is happening is that the s.fileno() def is failing due to the socket connection being read only or it failed and closed before it could set the descriptor.

**Comment by elmiguel** [comment]
Changing the code to:
```python
            if hasattr(os, 'set_inheritable'):
                try:
                    os.set_inheritable(s.fileno(), True)
                except OSError:
                    from pprint import pprint
                    pprint(s)
```
allows me to see that the object is set as such:

<socket.socket fd=352, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000)>

But when I print out the s.fileno() it prints out 376

So changing it manually:

```python
            if hasattr(os, 'set_inheritable'):
                try:
                    # os.set_inheritable(s.fileno(), True)
                    os.set_inheritable(376, True)
                except OSError:
                    from pprint import pprint
                    pprint(s.fileno())
```
Allows me to bypass the initial error but continues to provide another error:

```python
  File "C:\Users\elmiguel\flask\lib\site-packages\flask\app.py", line 772, in run
    run_simple(host, port, self, **options)
  File "C:\Users\elmiguel\flask\lib\site-packages\werkzeug\serving.py", line 633, in run_simple
    application = DebuggedApplication(application, use_evalex)
  File "C:\Users\elmiguel\flask\lib\site-packages\werkzeug\debug\__init__.py", line 169, in __init__
    if self.pin is None:
  File "C:\Users\elmiguel\flask\lib\site-packages\werkzeug\debug\__init__.py", line 179, in _get_pin
    self._pin, self._pin_cookie = get_pin_and_cookie_name(self.app)
  File "C:\Users\elmiguel\flask\lib\site-packages\werkzeug\debug\__init__.py", line 96, in get_pin_and_cookie_name
    h.update('cookiesalt')
TypeError: Unicode-objects must be encoded before hashing
```

So changing  

h.update('cookiesalt')

to 

h.update(b'cookiesalt')


returns:
```python
Traceback (most recent call last):
  File "C:\Python34\lib\threading.py", line 920, in _bootstrap_inner
    self.run()
  File "C:\Python34\lib\threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\elmiguel\flask\lib\site-packages\werkzeug\serving.py", line 646, in inner
    fd=fd).serve_forever()
  File "C:\Users\elmiguel\flask\lib\site-packages\werkzeug\serving.py", line 550, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "C:\Users\elmiguel\flask\lib\site-packages\werkzeug\serving.py", line 458, in __init__
    socket.SOCK_STREAM)
  File "C:\Python34\lib\socket.py", line 295, in fromfd
    nfd = dup(fd)
OSError: [WinError 10038] An operation was attempted on something that is not a socket
```


Seems like the socket is being closed somewhere along the line before it is even being used fully.

**Comment by elmiguel** [comment]
Since the issue is really with werkzug, I think this is more appropriate:
https://github.com/mitsuhiko/werkzeug/issues/805

**Comment by patjones80** [comment]
Thanks for pointing out thread 805. Given that information should I roll back to an earlier version (0.10 or 0.9)?

**Comment by elmiguel** [comment]
If you make the change suggested in 805 to use the socket function instead
everything works fine. Once they push it to production then I would update.
If your not comfortable making changes to the source module, then I would
just roll back a version.

**Comment by patjones80** [comment]
I made the change in the source module and it seems to work fine. I'm left with another issue but it doesn't seem to have anything to do with werkzeug. Thank you!

**Comment by MindMapMaker** [comment]
I made the exact change as suggested #805 https://github.com/mitsuhiko/werkzeug/issues/805 eg:
Line 665 in file serving.py
 #          if hasattr(os, 'set_inheritable'):
 #              os.set_inheritable(s.fileno(), True)
            if hasattr(s, 'set_inheritable'):
                s.set_inheritable(True) 

Regretably it didn't work for me.
Anaconda Python 3.4

**Comment by antonylesuisse** [comment]
Not related to Odoo.
