### ISSUE TITLE
9.0-20151104 : Autoregistered website user can't access to the shop ( "403 Forbidden" )

### ISSUE THREAD

**Issue by esciara** [odoo/odoo#9528]
It looks like #1013 has reappeared and that #1786 is still not resolved: on version 9.0-20151104 (I used a docker image to test it), I had the same issue of autoregistered website users not being able to access the shop.
- I have checked the "Is a customer" setting in the Template User, and that does not do anything at all contrary to Odoo 8.
- I have checked the "Public" setting in the user settings, as suggested in #1786, which does not do anything either... Actually, it does something strange as it puts a "Sign In" next to the user that has already signed in :

![image](https://cloud.githubusercontent.com/assets/1336689/11095773/ef697120-8896-11e5-9cab-3b213fab7544.png)

I have been trying a number of combinations of settings and here is what I got:
- When the "Portal" setting is checked, the user accesses the portal (My Account) but cannot access the shop
- When the "Contact creation" setting is checked **and** the "Portal" setting is **not** checked, the user accesses the shop, but not the portal.
- When both the "Contact creation" **and** the "Portal" settings are checked, then again the user accesses the portal (My Account) but cannot access the shop

I cannot see why the "Contact creation" setting should be check to make this work... My expectation would be that only the "Is a customer" setting in the Template User should be checked... And the "Portal" setting of course, but that is done by default.

There does not seem to be any way around the problem... That looks like is a pretty big bug to me as it means clients cannot create their own account, meaning loss of information and loss of sales. Anyway, it impacts our business a lot.

Any workaround? Urgent fix to be expected?

Em

**Comment by ecwashburn** [comment]
Please let me know if you found a solution to this problem.  I have the same problems.  Thanks

**Comment by JKE-be** [comment]
Cannot reproduce

**Comment by usinepi** [comment]
Hi ! 

I'm still encountering this problem with Odoo V.9 community.
But just with one client ! All the settings seem to be the same but just one has this 403 error.
The client / I updated this profil or it has maybe been created in a different way that could explain why it's working differently with it.
Anyway, any ideas would be welcome ! 
Thanks !

**Comment by JKE-be** [comment]
Can you show us your log ? 

you can also try to go to your.website.com/shop?debug=1 to have more info on which model your user is not allowed to read.

**Comment by usinepi** [comment]
This is the info I get : 
(u'The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\n\n(Document type: res.partner, Operation: read)', None)
How can I give access to res.partner to this client (his info only) ?

**Comment by usinepi** [comment]
I did it (debug mode) : I clicked on this user and another one working but I didn't see any difference.
Just "portal" selected.
They are all in the group "Other Extra Rights / Portal" with same permissions.
What is ACL :-)... sorry ?

**Comment by usinepi** [comment]
Any idea ?

**Comment by JKE-be** [comment]
debug mode > settings > groups > filter by "users contains user 1"

vs 

debug mode > settings > groups > filter by "users contains user 2"

you should see an extra group probably.

**Comment by JKE-be** [comment]
pm me to stop to spam on this tread ;)

jke odoo com

**Comment by usinepi** [comment]
@JKE-be Sorry ;-)

**Comment by usinepi** [comment]
@JKE-be I should maybe create a new user ? But there is no way to link the infos of this existing (and not working) user to the new one ?
