### ISSUE TITLE
apps menu not working in odoo 8

### ISSUE THREAD

**Issue by ecoitsolutions** [odoo/odoo#9529]
Since 3 days ago accessing apps menu and updates from within settings  is not working anymore, it gives a broken page showing no apps at all. Is it just a temporary problem or has been deprecated?
The page not working is https://apps.openerp.com/apps/embed/client?db=apps

**Comment by advsp** [comment]
I have the same issue.  IS this a bug?

**Comment by dmo-odoo** [comment]
Hello,

What version of Odoo are you using ? Could you please re-test now if you still have this issue ?

Best regards,
David

**Comment by advsp** [comment]
I am usi8ng v8.0 on-site.  The apps menu started working again the next day.  I did see another problem a couple days later but not as bad.  It was limiting the size of the window again but much larger than before so I could at least scroll through and see waht was there.
 
Now I cannot get Odoo pages to load correctly at all.  I updated a couple fo the apps from Cenit and then updated Odoo and thsi behavior started.  Every time I load a page it gives me error messages like:
Could not get content for /website/static/src/css/snippets.css defined in bundle 'website.assets_editor'.
Could not get content for /website/static/src/css/editor.css defined in bundle 'website.assets_editor'.
Could not get content for /web/static/lib/jquery.ui/css/smoothness/jquery‐ui‐1.9.1.custom.css defined in bundle 'website.assets_editor'.
Could not get content for /web/static/lib/select2/select2.css defined in bundle 'website.assets_editor'.
Could not get content for /website/static/lib/select2‐bootstrap‐css/select2‐bootstrap.css defined in bundle 'website.assets_editor'. 
 
A screenshot of what it looks like is attached.  So I cannot test further now.

Regards,
 
Bob Winchester, President
Advantage Sports LLC
PO Box 397
Dover, NH  03821-0397
Phone: (603) 749-1483
Fax: (603) 617-2824
E-mail: bob@advantagerugby.com

 
 

-----Original Message-----

**Comment by dmo-odoo** [comment]
Hello,

I don't understand what your website issue has to do with the apps menu.
Could you please be more precise whether or not the apps menu now correctly works for you, please ?

Best regards,
David

**Comment by advsp** [comment]
It is not just the website page, it is every page in Odoo.  Attached see what it looks like when I try to get to the Settings menu, for example.  I can't even get to the Apps menu to test anything.

Regards,
 
Bob Winchester, President
Advantage Sports LLC
PO Box 397
Dover, NH  03821-0397
Phone: (603) 749-1483
Fax: (603) 617-2824
E-mail: bob@advantagerugby.com

 
 
-----Original Message-----

**Comment by dmo-odoo** [comment]
I'm sorry but this issue was opened by ecoitsolutions about the Apps menu, and it is now fixed. Your issue clearly hasn't anything to do with the main one, so if you have a support contract, you can contact online@odoo.com about it.

Best regards,
David

**Comment by ecoitsolutions** [comment]
I confirm the problem has been resolved. Now i am able to browse the online apps catalog from within Odoo.
Thank you!
