### ISSUE TITLE
[9.0][sale_report]Currency Conversion Error

### ISSUE THREAD

**Issue by leopard7777777** [odoo/odoo#9531]
my company currency is CNY
my sale order pricelist currency is USD
1CNY = 0.15USD

sale_report.py

sum(l.price_total \* COALESCE(cr.rate, 1.0)) as price_total,
sum(l.price_subtotal \* COALESCE(cr.rate, 1.0)) as price_subtotal,

my sale order is 10USD (pricelist currency is USD)

left join currency_rate cr on (cr.currency_id = pp.currency_id and
                        cr.date_start <= coalesce(s.date_order, now()) and
                        (cr.date_end is null or cr.date_end > coalesce(s.date_order, now())))

get rate (0.15) 
the price of report is 10*0.15 = 1.5CNY
expect 10 / 0.15

**Comment by lem8r** [comment]
Maybe you should edit your exchange rates?

**Comment by pedrobaeza** [comment]
Same answer as in https://github.com/odoo/odoo/issues/9503
