### ISSUE TITLE
[8.0] Customer Payment Terms instead of Supplier Payment Terms 

### ISSUE THREAD

**Issue by chrisdec** [odoo/odoo#9539]
Hello, 

I noticed a problem with payment terms regarding the sale (and purchase) of a Make to Order product.

Steps to reproduce
---------------------------
1.Open runbot 

2.Create a Make to Order product 

Sales >> Products >> Products >> Create 

Name : Make To Order Product
Product type : Stockable Product 
Routes : Buy + Make to Order
Supplier : Asustek 
Sale Price : 100
Cost Price : 50

3.Configure Customer Payment Terms 

Sales >> Sales >> Customers
Find Agrolait
Customer Payment Term : 15 Days (Accounting Tab on Partner Form View) 

4.Configure Supplier Payment Terms 

Purchase >> Purchase >> Suppliers 

Find Asustek 
Supplier Payment Term : 30 Days end of Month (Accounting Tab on Partner Form View) 

5.Create a Sales Order

Sales >> Sales >> Sales Orders >> Create

Customer = Agrolait 
Product = Make to Order Product 

6.Check that there is no purchase order in draft state for Asustek

7.Confirm the Sales Order

8.Find the automatically generated Purchase Order 

In purchases >> Purchase >> Request for quotation 
Find the PO for Asustek with Make to order Product 
Invoicing control : Based on incoming shipments (Deliveries & invoices Tab),

9.Confirm The purchase order 

10.Receive product 

Receive product >> Transfer >> Apply 

11.Create the supplier invoice 

("Create invoice" on the Incoming Shipment >> Create) 

Current behavior 
-------------------

Payment Terms on supplier Invoice are "15 Days". It is the customer payment term of Agrolait 

Expected behavior 
--------------------------

Payment Terms on supplier invoice must be the supplier payment term of Asustek "30 Days end of Month"

Thanks!

**Comment by simongoffin** [comment]
Closed with e3b90ba1d45f9d8c23852b92bcf672b435f43cc6
