### ISSUE TITLE
Partial reconciliation is working wrongly

### ISSUE THREAD

**Issue by Maurice67205** [odoo/odoo#9542]
make an invoice of 444 € with 20 % Vat = 532,80 e  total and then register a payment of 400
the line containing the Account receivable account is flagged as reconciled which is wrong from an accouting point of view.

![odoo9](https://cloud.githubusercontent.com/assets/11387919/11120447/ff031294-894f-11e5-934c-d19b91ef00b6.png)

**Comment by fclementic2c** [comment]
+1

**Comment by fclementic2c** [comment]
To avoid misunderstanding...
Partial reconcile looks like a full reconcile. It my lead to confusion (the invoice is not fully paid here for instance)
However, in the ledger, balances are Ok.

**Comment by seyed-mohammad-motahar** [comment]
+1

**Comment by pedrobaeza** [comment]
Well, although it's not the best, you always have the residual amount for checking the remaining, so I close this.
