### ISSUE TITLE
Too easy to give admin NO access to settings/user creation etc

### ISSUE THREAD

**Issue by bmart** [odoo/odoo#9543]
Just evaluating odoo9 after being a long-time odoo6-7-8 user.  I was trying to get into the Technical Settings options and it looks like I made myself an 'admin' who can only 'configure' stuff but can't install apps or create users or set permissions. And since I am the only user at the moment I am stuck.  

I realize I made an error. But I don't think this is an error you should be allowed to make. The super user should just be able to do everything all the time. And if you want to make other users with 'less' ability, you should be forced to create more users.  
Any ideas?  I am either going to restart a fresh DB or go in and edit the DB manually. 

BTW, the new UI looks killer!
regards

**Comment by Yenthe666** [comment]
@bmart have you activated the technical features in your Odoo 9? In V7/V8 it was under Settings > Users by ticking the checkbox 'Technical Features', in Odoo 9 it is done by activating the developer mode.
When you activate the developer mode you will have all admin rights.

**Comment by bmart** [comment]
I've tried that with no luck. I did get the additional features, but nothing for user control or app management.  I'll try to recreate the issue step by step and follow-up.

**Comment by kkrutko** [comment]
hi bmart,
I did the same=). I used url from browser history http://localhost:8069/web?#page=0&limit=80&view_type=list&model=res.users&action=69

**Comment by maltehelmhold** [comment]
oh boy really, I use Odoo 9 for 10 Minutes and after the same happened to me I'm asking myself only one thing: how can ODOO DOOOO something like that! WHY!!? 

@kkrutko at least your url also worked for me :):) thank you thank you!

**Comment by guru3636** [comment]
Thank you so much kkrutko..your URL worked for me as well.. trying to learn odoo9 and its like just creating nightmares for the beginners.

**Comment by dreispt** [comment]
Changing the "Administration" access to configuration makes the "Settings" menu inaccessible to admin. This can be easily fixed by adding that Group to the Settings Menu item.

**Comment by Yenthe666** [comment]
@mart-e forwarding this one to you. :)

**Comment by wtaferner** [comment]
@dreispt 
Nice, you can add tags to issues of Odoo official? Are there more people who are not employees or part of Odoo SA who can do this?

**Comment by Yenthe666** [comment]
@wtaferner this is an experiment from Odoo and the only two persons outside Odoo that can do this are Dreis and me. We can label and close issues.

**Comment by wtaferner** [comment]
@Yenthe666 
Thx for the info...I like the experiment as I think Odoo SA should work together with devs outside to make a difference to the issues and PR piling up (OPW is not always the best way to qualify as it is only one perspective at a time). At least for qualifying imho it should make a difference as it should save them time and money and helps to improve collaboration and quality. Funny though that obviously Github finally allows this kind of collaboration technically...or is it completely based on trust which would be an even more awesome move?! :+1:

**Comment by Yenthe666** [comment]
@wtaferner it is completely based on trust, we have full admin rights across all of Odoo. So it is Odoo making an awesome move with people they've seen helping a lot.

**Comment by mart-e** [comment]
Well, not full admin rights (very few people have that ;-)) but indeed, getting the nice tag "Odoo member" to help us :-)

Back to the reported issue. The administrator has all rights and no restriction applies to him server side (which is one of the reason you usually do **not** want to use the admin for everyday use) but changing the groups can still affect what he *sees* (not what he can do). This is why we have `res.group` for multi-currency or unit of measures.

So we could put the level down from `base.group_erp_manager` to `base.group_configuration` but then next the report will be somebody that removed the administrations rights all together (or removed the menu, who knows).
My point is that, you can always screw up something in the administration configuration but I don't think we should try to prevent it in all cases. Administration is for advanced users and you need to be aware you can break things.
In the worst case scenario (delete menu, etc.), you can still update the "base" module and get back with the required data.

Now what I think, could/should be done is not to prevent users to use admin as their main account (by creating a simple user at the database creation). But that should be discussed if it's the direction we want to go.
But at least, this is not something that we will change in current version.

**Comment by pscomp** [comment]
Changed the "Administration" access to configuration and now I lost the "Settings" menu to admin. How do I fix this?

**Comment by mart-e** [comment]
@pscomp update your base module

**Comment by pscomp** [comment]
@mart-e Thanks
I used this url http://localhost:8069/web?#page=0&limit=80&view_type=list&model=res.users&action=69
and I was able to edit the access for administrator. Now I got the settings back

**Comment by moy2010** [comment]
Thanks a lot for the solution, @kkrutko !

**Comment by carrycsf** [comment]
@pscomp thanks man this is very helpful for me

**Comment by delcain** [comment]
@kkrutko tnks man

**Comment by anupprogrammer** [comment]
@pscomp your link helped me to solve the issues...
