### ISSUE TITLE
Bug on hr.recruitment when trying to create hr.job through xmlrpc api call

### ISSUE THREAD

**Issue by BlommaertsEdwin** [odoo/odoo#9545]
**Given:**
Odoo v8.1
Must have hr and hr_recruitment odoo modules installed.

**When**:
Upon attempting to create a hr.job record through an xmlrpc api call.

**Got:**
Error with following traceback 
File "addons/hr_recruitment/hr_recruitment.py", Line 585, in create\n alias_context = dict(context, alias_model_name=\'hr.applicant\', alias_parent_model_name=self._name)\nTypeError: \'NoneType\' object is not iterable\n'

**Expected:**
hr.job to be created

**Suggestion:**
Change the following code on line 585 in hr_recruitment:
    alias_context = dict(context, alias_model_name='hr.applicant', alias_parent_model_name=self._name)
TO:
    alias_context = dict(**context=context**, alias_model_name='hr.applicant', alias_parent_model_name=self._name)

**Comment by Yenthe666** [comment]
Hi @BlommaertsEdwin,

Thank you for your bug report.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
