### ISSUE TITLE
external_layout_header problem on pdf

### ISSUE THREAD

**Issue by almas** [odoo/odoo#9546]
On pdf there is external_layout_header bug. Header override on top of some content.

When I select PDF then it shows.

![saleorderbug1](https://cloud.githubusercontent.com/assets/90593/11139885/956b482c-8a0f-11e5-9140-2607ee42b599.png)

![saleorderbug2](https://cloud.githubusercontent.com/assets/90593/11139884/95177cf6-8a0f-11e5-9d8e-e607d812abd3.png)

**Comment by almas** [comment]
It fixing this problem:

<div class="col-xs-3" name="company_address">
                <div t-field="company.partner_id" t-field-options="{&quot;widget&quot;: &quot;contact&quot;, &quot;fields&quot;: [&quot;address&quot;, &quot;name&quot;], &quot;no_marker&quot;: true}" style="border-bottom: 1px solid black;max-height:80px;"/>
            </div>

But I have no other idea.

**Comment by sle-odoo** [comment]
You could customize the paper format (margin-top and header-spacing) according to your needs. Also, i'm not sure but it looks like the DPI of your pdf is kind of low.

**Comment by almas** [comment]
Mmm. I tried it on 2 other systems. But three of them also same. I tried margin-top. But it didn't work. It works on HTML, but not PDF. PDF always show like this. I don't think it's just DPI problem. I don't know much about PDF but I know CSS and HTML.

**Comment by Yenthe666** [comment]
Hi @almas,

This should be handled by the paper format and margins.
The paper format can be configurred under `Settings > Reports > Paper format`.

Closing this, since this is not really a bug.
