### ISSUE TITLE
[8.0][sale_service] Service can't be set to "Make to Order"

### ISSUE THREAD

**Issue by IljaSchumacher** [odoo/odoo#9548]
To make sale_service work and generate Project Tasks from Sale Order lines the product must have the following settings:
Sale_Service Doc:
Product Type = Service
Procurement Method (Order fulfillment) = MTO (Make to Order)
Supply/Procurement Method = Manufacture

As soon as we set the ProductType to "Service" the procurement tab does not allow to set a procurement method.

This issue has been mentioned in the forums:
https://www.odoo.com/forum/help-1/question/how-a-service-product-can-be-make-to-order-if-the-routes-dont-appear-on-the-form-85272

Example Service (No routes selectable):
![1](https://cloud.githubusercontent.com/assets/5556062/11142437/8dfc0788-89ed-11e5-8dd0-91e3a6390b44.png)
![2](https://cloud.githubusercontent.com/assets/5556062/11142439/90d3fd94-89ed-11e5-98cd-d4a4c03a8535.png)

Example Consumable (Routes selectable):
![3](https://cloud.githubusercontent.com/assets/5556062/11142456/a82f7c2a-89ed-11e5-8372-f2b872d9a6bb.png)
![4](https://cloud.githubusercontent.com/assets/5556062/11142457/ac20e2c4-89ed-11e5-9fed-07eda0264c35.png)

**Comment by Yenthe666** [comment]
Hi @IljaSchumacher,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
