### ISSUE TITLE
[8.0][website] Banner background image is set in current slide and in all slides

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#9549]
When you use a carousel with more than 1 slide and add a background to 1 of them, that background is added twice: in the slide and in the carousel.

In case your theme gives to both elements the same size, it will not matter in the current slide, but if sizes are different, you will see a background inside a bigger version of itself.

In any case, all slides get that background, which is not desired.

The only workaround for now is to remove it from the upper div manually from HTML view.

**Comment by Yenthe666** [comment]
Hi @Yajo,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
