### ISSUE TITLE
[7.0] Action Buttons in tree are disabled automatically

### ISSUE THREAD

**Issue by 42gmbh** [odoo/odoo#9551]
If you are placing an action button in a tree it is automatically disabled after the first click. The attribute disabled="disabled" is added by openerp after the first click on the button and it is no longer active.

e.g.

``` XML
<button class="oe_inline oe_stat_button" type="object" readonly="0" string="GO" icon="gtk-go-forward" name="my_action_go" />
```

"my_action_go" opens an URL with target="new".

This behavior is exactly what was done with this issue at launchpad:
https://bugs.launchpad.net/openerp-web/+bug/1078157

It would be very nice if it's possible to force a button not to become disabled.

**Comment by elgow** [comment]
Any action on this issue? It's a major obstacle to using action buttons in a list view.

**Comment by elgow** [comment]
The problem lies at addons/web/static/src/js/views/list_view.js:1084

This code 

<code> 
            .delegate('td.oe_list_field_cell button', 'click', function (e) {
                e.stopPropagation();
                var $target = $(e.currentTarget),
                      field = $target.closest('td').data('field'),
                       $row = $target.closest('tr'),
                  record_id = self.row_id($row);
                
                if ($target.attr('disabled')) {
                    return;
                }
                $target.attr('disabled', 'disabled');

                // note: $.data converts data to number if it's composed only
                // of digits, nice when storing actual numbers, not nice when
                // storing strings composed only of digits. Force the action
                // name to be a string
                $(self).trigger('action', [field.toString(), record_id, function (id) {
                    $target.removeAttr('disabled');
                    return self.reload_record(self.records.get(id));
                }]);
            })
</code>

carefully prepares a callback function to clear the disabled attribute, but that data is not accessible from even a client action called by the button, and I haven't discovered a way to get the platform code to actually execute it. 

If there is some return value from the action that will get this function executed can someone please reveal it? Otherwise this info should assist in fixing this bug.

**Comment by elgow** [comment]
Understood, but not solved, at least for the case of lists in a wizard. 

If the action returns a next action of {type: 'ir_actions_act_window_close'} then the disabled attribute will get removed from the button, but in addition any active wizard will be closed. 

The function above that does <code>$target.removeAttr('disabled');</code> becomes a callback named on_close in the context of the action event. That callback will only be executed by the handler for the ir_actions_act_window_close event in this code.

<code>
   ir_actions_act_window_close: function (action, options) {
        if (!this.dialog) {
            options.on_close();
        }
        this.dialog_stop();
        return $.when();
    },
</code>

One solution would be to pass the event options when executing a client action at the call to <code>ClientWidget(this, action)</code> in 

<code>
    ir_actions_client: function (action, options) {
        var self = this;
        var ClientWidget = core.action_registry.get(action.tag);
        if (!ClientWidget) {
            return self.do_warn("Action Error", "Could not find client action '" + action.tag + "'.");
        }
        if (!(ClientWidget.prototype instanceof Widget)) {
            var next;
            if ((next = ClientWidget(this, action))) {
                return this.do_action(next, options);
            }
            return $.when();
        }
</code> 

That would let a client action execute the button on_close and clear the disabled attribute.

**Comment by Yenthe666** [comment]
Hi @42gmbh,

Thank you for your report.
The official support for Odoo 7.0 is however expired (Odoo only supports the latest three versions) so this won't be handled anymore.
If you still face this in version 8.0, 9.0 or 10.0 please feel free to create a new bug report and we'll look into it as soon as possible.

Regards,
Yenthe
