### ISSUE TITLE
[8.0][website] <span class="cke_widget_new"/> disables "Insert Blocks"

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#9553]
Related to https://github.com/odoo/odoo/issues/6540 probably.

Steps to reproduce:
1. Install `website`.
2. Go to any web page.
3. Use the HTML editor and add `<span class="cke_widget_new"/>` anywhere in your view.
4. Save.
5. Edit that view again. Insert blocks button is missing, and cannot edit any view.

You could ask: why would anybody do those steps? True, it's stupid, but CKEditor seems to add that in some point and makes the user unable to edit again his webpage.

So either it should not add that, or it should not break when that is added.

Tested in 9.0 and it does not seem affected.

**Comment by Danisan** [comment]
Thanks! this helped me to solve this!. I uninstalled ckeditor from several instances

**Comment by Yajo** [comment]
Workaround: enter the ir.ui.view record, search for any appearance of `*cke*`, and remove all attributes and classes containing it.

**Comment by Yenthe666** [comment]
Hi @Yajo,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
