### ISSUE TITLE
[8.0] [account_voucher] Cannot unreconcile payment due to left over entries

### ISSUE THREAD

**Issue by dvdhinesh** [odoo/odoo#9564]
Steps to reproduce:

1) Enter a payment for the receipt.
2) Add a payment for it in supplier payments
3) Cancel the purchase receipt.
4) Try to unreconcile that payment and you can't do it due to left over entries.

**Comment by levkar** [comment]
I confirm this also happens when an invoice is cancelled. I can't believe nobody is complaining about this and haven't merged yet. Many of our customers are suffering from unchangeable vouchers.

thanks @dvdhinesh for the smart solution

**Comment by dvdhinesh** [comment]
@mart-e @odony Could you look at this issue?

**Comment by levkar** [comment]
Here's a module that fixes this problem:

https://github.com/ingadhoc/odoo-addons/blob/8.0/account_voucher_fix/account_voucher.py

**Comment by Yenthe666** [comment]
Hi @dvdhinesh,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
