### ISSUE TITLE
[8.0] Deleting a route leaves behind push rules which are still active

### ISSUE THREAD

**Issue by pjmcdermott** [odoo/odoo#9568]
I have been struggling with a stock moves that were being created automatically when I could find no associated route / push rule. I have discovered that deleting a **route** leaves behind push rules. But these push rules are still marked active and are still applied. So Odoo applies rules which are impossible to find find the web UI.

To see push rules which are not allocated to any routes I did the following query in Postgres:

``` sql
select * from stock_location_path where route_id is null;
```

I am experiencing this on a fairly recent nightly build: 8.0-20151104.

To test:
1. Go to Warehouse | Configuration | Routes
2. Press "Create" to create a new route
3. Enter a route name "Test"
4. Under Push rules, press "Add an item"
5. Enter an operation name, source location, destination location and operation type
6. Save & Close the push rule
7. Save the route
8. Activate the developer mode
9. Open the view for the new route "Test"
10. Get the ID for the new route with "View metadata" on the LHS drop-down
11. Search for push rules using this route with `select * from stock_location_route where route_id=NNN` where NNN is the new route ID in a Postgres console
12. Note the ID of the push rule as PPP
13. Go back to the Odoo web UI.
14. Delete the new route by selecting "Delete" from the drop down menu
15. Go back to the Postgres console
16. Search for the push rule using `select * from stock_location_path where id=PPP` where PPP is the new **rule ID**\* from above
17. Note that the push rule still exists in the database, it is still marked as active, but the `route_id` column is NULL

NB Deleting a push rule from the web UI by pressing the trashcan against the push rule line in the route view works as expected: the push rule is deleted.

I suspect there may be a similar issue with pull rules, but I have not tested yet

**Comment by jco-odoo** [comment]
need to add the ondelete='cascade' on the pull_ids/push_ids

**Comment by pjmcdermott** [comment]
@jco-odoo This change is in the model definition for ```stock_location_route```, therefore a bug, correct?

**Comment by mrzingo** [comment]
Have  this been closed?

**Comment by Yenthe666** [comment]
Hi @pjmcdermott,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
