### ISSUE TITLE
In name_search() handle spaces as "%" to have a friendlier search.

### ISSUE THREAD

**Issue by xmo-odoo** [odoo/odoo#958]
Suggested by Daniel Reis: https://twitter.com/reis_pt/status/484652626764894208

**Comment by Yenthe666** [comment]
@xmo-odoo any update on this?

**Comment by Yenthe666** [comment]
@xmo-odoo can you give feedback here?

**Comment by pedrobaeza** [comment]
It seems that until October 2018 it's not the turn to ask if there's any update on this, hehe, but I'm reviewing oldest issues, and this is one of the oldest.

**Comment by pedrobaeza** [comment]
I think we can finally close this, as no answer nor plans. An OCA module has been developed meanwhile for having this feature: https://github.com/OCA/server-tools/tree/8.0/base_name_search_improved
