### ISSUE TITLE
Odoo 8: No apps shown in Modules / App

### ISSUE THREAD

**Issue by COLABORATI** [odoo/odoo#9580]
In the Settings Section there are no apps shown. I am talking about this menu: 
http://odoo-8-vm:8069/web?#menu_id=54&action=38

there are no apps listed. 

If there are any prerequisites to be able to install apps, this should appear in that window.

**Comment by daveblez** [comment]
I  see just a thumb-nail sized panel, too small to see any apps, instead of the usual full-page kanban view.
It was working fine last week.

**Comment by Yenthe666** [comment]
Hi @COLABORATI,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
