### ISSUE TITLE
[9.0] Point of Sale - Wrong format in Products Prices and Quantities

### ISSUE THREAD

**Issue by airitos** [odoo/odoo#9583]
Hello

I'm writing to report an issue regarding the POS module V9. We noticed that product prices and quantities are not well formatted  in the POS interface. You can configure english language, USD currency for company and pricelist.

Steps to reproduce:
- For language english, define a dot as Decimal Separator and a comma as Thousands Separator and [3,0] as Separator Format
- Define zero as Decimal Accuracy for "Product Unit of Measure"
- Define english language, USD currency for Company and Price List
- Define big prices (more than 1,000.00 USD) for products "2L Evian" and "50cl Perrier". This will let you confirm.
- Start Point of Sale interface
- Click on product "2L Evian" twice, to add 2 units of this product to the cart.

First of all notice the main product area, only the first product gets well formated (formatLang) with both Decimal Separator and Thousands Separator. All other products in the main area are not well formatted.

Look now to the Shopping Cart area, where we have 2 units of "2L Evian", see? Quantity is not formatted according to defined Decimal Accuracy (zero digits).

Now look to the price in the Shopping Cart area, no Thousands Separator either.

Receips are not well formatted either

We do believe this is bug because it behaves pretty well in Odoo V8

King Regards
Aires Silvestre

**Comment by jorenvo** [comment]
Hi,

The issue should have been resolved in 9.0 in https://github.com/odoo/odoo/commit/b32355e9b7bbd6f3b967cab3d797d6860b4b24f8 . Let me know if you're still experiencing issues with this.


Kind regards,
Joren
