### ISSUE TITLE
[9.0] Account move export issue

### ISSUE THREAD

**Issue by be-cloud-js** [odoo/odoo#9588]
Hello,

I had an error while exporting my account moves to csv, line 310 of account_move.py complains that Set does not have **get_item**

Changed the line to

```
        counterpart = list(counterpart)[0:2] + ["..."]
```

fixed the problem... I suppose there is a better way though.

Cheers,

Jerome

**Comment by Yenthe666** [comment]
@qdp-odoo this is still the case, can you give feedback?
https://github.com/odoo/odoo/blob/2d73ea9bed1c6f5c801d73776e223e2be84d25f6/addons/account/models/account_move.py#L360

**Comment by qdp-odoo** [comment]
cannot reproduce on v11, so I'm suppose this is okay now
