### ISSUE TITLE
[I18N][14.0] Missing "Get Authorization Code" from google_drive.pot file 

### ISSUE THREAD

**Issue by SonCrits** [odoo/odoo#95970]
Impacted versions: 14.0

Steps to reproduce: 
Translate "Get Authorization Code" in wizard google_drive_auth_code_wizard
Current behavior: 
There are no "Get Authorization Code" in .pot file 
Expected behavior:
Translate "Get Authorization Code" in wizard google_drive_auth_code_wizard
Video/Screenshot link [(optional):

**Comment by SonCrits** [comment]
@vrbh-odoo help me please

**Comment by niyasraphy** [comment]
hi @SonCrits ,
the module has stopped working since 3rd October 2022, now the end users wont see this wizard.
see: https://github.com/odoo/odoo/commit/939ffdfadd82789d8ad17245f48814270755b042

feel free to close :)

**Comment by SonCrits** [comment]
> hi @SonCrits , the module has stopped working since 3rd October 2022, now the end users wont see this wizard. see: [939ffdf](https://github.com/odoo/odoo/commit/939ffdfadd82789d8ad17245f48814270755b042)
> 
> feel free to close :)

Thank you, I forgot about this issue 👍
