### ISSUE TITLE
Can not Update Inventory in Product

### ISSUE THREAD

**Issue by browseinfo** [odoo/odoo#960]
Impacted versions:
master (8.0)

Steps to reproduce:
	On master version go to sale > Products > Products
	Open a Product
	Go to Inventory Tab
	Click On "Update" Button.
	Try To again "Update" inventory..

Current behavior :
	Can not update inventory second time.
	Button will work properly only when after refreshing the page.

Expected behavior:
	without refresh the page, update inventory should  work properly.

Please check link for video http://youtu.be/K_Unyxb9Ec0
Hope you confirm this bug and revert the solution as soon as possible.

Thanks,

**Comment by Yenthe666** [comment]
Dear @browseinfo,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
