### ISSUE TITLE
button Validate remains disabled with Safari only

### ISSUE THREAD

**Issue by StephaneLu** [odoo/odoo#9604]
Unable to upload csv files with Safari, the validate button remains disabled.
Works fine with Chrome and Firefox.

some hints with :
import.js

    /**
     * Safari does not deal well at all with raw JSON data being
     * returned. As a result, we're going to cheat by using a
     * pseudo-jsonp: instead of getting JSON data in the iframe, we're
     * getting a ``script`` tag which consists of a function call and
     * the returned data (the json dump).

Thank you for your help

**Comment by xmo-odoo** [comment]
That's not a hint. And sadly Odoo does not yet have a psychic department capable of mind reading over TCP/IP, so without more informations (Safari version, Odoo version, CSV data being uploaded and how/where, console & terminal errors if any, …) allowing us to reproduce the issue there isn't much we can do or say aside from "works fine here".
