### ISSUE TITLE
date format exported to excel from odoo not showing correct date format

### ISSUE THREAD

**Issue by Nuru112** [odoo/odoo#96081]
Impacted versions:

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by mrbayati2002** [comment]
Hi,
please comment your odoo version and screenshot of the problem
thanks.

**Comment by Yenthe666** [comment]
Closing as nothing is filled in of the template. You can create a new one if you decide to add all the info & context :)
