### ISSUE TITLE
[9.0][account_account] MultiCompany Adviser Unable to create account_account

### ISSUE THREAD

**Issue by Ben17000** [odoo/odoo#9609]
Hi,
When trying to create a new account_account with an adviser user get the msg :
The requested operation cannot be completed due to security restrictions. Please contact your system administrator.
(Document type: Account, Operation: write) 

in console :
openerp.models: Access Denied by record rules for operation: write on record ids: [279, 280, 281, 282, 283, 284, 285, 294, 300, 305, 306, 307, 308, 309, 312, 342, 346, 347, 348, 349, 350, 351, 352, 353, 355, 356, 357, 359, 362, 363, 364, 365, 366, 367, 368, 369, 370, 375, 376, 379, 380, 385, 386, 387], uid: 5, model: account.account

I can not understand why odoo tries to write on those ids !

env :
odoo v9 commit 9687eb3d8434a09b5f564b49eaa8bb8e88ff9d1c  17/11/2015
users : admin, compta (adviser)
companies : main, aaa with a french chart of account on each company
Thanks for your help.
Ben

**Comment by chris-brehme** [comment]
I've the same problem here. Are there any news about this issue?

**Comment by Ben17000** [comment]
cf fix https://github.com/odoo/odoo/commit/f3ef7001cf35da72a6c35d958b3360fc9b2dd26d
