### ISSUE TITLE
Calendar does not show automatically new events in the responsible filter

### ISSUE THREAD

**Issue by sheltonfreddy** [odoo/odoo#961]
Copied from LP:

This issue still exists.

Seen in version 7.0, trunk and saas. Steps to reproduce:

- Create a new database with demo data.
- Install the 'base_calendar' module.
- Logged as Administrator, go to Messaging -> Calendar, and add a new event to the calendar.
- Without refreshing the web page, uncheck the Administrator checkbox on the "Responsible" selector in the sidebar, and recheck it again.

New events are not shown in the filter until the web page or view is refreshed on the browser and the web cache is updated.

**Comment by Yenthe666** [comment]
Dear @sheltonfreddy,

Thank you for reporting this issue!
At this point Odoo 6.0, 6.1 and 7.0 are no longer supported for bugsfixes anymore, which means we will no longer handle these bugs.
If you still face this issue on Odoo 8, 9 or 10 we'd like to ask you to create a new issue on how to reproduce this.
Our apologies.

Regards,
Yenthe
