### ISSUE TITLE
Mail group translation  doesn't work 

### ISSUE THREAD

**Issue by yk2kus** [odoo/odoo#9628]
Translations of mail groups doesn't work, it remains static.

![selection_008](https://cloud.githubusercontent.com/assets/6999933/11247642/14f1a288-8e04-11e5-9345-5bbdaa8fe003.png)

**Comment by Yenthe666** [comment]
Hi @yk2kus,

Thanks a lot for your bug report but this was probably never translated/handled.
At this point it is working fine though. 

Regards,
Yenthe
