### ISSUE TITLE
[9.0] Calendar Weeks are incorrect by one week

### ISSUE THREAD

**Issue by watermelonjuice** [odoo/odoo#9629]
![screenshot from 2015-11-19 01-06-33](https://cloud.githubusercontent.com/assets/5452111/11248045/0b7b5bc6-8e5a-11e5-8f25-7961354ab9e1.png)

Weeks numbers are incorrect by one week as you can see in the screenshot. e.g. Jan 3 is considered week 53. Jan 10 is week 1. It should be Jan 3 is week 1. Jan 10 is week 2.

I'm using the 20151118 deb package. Time zone is set to Asia/Hong Kong.

![screenshot from 2015-11-19 01-06-42](https://cloud.githubusercontent.com/assets/5452111/11248093/4f0dd666-8e5a-11e5-893f-19804848b75f.png)

**Comment by xmo-odoo** [comment]
Odoo uses [ISO week numbering](https://en.wikipedia.org/wiki/ISO_week_date) in which week 1 is the week containing the year's first Thursday. For 2016 in ISO week numbering, week 1 is [the week starting January 4th](http://www.epochconverter.com/date-and-time/weeknumbers-by-year.php?year=2016), and January 3rd, 2016 is indeed Week 53 of 2015.

**Comment by machadotiago** [comment]
I'm facing the same issue but now it does not correspond with the information that we can find in the ISO Wikipedia page. 
As you can see, on wikipedia it says that we are in CW 2, but my odoo calendar says that we are in CW 1: 

<img width="915" alt="160115 at 00 00 49" src="https://cloud.githubusercontent.com/assets/3775353/12343502/52ffe8ac-bb1b-11e5-85a5-88b44200667f.PNG">
<img width="253" alt="160115 at 00 01 05" src="https://cloud.githubusercontent.com/assets/3775353/12343501/52feda02-bb1b-11e5-999f-4218e4718eb1.PNG">
