### ISSUE TITLE
Scheduled Actions not running in Odoo 8.0

### ISSUE THREAD

**Issue by agstyo** [odoo/odoo#9632]
![selection_019](https://cloud.githubusercontent.com/assets/15026123/11260903/25cc4a9c-8ea2-11e5-9a1c-385758923ec3.png)

```
 def import_products(self):
        """ Import product""
        for backend in self:
            backend.import_product()
        return True
```

This is not working, please help me,

**Comment by Yenthe666** [comment]
This is not default Odoo code and nobody from Odoo itself will help you with this, they always close these questions since they don't belong here.
Post it at https://www.odoo.com/forum and you'll get help soon enough!
(CC @mart-e)

**Comment by agstyo** [comment]
I don't have karma :(

**Comment by Yenthe666** [comment]
@agstyo validate your e-mail and you'll get karma normally. If that doesn't work contact online@odoo.com so they can give you enough karma to create a new question.

**Comment by mart-e** [comment]
@agstyo You may want to check the [technical documentation](https://www.odoo.com/documentation/9.0/) (e.g. the [server actions](https://www.odoo.com/documentation/9.0/reference/actions.html#server-actions-ir-actions-server) section) for such questions.
Closing as not a bug report
