### ISSUE TITLE
[enterprise] jscript bug on accounting dashboard

### ISSUE THREAD

**Issue by elicoidal** [odoo/odoo#9637]
**jscript bug on accounting dashboard**

Impacted versions:
 - 9.0 EE
- Ubuntu 15.10 with FF42
- Code pulled on 151108 (standard + EE)
- No custom modules

Steps to reproduce:

 1. Go to the accounting dashboard
 2. a traceback appear (check screenshot)
![screenshot from 2015-11-19 16-43-52](https://cloud.githubusercontent.com/assets/7600613/11267421/338f30ec-8ee6-11e5-8566-810ccd5c2820.png)

**Comment by mge-odoo** [comment]
Hi,
We have recently updated the nvd3 library used in this dashboard. The removed function (tooltips) has been removed here https://github.com/odoo/odoo/commit/329552b78ee6c9efb8abc2a4a3c78f37d43871ac#diff-ba6747ed13753af7c1396bbb03f518daL59

Make sure you have pulled the latest version of Odoo.
