### ISSUE TITLE
Exception when searching in Project/Tasks in kanban view

### ISSUE THREAD

**Issue by jkanev-eemagine** [odoo/odoo#9642]
Steps to reproduce:
1. Log into OpenERP 7.0, go to tab Projects, then to menu item Tasks
2. Enter some text in the top right search field

Expected: drop-down list with detailed search suggestions

Observed: Dialog with server exception:
    "Error: NameError: name 'project_id' is not defined"

Remark:
This happens with the current code from github/odoo branch 7.0, as well as with the github/oca/ocb branch 7.0 code. It only happens whith our well-filled company database; using a clean database I cannot reproduce the error.
The problem is fixed by the commit
https://github.com/eemagine-medical/OCB/commit/13c15b6f58b196dc385def9bdfcd467e3e27ead4

**Comment by Yenthe666** [comment]
Hi @jkanev-eemagine,

Thank you for your bug report.
At this point Odoo 7 & Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe

**Comment by jkanev-eemagine** [comment]
Hi Yenthe, at the time, before reporting the bug, we had provided a fix: https://github.com/eemagine-medical/OCB/commit/d206710c1f196bba7ccca02077c5f15552122295
and had issued a pull request: https://github.com/OCA/OCB/pull/387.

I can see that pull requests from 2017 are still put into the 7.0 branch of the OCA/OCB code, so it would be nice if you could re-consider. All automatic tests have passed, and the issue is a really small one.

All the best, Jacob.

____________________________________________________________

    Jacob Kanev  |  Senior Software Developer / Project Manager / Head of IT

    eemagine Medical Imaging Solutions GmbH
    Email: jacob.kanev@eemagine.com  |  Web: http://www.eemagine.com
    eemagine GmbH and ANT Neuro BV are part of the Neuromotion group

**Comment by Yenthe666** [comment]
Hi @jkanev-eemagine,

Thanks for the feedback. There are two reasons why that won't be possible:
1) The PR is against OCA, not Odoo
2) Odoo V7 and Odoo V8 are end of life, which means not a single commit or change will be made to these versions as they're no longer official supported by Odoo S.A.

Regards,
Yenthe
