### ISSUE TITLE
A method called with self.env.user is executed with the superuser 

### ISSUE THREAD

**Issue by ghost** [odoo/odoo#9649]
# A method called with self.env.user is executed with the superuser 

### Impacted versions:

 - 8.0

### Steps to reproduce:

 1. Create a new new module
 2. In any model, inherit a method (eg: create, write, name_get, ...)
 3. Call a method on res.users with the current user (you have to use self.env.user)

**Example***
```python
@api.model
def fields_view_get(self, view_id=None, view_type=False, toolbar=False, submenu=False):
    res = super(res_partner, self).fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
    if self.env.user.has_group('base.group_sale_manager'):
        for node in doc.xpath("//field[@name='my_field']"):
            node.attrib['readonly'] = "False"
            if 'modifiers' in node.attrib:
                modifiers = json.loads(node.attrib["modifiers"])
                modifiers.pop('readonly', None)
                node.attrib['modifiers'] = json.dumps(modifiers)

    res['arch'] = etree.tostring(doc)
    return res
```

### Current behavior:

**The current user doesn't have the group "Sale Manager"**
 - The method self.env.user.has_group('base.group_sale_manager') returns **True**

### Expected behavior:

 - The method should return self.env.user.has_group('base.group_sale_manager') **False**

### Why 
When you execute self.env.user, you call the following method: 
```python
@property
def user(self):
    """ return the current user (as an instance) """
    return self(user=SUPERUSER_ID)['res.users'].browse(self.uid)
```
The method will browse the current user with the **superuser**.
However, call a method with the superuser will change the uid.

After that, any method called are executed with the superuser.

### How I've fixed my problem 
```python
self.env['res.users'].browse(self.env.uid).has_group('base.group_sale_manager')
```

Thank for all.

Best regards,
Sylvain Van Hoof

**Comment by andreparames** [comment]
I think the confusion is that `has_group()` doesn't actually work with the given recordset, but with the current `uid`. So your code

```python
self.env['res.users'].browse(self.env.uid).has_group('base.group_sale_manager')
```
is actually equivalent to:
```python
self.env['res.users'].has_group('base.group_sale_manager')
```
I do agree that the naming is confusing, though.

**Comment by xmo-odoo** [comment]
@andreparames is completely right. `has_group`'s has an odd signature which sort-of makes sense in the old API, but it is quite terrible in the new API.

Sadly we didn't think to build a separated "new API" version originally (as had to be done with read or browse) and it's too late to do so now (as it would most likely break existing code). So it's not going to change, except maybe to generate a warning when it's called from a new API context if we add a "good" way to check for access rights in the future.

/cc @odony @rco-odoo

**Comment by StefanRijnhart** [comment]
Kindly asking you to reconsider not to fix this, given that there is a security aspect to this?

**Comment by antonylesuisse** [comment]
Yes we wont proably change this one for compatibility but we might add new one maybe something in the style self.env.user_has_group() on env instead of res.users and self.env['res.user'].check_for_group() i'm sure @rco-odoo will find an elegant naming but it's low priority.

**Comment by andreparames** [comment]
I should note that this pattern (`self.env.user.has_group(...)`) is being used in Odoo's own codebase, maybe they should be checked out, since they're probably falling to the same misconception: https://github.com/odoo/odoo/search?utf8=%E2%9C%93&q=%22self.env.user.has_group%22&type=Code

**Comment by antonylesuisse** [comment]
@xmo-odoo will check our codebase for misuses.

**Comment by antonylesuisse** [comment]
cc @odony because some of them might be a security issue.

**Comment by xmo-odoo** [comment]
@StefanRijnhart @ghost @andreparames after discussing this internally, we're reverting my previous comment considering that the usability and security implication override the breakage of (currently incorrect/misbehaving) code.

**Comment by xmo-odoo** [comment]
But do note that it's only for `has_group` generally speaking methods called on `self.env.user` will remain executed as superuser, because that's the user for that recordset.

**Comment by xmo-odoo** [comment]
Opened PR #10423 to fix this issue.
