### ISSUE TITLE
Missing view for quality_control.quality_check_view_form_small in Odoov15.0

### ISSUE THREAD

**Issue by longbui-novobi** [odoo/odoo#96507]
Impacted versions:
15.0
Hi all, 
I have just figured out the issue when checking the difference between Odoov14.0 and Odoov15.0
The function 
![image](https://user-images.githubusercontent.com/74339503/180367528-b4f5e81f-2d55-4661-94ea-33b7b3973aa6.png)
of odoo reference to the id **quality_control.quality_check_view_form_small** but it's disappeared in Odoov15.0

**Comment by niyasraphy** [comment]
hi @longbui-novobi ,
removed dead code from master in: https://github.com/odoo/enterprise/commit/7c5adf5aa8ba6058f02e809db3a1ee2a5fd5fa67
feel free to close the ticket.
thanks

**Comment by longbui-novobi** [comment]
Thanks @niyasraphy and @vava-odoo
