### ISSUE TITLE
[Odoo 9.0]  Task Description Editor can only paste HTML format text

### ISSUE THREAD

**Issue by angelapper** [odoo/odoo#9651]
I tried the version 9, everything is good, and really like to see for task description it have new wysiwyg editor. But, it seem not work well. It can not paste plain text directly. I tried both of the note's editor and task description editor did not work.

I am using latest version Chrome 

So I did a little bit research by myself on version 9, and got to know. It is using a new js editor which is 
https://github.com/summernote

and I found which part cause the problem in
odoo
\addons\web_editor\static\src\summernote.js

```javascript
function summernote_paste (event) {
.............
    var html = clipboardData.getData("text/html");
    var $node = $('<div/>').html(html);
..............
}
```

So I change it to 
```javascript
 //[FIX] Angelapper: this part prevent plain text to paste
    var html = clipboardData.getData("text/html");
    var content= clipboardData.getData("text");
    if (html !== undefined && html !=="") {
        content=html;
    }
    var $node = $('<div/>').html(content);
    //END OF FIX
```

Now, it works fine.

**Comment by nle-odoo** [comment]
Hello, it should be solved with https://github.com/odoo/odoo/commit/919678b in a similar way as you proposed. Thanks for reporting.
