### ISSUE TITLE
[9.0]openerp-gevent not present in rpm

### ISSUE THREAD

**Issue by flotho** [odoo/odoo#9673]
Hi,

I was desperately trying to make work the chat in v9 and I discovered that the openerp-gevent is not bundled in the rpm. This one https://github.com/odoo/odoo/issues/4021 could also be concerned by this issue
In the v8, openerp-gevent was part of the rpm.
Which is the appropriate file to modify for rpm pacckaging?

**Comment by flotho** [comment]
I precise that with latest git it works perfectly!

**Comment by rriemann** [comment]
This might be related to the issue with the odoo docker image (v9). When setting workers > 0, the server doesn't start and I get in the logs:
`odoo-server | /usr/bin/python: can't open file '/usr/bin/openerp-gevent': [Errno 2] No such file or director` odoo/docker#42

**Comment by flotho** [comment]
Hi @rriemann , 
I precise that Odoo 9 works with openerp-gevent when pull form git. Yet openerp-gevent is not delivered in the rpm. So it's a packaging issue.

**Comment by rriemann** [comment]
I agree. So where is the place to report packaging issues?

**Comment by flotho** [comment]
hi @xmo-odoo , any chance to have a tip so that we made a PR for you?

**Comment by xmo-odoo** [comment]
@flotho don't ask me, ask @sle-odoo he's the one who's built and maintains packaging.

**Comment by flotho** [comment]
@xmo-odoo sorry, I pointed to the wrong user ;-)
So @sle-odoo any chance to lead us on the process to add dependencies in packages?
regards

**Comment by sle-odoo** [comment]
at first sight it looks like the removal of openerp-gevent from the scripts part in setup.py was probably not without consequences. see rev a0eb172cab590982168492ad16ad90c2228c6424

we could revert this commit but maybe a better fix would be to make odoo not depends on this executable in the path..

this looks related to https://github.com/odoo/odoo/blob/9.0/openerp/service/server.py#L442

**Comment by flotho** [comment]
@sle-odoo, thanks for the time spent on this.
What could be the way to prevent odoo from this dependance?

regards

**Comment by flotho** [comment]
Hi @sle-odoo,
What is your recommendation? A PR from us reverting those changes?

Regards

**Comment by flotho** [comment]
Hi @sle-odoo, 

What could be the new way to deploy livechat since openerp-gevent is no more part of the packages?
regards

**Comment by mlaitinen** [comment]
The same applies to .deb installation. How can I enable multiprocess without `openerp-gevent`?

**Comment by intero-chz** [comment]
Hi,

is there any solution to this problem, yet? How can i fix an already used Odoo "manually" after installation? Would it be enough to set up an openerp-gevent under /usr/bin?

Best regards

**Comment by mlaitinen** [comment]
@intero-chz Here's a workaround for you: https://github.com/odoo/odoo/pull/10207#issuecomment-216745382

**Comment by mlaitinen** [comment]
This issue should be closed, because #10207 was merged.
