### ISSUE TITLE
ProgrammingError: can't adapt type 'res.partner  HELP 

### ISSUE THREAD

**Issue by EyCas** [odoo/odoo#9675]
My code:
```python
    @api.multi
    def print_report(self):
		partner_id = self.env['res.partner'].search([('customer','=',True),('user_id','=',self.customer_id.id)])
		for partner in self.env['res.partner'].browse(partner_id):
			account = self.env['account.account'].browse(8)
			conditions = self.env['account.move.line'].search([('partner_id','=',partner.id.id),('account_id','=',account.id),('reconcile_id','=',False)], order='date asc')
			if not conditions:
					raise except_orm(('Alerta'),("El cliente y la cuenta seleccionados no tienen apuntes contables."))
			datas={}
			datas['model'] = 'account.move.line'
			datas['ids'] = conditions.ids
			datas['date_start'] = self.date_start
			datas['date_end'] = self.date_end

			return self.pool['report'].get_action(self.env.cr, self.env.uid, [],
			        'res.partner.historic', data=datas, context=self._context)
```

**Comment by leopard7777777** [comment]
v8 api search method return object..not ids

**Comment by xmo-odoo** [comment]
Exactly what @leopard7777777 noted: in the v8 API methods tend to return recordsets (formerly browse objects), not ids. This means your third line browses the recordset, which uses ~browse_records themselves as ids, which blows up because they're can't be adapted to ids.

Just iterate on `partner_id` directly

**Comment by EyCas** [comment]
@xmo-odoo @leopard7777777  But if I change for:
for partner in self.env['res.partner'].browse(partner_id.id):
.
.


appear this error:

('ValueError', 'Expected singleton: res.partner(11298, 11438, 11176, 11264, 10647, 10950, 11394, 11018, 11506, 11329, 10623, 11437, 10711, 10809, 10831, 10679...

![seleccion_046](https://cloud.githubusercontent.com/assets/9012554/11341639/e153eb7a-91c8-11e5-9b6d-941f66bc15f8.png)

**Comment by xmo-odoo** [comment]
That's because what you are doing makes no sense. You're asking for a single id from a non-singleton recordset, which has multiple ids, and for some reason you're still trying to create a copy of a recodset you already have. Why don't you just iterate on the ill-named `partner_id`?

**Comment by EyCas** [comment]
ok. Thanks @xmo-odoo
