### ISSUE TITLE
issue in the Installation instructions for packaged installers - "RPM"

### ISSUE THREAD

**Issue by wikibit** [odoo/odoo#9679]
Hi,

it seems the instructions are not valid in a lot of cases:
the instructions read:

1. $ sudo yum install -y epel-release
2. $ sudo yum install -y postgresql-server
3. $ sudo postgresql-setup initdb
4. $ sudo systemctl enable postgresql
5. $ sudo systemctl start postgresql
6. $ sudo yum-config-manager --add-repo=https://nightly.odoo.com/9.0/nightly/rpm/odoo.repo
7. $ sudo yum install -y odoo
8. $ sudo systemctl enable odoo
9. $ sudo systemctl start odoo

On a fresh, minimal and clean Centos 6.7 install, this results in:
1. ok
2. ok
3. sudo: postgresql-setup: command not found
--> the script does not seem to come with the postgres install
find /* | grep postgresql-setup --> no results

so, what are the steps to resolve this and continue the installation?

**Comment by sle-odoo** [comment]
These instructions are only tested on centos 7 with the fedora epel 7 repositories activated. We don't have instructions for centos6 and the package is not likely to work as it only bundle a systemd unitfile. Also, we have not tested that all the dependencies are met on centos 6.

We don't plan to publish another rpm working with centos6. Maybe you should try a source install and then create a sysvinit unitfile for it?
