### ISSUE TITLE
Controller endpoints with auth='admin' do not work

### ISSUE THREAD

**Issue by aisopuro** [odoo/odoo#9688]
The [documentation](https://www.odoo.com/documentation/8.0/reference/http.html) says that one should use `auth='admin'` to enable a request context with admin rights. However, doing this throws an error, since the method used in `ir_http.py` does not find the appropriate function (in this case it looks for `_auth_method_admin`, as seen [here](https://www.odoo.com/documentation/8.0/reference/http.html)).

It seems that the appropriate keyword is `public`, since `_auth_method_public` [does set the request uid to `SUPERUSER_ID`](https://github.com/odoo/odoo/blob/8.0/openerp/addons/base/ir/ir_http.py#L75).

Current behaviour:
- The documentation on Web Controllers says to use the auth method `'admin'`, while the actual required keyword is `'public'`.

Expected behaviour:
- The documentation and functionality should agree.

**Comment by andreparames** [comment]
> It seems that the appropriate keyword is public, since _auth_method_public does set the request uid to SUPERUSER_ID.

No, it uses the SUPERUSER_ID to fetch the public user (it's a "special" user), and the request uid is set to the ID of that "public user."

**Comment by aisopuro** [comment]
OK, then I guess there should be an `_auth_method_admin` added to `ir_http.py`.

**Comment by andreparames** [comment]
Yeah, and `public` should be added to the docs.
