### ISSUE TITLE
[9.0 Enterprise] Exporting all taxes doesn't work

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#9692]
**The select all checkmark does not work when exporting taxes**

Impacted versions:

 - 9.0 Enterprise

Steps to reproduce:

 1. Install accounting
 2. Navigate to Accounting > Configuration > Taxes
 3. Check the checkmark at the top to select all records
<img src="http://i.imgur.com/TXfeUtu.png" alt="Check all option"/>
 4. Click on Action -> Export

Current behavior:

 - Only the first record is exported, not all the others. When you would manually select all records it would export them correctly.

Expected behavior:

 - All records are selected AND exported when clicking on export.

**Comment by Yenthe666** [comment]
@odony could somebody look at this one please? Sorry for the ping but its Enterprise.

**Comment by qsm-odoo** [comment]
The problem was indeed specific for exporting taxes.
This has been fixed in 9.0 enterprise with commit https://github.com/odoo/enterprise/commit/90a30d4c835812710939dbc8951b11134120faf1
