### ISSUE TITLE
[8.0] Mass mailing - Partner's language not used

### ISSUE THREAD

**Issue by francoislawarree** [odoo/odoo#9695]
Hi,

I detected that the language field defined on the partner is not taken into account when i send my email through "Mass mailing" module.

Here are the steps to follow: 

**1) Design of my mass mailing template in 3 languages (FR - EN - NL). I Changed the title for each language:**

Mass mailing - Test
![image](https://cloud.githubusercontent.com/assets/11072956/11342191/6434d4ae-9206-11e5-8d88-4ec3a3e7c464.png)
EN
![image](https://cloud.githubusercontent.com/assets/11072956/11342132/0ba4655c-9206-11e5-81d5-365b5d9eadb4.png)
FR
![image](https://cloud.githubusercontent.com/assets/11072956/11342145/1988d98c-9206-11e5-9166-87502a7ee368.png)
NL
![image](https://cloud.githubusercontent.com/assets/11072956/11342151/25777852-9206-11e5-9a5b-d7ee98b370e8.png)

**2) Create a mass mailing and select my previous template designed:** 
![image](https://cloud.githubusercontent.com/assets/11072956/11342290/e046a2ac-9206-11e5-8201-5c9012253ae1.png)

**And where i define the receivers as 3 partners in the 3 different languages:**
![image](https://cloud.githubusercontent.com/assets/11072956/11342257/bb5f8120-9206-11e5-9b1f-d605566616d3.png)

**As unexpected all of the 3 receivers have the same email without any translation taken into account.**

Dutch email sent:
![image](https://cloud.githubusercontent.com/assets/11072956/11342351/3f249e3c-9207-11e5-9735-1f2d896219a3.png)

English email sent:
![image](https://cloud.githubusercontent.com/assets/11072956/11342366/4e98502a-9207-11e5-98fb-525b2566ea86.png)

French email sent:
![image](https://cloud.githubusercontent.com/assets/11072956/11342375/620f61ac-9207-11e5-92b7-58ceea88d11e.png)

**On the email-template we have the possibility to define a field that will determine the language concerned but this option should be also considered when a mass mailing is sent to all the concerned receivers which is, for me, a basic feature for the mass mailing module.**

screen with the language option : 
![image](https://cloud.githubusercontent.com/assets/11072956/11342434/b4202d5a-9207-11e5-97d9-fc36a062b0df.png)

Regards,

François

**Comment by mart-e** [comment]
Hello,

As the name of the module states it, this is a feature to send an email to a large number of person. We definitely don't want to send a different email to each of the recipient, that would be a performance killer.

Your screenshot looks like a mail template, not a mass mailing configuration. Moreover to see this window with these options, you probably needed to go to settings menu in technincal features. When using the "Mail Template" menu in the "Marketing" application, you will not see these fields. We have specifically hidden it as may be confusing in the scenario of a mass mailing.
