### ISSUE TITLE
[9.0] IE11, App: Project, Dashboard: Ugly!

### ISSUE THREAD

**Issue by auditum** [odoo/odoo#9696]
Action:
Create some projects with tasks inside.

Expected result:
Dashboard shows nice looking cards for projects.

Result:
![odoo9-ie11](https://cloud.githubusercontent.com/assets/15155714/11343431/57aecc98-920c-11e5-8cb3-05a104e2150b.PNG)

--> CSS is broken for IE 11.

**Comment by rvalyi** [comment]
@auditum isn't this fixed by https://github.com/odoo/odoo/commit/6fd7fc9643932e238ba9211405053c5cb3a387e3 ?

**Comment by auditum** [comment]
doesn't seem so. the blue task-boxes (class: o_project_kanban_boxes) are not aligned to the right and the row does not break on line ending, like it does in Chrome, Firefox etc.

can anybody confirm this?

furthermore, IE11 users cannot click on projects to view tasks because of a strict mode restriction, as described in issue #8516

![20151124_odoo-projects-css-err](https://cloud.githubusercontent.com/assets/15155714/11380757/55949c70-92f8-11e5-9edc-38f765cba92a.PNG)
