### ISSUE TITLE
[8.0] the super with the new api in function field is not work

### ISSUE THREAD

**Issue by JulioSerna** [odoo/odoo#9699]
Impacted version
- 8.0

Steps to reproduce
- To create module custom with depends to **sale_order_dates**
- Inherit **sale.order** model and try to make super with **api.multi** to **_get_commitment_date** function

Current Behavior
- When create sale order shows error in argument of the function **_get_commitment_date** 

Expected Behavior
- it should be able to inherit function field with the new api 

I made a video,
https://youtu.be/CFjzyYY40t4

**Comment by andreparames** [comment]
The problem is that the automatic API conversion doesn't fill in all the fields, only `cr`, `uid`, `ids` and `context`.

Try passing them explicitly in your code:

```python
@api.multi
@api.depends('order_line.product_id')
def _get_commitment_date(self):
    res = super(SaleOrder, self)._get_commitment_date(name="commitment_date", arg=None)
```

**Comment by Yenthe666** [comment]
Hi @JulioSerna ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
On a sidenote: the example from (@)andreparames should handle your case.

Regards,
Yenthe
