### ISSUE TITLE
[9.0] [survey] Translations in survey doesn't work with French(BE), gives traceback.

### ISSUE THREAD

**Issue by kga-odoo** [odoo/odoo#9712]
Steps To reproduce:

In 9.0 with all db 

1. Got to settings>Translations> Load a Translation.
2. Select any French(BE), select websites. Click on "Load" Button.
3. Go to Preferences menu from top right Corner.
4. Change the language to French(BE).
 Go to Survey menu, it will give traceback as in below image
![image](https://cloud.githubusercontent.com/assets/12183876/11365464/c1bba6ae-92cc-11e5-8a6d-4917fecf33b0.png)

**Comment by lfend** [comment]
Hi, 
Same issue and same traceback here with the French(FR) translation. 

Tried to 2 others  translations (spanish and romanian), no issue.

**Comment by mart-e** [comment]
Hello,

Indeed there was an error in the translation of the survey view that made the rendering crashing. I have fixed it and updated the translations at e8e5405d0cafa460648b1bab5b144fb81ebd9508.

Thanks for the report, let me know if you notice other issues like this in only one language.
