### ISSUE TITLE
how to Change Odoo Default Menu Item View

### ISSUE THREAD

**Issue by bodyx1994** [odoo/odoo#97161]
how to Change Odoo Default Menu Item View
from this [https://i.stack.imgur.com/tV8P3.png](url)
to this [https://i.stack.imgur.com/wtPNN.png](url)
and THX

**Comment by niyasraphy** [comment]
If you need such a view in community you have to develop your own or use any third party apps/theme that brings this in CE.
thanks.

**Comment by Yenthe666** [comment]
Indeed :) Please ask these kind of questions on the official help forum at https://www.odoo.com/forum/help-1
