### ISSUE TITLE
RecursionError: maximum recursion depth exceeded in comparison

### ISSUE THREAD

**Issue by goyanipankaj** [odoo/odoo#97189]
Impacted versions: 14.0 EE

Steps to reproduce: 
- Create 2 warehouse & routes same like in video.
- Create product with routes configuration same like in video.
- Check configuration same like in video

Current behavior: Recursive error.

Expected behavior: I think it's not allow to do configuration if anything wrong then raise warning.
Please check more about this video into how to reproduce this issue/error.
Please let me know how we can sort out this issue.
Because our customer using odoo last from 13.0EE and he is not happy because it's issue last from one week we are facing and we are trying to resolve.

Video/Screenshot link (optional): 

https://user-images.githubusercontent.com/8874012/182124544-1639eea1-2f86-4031-878c-9b91b4085d64.mp4

Support ticket number submitted via odoo.com/help (optional):
Ticker number: #2941742

**Comment by goyanipankaj** [comment]
Support ticket number submitted via odoo.com/help

**Comment by nouraellm** [comment]
Hello,

I confirm what VHZ explained in your ticket.

To solve the problem you need to correct the configuration of your MTO route. We encourage you to review the routes/rules and to read the [documentation](https://www.odoo.com/documentation/14.0/applications/inventory_and_mrp/inventory/routes.html) if necessary.
