### ISSUE TITLE
ir.cron actions are skipped without any log

### ISSUE THREAD

**Issue by FredericoCoelhoNunes** [odoo/odoo#97191]
**Impacted versions:** 15

**Steps to reproduce:**

Not sure how to reproduce it. I simply created a couple of ir.cron actions which I can trigger manually, but that never repeat on their execution date.

**Current behavior:**

In my production Odoo server, all my ir.cron scheduled actions are simply ignored. The "Next Execution Date" passes and nothing happens, the date doesn't change, and nothing shows up in the logs.

A couple of additional details that might help debugging:

* whenever I restart the server and reinstall the app (e.g.: when I deploy a new feature), the ir.cron actions are triggered once if their "Next Execution Date" was in the past. Then the "Next Execution Date" is updated, but it never triggers again as explained above.
* everything works fine in my dev server. This is simply a parallel deployment of Odoo on another machine, it has the exact same configuration with the differences being:
  * the database is a locally running Postgres instance, rather than the more robust option used in production (AWS Aurora)
  * the production server runs as a systemd service, whereas the dev server is launched by simply running the odoo command.
* when I trigger the actions manually, they work BUT the "Next Execution Date" is NOT updated.

**Expected behavior:**

ir.cron actions are triggered on their "Next Execution Date", or if skipped, at least something appears on the logs to help debug.

**Video/Screenshot link (optional):**

**Support ticket number submitted via odoo.com/help (optional):**

**Comment by mrbayati2002** [comment]
Hi @FredericoCoelhoNunes 
Can you share a screen shot of the config that you do in scheduled actions for this cron?

**Comment by FredericoCoelhoNunes** [comment]
Hi @mrbayati2002 , sure!
Here's what I have in the code for one of the actions that is not running:
![image](https://user-images.githubusercontent.com/51457048/183097462-1230efbf-43bf-4370-8bb8-36b7cdfed5c7.png)
and here is what it looks like in the interface (notice how the "Next Execution Date" is in the past!):
![image](https://user-images.githubusercontent.com/51457048/183097536-5c13d866-85e8-4549-a22c-d61709e750b0.png)

The other 3 actions that are failing are configured similarly, let me know if you also want to see them (I thought one would be enough)

**Comment by mrbayati2002** [comment]
Hi,
everything seems alright. Can you add 
`<field name="state">code</field>`
to your cron xml file and check it again.
such https://github.com/odoo/odoo/blob/15.0/addons/account/data/service_cron.xml#L12
this is only thing that I found.
I appreciate that if you find the solution share with us :)

**Comment by mrbayati2002** [comment]
maybe its not related because it works fine when manually executed.
is there anything in the log?

**Comment by FredericoCoelhoNunes** [comment]
Thanks for the tips @mrbayati2002 .

Regarding the logs: absolutely nothing shows up when it passes the execution date - not even an INFO or DEBUG message. I was watching the logs live to ensure I didn't miss anything.
However, as I mentioned, whenever I restart the server/reinstall the app, all the scheduled actions are triggered immediately. Here is what the logs show when the above action is triggered:
```
2022-08-09 09:11:28,497 1787677 INFO odoo odoo.addons.base.models.ir_cron: Starting job `<my job name>`. 
2022-08-09 09:11:28,504 1787677 INFO odoo odoo.addons.base.models.ir_cron: Job `<my job name>` done. 
2022-08-09 09:11:28,504 1787677 DEBUG odoo odoo.addons.base.models.ir_cron: 0.007s (cron <my job name>, server action 701 with uid 1)
```

Also, it seems that immediately after restarting, the cron works at least for some time. I just tested it for a few times in a row (by manually changing the Execution Date to a few minutes from now) and all actions were triggered.
But I know for a fact that after a few days or hours, it stops working, as evidenced by the fact that when I check again in a few days, the Execution Date will be stuck.

Is there a chance the cron "server" stops working after a while and doesn't reboot on it's own? That's the only explanation I have for this behavior...

**Comment by nilshamerlinck** [comment]
Hi @FredericoCoelhoNunes next time it happens, you might want to check if the cron worker is still properly connected to the db:

``` 
$ PGPASSWORD="password" psql -d postgres -h host -U user
postgres=# NOTIFY cron_trigger;
```

A line like this one should appear in logs: `DEBUG ? odoo.service.server: WorkerCron (23623) polling for jobs`

**Comment by FredericoCoelhoNunes** [comment]
@nilshamerlinck thanks for the suggestion, I will do that!
Just a quick question - how should I proceed in case the cron worker is not properly connected to the db?

**Comment by nilshamerlinck** [comment]
I'm not sure :) 

If the cron worker stops working after a while, I wonder if it's not because the aurora pg server has been restarted meanwhile or connection was cut somehow in a way that would not be detected by odoo.

Let us know the result once it happens again ;-)

**Comment by nilshamerlinck** [comment]
Hi @FredericoCoelhoNunes what is your `workers =` configuration value?

**Comment by FredericoCoelhoNunes** [comment]
hi @nilshamerlinck , config is `workers = 0` in both dev and prod.

**Comment by nilshamerlinck** [comment]
Hi @FredericoCoelhoNunes 
- does a `grep psycopg2` on logs give any result? (for errors such as `psycopg2.OperationalError: SSL connection has been closed unexpectedly` or `psycopg2.InterfaceError: connection already closed` that could occur on pg disconnections)
- might be worth trying to run your instance in multiprocessing mode, i.e. [`workers > 0`](https://www.odoo.com/documentation/15.0/administration/install/deploy.html#worker-number-calculation), and see if issue persists

**Comment by FredericoCoelhoNunes** [comment]
Hi @nilshamerlinck , answering your questions:

* The first log in my log file is on `2022-08-15 06:14:54,874`, and ever since that time, neither `grep psycopg2` or `grep polling` shows any result!
* Will give this a shot!

Thanks a lot for spending all this time trying to help me debug, really appreciate it!

**Comment by FredericoCoelhoNunes** [comment]
@nilshamerlinck setting `workers = 4` seems to have worked, at least for the past couple of days the scheduled actions have been running normally!!

**Comment by FredericoCoelhoNunes** [comment]
OK, I've checked and `workers = 4` really appears to have fixed the issue. Quite strange as `workers = 0` is working on the dev server, but I won't question it! Thanks a lot to everyone that helped, I'm closing the issue now.
