### ISSUE TITLE
patch to res_partner_view to use small images in kanban view for sane page load times

### ISSUE THREAD

**Issue by royaladmin** [odoo/odoo#9731]
My friend is uploading pictures of business cards as his contact pictures.

Odoo excellently creates three distinct image copies, the original, a medium size, and a small.

In my friend's case, the full size images can be 250K to 2M.  The smalls are no more than a few K.

The Kanban view for res_partner was fetching the full size images, meaning as soon as my friend had 30 contacts, he was having 36MB page fetches for the Kanban view.

The patch I added in my copy switches 'image' to 'image_small' in three places in the res_partner_kanban_view in res_partner_view.xml.
<field name="image_small"/>
<t t-if="record.image_small.raw_value">
<t t-if="record.image_small.raw_value">
Now his Contacts page loads at regular speed.

My appreciation for your great software.

This second part is an enhancement more than a fix:

My friend also wanted to some how be able to click to see the full size image of the business cards.
I am not sure if there may be a core way to view the big images.  I gratefully followed the snippets in https://www.odoo.com/forum/help-1/question/how-to-open-see-customers-image-in-full-size-74217 and can report complete success, slightly adjusting for Odoo 9 with the bouncy Edit button.

Gratitude for hosting and contributing in the forums.

Jim
For the INTER-DIMENSIONAL-SPACE-PORT

**Comment by mge-odoo** [comment]
Hi,
Thanks for you feedback. The usage of 'image_small' seems reasonable but it seems that we already use it --> https://github.com/odoo/odoo/blob/9.0/openerp/addons/base/res/res_partner_view.xml#L391

In which version are you ?

**Comment by royaladmin** [comment]
Hello,

I am on the origin/9.0 branch.
cd openerp/addons/base/res
git log -- res_partner_view.xml
1e64c660f5afa56e5d7ca04b12c536edf87a5cbd

I see the usage you mention on L391.  The main part of my patch is to L383 to adjust the field that is queried and whose values ride in the fields data response JSON.  Patch also adjusts L390 and L393 to compensate for change on L383.

A side-effect is on L391, with already image_small correct as you mention, and with L383 adjusted to have image_small pre-loaded in the browser, the kanban_image() on L391 generates a very fast data: url for the image_small.

**Comment by mge-odoo** [comment]
Is this https://github.com/odoo-dev/odoo/commit/025fa4791c966cc35ad81f5664f25c8bd0502fb5 fixes the issue ?

Again, thanks for your feedback.

**Comment by algolconsulting** [comment]
up, the issue it's still there, the solution [odoo-dev@025fa47](https://github.com/odoo-dev/odoo/commit/025fa4791c966cc35ad81f5664f25c8bd0502fb5), partially fix the issue, the same thing must be done on the kanban view in the base.view_partner_form template (still in the res_partner_view.xml).

**Comment by mge-odoo** [comment]
Hi,

Again, thanks for your feedback.
The commit https://github.com/odoo/odoo/commit/bf264450576c2aa596287c5225a7371a57a926a0 in master fix the issue.
