### ISSUE TITLE
[9.0] product qty_available doesn't compute

### ISSUE THREAD

**Issue by leopard7777777** [odoo/odoo#9732]
Impacted versions:
- 9.0

Steps to reproduce:
1. create product
2. inventory adjustment
3. upgrade modules and restart
4. stock.quant exists but qty_avaliable does't compute

Current behavior:
- stock.quant records exist
- qty_avaliable does't compute

Expected behavior:
- field computes

sometimes, i upgrade modules, one field in product modules(odoo is compute but not store),store in mine,It won't compute.

**Comment by leopard7777777** [comment]
Now I know why so slow when i browse my product. function field will compute every time. Hundreds of DB query requests each template.. a page will generate tens of thousands of query requests ...I suggest to upgrade field to compute field instead of function field

**Comment by leopard7777777** [comment]
I found this bug.. stock_location record parent_right is worry.....
Maybe you can use compute field (with cache) to improve

**Comment by pedrobaeza** [comment]
It seems that you have manipulated somehow the stock.location table, but this is not reproduced in normal conditions, so I close this issue as no real bug appreciated.

If you reproduce in the runbot infrastructure, that are DBs automatically deployed with all the standard modules installed, accessible in http://runbot.odoo.com/runbot, then please open a new issue with all the steps done before getting the error. Don't be shy to include all the possible details, and even better if you provide some screenshots or videos.
