### ISSUE TITLE
3rd payment acquirer not present in website sales ecommerce and sales module

### ISSUE THREAD

**Issue by tommynguyen1505** [odoo/odoo#97367]
Impacted versions: 15.0

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional): 
Paypal has enabled or test mode

![image](https://user-images.githubusercontent.com/108329449/182560596-b84a965d-da3b-421f-9631-3dce659d4dd0.png)

But not present when paid an order
![image](https://user-images.githubusercontent.com/108329449/182560684-e640e118-a5c1-4d66-9d2b-40da80275c07.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by Feyensv** [comment]
Is this currency in the supported currencies of paypal ?
-> https://github.com/odoo/odoo/blob/15.0/addons/payment_paypal/const.py

**Comment by vava-odoo** [comment]
Supported currencies will be displayed when configuring the provider, including Paypal, with this PR (probably in saas-16.1, not in previous versions) : https://github.com/odoo/odoo/pull/101018
