### ISSUE TITLE
Odoo multi-website improvements debate

### ISSUE THREAD

**Issue by antespi** [odoo/odoo#9745]
This is a start-point for talking about multi-website support roadmap in Odoo. Core support it in v9 and it's backported to v8 in https://github.com/odoo/odoo-extra/tree/8.0/website_multi addon.

What's supported right now:
- Configurable menu per website
- Configurable pages per website
- Configurable layouts per website (header and footer): using website_id (testing pending in v8)
- Configurable products/products categories per website, in order to have several e-commerce shops in the same company/database: using user_id and record rules (testing pending)

What's NOT supported right now:
- Configurable options per website (Show sign in, show logo, automatic footer, ...)
- Configurable theme per website (one with Enark other with Graphene, for example)
- Website creation wizard, for creating top menu, homepage, contact us, ... base pages in order to start editing afterwords.
- Pages management tree view, in order to have a list of all pages in a website

There are several issues to take into account:
- Several addons (themes, website_sale, ...) inherit from `website.layout` in order to add JS, CSS, HTML blocks, ... If you install two theme addons, then they fight for adding static assets and result is a mess.
- We can not create a new layout per website (for example for personalizing header and footer), because then all addons (themes, website_sale, ...) inheriting `website.layout` will not add custom content in the new layout.
- Active/deactive options are the same as active/deactive views, but this is applying to all websites, unless `customize_show = True` views were re-created when website is created.

Possible design solution:
- Create a website template model (for example `ir.ui.view.template`). Similar to `account.account.template`. This model will save website template from addons.
- Create a theme model (for example `ir.ui.theme`) in order to have a theme list
- Add a field 
- Implement a wizard for creating a new website that:
  - Create a website related views from website template filtering by theme
  - Associate these views to the new website
  - Create an empty homepage
  - Create a top menu with an entry 'Home' pointing to homepage
- Implement a wizard for sync new views added to `ir.ui.view.template` into an exists website, not overwriting already edited views by user.
- Addons inheriting from website addon will add views to `ir.ui.view.template` and then sync them to default website.
- Change/extend `t-call` Qweb tag implementation (or create a new `t-call-website` tag), in order to load qweb templates associated with current website, only in website requests. Take in account that with these implementation there is one `website.layout` per website, so we have to use `key` and `website_id` fields, not `xml_id` field, like we currently do for pages.
- Change/extend `t-call-assets`Qweb tag implementation (or create a new `t-call-website-assets` tag), in order to minify assets filtering by website.
- Define an environtment attribute to known which website is executing this controller, reading this model, or rendering this view. This allow to implement multi-website aware addons.

This are just a preliminar ideas, suggested to change and opinions. That's why I launch this issue, to talk about it, because we can not compare Odoo multi-website with Wordpress or Joomla multi-website systems.

This implementation is similar to multi-company or multi-currency. This is transversal to Odoo. So I suppose that this implementation will be welcome in `master` branch, in order to be ready for v10 version.
Then, after success we can implement a backport to v9 and v8.

Any opinions, questions, suggestions?
Thanks

**Comment by lukebranch** [comment]
@antespi ,

I've got nothing useful to add to the discussion in terms of what you've suggested, I think your list pretty much covers most of the questions i've had regarding multi-website in Odoo.

I've often wondered about how to assign different themes and modules per website as well in 8.0 and 9.0. It would be great if it could achieve the same functionality/granularity as magento with it's inheritance mechanism for themes (base > website > store > store view).

In Hong Kong and China for example there are many companies that operate multiple business entities, each with one or more websites per business entity, that require different website themes, pages, multi-language per website, different views per language/store view.

Currently I cannot figure out how to achieve this in 9.0, and have not even attempted to try and figure out how to achieve this in 8.0.

**Comment by rafaelbn** [comment]
@lukebranch We have this is Odoo v8, both are same database, and same company, two themes:

- https://www.valquejigoso.com
- https://tienda.valquejigoso.com/

So this issue is very useful and of course we can achieve it. Odoo will be much more better than Magento very soon.

I will have more example in multi-website in a short time.

Let's Odoo talk ;-) :+1:

**Comment by Yajo** [comment]
There's still one more problem you did not mention. What about controllers?

For example, if you install `website_crm`, it creates some of them, such as `/crm/contactus`, but it could happen that you want to have it for one website and not for another. Or maybe you want a blog in one website and a shop in another...

And what about the views created by those modules? If I install a module that adds views in a multiwebsite database, should it create the same view in each website? Should I choose?

I guess controllers should have also their own model with a One2many to websites, and allow to en/disable them in concrete websites.

BTW, `/crm/contactus` renders a view on failure, but which one in case of a multiwebsite?

And about making multiwebsite-aware addons... I think Odoo should be multiwebsite-aware by default (although one of them would be the *default*), and then all addons would be automatically compatible. Only 1 website? No problem. Of course in v>=10.

An easy UX IMO would be:

- You get to your Odoo server from a different URL.
  - Do you have admin rights for website module?
    - Yes.
      - Dialog: *We detected you logged in from a different domain. Is this a new website?*
        - Yes.
          - Website creation dialog.
        - No.
          - `exit()`.
    - No.
      - `exit()`.
  - No.
    - `exit()`.

```
def exit(self):
  # Render default website
  [...]

  if self.env.user.has_website_admin_rights():
    # Add current domain to known domains of current website
    [...]
```

**Comment by lisandi** [comment]
@rafaelbn Nice your examples and they also prove that multi-website is working as multi-lingual too. Thanks for sharing.

Probably you could address a seo friendly url for sites to i.e. without that /page/ or with a definable /slides , /blog etc path segment, which is multilingual to.

**Comment by antespi** [comment]
@Yajo, you're right, using an environtment variable for knowing which website is being calling: 
> Define an environtment attribute to known which website is executing this controller, reading this model, or rendering this view. This allow to implement multi-website aware addons.

Your UX example is great!

In my propusal, there are two kind of views created by a website addon:
* Ones for backend, the typical ```ir.ui.view``` objects
* Ones for multi-website frontend, ```ir.ui.view.template``` objects

After installation, user can copy  ```ir.ui.view.template``` as ```ir.ui.view``` objects relating them with the website he wants, using:
> Implement a wizard for sync new views added to ir.ui.view.template into an exists website, not overwriting already edited views by user.

**Comment by antonylesuisse** [comment]
@antespi correction about what is supported now:

What is supported now 

- Configurable layouts per website (header and footer): use website_id
- Configurable products/products categories per website, in order to have several e-commerce shops in the same company/database. use user_id and record rules

What's NOT supported right now:

Configurable options per website (Show sign in, show logo, automatic footer, ...)
Configurable theme per website (one with Enark other with Graphene, for example)
Website creation wizard, for creating top menu, homepage, contact us, ... base pages in order to start editing afterwords.
Pages management tree view, in order to have a list of all pages in a website

**Comment by antespi** [comment]
@antonylesuisse Thanks for your points, I'm going to test them in v8 too. I've just updated initial comment in order to include it

**Comment by lisandi** [comment]
@Yajo
In TYPO3 this example gets solved with domain records which you can assign to each page and they are valid for the branch the page with the domain record is the top of.
This way you can even assign subdomains t a certain page inside TYPO3 (so we could do the same in Odoo) which you than can redirect with parameters i.e, 200, 301 etc to the correct domain or page.
The first request is coming to the index file and than it is looking for a domain record and if non exists like the one the visitor is looking for than the default page will be chosen. (first page in the Tree = which reflects also the menu. And you can set pages on hide or not in menu or set a internal or external redirect.

We run one installation with 400 church communities in one single TYPO3 database. Odoo would be actually much better for their purposes as it would offer also the complete management for all kind of necessary businesses and administration tasks.

**Comment by lukebranch** [comment]
@rafaelbn ,

Nice work!

I'll keep a close eye on this thread to see how this develops in the context of >=Master/10.0 and backporting to 9.0/8.0.

**Comment by antespi** [comment]
@antonylesuisse Your suggestion for getting two ```website.footer_custom``` doesn't work in v8, because  ```_check_xml``` throws an exception:
```
'Field(s) `arch` failed against a constraint: Invalid view definition\n\nError details:\nElement \'<xpath expr="//div[@id=\'footer_container\']">\' cannot be located in parent view\n\nError context:\nView `Footer`\n[view_id: 2298, xml_id: n/a, model: n/a, parent_id: 894]'
```

This is because there are two views with this XML:
```
<data inherit_id="website.layout" name="Footer">
  <xpath expr="//div[@id='footer_container']" position="replace">
    <div class="oe_structure" id="footer"/>
  </xpath>
</data>
```

The firts one remove ```<div id="footer_container">``` element and the second one doesn't find it. Footer duplication is running well in v9

**Comment by antespi** [comment]
@antonylesuisse well, in v9 duplicating footer view is working because its XML is:

```
<data inherit_id="website.layout" name="Footer">
    <xpath expr="//div[@id='footer']" position="replace">
        <div class="oe_structure" id="footer">
            <section>
                <div class="container">
                    <div class="row">
                        <div class="col-md-4">
                            <h4 class="mt16">Subtitle</h4>
                            <p>
                                <a href="/">Homepage</a>
                            </p>
                        </div>
                        <div class="col-md-4">
                            <h4 class="mt16">Subtitle 2</h4>
                            <p>
                                ...
                            </p>
                        </div>
                        <div class="col-md-4">
                            <h4 class="mt16">Subtitle 3</h4>
                            <p>
                                ...
                            </p>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </xpath>
</data>
```

And then it's writing ```<div class="oe_structure" id="footer">```, so both divs has the same id. So the first replace the element and the second replace it again.

But it you set an scenario like this:
* Two websites "Website A" (website-a.yourdomain.com) and "Website B" (website-b.yourdomain.com)
* Duplicate ```website.footer_custom``` view twice
* First footer is "Footer A" and its website_id is  "Website A". Its xml_id is blank. Modify its contents, for example, first column is now "Subtitle A"
* Second footer is "Footer B" an its website_id is  "Website B". Its xml_id is blank. Modify its contents, for example, first column is now "Subtitle B"
* Go to a browser: https://website-a.yourdomain.com At footer you'll see "Subtitle B"
* Go to a browser: https://website-b.yourdomain.com At footer you'll see "Subtitle B"
* See page view using Customize > Editor HTML and all footers appear in the views list

How do you set different footers per website in v9?

**Comment by antonylesuisse** [comment]
@antespi You are right, multiwebsite works for simple static pages (key,website_id) is the unique key. But it fails when you start using inherit_id. We need to fix that first.

**Comment by antespi** [comment]
@antonylesuisse I'm searching for it in master branch. I'll PR with a fix as soon as possible. Thanks.

**Comment by treviser** [comment]
I have one new client and several prospects which have one legal entity with 2 or more different restaurants with different names, differents POS, different menus (products and product categories), different domain names (i.e. onerestaurant.com, anotherrestaurant.com, thirdrestaurant.com). Is it possible at all the realise this scenario with 9.0 multi website? Can I still use dbfilter?

**Comment by antespi** [comment]
@treviser, in v9 multi-website support is limited. OCA team are working for supporting it transversally in v8 (this work is as fast as we can), but I don't know if oficial Odoo headquarter is working on it too. 

Please, @antonylesuisse could you share with us your roadmap in this topic?
Thanks

**Comment by lisandi** [comment]
On Thu, Dec 10, 2015 at 9:01 PM, Antonio Espinosa <notifications@github.com>
wrote:

> but I don't know if oficial Odoo headquarter is working on it too.


Why don't you ask them and collaborate instead of reinventing wheels a
multiple times.


With kind regards,
Mit freundlichen Grüßen,
Con un cordial saludo,
Cordialement,
с сердечным приветом,
เรื่องที่เกี่ยวกับชนิด,
與親切的問候,

 *ANDI BECKER*

CEO/General Manager LisAndi Co., Ltd.

*about.me/andibecker
<http://about.me/andibecker>--------------------------------------------------*
*LisAndi Co. Ltd.*, Phuket, Thailand (lisandi.com)
15/21 M.2 Viset Road, Rawai, Muang, Phuket, Thailand 83130

Mobile: +66 (0)81 606 3378
VoIP:   +49 (0)711 50 88788 50
Fax:     +49 (0)711 50 88788 50
Skype:          lisandi
Facebook:     andibecker
Google Talk/Facetime/eMail:  andi@lisandi.com

--------------------------------------------------
This email may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this email by mistake),
please notify the sender immediately and destroy this email. Any
unauthorized copying, disclosure or distribution of the material in this
email is strictly prohibited. Email transmission security and error-free
status cannot be guaranteed as information could be intercepted, corrupted,
destroyed, delayed, incomplete, or contain viruses. The sender therefore
does not accept liability for any errors or omissions in the contents of
this message which may arise as a result of email transmission

**Comment by treviser** [comment]
@antespi thanks for the clarification. @antonylesuisse: do you have any hints for information about the supported feature of multi website in 9.0 (CE and EE), and: can I use it with dbfilter?

But to stay on topic, could the efforts of Organizational Units (https://odoo-community.org/groups/contributors-15/contributors-29207?mode=thread&date_begin=&date_end=) of relevance for this discussion?

**Comment by jbeficent** [comment]
@treviser Operating Units would be a split of the company from a management perspective. So you could potentially assign OU-specific website themes, products,.. What is important to understand in the OU approach is that warehouses are OU-specific, so that ownership of stock is held at OU level. That may be a hard criteria to define when you need to manage by OU.

If products and product categories can be website-specific, by user_id, then there's no need for the OU at website level.  Perhaps mapping that user_id with a corresponding OU would help attract the correct OU when a sales order is created from the website.

**Comment by treviser** [comment]
Thanks Jordi, I'm starting to see it clearer. For me it seems only logical, that OUs must have ownership of stocks in order to calculate COGS per OU, which is in my opinion one of the most important goals to achieve with OUs. If it is possible to link user_id with OUs, together with the functional coverage you have proposed in your discussion paper, this would lead to a great and comprehensive solution.

**Comment by rafaelbn** [comment]
Hi,
"Odoo multi-website improvements debate" is the topic of this issue an not "Odoo Operating Units improvements debate".
Please maintain clear the issue and open a new one with other topic
Thanks

**Comment by avanzella** [comment]
Hello,
I'm currently developing a v9 configuration with a single database, 3 companies (1 mother and 2 childs) and 3 e-commerce shops.
Adding a company_id in the product.public.category model and defining different public users per website together with a record rule is working fine for the public visitors.
But how to sort out the situation for the portal users?
How to get a single portal user to log in the different shops and see the related product categories?
Is there a way to force the portal user company_id depending of the domain?
Thanks for your feedback.

**Comment by JosDeGraeve** [comment]
Hi,

Imho, the best way to avoid a mess, is to have separate portal users ( and
res.partner records ) for each company.

Regards,

Jos De Graeve - Apertoso business ICT

http://www.apertoso.be/

Guido Gezellelaan 16 - B-9800 Deinze - Belgium

Direct: +32 9 381 64 51
General:+32 9 381 64 50
Mobile: +32 475 54 68 80
mail/im/skype: Jos.DeGraeve@apertoso.be - apertoso

2016-04-04 10:52 GMT+02:00 avanzella <notifications@github.com>:

**Comment by avanzella** [comment]
Hi Jos,
Thanks for your return.
Straight forward solution indeed but it forces the client to have a separate email address for each company...
Regards

**Comment by JosDeGraeve** [comment]
Hi,

That restriction might be easier to lift then reworking the multicompany
access rules.

Regards,

Jos De Graeve - Apertoso business ICT

http://www.apertoso.be/

Guido Gezellelaan 16 - B-9800 Deinze - Belgium

Direct: +32 9 381 64 51
General:+32 9 381 64 50
Mobile: +32 475 54 68 80
mail/im/skype: Jos.DeGraeve@apertoso.be - apertoso

2016-04-04 17:29 GMT+02:00 avanzella <notifications@github.com>:

**Comment by avanzella** [comment]
There is another issue occurring with multi-website / e-commerce configurations and Paypal paiement acquirer.
The return URL seems to be linked to the web.base.url. Therefore, despite using different Paypal accounts, the return URL from Paypal is "forced" to the web.base.url root and not the actual website domain.
Eg.: 3 domains web1.com, web2.com, web3.com - when doing a Paypal payment from web3.com, if the web.base.url is web1.com, the return URL will be web1.com/payment/paypal/dpn/ which is obviously raising an error...
Any idea on how to solve this issue?
Regards

**Comment by JosDeGraeve** [comment]
If you have odoo enterprise, you can have it fixed by odoo because it's a
bug.
Otherwise this will need to get fixed in a custom module.

Regards,

Jos De Graeve - Apertoso business ICT

http://www.apertoso.be/

Guido Gezellelaan 16 - B-9800 Deinze - Belgium

Direct: +32 9 381 64 51
General:+32 9 381 64 50
Mobile: +32 475 54 68 80
mail/im/skype: Jos.DeGraeve@apertoso.be - apertoso

2016-04-04 18:44 GMT+02:00 avanzella <notifications@github.com>:

**Comment by avanzella** [comment]
I do have Odoo Enterprise, but I have to say that my experience with their technical support has been very disappointing with regards to the investment (minimum 1200 €).
As a Enterprise subscriber you are not entitled to any functional nor technical support.
So...

**Comment by brychmilan** [comment]
@rafaelbn 
Hello Rafael, do you have some describe how you achieve subdomain routing in Odoo please? 
This feature I find long time and will be perfect if Odoo can do this.

Thank you very much.
Milan

**Comment by treviser** [comment]
It looks like the multi-website experts are gathered here. I urgently need (paid) help and in a first step an assessment of the feasibility in general, would anybody of you experts like to chime in:
https://www.odoo.com/groups/community-59/community-27068668

**Comment by lukebranch** [comment]
@treviser ,

Have you had any luck with this? I also have some customers (Odoo 10.0c or 11.0c when it's released) who would really like to implement at least one of the following scenarios:

Single Odoo DB, Single Legal Entity (ie. not multi-company mode), multiple websites and storefronts:
In this scenarios we have a trading company who is the sole distributor for their region and will run websites for specific brands under their control along with their own distributor website.

Each store should be able to display it's own products, categories, and have it's own theme.

Single Odoo DB, Multiple Legal Entity (ie. multi-company mode), multiple websites and storefronts.

I believe even partial support for multi-website may be ok for them as long as they understand what to expect out of a multi-website implementation with Odoo.

**Comment by treviser** [comment]
@lukebranch 
The discussion in the mailing list was not as fruitful as expected, especially I did not receive any concrete proposals.
My scenario is:
Single Odoo DB, single legal entity, multiple Organziational Units (OCA OUs), multiple websites and storefronts, multiple POS.
Based on the discussion I believe that multiple legal entities or OUs should not make the big difference.
I have my first customer, but a very tight budget to start with.
My intention now is to start with the first website/storefront/OU and POS (manually and quick and dirty), after the realisation of this I will have some more budget.
My idea is to start with Axel Mendoza @aek as a guide to step-by-step directives on how to set this up based on all information I have gathered so far. Something like:
- how to activate multi-website mode in 10c
- how to set up public users
- how to prepare existing website themes for multi-website use (copying and renaming templates etc)
- how to set up the OU and corresponding users
- how to set up dbfilter (if possible at all) in a multi-db environment
- how to set up website sales teams
etc.
I have a budget of USD 400 for these first steps and an additional USD 800 when starting with the second OU. I had a first contact with @aek about general availability and capability to support, but not more concrete yet.
If we could join forces, I'll be more than willing to cooperate.

**Comment by treviser** [comment]
I don't know if you are aware that [PR1](https://apps.odoo.com/apps/modules/browse?author=PR1) recently released a couple of modules for multi-website etc.. These modules are quite costly and I don't know how to assess them without knowing more about their approach and realization.

**Comment by lukebranch** [comment]
@treviser ,

Brilliant, thanks for the heads up! I noticed those yesterday while digging around. I'll try reach out to them to discuss and see if I can arrange some sort of demonstration and discussion.

They are rather costly modules, I agree, however i'm certainly interested in what they've done regardless.

Once I hear back i'll update this thread with more information on my discussion with them.

I've seen a fair bit of refactoring around the website module including abstracting the portal away from the website module here:

https://github.com/odoo/odoo/pull/17100/files

which is very interesting. It would be really great if we were able to see some changes related to allowing at least partial support of the multi-website functionality within Odoo in 11. I'll be watching the PR's closely towards October, hopefully the guys in Odoo R&D are listening, and they pull something out of their sleeves for the 11.0 release.

**Comment by Yajo** [comment]
@sebastienbeau Presented recently Shop Invader, a project that aims to fix all of this, although it's not production-ready yet AFAIK.

Maybe he wants to introduce it here and point interested users to the correct communication channels about the project.

**Comment by lukebranch** [comment]
I remember discussing something similar to this (Odoo/OpenERP > Locomotive CMS) with I believe Raphael (@)rvalyi many years ago here:
https://github.com/akretion/connector-search-engine/issues/3

I'd definitely be very interested in something like this if there is an ongoing project underway.

**Comment by nafex** [comment]
There is a question about Multi-Website on "Ask Me Anything w/ Odoo CEO Fabien Pinckaers": https://youtu.be/7iRySgJYS8Y?t=1h8m50s
at 1:08:50
Its on Odoo's roadmap but it seems it will be available only on v12...

**Comment by lukebranch** [comment]
@nafex ,

That is excellent news, thank you!

I was meaning to watch the AMA when I could find a bit of time. Thanks for the link, that is excellent news that there it's on the roadmap for a near-future release.

I really hope they can finish development in time for a version 11.0 release.

**Comment by Yajo** [comment]
Those of you interested in this, there you have support for applying a different theme per website: https://github.com/OCA/website/pull/354. Also a little related fix for Odoo: https://github.com/odoo/odoo/pull/17635. Regards.

**Comment by Yajo** [comment]
Aforementioned PR was merged, and [`website_multi_theme` module is widely available](https://www.odoo.com/apps/modules/10.0/website_multi_theme/), courtesy of @Tecnativa.

**Comment by Yenthe666** [comment]
Good job guys! @antespi and @Yajo would you guys mind me closing this report? @antonylesuisse do you want to provide anymore info/details?

**Comment by pedrobaeza** [comment]
You can close it although there's still work to do for integrating this on core.

**Comment by Yenthe666** [comment]
Agreed - I'd suggest somebody to create a new report on the tracker for V11 that is updated and relevant for V11. I'll make sure it gets attention from there on, just ping me.

**Comment by Yajo** [comment]
11.0 migration is on the way: https://github.com/OCA/website/pull/398
