### ISSUE TITLE
[15.0] [mail] Users cannot schedule activities (for other users) on models for those they have no write permission

### ISSUE THREAD

**Issue by jabelchi** [odoo/odoo#97457]
**Impacted versions:** 
Tested in V13 and V15

**Steps to reproduce:**
- User 1 belongs to group "See Subscriptions".
- He schedules an activity for himself on a subscription --> OK
- He schedules an activity for another user on a subscription --> NOT OK --> He gets the message: 

_You are not allowed to modify 'Subscription' (sale.subscription) records.
This operation is allowed for the following groups:
- Subscriptions/Administrator
- User types/Portal"_

**Current behavior:**
The user gets an error message when scheduling an activity for another user in a model he don't have write access to. 

**Expected behavior:**
The user can schedule an activity for any other user, even if they do not have write permissions for the model.

**Comment by jabelchi** [comment]
This is still a problem for us. Any solution?

**Comment by dalaOdoo** [comment]
@jabelchi there is the posibility to put a property _mail_post_access on the python class.

Here is an example : https://github.com/odoo/odoo/pull/45629/files.

I will investigate the possibility to add that on "sales order class" but it means also giving the right to add a message in the chatter. 
I will also send your feedback to our PO of activities as we may want a different level of right for activities than messages.
