### ISSUE TITLE
[8.0] api: Ignored domain in many2many fields

### ISSUE THREAD

**Issue by moylop260** [odoo/odoo#9747]
Steps:
1. Go to Menu: Sales -> Configuration -> Products categories & atributes -> Product categories
2. Create a new route with `product_categ_selectable=False`
   ![product categories odoo](https://cloud.githubusercontent.com/assets/6644187/11408275/0d514024-9386-11e5-9d44-c908a1c241d1.png)

![product categories odoo2](https://cloud.githubusercontent.com/assets/6644187/11408319/449c2814-9386-11e5-87d5-6f9d92130d9c.png)

![product categories odoo 3](https://cloud.githubusercontent.com/assets/6644187/11408330/60762a76-9386-11e5-8026-357ea2446109.png)

Saw:
 Value with different domain assigned

Expected:
 Values with different domain don't assigned

Environment:
 http://115127-8-0-1c5c25.runbot8.odoo.com/

**Comment by Yenthe666** [comment]
Hi @moylop260,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
