### ISSUE TITLE
[9.0] Point of Sale - Product Quantities - No localization and Incoherence

### ISSUE THREAD

**Issue by airitos** [odoo/odoo#9748]
In the Point Of Sale V9 very last build (2015/11/26) when you select a product, the quantity (shopping cart area) displays "1" but right after you click again in the same product now quantity displays "2.000" and here there are 3 issues:

First:
There must be coherence in the display of the quantity, if more the one quantity shows X.000 a single unit should display 1.000 also.

Second:
Quantity is not localized (formatLang). Portuguese localization (and most of Europe) uses the dot (.) as thousands separator, so 5.000 for us is not five unit of but five thousand units of. To check this you can load the Portuguese language or you can temporally configure a comma for decimal separator in the en_US default language and than you can check quantities in the inventory module and after in the Point Of Sale.

Third:
Quantity in Point Of Sale shopping cart does not respect the Decimal Accuracy defined for "Product Unit of Measure". If you check in the inventory module, the product quantities complies with the decimal accuracy defined for "Product Unit of Measure". Check "Settings -> Technical -> Database Structure -> Decimal Accuracy. In our customer there is nothing to scale, no products with weight so they do not need all that zeros after the quantity. So change this decimal accuracy to zero and check what I am talking about.

Furthermore all the issues above are transferred to the receipt report printed int the thermal printer.

Before anyone says that quantities is not mean to be localized and compliance with decimal accuracy let me state this:
We are Angolan partner and sell in Angola. In Angola, localization same as Portugal, we use dot (.) for thousands separator and comma (,) for decimal separator and yes, we need thousands separator because we deal with big numbers in our currency AOA. For example I pay 4.000,00 AOA (four thousand kwanzas to fill up my car in the gas station) 1 USD = 134 AOA
So we have big numbers, we need thousands separator and we do not need quantities with decimal size of 3 when our customer does not scales a thing, no products with weight.
Current scenario leads to ugly and unformatted receipts getting out from thermal printer.

Kind Regards

**Comment by jorenvo** [comment]
Hi,

The first issue you described was fixed in 4b003afd0ab125b0296de8939626ae889ccdab47. The second issue was fixed in multiple commits of which the first one was 261ccf7c56062930b1d712ae860fe01dd8718968. The third issue was solved in a6ad7b9b250c6f1f6f11c93318da9149e0814863.


Kind regards,
Joren
