### ISSUE TITLE
Typo in German Translation of HR

### ISSUE THREAD

**Issue by Baenz-Ledin** [odoo/odoo#97509]
Impacted versions: 15

Steps to reproduce: Open an Employee

Current behavior: On the top right it says "Studenzettel"

Expected behavior: should say "Stu**n**denzettel"

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by Yenthe666** [comment]
You can request access to Transifex (https://explore.transifex.com/odoo/) and fix the translated term there :) It's not managed by Odoo SA itself in fact but done on a voluntary basis.

**Comment by Baenz-Ledin** [comment]
Thanks, I just fixed it.
