### ISSUE TITLE
[9.0] list_view.js do_delete bug

### ISSUE THREAD

**Issue by leopard7777777** [odoo/odoo#9751]
Impacted versions:
- 9.0

Steps to reproduce:
1. There are 100 items
2. delete a page (80 items)

Current behavior:
- self.$pager.find('ul li:first a').trigger('click');     BUG
- self.$pager.find('ul li:first a') is null

Expected behavior:
- do_delete function
- Before trigger,load next page

**Comment by ged-odoo** [comment]
I cannot reproduce your bug.

Could you give some more information: 
* what version are you using? (enterprise/9.0? community/9.0?)
* where in odoo does this happen? in which application/view/action?
* where do you click exactly? do you select all the records and click on the delete button in the action submenu?

**Comment by leopard7777777** [comment]
I click on the delete button in the action submenu (product_template list view)
I found load the record of product_template costs a few seconds.. beacause of the many compute field(I add,or odoo) ...is about at least 3 sec each page.
The bug will reporduct occasionally...Not every time...so I just add 

- self.update_pager(self.dataset);

before self.$pager.find('ul li:first a')
 
I think maybe depends on load cost and delay 

Thanks so much for response...

**Comment by pedrobaeza** [comment]
This has been improved in latest v11 version with the view rewritten, and now pager and current record is updated properly after deleting a record, so we can consider this solved by this enhancement.
