### ISSUE TITLE
[8.0] Change image with binary field in new API needs page refresh

### ISSUE THREAD

**Issue by adrienpeiffer** [odoo/odoo#9753]
I created a model in which I would like to add images. I inspired product.template
The code looks like this in the new api : 

``` @api.one
    @api.depends('image')
    def _get_medium_image(self):
        self.image_medium =\
            tools.image_get_resized_images(self.image)['image_medium']

    @api.one
    @api.depends('image')
    def _get_small_image(self):
        self.image_small =\
            tools.image_get_resized_images(self.image)['image_small']

    @api.one
    def _set_image_from_medium(self):
        self.image = tools.image_resize_image_big(self.image_medium)

    @api.one
    def _set_image_from_small(self):
        self.write({'image': tools.image_resize_image_big(self.image_small)})

    image = fields.Binary(string="Image")
    image_medium = fields.Binary(compute='_get_medium_image', inverse='_set_image_from_medium',
                                 string="Medium-sized image", store=True)
    image_small = fields.Binary(compute='_get_small_image', inverse='_set_image_from_small',
                                string="Small-sized image", type="binary",
                                store=True)
```

when I change the medium image in the form view, and I come back in the kanban view. the image is correctly displayed in the form view but it is always the old image in the kanban view. After a refresh, the image is displayed correctly (A browser refresh is necessary, a simply click on the menu to reload the action doesn't work). In product.template in which the code is written in old API, it is not necessary to refresh the page.

@rco-odoo any idea ?

**Comment by rubencabrera** [comment]
Hello, can you post the view code? I can't seem to reproduce the behaviour.

**Comment by Yenthe666** [comment]
Hi @adrienpeiffer,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
