### ISSUE TITLE
Error on report change page

### ISSUE THREAD

**Issue by hurrinico** [odoo/odoo#9754]
Hi,
on runbot i've done the following steps:
- I create a product 'test_product' with a very long sale description
- i create a Sale Order with product's line test_product
- I print the Order

Watching the report you can see that description overwrite the header's table.

Best Regards

**Comment by sle-odoo** [comment]
It is due to wkhtmltopdf. It'll automatically move the cells across pages so that printing a table doest not cut it right of a middle of a sentence like google chrome does, but if a cell is too big too fit on a page, strange things happen. Not much we can do. Regards.
