### ISSUE TITLE
[8.0] sale_margin Sale order margin is wrong is you use Unit of Sale

### ISSUE THREAD

**Issue by ManLopez** [odoo/odoo#9756]
Impacted versions:
- 8.0

Steps to reproduce:

1) Activate "Allow using different units of measure " in Settings -> Configuration -> Sales
2) Activate "Manage Secondary Unit of Measure " in user settings
3) Create a product "PRODUCT TEST" with following data:
Unit of Measure (uom_id): Kg

Sale price (list_price): 5€/kg

Purchase Unit of Measure (uom_po_id): Kg

Cost Price (standar_price): 2€/kg

Unit of Sale (uos_id): Box

Unit of Measure -> UOS Coeff (uos_coeff) : 0,05 (each box weights 20 Kg, so coeff. 1/20=0,05)

4) Create a new sale order
5) Insert a line of PRODUCT TEST with quantity 1 Box (UoS)
6) Calculate (refresh) the sale order, so sale order margin can be computed.

![captura0](https://cloud.githubusercontent.com/assets/16029392/11420045/c831384a-942b-11e5-90aa-35ff31b44d14.JPG)
![captura1](https://cloud.githubusercontent.com/assets/16029392/11420067/e4bcdc6c-942b-11e5-86b3-17417deb5cc7.JPG)

Current behavior:
- Margin: 98€

Expected behavior:
- Margin: ((20 x 5) - (20 x 2)) = 60€ 

It seems that it is mixing apples and oranges, because is calculating the margin as follows:

[1 uos x 100 € (uos unit price)] - [1 uos x 2€ (uom standard cost price)] = 98€

what is obviously wrong, if you use unit price of the uos you should use cost unit price of the uos, or it can be also used both uom for unit price and cost price.

**Comment by SaFi2266** [comment]
Hello,
I faced same issue but with negative margin where:
produck X with
uom = pcs
uom cost price = 5.97
uom sale price = 7.2
uos = square meter
uos coeff = 1.5

when sale 50 pcs of product X 
50 x 7.2 = 360
where margin as I understand is
7.2 - 5.97 = 1.23 then the expected margin is 50 x 1.23 = 61.5
**BUT** I get **-88.4** as a margin

when don't use uos everything works fine 

Regards,

**Comment by Yenthe666** [comment]
Hi @ManLopez,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
