### ISSUE TITLE
[9.0] Error when new Application HR Recruitment

### ISSUE THREAD

**Issue by thanhchatvn** [odoo/odoo#9757]
Today i process new Application inside Recruitment App
1. New job Position >> Ok Done
2. New Application >> And i on change Job , after browse show me error
3. please check source : hr_recruitment>>models>>hr_recruitment.py line 232, function _onchange_job_id_internal

We're can not set stage_id = ....ids[0]
Because if not stage in database, can not return ids, ids is None, can not get ids[0]

![selection_008](https://cloud.githubusercontent.com/assets/3313064/11420942/04cf3102-9464-11e5-81b1-f59c82999a0f.png)
![selection_009](https://cloud.githubusercontent.com/assets/3313064/11420943/0523c83e-9464-11e5-84e4-2db52f02f6ee.png)
![selection_010](https://cloud.githubusercontent.com/assets/3313064/11420944/05251978-9464-11e5-8328-bc3ff7e34888.png)

**Comment by xmo-odoo** [comment]
Could you try updating to a more recent revision? All applications were given at least one stage by default in revision ed3d6aff, but the initial code as of a805e091 didn't have a default for `stage_ids` so if your checkout happened between these you could get a job position with no stages even if you didn't manually delete them.

**Comment by jorenvo** [comment]
Hi,

As mentioned by @xmo-odoo this issue was probably resolved in ed3d6aff8196f5f270b0a77a0076fd6e75f28d55. If the issue persists don't hesitate to reopen this issue.


Kind regards,
Joren
