### ISSUE TITLE
[8.0] onchange in model.py crashes for forms with multiple levels of nesting

### ISSUE THREAD

**Issue by NL66278** [odoo/odoo#9762]
When an onchange is triggered through creating a record in yaml import, the onchange handling will crash when the form passed for the model, or the default form, contains multiple nesting of levels for one2many fields.

The code for collecting onchange methods in model.py, the function def _onchange_spec(self, view_info=None): will descend into all levels of nesting. However the function def onchange(self, values, field_name, field_onchange): will trigger an exception on the line with name, subname = dotname.split('.'), because the fieldname will contain more then one dot.

This occurs even if the nested field has no onchange method attached at all, because all nested fields are collected and added to the huge field_onchange dictionary. This also seems not very efficient to me, apart from the crash.

**Comment by Yenthe666** [comment]
Hi @NL66278 ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
