### ISSUE TITLE
OWL dev mode

### ISSUE THREAD

**Issue by lavrenkov-sketch** [odoo/odoo#97670]
Impacted versions: 15

Steps to reproduce: open browser debug tools

Odoo always run OWL in dev mod inside production docker. How fix it?

![Снимок экрана от 2022-08-08 10-16-14](https://user-images.githubusercontent.com/52679491/183361224-a23c21ca-1065-4576-9ed5-a234c59e7afb.png)

**Comment by jorenvo** [comment]
You are probably in developer mode. Leaving it will take OWL out of dev mode as well:

![image](https://user-images.githubusercontent.com/10252581/183773990-23e0476a-1a97-44ba-96af-a8370132ef3e.png)
