### ISSUE TITLE
XMLRPC error - KeyError: 'user_id' by requesting field manager_id

### ISSUE THREAD

**Issue by ArthurBorsboom** [odoo/odoo#9771]
Odoo: 9.0-20151109
Database: clean DB without demo content
Apps installed: only Project Management
Model: project.task
Action: execute_kw + search_read
Filter: project_id = 1
Requested field: manager_id

This gives a XML RPC Exception with traceback ending in: KeyError: 'user_id'

**Comment by pedrobaeza** [comment]
AFAIK, this is not failing, but there's not enough information, so I'm going to close it. If the problem persists, please open a new issue giving more information, and not stripping traceback.
