### ISSUE TITLE
[auth_ldap] TLS doesn't work

### ISSUE THREAD

**Issue by qtheuret** [odoo/odoo#9772]
**LDAP authentication with TLS doesn't work**

Impacted versions:

 - 8.0
 - 9.0

Steps to reproduce:

 1. install the auth_ldap module
 2. configure the LDAP service on the company form
 3. Set 'use TLS' as True
 3. try to connect with a LDAP user

Current behavior:

 - Cannot connect to LDAP server when conn.start_tls_s() is ran.

Expected behavior:

 - The LDAP authentication should work as expected with TLS.

Some other information:
  - If I modify the source code to use 'ldaps' instead of 'ldap' in server uri and not run conn.start_tls_s(), it works well.

**Comment by mart-e** [comment]
@qtheuret See the launchpad report [lp:389033](https://bugs.launchpad.net/openobject-addons/+bug/389033).

Quoting @odony:

> The current users_ldap does not support ldaps (which is LDAP over SSL not SASL), so I am marking this as a whishlist. All contributions are welcome by the way"

But we do support STARTTLS using `ldap://` URLs

**Comment by odony** [comment]
Yes, you're probably confusing "Use TLS", which means "Enable data confidentiality protection by using the StartTLS LDAP extension", with the `ldaps` protocol, which is basically LDAP tunnelled through SSL on a dedicated port.
Not sure if supporting `ldaps` is very useful nowadays, but there is more to it than the two-line patch you mention. It would also require a change of config setting to distinguish `StartTLS` and `ldaps` mode - unless we decide that `ldaps` is simply enabled by setting the port to 636.  But what would be the meaning of the "Use TLS" checkbox when port 636 is set?
As usual, please [make a PR](https://github.com/odoo/odoo/blob/9.0/CONTRIBUTING.md) on master if you'd like to implement it (and you could close this issue as well)

**Comment by qtheuret** [comment]
Ok, thank you for your quickly reply. After reading some documentations, you are right, the ldaps protocol is deprecated in favor of Start TLS [RFC2830]. So I'll change my LDAP server configuration.
