### ISSUE TITLE
9.0 - Stages in Tasks and Issues very confusing.

### ISSUE THREAD

**Issue by stephaniemillet** [odoo/odoo#9776]
My customer - going live in January 2016 - has a lot of question about stages in Task and Issue in V9.

1. How is it possible to define a sequence on the stage, and a stage by default when creating a new task or issue ? 

2. Is it  (and how) possible to have different stage for Issue ans Task : there is Only one menu : ‘Configuration > stage’

3.  On task form view, stages doesn't appear anymore on a line. So it looks like we can change stage only in Kanban view (?)

4 .  From issue [9.0] Default stage (and add member) feature is missing#9030
we understand we have to re-define new stage for each project ? 

5.  The process is not stable
When we create a task : we can see all the stage
When we assigne it to a project : line of stages just disappear.

6 - same remarks as in : [Project] Text of stages not visible fully #9329

**Comment by lannex-alex** [comment]
Same problem here,

Project/Configuration/Stages is lacking functionality. You can configure everything about the stage but you can't re-use it in another project.

Yes you can clone the project and the cloned project will use the same Stages in this way the stages won't be duplicated but if you need to add another stage after creating all the projects you will need to add a new stage for each project in the Kanban view which is unmanageable eg. you have 500 active projects and you need to add a new stage in all of them, good luck with that!

Please add this functionality.

**Comment by stephaniemillet** [comment]
Hello Alex,

Thank you for your comment
Seems that we agree to say that : 
Project/Configuration/Stages is lacking functionality and it is unmanageable

Here is my customer flow : 
The end user creates Sales order, and when he confirms, because some products are ‘Invoice based on time and material’ and 'Create a task and track hours’, 
Odoo creates a analytic contract and a project
So the end-user CAN’T duplicate a project to create a new one, as it is created from the SO confirmation

So at the end of the day, end users have created 
- a lot of tasks or issues with NO status
- and a lot of project, with no stage.
And the end user has no access right to create stages.

Odoo people, please explain me what would be the best solution to  assign stages to all tasks and issues without spoiling time re-configuring everything all the time.
Txs a lot

**Comment by stephaniemillet** [comment]
Odoo's Answer : 
Hello stephanie,

9.0 - Stages in Tasks and Issues very confusing :- https://github.com/odoo/odoo/issues/9776

1. How is it possible to define a sequence on the stage, and a stage by default when creating a new task or issue ?
Ans :- Yes, it is possible. You can define a sequence on the stage. To define a sequence on stage, go to Project > Open Stage >EDIT > Change the sequence in the sequence field > Save > Check.

In odoo 9.0, you can not define default stages for new project. The flow of some functionality was changed. In v9, when you define any new stage that time you have select project for display this stage into project. You not have to define stages into Project as like odoo 8.0
The Example was explained in Video file,please take view of it at:- https://youtu.be/zVNPkHAG9DU

2. Is it (and how) possible to have different stage for Issue ans Task : there is Only one menu : ‘Configuration > stage’
Ans :- In odoo 9.0, it is not possible to defined different stage for issue and Task.

3. On task form view, stages doesn't appear anymore on a line. So it looks like we can change stage only in Kanban view (?)
Ans :- You can change the stages of task from kanban view or form view of task.
The Example was explained in Video file, please take view of it at :- https://youtu.be/HSGjuAgYhrw

4 . From issue [9.0] Default stage (and add member) feature is missing ( #9030 )we understand we have to re-define new stage for each project ?
Ans :- As my colleague Antony's comment on ( # 9030), we remove “Default for New Projects”field from the stages and you can create new stage from kanban view. If you want to change it just add a default value on stage_ids of project with ir.values (no code needed). 
In odoo 9.0, we remove the “Team” tab from the project. If you have to add members into project then add as followers.

5.The process is not stable When we create a task : we can see all the stage When we assigne it to a project : line of stages just disappear.
Ans :- System see all the stage into task which we assign into a project.
The Example was explained in Video file, please take view of it at :- https://youtu.be/iTFpi0aOXmI

6 - same remarks as in : [Project] Text of stages not visible fully
Ans :- You have to just scroll right side for see the text of stages.
The Example was explained in Video file, please take view of it at :- https://youtu.be/CvlbXEsnDyU

One Requests for Quotation from two Quotations with same Supplier :- https://github.com/odoo/odoo/issues/7052

Ans :- I have checked mentioned issue in run bot 9.0 branch. When creating a PO from a MTO flow , ‘Origin ( Source Document) ’ field on the PO keep track on the SO number. If we don’t confirm the PO, it creates new lines for new product in same PO or increment quantities on existing lines from others SO, through MTO flow, in this existing purchase order and also system show the new SO reference with last SO reference in the ‘Origin ( Source Document) ’ field.

The Example was explained in Video file, please take view of it at :- https://youtu.be/LytY4jeWGSM

I hope this information will help you.

Thanks & Regards

Mitesh Prajapati
Odoo Support Enterprise

**Comment by Yenthe666** [comment]
Hi @stephaniemillet,

Thanks a lot for your report. I'm closing this since the Odoo support channel has answered all your questions. If things aren't clear or if you need more information you can continue the conversation by e-mail.

Regards,
Yenthe

**Comment by dreispt** [comment]
FYI there is an OCA module restoring the default stages feature: https://github.com/OCA/project/tree/9.0/project_task_default_stage

**Comment by bistaray** [comment]
See also my comment at https://github.com/odoo/odoo/issues/8660
