### ISSUE TITLE
[V9] Adyen - Merchant Signature Error

### ISSUE THREAD

**Issue by Gh0st4unt3r** [odoo/odoo#9786]
The below image shows an error on the merchant signature.

We have been testing this gateway for abound 7 days and trying to fix the code to find out why its forming an incorrect merchant signature different to what Adyen gateway are expecting.

From what we have gathered is that adyen are introducing SHA256 and are deprecating SHA1 but are still able to use this as encryption method, hopefully we can find the solution as we have exhausted all options to fix the issue.

UPDATE:
I have been informed that this happens also on the Odoo Hosted and Odoo On Premises versions

![merchant_signature_error](https://cloud.githubusercontent.com/assets/13893077/11440477/9c82921e-94fa-11e5-920e-c84fa5001b53.png)

**Comment by sermanes** [comment]
Do you have the solution?

**Comment by Gh0st4unt3r** [comment]
We have not found a solution to this as of yet, we are hoping that the community along with anyone from the Odoo team could shed some light on what could be causing this so we can fix.

Can you share if you have the same problem as well including any errors you may be facing too.

**Comment by sermanes** [comment]
I'm working to find a solution. I have the same error so if I can resolve I share you, but i think the problem is for adyen, anyway I will try to resolve. If i have some information I will tell you.
P.D. Sorry for my bad english.

**Comment by sermanes** [comment]
Okey I resolve the problem my fail was in the configuration file, maybe you have the same error.

**Comment by willmakenoise** [comment]
I am having the same problem. 
What do you mean by configuration file? Are you thinking of the "Skin HMAC Key" in "Website Admin" -> "Payment Acquirers"?

Thanks!

**Comment by sermanes** [comment]
Yes, the Key was wrong, however i dont know where is the file configuration. My department is web-front so I only can say that. I hope I help you. 
P.D.: Sorry for my english

**Comment by JayVora-SerpentCS** [comment]
Did you get it working?
We are working on Adyen recurring manual as an advancement.

**Comment by sermanes** [comment]
@JayVora-SerpentCS  Yes the problem was in the Key, my problem, but I dont know in other cases.

Sorry! :(

**Comment by willmakenoise** [comment]
I still haven't gotten it to work. 
When I try to pay from the web store, I get this:
"Invalid Request

Unfortunately we were unable to process this request
Error: Merchant signature was not valid!<br />You can test the HMAC Calculation by submitting a payment request to https://ca-test.adyen.com/ca/ca/skin/checkhmac.shtml"

I have tried to generate HMAC keys over and over.. tried all sorts of combos in the Ayden config view, but no luck.

**Comment by Fuchur777** [comment]
@sermanes Would you be able to share with us what field form Adyen you matched with teh Fields in Odoo?
I am running a Test Adyen environment and test settings in Odoo and cannot seem to find a valid combination to pass the mentioned error.

Thanks!

**Comment by Fuchur777** [comment]
@willmakenoise @JayVora-SerpentCS 
With Odoo 8 you have to use the **old** HMAC keys!
1. Under Edit Skin > HMAC Keys > Click: Switch to older HMAC-SHA1 signing and keys
2. Then replace the ******* with your own secret key.
3. In Odoo 8 fill in this secret key under Skin HMAC Key.
And error message is gone.

**Comment by willmakenoise** [comment]
@Fuchur777 
Thanks for you reply.
I'm using Odoo 9 Enterprise, and I've tried using the both types of HMAC keys (old & new) several times. No luck.
