### ISSUE TITLE
Correct spelling of _compute_hide_picking_type

### ISSUE THREAD

**Issue by tojon** [odoo/odoo#97863]
`_compute_hide_picking_type` is misspelled.

https://github.com/odoo/odoo/blob/fcc74186330c8df37cfac08455bd7bba44d4656b/addons/stock/models/stock_picking.py#L420

**Comment by niyasraphy** [comment]
hi @tojon ,
this has been fixed in the master in the following commit:  https://github.com/odoo/odoo/commit/8dc3f59f18e7607fe45642e2046b90a562b837ff

feel free to close the ticket.
thanks

**Comment by tojon** [comment]
Confirmed it's now correct in main aka. master.
