### ISSUE TITLE
[8.0] stock: Slowest individual queries to get product quantity availability 

### ISSUE THREAD

**Issue by moylop260** [odoo/odoo#9793]
I checked the log of postgresql with `pgbadger` and see next `Slowest individual queries`:  
![pgbadger pgbadger yoytec_browse 2015 11 25](https://cloud.githubusercontent.com/assets/6644187/11447256/61560718-9511-11e5-99c6-3d6047ace333.png)

I checked the current method that execute this queries: [_product_available](https://github.com/odoo/odoo/blob/50c0778d67e4c309cf4a56dab84e5cb051cba300/addons/stock/product.py#L144-L145)

If I want to know the currently product quantity on-hand (without `virtual available`) this method will get all other fields `virtual available` and queries needlessly.

IMHO this lines could be optimize to get a better performance.

**Comment by leopard7777777** [comment]
+1

**Comment by gdgellatly** [comment]
Did you run EXPLAIN ANALYZE on the queries to see the slow part?  This kind
of slow query is usually just a case of adding an appropriate index.  Its
not like it is a particularly difficult or complex query so I imagine it is
just running loops for filtering.

I notice on stock.move table I have a composite index made up of
product_id, state, location_id, location_dest_id.  Not sure of the order (I
think that is it) but willing to bet it was this query or similar that made
me do it and I certainly don't have these issues.

**Comment by moylop260** [comment]
@gdgellatly 
I'm talking about follow fix: https://github.com/odoo/odoo/pull/10975

**Comment by jgrandguillaume** [comment]
Hi,

Not sure you don't have another trouble to face perf issue with that query, but still your fix #10975 sounds good to me !

Regards,

**Comment by gdgellatly** [comment]
Tbh looking at fix, real problem is obvious. The function fields that use
stock moves should be refactored out from those that need quants but until
then this fix is best.

**Comment by moylop260** [comment]
@gdgellatly 
Yes, you are right!
For new api we don't have `fields` variable, then we will need a fix with a split of methods.
First one for quants.
Second one for virtual (with invoke to the first one).

But this is a big fix... then I hope that odoo accepted this one, for later proposal a big refactory here.

**Comment by Yenthe666** [comment]
Hi @moylop260 ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
P.S: Feel free to change the PR for V9 or up if you can.

Regards,
Yenthe
