### ISSUE TITLE
[9.0] odoo 9 nightlies have version < 9.0

### ISSUE THREAD

**Issue by sbidoul** [odoo/odoo#9799]
I noticed that that the nightly odoo 9.0 packages have a version that is smaller than 9.0.

For instance https://nightly.odoo.com/9.0/nightly/src/odoo_9.0c.20151128.zip, when built, receives version number 9.0rc20151128, which according to pip is a version number that is < 9, as illustrated by this snippet.

```python
>>> from pkg_resources import parse_version
>>> v9 = parse_version("9.0")
>>> v = parse_version("9.0rc20151128")
>>> v >= v9
False
```

Is it on purpose that these packages are still considered release candidates?

**Comment by sle-odoo** [comment]
isn't it the right behavior? release candidate are inferior to the stable version

**Comment by katyukha** [comment]
Version change to stable 9.0 branch come from this commit: 0a6edac151d6d34b264735729d6575b399dc6455

Adding 'c' to version number ([line 16](https://github.com/odoo/odoo/commit/0a6edac151d6d34b264735729d6575b399dc6455#diff-4726c039f03e1c5eb73189aca66b281cR15)) makes this version look like release candidate after normalization.

So current 9.0 branch have folowing behavior:

```python
import openerp
import pkg_resources as pkg

print openerp.release.version                        # prints  9.0c
print pkg.parse_version(openerp.release.version)     # prints  9.0rc0

# so any code that checks odoo versions will fail:
if pkg.parse_version(openerp.release.version) >= pkg.parse_version('9.0'):
    # 9.0rc0 < 9.0, so this code will not be executed
    print "Do somethin special for odoo 9.0+"
```

This causes errors even when interactiong with multiple odoo versions via RPC, bacause some rpc-methods (like those related to database management) changed their parametr lists in 9.0

Even when we will try to install odoo 9.0 via setup.py, it may print warning like:
```
python2.7/site-packages/setuptools/dist.py:285: UserWarning: Normalizing '9.0c' to '9.0rc0'
  normalized_version,
```

Maybe would be better to use this info [Local version segments](https://www.python.org/dev/peps/pep-0440/#local-version-segments) and use for example '+' separator for 'c' version modifier?

Thus following will work:

```python
import pkg_resources as pkg

if pkg.parse_version('9.0+c') >= pkg.parse_version('9.0'):
    # This code will work
    print "Do somethin special for odoo 9.0+"
```

**Comment by sbidoul** [comment]
@sle-odoo AFAIU 9.0 nightlies are posterior to the offcial 9.0 release, so they should have a greater version number.

**Comment by sle-odoo** [comment]
In your original message: is 9.0rc20151128 > 9.0 ? False. Looks good to me.
However, there is a confirmed issue stated by @katyukha and we propose to fix it by typing

       sudo apt-get install odoo=9.0c*

It will downgrade the odoo9.0.2015(...) to odoo9.0c.2015(...), which are the current versions provided by nightly.odoo.com following rev 0a6edac.

**Comment by katyukha** [comment]
I think it is not obviouse that lastest Odoo nightly versions are less than 9.0.

Usualy in requirements or any other version aware code to get latest version it is obvious to write something like ```odoo>=9.0```, wich is supposed to represent all Odoo versions after 9.0 release. And when somebody need to update Odoo, or just compare Odoo versions in his application (for example one that interact with multiple odoo versions via RPC), he unexpectedly find that something is not working, because latest odoo version have version number less than expected.

May be i am not right, but, writning code like:
 ```python
if self.server_version() >= parse_version('9.0'):
    # do something specific to 9.0
```
I expect that this code will work for all Odoo versions 9.0 series.

**Comment by sbidoul** [comment]
I agree with @katyukha 

> In your original message: is 9.0rc20151128 > 9.0 ? False. Looks good to me.

`parse_version` works correctly, yes.

But I mean if I write a `setup.py` with `install_requires='odoo >= 9.0'`, it currently does not find nightlies that have been released after 9.0 stable. That does *not* look correct to me.

The c suffix indeeds means RC according to PEP 440 (which is the accepted convention for python package version specifiers). The e suffix means nothing AFAIK. Please  make sure the Odoo versioning scheme is compatible with python conventions. A workaround for .deb versioning is not enough.

**Comment by sbidoul** [comment]
@sle-odoo by the way, I'm wondering if encoding the concept of community vs enterprise in the version number is sustainable. Indeed, these are rather different packages than different versions of the same package.

IMO it would be better to have an `odoo-community` package and an `odoo-enterprise` package that depends on the former.

**Comment by katyukha** [comment]
Are there any changes planned related to this issue?

Note, that ```version``` as string seems not been used in changes provided by commit 0a6edac.
Instead there ```version_info``` tuple is used to determine if it is community or enterprise release.
Thus, changing ```version``` encoding, seems, require only single line modification.

**Comment by sbidoul** [comment]
I'll close this one as this is being handled in 10

**Comment by Yenthe666** [comment]
Thank you for closing the issue and keeping track of it @sbidoul 👍
