### ISSUE TITLE
Missing revision in lp:openobject-server/7.0

### ISSUE THREAD

**Issue by StefanRijnhart** [odoo/odoo#98]
Happy to see that Launchpad is still kept up to date. I did notice a glitch in this process: lp:openobject-server/7.0 is still missing git revision c0882872becf81 which was included in the 7.0 git branch on the 18th of May.

**Comment by mart-e** [comment]
As mentioned on [GitHub Transition](https://github.com/odoo/odoo/wiki/GitHub-Transition) page, everything has been migrated now
