### ISSUE TITLE
Odoo 9 does not upgrade to the latest deb

### ISSUE THREAD

**Issue by seggaf** [odoo/odoo#9800]
apt-get update gets ign hits
and apt-get upgrade did not detect & upgrading to the latest deb

im using debian 8.2 jessie
current odoo.9 deb is 20151122

I installed using the nightly deb repository
wget -O - https://nightly.odoo.com/odoo.key | apt-key add -
echo "deb http://nightly.odoo.com/9.0/nightly/deb/ ./" >> /etc/apt/sources.list
apt-get update
apt-get install odoo

**Comment by sle-odoo** [comment]
```
root@sle-mbp:/home/sle# apt-cache policy odoo
odoo:
  Installed: (none)
  Candidate: 9.0c.20151202
  Version table:
     9.0c.20151202 0
        500 http://nightly.odoo.com/9.0/nightly/deb/ ./ Packages
```
It's working at my end. could you `apt-get clean` and retry?

**Comment by seggaf** [comment]
Hi @sle-odoo 

apt-get clean done.
but it doesn't work still to update

root@SGFPL-DB82:/home/mohamed# apt-get update
Ign http://ftp.cn.debian.org jessie InRelease                                                    
Hit http://security.debian.org jessie/updates InRelease                                          
Hit http://ftp.cn.debian.org jessie-updates InRelease                                                
Get:1 http://ftp.cn.debian.org jessie Release.gpg [2,373 B]                                                                      
Get:2 http://ftp.cn.debian.org jessie-updates/main Sources [2,296 B]                               
Hit http://security.debian.org jessie/updates/main Sources                               
Get:3 http://ftp.cn.debian.org jessie-updates/main amd64 Packages/DiffIndex [367 B]
Get:4 http://ftp.cn.debian.org jessie-updates/main i386 Packages/DiffIndex [367 B]                                
Get:5 http://ftp.cn.debian.org jessie-updates/main Translation-en [2,506 B]   
Hit http://security.debian.org jessie/updates/main amd64 Packages                                  
Hit http://ftp.cn.debian.org jessie Release                                                                        
Ign http://nightly.odoo.com ./ InRelease                              
Hit http://ftp.cn.debian.org jessie/main Sources
Hit http://security.debian.org jessie/updates/main i386 Packages                           
Hit http://ftp.cn.debian.org jessie/main amd64 Packages                                        
Hit http://ftp.cn.debian.org jessie/main i386 Packages                                                                       
Hit http://security.debian.org jessie/updates/main Translation-en                                                            
Hit http://ftp.cn.debian.org jessie/main Translation-en                                         
Get:6 http://nightly.odoo.com ./ Release.gpg [819 B]           
Get:7 http://nightly.odoo.com ./ Release [1,186 B]  
Get:8 http://nightly.odoo.com ./ Packages [1,808 B]     
Ign http://nightly.odoo.com ./ Translation-en_SG                                                                                 
Ign http://nightly.odoo.com ./ Translation-en                                                                                    
Fetched 11.7 kB in 11s (1,010 B/s)                                                                                               
Reading package lists... Done
root@SGFPL-DB82:/home/mohamed# apt-get upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... The following packages were automatically installed and are no longer required:
  python-bs4 python-ofxparse
Use 'apt-get autoremove' to remove them.
Done
The following packages have been kept back:
  icedove
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
root@SGFPL-DB82:/home/mohamed# apt-cache policy odoo
odoo:
  Installed: 9.0.20151122
  Candidate: 9.0.20151122
  Version table:
 *** 9.0.20151122 0
        100 /var/lib/dpkg/status
     9.0c.20151202 0
        500 http://nightly.odoo.com/9.0/nightly/deb/ ./ Packages

**Comment by odony** [comment]
@seggaf Could you try this command as a one-shot step to fix the upgrade problem:

        $ sudo apt-get install -s odoo=9.0c*

**Comment by odony** [comment]
(without the `-s`, sorry for the typo in the previous message)

**Comment by seggaf** [comment]
@odony 

root@SGFPL-DB82:/home/mohamed# apt-get install odoo=9.0c*
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Selected version '9.0c.20151203' (nightly.odoo.com [all]) for 'odoo'
The following packages were automatically installed and are no longer required:
  python-bs4 python-ofxparse
Use 'apt-get autoremove' to remove them.
The following packages will be DOWNGRADED:
  odoo
0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 6 not upgraded.
Need to get 57.4 MB of archives.
After this operation, 62.5 kB of additional disk space will be used.
Do you want to continue? [Y/n] 

I clicked Yes to "downgrade"
now everything is fine with odoo-9c latest installed

Thanks

**Comment by katyukha** [comment]
Related #9799

**Comment by cyaneo1** [comment]
Hello,

i have the same issue, i tried 
`apt-get install odoo=9.0c*`
i clicked Yes to downgrade

running `apt-cache policy odoo` return this
    
```
odoo:
    Installed: 9.0c.20151217
    Candidate: 9.0c.20151217
    Version table:
     *** 9.0c.20151217 0
            500 http://nightly.odoo.com/9.0/nightly/deb/ ./ Packages
            100 /var/lib/dpkg/status

```

nevertheless my odoo instance is not up to date (at the latest version)

![odoo](https://cloud.githubusercontent.com/assets/14825852/11885963/d0e50674-a524-11e5-8034-d2ab1007e420.png)

i tried also `service odoo restart` unsuccesfully

Could you help me to fix this upgrade problem ?

**Comment by dansanti** [comment]
Well, i have to unistall odoo, and install it again, but in one of 2
servers, i get package instalation error : chmod can't found /var/lib/odoo

**Comment by cyaneo1** [comment]
Hello,
i tried to rebuild my dpkg status file
```
root@odoo:~# mv /var/lib/dpkg/status /var/lib/dpkg/status_bkup
root@odoo:~# cp /var/backups/dpkg.status.1.gz /var/lib/dpkg/
root@odoo:~# gunzip -d /var/lib/dpkg/dpkg.status.1.gz
root@odoo:~# mv /var/lib/dpkg/dpkg.status.1 /var/lib/dpkg/status
```

```
root@odoo:~# apt-cache policy odoo
odoo:
  Installed: 9.0.20151103
  Candidate: 9.0.20151103
  Version table:
 *** 9.0.20151103 0
        100 /var/lib/dpkg/status
     9.0c.20151217 0
        500 http://nightly.odoo.com/9.0/nightly/deb/ ./ Packages
```
then i retried to upgrade odoo

```
root@odoo:~# apt-get install odoo=9.0c*
Reading package lists... Done
Building dependency tree
Reading state information... Done
Selected version '9.0c.20151217' (nightly.odoo.com [all]) for 'odoo'
The following packages will be DOWNGRADED:
  odoo
0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 13 not upgraded.
Need to get 57.8 MB of archives.
After this operation, 15.4 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://nightly.odoo.com/9.0/nightly/deb/ ./ odoo 9.0c.20151217 [57.8 MB]
Fetched 57.8 MB in 2s (27.0 MB/s)
debconf: delaying package configuration, since apt-utils is not installed
dpkg: warning: downgrading odoo from 9.0.20151103 to 9.0c.20151217
dpkg: warning: files list file for package 'python-bs4' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'python-ofxparse' missing; assuming package has no files currently installed
(Reading database ... 40963 files and directories currently installed.)
Preparing to unpack .../odoo_9.0c.20151217_all.deb ...
Unpacking odoo (9.0c.20151217) over (9.0.20151103) ...
Processing triggers for systemd (215-17+deb8u2) ...
Setting up odoo (9.0c.20151217) ...

root@odoo:~# apt-cache policy odoo
odoo:
  Installed: 9.0c.20151217
  Candidate: 9.0c.20151217
  Version table:
 *** 9.0c.20151217 0
        500 http://nightly.odoo.com/9.0/nightly/deb/ ./ Packages
        100 /var/lib/dpkg/status
````
the result is the same. 

My odoo instance is still __Version 9.0-20151103 (Community Edition)__

i don't want reinstall odoo.

**Comment by dansanti** [comment]
BTW, if you use apt-get remove, you don't lose data or plugins..

**Comment by odony** [comment]
@cyaneo1 What do you mean with *i tried also service odoo restart unsuccesfully* ? Did you restart the service and the problem remained, or did you fail to restart it? You might want to kill the process and start a clean Odoo server, or possibly reboot the machine if you're not sure how to kill the process. If you still have the old server running this could explain the problem (the version number is located in the `openerp/release.py` file and requires a restart of the Odoo service)

**Comment by cyaneo1** [comment]
Hello,

first i tred to restart only odoo service with command ``service odoo stop`` and ``service odoo start``.
Something was wrong. i had an error message saying that it was not possible to stop the service.
i have restarted my server and now everything is fine.

thanks for your help.
