### ISSUE TITLE
[9,0] hr_contract module not available

### ISSUE THREAD

**Issue by pndiku** [odoo/odoo#9805]
I've done a fresh install of 9.0 and I can't access Employee contracts. The module is in the python addons directory but doesn't show in the Apps, or under "Employees"

**Comment by Amit-Parik** [comment]
I think you have to remove the "Apps" filter from the module list.
Because some of the module doesn't consider on "Apps' category, so once you will remove the apps filter then you can able to find the Employee contracts module.

Thank you!

**Comment by pndiku** [comment]
Thanks! Works.
