### ISSUE TITLE
how can i reset the admin password?

### ISSUE THREAD

**Issue by ufoe** [odoo/odoo#9806]
i forgot the admin password and there is no other user can change the setting to enable the reset password function.

how can i do to get the admin password or reset the admin password.

**Comment by msteinfeld** [comment]
/etc/Odoo/openerp-config.xx

There you can change password for admin

Intero Technologies GmbH
Maik Steinfeld
Heinrich Heine Ring 76
18435 Stralsund

Von: ufoe <notifications@github.com>
Gesendet: 29.11.2015 4:20 nachm.
An: odoo/odoo
Betreff: [odoo] how can i reset the admin password? (#9806) 

i forgot the admin password and there is no other user can change the setting to enable the reset password function.

how can i do to get the admin password or reset the admin password.

**Comment by andreparames** [comment]
@msteinfeld That's the master password, not admin.

@ufoe the only way we manage to do it was by choosing a new password, manually generating a new hash using Python, and then replacing that hash in the database.

First you choose the password, and you run a small Python snippet that generates the hash (replacing MY_PASSWORD with the one you chose):

```python
from passlib.context import CryptContext
print CryptContext(['pbkdf2_sha512']).encrypt('MY_PASSWORD')
```
Then replace the hash in the database with the new one by running this SQL query (replace HASH by the result of the previous command)
```sql
UPDATE res_users SET password='', password_crypt='HASH' WHERE id=1;
```
After that, restart Odoo and you should be able to login.

By the way, to avoid this problem, you can enable a setting that allows you to reset the password from the login page.

**Comment by msteinfeld** [comment]
Master password..right..my fault.
In Version 8 there was one column for non hashed pw and one column for hashed in table res.users. When setting non hashed, you was able to login with.  Isn't that available anymore?

Intero Technologies GmbH
Maik Steinfeld
Heinrich Heine Ring 76
18435 Stralsund

Von: andreparames <notifications@github.com>
Gesendet: 29.11.2015 8:47 nachm.
An: odoo/odoo
Cc: Maik Steinfeld
Betreff: Re: [odoo] how can i reset the admin password? (#9806) 

@msteinfeld That's the master password, not admin.

@ufoe the only way we manage to do it was by choosing a new password, manually generating a new hash using Python, and then replacing that hash in the database.

First you choose the password, and you run a small Python snippet that generates the hash (replacing MY_PASSWORD with the one you chose):

from passlib.context import CryptContext
print CryptContext(['pbkdf2_sha512']).encrypt('MY_PASSWORD')

Then replace the hash in the database with the new one by running this SQL query (replace HASH by the result of the previous command)

UPDATE res_users SET password='', password_crypt='HASH' WHERE id=1;

After that, restart Odoo and you should be able to login.

By the way, to avoid this problem, you can enable a setting that allows you to reset the password from the login page.

**Comment by ufoe** [comment]
@andreparames 

I updated the password as your suggestion. And i can login with the new password for admin. But there is something wrong with the admin account.

"
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
"


However, the other users can access the system.

**Comment by ufoe** [comment]
@andreparames 

the sql should be 
```sql
UPDATE res_users SET password_crypt='your new password hash' WHERE id=1;
```

thanks for your help


@msteinfeld  thanks all the same.

**Comment by andreparames** [comment]
@ufoe glad you could fix it :smiley: please close the issue!

**Comment by Primussimus** [comment]
Hi 
please i need your help 
i'm using Odoo and i forget my admin password and i saw your case. I want to know where or how to run this on my server

from passlib.context import CryptContext
print CryptContext(['pbkdf2_sha512']).encrypt('MY_PASSWORD')
think

**Comment by jesusdanielcf** [comment]
@Primussimus you need to install Python in your server and run those commands on Python console.

I made a script in Python to update your Odoo's user password:
https://github.com/jesusdanielcf/OdooUserPassChanger

You can install Python in your server and try to run those commands on Python console, or if you want you can try the script one installed Python with the following command:
`python OdooUserPassChanger.py`

**Comment by Hyperthinkk** [comment]
@jesusdanielcf How to use this script to change the password.

**Comment by jesusdanielcf** [comment]
Hi @Hyperthinkk to use the script you should check your databases available in your PostgreSQL 
`psql -U pgadmin -l`

The command above will show you your databases and owners in your PostgreSQL.

The next step is to run the script  (The script was developed with Python 3, if you are using Python 2 you need to use raw_input instead of input) and the script will ask for your database name, database user, database password (Your PostgreSQL's password) and database's IP address (localhost if you are working in the same machine where the database is located) to connect to the database. 

Once connected you will be asked for the new password that you want for your Odoo user. The script will update the password field in the database with the new password (Odoo user's password)  encrypting it.

I hope I could help you and the script will help you.

**Comment by my1649** [comment]
I know this is closed and solved, but found a better solution on Odoo forum.
[https://www.odoo.com/forum/help-1/question/how-to-recover-the-admin-password-107445]

> update res_users set password='new_password' where login='admin';
_OR_
> update res_users set password='new_password' where id=1;

**More information for Docker**
Go to the DB container (not the Odoo container), login or bash into the terminal
```
~$  su postgres
~$  psql
psql (9.4.14)                                                                                       
Type "help" for help.                                                                               

postgres=#  \c **_Your_Database_Name_**
You are now connected to database "**_Your_database_Name_**" as user "postgres"

YOurDatabase_Name=# update res_users set password='new_password' where login='admin';
UPDATE 1
```
Please be reminded to login with your '**_new_password_**' and change it right immediately. Its unencrypted.

**Comment by Ducnv5** [comment]
Hello,
I read this article.
But in my db, there is no column named "password_crypt", all columns are "id, active, login, password, company_id, partner_id, create_date, signature, action_id, share, create_uid, write_uid, write_date, alias_id, notification_type, odoobot_state, sale_team_id, target_sales_won, target_sales_done, website_id, employee_id, oauth_provider_id, oauth_uid, oauth_access_token, pos_security_pin"
and also no "openerp-server.conf" file

**Comment by abhi1498** [comment]
> @andreparames
> 
> I updated the password as your suggestion. And i can login with the new password for admin. But there is something wrong with the admin account.
> 
> "
> Internal Server Error
> 
> The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
> "
> 
> However, the other users can access the system.

hey can you please tell me how you solved after "internal server error"

**Comment by geraldo** [comment]
> ```sql
> UPDATE res_users SET password='', password_crypt='HASH' WHERE id=1;
> ```

There is no **password_crypt** field any more in table **res.users**, where is the hashed user password saved in Odoo 13?

**Comment by adsanz** [comment]
@geraldo In case you still wondering the field is now named "password" so the query should be 

```sql
UPDATE res_users SET password='HASH', WHERE id=1;
```

**Comment by yboujraf** [comment]
> @msteinfeld That's the master password, not admin.
> 
> @ufoe the only way we manage to do it was by choosing a new password, manually generating a new hash using Python, and then replacing that hash in the database.
> 
> First you choose the password, and you run a small Python snippet that generates the hash (replacing MY_PASSWORD with the one you chose):
> 
> ```python
> from passlib.context import CryptContext
> print CryptContext(['pbkdf2_sha512']).encrypt('MY_PASSWORD')
> ```
> 
> Then replace the hash in the database with the new one by running this SQL query (replace HASH by the result of the previous command)
> 
> ```sql
> UPDATE res_users SET password='', password_crypt='HASH' WHERE id=1;
> ```
> 
> After that, restart Odoo and you should be able to login.
> 
> By the way, to avoid this problem, you can enable a setting that allows you to reset the password from the login page.
> 
> It'd be nice if we had some way (command line switch?) to redefine the admin password without having to go through these lengths, though.

Dear @andreparames 

Do you have the same code for bash ?

Best Regards

**Comment by andreparames** [comment]
@yboujraf I don't think there's any way of generating a PBKDF2 SHA512 hash using only bash, but if you have Python installed, you can call it from bash to generate the hash, then use `psql` to update the database.

Feel free to email me at odoo@andreparames.com and I can help you set it up (for a fee).
