### ISSUE TITLE
How do i enable the enterprise edition? (no documentation available)

### ISSUE THREAD

**Issue by omer414** [odoo/odoo#9808]
I currently have a community edition running on ubuntu 14. So i went on and bought the enterprise edition from the settings panel as well. I got an email response with the auth code and a link to the download section. 

Now i am very confused, do i have to create a separate instance of odoo enterprise or does it all happen on my current community edition?

I have also tried uploading all the additional addons/modules from the enterprise edition to my current instance, but when i go to the enterprise modules it sends me back to the page to buy the enterprise edition.

I am fine with creating a new instance for enterprise, but where is the git repository for the enterprise? And if creating a new instance is the way to go, then where does the auth code fit in the picture? 

There is no documentation on anything regarding the enterprise edition. I tried contacting the support but after 2 days i received an email with the same download link, again.

**Comment by mart-e** [comment]
Hello,

I replied by email but to sum up (for others coming here, we will publish a documentation soon):

1. fetch the source code of Enterprise version containing the additional modules
2. deploy the new code/installation to your server (make sure to change the `addons_path` if you use separated folders)
3. update the `web` module to use the new webclient
