### ISSUE TITLE
[9.0] sale.order doesn;t generate stock.picking 

### ISSUE THREAD

**Issue by leopard7777777** [odoo/odoo#9809]
Impacted versions:

 - 9.0

Steps to reproduce:

 1. create a new sale order
 2. comfire sale
 3. validate the stock.picking

Current behavior:

 - stock.picking lost

Expected behavior:

 - stock.pocking

sale/sale.py  548

- if line.state != 'sale' or not line.product_id._need_procurement():
    continue

_need_procurement()  return False unless product.type == 'service' and product.track_service == 'task'

my product type is "product" (Stock Product)

**Comment by mart-e** [comment]
How can the stock.picking not be generated if you say at step 3 that you confirm it?
Please specify the configuration of your product, which actions you make exactly, the modules installed,...

**Comment by sle-odoo** [comment]
Closing because of lack of response from the OP.
Regards
