### ISSUE TITLE
[8.0] Fiscal positions and Tax Included in Price 

### ISSUE THREAD

**Issue by chrisdec** [odoo/odoo#9811]
Hello, 

I noticed a problem in V 8.0 regarding fiscal positions and use of taxes Included in Price on products. 

Steps to reproduce
---------------------------

I use a company with Belgium chart of account and taxes. 

Go to Accounting > Configuration > Taxes > Taxes 

Find the "VAT-OUT-21-L" tax. Check "Tax Included in price". 

Create a product with following characteristics: 

Name = TEST
Sale price = 121
Customer Taxes = VAT-OUT-21-L

Create a customer with Fiscal Position = "Régime National"
(For this customer, Taxes on products are applied) 

Create an invoice with your customer and the product TEST: 

The subtotal is 100 and tax is 21. The price of your product excluding vat is 100.

Now, create another customer with fiscal position = "Régime Intracommunautaire"

(In this fiscal position, you can see that VAT-OUT-21-L must be replaced by VAT-OUT-00-EU-L. Thus, this customer doesn't pay taxes. ) 

Create a second invoice with second customer and your product TEST. 

Current Behavior 
----------------------

The tax is well "VAT-OUT-00-EU-L" but the subtotal is 121 and your tax is 0. There is a mistake. As seen above, your price excluding vat is 100. This customer must pay 100 and not 121. 

Expected behavior 
--------------------------

Subtotal must be 100 and tax must be 0. 

The Intracom customer only pay the price excluding vat. 

Thanks in advance for your answer,

Christelle

**Comment by jni-odoo** [comment]
Yes it is working as expected..
