### ISSUE TITLE
Point Of Sale Fiscal don`t working

### ISSUE THREAD

**Issue by ilyasProgrammer** [odoo/odoo#9815]
Problem:
Point of sale ignoring fiscal.

Steps to reproduce problem:
1. Create two tax (e.g. 10% and 15%) including in price.
2. Create the product and set up tax for it that included in price.
3. Create new fiscal and do tax mapping 10% replacing 15%.
4. Create new Point Of Sale Sale and add created taxes.
5. Open POS and ad that product in order.
6. Than apply fiscal on it.
7. Payment. Cash. Validate.
8. Close POS.
9. Push Validate and Close.
You will got ISSUE "Cannot create unbalanced journal entry."

Reason of ISSUE as i presume (look up method "_create_account_move_line" in point_of_sale.py):
In point_of_sale.py line: 

    for tax in account_tax_obj.browse(cr, uid, taxes, context=context).compute_all(line.price_unit * (100.0-line.discount) / 100.0, cur, line.qty)['taxes']:
as result ignoring fiscal.

Fix way as i suppose:

    #Add this before call compute_all
    +taxes = account_tax_obj.browse(cr, uid, taxes, context=context)
    +m_price = line.price_unit * (100.0-line.discount) / 100.0
    +m_fiscal = order.fiscal_position_id
    +   if m_fiscal:
    +       taxes = m_fiscal.map_tax(taxes)
    #And replace like this
    -for tax in account_tax_obj.browse(cr, uid, taxes, context=context).compute_all(line.price_unit * (100.0-line.discount) / 100.0, cur, line.qty)['taxes']:
    +for tax in taxes.compute_all(m_price, cur, line.qty, product=line.product_id, partner=line.order_id.partner_id or False)['taxes']:

Its analogy of _amount_line_tax in pos_order class.

Than you got it to work properly. But i have tested it superficially so its has to be done deeply.

**Comment by jorenvo** [comment]
Thanks for the report, it's fixed. You were right btw, we did not use the mapped taxes when creating the account moves, because of this the pos would attempt to create unbalanced lines (where paid != amount of order), which caused the problem.

**Comment by flotho** [comment]
I think it probably coming from a bad way taxes are handled : https://github.com/odoo/odoo/issues/10648
