### ISSUE TITLE
How to deploy/configure Odoo to avoid outgoing emails marked as spam

### ISSUE THREAD

**Issue by jdegoy** [odoo/odoo#9818]
Refer to https://github.com/odoo/odoo/issues/3347

I'm talking clean case. Install a Odoo server/DB and add the messaging domain as the domain you truly own. Then send an e-mail to a customer e-mail on an MS Exchange server. Will it be Junked? The answer is yes. 
What should I do; add a system parameter? Set it to which value?
Maybe technically there is no issue according to you but I need a more pragmatic answer to the problem. @mvaled ; what did you do to make it function without changing something in MS Exchange?
We cannot afford to reach out to all customers (to be, i.e. potentially the whole population) to change their MS Exchange filtering options...
So if the appropriate answer to my question is; you can't avoid this problem, you should not use the triangulation (no reply-to address), then so be it but at least I know.

**Comment by mvaled** [comment]
@jdegoy I didn't do anything.  I don't even use MS exchange but many of partners do and we communicate with them normally.

**Comment by pgu42** [comment]
This is likely a messaging configuration case and not an Odoo problem. if your messages are junked by your partner's messaging system then you should look at the error messages and correct the problems. It's likely that your mail server is either incorrectly configured or/and listed in some dnsbl servers or considered as a spam server

**Comment by jdegoy** [comment]
It's not even 100% ok for the e-mails we get as partners from Odoo itself. Some of them get junked, some not. Pretending to activate this feature comes without a hassle seems a denial of reality.
So what does Odoo do to make it function?
Which SMTP servers are recommended?

**Comment by mvaled** [comment]
@jdegoy I'm not really sure you should be looking to the Odoo configuration.  As I've said we have many partners of us use MS Exchange and they have not complained.  

Anyway our set up is like this: a Postfix MTA that is the destination of our Odoo domain.  If you configure your Odoo domain to be "myodoo.com", you MTA should be the destination of it.  We do so with a virtual mailbox domain and configure Postfix to check the alias table in the DB before to check recipients.  We also configured the MTA to deliver the incoming emails to "myodoo.com" using a custom script that reads the email from the stdin and insert into the Odoo DB (https://github.com/merchise-autrement/xoeuf/blob/develop/xoeuf/cli/mailgate.py).  Our MTA also relays all non-local emails to our Entreprise MTA (that is also a Postfix).

**Comment by jeffery9** [comment]
there have something you need to noticed.
1, first, not make spam 
2, make sure your smtp server [mail relay server] is configured properly.  for modern email ecosystem, there have many rule need to follow.  like  smtp server should have a reverse dns name, and have sPF record in dns system...  all those things, you should consult with your IT system engineer,

good luck

**Comment by slimit** [comment]
Sending emails to Gmail from Outlook with the same SMTP params get not junked whereis sending emails to customers from Odoo are not accepted by Gmail.

**Comment by mercadolino** [comment]
Same problem!
When I am sending an email directly from my mail server the email get's received in inbox. But when I configure the same server as odoo outgoing server and sent the email from odoo directly it arrives as spam.

**Comment by Whytehorse** [comment]
Here are the email headers sent by Odoo on my server(Odoo 8) default config.

Delivered-To: whytehorse@gmail.com
Received: by 10.55.135.133 with SMTP id j127csp907986qkd;
        Thu, 25 Aug 2016 06:25:23 -0700 (PDT)
X-Received: by 10.98.61.24 with SMTP id k24mr16220656pfa.100.1472131523039;
        Thu, 25 Aug 2016 06:25:23 -0700 (PDT)
Return-Path: <bounce-3798-res.partner-57@nexus-farm.com>
Received: from mail2.nexus-farm.com (mail2.nexus-farm.com. [205.210.20.122])
        by mx.google.com with ESMTPS id n79si15577640pfi.15.2016.08.25.06.25.22
        for <whytehorse@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Thu, 25 Aug 2016 06:25:23 -0700 (PDT)
Received-SPF: pass (google.com: domain of bounce-3798-res.partner-57@nexus-farm.com designates 205.210.20.122 as permitted sender) client-ip=205.210.20.122;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@nexus-farm.com;
       spf=pass (google.com: domain of bounce-3798-res.partner-57@nexus-farm.com designates 205.210.20.122 as permitted sender) smtp.mailfrom=bounce-3798-res.partner-57@nexus-farm.com;
       dmarc=pass (p=REJECT dis=NONE) header.from=nexus-farm.com
Received: from nexus.nexus-farm.com (cfc.cannabisfarmerscouncil.com [192.168.1.130])
	(using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))
	(No client certificate requested)
	by mail2.nexus-farm.com (Postfix) with ESMTPSA id 64DDC4014C
	for <whytehorse@gmail.com>; Thu, 25 Aug 2016 06:25:21 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=nexus-farm.com;
	s=mail; t=1472131521;
	bh=1BLVbyQ2OXLvkr+DIcJjpCalGoykN6yitY76v3dgFS0=;
	h=Subject:From:Reply-To:To:Date:From;
	b=vY/8Sao+fAMryBNxRakip4ruFPC6mPSndNASibLZfZWcAUKDjZq3cM0yPtA3FYpCb
	 i/wYx/C642GKwV2IrcTU+ctosPwDVPB673Zg9ADlEOspxq9Hd0+HppcXH5Sc2TIYh0
	 yDdUBqh4/QGWJ8ZVD/i7FJFNpZB6BYgCHsNMaMYE=
Content-Type: multipart/mixed; boundary="===============1534406978=="
MIME-Version: 1.0
Message-Id: <1472131523.303061008453369.999382830586363-openerp-57-res.partner@nexus>
Subject: Re: testy tester
From: James Snodgrass <james@nexus-farm.com>
Reply-To: Nexus <erp@nexus-farm.com>
To: testy tester <whytehorse@gmail.com>
Date: Thu, 25 Aug 2016 13:25:23 -0000

--===============1534406978==
Content-Type: multipart/alternative; boundary="===============1361602073=="
MIME-Version: 1.0

--===============1361602073==
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: base64

dGVzdAoKSmFtZXMgU25vZGdyYXNzCkZhcm1lcgpOZXh1cyBPbmUsIExMQwooNTA5KSA1ODItOTU3
NQp3d3cubmV4dXMtZmFybS5jb20gWzFdCkNPTkZJREVOVElBTElUWSBOT1RJQ0UgVGhpcyBFLU1h
aWwgdHJhbnNtaXNzaW9uIChhbmQvb3IgdGhlIGRvY3VtZW50cyBhY2NvbXBhbnlpbmcgaXQpIGlz
IGZvciB0aGUgc29sZSB1c2Ugb2YgdGhlIGludGVuZGVkIHJlY2lwaWVudChzKSBhbmQgbWF5IGNv
bnRhaW4gaW5mb3JtYXRpb24gcHJvdGVjdGVkIGJ5IHRoZSBhdHRvcm5leS1jbGllbnQgcHJpdmls
ZWdlLCB0aGUgYXR0b3JuZXktd29yay1wcm9kdWN0IGRvY3RyaW5lIG9yIG90aGVyIGFwcGxpY2Fi
bGUgcHJpdmlsZWdlcyBvciBjb25maWRlbnRpYWxpdHkgbGF3cyBvciByZWd1bGF0aW9ucy4gSWYg
eW91IGFyZSBub3QgYW4gaW50ZW5kZWQgcmVjaXBpZW50LCB5b3UgbWF5IG5vdCByZXZpZXcsIHVz
ZSwgY29weSwgZGlzY2xvc2Ugb3IgZGlzdHJpYnV0ZSB0aGlzIG1lc3NhZ2Ugb3IgYW55IG9mIHRo
ZSBpbmZvcm1hdGlvbiBjb250YWluZWQgaW4gdGhpcyBtZXNzYWdlIHRvIGFueW9uZS4gSWYgeW91
IGFyZSBub3QgdGhlIGludGVuZGVkIHJlY2lwaWVudCwgcGxlYXNlIGNvbnRhY3QgdGhlIHNlbmRl
ciBieSByZXBseSBlLW1haWwgYW5kIGRlc3Ryb3kgYWxsIGNvcGllcyBvZiB0aGlzIG1lc3NhZ2Ug
YW5kIGFueSBhdHRhY2htZW50cy4KClNlbnQgYnkgTmV4dXMgWzJdIHVzaW5nIE5vbmUgWzNdIE5l
eHVzCgosICBhY2Nlc3MgZGlyZWN0bHkgdG8gUGFydG5lciB0ZXN0eSB0ZXN0ZXIgWzRdCgoKWzFd
IGh0dHA6Ly93d3cubmV4dXMtZmFybS5jb20KWzJdIGh0dHA6Ly93d3cubmV4dXMtZmFybS5jb20K
WzNdIGh0dHBzOi8vd3d3Lm5leHVzLWZhcm0uY29tCls0XSBodHRwOi8vbmV4dXMubmV4dXMtZmFy
bS5jb20vd2ViL3NpZ251cD9yZWRpcmVjdD0lMkZ3ZWIlMjNhY3Rpb24lM0RtYWlsLmFjdGlvbl9t
YWlsX3JlZGlyZWN0JTI2bW9kZWwlM0RyZXMucGFydG5lciUyNmlkJTNENTcmdG9rZW49ZXZzenRm
SWdwNk92UFdyaHpOWjkmZGI9cHJvZHVjdGlvbgo=

--===============1361602073==
Content-Type: text/html; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: base64

PGJhc2UgaHJlZj0naHR0cDovL25leHVzLm5leHVzLWZhcm0uY29tJz4KPHA+dGVzdDwvcD4KCjxw
cmUgd3JhcD0iIj5KYW1lcyBTbm9kZ3Jhc3MKRmFybWVyCk5leHVzIE9uZSwgTExDCig1MDkpIDU4
Mi05NTc1CjxhIGNsYXNzPSJtb3otdHh0LWxpbmstYWJicmV2aWF0ZWQiIGhyZWY9Imh0dHA6Ly93
d3cubmV4dXMtZmFybS5jb20iPnd3dy5uZXh1cy1mYXJtLmNvbTwvYT4KQ09ORklERU5USUFMSVRZ
IE5PVElDRSBUaGlzIEUtTWFpbCB0cmFuc21pc3Npb24gKGFuZC9vciB0aGUgZG9jdW1lbnRzIGFj
Y29tcGFueWluZyBpdCkgaXMgZm9yIHRoZSBzb2xlIHVzZSBvZiB0aGUgaW50ZW5kZWQgcmVjaXBp
ZW50KHMpIGFuZCBtYXkgY29udGFpbiBpbmZvcm1hdGlvbiBwcm90ZWN0ZWQgYnkgdGhlIGF0dG9y
bmV5LWNsaWVudCBwcml2aWxlZ2UsIHRoZSBhdHRvcm5leS13b3JrLXByb2R1Y3QgZG9jdHJpbmUg
b3Igb3RoZXIgYXBwbGljYWJsZSBwcml2aWxlZ2VzIG9yIGNvbmZpZGVudGlhbGl0eSBsYXdzIG9y
IHJlZ3VsYXRpb25zLiBJZiB5b3UgYXJlIG5vdCBhbiBpbnRlbmRlZCByZWNpcGllbnQsIHlvdSBt
YXkgbm90IHJldmlldywgdXNlLCBjb3B5LCBkaXNjbG9zZSBvciBkaXN0cmlidXRlIHRoaXMgbWVz
c2FnZSBvciBhbnkgb2YgdGhlIGluZm9ybWF0aW9uIGNvbnRhaW5lZCBpbiB0aGlzIG1lc3NhZ2Ug
dG8gYW55b25lLiBJZiB5b3UgYXJlIG5vdCB0aGUgaW50ZW5kZWQgcmVjaXBpZW50LCBwbGVhc2Ug
Y29udGFjdCB0aGUgc2VuZGVyIGJ5IHJlcGx5IGUtbWFpbCBhbmQgZGVzdHJveSBhbGwgY29waWVz
IG9mIHRoaXMgbWVzc2FnZSBhbmQgYW55IGF0dGFjaG1lbnRzLjwvcHJlPgoKPGJyIC8+PHNtYWxs
PlNlbnQgYnkgPGEgc3R5bGU9J2NvbG9yOmluaGVyaXQnIGhyZWY9J2h0dHA6Ly93d3cubmV4dXMt
ZmFybS5jb20nPk5leHVzPC9hPiB1c2luZyA8YSBzdHlsZT0nY29sb3I6aW5oZXJpdCcgaHJlZj0n
aHR0cHM6Ly93d3cubmV4dXMtZmFybS5jb20nLz5OZXh1czwvYT48L3NtYWxsPgoKCiwgPHNwYW4g
Y2xhc3M9J29lX21haWxfZm9vdGVyX2FjY2Vzcyc+PHNtYWxsPmFjY2VzcyBkaXJlY3RseSB0byA8
YSBzdHlsZT0nY29sb3I6aW5oZXJpdCcgaHJlZj0naHR0cDovL25leHVzLm5leHVzLWZhcm0uY29t
L3dlYi9zaWdudXA/cmVkaXJlY3Q9JTJGd2ViJTIzYWN0aW9uJTNEbWFpbC5hY3Rpb25fbWFpbF9y
ZWRpcmVjdCUyNm1vZGVsJTNEcmVzLnBhcnRuZXIlMjZpZCUzRDU3JnRva2VuPWV2c3p0ZklncDZP
dlBXcmh6Tlo5JmRiPXByb2R1Y3Rpb24nPlBhcnRuZXIgdGVzdHkgdGVzdGVyPC9hPjwvc21hbGw+
PC9zcGFuPgoK

--===============1361602073==--

--===============1534406978==--

**Comment by Whytehorse** [comment]
Here's a normal header that doesn't get marked as spam(sent by thunderbird):
Delivered-To: whytehorse@gmail.com
Received: by 10.55.135.133 with SMTP id j127csp907340qkd;
        Thu, 25 Aug 2016 06:24:01 -0700 (PDT)
X-Received: by 10.98.202.202 with SMTP id y71mr16306489pfk.10.1472131441367;
        Thu, 25 Aug 2016 06:24:01 -0700 (PDT)
Return-Path: <james@nexus-farm.com>
Received: from mail2.nexus-farm.com (mail2.nexus-farm.com. [205.210.20.122])
        by mx.google.com with ESMTPS id i4si15558756pfi.181.2016.08.25.06.24.00
        for <whytehorse@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Thu, 25 Aug 2016 06:24:01 -0700 (PDT)
Received-SPF: pass (google.com: domain of james@nexus-farm.com designates 205.210.20.122 as permitted sender) client-ip=205.210.20.122;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@nexus-farm.com;
       spf=pass (google.com: domain of james@nexus-farm.com designates 205.210.20.122 as permitted sender) smtp.mailfrom=james@nexus-farm.com;
       dmarc=pass (p=REJECT dis=NONE) header.from=nexus-farm.com
Received: from [192.168.1.200] (solaria.nexus-farm.com [192.168.1.200])
	(using TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits))
	(No client certificate requested)
	by mail2.nexus-farm.com (Postfix) with ESMTPSA id E2F616FC03
	for <whytehorse@gmail.com>; Thu, 25 Aug 2016 06:23:58 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=nexus-farm.com;
	s=mail; t=1472131438;
	bh=OPm11+CkjXkJFPEq/j5HjcJhk1qxKHpX6AslemrslHc=;
	h=To:From:Subject:Date:From;
	b=hVz6Qg81h3LIrsxFF5/frPbEMfW+zAIreb0+spfJuUVEsa0lmYFAOTQjdAvl3EjaO
	 c/whBPvofLKKvUrQEghlxC/GTMR2jXAu1G455vW3uGprZl1++QeSvvE8vJZ1EVJ15V
	 BnO165gRrD4cjCD8FOwv11ZZyfImhCvpkDfakZFk=
To: Bang Tango <whytehorse@gmail.com>
From: James Snodgrass <james@nexus-farm.com>
Subject: test
Message-ID: <829b3dd6-8dfd-19bd-e079-6f3394bc03e7@nexus-farm.com>
Date: Thu, 25 Aug 2016 06:23:58 -0700
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101
 Thunderbird/45.2.0
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 7bit

test

**Comment by Whytehorse** [comment]
[http://wiki.apache.org/spamassassin/Rules/MIME_BASE64_TEXT](From Here)
SpamAssassin Rule: MIME_BASE64_TEXT

Standard description: Message text disguised using base64 encoding

Explanation

The message contains text that has been encoded using Base64 content transfer encoding but does not use a character set known to require it. This does not apply to text in the UTF-8 or big5 character sets.

This technique is assumed to be used by spammers as a form of obfuscation, presumably to bypass filters that are not MIME-aware.

Further Info

The default scores for this rule can be found in the online list of tests.

For details on Base64 encoding see RFC 2045 sec 6.8

This rule is known to trigger false positives in some circumstances. See (buglist)

**Comment by Whytehorse** [comment]
I ran a spam check on a mass email and it passes fine except for this:
The List-Unsubscribe header is required if you send mass emails, it enables the user to easily unsubscribe from your mailing list.
Your message does not contain a List-Unsubscribe header

I looked and there is no header, but there is an unsubscribe link in the footer so how do we add the header?

**Comment by lem8r** [comment]
Configure SPF and PTR

**Comment by pedrobaeza** [comment]
This is not an Odoo issue per se, and although interesting, I have to close. Please have this type of conversation on forums or mailing lists.
