### ISSUE TITLE
Inventory accounting incorrect when using BOM Odoo 9.0

### ISSUE THREAD

**Issue by elevationO** [odoo/odoo#9825]
As it ships Odoo 9 EE has decimal precision to 2.  The breakdown of cost when performing a production job will result in higher decimal precision required for accurate cost.  I feel this is a flaw in the system not a setup requirement by adjusting decimal precision.  My example:

I buy item A at $1000 

I make item A into 231 item B's.  Cost is $4.32900433 each

Even with the product extension module installed to calculate cost from BOM when rounded it displays $4.33 each.

The inventory valuation will show $1000.23.  This is in error as the final result from the PJ should match equally the input materials like any double entry system (given no loss or time factored).

To workaround now I am setting the decimal precision to 7 and finding that the valuation is correct.  This works for the testing I have done but the math still may not work in every situation.

Showing the $4.33 as the product cost is not the issue it's the valuation of the inventory that causes a serious problem.

**Comment by elevationO** [comment]
https://youtu.be/NVoruFy1nUs

**Comment by elevationO** [comment]
https://youtu.be/KAq7Hg6-sMo

**Comment by elevationO** [comment]
These two videos show the creation of new products, setting the real price/perpetual inventory, adding landed costs, and manufacturing the item.  The inventory valuation report shows the correct total but the balance sheets and journal entries for the MO are incorrect.  

This was done on Odoo runbot 9.0 but I have also confirmed it on enterprise edition.

This affects everyone!!

**Comment by pedrobaeza** [comment]
Sorry, but this is how everything ties together, having a common decimal precision that serves for all. If it's not correct, please change it, but in some places, the representation in screen will still be in only 2 decimal places, but that doesn't mean that the value is rounded.
