### ISSUE TITLE
Currency Rounding Issue at special values

### ISSUE THREAD

**Issue by alexander-heyber-manatec** [odoo/odoo#98270]
Impacted versions: All Versions

Steps to reproduce: 
- Open Odoo shell
- Type: 
     cur = env["res.currency"].browse(1)   # This will get the Main Currency
    cur.round(2469.99)
- Result will be 2469.9900000000002

Current behavior:
rounding 2469.99 by currency.round() method will result in 2469.9900000000002

Expected behavior:
rounding 2469.99 by currency.round() method should result in 2469.99

Video/Screenshot link (optional):
[odoo_bug.zip](https://github.com/odoo/odoo/files/9359106/odoo_bug.zip)

Support ticket number submitted via odoo.com/help (optional):

**Comment by gdgellatly** [comment]
It is correct. It would take to long to explain why, but feel free to google, it is an internal implementation detail. It won't display like that, but if not stored like that later float maths will be incorrect.

**Comment by Yenthe666** [comment]
Yup, it's an ancient debate in the Odoo world but was built this way on purpose and kept (for now).
