### ISSUE TITLE
[8.0] Record rule bug for account.analytic.account model

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#9830]
Hello,
there seems to be a weird bug, when trying to modify account.analytic.account multi company rule.

Tested with module account_analytic_analysis installed.

Steps to reproduce:
- create at least 3 companies.
- 1 company is set as parent to other two.
- Assign demo user to one of the child companies.
- Modify record rule somehow. For example I tried to allow to see all child companies of parent company: (['|', ('company_id','=',False), ('company_id','child_of',[user.company_id.parent_id.id])]). This is for Analytic Multi Company Rule.
  Try to open analytic contract list with Demo user.

You should get this AccessError:

``` python
AccessError

The requested operation cannot be completed due to security restrictions. Please contact your system administrator.

(Document type: product.product, Operation: read)
```

Weird thing about it, is that it throws product.product model access rights instead of account.analytic.account for some reason (and there seems to be no record rules for product.product at all).

Note. When trying on database without demo data, it worked properly. Don't know why it is bugged this way when trying with demo data.

Also reproduced same behavior on runbot: http://116389-8-0-1f07b9.runbot.odoo.com/, base database.

**Comment by Yenthe666** [comment]
Hi @oerp-odoo,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
