### ISSUE TITLE
[9.0] Improvement needs with multicurrency invoice payment

### ISSUE THREAD

**Issue by dsu-odoo** [odoo/odoo#9835]
- Create one db without demo data, Install Account and finance
- Company currency must be in USD, and also make true multi currency
- Now create one customer invoice with currency EUR (Set currency rate on currency, For ex. EUR=0.94 USD=1.00)
- I have customer invoice in currency EUR and when going to register payment it gives pop up and there I can see payment difference amount while payment amount is in EUR, When I select Payment method in USD then after it should give payment difference not when it popups first time. I think needs improvement here, https://goo.gl/9xLptg
- For better understanding see this video: https://goo.gl/OZb3Po

**Comment by mart-e** [comment]
Hello,

This is not a bug so no need to create an issue. By default it shows the payment difference in the currency of the invoice, no issue here.

If really you want, you can add an `attrs` to hide it as long as no payment method is selected but I don't think it adds much values outside of a multicurrency environment.

I think we already have enough issues on github that we don't need to create additional ones for such small details. Create a PR for master if you wish to change that.

**Comment by rim-odoo** [comment]
@dsu-odoo Check last message there: https://www.odoo.com/web#id=23&view_type=form&model=mail.group&menu_id=4697&action=1621
Please keep GitHub issues for external people

**Comment by dsu-odoo** [comment]
@mart-e Thats what I am talking about improvement, agree we can hide payment difference if payment method is not selected.

**Comment by dsu-odoo** [comment]
@rim-odoo 
![severus-snape-severus-snape-14207617-800-600](https://cloud.githubusercontent.com/assets/7599707/11508752/5d5e2b8c-9880-11e5-8aa0-3640d44c2027.jpg)

**Comment by dsu-odoo** [comment]
@rim-odoo 
![images](https://cloud.githubusercontent.com/assets/7599707/11508877/fddb10ca-9880-11e5-8a7c-21cd544e0499.jpeg)

**Comment by rmu-odoo** [comment]
Hello 

This issue has been fixed with followed PR , along side of my related task
https://github.com/odoo/odoo/pull/9581

Thanks.
