### ISSUE TITLE
[8.0] - import CODA - journal sequence

### ISSUE THREAD

**Issue by jdegoy** [odoo/odoo#9847]
Impacted versions:

8.0 and up?
Steps to reproduce:
Install a DB with at least one company on l10n_be. Install module l10n_be_coda.
Add a bank account to your company for which you have a CODA file.
Import the CODA file from the bank account in question.

Current behavior:
The bank statement journal sequence (reference) is populated with a value coming from the CODA file.
This is especially problematic when a customer uses manual bank statements first and then starts importing CODA files later on...

Expected behavior:
Use the journal sequence for CODA imports.
Alternatively put a checkbox on the Journal to allow to switch between current behavior and expected one.

**Comment by jdegoy** [comment]
![2015-12-01 14_37_46-testing](https://cloud.githubusercontent.com/assets/11032154/11503903/20ac30ea-9843-11e5-80fb-b8059842e846.png)
![2015-12-01 14_36_59-bank statements - odoo](https://cloud.githubusercontent.com/assets/11032154/11503900/20a77a3c-9843-11e5-8dce-8c298d2a33b2.png)
![2015-12-01 14_30_36-c__users_janik de goy_google drive_00 all - all_01 prj - projects_19 par -](https://cloud.githubusercontent.com/assets/11032154/11503902/20aa0306-9843-11e5-91b4-2835e86de285.png)

**Comment by jdegoy** [comment]
More elaborate option would be to add a new field "External Bank Statement Number". 
CODA import should populate it (without the user being able to alter it). 
For a manual bank statement the default value of this field should be = NULL. 
We need a sql unique constraint on a concatenation of Bank Account Number and this External Bank Statement Number to guarantee the same file cannot be imported twice for each bank account.

**Comment by simongoffin** [comment]
Hello Janik,

Keeping the value coming from the coda file as bank statement journal sequence is the behavior expected because this value is in fact the number of the corresponding account statement. With this value, we can check that all the previous account statements have been imported(ex: if the value 3 for account X is imported, it implies that 1 and 2 are already imported for account X.

Regards,

**Comment by jdegoy** [comment]
Most companies do not have coda files right from the start for each bank account. As a result in many cases we find combinations of the journal sequence and the coda sequence within the same fiscal year.
When your FY doesn't correspond to the one of the bank (the bank resets the sequence every first of januari) you will have a gap/jump in the numbering within you own FY which is not desirable either.
We wrote a module to handle this. Would you be interested in reviewing it?

**Comment by simongoffin** [comment]
Hello,

Yes we are interested in reviewing it but you must know that we will keep our behavior for the import of coda files.

Regards,
