### ISSUE TITLE
Default project data contains error

### ISSUE THREAD

**Issue by ArthurBorsboom** [odoo/odoo#9848]
In file openerp/addons/project/project_data.xml

line 299:
```
<field name="date_deadline" eval="'2015-%s-01' %(datetime.now().month+1)"/>
```
In December this leads to the non-existing month number 13, resulting in an error when deploying the Project management app.

Removing the +1 at least prevents this error.

**Comment by xmo-odoo** [comment]
That's been fixed in 0ee11f23f1
