### ISSUE TITLE
Postal Code should not be required for checkout

### ISSUE THREAD

**Issue by watermelonjuice** [odoo/odoo#985]
In the ecommerce module the checkout requires a postal code from countries that do not have postal codes. e.g. Hong Kong.

See this gist for a list of countries that do not have postal codes: https://gist.github.com/kennwilson/3902548

**Comment by Yenthe666** [comment]
Hi @watermelonjuice,

Thank you for your report.
In the meanwhile this has been fixed by not making the zip code mandatory.

Regards,
Yenthe
