### ISSUE TITLE
[8.0] property fields bugged. Messes account moves

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#9850]
It seems there is some strange bug, which is hard to reproduce, but when it happens I don't see a way how to work around it.. I noticed this happening when database had more than 3 companies defined (even though trying to reproduce it by creating more companies in another database didn't work)

I noticed this with property fields in product for valuation, like `property_stock_journal`, `property_stock_account_output_categ' and so on.

The problem is this. Some of the company property fields values are not recognized (or nor recognized correctly). What I mean in view, for example I select specific account when I am representing that company. I save changes, I see that I assigned those accounts, but when I do transfer I get error like this:

``` python
One of the following information is missing on the product or product category and prevents the accounting valuation entries to be created:
Product: Fresh new Product
Stock Input Account: False
Stock Output Account: False
Stock Valuation Account: False
Stock Journal: 1
```

The weird part is that I selected those accounts, but Odoo still sees it like there is no such fields defined. And for one company even weirder thing happened, it somehow uses other company property field values, instead of the one user is representing. And If I switch back to that company, change values of those fields, then switch again, In warning I will see values that were defined in that other company. 
**But values that were set in company user is representing, won't have any effect**. Also some of the companies work normally, some are bugged like I described. 

I also checked these fields using `shell` module in interactive python. This way it returns correct values. And going into `ir_property` table, I can see correct values set for all companies, but only for some companies. I mean if Odoo somehow stored that value, then it is correct one, but for some companies it does not even store any value and setting it, does not have any effect at all). But still for some reason when doing Transfer of goods (from Supplier to WH), it just does not see those values or sees another company values instead.

**Note about reproducing**. I don't know how to specifically reproduce it, but now it happened to me on two different databases. This bug is quite dangerous, because it might mess things without user even noticing it.

Can anyone suggest how can I debug property fields in depth or maybe know what could be wrong? Cause I ran out of ideas where to look.

**Comment by oerp-odoo** [comment]
I figured there was a problem with Picking type on purchase order. If picking type is set to another company than user represents, than all property fields behave like they are defined on that company. And if none is found, it behaves like nothing is set, so it just skips valuation all together.

This is really confusing, because Odoo does not warn you about that and it just changes behavior silently. And I wonder if it is really intended to be this way.

The root cause of this is `force_company` in context. This is used in domain when looking for correct value of property field. And that company is the one defined in Deliver to, instead of the company user is representing. 

So confusing part is that if you try to transfer goods and `Deliver to` picking type is for another company and it does not match what is defined in product form property fields for company that user is representing, when doing transfer of goods, you will get warning that some required fields are not defined even though when you go to product, you will see that fields are defined. So there should be at least additional info, telling that `Deliver to` does not match with user company, so you would at least know what wen't wrong.

Now it will look very weird, because it looks like property fields are just not working correctly (still don't know if this behavior is intended)

**Comment by feketemihai** [comment]
@oerp-odoo The picking_type is confusing when using purchase_requisition module, where the default picking_type is the one loaded when installing the stock module, meaning the one assigned to the first company created, see
https://github.com/odoo/odoo/blob/8.0/addons/purchase_requisition/purchase_requisition.py#L66-L68

so this should change like in the purchase module with 

https://github.com/odoo/odoo/blob/8.0/addons/purchase_requisition/purchase_requisition.py#L66-L68

I hope this will solve your issue.

**Comment by oerp-odoo** [comment]
@feketemihai well I don't use purchase_requisition module, only purchase, but the strange thing about default picking_type is that I could not see how purchase gets that default picking_type. I mean I saw there is a method `_get_picking_in` and it is used as a method to find default picking_type, bet when trying to debug (like trying to print in that method), I could not see that method being called at all. So I wonder how that default picking_type is assigned.

**Comment by feketemihai** [comment]
Now i remember...i made a issue some time ago about the Stock Journal which is not created automatically for every company, so you have to create on every company a stock journal and assigned it to the product category.

**Comment by Yenthe666** [comment]
Hi @oerp-odoo,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
