### ISSUE TITLE
[8.0][9.0]Accounts used during an inventory revalutation (change to the cost price of a product)

### ISSUE THREAD

**Issue by jbeficent** [odoo/odoo#9856]
Hello, 

Across different versions of Odoo when an inventory revaluation (using real-time inventory valuation) occurs by means of increasing or decreasing the cost price of a product, the accounts used should not be the product's income or expense accounts (v9) neither the input and output accounts (v7, v8). Separate Debit/Credit accounts should be defined for inventory revaluation, depending on product/product category. Even these accounts can potentially change depending of the amount that is adjusted.

See:
http://www.accountingcoach.com/blog/inventory-write-down

If the change is small, you might use a COGS account. If the amount is big, you might use a specific write-off account.

So, for v9 you can probably live with the current approach (use income/expense accounts), but in v8 (use stock input/stock output) should be fixed as it leads to totally incorrect results.

@sbidoul @KevinMcMenamin @gdgellatly @qdp-odoo this is linked to https://github.com/odoo/odoo/issues/2414

I can provide OPW for bugfixing in v8 if needed.

**Comment by jbeficent** [comment]
This bug was also filed here: https://bugs.launchpad.net/openobject-addons/+bug/1174045

**Comment by elicoidal** [comment]
@jbeficent I am not sure to consider this a bug or lack of feature.
Loss accounts can be specified at Inventory loss location level (in and out)  for that purpose. Is not that enough?
"Big/small" will depend on accountant appreciation and the account could be fixed in the accounting entry based on the evaluation.

**Comment by jbeficent** [comment]
@elicoidal It's not about changes to the physical inventory but change in the value of the current invemtory by means of change in the cost price.

**Comment by elicoidal** [comment]
@jbficent Agree

**Comment by qdp-odoo** [comment]
gotcha.

Expect a patch by today

**Comment by jbeficent** [comment]
@qdp-odoo I think that using the product's income/expense account is still not correct. At least when there's an increase in the valuation of the product, because that would impact on a 'Sales' P&L account. But in reality that's not a sale at all, and this would lead to confusion to accountants, that would see a sudden increase in the Gross Profit, for some income that is not attributable to direct sales.

The correct thing to do in my opinion is that income/expense coming from an inventory revaluation should be posted in the P&L under "Other Income & Expense", which is a category outside of Gross Profit. That helps the company to correctly identify what profit/expense is being generated from operating activities (gross revenue) vs. Other Income/Expense.

**Comment by jbeficent** [comment]
@qdp-odoo Inventory revaluation is similar to the treatment of the gain of an occasional sale of an asset in the sense that it cannot be attributed to the direct operations of the company, but due to exepcional circumstances.

**Comment by jbeficent** [comment]
@qdp-odoo Now that you're focused on US market, I highly recommend you to read this small but insightful book http://www.amazon.com/The-Entrepreneurs-Guide-Financial-Statements/dp/1440829357

**Comment by qdp-odoo** [comment]
Hello again,

here's the patch in 8.0: https://github.com/odoo/odoo/commit/077a168d4c925ebebab336fd3ee06032853b55e0
I just backported the patch of 9.0 to keep consistancy of behavior.

And patch in master, where more freedom is allowed (can create new fields) https://github.com/odoo/odoo/commit/40bd4a2f051996d4ab5ca7956562c8f552c4c969

Thanks for the contribution,
Quentin

**Comment by jbeficent** [comment]
Thanks @qdp-odoo !
