### ISSUE TITLE
 @api.onchange method not called when using inherits

### ISSUE THREAD

**Issue by krueger80** [odoo/odoo#9858]
### Impacted versions: 
 - 9.0 

### Step to reproduce: 
1.  Create a class using _inherits

        class SaleOrder(models.Model): 
            _inherit = 'sale.order' 
            _inherits = {'delivery.shipping.options': 'shipping_options_id'} 
            shipping_options_id = fields.Many2one('delivery.shipping.options', string='Shipping Options', ondelete="cascade", required=True)

2. On the other class, add a on change method 

        class ShippingOptions(models.Model): 
            _name = 'delivery.shipping.options' 
    
            sale_order_id = fields.One2many('sale.order', 'shipping_options_id') 
            test = fields.Char('Test') 
            @api.onchange('test') 
            def test_onchange(self): 
                """ This code is never called """ 

3. Extend the first class form view (in this case `sale_stock.view_order_form_inherit_sale_stock`) to add the fields of the inherited class.

        <field name="test" /> 

### Current behavior 
Changing the test field from the `sale.order` form doesn't trigger the `test_onchange` method. 

### Expected behavior 
Changing the test field from the `sale.order` form should trigger the `test_onchange` method.

**Comment by oerp-odoo** [comment]
@krueger80  using `_inherits`, class does not inherit its methods, only attributes, so I think this behavior is expected

**Comment by xmo-odoo** [comment]
@oerp-odoo 's answer is correct, `_inherits` delegates fields and only fields, that is expected.
