### ISSUE TITLE
tax_group_id creation from template doesn't work

### ISSUE THREAD

**Issue by kurkop** [odoo/odoo#9859]
tax_group_id not exists in account.tax.template but in account.tax yes. I could create this field in a model that overwrite account.tax.template but I think that this field should be avalaible in the core code of Odoo.

Message when I try add record with xml data:
```WARNING db openerp.models: account.tax.template.create() includes unknown fields: tax_group_id```

@blaggacao

**Comment by blaggacao** [comment]
+1
@qdp

**Comment by blaggacao** [comment]
@qdp-odoo

**Comment by qdp-odoo** [comment]
indeed, it was forgotten on the template.

I've fixed that in master (bdf088d) because due to restrictions imposed by our policy we should not change the database schemes on stable versions.

Thanks for the contribution,

**Comment by qdp-odoo** [comment]
my patch was stupidly incomplete and wrong... Here's the addentum: 7f71611

**Comment by blaggacao** [comment]
Ok, thanks, I understand. we will be able to replay that for our own purposes.
