### ISSUE TITLE
[8.0] multiple base currencies for multi company?

### ISSUE THREAD

**Issue by oerp-odoo** [odoo/odoo#9861]
Is there a way to use multiple base currencies? Now when there are multiple companies, and those companies use different currencies. And the same time those currencies are base currencies for those companies. 

For example if I set EUR to be base currency and one company uses EUR as its currency, that will work for that company. But for another company that uses USD, it will not work, because if I would sell anything with USD for that company it would convert it from EUR, instead of directly using USD.

Is it possible to have two base currencies like having exchange rate of 1.0, but if you would sell with different currency than company uses, it should make correct conversion depending on which currency is base for that company.

**Comment by Yenthe666** [comment]
Hi @oerp-odoo ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
On a sidenote: I believe this should work in V11, but I can't guarantee it.

Regards,
Yenthe
