### ISSUE TITLE
Importing invoice from csv not working

### ISSUE THREAD

**Issue by bhanukiran6688** [odoo/odoo#9863]
I want to import invoice lines from openerp 7 to odoo 8 through csv import.But I am getting this error,No matching record found for external id
<img width="775" alt="capture" src="https://cloud.githubusercontent.com/assets/16101706/11527861/666468ac-9909-11e5-8d04-08df94b426eb.PNG">

**Comment by xmo-odoo** [comment]
That'd belong more on the forum than here. It looks like you're trying to import invoices before having imported the relevant accounts (or having imported them with the wrong "external id", so odoo can't find the account when trying to import the invoice)
