### ISSUE TITLE
[9.0] Backend + Frontend Theme

### ISSUE THREAD

**Issue by 8cells** [odoo/odoo#9868]
When i have installed frontend theme and want install backend theme ('category' : 'Theme/Backend') i get error: "you are trying to install incompatible themes".

When i change category, for example 'category' : 'Website', everythinks is OK.

Should be able to install frontend and backend theme together!

**Comment by Yenthe666** [comment]
Hi @8cells,

I'm not sure what you mean with backend theme, since there are no backend themes by default in Odoo. There is only the front-end theme, you can't (by default) change the look of the backend.
I'm quite sure you're talking about a module that is not made by Odoo itself.

Regards,
Yenthe
