### ISSUE TITLE
[8.0] facebook login  is not working properly (email is not working)

### ISSUE THREAD

**Issue by noamix** [odoo/odoo#9880]
I'm facing a problem when using facebook login.

With facebook api V2.5 the email of the person making login, gave me something like that provider_2_user_10204983486577880

With facebook api V2.2 the email is correct

So I think api v2.5 of facebook is not working properly whit odoo 8.0

note: login works fine, the email is not well registered 

here I found some information about the issue, maybe it could be useful

https://developers.facebook.com/ads/blog/post/2015/07/08/marketing-api-v2_4/

any clue will be apreciated

**Comment by lioncodegr** [comment]
Hi, were you able to fix this? There is a suggestion for changing the validation URL from: 'https://graph.facebook.com/me' 
to: 'https://graph.facebook.com/me?fields=id,name,email&access_token={ACCESS_TOKEN}' but its still not working for us. Maybe the {ACCESS_TOKEN} part needs changing.

**Comment by p711** [comment]
This issue is still present in 10.0

**Comment by p711** [comment]
The fix is to change the Validation URL to `https://graph.facebook.com/me?fields=id,name,email,picture` without the access_token (it will be automatically filled in by Odoo). Unfortunately Odoo does not copy the profile picture. I Haven't checked why.

**Comment by Yenthe666** [comment]
@JKE-be as @p711 mentions this is also present in V10.. could you have a look/test please?

**Comment by Yenthe666** [comment]
Hi @maitaoriana ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.
@p711 please feel free to make a new report for V10 if you'd like.

Regards,
Yenthe

**Comment by JKE-be** [comment]
WIP for v9

thx for the patch.

Import picture is not supported by default in Odoo.
