### ISSUE TITLE
[9.0] [BUG] [Blocks User] website_forum - valid URL's aren't recognized. Forum -> New Link

### ISSUE THREAD

**Issue by bistaray** [odoo/odoo#9881]
Tested on runbot today 

http://117210-9-0-7909a4.runbot.odoo.com/forum/help-1/ask?post_type=link

1) Visit Website
2) Click Forum
3) Click the arrow next to ASK A QUESTION, and select SUBMIT LINK
4) Paste or Type a URL - anything you type, even "https://www.odoo.com/" triggers the "Please enter valid URL. Example: http://www.odoo.com" message 

At this point you are blocked, the message can't be dismissed, you are unable to continue.

![image](https://cloud.githubusercontent.com/assets/13910162/11546737/e7c8b4c6-9903-11e5-8687-3fbd92e42518.png)

**Comment by Yenthe666** [comment]
Hi @bistaray,

Thanks a lot for the bug report.
This bug is actually still present as of today. @JKE-be it is only still present in V9. V10 and up work fine. Can you fix it still?

Regards,
Yenthe

**Comment by Yenthe666** [comment]
@JKE-be on a sidenote, as we discussed before, the submit button doesn't work on V10 and up either as the button is disabled:
![image](https://user-images.githubusercontent.com/6352350/36200247-570f17e2-117c-11e8-9996-5afb0b1a5dcb.png)
