### ISSUE TITLE
Official documentation: Problems with building a development environment

### ISSUE THREAD

**Issue by syz-lm** [odoo/odoo#98861]
I just learned about odoo and followed the official tutorial to build the odoo development environment, but here I need to clone two warehouses, and the second warehouse is not directly available. I want to ask, how do you deal with it?

Below is a screenshot of the problem I'm having.

![image](https://user-images.githubusercontent.com/111848062/186584065-cb6c5105-0b8d-4315-919d-096cafdd8887.png)

![image](https://user-images.githubusercontent.com/111848062/186584125-faa4fae8-e392-449f-8284-c02a282d2722.png)

**Comment by gdgellatly** [comment]
That tutorial is for enterprise, if you don't have access, don't worry about it. You can still use the Community version and not much in Enterprise worth learning from a developer perspective.

**Comment by syz-lm** [comment]
Thank you very much.
