### ISSUE TITLE
[9.0 - odoo 9 Enterprise] --db-filter is not working properly.

### ISSUE THREAD

**Issue by turkeshmedma** [odoo/odoo#9891]
when we use --db-filter option and load url it loads nothing and gives 
500: Internal Server Error instead of loading data related to given DB.

![screenshot from 2015-12-03 16 30 42](https://cloud.githubusercontent.com/assets/10941532/11558928/6113712c-99db-11e5-97a6-3ea229226ca4.png)

**Comment by sle-odoo** [comment]
Please read the [db-filter documentation](https://www.odoo.com/documentation/8.0/setup/deploy.html#dbfilter). It's working properly at my end.

Regards
