### ISSUE TITLE
9.0: res config warns that enabling a feature changes the SaaS price even though I'm on premise

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#9892]
Steps to reproduce:

on a runbot base image for 9.0 community, install Project

Go to Project -> Settings, select "Generate tasks from sale orders"

I get the following unexpected message:
```
Warning!
Enabling this feature will install the following paying application(s) :
- Sales Management
- Invoicing
- Employee Directory 
```

As far as I know, these are community addons.

**Comment by gurneyalex** [comment]
@antonylesuisse can you look into this?

**Comment by mart-e** [comment]
@gurneyalex by paying, we say that these will install a new application, meaning it will change the price if you are in a per app basis contract (like for the SaaS). To make sure people enabling options will realise it will have an impact on their invoice at the end of the month.

**Comment by yostashiro** [comment]
If it only applies in SaaS environment, it would be nice to adjust the message as such to avoid confusion.

**Comment by gurneyalex** [comment]
@mart-e then the message is very confusing. To say the least. I got the remark from one customer for whom we had an on-premise test instance installed...

**Comment by gurneyalex** [comment]
may I suggest that you install a custom addon on your saas, which could come from odoo-extra or something like that to handle this?

**Comment by mart-e** [comment]
@gurneyalex I agree, I am working on moving it out of base or at least making it more clear. Should be done soon

**Comment by gurneyalex** [comment]
@mart-e many thanks :smile_cat:
