### ISSUE TITLE
pos order line not open backend

### ISSUE THREAD

**Issue by dkwarlock** [odoo/odoo#98982]
Impacted versions: master

Steps to reproduce: create pos order and go to backend and click on pos order line

Current behavior: Uncaught Promise > Invalid props for component 'FloatField': 'digits' is not a array

Expected behavior: open pos order line  wizard 

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by nhomar** [comment]
VErsion? can you share a video and odoo installation oinformation?
