### ISSUE TITLE
[9.0] Wrong images displayed for addresses of types "Shipping" and "Invoice" 

### ISSUE THREAD

**Issue by ghost** [odoo/odoo#9899]
With "Sales Management" module installed, when you edit a contact and add an address of type "shipping" or "invoice", you can see that their images are the one we expect (at first): a dollar sign for "invoice" and a truck for "shipping", as you can see here:

![beforesave](https://cloud.githubusercontent.com/assets/15160347/11563462/059e483c-99a2-11e5-872c-e7566b63de51.jpg)

Then, after we hit the "Save" button, these images get replaced by the "standard" contact image, as can be seen here:

![aftersave](https://cloud.githubusercontent.com/assets/15160347/11563481/1b8c2a60-99a2-11e5-8a0f-d64a73937843.jpg)

The images with the dollar sign for "invoice" and the truck for "shipping" should obviously be kept instead, as there is no way to tell of what type these addresses are from the screen shown.

**Comment by adekock11** [comment]
+1

**Comment by yvaucher** [comment]
I confirm this

I think avatar shouldn't be generated when contact type is invoicing or shipping

**Comment by pedrobaeza** [comment]
This has been fixed meanwhile in any moment of 9.0, so I close.
