### ISSUE TITLE
ir.rules should make user accesible in computed field search

### ISSUE THREAD

**Issue by argami** [odoo/odoo#9901]
**User should be accesible from computed field search**

Impacted versions:
- 8.0
  I guess that 9 and 7 shoud suffer same issue because is the same code but i haven't test it 

Steps to reproduce:
1. create a new computed field with a search option
2. in the search code access the context user

Current behavior:
- Returns the SUPERADMIN

Expected behavior:
- Get in some way the actual user that is retreiving the information

Little more info:
  I was in the need to get in a mult-company installation, for a computed field used in rules, to be able to reteive the user in the search. 

The issue (bug in my eyes) came from:

https://github.com/odoo/odoo/blob/9.0/openerp/addons/base/ir/ir_rule.py#L132-L141

``` python
    def domain_get(self, cr, uid, model_name, mode='read', context=None):
        dom = self._compute_domain(cr, uid, model_name, mode)
        if dom:
            # _where_calc is called as superuser. This means that rules can
            # involve objects on which the real uid has no acces rights.
            # This means also there is no implicit restriction (e.g. an object
            # references another object the user can't see).
            query = self.pool[model_name]._where_calc(cr, SUPERUSER_ID, dom, active_test=False)
            return query.where_clause, query.where_clause_params, query.tables
        return [], [], ['"' + self.pool[model_name]._table + '"']
```

In that function we force the SUPERUSER_ID to bypass access rules. The problem is not to use SUPERUSER_ID is that we never give any other option to send the actual user.

I guess a good behaviour will be access the information as superuser but send the information to the search with the real user.

In the mean time to fix the issue i just override this function with this:

``` python
    @api.model
    def domain_get(self, model_name, mode='read'):
        cr, uid, context = self.env.args
        context = dict(context or {})
        context['user']  = uid
        dom = self._compute_domain(model_name, mode)
        if dom:
            # _where_calc is called as superuser. This means that rules can
            # involve objects on which the real uid has no acces rights.
            # This means also there is no implicit restriction (e.g. an object
            # references another object the user can't see).
            print model_name, cr, dom, context
            query = self.pool[model_name]._where_calc(cr, SUPERUSER_ID, dom, active_test=False, context=context)
            return query.where_clause, query.where_clause_params, query.tables
        return [], [], ['"' + self.pool[model_name]._table + '"']
```

So from here i can retreive the user from the context without changing the code.

BTW: why in the god's name we dont pass the context that we receive?, my fix is really dirty because i was not able to get the context from the begining.

**Comment by Yenthe666** [comment]
Hi @argami ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
