### ISSUE TITLE
[8.0] Importing lst_price from CSV is not working for new products

### ISSUE THREAD

**Issue by joeadcock** [odoo/odoo#9905]
The CSV import is not importing lst_price on new products, the public price defaults to 1.00.  Note: the lst_price is imported correctly on existing products.

For example, this will create a new foo product with a price of 1.00:
**new_foo.csv**
```
"name","lst_price"
"foo","50.0"
```

**Comment by xmo-odoo** [comment]
It looks like there's something odd happening when creating a `product.template`, possibly something strange between a related field and its base (on the same model).

In the meantime, I would suggest importing to `list_price` on the same object (on `product.template`, `lst_price` is just a related field to `list_price`)

**Comment by xmo-odoo** [comment]
So finally got the time to look back into this.

During the 8.0 product rewrite, `lst_price` was added to `product.template` (it previously existed only on `product.product`) as an old-style related field, which [can not be used when creating a new record](https://github.com/odoo/odoo/blob/9.0/openerp/models.py#L4234-L4249). There's little chance that'd be changed for the current stable let alone the previous one (unless @odony disagrees). As a result, my previous workaround becomes the official fix: if you're importing a `product.template` write to `list_price` not `lst_price`, the latter is here for convenience and attributes compatibility with `product.product`.
