### ISSUE TITLE
Conditional expressions for list view colors, values do not evaluate properly

### ISSUE THREAD

**Issue by syz-lm** [odoo/odoo#99089]
I am learning the odoo developer tutorial by myself. When I go to the setting of the color of the custom list view, there is a decorative attribute in it. The value can be expressed using python conditional expressions. There is no problem with my expression, but it is a bit complicated. Why does it appear? What about errors like this? The version of odoo I'm learning is 15.

Please help me, is this a problem with my conditional expression or a new bug in odoo15?
Below is my code:
![image](https://user-images.githubusercontent.com/111848062/187172178-f7822a32-2789-4c8e-99e1-873f46826f4e.png)
Here is a screenshot of the error:
![image](https://user-images.githubusercontent.com/111848062/187172291-a1d21993-7540-47bd-826c-81884a7825d6.png)

**Comment by syz-lm** [comment]
The key code is this:
```python
decoration-info="len([1 for status in offer_ids.mapped('status') if status != 'accepted' and status != 'refused']) > 0"
```

**Comment by syz-lm** [comment]
This is clearer:
```python
len([1 for status in offer_ids.mapped('status') if status not in('accepted', 'refused'])) > 0
```

**Comment by syz-lm** [comment]
This is the document:
![image](https://user-images.githubusercontent.com/111848062/187175806-8197ecab-70bf-4a33-93ed-d33bd2d5e7ee.png)

**Comment by johnw-bluemark** [comment]
Even though you are writing python code, you must not forget that it is being stored in an XML document. This is technically invalid XML.
```
decoration-info="len([1 for status in offer_ids.mapped('status') if status != 'accepted' and status != 'refused']) > 0"
```
`>` is always supposed to be used as part of tag declarations, but you are using it in the python expression. Some XML parsers will allow this, but others will break when encountering this, as it isn't valid XML. The correct way to deal with this is to use XML entities. Replace `>` with `&gt;`. You can even see an example of this in the last image you posted, where `<` was replaced with `&lt;`.
