### ISSUE TITLE
[8.0] Multi-company bug in account_followup

### ISSUE THREAD

**Issue by andreparames** [odoo/odoo#9917]
The fields introduced into `res.partner` by the `account_followup` module, such as `latest_followup_level_id_without_lit`, are company-dependent, since the partner account is different per-company. But in commit 86126f1, those fields where marked as stored=True, so now there's only a single value being calculated, for the company whose user has last edited the partner (causing the fields to be recalculated).

This leads to obvious problems, one of which is a bug in which the module tries to send an email to a partner that has been calculated for the wrong company, throwing an error:

```
  File "/home/mstrans/openerp-8.0/addons/account_followup/wizard/account_followup_print.py", line 229, in do_process
    restot = self.process_partners(cr, uid, partner_list, data, context=restot_context)
  File "/home/thinkopen/OPENERP_REPS/8.0/openerp-8.0-new/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/mstrans/openerp-8.0/addons/account_followup/wizard/account_followup_print.py", line 171, in process_partners
    message = _("Follow-up letter of ") + "<I> " + partner.partner_id.latest_followup_level_id_without_lit.name + "</I>" + _(" will be sent")
TypeError: coercing to Unicode: need string or buffer, bool found
```

**Comment by Yenthe666** [comment]
Hi @andreparames,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
