### ISSUE TITLE
[8.0][website] If user deletes main menu, no way to restore

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#9918]
1. Install website.
2. Go to _Settings > Configuration > Website settings > Configure website menus_.
3. Delete all.

Now try to create a new menu, and let me know if you find a way. I tried:
- From there.
- From frontend website.
- Reinstalling website addon.

Nothing works.

**Comment by Yenthe666** [comment]
Hi @Yajo,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
