### ISSUE TITLE
[9.0] SQL syntax error when creating Database through web interface

### ISSUE THREAD

**Issue by codingisacopingstrategy** [odoo/odoo#9930]
Hello,

![screen shot 2015-12-04 at 18 17 51](https://cloud.githubusercontent.com/assets/56819/11596095/685e1a30-9ab3-11e5-9d62-3d7720509873.png)

Running 9.0c-20151204 on Debian 8,

The web interface is running. On first run, it presents me with the opportunity to create a database.

I choose US English.
Running PostgreSQL 9.4.5, I get a complaint about the syntax of the SQL.

The database itself gets created but none of the data structures are setup, it can not be used by odoo.

Cheers,

Eric

~~~
2015-12-04 17:07:40,372 9735 ERROR odoo openerp.service.db: CREATE DATABASE failed:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/service/db.py", line 49, in _initialize_db
    db_name, demo, None, update_module=True)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/registry.py", line 385, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 279, in load_modules
    loaded_modules, processed_modules = load_module_graph(cr, graph, status, perform_checks=update_module, report=report)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 137, in load_module_graph
    init_module_models(cr, package.name, models)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/module.py", line 293, in init_module_models
    result = obj._auto_init(cr, {'module': module_name})
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 2479, in _auto_init
    res = self._m2m_raise_or_create_relation(cr, f)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 2807, in _m2m_raise_or_create_relation
    cr.execute('CREATE INDEX ON "%s" ("%s")' % (m2m_tbl, col1))
  File "/usr/lib/python2.7/dist-packages/openerp/sql_db.py", line 139, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/sql_db.py", line 215, in execute
    res = self._obj.execute(query, params)
ProgrammingError: syntax error at or near "ON"
LINE 1: CREATE INDEX ON "ir_model_fields_group_rel" ("field_id")
                     ^
~~~

**Comment by driquelme** [comment]
I'm also having this problem but it's because I'm using postgres 8.1 and all 8.x versions requires a name to be specified upon index creation. 
I tested odoo 9 with a Postgres 9.x version and this error doesn't happen.
In your case I don't know what could be causing the error since you are using PostgreSQL 9.4.5.

**Comment by codingisacopingstrategy** [comment]
Thanks for your reaction.

Maybe there’s a way for Odoo to generate the database through the command line?

**Comment by xmo-odoo** [comment]
Tried with Posgtres 9.4.5, no issue. Are you sure you don't have a 8.x instance running to which you're connecting Odoo? As @driquelme noted the index name became optional in PosgreSQL 9.0, so the error doesn't make sense if you're connecting to a 9.4.5

> Maybe there’s a way for Odoo to generate the database through the command line?

You can create an empty database then start odoo with `-d {database} -i {modules,to,install}`. There's no reason for that to make a difference though, the automatic index generation will perform the same queries.

**Comment by omarfrikha** [comment]
how to run the sql command and retrieve their results with Odoo v9 using QWEB?

**Comment by codingisacopingstrategy** [comment]
@xmo-odoo this was indeed the problem!

odoo had installed the required postgres 9, and I thought it had upgraded the existing postgres 8 install.
But debian’s default behaviour is to install both at the same time and change the port for postgres 9 to 5433. Weirdly enough pg8 was listening on the default port, but `psql --version` returned 9.

Sorry for bothering you gang with this since it turned out to be a config problem on my end!

Cheers,

**Comment by xmo-odoo** [comment]
> Weirdly enough pg8 was listening on the default port, but psql --version returned 9.

Yeah `psql --version` returns its own version, not the server's, to get the server's use either `posgres --version` (though depending on PATH that may not help) or `psql -c 'select version()'` which should return the version of the server to which psql connected.

/cc @sle-odoo maybe the deb packaging could handle that or at least warn about it? There's a risk more people will hit it if they use the deb to update Odoo source.

**Comment by Paul-Hoo** [comment]
@driquelme 
Hi there, I'm using PostgreSQL 8.4.20 and facing the same issue, is it possible to continue using pg8 with odoo? Thanks.

**Comment by driquelme** [comment]
@Paul-Hoo I Don't think you can. Maybe upgrade Postgres to latest version ?

**Comment by Paul-Hoo** [comment]
@driquelme Yes you are correct, I've done so. Cheers.
