### ISSUE TITLE
Handling multiple on_change() methods for the same field

### ISSUE THREAD

**Issue by krueger80** [odoo/odoo#9935]
I can pretty much copy/paste this issue mentionned here:
https://www.odoo.com/fr_FR/forum/help-1/question/handling-multiple-on-change-methods-for-the-same-field-35790

### Impacted versions: 
 - 9.0 

### Step to reproduce: 

1.  Create a class that inherits a model and add an onchange method

        class ProductTemplate(models.Model):
            _inherit = 'product.template'
        
            @api.onchange('categ_id')
            def _set_default_for_stock_owner(self):
                for rec in self:
                    sale_delay = self.get_so_group_default_sale_delay()
                    rec.sale_delay = sale_delay

2. In another module that depend on the first module, inherit the same model and also add  an onchange method on the same field.

        class ProductTemplate(models.Model):
            _inherit = 'product.template'
        
            @api.onchange('categ_id')
            def _set_default_for_stock_owner(self):
                for rec in self:
                    allow_back_order = self.get_so_group_default_allow_back_order()
                    show_back_order = self.get_so_group_default_show_back_order()
                    rec.allow_back_order = allow_back_order
                    rec.show_back_order = show_back_order

### Current behavior 
After installing the second module, the onchange of the first module isn't called.

### Expected behavior 
After installing the second module, the onchange of the first module should be called.

**Comment by xmo-odoo** [comment]
The current behaviour makes sense as far as I'm concerned: since both methods have the exact same name, the new one *replaces* the old one, and since it doesn't call the old one, the old one's just lost. That's standard Python behaviour.

Either call the super-method when overriding it, or name the second onchange differently (I'm not certain that one works /cc @rco-odoo for confirmation)

**Comment by krueger80** [comment]
I guess you are right... But this is always risky to override another module because you can name a function the same name as function from the other module and break it. Therefore you cannot code a module without carefully check if you didn't mask a function somewhere else... Thanks for the code to be open source!

If there is no way to avoid that, I guess I will live with it.

**Comment by Whisno** [comment]
In order to avoid coupling between the base model and the extension, you can do
```
    @api.onchange('country_id')
    def _onchange_country(self):
        if hasattr(super(ResCompany, self), '_onchange_country'):
            super(ResCompany, self)._onchange_country()
```
