### ISSUE TITLE
ValueError: write() got multiple values for keyword argument 'context'

### ISSUE THREAD

**Issue by hotline007** [odoo/odoo#9938]
this error appear when test the module 

    ValueError: "write() got multiple values for keyword argument 'context'" while evaluating
    u"write('is_art_approved', True)"

my python code

    from openerp.osv import osv, fields
    class salesapproval_sale_order(osv.Model):
            _inherit = 'sale.order'
            _columns = {
               'state': fields.selection(
                    [('cancel', 'Cancelled'),('draft', 'Draft'),('confirmed', 'Confirmed'),('exception', 'Exception'),('done', 'Done')],
                    'Status', required=True, readonly=True, copy=False,
                    help='* The \'Draft\' status is set when the related sales order in draft status. \
                        \n* The \'Confirmed\' status is set when the related sales order is confirmed. \
                        \n* The \'Exception\' status is set when the related sales order is set as exception. \
                        \n* The \'Done\' status is set when the sales order line has been picked. \
                        \n* The \'Cancelled\' status is set when a user cancel the sales order related.'),
    
    }

my xml

    <?xml version="1.0" encoding="utf-8"?>
    <openerp>
    <data>
    <record id="sale_view_order_form" model="ir.ui.view">
    <field name="model">sale.order</field>
    <field name="inherit_id" ref="sale.view_order_form"/>
    <field name="arch" type="xml">
    <button name="print_quotation" position="after">
    <button name="approve_art" string="Approve Art" 
    states="draft,sent" groups="base.group_user"/>
    </button>
    <button name="action_button_confirm" position="attributes">
    <attribute name="states">art_approved</attribute>
    </button>
    <button name="print_quotation" position="attributes">
    <attribute name="states">draft,sent,art_approved</attribute>
    </button>
    <button name="cancel" position="attributes">
    <attribute name="states">draft,sent,art_approved</attribute>
    </button>
    </field>
    </record>
    </data>
    </openerp>

thanks in advance

**Comment by xmo-odoo** [comment]
Your snippets show neither the full error (which is inconvenient) nor the code actually triggering it, but from what little you have provided it looks like you are calling `write` in a new-API context giving it two parameters. `write` only takes a single parameter which must be a dict, so your call `write('is_art_approved', True)` should be `write({'is_art_approved': True})`.

And this kind of questions is usually a better fit for forums.
