### ISSUE TITLE
email.template doesn't respect the language decimal separator in Odoo 8.

### ISSUE THREAD

**Issue by lapagept** [odoo/odoo#9941]
Hello there,
See here, this is our setup for the french language. Decimal separator must be the comma (,).

![frfr](https://cloud.githubusercontent.com/assets/8990304/11616973/5a5ca9e8-9c56-11e5-8c62-cc9a7f2a8c14.png)

But in our email template, with this code : 

```
Order total : ${object.amount_total} $ ${object.pricelist_id.currency_id.name}
```

One of our sale order has a **total amount of 6,90 $ CAD**.

For the moment, the **email template returns 6.9 $ CAD**.

How could we change the dot for a comma and add one more zero to the price?

Thanks to help

**Comment by Derter** [comment]
Anyone has a solution for this?

**Comment by lapagept** [comment]
Still no solution here.

**Comment by gdgellatly** [comment]
There is a module for this. Might be in OCA. Just adds a simple mako/jinja
function. Google it, lots of people have this problem and solve it, same
for date formats.

**Comment by lapagept** [comment]
Not sure to understand your answer. Could you name or link the module you are talking about please?

**Comment by Derter** [comment]
I got a workaround for you:  

Order total: <strong>${("%.2f" % object.amount_total).replace('.', ',')}

"%.2f" % does double decimal always even if 00 and formats the float into string making replace function possible.

**Comment by lapagept** [comment]
Big thank for this solution Derter! It works for me.

**Comment by herohat** [comment]
The solution provided by @Derter doesn't work for me with numbers like 9000,  but this worked for me:

(You should get prices like:  9,000.00  )

`${'{:,.2f}'.format(object.amount_total)}`

**Comment by neps1192** [comment]
(You should get prices like: 9.000,00 )
${'{:,.2f}'.format(object.credit).replace(".","%").replace(",",".").replace("%",",")}

**Comment by pedrobaeza** [comment]
Closing as 8.0 is now a non supported version and several workarounds have been provided.
