### ISSUE TITLE
[15.0][14.0] wrong DATEV codes in l10n_de_skr03 and l10n_de_skr04

### ISSUE THREAD

**Issue by tv-openbig** [odoo/odoo#99426]
Impacted versions:
12.0, 13.0,14.0,15.0

Steps to reproduce:
- configure a german company
- install either l10n_de_skr03 or l10n_de_skr04
- check the field l10n_de_datev_code (for all the following taxes where this field has a value):

![Bildschirmfoto 2022-09-01 um 16 34 57](https://user-images.githubusercontent.com/8348598/187940879-0032563e-979e-4f6c-913b-cc6522fc2190.png)

All of these taxes have wrong values in the field l10n_de_datev_code:
For v15 you can find it in this file:
https://github.com/odoo/odoo/blob/15.0/addons/l10n_de_skr03/data/account_tax_fiscal_position_data.xml

line 597 13 -> 3
line 639 12 -> 2
line 954 19 -> 9
line 994 18 -> 8

You can compare the original source:
https://apps.datev.de/help-center/documents/0907043

If you check that document you would see that in the meantime the field l10n_de_datev_code 
should be 4-digits instead of 2-digits, f.e. to cover the One Stop Shop taxes (OSS) 
for B2C business in the EU.

Current behavior:

Your Odoo EE l10n_de_reports  DATEV export feature would export wrong values in the field "BU-Schlüssel".
The BU-Schlüssel (DATEV tax keys) for the OSS taxes would not allow to configure it with the valid 4-digits.
Furthermore please do me a favor and don't cripple the Odoo CE by moving this field to the Odoo EE 
tax view. This field should be configurable at least to correct the wrong values in original Odoo source code.

Expected behavior:

The DATEV export feature of Odoo EE should export the right values for the tax keys, otherwise the account moves created in DATEV will be probably wrong. Even the datev export tools of OCA and other 3rd party modules in order to create correct datev export will need correct tax keys and the possibility to configure the new 4-digits keys logic of DATEV.  

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by Yenthe666** [comment]
@oco-odoo

**Comment by william-andre** [comment]
Will be closed with https://github.com/odoo/odoo/pull/100289
