### ISSUE TITLE
V9 - POS Android doesn't connect to posbox

### ISSUE THREAD

**Issue by lannex-alex** [odoo/odoo#9942]
Tested with different devices and versions Android V5, V6  in Nexus 7, Samsung Tab S2, Nexus 5x

The devices can't connect to posbox. I cleaned the cache in all devices and get the same result. I updated posbox to latest version but no luck.

However I can connect to posbox using PC/Laptop tested with Win7, Win10, Linux and Mac there si no problem.

**Comment by jorenvo** [comment]
Tested with Chrome 47 on Android 5.1.1. I cannot reproduce the issue. Are you sure that your Android devices are on the same subnet as the posbox?

**Comment by jorenvo** [comment]
Closing this due to lack of response.
