### ISSUE TITLE
[9.0] [BUG] Mass mailing-  company logo sent as Odoo logo in email

### ISSUE THREAD

**Issue by jessica-dowd** [odoo/odoo#9947]
On a mass mailing campaign, the company logo is dragged in the email template builder. The logo has been updated and shows correctly on the system, but when the email is sent out, the Odoo logo still shows.

**Comment by asamoura** [comment]
Hi i have the same issue on my platform. Did this bug have a workaround? rgds

**Comment by jessica-oa** [comment]
Hi, @asamoura, it works if you only have one database. You may need to set the db filter too.

**Comment by avanzella** [comment]
Hi,
Any progress on this issue ?
Regards.

**Comment by sumito2b** [comment]
any update on the issue

**Comment by pedrobaeza** [comment]
Closing as solved with the dbfilter option, that's the proper deployment method.
