### ISSUE TITLE
[9.0] [BUG] Mass mailing- Images won’t upload on email builder

### ISSUE THREAD

**Issue by jessica-dowd** [odoo/odoo#9948]
When creating an email template on mass mailing and you want to upload an image, it does not upload the image chosen from the computer. 
However, the icons can get chosen and shows on the email template.

**Comment by mgrohmann** [comment]
The problem still exists in e49893ab2. It seems the CSRF token is missing when image gets uploaded.

The server log says: "CSRF validation failed on path '/web_editor/attachment/add'"

On the other hand, the normal website builder upload is working (the CSRV token is set).

**Comment by Yenthe666** [comment]
Hi @jessica-dowd,

Thanks a lot for your report.
This issue has been fixed in the meanwhile! If you update your Odoo to the latest source code it'll be fixed.

Regards,
Yenthe
