### ISSUE TITLE
Wrong language set in session for portal signup

### ISSUE THREAD

**Issue by PCatinean** [odoo/odoo#9949]
**Session language setup to english for all portal invitations**

Impacted versions:
- 8.0
  - Probably 9.0 (did not check)

Steps to reproduce:
1. Send portal invitation to user with a different language via email
2. Access link in email for /web/signup?token=foo

Current behavior:
- English is set as default language

Expected behavior:
- Language on the portal user / res.partner should be used instead as it is wrong to receive a email invitation to portal in German and end up at a English signup page

This happens when line 1352 in openerp.http.py hits, it has no language in request.session.context and sets the default english

**Comment by Yenthe666** [comment]
Hi @PCatinean ,

Thank you for your bug report and our apoligies that we haven't had the time to look at this bug report. We do our best to handle all of them, but we sometimes miss some.
At this point Odoo 8 is no longer supported as Odoo only supports three versions (9.0, 10.0, 11.0 at the moment).
If you can still reproduce this issue on Odoo 9, Odoo 10 or Odoo 11 we encourage you to create a new bug report.

Regards,
Yenthe
