### ISSUE TITLE
AttributeError: module 'werkzeug.routing' has no attribute 'NumberConverter'

### ISSUE THREAD

**Issue by raindog308** [odoo/odoo#99527]
Impacted versions: 15.0.20220905

Steps to reproduce: 

1. Install Odoo on a fully updated Debian 11.4, carefully following the docs.

2. Start server using systemctl.

3. Read Odoo docs for an hour to find how to connect to the server because the docs never actually say.

4. Google around and discover it's port 8069.  

5. Try to connect and get an internal server errorin /var/log/odoo/odoo-server.log
```
2022-09-05 05:35:20,623 97519 ERROR ? odoo.service.server: Worker WorkerCron (97519) Exception occurred, exiting... 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 1062, in _runloop
    self.process_work()
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 1157, in process_work
    from odoo.addons import base
  File "/usr/lib/python3/dist-packages/odoo/addons/base/__init__.py", line 5, in <module>
    from . import models
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/__init__.py", line 27, in <module>
    from . import ir_http
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 71, in <module>
    class SignedIntConverter(werkzeug.routing.NumberConverter):
AttributeError: module 'werkzeug.routing' has no attribute 'NumberConverter'
```

6. Feel sad.

7. Google some more and see this issue was discussed on the [Odoo forum back in July](https://www.odoo.com/forum/help-1/attributeerror-module-werkzeug-routing-has-no-attribute-numberconverter-207496), so it's apparently a known bug.  Feel your hopes soar.  

8. See the lone response refers to a Werkzeung version.

9. Check your Weurkzeung and discover it's version 2.2.2 which is the latest version:
```
# pip3 freeze | grep -i werk
Werkzeug==2.2.2

```

10. Spiral back into sadness.

11. Attempt to post the question on the forum, only to discover that the software there is badly broken, and even when it does work even basic formatting like hyperlinks aren't available.  Give up after getting various 403 Unauthorized and 500 Internal Server Errors.

12. Google some more and notice the [FreeBSD folks](https://bugs.freebsd.org/bugzilla//show_bug.cgi?id=265957
) are talking about this exact same problem, about 10 days ago.  

13. Decline to start hacking away at random source files you know nothing about based on advice from a forum about a different OS than the one you're using.

14. Start to wonder if anyone is actually using this software since it's been broken for two months and no one can really be testing it.

15. Give up and resolve to go look at some other product.

16. Feel a tinge of regret because you liked the online demo.

17. Resolve to at least open a GitHub bug before you go to bed.  Besides, you already have al these tabs open.

Current behavior: Odoo disappoints.

Expected behavior: Odoo delights.

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by Yenthe666** [comment]
Okay so first of all: I'm just a volunteer so don't shoot the messenger. Barely anyone from Odoo looks at the Github issues, they are pretty much dead and unmanaged. If you have bought the enterprise version open an official ticket through odoo.com/help.

As for your issue: I see you say "Check your Weurkzeung and discover it's version 2.2.2 which is the latest version" which is a bit odd because Odoo should not be runing on 2.2.2 but on `0.16.1` or `2.0.2` depending on your Python version. See the code:
https://github.com/odoo/odoo/blob/3999be22fdf670c452bf13db18cd0b79ed85bad6/requirements.txt#L43-L44

This makes me believe you wrongfully installed the dependencies causing these kind of issues for you 😉 
Perhaps my open source script (https://github.com/yenthe666/installscript) could help you to install a correct and working Odoo version.

Regards,
Yenthe

**Comment by raindog308** [comment]
I fired up a new VM and after doing the following, the error doesn't appear, so I believe you are right.  

apt-get update
apt-get -y upgrade
reboot
apt-get -y install postgresql
wget -O - https://nightly.odoo.com/odoo.key | apt-key add -
echo "deb http://nightly.odoo.com/15.0/nightly/deb/ ./" >> /etc/apt/sources.list.d/odoo.list
apt-get update
apt-get install odoo
