### ISSUE TITLE
[9.0]Error when installing CRM module

### ISSUE THREAD

**Issue by rgeromegnace** [odoo/odoo#9956]
When I install CRM module I get an error like the one evoke on this stackoverflow topic:
http://stackoverflow.com/questions/32970836/odoo-server-error

When I update /addons/crm/crm_data.xml file by adding a field name in following lines it works:
        <record model="crm.team" id="sales_team.team_sales_department">
            <field name="use_leads">True</field>
            <field name="alias_name">sales</field>
        </record>

I have this problem only on one of my odoo instances???

Regards,

**Comment by JayVora-SerpentCS** [comment]
@rgeromegnace This should not happen as addons/sales_team/sales_team_data.xml already contains the record info. 
Kindly update the latest source.
This should be closed.

**Comment by Yenthe666** [comment]
Hi @rgeromegnace,

As stated by @JayVora-SerpentCS this is already in the record, you should update to the latest code base.

Regards,
Yenthe

**Comment by metaminux** [comment]
Is this issue really closed, I can't see anywhere in 9.0 branch a fix.

Am I wrong ?
