### ISSUE TITLE
[8.0] Rounding error on shown of button to close bank statement

### ISSUE THREAD

**Issue by dsabrinarg** [odoo/odoo#9957]
##### Impacted versions:
- 8.0

##### How to reproduce:
I have made this video showing how to reproduce the error https://youtu.be/SypUGDnCuuk

##### Current behaviour: 
The system does not give the option to close from the screen the bank extract, you need to go again into the menu and close then the bank extract.

I have being testing instance.web.round_precision on balance_end_real and balance_end at this code line for example (for 2 decimal rounding):
round_pr = instance.web.round_precision

https://github.com/Vauxoo/odoo/blob/8.0/addons/account/static/src/js/account_widgets.js#L577
if (_.all(data, function(o) { return round_pr(o.balance_end_real) === round_pr(o.balance_end) })) {

##### Expected behaviour:
Button button_close_statement shown or not shown according to the amounts (including decimal) in the operation if the ending balance match with the computed balance.

**Comment by Whisno** [comment]
Ouch, float === float, that hurts
