### ISSUE TITLE
[9.0] Translate Language Odoo 9

### ISSUE THREAD

**Issue by thanhchatvn** [odoo/odoo#9958]
Dear All, 

- Openerp 8 qweb report i have use method translate_doc
Example: 
<t t-foreach="doc_ids" t-as="doc_id">
<t t-raw="translate_doc(doc_id, doc_model, 'partner_id.lang', account.report_invoice_document')"/>
</t>

From link : https://www.odoo.com/documentation/8.0/reference/reports.html

But, today i use it for odoo 9 inside my report deign, return my errror , please support for me??

![screenshot from 2015-12-08 11 25 42](https://cloud.githubusercontent.com/assets/3313064/11647738/7398c1c8-9d9e-11e5-93f5-2c79aab5aec5.png)

**Comment by mart-e** [comment]
Hello,

Please check the [9.0 documentation](https://www.odoo.com/documentation/8.0/reference/reports.html)
The `translate_doc` no longer exists, see [translatable templates section](https://www.odoo.com/documentation/9.0/reference/reports.html#translatable-templates)

**Comment by thanhchatvn** [comment]
Thanks my bro 
https://www.odoo.com/documentation/9.0/reference/reports.html
