### ISSUE TITLE
Element odoo has extra content: record, line 4

### ISSUE THREAD

**Issue by GabrielBatista191** [odoo/odoo#99638]
Impacted versions: 14.0

Steps to reproduce: When i try install my contract module

Current behavior: Error

Expected behavior: Install and upgrade 

Video/Screenshot link (optional):
[https://user-images.githubusercontent.com/71337084/188637076-07b61d2e-dd26-4205-8a50-f9cb4b75c0d7.png
](url)

My view 
![image](https://user-images.githubusercontent.com/71337084/188637330-ef2086bc-cc5c-4f32-8420-313a890dad84.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by wm-cortex** [comment]
As I can see in your code, the line# 10 has extra **double quotation** at the end of the line, remove it.

**Comment by GabrielBatista191** [comment]
> As I can see in your code, the line# 10 has extra **double quotation** at the end of the line, remove it.

I removed it however still popping the same error

**Comment by wm-cortex** [comment]
> I removed it however still popping the same error

Make sure your model name in line#6 (contract.consortium_invoice) is correct and match the name in python, and then install/upgrade the module

**Comment by GabrielBatista191** [comment]
> > I removed it however still popping the same error
> 
> Make sure your model name in line#6 (contract.consortium_invoice) is correct and match the name in python, and then install/upgrade the module

I did that, the model in the view was correct and the error persists :(
