### ISSUE TITLE
[9.0CE]Bug: Tax Cash Basis Journal: Wrong date of VAT entries

### ISSUE THREAD

**Issue by treviser** [odoo/odoo#9972]
When using cash-based VAT accounting, I observe the following:

Observed behaviour:
The entries of posts in the Tax Cash Basis Journal do always have the entry date (system date) as posting date instead of the payment date. Therefore proper tax reporting is impossible.

Steps to reproduce:
- Set-up accounting with Cash Basis allowed
- Set-up and assign a Tax Cash Basis Journal (Type: Miscellaneous, no default accounts)
- Create corresponding Tax Definitions:
  ![selection_135](https://cloud.githubusercontent.com/assets/1814941/11657608/2c56a670-9dbe-11e5-91db-04e87e681f03.png)
- Create an invoice:
  ![selection_126](https://cloud.githubusercontent.com/assets/1814941/11657759/3844e748-9dbf-11e5-9822-331d97354ed2.png)
- Pay the invoice:
  ![selection_132](https://cloud.githubusercontent.com/assets/1814941/11657803/79e4f760-9dbf-11e5-8347-4536dfaaf91b.png)

![selection_133](https://cloud.githubusercontent.com/assets/1814941/11657835/a84c0d5a-9dbf-11e5-960b-b7232c0175f8.png)
- Check the resulting journal entries:
  ![selection_134](https://cloud.githubusercontent.com/assets/1814941/11657894/f81d7f08-9dbf-11e5-93f7-6b940869fe2d.png)

Expected Behaviour:
Use payment date for cash-based VAT journal entries.

**Comment by treviser** [comment]
While doing further tests, I have found out that the posting date of a write-off (if a invoice is not paid in full) shows the same faulty behaviour.

**Comment by treviser** [comment]
Am I doing something terribly and obviously wrong? Any feedback is most welcome.

**Comment by funcurv** [comment]
I would expect the payment date for cash-based tax journal entries too. Looks as if there is a bug.

**Comment by pedrobaeza** [comment]
Is this still happening in latest code version?

**Comment by pedrobaeza** [comment]
Closing as there hasn't been an answer.

Feel free to open a new issue if this is still happening, but please include all the detailed steps to reproduce the problem, and better if it can be reproducible in a demo environment like runbot (http://runbot.odoo.com).
