### ISSUE TITLE
[9.0] Calendar - wrong time format for specific language

### ISSUE THREAD

**Issue by sergueikp** [odoo/odoo#9977]
Version impacted:
Version 9.0c-20151207 (Community Edition) 
OS : Windows

How to reproduce the bug:
1. Go to Settings > Load translation > load french language
2. Go to User Preferences > Select language : French > Save

Actual behaviour:
The time format in calendar is in American way : am or pm
Supposed behaviour : 
The time format must be in French way: 24 hours

![9 0_calendar_wrong_time_format](https://cloud.githubusercontent.com/assets/9844780/11662016/05059862-9dd5-11e5-993a-e8f96a464381.JPG)

**Comment by morphace** [comment]
+1 same for German

**Comment by jl2035** [comment]
1+ same for all languages I think

**Comment by mgazelle** [comment]
Settings -> Translation -> Select the language to modify

adjust the time format to %H:%M:S

**Comment by karsteneb** [comment]
The issue still exists, at least in Version 9.0c-20160902 (Community Edition). The time format is set to %H:%M:S in all installed languages, and the calendar shows the correct date format, but the wrong am/pm time format.

**Comment by wpichler** [comment]
Take a look at
https://github.com/odoo/odoo/pull/11234/files
This does work for me - so vote for it to get it in main v9.0 branch

**Comment by mart-e** [comment]
Fixed at c1d813ec1caf3ea38a1289a2fbc7c32fed34bc22 in 10.0
