### ISSUE TITLE
Odoo forum Question tools subscribe button is broken

### ISSUE THREAD

**Issue by aek** [odoo/odoo#9980]
After the last days updates to the Odoo forum online version the subscribe button is not working anymore. After debug it this seems to be the lines that cause the problem:
<pre><code>
$('.js_follow_btn').on('click', function (ev) {
    $('.js_follow_email').val($(ev.currentTarget).closest('.js_mg_follow_form').find('.js_follow_email').val());
});
</code></pre>

This is located on /website_mail_channel/static/src/js/website_mail_channel.snippet.js
The error is caused because 
<pre><code>$(ev.currentTarget).closest('.js_mg_follow_form').find('.js_follow_email').val()</code></pre>

returns undefined and don't find the needed email value for the next event handler to properly work at the on_click function of animation.registry.follow class at /website_mail/static/src/js/follow.js

**Comment by mart-e** [comment]
@aek thank you for your investigation, don't hesitate to provide a patch if you can

**Comment by Yenthe666** [comment]
@mart-e to add another issue on top of this one:
1) Create a new topic with a user that has less than 20 karma
2) Add spam in it
3) Login with a user that has enough karma to validate/invalidate new topics
4) Click on the 'X' because it contains spam
5) You have no ability to choose items from the dropdown:
<img src="http://i.imgur.com/1drFC1m.png" alt="Closing topic"/>

**Comment by Yenthe666** [comment]
@mart-e another issue on the forums: when you click on 'Tags' on the front page you'll get an internal server error:
<img src="http://i.imgur.com/HodLfzq.png" alt="Tags internal server error"/>

**Comment by mart-e** [comment]
@Yenthe666 please report  this kind of issues to Odoo online support as it's linked to our database. No need to ping me each time.

**Comment by JKE-be** [comment]
thank you for the feedback. Subscribe bug has been fixed in V9. and the bug when you close a post was a migration bug, it has been fixed in our db and for next migrations.
