### ISSUE TITLE
Chatter on stock picking object

### ISSUE THREAD

**Issue by Sameer1990** [odoo/odoo#9985]
**Show messages on chatter for stock picking**
Impacted versions:
 - 8.0

Steps to reproduce:
 1. runbot.odoo.com 
 2. Warehouse => All Operations => Delivery Orders  .
 3. When change status of picking (create-check availability- force availability-transfer or cancel).

Current behavior:
 - No message in chatter (just on 'create'  will add message on chatter ).

Expected behavior:
 - When change status should create message on chatter below .

**Comment by yostashiro** [comment]
We have this issue as well.  Adding `_track` entries like in below link doesn't trigger any chatter message at all.

https://github.com/rfhk/scli-custom/blob/9da2204bd09078664e2b31bd7a0cf926196fb1de/stock_state_adjust/model/stock.py#L38-L43

**Comment by Yenthe666** [comment]
Hi @Sameer1990 and @yostashiro,

This is now shown in the chatter (atleast I think you're talking about this):
![image](https://cloud.githubusercontent.com/assets/6352350/15471614/29b1eac6-20f7-11e6-88a4-62a3ada73da1.png)

Can one of you two confirm that this is fixed / OK now?

**Comment by yostashiro** [comment]
@Yenthe666 I believe this commit https://github.com/odoo/odoo/commit/d349584f9d281ea955f4a46235747c9b9866daa6 has fixed the issue.

Haven't studied how it's done for SO and PO in v9 (now that workflow has been removed, I guess similar logic should be applied) but the patch here appears rather cumbersome.  Anyway, I think this issue can be closed.

**Comment by Yenthe666** [comment]
@yostashiro,

Thanks for the reply! I'll close this. Should you ever encounter this again or find a problem with this just create a new report or post on this one.

Regards,
Yenthe

**Comment by Sameer1990** [comment]
Yes fixed it, thanks .
