### ISSUE TITLE
9.0 -'SECTION' missing in sales order TEMPLATE lines (#9157)

### ISSUE THREAD

**Issue by stephaniemillet** [odoo/odoo#9989]
see comment on issue #9157

**Comment by stephaniemillet** [comment]
Sections are missing on Sales order template
Section have to be defined in the template (if you use them to create sales order)
Or they are useless
So we need to be able to set section on our sales order template line

**Comment by Yenthe666** [comment]
Hi,

Please don't make two issues for the same problem. This was handled in https://github.com/odoo/odoo/commit/bde7f4dad1a852adb6d6bd4b1bca080b2f2fc23d, sorry for the late response on this one.
