### ISSUE TITLE
[9.0] Unable to select multiple taxes in sales, purchases, invoices, etc...

### ISSUE THREAD

**Issue by fdelayen** [odoo/odoo#9990]
There is a bug that prevent from selecting multiple taxes.
With taxes names of a few characters, its goes crazy, as you can see in the attachment.

![taxes](https://cloud.githubusercontent.com/assets/14359114/11689117/a8fdbd9e-9e90-11e5-856d-bd6c1473a462.png)

(Non enterprise version, classic menu)

**Comment by joolsr** [comment]
Also if the tax tag is long as in the example above, you cannot click it when its over the Total column to the right.

**Comment by Yenthe666** [comment]
Hi @joolsr,

This issue is not longer present in the latest V9:
![image](https://cloud.githubusercontent.com/assets/6352350/15471548/c5790cce-20f6-11e6-937a-e7ec1a42c80e.png)

Regards,
Yenthe

**Comment by joolsr** [comment]
Thanks. I think i remember it was fixed about 5 months back but not closed
here.

Julian
