### ISSUE TITLE
[13.0-16.0]bad/wrong code in stock module

### ISSUE THREAD

**Issue by jlzhou** [odoo/odoo#99981]
Impacted versions:
13.0-15.0-master

Steps to reproduce:
see source code in stock module

Current behavior:
bad model name 'stock.package_level'
wrong groups attribute 'base.main_company' in stock_package_level_views.xml'
wrong field name in is_done readonly attrs 'parent.state' in stock_package_level_views.xml'

Expected behavior:
rename bad model name and fix wrong code

**Comment by jlzhou** [comment]
@sle-odoo @pimodoo

**Comment by pimodoo** [comment]
@amoyaux

**Comment by niyasraphy** [comment]
hi @jlzhou ,
partially fixed in this commit:  https://github.com/odoo/odoo/commit/dd92cf35caeac59d5e30d053b4460c47e7b13e6b
thanks

**Comment by vava-odoo** [comment]
Solved in all stable versions with the commit mentioned by @niyasraphy
