### ISSUE TITLE
helpdesk:Error when deleting team from last stage

### ISSUE THREAD

**Issue by JaypalMaru** [odoo/odoo#99980]
Impacted versions:
15.0 EE

Steps to reproduce:
Go to Helpdesk/Configuration/Stages.
Try to Delete team from stages as shown in video.

Current behavior:

Expected behavior:

Video/Screenshot link (optional):
https://user-images.githubusercontent.com/105263557/189482220-c18a4345-b384-4572-a1d0-76dc9fef9592.mp4

Support ticket number submitted via odoo.com/help (optional):

**Comment by xavierbol** [comment]
Hello @JaypalMaru , 

Thanks for your feedback, the issue has been fixed by odoo/enterprise#31727

Have a nice day! 🙂
